### PR TITLE
td/aws_connect_hours_of_operation

### PR DESCRIPTION
**Pull request by GlennChia**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Description of changes

This PR makes 2 changes

- Renames `hours_of_operation_arn` to just `arn` since the resource itself is already called `aws_connect_hours_of_operation`. Hence users just have to call `aws_connect_hours_of_operation.example.arn` to get the ARN instead of `aws_connect_hours_of_operation.example.hours_of_operation_arn`
- Remove the timeouts which are unnecessary for this resource since timeouts were meant for the `aws_connect_instance` resource that has longer deployment time

### Output from acceptance testing:

Test the resource:

```
$ make testacc TESTS=TestAccConnectHoursOfOperation_serial PKG=connect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run='TestAccConnectHoursOfOperation_serial' -timeout 180m
=== RUN   TestAccConnectHoursOfOperation_serial
=== RUN   TestAccConnectHoursOfOperation_serial/basic
=== RUN   TestAccConnectHoursOfOperation_serial/disappears
--- PASS: TestAccConnectHoursOfOperation_serial (299.90s)
    --- PASS: TestAccConnectHoursOfOperation_serial/basic (190.13s)
    --- PASS: TestAccConnectHoursOfOperation_serial/disappears (109.78s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    309.514s
...
```

Test the data source:

```
$ make testacc TESTS=TestAccConnectHoursOfOperationDataSource PKG=connect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run='TestAccConnectHoursOfOperationDataSource' -timeout 180m
=== RUN   TestAccConnectHoursOfOperationDataSource_hoursOfOperationID
--- PASS: TestAccConnectHoursOfOperationDataSource_hoursOfOperationID (114.53s)
=== RUN   TestAccConnectHoursOfOperationDataSource_name
--- PASS: TestAccConnectHoursOfOperationDataSource_name (117.26s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    242.203s
...
```

### CODE REVIEW

**Review by AdamTylerLynch — APPROVED** [review]
BREAKING CHANGE INCLUDED. @ewbankkit 

LGTM 🚀

**Comment by GlennChia** [comment]
Hi @breathingdust , is it possible to help re-open this PR and change the destination branch to `main`? Seems like the `release/4.x` branch is deleted. Thanks!

**Comment by anGie44** [comment]
Hi @GlennChia , apologies for that! I've restored the release/4.x branch and will update the base branch

**Comment by GlennChia** [comment]
Hi @anGie44 thanks for the assist! Since the `release/4.x` branch is restored, perhaps we can retain that as the destination branch? Since this contains a breaking change I think it was intended for the `release/4.x` branch. Thanks!

**Comment by anGie44** [comment]
Of course, was my mistake! Ahh so the changes that lived in `release/4.x` were merged in on monday, so we're using the `main` branch now to hold all the upcoming 4.0 changes. I restored the branch to help re-open this PR, i thought Github would just change the base branch automatically 😞 , but we don't plan to add any new content there as `main` will become the release branch for 4.0.

**Comment by anGie44** [comment]
@GlennChia since this PR renames the attribute, I believe we'll need to follow documented [Best Practices] (https://www.terraform.io/plugin/sdkv2/best-practices/deprecations#renaming-a-computed-attribute) , so this will need to be a deprecation which can occur during any minor release, and then removal can occur in the v5.0 major release.

**Comment by GlennChia** [comment]
Thanks @anGie44. I've made the changes as per the guidance and re-ran the test case (I realised my test command could have been shorter since the prefix is shared by the resource and data source).

```
make testacc TESTARGS='-run=TestAccConnectHoursOfOperation_serial\|TestAccConnectHoursOfOperationDataSource' PKG=connect ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 1 -run=TestAccConnectHoursOfOperation_serial\|TestAccConnectHoursOfOperationDataSource -timeout 180m
=== RUN   TestAccConnectHoursOfOperationDataSource_hoursOfOperationID
--- PASS: TestAccConnectHoursOfOperationDataSource_hoursOfOperationID (178.91s)
=== RUN   TestAccConnectHoursOfOperationDataSource_name
--- PASS: TestAccConnectHoursOfOperationDataSource_name (124.06s)
=== RUN   TestAccConnectHoursOfOperation_serial
=== RUN   TestAccConnectHoursOfOperation_serial/basic
=== RUN   TestAccConnectHoursOfOperation_serial/disappears
--- PASS: TestAccConnectHoursOfOperation_serial (284.66s)
    --- PASS: TestAccConnectHoursOfOperation_serial/basic (166.21s)
    --- PASS: TestAccConnectHoursOfOperation_serial/disappears (118.44s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    595.314s
```

**Review by gdavison — APPROVED** [review]
Looks good! 🚀 

--- PASS: TestAccConnectHoursOfOperationDataSource_hoursOfOperationID (85.36s)
--- PASS: TestAccConnectHoursOfOperationDataSource_name (84.94s)
--- PASS: TestAccConnectHoursOfOperation_serial (186.11s)
    --- PASS: TestAccConnectHoursOfOperation_serial/basic (101.68s)
    --- PASS: TestAccConnectHoursOfOperation_serial/disappears (84.43s)

**Pull request merged**
