### PR TITLE
Add resources to manage Detective in an Organization

### LINKED ISSUE #23201: AWS Detective Organization Configuration resources
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enhance AWS detective within Terraform to designate the admin account with IAC and to set the flag to auto enroll new organization accounts from the admin account.

### New or Affected Resource(s)

* aws_detective_organization_configuration
* aws_detective_organization_admin_account

### Potential Terraform Configuration

```hcl
resource "aws_detective_organization_admin_account" "example"{
    account_id = "123456789012"
} 
```

```hcl
resource "aws_detective_organization_configuration" "example"{
    graph_arn   = resource.aws_detective_graph.example.graph_arn
    auto-enable = true | false
} 
```

### References

* [aws_administrator account](https://docs.aws.amazon.com/detective/latest/adminguide/accounts-designate-admin.html#accounts-designate-admin-api)
* [aws_detective_organization_configuration](https://docs.aws.amazon.com/detective/latest/adminguide/accounts-orgs-members-autoenable.html#accounts-orgs-members-autoenable-api)

#11672

### PR DESCRIPTION
**Pull request by owenfarrell**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23201.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23459.

Output from acceptance testing:

```
$ make testacc TESTS='TestAccDetective_serial/Organization' PKG=detective
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/detective/... -v -count 1 -parallel 20 -run='TestAccDetective_serial/Organization'  -timeout 180m
=== RUN   TestAccDetective_serial
=== RUN   TestAccDetective_serial/OrganizationAdminAccount
=== RUN   TestAccDetective_serial/OrganizationAdminAccount/basic
=== RUN   TestAccDetective_serial/OrganizationAdminAccount/disappears
=== RUN   TestAccDetective_serial/OrganizationAdminAccount/MultiRegion
=== RUN   TestAccDetective_serial/OrganizationConfiguration
=== RUN   TestAccDetective_serial/OrganizationConfiguration/basic
--- PASS: TestAccDetective_serial (226.23s)
    --- PASS: TestAccDetective_serial/OrganizationAdminAccount (153.58s)
        --- PASS: TestAccDetective_serial/OrganizationAdminAccount/basic (69.92s)
        --- PASS: TestAccDetective_serial/OrganizationAdminAccount/disappears (34.18s)
        --- PASS: TestAccDetective_serial/OrganizationAdminAccount/MultiRegion (49.48s)
    --- PASS: TestAccDetective_serial/OrganizationConfiguration (72.64s)
        --- PASS: TestAccDetective_serial/OrganizationConfiguration/basic (72.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/detective  233.285s
...
```

### CODE REVIEW

**Comment by kyle-c-simmons** [comment]
Hi there, Is there any updates on this PR? Thanks :+1:

**Comment by owenfarrell** [comment]
Rebased over a59ffd87692295317d4d066480100d5eedd3afd9. Made some updates to account for schema API changes for both resources and acceptance tests... but everything still passes okay.

**Comment by Jamie-Leon** [comment]
@breathingdust is there any update on getting this released?

**Comment by gyoza** [comment]
This would be incredibly useful to us as well..

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccDetective_serial/Graph' PKG=detective
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/detective/... -v -count 1 -parallel 20  -run=TestAccDetective_serial/Graph -timeout 360m
=== RUN   TestAccDetective_serial
=== PAUSE TestAccDetective_serial
=== CONT  TestAccDetective_serial
=== RUN   TestAccDetective_serial/Graph
=== RUN   TestAccDetective_serial/Graph/basic
=== RUN   TestAccDetective_serial/Graph/disappears
=== RUN   TestAccDetective_serial/Graph/tags
--- PASS: TestAccDetective_serial (121.20s)
    --- PASS: TestAccDetective_serial/Graph (121.20s)
        --- PASS: TestAccDetective_serial/Graph/basic (31.48s)
        --- PASS: TestAccDetective_serial/Graph/disappears (20.73s)
        --- PASS: TestAccDetective_serial/Graph/tags (68.99s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/detective	127.274s
```

**Pull request merged**
