### PR TITLE
Add AppConfig service

### PR DESCRIPTION
**Pull request by shuheiktgw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/hashicorp/terraform-provider-aws/issues/11973

Output from acceptance testing:

```
None
```

For a first step, I've added the AppConfig service. Thank you for your review!

### CODE REVIEW

**Comment by ewbankkit** [comment]
@shuheiktgw Thanks for the contribution.
Could you please also add the new service to `infrastructure/repository/labels-service.tf`.

**Comment by shuheiktgw** [comment]
Thank you for your review, @ewbankkit! Somehow it seems `appconfig` has been already added!

https://github.com/hashicorp/terraform-provider-aws/blob/626df9f590e8266965fe6caa3b10765a3072cba3/infrastructure/repository/labels-service.tf#L16

**Comment by ewbankkit** [comment]
@shuheiktgw Yes it is, I must have been looking at an older version 😄.

**Review by ewbankkit — APPROVED** [review]
LGTM.

**Comment by ryandeivert** [comment]
hi @ewbankkit it looks like this is approved and pending merge -- the following is dependent on this and awaiting merge of this PR:

https://github.com/hashicorp/terraform-provider-aws/pull/18032

**Review by bflad — APPROVED** [review]

**Pull request merged**
