### PR TITLE
Add kafkaconnect service

### PR DESCRIPTION
**Pull request by rtim75**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates to #20942 

Output from testing:

```
make test
==> Checking that code complies with gofmt requirements...
$ go test ./...  -timeout=5m
?       github.com/hashicorp/terraform-provider-aws     [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/acctest    26.640s
ok      github.com/hashicorp/terraform-provider-aws/internal/conns      (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/create     (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/experimental/nullable      (cached)
?       github.com/hashicorp/terraform-provider-aws/internal/experimental/sync  [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/flex       (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/generate/namevaluesfilters 6.147s
?       github.com/hashicorp/terraform-provider-aws/internal/provider   [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/accessanalyzer     12.116s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/account    2.486s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/acm        23.899s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/acmpca     41.572s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/amp        10.013s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/amplify    4.278s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apigateway 23.996s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2       19.338s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling     8.022s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appconfig  29.141s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appmesh    12.911s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apprunner  15.617s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appstream  18.067s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appsync    16.857s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/athena     18.699s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling        16.688s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/autoscalingplans   11.627s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/backup     12.218s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/batch      14.554s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/budgets    12.413s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/chime      14.701s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloud9     14.321s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudcontrol       16.058s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation     13.625s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront 18.345s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudhsmv2 20.340s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail 19.288s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch 22.409s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatchlogs     15.639s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codeartifact       19.541s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codebuild  19.224s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codecommit 18.631s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codedeploy 19.651s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline       24.002s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codestarconnections        21.076s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codestarnotifications      24.908s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidentity    20.009s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp 21.809s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/configservice      17.731s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    21.910s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cur        19.219s
?       github.com/hashicorp/terraform-provider-aws/internal/service/dataexchange       [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datapipeline       22.151s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datasync   19.478s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dax        23.253s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/detective  21.654s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/devicefarm 25.123s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/directconnect      19.871s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dlm        22.033s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        15.968s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/docdb      16.889s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ds 20.434s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb   23.623s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        47.690s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        19.483s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecrpublic  21.406s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecs        25.277s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/efs        27.242s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/eks        22.300s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        24.339s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticbeanstalk   27.105s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch      25.286s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elastictranscoder  29.441s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elb        27.661s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      30.499s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/emr        20.082s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/events     12.475s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/firehose   13.865s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fms        16.240s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fsx        14.016s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/gamelift   15.837s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glacier    18.520s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator  20.723s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       18.725s
?       github.com/hashicorp/terraform-provider-aws/internal/service/greengrass [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/guardduty  20.267s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        16.326s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/identitystore      13.933s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder       17.567s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/inspector  16.534s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iot        18.765s
?       github.com/hashicorp/terraform-provider-aws/internal/service/iotanalytics       [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/service/iotevents  [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      21.817s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesis    14.416s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalytics   16.750s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalyticsv2 20.951s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesisvideo       18.936s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kms        18.902s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation      10.949s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lambda     15.335s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lexmodels  12.606s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/licensemanager     16.710s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lightsail  17.848s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/macie      19.477s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/macie2     22.217s
?       github.com/hashicorp/terraform-provider-aws/internal/service/mediaconnect       [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediaconvert       22.532s
?       github.com/hashicorp/terraform-provider-aws/internal/service/medialive  [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediapackage       25.208s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediastore 24.045s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/memorydb   25.513s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/meta       24.612s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mq 27.327s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mwaa       23.731s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/neptune    22.859s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall    22.860s
?       github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager     [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opsworks   21.511s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/organizations      20.241s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/outposts   20.972s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint   25.257s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pricing    23.055s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/qldb       26.800s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 25.104s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ram        26.641s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        18.418s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshift   15.857s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups     23.046s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroupstaggingapi   19.031s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53    22.853s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53recoverycontrolconfig       17.686s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53recoveryreadiness   24.897s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver    19.860s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3 19.412s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3control  20.220s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3outposts 22.707s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  22.631s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/schemas    19.621s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager     23.534s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/securityhub        20.725s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo     25.455s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog     19.351s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicediscovery   20.168s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicequotas      22.521s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ses        21.581s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sfn        19.546s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/shield     23.980s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/signer     27.481s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/simpledb   24.834s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sns        29.570s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sqs        22.863s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssm        21.329s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssoadmin   24.400s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway     21.759s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sts        24.620s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/swf        22.523s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/synthetics 24.979s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite    20.801s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/transfer   21.370s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/waf        13.844s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/wafregional        11.225s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/wafv2      13.260s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/worklink   13.714s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/workspaces 13.022s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/xray       14.805s
ok      github.com/hashicorp/terraform-provider-aws/internal/tags       (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/tfresource (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/vault/helper/pgpkeys       (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/vault/sdk/helper/jsonutil  (cached)
ok      github.com/hashicorp/terraform-provider-aws/internal/verify     (cached)
?       github.com/hashicorp/terraform-provider-aws/version     [no test files]
```

### CODE REVIEW

**Comment by rtim75** [comment]
So according to [guidelines of adding new service](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-service) the necessary minimum should(the first resource of the service) should be submitted in this PR:

> Initial Resource: Some services can be big and it can be difficult for both reviewer & author to go through long feedback cycles on a big PR with many resources. Often feedback items in one resource will also need to be applied in other resources. We prefer you to submit the necessary minimum in a single PR, ideally just the first resource of the service.

---

BUT, the main reason for everyone to add a kafkaconnect is obviously the `connector` which requires 2 other resources to be added:
- plugin 
- worker configuration

So I'm wondering what the necessary minimum is in this case: only the connector resource that would expect plugins and workers configurations provided as strings? Or the whole pack of connector, plugin and worker configs?

**Comment by ewbankkit** [comment]
@rtim75 Thanks for the contribution :tada: :clap:.
Looking at the [Amazon MSK Connect API Reference](https://docs.aws.amazon.com/MCK/latest/mck/Welcome.html), you are correct - The `aws_mskconnect_custom_plugin` and `aws_mskconnect_worker_configuration` resource should be added first as the `aws_mskconnect_connector` resource refers to these by ARN.
Once this pre-requisites PR is ready and merged, `aws_mskconnect_custom_plugin` and `aws_mskconnect_worker_configuration` should be added as separate parallel PRs and then an `aws_mskconnect_connector` PR, dependent on the previous 2 PRs.

**Comment by rtim75** [comment]
Thanks @ewbankkit for clarifications. Then I guess I will mark this PR as ready and will continue working on `custom_plugin` and `worker_configuration` ones.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make test
==> Checking that code complies with gofmt requirements...
go test ./...  -timeout=5m
?   	github.com/hashicorp/terraform-provider-aws	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	7.673s
ok  	github.com/hashicorp/terraform-provider-aws/internal/conns	1.270s
ok  	github.com/hashicorp/terraform-provider-aws/internal/create	1.966s
ok  	github.com/hashicorp/terraform-provider-aws/internal/experimental/nullable	0.885s
?   	github.com/hashicorp/terraform-provider-aws/internal/experimental/sync	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/flex	2.048s
ok  	github.com/hashicorp/terraform-provider-aws/internal/generate/namevaluesfilters	8.002s
?   	github.com/hashicorp/terraform-provider-aws/internal/provider	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/accessanalyzer	6.794s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/account	7.944s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acm	13.808s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca	20.109s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amp	15.788s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amplify	12.831s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	7.225s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2	9.157s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	8.732s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appconfig	10.862s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appmesh	9.295s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apprunner	11.223s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appstream	13.743s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appsync	17.105s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/athena	18.608s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	16.451s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscalingplans	18.116s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/backup	20.965s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/batch	21.782s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/budgets	22.813s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/chime	24.340s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud9	23.668s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudcontrol	10.408s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	9.295s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	9.293s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudhsmv2	9.085s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail	6.716s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch	6.509s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatchlogs	21.405s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codeartifact	23.540s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codebuild	21.418s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codecommit	22.912s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codedeploy	24.064s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline	26.846s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codestarconnections	26.889s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codestarnotifications	14.664s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidentity	7.104s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	8.605s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/configservice	6.487s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	8.351s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cur	9.875s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/dataexchange	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datapipeline	10.206s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datasync	13.871s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dax	15.213s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/detective	5.499s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/devicefarm	8.656s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	8.308s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dlm	10.072s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	8.568s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/docdb	13.321s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ds	10.981s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	8.547s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	20.830s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	10.262s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecrpublic	5.200s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	9.434s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	4.446s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	6.746s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	7.198s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticbeanstalk	4.469s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch	13.791s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elastictranscoder	8.313s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elb	11.963s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	10.343s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emr	6.687s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/events	10.588s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	7.146s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fms	7.765s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	15.524s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/gamelift	11.576s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glacier	12.045s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator	8.117s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glue	4.979s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/greengrass	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	10.598s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	8.693s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/identitystore	6.219s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder	8.536s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/inspector	5.404s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	10.917s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/iotanalytics	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/service/iotevents	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	13.376s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesis	12.052s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalytics	12.593s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalyticsv2	16.332s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisvideo	5.706s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kms	10.153s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	7.125s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	8.473s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lexmodels	5.125s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/licensemanager	7.150s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lightsail	9.510s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/macie	11.496s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/macie2	13.895s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/mediaconnect	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediaconvert	6.793s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediapackage	5.138s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediastore	8.279s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/memorydb	8.743s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	10.323s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mq	13.652s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mwaa	15.701s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	7.396s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall	4.989s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opsworks	7.020s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/organizations	14.993s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/outposts	7.188s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	10.603s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pricing	7.607s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/qldb	6.210s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	6.494s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ram	9.106s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	7.425s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshift	10.141s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups	12.178s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroupstaggingapi	5.008s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53	7.883s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53recoverycontrolconfig	5.854s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53recoveryreadiness	7.273s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver	5.142s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	9.088s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3control	6.497s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3outposts	9.366s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	7.216s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/schemas	6.618s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager	5.991s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/securityhub	6.649s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo	7.202s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	5.716s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicediscovery	8.240s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicequotas	5.497s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ses	9.689s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sfn	9.721s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/shield	9.181s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/signer	15.350s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/simpledb	20.232s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sns	21.468s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sqs	9.484s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssm	16.156s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssoadmin	20.867s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway	8.579s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sts	12.031s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/swf	5.998s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/synthetics	7.560s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite	13.118s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	19.767s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/waf	14.955s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafregional	6.641s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	7.423s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/worklink	5.312s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/workspaces	9.029s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/xray	12.687s
ok  	github.com/hashicorp/terraform-provider-aws/internal/tags	2.350s
ok  	github.com/hashicorp/terraform-provider-aws/internal/tfresource	28.211s
ok  	github.com/hashicorp/terraform-provider-aws/internal/vault/helper/pgpkeys	1.759s
ok  	github.com/hashicorp/terraform-provider-aws/internal/vault/sdk/helper/jsonutil	0.941s
ok  	github.com/hashicorp/terraform-provider-aws/internal/verify	1.134s
?   	github.com/hashicorp/terraform-provider-aws/version	[no test files]
```

**Comment by ewbankkit** [comment]
@rtim75 Thanks for the contribution :tada: :clap:.

**Pull request merged**
