### PR TITLE
F add support for model_data_source attribute in aws sagemaker model

### PR DESCRIPTION
**Pull request by rflament**
add support for model_data_source in sagemaker model.

It is necessary for deploying uncompressed models in sagemaker: https://docs.aws.amazon.com/sagemaker/latest/dg/large-model-inference-uncompressed.html

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by ewbankkit** [comment]
Should the new attribute also be added to the `primary_container` block?

**Comment by rflament** [comment]
@ewbankkit @DrFaust92  I fixed and ran the new acceptance test successfully.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@rflament Thanks for the contribution :tada: :clap:.

**Pull request merged**
