### PR TITLE
Added a boolean eventbridge attribute to s3/bucket_notification

### LINKED ISSUE #22013: Add S3 notifications for EventBridge
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

S3 notifications [now support EventBridge](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/).   
Add [S3 notification configuration](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification) for [EventBridge](https://aws.amazon.com/eventbridge/).

### New or Affected Resource(s)

* [ `aws_s3_bucket_notification`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_bucket_notification)

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_notification" "bucket_notification" {
  bucket = aws_s3_bucket.bucket.id

  bus {
    bus_arn     = aws_cloudwatch_event_bus.bus.arn
    events        = ["s3:ObjectCreated:*"]
  }
}
```

### References

* [https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/](https://aws.amazon.com/blogs/aws/new-use-amazon-s3-event-notifications-with-amazon-eventbridge/)

### PR DESCRIPTION
**Pull request by lparkes**
Added a boolean eventbridge attribute to s3/bucket_notification in order to support the EventBridge notifications for S3 buckets.

This is a draft PR. IMHO the code looks good and the acceptance test looks good, but I haven't gone through all the contribution document in detail yet. I do have one question right now though. Where/how do I write the documentation for the new attribute I have added?

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22013.

Output from acceptance testing:

```
lloyd@riftsweeper:software/terraform-provider-aws$ AWS_PROFILE=cicd make testacc TESTS=TestAccS3BucketNotification_eventbridge PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketNotification_eventbridge' -timeout 180m
=== RUN   TestAccS3BucketNotification_eventbridge
=== PAUSE TestAccS3BucketNotification_eventbridge
=== CONT  TestAccS3BucketNotification_eventbridge
--- PASS: TestAccS3BucketNotification_eventbridge (36.66s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3 36.702s
...
```

### CODE REVIEW

**Comment by konstankinollc** [comment]
Hi there,

Seems like absolutely required feature. Any prospect on when this can be completed/merged?

Thank you.

**Comment by kamilturek** [comment]
Hey @lparkes, you would need to update the documentation in [this file](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/s3_bucket_notification.html.markdown). It also might be worthy to create a change log like described [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process). Please let me know if you need any help.

**Comment by lparkes** [comment]
I have added documentaion for the new argument as well as creating a changelog entry. I didn't write an example for the new argument because it's a boolean. 
I've also run through Resource Contribution Guidelines checklist.

**Comment by davidalecrim** [comment]
Love that you took the time to create this PR @lparkes 🙏 
I happen to need this and I added a thumbsup already. Just have one small detail/suggestion, if you replace `relates` with `resolves` in the PR description, it will actually add the PR to the original issue, because at the time, it's not linked.

Just `resolves #22013`, ty!

**Comment by lparkes** [comment]
> Love that you took the time to create this PR @lparkes pray I happen to need this and I added a thumbsup already. Just have one small detail/suggestion, if you replace `relates` with `resolves` in the PR description, it will actually add the PR to the original issue, because at the time, it's not linked.
> 
> Just `resolves #22013`, ty!

Hi David. If you look very carefully, you will see that I didn't write the `relates` text. ewbankkit kindly added that, presumably because he had noticed that the issue had been recently created. I checked for an issue of course, but only before I started writing the code which was a couple of days before I created the PR.

Hmm. The HTML comment in the PR template says I should use `Closes`. Hold on one moment while I read the issue and double check I've got it all sorted.

**Review by YakDriver — APPROVED** [review]
Your changes look great! 🎉 Also, found a few things that were not quite right that needed fixing at the same time.

Output from acceptance tests (`us-west-2`):
```console
% make testacc TESTS=TestAccS3BucketNotification_ PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketNotification_' -timeout 180m
--- PASS: TestAccS3BucketNotification_eventbridge (26.96s)
--- PASS: TestAccS3BucketNotification_topic (29.84s)
--- PASS: TestAccS3BucketNotification_Topic_multiple (29.99s)
--- PASS: TestAccS3BucketNotification_queue (31.55s)
--- PASS: TestAccS3BucketNotification_lambdaFunction (37.87s)
--- PASS: TestAccS3BucketNotification_LambdaFunctionLambdaFunctionARN_alias (45.48s)
--- PASS: TestAccS3BucketNotification_update (50.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	51.345s
```

Output from acceptance tests (GovCloud):
```console
% make testacc TESTS=TestAccS3BucketNotification_ PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketNotification_' -timeout 180m
--- SKIP: TestAccS3BucketNotification_eventbridge (15.48s)
--- PASS: TestAccS3BucketNotification_topic (32.93s)
--- PASS: TestAccS3BucketNotification_Topic_multiple (33.08s)
--- PASS: TestAccS3BucketNotification_LambdaFunctionLambdaFunctionARN_alias (40.24s)
--- PASS: TestAccS3BucketNotification_queue (41.50s)
--- PASS: TestAccS3BucketNotification_lambdaFunction (45.22s)
--- PASS: TestAccS3BucketNotification_update (55.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	56.296s
```

**Comment by lparkes** [comment]
Sorry for the argument/attribute typo in the changelog. I did check the terminology and I knew "argument" was correct and I still managed to type the wrong word in. 
Thanks for merging the PR.

**Pull request merged**
