### PR TITLE
Tech Debt: Migrating Terraform Quicksight Service to AWS SDK V2

### PR DESCRIPTION
**Pull request by Snackeroo**
### Description
 Bringing Quicksight to use the next version of AWS SDK
### Relations
Relates [#32976](https://github.com/hashicorp/terraform-provider-aws/issues/32976)
Closes [#36198](https://github.com/hashicorp/terraform-provider-aws/issues/36198)

### Output from Acceptance Testing
I need help from maintainers to run Acceptance Testings

### CODE REVIEW

**Comment by Snackeroo** [comment]
I saw a maintainer has picked up this PR, should I can start updating the necessary changes and resolving the current conflicts?

**Comment by Snackeroo** [comment]
I saw all of my commits reverted without comments and all the work was redone. Should I close this pull request and let the maintainer open a separate pull request? If all my commits are reverted anyway then I should not be involved in this work.

**Comment by ewbankkit** [comment]
@Snackeroo Thanks for all your work on this 👏.
I did the revert and then re-apply as I find it the easiest way of dealing with PRs that we have let sit for a while and have a large number of non-trivial merge conflicts.
After completing testing we aim to merge this PR for this week's release.

**Comment by Snackeroo** [comment]
> @Snackeroo Thanks for all your work on this 👏. I did the revert and then re-apply as I find it the easiest way of dealing with PRs that we have let sit for a while and have a large number of non-trivial merge conflicts. After completing testing we aim to merge this PR for this week's release.

No problem. Thank you for putting a lot of work to reapply and update this PR. It got stale after a while. I really appreciate the thorough communication @ewbankkit

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccQuickSight_serial/AccountSubscription' PKG=quicksight
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 20  -run=TestAccQuickSight_serial/AccountSubscription -timeout 360m
=== RUN   TestAccQuickSight_serial
=== PAUSE TestAccQuickSight_serial
=== CONT  TestAccQuickSight_serial
=== RUN   TestAccQuickSight_serial/AccountSubscription
=== RUN   TestAccQuickSight_serial/AccountSubscription/basic
=== RUN   TestAccQuickSight_serial/AccountSubscription/disappears
--- PASS: TestAccQuickSight_serial (302.95s)
    --- PASS: TestAccQuickSight_serial/AccountSubscription (302.95s)
        --- PASS: TestAccQuickSight_serial/AccountSubscription/basic (153.43s)
        --- PASS: TestAccQuickSight_serial/AccountSubscription/disappears (149.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	308.272s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.764s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightAnalysis_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightAnalysis_ -timeout 360m
=== RUN   TestAccQuickSightAnalysis_basic
=== PAUSE TestAccQuickSightAnalysis_basic
=== RUN   TestAccQuickSightAnalysis_disappears
=== PAUSE TestAccQuickSightAnalysis_disappears
=== RUN   TestAccQuickSightAnalysis_sourceEntity
=== PAUSE TestAccQuickSightAnalysis_sourceEntity
=== RUN   TestAccQuickSightAnalysis_update
=== PAUSE TestAccQuickSightAnalysis_update
=== RUN   TestAccQuickSightAnalysis_parametersConfig
=== PAUSE TestAccQuickSightAnalysis_parametersConfig
=== RUN   TestAccQuickSightAnalysis_forceDelete
=== PAUSE TestAccQuickSightAnalysis_forceDelete
=== RUN   TestAccQuickSightAnalysis_Definition_calculatedFields
=== PAUSE TestAccQuickSightAnalysis_Definition_calculatedFields
=== CONT  TestAccQuickSightAnalysis_basic
=== CONT  TestAccQuickSightAnalysis_parametersConfig
--- PASS: TestAccQuickSightAnalysis_parametersConfig (39.08s)
=== CONT  TestAccQuickSightAnalysis_Definition_calculatedFields
--- PASS: TestAccQuickSightAnalysis_basic (39.21s)
=== CONT  TestAccQuickSightAnalysis_forceDelete
--- PASS: TestAccQuickSightAnalysis_forceDelete (34.95s)
=== CONT  TestAccQuickSightAnalysis_sourceEntity
--- PASS: TestAccQuickSightAnalysis_Definition_calculatedFields (39.10s)
=== CONT  TestAccQuickSightAnalysis_update
--- PASS: TestAccQuickSightAnalysis_sourceEntity (38.79s)
=== CONT  TestAccQuickSightAnalysis_disappears
--- PASS: TestAccQuickSightAnalysis_disappears (34.82s)
--- PASS: TestAccQuickSightAnalysis_update (71.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	154.838s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.365s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightDashboard_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightDashboard_ -timeout 360m
=== RUN   TestAccQuickSightDashboard_basic
=== PAUSE TestAccQuickSightDashboard_basic
=== RUN   TestAccQuickSightDashboard_disappears
=== PAUSE TestAccQuickSightDashboard_disappears
=== RUN   TestAccQuickSightDashboard_sourceEntity
=== PAUSE TestAccQuickSightDashboard_sourceEntity
=== RUN   TestAccQuickSightDashboard_updateVersionNumber
=== PAUSE TestAccQuickSightDashboard_updateVersionNumber
=== RUN   TestAccQuickSightDashboard_dashboardSpecificConfig
=== PAUSE TestAccQuickSightDashboard_dashboardSpecificConfig
=== CONT  TestAccQuickSightDashboard_basic
=== CONT  TestAccQuickSightDashboard_updateVersionNumber
--- PASS: TestAccQuickSightDashboard_basic (38.87s)
=== CONT  TestAccQuickSightDashboard_dashboardSpecificConfig
--- PASS: TestAccQuickSightDashboard_updateVersionNumber (73.71s)
=== CONT  TestAccQuickSightDashboard_sourceEntity
--- PASS: TestAccQuickSightDashboard_dashboardSpecificConfig (36.94s)
=== CONT  TestAccQuickSightDashboard_disappears
--- PASS: TestAccQuickSightDashboard_disappears (34.25s)
--- PASS: TestAccQuickSightDashboard_sourceEntity (40.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	118.776s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.370s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightDataSet' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightDataSet -timeout 360m
=== RUN   TestAccQuickSightDataSetDataSource_basic
=== PAUSE TestAccQuickSightDataSetDataSource_basic
=== RUN   TestAccQuickSightDataSet_basic
=== PAUSE TestAccQuickSightDataSet_basic
=== RUN   TestAccQuickSightDataSet_disappears
=== PAUSE TestAccQuickSightDataSet_disappears
=== RUN   TestAccQuickSightDataSet_columnGroups
=== PAUSE TestAccQuickSightDataSet_columnGroups
=== RUN   TestAccQuickSightDataSet_columnLevelPermissionRules
=== PAUSE TestAccQuickSightDataSet_columnLevelPermissionRules
=== RUN   TestAccQuickSightDataSet_dataSetUsageConfiguration
=== PAUSE TestAccQuickSightDataSet_dataSetUsageConfiguration
=== RUN   TestAccQuickSightDataSet_fieldFolders
=== PAUSE TestAccQuickSightDataSet_fieldFolders
=== RUN   TestAccQuickSightDataSet_logicalTableMap
=== PAUSE TestAccQuickSightDataSet_logicalTableMap
=== RUN   TestAccQuickSightDataSet_permissions
=== PAUSE TestAccQuickSightDataSet_permissions
=== RUN   TestAccQuickSightDataSet_permissionsMultiple
=== PAUSE TestAccQuickSightDataSet_permissionsMultiple
=== RUN   TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== PAUSE TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== RUN   TestAccQuickSightDataSet_refreshProperties
    data_set_test.go:414: Environment variable QUICKSIGHT_ATHENA_TESTING_ENABLED is not set
--- SKIP: TestAccQuickSightDataSet_refreshProperties (0.00s)
=== RUN   TestAccQuickSightDataSet_tags
=== PAUSE TestAccQuickSightDataSet_tags
=== RUN   TestAccQuickSightDataSet_noPhysicalTableMap
=== PAUSE TestAccQuickSightDataSet_noPhysicalTableMap
=== CONT  TestAccQuickSightDataSetDataSource_basic
=== CONT  TestAccQuickSightDataSet_logicalTableMap
--- PASS: TestAccQuickSightDataSetDataSource_basic (30.29s)
=== CONT  TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
--- PASS: TestAccQuickSightDataSet_logicalTableMap (54.22s)
=== CONT  TestAccQuickSightDataSet_noPhysicalTableMap
--- PASS: TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration (29.43s)
=== CONT  TestAccQuickSightDataSet_tags
--- PASS: TestAccQuickSightDataSet_noPhysicalTableMap (36.03s)
=== CONT  TestAccQuickSightDataSet_columnLevelPermissionRules
--- PASS: TestAccQuickSightDataSet_columnLevelPermissionRules (29.27s)
=== CONT  TestAccQuickSightDataSet_fieldFolders
--- PASS: TestAccQuickSightDataSet_tags (66.49s)
=== CONT  TestAccQuickSightDataSet_dataSetUsageConfiguration
--- PASS: TestAccQuickSightDataSet_fieldFolders (29.24s)
=== CONT  TestAccQuickSightDataSet_permissionsMultiple
--- PASS: TestAccQuickSightDataSet_dataSetUsageConfiguration (29.74s)
=== CONT  TestAccQuickSightDataSet_permissions
--- PASS: TestAccQuickSightDataSet_permissionsMultiple (30.71s)
=== CONT  TestAccQuickSightDataSet_disappears
--- PASS: TestAccQuickSightDataSet_disappears (25.69s)
=== CONT  TestAccQuickSightDataSet_columnGroups
--- PASS: TestAccQuickSightDataSet_permissions (72.34s)
=== CONT  TestAccQuickSightDataSet_basic
--- PASS: TestAccQuickSightDataSet_columnGroups (29.89s)
--- PASS: TestAccQuickSightDataSet_basic (30.31s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	263.485s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.353s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightDataSource_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightDataSource_ -timeout 360m
=== RUN   TestAccQuickSightDataSource_basic
=== PAUSE TestAccQuickSightDataSource_basic
=== RUN   TestAccQuickSightDataSource_disappears
=== PAUSE TestAccQuickSightDataSource_disappears
=== RUN   TestAccQuickSightDataSource_tags
=== PAUSE TestAccQuickSightDataSource_tags
=== RUN   TestAccQuickSightDataSource_permissions
=== PAUSE TestAccQuickSightDataSource_permissions
=== RUN   TestAccQuickSightDataSource_name
=== PAUSE TestAccQuickSightDataSource_name
=== CONT  TestAccQuickSightDataSource_basic
=== CONT  TestAccQuickSightDataSource_permissions
--- PASS: TestAccQuickSightDataSource_basic (23.62s)
=== CONT  TestAccQuickSightDataSource_tags
--- PASS: TestAccQuickSightDataSource_permissions (59.64s)
=== CONT  TestAccQuickSightDataSource_disappears
--- PASS: TestAccQuickSightDataSource_tags (52.91s)
=== CONT  TestAccQuickSightDataSource_name
--- PASS: TestAccQuickSightDataSource_disappears (20.78s)
--- PASS: TestAccQuickSightDataSource_name (39.47s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	120.890s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.353s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightFolder' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightFolder -timeout 360m
=== RUN   TestAccQuickSightFolderMembership_basic
=== PAUSE TestAccQuickSightFolderMembership_basic
=== RUN   TestAccQuickSightFolderMembership_disappears
=== PAUSE TestAccQuickSightFolderMembership_disappears
=== RUN   TestAccQuickSightFolder_basic
=== PAUSE TestAccQuickSightFolder_basic
=== RUN   TestAccQuickSightFolder_disappears
=== PAUSE TestAccQuickSightFolder_disappears
=== RUN   TestAccQuickSightFolder_permissions
=== PAUSE TestAccQuickSightFolder_permissions
=== RUN   TestAccQuickSightFolder_tags
=== PAUSE TestAccQuickSightFolder_tags
=== RUN   TestAccQuickSightFolder_parentFolder
=== PAUSE TestAccQuickSightFolder_parentFolder
=== RUN   TestAccQuickSightFolder_parentFolderNested
=== PAUSE TestAccQuickSightFolder_parentFolderNested
=== CONT  TestAccQuickSightFolderMembership_basic
=== CONT  TestAccQuickSightFolder_permissions
--- PASS: TestAccQuickSightFolderMembership_basic (29.40s)
=== CONT  TestAccQuickSightFolder_parentFolder
--- PASS: TestAccQuickSightFolder_permissions (42.68s)
=== CONT  TestAccQuickSightFolder_parentFolderNested
--- PASS: TestAccQuickSightFolder_parentFolder (27.42s)
=== CONT  TestAccQuickSightFolder_tags
--- PASS: TestAccQuickSightFolder_parentFolderNested (28.67s)
=== CONT  TestAccQuickSightFolder_basic
--- PASS: TestAccQuickSightFolder_basic (13.00s)
=== CONT  TestAccQuickSightFolder_disappears
--- PASS: TestAccQuickSightFolder_tags (29.69s)
=== CONT  TestAccQuickSightFolderMembership_disappears
--- PASS: TestAccQuickSightFolder_disappears (10.07s)
--- PASS: TestAccQuickSightFolderMembership_disappears (28.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	120.120s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.353s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightGroup' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightGroup -timeout 360m
=== RUN   TestAccQuickSightGroupDataSource_basic
=== PAUSE TestAccQuickSightGroupDataSource_basic
=== RUN   TestAccQuickSightGroupMembership_basic
=== PAUSE TestAccQuickSightGroupMembership_basic
=== RUN   TestAccQuickSightGroupMembership_withNamespace
=== PAUSE TestAccQuickSightGroupMembership_withNamespace
=== RUN   TestAccQuickSightGroupMembership_disappears
=== PAUSE TestAccQuickSightGroupMembership_disappears
=== RUN   TestAccQuickSightGroup_basic
=== PAUSE TestAccQuickSightGroup_basic
=== RUN   TestAccQuickSightGroup_withDescription
=== PAUSE TestAccQuickSightGroup_withDescription
=== RUN   TestAccQuickSightGroup_disappears
=== PAUSE TestAccQuickSightGroup_disappears
=== CONT  TestAccQuickSightGroupDataSource_basic
=== CONT  TestAccQuickSightGroup_basic
--- PASS: TestAccQuickSightGroupDataSource_basic (9.74s)
=== CONT  TestAccQuickSightGroup_disappears
--- PASS: TestAccQuickSightGroup_basic (19.28s)
=== CONT  TestAccQuickSightGroup_withDescription
--- PASS: TestAccQuickSightGroup_disappears (9.87s)
=== CONT  TestAccQuickSightGroupMembership_withNamespace
--- PASS: TestAccQuickSightGroup_withDescription (18.88s)
=== CONT  TestAccQuickSightGroupMembership_disappears
--- PASS: TestAccQuickSightGroupMembership_disappears (15.66s)
=== CONT  TestAccQuickSightGroupMembership_basic
--- PASS: TestAccQuickSightGroupMembership_basic (17.64s)
--- PASS: TestAccQuickSightGroupMembership_withNamespace (130.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	154.698s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.370s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightIAMPolicyAssignment_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightIAMPolicyAssignment_ -timeout 360m
=== RUN   TestAccQuickSightIAMPolicyAssignment_basic
=== PAUSE TestAccQuickSightIAMPolicyAssignment_basic
=== RUN   TestAccQuickSightIAMPolicyAssignment_disappears
=== PAUSE TestAccQuickSightIAMPolicyAssignment_disappears
=== RUN   TestAccQuickSightIAMPolicyAssignment_assignmentStatus
=== PAUSE TestAccQuickSightIAMPolicyAssignment_assignmentStatus
=== RUN   TestAccQuickSightIAMPolicyAssignment_identities
=== PAUSE TestAccQuickSightIAMPolicyAssignment_identities
=== CONT  TestAccQuickSightIAMPolicyAssignment_basic
=== CONT  TestAccQuickSightIAMPolicyAssignment_assignmentStatus
--- PASS: TestAccQuickSightIAMPolicyAssignment_basic (14.61s)
=== CONT  TestAccQuickSightIAMPolicyAssignment_disappears
--- PASS: TestAccQuickSightIAMPolicyAssignment_disappears (13.04s)
=== CONT  TestAccQuickSightIAMPolicyAssignment_identities
--- PASS: TestAccQuickSightIAMPolicyAssignment_assignmentStatus (29.53s)
--- PASS: TestAccQuickSightIAMPolicyAssignment_identities (19.37s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	52.155s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.362s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightIngestion_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightIngestion_ -timeout 360m
=== RUN   TestAccQuickSightIngestion_basic
=== PAUSE TestAccQuickSightIngestion_basic
=== RUN   TestAccQuickSightIngestion_disappears_dataSet
=== PAUSE TestAccQuickSightIngestion_disappears_dataSet
=== CONT  TestAccQuickSightIngestion_basic
=== CONT  TestAccQuickSightIngestion_disappears_dataSet
--- PASS: TestAccQuickSightIngestion_disappears_dataSet (28.11s)
--- PASS: TestAccQuickSightIngestion_basic (31.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	36.272s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.352s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightNamespace_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightNamespace_ -timeout 360m
=== RUN   TestAccQuickSightNamespace_basic
=== PAUSE TestAccQuickSightNamespace_basic
=== RUN   TestAccQuickSightNamespace_disappears
=== PAUSE TestAccQuickSightNamespace_disappears
=== RUN   TestAccQuickSightNamespace_tags
=== PAUSE TestAccQuickSightNamespace_tags
=== CONT  TestAccQuickSightNamespace_basic
=== CONT  TestAccQuickSightNamespace_tags
--- PASS: TestAccQuickSightNamespace_basic (123.64s)
=== CONT  TestAccQuickSightNamespace_disappears
--- PASS: TestAccQuickSightNamespace_tags (136.40s)
--- PASS: TestAccQuickSightNamespace_disappears (120.96s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	249.529s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.369s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightRefreshSchedule_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightRefreshSchedule_ -timeout 360m
=== RUN   TestAccQuickSightRefreshSchedule_basic
=== PAUSE TestAccQuickSightRefreshSchedule_basic
=== RUN   TestAccQuickSightRefreshSchedule_disappears
=== PAUSE TestAccQuickSightRefreshSchedule_disappears
=== RUN   TestAccQuickSightRefreshSchedule_weeklyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_weeklyRefresh
=== RUN   TestAccQuickSightRefreshSchedule_invalidWeeklyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_invalidWeeklyRefresh
=== RUN   TestAccQuickSightRefreshSchedule_monthlyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_monthlyRefresh
=== RUN   TestAccQuickSightRefreshSchedule_invalidMonthlyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_invalidMonthlyRefresh
=== RUN   TestAccQuickSightRefreshSchedule_invalidRefreshInterval
=== PAUSE TestAccQuickSightRefreshSchedule_invalidRefreshInterval
=== CONT  TestAccQuickSightRefreshSchedule_basic
=== CONT  TestAccQuickSightRefreshSchedule_monthlyRefresh
--- PASS: TestAccQuickSightRefreshSchedule_basic (32.09s)
=== CONT  TestAccQuickSightRefreshSchedule_invalidRefreshInterval
=== CONT  TestAccQuickSightRefreshSchedule_weeklyRefresh
--- PASS: TestAccQuickSightRefreshSchedule_monthlyRefresh (32.11s)
--- PASS: TestAccQuickSightRefreshSchedule_invalidRefreshInterval (2.01s)
=== CONT  TestAccQuickSightRefreshSchedule_invalidWeeklyRefresh
--- PASS: TestAccQuickSightRefreshSchedule_invalidWeeklyRefresh (1.06s)
=== CONT  TestAccQuickSightRefreshSchedule_disappears
--- PASS: TestAccQuickSightRefreshSchedule_weeklyRefresh (30.15s)
=== CONT  TestAccQuickSightRefreshSchedule_invalidMonthlyRefresh
--- PASS: TestAccQuickSightRefreshSchedule_disappears (28.15s)
--- PASS: TestAccQuickSightRefreshSchedule_invalidMonthlyRefresh (1.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	68.490s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.373s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightTemplate' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightTemplate -timeout 360m
=== RUN   TestAccQuickSightTemplateAlias_basic
=== PAUSE TestAccQuickSightTemplateAlias_basic
=== RUN   TestAccQuickSightTemplateAlias_disappears
=== PAUSE TestAccQuickSightTemplateAlias_disappears
=== RUN   TestAccQuickSightTemplate_basic
=== PAUSE TestAccQuickSightTemplate_basic
=== RUN   TestAccQuickSightTemplate_disappears
=== PAUSE TestAccQuickSightTemplate_disappears
=== RUN   TestAccQuickSightTemplate_barChart
=== PAUSE TestAccQuickSightTemplate_barChart
=== RUN   TestAccQuickSightTemplate_table
=== PAUSE TestAccQuickSightTemplate_table
=== RUN   TestAccQuickSightTemplate_sourceEntity
=== PAUSE TestAccQuickSightTemplate_sourceEntity
=== RUN   TestAccQuickSightTemplate_tags
=== PAUSE TestAccQuickSightTemplate_tags
=== RUN   TestAccQuickSightTemplate_update
=== PAUSE TestAccQuickSightTemplate_update
=== CONT  TestAccQuickSightTemplateAlias_basic
=== CONT  TestAccQuickSightTemplate_table
--- PASS: TestAccQuickSightTemplateAlias_basic (31.25s)
=== CONT  TestAccQuickSightTemplate_disappears
--- PASS: TestAccQuickSightTemplate_table (50.98s)
=== CONT  TestAccQuickSightTemplate_barChart
--- PASS: TestAccQuickSightTemplate_disappears (28.29s)
=== CONT  TestAccQuickSightTemplate_basic
--- PASS: TestAccQuickSightTemplate_barChart (30.84s)
=== CONT  TestAccQuickSightTemplate_tags
--- PASS: TestAccQuickSightTemplate_basic (31.10s)
=== CONT  TestAccQuickSightTemplate_update
--- PASS: TestAccQuickSightTemplate_update (53.63s)
=== CONT  TestAccQuickSightTemplateAlias_disappears
--- PASS: TestAccQuickSightTemplate_tags (69.46s)
=== CONT  TestAccQuickSightTemplate_sourceEntity
--- PASS: TestAccQuickSightTemplateAlias_disappears (29.64s)
--- PASS: TestAccQuickSightTemplate_sourceEntity (32.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	189.239s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.373s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightTheme' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightTheme -timeout 360m
=== RUN   TestAccQuickSightThemeDataSource_basic
=== PAUSE TestAccQuickSightThemeDataSource_basic
=== RUN   TestAccQuickSightThemeDataSource_fullConfig
=== PAUSE TestAccQuickSightThemeDataSource_fullConfig
=== RUN   TestAccQuickSightTheme_basic
=== PAUSE TestAccQuickSightTheme_basic
=== RUN   TestAccQuickSightTheme_disappears
=== PAUSE TestAccQuickSightTheme_disappears
=== RUN   TestAccQuickSightTheme_fullConfig
=== PAUSE TestAccQuickSightTheme_fullConfig
=== RUN   TestAccQuickSightTheme_update
=== PAUSE TestAccQuickSightTheme_update
=== CONT  TestAccQuickSightThemeDataSource_basic
=== CONT  TestAccQuickSightTheme_disappears
--- PASS: TestAccQuickSightTheme_disappears (12.09s)
=== CONT  TestAccQuickSightTheme_basic
--- PASS: TestAccQuickSightThemeDataSource_basic (13.10s)
=== CONT  TestAccQuickSightThemeDataSource_fullConfig
--- PASS: TestAccQuickSightThemeDataSource_fullConfig (12.35s)
=== CONT  TestAccQuickSightTheme_update
--- PASS: TestAccQuickSightTheme_basic (13.38s)
=== CONT  TestAccQuickSightTheme_fullConfig
--- PASS: TestAccQuickSightTheme_fullConfig (13.36s)
--- PASS: TestAccQuickSightTheme_update (19.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	49.981s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.398s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightUser' PKG=quicksight ACCTEST_PARALLELISM=2   
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightUser -timeout 360m
=== RUN   TestAccQuickSightUserDataSource_basic
=== PAUSE TestAccQuickSightUserDataSource_basic
=== RUN   TestAccQuickSightUser_basic
=== PAUSE TestAccQuickSightUser_basic
=== RUN   TestAccQuickSightUser_withInvalidFormattedEmailStillWorks
=== PAUSE TestAccQuickSightUser_withInvalidFormattedEmailStillWorks
=== RUN   TestAccQuickSightUser_withNamespace
    user_test.go:92: Environment variable QUICKSIGHT_NAMESPACE is not set
--- SKIP: TestAccQuickSightUser_withNamespace (0.00s)
=== RUN   TestAccQuickSightUser_disappears
=== PAUSE TestAccQuickSightUser_disappears
=== CONT  TestAccQuickSightUserDataSource_basic
=== CONT  TestAccQuickSightUser_withInvalidFormattedEmailStillWorks
--- PASS: TestAccQuickSightUserDataSource_basic (14.53s)
=== CONT  TestAccQuickSightUser_disappears
--- PASS: TestAccQuickSightUser_withInvalidFormattedEmailStillWorks (26.96s)
=== CONT  TestAccQuickSightUser_basic
--- PASS: TestAccQuickSightUser_disappears (14.70s)
--- PASS: TestAccQuickSightUser_basic (23.93s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	55.806s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.355s [no tests to run]
```
```console
% make testacc TESTARGS='-run=TestAccQuickSightVPCConnection_' PKG=quicksight ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/quicksight/... -v -count 1 -parallel 2  -run=TestAccQuickSightVPCConnection_ -timeout 360m
=== RUN   TestAccQuickSightVPCConnection_basic
=== PAUSE TestAccQuickSightVPCConnection_basic
=== RUN   TestAccQuickSightVPCConnection_disappears
=== PAUSE TestAccQuickSightVPCConnection_disappears
=== RUN   TestAccQuickSightVPCConnection_tags
=== PAUSE TestAccQuickSightVPCConnection_tags
=== CONT  TestAccQuickSightVPCConnection_basic
=== CONT  TestAccQuickSightVPCConnection_tags
--- PASS: TestAccQuickSightVPCConnection_basic (147.76s)
=== CONT  TestAccQuickSightVPCConnection_disappears
--- PASS: TestAccQuickSightVPCConnection_tags (168.07s)
--- PASS: TestAccQuickSightVPCConnection_disappears (146.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	299.783s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.381s [no tests to run]
```

**Pull request merged**
