### PR TITLE
New DataSource: aws_appmesh_virtual_gateway

### LINKED ISSUE #26907: [New Data Source]: aws_appmesh_virtual_gateway
### Description

Could we please have a new data source to allow us to lookup **aws_appmesh_virtual_gateway** resources without having to use remote state

### Requested Resource(s) and/or Data Source(s)

aws_appmesh_virtual_gateway

### Potential Terraform Configuration

```terraform
data "aws_appmesh_virtual_gateway" "sample_filtered_on_name" {
    name = "simpleapp"
}

data "aws_appmesh_virtual_gateway" "sample_filtered_on_tag_name" {
   tags = {
    myTag = "simpleapp_virtual_gateway"
   }
}
```

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by AhmedGrati**
### Description
New DataSource for `aws_appmesh_virtual_gateway`

### Relations

Closes #26907.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/17590.

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccAppMeshVirtualGatewayDataSource  PKG=appmesh
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appmesh/... -v -count 1 -parallel 20 -run='TestAccAppMeshVirtualGatewayDataSource'  -timeout 180m
=== RUN   TestAccAppMeshVirtualGatewayDataSource_basic
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_basic
=== RUN   TestAccAppMeshVirtualGatewayDataSource_backendDefaults
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_backendDefaults
=== RUN   TestAccAppMeshVirtualGatewayDataSource_backendDefaultsUpdated
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_backendDefaultsUpdated
=== RUN   TestAccAppMeshVirtualGatewayDataSource_backendDefaultsCertificate
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_backendDefaultsCertificate
=== RUN   TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPool
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPool
=== RUN   TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPoolUpdated
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPoolUpdated
=== RUN   TestAccAppMeshVirtualGatewayDataSource_listenerHealthChecks
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_listenerHealthChecks
=== RUN   TestAccAppMeshVirtualGatewayDataSource_listenerTLSACM
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_listenerTLSACM
=== RUN   TestAccAppMeshVirtualGatewayDataSource_listenerTLSFile
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_listenerTLSFile
=== RUN   TestAccAppMeshVirtualGatewayDataSource_listenerValidation
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_listenerValidation
=== RUN   TestAccAppMeshVirtualGatewayDataSource_logging
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_logging
=== RUN   TestAccAppMeshVirtualGatewayDataSource_tags
=== PAUSE TestAccAppMeshVirtualGatewayDataSource_tags
=== CONT  TestAccAppMeshVirtualGatewayDataSource_basic
=== CONT  TestAccAppMeshVirtualGatewayDataSource_listenerValidation
=== CONT  TestAccAppMeshVirtualGatewayDataSource_tags
=== CONT  TestAccAppMeshVirtualGatewayDataSource_logging
=== CONT  TestAccAppMeshVirtualGatewayDataSource_listenerTLSFile
=== CONT  TestAccAppMeshVirtualGatewayDataSource_backendDefaultsCertificate
=== CONT  TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPoolUpdated
=== CONT  TestAccAppMeshVirtualGatewayDataSource_listenerHealthChecks
=== CONT  TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPool
=== CONT  TestAccAppMeshVirtualGatewayDataSource_listenerTLSACM
=== CONT  TestAccAppMeshVirtualGatewayDataSource_backendDefaultsUpdated
=== CONT  TestAccAppMeshVirtualGatewayDataSource_backendDefaults
--- PASS: TestAccAppMeshVirtualGatewayDataSource_listenerHealthChecks (26.14s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_basic (28.43s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_backendDefaultsCertificate (28.48s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_listenerValidation (28.53s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPoolUpdated (28.64s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_backendDefaultsUpdated (28.68s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_backendDefaults (28.70s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_listenerTLSFile (28.70s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_tags (28.72s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_logging (28.73s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_listenerConnectionPool (28.76s)
--- PASS: TestAccAppMeshVirtualGatewayDataSource_listenerTLSACM (61.52s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appmesh    61.677s
...
```

### CODE REVIEW

**Review by sandeep-s-solanki — APPROVED** [review]
LGTM

**Review by sandeep-s-solanki — COMMENTED** [review]
@AhmedGrati Great work! Checks on the PR are failing. Please could you take a look: 
https://github.com/hashicorp/terraform-provider-aws/actions/runs/3170021436/jobs/5162326582

We are eagerly awaiting this change, please let us know if we can help.

Thanks

**Comment by AhmedGrati** [comment]
@sandeep-s-solanki Thank you 😊 ! Sure I will fix it ASAP 🙏.

**Comment by AhmedGrati** [comment]
@sandeep-s-solanki It looks like this error comes from the fact that we are using version `v1` of this action: `actions/first-interaction`. For more context, check this GitHub thread: [https://github.com/actions/first-interaction/issues/101](https://github.com/actions/first-interaction/issues/101).
Therefore, migrating to `v1.1.1` solves the problem. I can create an issue and a PR to solve this problem if you want.

**Comment by sandeep-s-solanki** [comment]
@AhmedGrati that would be great to solve the issue. We will wait for this PR to merged. Do you know how long the merging process takes for a PR once all check have passed? Thank again for your help

**Comment by AhmedGrati** [comment]
@sandeep-s-solanki I have solved the issue in a separate PR. Once merged, we could re-run this pipeline. It would be really great if you review it 🙏😊.

**Comment by AhmedGrati** [comment]
Hey @sandeep-s-solanki, I think it's ready to merge now. Thank you for your efforts 🙏😊.

**Review by sandeep-s-solanki — APPROVED** [review]

**Comment by sandeep-s-solanki** [comment]
@AhmedGrati looks great. Thank for your help! 👍

**Comment by sandeep-s-solanki** [comment]
@AhmedGrati who can merge this, as all checks have now paased?

**Comment by AhmedGrati** [comment]
Hey @breathingdust, Is there anything else we need to do to get this PR going?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAppMesh_serial/^VirtualGateway$$' PKG=appmesh
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appmesh/... -v -count 1 -parallel 20  -run=TestAccAppMesh_serial/^VirtualGateway$ -timeout 180m
=== RUN   TestAccAppMesh_serial
=== PAUSE TestAccAppMesh_serial
=== CONT  TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/VirtualGateway
=== RUN   TestAccAppMesh_serial/VirtualGateway/listenerTls
=== RUN   TestAccAppMesh_serial/VirtualGateway/logging
=== RUN   TestAccAppMesh_serial/VirtualGateway/tags
=== RUN   TestAccAppMesh_serial/VirtualGateway/disappears
=== RUN   TestAccAppMesh_serial/VirtualGateway/backendDefaultsCertificate
=== RUN   TestAccAppMesh_serial/VirtualGateway/listenerConnectionPool
=== RUN   TestAccAppMesh_serial/VirtualGateway/listenerHealthChecks
=== RUN   TestAccAppMesh_serial/VirtualGateway/basic
=== RUN   TestAccAppMesh_serial/VirtualGateway/backendDefaults
=== RUN   TestAccAppMesh_serial/VirtualGateway/listenerValidation
=== RUN   TestAccAppMesh_serial/VirtualGateway/multiListenerValidation
--- PASS: TestAccAppMesh_serial (338.93s)
    --- PASS: TestAccAppMesh_serial/VirtualGateway (338.93s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/listenerTls (90.28s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/logging (36.88s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/tags (36.88s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/disappears (12.97s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/backendDefaultsCertificate (15.76s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/listenerConnectionPool (25.99s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/listenerHealthChecks (26.14s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/basic (15.54s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/backendDefaults (26.19s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/listenerValidation (26.16s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/multiListenerValidation (26.14s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appmesh	346.915s
% make testacc TESTARGS='-run=TestAccAppMesh_serial/^VirtualGateway$$/dataSourceBasic' PKG=appmesh
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appmesh/... -v -count 1 -parallel 20  -run=TestAccAppMesh_serial/^VirtualGateway$/dataSourceBasic -timeout 180m
=== RUN   TestAccAppMesh_serial
=== PAUSE TestAccAppMesh_serial
=== CONT  TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/VirtualGateway
=== RUN   TestAccAppMesh_serial/VirtualGateway/dataSourceBasic
--- PASS: TestAccAppMesh_serial (14.70s)
    --- PASS: TestAccAppMesh_serial/VirtualGateway (14.70s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/dataSourceBasic (14.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appmesh	19.835s
```

**Comment by ewbankkit** [comment]
@AhmedGrati Thanks for the contribution :tada: :clap:.

**Pull request merged**
