### PR TITLE
New resource: `aws_vpclattice_service_network_service_association`

### LINKED ISSUE #30410: [New Resource]: aws_vpclattice_service_network_service_association
### Description

AWS VPC Lattice recently reached GA. A Service Network Service Association allows a VPC Lattice Service Network to be associated with a VPC Lattice Service.

### Requested Resource(s) and/or Data Source(s)

* aws_vpclattice_service_network_service_association

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_service_network_service_association" "example" {
  service_identifier         = aws_vpclattice_service.example.id
  service_network_identifier = aws_vpclattice_service_network.example.id
}
```

### References

* API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateServiceNetworkServiceAssociation.html
* API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
* User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by meetreks**
### Description

This change is to add a new resource for VPC Lattice Service Network Association.  You can see this issue for more details - https://github.com/hashicorp/terraform-provider-aws/issues/30410

### Relations

Closes #30410.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/30380.

### References

The API reference can be found here -- https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateServiceNetworkServiceAssociation.html

### Output from Acceptance Testing

```
:~/terraform-provider-aws (f-aws_vpclattice_service) $ make testacc PKG=vpclattice TESTS=TestAccVPCLatticeServiceNetworkAsc_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 20 -run='TestAccVPCLatticeServiceNetworkAsc_'  -timeout 180m
=== RUN   TestAccVPCLatticeServiceNetworkAsc_basic
=== PAUSE TestAccVPCLatticeServiceNetworkAsc_basic
=== RUN   TestAccVPCLatticeServiceNetworkAsc_disappears
=== PAUSE TestAccVPCLatticeServiceNetworkAsc_disappears
=== RUN   TestAccVPCLatticeServiceNetworkAsc_tags
=== PAUSE TestAccVPCLatticeServiceNetworkAsc_tags
=== CONT  TestAccVPCLatticeServiceNetworkAsc_basic
=== CONT  TestAccVPCLatticeServiceNetworkAsc_tags
=== CONT  TestAccVPCLatticeServiceNetworkAsc_disappears
--- PASS: TestAccVPCLatticeServiceNetworkAsc_basic (24.11s)
--- PASS: TestAccVPCLatticeServiceNetworkAsc_disappears (28.82s)
--- PASS: TestAccVPCLatticeServiceNetworkAsc_tags (70.42s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice 70.497s

...
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCLatticeServiceNetworkServiceAssociation_' PKG=vpclattice ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 2  -run=TestAccVPCLatticeServiceNetworkServiceAssociation_ -timeout 180m
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_tags
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_tags
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_tags
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_basic (39.19s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_disappears (33.08s)
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_tags (84.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice	97.572s
``

**Comment by ewbankkit** [comment]
@meetreks Thanks for the contribution :tada: :clap:.
In general, everything was great.
I renamed the resource to `aws_vpclattice_service_network_service_association` to match the underlying AWS APIs.
The documentation needs completion before I can merge.

**Comment by meetreks** [comment]
> @meetreks Thanks for the contribution 🎉 👏. In general, everything was great. I renamed the resource to `aws_vpclattice_service_network_service_association` to match the underlying AWS APIs. The documentation needs completion before I can merge.

Thanks @ewbankkit as always. You mean the docs html completed right?

**Comment by ewbankkit** [comment]
@meetreks Correct.

**Comment by meetreks** [comment]
@ewbankkit fixed the webdocs, kindly review and let me know.

**Pull request merged**
