### PR TITLE
[#19212] Fix secretsmanager_secret_version update

### LINKED ISSUE #19212: aws_secretsmanager_secret_version fails to move the AWSCURRENT label
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.10.0
```
### Affected Resource(s)

* aws_secretsmanager_secret_version

### Terraform Configuration Files

Any use of the `aws_secretsmanager_secret_version` resource with `version_stages` set to `[ "AWSCURRENT" ]`.

### Expected Behavior
If `aws_secretsmanager_secret_version` is told to set the `AWSCURRENT` label but the label is currently on a different version (e.g., one that's created by manually updating the secret in Secrets Manager in AWS console), then terraform should move the label back to the version tracked by terraform.

### Actual Behavior
With a plan like this:
```
  ~ resource "aws_secretsmanager_secret_version" "app-config-vars-from-tf" {
        id             = "staging3/workers/configs|DAC17BED-4C85-4187-A6D0-D46CE9D5780A"
      ~ version_stages = [
          + "AWSCURRENT",
        ]
        # (4 unchanged attributes hidden)
    }
```

We got an error like this:
```
Error: error updating Secrets Manager Secret "staging3/workers/configs" Version Stage "AWSCURRENT": InvalidParameterException: The parameter RemoveFromVersionId can't be empty. Staging label AWSCURRENT is currently attached to version 22bcae4b-f6b7-45e4-bf54-48495c69a33b, so you must explicitly reference that version in RemoveFromVersionId.
```

### Steps to Reproduce

1. Set  `version_stages` to `[ "AWSCURRENT" ]` for a `aws_secretsmanager_secret_version` resource
2. `terraform apply`
3. Manually update the secret outside of terraform so that the `AWSCURRENT` label is moved to a different version than the one tracked by terraform.
4. `terraform apply`

### References
- https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_UpdateSecretVersionStage.html#API_UpdateSecretVersionStage_RequestSyntax

### PR DESCRIPTION
**Pull request by syndbg**
Fixes the AWS SecretsManager API call failing when there's a drift
between the Terraform state and SecretsManager "state".

The drift is caused by someone/something updating outside of Terraform the given resource.
E.g AWS SecretsManager CLI or AWS SecretsManager Web UI/Console

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19212.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsSecretsManagerSecretVersion_VersionStages_external_update'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsSecretsManagerSecretVersion_VersionStages_external_update -timeout 180m
=== RUN   TestAccAwsSecretsManagerSecretVersion_VersionStages_external_update
=== PAUSE TestAccAwsSecretsManagerSecretVersion_VersionStages_external_update
=== CONT  TestAccAwsSecretsManagerSecretVersion_VersionStages_external_update
--- PASS: TestAccAwsSecretsManagerSecretVersion_VersionStages_external_update (61.19s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       61.246s
...
```

### CODE REVIEW

**Review by plamen-kutinchev — APPROVED** [review]

**Review by mtsvyatkovski — APPROVED** [review]

**Comment by syndbg** [comment]
Any chance you can take a look at this? @ewbankkit @bill-rich 👀

**Comment by syndbg** [comment]
Is there anything missing/done wrong in the PR?

We (https://github.com/sumup) kinda need this fix.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by X-Guardian** [comment]
@syndbg, are you able to resolve the conflicts on this PR, as this issue still exists.

**Comment by ewbankkit** [comment]
@syndbg Thanks for the contribution :tada: :clap:.

**Pull request merged**
