### PR TITLE
F aws transfer server structured logging destinations

### LINKED ISSUE #32653: [Enhancement]: Add StructuredLogDestinations Support to Transfer Server
### Description

I am looking to add support for structured logging destinations to the aws transfer server resource. Adding this property will allow users to enable structured logs from terraform for the transfer server and reap the various benefits such as the ones listed [here](https://docs.aws.amazon.com/transfer/latest/userguide/structured-logging.html).

### Affected Resource(s) and/or Data Source(s)

aws_transfer_server

### Potential Terraform Configuration

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

resource "aws_cloudwatch_log_group" "transfer" {
  name_prefix = "transfer_test_"
}

data "aws_iam_policy_document" "transfer_assume_role" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["transfer.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "iam_for_transfer" {
  name_prefix         = "iam_for_transfer_"
  assume_role_policy  = data.aws_iam_policy_document.transfer_assume_role.json
  managed_policy_arns = ["arn:aws:iam::aws:policy/service-role/AWSTransferLoggingAccess"]
}

resource "aws_transfer_server" "transfer" {
  endpoint_type = "PUBLIC"
  logging_role  = aws_iam_role.iam_for_transfer.arn
  protocols     = ["SFTP"]
  structured_log_destinations = [
    "${aws_cloudwatch_log_group.transfer.arn}:*"
  ]
}
```

### References

The StructuredLoggingDestinations property on the CreateServerInput and the UpdateServerInput on the transfer module is what I am looking to add. Here is a link to the CreateServerInput type for the transfer.CreateServer call:

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/transfer#CreateServerInput

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by CalvinE**
### Description

This PR adds support for the AWS Transfer Server Structured Logging Destinations property.

The AWS transfer module talks about this property [here](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/transfer#CreateServerInput)

### Relations

Closes #32653 

### References

Here is some sample terraform that uses the new property and shows that the changes work, assuming that you are overriding the aws provider with the version built with this PRs code.

```terraform
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
    }
  }
}

resource "aws_cloudwatch_log_group" "test" {
  name_prefix = "transfer_test_"
}

data "aws_iam_policy_document" "test" {
  statement {
    effect = "Allow"

    principals {
      type        = "Service"
      identifiers = ["transfer.amazonaws.com"]
    }

    actions = ["sts:AssumeRole"]
  }
}

resource "aws_iam_role" "test" {
  name_prefix         = "iam_for_transfer_"
  assume_role_policy  = data.aws_iam_policy_document.test.json
  managed_policy_arns = ["arn:aws:iam::aws:policy/service-role/AWSTransferLoggingAccess"]
}

resource "aws_transfer_server" "test" {
  endpoint_type = "PUBLIC"
  logging_role  = aws_iam_role.test.arn
  protocols     = ["SFTP"]
  structured_log_destinations = [
    "${aws_cloudwatch_log_group.test.arn}:*"
  ]
}

```

### Output from Acceptance Testing

The acceptance test is working. Was not sure how to get computed value for testing the value in the structured log destinations, so write a function to test using terraform state. Please let me know if there was a better way to do what I wanted to do.

```console
% make testacc TESTS=TestAccTransfer_serial/Server/StructuredLogDestinations PKG=transfer
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20 -run='TestAccTransfer_serial/Server/StructuredLogDestinations'  -timeout 180m
=== RUN   TestAccTransfer_serial
=== PAUSE TestAccTransfer_serial
=== CONT  TestAccTransfer_serial
=== RUN   TestAccTransfer_serial/Server
=== RUN   TestAccTransfer_serial/Server/StructuredLogDestinations
--- PASS: TestAccTransfer_serial (246.13s)
    --- PASS: TestAccTransfer_serial/Server (246.13s)
        --- PASS: TestAccTransfer_serial/Server/StructuredLogDestinations (246.13s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/transfer   246.333s
...
```

### CODE REVIEW

**Comment by CalvinE** [comment]
Sorry I see I have some lint issues. I will get those resolved and push those changes.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccTransfer_serial/Server/^basic$$' PKG=transfer
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20  -run=TestAccTransfer_serial/Server/^basic$ -timeout 180m
=== RUN   TestAccTransfer_serial
=== PAUSE TestAccTransfer_serial
=== CONT  TestAccTransfer_serial
=== RUN   TestAccTransfer_serial/Server
=== RUN   TestAccTransfer_serial/Server/basic
--- PASS: TestAccTransfer_serial (208.81s)
    --- PASS: TestAccTransfer_serial/Server (208.81s)
        --- PASS: TestAccTransfer_serial/Server/basic (208.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	214.559s
```
```console
% make testacc TESTARGS='-run=TestAccTransfer_serial/Server/^DataSourceBasic$$' PKG=transfer
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20  -run=TestAccTransfer_serial/Server/^DataSourceBasic$ -timeout 180m
=== RUN   TestAccTransfer_serial
=== PAUSE TestAccTransfer_serial
=== CONT  TestAccTransfer_serial
=== RUN   TestAccTransfer_serial/Server
=== RUN   TestAccTransfer_serial/Server/DataSourceBasic
--- PASS: TestAccTransfer_serial (186.06s)
    --- PASS: TestAccTransfer_serial/Server (186.06s)
        --- PASS: TestAccTransfer_serial/Server/DataSourceBasic (186.06s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	191.781s
```
```console
% make testacc TESTARGS='-run=TestAccTransfer_serial/Server/^StructuredLogDestinations$$' PKG=transfer
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20  -run=TestAccTransfer_serial/Server/^StructuredLogDestinations$ -timeout 180m
=== RUN   TestAccTransfer_serial
=== PAUSE TestAccTransfer_serial
=== CONT  TestAccTransfer_serial
=== RUN   TestAccTransfer_serial/Server
=== RUN   TestAccTransfer_serial/Server/StructuredLogDestinations
--- PASS: TestAccTransfer_serial (210.04s)
    --- PASS: TestAccTransfer_serial/Server (210.04s)
        --- PASS: TestAccTransfer_serial/Server/StructuredLogDestinations (210.04s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	215.460s
```

**Comment by ewbankkit** [comment]
@CalvinE Thanks for the contribution :tada: :clap:.

**Comment by CalvinE** [comment]
Happy to help @ewbankkit! I use terraform a lot!

**Pull request merged**
