### PR TITLE
provider: Update to Go v1.17

### LINKED ISSUE #22530: provider: updating to Go 1.17
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

* Update provider to be built using Go 1.17, which introduces changes to `go.mod` format as explained in https://go.dev/doc/go1.17#go-command
* `.go-version` can be aligned with `terraform` project that uses `1.17.2`

### Reference:
* https://go.dev/doc/go1.17

### PR DESCRIPTION
**Pull request by gdavison**
Updates Go version to Go v1.17

Closes #22530

### CODE REVIEW

**Comment by ewbankkit** [comment]
Will need to update `docs/contributing/development-environment.md`.

**Comment by ewbankkit** [comment]
For

```
Run go install golang.org/x/tools/cmd/goimports
  go install golang.org/x/tools/cmd/goimports
  shell: /usr/bin/bash -e {0}
  env:
    AWS_DEFAULT_REGION: us-west-2
    TERRAFORM_VERSION: 1.0.6
    GO_VERSION: 1.17.6
    GOROOT: /opt/hostedtoolcache/go/1.17.6/x64
    GOCACHE: /home/runner/.cache/go-build
go: downloading golang.org/x/tools v0.0.0-20200713011307-fd294ab11aed
go: downloading golang.org/x/mod v0.3.0
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: updates to go.mod needed; to update it:
	go mod tidy
Error: Process completed with exit code 1.
```

See https://go.dev/doc/go-get-install-deprecation.
I think `go install golang.org/x/tools/cmd/goimports@latest` will work.

**Comment by gdavison** [comment]
`Terraform Provider Checks / go test (pull_request)` is failing because of #22880

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Pull request merged**
