### PR TITLE
tests/d/servicecat_launch_paths: Fix for assumed role

### LINKED ISSUE #19998: servicecatalog: Test for launch paths data source fails if using assumed role
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.0.1
AWS v3.48.0

### Affected Resource(s)

* aws_servicecatalog_launch_paths

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```terraform
data "aws_caller_identity" "current" {}

resource "aws_servicecatalog_principal_portfolio_association" "test" {
  portfolio_id  = aws_servicecatalog_portfolio.test.id
  principal_arn = data. aws_caller_identity.current.arn
}

data "aws_servicecatalog_launch_paths" "test" {
  product_id = aws_servicecatalog_product_portfolio_association.test.product_id

  depends_on = [aws_servicecatalog_principal_portfolio_association.test]
}
```

### Debug Output

```
=== CONT  TestAccAWSServiceCatalogLaunchPathsDataSource_basic
    data_source_aws_servicecatalog_launch_paths_test.go:18: Step 1/1 error: Error running apply: exit status 1
        
        Error: error associating Service Catalog Principal with Portfolio: InvalidParametersException: Invalid parameter principalArn, assumed-role is not a recognized IAM identity type
        
          with aws_servicecatalog_principal_portfolio_association.test,
          on terraform_plugin_test.tf line 80, in resource "aws_servicecatalog_principal_portfolio_association" "test":
          80: resource "aws_servicecatalog_principal_portfolio_association" "test" {
        
--- FAIL: TestAccAWSServiceCatalogLaunchPathsDataSource_basic (65.72s)
```

### Expected Behavior

Should run test.

### Actual Behavior

Test errors.

### Steps to Reproduce

1. `TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run='TestAccAWSServiceCatalogLaunchPathsDataSource_basic' -timeout 180m`

### References

* #19957

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19998

Output from acceptance testing (`us-west-2`):

Using an assumed role:

```
--- PASS: TestAccAWSServiceCatalogLaunchPathsDataSource_basic (74.30s)
```

Output from acceptance testing (GovCloud):

Not using an assumed role:

```
--- PASS: TestAccAWSServiceCatalogLaunchPathsDataSource_basic (75.94s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
#### Before

```
=== RUN   TestAccAWSServiceCatalogLaunchPathsDataSource_basic
=== PAUSE TestAccAWSServiceCatalogLaunchPathsDataSource_basic
=== CONT  TestAccAWSServiceCatalogLaunchPathsDataSource_basic
    data_source_aws_servicecatalog_launch_paths_test.go:18: Step 1/1 error: Error running apply: exit status 1
        2021/06/29 16:42:49 [DEBUG] Using modified User-Agent: Terraform/0.12.31 HashiCorp-terraform-exec/0.14.0
        
        Error: error associating Service Catalog Principal with Portfolio: InvalidParametersException: Invalid parameter principalArn, assumed-role is not a recognized IAM identity type
        
          on terraform_plugin_test.tf line 80, in resource "aws_servicecatalog_principal_portfolio_association" "test":
          80: resource "aws_servicecatalog_principal_portfolio_association" "test" {
        
        
--- FAIL: TestAccAWSServiceCatalogLaunchPathsDataSource_basic (68.09s)
```

#### After

```
=== RUN   TestAccAWSServiceCatalogLaunchPathsDataSource_basic
=== PAUSE TestAccAWSServiceCatalogLaunchPathsDataSource_basic
=== CONT  TestAccAWSServiceCatalogLaunchPathsDataSource_basic
    data_source_aws_servicecatalog_launch_paths_test.go:18: Step 1/1 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout
        
        
        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
         <= read (data resources)
        
        Terraform will perform the following actions:
        
          # data.aws_servicecatalog_launch_paths.test will be read during apply
          # (config refers to values not yet known)
         <= data "aws_servicecatalog_launch_paths" "test"  {
              + id         = (known after apply)
              + product_id = "prod-i6xyd5nahepsy"
              + summaries  = (known after apply)
            }
        
        Plan: 0 to add, 0 to change, 0 to destroy.
--- FAIL: TestAccAWSServiceCatalogLaunchPathsDataSource_basic (75.49s)
```

**Comment by YakDriver** [comment]
This PR includes plugin SDK 2.7.0. This does not seem to play nicely with TF 0.14.

**Comment by ewbankkit** [comment]
Yes, I was actually running the acceptance test with Terraform 0.12.31.
Re-running with Terraform 1.0.0 passed:

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSServiceCatalogLaunchPathsDataSource_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSServiceCatalogLaunchPathsDataSource_basic -timeout 180m
=== RUN   TestAccAWSServiceCatalogLaunchPathsDataSource_basic
=== PAUSE TestAccAWSServiceCatalogLaunchPathsDataSource_basic
=== CONT  TestAccAWSServiceCatalogLaunchPathsDataSource_basic
--- PASS: TestAccAWSServiceCatalogLaunchPathsDataSource_basic (90.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	94.894s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
I suggest changing

```hcl
data "aws_servicecatalog_launch_paths" "test" {
  product_id = aws_servicecatalog_product_portfolio_association.test.product_id

  depends_on = [aws_servicecatalog_principal_portfolio_association.test]
}
```

to

```hcl
data "aws_servicecatalog_launch_paths" "test" {
  product_id = aws_servicecatalog_product_portfolio_association.test.product_id
}
```

as the `depends_on` is unnecessary (there's already an explicit dependency between the data source and resource) and this causes the Terraform 0.12.31 acceptance test issue.

**Comment by YakDriver** [comment]
I juggled the dependencies around to avoid `depends_on`.

**Pull request merged**
