### PR TITLE
Bug26868: fix RAM CSR retrieval

### PR DESCRIPTION
**Pull request by maxim-anetac**
#### Description

Given that an alternate account shared an ACM PCA with me,
When I tried to retrieve the ACM PCA resource,
I would encounter an AccessDeniedException as the default permission does not allow retrieval of the PCA's CSR.

#### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/26868.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/28017.

### CODE REVIEW

**Comment by maxim-anetac** [comment]
nm, I see it was actually fix in the main, we used 5.19

**Review by greg-anetac — APPROVED** [review]

**Comment by greg-anetac** [comment]
@justinretzolk could you review this PR please?

**Comment by justinretzolk** [comment]
Hey @greg-anetac 👋 Thanks for checking in here! I can't speak to when this will be prioritized just yet. We base our prioritization on the count of :+1: reactions and a few other considerations (more information: [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/)).

**Review by youmark — APPROVED** [review]

**Comment by greg-anetac** [comment]
> Hey @greg-anetac 👋 Thanks for checking in here! I can't speak to when this will be prioritized just yet. We base our prioritization on the count of 👍 reactions and a few other considerations (more information: [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/)).

@justinretzolk what's the threshold of 👍 reactions that is needed to make this PR considered for prioritization?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccACMPCACertificateAuthorityDataSource_' PKG=acmpca ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/acmpca/... -v -count 1 -parallel 2  -run=TestAccACMPCACertificateAuthorityDataSource_ -timeout 360m
2024/12/12 14:15:32 Initializing Terraform AWS Provider...
=== RUN   TestAccACMPCACertificateAuthorityDataSource_tags
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_tags
=== RUN   TestAccACMPCACertificateAuthorityDataSource_tags_NullMap
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_tags_NullMap
=== RUN   TestAccACMPCACertificateAuthorityDataSource_tags_EmptyMap
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_tags_EmptyMap
=== RUN   TestAccACMPCACertificateAuthorityDataSource_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_tags_DefaultTags_nonOverlapping
=== RUN   TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_DefaultTag
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_DefaultTag
=== RUN   TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_ResourceTag
=== RUN   TestAccACMPCACertificateAuthorityDataSource_basic
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_basic
=== RUN   TestAccACMPCACertificateAuthorityDataSource_s3ObjectACL
=== PAUSE TestAccACMPCACertificateAuthorityDataSource_s3ObjectACL
=== CONT  TestAccACMPCACertificateAuthorityDataSource_tags
=== CONT  TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccACMPCACertificateAuthorityDataSource_tags (14.13s)
=== CONT  TestAccACMPCACertificateAuthorityDataSource_tags_EmptyMap
--- PASS: TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_DefaultTag (14.52s)
=== CONT  TestAccACMPCACertificateAuthorityDataSource_tags_DefaultTags_nonOverlapping
--- PASS: TestAccACMPCACertificateAuthorityDataSource_tags_DefaultTags_nonOverlapping (12.63s)
=== CONT  TestAccACMPCACertificateAuthorityDataSource_basic
--- PASS: TestAccACMPCACertificateAuthorityDataSource_tags_EmptyMap (13.04s)
=== CONT  TestAccACMPCACertificateAuthorityDataSource_s3ObjectACL
--- PASS: TestAccACMPCACertificateAuthorityDataSource_s3ObjectACL (13.29s)
=== CONT  TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccACMPCACertificateAuthorityDataSource_basic (13.80s)
=== CONT  TestAccACMPCACertificateAuthorityDataSource_tags_NullMap
--- PASS: TestAccACMPCACertificateAuthorityDataSource_tags_NullMap (12.04s)
--- PASS: TestAccACMPCACertificateAuthorityDataSource_tags_IgnoreTags_Overlap_ResourceTag (13.42s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca	59.083s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@maxim-anetac Thanks for the contribution :tada: :clap:.

**Pull request merged**
