### PR TITLE
New Resources & Data Sources: ElastiCache Redis - User

### PR DESCRIPTION
**Pull request by drarnold**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates to https://github.com/hashicorp/terraform-provider-aws/issues/16327
Blocks https://github.com/hashicorp/terraform-provider-aws/pull/16504

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_elasticache_user: add elasticache_user resource [GH-16629]
```

Output from acceptance testing:
```
$ make testacc TESTARGS='-run=TestAccAWSElasticacheUser_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheUser_ -timeout 120m
=== RUN   TestAccAWSElasticacheUser_basic
=== PAUSE TestAccAWSElasticacheUser_basic
=== RUN   TestAccAWSElasticacheUser_updateAccessString
=== PAUSE TestAccAWSElasticacheUser_updateAccessString
=== RUN   TestAccAWSElasticacheUser_addPasswords
=== PAUSE TestAccAWSElasticacheUser_addPasswords
=== RUN   TestAccAWSElasticacheUser_removePasswords
=== PAUSE TestAccAWSElasticacheUser_removePasswords
=== CONT  TestAccAWSElasticacheUser_basic
=== CONT  TestAccAWSElasticacheUser_removePasswords
=== CONT  TestAccAWSElasticacheUser_addPasswords
=== CONT  TestAccAWSElasticacheUser_updateAccessString
--- PASS: TestAccAWSElasticacheUser_basic (35.69s)
--- PASS: TestAccAWSElasticacheUser_addPasswords (99.15s)
--- PASS: TestAccAWSElasticacheUser_updateAccessString (99.19s)
--- PASS: TestAccAWSElasticacheUser_removePasswords (99.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	101.319s
```

### CODE REVIEW

**Comment by drarnold** [comment]
Still need to add a lot of functionality, but the foundation is there now from a testability perspecitve.

**Comment by drarnold** [comment]
I feel that this is ready for review.  Please let me know if there is anything else we might need to go over.  Thank you!

**Comment by boxrick** [comment]
Any movement with this?

**Comment by edbighead** [comment]
patiently waiting

**Comment by boxrick** [comment]
I've ended up hacking my own Cloudformation / CLI hack in the meanwhile. It's sadly meant we used a bunch of workarounds.

If this needs some more tests or merge conflicts fixing to get it out, im happy to help.

**Comment by stevehipwell** [comment]
Any progress on this?

**Comment by OmarSalka** [comment]
@hashicorp/terraform-aws

**Comment by stevehipwell** [comment]
Could a maintainer rebase this?

**Comment by drarnold** [comment]
Sorry for the radio silence with this project.  I will start working on it again during the evenings and should try to get something out shortly.

**Review by bill-rich — APPROVED** [review]
LGTM
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheUser_ -timeout 180m
=== RUN   TestAccAWSElasticacheUser_basic
=== PAUSE TestAccAWSElasticacheUser_basic
=== RUN   TestAccAWSElasticacheUser_tags
=== PAUSE TestAccAWSElasticacheUser_tags
=== RUN   TestAccAWSElasticacheUser_disappears
=== PAUSE TestAccAWSElasticacheUser_disappears
=== CONT  TestAccAWSElasticacheUser_basic
=== CONT  TestAccAWSElasticacheUser_disappears
=== CONT  TestAccAWSElasticacheUser_tags
--- PASS: TestAccAWSElasticacheUser_disappears (14.71s)
--- PASS: TestAccAWSElasticacheUser_basic (17.78s)
--- PASS: TestAccAWSElasticacheUser_tags (40.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	40.196s
```

**Pull request merged**
