### PR TITLE
r/aws_neptune_global_cluster: Support for Neptune Global Databases

### LINKED ISSUE #26132: Neptune Global Cluster Support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support for newly released Neptune Global Databases 

### New or Affected Resource(s)

* aws_neptune_global_cluster
* aws_neptune_cluster

### Potential Terraform Configuration

```hcl
resource "aws_neptune_global_cluster" "example" {
  global_cluster_identifier = "global-test"
  engine                    = "neptune"
  engine_version            = "1.2.0.0"
}

resource "aws_neptune_cluster" "example" {
...
  global_cluster_identifier = aws_neptune_global_cluster.example.id
...
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2022/07/amazon-neptune-global-database/

### PR DESCRIPTION
**Pull request by larssnellman**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

 Closes #26132

Output from acceptance testing:

```
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 3 -run='TestAccNeptuneGlobalCluster'  -timeout 180m
=== RUN   TestAccNeptuneGlobalCluster_basic
=== PAUSE TestAccNeptuneGlobalCluster_basic
=== RUN   TestAccNeptuneGlobalCluster_completeBasic
=== PAUSE TestAccNeptuneGlobalCluster_completeBasic
=== RUN   TestAccNeptuneGlobalCluster_disappears
=== PAUSE TestAccNeptuneGlobalCluster_disappears
=== RUN   TestAccNeptuneGlobalCluster_DeletionProtection
=== PAUSE TestAccNeptuneGlobalCluster_DeletionProtection
=== RUN   TestAccNeptuneGlobalCluster_Engine
=== PAUSE TestAccNeptuneGlobalCluster_Engine
=== RUN   TestAccNeptuneGlobalCluster_EngineVersion
=== PAUSE TestAccNeptuneGlobalCluster_EngineVersion
=== RUN   TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
=== PAUSE TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
=== RUN   TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
=== PAUSE TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
=== RUN   TestAccNeptuneGlobalCluster_StorageEncrypted
=== PAUSE TestAccNeptuneGlobalCluster_StorageEncrypted
=== CONT  TestAccNeptuneGlobalCluster_basic
=== CONT  TestAccNeptuneGlobalCluster_EngineVersion
=== CONT  TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
--- PASS: TestAccNeptuneGlobalCluster_basic (36.29s)
=== CONT  TestAccNeptuneGlobalCluster_DeletionProtection
--- PASS: TestAccNeptuneGlobalCluster_EngineVersion (41.04s)
=== CONT  TestAccNeptuneGlobalCluster_Engine
--- PASS: TestAccNeptuneGlobalCluster_Engine (33.74s)
=== CONT  TestAccNeptuneGlobalCluster_StorageEncrypted
--- PASS: TestAccNeptuneGlobalCluster_DeletionProtection (78.92s)
=== CONT  TestAccNeptuneGlobalCluster_disappears
--- PASS: TestAccNeptuneGlobalCluster_StorageEncrypted (43.85s)
=== CONT  TestAccNeptuneGlobalCluster_completeBasic
--- PASS: TestAccNeptuneGlobalCluster_disappears (25.64s)
=== CONT  TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
--- PASS: TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted (155.85s)
--- PASS: TestAccNeptuneGlobalCluster_completeBasic (133.32s)
--- PASS: TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic (172.31s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	316.815s

TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 3 -run='TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters'  -timeout 180m
=== RUN   TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
=== PAUSE TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
=== CONT  TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
--- PASS: TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters (2165.37s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/neptune    2167.768s

...
```

### CODE REVIEW

**Comment by larssnellman** [comment]
This is ready for Hashi review. 

A shoutout I forgot to mention in the PR, this follows nearly the same implementation of aws_rds_global_cluster and aws_docdb_global_cluster since these Global APIs are similar.

Thanks in advance!

**Comment by AdamTylerLynch** [comment]
@larssnellman can you merge in the latest `main`, and fix the conflict.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccNeptuneGlobalCluster_\|TestAccNeptuneCluster_GlobalClusterIdentifier_' PKG=neptune ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 2  -run=TestAccNeptuneGlobalCluster_\|TestAccNeptuneCluster_GlobalClusterIdentifier_\|TestAccNeptuneCluster_basic -timeout 180m
=== RUN   TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
=== PAUSE TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
=== RUN   TestAccNeptuneGlobalCluster_basic
=== PAUSE TestAccNeptuneGlobalCluster_basic
=== RUN   TestAccNeptuneGlobalCluster_completeBasic
=== PAUSE TestAccNeptuneGlobalCluster_completeBasic
=== RUN   TestAccNeptuneGlobalCluster_disappears
=== PAUSE TestAccNeptuneGlobalCluster_disappears
=== RUN   TestAccNeptuneGlobalCluster_DeletionProtection
=== PAUSE TestAccNeptuneGlobalCluster_DeletionProtection
=== RUN   TestAccNeptuneGlobalCluster_Engine
=== PAUSE TestAccNeptuneGlobalCluster_Engine
=== RUN   TestAccNeptuneGlobalCluster_EngineVersion
=== PAUSE TestAccNeptuneGlobalCluster_EngineVersion
=== RUN   TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
=== PAUSE TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
=== RUN   TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
=== PAUSE TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
=== RUN   TestAccNeptuneGlobalCluster_StorageEncrypted
=== PAUSE TestAccNeptuneGlobalCluster_StorageEncrypted
=== CONT  TestAccNeptuneGlobalCluster_Engine
=== CONT  TestAccNeptuneGlobalCluster_completeBasic
--- PASS: TestAccNeptuneGlobalCluster_Engine (29.25s)
=== CONT  TestAccNeptuneGlobalCluster_DeletionProtection
--- PASS: TestAccNeptuneGlobalCluster_DeletionProtection (72.14s)
=== CONT  TestAccNeptuneGlobalCluster_disappears
--- PASS: TestAccNeptuneGlobalCluster_disappears (19.53s)
=== CONT  TestAccNeptuneGlobalCluster_basic
--- PASS: TestAccNeptuneGlobalCluster_basic (25.89s)
=== CONT  TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
--- PASS: TestAccNeptuneGlobalCluster_completeBasic (172.15s)
=== CONT  TestAccNeptuneGlobalCluster_StorageEncrypted
--- PASS: TestAccNeptuneGlobalCluster_StorageEncrypted (43.26s)
=== CONT  TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
--- PASS: TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted (159.98s)
=== CONT  TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
--- PASS: TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic (140.86s)
=== CONT  TestAccNeptuneGlobalCluster_EngineVersion
--- PASS: TestAccNeptuneGlobalCluster_EngineVersion (25.02s)
--- PASS: TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters (2528.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	2765.327s
```

**Comment by ewbankkit** [comment]
@larssnellman Thanks for the contribution :tada: :clap:.

**Pull request merged**
