### PR TITLE
New data source: aws_ecr_pull_through_cache_rule

### LINKED ISSUE #31578: New Data Source: aws_ecr_pull_through_cache_rule
### Description

Returns the pull through cache rules for a registry.

My use case is to have terraform check if the pull through cache rule has been setup for `quay.io`, then switch my ECS cluster pulling from `quay.io/rockylinux/rockylinux:9` to pull from the Amazon ECR repository URI `1484931600.dkr.ecr.us-east-1.amazonaws.com/quay.io/rockylinux/rockylinux:9`

### Requested Resource(s) and/or Data Source(s)

* aws_ecr_pull_through_cache_rule

### Potential Terraform Configuration

```terraform
data "aws_ecr_pull_through_cache_rule" "example" {
    ecr_repository_prefix = "quay"
}
```

### References

* https://github.com/hashicorp/terraform-provider-aws/issues/21951
* https://docs.aws.amazon.com/cli/latest/reference/ecr/describe-pull-through-cache-rules.html

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

Provides a new data source for the ECR Pull Through Cache Rule

### Relations

Closes #31578

### Output from Acceptance Testing

```
$ make testacc TESTARGS='-run=TestAccECRPullThroughCacheRuleDataSource_basic' PKG=ecr
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20  -run=TestAccECRPullThroughCacheRuleDataSource_basic -timeout 180m
=== RUN   TestAccECRPullThroughCacheRuleDataSource_basic
=== PAUSE TestAccECRPullThroughCacheRuleDataSource_basic
=== CONT  TestAccECRPullThroughCacheRuleDataSource_basic
--- PASS: TestAccECRPullThroughCacheRuleDataSource_basic (28.73s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        30.876s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccECRPullThroughCacheRuleDataSource_' PKG=ecr ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 2  -run=TestAccECRPullThroughCacheRuleDataSource_ -timeout 180m
=== RUN   TestAccECRPullThroughCacheRuleDataSource_basic
=== PAUSE TestAccECRPullThroughCacheRuleDataSource_basic
=== CONT  TestAccECRPullThroughCacheRuleDataSource_basic
--- PASS: TestAccECRPullThroughCacheRuleDataSource_basic (20.61s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	26.347s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Comment by vincentclee** [comment]
Thank You @bschaatsbergen . Can't wait to get my hands on it and test it out! :rocket:

**Comment by bschaatsbergen** [comment]
> Thank You @bschaatsbergen . Can't wait to get my hands on it and test it out! :rocket: 

Happy to help!

**Pull request merged**
