### PR TITLE
feat(vpc): Enable addition amazon provided ipv6 cidr

### LINKED ISSUE #25136: aws_vpc_ipv6_cidr_block_association only accepts IPAM pool
aws_vpc_ipv6_cidr_block_association only accepts IPAM pool, whereas via the console/CLI, one can request an Amazon provided block. Allows import though, with `ipv6_ipam_pool_id = ""`

### PR DESCRIPTION
**Pull request by project0**
* Extend existing `vpc_ipv6_cidr_block_association` resource to allow requesting additional ipv6 CIDR from the amazon pool

### Relations

Closes #25136

### References

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateVpcCidrBlock.html

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by posquit0** [comment]
Currently, there are some limitations to manage VPC's IPv6 CIDR. I hope that this feature will be implemented quickly.

**Comment by nikosmeds** [comment]
What can we do to get movement here? 🙏

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCIPv6CIDRBlockAssociation_basic\|TestAccVPCIPv6CIDRBlockAssociation_disappears' PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCIPv6CIDRBlockAssociation_basic\|TestAccVPCIPv6CIDRBlockAssociation_disappears -timeout 360m
=== RUN   TestAccVPCIPv6CIDRBlockAssociation_basic
=== PAUSE TestAccVPCIPv6CIDRBlockAssociation_basic
=== RUN   TestAccVPCIPv6CIDRBlockAssociation_disappears
=== PAUSE TestAccVPCIPv6CIDRBlockAssociation_disappears
=== CONT  TestAccVPCIPv6CIDRBlockAssociation_basic
=== CONT  TestAccVPCIPv6CIDRBlockAssociation_disappears
--- PASS: TestAccVPCIPv6CIDRBlockAssociation_basic (51.13s)
--- PASS: TestAccVPCIPv6CIDRBlockAssociation_disappears (57.31s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	62.522s
```

**Comment by ewbankkit** [comment]
@project0 Thanks for the contribution :tada: :clap:.

**Pull request merged**
