### PR TITLE
resource/aws_emr_cluster: Fix aws_emr_security_configuration destroy issues

### LINKED ISSUE #3465: Issue destroying EMR on AWS
_This issue was originally opened by @miloup as hashicorp/terraform#17330. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi,

Many of us in many company are facing an issue while trying to destroy an EMR infrastructure on AWS.
The Terraform folder has an **emr-requirements.tf** file which contains Security-Groups, Security-Configuration,...etc. and an **emr.tf** file which creates the cluster using the configuration is the **emr-requirements.tf**

When running "_terraform apply_", the infrastructure is successfully created, but when running "_terraform destroy_", it seems that Terraform does not wait for the EMR cluster to terminate before destroying the remaining resources which leads to a failure (timeout) due to their dependencies to this cluster. The only way to have a clean "destroy" is by making sure that the EMR cluster is terminated (by checking on the AWS console for instance), then run "_terraform destroy_" again. Now, all the remaining resources are destroyed.

Would you please fix this bug?

Thanks

### LINKED ISSUE #6279: aws_emr_cluster and aws_emr_security_configuration destroy issues
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.11.8 with AWS provider 1.30

I realize these aren't the latest versions but I don't think this module has changed recently and I haven't had a chance to test yet.

### Affected Resource(s)

* `aws_emr_cluster`
* `aws_emr_security_configuration`

### What I did

If I have terraform manage my `aws_emr_cluster` and pass a terraform-managed `aws_emr_security_configuration` into that cluster, `terraform destroy` fails consistently to destroy the security configuration.

### Expected Behavior

`terraform destroy` successfully cleans up all the resources it created

### Actual Behavior

```
Error: Error applying plan:

1 error(s) occurred:

* aws_emr_security_configuration.main (destroy): 1 error(s) occurred:

* aws_emr_security_configuration.main: InvalidRequestException: Security configuration 'tf-emr-sc-20181022205505705400000001' cannot be deleted because it is in use by active clusters.
	status code: 400, request id: e6338f23-d936-12e8-ad83-7bea3842861a
```

### Steps to Reproduce

1. Create a minimal EMR cluster with just `aws_emr_cluster` and give it an `aws_emr_security_configuration`.
2. `terraform apply`
3. `terraform destroy`

### Important Factoids

I think it's just not waiting long enough before attempting to destroy the security configuration. If I try again a minute or two later, the destroy works fine.

### PR DESCRIPTION
**Pull request by andrei-ilyin-mh**
This will fix #6279

Rewrite resourceAwsEMRClusterDelete to use cluster state returned by DescribeCluster instead of counting running cluster instances to check is cluster terminated. Previous approach might cause too early deletion of cluster's security group which might block deletion of ENI created for this cluster. In this case orphaned ENI is blocking deletion of security configuration as well as linked security group.

These changes was tested on our environments and has fixed painful security configuration deletion issues.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #6279.
Closes #3465.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_emr_cluster: Fix aws_emr_security_configuration destroy issues
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEMRCluster_security_config'

--- PASS: TestAccAWSEMRCluster_security_config (475.02s)
```

### CODE REVIEW

**Comment by xmj** [comment]
Is there anything else that needs to be done for this to be merged?

**Comment by annyip** [comment]
any update?

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```
--- PASS: TestAccEMRCluster_basic (498.93s)
--- PASS: TestAccEMRCluster_Kerberos_clusterDedicatedKdc (508.54s)
--- PASS: TestAccEMRCluster_ebs (544.68s)
--- PASS: TestAccEMRCluster_keepJob (550.65s)
--- PASS: TestAccEMRCluster_StepConcurrency_level (551.00s)
--- PASS: TestAccEMRCluster_InstanceFleetMaster_only (563.63s)
--- PASS: TestAccEMRCluster_security (585.81s)
--- PASS: TestAccEMRCluster_CustomAMI_id (769.74s)
--- PASS: TestAccEMRCluster_terminationProtected (675.60s)
--- PASS: TestAccEMRCluster_tags (893.02s)
--- PASS: TestAccEMRCluster_RootVolume_size (919.63s)
--- PASS: TestAccEMRCluster_MasterInstanceGroup_instanceType (970.80s)
--- PASS: TestAccEMRCluster_MasterInstanceGroup_name (980.30s)
--- PASS: TestAccEMRCluster_Step_basic (983.61s)
--- PASS: TestAccEMRCluster_EC2Attributes_defaultManagedSecurityGroups (997.66s)
--- PASS: TestAccEMRCluster_Step_multiple (536.07s)
--- PASS: TestAccEMRCluster_disappears (486.32s)
--- PASS: TestAccEMRCluster_CoreInstanceGroup_name (1060.80s)
--- PASS: TestAccEMRCluster_InstanceFleet_basic (1113.99s)
--- PASS: TestAccEMRCluster_s3Logging (613.65s)
--- PASS: TestAccEMRCluster_sJSON (400.21s)
--- PASS: TestAccEMRCluster_CoreInstanceGroup_autoScalingPolicy (648.83s)
--- PASS: TestAccEMRCluster_MasterInstanceGroup_instanceCount (1217.81s)
--- PASS: TestAccEMRCluster_additionalInfo (372.52s)
--- PASS: TestAccEMRCluster_Step_mode (958.18s)
--- PASS: TestAccEMRCluster_CoreInstanceGroup_instanceType (972.02s)
--- PASS: TestAccEMRCluster_MasterInstanceGroup_bidPrice (1570.08s)
--- PASS: TestAccEMRCluster_Bootstrap_ordering (1607.18s)
--- PASS: TestAccEMRCluster_CoreInstanceGroup_instanceCount (1040.68s)
--- PASS: TestAccEMRCluster_autoTerminationPolicy (703.99s)
--- PASS: TestAccEMRCluster_CoreInstanceGroup_bidPrice (1340.46s)
```

**Comment by ewbankkit** [comment]
@andrei-ilyin-mh Thanks for the contribution :tada: :clap:.

**Pull request merged**
