### PR TITLE
d/aws_imagebuilder_components - new data source

### PR DESCRIPTION
**Pull request by kamilturek**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #17035.

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccImageBuilderComponentsDataSource_" PKG_NAME=internal/service/imagebuilder
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run=TestAccImageBuilderComponentsDataSource_ -timeout 180m
=== RUN   TestAccImageBuilderComponentsDataSource_filter
=== PAUSE TestAccImageBuilderComponentsDataSource_filter
=== CONT  TestAccImageBuilderComponentsDataSource_filter
--- PASS: TestAccImageBuilderComponentsDataSource_filter (45.09s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder       51.845s
```

### CODE REVIEW

**Comment by kamilturek** [comment]
I'd need some help on this. It seems that there is some inconsistency in `ListComponents` call. Components are not returned by this call just after they were created. It takes a while for them to appear in the response. A way to reproduce this behaviour:

```terraform
resource "aws_imagebuilder_component" "test" {
  data = yamlencode({
    phases = [{
      name = "build"
      steps = [{
        action = "ExecuteBash"
        inputs = {
          commands = ["echo 'hello world'"]
        }
        name      = "example"
        onFailure = "Continue"
      }]
    }]
    schemaVersion = 1.0
  })
  name     = "aaa"
  platform = "Linux"
  version  = "1.0.0"
}

data "aws_imagebuilder_component" "test" {
  arn = aws_imagebuilder_component.test.arn
}

output "get_output" {
  value = data.aws_imagebuilder_component.test.arn
}

data "aws_imagebuilder_components" "test" {
  owner = "Self"

  filter {
    name   = "name"
    values = [aws_imagebuilder_component.test.name]
  }
}

output "list_output" {
  value = data.aws_imagebuilder_components.test.arns
}
```

Immediate outputs:
```
Outputs:

get_output = "arn:aws:imagebuilder:eu-central-1:113405211942:component/aaa/1.0.0/1"
list_output = toset([])
```

Re-applying the config after a while - list output appears:
```
Changes to Outputs:
  ~ list_output = [
      + "arn:aws:imagebuilder:eu-central-1:113405211942:component/aaa/1.0.0",
    ]
```

Does it mean that we need to introduce retries for some propagation time? The AWS docs do not mention anything about the eventual consistency of this service.

**Comment by kamilturek** [comment]
I managed to sort out the problem described above.

I had a look at how it is done in [ebs_volumes_data_source_test.go](https://github.com/hashicorp/terraform-provider-aws/blob/b039cc5402b960cf4ec4440e95af2d0d4fec7f6d/internal/service/ec2/ebs_volumes_data_source_test.go#L21-L28) and followed that way.

Basically, the first test step contains only the resource, and the second test step introduces a data source configuration. That way makes the newly created component already visible in the `ListComponents` response as it takes some time for it to appear there.

**Comment by ewbankkit** [comment]
@kamilturek Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
@kamilturek Thanks for the contribution :tada: :clap:.

**Pull request merged**
