### PR TITLE
add quicksight data source resource

### PR DESCRIPTION
**Pull request by lacernetic**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

NOTE: This code is an updated version of issue #11094 created by @mjgpy3. Due to his absence I will take up role in changing it according to the code review.

Relates #10990
Closes #11094

Output from acceptance testing:

```$ make testacc TESTARGS='-run=TestAccAWSQuickSightDataSource'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSQuickSightDataSource -timeout 180m
=== RUN   TestAccAWSQuickSightDataSource_basic
=== PAUSE TestAccAWSQuickSightDataSource_basic
=== RUN   TestAccAWSQuickSightDataSource_disappears
=== PAUSE TestAccAWSQuickSightDataSource_disappears
=== CONT  TestAccAWSQuickSightDataSource_basic
=== CONT  TestAccAWSQuickSightDataSource_disappears
--- PASS: TestAccAWSQuickSightDataSource_disappears (36.73s)
--- PASS: TestAccAWSQuickSightDataSource_basic (41.33s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       41.466s
```

```
$ make testacc TESTARGS='-run=TestAccAWSQuickSightDataSource'

...
```

### CODE REVIEW

**Comment by lacernetic** [comment]
I noticed that this PR has a label of "data-source", it can be a little confusing but this is a `resource` called "data-source"

**Comment by anGie44** [comment]
Hi @lacernetic, thank you again for this PR and extending the initial work submitted by @mjgpy3 ! Overall the implementation is in a good place. To get this into the upcoming release, I'm going to refactor some bits to align with our contributing practices and then this should be good to go. The first of which will be `Tags` handling; the methods added in this PR are the right idea, however, we have methods available to us in the provider which we can substitute in; for future reference https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#resource-tagging-code-implementation. The second refactoring will occur in method names tied to expanding/flattening API objects; we'll want to follow this guidance https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/data-handling-and-conversion.md#recommended-implementations. The third addition will then be custom waiter logic; as seen in the resource's Read CRUD operation, some retry handling can be necessary to ensure the resource is in a ready state. To generalize the retry logic for create and update operations, custom waiters will be added per https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#resource-lifecycle-retries . For the unit testing, I'll move that over to the specific resource test file and then add a `tags` related acceptance test as well.

**Comment by lacernetic** [comment]
@anGie44 Hey Angie! I totally want to allow edits for maintainers, but I'm struggling to find the option for it. I went to [github's guide](https://docs.github.com/en/github/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) on doing this, but I don't see that option anywhere. I am pretty confident that my organization is not interfering with this. Do you know of another way to do this?

**Comment by anGie44** [comment]
Hmm I would of shared the same link for reference 😅 No worries though! I can create a new PR that retains all of your commits and then push changes there.

**Pull request closed without merging**
