### PR TITLE
Add multiple listeners for Virtual Nodes, Routers, and Gateways

### LINKED ISSUE #26380: aws_appmesh_virtual_node should support multiple listeners
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Via the console it is possible to specify multiple listeners for an app mesh virtual node.

The terraform resource `aws_appmesh_virtual_node` seems to only support the ability to define a single listener. Even when importing a node with multiple listeners defined, it only creates configuration for the first listener in the list.

### New or Affected Resource(s)

* aws_appmesh_virtual_node

### Potential Terraform Configuration

```hcl
resource "aws_appmesh_virtual_node" "serviceb1" {
  name      = "serviceBv1"
  mesh_name = aws_appmesh_mesh.simple.id

  spec {
    backend {
      virtual_service {
        virtual_service_name = "servicea.simpleapp.local"
      }
    }

    listener {
      port_mapping {
        port     = 8081
        protocol = "http"
      }
    }

    listener {
      port_mapping {
        port     = 8080
        protocol = "http"
      }
    }

    service_discovery {
      dns {
        hostname = "serviceb.simpleapp.local"
      }
    }
  }
}
```

### PR DESCRIPTION
**Pull request by benmurden**
### Description

Add multiple listeners to App Mesh in order to support the changes made generally available on Aug 17, 2022. 

### Relations

Closes #26380

### References

https://aws.amazon.com/about-aws/whats-new/2022/08/aws-app-mesh-support-multiple-listeners/

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccAppMesh_serial/VirtualNode/multipleListeners PKG=appmesh

=== RUN   TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/VirtualNode
=== RUN   TestAccAppMesh_serial/VirtualNode/multipleListeners
--- PASS: TestAccAppMesh_serial (14.29s)
    --- PASS: TestAccAppMesh_serial/VirtualNode (14.29s)
        --- PASS: TestAccAppMesh_serial/VirtualNode/multipleListeners (14.29s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appmesh    14.532s

$ make testacc TESTS=TestAccAppMesh_serial/VirtualRouter/multipleListeners PKG=appmesh

=== RUN   TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/VirtualRouter
=== RUN   TestAccAppMesh_serial/VirtualRouter/multipleListeners
--- PASS: TestAccAppMesh_serial (23.05s)
    --- PASS: TestAccAppMesh_serial/VirtualRouter (23.05s)
        --- PASS: TestAccAppMesh_serial/VirtualRouter/multipleListeners (23.05s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appmesh    23.269s

$ make testacc TESTS=TestAccAppMesh_serial/VirtualGateway/multipleListeners PKG=appmesh

=== RUN   TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/VirtualGateway
=== RUN   TestAccAppMesh_serial/VirtualGateway/multipleListeners
--- PASS: TestAccAppMesh_serial (23.02s)
    --- PASS: TestAccAppMesh_serial/VirtualGateway (23.02s)
        --- PASS: TestAccAppMesh_serial/VirtualGateway/multipleListeners (23.02s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appmesh    23.230s

$ make testacc TESTS=TestAccAppMesh_serial/GatewayRoute/(grpcRoute|httpRoute|http2Route) PKG=appmesh

=== RUN   TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/GatewayRoute
=== RUN   TestAccAppMesh_serial/GatewayRoute/grpcRoute
=== RUN   TestAccAppMesh_serial/GatewayRoute/httpRoute
=== RUN   TestAccAppMesh_serial/GatewayRoute/http2Route
--- PASS: TestAccAppMesh_serial (323.53s)
    --- PASS: TestAccAppMesh_serial/GatewayRoute (323.53s)
        --- PASS: TestAccAppMesh_serial/GatewayRoute/grpcRoute (83.68s)
        --- PASS: TestAccAppMesh_serial/GatewayRoute/httpRoute (120.19s)
        --- PASS: TestAccAppMesh_serial/GatewayRoute/http2Route (119.66s)
PASS

$ make testacc TESTS=TestAccAppMesh_serial/Route/(grpc|http2?|tcp)RouteTargetPort PKG=appmesh

=== RUN   TestAccAppMesh_serial
=== RUN   TestAccAppMesh_serial/GatewayRoute
=== RUN   TestAccAppMesh_serial/Route
=== RUN   TestAccAppMesh_serial/Route/httpRouteTargetPort
=== RUN   TestAccAppMesh_serial/Route/tcpRouteTargetPort
=== RUN   TestAccAppMesh_serial/Route/grpcRouteTargetPort
=== RUN   TestAccAppMesh_serial/Route/http2RouteTargetPort
=== RUN   TestAccAppMesh_serial/VirtualRouter
--- PASS: TestAccAppMesh_serial (125.41s)
    --- PASS: TestAccAppMesh_serial/GatewayRoute (0.00s)
    --- PASS: TestAccAppMesh_serial/Route (125.40s)
        --- PASS: TestAccAppMesh_serial/Route/httpRouteTargetPort (33.03s)
        --- PASS: TestAccAppMesh_serial/Route/tcpRouteTargetPort (31.33s)
        --- PASS: TestAccAppMesh_serial/Route/grpcRouteTargetPort (30.70s)
        --- PASS: TestAccAppMesh_serial/Route/http2RouteTargetPort (30.34s)
    --- PASS: TestAccAppMesh_serial/VirtualRouter (0.00s)
PASS
```

### CODE REVIEW

**Comment by SW386** [comment]
Wouldn't we also need to enable specifying port match in route and gateway route? AWS throws errors if multiple listeners are added without those specifications in the route.

**Comment by benmurden** [comment]
@SW386 Thanks for the comment. Do you have an example of a config that would now fail as a result of these changes?

**Comment by SW386** [comment]
I do not have anything I can share, but If you go to the AWS Appmesh console and have a route defined without a port match connected to a node, then try to modify that node with multiple listeners, you will receive `All Routes that are targeting this Virtual Node must define a port before adding multiple listeners to this Virtual Node. ` Terraform currently doesn't support specifying this property.

**Comment by benmurden** [comment]
I see, thanks for clarifying. Are there examples of Terraform resources that validate based on the content of _other_ resources? It seems to me this sort of thing is usually covered by documentation e.g. Security Groups and Security Group Rules https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/security_group_rule.

**Comment by SW386** [comment]
I don't have anything on the Terraform side since those resources are not updated to include port match and multiple listeners are not supported. However, on the AWS side, you can find the dependencies here:

Virtual Routes:
https://docs.aws.amazon.com/app-mesh/latest/userguide/routes.html

Virtual Gateway Rotues: 
https://docs.aws.amazon.com/app-mesh/latest/userguide/gateway-routes.html

For both resources, under match configuration, Port match is optional for a single listener but required for multiple listeners.

**Comment by benmurden** [comment]
I think I see now. Target Port is a required attribute when the target Virtual Node has multiple listeners. 🤔 

Still, I'm not sure how one would implement this; as mentioned, I'm unaware of previous examples of resources that validate against the attributes of related resources. The simplest option in that case might be to document this requirement.

**Comment by benmurden** [comment]
@SW386 I think that should do it for adding target ports. Could you have a look and confirm everything looks to be in order?

**Comment by SW386** [comment]
This looks right to me!

**Comment by benmurden** [comment]
Seems another PR #27799 was merged instead. Closing.

**Pull request closed without merging**
