### PR TITLE
New resource: `aws_globalaccelerator_custom_routing_accelerator`

### PR DESCRIPTION
**Pull request by jlsalmon**
### Description

This is a revival of #22162, rebased on main and refactored to conform to the latest SDK style.

Note: I have _not_ added new resources for the `AllowCustomRoutingTraffic` and `DenyCustromRoutingTraffic` API methods, because it's currently not clear to me what the best way of approaching these might be. Also, my current use case doesn't require me to manage these via Terraform (my application is responsible for updating these at runtime). I would suggest these could be implemented in a follow-up PR.

### Relations

Relates #16690.
Closes #22162.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27839.

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by amontalban** [comment]
Thank you for doing this @jlsalmon we cannot wait to have this in the AWS provider!

@justinretzolk let me know if you need some feedback on testing this.

**Comment by jlsalmon** [comment]
Many thanks @ewbankkit for giving this some fresh momentum! 🙏

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccGlobalAccelerator' PKG=globalaccelerator ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/globalaccelerator/... -v -count 1 -parallel 3  -run=TestAccGlobalAccelerator -timeout 180m
=== RUN   TestAccGlobalAcceleratorAcceleratorDataSource_basic
=== PAUSE TestAccGlobalAcceleratorAcceleratorDataSource_basic
=== RUN   TestAccGlobalAcceleratorAccelerator_basic
=== PAUSE TestAccGlobalAcceleratorAccelerator_basic
=== RUN   TestAccGlobalAcceleratorAccelerator_ipAddressType_dualStack
=== PAUSE TestAccGlobalAcceleratorAccelerator_ipAddressType_dualStack
=== RUN   TestAccGlobalAcceleratorAccelerator_byoip
=== PAUSE TestAccGlobalAcceleratorAccelerator_byoip
=== RUN   TestAccGlobalAcceleratorAccelerator_disappears
=== PAUSE TestAccGlobalAcceleratorAccelerator_disappears
=== RUN   TestAccGlobalAcceleratorAccelerator_update
=== PAUSE TestAccGlobalAcceleratorAccelerator_update
=== RUN   TestAccGlobalAcceleratorAccelerator_attributes
=== PAUSE TestAccGlobalAcceleratorAccelerator_attributes
=== RUN   TestAccGlobalAcceleratorAccelerator_tags
=== PAUSE TestAccGlobalAcceleratorAccelerator_tags
=== RUN   TestAccGlobalAcceleratorCustomRoutingAcceleratorDataSource_basic
=== PAUSE TestAccGlobalAcceleratorCustomRoutingAcceleratorDataSource_basic
=== RUN   TestAccGlobalAcceleratorCustomRoutingAccelerator_basic
=== PAUSE TestAccGlobalAcceleratorCustomRoutingAccelerator_basic
=== RUN   TestAccGlobalAcceleratorCustomRoutingAccelerator_disappears
=== PAUSE TestAccGlobalAcceleratorCustomRoutingAccelerator_disappears
=== RUN   TestAccGlobalAcceleratorCustomRoutingAccelerator_tags
=== PAUSE TestAccGlobalAcceleratorCustomRoutingAccelerator_tags
=== RUN   TestAccGlobalAcceleratorCustomRoutingAccelerator_update
=== PAUSE TestAccGlobalAcceleratorCustomRoutingAccelerator_update
=== RUN   TestAccGlobalAcceleratorCustomRoutingEndpointGroup_basic
=== PAUSE TestAccGlobalAcceleratorCustomRoutingEndpointGroup_basic
=== RUN   TestAccGlobalAcceleratorCustomRoutingEndpointGroup_disappears
=== PAUSE TestAccGlobalAcceleratorCustomRoutingEndpointGroup_disappears
=== RUN   TestAccGlobalAcceleratorCustomRoutingEndpointGroup_endpointConfiguration
=== PAUSE TestAccGlobalAcceleratorCustomRoutingEndpointGroup_endpointConfiguration
=== RUN   TestAccGlobalAcceleratorCustomRoutingListener_basic
=== PAUSE TestAccGlobalAcceleratorCustomRoutingListener_basic
=== RUN   TestAccGlobalAcceleratorCustomRoutingListener_disappears
=== PAUSE TestAccGlobalAcceleratorCustomRoutingListener_disappears
=== RUN   TestAccGlobalAcceleratorEndpointGroup_basic
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_basic
=== RUN   TestAccGlobalAcceleratorEndpointGroup_disappears
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_disappears
=== RUN   TestAccGlobalAcceleratorEndpointGroup_ALBEndpoint_clientIP
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_ALBEndpoint_clientIP
=== RUN   TestAccGlobalAcceleratorEndpointGroup_instanceEndpoint
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_instanceEndpoint
=== RUN   TestAccGlobalAcceleratorEndpointGroup_multiRegion
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_multiRegion
=== RUN   TestAccGlobalAcceleratorEndpointGroup_portOverrides
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_portOverrides
=== RUN   TestAccGlobalAcceleratorEndpointGroup_tcpHealthCheckProtocol
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_tcpHealthCheckProtocol
=== RUN   TestAccGlobalAcceleratorEndpointGroup_update
=== PAUSE TestAccGlobalAcceleratorEndpointGroup_update
=== RUN   TestAccGlobalAcceleratorListener_basic
=== PAUSE TestAccGlobalAcceleratorListener_basic
=== RUN   TestAccGlobalAcceleratorListener_disappears
=== PAUSE TestAccGlobalAcceleratorListener_disappears
=== RUN   TestAccGlobalAcceleratorListener_update
=== PAUSE TestAccGlobalAcceleratorListener_update
=== CONT  TestAccGlobalAcceleratorAcceleratorDataSource_basic
=== CONT  TestAccGlobalAcceleratorCustomRoutingEndpointGroup_endpointConfiguration
=== CONT  TestAccGlobalAcceleratorCustomRoutingAcceleratorDataSource_basic
--- PASS: TestAccGlobalAcceleratorCustomRoutingAcceleratorDataSource_basic (78.48s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingEndpointGroup_disappears
--- PASS: TestAccGlobalAcceleratorAcceleratorDataSource_basic (102.36s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingEndpointGroup_basic
--- PASS: TestAccGlobalAcceleratorCustomRoutingEndpointGroup_disappears (158.80s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingAccelerator_update
--- PASS: TestAccGlobalAcceleratorCustomRoutingEndpointGroup_basic (171.04s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingAccelerator_tags
--- PASS: TestAccGlobalAcceleratorCustomRoutingAccelerator_update (122.01s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingAccelerator_disappears
--- PASS: TestAccGlobalAcceleratorCustomRoutingAccelerator_tags (98.65s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingAccelerator_basic
--- PASS: TestAccGlobalAcceleratorCustomRoutingAccelerator_disappears (81.47s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_multiRegion
--- PASS: TestAccGlobalAcceleratorCustomRoutingAccelerator_basic (86.07s)
=== CONT  TestAccGlobalAcceleratorListener_update
--- PASS: TestAccGlobalAcceleratorCustomRoutingEndpointGroup_endpointConfiguration (609.49s)
=== CONT  TestAccGlobalAcceleratorListener_disappears
--- PASS: TestAccGlobalAcceleratorListener_update (168.67s)
=== CONT  TestAccGlobalAcceleratorListener_basic
--- PASS: TestAccGlobalAcceleratorEndpointGroup_multiRegion (198.87s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_disappears
--- PASS: TestAccGlobalAcceleratorListener_disappears (142.72s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_update
--- PASS: TestAccGlobalAcceleratorListener_basic (144.53s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_instanceEndpoint
--- PASS: TestAccGlobalAcceleratorEndpointGroup_disappears (190.83s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_tcpHealthCheckProtocol
--- PASS: TestAccGlobalAcceleratorEndpointGroup_update (230.74s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_portOverrides
--- PASS: TestAccGlobalAcceleratorEndpointGroup_tcpHealthCheckProtocol (194.03s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingListener_disappears
--- PASS: TestAccGlobalAcceleratorCustomRoutingListener_disappears (141.66s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_basic
--- PASS: TestAccGlobalAcceleratorEndpointGroup_portOverrides (228.17s)
=== CONT  TestAccGlobalAcceleratorAccelerator_disappears
=== CONT  TestAccGlobalAcceleratorAccelerator_tags
--- PASS: TestAccGlobalAcceleratorAccelerator_disappears (70.78s)
--- PASS: TestAccGlobalAcceleratorEndpointGroup_basic (192.83s)
=== CONT  TestAccGlobalAcceleratorAccelerator_attributes
--- PASS: TestAccGlobalAcceleratorAccelerator_tags (87.98s)
=== CONT  TestAccGlobalAcceleratorEndpointGroup_ALBEndpoint_clientIP
--- PASS: TestAccGlobalAcceleratorEndpointGroup_instanceEndpoint (729.22s)
=== CONT  TestAccGlobalAcceleratorAccelerator_update
--- PASS: TestAccGlobalAcceleratorAccelerator_attributes (265.62s)
=== CONT  TestAccGlobalAcceleratorAccelerator_ipAddressType_dualStack
--- PASS: TestAccGlobalAcceleratorAccelerator_update (145.80s)
=== CONT  TestAccGlobalAcceleratorCustomRoutingListener_basic
--- PASS: TestAccGlobalAcceleratorAccelerator_ipAddressType_dualStack (77.30s)
=== CONT  TestAccGlobalAcceleratorAccelerator_basic
--- PASS: TestAccGlobalAcceleratorAccelerator_basic (76.17s)
=== CONT  TestAccGlobalAcceleratorAccelerator_byoip
    accelerator_test.go:349: Environment variable GLOBALACCELERATOR_BYOIP_IPV4_ADDRESS not set
--- SKIP: TestAccGlobalAcceleratorAccelerator_byoip (0.14s)
--- PASS: TestAccGlobalAcceleratorCustomRoutingListener_basic (134.26s)
--- PASS: TestAccGlobalAcceleratorEndpointGroup_ALBEndpoint_clientIP (796.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator	2172.714s
```

**Comment by amontalban** [comment]
Thank you very much @ewbankkit !!

**Pull request merged**
