### PR TITLE
Don't ignore dualstack prefix in Route 53 alias names

### LINKED ISSUE #6480: Dualstack prefix forcibly removed from ALIAS records
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.10
+ provider.aws v1.44.0
+ provider.terraform v1.0.2

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "big_happy_alias_record" {
  zone_id = "${var.zone_id}"
  name    = "${var.name}"
  type    = "${var.type}"

  alias {
    name                   = "${var.alias_name}"
    zone_id                = "${var.alias_zone_id}"
    evaluate_target_health = "${var.alias_evaluate_target_health}"
  }

  allow_overwrite = "${var.allow_overwrite}"
}

```

### Expected Behavior

I imported an existing DNS record into terraform, which was an ALIAS record that contained a "dualstack" prefix in its alias target.  I then ran a trivial apply operation on the resource to change the "allow_overwrite" value to false.  This should not have silently changed the ALIAS target in the record.

### Actual Behavior

The initial import worked fine, but when I run any apply whatsoever on the resource it ends up silently stripping off the "dualstack" prefix without saying anything in the plan.  

### Steps to Reproduce

1. `terraform apply` with any changes after importing an ALIAS record whose target has a dualstack prefix

### Important Factoids

I think I narrowed down why this is happening.  I inspected the debug output and found that the prefix did indeed seem to be stripped off halfway through the apply operation, so I checked the provider code and found [this function](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_route53_record.go#L957).  I haven't read this in any detail but it appears this would cause any ALIAS record in terraform to have its dualstack prefix stripped off 100% of the time.  Can anyone provide any insight into why this would be the desired/appropriate behavior? We actually do want many of our ALIAS records to use dualstack, so this pretty much means the route 53 resources are largely not useful at all in our case.

### References

### LINKED ISSUE #8013: aws_route53_record does not display alias names correctly
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.13
+ provider.aws v2.1.0
+ provider.helm v0.9.0
+ provider.kubernetes v1.5.2
```

### Affected Resource(s)

* aws_route53_record

### Terraform Configuration Files

```hcl
resource "aws_route53_record" "a_record" {
  zone_id = "${data.aws_route53_zone.brace.zone_id}"
  name    = XXXXXXX
  type    = "A"

  alias {
    name                   = "dualstack.${data.aws_elb.nginx-ingress.dns_name}"
    zone_id                = "${data.aws_elb.nginx-ingress.zone_id}"
    evaluate_target_health = false
  }
}
```

### Plan output

```
  ~ aws_route53_record.a_record
      alias.2394777190.evaluate_target_health:  "false" => "false"
      alias.2394777190.name:                    "a730c7bd249cb11e9b40b0a9d4fc1bd8-419703141.us-east-2.elb.amazonaws.com" => ""
      alias.2394777190.zone_id:                 "Z3AADJGX6KTTL2" => ""
      alias.~1237102533.evaluate_target_health: "" => "false"
      alias.~1237102533.name:                   "" => "${data.aws_elb.nginx-ingress.dns_name}"
      alias.~1237102533.zone_id:                "" => "${data.aws_elb.nginx-ingress.zone_id}"
```

### Expected Behavior

the alias name should be "dualstack.<elb hostname>" for alias.xxx.name 

### Actual Behavior

only the ELB hostname shows up for alias.xxx.name
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

nothing that i can tell is different. this is how i set up the `aws_elb`: it scrapes it out of k8s by looking for the service installed by nginx-ingress.

```hcl
data "kubernetes_service" "nginx_ingress" {
  metadata {
    name      = "${var.nginx_ingress["helm_name"]}-controller"
    namespace = "nginx-ingress"
  }

  depends_on = ["helm_release.nginx_ingress"]
}

data "aws_elb" "nginx-ingress" {
  name = "${element(split("-", element(split(".", data.kubernetes_service.nginx_ingress.load_balancer_ingress.0.hostname), 0)), 0)}"
}
```
### References

maybe its related to this??

* #7998

for more info on why `dualstack.` should really always be prefixed in this situation, search for `dualstack` on this page https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/resource-record-sets-values-alias.html

### PR DESCRIPTION
**Pull request by ngaya-ll**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #6480
Closes #8013

Currently, Terraform ignores the presence or absence of a `dualstack.` prefix in the alias target name when comparing Route 53 alias records.  However, the prefix is significant for aliases referencing an ELB as the un-prefixed domain name does not support AAAA queries.

The present normalization behavior was added in https://github.com/hashicorp/terraform/pull/9704 by @stack72.  In https://github.com/Hashicorp/terraform/issues/9628, @voltechs reported seeing a "perpetual diff" situation when using the unprefixed name, but I was not able to reproduce this behavior in a test case I added.

This PR removes the normalization logic, so that Terraform considers `dualstack.example-123456789.region.elb.amazonaws.com` and `example-123456789.region.elb.amazonaws.com` as distinct alias targets.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Don't ignore dualstack prefix in Route 53 alias names.
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSRoute53Record_Alias'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSRoute53Record_Alias -timeout 120m
=== RUN   TestAccAWSRoute53Record_Alias_Elb
=== PAUSE TestAccAWSRoute53Record_Alias_Elb
=== RUN   TestAccAWSRoute53Record_Alias_S3
=== PAUSE TestAccAWSRoute53Record_Alias_S3
=== RUN   TestAccAWSRoute53Record_Alias_VpcEndpoint
=== PAUSE TestAccAWSRoute53Record_Alias_VpcEndpoint
=== RUN   TestAccAWSRoute53Record_Alias_Uppercase
=== PAUSE TestAccAWSRoute53Record_Alias_Uppercase
=== RUN   TestAccAWSRoute53Record_AliasChange
=== PAUSE TestAccAWSRoute53Record_AliasChange
=== RUN   TestAccAWSRoute53Record_AliasChangeDualstack
=== PAUSE TestAccAWSRoute53Record_AliasChangeDualstack
=== CONT  TestAccAWSRoute53Record_Alias_Elb
=== CONT  TestAccAWSRoute53Record_AliasChange
=== CONT  TestAccAWSRoute53Record_Alias_S3
=== CONT  TestAccAWSRoute53Record_Alias_VpcEndpoint
=== CONT  TestAccAWSRoute53Record_Alias_Uppercase
=== CONT  TestAccAWSRoute53Record_AliasChangeDualstack
--- PASS: TestAccAWSRoute53Record_Alias_Uppercase (132.95s)
--- PASS: TestAccAWSRoute53Record_Alias_Elb (132.97s)
--- PASS: TestAccAWSRoute53Record_Alias_S3 (134.36s)
--- PASS: TestAccAWSRoute53Record_AliasChangeDualstack (178.90s)
--- PASS: TestAccAWSRoute53Record_AliasChange (183.16s)
--- PASS: TestAccAWSRoute53Record_Alias_VpcEndpoint (544.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	544.084s
```

### CODE REVIEW

**Comment by pascal-hofmann** [comment]
Workaround for `A` and `AAAA` records until this is merged: 
Both `A` and `AAAA` records do not need to point to the `dualstack.` alias. They only resolve to either ipv4 or ipv6 addresses anyway.

So for…
- `A` records: Use no prefix at all
- `AAAA` records: Use `ipv6.` prefix instead of `dualstack.` prefix.

**Comment by Cellane** [comment]
@pascal-hofmann 
I tried your workaround, thank you so much for posting it, but I don’t think it’s working for me.

First, I checked the DNS entries related to the load balancer:

- I get (presumably) correct IPv4 address when I run `dig <load-balancer> A`
- I get (presumably) correct IPv6 address when I run `dig <load-balancer> AAAA`
- I also get the same responses for `dig dualstack.<load-balancer> A` and `dig dualstack.<load-balancer> AAAA`
- However, `dig ipv6.<load-balancer> AAAA` returns nothing

After setting up records on `<my-domain>` with the prefixes you mentioned, I get sort of expected results:

- If I run `dig <my-domain> A`, I get the same IPv4 address as when I run `dig <load-balancer> A`
- However, if I run `dig <my-domain> AAAA` with the AAAA record pointing at the `ipv6` prefix, I get the same no-answer.

It could be just an issue with DNS propagation (although I kept flushing local cache between tries, and run the `dig` commands with `@ns-177.awsdns-22.com`, a name-server associated with my domain & zone), but for me, it seems like no prefix actually works nowadays:

That’s because if I point both the `A` and `AAAA` records directly at load balancer’s `dns_name`, both `dig <my-domain> A` and `dig <my-domain> AAAA` seem to work just fine.

**Comment by alkis-hexa** [comment]
Hey guys,
is this going to be fixed ? I think AWS is now forcing on all `A` or `AAAA` records to use the "dualstack." in front of the Load Balancer even if the type of the Load Balancer is set to `ipv4`.


`module "records" {
  source  = "terraform-aws-modules/route53/aws//modules/records"
  version = "~> 1.0"

  zone_name = data.aws_route53_zone.current.name
  records = [for record in ["test1", "test2", "test3"] :
    {
      name = record
      type = "A"
      alias = {
        name    =  format("dualstack.%s", module.alb_cluster_admin.this_lb_dns_name)
        zone_id = data.aws_route53_zone.current.zone_id
        ttl = 60
      }
    }
  ]

  depends_on = [module.alb_cluster_admin]
}`

even the above will not work as terraform is forcing the prefix out. On the AWS Console though it is as default to pick up the "dualstack." as prefix...

**Review by YakDriver — APPROVED** [review]
Looks good! Thanks 🎉 

@ngaya-ll @pascal-hofmann @Cellane @alkis-hexa My apologies for the delay in this fix. Thank you for contributing to the resolution of the issue.

```console
% make testacc TESTS=TestAccRoute53Record PKG=route53 
\==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53/... -v -count 1 -parallel 20 -run='TestAccRoute53Record'  -timeout 180m
--- PASS: TestAccRoute53Record_Allow_doNotOverwrite (180.26s)
--- PASS: TestAccRoute53Record_generatesSuffix (183.86s)
--- PASS: TestAccRoute53Record_Support_caa (184.99s)
--- PASS: TestAccRoute53Record_basic (207.79s)
--- PASS: TestAccRoute53Record_empty (224.79s)
--- PASS: TestAccRoute53Record_longTXTrecord (225.89s)
--- PASS: TestAccRoute53Record_Support_txt (231.39s)
--- PASS: TestAccRoute53Record_Support_ds (241.65s)
--- PASS: TestAccRoute53Record_Support_spf (242.87s)
--- PASS: TestAccRoute53Record_MultiValueAnswer_basic (254.16s)
--- PASS: TestAccRoute53Record_Geolocation_basic (256.62s)
--- PASS: TestAccRoute53Record_Allow_overwrite (272.25s)
--- PASS: TestAccRoute53Record_wildcard (311.05s)
--- PASS: TestAccRoute53Record_Alias_change (318.37s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_multiValueAnswer (323.69s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_latency (324.35s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_weighted (330.43s)
--- PASS: TestAccRoute53Record_Alias_changeDualstack (330.89s)
--- PASS: TestAccRoute53Record_HealthCheckID_setIdentifierChange (340.79s)
--- PASS: TestAccRoute53Record_Weighted_alias (393.48s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_failover (239.21s)
--- PASS: TestAccRoute53Record_Disappears_multipleRecords (244.72s)
--- PASS: TestAccRoute53Record_Latency_basic (182.14s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_geolocationContinent (258.21s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_geolocationCountrySpecified (225.71s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_geolocationCountrySubdivision (253.34s)
--- PASS: TestAccRoute53Record_fqdn (205.23s)
--- PASS: TestAccRoute53Record_typeChange (250.63s)
--- PASS: TestAccRoute53Record_trailingPeriodAndZoneID (166.81s)
--- PASS: TestAccRoute53Record_SetIdentifierRename_geolocationCountryDefault (265.72s)
--- PASS: TestAccRoute53Record_Disappears_basic (182.24s)
--- PASS: TestAccRoute53Record_Alias_uppercase (193.15s)
--- PASS: TestAccRoute53Record_Alias_s3 (189.23s)
--- PASS: TestAccRoute53Record_Weighted_basic (180.39s)
--- PASS: TestAccRoute53Record_Alias_elb (204.44s)
--- PASS: TestAccRoute53Record_setIdentifierChangeBasicToWeighted (284.84s)
--- PASS: TestAccRoute53Record_nameChange (298.55s)
--- PASS: TestAccRoute53Record_HealthCheckID_typeChange (303.39s)
--- PASS: TestAccRoute53Record_underscored (154.78s)
--- PASS: TestAccRoute53Record_failover (177.89s)
--- PASS: TestAccRoute53Record_WeightedToSimple_basic (215.13s)
--- PASS: TestAccRoute53Record_Alias_vpcEndpoint (507.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53	839.242s
```

**Pull request merged**
