### PR TITLE
d/aws_securityhub_standards_control_associations: new data source

### PR DESCRIPTION
**Pull request by kamilturek**
### Description
This PR adds a `aws_securityhub_standards_control_associations` plural data source.

### Relations
Relates https://github.com/hashicorp/terraform-provider-aws/issues/33082.

### References
https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_ListStandardsControlAssociations.html

### Output from Acceptance Testing
```console
% make testacc PKG=securityhub ACCTEST_PARALLELISM=1 TESTARGS="-run=TestAccSecurityHub_serial"
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/securityhub/... -v -count 1 -parallel 1  -run=TestAccSecurityHub_serial -timeout 360m
=== RUN   TestAccSecurityHub_serial
=== PAUSE TestAccSecurityHub_serial
=== CONT  TestAccSecurityHub_serial
=== RUN   TestAccSecurityHub_serial/StandardsAssociationsDataSource
=== RUN   TestAccSecurityHub_serial/StandardsAssociationsDataSource/basic
--- PASS: TestAccSecurityHub_serial (41.63s)
    --- PASS: TestAccSecurityHub_serial/StandardsAssociationsDataSource (41.63s)
        --- PASS: TestAccSecurityHub_serial/StandardsAssociationsDataSource/basic (41.63s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/securityhub        46.440s
```

### CODE REVIEW

**Review by jar-b — COMMENTED** [review]
Hi @kamilturek - Thanks for your submission!

As of 2023-10-20 we've started to require all net-new data sources use Terraform Plugin Framework. 

https://github.com/hashicorp/terraform-provider-aws/issues/32917
https://hashicorp.github.io/terraform-provider-aws/terraform-plugin-development-packages/#which-plugin-version-should-i-use

Maintainers will convert Plugin-SDK based data sources as part of the review process, but if you'd like to do the conversion in the meantime we would greatly appreciate it!

**Comment by kamilturek** [comment]
Hey @jar-b, I'll convert it to the framework. Thanks for letting me know!

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=securityhub TESTS=TestAccSecurityHub_serial/StandardsControlAssociationsDataSource
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/securityhub/... -v -count 1 -parallel 20 -run='TestAccSecurityHub_serial/StandardsControlAssociationsDataSource'  -timeout 360m
=== RUN   TestAccSecurityHub_serial
=== PAUSE TestAccSecurityHub_serial
=== CONT  TestAccSecurityHub_serial
=== RUN   TestAccSecurityHub_serial/StandardsControlAssociationsDataSource
=== RUN   TestAccSecurityHub_serial/StandardsControlAssociationsDataSource/basic
--- PASS: TestAccSecurityHub_serial (63.09s)
    --- PASS: TestAccSecurityHub_serial/StandardsControlAssociationsDataSource (63.09s)
        --- PASS: TestAccSecurityHub_serial/StandardsControlAssociationsDataSource/basic (63.09s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/securityhub        69.256s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @kamilturek! 👍 

Just adjusted the result slightly to include the full object returned from the `ListStandardsControlAssociations` API, rather than pulling out just the standards ARN.

**Comment by kamilturek** [comment]
@jar-b 

I followed the common approach for plural data sources and pulled just a list of attributes (e.g. `arns`, `names` - like [in here](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/autoscaling_groups)) but I agree having 
full objects is way better. Thanks a lot for help!

**Comment by jar-b** [comment]
Totally understandable! There are a _bunch_ of older resources which only return a subset of the API response fields. This is great for simplicity, but for new resources/data sources we tend to stick with matching the AWS API as close as possible to make it easier for users to translate between other interfaces (such as the AWS CLI or API documentation) and Terraform.

By no means meant to criticize the initial implementation, just to give some context to why the attributes changed. Thanks again for adding this! 👍

**Pull request merged**
