### PR TITLE
New resource: aws_iot_billing_group

### LINKED ISSUE #31030: [New Resource]: IoT Billing Groups
### Description

Currently, there is no way to manage AWS IoT billing groups with the AWS Terraform provider. This functionality is supported by the AWS CLI - https://docs.aws.amazon.com/cli/latest/reference/iot/create-billing-group.html

### Requested Resource(s) and/or Data Source(s)

aws_iot_billing_group resource

### Potential Terraform Configuration

```terraform
resource "aws_iot_billing_group" "billing_group" {
  name = "Billing group name"
  properties {
    description = "This is my billing group"
  }
  tags = {
    Name    = "Billing Group"
    Service = "IoT Core"
  }
}
```

### References

Create: https://docs.aws.amazon.com/cli/latest/reference/iot/create-billing-group.html
Update: https://docs.aws.amazon.com/cli/latest/reference/iot/update-billing-group.html
Delete: https://docs.aws.amazon.com/cli/latest/reference/iot/delete-billing-group.html
Describe: https://docs.aws.amazon.com/cli/latest/reference/iot/describe-billing-group.html

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by jmmarko**
### Description

Add resource: aws_iot_billing_group

### Relations

Closes #31030.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/22750.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/10629.

### References

Create: https://docs.aws.amazon.com/cli/latest/reference/iot/create-billing-group.html
Update: https://docs.aws.amazon.com/cli/latest/reference/iot/update-billing-group.html
Delete: https://docs.aws.amazon.com/cli/latest/reference/iot/delete-billing-group.html
Describe: https://docs.aws.amazon.com/cli/latest/reference/iot/describe-billing-group.html

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccIoTBillingGroup PKG=iot 

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTBillingGroup'  -timeout 180m
=== RUN   TestAccIoTBillingGroup_basic
=== PAUSE TestAccIoTBillingGroup_basic
=== RUN   TestAccIoTBillingGroup_disappears
=== PAUSE TestAccIoTBillingGroup_disappears
=== RUN   TestAccIoTBillingGroup_tags
=== PAUSE TestAccIoTBillingGroup_tags
=== RUN   TestAccIoTBillingGroup_properties
=== PAUSE TestAccIoTBillingGroup_properties
=== CONT  TestAccIoTBillingGroup_basic
=== CONT  TestAccIoTBillingGroup_tags
=== CONT  TestAccIoTBillingGroup_properties
=== CONT  TestAccIoTBillingGroup_disappears
--- PASS: TestAccIoTBillingGroup_disappears (10.77s)
--- PASS: TestAccIoTBillingGroup_basic (14.10s)
--- PASS: TestAccIoTBillingGroup_properties (21.35s)
--- PASS: TestAccIoTBillingGroup_tags (28.68s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iot        30.823s
```

### CODE REVIEW

**Review by dastko — APPROVED** [review]

**Review by markovuk992 — APPROVED** [review]

**Comment by abhinaysutrakar** [comment]
is this fix available now ?

**Comment by jmmarko** [comment]
> is this fix available now ?

The PR is waiting for review and to be merged. Please vote above to raise the priority of the PR. Thanks.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIoTBillingGroup_' PKG=iot ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 2  -run=TestAccIoTBillingGroup_ -timeout 360m
=== RUN   TestAccIoTBillingGroup_basic
=== PAUSE TestAccIoTBillingGroup_basic
=== RUN   TestAccIoTBillingGroup_disappears
=== PAUSE TestAccIoTBillingGroup_disappears
=== RUN   TestAccIoTBillingGroup_tags
=== PAUSE TestAccIoTBillingGroup_tags
=== RUN   TestAccIoTBillingGroup_properties
=== PAUSE TestAccIoTBillingGroup_properties
=== CONT  TestAccIoTBillingGroup_basic
=== CONT  TestAccIoTBillingGroup_tags
--- PASS: TestAccIoTBillingGroup_basic (24.54s)
=== CONT  TestAccIoTBillingGroup_properties
--- PASS: TestAccIoTBillingGroup_tags (57.27s)
=== CONT  TestAccIoTBillingGroup_disappears
--- PASS: TestAccIoTBillingGroup_properties (39.06s)
--- PASS: TestAccIoTBillingGroup_disappears (16.68s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	79.191s
```
```console
% make testacc TESTARGS='-run=TestAccIoTEventConfigurations_serial' PKG=iot                      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTEventConfigurations_serial -timeout 360m
=== RUN   TestAccIoTEventConfigurations_serial
=== PAUSE TestAccIoTEventConfigurations_serial
=== CONT  TestAccIoTEventConfigurations_serial
=== RUN   TestAccIoTEventConfigurations_serial/basic
--- PASS: TestAccIoTEventConfigurations_serial (22.69s)
    --- PASS: TestAccIoTEventConfigurations_serial/basic (22.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	28.351s
```

**Comment by ewbankkit** [comment]
@jmmarko Thanks for the contribution :tada: :clap:.

**Pull request merged**
