### PR TITLE
:memo: Replace docs to remove clients filter and just have a normal lookup

### PR DESCRIPTION
**Pull request by danquack**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #22615

### CODE REVIEW

**Review by kamilturek — CHANGES_REQUESTED** [review]
We've just merged a PR that introduces the `client_names` attribute to `aws_cognito_user_pool_clients` data source. Please see:
https://github.com/hashicorp/terraform-provider-aws/pull/22615

Maybe we could adjust your example to get the names directly from `aws_cognito_user_pool_clients.client_names`. What do you think?

**Comment by kamilturek** [comment]
@danquack Sounds good to me 🚀

**Comment by danquack** [comment]
I'm not sure what that test is that is failing. Is it a flaky test or is something broken? This change does not add or remove links, so not sure why it would be erroring.

**Comment by justinretzolk** [comment]
Hey @danquack -- that test seems to be failing pretty consistently across the board, so definitely not an issue with your PR. We've just started the process to release the next provider version, so I'll need to wait to merge until after that process is done, but then I'll get this merged in. Thank you for your contribution! 🚀

**Pull request merged**
