### PR TITLE
resource/aws_network_interface: Use first of private_ips as primary

### PR DESCRIPTION
**Pull request by matt-deboer**
This changes `private_ips` to List (instead of Set) for more intuitive/predictable behavior, which helps to solve issues #836 and #996.

Before this change, there was no reliable way to configure the primary_ip --> you simply got the ip address whose string value's hash had the lowest lexical sort order. Deterministic, yes, but not determined by the order the ips were specified in the list :)

### CODE REVIEW

**Comment by justinclayton** [comment]
This is pretty important to anyone who needs to attach more than one interface to an instance in a particular order, such as anything using a `keepalived`-style pattern.

**Comment by curator** [comment]
Agreed ... this keeps us from building infrastructures where HA is dependent on deterministic addressing order.

**Comment by matt-deboer** [comment]
@radeksimko any chance of taking another look at this one?

**Comment by thallam08** [comment]
This issue might be resolved by updating the documentation.  The option "private_ip" is not documented at https://www.terraform.io/docs/providers/aws/r/network_interface.html

**Comment by nbaztec** [comment]
I tested the above configuration however the privateIP seemed to be ignored:

```
resource "aws_vpc" "main" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_subnet" "public_a" {
  vpc_id = "${aws_vpc.main.id}"
  cidr_block = "10.0.0.0/24"
  availability_zone = "eu-central-1a"
}

resource "aws_network_interface" "test" {
  subnet_id   = "${aws_subnet.public_a.id}"
  private_ip  = "10.0.0.60"
  private_ips = ["10.0.0.51", "10.0.0.40", "10.0.0.30"]
}
```

```
$ terraform apply
aws_vpc.main: Creating...
  assign_generated_ipv6_cidr_block: "" => "false"
  cidr_block:                       "" => "10.0.0.0/16"
  default_network_acl_id:           "" => "<computed>"
  default_route_table_id:           "" => "<computed>"
  default_security_group_id:        "" => "<computed>"
  dhcp_options_id:                  "" => "<computed>"
  enable_classiclink:               "" => "<computed>"
  enable_classiclink_dns_support:   "" => "<computed>"
  enable_dns_hostnames:             "" => "<computed>"
  enable_dns_support:               "" => "true"
  instance_tenancy:                 "" => "<computed>"
  ipv6_association_id:              "" => "<computed>"
  ipv6_cidr_block:                  "" => "<computed>"
  main_route_table_id:              "" => "<computed>"
aws_vpc.main: Creation complete after 2s (ID: vpc-75ec0b1e)
aws_subnet.public_a: Creating...
  assign_ipv6_address_on_creation: "" => "false"
  availability_zone:               "" => "eu-central-1a"
  cidr_block:                      "" => "10.0.0.0/24"
  ipv6_cidr_block:                 "" => "<computed>"
  ipv6_cidr_block_association_id:  "" => "<computed>"
  map_public_ip_on_launch:         "" => "false"
  vpc_id:                          "" => "vpc-75ec0b1e"
aws_subnet.public_a: Creation complete after 1s (ID: subnet-2844ef43)
aws_network_interface.test: Creating...
  attachment.#:           "" => "<computed>"
  private_dns_name:       "" => "<computed>"
  private_ip:             "" => "10.0.0.60"
  private_ips.#:          "" => "3"
  private_ips.2391807628: "" => "10.0.0.51"
  private_ips.2949480860: "" => "10.0.0.30"
  private_ips.3767277403: "" => "10.0.0.40"
  private_ips_count:      "" => "<computed>"
  security_groups.#:      "" => "<computed>"
  source_dest_check:      "" => "true"
  subnet_id:              "" => "subnet-2844ef43"
```

However the primary was not set correctly as per the console.

```
Network interface ID: eni-1cb07249 | Subnet ID: subnet-2844ef43
VPC ID: vpc-75ec0b1e
MAC address: 02:87:95:cf:fe:3c 
Primary private IPv4 IP: 10.0.0.51
Secondary private IPv4 IPs: 10.0.0.30, 10.0.0.40
```

https://imgur.com/a/UwYMT

**Comment by thallam08** [comment]
I can confirm that the template above is not working.

Maybe the logic needs to be:
- If "private_ip" is set, then use that and prepend it to the "private_ips" if its not already there
- Or if "private_ip" is not set, then set it to the first IP in the "private_ips" list
- Always set the primary IP for an interface to the "private_ip"

Alternatively drop the "private_ip" as it's not documented and just use the first item in "private_ips"

**Comment by thallam08** [comment]
The AWS API works by specifying that one of the IP addresses is primary. http://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_PrivateIpAddressSpecification.html

Order is not the determining factor. 

Maybe the cleanest fix is to make sure that "private_ip" is honoured as the primary IP address, and this option is documented.

**Comment by thallam08** [comment]
From the CLI documentation:
`
--private-ip-address (string)

    The primary private IPv4 address of the network interface. If you don't specify an IPv4 address, Amazon EC2 selects one for you from the subnet's IPv4 CIDR range. If you specify an IP address, you cannot indicate any IP addresses specified in privateIpAddresses as primary (only one IP address can be designated as primary).

--private-ip-addresses (list)

    One or more private IPv4 addresses.
`

**Comment by nbaztec** [comment]
I agree with @thallam08 

After reviewing the AWS API it seems the plugin wasn't handling the private IP as it was supposed to be.
I've updated #1749 to behave in a reliable way and updated the tests accordingly. It's highly important to us that we switch away from our custom plugin to an officially supported/working one.

**Comment by thallam08** [comment]
There's a related issue that may not have been logged.  If you change the list of IPs then the primary IP may change.  The AWS CLI allows for adding and removing secondary IPs.  As implemented this module does not allow us to do this reliably as it may try to change the primary IP and either have to recreate the resource or fail (eg primary interface).

**Comment by yn-academia** [comment]
If you include both the "private_ip" and "private_ips", and make sure that "private_ip" is included in the list of "private_ips", it does what you want.

**Comment by yn-academia** [comment]
The real issue here is that "private_ip" is ignored completely, even when set. It's set in the state, but it doesn't seem to propagate to AWS as the primary

**Comment by thallam08** [comment]
That does not work for a non-primary interface.
Not sure it always works for primary interface.

**Comment by YakDriver** [comment]
This is closed by #17846. Let us know if that does not solve for your situation.

**Pull request closed without merging**
