### PR TITLE
Lakeformation Permissions trigger Force New

### PR DESCRIPTION
**Pull request by Tonkonozhenko**
Closes: #26557.
Closes: https://github.com/hashicorp/terraform-provider-aws/issues/30095.
Closes: https://github.com/hashicorp/terraform-provider-aws/issues/28448.

### CODE REVIEW

**Comment by justinretzolk** [comment]
Relates: #26557

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLakeFormation_serial/Permissions' PKG=lakeformation       
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/Permissions -timeout 180m
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/PermissionsBasic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/disappears
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTag
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicyMultiple
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/basic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/database
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/basic
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/database
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTag
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/table
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTable
=== RUN   TestAccLakeFormation_serial/PermissionsTable/basic
=== RUN   TestAccLakeFormation_serial/PermissionsTable/iamAllowed
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect
=== RUN   TestAccLakeFormation_serial/PermissionsTable/selectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTable/implicit
=== RUN   TestAccLakeFormation_serial/PermissionsTable/multipleRoles
=== RUN   TestAccLakeFormation_serial/PermissionsTable/selectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/basic
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly
--- PASS: TestAccLakeFormation_serial (936.97s)
    --- PASS: TestAccLakeFormation_serial/PermissionsBasic (319.30s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/disappears (86.72s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTag (23.90s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicyMultiple (25.02s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/basic (24.82s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataLocation (27.10s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple (32.57s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy (24.82s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/database (26.14s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed (48.21s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (181.32s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (24.20s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (25.78s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (37.27s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (24.89s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (33.17s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (28.49s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (26.92s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTable (256.72s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/basic (25.65s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/iamAllowed (46.69s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect (24.27s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectPlus (25.51s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly (34.04s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus (25.23s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/implicit (24.92s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/multipleRoles (25.45s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectOnly (24.95s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns (179.63s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus (25.48s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/basic (63.43s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit (35.13s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns (26.90s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly (28.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	942.524s
```

**Comment by ewbankkit** [comment]
@Tonkonozhenko Thanks for the contribution :tada: :clap:.

**Comment by Tonkonozhenko** [comment]
@ewbankkit thank you for your PR improvements and for merging it

**Pull request merged**
