### PR TITLE
feat: Add new aws_synthetics_runtime_verison and aws_synthetics_runtime_verisons data sources

### LINKED ISSUE #39165: [New Data Source]: `aws_synthetics_runtime_versions`
### Description

A data source to describe available runtime versions. 

### Requested Resource(s) and/or Data Source(s)

- `aws_synthetics_runtime_versions`

### Potential Terraform Configuration

```terraform
data "aws_synthetics_runtime_versions" "example" {
  # synthetic attribute to filter out items with a deprecation data
  skip_deprecated = true
}
```

### References

- https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_DescribeRuntimeVersions.html

### Would you like to implement a fix?

None

### LINKED ISSUE #39166: [New Data Source]: `aws_synthetics_runtime_version`
### Description

This would be a singular variant of the data source described in #39165. It could potentially allow for filtering to a "latest" version using the `ReleaseDate` field. 

### Requested Resource(s) and/or Data Source(s)

- `aws_synthetics_runtime_version`

### Potential Terraform Configuration

```terraform
data "aws_synthetics_runtime_version" "example" {
  # Required
  prefix = "syn-nodejs-puppeteer" # OR "syn-python-selenium"
  
  # One of
  latest  = true
  version = "9.0"
}
```

### References

- https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_DescribeRuntimeVersions.html

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by acwwat**
### Description

This PR is to add the new `aws_synthetics_runtime_version` and `aws_synthetics_runtime_versions` data sources.

### Relations

Closes #39165
Closes #39166

### References

Referred to [DescribeRuntimeVersions](https://docs.aws.amazon.com/AmazonSynthetics/latest/APIReference/API_DescribeRuntimeVersions.html) for specs.

### Output from Acceptance Testing

```console
$ make testacc TESTS="TestAccSyntheticsRuntimeVersionDataSource_|TestAccSyntheticsRuntimeVersionsDataSource_" PKG=synthetics
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/synthetics/... -v -count 1 -parallel 20 -run='TestAccSyntheticsRuntimeVersionDataSource_|TestAccSyntheticsRuntimeVersionsDataSource_'  -timeout 360m
=== RUN   TestAccSyntheticsRuntimeVersionDataSource_basic
=== PAUSE TestAccSyntheticsRuntimeVersionDataSource_basic
=== RUN   TestAccSyntheticsRuntimeVersionDataSource_deprecatedVersion
=== PAUSE TestAccSyntheticsRuntimeVersionDataSource_deprecatedVersion
=== RUN   TestAccSyntheticsRuntimeVersionsDataSource_basic
=== PAUSE TestAccSyntheticsRuntimeVersionsDataSource_basic
=== RUN   TestAccSyntheticsRuntimeVersionsDataSource_skipDeprecated
=== PAUSE TestAccSyntheticsRuntimeVersionsDataSource_skipDeprecated
=== CONT  TestAccSyntheticsRuntimeVersionDataSource_basic
=== CONT  TestAccSyntheticsRuntimeVersionsDataSource_basic
=== CONT  TestAccSyntheticsRuntimeVersionsDataSource_skipDeprecated
=== CONT  TestAccSyntheticsRuntimeVersionDataSource_deprecatedVersion
--- PASS: TestAccSyntheticsRuntimeVersionDataSource_deprecatedVersion (16.10s)
--- PASS: TestAccSyntheticsRuntimeVersionDataSource_basic (16.12s)
--- PASS: TestAccSyntheticsRuntimeVersionsDataSource_basic (16.20s)
--- PASS: TestAccSyntheticsRuntimeVersionsDataSource_skipDeprecated (19.74s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/synthetics 20.053s

$
```

### CODE REVIEW

**Review by jar-b — COMMENTED** [review]
Hi @acwwat - Thanks for your submission!

As of 2023-10-20 all net-new data sources are required to use Terraform Plugin Framework. More context is available in this pinned issue and the provider contributor guide.

- https://github.com/hashicorp/terraform-provider-aws/issues/32917
- https://hashicorp.github.io/terraform-provider-aws/terraform-plugin-development-packages/#which-plugin-version-should-i-use

Maintainers will convert Plugin-SDK based data sources as part of the review process, but if you'd like to do the conversion in the meantime we would greatly appreciate it!

**Comment by acwwat** [comment]
> Hi @acwwat - Thanks for your submission!
> 
> As of 2023-10-20 all net-new data sources are required to use Terraform Plugin Framework. More context is available in this pinned issue and the provider contributor guide.
> 
> * [Policy Change Notice: Net-new resources/data sources will be required to be based on aws-sdk-go-v2 / terraform-plugin-framework #32917](https://github.com/hashicorp/terraform-provider-aws/issues/32917)
> * https://hashicorp.github.io/terraform-provider-aws/terraform-plugin-development-packages/#which-plugin-version-should-i-use
> 
> Maintainers will convert Plugin-SDK based data sources as part of the review process, but if you'd like to do the conversion in the meantime we would greatly appreciate it!

OK let me give it a go later. I saw that the rest of the synthetics resources are still using the plugin SDK so I kept to that convention initially.

**Comment by acwwat** [comment]
@jar-b I've rewritten the data sources with the Terraform Plugin Framework. Please review, thanks.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=synthetics TESTS=TestAccSyntheticsRuntimeVersion
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/synthetics/... -v -count 1 -parallel 20 -run='TestAccSyntheticsRuntimeVersion'  -timeout 360m

--- PASS: TestAccSyntheticsRuntimeVersionsDataSource_basic (10.21s)
--- PASS: TestAccSyntheticsRuntimeVersionDataSource_deprecatedVersion (10.21s)
--- PASS: TestAccSyntheticsRuntimeVersionDataSource_basic (10.25s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/synthetics 16.489s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @acwwat! 👍

**Comment by jar-b** [comment]
Canary resource acceptance tests after migrating to the runtime version data source:

```console
% make testacc PKG=synthetics TESTS=TestAccSyntheticsCanary_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/synthetics/... -v -count 1 -parallel 20 -run='TestAccSyntheticsCanary_'  -timeout 360m

--- PASS: TestAccSyntheticsCanary_tags (94.55s)
--- PASS: TestAccSyntheticsCanary_runtimeVersion (129.64s)
--- PASS: TestAccSyntheticsCanary_runTracing (144.68s)
--- PASS: TestAccSyntheticsCanary_startCanary (194.92s)
--- PASS: TestAccSyntheticsCanary_run (216.00s)
--- PASS: TestAccSyntheticsCanary_runEnvironmentVariables (219.09s)
--- PASS: TestAccSyntheticsCanary_artifactEncryption (237.15s)
--- PASS: TestAccSyntheticsCanary_disappears (470.10s)
--- PASS: TestAccSyntheticsCanary_s3 (559.86s)
--- PASS: TestAccSyntheticsCanary_StartCanary_codeChanges (586.04s)
--- PASS: TestAccSyntheticsCanary_basic (606.08s)
--- PASS: TestAccSyntheticsCanary_rate (678.13s)
--- PASS: TestAccSyntheticsCanary_vpc (2180.95s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/synthetics 2187.415s
```

**Pull request merged**
