### PR TITLE
F verifiedaccess endpoint

### PR DESCRIPTION
**Pull request by markoskandylis**
### Description

Adds support for VerrifiedAccess Endpoint

### Relations

Relates #29689.

### References

https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_VerifiedAccessEndpoint.html

### Output from Acceptance Testing

```console
make testacc TESTARGS='-run=TestAccEC2VerifiedAccessEndpoint_' PKG=ec2  ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2VerifiedAccessEndpoint_ -timeout 360m
=== RUN   TestAccEC2VerifiedAccessEndpoint_basic
=== PAUSE TestAccEC2VerifiedAccessEndpoint_basic
=== RUN   TestAccEC2VerifiedAccessEndpoint_networkInterface
=== PAUSE TestAccEC2VerifiedAccessEndpoint_networkInterface
=== RUN   TestAccEC2VerifiedAccessEndpoint_tags
=== PAUSE TestAccEC2VerifiedAccessEndpoint_tags
=== RUN   TestAccEC2VerifiedAccessEndpoint_disappears
=== PAUSE TestAccEC2VerifiedAccessEndpoint_disappears
=== CONT  TestAccEC2VerifiedAccessEndpoint_basic
=== CONT  TestAccEC2VerifiedAccessEndpoint_tags
=== CONT  TestAccEC2VerifiedAccessEndpoint_networkInterface
--- PASS: TestAccEC2VerifiedAccessEndpoint_tags (1164.51s)
=== CONT  TestAccEC2VerifiedAccessEndpoint_disappears
--- PASS: TestAccEC2VerifiedAccessEndpoint_networkInterface (1188.87s)
--- PASS: TestAccEC2VerifiedAccessEndpoint_basic (1236.50s)
--- PASS: TestAccEC2VerifiedAccessEndpoint_disappears (1459.27s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	2627.346s

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Acceptance tests so far:

```console
% make testacc TESTARGS='-run=TestAccEC2VerifiedAccessEndpoint_' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2VerifiedAccessEndpoint_ -timeout 360m
=== RUN   TestAccEC2VerifiedAccessEndpoint_basic
=== PAUSE TestAccEC2VerifiedAccessEndpoint_basic
=== RUN   TestAccEC2VerifiedAccessEndpoint_disappears
=== PAUSE TestAccEC2VerifiedAccessEndpoint_disappears
=== CONT  TestAccEC2VerifiedAccessEndpoint_basic
=== CONT  TestAccEC2VerifiedAccessEndpoint_disappears
--- PASS: TestAccEC2VerifiedAccessEndpoint_disappears (1408.01s)
--- PASS: TestAccEC2VerifiedAccessEndpoint_basic (1470.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1484.543s
```

**Comment by markoskandylis** [comment]
make testacc TESTARGS='-run=TestAccEC2VerifiedAccessEndpoint_' PKG=ec2  ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2VerifiedAccessEndpoint_ -timeout 360m
=== RUN   TestAccEC2VerifiedAccessEndpoint_basic
=== PAUSE TestAccEC2VerifiedAccessEndpoint_basic
=== RUN   TestAccEC2VerifiedAccessEndpoint_networkInterface
=== PAUSE TestAccEC2VerifiedAccessEndpoint_networkInterface
=== RUN   TestAccEC2VerifiedAccessEndpoint_tags
=== PAUSE TestAccEC2VerifiedAccessEndpoint_tags
=== RUN   TestAccEC2VerifiedAccessEndpoint_disappears
=== PAUSE TestAccEC2VerifiedAccessEndpoint_disappears
=== CONT  TestAccEC2VerifiedAccessEndpoint_basic
=== CONT  TestAccEC2VerifiedAccessEndpoint_tags
=== CONT  TestAccEC2VerifiedAccessEndpoint_networkInterface
--- PASS: TestAccEC2VerifiedAccessEndpoint_tags (1049.66s)
=== CONT  TestAccEC2VerifiedAccessEndpoint_disappears
--- PASS: TestAccEC2VerifiedAccessEndpoint_networkInterface (1070.57s)
--- PASS: TestAccEC2VerifiedAccessEndpoint_basic (1085.81s)


--- PASS: TestAccEC2VerifiedAccessEndpoint_disappears (1256.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	2310.058s

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccVerifiedAccessEndpoint_' PKG=ec2 ACCTEST_PARALLELISM=2  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVerifiedAccessEndpoint_ -timeout 720m
=== RUN   TestAccVerifiedAccessEndpoint_basic
=== PAUSE TestAccVerifiedAccessEndpoint_basic
=== RUN   TestAccVerifiedAccessEndpoint_networkInterface
=== PAUSE TestAccVerifiedAccessEndpoint_networkInterface
=== RUN   TestAccVerifiedAccessEndpoint_tags
=== PAUSE TestAccVerifiedAccessEndpoint_tags
=== RUN   TestAccVerifiedAccessEndpoint_disappears
=== PAUSE TestAccVerifiedAccessEndpoint_disappears
=== CONT  TestAccVerifiedAccessEndpoint_basic
=== CONT  TestAccVerifiedAccessEndpoint_tags
--- PASS: TestAccVerifiedAccessEndpoint_tags (1143.93s)
=== CONT  TestAccVerifiedAccessEndpoint_networkInterface
--- PASS: TestAccVerifiedAccessEndpoint_basic (1361.01s)
=== CONT  TestAccVerifiedAccessEndpoint_disappears
--- PASS: TestAccVerifiedAccessEndpoint_networkInterface (1059.30s)
--- PASS: TestAccVerifiedAccessEndpoint_disappears (1387.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	2753.739s
```

**Comment by ewbankkit** [comment]
@markoskandylis Thanks for the contribution :tada: :clap:.

**Pull request merged**
