### PR TITLE
Add data source for default scraper configuration

### PR DESCRIPTION
**Pull request by bonclay7**
Amazon Managed service for Prometheus proposes a default, AWS-managed scrape configuration for the managed collector. This simplifies even further Prometheus metrics collection for EKS. This PR proposes a data source and documentation updates to use with the scraper. 

```terraform
data "aws_prometheus_scraper_configuration" "this" {}

resource "aws_prometheus_scraper" "this" {
  ...
  scrape_configuration = data.aws_prometheus_scraper_configuration.this.default
}
```

### Relations
Continuation of https://github.com/hashicorp/terraform-provider-aws/pull/34749/

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccAMPScraperConfigurationDataSource PKG=amp
==> Checking that code complies with gofmt requirements...
go install
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/amp/... -v -count 1 -parallel 20 -run='TestAccAMPScraperConfigurationDataSource'  -timeout 360m
=== RUN   TestAccAMPScraperConfigurationDataSource_basic
=== PAUSE TestAccAMPScraperConfigurationDataSource_basic
=== CONT  TestAccAMPScraperConfigurationDataSource_basic
--- PASS: TestAccAMPScraperConfigurationDataSource_basic (30.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amp	34.371s
...
```

### CODE REVIEW

**Comment by bonclay7** [comment]
Any updates on this one @justinretzolk ?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAMPDefaultScraperConfigurationDataSource_' PKG=amp
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.2 test ./internal/service/amp/... -v -count 1 -parallel 20  -run=TestAccAMPDefaultScraperConfigurationDataSource_ -timeout 360m
2024/10/09 14:32:22 Initializing Terraform AWS Provider...
=== RUN   TestAccAMPDefaultScraperConfigurationDataSource_basic
=== PAUSE TestAccAMPDefaultScraperConfigurationDataSource_basic
=== CONT  TestAccAMPDefaultScraperConfigurationDataSource_basic
--- PASS: TestAccAMPDefaultScraperConfigurationDataSource_basic (8.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amp	13.694s
```

**Comment by ewbankkit** [comment]
@bonclay7 Thanks for the contribution :tada: :clap:.
I renamed the data source to `aws_prometheus_default_scraper_configuration`.

**Comment by ewbankkit** [comment]
```console
% make golangci-lint PKG=amp
make: golangci-lint Checks / 1 of 3...
make: golangci-lint Checks / 2 of 3...
WARN [config_reader] The configuration option `linters.errcheck.ignore` is deprecated, please use `linters.errcheck.exclude-functions`. 
make: golangci-lint Checks / 3 of 3...
```

**Comment by ewbankkit** [comment]
@bonclay7 Thanks for the contribution :tada: :clap:.

**Pull request merged**
