### PR TITLE
r/aws_medialive_channel: documentation fixes.

### PR DESCRIPTION
**Pull request by gbw**
### Description
Removes a duplicate section in the medialive channel documentation.

### Relations
N/A

### References
[SCTE 20 Source Settings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/medialive@v1.35.0/types#Scte20SourceSettings)

### Output from Acceptance Testing
N/A

### CODE REVIEW

**Comment by AdamTylerLynch** [comment]
@gbw are you an AWS employee?

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀

**Comment by gbw** [comment]
> @gbw are you an AWS employee?

I'm not a AWS employee. Thank you for the review.

**Comment by johnsonaj** [comment]
@gbw thank you for the contribution! 🎉

**Pull request merged**
