### PR TITLE
provider: Use Values functions to validate SDK Enums: A

### PR DESCRIPTION
**Pull request by mattburgess**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #14601

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by mattburgess** [comment]
* This resolves all `aws_resource_a*` AWSV001 violations
*  I've not run any acceptance tests yet but can try to do so in the next couple of days
* There's a couple of lintignores in here for what appear to be missing _Values() functions in the upstream AWS SDK. My intent here is to collect them up once all resources are migrated to, so they can all be reported at the same time.
* I've not yet done a full assessment of how many of these introduce any user-visible changes but I did spot a couple on my way through this PR.

**Comment by mattburgess** [comment]
User-visible changes introduced by this PR are:

* r/aws_api_gateway_domain_name: add "PRIVATE" as a supported endpoint type
* r/aws_apigatewayv2_domain_name:  add "EDGE" as a supported endpoint type
* r/aws_apigatewayv2_domain_name: add "TLS_1_0" as a supported security policy
* r/aws_appsync_datasource: add "RELATIONAL_DATABASE" as a supported DataSource type
* r/aws_autoscalingplans_scaling_plan: add "Average", "Minimum", "Maximum", and "SampleCount" as supported metric statistics

And herein we hit the drawbacks mentioned in the PR. I'd appreciate some advice on my options here please:

1. Accept that users will now be able to specify the additional values, but they may well not work (see, for example, #8870 / #9337 for the work required to support `RELATIONAL_DATABASE` as a valid `aws_appsync_datasource` type). As this PR doesn't add documentation for the additional supported values then it may be a brave user who decides to just try it on a whim and therefore they get to keep all the pieces when it breaks? These kind of changes are likely to occur as and when additions are made to enums in the upstream SDK, so from a "we're only hitting now what we'll hit in the future anyway" perspective, this approach may be suitable now.
1. Slightly more user-friendly; simply drop any changes in this PR that introduce new values to the lists accepted by the validator to keep the current behaviour. Adding a lintignore will be good enough for these cases for the time being, and it can be removed in any patch that adds fully tested support for the new values. But, as above, future SDK enum additions will creep in given time anyway so :shrug:

**Comment by juneeighteen** [comment]
@mattburgess Anything I can do to help with this PR? I could really use the "r/aws_appsync_datasource: add "RELATIONAL_DATABASE" as a supported DataSource type" addition.

**Comment by mattburgess** [comment]
> @mattburgess Anything I can do to help with this PR? I could really use the "r/aws_appsync_datasource: add "RELATIONAL_DATABASE" as a supported DataSource type" addition.

You probably want to put your :+1: on #9337 then; as it stands, this PR of mine will only allow you to specify `type = "RELATIONAL_DATABASE"` but you'll need the additional configuration support that #9337 implements to properly set up the datasource.

**Comment by justinretzolk** [comment]
👋 We discussed this out of band with Matt. The team would like to revisit how we deal with enumerated values when we migrate to AWS Go SDK v2. With that in mind, closing this PR.

**Pull request closed without merging**
