### PR TITLE
resource/aws_route53_traffic_policy: new resource

### PR DESCRIPTION
**Pull request by mwieczorek**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #11256 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Resource: aws_route53_traffic_policy
```

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccAWSRoute53TrafficPolicy_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSRoute53TrafficPolicy_basic -timeout 120m
=== RUN   TestAccAWSRoute53TrafficPolicy_basic
=== PAUSE TestAccAWSRoute53TrafficPolicy_basic
=== CONT  TestAccAWSRoute53TrafficPolicy_basic
--- PASS: TestAccAWSRoute53TrafficPolicy_basic (17.51s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       17.574s

...
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by mwieczorek** [comment]
I'd like to ask for feedback from maintainers regarding this PR. 

I fully understand the amount of open PRs is huge to do a full review/merge process. But no feedback for almost 5 months put me in doubt if my contribution even makes sense. 
"Traffic policies" may not be widely used by aws terraform provider users and demand for it is not so high. Maybe the FAQ and Contribution Guidelines could be extended to provide a better explanation of how external contributors PRs are prioritized, if it's just a simple 👍  number, if the roadmap has any impact, etc. Additional guidelines if there's anything that can help to speed up things. I think it's especially important for first-time contributors. 

For me, it's also ok to just put a comment like "because of a high volume of PRs and other priorities from the roadmap we cannot start work on this PR at least until Q2 2021".

Adding some of the maintainers here to hopefully get more visibility: @bflad, @gdavison, @anGie44, @bill-rich

**Comment by selslack** [comment]
@bflad, @gdavison, @anGie44, @bill-rich @mwieczorek how can I help to get this PR merged?

**Comment by ewbankkit** [comment]
Superseded by https://github.com/hashicorp/terraform-provider-aws/pull/23602.
@mwieczorek Thanks for the contribution :tada: :clap:.

**Pull request closed without merging**
