### PR TITLE
#507: aws_db_instance: Add support for in-place identifier update

### LINKED ISSUE #507: changing identifier in RDS (aws_db_instance) will destroy/create the db
_This issue was originally opened by @adrianlop as hashicorp/terraform#11636. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
0.8.5

### Affected Resource(s)
- aws_db_instance

### Expected Behavior
Using AWS RDS UI you can change the identifier and it won't recreate the database, it will only apply it on the preferred maintenance window/apply immediately if you select it.

image

This change also changes the endpoint, so AWS will give you a warn as expected: `Warning! Endpoint will also change`.

### Actual Behavior
Terraform will destroy + recreate the instance. It should only apply the change in the maintenance window or immediately if you selected `apply_immediately=true`, not destroy the DB.

Thanks.

### PR DESCRIPTION
**Pull request by dee-kryvenko**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #507

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES:

- resource /aws_db_instance: **BACKWARD INCOMPATIBLE** now uses `resource_id` as `id` instead of `identifier` - this change allows for in-place updates for `identifier` (previously it would want to re-create the resource as reported in #507).
```

Output from acceptance testing:

```
$ make testacc ACCTEST_PARALLELISM=5 TESTARGS='-run=TestAccAWSDBInstance_identifierUpdate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 5 -run=TestAccAWSDBInstance_identifierUpdate -timeout 120m
=== RUN   TestAccAWSDBInstance_identifierUpdate
=== PAUSE TestAccAWSDBInstance_identifierUpdate
=== CONT  TestAccAWSDBInstance_identifierUpdate
--- PASS: TestAccAWSDBInstance_identifierUpdate (620.57s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       623.500s
```

I did run all the `TestAccAWSDBInstance` tests but I don't have a single output for all of them at once. I had to fix a lot of tests and I were re-running them one-by-one. The single test that is failing is `TestAccAWSDBInstance_S3Import` (due to #13391) and also `TestAccAWSDBInstance_ec2Classic` is skipped since I do not have access to an Classic EC2 enabled account.

### CODE REVIEW

**Comment by dee-kryvenko** [comment]
WIP: Still need to update tests and docs

**Comment by dee-kryvenko** [comment]
Also found an issue, seems it only picking up updates in `address`, `arn` and `endpoint` only in the second apply. Seems like some eventual consistency, will try to fix it tomorrow...

**Comment by dee-kryvenko** [comment]
I'm not sure why `goreleaser` has failed - I do not see a smoking gun in the logs

**Comment by dee-kryvenko** [comment]
Any chance I could celebrate my first contribution to aws provider on Christmas?

**Comment by Kaisbn** [comment]
Hi!
`goreleaser` seems to have timed-out. Maybe the test needs to be re-run?

Any chance this can be merged soon?

**Pull request closed without merging**
