### PR TITLE
[Bug] Fix cost category rule ordering

### LINKED ISSUE #26774: Cost Category rules out of order
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform provider version 4.29

### Affected Resource(s)

* aws_ce_cost_category

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

I've redacted some of the `values` as those are company sensitive. Apart from that, this is the terraform configuration that is being used.

```hcl
resource "aws_ce_cost_category" "cost_center" {
  name         = "Cost Center"
  rule_version = "CostCategoryExpression.v1"

  default_value = "uncategorized"

  rule {
    type  = "REGULAR"
    value = "prod-roles"
    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT"
          values        = [local.production]
          match_options = ["EQUALS"]
        }
      }
      and {
        tags {
          key = "role"
          values = ["..."]
          match_options = ["EQUALS"]
        }
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "rnd-roles"
    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT"
          values        = [local.development]
          match_options = ["EQUALS"]
        }
      }
      and {
        tags {
          key = "role"
          values = ["..." ]
          match_options = ["EQUALS"]
        }
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "rnd-accounts"
    rule {
      dimension {
        key = "LINKED_ACCOUNT"
        values = ["..." ]
        match_options = ["EQUALS"]
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "prod-env"
    rule {
      tags {
        key = "environment"
        values = [
          "production",
          "prod",
        ]
        match_options = ["EQUALS"]
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "rnd-env"
    rule {
      tags {
        key = "environment"
        values = [
          "development",
          "dev",
          "staging",
        ]
        match_options = ["EQUALS"]
      }
    }
  }

}

```

### Expected Behavior

When I define these rules in Terraform, I'm expecting the rules that are defined in order in Terraform to also show up in the same order in the cost category rules editor. 
i.e.
```
1. prod-roles
2. rnd-roles
3. rnd-accounts
4. prod-env
5. rnd-env
```

### Actual Behavior

When the Terraform is applied and the rules are processed in AWS, I'm seeing these rules are out of order. It looks like this in the rules editor

```
1. prod-roles
2. prod-env
3. rnd-roles
4. rnd-accounts
5. rnd-env
```
### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by drewtul**
### Description

Fix cost category rule ordering by changing rules from Set to List in the schema.

Not this might cause a change for users at next plan as the List implies rules being in configuration specified order and set does not. This gives the user control over their rule order, but may change existing applied rule order.

### Relations

Closes #26774

### Output from Acceptance Testing

```console
%  make testacc TESTS=TestAccCECostCategory_ PKG=ce
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/ce/... -v -count 1 -parallel 20 -run='TestAccCECostCategory_'  -timeout 360m
2024/12/11 09:55:35 Initializing Terraform AWS Provider...
=== RUN   TestAccCECostCategory_basic
=== PAUSE TestAccCECostCategory_basic
=== RUN   TestAccCECostCategory_effectiveStart
=== PAUSE TestAccCECostCategory_effectiveStart
=== RUN   TestAccCECostCategory_disappears
=== PAUSE TestAccCECostCategory_disappears
=== RUN   TestAccCECostCategory_complete
=== PAUSE TestAccCECostCategory_complete
=== RUN   TestAccCECostCategory_notWithAnd
=== PAUSE TestAccCECostCategory_notWithAnd
=== RUN   TestAccCECostCategory_splitCharge
=== PAUSE TestAccCECostCategory_splitCharge
=== RUN   TestAccCECostCategory_tags
=== PAUSE TestAccCECostCategory_tags
=== CONT  TestAccCECostCategory_basic
=== CONT  TestAccCECostCategory_notWithAnd
=== CONT  TestAccCECostCategory_tags
=== CONT  TestAccCECostCategory_splitCharge
=== CONT  TestAccCECostCategory_disappears
=== CONT  TestAccCECostCategory_complete
=== CONT  TestAccCECostCategory_effectiveStart
--- PASS: TestAccCECostCategory_disappears (21.67s)
--- PASS: TestAccCECostCategory_notWithAnd (22.34s)
--- PASS: TestAccCECostCategory_basic (22.91s)
--- PASS: TestAccCECostCategory_effectiveStart (33.23s)
--- PASS: TestAccCECostCategory_complete (36.57s)
--- PASS: TestAccCECostCategory_splitCharge (39.45s)
--- PASS: TestAccCECostCategory_tags (45.67s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ce 50.411s

```

### CODE REVIEW

**Review by ewbankkit — COMMENTED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCE' PKG=ce ACCTEST_PARALLELISM=2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/ce/... -v -count 1 -parallel 2  -run=TestAccCE -timeout 360m
2024/12/11 11:00:10 Initializing Terraform AWS Provider...
=== RUN   TestAccCEAnomalyMonitor_basic
=== PAUSE TestAccCEAnomalyMonitor_basic
=== RUN   TestAccCEAnomalyMonitor_disappears
=== PAUSE TestAccCEAnomalyMonitor_disappears
=== RUN   TestAccCEAnomalyMonitor_update
=== PAUSE TestAccCEAnomalyMonitor_update
=== RUN   TestAccCEAnomalyMonitor_tags
=== PAUSE TestAccCEAnomalyMonitor_tags
=== RUN   TestAccCEAnomalyMonitor_Dimensional
=== PAUSE TestAccCEAnomalyMonitor_Dimensional
=== RUN   TestAccCEAnomalySubscription_basic
=== PAUSE TestAccCEAnomalySubscription_basic
=== RUN   TestAccCEAnomalySubscription_disappears
=== PAUSE TestAccCEAnomalySubscription_disappears
=== RUN   TestAccCEAnomalySubscription_Frequency
=== PAUSE TestAccCEAnomalySubscription_Frequency
=== RUN   TestAccCEAnomalySubscription_MonitorARNList
=== PAUSE TestAccCEAnomalySubscription_MonitorARNList
=== RUN   TestAccCEAnomalySubscription_Subscriber
=== PAUSE TestAccCEAnomalySubscription_Subscriber
=== RUN   TestAccCEAnomalySubscription_tags
=== PAUSE TestAccCEAnomalySubscription_tags
=== RUN   TestAccCECostAllocationTag_basic
=== PAUSE TestAccCECostAllocationTag_basic
=== RUN   TestAccCECostAllocationTag_disappears
=== PAUSE TestAccCECostAllocationTag_disappears
=== RUN   TestAccCECostCategoryDataSource_basic
=== PAUSE TestAccCECostCategoryDataSource_basic
=== RUN   TestAccCECostCategory_basic
=== PAUSE TestAccCECostCategory_basic
=== RUN   TestAccCECostCategory_effectiveStart
=== PAUSE TestAccCECostCategory_effectiveStart
=== RUN   TestAccCECostCategory_disappears
=== PAUSE TestAccCECostCategory_disappears
=== RUN   TestAccCECostCategory_complete
=== PAUSE TestAccCECostCategory_complete
=== RUN   TestAccCECostCategory_notWithAnd
=== PAUSE TestAccCECostCategory_notWithAnd
=== RUN   TestAccCECostCategory_splitCharge
=== PAUSE TestAccCECostCategory_splitCharge
=== RUN   TestAccCECostCategory_tags
=== PAUSE TestAccCECostCategory_tags
=== RUN   TestAccCETagsDataSource_basic
=== PAUSE TestAccCETagsDataSource_basic
=== RUN   TestAccCETagsDataSource_filter
=== PAUSE TestAccCETagsDataSource_filter
=== CONT  TestAccCEAnomalyMonitor_basic
=== CONT  TestAccCECostAllocationTag_disappears
--- PASS: TestAccCECostAllocationTag_disappears (10.45s)
=== CONT  TestAccCECostCategory_notWithAnd
--- PASS: TestAccCEAnomalyMonitor_basic (12.16s)
=== CONT  TestAccCETagsDataSource_filter
--- PASS: TestAccCECostCategory_notWithAnd (11.63s)
=== CONT  TestAccCETagsDataSource_basic
--- PASS: TestAccCETagsDataSource_filter (9.94s)
=== CONT  TestAccCECostCategory_tags
--- PASS: TestAccCETagsDataSource_basic (9.70s)
=== CONT  TestAccCECostCategory_splitCharge
--- PASS: TestAccCECostCategory_tags (26.33s)
=== CONT  TestAccCEAnomalySubscription_disappears
--- PASS: TestAccCECostCategory_splitCharge (21.45s)
=== CONT  TestAccCECostAllocationTag_basic
--- PASS: TestAccCEAnomalySubscription_disappears (10.03s)
=== CONT  TestAccCEAnomalySubscription_tags
--- PASS: TestAccCECostAllocationTag_basic (24.37s)
=== CONT  TestAccCEAnomalySubscription_Subscriber
--- PASS: TestAccCEAnomalySubscription_tags (26.31s)
=== CONT  TestAccCEAnomalySubscription_MonitorARNList
--- PASS: TestAccCEAnomalySubscription_MonitorARNList (19.22s)
=== CONT  TestAccCEAnomalySubscription_Frequency
--- PASS: TestAccCEAnomalySubscription_Subscriber (41.25s)
=== CONT  TestAccCEAnomalyMonitor_tags
--- PASS: TestAccCEAnomalySubscription_Frequency (18.92s)
=== CONT  TestAccCEAnomalySubscription_basic
--- PASS: TestAccCEAnomalySubscription_basic (11.77s)
=== CONT  TestAccCEAnomalyMonitor_Dimensional
--- PASS: TestAccCEAnomalyMonitor_tags (24.22s)
=== CONT  TestAccCECostCategory_effectiveStart
--- PASS: TestAccCEAnomalyMonitor_Dimensional (11.21s)
=== CONT  TestAccCECostCategory_complete
--- PASS: TestAccCECostCategory_effectiveStart (19.28s)
=== CONT  TestAccCECostCategory_disappears
--- PASS: TestAccCECostCategory_complete (18.79s)
=== CONT  TestAccCEAnomalyMonitor_update
--- PASS: TestAccCECostCategory_disappears (9.75s)
=== CONT  TestAccCECostCategory_basic
--- PASS: TestAccCEAnomalyMonitor_update (17.20s)
=== CONT  TestAccCEAnomalyMonitor_disappears
--- PASS: TestAccCECostCategory_basic (11.88s)
=== CONT  TestAccCECostCategoryDataSource_basic
--- PASS: TestAccCEAnomalyMonitor_disappears (9.48s)
--- PASS: TestAccCECostCategoryDataSource_basic (9.93s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ce	199.151s
```

**Review by ewbankkit — DISMISSED** [review]

**Review by johnsonaj — DISMISSED** [review]
LGTM 🚀

**Review by johnsonaj — APPROVED** [review]

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@drewtul Thanks for the contribution :tada: :clap:.

**Comment by drewtul** [comment]
@ewbankkit Thanks for review and merge!

**Pull request merged**
