### PR TITLE
New resource: aws_lightsail_instance_public_ports

### LINKED ISSUE #700: aws_lightsail provider should support open port management
_This issue was originally opened by @sean-brandt as hashicorp/terraform#13759. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lightsail

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
What should have happened?

aws_lightsail provider should allow for managing open ports

### PR DESCRIPTION
**Pull request by mavericknsk**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #700
Relates #14905

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws/resource_aws_lightsail_public_ports
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by a14m** [comment]
any updates on this?

**Comment by snoopdouglas** [comment]
Updates please, having all instances stuck only allowing ports 22+80 without external intervention is a royal pain.

**Comment by eskimo220** [comment]
I think this is very useful. I hope to be noticed by more people

**Comment by FreedomBen** [comment]
Will this be merged soon?  I'm currently bound to lightsail, and manually configuring the ports has led to many bugs and broken things.  Would really like to have this merged.  I'm a little disappointed that it's been open for so long.

**Comment by joelradon** [comment]
Please merge :) 

This is a must have to use lightsail with terraform.

**Comment by missinglink** [comment]
I just lost 2 hours debugging SSL errors only to find out that `lightsail` has a hidden firewall tab in the UI 😡 

Screenshot 2020-02-11 at 16 09 15

**Comment by missinglink** [comment]
Also worth noting that right now, any time the instance is recreated it will revert to the default ports of `22` + `80`, so it's not really possible to have SSL termination.

**Comment by missinglink** [comment]
Hi @aeschright, this issue has 41x thumbs-ups and the code looks ready to go?
Could you please let us know what more is required before this can be merged?

**Comment by joelradon** [comment]
> Also worth noting that right now, any time the instance is recreated it will revert to the default ports of `22` + `80`, so it's not really possible to have SSL termination.

Yes we use terraform because of it's automation capabilities. You cannot perform complete automation on lightsail instances unless you are ONLY using port 80. Since even basic websites use 443, we cannot automate certificate portion of our scripts. We must first go into GUI and open up 443. 

It sure doesn't feel like the terraform way ;)

**Comment by missinglink** [comment]
Agreed, I don't think anyone is against merging this, it's just a question of what's left to do.

FYI there is an additional issue to consider when using `letsencrypt`.. if your application is requesting a cert and storing it on disk, the cert file will be lost during a reboot.

This can be resolved by creating a small block store volume and keeping the cert files there across reboots, unfortunately this is also not currently supported by `terraform-provider-aws`.

**Comment by joelradon** [comment]
> Agreed, I don't think anyone is against merging this, it's just a question of what's left to do.
> 
> FYI there is an additional issue to consider when using `letsencrypt`.. if your application is requesting a cert and storing it on disk, the cert file will be lost during a reboot.
> 
> This can be resolved by creating a small [block storage volume](https://aws.amazon.com/lightsail/features/highly-available-storage/) and keeping the cert files there across reboots, unfortunately this is also not currently supported by `terraform-provider-aws`.

Good point on the storage. That could also be handling by backing up the certs to S3 via schedule of weekly, and performing S3 sync on boot.

I do like the way you are handling it better.

**Comment by missinglink** [comment]
For some unknown reason the [Default public network ports open for specific instance images](https://lightsail.aws.amazon.com/ls/docs/en_us/articles/understanding-firewall-and-port-mappings-in-amazon-lightsail) section of the documentation says that 443 is open by default for all `application stacks` but not for `base operating systems`. 🤷‍♂

**Comment by snoopdouglas** [comment]
@missinglink Of course, because who'd want to do any kind of SSL termination *without* running WordPress?

**Comment by missinglink** [comment]
Anyhoo, regardless of the obstacles, I'm available to help out, I have a desire and motivation to improve the Lightsail support within Terraform.

**Comment by missinglink** [comment]
I was able to get this to compile under `go version go1.13.5 darwin/amd64` with the following changes:

```bash
# pull in latest changes from 'terraform-providers/terraform-provider-aws'
git rebase origin/master
```

```diff
diff --git a/aws/resource_aws_lightsail_public_ports.go b/aws/resource_aws_lightsail_public_ports.go
index 752eff78e..7960dad6b 100644
--- a/aws/resource_aws_lightsail_public_ports.go
+++ b/aws/resource_aws_lightsail_public_ports.go
@@ -6,8 +6,8 @@ import (
        "github.com/aws/aws-sdk-go/aws"
        "github.com/aws/aws-sdk-go/aws/awserr"
        "github.com/aws/aws-sdk-go/service/lightsail"
-       "github.com/hashicorp/terraform/helper/schema"
-       "github.com/hashicorp/terraform/helper/validation"
+       "github.com/hashicorp/terraform-plugin-sdk/helper/schema"
+       "github.com/hashicorp/terraform-plugin-sdk/helper/validation"
 )
```

**Comment by missinglink** [comment]
worked perfectly with the following config:

```tpl
resource "aws_lightsail_public_ports" "lightsail_public_ports" {
  instance_name     = "lightsail_instance_name"
  port_infos {
    protocol    = "tcp"
    from_port   = 22
    to_port     = 22
  }
  port_infos {
    protocol    = "tcp"
    from_port   = 80
    to_port     = 80
  }
  port_infos {
    protocol    = "tcp"
    from_port   = 443
    to_port     = 443
  }
}
```

**Comment by missinglink** [comment]
IMO the name `port_info` should be in the singular form `port_info` as per https://www.terraform.io/docs/extend/schemas/schema-types.html#typeset or name it after the aws API and call it `public_port`?

**Comment by missinglink** [comment]
I tried changing the `aws_lightsail_instance.user_data` and doing a `terraform apply`:

```bash
-/+ aws_lightsail_instance.lightsail_instance_cdn (new resource required)
...
\napt-get update -y\napt-get upgrade -y\n" (forces new resource)
      username:               "ubuntu" => <computed>

  + aws_lightsail_public_ports.lightsail_public_ports
      id:                     <computed>
      instance_name:          "lightsail_instance_cdn"
      port_infos.#:           "3"
      port_infos.0.from_port: "22"
      port_infos.0.protocol:  "tcp"
      port_infos.0.to_port:   "22"
      port_infos.1.from_port: "80"
      port_infos.1.protocol:  "tcp"
      port_infos.1.to_port:   "80"
      port_infos.2.from_port: "443"
      port_infos.2.protocol:  "tcp"
      port_infos.2.to_port:   "443"

  + aws_lightsail_static_ip_attachment.lightsail_ip_assignment_cdn
      id:                     <computed>
      instance_name:          "${aws_lightsail_instance.lightsail_instance_cdn.id}"
      ip_address:             <computed>
      static_ip_name:         "lightsail_ip_cdn"


Plan: 3 to add, 0 to change, 1 to destroy.
```

However there seems to be a race condition where maybe the ports are assigned first?
The instance was recreated but the port mapping was still `80/443`

I ran `terraform apply` again and it added the ports correctly on the second execution:

```bash
Terraform will perform the following actions:

  + aws_lightsail_public_ports.lightsail_public_ports
      id:                     <computed>
      instance_name:          "lightsail_instance_cdn"
      port_infos.#:           "3"
      port_infos.0.from_port: "22"
      port_infos.0.protocol:  "tcp"
      port_infos.0.to_port:   "22"
      port_infos.1.from_port: "80"
      port_infos.1.protocol:  "tcp"
      port_infos.1.to_port:   "80"
      port_infos.2.from_port: "443"
      port_infos.2.protocol:  "tcp"
      port_infos.2.to_port:   "443"


Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by missinglink** [comment]
The following script can be used to compile the code for testing https://gist.github.com/missinglink/1cc17e40184ac82203d6dc26373969aa

```bash
# requires golang (Im using go version go1.13.5 darwin/amd64)
./custom_provider_aws.sh
```

This will generate the following file in `.terraform.d`

```bash
-rwxr-xr-x  1 peter  staff   198M Feb 12 16:39 ../.terraform.d/plugins/darwin_amd64/terraform-provider-aws_v9.00.0_x4
```

You can then reference that version from your configs:

```bash
provider "aws" {
  region = "us-east-1"
  version = "~> 9.00"
}
```

see: https://www.terraform.io/docs/extend/writing-custom-providers.html
see: https://www.terraform.io/docs/configuration/providers.html#third-party-plugins

**Comment by missinglink** [comment]
adding a `depends_on` condition to the `aws_lightsail_public_ports` resource seems to resolve the race condition:
```bash
depends_on        = ["aws_lightsail_instance.lightsail_instance_cdn"]
```

this is my first time looking at the terraform internals, any know of there is a way to define that dependency internally within the `provider` code?

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by leacollaboro** [comment]
What's the latest with this? Thanks!

**Comment by alon-sabi-ai** [comment]
Is this going anywhere?

**Comment by YakDriver** [comment]
@mavericknsk  Thank you for this PR! I will be looking at it in the near future. I may need to make some minor changes. Coordinate with me if you intend to push to this branch and make sure to pull any changes I've made. Please note that you will still receive all credit for the PR and your code. Thanks again for your interest!

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

Acceptance tests on commercial (`us-west-2`):
```
--- PASS: TestAccAWSLightsailInstancePublicPorts_multiple (46.45s)
--- PASS: TestAccAWSLightsailInstancePublicPorts_basic (54.95s)
```

Acceptance tests on GovCloud:
```
--- SKIP: TestAccAWSLightsailInstancePublicPorts_basic (1.29s)
--- SKIP: TestAccAWSLightsailInstancePublicPorts_multiple (1.29s)
```

**Pull request merged**
