### PR TITLE
aws_sagemaker_endpoint_configuration: supports inputandoutput

### LINKED ISSUE #37330: [Enhancement]: SageMaker Endpoints: add `InputAndOutput` capture options mode
### Description

For SageMaker endpoints, data capture can be configured to capture the Input, Output OR both as "InputAndOutput".  Currently the provider rejects this option setting for "InputAndOutput" with the error message:

Error: expected data_capture_config.0.capture_options.0.capture_mode to be one of [Input Output], got InputAndOutput

For capture_mode, the aws_sagemaker_endpoint_configuration should accept "Input", "Output" OR "InputAndOutput" as valid values.

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_endpoint_configuration

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_endpoint_configuration" "my_endpoint_configuration" {
  name        = "my_endpoint_configuration"

  production_variants {
    variant_name           = "variant-1"
    model_name             = aws_sagemaker_model.my_model.name
    initial_instance_count = 1
    instance_type          = "ml.t2.medium"
  }
  data_capture_config {
    initial_sampling_percentage = 100
    destination_s3_uri          = "s3://my_bucket/my_path"
    capture_options {
      capture_mode = "InputAndOutput"
    }
    enable_capture = true
  }
  depends_on = [
    aws_sagemaker_model.my_model
  ]
}
```

### References

See SageMaker allowed values for capture mode in endpoint configuration at https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CaptureOption.html#sagemaker-Type-CaptureOption-CaptureMode

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by nikhil-goenka**
### Relations

Closes #37330

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccSageMakerEndpointConfiguration_dataCapture PKG=sagemaker
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerEndpointConfiguration_dataCapture'  -timeout 360m
=== RUN   TestAccSageMakerEndpointConfiguration_dataCapture
=== PAUSE TestAccSageMakerEndpointConfiguration_dataCapture
=== RUN   TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
=== PAUSE TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
=== CONT  TestAccSageMakerEndpointConfiguration_dataCapture
=== CONT  TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture (61.03s)
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput (63.33s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	89.533s

...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
[nikhil-goenka](https://github.com/nikhil-goenka) missing changelog. otherwise LGTM

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMakerEndpointConfiguration_dataCapture' PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.4 test ./internal/service/sagemaker/... -v -count 1 -parallel 20  -run=TestAccSageMakerEndpointConfiguration_dataCapture -timeout 360m
=== RUN   TestAccSageMakerEndpointConfiguration_dataCapture
=== PAUSE TestAccSageMakerEndpointConfiguration_dataCapture
=== RUN   TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
=== PAUSE TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
=== CONT  TestAccSageMakerEndpointConfiguration_dataCapture
=== CONT  TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput (21.87s)
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture (24.77s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	29.256s
```

**Comment by ewbankkit** [comment]
@nikhil-goenka Thanks for the contribution :tada: :clap:.

**Comment by tyegagne** [comment]
For awareness, we are attempting to implement this endpoint configuration:

```
  data_capture_config {
    initial_sampling_percentage = 100
    destination_s3_uri          = "s3://xx/xx/inferences/"
    capture_options {
      capture_mode = "Input"
    }
    enable_capture = true
  }
```

We have successful builds for both capture_mode = 'Input' OR capture_mode = 'Output' however our build attempts with 'InputAndOutput' are generating this error: 

```
Error: creating SageMaker Endpoint: ValidationException: Cannot create endpoint using DeploymentConfig due to unsupported features in the requested endpoint configuration. Please refer documentation for a list of exclusions.

status code: 400, request id: xx
```

**Pull request merged**
