### PR TITLE
resource/aws_cloudhsm2_hsm: Prevent creation of extra HSMs

### LINKED ISSUE #8648: Terraform state gets out of sync with AWS CloudHSM v2 resources, and creates more CloudHSM v2 instances than defined in the code
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version 

Terraform v0.11.8

### Affected Resource(s)

aws_cloudhsm_v2_hsm

### Terraform Configuration Files

```hcl

resource "aws_cloudhsm_v2_cluster" "main" {
  hsm_type   = "hsm1.medium"
  subnet_ids = ["${var.subnet_ids}"]

  tags {
    Name        = "cloudhsm.${var.region}.${var.env}.${var.stack}"
    environment = "${var.env}"
    stack       = "${var.stack}"
  }
}

resource "aws_cloudhsm_v2_hsm" "hsm1" {
  subnet_id  = "${element(var.subnet_ids, 0)}"
  cluster_id = "${aws_cloudhsm_v2_cluster.main.cluster_id}"
}

resource "aws_cloudhsm_v2_hsm" "hsm2" {
  subnet_id  = "${element(var.subnet_ids, 1)}"
  cluster_id = "${aws_cloudhsm_v2_cluster.main.cluster_id}"
}
```

### Expected Behavior

Once two cloudhsm instances are created, subsequent terraform runs don't change anything. More specifically, terraform doesn't create more cloudhsm instances.

### Actual Behavior

Some subsequent runs randomly create a _new_ cloudhsm instance, in addition to existing. This happens randomly from time to time, and we end up with more than two instances. I.e.; terraform state says only two instances are there, while there are more than two in AWS.
 
### Steps to Reproduce

Haven't been able to reproduce yet. From what we've seen, terraform can run for months before it starts showing this weird behavior. Haven't noticed any patterns.

### Important Factoids

This is happening in two AWS accounts

### PR DESCRIPTION
**Pull request by mattburgess**
From https://aws.amazon.com/cloudhsm/faqs/:

> Amazon monitors and maintains the HSM and network for availability and error
> conditions. If an HSM fails or loses network connectivity, the HSM will be
> automatically replaced

When this happens, the replacement HSM joins the cluster with a new HSM ID
but attached to the same ENI ID as the failed HSM. So, track HSM instances
using their ENI ID rather than their HSM ID.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8648

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_cloudhsmv2_hsm: Prevent additional HSMs from being created after the HSM service replaces a faulty HSM [GH-8648]
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by mattburgess** [comment]
Draft PR raised because:

1. I've not run the acceptance tests yet; tomorrow hopefully!
2. I've no idea if https://github.com/terraform-providers/terraform-provider-aws/pull/12435/files#diff-86eb031620ea6d677edc58c55baf9457R93-R99 is the right pattern for handling the fact that the IDs used to track the resources have completed changed

**Comment by fprimex** [comment]
Hi @mattburgess , how is progress on this PR going?

**Comment by mattburgess** [comment]
Apologies for the lack of progress on this PR folks. I'm struggling to find time to do much with it. But what I can say is that I think that at least https://github.com/hashicorp/terraform-provider-aws/pull/12435/files#diff-b66a2150b744c0017e8e529c2901542700367d503c590df4508efa5ed1ddc86cR93-R97 is wrong.

I think what is needed here is a migration function, so that current TF state that tracks HSMs by ID is migrated, instead, to track HSMs by ENI ID. But I haven't delved enough into how TF migration functions work to implement that yet, nor how to adequately unit test it. Hopefully this is enough to let the next person pick up the baton and run with this. I _may_ come back to it at some point but really can't commit to any timescales.

**Comment by bflad** [comment]
Hi @mattburgess 👋  Thank you for submitting this.

Since changing the resource identifier (`id` attribute) and resource import identifier are considered [breaking changes](https://www.terraform.io/docs/extend/best-practices/versioning.html#example-major-number-increments), we have opted to implement this in a backwards compatible manner by matching via either the HSM ID or ENI ID: https://github.com/hashicorp/terraform-provider-aws/pull/18580

Since the fix will be covered with a different approach, I'm going to close this pull request. Please track the other one for further updates and thanks again.

**Pull request closed without merging**
