### PR TITLE
Adding tags to Grafana schema

### LINKED ISSUE #24238: support to add tags
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

aws console is showing tags option to add the tags for the grafana workspace but couldn't add tags using the terraform

Error: Unsupported argument
│ 
│   on AMG/main.tf line 9, in resource "aws_grafana_workspace" "grafana_workspace":
│    9:   tags = merge(
│ 
│ An argument named "tags" is not expected here.

terraform version used v1.1.7
aws provider version 4.9.0

### New or Affected Resource(s)

- aws_grafana_workspace

### PR DESCRIPTION
**Pull request by AndreKapraty**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #24238.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccGrafana_serial PKG=grafana
    --- PASS: TestAccGrafana_serial/Workspace (1018.98s)
        --- PASS: TestAccGrafana_serial/Workspace/notificationDestinations (214.48s)
        --- PASS: TestAccGrafana_serial/Workspace/tags (148.63s)
...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Please follow contribution guide for tagging support:
https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#adding-resource-tagging-support

**Comment by AndreKapraty** [comment]
> https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#adding-resource-tagging-support

Ok, thanks

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccGrafana_serial/DataSource PKG=grafana
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/grafana/... -v -count 1 -parallel 20 -run='TestAccGrafana_serial/DataSource'  -timeout 180m
=== RUN   TestAccGrafana_serial
=== RUN   TestAccGrafana_serial/DataSource
=== RUN   TestAccGrafana_serial/DataSource/basic
--- PASS: TestAccGrafana_serial (151.71s)
    --- PASS: TestAccGrafana_serial/DataSource (151.71s)
        --- PASS: TestAccGrafana_serial/DataSource/basic (151.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	155.846s
% make testacc TESTS=TestAccGrafana_serial/Workspace PKG=grafana
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/grafana/... -v -count 1 -parallel 20 -run='TestAccGrafana_serial/Workspace'  -timeout 180m
=== RUN   TestAccGrafana_serial
=== RUN   TestAccGrafana_serial/Workspace
=== RUN   TestAccGrafana_serial/Workspace/disappears
=== RUN   TestAccGrafana_serial/Workspace/organization
    acctest.go:726: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccGrafana_serial/Workspace/dataSources
=== RUN   TestAccGrafana_serial/Workspace/permissionType
=== RUN   TestAccGrafana_serial/Workspace/notificationDestinations
=== RUN   TestAccGrafana_serial/Workspace/tags        
=== RUN   TestAccGrafana_serial/Workspace/saml
=== RUN   TestAccGrafana_serial/Workspace/sso
    acctest.go:746: skipping tests: AccessDeniedException: User: arn:aws:sts::187416307283:assumed-role/terraform_team1_dev-developer/kewbank@hashicorp.com is not authorized to perform: sso:ListInstances
--- PASS: TestAccGrafana_serial (938.27s)
    --- PASS: TestAccGrafana_serial/Workspace (938.27s)
        --- PASS: TestAccGrafana_serial/Workspace/disappears (138.62s)
        --- SKIP: TestAccGrafana_serial/Workspace/organization (0.35s)
        --- PASS: TestAccGrafana_serial/Workspace/dataSources (149.07s)
        --- PASS: TestAccGrafana_serial/Workspace/permissionType (201.90s)
        --- PASS: TestAccGrafana_serial/Workspace/notificationDestinations (155.87s)
        --- PASS: TestAccGrafana_serial/Workspace/tags (163.90s)
        --- PASS: TestAccGrafana_serial/Workspace/saml (144.99s)
        --- SKIP: TestAccGrafana_serial/Workspace/sso (0.38s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	963.455s
```

**Comment by ewbankkit** [comment]
@AndreKapraty Thanks for the contribution :tada: :clap:.
In general everything was great.
I went ahead and made a few minor changes to get this ready for this week's release.

**Comment by AndreKapraty** [comment]
Thank you @ewbankkit for finishing this PR :)

**Pull request merged**
