### PR TITLE
f/aws_cloudwatch_event_target: Add Capacity Providers

### PR DESCRIPTION
**Pull request by nckslvrmn**
### Description

Adds the capacity_provider_strategy option to the ECS target type for cloudwatch event targets

### Relations

Closes [#21320](https://github.com/hashicorp/terraform-provider-aws/issues/21320)

### Output from Acceptance Testing

```
$ TESTS=TestAccEventsTarget_ecsCapacityProvider PKG=events ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 1 -run='TestAccEventsTarget_ecsCapacityProvider'  -timeout 180m
=== RUN   TestAccEventsTarget_ecsCapacityProvider
=== PAUSE TestAccEventsTarget_ecsCapacityProvider
=== CONT  TestAccEventsTarget_ecsCapacityProvider
--- PASS: TestAccEventsTarget_ecsCapacityProvider (65.14s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/events     65.194s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEventsTarget_' PKG=events ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 3  -run=TestAccEventsTarget_ -timeout 180m
=== RUN   TestAccEventsTarget_basic
=== PAUSE TestAccEventsTarget_basic
=== RUN   TestAccEventsTarget_disappears
=== PAUSE TestAccEventsTarget_disappears
=== RUN   TestAccEventsTarget_eventBusName
=== PAUSE TestAccEventsTarget_eventBusName
=== RUN   TestAccEventsTarget_eventBusARN
=== PAUSE TestAccEventsTarget_eventBusARN
=== RUN   TestAccEventsTarget_generatedTargetID
=== PAUSE TestAccEventsTarget_generatedTargetID
=== RUN   TestAccEventsTarget_RetryPolicy_deadLetter
=== PAUSE TestAccEventsTarget_RetryPolicy_deadLetter
=== RUN   TestAccEventsTarget_full
=== PAUSE TestAccEventsTarget_full
=== RUN   TestAccEventsTarget_ssmDocument
=== PAUSE TestAccEventsTarget_ssmDocument
=== RUN   TestAccEventsTarget_http
=== PAUSE TestAccEventsTarget_http
=== RUN   TestAccEventsTarget_http_params
=== PAUSE TestAccEventsTarget_http_params
=== RUN   TestAccEventsTarget_ecs
=== PAUSE TestAccEventsTarget_ecs
=== RUN   TestAccEventsTarget_redshift
=== PAUSE TestAccEventsTarget_redshift
=== RUN   TestAccEventsTarget_ecsWithoutLaunchType
=== PAUSE TestAccEventsTarget_ecsWithoutLaunchType
=== RUN   TestAccEventsTarget_ecsWithBlankLaunchType
=== PAUSE TestAccEventsTarget_ecsWithBlankLaunchType
=== RUN   TestAccEventsTarget_ecsWithBlankTaskCount
=== PAUSE TestAccEventsTarget_ecsWithBlankTaskCount
=== RUN   TestAccEventsTarget_ecsFull
=== PAUSE TestAccEventsTarget_ecsFull
=== RUN   TestAccEventsTarget_ecsCapacityProvider
=== PAUSE TestAccEventsTarget_ecsCapacityProvider
=== RUN   TestAccEventsTarget_batch
=== PAUSE TestAccEventsTarget_batch
=== RUN   TestAccEventsTarget_kinesis
=== PAUSE TestAccEventsTarget_kinesis
=== RUN   TestAccEventsTarget_sqs
=== PAUSE TestAccEventsTarget_sqs
=== RUN   TestAccEventsTarget_Input_transformer
=== PAUSE TestAccEventsTarget_Input_transformer
=== RUN   TestAccEventsTarget_inputTransformerJSONString
=== PAUSE TestAccEventsTarget_inputTransformerJSONString
=== RUN   TestAccEventsTarget_partnerEventBus
    target_test.go:853: Environment variable EVENT_BRIDGE_PARTNER_EVENT_BUS_NAME is not set
--- SKIP: TestAccEventsTarget_partnerEventBus (0.00s)
=== CONT  TestAccEventsTarget_basic
=== CONT  TestAccEventsTarget_redshift
=== CONT  TestAccEventsTarget_batch
--- PASS: TestAccEventsTarget_basic (40.09s)
=== CONT  TestAccEventsTarget_full
--- PASS: TestAccEventsTarget_full (51.17s)
=== CONT  TestAccEventsTarget_ecs
--- PASS: TestAccEventsTarget_ecs (32.49s)
=== CONT  TestAccEventsTarget_http_params
--- PASS: TestAccEventsTarget_batch (125.43s)
=== CONT  TestAccEventsTarget_http
--- PASS: TestAccEventsTarget_http (28.18s)
=== CONT  TestAccEventsTarget_ssmDocument
--- PASS: TestAccEventsTarget_ssmDocument (19.62s)
=== CONT  TestAccEventsTarget_Input_transformer
--- PASS: TestAccEventsTarget_http_params (80.34s)
=== CONT  TestAccEventsTarget_inputTransformerJSONString
--- PASS: TestAccEventsTarget_Input_transformer (44.47s)
=== CONT  TestAccEventsTarget_ecsWithBlankTaskCount
--- PASS: TestAccEventsTarget_inputTransformerJSONString (39.90s)
=== CONT  TestAccEventsTarget_ecsCapacityProvider
--- PASS: TestAccEventsTarget_ecsWithBlankTaskCount (33.21s)
=== CONT  TestAccEventsTarget_ecsFull
--- PASS: TestAccEventsTarget_redshift (274.96s)
=== CONT  TestAccEventsTarget_eventBusARN
--- PASS: TestAccEventsTarget_ecsFull (31.77s)
=== CONT  TestAccEventsTarget_RetryPolicy_deadLetter
--- PASS: TestAccEventsTarget_eventBusARN (19.59s)
=== CONT  TestAccEventsTarget_generatedTargetID
--- PASS: TestAccEventsTarget_generatedTargetID (20.46s)
=== CONT  TestAccEventsTarget_ecsWithBlankLaunchType
--- PASS: TestAccEventsTarget_ecsCapacityProvider (83.58s)
=== CONT  TestAccEventsTarget_ecsWithoutLaunchType
--- PASS: TestAccEventsTarget_RetryPolicy_deadLetter (55.57s)
=== CONT  TestAccEventsTarget_eventBusName
--- PASS: TestAccEventsTarget_eventBusName (20.08s)
=== CONT  TestAccEventsTarget_disappears
--- PASS: TestAccEventsTarget_disappears (17.47s)
=== CONT  TestAccEventsTarget_sqs
--- PASS: TestAccEventsTarget_sqs (63.71s)
=== CONT  TestAccEventsTarget_kinesis
--- PASS: TestAccEventsTarget_kinesis (58.03s)
--- PASS: TestAccEventsTarget_ecsWithBlankLaunchType (311.48s)
--- PASS: TestAccEventsTarget_ecsWithoutLaunchType (308.47s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/events	640.078s
```

**Comment by ewbankkit** [comment]
@nckslvrmn Thanks for the contribution :tada: :clap:.

**Comment by nckslvrmn** [comment]
Thanks @ewbankkit! I figured it was time to give something back to the tool I use so often. Also it was a nice learning experience. I noticed you pushed some commits, I assume those were to bring the cloudwatch events resources in line with the most recent standards? I did notice some other resources looked different than these.

Also, I think the [first time committer PR comment github action](https://github.com/hashicorp/terraform-provider-aws/actions/runs/3176253634/jobs/5175336598) is broken, as it was failing on every commit I pushed.

**Comment by nckslvrmn** [comment]
https://github.com/actions/first-interaction/issues/101 looks like an upstream issue with that particular action

**Pull request merged**
