### PR TITLE
Add reader_endpoint_address attribute for aws_elasticache_replication_group resource

### LINKED ISSUE #10519: Reader endpoint in aws_elasticache_replication_group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS ElastiCache replication group for Redis has attribute called `ReaderEndpoint`. It has the same structure as `PrimaryEndpoint`.

Terraform aws provider already gives us `primary_endpoint_address` attribute.
Implement a new, similar attribute (`reader_endpoint_address`?) for the reader endpoint.

https://docs.aws.amazon.com/cli/latest/reference/elasticache/describe-replication-groups.html

### New or Affected Resource(s)

* `aws_elasticache_replication_group` resource and datasource

### PR DESCRIPTION
**Pull request by teraken0509**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10519

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
r/aws_elasticache_replication_group: add `reader_endpoint_address` attribute
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSElasticacheReplicationGroup_multiAzInVpc'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSElasticacheReplicationGroup_multiAzInVpc -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSElasticacheReplicationGroup_multiAzInVpc
=== PAUSE TestAccAWSElasticacheReplicationGroup_multiAzInVpc
=== CONT  TestAccAWSElasticacheReplicationGroup_multiAzInVpc
--- PASS: TestAccAWSElasticacheReplicationGroup_multiAzInVpc (1085.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1085.230s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.012s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.036s [no tests to run]
```

```
$ make testacc TESTARGS='-run=TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2 -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2
=== PAUSE TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2
=== CONT  TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2
--- PASS: TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2 (945.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	945.239s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.009s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.128s [no tests to run]
```

### CODE REVIEW

**Comment by kterada0509** [comment]
Re-run acctest.

```
$ make testacc TESTARGS='-run=TestAccAWSElasticacheReplicationGroup_multiAzInVpc'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSElasticacheReplicationGroup_multiAzInVpc -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSElasticacheReplicationGroup_multiAzInVpc
=== PAUSE TestAccAWSElasticacheReplicationGroup_multiAzInVpc
=== CONT  TestAccAWSElasticacheReplicationGroup_multiAzInVpc
--- PASS: TestAccAWSElasticacheReplicationGroup_multiAzInVpc (1074.17s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1074.247s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.010s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.026s [no tests to run]
```

```
$  make testacc TESTARGS='-run=TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2 -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2
=== PAUSE TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2
=== CONT  TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2
--- PASS: TestAccAWSElasticacheReplicationGroup_redisClusterInVpc2 (871.68s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	871.758s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.012s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.024s [no tests to run]
```

**Comment by Alberts00** [comment]
Hey @kterada0509, any chance you could also update documentation to provide information about the existence of the reader_endpoint attribute? See the ["CONTRIBUTING" checklist](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#checklists-for-contribution).

**Comment by kterada0509** [comment]
@Alberts00 
Thanks, I added attribute for docs.

**Comment by gdavison** [comment]
Thanks for the PR, @teraken0509. We've merged #9979, which also supports the data source

**Pull request closed without merging**
