### PR TITLE
r/aws_autoscaling_lifecycle_hook:  Add plan time validation for `aws_autoscaling_lifecycle_hook`

### PR DESCRIPTION
**Pull request by jphuynh**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_autoscaling_lifecycle_hook: Add plan time validation for `aws_autoscaling_lifecycle_hook`
```

Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAutoscalingLifecycleHook_ -timeout 120m
=== RUN   TestAccAWSAutoscalingLifecycleHook_basic
=== PAUSE TestAccAWSAutoscalingLifecycleHook_basic
=== RUN   TestAccAWSAutoscalingLifecycleHook_omitDefaultResult
=== PAUSE TestAccAWSAutoscalingLifecycleHook_omitDefaultResult
=== CONT  TestAccAWSAutoscalingLifecycleHook_basic
=== CONT  TestAccAWSAutoscalingLifecycleHook_omitDefaultResult
--- PASS: TestAccAWSAutoscalingLifecycleHook_basic (208.25s)
--- PASS: TestAccAWSAutoscalingLifecycleHook_omitDefaultResult (208.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	208.295s

...
```

### CODE REVIEW

**Comment by jphuynh** [comment]
Do you think there is a chance this one gets a review @breathingdust ? :)

**Comment by breathingdust** [comment]
Hi @jphuynh! Thanks for the contribution. 🚀  We typically tackle PR's in order of community support (via reactions). That said we often can get smaller PR's like this in our internal gardening days, so hopefully we can get this one in then.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAutoScalingGroup_initialLifecycleHook\|TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_simple\|TestAccAutoScalingLifecycleHook_' PKG=autoscaling ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 2  -run=TestAccAutoScalingGroup_initialLifecycleHook\|TestAccAutoScalingGroup_basic\|TestAccAutoScalingGroup_simple\|TestAccAutoScalingLifecycleHook_ -timeout 360m
=== RUN   TestAccAutoScalingGroup_basic
=== PAUSE TestAccAutoScalingGroup_basic
=== RUN   TestAccAutoScalingGroup_simple
=== PAUSE TestAccAutoScalingGroup_simple
=== RUN   TestAccAutoScalingGroup_initialLifecycleHook
=== PAUSE TestAccAutoScalingGroup_initialLifecycleHook
=== RUN   TestAccAutoScalingLifecycleHook_basic
=== PAUSE TestAccAutoScalingLifecycleHook_basic
=== RUN   TestAccAutoScalingLifecycleHook_disappears
=== PAUSE TestAccAutoScalingLifecycleHook_disappears
=== RUN   TestAccAutoScalingLifecycleHook_omitDefaultResult
=== PAUSE TestAccAutoScalingLifecycleHook_omitDefaultResult
=== CONT  TestAccAutoScalingGroup_basic
=== CONT  TestAccAutoScalingLifecycleHook_basic
--- PASS: TestAccAutoScalingGroup_basic (58.93s)
=== CONT  TestAccAutoScalingGroup_initialLifecycleHook
--- PASS: TestAccAutoScalingLifecycleHook_basic (160.89s)
=== CONT  TestAccAutoScalingLifecycleHook_omitDefaultResult
--- PASS: TestAccAutoScalingLifecycleHook_omitDefaultResult (165.11s)
=== CONT  TestAccAutoScalingLifecycleHook_disappears
--- PASS: TestAccAutoScalingLifecycleHook_disappears (141.03s)
=== CONT  TestAccAutoScalingGroup_simple
--- PASS: TestAccAutoScalingGroup_initialLifecycleHook (493.86s)
--- PASS: TestAccAutoScalingGroup_simple (226.85s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling        699.631s
```

**Comment by ewbankkit** [comment]
@jphuynh Thanks for the contribution :tada: :clap:.

**Pull request merged**
