### PR TITLE
API Gateway basePath import options for OpenAPI

### LINKED ISSUE #4402: AWS integration with Swagger does not seem to consider basePath
### Terraform Version
Terraform v0.11.7

### Affected Resource(s)
- aws_api_gateway_rest_api

### Terraform Configuration Files
```hcl
resource "aws_api_gateway_rest_api" "rest_api" {
  name        = "${local.full_prefix}-ep-cloud-api"
  description = "${local.api_title}"
  body        = "${data.template_file.swagger_template.rendered}"
}
```

```json
...swagger...
 "basePath": "prod",
 "schemes": [
    "https"
  ],
...
```

### Expected Behavior
In the AWS Api Gateway I see:
```
Auth: NONE
ARN: arn:aws:execute-api:region:accountId:apiId/*/POST/my-endpoint
```

But I think I should see:

`ARN: arn:aws:execute-api:region:accountId:apiId/*/POST/prod/my-endpoint`

where the `prod` is read from the Swagger's `basePath`, according to https://swagger.io/docs/specification/2-0/api-host-and-base-path.

### Actual Behavior
What actually happened?

### Steps to Reproduce
Try a `swagger.json` with `basePath` set.

### Important Factoids
There are workarounds I think, still worth signaling.

### PR DESCRIPTION
**Pull request by dooreelko**
Fixes #4402

Changes proposed in this pull request:

* New parameter on `aws_api_gateway_rest_api` resource
* Tests for the 3 modes
* Docs about the parameter

Output from acceptance testing:
*did not run, sorry* Is there a way to run it without actually creating resources? Let's talk :)

```
$ make testacc TESTARGS='-run=TestAccAWSAvailabilityZones'
...
```

### CODE REVIEW

**Comment by djweinheimer** [comment]
@dooreelko,  any movement on this PR?  We could use this fix for importing our OpenAPI docs into API Gateway.

**Comment by dooreelko** [comment]
@djweinheimer i wish to see it merged too. do you think i missed something in the submission? (well, except it diverged and has merge conflicts now).
it's either something's missing in the PR or Hashicorp is too busy with other things...

**Comment by djweinheimer** [comment]
@dooreelko , maybe add @bflad as a reviewer

**Comment by djweinheimer** [comment]
This would be great to have because we are using terraform to provision our API Gateway and have to set the api version in every uri path.

**Comment by dooreelko** [comment]
@djweinheimer, i don't seem to have rights to add @bflad as a reviewer. he did change some tags on the PR, though, I guess it's just a low priority :(

**Comment by hijakebye** [comment]
Desperately need this capability! What's the status on this? doesn't look like it's been merged yet

**Comment by dooreelko** [comment]
I wish I knew how I could speed this up 
¯\_(ツ)_/¯

**Comment by bflad** [comment]
Hi @dooreelko 👋  Thank you for submitting this and apologies for the delayed review. We typically use the number of 👍  reactions to help [prioritize pull requests](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/FAQ.md#how-do-you-decide-what-gets-merged-for-each-release), but we have been shorthanded to follow an alternate path to catch pull requests that have been lingering. The team will be implementing that additional process this year.

In this case, we would prefer to follow the `PutRestApi` API and [CloudFormation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-restapi.html#cfn-apigateway-restapi-parameters) lead of just accepting a map of strings named `parameters`. This leaves it generic should other parameter keys be accepted, such as `ignore=documentation`.

What I'll do in this case is refactor the implementation into functionality, on top of your commits, so you still get contribution credit. 👍

**Pull request merged**
