### PR TITLE
Updates `aws-sdk-go-base` and better documents authentication changes

### LINKED ISSUE #23110: 4.0 - Issue with EC2 Instance Metadata running inside Container
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
v1.1.2

### Affected Resource(s)
The provider itself

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = "us-east-2"

  assume_role {
    role_arn = "<redacted>"
  }
}

```

### Expected Behavior

Terraform should plan and run using the EC2 metadata.

### Actual Behavior

```
| Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, canceled, context deadline exceeded
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on configuration.tf line 11, in provider "aws":
│   11: provider "aws" {
```

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Today when switching to v4.0, we discovered we could no longer run Terraform on EC2 instances that use the AWS Instance Metadata service. Running v4.0 locally works fine. But running the same terraform on an EC2 instance (such as for CICD) results in the error shown above.

Rolling back to 3.74.1 fixes the issue and all works as planned.

The instances in question are running both v1 and v2 of the Instance Metadata service.

### LINKED ISSUE #23116: aws provider v4.0.0 doesn't support ap-northeast-3 region
Dear,

It seems the latest aws provider v4.0.0 doesn't support Osaka region(ap-northeast-3),  I see this error:

```
Initializing provider plugins...
- Using previously-installed hashicorp/aws v4.0.0

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, we recommend adding version constraints in a required_providers block
in your configuration, with the constraint strings suggested below.

* hashicorp/aws: version = "~> 4.0.0"

Terraform has been successfully initialized!
...

Refreshing state...

Error: Invalid AWS Region: ap-northeast-3
...
```

If I pin provider version to v3.74.1, then it works.

Thank you!
Regards,

Lei

### LINKED ISSUE #23131: v4: Authentication not honoring AWS_ACCESS_KEY_ID and AWS_SECRET_ACCESS_KEY
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Provider 4.0.0 does no longer respect the credentials set in the environment (`AWS_ACCESS_KEY_ID`,` AWS_SECRET_ACCESS_KEY`).

I run a number of project on GitLab CI/CD and have used the same approach for years, but today it broke.  I have the secrets stored on group account in environment variables.

When it does not find the credentials in the environment it looks for "profiles" in `~/.aws/credentials` etc. When that fails it tries the meta data service (which I do not have since I do not run on EC2 (I think GitLab runs on GCP)) and hence fails miserably.

My workaround was to put the creds in a file like:
`mkdir -p ~/.aws && echo -e "[profile-name]\naws_access_key_id = $AWS_ACCESS_KEY_ID\naws_secret_access_key = $AWS_SECRET_ACCESS_KEY\n" > ~/.aws/credentials`

And finally carefully clean out these credentials `rm -rf ~/.aws/credentials`

Far from optimal but doing so it works, for me.

FWIW

(From @rexsuecia in this comment: https://github.com/hashicorp/terraform-provider-aws/issues/23110#issuecomment-1036354319)

### References

* #23110

### LINKED ISSUE #23182: Authentication: unable to add custom RootCAs HTTPClient, has no WithTransportOptions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

AWS Provider v4.0

### Terraform Configuration Files

All

### Debug Output

```
Error: error configuring terraform AWS provider: loading configuration: unable to add custom RootCAs HTTPClient, has no WithTransportOptions, *http.Client
```

### Expected Behavior

Provider should work.

### Actual Behavior

Provider does not work at all.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This affects the ISO regions but potentially others as well.

### References

* #20824
* #22804
* hashicorp/aws-sdk-go-base#92
* hashicorp/aws-sdk-go-base#91
* hashicorp/aws-sdk-go-base#88
* hashicorp/aws-sdk-go-base#78

### PR DESCRIPTION
**Pull request by gdavison**
Updates `aws-sdk-go-base` and better documents authentication changes

Closes #23110
Closes #23182
Closes #23116
Closes #23131

Output from acceptance testing:

N/A

### CODE REVIEW

**Comment by ewbankkit** [comment]
Added a CHANGELOG entry for https://github.com/hashicorp/terraform-provider-aws/issues/23116 but we will need additional entries for the other fixes.

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by AlexanderLahutsin** [comment]
`╷
│ Error: error configuring Terraform AWS Provider: no valid credential sources for Terraform AWS Provider found.
│ 
│ Please see https://registry.terraform.io/providers/hashicorp/aws
│ for more information about providing credentials.
│ 
│ Error: no EC2 IMDS role found, operation error ec2imds: GetMetadata, request send failed, Get "http://169.254.169.254/latest/meta-data/iam/security-credentials/": dial tcp 169.254.169.254:80: i/o timeout
│ 
│ 
│   with provider["registry.terraform.io/hashicorp/aws"],
│   on <input-prompt> line 1:
│   (source code not available)
│ 
╵`
Screenshot from 2022-02-17 14-15-41

**Pull request merged**
