### PR TITLE
resource/aws_opensearch_domain: Fixes eventual consistency error when adding role to access policy

### LINKED ISSUE #26433: OpenSearch: ValidationException on the domain `access_policies`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.27.0
```

### Affected Resource(s)

* aws_opensearch_domain

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
provider "aws" {
  region = var.aws_region
}

data "aws_caller_identity" "current" {}

resource "aws_opensearch_domain" "example" {
  domain_name    = "example"
  engine_version = "OpenSearch_1.3"

  cluster_config {
    instance_type = "r4.large.search"
  }

  ebs_options {
    ebs_enabled = true
    volume_size = 50
  }

  access_policies = data.aws_iam_policy_document.opensearch.json

  tags = {
    Domain = var.domain
  }
}

data "aws_iam_policy_document" "opensearch" {
  statement {
    effect = "Allow"
    principals {
      identifiers = [
        "arn:aws:iam::<AWS_ACCOUNT_ID>:role/foo",
      ]
      type = "AWS"
    }
    actions   = ["es:*"]
    resources = ["arn:aws:es:${var.aws_region}:${data.aws_caller_identity.current.account_id}:domain/${var.domain}/*"]
  }
}

variable "aws_region" {
  default = "us-east-1"
}

variable "domain" {
  default = "TestDomain"
}
```

### Debug Output

https://gist.github.com/samuel-phan/3a0e3df647bb8421445441d0e470f878

### Panic Output

None.

### Expected Behavior

The second `terraform apply` should change the OpenSearch domain's policy.

### Actual Behavior

The second `terraform apply` fails.

### Steps to Reproduce

1. `terraform apply`
2. Add a principal in the IAM policy:
    ```hcl
    principals {
      identifiers = [
        "arn:aws:iam::<AWS_ACCOUNT_ID>:role/foo",
        "arn:aws:iam::<AWS_ACCOUNT_ID>:role/bar",
      ]
      type = "AWS"
    }
    ```
3. `terraform apply` fails with this error:
    ```
    aws_opensearch_domain.example: Modifying... [id=arn:aws:es:us-east-1:859573184227:domain/example]
    ╷
    │ Error: ValidationException: 1 validation error detected: Value '{
    │   "Version": "2012-10-17",
    │   "Statement": [
    │     {
    │       "Sid": "",
    │       "Effect": "Allow",
    │       "Action": "es:*",
    │       "Resource": "arn:aws:es:us-east-1:859573184227:domain/TestDomain/*",
    │       "Principal": {
    │         "AWS": [
    │           "arn:aws:iam::864830204113:role/sso/fed.power.user",
    │           "arn:aws:iam::864830204113:role/sso/fed.admin.user"
    │         ]
    │       }
    │     }
    │   ]
    │ }' at 'accessPolicies' failed to satisfy constraint: Member must satisfy regular expression pattern: .*
    │
    │   with aws_opensearch_domain.example,
    │   on main.tf line 7, in resource "aws_opensearch_domain" "example":
    │    7: resource "aws_opensearch_domain" "example" {
    ```

### Important Factoids

None.

### References

None.

### PR DESCRIPTION
**Pull request by gdavison**
### Description

When adding an IAM Role to the OpenSearch Domain's access policy, IAM eventual consistency sometimes leads to an error such as

> Error: updating OpenSearch Domain (...): InvalidTypeException: Error setting policy:

The error message also wraps the policy in `[` and `]`, suggesting that the policy is unexpectedly a single-element array.

### Relations

Closes #26433

### Output from Acceptance Testing

```console
% make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_Policy_

--- PASS: TestAccOpenSearchDomain_Policy_ignoreEquivalent (2133.95s)
--- PASS: TestAccOpenSearchDomain_Policy_addPrincipal (2116.35s)
--- PASS: TestAccOpenSearchDomain_Policy_basic (2080.24s)
```

Note that there are other existing errors for `aws_opensearch_domain`, mostly

> Error: updating OpenSearch Domain (...): ValidationException: A change/update is in progress. Please wait for it to complete before requesting another change.

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=opensearch TESTS=TestAccOpenSearchDomain_Policy_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 20 -run='TestAccOpenSearchDomain_Policy_'  -timeout 360m
=== RUN   TestAccOpenSearchDomain_Policy_basic
=== PAUSE TestAccOpenSearchDomain_Policy_basic
=== RUN   TestAccOpenSearchDomain_Policy_addPrincipal
=== PAUSE TestAccOpenSearchDomain_Policy_addPrincipal
=== RUN   TestAccOpenSearchDomain_Policy_ignoreEquivalent
=== PAUSE TestAccOpenSearchDomain_Policy_ignoreEquivalent
=== CONT  TestAccOpenSearchDomain_Policy_basic
=== CONT  TestAccOpenSearchDomain_Policy_ignoreEquivalent
=== CONT  TestAccOpenSearchDomain_Policy_addPrincipal
--- PASS: TestAccOpenSearchDomain_Policy_basic (2048.81s)
--- PASS: TestAccOpenSearchDomain_Policy_addPrincipal (2085.91s)
--- PASS: TestAccOpenSearchDomain_Policy_ignoreEquivalent (2255.17s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearch 2259.415s
```

**Comment by biswadip37** [comment]
Hello!, when can we expect this pr to be merged ?

We are using 5.37.0 as of now. After merging do we have to use any other version ? if yes can you please share the version.

Thank you :)

**Comment by rmccarthy-ellevation** [comment]
Awesome, thanks for the fix. Are what is the ETA on this being merged and available for public use? Apologizies if this seems pushy. Thanks!

**Comment by gdavison** [comment]
This will be released in v5.42.0, which should be released Thursday, 21 March

**Comment by rmccarthy-ellevation** [comment]
> This will be released in v5.42.0, which should be released Thursday, 21 March

Awesome, thank you!

**Pull request merged**
