### PR TITLE
Add replication time control

### PR DESCRIPTION
**Pull request by rebrowning**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #10974 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
adds replication time control configuration
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSS3Bucket_ReplicationTimeControl'

...
```

EDIT: I've added logic so that you don't have to specify a filter alongside RTC in order to use the v2 api

### CODE REVIEW

**Comment by alexmirkhaydarov** [comment]
Any update on this? I see there is a conflict on this PR, if it's resolved, can it be looked into? Thanks!

**Comment by rebrowning** [comment]
fixed the merge conflicts that existed and updated some other linting issues that were found in the additions.

**Comment by jonjohnston** [comment]
Since this requires changes to replication configuration, should also include the new ability to replicate delete markers.
`"DeleteMarkerReplication": {
                "Status": "Enabled"
            }`

**Comment by jonjohnston** [comment]
What is the holdup on this? This is a feature that has been available for over a year and yet can't use terraform to implement it. Please follow up on this.

**Comment by alexmirkhaydarov** [comment]
@bflad, Could you please have a look at this PR? It would be nice to have this feature added to terraform aws provider. Thanks!

**Comment by manherfo** [comment]
@bflad, Could you please have a look at this PR? It would be useful to have this feature added to terraform aws provider. Thanks!

**Comment by lwoerdeman** [comment]
@bflad, any updates on this? Would be great to have this merged!

**Comment by joeran-lab** [comment]
@bflad, Could you please have a look at this PR? It would be useful to have this feature added to terraform aws provider. Thanks!

**Comment by timoguin** [comment]
Hey @rebrowning, great work on this PR! I can confirm that it works. What do you think about removing the magic handling of the `metrics` and `filter` attributes. I think it may be better to stick closer to the S3 API and instead add notes to the documentation about dependencies between the various settings.

**Comment by Xercoy** [comment]
This would be a great feature to have as part of the AWS provider. Not doing too much replication yet so manually toggling these options isn't too bad, but I can't imagine a scalable solution without this. Thanks for taking the time to work on this @rebrowning and to all reviewers @bflad.

**Comment by jonjohnston** [comment]
What is the hold up on this feature?!?

**Comment by myrabokhari** [comment]
Any updates on this? It would be great to have this feature up as soon as possible. Thanks!

**Comment by TheNomet** [comment]
Hello! Any updates on this? Would be extremely useful to have the PR merged and the functionality available?
And thank you @rebrowning for working on this!

**Comment by ewbankkit** [comment]
This functionality has been implemented via #21176 and released in **v3.64.0** of the Terraform AWS Provider.

**Comment by ewbankkit** [comment]
@rebrowning Thanks for the contribution :tada: :clap:.

**Pull request closed without merging**
