### PR TITLE
New resource: aws_grafana_role_association

### LINKED ISSUE #23665: Manage SSO/SAML users/groups for Amazon Managed Grafana (AMG)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS extended the API for Amazon Managed Grafana (AMG) which allows to configure authentication and authorization. For example, by mapping AWS SSO users and groups to Grafana (see https://docs.aws.amazon.com/grafana/latest/APIReference/API_UpdatePermissions.html).

### New or Affected Resource(s)

* `aws_grafana_user_association`

### PR DESCRIPTION
**Pull request by AlexanderSchiff**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23665

I think there may be a bug in the AWS Grafana SDK. I don't see the role associations being mapped even though I can see the events in cloud trail.

Note that the `user_ids` and `group_ids` must exist in AWS SSO prior to running these tests. There are no terraform resources for AWS SSO users and groups, so I created the test user and test group through the UI. Output from acceptance testing:

```
GOROOT=C:\Program Files\Go #gosetup
GOPATH=C:\Users\alexa\go #gosetup
"C:\Program Files\Go\bin\go.exe" test -c -o C:\Users\alexa\AppData\Local\Temp\GoLand\___9go_test_github_com_hashicorp_terraform_provider_aws_internal_service_grafana.test.exe -gcflags "all=-N -l" github.com/hashicorp/terraform-provider-aws/internal/service/grafana #gosetup
"C:\Program Files\Go\bin\go.exe" tool test2json -t "C:\Program Files\JetBrains\GoLand 2021.3.2\plugins\go\lib\dlv\windows\dlv.exe" --listen=127.0.0.1:63348 --headless=true --api-version=2 --check-go-version=false --only-same-user=false exec C:\Users\alexa\AppData\Local\Temp\GoLand\___9go_test_github_com_hashicorp_terraform_provider_aws_internal_service_grafana.test.exe -- -test.v -test.paniconexit0 #gosetup
API server listening at: 127.0.0.1:63348
=== RUN   TestAccGrafana_serial
--- FAIL: TestAccGrafana_serial (2597.13s)
=== RUN   TestAccGrafana_serial/RoleAssociation
    --- FAIL: TestAccGrafana_serial/RoleAssociation (2597.13s)
=== RUN   TestAccGrafana_serial/RoleAssociation/usersAndGroupsAdmin
    role_association_test.go:142: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_grafana_role_association.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        --- FAIL: TestAccGrafana_serial/RoleAssociation/usersAndGroupsAdmin (595.80s)

=== RUN   TestAccGrafana_serial/RoleAssociation/usersAndGroupsEditor
    role_association_test.go:172: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_grafana_role_association.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        --- FAIL: TestAccGrafana_serial/RoleAssociation/usersAndGroupsEditor (488.56s)

=== RUN   TestAccGrafana_serial/RoleAssociation/usersAdmin
    role_association_test.go:22: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_grafana_role_association.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        --- FAIL: TestAccGrafana_serial/RoleAssociation/usersAdmin (994.90s)

=== RUN   TestAccGrafana_serial/RoleAssociation/usersEditor
    role_association_test.go:52: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_grafana_role_association.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        --- FAIL: TestAccGrafana_serial/RoleAssociation/usersEditor (178.20s)

=== RUN   TestAccGrafana_serial/RoleAssociation/groupsAdmin
    role_association_test.go:82: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_grafana_role_association.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        --- FAIL: TestAccGrafana_serial/RoleAssociation/groupsAdmin (172.31s)

=== RUN   TestAccGrafana_serial/RoleAssociation/groupsEditor
    role_association_test.go:112: Step 1/1 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_grafana_role_association.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: Root resource was present, but now absent.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
        --- FAIL: TestAccGrafana_serial/RoleAssociation/groupsEditor (167.36s)



FAIL


Debugger finished with the exit code 0

```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@AlexanderSchiff Thanks for the contribution :tada: :clap:.
The problem was that the resource ID was not being set: `d.SetId(...)`.
I have fixed that and also replaced the hard-coded user and group IDs in the acceptance tests with values read from environment variables.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% GRAFANA_SSO_USER_ID=... GRAFANA_SSO_GROUP_ID=... make testacc TESTS=TestAccGrafana_serial/RoleAssociation PKG=grafana 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/grafana/... -v -count 1 -parallel 20 -run='TestAccGrafana_serial/RoleAssociation'  -timeout 180m
=== RUN   TestAccGrafana_serial
=== RUN   TestAccGrafana_serial/RoleAssociation
=== RUN   TestAccGrafana_serial/RoleAssociation/usersAdmin
=== RUN   TestAccGrafana_serial/RoleAssociation/usersEditor
=== RUN   TestAccGrafana_serial/RoleAssociation/groupsAdmin
=== RUN   TestAccGrafana_serial/RoleAssociation/groupsEditor
=== RUN   TestAccGrafana_serial/RoleAssociation/usersAndGroupsAdmin
=== RUN   TestAccGrafana_serial/RoleAssociation/usersAndGroupsEditor
--- PASS: TestAccGrafana_serial (883.95s)
    --- PASS: TestAccGrafana_serial/RoleAssociation (883.95s)
        --- PASS: TestAccGrafana_serial/RoleAssociation/usersAdmin (148.55s)
        --- PASS: TestAccGrafana_serial/RoleAssociation/usersEditor (146.57s)
        --- PASS: TestAccGrafana_serial/RoleAssociation/groupsAdmin (149.42s)
        --- PASS: TestAccGrafana_serial/RoleAssociation/groupsEditor (146.47s)
        --- PASS: TestAccGrafana_serial/RoleAssociation/usersAndGroupsAdmin (146.37s)
        --- PASS: TestAccGrafana_serial/RoleAssociation/usersAndGroupsEditor (146.57s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	888.089s
```

**Comment by andreaswittig** [comment]
@AlexanderSchiff @ewbankkit Thanks for the effort you put into this. Highly appreciated! 👍

**Comment by AlexanderSchiff** [comment]
@ewbankkit how did you decide `TypeSet` over `TypeList` for `group_ids` and `user_ids`?

**Comment by ewbankkit** [comment]
Whether or not order is significant (`TypeList`) or not (`TypeSet`).

**Pull request merged**
