### PR TITLE
r/chatbot: Fix SNS topic ARNs ordering in Slack channel configuration

### LINKED ISSUE #39025: [Bug]: aws_chatbot_slack_channel_configuration with more than one SNS topic causes "Error: Provider produced inconsistent result after apply"
### Terraform Core Version

1.9.2

### AWS Provider Version

5.64.0

### Affected Resource(s)

aws_chatbot_slack_channel_configuration

### Expected Behavior

`terraform apply` creates AWS Chatbot Slack Channel configuration with multiple associated SNS topics and completes successfully.

### Actual Behavior

`terraform apply` creates AWS Chatbot Slack Channel configuration with multiple associated SNS topics but then throws errors.

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_chatbot_slack_channel_configuration.NAME, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: .sns_topic_arns[0]: was cty.StringVal("arn:aws:sns:AWSREGION:AWSACCOUNTID:TOPICARN1"), but now
│ cty.StringVal("arn:aws:sns:AWSREGION:AWSACCOUNTID:TOPICARN3").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_chatbot_slack_channel_configuration.NAME, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: .sns_topic_arns[1]: was
│ cty.StringVal("arn:aws:sns:AWSREGION:AWSACCOUNTID:TOPICARN2"), but now
│ cty.StringVal("arn:aws:sns:AWSREGION:AWSACCOUNTID:TOPICNARN1").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
╵
╷
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_chatbot_slack_channel_configuration.NAME, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
│ unexpected new value: .sns_topic_arns[2]: was cty.StringVal("AWSREGION:AWSACCOUNTID:TOPICARN3"), but now
│ cty.StringVal("AWSREGION:AWSACCOUNTID:TOPICARN2").
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

```
resource "aws_chatbot_slack_channel_configuration" "NAME" {
  configuration_name    = "CONFIGNAME-${var.env}"
  iam_role_arn          = aws_iam_role.chatbot_role.arn
  slack_channel_id      = var.slack_channel_id
  slack_team_id         = "SLACKTEAMID"
  guardrail_policy_arns = ["arn:aws:iam::aws:policy/ReadOnlyAccess"]
  sns_topic_arns        = [data.terraform_remote_state.REPO1.outputs.TOPICARN1, data.terraform_remote_state.REPO2.outputs.TOPICARN2, data.terraform_remote_state.REPO3.outputs.TOPICARN3]
  tags                  = local.tags
}
```

### Steps to Reproduce

Create a valid aws_chatbot_slack_channel_configuration resource where sns_topic_arns is a list of more than 1 arns. I have hit this issue by creating a list of 3 arns.

### Debug Output

none

### Panic Output

none

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by max-ts0gt**
### Description
This PR fixes an inconsistency in the aws_chatbot_slack_channel_configuration resource where it unnecessarily triggers plan changes when SNS topics are returned in a different order from the AWS API.

The fix implements sorting of SNS topic ARNs before comparison in the slackChannelConfigurationHasChanges function, ensuring that the order of topics doesn't trigger unnecessary updates.

Before this fix:
Plan would show changes when AWS returns topics in different order:
```
sns_topic_arns = [
    - "arn:aws:sns:us-west-2:123456789012:topic2"
    - "arn:aws:sns:us-west-2:123456789012:topic1"
    - "arn:aws:sns:us-west-2:123456789012:topic1"
    - "arn:aws:sns:us-west-2:123456789012:topic2"
]
```
After this fix:
No changes shown when only order differs:
```
sns_topic_arns = [
    - "arn:aws:sns:us-west-2:123456789012:topic1"
    - "arn:aws:sns:us-west-2:123456789012:topic2"
]
```

Closes #39025
Closes #39870

### CODE REVIEW

**Review by YakDriver — DISMISSED** [review]
LGTM 🥇

**Review by johnsonaj — DISMISSED** [review]
LGTM 🚀

**Comment by johnsonaj** [comment]
@max-ts0gt thank you for the contribution! 🎉 

I changed `sns_topic_arns` from a `List` to `Set`, which effectively ignores the order without needing to sort.

**Comment by i5o** [comment]
Thanks for the change.
@johnsonaj do you think this can be ported to Ms teams channel config too? It has the same issue. I could try copying and pasting this PR but for msteams if that seems doable

**Pull request merged**
