### PR TITLE
r/aws_sesv2_configuration_set_event_destination: new resource

### LINKED ISSUE #17570: Support SES v2 Delivery Delayed notifications
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As of ~June 2020 AWS had support for enabling notifications for messages being delayed in their system waiting on a soft bounce.

https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-ses-can-now-send-notifications-when-the-delivery-of-an-email-is-delayed/

This seems to be a bit special since they have a big note about it .. 

> To add the DELIVERY_DELAY event type to an event destination, you have to use the UpdateConfigurationSetEventDestination operation in the Amazon SES API V2. Currently, you can't add this event type to a configuration set by using the Amazon SES console.

here: https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-add-event-destination-sns.html

It's also not available to be set in the AWS UI.

### New or Affected Resource(s)

* aws_sesv2_event_destination

### Potential Terraform Configuration

```hcl
resource "aws_sesv2_event_destination" "cloudwatch" {
  matching_types         = ["delay"] # of course combined with any other valid value for this field
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/06/amazon-ses-can-now-send-notifications-when-the-delivery-of-an-email-is-delayed/
* https://docs.aws.amazon.com/ses/latest/DeveloperGuide/event-publishing-add-event-destination-sns.html
* https://docs.aws.amazon.com/ses/latest/APIReference-V2/API_EventDestinationDefinition.html#SES-Type-EventDestinationDefinition-MatchingEventTypes

### PR DESCRIPTION
**Pull request by kamilturek**
### Description
This PR introduces the `aws_sesv2_configuration_set_event_destination` resource.

### Relations
Relates #26796.
Closes #17570.

### References
https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html

### Output from Acceptance Testing
```
$ make testacc TESTARGS="-run=TestAccSESV2ConfigurationSetEventDestination_" PKG=sesv2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run=TestAccSESV2ConfigurationSetEventDestination_ -timeout 180m
=== RUN   TestAccSESV2ConfigurationSetEventDestination_basic
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_basic
=== RUN   TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_pinpointDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_pinpointDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_snsDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_snsDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_disappears
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_disappears
=== CONT  TestAccSESV2ConfigurationSetEventDestination_basic
=== CONT  TestAccSESV2ConfigurationSetEventDestination_pinpointDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_basic (33.91s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_disappears
--- PASS: TestAccSESV2ConfigurationSetEventDestination_pinpointDestination (39.75s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_snsDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_disappears (15.79s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_snsDestination (35.82s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination (31.90s)
--- PASS: TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination (484.78s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sesv2      536.477s
```

### CODE REVIEW

**Comment by F21** [comment]
@kamilturek Any possibility this can be finished?

**Comment by kamilturek** [comment]
Hey @F21, I've been short on free time recently but I'll come back and finish it soon 👍

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ make testacc TESTARGS="-run=TestAccSESV2ConfigurationSetEventDestination_" PKG=sesv2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 2  -run=TestAccSESV2ConfigurationSetEventDestination_ -timeout 180m
=== RUN   TestAccSESV2ConfigurationSetEventDestination_basic
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_basic
=== RUN   TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_pinpointDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_pinpointDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_snsDestination
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_snsDestination
=== RUN   TestAccSESV2ConfigurationSetEventDestination_disappears
=== PAUSE TestAccSESV2ConfigurationSetEventDestination_disappears
=== CONT  TestAccSESV2ConfigurationSetEventDestination_basic
=== CONT  TestAccSESV2ConfigurationSetEventDestination_pinpointDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_basic (26.30s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_pinpointDestination (27.54s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_cloudWatchDestination (22.21s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_disappears
--- PASS: TestAccSESV2ConfigurationSetEventDestination_disappears (11.39s)
=== CONT  TestAccSESV2ConfigurationSetEventDestination_snsDestination
--- PASS: TestAccSESV2ConfigurationSetEventDestination_snsDestination (24.09s)
--- PASS: TestAccSESV2ConfigurationSetEventDestination_kinesisFirehoseDestination (268.21s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sesv2      301.046s
```

**Comment by jar-b** [comment]
Thanks for your contribution @kamilturek! 

Really impressive to get all of those destinations implemented together with full test coverage 👍

**Pull request merged**
