### PR TITLE
fix: Add skip_destroy to be present in diff.

### LINKED ISSUE #30353: [Bug]: aws_cloudwatch_log_group invalid value for skip_destroy
### Terraform Core Version

1.3.9,1.4.2

### AWS Provider Version

4.54.0,4.60.0

### Affected Resource(s)

aws_cloudwatch_log_group

### Expected Behavior

The plan/apply should have completed without error

### Actual Behavior

The apply errored following introduction of the attribute `skip_destroy`

### Relevant Error/Panic Output Snippet

```shell
│ aws_cloudwatch_log_group.log_group
    │ to include new values learned so far during apply, provider
    │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
    │ .skip_destroy: was cty.False, but now null.
    │
    │ This is a bug in the provider, which should be reported in the provider's
    │ own issue tracker.
```

### Terraform Configuration Files

resource "aws_cloudwatch_log_group" "yada" {
  name         = "Yada"
  skip_destroy = var.skip
}

variable "skip" {
  type    = bool
  default = false
}

### Steps to Reproduce

We could not reproduce when trying the same configuration on a different stack.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by grahamhar**
### Description

As reported in #30353 on some occasions a plan or apply fails with the following error

```
    │ aws_cloudwatch_log_group.log_group
    │ to include new values learned so far during apply, provider
    │ "registry.terraform.io/hashicorp/aws" produced an invalid new value for
    │ .skip_destroy: was cty.False, but now null.
    │
    │ This is a bug in the provider, which should be reported in the provider's
    │ own issue tracker.
``` 

The fix was inspired by https://github.com/hashicorp/terraform-provider-aws/pull/29812

### Relations

Closes #30353 

### Output from Acceptance Testing

```
 make testacc TESTS="TestAccLogsGroup*" PKG=logs
    ==> Checking that code complies with gofmt requirements...
    TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsGroup*'  -timeout 180m
    === RUN   TestAccLogsGroupDataSource_basic
    === PAUSE TestAccLogsGroupDataSource_basic
    === RUN   TestAccLogsGroup_basic
    === PAUSE TestAccLogsGroup_basic
    === RUN   TestAccLogsGroup_nameGenerate
    === PAUSE TestAccLogsGroup_nameGenerate
    === RUN   TestAccLogsGroup_namePrefix
    === PAUSE TestAccLogsGroup_namePrefix
    === RUN   TestAccLogsGroup_disappears
    === PAUSE TestAccLogsGroup_disappears
    === RUN   TestAccLogsGroup_tags
    === PAUSE TestAccLogsGroup_tags
    === RUN   TestAccLogsGroup_kmsKey
    === PAUSE TestAccLogsGroup_kmsKey
    === RUN   TestAccLogsGroup_retentionPolicy
    === PAUSE TestAccLogsGroup_retentionPolicy
    === RUN   TestAccLogsGroup_multiple
    === PAUSE TestAccLogsGroup_multiple
    === RUN   TestAccLogsGroup_skipDestroy
    === PAUSE TestAccLogsGroup_skipDestroy
    === RUN   TestAccLogsGroup_skipDestroyInconsistentPlan
    === PAUSE TestAccLogsGroup_skipDestroyInconsistentPlan
    === RUN   TestAccLogsGroupsDataSource_basic
    === PAUSE TestAccLogsGroupsDataSource_basic
    === RUN   TestAccLogsGroupsDataSource_noPrefix
    === PAUSE TestAccLogsGroupsDataSource_noPrefix
    === CONT  TestAccLogsGroupDataSource_basic
    === CONT  TestAccLogsGroup_retentionPolicy
    === CONT  TestAccLogsGroup_nameGenerate
    === CONT  TestAccLogsGroup_multiple
    === CONT  TestAccLogsGroup_basic
    === CONT  TestAccLogsGroup_disappears
    === CONT  TestAccLogsGroup_kmsKey
    === CONT  TestAccLogsGroup_skipDestroyInconsistentPlan
    === CONT  TestAccLogsGroupsDataSource_noPrefix
    === CONT  TestAccLogsGroup_namePrefix
    === CONT  TestAccLogsGroup_tags
    === CONT  TestAccLogsGroupsDataSource_basic
    === CONT  TestAccLogsGroup_skipDestroy
    --- PASS: TestAccLogsGroup_disappears (94.05s)
    --- PASS: TestAccLogsGroupsDataSource_basic (96.80s)
    --- PASS: TestAccLogsGroup_multiple (99.32s)
    --- PASS: TestAccLogsGroup_skipDestroy (100.02s)
    --- PASS: TestAccLogsGroupDataSource_basic (100.12s)
    --- PASS: TestAccLogsGroupsDataSource_noPrefix (101.94s)
    --- PASS: TestAccLogsGroup_nameGenerate (119.04s)
    --- PASS: TestAccLogsGroup_namePrefix (119.61s)
    --- PASS: TestAccLogsGroup_basic (120.16s)
    --- PASS: TestAccLogsGroup_skipDestroyInconsistentPlan (138.36s)
    --- PASS: TestAccLogsGroup_retentionPolicy (194.55s)
    --- PASS: TestAccLogsGroup_tags (194.74s)
    --- PASS: TestAccLogsGroup_kmsKey (199.30s)
    PASS
    ok      github.com/hashicorp/terraform-provider-aws/internal/service/logs       202.631s

```

### CODE REVIEW

**Comment by SizZiKe** [comment]
@justinretzolk what's blocking this from being merged? We're being affected by this provider bug.

**Comment by justinretzolk** [comment]
Hey @SizZiKe 👋 Thank you for checking in on this! Unfortunately I can't provide an ETA on when this will be reviewed/merged due to the potential of shifting priorities. We prioritize by count of :+1: reactions and a few other things (more information on our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) if you're interested).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLogsGroup_' PKG=logs ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 2  -run=TestAccLogsGroup_ -timeout 360m
=== RUN   TestAccLogsGroup_basic
=== PAUSE TestAccLogsGroup_basic
=== RUN   TestAccLogsGroup_nameGenerate
=== PAUSE TestAccLogsGroup_nameGenerate
=== RUN   TestAccLogsGroup_namePrefix
=== PAUSE TestAccLogsGroup_namePrefix
=== RUN   TestAccLogsGroup_disappears
=== PAUSE TestAccLogsGroup_disappears
=== RUN   TestAccLogsGroup_tags
=== PAUSE TestAccLogsGroup_tags
=== RUN   TestAccLogsGroup_kmsKey
=== PAUSE TestAccLogsGroup_kmsKey
=== RUN   TestAccLogsGroup_logGroupClass
=== PAUSE TestAccLogsGroup_logGroupClass
=== RUN   TestAccLogsGroup_retentionPolicy
=== PAUSE TestAccLogsGroup_retentionPolicy
=== RUN   TestAccLogsGroup_multiple
=== PAUSE TestAccLogsGroup_multiple
=== RUN   TestAccLogsGroup_skipDestroy
=== PAUSE TestAccLogsGroup_skipDestroy
=== RUN   TestAccLogsGroup_skipDestroyInconsistentPlan
=== PAUSE TestAccLogsGroup_skipDestroyInconsistentPlan
=== CONT  TestAccLogsGroup_basic
=== CONT  TestAccLogsGroup_logGroupClass
--- PASS: TestAccLogsGroup_logGroupClass (16.73s)
=== CONT  TestAccLogsGroup_skipDestroy
--- PASS: TestAccLogsGroup_basic (20.15s)
=== CONT  TestAccLogsGroup_skipDestroyInconsistentPlan
--- PASS: TestAccLogsGroup_skipDestroy (15.15s)
=== CONT  TestAccLogsGroup_disappears
--- PASS: TestAccLogsGroup_skipDestroyInconsistentPlan (25.85s)
=== CONT  TestAccLogsGroup_kmsKey
--- PASS: TestAccLogsGroup_disappears (16.79s)
=== CONT  TestAccLogsGroup_tags
--- PASS: TestAccLogsGroup_tags (42.56s)
=== CONT  TestAccLogsGroup_multiple
--- PASS: TestAccLogsGroup_kmsKey (50.15s)
=== CONT  TestAccLogsGroup_namePrefix
--- PASS: TestAccLogsGroup_multiple (15.53s)
=== CONT  TestAccLogsGroup_retentionPolicy
--- PASS: TestAccLogsGroup_namePrefix (18.59s)
=== CONT  TestAccLogsGroup_nameGenerate
--- PASS: TestAccLogsGroup_nameGenerate (19.00s)
--- PASS: TestAccLogsGroup_retentionPolicy (41.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/logs	153.417s
```

**Comment by ewbankkit** [comment]
@grahamhar Thanks for the contribution :tada: :clap:.

**Pull request merged**
