### PR TITLE
New aws_lb / aws_albs datasource

### LINKED ISSUE #25687: Allow multiple results for aws_lb data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it is possible to fetch only one LB with `aws_lb` data source if multiple matched it will fail with error:
```
Error: Search returned XX results, please revise so only one is returned
```
But in some cases we don't know LB NAME or ARN and we want to get them all and do something with that list. An example is LBs provisioned with k8s they all have similar tags and we might want get ARN for each matched some tag.

### New or Affected Resource(s)

`aws_lb` or new resource `aws_lbs`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by mtt88**
### Description

New `aws_lbs`/`aws_albs` datasource - allows user to query for all load balancers in a region and optionally filter by tags.

### Relations

Closes #25687

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccELBV2LoadBalancersDataSource_basic PKG=elbv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run='TestAccELBV2LoadBalancersDataSource_basic'  -timeout 180m
=== RUN   TestAccELBV2LoadBalancersDataSource_basic
=== PAUSE TestAccELBV2LoadBalancersDataSource_basic
=== CONT  TestAccELBV2LoadBalancersDataSource_basic
--- PASS: TestAccELBV2LoadBalancersDataSource_basic (180.42s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      180.476s

...
```

### CODE REVIEW

**Comment by phzietsman** [comment]
@ewbankkit @justinretzolk could you eye-ball this one, please 🙏

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccELBV2LoadBalancersDataSource_' PKG=elbv2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 3  -run=TestAccELBV2LoadBalancersDataSource_ -timeout 180m
=== RUN   TestAccELBV2LoadBalancersDataSource_basic
=== PAUSE TestAccELBV2LoadBalancersDataSource_basic
=== CONT  TestAccELBV2LoadBalancersDataSource_basic
--- PASS: TestAccELBV2LoadBalancersDataSource_basic (159.28s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	165.041s
% make testacc TESTARGS='-run=TestAccELBV2LoadBalancerDataSource_' PKG=elbv2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 3  -run=TestAccELBV2LoadBalancerDataSource_ -timeout 180m
=== RUN   TestAccELBV2LoadBalancerDataSource_basic
=== PAUSE TestAccELBV2LoadBalancerDataSource_basic
=== RUN   TestAccELBV2LoadBalancerDataSource_outpost
=== PAUSE TestAccELBV2LoadBalancerDataSource_outpost
=== RUN   TestAccELBV2LoadBalancerDataSource_backwardsCompatibility
=== PAUSE TestAccELBV2LoadBalancerDataSource_backwardsCompatibility
=== CONT  TestAccELBV2LoadBalancerDataSource_basic
=== CONT  TestAccELBV2LoadBalancerDataSource_backwardsCompatibility
=== CONT  TestAccELBV2LoadBalancerDataSource_outpost
    acctest.go:1368: skipping since no Outposts found
--- SKIP: TestAccELBV2LoadBalancerDataSource_outpost (0.99s)
--- PASS: TestAccELBV2LoadBalancerDataSource_backwardsCompatibility (171.48s)
--- PASS: TestAccELBV2LoadBalancerDataSource_basic (172.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	178.707s
% make testacc TESTARGS='-run=TestAccELBV2LoadBalancer_ALB_basic\|TestAccELBV2LoadBalancer_NLB_basic\|TestAccELBV2LoadBalancer_disappears' PKG=elbv2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 3  -run=TestAccELBV2LoadBalancer_ALB_basic\|TestAccELBV2LoadBalancer_NLB_basic\|TestAccELBV2LoadBalancer_disappears -timeout 180m
=== RUN   TestAccELBV2LoadBalancer_ALB_basic
=== PAUSE TestAccELBV2LoadBalancer_ALB_basic
=== RUN   TestAccELBV2LoadBalancer_NLB_basic
=== PAUSE TestAccELBV2LoadBalancer_NLB_basic
=== RUN   TestAccELBV2LoadBalancer_disappears
=== PAUSE TestAccELBV2LoadBalancer_disappears
=== CONT  TestAccELBV2LoadBalancer_ALB_basic
=== CONT  TestAccELBV2LoadBalancer_disappears
=== CONT  TestAccELBV2LoadBalancer_NLB_basic
--- PASS: TestAccELBV2LoadBalancer_disappears (147.15s)
--- PASS: TestAccELBV2LoadBalancer_ALB_basic (157.32s)
--- PASS: TestAccELBV2LoadBalancer_NLB_basic (213.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	218.912s
```

**Comment by ewbankkit** [comment]
@mtt88 Thanks for the contribution :tada: :clap:.
In general everything was great. I removed the `aws_albs` alias as we are only keep the `aws_alb_*` resources around for backwards compatibility.

**Comment by mtt88** [comment]
Thanks for reviewing @ewbankkit

**Pull request merged**
