### PR TITLE
Modifications to resolve github CI errors

### LINKED ISSUE #22438: data_source/aws_vpc_ipam_pool acceptance tests are failing in CI due to parallelism
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_vpc_ipam_pool

The data source for IPAM pool searches is failing because it currently returns the first pool it finds that matches its criteria. Due to low availability of `filters`, its finding the incorrect pool from other CI tests and then the DS `arn` does not match the API returned `arn`. 

- [ ] add an implicit reference `ipam_pool_id = aws_vpc_ipam_pool.test.id` [here](https://github.com/hashicorp/terraform-provider-aws/blob/63d5a9c8cf8cc82ca8e88f77b426b40b2e448786/internal/service/ec2/vpc_ipam_pool_data_source_test.go#L69) so the DS finds the specific one we built in CI
- [ ] remove the explicit `depends_on` from the acc test config
- [ ] add an error to the resource if it finds more than 1 pool based on search criteria, [example](https://github.com/hashicorp/terraform-provider-aws/blob/63d5a9c8cf8cc82ca8e88f77b426b40b2e448786/internal/service/ec2/vpc_data_source.go#L174)

This change will make this DS less useful for accounts with more than 1 pool but that is currently due to a limitation with the API

### PR DESCRIPTION
**Pull request by jpalan-amazon**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #22438

2022-01-10T09:32:26-08:00 info layer=debugger launching process with args: [/var/folders/km/mt9r_90d1fv2_rpcb1nxkjb8_kl971/T/__debug_bin1626238921 -test.v -test.run ^TestAccDataSourceVPCIpamPool_basic$]
Type 'dlv help' for list of commands.
2022-01-10T09:32:33-08:00 debug layer=debugger continuing
=== RUN   TestAccDataSourceVPCIpamPool_basic
=== PAUSE TestAccDataSourceVPCIpamPool_basic
=== CONT  TestAccDataSourceVPCIpamPool_basic
--- PASS: TestAccDataSourceVPCIpamPool_basic (59.77s)
PASS
Process 54636 has exited with status 0
Detaching
2022-01-10T09:33:32-08:00 debug layer=debugger detaching
dlv dap (54591) exited with code: 0

```
$ make testacc TESTARGS='-run=func TestAccDataSourceVPCIpamPool_basic' PKG_NAME='./internal/service/ec2'

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@jpalan-amazon Thanks for the contribution :tada: :clap:.
`CHANGELOG.md` should not be modified directly for upcoming releases - our [Contributing Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process) contains instructions on how to add a CHANGELOG entry.

**Comment by jpalan-amazon** [comment]
> @jpalan-amazon Thanks for the contribution 🎉 👏. `CHANGELOG.md` should not be modified directly for upcoming releases - our [Contributing Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process) contains instructions on how to add a CHANGELOG entry.

@ewbankkit Thank you for pointing that out. I moved the changelog notes into `.changelog/` directory.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccDataSourceVPCIpamPool_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccDataSourceVPCIpamPool_' -timeout 180m
=== RUN   TestAccDataSourceVPCIpamPool_basic
=== PAUSE TestAccDataSourceVPCIpamPool_basic
=== CONT  TestAccDataSourceVPCIpamPool_basic
--- PASS: TestAccDataSourceVPCIpamPool_basic (46.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	50.729s
```

**Comment by ewbankkit** [comment]
@jpalan-amazon Thanks for the contribution :tada: :clap:.
I added additional checks so that all attributes are verified and this showed up that some attributes weren't being set at all 😄.
I fixed these and added to the CHANGELOG.

**Comment by jpalan-amazon** [comment]
> @jpalan-amazon Thanks for the contribution 🎉 👏. I added additional checks so that all attributes are verified and this showed up that some attributes weren't being set at all 😄. I fixed these and added to the CHANGELOG.

@ewbankkit Awesome! Thank you for taking care of this, much appreciated.

**Pull request merged**
