### PR TITLE
Add Ubuntu 22.04 to Cloud9 ec2 options

### LINKED ISSUE #33625: [Enhancement]: Add Ubuntu 22.04 as possible image for Cloud9 Environment
### Description

Since a few weeks AWS offers Ubuntu 22.04 LTS as image for Cloud9 Environments next to Amazon Linux 2, but currently only Ubuntu 18.04 is available via the Terraform Provider. 
image

When trying to use Ubuntu 22.04 as image this is the error response:
`| Error: expected image_id to be one of [amazonlinux-1-x86_64 amazonlinux-2-x86_64 ubuntu-18.04-x86_64 resolve:ssm:/aws/service/cloud9/amis/amazonlinux-1-x86_64 resolve:ssm:/aws/service/cloud9/amis/amazonlinux-2-x86_64 resolve:ssm:/aws/service/cloud9/amis/ubuntu-18.04-x86_64], got ubuntu-22.04-x86_64
│ 
│   with aws_cloud9_environment_ec2.this["test"],
│   on main.tf line 39, in resource "aws_cloud9_environment_ec2" "this":
│   39:   image_id        = each.value.image_id`

Despite Ubuntu 18.04 is not available anymore in the AWS console (see Screenshot), it still part of the CLI/API and can be used in Terraform to deploy a Ubuntu 18.04 Environment that can be manually upgraded to 22.04. 

### Affected Resource(s) and/or Data Source(s)

aws_cloud9_environment_ec2

### Potential Terraform Configuration

```terraform
resource "aws_cloud9_environment_ec2" "this" {
  name            = "Cloud9-Ubuntu22.04"
  instance_type   = "t3a.medium"
  connection_type = "CONNECT_SSM"
  image_id        = "ubuntu-22.04-x86_64"
  subnet_id       = "subnet-12345abcdef"
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/cloud9/create-environment-ec2.html 

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by autotune**
> ### Description
> 
> Since a few weeks AWS offers Ubuntu 22.04 LTS as image for Cloud9 Environments next to Amazon Linux 2, but currently only Ubuntu 18.04 is available via the Terraform Provider. image
> 
> When trying to use Ubuntu 22.04 as image this is the error response: `| Error: expected image_id to be one of [amazonlinux-1-x86_64 amazonlinux-2-x86_64 ubuntu-18.04-x86_64 resolve:ssm:/aws/service/cloud9/amis/amazonlinux-1-x86_64 resolve:ssm:/aws/service/cloud9/amis/amazonlinux-2-x86_64 resolve:ssm:/aws/service/cloud9/amis/ubuntu-18.04-x86_64], got ubuntu-22.04-x86_64 │ │ with aws_cloud9_environment_ec2.this["test"], │ on main.tf line 39, in resource "aws_cloud9_environment_ec2" "this": │ 39: image_id = each.value.image_id`
> 
> Despite Ubuntu 18.04 is not available anymore in the AWS console (see Screenshot), it still part of the CLI/API and can be used in Terraform to deploy a Ubuntu 18.04 Environment that can be manually upgraded to 22.04.
> ### Affected Resource(s) and/or Data Source(s)
> 
> aws_cloud9_environment_ec2
> ### Potential Terraform Configuration
> 
> ```terraform
> resource "aws_cloud9_environment_ec2" "this" {
>   name            = "Cloud9-Ubuntu22.04"
>   instance_type   = "t3a.medium"
>   connection_type = "CONNECT_SSM"
>   image_id        = "ubuntu-22.04-x86_64"
>   subnet_id       = "subnet-12345abcdef"
> }
> ```
> 
> ### References
> 
> https://docs.aws.amazon.com/cli/latest/reference/cloud9/create-environment-ec2.html
> ### Would you like to implement a fix?
> 
> YES

### Relations

Closes #33625

### Output from Acceptance Testing
```brianadams@Brians-MacBook-Pro-2 terraform-provider-aws % make testacc TESTS=testAccEnvironmentEC2Config_allFields PKG=cloud9
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloud9/... -v -count 1 -parallel 20 -run='testAccEnvironmentEC2Config_allFields'  -timeout 360m

testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud9

```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloud9EnvironmentEC2_' PKG=cloud9 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloud9/... -v -count 1 -parallel 2  -run=TestAccCloud9EnvironmentEC2_ -timeout 360m
=== RUN   TestAccCloud9EnvironmentEC2_basic
=== PAUSE TestAccCloud9EnvironmentEC2_basic
=== RUN   TestAccCloud9EnvironmentEC2_allFields
=== PAUSE TestAccCloud9EnvironmentEC2_allFields
=== RUN   TestAccCloud9EnvironmentEC2_tags
=== PAUSE TestAccCloud9EnvironmentEC2_tags
=== RUN   TestAccCloud9EnvironmentEC2_disappears
=== PAUSE TestAccCloud9EnvironmentEC2_disappears
=== CONT  TestAccCloud9EnvironmentEC2_basic
=== CONT  TestAccCloud9EnvironmentEC2_tags
--- PASS: TestAccCloud9EnvironmentEC2_basic (171.04s)
=== CONT  TestAccCloud9EnvironmentEC2_allFields
--- PASS: TestAccCloud9EnvironmentEC2_tags (222.34s)
=== CONT  TestAccCloud9EnvironmentEC2_disappears
--- PASS: TestAccCloud9EnvironmentEC2_allFields (175.72s)
--- PASS: TestAccCloud9EnvironmentEC2_disappears (170.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud9	398.831s
```

**Comment by ewbankkit** [comment]
@autotune Thanks for the contribution :tada: :clap:.

**Comment by simon97k** [comment]
Thanks for adding this!

**Comment by autotune** [comment]
@ewbankkit @simon97k Sure thing! Keep an eye out for my 100 days of Terraform contributions challenge, 94 more to go!

**Pull request merged**
