### PR TITLE
resource/aws_ssm_service_setting: Add new resource

### LINKED ISSUE #12816: Need SSM update-service-setting equivalent
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There does not appear to be a way currently of performing the equivalent of an aws ssm update-service-setting CLI command.  This command is used for increasing the throughput of the parameters store (https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html) and changing the default tier of the parameters (https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-default-tier.html)

### New or Affected Resource(s)

* aws_ssm_service_setting ?

### Potential Terraform Configuration

```hcl
resource "aws_ssm_service_setting" {
  id = "<arn for setting>"
  value = "<value>"
}
```

### References

* https://docs.aws.amazon.com/systems-manager/latest/userguide/parameter-store-throughput.html
* https://docs.aws.amazon.com/systems-manager/latest/userguide/ps-default-tier.html

### PR DESCRIPTION
**Pull request by chroju**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12816

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Resource: aws_ssm_service_setting
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSSMServiceSetting_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSSMServiceSetting_basic -timeout 120m
=== RUN   TestAccAWSSSMServiceSetting_basic
=== PAUSE TestAccAWSSSMServiceSetting_basic
=== CONT  TestAccAWSSSMServiceSetting_basic
--- PASS: TestAccAWSSSMServiceSetting_basic (41.04s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       43.005s
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Review by matthewharnett — APPROVED** [review]

**Comment by joebowbeerxealth** [comment]
@ryan-dyer-sp @chroju ETA?

**Comment by joebowbeer** [comment]
@ryan-dyer-sp @chroju ETA?

**Comment by fatbasstard** [comment]
@ryan-dyer-sp @chroju Any chance this will make a release?

**Comment by chroju** [comment]
Sorry, but I have no idea what to do to get this merged. Some GitHub Actions were failed, but this seems to be caused by files other than the ones I added in this PR. Should I just merge the latest `main` branch?

**Comment by fatbasstard** [comment]
@chroju It's under the rader of maintainers now, any chance you could give this PR some TLC??

See https://github.com/hashicorp/terraform-provider-aws/issues/12816#issuecomment-1125201874

**Comment by chroju** [comment]
@fatbasstard Thanks for your comment. I have fixed it.

```
testacc TESTS=TestAccSSMServiceSetting_basic PKG=ssm
Enter MFA code for arn:aws:iam::376585504040:mfa/chroju: 620639
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMServiceSetting_basic'  -timeout 180m
=== RUN   TestAccSSMServiceSetting_basic
=== PAUSE TestAccSSMServiceSetting_basic
=== CONT  TestAccSSMServiceSetting_basic
--- PASS: TestAccSSMServiceSetting_basic (15.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssm	16.950s
```

**Review by YakDriver — APPROVED** [review]
Looks good! Thank you 🎉 

```console
% make testacc TESTS=TestAccSSMServiceSetting_basic PKG=ssm
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ssm/... -v -count 1 -parallel 20 -run='TestAccSSMServiceSetting_basic'  -timeout 180m
--- PASS: TestAccSSMServiceSetting_basic (62.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssm	64.023s
```

**Pull request merged**
