### PR TITLE
New resource/aws_vpc_endpoint_connection_accepter

### LINKED ISSUE #22288: Provide a way to accept VPC Endpoints when the VPC Endpoint Service is managed in a separate account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the `aws_vpc_endpoint` resource has an `auto_accept` option that works when the AWS VPC Endpoint and the AWS VPC Endpoint Service are in the same AWS account. When the AWS VPC Endpoint and AWS VPC Endpoint Service are in different AWS accounts, Terraform does not currently provide a solution to create a VPC Endpoint in a separate account, accept it in the first account, and then make changes to the VPC Endpoint that are only possible after the VPC Endpoint is accepted, like enabling the private DNS name.

The AWS API provides the call `aws ec2 accept-vpc-endpoint-connections` which works regardless of which originating account the VPC Endpoint is from.

### New or Affected Resource(s)

Create new resources:

* `aws_vpc_endpoint_service_connection_acceptance`
* `aws_vpc_endpoint_private_dns`

### Potential Terraform Configuration

```hcl
resource "aws_vpc_endpoint_service" "foo" {
  provider = aws.account_foo
  acceptance_required = true
  network_load_balancer_arns = ["arn:placeholder"]
}

resource "aws_vpc_endpoint" "bar" {
  provider = aws.account_bar
  vpc_id = "placeholder"
  service_name = aws_vpc_endpoint_service.foo.service_name
  vpc_endpoint_type = "Interface"
  security_group_ids = ["placeholder"]
  subnet_ids = ["placeholder"]
}

resource "aws_vpc_endpoint_service_connection_acceptance" "foo" {
  provider = aws.account_foo
  service_id = aws_vpc_endpoint_service.foo.service
  endpoint_id = aws_vpc_endpoint.bar.id
}

resource "aws_vpc_endpoint_private_dns" "bar" {
  provider = aws.account_bar
  acceptance_id = aws_vpc_endpoint_service_connection_acceptance.foo.id
  private_dns_enable = true
}

```

### References
N/A

### PR DESCRIPTION
**Pull request by shedimon**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22288.

### New resource justification

With the current state it is impossible to accept VPC Endpoint Connection request in AWS account, that differs from the AWS Endpoint AWS account. This PR adds the resource, that accepts the connection request.

### Open questions
1. Should `state` be tracked and exported as an attribute? Should we force new resource in case it's changed?
2. I've failed to run the test config with the `alternate` provider, since it failed on missing the security token and session token for the assumed role. I've ran it using the inlined providers with assume_role configs, but removed it and replicated the approach I've discovered in the source code.

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccVpcEndpointServiceAccepter_crossAccount'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccVpcEndpointServiceAccepter_crossAccount -timeout 180m
=== RUN   TestAccVpcEndpointServiceAccepter_crossAccount
--- PASS: TestAccVpcEndpointServiceAccepter_crossAccount (425.90s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	428.578s
```

### CODE REVIEW

**Comment by shedimon** [comment]
Hi @bflad @ewbankkit could you please help me to understand why is this construction is not passing the linting and how do I fix it?
```go
d.Set("state", aws.StringValue(vpceConn.(ec2.VpcEndpointConnection).VpcEndpointState))
```

https://github.com/hashicorp/terraform-provider-aws/pull/19083/files#diff-6dc736a2ad8432267c3a353df153d978047b6b4fb71237aa1f4225abc5df7063R232:
```
 AWSAT005: avoid hardcoded ARN AWS partitions, use aws_partition data source
```

The one with the connection `state` attribute is something I'd like to understand as well. Should state be tracked and exported as an attribute? Should we force new resource in case it's changed? What are the best practices for that?

**Comment by shedimon** [comment]
The issue with the connection `state` seems a bit tricky. You can reject and then accept the connection again. From my perspective if connection was rejected in the UI `connection_accepter` resource should try and re-create itself - accept the connection from the endpoint to the service again. Or it can be destroyed and removed from the config. What is the way to make such changes with the `Computed` attribute?

**Comment by shedimon** [comment]
Hi @bflad @ewbankkit @anGie44 could you please help me to understand why are these constructions are not passing the linting and how do I fix them?

*  `AWS Go SDK pointer conversion function for `d.Set()` value is extraneous`:
```go
d.Set("state", aws.StringValue(vpceConn.(ec2.VpcEndpointConnection).VpcEndpointState))
```
* ` AWSAT005: avoid hardcoded ARN AWS partitions, use aws_partition data source`:
```
allowed_principals = [
    "arn:aws:iam::${data.aws_caller_identity.alternate.account_id}:root",
]
```

**Comment by shedimon** [comment]
The issue with the connection `state` seems a bit tricky. You can reject and then accept the connection again. From my perspective if connection was rejected in the UI `connection_accepter` resource should try and re-create itself - accept the connection from the endpoint to the service again. Or it can be destroyed and removed from the config. What is the way to make such changes with the Computed attribute?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc PKG=ec2 TESTS=TestAccEC2VPCEndpointConnectionAccepter_                     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2VPCEndpointConnectionAccepter_' -timeout 180m
=== RUN   TestAccEC2VPCEndpointConnectionAccepter_crossAccount
--- PASS: TestAccEC2VPCEndpointConnectionAccepter_crossAccount (361.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	365.176s
```

**Comment by ewbankkit** [comment]
@shedimon Thanks for the contribution :tada: :clap:.
In general everything was great.
I refactored to fit into the new per-service package structure and renamed the attributes to match other resources:

* `state` -> `vpc_endpoint_state`
* `endpoint_id` -> `vpc_endpoint_id`
* `service_id` -> `vpc_endpoint_service_id`

**Comment by shedimon** [comment]
Hi @ewbankkit, thanks a lot!

Happy holidays! :)

**Pull request merged**
