### PR TITLE
fix: Fix EKS cluster name regex

### LINKED ISSUE #35843: [Docs]: Incorrect regex on EKS cluster name argument
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_entry#cluster_name

### Description

The regex and the description of "clustername" don't match.  If the description is correct and a 1 character name is allowed, the regex should read:
`^[0-9A-Za-z][A-Za-z0-9\-_]*$`
instead of
`^[0-9A-Za-z][A-Za-z0-9\-_]+$`
It's not immediately obvious which is correct, though I'd guess the description.

Edit: This is repeated everywhere the clustername argument appears.
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_access_policy_association#cluster_name
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eks_cluster#name

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by acwwat**
### Description

This PR is to fix the regex pattern for the EKS cluster name that is included in the documentation for numerous EKS-related resources.

I'd also like to ask the maintainers to see whether it makes sense to just remove the regex from the non-cluster resource docs. Once the EKS cluster is created (and it makes sense to provide the regex there), the name is simply referenced by other resources so I don't think providing the exact format is super useful. Let me know what you think - I can update the PR to remove them if you think it makes sense. Thanks.

### Relations

Closes #35843

### References

Referred to the [API reference](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#AmazonEKS-CreateCluster-request-name) for the cluster name regex.

### Output from Acceptance Testing

```console
$ make testacc TESTS=TestValidClusterName PKG=eks
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestValidClusterName'  -timeout 360m
=== RUN   TestValidClusterName
=== PAUSE TestValidClusterName
=== CONT  TestValidClusterName
--- PASS: TestValidClusterName (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/eks        0.186s

$
```

### CODE REVIEW

**Comment by mattburgess** [comment]
Looks like the [validation function](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/eks/validate.go#L20) is actually incorrect as well.

Feel free to include the following change in this PR @acwwat :

```
diff --git a/internal/service/eks/validate.go b/internal/service/eks/validate.go
index 9195a044cb..3bb4b598c6 100644
--- a/internal/service/eks/validate.go
+++ b/internal/service/eks/validate.go
@@ -17,7 +17,7 @@ func validClusterName(v interface{}, k string) (ws []string, errors []error) {
        }
 
        // https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_RequestSyntax
-       pattern := `^[0-9A-Za-z][0-9A-Za-z_-]+$`
+       pattern := `^[0-9A-Za-z][0-9A-Za-z_-]*$`
        if !regexache.MustCompile(pattern).MatchString(value) {
                errors = append(errors, fmt.Errorf(
                        "%q doesn't comply with restrictions (%q): %q",
diff --git a/internal/service/eks/validate_test.go b/internal/service/eks/validate_test.go
index f6627cc653..777f7aa024 100644
--- a/internal/service/eks/validate_test.go
+++ b/internal/service/eks/validate_test.go
@@ -20,6 +20,10 @@ func TestValidClusterName(t *testing.T) {
                        Value:    "my-valid-eks-cluster_1_dev",
                        ErrCount: 0,
                },
+               {
+                       Value:    "a",
+                       ErrCount: 0,
+               },
                {
                        Value:    `_invalid`,
                        ErrCount: 1,
```

The new test fails on current `main`:

```sh
$ make testacc TESTS=TestValidClusterName PKG=eks
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestValidClusterName'  -timeout 360m
=== RUN   TestValidClusterName
=== PAUSE TestValidClusterName
=== CONT  TestValidClusterName
    validate_test.go:65: Expected the EKS Cluster Name to trigger a validation error: a, expected 0, got 1 errors
--- FAIL: TestValidClusterName (0.00s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/eks	0.362s
FAIL
make: *** [GNUmakefile:359: testacc] Error 1
```

And passes with the regex change applied:

```sh
$ make testacc TESTS=TestValidClusterName PKG=eks
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestValidClusterName'  -timeout 360m
=== RUN   TestValidClusterName
=== PAUSE TestValidClusterName
=== CONT  TestValidClusterName
--- PASS: TestValidClusterName (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	0.330s
```

**Comment by mattburgess** [comment]
Oh, and as to your suggestion about removing the regex from all but the cluster resource docs I'd definitely agree although I'm a mere contributor not a maintainer.

**Comment by acwwat** [comment]
@mattburgess Thanks for catching the regex issue in the code. I've incorporated your suggested changes to the code. I've also decided to just remove the regex from the non-cluster resource docs for cleanliness and ease of maintenance going forward.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@acwwat Thanks for the contribution :tada: :clap:.

**Pull request merged**
