### PR TITLE
aws_cloudwatch_log_group: Allow a three year retention period (1096 days)

### LINKED ISSUE #29423: [Bug]: aws_cloudwatch_log_group resource: Allow 3 year retention
### Terraform Core Version

1.3.8

### AWS Provider Version

4.51.0

### Affected Resource(s)

aws_cloudwatch_log_group

### Expected Behavior

I successfully changed the retention settings in the console to 3 years (1096 days).

I went to do this via Terraform and I am unable to do it.  The documentation says that only the following is allowed for the retention_in_days attribute:

1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 2192, 2557, 2922, 3288, 3653, and 0

I would have expected Terraform to allow the same values as per the console.

### Actual Behavior

I am shown an error:

```
Error: expected retention_in_days to be one of [0 1 3 5 7 14 30 60 90 120 150 180 365 400 545 731 1827 2192 2557 2922 3288 3653], got 1096
│
│   with module.customer_contoso.aws_cloudwatch_log_group.flow_log_group,
│   on customer/flow_logs.tf line 11, in resource "aws_cloudwatch_log_group" "flow_log_group":
│   11:   retention_in_days = var.flow_log_retention_in_days
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```hcl
resource "aws_flow_log" "flow_log" {
  iam_role_arn    = var.flow_log_role_arn
  log_destination = aws_cloudwatch_log_group.flow_log_group.arn
  traffic_type    = "ALL"
  vpc_id          = aws_vpc.main.id
}

resource "aws_cloudwatch_log_group" "flow_log_group" {
  name = "testing-flowlogs"
  retention_in_days = 1096
}
```

### Steps to Reproduce

Created the following resource:

```hcl
resource "aws_cloudwatch_log_group" "flow_log_group" {
  name = "testing-flowlogs"
  retention_in_days = 1096
}
```

...and applied it in Terraform.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by leewilmott**
### Description

This change will allow a three year retention period to be set on the aws_cloudwatch_log_group resource.  Such a retention period is allowed to be set in the console, but not [currently] via Terraform.

### Relations

Closes #29423

### Output from Acceptance Testing

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 20 -run='TestAccLogsGroup_retentionPolicy'  -timeout 180m
=== RUN   TestAccLogsGroup_retentionPolicy
=== PAUSE TestAccLogsGroup_retentionPolicy
=== CONT  TestAccLogsGroup_retentionPolicy
--- PASS: TestAccLogsGroup_retentionPolicy (45.95s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/logs       46.066s
...
```

### CODE REVIEW

**Comment by leewilmott** [comment]
Hi @mattburgess,

This was created to address this: https://github.com/hashicorp/terraform-provider-aws/issues/29423

Many thanks,

Lee

**Review by mattburgess — COMMENTED** [review]
@leewilmott this looks great to me! The only minor issue is that as per https://hashicorp.github.io/terraform-provider-aws/changelog-process/#changelog-format your ChangeLog entry needs to be against the PR number (29426) not the issue number.

**Comment by leewilmott** [comment]
@mattburgess, thank you...I will update that now.  Out of interest, how would I have done this?  I wouldn't have known the PR number until 'after' I created a PR...so, I guess you need to create the PR first and then make a subsequent change to add the ChangeLog data....is that correct?

**Comment by leewilmott** [comment]
@mattburgess, I have now made that change...thank you!  Over to you for review.

**Comment by mattburgess** [comment]
> so, I guess you need to create the PR first and then make a subsequent change to add the ChangeLog data....is that correct?

I believe so... that's certainly what I do anyway.

**Comment by mattburgess** [comment]
> @mattburgess, I have now made that change...thank you! Over to you for review.

Ok. Just to set expectations, I only recently got "Collaborator" status on this project so I'm double checking with the maintainers to make sure I'm reviewing/approving correctly. I'll get back to you as soon as I find out.

**Comment by leewilmott** [comment]
That's fine...and I'm not a professional coder either.  So, I appreciate any guidance and suggestions.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLogsGroup_' PKG=logs ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 3  -run=TestAccLogsGroup_ -timeout 180m
=== RUN   TestAccLogsGroup_basic
=== PAUSE TestAccLogsGroup_basic
=== RUN   TestAccLogsGroup_nameGenerate
=== PAUSE TestAccLogsGroup_nameGenerate
=== RUN   TestAccLogsGroup_namePrefix
=== PAUSE TestAccLogsGroup_namePrefix
=== RUN   TestAccLogsGroup_disappears
=== PAUSE TestAccLogsGroup_disappears
=== RUN   TestAccLogsGroup_tags
=== PAUSE TestAccLogsGroup_tags
=== RUN   TestAccLogsGroup_kmsKey
=== PAUSE TestAccLogsGroup_kmsKey
=== RUN   TestAccLogsGroup_retentionPolicy
=== PAUSE TestAccLogsGroup_retentionPolicy
=== RUN   TestAccLogsGroup_multiple
=== PAUSE TestAccLogsGroup_multiple
=== RUN   TestAccLogsGroup_skipDestroy
=== PAUSE TestAccLogsGroup_skipDestroy
=== CONT  TestAccLogsGroup_basic
=== CONT  TestAccLogsGroup_kmsKey
=== CONT  TestAccLogsGroup_multiple
--- PASS: TestAccLogsGroup_multiple (15.26s)
=== CONT  TestAccLogsGroup_skipDestroy
--- PASS: TestAccLogsGroup_basic (17.79s)
=== CONT  TestAccLogsGroup_retentionPolicy
--- PASS: TestAccLogsGroup_skipDestroy (13.23s)
=== CONT  TestAccLogsGroup_disappears
--- PASS: TestAccLogsGroup_disappears (11.27s)
=== CONT  TestAccLogsGroup_tags
--- PASS: TestAccLogsGroup_kmsKey (48.44s)
=== CONT  TestAccLogsGroup_namePrefix
--- PASS: TestAccLogsGroup_retentionPolicy (41.47s)
=== CONT  TestAccLogsGroup_nameGenerate
--- PASS: TestAccLogsGroup_namePrefix (18.00s)
--- PASS: TestAccLogsGroup_nameGenerate (16.51s)
--- PASS: TestAccLogsGroup_tags (41.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/logs	86.358s
```

**Comment by ewbankkit** [comment]
@leewilmott Thanks for the contribution :tada: :clap:.

**Comment by leewilmott** [comment]
That's great, thank you @ewbankkit!

**Pull request merged**
