### PR TITLE
r/aws_fms_policy: Add new resource for AWS Firewall Manager Policy

### LINKED ISSUE #4058: Feature Request: Support Firewall Manager Policies
Amazon has released a new service, Firewall Manager, which provides centralized configuration of WAF rules across accounts and applications. https://aws.amazon.com/about-aws/whats-new/2018/04/introducing-aws-firewall-manager/

Please vote on this issue by adding a :+1: reaction to the original issue to help prioritize interest. If you're interested in implementing this feature request, please comment below.

Prerequisites:
* aws-sdk-go v1.13.28: #4048
* `meta.(*AWSClient).fmsconn`: #4049

### Terraform Version

terraform 0.10+

### New Resource(s)

- `aws_fms_policy`

### Terraform Configuration Files

```hcl
# Example implementation, may change when developed
resource "aws_fms_policy" "example" {
  exclude_resource_tags = true        # Required
  name                  = "example"   # Required
  remediation_enabled   = true        # Required
  resource_tags         = ["example"] # Optional
  resource_type         = "AWS::ElasticLoadBalancingV2::LoadBalancer" # Required

  security_service_policy_data { # Required
    managed_service_data = "{}"  # Required
    type                 = "WAF" # Required
  }
}
```

### Expected Behavior

Resource creates, updates, and deletes Firewall Manager policies.

### Actual Behavior

New feature.

### References

* https://docs.aws.amazon.com/waf/latest/developerguide/fms-chapter.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/fms/#FMS.PutPolicy

### PR DESCRIPTION
**Pull request by robh007**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #4058 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* New resource: aws_fms_policy
```

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSFmsPolicy_basic'
--- PASS: TestAccAWSFmsPolicy_basic (31.86s)

make testacc TEST=./aws TESTARGS='-run=TestAccAWSFmsPolicy_tags'
--- PASS: TestAccAWSFmsPolicy_tags (49.66s)

...
```

### CODE REVIEW

**Comment by robh007** [comment]
Latest test outputs.

make testacc TEST=./aws TESTARGS='-run=TestAccAWSFmsPolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSFmsPolicy -timeout 120m
=== RUN   TestAccAWSFmsPolicy_importBasic
=== PAUSE TestAccAWSFmsPolicy_importBasic
=== RUN   TestAccAWSFmsPolicy_basic
=== PAUSE TestAccAWSFmsPolicy_basic
=== RUN   TestAccAWSFmsPolicy_tags
=== PAUSE TestAccAWSFmsPolicy_tags
=== CONT  TestAccAWSFmsPolicy_importBasic
=== CONT  TestAccAWSFmsPolicy_tags
=== CONT  TestAccAWSFmsPolicy_basic
--- PASS: TestAccAWSFmsPolicy_basic (29.59s)
--- PASS: TestAccAWSFmsPolicy_importBasic (34.18s)
--- PASS: TestAccAWSFmsPolicy_tags (45.09s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       45.152s

**Comment by ewbankkit** [comment]
As of [AWS SDK v1.27.3](https://github.com/aws/aws-sdk-go/releases/tag/v1.27.3), AWS Firewall Manager policies support [resource tagging](https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_TagResource.html).
Requires:
* https://github.com/terraform-providers/terraform-provider-aws/pull/11501

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Review by bill-rich — APPROVED** [review]
LGTM

**Pull request merged**
