### PR TITLE
r/aws_apigatewayv2_stage: Correctly handle deletion of route_settings

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes: https://github.com/hashicorp/terraform-provider-aws/issues/16094.

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_apigatewayv2_stage: Correctly handle deletion of route_settings
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Stage_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSAPIGatewayV2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== PAUSE TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== RUN   TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_disappears
=== PAUSE TestAccAWSAPIGatewayV2Stage_disappears
=== RUN   TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_Deployment
=== PAUSE TestAccAWSAPIGatewayV2Stage_Deployment
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== RUN   TestAccAWSAPIGatewayV2Stage_StageVariables
=== PAUSE TestAccAWSAPIGatewayV2Stage_StageVariables
=== RUN   TestAccAWSAPIGatewayV2Stage_Tags
=== PAUSE TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_StageVariables
--- PASS: TestAccAWSAPIGatewayV2Stage_basicWebSocket (21.08s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (33.37s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (33.85s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== CONT  TestAccAWSAPIGatewayV2Stage_Deployment
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute (37.98s)
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp (44.02s)
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket (45.42s)
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (24.58s)
=== CONT  TestAccAWSAPIGatewayV2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp (41.40s)
=== CONT  TestAccAWSAPIGatewayV2Stage_disappears
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket (41.28s)
=== CONT  TestAccAWSAPIGatewayV2Stage_autoDeployHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (14.36s)
=== CONT  TestAccAWSAPIGatewayV2Stage_defaultHttpStage
--- PASS: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (58.89s)
=== CONT  TestAccAWSAPIGatewayV2Stage_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_defaultHttpStage (18.91s)
=== CONT  TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
--- PASS: TestAccAWSAPIGatewayV2Stage_autoDeployHttp (32.23s)
--- PASS: TestAccAWSAPIGatewayV2Stage_basicHttp (17.51s)
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (30.47s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	182.621s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
As noticed by @DrFaust92:

```console
$ AWS_DEFAULT_REGION=us-east-2 make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Stage_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSAPIGatewayV2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== PAUSE TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== RUN   TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_disappears
=== PAUSE TestAccAWSAPIGatewayV2Stage_disappears
=== RUN   TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_Deployment
=== PAUSE TestAccAWSAPIGatewayV2Stage_Deployment
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== RUN   TestAccAWSAPIGatewayV2Stage_StageVariables
=== PAUSE TestAccAWSAPIGatewayV2Stage_StageVariables
=== RUN   TestAccAWSAPIGatewayV2Stage_Tags
=== PAUSE TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== CONT  TestAccAWSAPIGatewayV2Stage_Tags
--- PASS: TestAccAWSAPIGatewayV2Stage_basicWebSocket (15.31s)
=== CONT  TestAccAWSAPIGatewayV2Stage_StageVariables
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (24.57s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp (33.09s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (22.54s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
    resource_aws_apigatewayv2_stage_test.go:618: Step 1/4 error: Error running apply: 2020/11/11 10:44:02 [DEBUG] Using modified User-Agent: Terraform/0.12.26 HashiCorp-terraform-exec/0.10.0
        
        Error: error creating API Gateway v2 stage: BadRequestException: CloudWatch Logs role ARN must be set in account settings to enable logging
        
        
--- FAIL: TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket (5.73s)
=== CONT  TestAccAWSAPIGatewayV2Stage_Deployment
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute (25.92s)
=== CONT  TestAccAWSAPIGatewayV2Stage_disappears
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (15.74s)
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (10.40s)
=== CONT  TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
    resource_aws_apigatewayv2_stage_test.go:392: Step 1/4 error: Error running apply: 2020/11/11 10:44:23 [DEBUG] Using modified User-Agent: Terraform/0.12.26 HashiCorp-terraform-exec/0.10.0
        
        Error: error creating API Gateway v2 stage: BadRequestException: CloudWatch Logs role ARN must be set in account settings to enable logging
        
        
--- FAIL: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket (5.34s)
=== CONT  TestAccAWSAPIGatewayV2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp (31.77s)
=== CONT  TestAccAWSAPIGatewayV2Stage_defaultHttpStage
--- PASS: TestAccAWSAPIGatewayV2Stage_defaultHttpStage (12.66s)
=== CONT  TestAccAWSAPIGatewayV2Stage_autoDeployHttp
2020/11/11 10:44:41 [DEBUG] Trying to get account information via sts:GetCallerIdentity
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (20.55s)
=== CONT  TestAccAWSAPIGatewayV2Stage_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_basicHttp (11.51s)
--- PASS: TestAccAWSAPIGatewayV2Stage_autoDeployHttp (19.62s)
--- PASS: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (43.39s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	108.152s
FAIL
GNUmakefile:27: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
Running in a region where a CloudWatch role ARN has not been configured:

```console
$ AWS_DEFAULT_REGION=eu-west-1 make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Stage_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSAPIGatewayV2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== PAUSE TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== RUN   TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_disappears
=== PAUSE TestAccAWSAPIGatewayV2Stage_disappears
=== RUN   TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_Deployment
=== PAUSE TestAccAWSAPIGatewayV2Stage_Deployment
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== RUN   TestAccAWSAPIGatewayV2Stage_StageVariables
=== PAUSE TestAccAWSAPIGatewayV2Stage_StageVariables
=== RUN   TestAccAWSAPIGatewayV2Stage_Tags
=== PAUSE TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== CONT  TestAccAWSAPIGatewayV2Stage_Tags
--- PASS: TestAccAWSAPIGatewayV2Stage_basicWebSocket (22.85s)
=== CONT  TestAccAWSAPIGatewayV2Stage_StageVariables
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (35.51s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp (48.84s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (33.11s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
    resource_aws_api_gateway_account_test.go:133: skipping tests; no API Gateway CloudWatch role ARN has been configured in this region
--- SKIP: TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket (1.03s)
=== CONT  TestAccAWSAPIGatewayV2Stage_Deployment
=== CONT  TestAccAWSAPIGatewayV2Stage_disappears
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute (40.86s)
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (26.13s)
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
    resource_aws_api_gateway_account_test.go:133: skipping tests; no API Gateway CloudWatch role ARN has been configured in this region
--- SKIP: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket (1.01s)
=== CONT  TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (15.32s)
=== CONT  TestAccAWSAPIGatewayV2Stage_AccessLogSettings
    resource_aws_api_gateway_account_test.go:133: skipping tests; no API Gateway CloudWatch role ARN has been configured in this region
--- SKIP: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (1.00s)
=== CONT  TestAccAWSAPIGatewayV2Stage_defaultHttpStage
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp (46.55s)
=== CONT  TestAccAWSAPIGatewayV2Stage_autoDeployHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_defaultHttpStage (18.87s)
=== CONT  TestAccAWSAPIGatewayV2Stage_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (32.75s)
--- PASS: TestAccAWSAPIGatewayV2Stage_basicHttp (18.81s)
--- PASS: TestAccAWSAPIGatewayV2Stage_autoDeployHttp (36.43s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	131.885s
```

**Review by DrFaust92 — APPROVED** [review]
LGTM

```
--- PASS: TestAccAWSAPIGatewayV2Stage_basicWebSocket (62.23s)
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (81.54s)
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp (120.29s)
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket (109.09s)
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (56.79s)
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket (112.54s)
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (35.07s)
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (78.12s)
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp (110.24s)
--- PASS: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (86.10s)
--- PASS: TestAccAWSAPIGatewayV2Stage_defaultHttpStage (54.51s)
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (82.48s)
--- PASS: TestAccAWSAPIGatewayV2Stage_autoDeployHttp (85.65s)
--- PASS: TestAccAWSAPIGatewayV2Stage_basicHttp (45.70s)
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute (95.98s)
```

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @ewbankkit for the contribution!

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Stage_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSAPIGatewayV2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== PAUSE TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== RUN   TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_disappears
=== PAUSE TestAccAWSAPIGatewayV2Stage_disappears
=== RUN   TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_Deployment
=== PAUSE TestAccAWSAPIGatewayV2Stage_Deployment
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== RUN   TestAccAWSAPIGatewayV2Stage_StageVariables
=== PAUSE TestAccAWSAPIGatewayV2Stage_StageVariables
=== RUN   TestAccAWSAPIGatewayV2Stage_Tags
=== PAUSE TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
--- PASS: TestAccAWSAPIGatewayV2Stage_basicWebSocket (18.12s)
=== CONT  TestAccAWSAPIGatewayV2Stage_Tags
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute (33.25s)
=== CONT  TestAccAWSAPIGatewayV2Stage_StageVariables
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp (41.61s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (29.61s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (28.50s)
=== CONT  TestAccAWSAPIGatewayV2Stage_disappears
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (14.16s)
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket (41.18s)
=== CONT  TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp (41.63s)
=== CONT  TestAccAWSAPIGatewayV2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (28.42s)
=== CONT  TestAccAWSAPIGatewayV2Stage_defaultHttpStage
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket (40.08s)
=== CONT  TestAccAWSAPIGatewayV2Stage_autoDeployHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (27.89s)
=== CONT  TestAccAWSAPIGatewayV2Stage_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_defaultHttpStage (16.89s)
=== CONT  TestAccAWSAPIGatewayV2Stage_Deployment
--- PASS: TestAccAWSAPIGatewayV2Stage_basicHttp (16.86s)
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (20.36s)
--- PASS: TestAccAWSAPIGatewayV2Stage_autoDeployHttp (32.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	150.361s
```

Verified Acceptance Tests in GovCloud (us-gov-west-1)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2Stage_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSAPIGatewayV2Stage_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_basicHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_basicHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== PAUSE TestAccAWSAPIGatewayV2Stage_defaultHttpStage
=== RUN   TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_autoDeployHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_disappears
=== PAUSE TestAccAWSAPIGatewayV2Stage_disappears
=== RUN   TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== PAUSE TestAccAWSAPIGatewayV2Stage_AccessLogSettings
=== RUN   TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== PAUSE TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_Deployment
=== PAUSE TestAccAWSAPIGatewayV2Stage_Deployment
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
=== RUN   TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== PAUSE TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
=== RUN   TestAccAWSAPIGatewayV2Stage_StageVariables
=== PAUSE TestAccAWSAPIGatewayV2Stage_StageVariables
=== RUN   TestAccAWSAPIGatewayV2Stage_Tags
=== PAUSE TestAccAWSAPIGatewayV2Stage_Tags
=== CONT  TestAccAWSAPIGatewayV2Stage_basicWebSocket
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute
--- PASS: TestAccAWSAPIGatewayV2Stage_basicWebSocket (13.71s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp_WithRoute (26.16s)
=== CONT  TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsHttp (31.94s)
=== CONT  TestAccAWSAPIGatewayV2Stage_Deployment
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsHttp (30.18s)
=== CONT  TestAccAWSAPIGatewayV2Stage_disappears
--- PASS: TestAccAWSAPIGatewayV2Stage_Deployment (16.17s)
=== CONT  TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket
--- PASS: TestAccAWSAPIGatewayV2Stage_disappears (9.62s)
=== CONT  TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription
--- PASS: TestAccAWSAPIGatewayV2Stage_RouteSettingsWebSocket (47.20s)
=== CONT  TestAccAWSAPIGatewayV2Stage_AccessLogSettings
--- PASS: TestAccAWSAPIGatewayV2Stage_ClientCertificateIdAndDescription (21.04s)
=== CONT  TestAccAWSAPIGatewayV2Stage_defaultHttpStage
--- PASS: TestAccAWSAPIGatewayV2Stage_DefaultRouteSettingsWebSocket (31.01s)
=== CONT  TestAccAWSAPIGatewayV2Stage_autoDeployHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_defaultHttpStage (12.65s)
=== CONT  TestAccAWSAPIGatewayV2Stage_Tags
--- PASS: TestAccAWSAPIGatewayV2Stage_AccessLogSettings (21.93s)
=== CONT  TestAccAWSAPIGatewayV2Stage_basicHttp
--- PASS: TestAccAWSAPIGatewayV2Stage_autoDeployHttp (21.27s)
=== CONT  TestAccAWSAPIGatewayV2Stage_StageVariables
--- PASS: TestAccAWSAPIGatewayV2Stage_Tags (21.06s)
--- PASS: TestAccAWSAPIGatewayV2Stage_basicHttp (13.23s)
--- PASS: TestAccAWSAPIGatewayV2Stage_StageVariables (19.75s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	121.678s
```

**Pull request merged**
