### PR TITLE
aws_elb & aws_lb: Add desync_mitigation_mode

### LINKED ISSUE #14696: Support for `routing.http.desync_mitigation_mode` in ALB/CLB
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Application Load Balancer (ALB) and Classic Load Balancer (CLB) now support HTTP Desync Mitigation Mode, a new feature that protects your application from issues due to HTTP Desync. Modern day web applications are typically built with a chain of proxies that ensure fast and reliable communication between clients and servers. While these proxies follow a standard mechanism to parse RFC 7230 compliant HTTP/1.1 requests, they may have differences in interpretation while parsing non-compliant requests. These differences in interpretation can cause Desync where different proxies in the chain may disagree on request boundaries and therefore may not process the same request. This could leave behind arbitrary messages that may be prepended to the next request in the queue and smuggled to the backend. Ultimately, request smuggling can make applications vulnerable to request queue or cache poisoning, which could lead to credential hijacking or execution of unauthorized commands. 
> 
> An option to mitigate Desync is to only allow requests that strictly conform to RFC. However, a large percentage of real world requests include characters that don't strictly conform to RFC. As a result, pursuing a strategy of only allowing requests that has strict conformance could pose an availability risk to some legitimate use-cases. With Desync Mitigation Mode, your ALB/CLB will provide durable security while maintaining the availability and performance of your application. To accomplish this, the load balancer will classify every request based on its threat level using an AWS Open Source library called HTTP Desync Guardian. You can then configure your load balancer and choose the appropriate mitigation strategy based on the security needs of your application. With this feature, your ALB or CLB will mitigate threats to your application from HTTP vulnerabilities both in front of the load balancer and behind it.
> 
> With Desync Mitigation Mode, customers can choose among three modes - “Defensive”, “Strictest”, and “Monitor”. In the “Defensive” mode, the load balancer will perform three specific tasks. First, it will allow your application to receive known safe requests irrespective of their RFC 7230 compliance. Second, it will block requests that are not RFC compliant and are known security threats. Third, it will close both the client and upstream connections irrespective of HTTP keep-alive limits for ambiguous requests. Ambiguous requests are requests that are not RFC 7230 compliant, and can cause Desync because they are subject to varying interpretations by different proxies or web-servers. The “Defensive” mode is chosen as your default as it provides a durable hands-free mitigation against HTTP Desync, while maintaining the availability of your application. You can opt into the “Strictest” mode if you need to ensure that your application only sees requests that are RFC 7230 compliant. Finally, you also have the flexibility to configure “Monitor” mode, if you want your load balancer to forward all requests it receives, regardless of classification, to the application behind it. 

### New or Affected Resource(s

* aws_elb
* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "lb_test" {
  desync_mitigation_mode = {monitor,defensive,strictest}
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/08/application-and-classic-load-balancers-adding-defense-in-depth-with-introduction-of-desync-mitigation-mode/

* https://docs.aws.amazon.com/elasticloadbalancing/latest/application/application-load-balancers.html#desync-mitigation-mode

### PR DESCRIPTION
**Pull request by roberth-k**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14696

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
ENHANCEMENTS:

data-source/aws_elb: Add `desync_mitigation_mode` attribute
data-source/aws_lb: Add `desync_mitigation_mode` attribute
resource/aws_elb: Add `desync_mitigation_mode` attribute
resource/aws_lb: Add `desync_mitigation_mode` attribute
```

Output from acceptance testing:

```
f-lb_desync_mitigation_mode-2 $ make testacc PKG=elbv2 TESTS=TestAccELBV2LoadBalancer_ ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 2 -run='TestAccELBV2LoadBalancer_' -timeout 180m
=== RUN   TestAccELBV2LoadBalancer_ALB_basic
=== PAUSE TestAccELBV2LoadBalancer_ALB_basic
=== RUN   TestAccELBV2LoadBalancer_NLB_basic
=== PAUSE TestAccELBV2LoadBalancer_NLB_basic
=== RUN   TestAccELBV2LoadBalancer_LoadBalancerType_gateway
=== PAUSE TestAccELBV2LoadBalancer_LoadBalancerType_gateway
=== RUN   TestAccELBV2LoadBalancer_ipv6SubnetMapping
=== PAUSE TestAccELBV2LoadBalancer_ipv6SubnetMapping
=== RUN   TestAccELBV2LoadBalancer_LoadBalancerTypeGateway_enableCrossZoneLoadBalancing
=== PAUSE TestAccELBV2LoadBalancer_LoadBalancerTypeGateway_enableCrossZoneLoadBalancing
=== RUN   TestAccELBV2LoadBalancer_ALB_outpost
=== PAUSE TestAccELBV2LoadBalancer_ALB_outpost
=== RUN   TestAccELBV2LoadBalancer_networkLoadBalancerEIP
=== PAUSE TestAccELBV2LoadBalancer_networkLoadBalancerEIP
=== RUN   TestAccELBV2LoadBalancer_NLB_privateIPv4Address
=== PAUSE TestAccELBV2LoadBalancer_NLB_privateIPv4Address
=== RUN   TestAccELBV2LoadBalancer_backwardsCompatibility
=== PAUSE TestAccELBV2LoadBalancer_backwardsCompatibility
=== RUN   TestAccELBV2LoadBalancer_generatedName
=== PAUSE TestAccELBV2LoadBalancer_generatedName
=== RUN   TestAccELBV2LoadBalancer_generatesNameForZeroValue
=== PAUSE TestAccELBV2LoadBalancer_generatesNameForZeroValue
=== RUN   TestAccELBV2LoadBalancer_namePrefix
=== PAUSE TestAccELBV2LoadBalancer_namePrefix
=== RUN   TestAccELBV2LoadBalancer_tags
=== PAUSE TestAccELBV2LoadBalancer_tags
=== RUN   TestAccELBV2LoadBalancer_NetworkLoadBalancer_updateCrossZone
=== PAUSE TestAccELBV2LoadBalancer_NetworkLoadBalancer_updateCrossZone
=== RUN   TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateHTTP2
=== PAUSE TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateHTTP2
=== RUN   TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDropInvalidHeaderFields
=== PAUSE TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDropInvalidHeaderFields
=== RUN   TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDeletionProtection
=== PAUSE TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDeletionProtection
=== RUN   TestAccELBV2LoadBalancer_updatedSecurityGroups
=== PAUSE TestAccELBV2LoadBalancer_updatedSecurityGroups
=== RUN   TestAccELBV2LoadBalancer_updatedSubnets
=== PAUSE TestAccELBV2LoadBalancer_updatedSubnets
=== RUN   TestAccELBV2LoadBalancer_updatedIPAddressType
=== PAUSE TestAccELBV2LoadBalancer_updatedIPAddressType
=== RUN   TestAccELBV2LoadBalancer_noSecurityGroup
=== PAUSE TestAccELBV2LoadBalancer_noSecurityGroup
=== RUN   TestAccELBV2LoadBalancer_ALB_accessLogs
=== PAUSE TestAccELBV2LoadBalancer_ALB_accessLogs
=== RUN   TestAccELBV2LoadBalancer_ALBAccessLogs_prefix
=== PAUSE TestAccELBV2LoadBalancer_ALBAccessLogs_prefix
=== RUN   TestAccELBV2LoadBalancer_NLB_accessLogs
=== PAUSE TestAccELBV2LoadBalancer_NLB_accessLogs
=== RUN   TestAccELBV2LoadBalancer_NLBAccessLogs_prefix
=== PAUSE TestAccELBV2LoadBalancer_NLBAccessLogs_prefix
=== RUN   TestAccELBV2LoadBalancer_NetworkLoadBalancerSubnet_change
=== PAUSE TestAccELBV2LoadBalancer_NetworkLoadBalancerSubnet_change
=== RUN   TestAccELBV2LoadBalancer_updateDesyncMitigationMode
=== PAUSE TestAccELBV2LoadBalancer_updateDesyncMitigationMode
=== CONT  TestAccELBV2LoadBalancer_ALB_basic
=== CONT  TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateHTTP2
--- PASS: TestAccELBV2LoadBalancer_ALB_basic (182.23s)
=== CONT  TestAccELBV2LoadBalancer_updateDesyncMitigationMode
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateHTTP2 (307.58s)
=== CONT  TestAccELBV2LoadBalancer_NetworkLoadBalancerSubnet_change
--- PASS: TestAccELBV2LoadBalancer_updateDesyncMitigationMode (309.43s)
=== CONT  TestAccELBV2LoadBalancer_NLBAccessLogs_prefix
--- PASS: TestAccELBV2LoadBalancer_NetworkLoadBalancerSubnet_change (485.83s)
=== CONT  TestAccELBV2LoadBalancer_NLB_accessLogs
--- PASS: TestAccELBV2LoadBalancer_NLBAccessLogs_prefix (362.80s)
=== CONT  TestAccELBV2LoadBalancer_ALBAccessLogs_prefix
--- PASS: TestAccELBV2LoadBalancer_ALBAccessLogs_prefix (340.48s)
=== CONT  TestAccELBV2LoadBalancer_NLB_privateIPv4Address
--- PASS: TestAccELBV2LoadBalancer_NLB_accessLogs (418.68s)
=== CONT  TestAccELBV2LoadBalancer_NetworkLoadBalancer_updateCrossZone
--- PASS: TestAccELBV2LoadBalancer_NLB_privateIPv4Address (241.60s)
=== CONT  TestAccELBV2LoadBalancer_tags
--- PASS: TestAccELBV2LoadBalancer_NetworkLoadBalancer_updateCrossZone (323.24s)
=== CONT  TestAccELBV2LoadBalancer_namePrefix
--- PASS: TestAccELBV2LoadBalancer_namePrefix (180.03s)
=== CONT  TestAccELBV2LoadBalancer_ALB_accessLogs
--- PASS: TestAccELBV2LoadBalancer_tags (324.26s)
=== CONT  TestAccELBV2LoadBalancer_noSecurityGroup
--- PASS: TestAccELBV2LoadBalancer_noSecurityGroup (236.71s)
=== CONT  TestAccELBV2LoadBalancer_updatedIPAddressType
--- PASS: TestAccELBV2LoadBalancer_ALB_accessLogs (398.41s)
=== CONT  TestAccELBV2LoadBalancer_updatedSubnets
--- PASS: TestAccELBV2LoadBalancer_updatedIPAddressType (301.62s)
=== CONT  TestAccELBV2LoadBalancer_updatedSecurityGroups
--- PASS: TestAccELBV2LoadBalancer_updatedSubnets (278.37s)
=== CONT  TestAccELBV2LoadBalancer_generatesNameForZeroValue
--- PASS: TestAccELBV2LoadBalancer_updatedSecurityGroups (237.65s)
=== CONT  TestAccELBV2LoadBalancer_generatedName
--- PASS: TestAccELBV2LoadBalancer_generatesNameForZeroValue (237.93s)
=== CONT  TestAccELBV2LoadBalancer_backwardsCompatibility
--- PASS: TestAccELBV2LoadBalancer_generatedName (177.05s)
=== CONT  TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDeletionProtection
--- PASS: TestAccELBV2LoadBalancer_backwardsCompatibility (186.58s)
=== CONT  TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDropInvalidHeaderFields
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDeletionProtection (355.87s)
=== CONT  TestAccELBV2LoadBalancer_LoadBalancerTypeGateway_enableCrossZoneLoadBalancing
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDropInvalidHeaderFields (296.55s)
=== CONT  TestAccELBV2LoadBalancer_networkLoadBalancerEIP
--- PASS: TestAccELBV2LoadBalancer_LoadBalancerTypeGateway_enableCrossZoneLoadBalancing (168.24s)
=== CONT  TestAccELBV2LoadBalancer_ALB_outpost
    acctest.go:1241: skipping acceptance testing: AccessDeniedException: User: arn:aws:iam::868807437771:user/cloud_user is not authorized to perform: outposts:ListOutposts on resource: arn:aws:outposts:us-east-1:868807437771:* with an explicit deny
--- SKIP: TestAccELBV2LoadBalancer_ALB_outpost (0.40s)
=== CONT  TestAccELBV2LoadBalancer_LoadBalancerType_gateway
--- PASS: TestAccELBV2LoadBalancer_networkLoadBalancerEIP (223.42s)
=== CONT  TestAccELBV2LoadBalancer_ipv6SubnetMapping
--- PASS: TestAccELBV2LoadBalancer_LoadBalancerType_gateway (113.67s)
=== CONT  TestAccELBV2LoadBalancer_NLB_basic
--- PASS: TestAccELBV2LoadBalancer_ipv6SubnetMapping (207.86s)
--- PASS: TestAccELBV2LoadBalancer_NLB_basic (234.79s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      3588.660s

f-lb_desync_mitigation_mode-2 $ make testacc PKG=elbv2 TESTS=TestAccELBV2LoadBalancerDataSource_ ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 2 -run='TestAccELBV2LoadBalancerDataSource_' -timeout 180m
=== RUN   TestAccELBV2LoadBalancerDataSource_basic
=== PAUSE TestAccELBV2LoadBalancerDataSource_basic
=== RUN   TestAccELBV2LoadBalancerDataSource_outpost
=== PAUSE TestAccELBV2LoadBalancerDataSource_outpost
=== RUN   TestAccELBV2LoadBalancerDataSource_backwardsCompatibility
=== PAUSE TestAccELBV2LoadBalancerDataSource_backwardsCompatibility
=== CONT  TestAccELBV2LoadBalancerDataSource_basic
=== CONT  TestAccELBV2LoadBalancerDataSource_backwardsCompatibility
--- PASS: TestAccELBV2LoadBalancerDataSource_basic (240.44s)
=== CONT  TestAccELBV2LoadBalancerDataSource_outpost
--- PASS: TestAccELBV2LoadBalancerDataSource_backwardsCompatibility (240.44s)
=== CONT  TestAccELBV2LoadBalancerDataSource_outpost
    acctest.go:1250: skipping since no Outposts found
--- SKIP: TestAccELBV2LoadBalancerDataSource_outpost (0.29s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      242.559s

f-lb_desync_mitigation_mode-2 $ make testacc PKG=elb TESTS=TestAccELBLoadBalancer_ ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elb/... -v -count 1 -parallel 2 -run='TestAccELBLoadBalancer_' -timeout 180m
=== RUN   TestAccELBLoadBalancer_basic
=== PAUSE TestAccELBLoadBalancer_basic
=== RUN   TestAccELBLoadBalancer_disappears
=== PAUSE TestAccELBLoadBalancer_disappears
=== RUN   TestAccELBLoadBalancer_fullCharacterRange
=== PAUSE TestAccELBLoadBalancer_fullCharacterRange
=== RUN   TestAccELBLoadBalancer_AccessLogs_enabled
=== PAUSE TestAccELBLoadBalancer_AccessLogs_enabled
=== RUN   TestAccELBLoadBalancer_AccessLogs_disabled
=== PAUSE TestAccELBLoadBalancer_AccessLogs_disabled
=== RUN   TestAccELBLoadBalancer_namePrefix
=== PAUSE TestAccELBLoadBalancer_namePrefix
=== RUN   TestAccELBLoadBalancer_generatedName
=== PAUSE TestAccELBLoadBalancer_generatedName
=== RUN   TestAccELBLoadBalancer_generatesNameForZeroValue
=== PAUSE TestAccELBLoadBalancer_generatesNameForZeroValue
=== RUN   TestAccELBLoadBalancer_availabilityZones
=== PAUSE TestAccELBLoadBalancer_availabilityZones
=== RUN   TestAccELBLoadBalancer_tags
=== PAUSE TestAccELBLoadBalancer_tags
=== RUN   TestAccELBLoadBalancer_ListenerSSLCertificateID_iamServerCertificate
=== PAUSE TestAccELBLoadBalancer_ListenerSSLCertificateID_iamServerCertificate
=== RUN   TestAccELBLoadBalancer_Swap_subnets
=== PAUSE TestAccELBLoadBalancer_Swap_subnets
=== RUN   TestAccELBLoadBalancer_instanceAttaching
=== PAUSE TestAccELBLoadBalancer_instanceAttaching
=== RUN   TestAccELBLoadBalancer_listener
=== PAUSE TestAccELBLoadBalancer_listener
=== RUN   TestAccELBLoadBalancer_healthCheck
=== PAUSE TestAccELBLoadBalancer_healthCheck
=== RUN   TestAccELBLoadBalancer_timeout
=== PAUSE TestAccELBLoadBalancer_timeout
=== RUN   TestAccELBLoadBalancer_connectionDraining
=== PAUSE TestAccELBLoadBalancer_connectionDraining
=== RUN   TestAccELBLoadBalancer_securityGroups
=== PAUSE TestAccELBLoadBalancer_securityGroups
=== RUN   TestAccELBLoadBalancer_desyncMitigationMode
=== PAUSE TestAccELBLoadBalancer_desyncMitigationMode
=== RUN   TestAccELBLoadBalancer_desyncMitigationMode_update
=== PAUSE TestAccELBLoadBalancer_desyncMitigationMode_update
=== CONT  TestAccELBLoadBalancer_basic
=== CONT  TestAccELBLoadBalancer_ListenerSSLCertificateID_iamServerCertificate
--- PASS: TestAccELBLoadBalancer_basic (29.02s)
=== CONT  TestAccELBLoadBalancer_healthCheck
--- PASS: TestAccELBLoadBalancer_ListenerSSLCertificateID_iamServerCertificate (39.55s)
=== CONT  TestAccELBLoadBalancer_listener
--- PASS: TestAccELBLoadBalancer_healthCheck (42.91s)
=== CONT  TestAccELBLoadBalancer_instanceAttaching
--- PASS: TestAccELBLoadBalancer_listener (113.33s)
=== CONT  TestAccELBLoadBalancer_Swap_subnets
--- PASS: TestAccELBLoadBalancer_instanceAttaching (119.17s)
=== CONT  TestAccELBLoadBalancer_desyncMitigationMode
--- PASS: TestAccELBLoadBalancer_desyncMitigationMode (25.65s)
=== CONT  TestAccELBLoadBalancer_desyncMitigationMode_update
--- PASS: TestAccELBLoadBalancer_Swap_subnets (88.10s)
=== CONT  TestAccELBLoadBalancer_timeout
--- PASS: TestAccELBLoadBalancer_timeout (38.79s)
=== CONT  TestAccELBLoadBalancer_securityGroups
--- PASS: TestAccELBLoadBalancer_desyncMitigationMode_update (64.03s)
=== CONT  TestAccELBLoadBalancer_connectionDraining
--- PASS: TestAccELBLoadBalancer_securityGroups (46.21s)
=== CONT  TestAccELBLoadBalancer_namePrefix
--- PASS: TestAccELBLoadBalancer_connectionDraining (56.91s)
=== CONT  TestAccELBLoadBalancer_generatesNameForZeroValue
--- PASS: TestAccELBLoadBalancer_namePrefix (23.08s)
=== CONT  TestAccELBLoadBalancer_generatedName
--- PASS: TestAccELBLoadBalancer_generatesNameForZeroValue (24.05s)
=== CONT  TestAccELBLoadBalancer_tags
--- PASS: TestAccELBLoadBalancer_generatedName (22.82s)
=== CONT  TestAccELBLoadBalancer_AccessLogs_enabled
--- PASS: TestAccELBLoadBalancer_tags (61.75s)
=== CONT  TestAccELBLoadBalancer_availabilityZones
--- PASS: TestAccELBLoadBalancer_AccessLogs_enabled (74.87s)
=== CONT  TestAccELBLoadBalancer_fullCharacterRange
--- PASS: TestAccELBLoadBalancer_availabilityZones (41.03s)
=== CONT  TestAccELBLoadBalancer_disappears
--- PASS: TestAccELBLoadBalancer_fullCharacterRange (23.95s)
=== CONT  TestAccELBLoadBalancer_AccessLogs_disabled
--- PASS: TestAccELBLoadBalancer_disappears (19.89s)
--- PASS: TestAccELBLoadBalancer_AccessLogs_disabled (75.42s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elb        548.016s

f-lb_desync_mitigation_mode-2 $ make testacc PKG=elb TESTS=TestAccELBLoadBalancerDataSource_ ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elb/... -v -count 1 -parallel 2 -run='TestAccELBLoadBalancerDataSource_' -timeout 180m
=== RUN   TestAccELBLoadBalancerDataSource_basic
=== PAUSE TestAccELBLoadBalancerDataSource_basic
=== CONT  TestAccELBLoadBalancerDataSource_basic
--- PASS: TestAccELBLoadBalancerDataSource_basic (55.42s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elb        57.333s
```

### CODE REVIEW

**Comment by reedloden** [comment]
@roberth-k care to rebase to fix the conflicts?

**Comment by roberth-k** [comment]
@reedloden I will rebase and re-run the acceptance tests when maintainers indicate a review is scheduled.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by roberth-k** [comment]
Thank you for the heads up @breathingdust -- I'll bring the PR up to date in about a week or so.

**Comment by roberth-k** [comment]
@breathingdust The PR is now up to date.

**Review by anGie44 — APPROVED** [review]
Thank you for contributing to this feature @roberth-k ! Looks great 🚀 

Output of acceptance tests:
```
--- PASS: TestAccELBLoadBalancerDataSource_basic (267.08s)
--- PASS: TestAccELBLoadBalancer_AccessLogs_disabled (272.24s)
--- PASS: TestAccELBLoadBalancer_AccessLogs_enabled (237.63s)
--- PASS: TestAccELBLoadBalancer_ListenerSSLCertificateID_iamServerCertificate (167.02s)
--- PASS: TestAccELBLoadBalancer_Swap_subnets (123.45s)
--- PASS: TestAccELBLoadBalancer_availabilityZones (268.65s)
--- PASS: TestAccELBLoadBalancer_basic (164.52s)
--- PASS: TestAccELBLoadBalancer_connectionDraining (235.95s)
--- PASS: TestAccELBLoadBalancer_desyncMitigationMode (54.56s)
--- PASS: TestAccELBLoadBalancer_desyncMitigationMode_update (148.25s)
--- PASS: TestAccELBLoadBalancer_disappears (50.11s)
--- PASS: TestAccELBLoadBalancer_fullCharacterRange (140.14s)
--- PASS: TestAccELBLoadBalancer_generatedName (129.21s)
--- PASS: TestAccELBLoadBalancer_generatesNameForZeroValue (49.21s)
--- PASS: TestAccELBLoadBalancer_healthCheck (109.48s)
--- PASS: TestAccELBLoadBalancer_instanceAttaching (352.77s)
--- PASS: TestAccELBLoadBalancer_listener (200.02s)
--- PASS: TestAccELBLoadBalancer_namePrefix (188.17s)
--- PASS: TestAccELBLoadBalancer_securityGroups (65.70s)
--- PASS: TestAccELBLoadBalancer_tags (77.89s)
--- PASS: TestAccELBLoadBalancer_timeout (63.51s)

--- PASS: TestAccELBV2LoadBalancer_ipv6SubnetMapping (309.91s)
--- PASS: TestAccELBV2LoadBalancer_networkLoadBalancerEIP (581.12s)
--- PASS: TestAccELBV2LoadBalancerDataSource_backwardsCompatibility (275.02s)
--- PASS: TestAccELBV2LoadBalancerDataSource_basic (287.13s)
--- PASS: TestAccELBV2LoadBalancer_ALBAccessLogs_prefix (256.76s)
--- PASS: TestAccELBV2LoadBalancer_ALB_accessLogs (358.15s)
--- PASS: TestAccELBV2LoadBalancer_ALB_basic (269.00s)
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDeletionProtection (334.23s)
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateDropInvalidHeaderFields (322.18s)
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateHTTP2 (387.32s)
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateWafFailOpen (308.26s)
--- PASS: TestAccELBV2LoadBalancer_LoadBalancerTypeGateway_enableCrossZoneLoadBalancing (170.66s)
--- PASS: TestAccELBV2LoadBalancer_LoadBalancerType_gateway (250.10s)
--- PASS: TestAccELBV2LoadBalancer_NLBAccessLogs_prefix (346.87s)
--- PASS: TestAccELBV2LoadBalancer_NLB_accessLogs (356.44s)
--- PASS: TestAccELBV2LoadBalancer_NLB_basic (270.72s)
--- PASS: TestAccELBV2LoadBalancer_NLB_privateIPv4Address (231.39s)
--- PASS: TestAccELBV2LoadBalancer_NetworkLoadBalancerSubnet_change (425.62s)
--- PASS: TestAccELBV2LoadBalancer_NetworkLoadBalancer_updateCrossZone (387.87s)
--- PASS: TestAccELBV2LoadBalancer_backwardsCompatibility (309.30s)
--- PASS: TestAccELBV2LoadBalancer_generatedName (256.36s)
--- PASS: TestAccELBV2LoadBalancer_generatesNameForZeroValue (287.00s)
--- PASS: TestAccELBV2LoadBalancer_namePrefix (266.55s)
--- PASS: TestAccELBV2LoadBalancer_noSecurityGroup (167.65s)
--- PASS: TestAccELBV2LoadBalancer_tags (377.94s)
--- PASS: TestAccELBV2LoadBalancer_updateDesyncMitigationMode (322.91s)
--- PASS: TestAccELBV2LoadBalancer_updatedIPAddressType (215.02s)
--- PASS: TestAccELBV2LoadBalancer_updatedSecurityGroups (368.56s)
--- PASS: TestAccELBV2LoadBalancer_updatedSubnets (393.75s)
--- SKIP: TestAccELBV2LoadBalancerDataSource_outpost (1.29s)
--- SKIP: TestAccELBV2LoadBalancer_ALB_outpost (1.14s)
```

**Pull request merged**
