### PR TITLE
New Data Source: aws_route53_zones

### LINKED ISSUE #17334: Ability to retrieve all route 53 zones from data.aws_route53_zone
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_route53_zone

### Potential Terraform Configuration

We need the ability to retrieve all of the avialable route 53 hosted zones in the account/region we are targeting. 
Currently we must provide a name/zone_id to the data, however this is information we do not have at the time of deployment.

```hcl
provider "aws" {
  region = "us-east-1"
}
data "aws_route53_zone" "all" {}
```

### LINKED ISSUE #37465: [New Data Source]: `aws_route53_zones` Get list (!) of hosted zones
### Description

I have several hosted zones in my AWS account and some zones are sub-zones e.g. `example.com`, `app1.example.com`, `app2.example.com`, etc., which are managed by an "external" stack.

If I want to to place a new application to my account, I want to select the "best fitting" zone, depending on the domain for the new application:
* app1.example.com -> "" (empty) A record in `app1.example.com`
* new.example.com -> "new" A record in `example.com`
* very.deep.app2.example.com -> "very.deep" A record in `example.com`

I have already implented a some logic with terraform functions for selecting the zone, but for getting the list of hosted zones I'm using `external` provider, which just executes `aws route53 list-hosted-zones --query HostedZones --output json` (plus some hacky workaround by converting this output to base64, because this data source supports "key/value JSON", only)

It would be great, if I could use a native list data source for better stability and less external dependencies...
This new data source might be ideal for new contributers, because of existing similar list data sources and the "List" API is already being used by the existing `aws_route53_zone`(without trailing 's'): https://github.com/hashicorp/terraform-provider-aws/blob/42ad9820ef6474603f0910bded17b1679704375c/internal/service/route53/zone_data_source.go#L116

### Requested Resource(s) and/or Data Source(s)

* aws_route53_zones

(Mind the trailing 's'!)

### Potential Terraform Configuration

```terraform
data "aws_route53_zones" "account_zones" {
  private_zone = false
}
```

### References

Get some "inspiration" from similar data source:
* https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/route53/zone.go

AWS API:
* https://docs.aws.amazon.com/Route53/latest/APIReference/API_ListHostedZones.html

Links to comparable data sources:
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/availability_zones
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/eips
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/vpcs
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/data-sources/subnets
* and many more...

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by yuonoda**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17334
Closes #37465

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccDataSourceAwsRoute53Zones'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsRoute53Zones -timeout 120m
=== RUN   TestAccDataSourceAwsRoute53Zones_basic
=== PAUSE TestAccDataSourceAwsRoute53Zones_basic
=== CONT  TestAccDataSourceAwsRoute53Zones_basic
--- PASS: TestAccDataSourceAwsRoute53Zones_basic (60.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       62.732s
...
```

### CODE REVIEW

**Comment by hfeixas** [comment]
Hey guys, has anyone had a chance to review this ? Would really like to see this feature implemented.

**Comment by yuonoda** [comment]
@hfeixas Thank you for your comment. Because there are so many pull requests, they shouldn't have time to review this request. So give me 👍 reaction to tell reviewers this feature needs to be implemented.

**Comment by antonosmond** [comment]
It'd be nice if this took filters e.g. `vpc_id`.
The AWS CLI has `aws route53 list-hosted-zones-by-vpc` so it must be possible to get the hosted zones for a given VPC ID and potentially other filters too.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by freakinhippie** [comment]
I know this is a very old PR, but I would like to see it implemented too.

FWIW, in following with the pattern of other recent pluralized data sources, I don't think an empty result set should raise an error, it should just return an empty list.

**Comment by yermulnik** [comment]
> I know this is a very old PR, but I would like to see it implemented too.

Bumping this thread to see whether this feature is feasible yet.

**Comment by LukasdeBoer** [comment]
This one would be very nice for us too.

**Comment by dreinhardt-terminus** [comment]
We would like this as well

**Comment by DJAlPee** [comment]
I have created a new issue without knowing, that this PR already existed: https://github.com/hashicorp/terraform-provider-aws/issues/37465 (Next time, I should search not only the issues )
Unfortunately, this PR won't solve my problem directly, because I need the hosted zone names for my case, too. This can be easily achieved by using the `aws_route_zone` data source with `for_each`. Ideally, this shouldn't be neccessary, because the list call to AWS provides already a lot of information, which could be used for the resource.

> It'd be nice if this took filters e.g. `vpc_id`. The AWS CLI has `aws route53 list-hosted-zones-by-vpc` so it must be possible to get the hosted zones for a given VPC ID and potentially other filters too.

With all information provided, it should be possible to filter the results with terraform functions.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRoute53ZonesDataSource_' PKG=route53
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/route53/... -v -count 1 -parallel 20  -run=TestAccRoute53ZonesDataSource_ -timeout 360m
=== RUN   TestAccRoute53ZonesDataSource_basic
=== PAUSE TestAccRoute53ZonesDataSource_basic
=== CONT  TestAccRoute53ZonesDataSource_basic
--- PASS: TestAccRoute53ZonesDataSource_basic (84.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53	89.773s
```

**Comment by ewbankkit** [comment]
@yuonoda Thanks for the contribution :tada: :clap:.

**Pull request merged**
