### PR TITLE
Adding option to capture snapshots on destroy of ebs_volume using final_snapshot parameter

### LINKED ISSUE #2109: Add option to capture snapshots on destroy of `ebs_volume`
Seems like `ebs_volumes` should have a parameter to trigger a snapshot of the volume before deleting, much like [final_snapshot_identifer](https://www.terraform.io/docs/providers/aws/r/db_instance.html#final_snapshot_identifier) in `db_instance`

### PR DESCRIPTION
**Pull request by AndreKapraty**
Adding option to capture snapshots on destroy of ebs_volume using final_snapshot parameter

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #2109

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EBSVolume_FinalSnapshot' -timeout 180m
=== RUN   TestAccEC2EBSVolume_FinalSnapshot
=== PAUSE TestAccEC2EBSVolume_FinalSnapshot
=== CONT  TestAccEC2EBSVolume_FinalSnapshot
--- PASS: TestAccEC2EBSVolume_FinalSnapshot (58.84s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        69.297s
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Supersedes #11118.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2EBSVolume\|TestAccEC2EBSSnapshot' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2EBSVolume\|TestAccEC2EBSSnapshot -timeout 180m
=== RUN   TestAccEC2EBSSnapshotCopy_basic
=== PAUSE TestAccEC2EBSSnapshotCopy_basic
=== RUN   TestAccEC2EBSSnapshotCopy_disappears
=== PAUSE TestAccEC2EBSSnapshotCopy_disappears
=== RUN   TestAccEC2EBSSnapshotCopy_tags
=== PAUSE TestAccEC2EBSSnapshotCopy_tags
=== RUN   TestAccEC2EBSSnapshotCopy_withDescription
=== PAUSE TestAccEC2EBSSnapshotCopy_withDescription
=== RUN   TestAccEC2EBSSnapshotCopy_withRegions
=== PAUSE TestAccEC2EBSSnapshotCopy_withRegions
=== RUN   TestAccEC2EBSSnapshotCopy_withKMS
=== PAUSE TestAccEC2EBSSnapshotCopy_withKMS
=== RUN   TestAccEC2EBSSnapshotCopy_storageTier
=== PAUSE TestAccEC2EBSSnapshotCopy_storageTier
=== RUN   TestAccEC2EBSSnapshotCreateVolumePermission_basic
=== PAUSE TestAccEC2EBSSnapshotCreateVolumePermission_basic
=== RUN   TestAccEC2EBSSnapshotCreateVolumePermission_disappears
=== PAUSE TestAccEC2EBSSnapshotCreateVolumePermission_disappears
=== RUN   TestAccEC2EBSSnapshotDataSource_basic
=== PAUSE TestAccEC2EBSSnapshotDataSource_basic
=== RUN   TestAccEC2EBSSnapshotDataSource_filter
=== PAUSE TestAccEC2EBSSnapshotDataSource_filter
=== RUN   TestAccEC2EBSSnapshotDataSource_mostRecent
=== PAUSE TestAccEC2EBSSnapshotDataSource_mostRecent
=== RUN   TestAccEC2EBSSnapshotIDsDataSource_basic
=== PAUSE TestAccEC2EBSSnapshotIDsDataSource_basic
=== RUN   TestAccEC2EBSSnapshotIDsDataSource_sorted
=== PAUSE TestAccEC2EBSSnapshotIDsDataSource_sorted
=== RUN   TestAccEC2EBSSnapshotIDsDataSource_empty
=== PAUSE TestAccEC2EBSSnapshotIDsDataSource_empty
=== RUN   TestAccEC2EBSSnapshotImport_basic
=== PAUSE TestAccEC2EBSSnapshotImport_basic
=== RUN   TestAccEC2EBSSnapshotImport_disappears
=== PAUSE TestAccEC2EBSSnapshotImport_disappears
=== RUN   TestAccEC2EBSSnapshotImport_Disappears_s3Object
=== PAUSE TestAccEC2EBSSnapshotImport_Disappears_s3Object
=== RUN   TestAccEC2EBSSnapshotImport_tags
=== PAUSE TestAccEC2EBSSnapshotImport_tags
=== RUN   TestAccEC2EBSSnapshotImport_storageTier
=== PAUSE TestAccEC2EBSSnapshotImport_storageTier
=== RUN   TestAccEC2EBSSnapshot_basic
=== PAUSE TestAccEC2EBSSnapshot_basic
=== RUN   TestAccEC2EBSSnapshot_disappears
=== PAUSE TestAccEC2EBSSnapshot_disappears
=== RUN   TestAccEC2EBSSnapshot_storageTier
=== PAUSE TestAccEC2EBSSnapshot_storageTier
=== RUN   TestAccEC2EBSSnapshot_outpost
=== PAUSE TestAccEC2EBSSnapshot_outpost
=== RUN   TestAccEC2EBSSnapshot_tags
=== PAUSE TestAccEC2EBSSnapshot_tags
=== RUN   TestAccEC2EBSSnapshot_withDescription
=== PAUSE TestAccEC2EBSSnapshot_withDescription
=== RUN   TestAccEC2EBSSnapshot_withKMS
=== PAUSE TestAccEC2EBSSnapshot_withKMS
=== RUN   TestAccEC2EBSVolumeAttachment_basic
=== PAUSE TestAccEC2EBSVolumeAttachment_basic
=== RUN   TestAccEC2EBSVolumeAttachment_skipDestroy
=== PAUSE TestAccEC2EBSVolumeAttachment_skipDestroy
=== RUN   TestAccEC2EBSVolumeAttachment_attachStopped
=== PAUSE TestAccEC2EBSVolumeAttachment_attachStopped
=== RUN   TestAccEC2EBSVolumeAttachment_update
=== PAUSE TestAccEC2EBSVolumeAttachment_update
=== RUN   TestAccEC2EBSVolumeAttachment_disappears
=== PAUSE TestAccEC2EBSVolumeAttachment_disappears
=== RUN   TestAccEC2EBSVolumeAttachment_stopInstance
=== PAUSE TestAccEC2EBSVolumeAttachment_stopInstance
=== RUN   TestAccEC2EBSVolumeDataSource_basic
=== PAUSE TestAccEC2EBSVolumeDataSource_basic
=== RUN   TestAccEC2EBSVolumeDataSource_multipleFilters
=== PAUSE TestAccEC2EBSVolumeDataSource_multipleFilters
=== RUN   TestAccEC2EBSVolume_basic
=== PAUSE TestAccEC2EBSVolume_basic
=== RUN   TestAccEC2EBSVolume_disappears
=== PAUSE TestAccEC2EBSVolume_disappears
=== RUN   TestAccEC2EBSVolume_updateAttachedEBSVolume
=== PAUSE TestAccEC2EBSVolume_updateAttachedEBSVolume
=== RUN   TestAccEC2EBSVolume_updateSize
=== PAUSE TestAccEC2EBSVolume_updateSize
=== RUN   TestAccEC2EBSVolume_updateType
=== PAUSE TestAccEC2EBSVolume_updateType
=== RUN   TestAccEC2EBSVolume_UpdateIops_io1
=== PAUSE TestAccEC2EBSVolume_UpdateIops_io1
=== RUN   TestAccEC2EBSVolume_UpdateIops_io2
=== PAUSE TestAccEC2EBSVolume_UpdateIops_io2
=== RUN   TestAccEC2EBSVolume_kmsKey
=== PAUSE TestAccEC2EBSVolume_kmsKey
=== RUN   TestAccEC2EBSVolume_noIops
=== PAUSE TestAccEC2EBSVolume_noIops
=== RUN   TestAccEC2EBSVolume_invalidIopsForType
=== PAUSE TestAccEC2EBSVolume_invalidIopsForType
=== RUN   TestAccEC2EBSVolume_invalidThroughputForType
=== PAUSE TestAccEC2EBSVolume_invalidThroughputForType
=== RUN   TestAccEC2EBSVolume_withTags
=== PAUSE TestAccEC2EBSVolume_withTags
=== RUN   TestAccEC2EBSVolume_multiAttach_io1
=== PAUSE TestAccEC2EBSVolume_multiAttach_io1
=== RUN   TestAccEC2EBSVolume_multiAttach_io2
=== PAUSE TestAccEC2EBSVolume_multiAttach_io2
=== RUN   TestAccEC2EBSVolume_multiAttach_gp2
=== PAUSE TestAccEC2EBSVolume_multiAttach_gp2
=== RUN   TestAccEC2EBSVolume_outpost
=== PAUSE TestAccEC2EBSVolume_outpost
=== RUN   TestAccEC2EBSVolume_GP3_basic
=== PAUSE TestAccEC2EBSVolume_GP3_basic
=== RUN   TestAccEC2EBSVolume_GP3_iops
=== PAUSE TestAccEC2EBSVolume_GP3_iops
=== RUN   TestAccEC2EBSVolume_GP3_throughput
=== PAUSE TestAccEC2EBSVolume_GP3_throughput
=== RUN   TestAccEC2EBSVolume_gp3ToGP2
=== PAUSE TestAccEC2EBSVolume_gp3ToGP2
=== RUN   TestAccEC2EBSVolume_io1ToGP3
=== PAUSE TestAccEC2EBSVolume_io1ToGP3
=== RUN   TestAccEC2EBSVolume_snapshotID
=== PAUSE TestAccEC2EBSVolume_snapshotID
=== RUN   TestAccEC2EBSVolume_snapshotIDAndSize
=== PAUSE TestAccEC2EBSVolume_snapshotIDAndSize
=== RUN   TestAccEC2EBSVolume_finalSnapshot
=== PAUSE TestAccEC2EBSVolume_finalSnapshot
=== RUN   TestAccEC2EBSVolumesDataSource_basic
=== PAUSE TestAccEC2EBSVolumesDataSource_basic
=== CONT  TestAccEC2EBSSnapshotCopy_basic
=== CONT  TestAccEC2EBSVolumeAttachment_update
=== CONT  TestAccEC2EBSVolume_invalidThroughputForType
--- PASS: TestAccEC2EBSVolume_invalidThroughputForType (3.40s)
=== CONT  TestAccEC2EBSVolumesDataSource_basic
--- PASS: TestAccEC2EBSVolumesDataSource_basic (35.86s)
=== CONT  TestAccEC2EBSVolume_finalSnapshot
--- PASS: TestAccEC2EBSSnapshotCopy_basic (68.44s)
=== CONT  TestAccEC2EBSVolume_snapshotIDAndSize
--- PASS: TestAccEC2EBSVolume_finalSnapshot (58.95s)
=== CONT  TestAccEC2EBSVolume_snapshotID
--- PASS: TestAccEC2EBSVolume_snapshotIDAndSize (76.30s)
=== CONT  TestAccEC2EBSVolume_io1ToGP3
--- PASS: TestAccEC2EBSVolume_snapshotID (74.24s)
=== CONT  TestAccEC2EBSVolume_gp3ToGP2
--- PASS: TestAccEC2EBSVolumeAttachment_update (179.54s)
=== CONT  TestAccEC2EBSVolume_GP3_throughput
--- PASS: TestAccEC2EBSVolume_io1ToGP3 (57.20s)
=== CONT  TestAccEC2EBSVolume_GP3_iops
--- PASS: TestAccEC2EBSVolume_gp3ToGP2 (57.42s)
=== CONT  TestAccEC2EBSVolume_GP3_basic
--- PASS: TestAccEC2EBSVolume_GP3_throughput (58.15s)
=== CONT  TestAccEC2EBSVolume_outpost
    acctest.go:1308: skipping since no Outposts found
--- SKIP: TestAccEC2EBSVolume_outpost (0.73s)
=== CONT  TestAccEC2EBSVolume_multiAttach_gp2
--- PASS: TestAccEC2EBSVolume_multiAttach_gp2 (3.26s)
=== CONT  TestAccEC2EBSVolume_multiAttach_io2
--- PASS: TestAccEC2EBSVolume_GP3_iops (58.01s)
=== CONT  TestAccEC2EBSVolume_multiAttach_io1
--- PASS: TestAccEC2EBSVolume_GP3_basic (36.69s)
=== CONT  TestAccEC2EBSVolume_withTags
--- PASS: TestAccEC2EBSVolume_multiAttach_io2 (35.92s)
=== CONT  TestAccEC2EBSVolume_updateSize
--- PASS: TestAccEC2EBSVolume_multiAttach_io1 (36.09s)
=== CONT  TestAccEC2EBSVolume_invalidIopsForType
--- PASS: TestAccEC2EBSVolume_invalidIopsForType (7.73s)
=== CONT  TestAccEC2EBSVolume_noIops
--- PASS: TestAccEC2EBSVolume_withTags (73.06s)
=== CONT  TestAccEC2EBSVolume_kmsKey
--- PASS: TestAccEC2EBSVolume_noIops (40.34s)
=== CONT  TestAccEC2EBSVolume_UpdateIops_io2
--- PASS: TestAccEC2EBSVolume_updateSize (68.42s)
=== CONT  TestAccEC2EBSVolume_UpdateIops_io1
--- PASS: TestAccEC2EBSVolume_kmsKey (46.45s)
=== CONT  TestAccEC2EBSVolume_updateType
--- PASS: TestAccEC2EBSVolume_UpdateIops_io2 (63.85s)
=== CONT  TestAccEC2EBSVolumeDataSource_multipleFilters
--- PASS: TestAccEC2EBSVolume_UpdateIops_io1 (62.89s)
=== CONT  TestAccEC2EBSVolume_updateAttachedEBSVolume
--- PASS: TestAccEC2EBSVolumeDataSource_multipleFilters (35.51s)
=== CONT  TestAccEC2EBSVolume_disappears
--- PASS: TestAccEC2EBSVolume_updateType (61.39s)
=== CONT  TestAccEC2EBSVolume_basic
--- PASS: TestAccEC2EBSVolume_disappears (34.27s)
=== CONT  TestAccEC2EBSSnapshotImport_basic
--- PASS: TestAccEC2EBSVolume_basic (38.09s)
=== CONT  TestAccEC2EBSVolumeAttachment_attachStopped
--- PASS: TestAccEC2EBSVolume_updateAttachedEBSVolume (200.45s)
=== CONT  TestAccEC2EBSVolumeAttachment_skipDestroy
--- PASS: TestAccEC2EBSSnapshotImport_basic (137.09s)
=== CONT  TestAccEC2EBSVolumeAttachment_basic
--- PASS: TestAccEC2EBSVolumeAttachment_attachStopped (147.81s)
=== CONT  TestAccEC2EBSSnapshot_withKMS
--- PASS: TestAccEC2EBSSnapshot_withKMS (59.98s)
=== CONT  TestAccEC2EBSSnapshot_withDescription
--- PASS: TestAccEC2EBSVolumeAttachment_skipDestroy (134.31s)
=== CONT  TestAccEC2EBSSnapshot_tags
--- PASS: TestAccEC2EBSSnapshot_withDescription (54.23s)
=== CONT  TestAccEC2EBSSnapshot_outpost
    acctest.go:1308: skipping since no Outposts found
--- SKIP: TestAccEC2EBSSnapshot_outpost (0.46s)
=== CONT  TestAccEC2EBSSnapshot_storageTier
--- PASS: TestAccEC2EBSVolumeAttachment_basic (145.85s)
=== CONT  TestAccEC2EBSSnapshot_disappears
--- PASS: TestAccEC2EBSSnapshot_disappears (51.39s)
=== CONT  TestAccEC2EBSSnapshot_basic
--- PASS: TestAccEC2EBSSnapshot_tags (79.91s)
=== CONT  TestAccEC2EBSSnapshotImport_storageTier
--- PASS: TestAccEC2EBSSnapshot_basic (54.48s)
=== CONT  TestAccEC2EBSSnapshotImport_tags
--- PASS: TestAccEC2EBSSnapshot_storageTier (118.59s)
=== CONT  TestAccEC2EBSSnapshotImport_Disappears_s3Object
--- PASS: TestAccEC2EBSSnapshotImport_Disappears_s3Object (154.52s)
=== CONT  TestAccEC2EBSSnapshotImport_disappears
--- PASS: TestAccEC2EBSSnapshotImport_tags (176.91s)
=== CONT  TestAccEC2EBSVolumeAttachment_stopInstance
--- PASS: TestAccEC2EBSSnapshotImport_storageTier (238.32s)
=== CONT  TestAccEC2EBSVolumeDataSource_basic
--- PASS: TestAccEC2EBSVolumeDataSource_basic (36.55s)
=== CONT  TestAccEC2EBSVolumeAttachment_disappears
--- PASS: TestAccEC2EBSSnapshotImport_disappears (135.94s)
=== CONT  TestAccEC2EBSSnapshotCreateVolumePermission_disappears
--- PASS: TestAccEC2EBSVolumeAttachment_stopInstance (145.22s)
=== CONT  TestAccEC2EBSSnapshotIDsDataSource_empty
--- PASS: TestAccEC2EBSSnapshotIDsDataSource_empty (9.88s)
=== CONT  TestAccEC2EBSSnapshotIDsDataSource_sorted
--- PASS: TestAccEC2EBSSnapshotCreateVolumePermission_disappears (72.03s)
=== CONT  TestAccEC2EBSSnapshotIDsDataSource_basic
--- PASS: TestAccEC2EBSVolumeAttachment_disappears (154.82s)
=== CONT  TestAccEC2EBSSnapshotDataSource_mostRecent
--- PASS: TestAccEC2EBSSnapshotIDsDataSource_sorted (78.83s)
=== CONT  TestAccEC2EBSSnapshotDataSource_filter
--- PASS: TestAccEC2EBSSnapshotIDsDataSource_basic (57.80s)
=== CONT  TestAccEC2EBSSnapshotDataSource_basic
--- PASS: TestAccEC2EBSSnapshotDataSource_filter (50.69s)
=== CONT  TestAccEC2EBSSnapshotCopy_storageTier
--- PASS: TestAccEC2EBSSnapshotDataSource_basic (51.49s)
=== CONT  TestAccEC2EBSSnapshotCreateVolumePermission_basic
--- PASS: TestAccEC2EBSSnapshotDataSource_mostRecent (96.66s)
=== CONT  TestAccEC2EBSSnapshotCopy_withKMS
--- PASS: TestAccEC2EBSSnapshotCopy_withKMS (66.34s)
=== CONT  TestAccEC2EBSSnapshotCopy_tags
--- PASS: TestAccEC2EBSSnapshotCreateVolumePermission_basic (84.36s)
=== CONT  TestAccEC2EBSSnapshotCopy_withRegions
--- PASS: TestAccEC2EBSSnapshotCopy_storageTier (134.02s)
=== CONT  TestAccEC2EBSSnapshotCopy_withDescription
--- PASS: TestAccEC2EBSSnapshotCopy_withRegions (66.56s)
=== CONT  TestAccEC2EBSSnapshotCopy_disappears
--- PASS: TestAccEC2EBSSnapshotCopy_tags (92.63s)
--- PASS: TestAccEC2EBSSnapshotCopy_withDescription (67.64s)
--- PASS: TestAccEC2EBSSnapshotCopy_disappears (67.14s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1561.248s
```

**Comment by ewbankkit** [comment]
@AndreKapraty Thanks for the contribution :tada: :clap:.

**Comment by AndreKapraty** [comment]
> @AndreKapraty Thanks for the contribution 🎉 👏.

Thanks for helping finish this PR)

**Pull request merged**
