### PR TITLE
resource/aws_network_interface: add support for interface_type argument for EFA

### LINKED ISSUE #8487: Elastic Fabric Adapter for EC2 instances
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

EFA network interfaces for EC2 instances [now](https://aws.amazon.com/about-aws/whats-new/2019/04/elastic-fabric-adapter-is-now-generally-available/) [available](https://aws.amazon.com/blogs/aws/now-available-elastic-fabric-adapter-efa-for-tightly-coupled-hpc-workloads/).

### LINKED ISSUE #18839: r/aws_network_interface add support for interface_type argument
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Allow the resource to indicate the type of network interface to create. Specifically, to create an Elastic Fabric Adapter (EFA), specify `efa` which is currently supported by the API. 

### New or Affected Resource(s)

* aws_network_interface

### Potential Terraform Configuration

```hcl
resource "aws_network_interface" "foo" {
  subnet_id         = aws_subnet.foo.id
  private_ips       = ["172.16.10.100"]
  interface_type    = "efa"
}
```

### References

* https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-eni.html#network-cards
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateNetworkInterface.html

### PR DESCRIPTION
**Pull request by farhanangullia**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18839.
Closes #8487.

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
enhancement:

resource/aws_network_interface: Add support for `interface_type` argument for EFA

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSENI_interfaceType'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSENI_interfaceType -timeout 180m


=== RUN   TestAccAWSENI_interfaceType_unspecifiedDefaultsToInterface
=== PAUSE TestAccAWSENI_interfaceType_unspecifiedDefaultsToInterface
=== RUN   TestAccAWSENI_interfaceType_efa
=== PAUSE TestAccAWSENI_interfaceType_efa
=== CONT  TestAccAWSENI_interfaceType_unspecifiedDefaultsToInterface
=== CONT  TestAccAWSENI_interfaceType_efa

--- PASS: TestAccAWSENI_interfaceType_efa (162.79s)
--- PASS: TestAccAWSENI_interfaceType_unspecifiedDefaultsToInterface (163.05s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       165.192s

...
```

### CODE REVIEW

**Comment by YakDriver** [comment]
@farhanangullia Thanks for this PR! After a quick scan, it looks good: implementation, tests, docs. 👍 Hopefully we'll have a chance for a full review soon.

**Comment by farhanangullia** [comment]
> @farhanangullia Thanks for this PR! After a quick scan, it looks good: implementation, tests, docs. 👍 Hopefully we'll have a chance for a full review soon.

Thanks @YakDriver, let me know if it requires refactoring! Cheers 😄

**Comment by farhanangullia** [comment]
Hi @YakDriver @ewbankkit, any chance of a review soon? :-)

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSENI_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSENI_ -timeout 180m
=== RUN   TestAccAWSENI_basic
=== PAUSE TestAccAWSENI_basic
=== RUN   TestAccAWSENI_IPv6
=== PAUSE TestAccAWSENI_IPv6
=== RUN   TestAccAWSENI_Tags
=== PAUSE TestAccAWSENI_Tags
=== RUN   TestAccAWSENI_IPv6Count
=== PAUSE TestAccAWSENI_IPv6Count
=== RUN   TestAccAWSENI_disappears
=== PAUSE TestAccAWSENI_disappears
=== RUN   TestAccAWSENI_Description
=== PAUSE TestAccAWSENI_Description
=== RUN   TestAccAWSENI_Attachment
=== PAUSE TestAccAWSENI_Attachment
=== RUN   TestAccAWSENI_IgnoreExternalAttachment
=== PAUSE TestAccAWSENI_IgnoreExternalAttachment
=== RUN   TestAccAWSENI_SourceDestCheck
=== PAUSE TestAccAWSENI_SourceDestCheck
=== RUN   TestAccAWSENI_PrivateIpsCount
=== PAUSE TestAccAWSENI_PrivateIpsCount
=== RUN   TestAccAWSENI_InterfaceType_efa
=== PAUSE TestAccAWSENI_InterfaceType_efa
=== CONT  TestAccAWSENI_basic
=== CONT  TestAccAWSENI_Attachment
=== CONT  TestAccAWSENI_InterfaceType_efa
--- PASS: TestAccAWSENI_basic (69.53s)
=== CONT  TestAccAWSENI_PrivateIpsCount
--- PASS: TestAccAWSENI_InterfaceType_efa (72.58s)
=== CONT  TestAccAWSENI_SourceDestCheck
--- PASS: TestAccAWSENI_Attachment (131.22s)
=== CONT  TestAccAWSENI_IgnoreExternalAttachment
--- PASS: TestAccAWSENI_SourceDestCheck (105.64s)
=== CONT  TestAccAWSENI_IPv6Count
--- PASS: TestAccAWSENI_PrivateIpsCount (128.04s)
=== CONT  TestAccAWSENI_Description
--- PASS: TestAccAWSENI_IgnoreExternalAttachment (126.87s)
=== CONT  TestAccAWSENI_disappears
--- PASS: TestAccAWSENI_Description (87.69s)
=== CONT  TestAccAWSENI_Tags
--- PASS: TestAccAWSENI_IPv6Count (123.78s)
=== CONT  TestAccAWSENI_IPv6
--- PASS: TestAccAWSENI_disappears (66.62s)
--- PASS: TestAccAWSENI_Tags (107.20s)
--- PASS: TestAccAWSENI_IPv6 (108.38s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	413.511s
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate_' ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSLaunchTemplate_ -timeout 180m
=== RUN   TestAccAWSLaunchTemplate_basic
=== PAUSE TestAccAWSLaunchTemplate_basic
=== RUN   TestAccAWSLaunchTemplate_Name_Generated
=== PAUSE TestAccAWSLaunchTemplate_Name_Generated
=== RUN   TestAccAWSLaunchTemplate_Name_Prefix
=== PAUSE TestAccAWSLaunchTemplate_Name_Prefix
=== RUN   TestAccAWSLaunchTemplate_disappears
=== PAUSE TestAccAWSLaunchTemplate_disappears
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3
=== RUN   TestAccAWSLaunchTemplate_EbsOptimized
=== PAUSE TestAccAWSLaunchTemplate_EbsOptimized
=== RUN   TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
=== PAUSE TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
=== RUN   TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
=== PAUSE TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
=== RUN   TestAccAWSLaunchTemplate_data
=== PAUSE TestAccAWSLaunchTemplate_data
=== RUN   TestAccAWSLaunchTemplate_description
=== PAUSE TestAccAWSLaunchTemplate_description
=== RUN   TestAccAWSLaunchTemplate_update
=== PAUSE TestAccAWSLaunchTemplate_update
=== RUN   TestAccAWSLaunchTemplate_Tags
=== PAUSE TestAccAWSLaunchTemplate_Tags
=== RUN   TestAccAWSLaunchTemplate_capacityReservation_preference
=== PAUSE TestAccAWSLaunchTemplate_capacityReservation_preference
=== RUN   TestAccAWSLaunchTemplate_capacityReservation_target
=== PAUSE TestAccAWSLaunchTemplate_capacityReservation_target
=== RUN   TestAccAWSLaunchTemplate_cpuOptions
=== PAUSE TestAccAWSLaunchTemplate_cpuOptions
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_t2
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_t2
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_t3
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_t3
=== RUN   TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== PAUSE TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== RUN   TestAccAWSLaunchTemplate_networkInterface
=== PAUSE TestAccAWSLaunchTemplate_networkInterface
=== RUN   TestAccAWSLaunchTemplate_networkInterfaceAddresses
=== PAUSE TestAccAWSLaunchTemplate_networkInterfaceAddresses
=== RUN   TestAccAWSLaunchTemplate_networkInterfaceType
=== PAUSE TestAccAWSLaunchTemplate_networkInterfaceType
=== RUN   TestAccAWSLaunchTemplate_associatePublicIPAddress
=== PAUSE TestAccAWSLaunchTemplate_associatePublicIPAddress
=== RUN   TestAccAWSLaunchTemplate_associateCarrierIPAddress
=== PAUSE TestAccAWSLaunchTemplate_associateCarrierIPAddress
=== RUN   TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn
=== PAUSE TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn
=== RUN   TestAccAWSLaunchTemplate_placement_partitionNum
=== PAUSE TestAccAWSLaunchTemplate_placement_partitionNum
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== RUN   TestAccAWSLaunchTemplate_instanceMarketOptions
=== PAUSE TestAccAWSLaunchTemplate_instanceMarketOptions
=== RUN   TestAccAWSLaunchTemplate_licenseSpecification
=== PAUSE TestAccAWSLaunchTemplate_licenseSpecification
=== RUN   TestAccAWSLaunchTemplate_metadataOptions
=== PAUSE TestAccAWSLaunchTemplate_metadataOptions
=== RUN   TestAccAWSLaunchTemplate_enclaveOptions
=== PAUSE TestAccAWSLaunchTemplate_enclaveOptions
=== RUN   TestAccAWSLaunchTemplate_hibernation
=== PAUSE TestAccAWSLaunchTemplate_hibernation
=== RUN   TestAccAWSLaunchTemplate_defaultVersion
=== PAUSE TestAccAWSLaunchTemplate_defaultVersion
=== RUN   TestAccAWSLaunchTemplate_updateDefaultVersion
=== PAUSE TestAccAWSLaunchTemplate_updateDefaultVersion
=== CONT  TestAccAWSLaunchTemplate_basic
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_t3
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t3 (15.67s)
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses (15.72s)
=== CONT  TestAccAWSLaunchTemplate_updateDefaultVersion
--- PASS: TestAccAWSLaunchTemplate_basic (15.78s)
=== CONT  TestAccAWSLaunchTemplate_metadataOptions
--- PASS: TestAccAWSLaunchTemplate_metadataOptions (14.64s)
=== CONT  TestAccAWSLaunchTemplate_licenseSpecification
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount (14.77s)
=== CONT  TestAccAWSLaunchTemplate_instanceMarketOptions
--- PASS: TestAccAWSLaunchTemplate_licenseSpecification (14.88s)
=== CONT  TestAccAWSLaunchTemplate_placement_partitionNum
--- PASS: TestAccAWSLaunchTemplate_updateDefaultVersion (45.01s)
=== CONT  TestAccAWSLaunchTemplate_defaultVersion
--- PASS: TestAccAWSLaunchTemplate_placement_partitionNum (28.71s)
=== CONT  TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn
--- PASS: TestAccAWSLaunchTemplate_instanceMarketOptions (58.23s)
=== CONT  TestAccAWSLaunchTemplate_hibernation
--- PASS: TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn (16.98s)
=== CONT  TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_defaultVersion (32.04s)
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_t2
--- PASS: TestAccAWSLaunchTemplate_data (15.03s)
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t2 (13.56s)
=== CONT  TestAccAWSLaunchTemplate_associateCarrierIPAddress
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_nonBurstable (13.57s)
=== CONT  TestAccAWSLaunchTemplate_enclaveOptions
--- PASS: TestAccAWSLaunchTemplate_hibernation (33.92s)
=== CONT  TestAccAWSLaunchTemplate_Tags
--- PASS: TestAccAWSLaunchTemplate_enclaveOptions (33.43s)
=== CONT  TestAccAWSLaunchTemplate_capacityReservation_target
--- PASS: TestAccAWSLaunchTemplate_Tags (33.33s)
=== CONT  TestAccAWSLaunchTemplate_cpuOptions
--- PASS: TestAccAWSLaunchTemplate_cpuOptions (11.04s)
=== CONT  TestAccAWSLaunchTemplate_update
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_target (17.51s)
=== CONT  TestAccAWSLaunchTemplate_associatePublicIPAddress
--- PASS: TestAccAWSLaunchTemplate_associateCarrierIPAddress (99.71s)
=== CONT  TestAccAWSLaunchTemplate_networkInterfaceType
--- PASS: TestAccAWSLaunchTemplate_networkInterfaceType (13.07s)
=== CONT  TestAccAWSLaunchTemplate_networkInterfaceAddresses
--- PASS: TestAccAWSLaunchTemplate_update (56.34s)
=== CONT  TestAccAWSLaunchTemplate_networkInterface
--- PASS: TestAccAWSLaunchTemplate_associatePublicIPAddress (98.08s)
=== CONT  TestAccAWSLaunchTemplate_description
--- PASS: TestAccAWSLaunchTemplate_networkInterfaceAddresses (59.14s)
=== CONT  TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
--- PASS: TestAccAWSLaunchTemplate_networkInterface (60.68s)
=== CONT  TestAccAWSLaunchTemplate_disappears
--- PASS: TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock (12.31s)
=== CONT  TestAccAWSLaunchTemplate_capacityReservation_preference
--- PASS: TestAccAWSLaunchTemplate_disappears (9.46s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_description (25.23s)
=== CONT  TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_preference (13.47s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3
--- PASS: TestAccAWSLaunchTemplate_ElasticInferenceAccelerator (23.33s)
=== CONT  TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (41.12s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3 (31.38s)
=== CONT  TestAccAWSLaunchTemplate_Name_Generated
--- PASS: TestAccAWSLaunchTemplate_Name_Generated (12.71s)
=== CONT  TestAccAWSLaunchTemplate_EbsOptimized
--- PASS: TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination (42.77s)
=== CONT  TestAccAWSLaunchTemplate_Name_Prefix
--- PASS: TestAccAWSLaunchTemplate_Name_Prefix (13.12s)
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (55.85s)
--- PASS: TestAccAWSLaunchTemplate_EbsOptimized (54.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	405.491s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSENI_' ACCTEST_PARALLELISM=3                  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSENI_ -timeout 180m
=== RUN   TestAccAWSENI_basic
=== PAUSE TestAccAWSENI_basic
=== RUN   TestAccAWSENI_IPv6
=== PAUSE TestAccAWSENI_IPv6
=== RUN   TestAccAWSENI_Tags
=== PAUSE TestAccAWSENI_Tags
=== RUN   TestAccAWSENI_IPv6Count
=== PAUSE TestAccAWSENI_IPv6Count
=== RUN   TestAccAWSENI_disappears
=== PAUSE TestAccAWSENI_disappears
=== RUN   TestAccAWSENI_Description
=== PAUSE TestAccAWSENI_Description
=== RUN   TestAccAWSENI_Attachment
=== PAUSE TestAccAWSENI_Attachment
=== RUN   TestAccAWSENI_IgnoreExternalAttachment
=== PAUSE TestAccAWSENI_IgnoreExternalAttachment
=== RUN   TestAccAWSENI_SourceDestCheck
=== PAUSE TestAccAWSENI_SourceDestCheck
=== RUN   TestAccAWSENI_PrivateIpsCount
=== PAUSE TestAccAWSENI_PrivateIpsCount
=== RUN   TestAccAWSENI_InterfaceType_efa
=== PAUSE TestAccAWSENI_InterfaceType_efa
=== CONT  TestAccAWSENI_basic
=== CONT  TestAccAWSENI_Attachment
=== CONT  TestAccAWSENI_IPv6Count
--- PASS: TestAccAWSENI_basic (72.40s)
=== CONT  TestAccAWSENI_Description
--- PASS: TestAccAWSENI_IPv6Count (137.92s)
=== CONT  TestAccAWSENI_Tags
--- PASS: TestAccAWSENI_Attachment (143.13s)
=== CONT  TestAccAWSENI_disappears
--- PASS: TestAccAWSENI_Description (97.96s)
=== CONT  TestAccAWSENI_IPv6
--- PASS: TestAccAWSENI_disappears (69.27s)
=== CONT  TestAccAWSENI_PrivateIpsCount
--- PASS: TestAccAWSENI_Tags (114.47s)
=== CONT  TestAccAWSENI_SourceDestCheck
--- PASS: TestAccAWSENI_IPv6 (115.33s)
=== CONT  TestAccAWSENI_InterfaceType_efa
--- PASS: TestAccAWSENI_PrivateIpsCount (142.18s)
=== CONT  TestAccAWSENI_IgnoreExternalAttachment
--- PASS: TestAccAWSENI_InterfaceType_efa (73.94s)
--- PASS: TestAccAWSENI_SourceDestCheck (116.47s)
--- PASS: TestAccAWSENI_IgnoreExternalAttachment (137.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	495.509s
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSLaunchTemplate_' ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 3 -run=TestAccAWSLaunchTemplate_ -timeout 180m
=== RUN   TestAccAWSLaunchTemplate_basic
=== PAUSE TestAccAWSLaunchTemplate_basic
=== RUN   TestAccAWSLaunchTemplate_Name_Generated
=== PAUSE TestAccAWSLaunchTemplate_Name_Generated
=== RUN   TestAccAWSLaunchTemplate_Name_Prefix
=== PAUSE TestAccAWSLaunchTemplate_Name_Prefix
=== RUN   TestAccAWSLaunchTemplate_disappears
=== PAUSE TestAccAWSLaunchTemplate_disappears
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
=== RUN   TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3
=== PAUSE TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3
=== RUN   TestAccAWSLaunchTemplate_EbsOptimized
=== PAUSE TestAccAWSLaunchTemplate_EbsOptimized
=== RUN   TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
=== PAUSE TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
=== RUN   TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
=== PAUSE TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
=== RUN   TestAccAWSLaunchTemplate_data
=== PAUSE TestAccAWSLaunchTemplate_data
=== RUN   TestAccAWSLaunchTemplate_description
=== PAUSE TestAccAWSLaunchTemplate_description
=== RUN   TestAccAWSLaunchTemplate_update
=== PAUSE TestAccAWSLaunchTemplate_update
=== RUN   TestAccAWSLaunchTemplate_Tags
=== PAUSE TestAccAWSLaunchTemplate_Tags
=== RUN   TestAccAWSLaunchTemplate_capacityReservation_preference
=== PAUSE TestAccAWSLaunchTemplate_capacityReservation_preference
=== RUN   TestAccAWSLaunchTemplate_capacityReservation_target
=== PAUSE TestAccAWSLaunchTemplate_capacityReservation_target
=== RUN   TestAccAWSLaunchTemplate_cpuOptions
=== PAUSE TestAccAWSLaunchTemplate_cpuOptions
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_t2
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_t2
=== RUN   TestAccAWSLaunchTemplate_creditSpecification_t3
=== PAUSE TestAccAWSLaunchTemplate_creditSpecification_t3
=== RUN   TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== PAUSE TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
=== RUN   TestAccAWSLaunchTemplate_networkInterface
=== PAUSE TestAccAWSLaunchTemplate_networkInterface
=== RUN   TestAccAWSLaunchTemplate_networkInterfaceAddresses
=== PAUSE TestAccAWSLaunchTemplate_networkInterfaceAddresses
=== RUN   TestAccAWSLaunchTemplate_networkInterfaceType
=== PAUSE TestAccAWSLaunchTemplate_networkInterfaceType
=== RUN   TestAccAWSLaunchTemplate_associatePublicIPAddress
=== PAUSE TestAccAWSLaunchTemplate_associatePublicIPAddress
=== RUN   TestAccAWSLaunchTemplate_associateCarrierIPAddress
=== PAUSE TestAccAWSLaunchTemplate_associateCarrierIPAddress
=== RUN   TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn
=== PAUSE TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn
=== RUN   TestAccAWSLaunchTemplate_placement_partitionNum
=== PAUSE TestAccAWSLaunchTemplate_placement_partitionNum
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
=== RUN   TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== PAUSE TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
=== RUN   TestAccAWSLaunchTemplate_instanceMarketOptions
=== PAUSE TestAccAWSLaunchTemplate_instanceMarketOptions
=== RUN   TestAccAWSLaunchTemplate_licenseSpecification
=== PAUSE TestAccAWSLaunchTemplate_licenseSpecification
=== RUN   TestAccAWSLaunchTemplate_metadataOptions
=== PAUSE TestAccAWSLaunchTemplate_metadataOptions
=== RUN   TestAccAWSLaunchTemplate_enclaveOptions
=== PAUSE TestAccAWSLaunchTemplate_enclaveOptions
=== RUN   TestAccAWSLaunchTemplate_hibernation
=== PAUSE TestAccAWSLaunchTemplate_hibernation
=== RUN   TestAccAWSLaunchTemplate_defaultVersion
=== PAUSE TestAccAWSLaunchTemplate_defaultVersion
=== RUN   TestAccAWSLaunchTemplate_updateDefaultVersion
=== PAUSE TestAccAWSLaunchTemplate_updateDefaultVersion
=== CONT  TestAccAWSLaunchTemplate_basic
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_t3
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t3 (20.97s)
=== CONT  TestAccAWSLaunchTemplate_updateDefaultVersion
--- PASS: TestAccAWSLaunchTemplate_basic (21.11s)
=== CONT  TestAccAWSLaunchTemplate_defaultVersion
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6AddressCount (21.12s)
=== CONT  TestAccAWSLaunchTemplate_hibernation
--- PASS: TestAccAWSLaunchTemplate_defaultVersion (44.92s)
=== CONT  TestAccAWSLaunchTemplate_enclaveOptions
--- PASS: TestAccAWSLaunchTemplate_hibernation (46.36s)
=== CONT  TestAccAWSLaunchTemplate_metadataOptions
--- PASS: TestAccAWSLaunchTemplate_updateDefaultVersion (58.79s)
=== CONT  TestAccAWSLaunchTemplate_licenseSpecification
--- PASS: TestAccAWSLaunchTemplate_metadataOptions (17.03s)
=== CONT  TestAccAWSLaunchTemplate_instanceMarketOptions
--- PASS: TestAccAWSLaunchTemplate_licenseSpecification (18.70s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination
--- PASS: TestAccAWSLaunchTemplate_enclaveOptions (44.99s)
=== CONT  TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination
--- PASS: TestAccAWSLaunchTemplate_instanceMarketOptions (56.14s)
=== CONT  TestAccAWSLaunchTemplate_ElasticInferenceAccelerator
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_DeleteOnTermination (61.63s)
=== CONT  TestAccAWSLaunchTemplate_EbsOptimized
--- PASS: TestAccAWSLaunchTemplate_NetworkInterfaces_DeleteOnTermination (57.46s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3
--- PASS: TestAccAWSLaunchTemplate_ElasticInferenceAccelerator (31.28s)
=== CONT  TestAccAWSLaunchTemplate_disappears
--- PASS: TestAccAWSLaunchTemplate_disappears (12.15s)
=== CONT  TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS_Gp3 (44.03s)
=== CONT  TestAccAWSLaunchTemplate_capacityReservation_target
--- PASS: TestAccAWSLaunchTemplate_BlockDeviceMappings_EBS (43.29s)
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_t2
--- PASS: TestAccAWSLaunchTemplate_EbsOptimized (71.50s)
=== CONT  TestAccAWSLaunchTemplate_creditSpecification_nonBurstable
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_target (21.28s)
=== CONT  TestAccAWSLaunchTemplate_cpuOptions
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_t2 (16.98s)
=== CONT  TestAccAWSLaunchTemplate_Name_Prefix
--- PASS: TestAccAWSLaunchTemplate_cpuOptions (14.37s)
=== CONT  TestAccAWSLaunchTemplate_Name_Generated
--- PASS: TestAccAWSLaunchTemplate_creditSpecification_nonBurstable (17.51s)
=== CONT  TestAccAWSLaunchTemplate_associatePublicIPAddress
--- PASS: TestAccAWSLaunchTemplate_Name_Prefix (17.02s)
=== CONT  TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses
--- PASS: TestAccAWSLaunchTemplate_Name_Generated (16.78s)
=== CONT  TestAccAWSLaunchTemplate_placement_partitionNum
--- PASS: TestAccAWSLaunchTemplate_networkInterface_ipv6Addresses (17.94s)
=== CONT  TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn
--- PASS: TestAccAWSLaunchTemplate_placement_partitionNum (35.47s)
=== CONT  TestAccAWSLaunchTemplate_associateCarrierIPAddress
--- PASS: TestAccAWSLaunchTemplate_Placement_HostResourceGroupArn (21.78s)
=== CONT  TestAccAWSLaunchTemplate_networkInterfaceAddresses
--- PASS: TestAccAWSLaunchTemplate_associatePublicIPAddress (107.83s)
=== CONT  TestAccAWSLaunchTemplate_networkInterfaceType
--- PASS: TestAccAWSLaunchTemplate_networkInterfaceAddresses (63.74s)
=== CONT  TestAccAWSLaunchTemplate_networkInterface
--- PASS: TestAccAWSLaunchTemplate_networkInterfaceType (16.77s)
=== CONT  TestAccAWSLaunchTemplate_Tags
--- PASS: TestAccAWSLaunchTemplate_associateCarrierIPAddress (107.68s)
=== CONT  TestAccAWSLaunchTemplate_capacityReservation_preference
--- PASS: TestAccAWSLaunchTemplate_Tags (43.41s)
=== CONT  TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock
--- PASS: TestAccAWSLaunchTemplate_capacityReservation_preference (16.54s)
=== CONT  TestAccAWSLaunchTemplate_update
--- PASS: TestAccAWSLaunchTemplate_networkInterface (61.98s)
=== CONT  TestAccAWSLaunchTemplate_description
--- PASS: TestAccAWSLaunchTemplate_IamInstanceProfile_EmptyConfigurationBlock (13.89s)
=== CONT  TestAccAWSLaunchTemplate_data
--- PASS: TestAccAWSLaunchTemplate_data (19.07s)
--- PASS: TestAccAWSLaunchTemplate_description (30.45s)
--- PASS: TestAccAWSLaunchTemplate_update (54.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	482.406s
```

**Comment by ewbankkit** [comment]
@farhanangullia Thanks for the contribution.
I went ahead and added the `aws_launch_template` support for `interface_type` so that the linked issue can be closed out.

**Pull request merged**
