### PR TITLE
Service Catalog PortfolioProductAssociation

### PR DESCRIPTION
**Pull request by ahgittin**
This PR adds support for the `aws_servicecatalog_portfolio_product_association`.

This part of the provisioned_product dependencies in #13797 and will be included there, but this PR has the changes for that one resource isolated for easier review, done in such a way that this PR can be merged on its own.  As a product association depends on product, this depends on and builds the PR for `aws_servicecatalog_product` #13834.  Once that is reviewed and merged the incremental difference in this PR should be much smaller.

All comments to date on #13797 (and lessons since then) have been incorporated here. This is ready for review.

## Community Note

Please vote on this pull request by adding a 👍 reaction to the original pull request comment to help the community and maintainers prioritize this request
Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

* Relates #13797
* Closes #4980
* Closes #13834

Release note for `CHANGELOG`:

New Resource: `aws_servicecatalog_portfolio_product_association`

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSServiceCatalogPortfolioProductAssociation' 2>&1 | tee x.log
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSServiceCatalogPortfolioProductAssociation -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSServiceCatalogPortfolioProductAssociation_basic
=== PAUSE TestAccAWSServiceCatalogPortfolioProductAssociation_basic
=== RUN   TestAccAWSServiceCatalogPortfolioProductAssociation_disappears
=== PAUSE TestAccAWSServiceCatalogPortfolioProductAssociation_disappears
=== RUN   TestAccAWSServiceCatalogPortfolioProductAssociation_Portfolio_update
=== PAUSE TestAccAWSServiceCatalogPortfolioProductAssociation_Portfolio_update
=== RUN   TestAccAWSServiceCatalogPortfolioProductAssociation_Product_update
=== PAUSE TestAccAWSServiceCatalogPortfolioProductAssociation_Product_update
=== RUN   TestAccAWSServiceCatalogPortfolioProductAssociation_update_all
=== PAUSE TestAccAWSServiceCatalogPortfolioProductAssociation_update_all
=== CONT  TestAccAWSServiceCatalogPortfolioProductAssociation_basic
=== CONT  TestAccAWSServiceCatalogPortfolioProductAssociation_Product_update
=== CONT  TestAccAWSServiceCatalogPortfolioProductAssociation_Portfolio_update
=== CONT  TestAccAWSServiceCatalogPortfolioProductAssociation_disappears
=== CONT  TestAccAWSServiceCatalogPortfolioProductAssociation_update_all
2020/06/22 11:25:05 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio.test-eazpm (prepare state)
2020/06/22 11:25:05 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket.bucket (prepare state)
2020/06/22 11:25:05 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio_product_association.test (prepare state)
2020/06/22 11:25:05 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket_object.template1 (prepare state)
2020/06/22 11:25:05 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_product.test-eazpm (prepare state)
2020/06/22 11:25:05 DestroyEdgeTransformer: pruning unused resource node data.aws_region.current (prepare state)
2020/06/22 11:25:06 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket_object.template1 (prepare state)
2020/06/22 11:25:06 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket.bucket (prepare state)
2020/06/22 11:25:06 DestroyEdgeTransformer: pruning unused resource node data.aws_region.current (prepare state)
--- PASS: TestAccAWSServiceCatalogPortfolioProductAssociation_basic (35.12s)
--- PASS: TestAccAWSServiceCatalogPortfolioProductAssociation_disappears (35.68s)
2020/06/22 11:25:22 DestroyEdgeTransformer: pruning unused resource node data.aws_region.current (prepare state)
2020/06/22 11:25:22 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket_object.template1 (prepare state)
2020/06/22 11:25:22 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_product.test-fj26p (prepare state)
2020/06/22 11:25:22 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio_product_association.test (prepare state)
2020/06/22 11:25:22 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio.test-xib20 (prepare state)
2020/06/22 11:25:22 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket.bucket (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket_object.template1 (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio_product_association.test (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node data.aws_region.current (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio.test-zrhp2 (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_product.test-zrhp2 (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket.bucket (prepare state)
--- PASS: TestAccAWSServiceCatalogPortfolioProductAssociation_Portfolio_update (54.33s)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket.bucket (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_s3_bucket_object.template1 (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio.test-i2we2 (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_product.test-wkjqo (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio_product_association.test (prepare state)
2020/06/22 11:25:29 DestroyEdgeTransformer: pruning unused resource node data.aws_region.current (prepare state)
--- PASS: TestAccAWSServiceCatalogPortfolioProductAssociation_update_all (60.20s)
--- PASS: TestAccAWSServiceCatalogPortfolioProductAssociation_Product_update (60.55s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	62.023s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.499s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.315s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	0.488s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/apigatewayv2/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	0.334s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ecs/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	0.532s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/guardduty/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/iam/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kinesisanalytics/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kms/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/neptune/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/rds/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/secretsmanager/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/servicediscovery/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/workspaces/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource	0.691s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/helper/awsprovidertype/keyvaluetags	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	0.925s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	1.107s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	0.461s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR002	0.320s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr	0.233s [no tests to run]
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by ahgittin** [comment]
This has been updated as per the 18 Aug notification to use the v2 sdk and remove `aws.erb` (fixing the conflicts), and also updating to conform to the stricter markdown checks.

**Comment by YakDriver** [comment]
@ahgittin Thank you for your work on this PR! I will be working on this before long. In order to expedite the process, I will likely make some changes. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Comment by YakDriver** [comment]
@ahgittin @cloudsoft Thank you very much for all your work on this PR! I'm excited to work with you on this. However, in order to work with this PR, I need two things:

1. You must check the "Allow edits from maintainers" box. It is currently not checked. (Only @cloudsoft will be able to check the box since the fork with this branch is in the @cloudsoft repo.)
2. Currently there are 112 commits, many of which significantly rewrite the branch. All 112 commits need to be squashed into a single commit to proceed.

Since we look forward to adding this feature to the AWS Provider, we need you to make these changes by March 11, 2021. If you are unable to do this, we understand and thank you for your work. However, we will not be able to use this contribution.

**Comment by ahgittin** [comment]
Replaced by https://github.com/hashicorp/terraform-provider-aws/pull/18074

**Pull request closed without merging**
