### PR TITLE
r/aws_cloudwatch_log_group: Remove default value (`STANDARD`) for `log_group_class` argument and mark as Computed

### PR DESCRIPTION
**Pull request by ewbankkit**
### Description

Change `aws_cloudwatch_log_group.log_group_class` to [`Computed`](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#computed) as it's not (yet) supported in AWS GovCloud (US) or AWS China. 

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34810.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34809.

#### AWS Commercial

```console
% make testacc TESTARGS='-run=TestAccLogsGroup_\|TestAccLogsGroupDataSource_' PKG=logs ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 3  -run=TestAccLogsGroup_\|TestAccLogsGroupDataSource_ -timeout 360m
=== RUN   TestAccLogsGroupDataSource_basic
=== PAUSE TestAccLogsGroupDataSource_basic
=== RUN   TestAccLogsGroup_basic
=== PAUSE TestAccLogsGroup_basic
=== RUN   TestAccLogsGroup_nameGenerate
=== PAUSE TestAccLogsGroup_nameGenerate
=== RUN   TestAccLogsGroup_namePrefix
=== PAUSE TestAccLogsGroup_namePrefix
=== RUN   TestAccLogsGroup_disappears
=== PAUSE TestAccLogsGroup_disappears
=== RUN   TestAccLogsGroup_tags
=== PAUSE TestAccLogsGroup_tags
=== RUN   TestAccLogsGroup_kmsKey
=== PAUSE TestAccLogsGroup_kmsKey
=== RUN   TestAccLogsGroup_logGroupClass
=== PAUSE TestAccLogsGroup_logGroupClass
=== RUN   TestAccLogsGroup_retentionPolicy
=== PAUSE TestAccLogsGroup_retentionPolicy
=== RUN   TestAccLogsGroup_multiple
=== PAUSE TestAccLogsGroup_multiple
=== RUN   TestAccLogsGroup_skipDestroy
=== PAUSE TestAccLogsGroup_skipDestroy
=== CONT  TestAccLogsGroupDataSource_basic
=== CONT  TestAccLogsGroup_kmsKey
=== CONT  TestAccLogsGroup_namePrefix
--- PASS: TestAccLogsGroupDataSource_basic (15.62s)
=== CONT  TestAccLogsGroup_tags
--- PASS: TestAccLogsGroup_namePrefix (25.85s)
=== CONT  TestAccLogsGroup_nameGenerate
--- PASS: TestAccLogsGroup_nameGenerate (24.97s)
=== CONT  TestAccLogsGroup_multiple
--- PASS: TestAccLogsGroup_kmsKey (62.33s)
=== CONT  TestAccLogsGroup_logGroupClass
--- PASS: TestAccLogsGroup_tags (54.93s)
=== CONT  TestAccLogsGroup_skipDestroy
--- PASS: TestAccLogsGroup_multiple (18.86s)
=== CONT  TestAccLogsGroup_disappears
--- PASS: TestAccLogsGroup_logGroupClass (19.89s)
=== CONT  TestAccLogsGroup_retentionPolicy
--- PASS: TestAccLogsGroup_skipDestroy (21.16s)
=== CONT  TestAccLogsGroup_basic
--- PASS: TestAccLogsGroup_disappears (23.18s)
--- PASS: TestAccLogsGroup_basic (24.58s)
--- PASS: TestAccLogsGroup_retentionPolicy (50.51s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/logs	138.605s
```

#### AWS GovCloud (US)

```console
% make testacc TESTARGS='-run=TestAccLogsGroup_\|TestAccLogsGroupDataSource_' PKG=logs ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 3  -run=TestAccLogsGroup_\|TestAccLogsGroupDataSource_ -timeout 360m
=== RUN   TestAccLogsGroupDataSource_basic
=== PAUSE TestAccLogsGroupDataSource_basic
=== RUN   TestAccLogsGroup_basic
=== PAUSE TestAccLogsGroup_basic
=== RUN   TestAccLogsGroup_nameGenerate
=== PAUSE TestAccLogsGroup_nameGenerate
=== RUN   TestAccLogsGroup_namePrefix
=== PAUSE TestAccLogsGroup_namePrefix
=== RUN   TestAccLogsGroup_disappears
=== PAUSE TestAccLogsGroup_disappears
=== RUN   TestAccLogsGroup_tags
=== PAUSE TestAccLogsGroup_tags
=== RUN   TestAccLogsGroup_kmsKey
=== PAUSE TestAccLogsGroup_kmsKey
=== RUN   TestAccLogsGroup_logGroupClass
=== PAUSE TestAccLogsGroup_logGroupClass
=== RUN   TestAccLogsGroup_retentionPolicy
=== PAUSE TestAccLogsGroup_retentionPolicy
=== RUN   TestAccLogsGroup_multiple
=== PAUSE TestAccLogsGroup_multiple
=== RUN   TestAccLogsGroup_skipDestroy
=== PAUSE TestAccLogsGroup_skipDestroy
=== CONT  TestAccLogsGroupDataSource_basic
=== CONT  TestAccLogsGroup_kmsKey
=== CONT  TestAccLogsGroup_namePrefix
--- PASS: TestAccLogsGroupDataSource_basic (18.43s)
=== CONT  TestAccLogsGroup_disappears
--- PASS: TestAccLogsGroup_namePrefix (22.45s)
=== CONT  TestAccLogsGroup_nameGenerate
--- PASS: TestAccLogsGroup_disappears (18.45s)
=== CONT  TestAccLogsGroup_basic
--- PASS: TestAccLogsGroup_nameGenerate (21.73s)
=== CONT  TestAccLogsGroup_multiple
--- PASS: TestAccLogsGroup_kmsKey (57.87s)
=== CONT  TestAccLogsGroup_skipDestroy
--- PASS: TestAccLogsGroup_basic (22.51s)
=== CONT  TestAccLogsGroup_retentionPolicy
--- PASS: TestAccLogsGroup_multiple (19.95s)
=== CONT  TestAccLogsGroup_logGroupClass
    acctest.go:943: skipping tests; current partition (aws-us-gov) does not equal aws
--- SKIP: TestAccLogsGroup_logGroupClass (0.00s)
=== CONT  TestAccLogsGroup_tags
--- PASS: TestAccLogsGroup_skipDestroy (24.48s)
--- PASS: TestAccLogsGroup_retentionPolicy (57.80s)
--- PASS: TestAccLogsGroup_tags (56.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/logs	126.358s
```

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc TESTARGS='-run=TestAccLogsGroup_\|TestAccLogsGroupDataSource_' PKG=logs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/logs/... -v -count 1 -parallel 20  -run=TestAccLogsGroup_\|TestAccLogsGroupDataSource_ -timeout 360m

--- PASS: TestAccLogsGroup_skipDestroy (53.28s)
--- PASS: TestAccLogsGroup_logGroupClass (55.78s)
--- PASS: TestAccLogsGroup_disappears (57.11s)
--- PASS: TestAccLogsGroup_basic (59.83s)
--- PASS: TestAccLogsGroup_nameGenerate (60.35s)
--- PASS: TestAccLogsGroup_namePrefix (60.49s)
--- PASS: TestAccLogsGroup_multiple (61.68s)
--- PASS: TestAccLogsGroupDataSource_basic (71.37s)
--- PASS: TestAccLogsGroup_tags (96.51s)
--- PASS: TestAccLogsGroup_retentionPolicy (96.67s)
--- PASS: TestAccLogsGroup_kmsKey (122.83s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/logs       126.177s
```

**Comment by raisullip** [comment]
👍

**Comment by gabrielmattern** [comment]
👍

**Comment by karolytanczos-govcio** [comment]
Yesterday and today we tried to deploy an ECS service on GovCloud and it failed with the following message:
`- InvalidParameterException: Only Standard log class is supported.`

Prior to fail creating the service the following message was printed about the CloudWatch:
```
# module.xxx-xxx-xxx.aws_cloudwatch_log_group.log-group will be created
  + resource "aws_cloudwatch_log_group" "log-group" {
      + arn               = (known after apply)
      + id                = (known after apply)
      + log_group_class   = "STANDARD"
      + name              = "/ecs/xxxx-xxxx-xxxx"
      + name_prefix       = (known after apply)
      + retention_in_days = 0
      + skip_destroy      = false
```

I'm confused, should it be `Standard` or `Computed`?

**Comment by michael-miara** [comment]
> Yesterday and today we tried to deploy an ECS service on GovCloud and it failed with the following message: `- InvalidParameterException: Only Standard log class is supported.`
> 
> Prior to fail creating the service the following message was printed about the CloudWatch:
> 
> ```
> # module.xxx-xxx-xxx.aws_cloudwatch_log_group.log-group will be created
>   + resource "aws_cloudwatch_log_group" "log-group" {
>       + arn               = (known after apply)
>       + id                = (known after apply)
>       + log_group_class   = "STANDARD"
>       + name              = "/ecs/xxxx-xxxx-xxxx"
>       + name_prefix       = (known after apply)
>       + retention_in_days = 0
>       + skip_destroy      = false
> ```
> 
> I'm confused, should it be `Standard` or `Computed`?

i am still seeing this as well

**Comment by karolytanczos-govcio** [comment]
> > Yesterday and today we tried to deploy an ECS service on GovCloud and it failed with the following message: `- InvalidParameterException: Only Standard log class is supported.`
> > Prior to fail creating the service the following message was printed about the CloudWatch:
> > ```
> > # module.xxx-xxx-xxx.aws_cloudwatch_log_group.log-group will be created
> >   + resource "aws_cloudwatch_log_group" "log-group" {
> >       + arn               = (known after apply)
> >       + id                = (known after apply)
> >       + log_group_class   = "STANDARD"
> >       + name              = "/ecs/xxxx-xxxx-xxxx"
> >       + name_prefix       = (known after apply)
> >       + retention_in_days = 0
> >       + skip_destroy      = false
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > I'm confused, should it be `Standard` or `Computed`?
> 
> i am still seeing this as well

We implemented a workaround for this bug. We hardcoded the Terraform version under the required_provider section. The last known stable version was 5.26.0:
```
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "5.26.0"
    }
```
Version 5.30.0 is still failing.

**Pull request merged**
