### PR TITLE
WAFv2: Added support for custom response bodies

### LINKED ISSUE #18754: AWS WAF v2 custom response body [feature request]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You can instruct AWS WAF to send a custom HTTP response back to the client for rule actions or web ACL default actions that are set to block the request. Currently this configuration is not supported in Terraform.

### New or Affected Resource(s)

New Resource: aws_wafv2_response_body (?)
Affected Resource: aws_wafv2_web_acl, aws_wafv2_rule_group

### References
https://docs.aws.amazon.com/waf/latest/developerguide/customizing-the-response-for-blocked-requests.html

### PR DESCRIPTION
**Pull request by andyalm**
This adds support for adding custom response bodies to both the `aws_wafv2_web_acl` and `aws_wafv2_rule_group` resources. Here is an example:

```
resource "aws_wafv2_rule_group" "test" {
  name     = "sample-rule"
  scope    = "REGIONAL"

  custom_response_body {
    key          = "test_body_1"
    content      = "test response 1"
    content_type = "TEXT_PLAIN"
  }

  custom_response_body {
    key          = "throttled"
    content      = "<html><body>you have been throttled</body></html>"
    content_type = "TEXT_HTML"
  }

  rule {
    name     = "rule-1"
    priority = 1

    action {
      block {
        custom_response {
          response_code = 429
          custom_response_body_key = "throttled"
        }
      }
    }

    statement {
      geo_match_statement {
        country_codes = ["US", "NL"]
      }
    }
  }
}
```

This is marked as a draft as I still need to update the documentation and release notes.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #18754

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsWafv2WebACL_.+'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsWafv2WebACL_.+ -timeout 180m
=== RUN   TestAccAwsWafv2WebACL_basic
=== PAUSE TestAccAwsWafv2WebACL_basic
=== RUN   TestAccAwsWafv2WebACL_updateRule
=== PAUSE TestAccAwsWafv2WebACL_updateRule
=== RUN   TestAccAwsWafv2WebACL_UpdateRuleProperties
=== PAUSE TestAccAwsWafv2WebACL_UpdateRuleProperties
=== RUN   TestAccAwsWafv2WebACL_ChangeNameForceNew
=== PAUSE TestAccAwsWafv2WebACL_ChangeNameForceNew
=== RUN   TestAccAwsWafv2WebACL_Disappears
=== PAUSE TestAccAwsWafv2WebACL_Disappears
=== RUN   TestAccAwsWafv2WebACL_ManagedRuleGroupStatement
=== PAUSE TestAccAwsWafv2WebACL_ManagedRuleGroupStatement
=== RUN   TestAccAwsWafv2WebACL_Minimal
=== PAUSE TestAccAwsWafv2WebACL_Minimal
=== RUN   TestAccAwsWafv2WebACL_RateBasedStatement
=== PAUSE TestAccAwsWafv2WebACL_RateBasedStatement
=== RUN   TestAccAwsWafv2WebACL_GeoMatchStatement
=== PAUSE TestAccAwsWafv2WebACL_GeoMatchStatement
=== RUN   TestAccAwsWafv2WebACL_GeoMatchStatement_ForwardedIPConfig
=== PAUSE TestAccAwsWafv2WebACL_GeoMatchStatement_ForwardedIPConfig
=== RUN   TestAccAwsWafv2WebACL_IPSetReferenceStatement
=== PAUSE TestAccAwsWafv2WebACL_IPSetReferenceStatement
=== RUN   TestAccAwsWafv2WebACL_IPSetReferenceStatement_IPSetForwardedIPConfig
=== PAUSE TestAccAwsWafv2WebACL_IPSetReferenceStatement_IPSetForwardedIPConfig
=== RUN   TestAccAwsWafv2WebACL_RateBasedStatement_ForwardedIPConfig
=== PAUSE TestAccAwsWafv2WebACL_RateBasedStatement_ForwardedIPConfig
=== RUN   TestAccAwsWafv2WebACL_RuleGroupReferenceStatement
=== PAUSE TestAccAwsWafv2WebACL_RuleGroupReferenceStatement
=== RUN   TestAccAwsWafv2WebACL_CustomRequestHandling
=== PAUSE TestAccAwsWafv2WebACL_CustomRequestHandling
=== RUN   TestAccAwsWafv2WebACL_CustomResponse
=== PAUSE TestAccAwsWafv2WebACL_CustomResponse
=== RUN   TestAccAwsWafv2WebACL_Tags
=== PAUSE TestAccAwsWafv2WebACL_Tags
=== RUN   TestAccAwsWafv2WebACL_MaxNestedRateBasedStatements
=== PAUSE TestAccAwsWafv2WebACL_MaxNestedRateBasedStatements
=== RUN   TestAccAwsWafv2WebACL_MaxNestedOperatorStatements
=== PAUSE TestAccAwsWafv2WebACL_MaxNestedOperatorStatements
=== CONT  TestAccAwsWafv2WebACL_basic
=== CONT  TestAccAwsWafv2WebACL_IPSetReferenceStatement
=== CONT  TestAccAwsWafv2WebACL_ManagedRuleGroupStatement
=== CONT  TestAccAwsWafv2WebACL_MaxNestedOperatorStatements
=== CONT  TestAccAwsWafv2WebACL_MaxNestedRateBasedStatements
=== CONT  TestAccAwsWafv2WebACL_Tags
=== CONT  TestAccAwsWafv2WebACL_CustomResponse
=== CONT  TestAccAwsWafv2WebACL_CustomRequestHandling
=== CONT  TestAccAwsWafv2WebACL_RuleGroupReferenceStatement
=== CONT  TestAccAwsWafv2WebACL_RateBasedStatement_ForwardedIPConfig
=== CONT  TestAccAwsWafv2WebACL_IPSetReferenceStatement_IPSetForwardedIPConfig
=== CONT  TestAccAwsWafv2WebACL_GeoMatchStatement_ForwardedIPConfig
=== CONT  TestAccAwsWafv2WebACL_RateBasedStatement
=== CONT  TestAccAwsWafv2WebACL_ChangeNameForceNew
=== CONT  TestAccAwsWafv2WebACL_Disappears
=== CONT  TestAccAwsWafv2WebACL_UpdateRuleProperties
=== CONT  TestAccAwsWafv2WebACL_Minimal
=== CONT  TestAccAwsWafv2WebACL_updateRule
=== CONT  TestAccAwsWafv2WebACL_GeoMatchStatement
--- PASS: TestAccAwsWafv2WebACL_Minimal (47.10s)
--- PASS: TestAccAwsWafv2WebACL_Disappears (59.21s)
--- PASS: TestAccAwsWafv2WebACL_MaxNestedRateBasedStatements (73.74s)
--- PASS: TestAccAwsWafv2WebACL_IPSetReferenceStatement (84.03s)
--- PASS: TestAccAwsWafv2WebACL_ManagedRuleGroupStatement (91.26s)
--- PASS: TestAccAwsWafv2WebACL_RateBasedStatement (95.62s)
--- PASS: TestAccAwsWafv2WebACL_RateBasedStatement_ForwardedIPConfig (101.08s)
--- PASS: TestAccAwsWafv2WebACL_CustomRequestHandling (106.03s)
--- PASS: TestAccAwsWafv2WebACL_GeoMatchStatement (108.89s)
--- PASS: TestAccAwsWafv2WebACL_MaxNestedOperatorStatements (116.30s)
--- PASS: TestAccAwsWafv2WebACL_CustomResponse (121.01s)
--- PASS: TestAccAwsWafv2WebACL_UpdateRuleProperties (130.49s)
--- PASS: TestAccAwsWafv2WebACL_RuleGroupReferenceStatement (137.94s)
--- PASS: TestAccAwsWafv2WebACL_IPSetReferenceStatement_IPSetForwardedIPConfig (145.30s)
--- PASS: TestAccAwsWafv2WebACL_GeoMatchStatement_ForwardedIPConfig (148.79s)
--- PASS: TestAccAwsWafv2WebACL_ChangeNameForceNew (162.43s)
--- PASS: TestAccAwsWafv2WebACL_basic (168.00s)
--- PASS: TestAccAwsWafv2WebACL_updateRule (169.22s)
--- PASS: TestAccAwsWafv2WebACL_Tags (188.27s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       189.630s
```

### CODE REVIEW

**Comment by tylerhjones** [comment]
30 days open on this pr, a missing feature set for sure. thanks @andyalm for doing this work.

**Comment by anewton1980** [comment]
this is exactly what I am looking for, any update on when this will be released?

**Comment by dcastroma** [comment]
Good enhanced by @andyalm and very useful, but lost because nobody review it.

**Comment by KFoxder** [comment]
@andyalm thanks for doing this... would love to use this. Not sure how we can help prioritize it. Let me now if there is anything we can do to help move this along.

**Comment by jonnyshaw89** [comment]
We need this feature!
What is blocking this being merged?

**Comment by andyalm** [comment]
@KFoxder @jonnyshaw89 thanks for chiming in. I wish I knew how to get a review on this change. I've got two PR's that have been open for more than a month. As far as I know, I have done all of the steps on the checklist to get a review. From time to time, I have to resolve conflicts that appear in `main`. I just did that again so it should be ready to merge again, if we can figure out how to get some eyes on it from a reviewer.

**Comment by KFoxder** [comment]
@bflad @breathingdust @YakDriver Is there any way we can help prioritize a review on this?

**Comment by hoebelix** [comment]
We need this feature too! Maybe the problem is that there is no open issue for this? The original issue https://github.com/hashicorp/terraform-provider-aws/issues/18754 is closed although this PR is not merged yet. Can anybody reopen this issue please?

**Comment by jemstep-kerry** [comment]
@hc-github-team-terraform-aws Please could we get a review on this?
Thank you for all your great work!

**Comment by n00borama** [comment]
Please review, in much need of this also.  Thanks.

**Comment by anewton1980** [comment]
is this available in the current release ?

**Comment by iokiwi** [comment]
Also here because I need this missing feature. @hc-github-team-terraform-aws if you are going to offload the burden of feature development and maintenance to the community, at least don't stand in the way of the community to get things merged and released.

**Comment by MumakiI** [comment]
Folks, how is that possible to expedite this? We need the feature very much!!!

**Comment by andyalm** [comment]
Thanks for the heads up @zhelding. I've updated my changes to work with the new file structure and its passing all checks again. Is there anything else I need to do to get a review?

**Comment by zhelding** [comment]
Hi @andyalm. No further action is required on your end for merging this pull request.

This pull request will now be addressed via our standard prioritization process. Unfortunately, given the large quantity of issues and pull requests we receive, we are not always able to review every pull request in a timely manner.

We prioritize contributions that provide the greatest value to the largest number of users -- which we primarily infer based on the number of :thumbsup: [reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/).  Additionally, an explanation of the particular use case for a contribution can provide information on how the changes might be useful in a broader context.

You can get a view of the wider development plans for the provider via our [road map](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md), published quarterly.

Thank you again for your contribution and your patience.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by anGie44** [comment]
Thanks again @andyalm for contributing to this feature! 🚀 

Output of acceptance tests:
```
--- PASS: TestAccWAFV2WebACL_disappears (387.50s)
--- PASS: TestAccWAFV2WebACL_minimal (698.41s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_forwardedIP (1147.57s)
--- PASS: TestAccWAFV2WebACL_RateBased_maxNested (1428.77s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_basic (1479.46s)
--- PASS: TestAccWAFV2WebACL_RateBased_forwardedIP (1479.55s)
--- PASS: TestAccWAFV2WebACL_Update_nameForceNew (1600.82s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_basic (1978.72s)
--- PASS: TestAccWAFV2WebACL_Custom_response (2023.12s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_basic (2032.84s)
--- PASS: TestAccWAFV2WebACL_tags (2033.49s)
--- PASS: TestAccWAFV2WebACL_Custom_requestHandling (2033.68s)
--- PASS: TestAccWAFV2WebACL_Update_ruleProperties (2033.93s)
--- PASS: TestAccWAFV2WebACL_basic (2043.04s)
--- PASS: TestAccWAFV2WebACL_RateBased_basic (2084.49s)
--- PASS: TestAccWAFV2WebACL_Update_rule (2098.01s)
--- PASS: TestAccWAFV2WebACL_RuleGroupReference_basic (2110.78s)
--- PASS: TestAccWAFV2WebACL_Operators_maxNested (2126.08s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_forwardedIP (2157.08s)

--- PASS: TestAccWAFV2RuleGroup_disappears (294.35s)
--- PASS: TestAccWAFV2RuleGroup_ipSetReferenceStatement (1131.80s)
--- PASS: TestAccWAFV2RuleGroup_minimal (1325.96s)
--- PASS: TestAccWAFV2RuleGroup_regexPatternSetReferenceStatement (1371.22s)
--- PASS: TestAccWAFV2RuleGroup_sizeConstraintStatement (1586.00s)
--- PASS: TestAccWAFV2RuleGroup_xssMatchStatement (1680.39s)
--- PASS: TestAccWAFV2RuleGroup_changeMetricNameForceNew (1707.50s)
--- PASS: TestAccWAFV2RuleGroup_updateRuleProperties (1709.58s)
--- PASS: TestAccWAFV2RuleGroup_GeoMatchStatement_forwardedIP (1742.71s)
--- PASS: TestAccWAFV2RuleGroup_changeNameForceNew (1763.20s)
--- PASS: TestAccWAFV2RuleGroupDataSource_basic (1763.22s)
--- PASS: TestAccWAFV2RuleGroup_RuleAction_customRequestHandling (1763.30s)
--- PASS: TestAccWAFV2RuleGroup_geoMatchStatement (1867.83s)
--- PASS: TestAccWAFV2RuleGroup_updateRule (1912.48s)
--- PASS: TestAccWAFV2RuleGroup_basic (542.82s)
--- PASS: TestAccWAFV2RuleGroup_tags (1962.77s)
--- PASS: TestAccWAFV2RuleGroup_sqliMatchStatement (1963.73s)
--- PASS: TestAccWAFV2RuleGroup_RuleAction_customResponse (2017.13s)
--- PASS: TestAccWAFV2RuleGroup_byteMatchStatement (886.62s)
--- PASS: TestAccWAFV2RuleGroup_logicalRuleStatements (2068.75s)
--- PASS: TestAccWAFV2RuleGroup_ruleAction (2094.63s)
--- PASS: TestAccWAFV2RuleGroup_changeCapacityForceNew (2109.83s)
--- PASS: TestAccWAFV2RuleGroup_IPSetReferenceStatement_ipsetForwardedIP (804.92s)
--- PASS: TestAccWAFV2RuleGroup_ByteMatchStatement_fieldToMatch (1860.17s)
```

**Pull request merged**
