### PR TITLE
Use proper name for networking term Statmux

### PR DESCRIPTION
**Pull request by dkujawski**
### Description
Statmux is a shortened name for Statistical Multiplexing

Rename code references from `statemux` and `Statemux` to `statmux` and `Statmux` respectively.

### Relations

Relates #4936

### References

See: 
- https://en.wikipedia.org/wiki/Statistical_time-division_multiplexing
- https://aws.amazon.com/medialive/features/statmux/
### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccMediaLive_serial PKG=medialive

...
```

### CODE REVIEW

**Review by bschaatsbergen — APPROVED** [review]
LGTM :rocket: (needs a few test runs and a core member to validate this)

**Comment by dkujawski** [comment]
It would be a breaking change.  Going to update to deprecate the miss-spelled argument and add the correct.  Should have this updated first thing next week.

**Comment by johnsonaj** [comment]
```console
$ make testacc TESTARGS='-run=TestAccMediaLive_serial/MultiplexProgram' PKG=medialive
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLive_serial/MultiplexProgram -timeout 180m
=== RUN   TestAccMediaLive_serial
=== RUN   TestAccMediaLive_serial/MultiplexProgram
=== RUN   TestAccMediaLive_serial/MultiplexProgram/basic
=== RUN   TestAccMediaLive_serial/MultiplexProgram/update
=== RUN   TestAccMediaLive_serial/MultiplexProgram/disappears
--- PASS: TestAccMediaLive_serial (216.11s)
    --- PASS: TestAccMediaLive_serial/MultiplexProgram (216.11s)
        --- PASS: TestAccMediaLive_serial/MultiplexProgram/basic (57.51s)
        --- PASS: TestAccMediaLive_serial/MultiplexProgram/update (102.30s)
        --- PASS: TestAccMediaLive_serial/MultiplexProgram/disappears (56.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	218.660s
```

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀

**Pull request merged**
