### PR TITLE
Rolesanywhere trustanchor resource

### PR DESCRIPTION
**Pull request by mattburgess**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #25727

Output from acceptance testing:

```
$ make testacc TESTS=TestAccRolesAnywhereTrustAnchor PKG=rolesanywhere
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rolesanywhere/... -v -count 1 -parallel 20 -run='TestAccRolesAnywhereTrustAnchor'  -timeout 180m
=== RUN   TestAccRolesAnywhereTrustAnchor_basic
--- PASS: TestAccRolesAnywhereTrustAnchor_basic (24.65s)
=== RUN   TestAccRolesAnywhereTrustAnchor_tags
--- PASS: TestAccRolesAnywhereTrustAnchor_tags (40.93s)
=== RUN   TestAccRolesAnywhereTrustAnchor_disappears
--- PASS: TestAccRolesAnywhereTrustAnchor_disappears (17.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rolesanywhere	83.333s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@mattburgess It looks like `RolesAnywhereConn` isn't being initialized in `internal/conns/config_gen.go` and hence is `nil`, causing the panic.

**Comment by mattburgess** [comment]
> @mattburgess It looks like `RolesAnywhereConn` isn't being initialized in `internal/conns/config_gen.go` and hence is `nil`, causing the panic.

Awesome, thanks @ewbankkit. I'd completely forgotten I'd had to mark client-gen to be skipped in the names csv file! I've followed the same pattern as Kendra in `config.go` and that's got things to the point where it's trying to actually create resources. I'm hoping to have this PR ready in the next couple of days.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRolesAnywhereTrustAnchor_' PKG=rolesanywhere ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rolesanywhere/... -v -count 1 -parallel 2  -run=TestAccRolesAnywhereTrustAnchor_ -timeout 180m
=== RUN   TestAccRolesAnywhereTrustAnchor_basic
=== PAUSE TestAccRolesAnywhereTrustAnchor_basic
=== RUN   TestAccRolesAnywhereTrustAnchor_tags
=== PAUSE TestAccRolesAnywhereTrustAnchor_tags
=== RUN   TestAccRolesAnywhereTrustAnchor_disappears
=== PAUSE TestAccRolesAnywhereTrustAnchor_disappears
=== RUN   TestAccRolesAnywhereTrustAnchor_certificateBundle
=== PAUSE TestAccRolesAnywhereTrustAnchor_certificateBundle
=== CONT  TestAccRolesAnywhereTrustAnchor_basic
=== CONT  TestAccRolesAnywhereTrustAnchor_disappears
--- PASS: TestAccRolesAnywhereTrustAnchor_disappears (23.89s)
=== CONT  TestAccRolesAnywhereTrustAnchor_certificateBundle
--- PASS: TestAccRolesAnywhereTrustAnchor_basic (26.18s)
=== CONT  TestAccRolesAnywhereTrustAnchor_tags
--- PASS: TestAccRolesAnywhereTrustAnchor_certificateBundle (17.36s)
--- PASS: TestAccRolesAnywhereTrustAnchor_tags (51.61s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rolesanywhere	81.945s
```

**Comment by ewbankkit** [comment]
@mattburgess Thanks for the contribution :tada: :clap:.
I added an acceptance test for the `CERTIFICATE_BUNDLE` case.

**Comment by ewbankkit** [comment]
```console
% make providerlint golangci-lint
==> Checking source code with providerlint...
==> Checking source code with golangci-lint...
```

**Pull request merged**
