### PR TITLE
Updating port numbers in custom service endpoints documentation

### LINKED ISSUE #15756: localstack provider example in docs needs updating with single port
On the page https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack is an example of using terrafrom with localstack - it lists out different ports with different numbers but as of 2020-09-15 all services are now routed through port 4566 only - no other ports are used.  Could the example be updated in the terraform docs?

### LINKED ISSUE #18923: Incomplete documentation for Localstack usage
_This issue was originally opened by @sergey-morenets as hashicorp/terraform#28420. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
Hi

Documentation section about Localstack usage: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/guides/custom-service-endpoints#localstack contains outdated endpoint values:

```
endpoints {
    apigateway     = "http://localhost:4567"
    cloudformation = "http://localhost:4581"
    cloudwatch     = "http://localhost:4582"
    dynamodb       = "http://localhost:4569"
    ec2            = "http://localhost:4597"
    es             = "http://localhost:4578"
    firehose       = "http://localhost:4573"
    iam            = "http://localhost:4593"
    kinesis        = "http://localhost:4568"
    lambda         = "http://localhost:4574"
    route53        = "http://localhost:4580"
    redshift       = "http://localhost:4577"
    s3             = "http://localhost:4572"
    secretsmanager = "http://localhost:4584"
    ses            = "http://localhost:4579"
    sns            = "http://localhost:4575"
    sqs            = "http://localhost:4576"
    ssm            = "http://localhost:4583"
    stepfunctions  = "http://localhost:4585"
    sts            = "http://localhost:4592"
  }

```
Since 09/2020 and 0.11.5 all services are exposed via the edge service (port 4566) only (according to the documentation (https://github.com/localstack/localstack)
So I guess this configuration block should be revised to include updated configuration for LocalStack 0.11.5 and higher.

### PR DESCRIPTION
**Pull request by LukeHendrick**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15756
Closes #18923

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Localstack updated to expose only port 4566, updating documentation to reflect this change
```

### CODE REVIEW

**Comment by sumodirjo** [comment]
Closes #18923

**Comment by whummer** [comment]
Thanks @LukeHendrick ! 👍 

Dear maintainers - would be great if we could get this change in (after the conflicts are resolved). Is there anything needed to get this PR merged?

**Comment by LukeHendrick** [comment]
@DrFaust92, is there anything we need to get this PR merged?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@LukeHendrick Thanks for the contribution :tada: :clap:.

**Pull request merged**
