### PR TITLE
provider: Upgrade to `aws-sdk-go-base/v2`

### PR DESCRIPTION
**Pull request by gdavison**
Upgrades `aws-sdk-go-base` to `aws-sdk-go-base/v2`

### CODE REVIEW

**Comment by ewbankkit** [comment]
Is a CHANGELOG entry required?

**Comment by gdavison** [comment]
🔢 Error: Validation Failed. Issues cannot have more than 100 labels

**Comment by ewbankkit** [comment]
Not sure why `go test` fails in CI; works for me:

```console
% make test
==> Checking that code complies with gofmt requirements...
go test ./...  -timeout=5m
go: downloading github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2 v2.0.0-beta.6
go: downloading github.com/hashicorp/aws-sdk-go-base/v2 v2.0.0-beta.5
?   	github.com/hashicorp/terraform-provider-aws	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	9.076s
?   	github.com/hashicorp/terraform-provider-aws/internal/attrmap	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/conns	1.635s
ok  	github.com/hashicorp/terraform-provider-aws/internal/create	1.375s
ok  	github.com/hashicorp/terraform-provider-aws/internal/experimental/nullable	1.740s
?   	github.com/hashicorp/terraform-provider-aws/internal/experimental/sync	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/flex	2.268s
ok  	github.com/hashicorp/terraform-provider-aws/internal/generate/namevaluesfilters	5.278s
?   	github.com/hashicorp/terraform-provider-aws/internal/provider	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/accessanalyzer	6.805s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/account	8.832s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acm	16.730s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acmpca	30.456s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amp	17.399s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/amplify	15.491s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	8.338s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2	8.259s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	7.724s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appconfig	9.198s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appmesh	6.807s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apprunner	11.628s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appstream	13.061s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appsync	13.588s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/athena	6.523s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	9.143s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscalingplans	9.630s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/backup	15.127s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/batch	14.136s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/budgets	17.352s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/chime	19.323s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud9	22.506s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudcontrol	11.512s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	16.566s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	9.273s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudhsmv2	15.542s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudsearch	22.443s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail	11.555s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch	13.468s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatchlogs	12.269s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codeartifact	10.310s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codebuild	12.854s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codecommit	11.261s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codedeploy	11.662s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline	16.802s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codestarconnections	17.871s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codestarnotifications	19.545s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidentity	17.309s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	18.444s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/configservice	7.514s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	7.393s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cur	18.893s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dataexchange	22.977s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datapipeline	26.147s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datasync	26.005s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dax	8.439s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/detective	10.628s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/devicefarm	9.044s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	7.544s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dlm	10.919s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	8.454s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/docdb	10.748s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ds	5.660s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb	14.949s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	26.777s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	6.618s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecrpublic	6.109s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	9.877s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	9.021s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	6.580s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	8.971s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticbeanstalk	9.698s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch	5.499s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elastictranscoder	9.162s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elb	9.280s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	14.919s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emr	6.668s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/events	13.984s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	10.883s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fms	11.992s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	12.641s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/gamelift	14.778s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glacier	7.634s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator	4.803s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glue	9.421s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/grafana	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/service/greengrass	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	13.430s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	8.578s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/identitystore	6.069s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder	8.134s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/inspector	9.772s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	11.751s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/iotanalytics	[no test files]
?   	github.com/hashicorp/terraform-provider-aws/internal/service/iotevents	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	12.591s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafkaconnect	16.712s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesis	7.119s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalytics	6.259s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalyticsv2	10.437s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesisvideo	13.470s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kms	7.534s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	10.801s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	9.491s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lexmodels	6.209s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/licensemanager	9.750s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lightsail	7.269s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/macie	10.584s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/macie2	11.423s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/mediaconnect	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediaconvert	6.563s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediapackage	10.579s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mediastore	5.181s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/memorydb	7.667s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	9.543s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mq	11.275s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mwaa	9.459s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	5.185s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall	9.547s
?   	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	[no test files]
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opsworks	7.016s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/organizations	13.794s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/outposts	6.414s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	7.343s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pricing	8.922s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/qldb	15.120s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	9.612s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ram	6.590s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	15.426s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshift	10.491s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups	9.677s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroupstaggingapi	10.848s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53	7.354s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53recoverycontrolconfig	14.748s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53recoveryreadiness	7.332s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver	7.009s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	13.072s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3control	8.960s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3outposts	7.276s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	5.587s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/schemas	6.063s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager	10.676s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/securityhub	8.035s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo	9.096s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	6.251s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicediscovery	8.977s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicequotas	7.575s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ses	7.381s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sfn	10.924s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/shield	5.990s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/signer	13.841s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/simpledb	15.240s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sns	18.414s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sqs	17.485s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssm	9.625s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssoadmin	6.226s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway	7.701s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sts	7.940s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/swf	7.036s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/synthetics	7.310s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite	10.056s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	6.695s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/waf	5.844s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafregional	3.885s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	7.571s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/worklink	9.097s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/workspaces	11.046s
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/xray	12.270s
ok  	github.com/hashicorp/terraform-provider-aws/internal/tags	0.767s
ok  	github.com/hashicorp/terraform-provider-aws/internal/tfresource	28.518s
ok  	github.com/hashicorp/terraform-provider-aws/internal/vault/helper/pgpkeys	0.767s
ok  	github.com/hashicorp/terraform-provider-aws/internal/vault/sdk/helper/jsonutil	1.569s
ok  	github.com/hashicorp/terraform-provider-aws/internal/verify	1.265s
?   	github.com/hashicorp/terraform-provider-aws/version	[no test files]
```

**Comment by gdavison** [comment]
`Terraform Provider Checks / go test (pull_request)` is failing when trying to test `internal/generate/tags` because all Go files are excluded due to build constraints #22880

**Pull request merged**
