### PR TITLE
Add dms endpoint s3 attributes to keep format from changing to default on update

### PR DESCRIPTION
**Pull request by Niarfe**
This is a resubmission of https://github.com/terraform-providers/terraform-provider-aws/pull/11576

Original description:
```
Extend DMS S3 settings to support updated API changes in aws-sdk-go.
This is so that we can avoid using extra_connection_attributes.
```

I've tested functionality to dms endpoint for the issue that I want to address.  

Issue: Given a created dms migration with an s3 target endpoint in parquet format, if you updated and execute a terraform update the target endpoint format reverts to csv.  

With current changes:  Created a dms migration with an s3 target endpoint, then changed the name of the bucket, ran terraform apply and verified the migration still proceeded with original parquet format.

Relates to #11576

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates to #11576

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

ENHANCEMENTS:

resource/aws_dms_endpoint: Added missing `s3_settings` attributes `ServiceAccessRoleArn, ExternalTableDefinition, CsvRowDelimiter, CsvDelimiter, BucketFolder, BucketName, CompressionType, TimestampColumnName, DataFormat, ParquetVersion, EncryptionMode, ServerSideEncryptionKmsKeyId`

Output from acceptance testing:

```
$ go version
go version go1.15 linux/amd64

$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsDmsEndpoint'
...
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch (157.41s)    
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_ErrorRetryDuration (173.00s)    
--- PASS: TestAccAwsDmsEndpoint_Elasticsearch_FullLoadErrorPercentage (173.57s)    
--- PASS: TestAccAwsDmsEndpoint_Db2 (223.90s)    
--- PASS: TestAccAwsDmsEndpoint_DocDB (225.37s)    
--- PASS: TestAccAwsDmsEndpoint_Kafka_Broker (226.68s)    
--- PASS: TestAccAwsDmsEndpoint_basic (226.69s)    
--- PASS: TestAccAwsDmsEndpoint_Kafka_Topic (227.48s)    
--- PASS: TestAccAwsDmsEndpoint_MongoDb (228.72s)    
--- PASS: TestAccAwsDmsEndpoint_DynamoDb (238.63s)    
--- PASS: TestAccAwsDmsEndpoint_S3_Parquet (238.97s)    
--- PASS: TestAccAwsDmsEndpoint_S3_Csv (239.37s)    
--- PASS: TestAccAwsDmsEndpoint_Kinesis (251.62s)    
PASS    
ok      github.com/terraform-providers/terraform-provider-aws/aws   251.673s 
```

### CODE REVIEW

**Comment by azhurbilo** [comment]
@breathingdust could you check this MR please? we also use S3 for DMS as target and need setup "DataFormat=parquet;ParquetVersion=PARQUET_2_0"

**Comment by YakDriver** [comment]
Related #14340
Related #17591
Related #18750

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by YakDriver** [comment]
Thanks so much for this submission! There's a lot of good work here. Unfortunately, many of the issues have been resolved apart from this PR. We value your time in submissions and do our best to make sure contributions don't go to waste. We're sorry for this not being used. Rest assured we are always seeking to improve our processes so that this doesn't happen again.

**Pull request closed without merging**
