### PR TITLE
service/opsworks: add default tags support to opsworks_*_layer resources

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #7926

Output from acceptance testing:

```
Will be managed by CI nightly tests
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
Documentation?

**Comment by anGie44** [comment]
> Documentation?

Ahhh 🤦‍♀️ , good catch ! will update here (and the other PR(s))

**Review by ewbankkit — APPROVED** [review]
LGTM 🚀.

**Pull request merged**
