### PR TITLE
F/#25314 - Return the public key material for a `aws_key_pair`

### LINKED ISSUE #25314: Support public_key on aws_key_pair.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Now `DescribeKeyPairs` API supports `IncludePublicKey` parameter and `KeyPairInfo` response has `publicKey` entry.
So please support `public_key` attribute on `aws_key_pair` data source.

### New or Affected Resource(s)

* `aws_key_pair` (data source)

### References

* https://aws.amazon.com/about-aws/whats-new/2022/04/aws-management-features-ec2-key-pairs/
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeKeyPairs.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_KeyPairInfo.html

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #25314 

Output from acceptance testing:

```
bruno@pop-os ~/G/terraform-provider-aws (f/#25314-aws-key-pair-public-key)> make testacc TESTS=TestAccEC2KeyPairDataSource_ PKG=ec2                                                                                                     (base) 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2KeyPairDataSource_'  -timeout 180m
=== RUN   TestAccEC2KeyPairDataSource_basic
=== PAUSE TestAccEC2KeyPairDataSource_basic
=== RUN   TestAccEC2KeyPairDataSource_includePublicKey
=== PAUSE TestAccEC2KeyPairDataSource_includePublicKey
=== CONT  TestAccEC2KeyPairDataSource_basic
=== CONT  TestAccEC2KeyPairDataSource_includePublicKey
--- PASS: TestAccEC2KeyPairDataSource_includePublicKey (7.51s)
--- PASS: TestAccEC2KeyPairDataSource_basic (8.10s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        8.177s
bruno@pop-os ~/G/terraform-provider-aws (f/#25314-aws-key-pair-public-key)> make testacc TESTS=TestAccEC2KeyPair_ PKG=ec2                                                                                                               (base) 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2KeyPair_'  -timeout 180m
=== RUN   TestAccEC2KeyPair_basic
=== PAUSE TestAccEC2KeyPair_basic
=== RUN   TestAccEC2KeyPair_tags
=== PAUSE TestAccEC2KeyPair_tags
=== RUN   TestAccEC2KeyPair_nameGenerated
=== PAUSE TestAccEC2KeyPair_nameGenerated
=== RUN   TestAccEC2KeyPair_namePrefix
=== PAUSE TestAccEC2KeyPair_namePrefix
=== RUN   TestAccEC2KeyPair_disappears
=== PAUSE TestAccEC2KeyPair_disappears
=== CONT  TestAccEC2KeyPair_basic
=== CONT  TestAccEC2KeyPair_namePrefix
=== CONT  TestAccEC2KeyPair_disappears
=== CONT  TestAccEC2KeyPair_nameGenerated
=== CONT  TestAccEC2KeyPair_tags
--- PASS: TestAccEC2KeyPair_disappears (6.91s)
--- PASS: TestAccEC2KeyPair_basic (9.71s)
--- PASS: TestAccEC2KeyPair_namePrefix (9.83s)
--- PASS: TestAccEC2KeyPair_nameGenerated (9.83s)
--- PASS: TestAccEC2KeyPair_tags (21.12s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        21.230s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Interesting, the `public_key` that you provide through the `aws_key_pair` resource, is not what's coming back from the DescribeKeyPair API call.

For example, in the create I can set PublicKey to`ssh-rsa xxxx email@example.com` and a KeyPairName `Foobar`. 
The response from the DescribeKeyPair.PublicKey will be `ssh-rsa xxxx {Foobar}`.

**Comment by ewbankkit** [comment]
@bschaatsbergen I added a new function `OpenSHHPublicKeysEqual` that ignores the comment part of the key when comparing.

The tests now pass:

```console
% make testacc TESTARGS='-run=TestAccEC2KeyPairDataSource_' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2KeyPairDataSource_ -timeout 180m
=== RUN   TestAccEC2KeyPairDataSource_basic
=== PAUSE TestAccEC2KeyPairDataSource_basic
=== RUN   TestAccEC2KeyPairDataSource_includePublicKey
=== PAUSE TestAccEC2KeyPairDataSource_includePublicKey
=== CONT  TestAccEC2KeyPairDataSource_basic
=== CONT  TestAccEC2KeyPairDataSource_includePublicKey
--- PASS: TestAccEC2KeyPairDataSource_includePublicKey (17.49s)
--- PASS: TestAccEC2KeyPairDataSource_basic (18.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	25.314s
```

**Comment by ewbankkit** [comment]
Could you please also add `create_time` and `key_type` attributes to the data source, plus `key_type` as a Computed attribute to the `aws_key_pair` resource? Thanks.

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen I added a new function `OpenSHHPublicKeysEqual` that ignores the comment part of the key when comparing.
> 
> The tests now pass:
> 
> ```
> % make testacc TESTARGS='-run=TestAccEC2KeyPairDataSource_' PKG=ec2 ACCTEST_PARALLELISM=2
> ==> Checking that code complies with gofmt requirements...
> TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2KeyPairDataSource_ -timeout 180m
> === RUN   TestAccEC2KeyPairDataSource_basic
> === PAUSE TestAccEC2KeyPairDataSource_basic
> === RUN   TestAccEC2KeyPairDataSource_includePublicKey
> === PAUSE TestAccEC2KeyPairDataSource_includePublicKey
> === CONT  TestAccEC2KeyPairDataSource_basic
> === CONT  TestAccEC2KeyPairDataSource_includePublicKey
> --- PASS: TestAccEC2KeyPairDataSource_includePublicKey (17.49s)
> --- PASS: TestAccEC2KeyPairDataSource_basic (18.72s)
> PASS
> ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	25.314s
> ```

Neat fix, I'll take care of what you mentioned in the last comment.

**Comment by bschaatsbergen** [comment]
@ewbankkit, done. Do you suggest that we also fix the existing limitation mentioned through this PR or another one - https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/key_pair#import ?

**Comment by ewbankkit** [comment]
@bschaatsbergen I suggest a separate PR to deal with that - There will have to be a `DiffSuppressFunc` to handle the different content of the public key string returned by the AWS API.

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen I suggest a separate PR to deal with that - There will have to be a `DiffSuppressFunc` to handle the different content of the public key string returned by the AWS API.

Right on, will note it down to pick up in the near future. Removed draft status from this PR.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2KeyPairDataSource_' PKG=ec2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2KeyPairDataSource_ -timeout 180m
=== RUN   TestAccEC2KeyPairDataSource_basic
=== PAUSE TestAccEC2KeyPairDataSource_basic
=== RUN   TestAccEC2KeyPairDataSource_includePublicKey
=== PAUSE TestAccEC2KeyPairDataSource_includePublicKey
=== CONT  TestAccEC2KeyPairDataSource_basic
=== CONT  TestAccEC2KeyPairDataSource_includePublicKey
--- PASS: TestAccEC2KeyPairDataSource_includePublicKey (16.34s)
--- PASS: TestAccEC2KeyPairDataSource_basic (16.45s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	20.901s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
```console
% make providerlint
==> Checking source code with providerlint...
```

**Pull request merged**
