### PR TITLE
add support for SQS-managed SSE

### LINKED ISSUE #21948: Add support for SSE-SQS
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add support for [SSE-SQS](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-sqs-server-side-encryption-keys-sse/) managed server-side encryption on SQS queues.

### New or Affected Resource(s)

* aws_sqs_queue

### Potential Terraform Configuration

```hcl
resource "aws_sqs_queue" "terraform_queue" {
    ...
    sqs_managed_sse_enabled = true
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-sqs-server-side-encryption-keys-sse/

### PR DESCRIPTION
**Pull request by rmorris1218**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21948 -- add support for SSE-SQS for the `aws_sqs_queue` resource.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccSQSQueue_encryption PKG=sqs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sqs/... -v -count 1 -parallel 20 -run='TestAccSQSQueue_encryption' -timeout 180m
=== RUN   TestAccSQSQueue_encryption
=== PAUSE TestAccSQSQueue_encryption
=== CONT  TestAccSQSQueue_encryption
--- PASS: TestAccSQSQueue_encryption (116.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sqs	119.555s
...
```

### CODE REVIEW

**Comment by rmorris1218** [comment]
This is contingent on the `aws-sdk-go` bump to at least `v1.42.11` (see [here](https://github.com/aws/aws-sdk-go/commit/cd7ead6c9f1bebca4f28dbf5cc95fd7d76fc9fb3))

**Comment by ktham** [comment]
What will happen if `sqs_managed_sse_enabled` is set to `true` and `kms_master_key_id` is not empty?

**Comment by rmorris1218** [comment]
If they are both set, received: `InvalidAttributeName: You can use one type of server-side encryption (SSE) at one time. You can either enable KMS SSE or SQS SSE.` .. I added `ConflictsWith` constraints for both of those to avoid the error.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccSQSQueue_ PKG=sqs          
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sqs/... -v -count 1 -parallel 20 -run='TestAccSQSQueue_' -timeout 180m
=== RUN   TestAccSQSQueue_basic
=== PAUSE TestAccSQSQueue_basic
=== RUN   TestAccSQSQueue_disappears
=== PAUSE TestAccSQSQueue_disappears
=== RUN   TestAccSQSQueue_Name_generated
=== PAUSE TestAccSQSQueue_Name_generated
=== RUN   TestAccSQSQueue_NameGenerated_fifoQueue
=== PAUSE TestAccSQSQueue_NameGenerated_fifoQueue
=== RUN   TestAccSQSQueue_namePrefix
=== PAUSE TestAccSQSQueue_namePrefix
=== RUN   TestAccSQSQueue_NamePrefix_fifoQueue
=== PAUSE TestAccSQSQueue_NamePrefix_fifoQueue
=== RUN   TestAccSQSQueue_tags
=== PAUSE TestAccSQSQueue_tags
=== RUN   TestAccSQSQueue_update
=== PAUSE TestAccSQSQueue_update
=== RUN   TestAccSQSQueue_policy
=== PAUSE TestAccSQSQueue_policy
=== RUN   TestAccSQSQueue_recentlyDeleted
=== PAUSE TestAccSQSQueue_recentlyDeleted
=== RUN   TestAccSQSQueue_redrivePolicy
=== PAUSE TestAccSQSQueue_redrivePolicy
=== RUN   TestAccSQSQueue_fifoQueue
=== PAUSE TestAccSQSQueue_fifoQueue
=== RUN   TestAccSQSQueue_FIFOQueue_expectNameError
=== PAUSE TestAccSQSQueue_FIFOQueue_expectNameError
=== RUN   TestAccSQSQueue_FIFOQueue_contentBasedDeduplication
=== PAUSE TestAccSQSQueue_FIFOQueue_contentBasedDeduplication
=== RUN   TestAccSQSQueue_FIFOQueue_highThroughputMode
=== PAUSE TestAccSQSQueue_FIFOQueue_highThroughputMode
=== RUN   TestAccSQSQueue_StandardQueue_expectContentBasedDeduplicationError
=== PAUSE TestAccSQSQueue_StandardQueue_expectContentBasedDeduplicationError
=== RUN   TestAccSQSQueue_encryption
=== PAUSE TestAccSQSQueue_encryption
=== RUN   TestAccSQSQueue_zeroVisibilityTimeoutSeconds
=== PAUSE TestAccSQSQueue_zeroVisibilityTimeoutSeconds
=== RUN   TestAccSQSQueue_defaultKMSDataKeyReusePeriodSeconds
=== PAUSE TestAccSQSQueue_defaultKMSDataKeyReusePeriodSeconds
=== CONT  TestAccSQSQueue_basic
=== CONT  TestAccSQSQueue_redrivePolicy
=== CONT  TestAccSQSQueue_NamePrefix_fifoQueue
=== CONT  TestAccSQSQueue_Name_generated
=== CONT  TestAccSQSQueue_namePrefix
=== CONT  TestAccSQSQueue_tags
=== CONT  TestAccSQSQueue_disappears
=== CONT  TestAccSQSQueue_defaultKMSDataKeyReusePeriodSeconds
=== CONT  TestAccSQSQueue_zeroVisibilityTimeoutSeconds
=== CONT  TestAccSQSQueue_encryption
=== CONT  TestAccSQSQueue_StandardQueue_expectContentBasedDeduplicationError
=== CONT  TestAccSQSQueue_FIFOQueue_highThroughputMode
=== CONT  TestAccSQSQueue_FIFOQueue_contentBasedDeduplication
=== CONT  TestAccSQSQueue_FIFOQueue_expectNameError
=== CONT  TestAccSQSQueue_NameGenerated_fifoQueue
=== CONT  TestAccSQSQueue_fifoQueue
=== CONT  TestAccSQSQueue_policy
=== CONT  TestAccSQSQueue_recentlyDeleted
=== CONT  TestAccSQSQueue_update
--- PASS: TestAccSQSQueue_StandardQueue_expectContentBasedDeduplicationError (7.27s)
--- PASS: TestAccSQSQueue_FIFOQueue_expectNameError (7.88s)
--- PASS: TestAccSQSQueue_disappears (30.97s)
--- PASS: TestAccSQSQueue_basic (42.31s)
--- PASS: TestAccSQSQueue_zeroVisibilityTimeoutSeconds (42.70s)
--- PASS: TestAccSQSQueue_namePrefix (42.87s)
--- PASS: TestAccSQSQueue_defaultKMSDataKeyReusePeriodSeconds (43.04s)
--- PASS: TestAccSQSQueue_NameGenerated_fifoQueue (43.04s)
--- PASS: TestAccSQSQueue_Name_generated (43.04s)
--- PASS: TestAccSQSQueue_fifoQueue (43.25s)
--- PASS: TestAccSQSQueue_NamePrefix_fifoQueue (43.35s)
--- PASS: TestAccSQSQueue_FIFOQueue_contentBasedDeduplication (43.35s)
--- PASS: TestAccSQSQueue_redrivePolicy (45.12s)
--- PASS: TestAccSQSQueue_FIFOQueue_highThroughputMode (55.73s)
--- PASS: TestAccSQSQueue_update (56.09s)
--- PASS: TestAccSQSQueue_tags (64.29s)
--- PASS: TestAccSQSQueue_encryption (66.22s)
--- PASS: TestAccSQSQueue_policy (80.43s)
--- PASS: TestAccSQSQueue_recentlyDeleted (88.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sqs	92.055s
```

**Comment by ewbankkit** [comment]
@rmorris1218 Thanks for the contribution :tada: :clap:.

**Pull request merged**
