### PR TITLE
MediaLive h265 support

### PR DESCRIPTION
**Pull request by LasseEmilHildebrandt**
### Description

This PR adds support for MediaLive H265 encoding.

### Output from Acceptance Testing

```
make testacc TESTS=TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings PKG=medialive
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings
=== PAUSE TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings
=== CONT  TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings (85.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	87.241s
...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @LasseEmilHildebrandt 👋 Thank you for taking the time to raise this, and for _all_ of the contributions you've made recently! Please feel free to ignore the automated comment about allowing maintainers to edit on PRs moving forward. We understand that this is something you're not able to allow due to policy, and don't want you to feel that you have to call it out every time 🙂.

**Comment by LasseEmilHildebrandt** [comment]
> Hey @LasseEmilHildebrandt 👋 Thank you for taking the time to raise this, and for _all_ of the contributions you've made recently! Please feel free to ignore the automated comment about allowing maintainers to edit on PRs moving forward. We understand that this is something you're not able to allow due to policy, and don't want you to feel that you have to call it out every time 🙂.

Hey @justinretzolk - Thanks for letting me know :smile: . I'll forward this to @jonasdkhansen & @quartercastle , as we tend to collaborate on these changes.

**Review by johnsonaj — COMMENTED** [review]
@LasseEmilHildebrandt PR looks good overall. Just one minor change to the CHANGELOG entry. Also, can you rebase/merge `main`?

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTARGS='-run=TestAccMediaLiveChannel_' PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLiveChannel_ -timeout 180m
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (75.49s)
--- PASS: TestAccMediaLiveChannel_AudioDescriptions_codecSettings (79.79s)
--- PASS: TestAccMediaLiveChannel_basic (101.38s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings (108.54s)
--- PASS: TestAccMediaLiveChannel_hls (142.80s)
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (148.53s)
--- PASS: TestAccMediaLiveChannel_disappears (171.29s)
--- PASS: TestAccMediaLiveChannel_updateTags (197.37s)
--- PASS: TestAccMediaLiveChannel_M2TS_settings (211.43s)
--- PASS: TestAccMediaLiveChannel_update (237.47s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h264Settings (242.71s)
--- PASS: TestAccMediaLiveChannel_status (336.34s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	339.403s
```

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thank you for the contribution! 🎉

**Pull request merged**
