### PR TITLE
r/aws_organizations_account: Allow Import when IAM Billing is set

### PR DESCRIPTION
**Pull request by Alex-Waring**
### Description
Makes use of the latest framework to implement a backwards compatible import, that allows you to specify the state of aws_organizations_account.

### Relations
Closes https://github.com/hashicorp/terraform-provider-aws/issues/35661.

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccOrganizations PKG=organizations

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/organizations/... -v -count 1 -parallel 20 -run='TestAccOrganizations'  -timeout 360m
=== RUN   TestAccOrganizations_serial
=== PAUSE TestAccOrganizations_serial
=== RUN   TestAccOrganizationsPoliciesDataSource_basic
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccOrganizationsPoliciesDataSource_basic (0.65s)
=== RUN   TestAccOrganizationsPoliciesForTargetDataSource_basic
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
--- SKIP: TestAccOrganizationsPoliciesForTargetDataSource_basic (0.21s)
=== CONT  TestAccOrganizations_serial
=== RUN   TestAccOrganizations_serial/Organization
=== RUN   TestAccOrganizations_serial/Organization/disappears
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/FeatureSet_Basic
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/FeatureSet_Update
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/FeatureSet_ForcesNew
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/DataSource_basic
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/DataSource_memberAccount
=== RUN   TestAccOrganizations_serial/Organization/basic
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/AwsServiceAccessPrincipals
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/EnabledPolicyTypes
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Organization/DataSource_delegatedAdministrator
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/Account
=== RUN   TestAccOrganizations_serial/Account/basic
    account_test.go:40: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/CloseOnDeletion
    account_test.go:79: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/ParentId
    account_test.go:119: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/Tags
    account_test.go:160: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/GovCloud
    account_test.go:210: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/OrganizationalUnit
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/update
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/tags
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/DataSource_basic
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/ChildAccountsDataSource_basic
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/DescendantAccountsDataSource_basic
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/PluralDataSource_basic
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/basic
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/OrganizationalUnit/disappears
    acctest.go:1017: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccOrganizations_serial/PolicyDataSource
=== RUN   TestAccOrganizations_serial/PolicyDataSource/UnattachedPolicy
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/DelegatedAdministrator
=== RUN   TestAccOrganizations_serial/DelegatedAdministrator/basic
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/DelegatedAdministrator/disappears
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/Policy
=== RUN   TestAccOrganizations_serial/Policy/Type_SCP
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/ImportAwsManagedPolicy
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/basic
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/concurrent
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/Description
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/Type_Backup
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/Type_Tag
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/Tags
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/SkipDestroy
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/disappears
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/Policy/Type_AI_OPT_OUT
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/PolicyAttachment
=== RUN   TestAccOrganizations_serial/PolicyAttachment/SkipDestroy
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/PolicyAttachment/disappears
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/PolicyAttachment/Account
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/PolicyAttachment/OrganizationalUnit
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/PolicyAttachment/Root
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccOrganizations_serial/ResourcePolicy
=== RUN   TestAccOrganizations_serial/ResourcePolicy/basic
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/ResourcePolicy/disappears
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/ResourcePolicy/tags
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/DelegatedAdministrators
=== RUN   TestAccOrganizations_serial/DelegatedAdministrators/basic
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/DelegatedServices
=== RUN   TestAccOrganizations_serial/DelegatedServices/basic
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/DelegatedServices/multiple
    acctest.go:855: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
=== RUN   TestAccOrganizations_serial/ResourceTags
=== RUN   TestAccOrganizations_serial/ResourceTags/basic
    acctest.go:988: skipping tests; this AWS account must not be an existing member of an AWS Organization
--- PASS: TestAccOrganizations_serial (46.73s)
    --- PASS: TestAccOrganizations_serial/Organization (20.47s)
        --- SKIP: TestAccOrganizations_serial/Organization/disappears (3.52s)
        --- SKIP: TestAccOrganizations_serial/Organization/FeatureSet_Basic (0.20s)
        --- SKIP: TestAccOrganizations_serial/Organization/FeatureSet_Update (1.10s)
        --- SKIP: TestAccOrganizations_serial/Organization/FeatureSet_ForcesNew (0.19s)
        --- SKIP: TestAccOrganizations_serial/Organization/DataSource_basic (1.63s)
        --- PASS: TestAccOrganizations_serial/Organization/DataSource_memberAccount (11.91s)
        --- SKIP: TestAccOrganizations_serial/Organization/basic (0.19s)
        --- SKIP: TestAccOrganizations_serial/Organization/AwsServiceAccessPrincipals (0.20s)
        --- SKIP: TestAccOrganizations_serial/Organization/EnabledPolicyTypes (1.53s)
        --- SKIP: TestAccOrganizations_serial/Organization/DataSource_delegatedAdministrator (0.00s)
    --- PASS: TestAccOrganizations_serial/Account (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/basic (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/CloseOnDeletion (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/ParentId (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/Tags (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/GovCloud (0.00s)
    --- PASS: TestAccOrganizations_serial/OrganizationalUnit (8.32s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/update (0.23s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/tags (1.32s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/DataSource_basic (0.21s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/ChildAccountsDataSource_basic (1.43s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/DescendantAccountsDataSource_basic (0.22s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/PluralDataSource_basic (3.63s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/basic (0.21s)
        --- SKIP: TestAccOrganizations_serial/OrganizationalUnit/disappears (1.07s)
    --- PASS: TestAccOrganizations_serial/PolicyDataSource (0.20s)
        --- SKIP: TestAccOrganizations_serial/PolicyDataSource/UnattachedPolicy (0.20s)
    --- PASS: TestAccOrganizations_serial/DelegatedAdministrator (0.00s)
        --- SKIP: TestAccOrganizations_serial/DelegatedAdministrator/basic (0.00s)
        --- SKIP: TestAccOrganizations_serial/DelegatedAdministrator/disappears (0.00s)
    --- PASS: TestAccOrganizations_serial/Policy (10.69s)
        --- SKIP: TestAccOrganizations_serial/Policy/Type_SCP (1.33s)
        --- SKIP: TestAccOrganizations_serial/Policy/ImportAwsManagedPolicy (0.20s)
        --- SKIP: TestAccOrganizations_serial/Policy/basic (1.18s)
        --- SKIP: TestAccOrganizations_serial/Policy/concurrent (0.19s)
        --- SKIP: TestAccOrganizations_serial/Policy/Description (3.46s)
        --- SKIP: TestAccOrganizations_serial/Policy/Type_Backup (0.20s)
        --- SKIP: TestAccOrganizations_serial/Policy/Type_Tag (1.20s)
        --- SKIP: TestAccOrganizations_serial/Policy/Tags (0.20s)
        --- SKIP: TestAccOrganizations_serial/Policy/SkipDestroy (1.16s)
        --- SKIP: TestAccOrganizations_serial/Policy/disappears (1.38s)
        --- SKIP: TestAccOrganizations_serial/Policy/Type_AI_OPT_OUT (0.20s)
    --- PASS: TestAccOrganizations_serial/PolicyAttachment (6.85s)
        --- SKIP: TestAccOrganizations_serial/PolicyAttachment/SkipDestroy (1.30s)
        --- SKIP: TestAccOrganizations_serial/PolicyAttachment/disappears (1.45s)
        --- SKIP: TestAccOrganizations_serial/PolicyAttachment/Account (1.45s)
        --- SKIP: TestAccOrganizations_serial/PolicyAttachment/OrganizationalUnit (1.16s)
        --- SKIP: TestAccOrganizations_serial/PolicyAttachment/Root (1.50s)
    --- PASS: TestAccOrganizations_serial/ResourcePolicy (0.00s)
        --- SKIP: TestAccOrganizations_serial/ResourcePolicy/basic (0.00s)
        --- SKIP: TestAccOrganizations_serial/ResourcePolicy/disappears (0.00s)
        --- SKIP: TestAccOrganizations_serial/ResourcePolicy/tags (0.00s)
    --- PASS: TestAccOrganizations_serial/DelegatedAdministrators (0.00s)
        --- SKIP: TestAccOrganizations_serial/DelegatedAdministrators/basic (0.00s)
    --- PASS: TestAccOrganizations_serial/DelegatedServices (0.00s)
        --- SKIP: TestAccOrganizations_serial/DelegatedServices/basic (0.00s)
        --- SKIP: TestAccOrganizations_serial/DelegatedServices/multiple (0.00s)
    --- PASS: TestAccOrganizations_serial/ResourceTags (0.20s)
        --- SKIP: TestAccOrganizations_serial/ResourceTags/basic (0.20s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/organizations	54.826s
...
```

### CODE REVIEW

**Comment by Alex-Waring** [comment]
@justinretzolk can this be reviewed by you or someone in the community?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccOrganizations_serial/Account' PKG=organizations
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/organizations/... -v -count 1 -parallel 20  -run=TestAccOrganizations_serial/Account -timeout 360m
=== RUN   TestAccOrganizations_serial
=== PAUSE TestAccOrganizations_serial
=== CONT  TestAccOrganizations_serial
=== RUN   TestAccOrganizations_serial/Account
=== RUN   TestAccOrganizations_serial/Account/basic
    account_test.go:41: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/CloseOnDeletion
    account_test.go:80: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/ParentId
    account_test.go:120: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/Tags
    account_test.go:161: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
=== RUN   TestAccOrganizations_serial/Account/GovCloud
    account_test.go:211: Environment variable TEST_AWS_ORGANIZATION_ACCOUNT_EMAIL_DOMAIN is not set
--- PASS: TestAccOrganizations_serial (0.00s)
    --- PASS: TestAccOrganizations_serial/Account (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/basic (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/CloseOnDeletion (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/ParentId (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/Tags (0.00s)
        --- SKIP: TestAccOrganizations_serial/Account/GovCloud (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/organizations	4.138s
```

**Comment by ewbankkit** [comment]
@Alex-Waring Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
@Alex-Waring Thanks for the contribution :tada: :clap:.

**Pull request merged**
