### PR TITLE
Issue 16973 - allow for ARNs and partner event bus names

### LINKED ISSUE #16973: aws_cloudwatch_event_rule does not support EventBus ARNs in event_bus_name
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```sh
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.22.0
```

### Affected Resource(s)

* aws_cloudwatch_event_rule

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.22.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}

resource "aws_cloudwatch_event_rule" "example_event_bus_rule" {
  name           = "example"
  event_bus_name = "arn:aws:events:us-east-1:123456789012:event-bus/default"
  event_pattern  = ""
}
```

### Expected Behavior

The plan should succeed. AWS recently allowed Rules to be put directly against Event Buses in other Accounts.

### Actual Behavior

Terraform Plan rejects the an `event_bus_name` of `arn:aws:events:us-east-1:123456789012:event-bus/default` when it doesn't match its expected format.  

```sh
Error: expected value of event_bus_name to match regular expression "^[a-zA-Z0-9._\\-]+$", got arn:aws:events:us-east-1:123456789012:event-bus/default

  on example.tf line 16, in resource "aws_cloudwatch_event_rule" "example_event_bus_rule":
  16:   event_bus_name = "arn:aws:events:us-east-1:123456789012:event-bus/default"
```

The AWS API for PutRule now supports an extended Regex, that allows either an ARN or an EventBus Name
`(arn:aws[\w-]*:events:[a-z]{2}-[a-z]+-[\w-]+:[0-9]{12}:event-bus\/)?[/\.\-_A-Za-z0-9]+`

### Steps to Reproduce

1. `terraform plan`

### References

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutRule.html#API_PutRule_RequestSyntax
https://aws.amazon.com/blogs/compute/simplifying-cross-account-access-with-amazon-eventbridge-resource-policies/

### PR DESCRIPTION
**Pull request by mdragilev**
Updated to allow partner names for the AWS Event Bridge as well as allow to use ARNs in place of event bridge names as that works with the AWS CLI.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16973

Output from acceptance testing:

### CODE REVIEW

**Comment by bflad** [comment]
Hi @mdragilev 👋  Thank you for submitting this. It appears this was resolved with https://github.com/hashicorp/terraform-provider-aws/pull/16815, which was released yesterday with version 3.34.0 of the Terraform AWS Provider.

**Comment by bflad** [comment]
Actually, my bad, this is for ARNs as well. I'm going to assign this to @gdavison who is most familiar here.

**Comment by gdavison** [comment]
This was resolved by #18143, which will be released in v3.36.0 later this week

**Comment by prashant-tyagi-cko** [comment]
This fixed the Eventbus name error but now I get error while setting ID - "error reading CloudWatch Events Rule (aws.partner/appflow/salesforce.com/xxx/foo-eventbus/bar-rule): unexpected format for ID ("aws.partner/appflow/salesforce.com/xxx/foo-eventbus/bar-rule"), expected <event-bus-name>/<rule-name> or <rule-name>"

**Pull request closed without merging**
