### PR TITLE
resource/aws_ecs_capacity_provider: Add support for ECS capacity provider update

### PR DESCRIPTION
**Pull request by shuheiktgw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes https://github.com/hashicorp/terraform-provider-aws/issues/16943

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_ecs_capacity_provider: Add support for ECS capacity provider update
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEcsCapacityProvider_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEcsCapacityProvider_* -timeout 120m
=== RUN   TestAccAWSEcsCapacityProvider_basic
=== PAUSE TestAccAWSEcsCapacityProvider_basic
=== RUN   TestAccAWSEcsCapacityProvider_disappears
=== PAUSE TestAccAWSEcsCapacityProvider_disappears
=== RUN   TestAccAWSEcsCapacityProvider_ManagedScaling
=== PAUSE TestAccAWSEcsCapacityProvider_ManagedScaling
=== RUN   TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== PAUSE TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== RUN   TestAccAWSEcsCapacityProvider_Tags
=== PAUSE TestAccAWSEcsCapacityProvider_Tags
=== CONT  TestAccAWSEcsCapacityProvider_basic
=== CONT  TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== CONT  TestAccAWSEcsCapacityProvider_ManagedScaling
=== CONT  TestAccAWSEcsCapacityProvider_disappears
=== CONT  TestAccAWSEcsCapacityProvider_Tags
--- PASS: TestAccAWSEcsCapacityProvider_ManagedScalingPartial (125.44s)
--- PASS: TestAccAWSEcsCapacityProvider_disappears (137.43s)
--- PASS: TestAccAWSEcsCapacityProvider_basic (144.27s)
--- PASS: TestAccAWSEcsCapacityProvider_ManagedScaling (193.10s)
--- PASS: TestAccAWSEcsCapacityProvider_Tags (306.73s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	308.731s
```

Thank you for your review! 👍

### CODE REVIEW

**Comment by shuheiktgw** [comment]
This PR conflicts with https://github.com/hashicorp/terraform-provider-aws/pull/16941

**Comment by eddgrant** [comment]
Hey folks,

My team is _really_ keen to see this PR make its way through to a release :pray: . I thought it might be beneficial to the review process if I were to build the AWS Provider from this branch and do some manual testing. It took me a bit of twoing and froing to figure out how to get Terraform to use the locally built provider binary but I have completed some basic testing and can happily confirm that I was able to update the following properties in-place, without requiring resource replacement:

1. maximum_scaling_step_size
2. minimum_scaling_step_size
3. target_capacity

### Demonstrative screenshots:

#### Capacity Provider: Before state
image

#### Terraform apply: Proposed changes
image

#### Terraform output
image

#### Capacity Provider: After State
image
 
Hope this is helpful, happy to do any more testing if it'll help get this through to inclusion in a release.

**Comment by bflad** [comment]
Ready for rebase now that #16941 has been merged. 👍

**Comment by shuheiktgw** [comment]
Thank you! I'll update the PR!

**Comment by shuheiktgw** [comment]
@bflad I've updated the PR so would you review it?

**Comment by wendtek** [comment]
Is there any other testing or review that needs to be done on this PR? It would make workflows with capacity providers significantly more viable.

**Comment by legal90** [comment]
@shuheiktgw Thank you very much for implementing this! Could you please rebase you branch once again and fix conflicts.

Hopefully, @bflad can review it soon ;)

**Comment by shuheiktgw** [comment]
Thank you for pinging me, @legal90! I've rebased it again 👍

**Comment by hlarsen** [comment]
Anything anyone can do to help move this along? I (and it appears plenty of others) would love to see this merged...

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsCapacityProvider_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEcsCapacityProvider_ -timeout 180m
=== RUN   TestAccAWSEcsCapacityProvider_basic
=== PAUSE TestAccAWSEcsCapacityProvider_basic
=== RUN   TestAccAWSEcsCapacityProvider_disappears
=== PAUSE TestAccAWSEcsCapacityProvider_disappears
=== RUN   TestAccAWSEcsCapacityProvider_ManagedScaling
=== PAUSE TestAccAWSEcsCapacityProvider_ManagedScaling
=== RUN   TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== PAUSE TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== RUN   TestAccAWSEcsCapacityProvider_Tags
=== PAUSE TestAccAWSEcsCapacityProvider_Tags
=== CONT  TestAccAWSEcsCapacityProvider_basic
=== CONT  TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== CONT  TestAccAWSEcsCapacityProvider_Tags
=== CONT  TestAccAWSEcsCapacityProvider_disappears
=== CONT  TestAccAWSEcsCapacityProvider_ManagedScaling
--- PASS: TestAccAWSEcsCapacityProvider_disappears (59.40s)
--- PASS: TestAccAWSEcsCapacityProvider_ManagedScalingPartial (60.01s)
--- PASS: TestAccAWSEcsCapacityProvider_basic (70.51s)
--- PASS: TestAccAWSEcsCapacityProvider_Tags (99.70s)
--- PASS: TestAccAWSEcsCapacityProvider_ManagedScaling (122.22s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	126.208s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsCapacityProvider_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEcsCapacityProvider_ -timeout 180m
=== RUN   TestAccAWSEcsCapacityProvider_basic
=== PAUSE TestAccAWSEcsCapacityProvider_basic
=== RUN   TestAccAWSEcsCapacityProvider_disappears
=== PAUSE TestAccAWSEcsCapacityProvider_disappears
=== RUN   TestAccAWSEcsCapacityProvider_ManagedScaling
=== PAUSE TestAccAWSEcsCapacityProvider_ManagedScaling
=== RUN   TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== PAUSE TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== RUN   TestAccAWSEcsCapacityProvider_Tags
=== PAUSE TestAccAWSEcsCapacityProvider_Tags
=== CONT  TestAccAWSEcsCapacityProvider_basic
=== CONT  TestAccAWSEcsCapacityProvider_ManagedScalingPartial
=== CONT  TestAccAWSEcsCapacityProvider_ManagedScaling
=== CONT  TestAccAWSEcsCapacityProvider_Tags
=== CONT  TestAccAWSEcsCapacityProvider_disappears
--- PASS: TestAccAWSEcsCapacityProvider_basic (62.11s)
--- PASS: TestAccAWSEcsCapacityProvider_disappears (62.52s)
--- PASS: TestAccAWSEcsCapacityProvider_Tags (98.56s)
--- PASS: TestAccAWSEcsCapacityProvider_ManagedScalingPartial (105.01s)
--- PASS: TestAccAWSEcsCapacityProvider_ManagedScaling (145.98s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	149.215s
```

**Comment by ewbankkit** [comment]
@shuheiktgw Thanks for the contribution :tada: :clap:.

**Pull request merged**
