### PR TITLE
r/aws_sagemaker_domain: add arguments to DefaultResourceSpec

### LINKED ISSUE #21474: Missing argument in sagemaker domain for studio lifecycle configuration
### Terraform CLI and Terraform AWS Provider Version

Current Terraform Version
Terraform v0.12.31

provider.aws v3.63.0
(latest provider)

### Affected Resource(s)
* aws_sagemaker_domain
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain

### Use case
Trying to attach a lifecycle configuration to the jupyter_server_app_settings in sagemaker domain I've found out that there is one argument missing:

In Default User Settings --> Jupyter Server App Settings --> Default Resource Spec the argument LifecycleConfigArn is missing, it is available in several aws sagemaker API commands like:

update-domain: https://docs.aws.amazon.com/cli/latest/reference/sagemaker/update-domain.html
create-domain: https://docs.aws.amazon.com/cli/latest/reference/sagemaker/create-domain.html

### PR DESCRIPTION
**Pull request by philof**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21474

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccDomain_kernelGatewayAppSettings_lifecycleConfig' PKG_NAME=internal/service/sagemaker
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run=TestAccDomain_kernelGatewayAppSettings_lifecycleConfig -timeout 180m
=== RUN   TestAccDomain_kernelGatewayAppSettings_lifecycleConfig
--- PASS: TestAccDomain_kernelGatewayAppSettings_lifecycleConfig (402.17s)
PASS
ok       github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  403.972s
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
@philof missing docs

**Comment by fatboysalimshady** [comment]
@philof can we add this for create app as well?

**Comment by DrFaust92** [comment]
while verifying acceptance tests:

```
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig
panic: Invalid address to set: []string{"default_user_settings", "0", "kernel_gateway_app_settings", "0", "default_resource_spec", "0", "lifcycle_config_arn"}

goroutine 20393 [running]:
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*ResourceData).Set(0x14002c29300, 0x106ce39b5, 0x15, 0x1079d4060, 0x14002ab0510, 0x0, 0x0)
        /Users/ilia/go/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource_data.go:230 +0x2d4
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.resourceDomainRead(0x14002c29300, 0x108447f80, 0x140018c0000, 0x1400397fae0, 0x0)
        /Users/ilia/git/terraform-provider-aws/internal/service/sagemaker/domain.go:384 +0x4e4
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.resourceDomainCreate(0x14002c29300, 0x108447f80, 0x140018c0000, 0xffffffffffffffff, 0x14001bbd798)
        /Users/ilia/git/terraform-provider-aws/internal/service/sagemaker/domain.go:351 +0x6b0
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).create(0x1400049b180, 0x1097261a8, 0x14002aadbc0, 0x14002c29300, 0x108447f80, 0x140018c0000, 0x0, 0x0, 0x0)
        /Users/ilia/go/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:318 +0x170
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0x1400049b180, 0x1097261a8, 0x14002aadbc0, 0x14002197340, 0x14002a817e0, 0x108447f80, 0x140018c0000, 0x0, 0x0, 0x0, ...)
        /Users/ilia/go/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/resource.go:456 +0x4ec
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0x14000f700a8, 0x1097261a8, 0x14002aadbc0, 0x14002adca00, 0x14002aadbc0, 0x1090dd760, 0x0)
        /Users/ilia/go/pkg/mod/github.com/gdavison/terraform-plugin-sdk/v2@v2.7.1-0.20210913224932-c7c2dbd9e010/helper/schema/grpc_provider.go:955 +0x6f8
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0x14001f44120, 0x109726250, 0x14002aadbc0, 0x140021971f0, 0x14001f44120, 0x105c39b40, 0x108e5d480)
        /Users/ilia/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/server/server.go:332 +0x94
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x1090dd760, 0x14001f44120, 0x109726250, 0x14001ffeb40, 0x14001614480, 0x0, 0x109726250, 0x14001ffeb40, 0x14001c3b800, 0x750)
        /Users/ilia/go/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.3.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x1c8
google.golang.org/grpc.(*Server).processUnaryRPC(0x1400120a380, 0x10974ae78, 0x14002e58480, 0x140016c9a00, 0x1400253e600, 0x10d1f70e0, 0x0, 0x0, 0x0)
        /Users/ilia/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x3e8
google.golang.org/grpc.(*Server).handleStream(0x1400120a380, 0x10974ae78, 0x14002e58480, 0x140016c9a00, 0x0)
        /Users/ilia/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xa50
google.golang.org/grpc.(*Server).serveStreams.func1.2(0x1400211e1b0, 0x1400120a380, 0x10974ae78, 0x14002e58480, 0x140016c9a00)
        /Users/ilia/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0x94
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /Users/ilia/go/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1f8
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  3007.921s
```

**Comment by maldo91** [comment]
@DrFaust92 @philof can I help here somehow? Is there anything missing? Thanks :)

**Comment by DrFaust92** [comment]
Domain tests:

```
        --- PASS: TestAccSageMaker_serial/Domain/jupyterServerAppSettings (334.64s)
        --- PASS: TestAccSageMaker_serial/Domain/securityGroup (396.19s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig (332.03s)
        --- PASS: TestAccSageMaker_serial/Domain/basic (333.96s)
        --- PASS: TestAccSageMaker_serial/Domain/disappears (462.43s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettings (229.29s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage (395.96s)
        --- PASS: TestAccSageMaker_serial/Domain/kms (215.58s)
```

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by maldo91** [comment]
@DrFaust92 is it possible to add this to the next release?

**Comment by maldo91** [comment]
@DrFaust92 can we please add this fix on the next release? everything seems correct, right?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMaker_serial/App' PKG_NAME=internal/service/sagemaker         
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run=TestAccSageMaker_serial/App -timeout 180m
=== RUN   TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/App
=== RUN   TestAccSageMaker_serial/App/resourceSpec
=== RUN   TestAccSageMaker_serial/App/resourceSpecLifecycle
=== RUN   TestAccSageMaker_serial/App/basic
=== RUN   TestAccSageMaker_serial/App/disappears
=== RUN   TestAccSageMaker_serial/App/tags
--- PASS: TestAccSageMaker_serial (2515.27s)
    --- PASS: TestAccSageMaker_serial/App (2515.26s)
        --- PASS: TestAccSageMaker_serial/App/resourceSpec (443.02s)
        --- PASS: TestAccSageMaker_serial/App/resourceSpecLifecycle (523.98s)
        --- PASS: TestAccSageMaker_serial/App/basic (493.96s)
        --- PASS: TestAccSageMaker_serial/App/disappears (556.16s)
        --- PASS: TestAccSageMaker_serial/App/tags (498.14s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	2518.113s
% make testacc TESTARGS='-run=TestAccSageMaker_serial/Domain' PKG_NAME=internal/service/sagemaker
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run=TestAccSageMaker_serial/Domain -timeout 180m
=== RUN   TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/sharingSettings
=== RUN   TestAccSageMaker_serial/Domain/basic
=== RUN   TestAccSageMaker_serial/Domain/tags
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/kms
=== RUN   TestAccSageMaker_serial/Domain/securityGroup
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage
    domain_test.go:370: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/Domain/disappears
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage
    domain_test.go:331: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig
--- PASS: TestAccSageMaker_serial (2673.13s)
    --- PASS: TestAccSageMaker_serial/Domain (2673.13s)
        --- PASS: TestAccSageMaker_serial/Domain/sharingSettings (133.68s)
        --- PASS: TestAccSageMaker_serial/Domain/basic (255.62s)
        --- PASS: TestAccSageMaker_serial/Domain/tags (116.03s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings (194.16s)
        --- PASS: TestAccSageMaker_serial/Domain/kms (276.68s)
        --- PASS: TestAccSageMaker_serial/Domain/securityGroup (294.48s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/jupyterServerAppSettings (252.12s)
        --- PASS: TestAccSageMaker_serial/Domain/disappears (312.47s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettings (271.41s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage (315.88s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig (250.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	2676.242s
% make testacc TESTARGS='-run=TestAccSageMaker_serial/UserProfile' PKG_NAME=internal/service/sagemaker
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run=TestAccSageMaker_serial/UserProfile -timeout 180m
=== RUN   TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/UserProfile
=== RUN   TestAccSageMaker_serial/UserProfile/basic
=== RUN   TestAccSageMaker_serial/UserProfile/disappears
=== RUN   TestAccSageMaker_serial/UserProfile/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage
=== RUN   TestAccSageMaker_serial/UserProfile/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/tags
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_imageConfig
    user_profile_test.go:223: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
--- PASS: TestAccSageMaker_serial (2203.04s)
    --- PASS: TestAccSageMaker_serial/UserProfile (2203.04s)
        --- PASS: TestAccSageMaker_serial/UserProfile/basic (274.07s)
        --- PASS: TestAccSageMaker_serial/UserProfile/disappears (323.34s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettings (266.62s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage (267.17s)
        --- PASS: TestAccSageMaker_serial/UserProfile/jupyterServerAppSettings (265.02s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tags (266.67s)
        --- PASS: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings (268.95s)
        --- PASS: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_lifecycleConfig (271.18s)
        --- SKIP: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_imageConfig (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	2206.050s
```

**Pull request merged**
