### PR TITLE
Fix setting of the video_pid attribute in m2ts_settings

### LINKED ISSUE #29833: [Bug]: Incorrect encoder setting: `aws_medialive_channel`
### Terraform Core Version

1.3.9

### AWS Provider Version

4.56.0

### Affected Resource(s)

* aws_medialive_channel

### Expected Behavior

VideoPID to be applied

### Actual Behavior

Attributed not being passed correctly

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

https://github.com/hashicorp/terraform-provider-aws/blob/e84879d56e653f39f257c0b9709364a94c734dac/internal/service/medialive/channel_encoder_settings_schema.go#L4106-L4107

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by quartercastle**
### Description

Fix setting of the `video_pid` attribute in `m2ts_settings`

### Relations

Closes #29833

### Output from Acceptance Testing

```
$  make testacc TESTS=TestAccMediaLiveChannel_m2ts_settings PKG=medialive
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_m2ts_settings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_m2ts_settings
=== PAUSE TestAccMediaLiveChannel_m2ts_settings
=== CONT  TestAccMediaLiveChannel_m2ts_settings
--- PASS: TestAccMediaLiveChannel_m2ts_settings (104.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	106.488s
```

### CODE REVIEW

**Comment by quartercastle** [comment]
> Hey @quartercastle 👋 Thank you very much for your contribution! At times, our maintainers need to make direct edits to pull requests in order to help get it ready to be merged. Your current settings do not allow maintainers to make such edits. To help facilitate this, update your pull request to allow such edits as described in GitHub's [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) documentation. (If you're using a fork owned by an organization, your organization may not allow you to change this setting. If that is the case, let us know.)

I can't change this as the organisation i'm contributing from doesn't allow it at the moment.

**Comment by johnsonaj** [comment]
@quartercastle, the PR looks good. Since I cannot edit, can you correct the name of the `CHANGELOG` file to reflect the PR number? Name should be `29824.txt`

**Comment by quartercastle** [comment]
@johnsonaj thanks for the review, i have renamed the changelog in 9d7059d37.

**Comment by johnsonaj** [comment]
@quartercastle thanks for the contribution! 🎉

**Pull request merged**
