### PR TITLE
fix(events): fix arn based partner evernt bus id parse bug

### LINKED ISSUE #30293: [Bug]: Error creating "aws_cloudwatch_event_rule" while using Partner Event Sources - id format doesn't match
### Terraform Core Version

0.13.5, 0.14.0

### AWS Provider Version

4.0.0

### Affected Resource(s)

- aws_cloudwatch_event_rule

### Expected Behavior

Expected behaviour is that the EventBridge rule is created and all validations pass. While the rule does get created, it can't be used since a check fails due to an incorrect format. 

### Actual Behavior

Resource is created however it fails when the state is checked (terraform plan/apply).

### Relevant Error/Panic Output Snippet

```shell
Error: unexpected format for ID (arn:aws:events:eu-west-1:test-id:event-bus/aws.partner/salesforce.com/id1/id2/crm-sync-create-account-rule-terraform-test), expected EVENTBUSNAME/RULENAME or RULENAME
```

### Terraform Configuration Files

resource "aws_cloudwatch_event_rule" "event-bridge-rule" {
  name = "event-bridge-rule"
  description = "Testing creation of rules with Terraform"
  event_bus_name = data.aws_cloudwatch_event_bus.my-bus.name

  event_pattern = jsonencode({
    "source": [{
      "prefix": "aws.partner/salesforce.com"
    }],
    "detail-type": ["AccountChangeEvent"],
    "detail": {
      "payload": {
        "ChangeEventHeader": {
          "changeType": ["CREATE"]
        }
      }
    }
  })
}

### Steps to Reproduce

terraform plan / 
terraform apply

Both show the same error.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

I already researched the cause of why this happened and I got to the "_aws/internal/service/events/id.go_" file which contains a function called "**RuleParseResourceID**". 
A split of the rule name is done based on "/" and in my case the code will enter the 3rd "if" statement (if len(parts) > 2 ).

The event bus name that I have is under the following format: "arn:aws:events:eu-west-1:test-id:event-bus/aws.partner/salesforce.com/id1/id2"

The "id" that gets passed to the function is under the following format: 
"arn:aws:events:eu-west-1:test-id:event-bus/aws.partner/salesforce.com/id1/id2/test-rule-name"

I think the problem consists in our partner event bus name containing multiple "/". This makes the check of the "eventBusName" against the "eventBusARNPattern" regexp to fail causing the error to appear. I don't have the option to change the event bus name, it's created automatically.

### References

I found a very smilar issue - same resource, same error, same file and function causing the error- however it seems in my case it's still something different caused by a mismatch with the regular expression.
https://github.com/hashicorp/terraform-provider-aws/issues/18431

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by vitorf7**
### Description

This PR aims at fixing a bug related to issue #30293 where it seems that partner event bus rules can also make use be in the format `arn:...` which is causing some people (myself included) to not be able to create or even delete resources once you come across this bug.

### Relations

Closes #30293.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/27457.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/25510.

### References

Please refer to my comment in the initial issue in order to see the configuration I was using when I encountered this bug https://github.com/hashicorp/terraform-provider-aws/issues/30293#issuecomment-1505476917

### Output from Testing

```
$ make test TEST=internal/service/events/id_test.go TESTARGS=-run=TestRuleParseResourceID
==> Checking that code complies with gofmt requirements...
go test internal/service/events/id_test.go -run=TestRuleParseResourceID -timeout=5m
ok      command-line-arguments  0.342s
```

### CODE REVIEW

**Comment by TakumiHaruta** [comment]
Thanks for this bugfix.

Is anyone able to merge this PR and release?
Actually this bug blocked the development which requires to use EventBridge with a partner provider like Auth0.
It's a bit critical for us...

**Comment by vitorf7** [comment]
@TakumiHaruta Thank you so much. At my work we were also blocked because of this working with partner events as well (Genesys in my case).

Once it gets approved and merged in it should hopefully help you get everything sorted. If you are however in a pinch and wanna solve your problem sooner, then you could clone my branch locally and follow the guidelines on how to do local development from here https://hashicorp.github.io/terraform-provider-aws/development-environment/

I was personally facing some trouble when trying to use it since at work we had the terraform plan and terraform apply run from the docker image provided by hashicorp (and one we have at work) as my own machine is an Mac M1 which means the make build command from the makefile (in the terraform-provider-aws repo) would build an arch64 instead of a linux amd64.

After running env GOOS=linux GOARCH=amd64 go build ., then moving the built binary to the $GOPATH/bin and making sure that both the $GOPATH/bin and my ~/.terraformrc were both mounted to the correct places in the docker image, it all worked fine.

I was able to finally finish the work I was doing and it also meant that I not longer go the error you and I faced.

**Comment by TakumiHaruta** [comment]
@vitorf7 
Thank you for your guidance. That'd be really helpful.
We're actually hosting a private registry for aws provider on Terraform Cloud using goreleaser, but this PR seems not active since it was opened 3 months ago. I think it could be categorized as a hotfix.

@ewbankkit Hi, could you review and merge this PR when you have time? This is a bit critical for developers who use multiple providers.

**Comment by sean-redmond** [comment]
Be good to see this merged in, looks ready and will solve an issue I am running into.

**Comment by tapadarj** [comment]
Please confirm when it will be merged. I am facing the same issue.

**Comment by jar-b** [comment]
The `golangci-lint` action is failing due to network timeouts, not linter findings. Linting checks pass locally.

```console
% make lint PKG=events
==> Checking source code with golangci-lint...
==> Checking source code with providerlint...
==> Checking source code with importlint...
```

Will proceed with merging despite the failing check.

**Comment by jar-b** [comment]
Thanks for your contribution, @vitorf7 ! 👏

**Comment by vitorf7** [comment]
@jar-b no problem at all. Glad I was able to help.

**Pull request merged**
