### PR TITLE
data_source/aws_elasticache_replication_group: Output read_endpoint_addresses

### PR DESCRIPTION
**Pull request by commixon**
Relates to #5763

Changes proposed in this pull request:

* Adds `read_endpoint_addresses` in data_source_aws_elasticache_replication_group.go:
```
			"read_endpoint_addresses": {
				Type:     schema.TypeSet,
				Computed: true,
				Elem:     &schema.Schema{Type: schema.TypeString},
				Set:      schema.HashString,
			},
```

### CODE REVIEW

**Comment by RTodorov** [comment]
Hello there,

Any way we can get this PR reviewed? It's open for almost a year and the read-only endpoint is very important for many use-cases.

Thank you.

**Comment by RTodorov** [comment]
Hi @nywilken @joestump! Any chance we can make this happen? Thank you!

**Comment by ErrantConstruct** [comment]
I'm also curious if this can get merged in. Would be nice to spread read loads across the read replicas.

**Comment by RTodorov** [comment]
Hi @aeschright, can you please assist with this PR? Having the read endpoint address(es) is very important, this PR is 1 year old and we're getting no answer from the reviewers, this is very frustrating. Terraform itself is a great product but issues like this make it very hard to trust the ecosystem.
Thank you.

**Comment by aeschright** [comment]
Hi everyone! As you know, we're still digging through quite a backlog and onboarding new maintainers takes some time. At first look, I see that the test run results aren't included in the PR description, and that's something we'd want to have [before proceeding with the review](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#common-review-items). If @commixon is no longer able to work on this, someone else could submit a new PR with the changes. Thanks for your patience as we get things moving -- we appreciate the help!

**Comment by Shivang44** [comment]
@aeschright Hi, I've added a similar feature here with tests. Can you take a look? https://github.com/terraform-providers/terraform-provider-aws/issues/11313#issuecomment-578495783

**Comment by gdavison** [comment]
Thanks for the PR, @commixon. We've merged #9979, which also supports the resource

**Pull request closed without merging**
