### PR TITLE
Make the recovery_mechanism optional in account_recovery_settings

### PR DESCRIPTION
**Pull request by jakemillerkasasa**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes [#21143](https://github.com/hashicorp/terraform-provider-aws/issues/21143).
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30030.

I found that the schema for `account_recovery_setting` resource had the `recovery_mechanisms` property as required when it is optionals with max size of two in the [AWS](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cognito-userpool-accountrecoverysetting.html) documentation. The [terraform](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool#account_recovery_setting) documentation mirrors what the code was previously enforcing though. 

Output from acceptance testing:

```
$ make testacc TESTS=TestAccCognitoIDPUserPool_recovery PKG=cognitoidp
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 -run='TestAccCognitoIDPUserPool_recovery' -timeout 180m
=== RUN   TestAccCognitoIDPUserPool_recovery
=== PAUSE TestAccCognitoIDPUserPool_recovery
=== CONT  TestAccCognitoIDPUserPool_recovery
--- PASS: TestAccCognitoIDPUserPool_recovery (44.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	45.670s 

...
```

### CODE REVIEW

**Comment by AdamTylerLynch** [comment]
Verified docs and usage. LGTM 🚀

**Review by AdamTylerLynch — APPROVED** [review]

**Comment by jakemillerkasasa** [comment]
Hello, do we have insight on when this might get merged and if there is a targeted release to expect to see this change in? Thanks!

**Comment by bengaywins** [comment]
@AdamTylerLynch Any way to get this pushed through? We have user pools that do not need recovery mechanisms and this blocks that ability.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCognitoIDPUserPool_recovery\|TestAccCognitoIDPUserPool_basic' PKG=cognitoidp ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 2  -run=TestAccCognitoIDPUserPool_recovery\|TestAccCognitoIDPUserPool_basic -timeout 180m
=== RUN   TestAccCognitoIDPUserPool_basic
=== PAUSE TestAccCognitoIDPUserPool_basic
=== RUN   TestAccCognitoIDPUserPool_recovery
=== PAUSE TestAccCognitoIDPUserPool_recovery
=== CONT  TestAccCognitoIDPUserPool_basic
=== CONT  TestAccCognitoIDPUserPool_recovery
--- PASS: TestAccCognitoIDPUserPool_basic (19.01s)
--- PASS: TestAccCognitoIDPUserPool_recovery (40.93s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	46.251s
```

**Comment by ewbankkit** [comment]
@jakemillerkasasa Thanks for the contribution :tada: :clap:.
Since your changes it seems that AWS are now [provisioning default account recovery settings](https://docs.aws.amazon.com/cognito/latest/developerguide/how-to-recover-a-user-account.html):

> If you do not specify `AccountRecoverySetting`, Amazon Cognito uses the legacy mechanism to determine the password recovery method. In this case, Cognito uses a verified phone first. If the verified phone is not found for the user, Cognito falls back and will use verified email next.

So I changed the attribute to `Optional` + [`Computed`](https://developer.hashicorp.com/terraform/plugin/sdkv2/schemas/schema-behaviors#computed).

**Pull request merged**
