### PR TITLE
Implement dynamodb kinesis streaming destination

### LINKED ISSUE #16406: Amazon Kinesis Data Streams for Amazon DynamoDB
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Kinesis Data Streams for DynamoDB captures item-level modifications in any DynamoDB table and replicates them to a Kinesis data stream of your choice.

### New or Affected Resource(s)

* `aws_dynamodb_kinesis_streaming_destination`

### Potential Terraform Configuration

```hcl
resource "aws_dynamodb_kinesis_streaming_destination" "example" {
  table_name = aws_dynamodb_table.example.name
  stream_arn = aws_kinesis_stream.example.arn
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/now-you-can-use-amazon-kinesis-data-streams-to-capture-item-level-changes-in-your-amazon-dynamodb-table/).
[Developer Guide](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/kds.html).

Requires [AWS SDK v1.35.34](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.34):

* https://github.com/hashicorp/terraform-provider-aws/pull/16381

### PR DESCRIPTION
**Pull request by matthewrj**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16406

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Added resource for DynamoDB Kinesis streaming destination.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsDynamodbKinesisStreamingDestination'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsDynamodbKinesisStreamingDestination -timeout 120m
=== RUN   TestAccAwsDynamodbKinesisStreamingDestination_basic
=== PAUSE TestAccAwsDynamodbKinesisStreamingDestination_basic
=== RUN   TestAccAwsDynamodbKinesisStreamingDestination_disappears
=== PAUSE TestAccAwsDynamodbKinesisStreamingDestination_disappears
=== RUN   TestAccAwsDynamodbKinesisStreamingDestination_disappears_DynamoTable
=== PAUSE TestAccAwsDynamodbKinesisStreamingDestination_disappears_DynamoTable
=== CONT  TestAccAwsDynamodbKinesisStreamingDestination_basic
=== CONT  TestAccAwsDynamodbKinesisStreamingDestination_disappears_DynamoTable
=== CONT  TestAccAwsDynamodbKinesisStreamingDestination_disappears
--- PASS: TestAccAwsDynamodbKinesisStreamingDestination_disappears_DynamoTable (99.76s)
--- PASS: TestAccAwsDynamodbKinesisStreamingDestination_disappears (100.39s)
--- PASS: TestAccAwsDynamodbKinesisStreamingDestination_basic (134.92s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	136.461s
```

### CODE REVIEW

**Comment by matthewrj** [comment]
Would love an update on when we can expect this PR to be reviewed.

**Comment by barryoneill** [comment]
This PR is three months old now;  Is there some outstanding issue with it that one of us could address to get it merged?

**Comment by nicolas-lopez** [comment]
Hello this PR has been open for almost 4 month every checks and tests are green. Is there any reason why this PR can't be merged ? This new feature would be really appreciated. Thanks for your work and time.

**Comment by barendb** [comment]
Adding a bump to this as well, Matt has put some good work into this, would ❤️ to see it landed...

**Comment by kgrits** [comment]
Hey, any updates on this? I would reaaaally love to have this merged 👍

**Comment by anGie44** [comment]
Hi @matthewrj , thank you for this PR and your patience! I'll be completing my review to get this in an upcoming release, but just wanted to drop a note to please push up a `.changelog/16743.txt` file with this PR in the meantime. thanks in advance! (additional reference if needed: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-format)

**Review by anGie44 — CHANGES_REQUESTED** [review]

**Comment by anGie44** [comment]
Hi @matthewrj , thank you again for submitting this PR 😄 Since our release cadence generally falls on Thursdays, I've pushed up the changes to address the CR comments in addition to some additional refactoring to get everything inline for merging and making it into the upcoming release.

**Comment by anGie44** [comment]
Output of acceptance tests (commercial):
```
--- PASS: TestAccAwsDynamoDbKinesisStreamingDestination_disappears (65.38s)
--- PASS: TestAccAwsDynamoDbKinesisStreamingDestination_disappears_DynamoDbTable (66.09s)
--- PASS: TestAccAwsDynamoDbKinesisStreamingDestination_basic (68.61s)
```

Output of acceptance tests (Gov cloud):
```
--- SKIP: TestAccAwsDynamoDbKinesisStreamingDestination_disappears (52.20s)
--- SKIP: TestAccAwsDynamoDbKinesisStreamingDestination_disappears_DynamoDbTable (52.21s)
--- SKIP: TestAccAwsDynamoDbKinesisStreamingDestination_basic (52.21s)
```

**Review by anGie44 — APPROVED** [review]

**Comment by barryoneill** [comment]
Thanks @anGie44 !

**Pull request merged**
