### PR TITLE
Support for features in GuardDuty Detector

### LINKED ISSUE #30303: [Enhancement]: Use `features` instead of `dataSources` in aws_guardduty_detector
### Description

The use of `dataSources` is deprecated and the use of `features` is recommended.
https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-feature-object-api-changes-march2023.html
If new features are added to GuardDuty in the future, they will not be available.
> GuardDuty will not add new data source after this modification.

Adding RDS Login events (#28229) requires support for this issue.

### Affected Resource(s) and/or Data Source(s)

aws_guardduty_detector

### Potential Terraform Configuration

_No response_

### References

https://docs.aws.amazon.com/guardduty/latest/ug/guardduty-feature-object-api-changes-march2023.html
https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DetectorFeatureConfiguration.html
https://docs.aws.amazon.com/guardduty/latest/APIReference/API_DataSourceConfigurations.html

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by ringods**
### Relations

Closes #30303.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/18619.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/21030.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/19893.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/32949.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30859.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28229.

### Output from Acceptance Testing

```
$ make testacc TESTS="TestAccGuardDuty_serial/Detector" PKG=guardduty

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20 -run='TestAccGuardDuty_serial/Detector'  -timeout 180m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/Detector
=== RUN   TestAccGuardDuty_serial/Detector/features_eks_audit_logs
    detector_test.go:408: Step 1/3 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_guardduty_detector.test will be updated in-place
          ~ resource "aws_guardduty_detector" "test" {
                id                           = "66c4245df4d8e7e995a11d7a1d692dbd"
                # (5 unchanged attributes hidden)
        
              ~ features {
                  ~ name   = "CLOUD_TRAIL" -> "EKS_AUDIT_LOGS"
                    # (1 unchanged attribute hidden)
                }
              - features {
                  - enable = true -> null
                  - name   = "DNS_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "FLOW_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "S3_DATA_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_AUDIT_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EBS_MALWARE_PROTECTION" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "RDS_LOGIN_EVENTS" -> null
                }
              - features {
                  - enable = false -> null
                  - name   = "EKS_RUNTIME_MONITORING" -> null
        
                  - additional_configuration {
                      - enable = false -> null
                      - name   = "EKS_ADDON_MANAGEMENT" -> null
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "LAMBDA_NETWORK_LOGS" -> null
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
=== RUN   TestAccGuardDuty_serial/Detector/features_rds_login_events
    detector_test.go:570: Step 1/3 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_guardduty_detector.test will be updated in-place
          ~ resource "aws_guardduty_detector" "test" {
                id                           = "4ac4245e10a2615ac6f5ef2900f9672b"
                # (5 unchanged attributes hidden)
        
              ~ features {
                  ~ name   = "CLOUD_TRAIL" -> "RDS_LOGIN_EVENTS"
                    # (1 unchanged attribute hidden)
                }
              - features {
                  - enable = true -> null
                  - name   = "DNS_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "FLOW_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "S3_DATA_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_AUDIT_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EBS_MALWARE_PROTECTION" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "RDS_LOGIN_EVENTS" -> null
                }
              - features {
                  - enable = false -> null
                  - name   = "EKS_RUNTIME_MONITORING" -> null
        
                  - additional_configuration {
                      - enable = false -> null
                      - name   = "EKS_ADDON_MANAGEMENT" -> null
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "LAMBDA_NETWORK_LOGS" -> null
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
=== RUN   TestAccGuardDuty_serial/Detector/features_eks_runtime_monitoring
    detector_test.go:651: Step 1/3 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_guardduty_detector.test will be updated in-place
          ~ resource "aws_guardduty_detector" "test" {
                id                           = "fac4245e2bfbf48032b05bbd94917971"
                # (5 unchanged attributes hidden)
        
              ~ features {
                  ~ name   = "CLOUD_TRAIL" -> "EKS_RUNTIME_MONITORING"
                    # (1 unchanged attribute hidden)
        
                  + additional_configuration {
                      + enable = true
                      + name   = "EKS_ADDON_MANAGEMENT"
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "DNS_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "FLOW_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "S3_DATA_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_AUDIT_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EBS_MALWARE_PROTECTION" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "RDS_LOGIN_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_RUNTIME_MONITORING" -> null
        
                  - additional_configuration {
                      - enable = true -> null
                      - name   = "EKS_ADDON_MANAGEMENT" -> null
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "LAMBDA_NETWORK_LOGS" -> null
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
=== RUN   TestAccGuardDuty_serial/Detector/datasource_basic
=== RUN   TestAccGuardDuty_serial/Detector/datasource_id
=== RUN   TestAccGuardDuty_serial/Detector/basic
=== RUN   TestAccGuardDuty_serial/Detector/datasources_s3logs
=== RUN   TestAccGuardDuty_serial/Detector/datasources_malware_protection
=== RUN   TestAccGuardDuty_serial/Detector/features_ebs_malware_protection
    detector_test.go:489: Step 1/3 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_guardduty_detector.test will be updated in-place
          ~ resource "aws_guardduty_detector" "test" {
                id                           = "aec4245fa390ffb733dd33a8d363d8a0"
                # (5 unchanged attributes hidden)
        
              ~ features {
                  ~ name   = "CLOUD_TRAIL" -> "EBS_MALWARE_PROTECTION"
                    # (1 unchanged attribute hidden)
                }
              - features {
                  - enable = true -> null
                  - name   = "DNS_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "FLOW_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "S3_DATA_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_AUDIT_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EBS_MALWARE_PROTECTION" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "RDS_LOGIN_EVENTS" -> null
                }
              - features {
                  - enable = false -> null
                  - name   = "EKS_RUNTIME_MONITORING" -> null
        
                  - additional_configuration {
                      - enable = false -> null
                      - name   = "EKS_ADDON_MANAGEMENT" -> null
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "LAMBDA_NETWORK_LOGS" -> null
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
=== RUN   TestAccGuardDuty_serial/Detector/tags
=== RUN   TestAccGuardDuty_serial/Detector/datasources_kubernetes_audit_logs
=== RUN   TestAccGuardDuty_serial/Detector/datasources_all
=== RUN   TestAccGuardDuty_serial/Detector/features_s3_data_events
    detector_test.go:327: Step 1/3 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_guardduty_detector.test will be updated in-place
          ~ resource "aws_guardduty_detector" "test" {
                id                           = "b8c42460d47fe3280fae51468feed887"
                # (5 unchanged attributes hidden)
        
              ~ features {
                  ~ name   = "CLOUD_TRAIL" -> "S3_DATA_EVENTS"
                    # (1 unchanged attribute hidden)
                }
              - features {
                  - enable = true -> null
                  - name   = "DNS_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "FLOW_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "S3_DATA_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_AUDIT_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EBS_MALWARE_PROTECTION" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "RDS_LOGIN_EVENTS" -> null
                }
              - features {
                  - enable = false -> null
                  - name   = "EKS_RUNTIME_MONITORING" -> null
        
                  - additional_configuration {
                      - enable = false -> null
                      - name   = "EKS_ADDON_MANAGEMENT" -> null
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "LAMBDA_NETWORK_LOGS" -> null
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccGuardDuty_serial (392.07s)
    --- FAIL: TestAccGuardDuty_serial/Detector (392.07s)
        --- FAIL: TestAccGuardDuty_serial/Detector/features_eks_audit_logs (15.74s)
        --- FAIL: TestAccGuardDuty_serial/Detector/features_rds_login_events (13.92s)
        --- FAIL: TestAccGuardDuty_serial/Detector/features_eks_runtime_monitoring (14.08s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasource_basic (29.56s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasource_id (18.28s)
        --- PASS: TestAccGuardDuty_serial/Detector/basic (62.41s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_s3logs (34.27s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_malware_protection (33.69s)
        --- FAIL: TestAccGuardDuty_serial/Detector/features_ebs_malware_protection (13.84s)
        --- PASS: TestAccGuardDuty_serial/Detector/tags (47.62s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_kubernetes_audit_logs (34.12s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_all (60.60s)
        --- FAIL: TestAccGuardDuty_serial/Detector/features_s3_data_events (13.94s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	394.198s
FAIL

```

Current tests fail on the new `features`. See my ask for help below.

### CODE REVIEW

**Comment by ringods** [comment]
I need help to complete the test suite!

The new `features` API to a GuardDuty `detector` always populates the default values in the `GetDetector` API call. Hence, even when writing this as input HCL:

```hcl
resource "aws_guardduty_detector" "test" {
	features {
		name = "EKS_AUDIT_LOGS"
		enable = %[1]t
	}
}
```

all the other features are populated with the default values. This isn't the case for the deprecated `datasources` property. The output is this:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20 -run='TestAccGuardDuty_serial/Detector/features_s3_data_events'  -timeout 180m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/Detector
=== RUN   TestAccGuardDuty_serial/Detector/features_s3_data_events
    detector_test.go:327: Step 1/3 error: After applying this test step, the plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_guardduty_detector.test will be updated in-place
          ~ resource "aws_guardduty_detector" "test" {
                id                           = "9ac42167a267a218cc3a9cf1c0d8ad2d"
                # (5 unchanged attributes hidden)
        
              ~ features {
                  ~ name   = "CLOUD_TRAIL" -> "S3_DATA_EVENTS"
                    # (1 unchanged attribute hidden)
                }
              - features {
                  - enable = true -> null
                  - name   = "DNS_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "FLOW_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "S3_DATA_EVENTS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EKS_AUDIT_LOGS" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "EBS_MALWARE_PROTECTION" -> null
                }
              - features {
                  - enable = true -> null
                  - name   = "RDS_LOGIN_EVENTS" -> null
                }
              - features {
                  - enable = false -> null
                  - name   = "EKS_RUNTIME_MONITORING" -> null
        
                  - additional_configuration {
                      - enable = false -> null
                      - name   = "EKS_ADDON_MANAGEMENT" -> null
                    }
                }
              - features {
                  - enable = true -> null
                  - name   = "LAMBDA_NETWORK_LOGS" -> null
                }
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccGuardDuty_serial (15.93s)
    --- FAIL: TestAccGuardDuty_serial/Detector (15.93s)
        --- FAIL: TestAccGuardDuty_serial/Detector/features_s3_data_events (15.93s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	18.101s
FAIL
```

How should I write the tests that I verify the configured feature to be in the list with the correct `enabled` state?

**Comment by justinretzolk** [comment]
Hey @ringods 👋 Thank you for taking the time to raise this! Since you're having issues with the tests, feel free to leave them for now, and when we're able to prioritize this, someone from the team will be happy to help workshop them 🙂

**Comment by justinretzolk** [comment]
Hey all 👋 Thank you for checking in on this! Unfortunately I can't provide an ETA on when this will be reviewed/merged due to the potential of shifting priorities. We prioritize by count of :+1: reactions and a few other things (more information on our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) if you're interested). That said, with the deprecation called out above, I'll make sure to bring this one up to the team to see what we can do.

**Comment by ewbankkit** [comment]
@xxx Thanks for the contribution :tada: :clap:.
The solution I came up with is to have a separate `aws_guardduty_detector_feature` resource that manages a single detector feature.
You would then have one instance of the resource for each feature you want to manage via Terraform.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccGuardDuty_serial/Filter' PKG=guardduty
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20  -run=TestAccGuardDuty_serial/Filter -timeout 360m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/Filter
=== RUN   TestAccGuardDuty_serial/Filter/basic
=== RUN   TestAccGuardDuty_serial/Filter/update
=== RUN   TestAccGuardDuty_serial/Filter/tags
=== RUN   TestAccGuardDuty_serial/Filter/disappears
--- PASS: TestAccGuardDuty_serial (172.71s)
    --- PASS: TestAccGuardDuty_serial/Filter (172.71s)
        --- PASS: TestAccGuardDuty_serial/Filter/basic (49.88s)
        --- PASS: TestAccGuardDuty_serial/Filter/update (38.80s)
        --- PASS: TestAccGuardDuty_serial/Filter/tags (58.11s)
        --- PASS: TestAccGuardDuty_serial/Filter/disappears (25.92s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	177.788s
```
```console
% make testacc TESTARGS='-run=TestAccGuardDuty_serial/^Detector$$/datasource_' PKG=guardduty
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20  -run=TestAccGuardDuty_serial/^Detector$/datasource_ -timeout 360m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/Detector
=== RUN   TestAccGuardDuty_serial/Detector/datasource_basic
=== RUN   TestAccGuardDuty_serial/Detector/datasource_id
--- PASS: TestAccGuardDuty_serial (43.59s)
    --- PASS: TestAccGuardDuty_serial/Detector (43.59s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasource_basic (22.86s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasource_id (20.73s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	48.907s
```
```console
% make testacc TESTARGS='-run=TestAccGuardDuty_serial/DetectorFeature' PKG=guardduty
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20  -run=TestAccGuardDuty_serial/DetectorFeature -timeout 360m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/DetectorFeature
=== RUN   TestAccGuardDuty_serial/DetectorFeature/multiple
=== RUN   TestAccGuardDuty_serial/DetectorFeature/basic
=== RUN   TestAccGuardDuty_serial/DetectorFeature/additional_configuration
--- PASS: TestAccGuardDuty_serial (142.21s)
    --- PASS: TestAccGuardDuty_serial/DetectorFeature (142.21s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/multiple (64.97s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/basic (21.23s)
        --- PASS: TestAccGuardDuty_serial/DetectorFeature/additional_configuration (56.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	147.222s
```
```console
% make testacc TESTARGS='-run=TestAccGuardDuty_serial/^Detector$$' PKG=guardduty
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/guardduty/... -v -count 1 -parallel 20  -run=TestAccGuardDuty_serial/^Detector$ -timeout 360m
=== RUN   TestAccGuardDuty_serial
=== PAUSE TestAccGuardDuty_serial
=== CONT  TestAccGuardDuty_serial
=== RUN   TestAccGuardDuty_serial/Detector
=== RUN   TestAccGuardDuty_serial/Detector/tags
=== RUN   TestAccGuardDuty_serial/Detector/datasource_basic
=== RUN   TestAccGuardDuty_serial/Detector/datasource_id
=== RUN   TestAccGuardDuty_serial/Detector/basic
=== RUN   TestAccGuardDuty_serial/Detector/datasources_s3logs
=== RUN   TestAccGuardDuty_serial/Detector/datasources_kubernetes_audit_logs
=== RUN   TestAccGuardDuty_serial/Detector/datasources_malware_protection
=== RUN   TestAccGuardDuty_serial/Detector/datasources_all
--- PASS: TestAccGuardDuty_serial (370.85s)
    --- PASS: TestAccGuardDuty_serial/Detector (370.85s)
        --- PASS: TestAccGuardDuty_serial/Detector/tags (55.58s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasource_basic (21.83s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasource_id (21.22s)
        --- PASS: TestAccGuardDuty_serial/Detector/basic (78.72s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_s3logs (39.46s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_kubernetes_audit_logs (39.58s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_malware_protection (42.37s)
        --- PASS: TestAccGuardDuty_serial/Detector/datasources_all (72.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/guardduty	375.899s
```

**Pull request merged**
