### PR TITLE
Service Catalog Constraint resources

### PR DESCRIPTION
**Pull request by ahgittin**
This PR adds four resources for Service Catalog constraints:

* `servicecatalog_constraint`
* `servicecatalog_launch_notification_constraint`
* `servicecatalog_launch_role_constraint`
* `servicecatalog_launch_template_constraint`

The first of these is based on the AWS API which supports any constraint --https://docs.aws.amazon.com/servicecatalog/latest/dg/API_CreateConstraint.html .  The other three are based on the declarative CFN types which are simpler to work with -- eg https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-servicecatalog-launchtemplateconstraint.html.  The latter three as implemented here re-use code from the first but faithfully follow the CFN model.

This builds on (yet unmerged) #13797 which provides the Product and other SC resources used here.  (This PR will be considerably smaller once that one is merged.)

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #13797

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Resource: `aws_servicecatalog_constraint`
New Resource: `aws_servicecatalog_launch_notification_constraint`
New Resource: `aws_servicecatalog_launch_role_constraint`
New Resource: `aws_servicecatalog_launch_template_constraint`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSServiceCatalog[A-Za-z]*Constraint'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSServiceCatalog[A-Za-z]*Constraint -timeout 120m
=== RUN   TestAccAWSServiceCatalogConstraint_basic
=== PAUSE TestAccAWSServiceCatalogConstraint_basic
=== RUN   TestAccAWSServiceCatalogConstraint_disappears
=== PAUSE TestAccAWSServiceCatalogConstraint_disappears
=== RUN   TestAccAWSServiceCatalogConstraint_updateDescription
=== PAUSE TestAccAWSServiceCatalogConstraint_updateDescription
=== RUN   TestAccAWSServiceCatalogConstraint_updateParameters
=== PAUSE TestAccAWSServiceCatalogConstraint_updateParameters
=== RUN   TestAccAWSServiceCatalogLaunchNotificationConstraint_basic
=== PAUSE TestAccAWSServiceCatalogLaunchNotificationConstraint_basic
=== RUN   TestAccAWSServiceCatalogLaunchNotificationConstraint_disappears
=== PAUSE TestAccAWSServiceCatalogLaunchNotificationConstraint_disappears
=== RUN   TestAccAWSServiceCatalogLaunchNotificationConstraint_updateNotificationArns
=== PAUSE TestAccAWSServiceCatalogLaunchNotificationConstraint_updateNotificationArns
=== RUN   TestAccAWSServiceCatalogLaunchRoleConstraint_basic
=== PAUSE TestAccAWSServiceCatalogLaunchRoleConstraint_basic
=== RUN   TestAccAWSServiceCatalogLaunchRoleConstraint_disappears
--- PASS: TestAccAWSServiceCatalogLaunchRoleConstraint_disappears (36.42s)
=== RUN   TestAccAWSServiceCatalogLaunchRoleConstraint_updateParameters
=== PAUSE TestAccAWSServiceCatalogLaunchRoleConstraint_updateParameters
=== RUN   TestAccAWSServiceCatalogLaunchTemplateConstraint_basic
=== PAUSE TestAccAWSServiceCatalogLaunchTemplateConstraint_basic
=== RUN   TestAccAWSServiceCatalogLaunchTemplateConstraint_disappears
=== PAUSE TestAccAWSServiceCatalogLaunchTemplateConstraint_disappears
=== CONT  TestAccAWSServiceCatalogConstraint_basic
=== CONT  TestAccAWSServiceCatalogLaunchNotificationConstraint_updateNotificationArns
=== CONT  TestAccAWSServiceCatalogLaunchTemplateConstraint_basic
=== CONT  TestAccAWSServiceCatalogLaunchRoleConstraint_updateParameters
=== CONT  TestAccAWSServiceCatalogLaunchTemplateConstraint_disappears
=== CONT  TestAccAWSServiceCatalogLaunchRoleConstraint_basic
=== CONT  TestAccAWSServiceCatalogConstraint_updateParameters
=== CONT  TestAccAWSServiceCatalogLaunchNotificationConstraint_disappears
=== CONT  TestAccAWSServiceCatalogConstraint_updateDescription
=== CONT  TestAccAWSServiceCatalogConstraint_disappears
=== CONT  TestAccAWSServiceCatalogLaunchNotificationConstraint_basic
--- PASS: TestAccAWSServiceCatalogLaunchTemplateConstraint_disappears (28.87s)
--- PASS: TestAccAWSServiceCatalogConstraint_disappears (28.92s)
--- PASS: TestAccAWSServiceCatalogLaunchNotificationConstraint_basic (29.11s)
--- PASS: TestAccAWSServiceCatalogLaunchTemplateConstraint_basic (29.61s)
--- PASS: TestAccAWSServiceCatalogConstraint_basic (29.79s)
--- PASS: TestAccAWSServiceCatalogLaunchNotificationConstraint_disappears (32.86s)
--- PASS: TestAccAWSServiceCatalogLaunchRoleConstraint_basic (36.27s)
--- PASS: TestAccAWSServiceCatalogLaunchNotificationConstraint_updateNotificationArns (41.89s)
--- PASS: TestAccAWSServiceCatalogConstraint_updateDescription (43.29s)
--- PASS: TestAccAWSServiceCatalogLaunchRoleConstraint_updateParameters (45.76s)
--- PASS: TestAccAWSServiceCatalogConstraint_updateParameters (46.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	84.153s
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by ahgittin** [comment]
This has been updated as per the 18 Aug notification to use the v2 sdk and remove `aws.erb` (fixing the conflicts), and also updating to conform to the stricter markdown checks.

**Comment by YakDriver** [comment]
@ahgittin Thank you for your work on this PR! I will be working on this before long. In order to expedite the process, I will likely make some changes. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Comment by YakDriver** [comment]
@ahgittin @cloudsoft Thank you very much for all your work on this PR! I'm excited to work with you on this. However, in order to work with this PR, I need two things:

1. You must check the "Allow edits from maintainers" box. It is currently not checked. (Only @cloudsoft will be able to check the box since the fork with this branch is in the @cloudsoft repo.)
2. Currently there are 212 commits in this branch, many of which make significant conflicting changes. All 212 commits need to be squashed into a single commit to proceed.

Since we look forward to adding this feature to the AWS Provider, we need you to make these changes by March 11, 2021. If you are unable to do this, we understand and thank you for your work. However, we will not be able to use this contribution.

**Comment by ahgittin** [comment]
Replaced by https://github.com/hashicorp/terraform-provider-aws/pull/18074

**Pull request closed without merging**
