### PR TITLE
Bugfix: AppFlow: Ignore empty tasks

### LINKED ISSUE #25095: aws_appflow_flow has too strict validations on task.source_fields
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.2.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.16.0
```

### Affected Resource(s)

* aws_appflow_flow

### Terraform Configuration Files

```hcl
resource "aws_appflow_flow" "salesforce_to_eventbridge" {
  name = "example"

  source_flow_config {
    connector_type = "Salesforce"
    connector_profile_name = "my-connection"
    source_connector_properties {
      salesforce {
        object = "AccountChangeEvent"
      }
    }
  }

  destination_flow_config {
    connector_type = "EventBridge"
    destination_connector_properties {
      event_bridge {
        object = "aws.partner/appflow/salesforce.com/${data.aws_caller_identity.current.account_id}/example"

        error_handling_config {
          bucket_name = module.large_events_bucket.name
        }
      }
    }
  }

  task {
    task_type         = "Map_all"
    source_fields     = []
    task_properties = {
      EXCLUDE_SOURCE_FIELDS_LIST = "[]"
    }
    connector_operator {
      salesforce = "NO_OP"
    }
  }

  trigger_config {
    trigger_type = "Event"
  }
}

locals {
  large_events_bucket_name = "asdfasdf-appflow-salesforce-large-events"
}

module "large_events_bucket" {
  source  = "terraform-aws-modules/s3-bucket/aws"
  version = "3.2.1"

  bucket = local.large_events_bucket_name
  acl    = "private"

  attach_policy = true
  policy = jsonencode({
    Version = "2012-10-17"
    Statement = [{
      Effect = "Allow"
      Principal = {
        Service = "appflow.amazonaws.com"
      }
      Action = [
        "s3:PutObject",
        "s3:GetBucketAcl",
        "s3:PutObjectAcl",
        "s3:AbortMultipartUpload",
        "s3:ListMultipartUploadParts",
        "s3:ListBucketMultipartUploads",
      ]
      Resource = [
        "arn:aws:s3:::${local.large_events_bucket_name}",
        "arn:aws:s3:::${local.large_events_bucket_name}/*",
      ]
    }]
  })
}

```

### Expected Behavior

The flow should be created. The same configuration with CloudFormation works:

```yml
Resources:
  Flow:
    Type: 'AWS::AppFlow::Flow'
    Properties:
      FlowName: example
      SourceFlowConfig:
        ConnectorProfileName: my-connection
        ConnectorType: Salesforce
        SourceConnectorProperties:
          Salesforce:
            Object: AccountChangeEvent
      DestinationFlowConfigList:
        - ConnectorType: EventBridge
          DestinationConnectorProperties:
            EventBridge:
              Object: aws.partner/appflow/salesforce.com/${data.aws_caller_identity.current.account_id}/example
              ErrorHandlingConfig:
                BucketName: module.large_events_bucket.name
      Tasks:
        - TaskType: Map_all
          SourceFields: []
          TaskProperties: 
          - Key: EXCLUDE_SOURCE_FIELDS_LIST
            Value: '[]'
          ConnectorOperator:
            Salesforce: NO_OP
      TriggerConfig:
        TriggerType: Event
```

The goal is to have an appflow that passes each event field 1:1 to event bridge without having to specify each field explicitly.
https://stackoverflow.com/questions/66742683/how-to-map-fields-automatically-in-appflow

### Actual Behavior

The flow is not created with the following validation error:

```
│ Error: creating Appflow Flow (example): InvalidParameter: 1 validation error(s) found.
│ - missing required field, CreateFlowInput.Tasks[0].SourceFields.
│ 
│ 
│   with aws_appflow_flow.salesforce_to_eventbridge,
│   on main.tf line 1, in resource "aws_appflow_flow" "salesforce_to_eventbridge":
│   1: resource "aws_appflow_flow" "salesforce_to_eventbridge" {
```

### Steps to Reproduce

1. `terraform apply`

### PR DESCRIPTION
**Pull request by camro**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #25095

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by didiqaz122** [comment]
good

**Comment by camro** [comment]
Bump

**Comment by n11c** [comment]
@justinretzolk, the issue that this PR solves is really blocking for a bunch of users including myself.  
I just tested with provider 5.1.0 and the bug is still there:

```
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:       TaskType: "Map"
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:     },
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:     {
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:     },
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:     {
2023-06-05T09:58:44.723+0200 [DEBUG] provider.terraform-provider-aws_v5.1.0_x5:       ConnectorOperator: {

```


Any chance it could be considered for release soon?

**Comment by camro** [comment]
Bump

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTARGS='-run=TestAccAppFlowFlow_' PKG=appflow

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20  -run=TestAccAppFlowFlow_ -timeout 180m
--- PASS: TestAccAppFlowFlow_disappears (28.70s)
--- PASS: TestAccAppFlowFlow_TaskProperties (29.96s)
--- PASS: TestAccAppFlowFlow_basic (32.38s)
--- PASS: TestAccAppFlowFlow_update (47.04s)
--- PASS: TestAccAppFlowFlow_S3_outputFormatConfig_ParquetFileType (47.31s)
--- PASS: TestAccAppFlowFlow_tags (66.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	69.406s
```

**Comment by johnsonaj** [comment]
Thank you for the contribution! 🎉

**Comment by vgw-chriskruger** [comment]
I tried this fix out in 5.9.0 yesterday. Has it been tested? It didn't seem to work for me.

Update: Looking at the fix (I am not really familiar with go) I don't really understand why it would work? It looks like it is doing pointer comparison when we want structural comparison -  which is unlikely to ever break anything in this case, but  I don't see how it work? Happy to be educated if I am wrong.

**Pull request merged**
