### PR TITLE
r/cloudtrail: Exclude Management Event Sources

### LINKED ISSUE #11448: aws_cloudtrail resource: add support for exclude_management_event_sources to event_selector
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
They added an option to CloudTrail to exclude certain types of management events from your CloudTrail. This is currently just to filter out KMS events from your CloudTrail, since KMS can generate a lot of events if you have application(s) that use KMS for frequent encryption operations.

It doesn't look like the resource currently supports configuring this option.

### New or Affected Resource(s)

* resource: aws_cloudtrail

### Potential Terraform Configuration

```hcl
resource "aws_cloudtrail" "foo" {
  name = "foo"
  s3_bucket_name = "someCloudTrailBucket"

  event_selector {
    include_management_events        = true
    read_write_type                  = "All"
    exclude_management_event_sources = ["kms.amazonaws.com"]
  }
}
```

### References

* https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_EventSelector.html#awscloudtrail-Type-EventSelector-ExcludeManagementEventSources

### PR DESCRIPTION
**Pull request by StephenKing**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Description

[`ExcludeManagementEventSources`](https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_EventSelector.html) allows to disable KMS events to be included in CloudTrail trails. We paid >$2000 last month to store KMS decrypt events and Terraform doesn't yet support to disable this.

This PR is based on previous work by @DrFaust92 in #12390

Closes #11448

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_cloudtrail: Add `exclude_management_event_sources` attribute to `event_selector` configuration block
```

### Affected Resource(s)

- resource: aws_cloudtrail

###  Terraform Configuration

```hcl
resource "aws_cloudtrail" "this" {
  name = "test"
  s3_bucket_name = "test"

  event_selector {
    exclude_management_event_sources = ["kms.amazonaws.com"]
  }
}
```
Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloudTrail/Trail/eventSelectorExclude'      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudTrail/Trail/eventSelectorExclude -timeout 120m
=== RUN   TestAccAWSCloudTrailServiceAccount_basic
=== PAUSE TestAccAWSCloudTrailServiceAccount_basic
=== RUN   TestAccAWSCloudTrailServiceAccount_Region
=== PAUSE TestAccAWSCloudTrailServiceAccount_Region
=== RUN   TestAccAWSCloudTrail_serial
=== RUN   TestAccAWSCloudTrail_serial/Trail
=== RUN   TestAccAWSCloudTrail_serial/Trail/eventSelectorExclude
--- PASS: TestAccAWSCloudTrail_serial (103.27s)
    --- PASS: TestAccAWSCloudTrail_serial/Trail (103.27s)
        --- PASS: TestAccAWSCloudTrail_serial/Trail/eventSelectorExclude (103.27s)
=== CONT  TestAccAWSCloudTrailServiceAccount_basic
=== CONT  TestAccAWSCloudTrailServiceAccount_Region
--- PASS: TestAccAWSCloudTrailServiceAccount_basic (29.17s)
--- PASS: TestAccAWSCloudTrailServiceAccount_Region (29.83s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       134.596s
```

### CODE REVIEW

**Comment by ohmer** [comment]
any chance this gets merged?

**Comment by jglopez** [comment]
CloudTrail now also allows the ability to "Exclude Amazon RDS Data API events" (`rdsdata.amazonaws.com`) too.

https://docs.aws.amazon.com/awscloudtrail/latest/APIReference/API_EventSelector.html#awscloudtrail-Type-EventSelector-ExcludeManagementEventSources
https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/logging-using-cloudtrail-data-api.html#logging-using-cloudtrail-data-api.excluding-cloudtrail-events

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Review by anGie44 — APPROVED** [review]
Thank you for your contribution @StephenKing , overall LGTM 🚀 I've modified the tests a bit to check for each supported exclusion value and added a changelog file to get this into our upcoming release.

Output of acceptance tests (note failure in `enableLogging` occurs in `main`, unrelated to these changes):
```
--- FAIL: TestAccCloudTrail_serial (1015.57s)
    --- FAIL: TestAccCloudTrail_serial/Trail (1015.57s)
        --- PASS: TestAccCloudTrail_serial/Trail/basic (61.42s)
        --- PASS: TestAccCloudTrail_serial/Trail/cloudwatch (72.68s)
        --- PASS: TestAccCloudTrail_serial/Trail/globalServiceEvents (31.89s)
        --- SKIP: TestAccCloudTrail_serial/Trail/organization (0.19s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelectorDynamoDB (29.08s)
        --- PASS: TestAccCloudTrail_serial/Trail/multiRegion (82.28s)
        --- PASS: TestAccCloudTrail_serial/Trail/tags (82.45s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelector (123.38s)
        --- PASS: TestAccCloudTrail_serial/Trail/logValidation (57.15s)
        --- PASS: TestAccCloudTrail_serial/Trail/advancedEventSelector (34.09s)
        --- PASS: TestAccCloudTrail_serial/Trail/kmsKey (32.56s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelectorExclude (329.89s)
        --- PASS: TestAccCloudTrail_serial/Trail/insightSelector (33.44s)
        --- FAIL: TestAccCloudTrail_serial/Trail/enableLogging (45.05s) --- existing failure in main
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail	1019.229s
```

**Pull request merged**
