### PR TITLE
d/aws_athena_named_query

### PR DESCRIPTION
**Pull request by LukeHendrick**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAthenaNamedQueryDataSource' PKG=athena ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/athena/... -v -count 1 -parallel 1  -run=TestAccAthenaNamedQueryDataSource -timeout 180m
=== RUN   TestAccAthenaNamedQueryDataSource_basic
=== PAUSE TestAccAthenaNamedQueryDataSource_basic
=== CONT  TestAccAthenaNamedQueryDataSource_basic
--- PASS: TestAccAthenaNamedQueryDataSource_basic (35.90s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/athena	38.346s
...
```

AWS API does not provide a way to natively retrieve aws_athena_named_query by name (id only). This data source allows you to do that (and filter by workspace)

### CODE REVIEW

**Comment by LukeHendrick** [comment]
Hi @justinretzolk! Was able to update the docs and fix some formatting issues so now all checks are passing!

**Comment by justinretzolk** [comment]
Hey @LukeHendrick 👋 Thank you very much for your contribution! I'm the community manager for the provider, so I'm mostly taking a quick glance over this until one of our maintainers can take a look at the PR itself (in case you're unfamiliar with how we prioritize, we have a [document that details that](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/prioritization.md)).

One thing I did notice on a quick check that we'll need a [changelog entry](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process) as well. Other than that, this looks to be in good shape for review!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAthenaNamedQuery' PKG=athena ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/athena/... -v -count 1 -parallel 2  -run=TestAccAthenaNamedQuery -timeout 360m
=== RUN   TestAccAthenaNamedQueryDataSource_basic
=== PAUSE TestAccAthenaNamedQueryDataSource_basic
=== RUN   TestAccAthenaNamedQuery_basic
=== PAUSE TestAccAthenaNamedQuery_basic
=== RUN   TestAccAthenaNamedQuery_withWorkGroup
=== PAUSE TestAccAthenaNamedQuery_withWorkGroup
=== CONT  TestAccAthenaNamedQueryDataSource_basic
=== CONT  TestAccAthenaNamedQuery_withWorkGroup
--- PASS: TestAccAthenaNamedQueryDataSource_basic (54.79s)
=== CONT  TestAccAthenaNamedQuery_basic
--- PASS: TestAccAthenaNamedQuery_withWorkGroup (57.49s)
--- PASS: TestAccAthenaNamedQuery_basic (39.33s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/athena	99.976s
```

**Comment by ewbankkit** [comment]
@LukeHendrick Thanks for the contribution :tada: :clap:.

**Pull request merged**
