### PR TITLE
Add enabled attribute for aws_autoscaling_policy

### LINKED ISSUE #12624: Add ability to enable/disable aws_autoscaling_policy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In Feb 2020 AWS added the ability to enable/disable an Autoscaling Policy: https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-ec2-auto-scaling-now-supports-enabling-and-disabling-scaling-policies/

It would be nice to be able to manage this in Terraform.

### New or Affected Resource(s)

* aws_autoscaling_policy

### Potential Terraform Configuration

```hcl
resource "aws_autoscaling_policy" "bat" {
  name                   = "foobar3-terraform-test"
  scaling_adjustment     = 4
  adjustment_type        = "ChangeInCapacity"
  cooldown               = 300
  autoscaling_group_name = "${aws_autoscaling_group.bar.name}"
  enabled                = true
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/02/amazon-ec2-auto-scaling-now-supports-enabling-and-disabling-scaling-policies/
* https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-enable-disable-scaling-policy.html

### PR DESCRIPTION
**Pull request by teraken0509**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12624

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
add `enabled` attribute for aws_autoscaling_policy resource
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAutoscalingPolicy_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAutoscalingPolicy_basic -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAutoscalingPolicy_basic
=== PAUSE TestAccAWSAutoscalingPolicy_basic
=== CONT  TestAccAWSAutoscalingPolicy_basic
--- PASS: TestAccAWSAutoscalingPolicy_basic (125.83s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	127.125s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.497s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.403s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	0.410s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	0.508s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	0.405s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	0.726s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	0.414s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	0.302s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr	0.544s [no tests to run]
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAutoScalingPolicy_' PKG=autoscaling ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 2  -run=TestAccAutoScalingPolicy_ -timeout 180m
=== RUN   TestAccAutoScalingPolicy_basic
=== PAUSE TestAccAutoScalingPolicy_basic
=== RUN   TestAccAutoScalingPolicy_disappears
=== PAUSE TestAccAutoScalingPolicy_disappears
=== RUN   TestAccAutoScalingPolicy_predictiveScalingPredefined
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingPredefined
=== RUN   TestAccAutoScalingPolicy_predictiveScalingCustom
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingCustom
=== RUN   TestAccAutoScalingPolicy_predictiveScalingRemoved
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingRemoved
=== RUN   TestAccAutoScalingPolicy_predictiveScalingUpdated
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingUpdated
=== RUN   TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== PAUSE TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== RUN   TestAccAutoScalingPolicy_TargetTrack_predefined
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_predefined
=== RUN   TestAccAutoScalingPolicy_TargetTrack_custom
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_custom
=== RUN   TestAccAutoScalingPolicy_zeroValue
=== PAUSE TestAccAutoScalingPolicy_zeroValue
=== CONT  TestAccAutoScalingPolicy_basic
=== CONT  TestAccAutoScalingPolicy_zeroValue
--- PASS: TestAccAutoScalingPolicy_zeroValue (54.00s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingUpdated
--- PASS: TestAccAutoScalingPolicy_basic (108.44s)
=== CONT  TestAccAutoScalingPolicy_TargetTrack_custom
--- PASS: TestAccAutoScalingPolicy_predictiveScalingUpdated (95.91s)
=== CONT  TestAccAutoScalingPolicy_TargetTrack_predefined
--- PASS: TestAccAutoScalingPolicy_TargetTrack_custom (52.81s)
=== CONT  TestAccAutoScalingPolicy_simpleScalingStepAdjustment
--- PASS: TestAccAutoScalingPolicy_simpleScalingStepAdjustment (49.88s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingCustom
--- PASS: TestAccAutoScalingPolicy_TargetTrack_predefined (64.36s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingRemoved
--- PASS: TestAccAutoScalingPolicy_predictiveScalingCustom (57.42s)
=== CONT  TestAccAutoScalingPolicy_disappears
--- PASS: TestAccAutoScalingPolicy_disappears (51.46s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingPredefined
--- PASS: TestAccAutoScalingPolicy_predictiveScalingRemoved (112.49s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingPredefined (63.79s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	387.593s
```

**Comment by ewbankkit** [comment]
@teraken0509 Thanks for the contribution :tada: :clap:.

**Comment by FlorinAndrei** [comment]
Which release version will get this feature?

@ewbankkit

**Comment by ewbankkit** [comment]
This week's **v4.15.0** release will include the changes.

**Pull request merged**
