### PR TITLE
r/aws_wafv2_web_acl: add support for captcha in rule actions

### LINKED ISSUE #21754: WAFv2: Add support of Captcha into aws_wafv2_web_acl rule action statement
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_wafv2_web_acl

### Potential Terraform Configuration

```hcl
resource "aws_wafv2_web_acl" "example" {
  name        = "managed-rule-example"
  description = "Example of a captcha rule"
  scope       = "CLOUDFRONT"

  default_action {
    allow {}
  }

  rule {
    name     = "rule-1"
    priority = 1

    action {
      captcha {}
    }

    statement {
      rate_based_statement {
        limit              = 10000
        aggregate_key_type = "IP"

        scope_down_statement {
          geo_match_statement {
            country_codes = ["US", "NL"]
          }
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = false
      metric_name                = "friendly-rule-metric-name"
      sampled_requests_enabled   = false
    }
  }

  tags = {
    Tag1 = "Value1"
    Tag2 = "Value2"
  }

  visibility_config {
    cloudwatch_metrics_enabled = false
    metric_name                = "friendly-metric-name"
    sampled_requests_enabled   = false
  }
}
```

### References

* [AWS CLI - create-web-acl
](https://docs.aws.amazon.com/en_us/cli/latest/reference/wafv2/create-web-acl.html#:~:text=Captcha%20-%3E%20(structure))
* [AWS CLI - get-web-acl
](https://docs.aws.amazon.com/en_us/cli/latest/reference/wafv2/get-web-acl.html#:~:text=Captcha%20-%3E%20(structure))
* [sdk-for-go](https://docs.aws.amazon.com/sdk-for-go/api/service/wafv2/#CaptchaAction)
* [aws-sdk-php](https://github.com/aws/aws-sdk-php/releases/tag/3.200.2)
* https://aws.amazon.com/about-aws/whats-new/2021/11/aws-waf-captcha-support/

### PR DESCRIPTION
**Pull request by wedneyyuri**
We can now configure rules to run a CAPTCHA check against web requests and, as needed, send a CAPTCHA challenge to the client

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21754

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccWAFV2WebACL_' PKG_NAME=internal/service/wafv2

--- PASS: TestAccWAFV2WebACL_disappears (46.59s)
--- PASS: TestAccWAFV2WebACL_minimal (64.41s)
--- PASS: TestAccWAFV2WebACL_basic (66.79s)
--- PASS: TestAccWAFV2WebACL_Operators_maxNested (87.27s)
--- PASS: TestAccWAFV2WebACL_Update_nameForceNew (95.51s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_basic (104.39s)
--- PASS: TestAccWAFV2WebACL_Custom_response (106.21s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_basic (111.33s)
--- PASS: TestAccWAFV2WebACL_RateBased_forwardedIP (113.00s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_forwardedIP (114.08s)
--- PASS: TestAccWAFV2WebACL_RateBased_basic (120.77s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_basic (125.96s)
--- PASS: TestAccWAFV2WebACL_Update_rule (130.30s)
--- PASS: TestAccWAFV2WebACL_RateBased_maxNested (138.40s)
--- PASS: TestAccWAFV2WebACL_RuleGroupReference_basic (146.37s)
--- PASS: TestAccWAFV2WebACL_Update_ruleProperties (147.75s)
--- PASS: TestAccWAFV2WebACL_Custom_requestHandling (148.60s)
--- PASS: TestAccWAFV2WebACL_tags (182.04s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_forwardedIP (234.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	234.053s
```

### CODE REVIEW

**Comment by nouhab** [comment]
can you tell us when this pull request will be merged please ?

**Comment by flavioelawi** [comment]
Am I missing it or [CaptchaConfig](https://docs.aws.amazon.com/waf/latest/APIReference/API_Rule.html#WAF-Type-Rule-CaptchaConfig) is not included in this PR?

**Comment by jeffery7** [comment]
Is it this?  https://github.com/hashicorp/terraform-provider-aws/blob/8fb13701b5ef7202f79fc3cb2129974b13c5d800/internal/service/wafv2/helper.go#L441 
It sure would be great to be able to configure rate_based_rules to use Captcha using TF.

**Comment by kunalsumblyavenue** [comment]
Any idea when will this get merged ? Thanks

**Comment by nodomain** [comment]
Needing this as well.

**Comment by tolidano** [comment]
does it make sense for this to also support specifying the custom rule based CAPTCHA token lifetime as noted here: https://docs.aws.amazon.com/sdk-for-go/api/service/wafv2/#CaptchaConfig.SetImmunityTimeProperty

This is the same type as used in the WebACL: https://docs.aws.amazon.com/sdk-for-go/api/service/wafv2/#WebACL
But on the Rule: https://docs.aws.amazon.com/sdk-for-go/api/service/wafv2/#WebACL

**Comment by ewbankkit** [comment]
@wedneyyuri Thanks for the contribution :tada: :clap:.

**Pull request merged**
