### PR TITLE
r/spot_instance_request: add import support + refactor tests

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #13826

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_spot_instance_request: add plan time validation for `spot_type`
resource_aws_spot_instance_request: import support
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSpotInstanceRequest_'
--- PASS: TestAccAWSSpotInstanceRequest_basic (128.48s)
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (134.96s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (103.59s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (224.48s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (225.46s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (325.17s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (274.46s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (370.91s)
--- PASS: TestAccAWSSpotInstanceRequest_disappears (52.47s)
--- PASS: TestAccAWSSpotInstanceRequest_vpc (257.92s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Verified acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSSpotInstanceRequest_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSSpotInstanceRequest_ -timeout 120m
=== RUN   TestAccAWSSpotInstanceRequest_basic
=== PAUSE TestAccAWSSpotInstanceRequest_basic
=== RUN   TestAccAWSSpotInstanceRequest_withLaunchGroup
=== PAUSE TestAccAWSSpotInstanceRequest_withLaunchGroup
=== RUN   TestAccAWSSpotInstanceRequest_withBlockDuration
=== PAUSE TestAccAWSSpotInstanceRequest_withBlockDuration
=== RUN   TestAccAWSSpotInstanceRequest_vpc
=== PAUSE TestAccAWSSpotInstanceRequest_vpc
=== RUN   TestAccAWSSpotInstanceRequest_validUntil
=== PAUSE TestAccAWSSpotInstanceRequest_validUntil
=== RUN   TestAccAWSSpotInstanceRequest_withoutSpotPrice
=== PAUSE TestAccAWSSpotInstanceRequest_withoutSpotPrice
=== RUN   TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress
=== PAUSE TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress
=== RUN   TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes
=== PAUSE TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes
=== RUN   TestAccAWSSpotInstanceRequest_getPasswordData
=== PAUSE TestAccAWSSpotInstanceRequest_getPasswordData
=== RUN   TestAccAWSSpotInstanceRequest_disappears
=== PAUSE TestAccAWSSpotInstanceRequest_disappears
=== CONT  TestAccAWSSpotInstanceRequest_basic
=== CONT  TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress
=== CONT  TestAccAWSSpotInstanceRequest_disappears
=== CONT  TestAccAWSSpotInstanceRequest_getPasswordData
=== CONT  TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes
=== CONT  TestAccAWSSpotInstanceRequest_withoutSpotPrice
=== CONT  TestAccAWSSpotInstanceRequest_withBlockDuration
=== CONT  TestAccAWSSpotInstanceRequest_withLaunchGroup
=== CONT  TestAccAWSSpotInstanceRequest_validUntil
=== CONT  TestAccAWSSpotInstanceRequest_vpc
--- PASS: TestAccAWSSpotInstanceRequest_disappears (35.42s)
--- FAIL: TestAccAWSSpotInstanceRequest_vpc (78.65s)
    testing.go:669: Step 0 error: Check failed: Check 4/6 error: Expected exactly 1 network interface, found 0
--- PASS: TestAccAWSSpotInstanceRequest_basic (110.43s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (110.43s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (110.50s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (120.55s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (120.70s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (131.03s)
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (141.50s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (241.43s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	241.463s
FAIL
GNUmakefile:26: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

**Comment by DrFaust92** [comment]
fixed vpc test + rebased

**Comment by DrFaust92** [comment]
changed this up a bit to support import

**Comment by DrFaust92** [comment]
tests are now passing!

```
--- PASS: TestAccAWSSpotInstanceRequest_basic (130.78s)
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (142.07s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (118.47s)
--- PASS: TestAccAWSSpotInstanceRequest_vpc (141.48s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (118.15s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (123.61s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (135.58s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (190.08s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (185.17s)
--- PASS: TestAccAWSSpotInstanceRequest_disappears (317.70s)
--- PASS: TestAccAWSSpotInstanceRequest_tags (173.89s)
```

**Comment by bflad** [comment]
Hey @DrFaust92 👋  We would love to pick this up on Thursday as part of some gardening work. If you could rebase this and add a changelog file that would be awesome. Thank you!

**Comment by DrFaust92** [comment]
rebased

```
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (100.86s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (111.34s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (122.31s)
--- PASS: TestAccAWSSpotInstanceRequest_vpc (123.80s)
--- PASS: TestAccAWSSpotInstanceRequest_InterruptHibernate (128.79s)
--- PASS: TestAccAWSSpotInstanceRequest_InterruptStop (128.99s)
--- PASS: TestAccAWSSpotInstanceRequest_basic (133.63s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (137.37s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (144.44s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (159.34s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (198.25s)
--- PASS: TestAccAWSSpotInstanceRequest_tags (198.60s)
--- PASS: TestAccAWSSpotInstanceRequest_disappears (333.04s)
```

**Review by bflad — APPROVED** [review]
Looks good to me, thank you, @DrFaust92 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSEIPAssociation_spotInstance (324.66s)

--- PASS: TestAccAWSSpotInstanceRequest_basic (343.84s)
--- PASS: TestAccAWSSpotInstanceRequest_disappears (313.80s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (212.62s)
--- PASS: TestAccAWSSpotInstanceRequest_InterruptHibernate (327.43s)
--- PASS: TestAccAWSSpotInstanceRequest_InterruptStop (88.75s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (341.21s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (351.06s)
--- PASS: TestAccAWSSpotInstanceRequest_tags (152.64s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (339.82s)
--- PASS: TestAccAWSSpotInstanceRequest_vpc (341.75s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (333.88s)
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (308.06s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (79.75s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- PASS: TestAccAWSEIPAssociation_spotInstance (139.29s)

--- PASS: TestAccAWSSpotInstanceRequest_basic (127.90s)
--- PASS: TestAccAWSSpotInstanceRequest_disappears (309.16s)
--- PASS: TestAccAWSSpotInstanceRequest_getPasswordData (203.89s)
--- PASS: TestAccAWSSpotInstanceRequest_InterruptHibernate (125.23s)
--- PASS: TestAccAWSSpotInstanceRequest_InterruptStop (105.36s)
--- PASS: TestAccAWSSpotInstanceRequest_NetworkInterfaceAttributes (138.38s)
--- PASS: TestAccAWSSpotInstanceRequest_SubnetAndSGAndPublicIpAddress (140.94s)
--- PASS: TestAccAWSSpotInstanceRequest_tags (186.82s)
--- PASS: TestAccAWSSpotInstanceRequest_validUntil (317.22s)
--- PASS: TestAccAWSSpotInstanceRequest_vpc (120.42s)
--- PASS: TestAccAWSSpotInstanceRequest_withBlockDuration (326.41s)
--- PASS: TestAccAWSSpotInstanceRequest_withLaunchGroup (315.90s)
--- PASS: TestAccAWSSpotInstanceRequest_withoutSpotPrice (100.39s)
```

**Pull request merged**
