### PR TITLE
lambda_permission's imported function_name shouldn't be the function ARN but the function name

### LINKED ISSUE #16445: lambda_permission's imported function_name isn't function name but function ARN.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
$ terraform -v
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.18.0
```

### Affected Resource(s)

* aws_lambda_permission

### Terraform Configuration Files

```hcl
resource "aws_lambda_permission" "test" {
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.0"
    }
  }
}

provider "aws" {
  region = "ap-northeast-1"
}
```

Create a Lambda policy without Terraform.

```
$ aws lambda get-policy --function-name test-pr-16436 | jq .Policy -r | jq .
{
  "Version": "2012-10-17",
  "Id": "default",
  "Statement": [
    {
      "Sid": "AWSEvents_test-pr-16436",
      "Effect": "Allow",
      "Principal": {
        "Service": "events.amazonaws.com"
      },
      "Action": "lambda:InvokeFunction",
      "Resource": "arn:aws:lambda:ap-northeast-1:xxx:function:test-pr-16436",
      "Condition": {
        "ArnLike": {
          "AWS:SourceArn": "arn:aws:events:ap-northeast-1:xxx:rule/test-pr-16436"
        }
      }
    }
  ]
}
```

Import a resource `aws_lambda_permission` and check the state.

```
$ terraform import aws_lambda_permission.test test-pr-16436/AWSEvents_test-pr-16436
$ terraform state show aws_lambda_permission.test
```

### Expected Behavior

`function_name` is the Lambda Function's name.

```
$ tf state show aws_lambda_permission.test
# aws_lambda_permission.test:
resource "aws_lambda_permission" "test" {
    action        = "lambda:InvokeFunction"
    function_name = "test-pr-16436"
    id            = "AWSEvents_test-pr-16436"
    principal     = "events.amazonaws.com"
    source_arn    = "arn:aws:events:ap-northeast-1:xxx:rule/test-pr-16436"
    statement_id  = "AWSEvents_test-pr-16436"
}
```

### Actual Behavior

`function_name` is the Lambda Function's ARN.

```
$ tf state show aws_lambda_permission.test
# aws_lambda_permission.test:
resource "aws_lambda_permission" "test" {
    action        = "lambda:InvokeFunction"
    function_name = "arn:aws:lambda:ap-northeast-1:xxx:function:test-pr-16436"
    id            = "AWSEvents_test-pr-16436"
    principal     = "events.amazonaws.com"
    source_arn    = "arn:aws:events:ap-northeast-1:xxx:rule/test-pr-16436"
    statement_id  = "AWSEvents_test-pr-16436"
}
```

### Steps to Reproduce

1. `terraform import aws_lambda_permission.test test-pr-16436/AWSEvents_test-pr-16436`
1. `terraform state show aws_lambda_permission.test`

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_permission#function_name
  * > function_name - (Required) Name of the Lambda function whose resource policy you are updating

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Close #16445

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
BUG FIXES

resource/aws_lambda_permission: Fix imported Lambda Function name
```

Output from acceptance testing:

```console
$ make testacc PKG_NAME=internal/service/lambda TESTARGS='-run=TestLambdaPermission'   
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run=TestLambdaPermission -timeout 180m
=== RUN   TestLambdaPermissionUnmarshalling
--- PASS: TestLambdaPermissionUnmarshalling (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_alias
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_alias (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_govcloud
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_govcloud (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_version
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_version (0.00s)
=== RUN   TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_invalid
--- PASS: TestLambdaPermissionGetQualifierFromLambdaAliasOrVersionArn_invalid (0.00s)
=== RUN   TestLambdaPermissionGetFunctionNameFromLambdaArn_invalid
--- PASS: TestLambdaPermissionGetFunctionNameFromLambdaArn_invalid (0.00s)
=== RUN   TestLambdaPermissionGetFunctionNameFromLambdaArn_valid
--- PASS: TestLambdaPermissionGetFunctionNameFromLambdaArn_valid (0.00s)
=== RUN   TestLambdaPermissionGetFunctionNameFromGovCloudLambdaArn
--- PASS: TestLambdaPermissionGetFunctionNameFromGovCloudLambdaArn (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	1.629s
```

```console
$ make testacc PKG_NAME=internal/service/lambda TESTARGS='-run=TestAccLambdaPermission'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run=TestAccLambdaPermission -timeout 180m
=== RUN   TestAccLambdaPermission_basic
=== PAUSE TestAccLambdaPermission_basic
=== RUN   TestAccLambdaPermission_StatementID_duplicate
=== PAUSE TestAccLambdaPermission_StatementID_duplicate
=== RUN   TestAccLambdaPermission_withRawFunctionName
=== PAUSE TestAccLambdaPermission_withRawFunctionName
=== RUN   TestAccLambdaPermission_withStatementIdPrefix
=== PAUSE TestAccLambdaPermission_withStatementIdPrefix
=== RUN   TestAccLambdaPermission_withQualifier
=== PAUSE TestAccLambdaPermission_withQualifier
=== RUN   TestAccLambdaPermission_disappears
=== PAUSE TestAccLambdaPermission_disappears
=== RUN   TestAccLambdaPermission_multiplePerms
=== PAUSE TestAccLambdaPermission_multiplePerms
=== RUN   TestAccLambdaPermission_withS3
=== PAUSE TestAccLambdaPermission_withS3
=== RUN   TestAccLambdaPermission_withSNS
=== PAUSE TestAccLambdaPermission_withSNS
=== RUN   TestAccLambdaPermission_withIAMRole
=== PAUSE TestAccLambdaPermission_withIAMRole
=== CONT  TestAccLambdaPermission_basic
=== CONT  TestAccLambdaPermission_disappears
=== CONT  TestAccLambdaPermission_multiplePerms
=== CONT  TestAccLambdaPermission_withQualifier
=== CONT  TestAccLambdaPermission_withSNS
=== CONT  TestAccLambdaPermission_withIAMRole
=== CONT  TestAccLambdaPermission_withS3
=== CONT  TestAccLambdaPermission_withRawFunctionName
=== CONT  TestAccLambdaPermission_withStatementIdPrefix
=== CONT  TestAccLambdaPermission_StatementID_duplicate
--- PASS: TestAccLambdaPermission_basic (135.95s)
--- PASS: TestAccLambdaPermission_withIAMRole (146.25s)
--- PASS: TestAccLambdaPermission_withQualifier (166.24s)
--- PASS: TestAccLambdaPermission_StatementID_duplicate (171.17s)
--- PASS: TestAccLambdaPermission_withS3 (173.61s)
--- PASS: TestAccLambdaPermission_withRawFunctionName (178.74s)
--- PASS: TestAccLambdaPermission_withStatementIdPrefix (189.55s)
--- PASS: TestAccLambdaPermission_disappears (224.61s)
--- PASS: TestAccLambdaPermission_multiplePerms (235.91s)
--- PASS: TestAccLambdaPermission_withSNS (247.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	249.129s
```

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
I rebased and run the acceptance test.

```console
$ make testacc TESTARGS='-run=TestAccAWSLambdaPermission'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaPermission -timeout 180m
=== RUN   TestAccAWSLambdaPermission_basic
=== PAUSE TestAccAWSLambdaPermission_basic
=== RUN   TestAccAWSLambdaPermission_StatementId_Duplicate
=== PAUSE TestAccAWSLambdaPermission_StatementId_Duplicate
=== RUN   TestAccAWSLambdaPermission_withRawFunctionName
=== PAUSE TestAccAWSLambdaPermission_withRawFunctionName
=== RUN   TestAccAWSLambdaPermission_withStatementIdPrefix
=== PAUSE TestAccAWSLambdaPermission_withStatementIdPrefix
=== RUN   TestAccAWSLambdaPermission_withQualifier
=== PAUSE TestAccAWSLambdaPermission_withQualifier
=== RUN   TestAccAWSLambdaPermission_disappears
=== PAUSE TestAccAWSLambdaPermission_disappears
=== RUN   TestAccAWSLambdaPermission_multiplePerms
=== PAUSE TestAccAWSLambdaPermission_multiplePerms
=== RUN   TestAccAWSLambdaPermission_withS3
=== PAUSE TestAccAWSLambdaPermission_withS3
=== RUN   TestAccAWSLambdaPermission_withSNS
=== PAUSE TestAccAWSLambdaPermission_withSNS
=== RUN   TestAccAWSLambdaPermission_withIAMRole
=== PAUSE TestAccAWSLambdaPermission_withIAMRole
=== CONT  TestAccAWSLambdaPermission_basic
=== CONT  TestAccAWSLambdaPermission_withStatementIdPrefix
=== CONT  TestAccAWSLambdaPermission_withIAMRole
=== CONT  TestAccAWSLambdaPermission_withSNS
=== CONT  TestAccAWSLambdaPermission_withS3
=== CONT  TestAccAWSLambdaPermission_disappears
=== CONT  TestAccAWSLambdaPermission_withQualifier
=== CONT  TestAccAWSLambdaPermission_multiplePerms
=== CONT  TestAccAWSLambdaPermission_withRawFunctionName
=== CONT  TestAccAWSLambdaPermission_StatementId_Duplicate
--- PASS: TestAccAWSLambdaPermission_withStatementIdPrefix (134.81s)
--- PASS: TestAccAWSLambdaPermission_withQualifier (155.18s)
--- PASS: TestAccAWSLambdaPermission_basic (161.26s)
--- PASS: TestAccAWSLambdaPermission_withS3 (166.53s)
--- PASS: TestAccAWSLambdaPermission_withIAMRole (174.11s)
--- PASS: TestAccAWSLambdaPermission_withRawFunctionName (182.19s)
--- PASS: TestAccAWSLambdaPermission_StatementId_Duplicate (190.01s)
--- PASS: TestAccAWSLambdaPermission_withSNS (207.19s)
--- PASS: TestAccAWSLambdaPermission_multiplePerms (219.48s)
--- PASS: TestAccAWSLambdaPermission_disappears (226.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	228.075s
```

**Comment by suzuki-shunsuke** [comment]
I'm looking forward to your review!
Thanks.

**Comment by jpeeler** [comment]
This looks pretty similar to https://github.com/hashicorp/terraform-provider-aws/pull/12876. I know it's been almost an entire year, but if you're around @suzuki-shunsuke maybe you can rebase again?

**Comment by suzuki-shunsuke** [comment]
@jpeeler Solved the conflict.

**Comment by jpeeler** [comment]
Thanks, @suzuki-shunsuke. I was hoping @bflad might jump in on reviewing, but status says he's busy. @ewbankkit could you get this in?

**Comment by lukej7** [comment]
Is there a workaround for this at the moment? :/ Pretty please

**Pull request merged**
