### PR TITLE
bugfix: Lake Formation permissions/permissions_with_grant_option type

### LINKED ISSUE #31096: [Bug]: Lake Formation Resource Permission parameters need to be Lexical order
### Terraform Core Version

1.3.6

### AWS Provider Version

4.64.0

### Affected Resource(s)

* aws_lakeformation_permissions

### Expected Behavior

The following code block should not lead to deletion/creation of resources if unchanged.
```terraform
resource "aws_lakeformation_permissions" "lf_read" {
    permissions = ["SELECT", "DESCRIBE"]
    for_each = data.aws_iam_role.some_roles
    principal = each.value.arn
    table {
        database_name = var.glue_database
        wildcard = true
    }
}
```

### Actual Behavior

The above code block leads to deletion and creation of the lake formation permission on multiple runs due to internal/implicit reordering in the provider to lexical order.
image

Changing the source in Terraform for permissions to be lexical order stops this unexpected behaviour.

```terraform
resource "aws_lakeformation_permissions" "lf_read" {
    permissions = ["DESCRIBE", "SELECT"]
    for_each = data.aws_iam_role.some_roles
    principal = each.value.arn
    table {
        database_name = var.glue_database
        wildcard = true
    }
}
```

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

The documentation hints towards implicit lexical ordering. This helped with troubleshooting this issue. Happy to document this in the provider explicitly.

> Valid values may include ALL, ALTER, ASSOCIATE, CREATE_DATABASE, CREATE_TABLE, DATA_LOCATION_ACCESS, DELETE, DESCRIBE, DROP, INSERT, and SELECT

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lakeformation_permissions

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by diofeher**
When Lake Formation permissions are set without alphabetical order, every time a new Terraform apply is made, these resources are recreated. This can revoke permissions for long-running Glue jobs, causing significant production problems.

To resolve this issue, instead of using a list of strings, a set should be used.

Description:

### Description

**IMPORTANT**: I've modified the existing test:
**TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus**
changing the order of the permissions arguments because it wasn't needed to add a new test

To reproduce this error, you need to create an AWS Lake Formation permission with the following code:

```
data "aws_partition" "current" {}

resource "aws_iam_role" "test" {
  name = "test"
  path = "/"

  assume_role_policy = jsonencode({
    Statement = [{
      Action = "sts:AssumeRole"
      Effect = "Allow"
      Principal = {
        Service = "glue.${data.aws_partition.current.dns_suffix}"
      }
    }]
    Version = "2012-10-17"
  })
}

resource "aws_glue_catalog_database" "test" {
  name = "test"
}

resource "aws_glue_catalog_table" "test" {
  name          = "test"
  database_name = aws_glue_catalog_database.test.name

  storage_descriptor {
    columns {
      name = "event"
      type = "string"
    }

    columns {
      name = "timestamp"
      type = "date"
    }

    columns {
      name = "value"
      type = "double"
    }
  }
}

data "aws_caller_identity" "current" {}

data "aws_iam_session_context" "current" {
  arn = data.aws_caller_identity.current.arn
}

resource "aws_lakeformation_data_lake_settings" "test" {
  admins = [data.aws_iam_session_context.current.issuer_arn]
}

resource "aws_lakeformation_permissions" "test" {
  permissions = ["SELECT", "ALTER", "DELETE", "DESCRIBE", "DROP", "INSERT", "ALL"]
  principal   = aws_iam_role.test.arn

  table_with_columns {
    database_name = aws_glue_catalog_table.test.database_name
    name          = aws_glue_catalog_table.test.name
    wildcard      = true
  }

  # for consistency, ensure that admins are setup before testing
  depends_on = [aws_lakeformation_data_lake_settings.test]
}
```

The critical issue lies in the order of permissions. If "SELECT" is not the first member, it may conflict when permissions are returned from the provider, potentially causing the resource to be replaced when applying the new configuration.

### Relations

Relates to #33023
Closes #31096 and #22570

### Output from Acceptance Testing

Before:

```console
make testacc TESTS=TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus PKG=lakeformation
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/lakeformation/... -v -count 1 -parallel 20 -run='TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus'  -timeout 360m
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus
    permissions_test.go:793: Step 1/1 error: After applying this test step, the non-refresh plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
        -/+ destroy and then create replacement

        Terraform will perform the following actions:

          # aws_lakeformation_permissions.test must be replaced
        -/+ resource "aws_lakeformation_permissions" "test" {
              ~ id                            = "2278287602" -> (known after apply)
              ~ permissions                   = [ # forces replacement
                  - "ALL",
                  + "SELECT",
                    "ALTER",
                    # (3 unchanged elements hidden)
                    "INSERT",
                  - "SELECT",
                  + "ALL",
                ]
              ~ permissions_with_grant_option = [] -> (known after apply)
                # (2 unchanged attributes hidden)

              ~ table_with_columns {
                  ~ catalog_id    = "705532038218" -> (known after apply)
                    name          = "tf-acc-test-3155428143271683347"
                    # (2 unchanged attributes hidden)
                }
            }

        Plan: 1 to add, 0 to change, 1 to destroy.
--- FAIL: TestAccLakeFormation_serial (104.61s)
    --- FAIL: TestAccLakeFormation_serial/PermissionsTableWithColumns (104.61s)
        --- FAIL: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus (104.61s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation108.955s
FAIL
```

After:

```console
% make testacc TESTS=TestAccLakeFormation_serial PKG=lakeformation
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/lakeformation/... -v -count 1 -parallel 20 -run='TestAccLakeFormation_serial'  -timeout 360m
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/DataLakeSettings
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/basic
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/disappears
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/withoutCatalogId
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/readOnlyAdmins
=== RUN   TestAccLakeFormation_serial/DataCellsFilter
=== RUN   TestAccLakeFormation_serial/DataCellsFilter/rowFilter
=== RUN   TestAccLakeFormation_serial/DataCellsFilter/basic
=== RUN   TestAccLakeFormation_serial/DataCellsFilter/columnWildcard
=== RUN   TestAccLakeFormation_serial/DataCellsFilter/disappears
=== RUN   TestAccLakeFormation_serial/DataLakeSettingsDataSource
=== RUN   TestAccLakeFormation_serial/DataLakeSettingsDataSource/basic
=== RUN   TestAccLakeFormation_serial/DataLakeSettingsDataSource/readOnlyAdmins
=== RUN   TestAccLakeFormation_serial/ResourceLFTag
=== RUN   TestAccLakeFormation_serial/ResourceLFTag/table
=== RUN   TestAccLakeFormation_serial/ResourceLFTag/tableWithColumns
=== RUN   TestAccLakeFormation_serial/ResourceLFTag/basic
=== RUN   TestAccLakeFormation_serial/ResourceLFTag/disappears
=== RUN   TestAccLakeFormation_serial/ResourceLFTags
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/database
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/databaseMultipleTags
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/disappears
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/hierarchy
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/table
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/tableWithColumns
=== RUN   TestAccLakeFormation_serial/ResourceLFTags/basic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/basic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/disappears
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTag
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/dataCellsFilter
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicyMultiple
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/database
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/table
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/basic
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/database
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTag
=== RUN   TestAccLakeFormation_serial/PermissionsTable
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTable/basic
=== RUN   TestAccLakeFormation_serial/PermissionsTable/multipleRoles
=== RUN   TestAccLakeFormation_serial/PermissionsTable/selectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTable/selectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTable/iamAllowed
=== RUN   TestAccLakeFormation_serial/PermissionsTable/implicit
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/basic
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus
=== RUN   TestAccLakeFormation_serial/LFTags
=== RUN   TestAccLakeFormation_serial/LFTags/tagKeyComplex
=== RUN   TestAccLakeFormation_serial/LFTags/values
=== RUN   TestAccLakeFormation_serial/LFTags/valuesOverFifty
=== RUN   TestAccLakeFormation_serial/LFTags/basic
=== RUN   TestAccLakeFormation_serial/LFTags/disappears
--- PASS: TestAccLakeFormation_serial (7240.73s)
    --- PASS: TestAccLakeFormation_serial/DataLakeSettings (264.16s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/basic (74.82s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/disappears (76.69s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/withoutCatalogId (52.83s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/readOnlyAdmins (59.81s)
    --- PASS: TestAccLakeFormation_serial/DataCellsFilter (540.33s)
        --- PASS: TestAccLakeFormation_serial/DataCellsFilter/rowFilter (188.40s)
        --- PASS: TestAccLakeFormation_serial/DataCellsFilter/basic (120.02s)
        --- PASS: TestAccLakeFormation_serial/DataCellsFilter/columnWildcard (113.63s)
        --- PASS: TestAccLakeFormation_serial/DataCellsFilter/disappears (118.28s)
    --- PASS: TestAccLakeFormation_serial/DataLakeSettingsDataSource (147.07s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettingsDataSource/basic (73.25s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettingsDataSource/readOnlyAdmins (73.82s)
    --- PASS: TestAccLakeFormation_serial/ResourceLFTag (426.95s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTag/table (109.88s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTag/tableWithColumns (110.39s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTag/basic (101.09s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTag/disappears (105.59s)
    --- PASS: TestAccLakeFormation_serial/ResourceLFTags (1197.02s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/database (161.35s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/databaseMultipleTags (184.32s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/disappears (106.39s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/hierarchy (244.67s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/table (186.81s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/tableWithColumns (211.36s)
        --- PASS: TestAccLakeFormation_serial/ResourceLFTags/basic (102.11s)
    --- PASS: TestAccLakeFormation_serial/PermissionsBasic (1234.98s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/basic (87.77s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/disappears (177.58s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTag (109.32s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataCellsFilter (156.93s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataLocation (111.31s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy (111.25s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicyMultiple (141.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/database (100.00s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed (119.13s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple (120.66s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (1120.94s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (141.83s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (146.15s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (140.22s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (106.29s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter (196.25s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (127.34s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (128.38s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (134.48s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTable (1042.60s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect (101.73s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly (107.02s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus (108.67s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/basic (114.05s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/multipleRoles (132.32s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectOnly (113.97s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectPlus (115.26s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/iamAllowed (121.88s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/implicit (127.69s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns (801.39s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/basic (332.61s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit (125.43s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns (114.26s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly (115.10s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus (113.99s)
    --- PASS: TestAccLakeFormation_serial/LFTags (465.29s)
        --- PASS: TestAccLakeFormation_serial/LFTags/tagKeyComplex (63.42s)
        --- PASS: TestAccLakeFormation_serial/LFTags/values (112.83s)
        --- PASS: TestAccLakeFormation_serial/LFTags/valuesOverFifty (151.70s)
        --- PASS: TestAccLakeFormation_serial/LFTags/basic (70.57s)
        --- PASS: TestAccLakeFormation_serial/LFTags/disappears (66.75s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation7244.980s
...
```

### CODE REVIEW

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS="-run=TestAccLakeFormation_serial/PermissionsBasic/\|TestAccLakeFormation_serial/PermissionsTableWithColumns/" PKG=lakeformation

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/PermissionsBasic/\|TestAccLakeFormation_serial/PermissionsTableWithColumns/ -timeout 360m
2024/12/12 16:04:41 Initializing Terraform AWS Provider...
--- PASS: TestAccLakeFormation_serial (435.92s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns (131.88s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns (23.02s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly (22.00s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus (18.57s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/basic (47.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit (21.26s)
    --- PASS: TestAccLakeFormation_serial/PermissionsBasic (304.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/basic (23.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/database (21.22s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple (21.24s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataLocation (23.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy (20.53s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed (43.52s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataCellsFilter (23.68s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/disappears (84.38s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTag (21.53s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicyMultiple (21.87s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	442.222s
```

```console
% make testacc TESTARGS="-run=TestAccLakeFormation_serial/PermissionsDataSource/" PKG=lakeformation

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/PermissionsDataSource/ -timeout 360m
2024/12/12 16:26:23 Initializing Terraform AWS Provider...
--- PASS: TestAccLakeFormation_serial (184.87s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (184.87s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter (25.04s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (22.44s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (25.17s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (22.00s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (21.33s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (23.59s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (23.34s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (21.96s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	191.289s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLakeFormation_serial/^PermissionsDataSource$$' PKG=lakeformation
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/lakeformation/... -v -count 1 -parallel 20  -run=TestAccLakeFormation_serial/^PermissionsDataSource$ -timeout 360m
2024/12/13 09:03:43 Initializing Terraform AWS Provider...
=== RUN   TestAccLakeFormation_serial
=== PAUSE TestAccLakeFormation_serial
=== CONT  TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/table
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/basic
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/database
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTag
--- PASS: TestAccLakeFormation_serial (170.89s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (170.89s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (21.85s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (19.90s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (22.76s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (20.04s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataCellsFilter (23.97s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (21.70s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (20.16s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (20.50s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	176.378s
```

**Comment by johnsonaj** [comment]
@diofeher thank you for the contribution! 🎉

**Comment by diofeher** [comment]
Nice to see this one being merged :) Thanks @johnsonaj and @ewbankkit

**Pull request merged**
