### PR TITLE
tls_version_and_cipher_suite and xff_client_port

### LINKED ISSUE #21666: Add tls_version_and_cipher_suite to ALB
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add tls_version_and_cipher_suite to the ALB

### New or Affected Resource(s)

* aws_lb

### Potential Terraform Configuration

```hcl
resource "aws_lb" "test" {
  name               = "test-lb-tf"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.lb_sg.id]
  subnets            = aws_subnet.public.*.id

  enable_deletion_protection = true

  tls_version_and_cipher_suite = true

  access_logs {
    bucket  = aws_s3_bucket.lb_logs.bucket
    prefix  = "test-lb"
    enabled = true
  }

  tags = {
    Environment = "production"
  }
}```

### References

### PR DESCRIPTION
**Pull request by ericrichtert**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21666

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateTLSVersionAndCipherSuite' PKG_NAME=internal/service/elbv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run=TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateTLSVersionAndCipherSuite -timeout 180m
=== RUN   TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateTLSVersionAndCipherSuite
=== PAUSE TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateTLSVersionAndCipherSuite
=== CONT  TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateTLSVersionAndCipherSuite
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateTLSVersionAndCipherSuite (421.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	426.130s
...
```

### CODE REVIEW

**Comment by ericrichtert** [comment]
I fixed a mergeconflict and add xff_client_port for #22049

Closes #22049

**Comment by ericrichtert** [comment]
$ make testacc TESTARGS='-run=TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateXFFClientPort' PKG_NAME=internal/service/elbv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 20 -run=TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateXFFClientPort -timeout 180m
=== RUN   TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateXFFClientPort
=== PAUSE TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateXFFClientPort
=== CONT  TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateXFFClientPort
--- PASS: TestAccELBV2LoadBalancer_ApplicationLoadBalancer_updateXFFClientPort (334.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	337.138s

**Comment by MatteoPierro** [comment]
Why is this still not merged? It's a useful feature, I needed it recently and I had to enable the option manually for a several ALBs 😢

**Comment by ericrichtert** [comment]
> Why is this still not merged? It's a useful feature, I needed it recently and I had to enable the option manually for a several ALBs 😢

I don't know. There seems to be no attention from the maintainers for this request. I can solve the mergeconflicts, but as long as this isn't being planned to merge, I won't do that.

**Pull request closed without merging**
