### PR TITLE
Add eventual consistency protection to efs_file_system_policy

### LINKED ISSUE #21716: aws_efs_file_system_policy Resource Eventual Consistency Bug
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Latest

### Affected Resource(s)

* aws_efs_file_system_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
data "aws_iam_policy_document" "fs-writer-assume" {
  statement {
    effect  = "Allow"
    actions = ["sts:AssumeRole"]
    principals {
      type = "Service"
      identifiers = [
        "ec2.amazonaws.com"
      ]
    }
  }
}

resource "aws_iam_role" "fs-writer" {
  assume_role_policy = data.aws_iam_policy_document.fs-writer-assume.json
  name               = "fs-writer"
}

resource "aws_efs_file_system" "efs" {
  encrypted = true
}

resource "aws_efs_mount_target" "efs-mt" {
  file_system_id  = aws_efs_file_system.efs.id
  subnet_id       = "subnet-xxxxxx"
  security_groups = ["sg-xxxxxx"]
}

data "aws_iam_policy_document" "efs-policy" {
  statement {
    effect = "Allow"
    principals {
      type = "AWS"
      identifiers = [
        aws_iam_role.fs-writer.arn,
      ]
    }
    actions = [
      "elasticfilesystem:ClientMount",
      "elasticfilesystem:ClientRootAccess",
      "elasticfilesystem:ClientWrite",
      "elasticfilesystem:CreateAccessPoint",
      "elasticfilesystem:DeleteAccessPoint",
    ]
    resources = [
      aws_efs_file_system.efs.arn,
    ]
  }
}

resource "aws_efs_file_system_policy" "efs-policy" {
  file_system_id = aws_efs_file_system.efs.id
  policy         = data.aws_iam_policy_document.efs-policy.json
}
```

### Expected Behavior

This should create an IAM role, `fs-writer`, and an EFS FS with a policy that grants `fs-writer` access to it.

### Actual Behavior

This will frequently fail out on the first run with:

```Error: error putting EFS File System Policy (fs-XXXXXX): InvalidPolicyException: Policy contains invalid Principal block.
 {
   RespMetadata: {
     StatusCode: 400,
     RequestID: "3c57405f-87e8-4b15-8a15-95fcd0b0af46"
   },
   ErrorCode: "InvalidPolicyException",
   Message_: "Policy contains invalid Principal block."
 }

   with aws_efs_file_system_policy.efs-policy,
   on foo.tf line xxx, in resource "aws_efs_file_system_policy" "efs-policy":
  xxx: resource "aws_efs_file_system_policy" "efs-policy" {
```

### Steps to Reproduce

1. `terraform apply` on a clean slate, especially in a busy account. A reapply usually succeeds.

### Important Factoids

Most likely, this is eventual consistency between the IAM role being created and then being available to be used in an FS policy. The underlying resource doesn't have any retries around it to guard against eventual consistency bugs:

https://github.com/hashicorp/terraform-provider-aws/blob/ca2cb2838b07e373baa7ca5bbc5d0778509b493d/internal/service/efs/file_system_policy.go#L48-L68

### PR DESCRIPTION
**Pull request by joelthompson**
There was no retry logic around putting an EFS file system policy, which
would lead to errors when the same TF both creates a new IAM principal
(e.g., role) and tries to specify that principal in an EFS FS policy in
the same run. This adds retry logic when AWS returns an error about an
invalid principal in line with standard recommendations.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21716

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccEFSFileSystemPolicy' PKG_NAME=internal/service/efs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run=TestAccEFSFileSystemPolicy -timeout 180m
=== RUN   TestAccEFSFileSystemPolicy_basic
=== PAUSE TestAccEFSFileSystemPolicy_basic
=== RUN   TestAccEFSFileSystemPolicy_disappears
=== PAUSE TestAccEFSFileSystemPolicy_disappears
=== RUN   TestAccEFSFileSystemPolicy_policyBypass
=== PAUSE TestAccEFSFileSystemPolicy_policyBypass
=== CONT  TestAccEFSFileSystemPolicy_basic
=== CONT  TestAccEFSFileSystemPolicy_policyBypass
=== CONT  TestAccEFSFileSystemPolicy_disappears
--- PASS: TestAccEFSFileSystemPolicy_disappears (18.16s)
--- PASS: TestAccEFSFileSystemPolicy_basic (26.20s)
--- PASS: TestAccEFSFileSystemPolicy_policyBypass (27.11s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	29.112s
```

### CODE REVIEW

**Comment by jdebbink** [comment]
Please merge this.

**Comment by harshitp1987** [comment]
Please merge This

**Comment by arthurgurov** [comment]
Please merge this - we need it for our project too.

**Comment by phrytsen-gl** [comment]
@hc-github-team-terraform-aws  Please, review the issue.

**Comment by n3mawashi** [comment]
Please merge this.

**Comment by mandrado** [comment]
I need this too.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEFSFileSystemPolicy_' PKG=efs ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 2  -run=TestAccEFSFileSystemPolicy_ -timeout 180m
=== RUN   TestAccEFSFileSystemPolicy_basic
=== PAUSE TestAccEFSFileSystemPolicy_basic
=== RUN   TestAccEFSFileSystemPolicy_disappears
=== PAUSE TestAccEFSFileSystemPolicy_disappears
=== RUN   TestAccEFSFileSystemPolicy_policyBypass
=== PAUSE TestAccEFSFileSystemPolicy_policyBypass
=== RUN   TestAccEFSFileSystemPolicy_equivalentPolicies
=== PAUSE TestAccEFSFileSystemPolicy_equivalentPolicies
=== RUN   TestAccEFSFileSystemPolicy_equivalentPoliciesIAMPolicyDoc
=== PAUSE TestAccEFSFileSystemPolicy_equivalentPoliciesIAMPolicyDoc
=== CONT  TestAccEFSFileSystemPolicy_basic
=== CONT  TestAccEFSFileSystemPolicy_equivalentPolicies
--- PASS: TestAccEFSFileSystemPolicy_equivalentPolicies (69.53s)
=== CONT  TestAccEFSFileSystemPolicy_policyBypass
--- PASS: TestAccEFSFileSystemPolicy_basic (87.85s)
=== CONT  TestAccEFSFileSystemPolicy_equivalentPoliciesIAMPolicyDoc
--- PASS: TestAccEFSFileSystemPolicy_policyBypass (84.45s)
=== CONT  TestAccEFSFileSystemPolicy_disappears
--- PASS: TestAccEFSFileSystemPolicy_equivalentPoliciesIAMPolicyDoc (67.84s)
--- PASS: TestAccEFSFileSystemPolicy_disappears (44.57s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	204.523s
```

**Comment by ewbankkit** [comment]
@joelthompson Thanks for the contribution :tada: :clap:.

**Pull request merged**
