### PR TITLE
r/aws_efs_replication_configuration: support an existing FS as destination

### LINKED ISSUE #34863: [Enhancement]: Support EFS destination filesystem ID for EFS replication configuration
### Description

Brand new from 11/27: https://aws.amazon.com/blogs/aws/replication-failback-and-increased-iops-are-new-for-amazon-efs/

AWS now supports EFS replication to an **existing** EFS, and won't force you to replicate your source EFS into a new EFS. This would save me a bunch 😅 💸 

### Affected Resource(s) and/or Data Source(s)

`aws_efs_replication_configuration`

### Potential Terraform Configuration

```terraform
The `destination` block of `aws_efs_replication_configuration` should support a new `file_system_id` attribute alongside all the attributes it already supports and are inherited from the API structure
```

### References

API reference: https://docs.aws.amazon.com/efs/latest/ug/API_CreateReplicationConfiguration.html

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by yaronya**
### Description

AWS now [supports](https://aws.amazon.com/blogs/aws/replication-failback-and-increased-iops-are-new-for-amazon-efs/) EFS replication to an existing file system, and won't force you to replicate your source FS into a new one.

This PR takes the existing computed `file_system_id` attribute of `aws_efs_replication_configuration` resource and sets it to be also optional and sends it in the [CreateReplicationConfiguration](https://docs.aws.amazon.com/efs/latest/ug/API_CreateReplicationConfiguration.html) API call

### Relations

Closes #34863 

### Output from Acceptance Testing

```console
╰─❯ make testacc TESTS=TestAccEFSReplicationConfiguration_existingDestination PKG=efs

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run='TestAccEFSReplicationConfiguration_existingDestination'  -timeout 360m
=== RUN   TestAccEFSReplicationConfiguration_existingDestination
=== PAUSE TestAccEFSReplicationConfiguration_existingDestination
=== CONT  TestAccEFSReplicationConfiguration_existingDestination
--- PASS: TestAccEFSReplicationConfiguration_existingDestination (1432.67s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/efs        1434.962s

...
```

### CODE REVIEW

**Comment by yaronya** [comment]
Waiting on #35029 to complete tests

**Comment by yaronya** [comment]
Hey @justinretzolk @ewbankkit 
After #35029 was merged, I was able to set up a test that forms a replication between two file systems, but now I encounter an issue where it takes a lot for the replication to finish and become "enabled". 
How should I tackle such issue where an acceptance test might take a very long time?

See logs:
```
─❯ make testacc TESTS=TestAccEFSReplicationConfiguration_existingDestination PKG=efs

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run='TestAccEFSReplicationConfiguration_existingDestination'  -timeout 360m
=== RUN   TestAccEFSReplicationConfiguration_existingDestination
=== PAUSE TestAccEFSReplicationConfiguration_existingDestination
=== CONT  TestAccEFSReplicationConfiguration_existingDestination

    replication_configuration_test.go:142: Step 1/1 error: Error running apply: exit status 1
        
        Error: waiting for EFS Replication Configuration (fs-0e8ac485cdff85d96) create: timeout while waiting for state to become 'ENABLED' (last state: 'ENABLING', timeout: 10m0s)
        
          with aws_efs_replication_configuration.test,
          on terraform_plugin_test.tf line 23, in resource "aws_efs_replication_configuration" "test":
          23: resource "aws_efs_replication_configuration" "test" {
        
```

**Comment by ewbankkit** [comment]
@yaronya If there is a better default timeout value then you can change the value in `internal/service/efs/replication_configuration.go` and just let the acceptance test(s) run.
Otherwise you can add an explicit [`timeouts` block](https://developer.hashicorp.com/terraform/language/resources/syntax#operation-timeouts) to the acceptance test configuration.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEFSMountTarget_disappears' PKG=efs ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 2  -run=TestAccEFSMountTarget_disappears -timeout 360m
=== RUN   TestAccEFSMountTarget_disappears
=== PAUSE TestAccEFSMountTarget_disappears
=== CONT  TestAccEFSMountTarget_disappears
--- PASS: TestAccEFSMountTarget_disappears (123.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	132.496s
```
```console
% make testacc TESTARGS='-run=TestAccEFSReplicationConfiguration_basic\|TestAccEFSReplicationConfiguration_disappears' PKG=efs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20  -run=TestAccEFSReplicationConfiguration_basic\|TestAccEFSReplicationConfiguration_disappears -timeout 360m
=== RUN   TestAccEFSReplicationConfiguration_basic
=== PAUSE TestAccEFSReplicationConfiguration_basic
=== RUN   TestAccEFSReplicationConfiguration_disappears
=== PAUSE TestAccEFSReplicationConfiguration_disappears
=== CONT  TestAccEFSReplicationConfiguration_basic
=== CONT  TestAccEFSReplicationConfiguration_disappears
--- PASS: TestAccEFSReplicationConfiguration_disappears (462.95s)
--- PASS: TestAccEFSReplicationConfiguration_basic (547.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	553.120s
```
```console
% make testacc TESTARGS='-run=TestAccEFSReplicationConfiguration_allAttributes' PKG=efs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20  -run=TestAccEFSReplicationConfiguration_allAttributes -timeout 360m
=== RUN   TestAccEFSReplicationConfiguration_allAttributes
=== PAUSE TestAccEFSReplicationConfiguration_allAttributes
=== CONT  TestAccEFSReplicationConfiguration_allAttributes
--- PASS: TestAccEFSReplicationConfiguration_allAttributes (544.90s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	551.105s
```
```console
% make testacc TESTARGS='-run=TestAccEFSReplicationConfiguration_existingDestination' PKG=efs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20  -run=TestAccEFSReplicationConfiguration_existingDestination -timeout 360m
=== RUN   TestAccEFSReplicationConfiguration_existingDestination
=== PAUSE TestAccEFSReplicationConfiguration_existingDestination
=== CONT  TestAccEFSReplicationConfiguration_existingDestination
--- PASS: TestAccEFSReplicationConfiguration_existingDestination (1437.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	1443.721s
```

**Comment by ewbankkit** [comment]
@yaronya Thanks for the contribution :tada: :clap:.

**Pull request merged**
