### PR TITLE
Serverless app repo

### LINKED ISSUE #3981: Support for AWS Serverless Application Model and Repository
_This issue was originally opened by @obierlaire as hashicorp/terraform#17729. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

AWS offers now a repository of serverless applications. 
Basically, it's a SAM (Serverless Application Model) repository, where anybody can publish or use serverless application templates (similar as Cloudformation templates)

Terraform supports Cloudformation Data sources and Cloudformation Resources, but no SAM Data source/resource.

The API supports publishing SAM to SAR and consuming SAM from SAR (https://docs.aws.amazon.com/serverlessrepo/latest/devguide/resources.html)

### PR DESCRIPTION
**Pull request by gdavison**
Adds AWS Serverless Application Repository applications to the Terraform provider.

Changes proposed in this pull request:

* Adds the resource `aws_serverlessrepository_stack`
    * Can specify the version
* Adds the data source `aws_serverlessrepository_application`
    * I'm not sure this is all that useful

Fixes #3981

Needs:
- [x] tags
- [x] documentation
- ~import functionality~

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=ServerlessRepo'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=ServerlessRepo -timeout 120m
=== RUN   TestAccDataSourceAwsServerlessRepositoryApplication_Basic
--- PASS: TestAccDataSourceAwsServerlessRepositoryApplication_Basic (13.93s)
=== RUN   TestAccDataSourceAwsServerlessRepositoryApplication_Versioned
--- PASS: TestAccDataSourceAwsServerlessRepositoryApplication_Versioned (10.72s)
=== RUN   TestAccAwsServerlessRepositoryStack_basic
--- PASS: TestAccAwsServerlessRepositoryStack_basic (69.76s)
=== RUN   TestAccAwsServerlessRepositoryStack_versioned
--- PASS: TestAccAwsServerlessRepositoryStack_versioned (57.98s)
=== RUN   TestAccAwsServerlessRepositoryStack_tagged
--- PASS: TestAccAwsServerlessRepositoryStack_tagged (60.22s)
=== RUN   TestAccAwsServerlessRepositoryStack_versionUpdate
--- PASS: TestAccAwsServerlessRepositoryStack_versionUpdate (113.40s)
=== RUN   TestAccAwsServerlessRepositoryStack_update
--- PASS: TestAccAwsServerlessRepositoryStack_update (98.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	424.206s
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @gdavison is this still work in progress? Need any help?

**Comment by gdavison** [comment]
Hi @bflad. I'm still working on it slowly. I haven't had a chance to do much work on it recently.

**Comment by gdavison** [comment]
@bflad I've dropped the "[WIP]" :)

**Comment by gdavison** [comment]
I've put the "[WIP]" label back on. It needed import functionality, and that's causing a number of changes under the hood.

**Comment by gdavison** [comment]
I ran an informal survey at https://github.com/terraform-providers/terraform-provider-aws/issues/3981#issuecomment-531583153, and it's 7-0 for releasing now and backfilling `import` later.

So I'm removing the `[WIP]` again, @bflad

**Comment by kitsuneninetails** [comment]
Is this in limbo, or is someone going to push this forward?  It's been almost 3 months since the last update...

**Comment by dmccaffery** [comment]
... can we move this forward, please :)

**Comment by dmccaffery** [comment]
@gdavison ... I'm going to whip out a can of whoop pretty soon 💯 

I am super happy to help get this over the finish line with code, beer, wine, hugs, whatever is required.

**Comment by weslambert** [comment]
This is something I would like as well!  Thanks!

**Comment by chenrui333** [comment]
Any update on this?? Love this to be merged soon :)

**Comment by gdavison** [comment]
Finishing this is needed to complete the acceptance test `TestAccAwsSecretsManagerSecretRotation()` in #9487

**Comment by quixoticotech** [comment]
+1 For this. :)

**Pull request merged**
