### PR TITLE
fix: add missing 'id' values in pool map (#32106)

### LINKED ISSUE #32106: [Bug]: data.aws_vpc_ipam_pools lacks ipam_pool_id and/or id values
### Terraform Core Version

1.3.9

### AWS Provider Version

5.4.0

### Affected Resource(s)

* data.aws_vpc_ipam_pools

### Expected Behavior

Data source should return a full list of all IPAM pools available in the targeted account, containing information of each pool.
The `ipam_pool_id` and/or `id` fields of an individual pool map should be populated with the value retrieved from the AWS API.

### Actual Behavior

The `ipam_pool_id` and/or `id` fields of an individual pool are not populated by the data source:

```
  + ipam_pools = [
      + {
          + address_family                    = "ipv4"
          + allocation_default_netmask_length = 0
          + allocation_max_netmask_length     = 0
          + allocation_min_netmask_length     = 0
          + allocation_resource_tags          = {}
          + arn                               = "arn:aws:ec2::xxxxxxxxx:ipam-pool/ipam-pool-0440f4xxxxxxxxx"
          + auto_import                       = false
          + aws_service                       = ""
          + description                       = "xxxxxxxxx"
          + id                                = ""
          + ipam_pool_id                      = ""
          + ipam_scope_id                     = "ipam-scope-0c1b9exxxxxxxxx"
          + ipam_scope_type                   = "private"
          + locale                            = "None"
          + pool_depth                        = 1
          + publicly_advertisable             = false
          + source_ipam_pool_id               = ""
          + state                             = "create-complete"
          + tags                              = {
              + "Name"       = "regions"
              + "managed_by" = "AFT"
            }
        },
      + {
          + address_family                    = "ipv4"
          + allocation_default_netmask_length = 0
          + allocation_max_netmask_length     = 0
          + allocation_min_netmask_length     = 0
          + allocation_resource_tags          = {}
          + arn                               = "arn:aws:ec2::xxxxxxxxx:ipam-pool/ipam-pool-0938263xxxxxxxxx"
          + auto_import                       = false
          + aws_service                       = ""
          + description                       = "xxxxxxxxx"
          + id                                = ""
          + ipam_pool_id                      = ""
          + ipam_scope_id                     = "ipam-scope-0d6b751xxxxxxxxx"
          + ipam_scope_type                   = "private"
          + locale                            = "None"
          + pool_depth                        = 1
          + publicly_advertisable             = false
          + source_ipam_pool_id               = ""
          + state                             = "create-complete"
          + tags                              = {
              + "Name"       = "intra"
              + "managed_by" = "AFT"
            }
        },
        ...
```

The actual API response however contains all relevant information:

```
2023-06-20T15:33:03.458+0200 [DEBUG] provider.terraform-provider-aws_v5.4.0_x5: HTTP Response Received: http.status_code=200 @caller=github.com/hashicorp/aws-sdk-go-base/v2/awsv1shim/v2@v2.0.0-beta.30/logger.go:144 aws.service=EC2 http.response.body="<?xml version="1.0" encoding="UTF-8"?>
<DescribeIpamPoolsResponse xmlns="http://ec2.amazonaws.com/doc/2016-11-15/">
    <requestId>a402aae5-5f34-4b0b-94ce-75182b57375b</requestId>
    <ipamPoolSet>
        <item>
            <addressFamily>ipv4</addressFamily>
            <autoImport>false</autoImport>
            <description>xxxxxxxxxx</description>
            <ipamArn>arn:aws:ec2::xxxxxxxxxx:ipam/ipam-044f7b68xxxxxxxxxx</ipamArn>
            <ipamPoolArn>arn:aws:ec2::xxxxxxxxxx:ipam-pool/ipam-pool-0440f45xxxxxxxxxx</ipamPoolArn>
            <ipamPoolId>ipam-pool-0440f45136xxxxxxxxxx</ipamPoolId>
            <ipamRegion>eu-central-1</ipamRegion>
            <ipamScopeArn>arn:aws:ec2::xxxxxxxxxx:ipam-scope/ipam-scope-0c1b9e62xxxxxxxxxx</ipamScopeArn>
            <ipamScopeType>private</ipamScopeType>
            <locale>None</locale>
            <ownerId>xxxxxxxxxx</ownerId>
            <poolDepth>1</poolDepth>
            <state>create-complete</state>
            <tagSet>
                <item>
                    <key>managed_by</key>
                    <value>AFT</value>
                </item>
                <item>
                    <key>Name</key>
                    <value>regions</value>
                </item>
            </tagSet>
        </item>
        <item>
            <addressFamily>ipv4</addressFamily>
            <allocationDefaultNetmaskLength>25</allocationDefaultNetmaskLength>
            <allocationMaxNetmaskLength>25</allocationMaxNetmaskLength>
            <allocationMinNetmaskLength>25</allocationMinNetmaskLength>
            <autoImport>false</autoImport>
            <description>xxxxxxxxxx</description>
            <ipamArn>arn:aws:ec2::xxxxxxxxxx:ipam/ipam-044f7bxxxxxxxxxx</ipamArn>
            <ipamPoolArn>arn:aws:ec2::xxxxxxxxxx:ipam-pool/ipam-pool-05e2f5xxxxxxxxxx</ipamPoolArn>
            <ipamPoolId>ipam-pool-05e2f5dxxxxxxxxxx</ipamPoolId>
            <ipamRegion>eu-central-1</ipamRegion>
            <ipamScopeArn>arn:aws:ec2::xxxxxxxxxx:ipam-scope/ipam-scope-0d6b751xxxxxxxxxx</ipamScopeArn>
            <ipamScopeType>private</ipamScopeType>
            <locale>eu-central-1</locale>
            <ownerId>xxxxxxxxxx</ownerId>
            <poolDepth>2</poolDepth>
            <sourceIpamPoolId>ipam-pool-09382634dxxxxxxxxxx</sourceIpamPoolId>
            <state>create-complete</state>
            <tagSet>
                <item>
                    <key>managed_by</key>
                    <value>AFT</value>
                </item>
                <item>
                    <key>Name</key>
                    <value>eu-central-1</value>
                </item>
            </tagSet>
        </item>
        <item>
            <addressFamily>ipv4</addressFamily>
            <allocationDefaultNetmaskLength>22</allocationDefaultNetmaskLength>
            <allocationMaxNetmaskLength>22</allocationMaxNetmaskLength>
            <allocationMinNetmaskLength>22</allocationMinNetmaskLength>
            <autoImport>false</autoImport>
            <description>xxxxxxxxxx</description>
            <ipamArn>arn:aws:ec2::xxxxxxxxxx:ipam/ipam-044f7b681xxxxxxxxxx</ipamArn>
            <ipamPoolArn>arn:aws:ec2::xxxxxxxxxx:ipam-pool/ipam-pool-08f567c03xxxxxxxxxx</ipamPoolArn>
            <ipamPoolId>ipam-pool-08f567c03xxxxxxxxxx</ipamPoolId>
            <ipamRegion>eu-central-1</ipamRegion>
            <ipamScopeArn>arn:aws:ec2::xxxxxxxxxx:ipam-scope/ipam-scope-0c1b9xxxxxxxxxx</ipamScopeArn>
            <ipamScopeType>private</ipamScopeType>
            <locale>eu-central-1</locale>
            <ownerId>xxxxxxxxxx</ownerId>
            <poolDepth>2</poolDepth>
            <sourceIpamPoolId>ipam-pool-0440f4513xxxxxxxxxx</sourceIpamPoolId>
            <state>create-complete</state>
            <tagSet>
                <item>
                    <key>managed_by</key>
                    <value>AFT</value>
                </item>
                <item>
[truncated...]"
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
provider "aws" {
  region = "eu-central-1"
}

data "aws_vpc_ipam_pools" "test" {
  filter {
    name   = "address-family"
    values = ["ipv4"]
  }
}

output "ipam_pools" {
  value = data.aws_vpc_ipam_pools.test.ipam_pools
}
```

### Steps to Reproduce

- Create IPAM pools in the target account
- Query the information via the following data source:
```
data "aws_vpc_ipam_pools" "test" {
  filter {
    name   = "address-family"
    values = ["ipv4"]
  }
}
```
- Output the result using an ouput:
```
output "ipam_pools" {
  value = data.aws_vpc_ipam_pools.test.ipam_pools
}`
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by trc-ikeskin**
### Description

Add missing values for 'id' attribute for IPAM pools returned by the aws_vpc_ipam_pools data source

### Relations

Closes #32106

### Output from Acceptance Testing

```
make testacc TESTS=TestAccIPAMPoolsDataSource PKG=ec2
    
    ==> Checking that code complies with gofmt requirements...
    TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolsDataSource'  -timeout 180m
    === RUN   TestAccIPAMPoolsDataSource_basic
    === PAUSE TestAccIPAMPoolsDataSource_basic
    === RUN   TestAccIPAMPoolsDataSource_empty
    === PAUSE TestAccIPAMPoolsDataSource_empty
    === CONT  TestAccIPAMPoolsDataSource_basic
    === CONT  TestAccIPAMPoolsDataSource_empty
    --- PASS: TestAccIPAMPoolsDataSource_empty (9.80s)
    --- PASS: TestAccIPAMPoolsDataSource_basic (79.66s)
    PASS
    ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        88.286s

...
```

### CODE REVIEW

**Comment by trc-ikeskin** [comment]
Any maintainers available to implement this fix?

**Comment by justinretzolk** [comment]
Hey @trc-ikeskin 👋 Thank you for checking in on this! Unfortunately I can't provide an ETA on when this will be reviewed/merged due to the potential of shifting priorities. We prioritize by count of :+1: reactions and a few other things (more information on our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) if you're interested).

**Review by drewmullen — APPROVED** [review]
1 Small comment in the changelog but not big enough of a deal to block. Note the website docs already contained `id` and not the (now removed) `ipam_pool_id` so no changes required there

Thanks for finding, reporting, and fixing this bug! And thanks for your patience!

```shell
$ make testacc TESTS=TestAccIPAMPoolsDataSource PKG=ec2
=== RUN   TestAccIPAMPoolsDataSource_basic
=== PAUSE TestAccIPAMPoolsDataSource_basic
=== RUN   TestAccIPAMPoolsDataSource_empty
=== PAUSE TestAccIPAMPoolsDataSource_empty
=== CONT  TestAccIPAMPoolsDataSource_basic
=== CONT  TestAccIPAMPoolsDataSource_empty
--- PASS: TestAccIPAMPoolsDataSource_empty (20.09s)
--- PASS: TestAccIPAMPoolsDataSource_basic (151.88s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        154.091s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIPAMPoolsDataSource_basic' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccIPAMPoolsDataSource_basic -timeout 360m
=== RUN   TestAccIPAMPoolsDataSource_basic
=== PAUSE TestAccIPAMPoolsDataSource_basic
=== CONT  TestAccIPAMPoolsDataSource_basic
--- PASS: TestAccIPAMPoolsDataSource_basic (78.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	84.132s
```

**Comment by ewbankkit** [comment]
@trc-ikeskin Thanks for the contribution :tada: :clap:.

**Pull request merged**
