### PR TITLE
Added multi-session support on the `appstream_fleet` resource

### PR DESCRIPTION
**Pull request by DanielRieske**
### Description

This PR adds support for the multi-session capability on AppStream 2.0 fleets.

https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-appstream-2-0-session-fleets-windows-server-os/

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34245

### Output from Acceptance Testing

```console
make testacc TESTS=TestAccAppStreamFleet_multiSession PKG=appstream
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appstream/... -v -count 1 -parallel 20 -run='TestAccAppStreamFleet_multiSession'  -timeout 360m
=== RUN   TestAccAppStreamFleet_multiSession
=== PAUSE TestAccAppStreamFleet_multiSession
=== CONT  TestAccAppStreamFleet_multiSession
--- PASS: TestAccAppStreamFleet_multiSession (913.21s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appstream  915.372s
```

```console
make testacc TESTS=TestAccAppStreamFleet_ PKG=appstream 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appstream/... -v -count 1 -parallel 20 -run='TestAccAppStreamFleet_'  -timeout 360m
=== RUN   TestAccAppStreamFleet_basic
=== PAUSE TestAccAppStreamFleet_basic
=== RUN   TestAccAppStreamFleet_disappears
=== PAUSE TestAccAppStreamFleet_disappears
=== RUN   TestAccAppStreamFleet_completeWithStop
=== PAUSE TestAccAppStreamFleet_completeWithStop
=== RUN   TestAccAppStreamFleet_completeWithoutStop
=== PAUSE TestAccAppStreamFleet_completeWithoutStop
=== RUN   TestAccAppStreamFleet_withTags
=== PAUSE TestAccAppStreamFleet_withTags
=== RUN   TestAccAppStreamFleet_emptyDomainJoin
=== PAUSE TestAccAppStreamFleet_emptyDomainJoin
=== RUN   TestAccAppStreamFleet_multiSession
=== PAUSE TestAccAppStreamFleet_multiSession
=== CONT  TestAccAppStreamFleet_basic
=== CONT  TestAccAppStreamFleet_withTags
=== CONT  TestAccAppStreamFleet_multiSession
=== CONT  TestAccAppStreamFleet_emptyDomainJoin
=== CONT  TestAccAppStreamFleet_completeWithStop
=== CONT  TestAccAppStreamFleet_completeWithoutStop
=== CONT  TestAccAppStreamFleet_disappears
--- PASS: TestAccAppStreamFleet_completeWithoutStop (818.88s)
--- PASS: TestAccAppStreamFleet_emptyDomainJoin (862.81s)
--- PASS: TestAccAppStreamFleet_basic (869.92s)
--- PASS: TestAccAppStreamFleet_multiSession (877.00s)
--- PASS: TestAccAppStreamFleet_disappears (919.82s)
--- PASS: TestAccAppStreamFleet_withTags (931.11s)
--- PASS: TestAccAppStreamFleet_completeWithStop (1805.76s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appstream  1808.076s
```

### CODE REVIEW

**Comment by jackson-theisen** [comment]
@justinretzolk How can we get this prioritized for the next release? Seems to be sitting stagnant for some time now.

**Review by jackson-theisen — APPROVED** [review]

**Review by brianberzins — APPROVED** [review]
I've been using the appstream functionality and this is both desired AND looks good from my perspective!

**Comment by chaithanya1996** [comment]
This is exactly what we need. is there any plan to release this ? Thanks

**Comment by sayfeeahmed** [comment]
Please add this feature. This will greatly reduce my appstream costing.

**Comment by akramhossanbappy** [comment]
Please make this function available. 
This will enable numerous consoles to expire in a single session and drastically reduce the cost.

**Comment by DanielRieske** [comment]
I would recommend anyone who wants this prioritized to upvote the PR (👍) as this is one of the ways the maintainers will prioritize the PR to be reviewed.

All I can do is keep the branch up to date with main to make it as easy to review as possible.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=appstream TESTS=TestAccAppStreamFleet_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/appstream/... -v -count 1 -parallel 20 -run='TestAccAppStreamFleet_'  -timeout 360m

--- PASS: TestAccAppStreamFleet_disappears (815.79s)
--- PASS: TestAccAppStreamFleet_withTags (867.26s)
--- PASS: TestAccAppStreamFleet_completeWithoutStop (929.50s)
--- PASS: TestAccAppStreamFleet_basic (937.94s)
--- PASS: TestAccAppStreamFleet_emptyDomainJoin (1002.42s)
--- PASS: TestAccAppStreamFleet_multiSession (1073.71s)
--- PASS: TestAccAppStreamFleet_completeWithStop (1857.92s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appstream  1863.426s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @DanielRieske! 👍

**Pull request merged**
