### PR TITLE
Smooth output audio_only_timecode_control typo

### LINKED ISSUE #29159: [Bug]: medialive encodersettings
### Terraform Core Version

1.3.7

### AWS Provider Version

4.5.2

### Affected Resource(s)

* aws_medialive_channel

In the schema for ms smooth the key for audioOnlyTimecodeControl is sprcified as audio_only_timecodec_control
https://github.com/hashicorp/terraform-provider-aws/blob/ef7761e5e1421bd5d0601e09f3739b9e0629911a/internal/service/medialive/channel_encoder_settings_schema.go#L1090

and the spelling here is  audio_only_timecode_control
https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/medialive/channel_encoder_settings_schema.go#L3109

So we get the following error
```
Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
aws_security_group.sg: Refreshing state... [id=sg-03500334f2404e471]
aws_medialive_input.input-testa: Refreshing state... [id=8624773]
aws_medialive_input.input-testb: Refreshing state... [id=9597455]
aws_medialive_channel.channel-test: Refreshing state... [id=9736460]
╷
│ Error: setting AWS Elemental MediaLive Channel (9736460): Invalid address to set: []string{"encoder_settings", "0", "output_groups", "0", "output_group_settings", "0", "ms_smooth_group_settings", "0", "audio_only_timecode_control"}
│ 
│   with aws_medialive_channel.channel-test,
│   on cdk.tf.json line 563, in resource.aws_medialive_channel.channel-test:
│  563:       }
│ 
╵
Operation failed: failed running terraform plan (exit 1)
 ```
So we tried just to edit the key in generated terraform and apply to see what happened and get the following error

```
Terraform v1.3.7
on linux_amd64
Initializing plugins and modules...
╷
│ Error: Extraneous JSON object property
│ 
│   on cdk.tf.json line 126, in resource.aws_medialive_channel.channel-test.encoder_settings.output_groups[0].output_group_settings.ms_smooth_group_settings:
│  126:                   "audio_only_timecode_control": "USE_CONFIGURED_CLOCK",
│ 
│ No argument or block type is named "audio_only_timecode_control". Did you
│ mean "audio_only_timecodec_control"?
╵
Operation failed: failed running terraform plan (exit 1)
```
I think there is a spelling misstake in the schema

### Expected Behavior

the fieldname should be audio_only_timecode_control

### Actual Behavior

Since the key is spelled wrong we can not apply any chnages

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

we just downloaded an existing json setup from medialive
````
 const channel_config = JSON.parse(
                readFileSync(`./channel_config/${channel.file}.json`, 'utf-8'),
            )
            let encoderSetting = <MedialiveChannelEncoderSettings>channel_config['encoderSettings']

```
where we have created two of each MedialiveInput, MedialiveChannelDestinations and MedialiveChannelInputAttachments

````
            new MedialiveChannel(this, 'channel', channel.name), {
                name: channel.name,
                channelClass: 'SINGLE_PIPELINE',
                roleArn: `arn:aws:iam::${accountId}:role/MediaLiveAccessRole`,
                destinations: destinations,
                inputAttachments: attachements,
                inputSpecification: {
                    codec: 'AVC',
                    inputResolution: 'HD',
                    maximumBitrate: 'MAX_50_MBPS',
                },
                encoderSettings: encoderSetting,
                maintenance: {
                    maintenanceDay: channel.maintenance.day,
                    maintenanceStartTime: channel.maintenance.time
                }
            })

### Steps to Reproduce

just try to create a medialive channel with the follwoing outputgroup
msSmoothGroupSettings with audioOnlyTimecodecControl set to "USE_CONFIGURED_CLOCK"

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by LasseEmilHildebrandt**
### Description

Fixed typo regarding `audio_only_timecodec_control` -> `audio_only_timecode_control`. 

While testing, I also found that the `event_id` field was denoted as an Integer. 

Running the test without commit `4c192178a5f695e45ae711ab8383648b13ecd84f` yields the following output:

```
make testacc TESTS=TestAccMediaLiveChannel_MsSmooth_outputSettings PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_MsSmooth_outputSettings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_MsSmooth_outputSettings
=== PAUSE TestAccMediaLiveChannel_MsSmooth_outputSettings
=== CONT  TestAccMediaLiveChannel_MsSmooth_outputSettings
panic: encoder_settings.0.output_groups.0.output_group_settings.0.ms_smooth_group_settings.0.event_id: '' expected type 'int', got unconvertible type 'string', value: ''
```

### Relations

Resolves #29159

### References

The documentation also states that the `event_id` field is a string:
https://docs.aws.amazon.com/medialive/latest/apireference/channels.html#channels-model-smoothgroupeventidmode

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccMediaLiveChannel_MsSmooth_outputSettings PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_MsSmooth_outputSettings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_MsSmooth_outputSettings
=== PAUSE TestAccMediaLiveChannel_MsSmooth_outputSettings
=== CONT  TestAccMediaLiveChannel_MsSmooth_outputSettings
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (84.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	86.306s
...
```

### CODE REVIEW

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thanks for the contribution! Overall the PR looks good. Before I run test, can you merge/rebase this PR with main? A few dependencies have been added since this was open.

**Comment by LasseEmilHildebrandt** [comment]
Thanks for the review, @johnsonaj - The PR has been rebased unto master.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTS=TestAccMediaLiveChannel_ PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 180m
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (71.81s)
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (89.50s)
--- PASS: TestAccMediaLiveChannel_m2ts_settings (100.13s)
--- PASS: TestAccMediaLiveChannel_update (127.39s)
--- PASS: TestAccMediaLiveChannel_updateTags (135.02s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (150.57s)
--- PASS: TestAccMediaLiveChannel_basic (154.98s)
--- PASS: TestAccMediaLiveChannel_disappears (162.11s)
--- PASS: TestAccMediaLiveChannel_hls (198.13s)
--- PASS: TestAccMediaLiveChannel_status (317.66s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	320.641s
```

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thank you for the contribution! 🎉

**Pull request merged**
