### PR TITLE
Add `execution_role` to Athena Workgroup

### LINKED ISSUE #28386: [Enhancement]: aws_athena_workgroup support executionRole for PySpark engine
### Description

I'm trying to create a new `aws_athena_workgroup` resource running with the new `PySpark engine version 3`. When trying to create the workgroup, I get the following error:

```│ Error: error creating Athena WorkGroup: InvalidRequestException: executionRole is null or empty
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "fb9f14fa-2197-4b31-8bac-c147b082900c"
│   },
│   AthenaErrorCode: "INVALID_INPUT",
│   Message_: "executionRole is null or empty"
│ }
│
│   with aws_athena_workgroup.athena_spark_wg,
│   on athena.tf line 23, in resource "aws_athena_workgroup" "athena_spark_wg":
│   23: resource "aws_athena_workgroup" "athena_spark_wg" {
```
This appears to me that some of the new properties (at least execution role) that a Spark enabled Athena workgroup is dependent on has not yet been defined for the `aws_athena_workgroup` resource.

Is this enhancement already on the roadmap? If not, is there anything I can do to help move it along?

### Affected Resource(s) and/or Data Source(s)

* aws_athena_workgroup

### Potential Terraform Configuration

```terraform
resource "aws_athena_workgroup" "athena_spark_wg" {
  name        = local.athena_spark_wg_name
  description = "Analytics workgroup with PySpark engine v3"
  role        = aws_iam_role.athena_spark_execution_role.id

  configuration {
    enforce_workgroup_configuration    = false
    publish_cloudwatch_metrics_enabled = true

    engine_version {
      selected_engine_version = "PySpark engine version 3"
    }

    result_configuration {
      output_location = "s3://${aws_s3_bucket.my_bucket.bucket}/logs/athena_spark/"
    }
  }
}
```
```


### References

https://docs.aws.amazon.com/cli/latest/reference/athena/create-work-group.html

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Relations

Closes #28386

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by djleeam** [comment]
@bschaatsbergen , thanks for putting up this pull request. I did some `dev_overrides` testing with the changes in your branch on my AWS account and everything appears to work, afaik.

FYI, I also put up a small PR to your branch to fix the "Acceptance Test Linting / terrafmt" issue above.

https://github.com/bschaatsbergen/terraform-provider-aws/pull/437

**Comment by bschaatsbergen** [comment]
Ah that's nice of you @djleeam, I was on holidays, I'll finalize the PR asap

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAthenaWorkGroup_' PKG=athena ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/athena/... -v -count 1 -parallel 3  -run=TestAccAthenaWorkGroup_ -timeout 180m
=== RUN   TestAccAthenaWorkGroup_basic
=== PAUSE TestAccAthenaWorkGroup_basic
=== RUN   TestAccAthenaWorkGroup_aclConfig
=== PAUSE TestAccAthenaWorkGroup_aclConfig
=== RUN   TestAccAthenaWorkGroup_disappears
=== PAUSE TestAccAthenaWorkGroup_disappears
=== RUN   TestAccAthenaWorkGroup_bytesScannedCutoffPerQuery
=== PAUSE TestAccAthenaWorkGroup_bytesScannedCutoffPerQuery
=== RUN   TestAccAthenaWorkGroup_enforceWorkGroup
=== PAUSE TestAccAthenaWorkGroup_enforceWorkGroup
=== RUN   TestAccAthenaWorkGroup_configurationEngineVersion
=== PAUSE TestAccAthenaWorkGroup_configurationEngineVersion
=== RUN   TestAccAthenaWorkGroup_configurationExecutionRole
=== PAUSE TestAccAthenaWorkGroup_configurationExecutionRole
=== RUN   TestAccAthenaWorkGroup_publishCloudWatchMetricsEnabled
=== PAUSE TestAccAthenaWorkGroup_publishCloudWatchMetricsEnabled
=== RUN   TestAccAthenaWorkGroup_ResultEncryption_sseS3
=== PAUSE TestAccAthenaWorkGroup_ResultEncryption_sseS3
=== RUN   TestAccAthenaWorkGroup_ResultEncryption_kms
=== PAUSE TestAccAthenaWorkGroup_ResultEncryption_kms
=== RUN   TestAccAthenaWorkGroup_Result_outputLocation
=== PAUSE TestAccAthenaWorkGroup_Result_outputLocation
=== RUN   TestAccAthenaWorkGroup_requesterPaysEnabled
=== PAUSE TestAccAthenaWorkGroup_requesterPaysEnabled
=== RUN   TestAccAthenaWorkGroup_ResultOutputLocation_forceDestroy
=== PAUSE TestAccAthenaWorkGroup_ResultOutputLocation_forceDestroy
=== RUN   TestAccAthenaWorkGroup_description
=== PAUSE TestAccAthenaWorkGroup_description
=== RUN   TestAccAthenaWorkGroup_state
=== PAUSE TestAccAthenaWorkGroup_state
=== RUN   TestAccAthenaWorkGroup_forceDestroy
=== PAUSE TestAccAthenaWorkGroup_forceDestroy
=== RUN   TestAccAthenaWorkGroup_tags
=== PAUSE TestAccAthenaWorkGroup_tags
=== CONT  TestAccAthenaWorkGroup_basic
=== CONT  TestAccAthenaWorkGroup_ResultEncryption_kms
=== CONT  TestAccAthenaWorkGroup_description
--- PASS: TestAccAthenaWorkGroup_basic (18.32s)
=== CONT  TestAccAthenaWorkGroup_state
--- PASS: TestAccAthenaWorkGroup_description (29.63s)
=== CONT  TestAccAthenaWorkGroup_tags
--- PASS: TestAccAthenaWorkGroup_ResultEncryption_kms (32.33s)
=== CONT  TestAccAthenaWorkGroup_configurationEngineVersion
--- PASS: TestAccAthenaWorkGroup_state (42.95s)
=== CONT  TestAccAthenaWorkGroup_ResultEncryption_sseS3
--- PASS: TestAccAthenaWorkGroup_tags (47.59s)
=== CONT  TestAccAthenaWorkGroup_publishCloudWatchMetricsEnabled
--- PASS: TestAccAthenaWorkGroup_configurationEngineVersion (50.33s)
=== CONT  TestAccAthenaWorkGroup_configurationExecutionRole
--- PASS: TestAccAthenaWorkGroup_ResultEncryption_sseS3 (23.18s)
=== CONT  TestAccAthenaWorkGroup_requesterPaysEnabled
--- PASS: TestAccAthenaWorkGroup_configurationExecutionRole (27.10s)
=== CONT  TestAccAthenaWorkGroup_ResultOutputLocation_forceDestroy
--- PASS: TestAccAthenaWorkGroup_publishCloudWatchMetricsEnabled (35.28s)
=== CONT  TestAccAthenaWorkGroup_forceDestroy
--- PASS: TestAccAthenaWorkGroup_requesterPaysEnabled (35.00s)
=== CONT  TestAccAthenaWorkGroup_enforceWorkGroup
--- PASS: TestAccAthenaWorkGroup_forceDestroy (32.27s)
=== CONT  TestAccAthenaWorkGroup_bytesScannedCutoffPerQuery
--- PASS: TestAccAthenaWorkGroup_enforceWorkGroup (32.72s)
=== CONT  TestAccAthenaWorkGroup_Result_outputLocation
--- PASS: TestAccAthenaWorkGroup_ResultOutputLocation_forceDestroy (46.77s)
=== CONT  TestAccAthenaWorkGroup_disappears
--- PASS: TestAccAthenaWorkGroup_disappears (14.21s)
=== CONT  TestAccAthenaWorkGroup_aclConfig
--- PASS: TestAccAthenaWorkGroup_bytesScannedCutoffPerQuery (34.41s)
--- PASS: TestAccAthenaWorkGroup_aclConfig (19.91s)
--- PASS: TestAccAthenaWorkGroup_Result_outputLocation (45.91s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/athena	203.188s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Pull request merged**
