### PR TITLE
resource/aws_service_discovery_instance: new implementation

### LINKED ISSUE #8568: Add an aws_service_discovery_instance resource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [AWS Cloud Map API](https://docs.aws.amazon.com/cloud-map/latest/api/API_Operations.html) supports manual (de-)registering of instances to service discovery services. For a service discovery DNS namespace, this is the only way to manually add DNS records to the zone (attempts to edit the zone from Route 53 return an error "can only be managed through servicediscovery.amazonaws.com"). Adding an instance resource will allow managing custom DNS records in service discovery namespaces.

### New or Affected Resource(s)

* aws_service_discovery_instance

### Potential Terraform Configuration

```hcl
resource "aws_vpc" "example" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_service_discovery_private_dns_namespace" "example" {
  name        = "example.terraform.local"
  description = "example"
  vpc         = "${aws_vpc.example.id}"
}

resource "aws_service_discovery_service" "example" {
  name = "example"

  dns_config {
    namespace_id = "${aws_service_discovery_private_dns_namespace.example.id}"

    dns_records {
      ttl  = 10
      type = "A"
    }

    routing_policy = "MULTIVALUE"
  }

  health_check_custom_config {
    failure_threshold = 1
  }
}

resource "aws_service_discovery_instance" "example" {
  service_id = "${aws_service_discovery_service.example.id}"

  # must be unique among instances belonging to this service, specifying an existing one will update it
  instance_id = "example1"

  # an optional attribute for each of the well-defined attributes documented in RegisterInstance
  instance_ipv4 = "1.1.1.1"

  # supports up to 30 custom attributes
  attribute {
    key = "custom"
    value = "manually managed by terraform"
  }
}
```

### References

- <https://docs.aws.amazon.com/cloud-map/latest/api/API_RegisterInstance.html>
- <https://docs.aws.amazon.com/cloud-map/latest/api/API_GetInstance.html>
- <https://docs.aws.amazon.com/cloud-map/latest/api/API_DeregisterInstance.html>

### PR DESCRIPTION
**Pull request by dirk39**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8568

The output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSServiceDiscoveryInstance'

...
```
This is the implementation of the APIs to Register/Deregister instances into the AWS CloudMap service. Link to the doc [here](https://docs.aws.amazon.com/cloud-map/latest/api/Welcome.html)

### CODE REVIEW

**Comment by alexanderj1988** [comment]
exactly what we need , too!!!

**Comment by rupertohpen** [comment]
Any chance this can be merged?

**Comment by JeromeErasmus** [comment]
can we get this merged?

**Comment by denzhel** [comment]
Any chance this will get merged ?

**Comment by barakharyati** [comment]
Hi, any updates about that PR ?

**Comment by rupertohpen** [comment]
any reason not to push the button? Seems like someone has done quite some work to get this far and it would be a shame to let that effort go to waste - plus I could really use this feature that was inexplicably left out in the first place

**Comment by cageyv** [comment]
This resource also helps to solve this problem with AWS App Mesh
"Your application is unable to resolve the DNS name of a virtual service that it is attempting to connect to."
https://docs.aws.amazon.com/app-mesh/latest/userguide/troubleshoot-connectivity.html#ts-connectivity-dns-resolution-virtual-service

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSServiceDiscoveryInstance_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSServiceDiscoveryInstance_ -timeout 180m
=== RUN   TestAccAWSServiceDiscoveryInstance_private
=== PAUSE TestAccAWSServiceDiscoveryInstance_private
=== RUN   TestAccAWSServiceDiscoveryInstance_public
=== PAUSE TestAccAWSServiceDiscoveryInstance_public
=== RUN   TestAccAWSServiceDiscoveryInstance_http
=== PAUSE TestAccAWSServiceDiscoveryInstance_http
=== CONT  TestAccAWSServiceDiscoveryInstance_private
=== CONT  TestAccAWSServiceDiscoveryInstance_http
=== CONT  TestAccAWSServiceDiscoveryInstance_public
--- PASS: TestAccAWSServiceDiscoveryInstance_public (139.99s)
--- PASS: TestAccAWSServiceDiscoveryInstance_private (163.20s)
--- PASS: TestAccAWSServiceDiscoveryInstance_http (163.49s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	166.883s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSServiceDiscoveryInstance_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSServiceDiscoveryInstance_ -timeout 180m
=== RUN   TestAccAWSServiceDiscoveryInstance_private
=== PAUSE TestAccAWSServiceDiscoveryInstance_private
=== RUN   TestAccAWSServiceDiscoveryInstance_public
=== PAUSE TestAccAWSServiceDiscoveryInstance_public
=== RUN   TestAccAWSServiceDiscoveryInstance_http
=== PAUSE TestAccAWSServiceDiscoveryInstance_http
=== CONT  TestAccAWSServiceDiscoveryInstance_private
=== CONT  TestAccAWSServiceDiscoveryInstance_http
=== CONT  TestAccAWSServiceDiscoveryInstance_public
=== CONT  TestAccAWSServiceDiscoveryInstance_private
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryInstance_http
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryInstance_public
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryInstance_public (1.34s)
--- SKIP: TestAccAWSServiceDiscoveryInstance_private (1.34s)
--- SKIP: TestAccAWSServiceDiscoveryInstance_http (1.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.889s
```

**Pull request merged**
