### PR TITLE
f-DeleteUnusedFMManagedResources support for aws_fms_policy resource

### LINKED ISSUE #18037: Tags support for `aws_fms_policy`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add tag support for `aws_fms_policy`

### New or Affected Resource(s)

* aws_fms_policy

### Potential Terraform Configuration

```hcl
resource "aws_fms_policy" "example" {
  tags = {
    Tag1 = "TagValue"
  }
}
```

### LINKED ISSUE #19961: Add aws_fms_policy resource policy tagging functionality
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Link to AWS API Doc https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_TagResource.html#API_TagResource_RequestSyntax
AWS Firewall Manager supports policy tags (separate from resource_tags) directly in the GUI but they aren't represented in the tf resource documentation, and aren't present when the resource is imported after tags are manually assigned. I'd like to request the addition of tagging functionality for the aws_fms_policy resource

### New or Affected Resource(s)

* aws_fms_policy resource

### LINKED ISSUE #21294: Delete unused FMS resources support for aws_fms_policy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Support for the aws_fms_policy resource to be able to use the `DeleteUnusedFMManagedResources` FMS policy property. Currently it is not available and results in the resource always having `DeleteUnusedFMManagedResources` property set to false if created by Terraform. 

### New or Affected Resource(s)

* aws_fms_policy

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "aws_fms_policy" "example" {
  name                        = "FMS-Policy-Example"
  delete_unused_fms_resources = true
  exclude_resource_tags       = false
  remediation_enabled         = false
  resource_type_list          = ["AWS::ElasticLoadBalancingV2::LoadBalancer"]

  security_service_policy_data {
    type = "WAFV2"

    managed_service_data = jsonencode({
      type = "WAFV2",
      ruleGroups = [{
        id = aws_wafregional_rule_group.example.id
        overrideAction = {
          type = "COUNT"
        }
      }]
      defaultAction = {
        type = "BLOCK"
      }
      overrideCustomerWebACLAssociation = false
    })
  }
}

resource "aws_wafregional_rule_group" "example" {
  metric_name = "WAFRuleGroupExample"
  name        = "WAF-Rule-Group-Example"
}
```

### References

* https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_Policy.html
* https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.41.1/service/fms#Policy

### PR DESCRIPTION
**Pull request by CloudCally**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21294.
Closes #18037.
Closes #19961.

Output from acceptance testing:

```
Unable to run tests in current env.

I was able to run a plan/apply on an existing resource after building the provider and it did function as intended.
...
```

### CODE REVIEW

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by CloudCally** [comment]
Hello, @zhelding, is there anything more you need me to do to get this merged?

**Comment by zhelding** [comment]
Hi @CloudCally. No further action is required on your end for merging this pull request.

This pull request will now be addressed via our standard prioritization process. Unfortunately, given the large quantity of issues and pull requests we receive, we are not always able to review every pull request in a timely manner.

We prioritize contributions that provide the greatest value to the largest number of users -- which we primarily infer based on the number of :thumbsup: [reactions](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/).  Additionally, an explanation of the particular use case for a contribution can provide information on how the changes might be useful in a broader context.

You can get a view of the wider development plans for the provider via our [road map](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md), published quarterly.

Thank you again for your contribution and your patience.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccFMS_serial/Policy/basic PKG=fms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fms/... -v -count 1 -parallel 20 -run='TestAccFMS_serial/Policy/basic'  -timeout 180m
=== RUN   TestAccFMS_serial
=== RUN   TestAccFMS_serial/Policy
=== RUN   TestAccFMS_serial/Policy/basic
--- PASS: TestAccFMS_serial (2082.58s)
    --- PASS: TestAccFMS_serial/Policy (2082.58s)
        --- PASS: TestAccFMS_serial/Policy/basic (2082.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fms	2086.071s
% make testacc TESTS=TestAccFMS_serial/Policy/tags PKG=fms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fms/... -v -count 1 -parallel 20 -run='TestAccFMS_serial/Policy/tags'  -timeout 180m
=== RUN   TestAccFMS_serial
=== RUN   TestAccFMS_serial/Policy
=== RUN   TestAccFMS_serial/Policy/tags
--- PASS: TestAccFMS_serial (1191.19s)
    --- PASS: TestAccFMS_serial/Policy (1191.19s)
        --- PASS: TestAccFMS_serial/Policy/tags (1191.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fms	1194.907s
```

**Comment by ewbankkit** [comment]
@CloudCally @Victorp99 Thanks for the contribution :tada: :clap:.

**Pull request merged**
