### PR TITLE
r/aws_ami added `tpm_support` argument to `aws_ami` resource

### LINKED ISSUE #24860: aws_ami support for TPM2.0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS released TPM2.0 ("NitroTPM") support for EC2 a couple of days ago. With this, EC2 instances can store private keys in the TPM2.0 enclave instead of on-disk, which is really neat stuff.

### New or Affected Resource(s)

* aws_ami

### Potential Terraform Configuration

Maybe something like

```hcl
resource "aws_ami" "example" {
  name                = "terraform-example"
  virtualization_type = "hvm"
  root_device_name    = "/dev/xvda"
  boot_mode = "uefi"
  tpm_support = "v2.0"

  ebs_block_device {
    device_name = "/dev/xvda"
    snapshot_id = "snap-xxxxxxxx"
    volume_size = 8
  }
}
```

### References

* Announcement: https://aws.amazon.com/about-aws/whats-new/2022/05/amazon-ec2-nitrotpm-uefi-secure-boot/
* Blog post: https://aws.amazon.com/blogs/aws/amazon-ec2-now-supports-nitrotpm-and-uefi-secure-boot/
* Deep dive blog from December 2021: https://aws.amazon.com/blogs/compute/deep-dive-into-nitrotpm-and-uefi-secure-boot-support-in-amazon-ec2/
* Docs on creating an AMI with TPM2.0 support: https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/enable-nitrotpm-support-on-ami.html

### PR DESCRIPTION
**Pull request by nialdaly**
### Summary
This PR includes changes to the [aws_ami](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ami) resource, to include the `tpm_support` argument. The following AWS SDK resources were used to inform the logic and descriptions for the argument attributes:
- https://github.com/aws/aws-sdk-go/blob/v1.44.21/service/ec2/api.go
- https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/ec2.html

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #24860

Output from acceptance testing:
```
$ make testacc TESTS=TestAccEC2AMI_tpmSupport PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2AMI_tpmSupport'  -timeout 180m
=== RUN   TestAccEC2AMI_tpmSupport
=== PAUSE TestAccEC2AMI_tpmSupport
=== CONT  TestAccEC2AMI_tpmSupport
--- PASS: TestAccEC2AMI_tpmSupport (71.31s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        72.935s

```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2AMI' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2AMI -timeout 180m
=== RUN   TestAccEC2AMICopy_basic
=== PAUSE TestAccEC2AMICopy_basic
=== RUN   TestAccEC2AMICopy_description
=== PAUSE TestAccEC2AMICopy_description
=== RUN   TestAccEC2AMICopy_enaSupport
=== PAUSE TestAccEC2AMICopy_enaSupport
=== RUN   TestAccEC2AMICopy_destinationOutpost
=== PAUSE TestAccEC2AMICopy_destinationOutpost
=== RUN   TestAccEC2AMICopy_tags
=== PAUSE TestAccEC2AMICopy_tags
=== RUN   TestAccEC2AMIDataSource_natInstance
=== PAUSE TestAccEC2AMIDataSource_natInstance
=== RUN   TestAccEC2AMIDataSource_windowsInstance
=== PAUSE TestAccEC2AMIDataSource_windowsInstance
=== RUN   TestAccEC2AMIDataSource_instanceStore
=== PAUSE TestAccEC2AMIDataSource_instanceStore
=== RUN   TestAccEC2AMIDataSource_localNameFilter
=== PAUSE TestAccEC2AMIDataSource_localNameFilter
=== RUN   TestAccEC2AMIDataSource_gp3BlockDevice
=== PAUSE TestAccEC2AMIDataSource_gp3BlockDevice
=== RUN   TestAccEC2AMIFromInstance_basic
=== PAUSE TestAccEC2AMIFromInstance_basic
=== RUN   TestAccEC2AMIFromInstance_tags
=== PAUSE TestAccEC2AMIFromInstance_tags
=== RUN   TestAccEC2AMIFromInstance_disappears
=== PAUSE TestAccEC2AMIFromInstance_disappears
=== RUN   TestAccEC2AMIIDsDataSource_basic
=== PAUSE TestAccEC2AMIIDsDataSource_basic
=== RUN   TestAccEC2AMIIDsDataSource_sorted
=== PAUSE TestAccEC2AMIIDsDataSource_sorted
=== RUN   TestAccEC2AMILaunchPermission_basic
=== PAUSE TestAccEC2AMILaunchPermission_basic
=== RUN   TestAccEC2AMILaunchPermission_disappears
=== PAUSE TestAccEC2AMILaunchPermission_disappears
=== RUN   TestAccEC2AMILaunchPermission_Disappears_ami
=== PAUSE TestAccEC2AMILaunchPermission_Disappears_ami
=== RUN   TestAccEC2AMILaunchPermission_group
=== PAUSE TestAccEC2AMILaunchPermission_group
=== RUN   TestAccEC2AMILaunchPermission_organizationARN
=== PAUSE TestAccEC2AMILaunchPermission_organizationARN
=== RUN   TestAccEC2AMILaunchPermission_organizationalUnitARN
=== PAUSE TestAccEC2AMILaunchPermission_organizationalUnitARN
=== RUN   TestAccEC2AMI_basic
=== PAUSE TestAccEC2AMI_basic
=== RUN   TestAccEC2AMI_deprecateAt
=== PAUSE TestAccEC2AMI_deprecateAt
=== RUN   TestAccEC2AMI_description
=== PAUSE TestAccEC2AMI_description
=== RUN   TestAccEC2AMI_disappears
=== PAUSE TestAccEC2AMI_disappears
=== RUN   TestAccEC2AMI_ephemeralBlockDevices
=== PAUSE TestAccEC2AMI_ephemeralBlockDevices
=== RUN   TestAccEC2AMI_gp3BlockDevice
=== PAUSE TestAccEC2AMI_gp3BlockDevice
=== RUN   TestAccEC2AMI_tags
=== PAUSE TestAccEC2AMI_tags
=== RUN   TestAccEC2AMI_outpost
=== PAUSE TestAccEC2AMI_outpost
=== RUN   TestAccEC2AMI_boot
=== PAUSE TestAccEC2AMI_boot
=== RUN   TestAccEC2AMI_tpmSupport
=== PAUSE TestAccEC2AMI_tpmSupport
=== CONT  TestAccEC2AMICopy_basic
=== CONT  TestAccEC2AMILaunchPermission_disappears
--- PASS: TestAccEC2AMILaunchPermission_disappears (360.32s)
=== CONT  TestAccEC2AMI_tpmSupport
--- PASS: TestAccEC2AMICopy_basic (382.97s)
=== CONT  TestAccEC2AMI_boot
--- PASS: TestAccEC2AMI_tpmSupport (65.89s)
=== CONT  TestAccEC2AMI_outpost
    acctest.go:1308: skipping since no Outposts found
--- SKIP: TestAccEC2AMI_outpost (1.52s)
=== CONT  TestAccEC2AMI_tags
--- PASS: TestAccEC2AMI_boot (67.54s)
=== CONT  TestAccEC2AMI_gp3BlockDevice
--- PASS: TestAccEC2AMI_gp3BlockDevice (66.95s)
=== CONT  TestAccEC2AMI_ephemeralBlockDevices
--- PASS: TestAccEC2AMI_tags (94.91s)
=== CONT  TestAccEC2AMI_disappears
--- PASS: TestAccEC2AMI_ephemeralBlockDevices (66.04s)
=== CONT  TestAccEC2AMI_description
--- PASS: TestAccEC2AMI_disappears (63.57s)
=== CONT  TestAccEC2AMI_deprecateAt
--- PASS: TestAccEC2AMI_deprecateAt (79.77s)
=== CONT  TestAccEC2AMI_basic
--- PASS: TestAccEC2AMI_description (82.71s)
=== CONT  TestAccEC2AMILaunchPermission_organizationalUnitARN
    acctest.go:697: skipping tests; this AWS account must not be an existing member of an AWS Organization
--- SKIP: TestAccEC2AMILaunchPermission_organizationalUnitARN (0.17s)
=== CONT  TestAccEC2AMILaunchPermission_organizationARN
--- PASS: TestAccEC2AMI_basic (67.86s)
=== CONT  TestAccEC2AMILaunchPermission_group
--- PASS: TestAccEC2AMILaunchPermission_organizationARN (371.25s)
=== CONT  TestAccEC2AMILaunchPermission_Disappears_ami
--- PASS: TestAccEC2AMILaunchPermission_group (364.44s)
=== CONT  TestAccEC2AMIFromInstance_disappears
--- PASS: TestAccEC2AMILaunchPermission_Disappears_ami (360.01s)
=== CONT  TestAccEC2AMILaunchPermission_basic
--- PASS: TestAccEC2AMIFromInstance_disappears (334.58s)
=== CONT  TestAccEC2AMIIDsDataSource_sorted
--- PASS: TestAccEC2AMIIDsDataSource_sorted (97.24s)
=== CONT  TestAccEC2AMIIDsDataSource_basic
--- PASS: TestAccEC2AMIIDsDataSource_basic (17.68s)
=== CONT  TestAccEC2AMIFromInstance_basic
--- PASS: TestAccEC2AMILaunchPermission_basic (370.95s)
=== CONT  TestAccEC2AMIFromInstance_tags
--- PASS: TestAccEC2AMIFromInstance_basic (319.53s)
=== CONT  TestAccEC2AMICopy_tags
--- PASS: TestAccEC2AMIFromInstance_tags (369.39s)
=== CONT  TestAccEC2AMIDataSource_instanceStore
--- PASS: TestAccEC2AMIDataSource_instanceStore (38.00s)
=== CONT  TestAccEC2AMIDataSource_windowsInstance
--- PASS: TestAccEC2AMIDataSource_windowsInstance (38.79s)
=== CONT  TestAccEC2AMIDataSource_natInstance
--- PASS: TestAccEC2AMIDataSource_natInstance (38.77s)
=== CONT  TestAccEC2AMICopy_enaSupport
--- PASS: TestAccEC2AMICopy_tags (409.80s)
=== CONT  TestAccEC2AMICopy_destinationOutpost
    acctest.go:1308: skipping since no Outposts found
--- SKIP: TestAccEC2AMICopy_destinationOutpost (0.55s)
=== CONT  TestAccEC2AMIDataSource_gp3BlockDevice
--- PASS: TestAccEC2AMIDataSource_gp3BlockDevice (64.71s)
=== CONT  TestAccEC2AMICopy_description
--- PASS: TestAccEC2AMICopy_enaSupport (383.01s)
=== CONT  TestAccEC2AMIDataSource_localNameFilter
--- PASS: TestAccEC2AMIDataSource_localNameFilter (40.53s)
--- PASS: TestAccEC2AMICopy_description (397.34s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	2743.916s
```

**Comment by ewbankkit** [comment]
@nialdaly Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
```console
% make providerlint && make golangci-lint
==> Checking source code with providerlint...
==> Checking source code with golangci-lint...
```

**Comment by nialdaly** [comment]
Thanks! @ewbankkit

**Pull request merged**
