### PR TITLE
Various data sources: Return empty lists rather than errors when no resources match

### LINKED ISSUE #8302: Feature Request: Allow data sources searching tags/filters to return empty results
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are use-cases for data sources such as `aws_vpcs` or `aws_security_groups` that do not return results based on the tags/filter.  If there are not results, these data sources will error out during the planning stage.  Having a flag that allowed these data sources to return empty lists could expand their usage to search for resources that might not exist yet, but could in future runs.

### New or Affected Resource(s)

* data.aws_vpcs
* data.aws_security_groups
* probably could be expanded to more data sources

### Potential Terraform Configuration

```hcl
data "aws_security_groups" "fake" {
  allow_empty_results = true
  tags = {
    is_fake = "true"
  }
}

data "aws_vpcs" "fake" {
  allow_empty_results = true
  filter {
    name = "vpc-id"
    values = ["vpc-fake"]
  }
}

resource "aws_security_group" "this" {
  name        = "example-fake-sg-rule"
  description = "Allow inbound traffic for ssh"
  vpc_id      = "${var.vpc_id}"

  ingress {
    from_port       = 22
    to_port         = 22
    protocol        = "tcp"
    security_groups = ["${concat(var.ingress_security_groups, data.aws_security_groups.fake.ids)}"]
  }
}
```

### LINKED ISSUE #17540: Allow data resource that lookup sets of items to return empty sets.
### Community Note

* Please vote on this issue by adding a � [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

data resource that exist to generate a list of items should (or should be able to) return an empty list when no resource match the filters used.

### New or Affected Resource(s)

More or less any data resource ending in a plural, a few of many that likely exhibit this issue:  

* `aws_autoscaling_groups`
* `aws_instances`
* `aws_subnet_ids`
* ...

### Potential Terraform Configuration

I need to create a resource for_each of some other thing. Things that exists outside TF's control.

```hcl
data "aws_things" "lookup" {
  ...
}

resource "aws_other_thing" "make" {
  for_each = data.aws_things.lookup.ids

  ...
  build_from_thing = each.key
}
```

(note this is only one of several patterns that run into this problem, but in my experience the most common.)

Right now this works, but only when something is actually found.
When the possibility exist that in, non error condition, there may be zero of those things, making things work is much more complex.
All (or most) data resource that lookup sets of things issue an error when they find nothing.

### Attempted Solutions

The general workaround is to use a wider query that is assured to always return _something_ and lookup enough about each of those results to manually filter that in terraform.
Besides being much more complex and requiring many more data requests, this has many other issues that I shouldn't need to go into.

### References

https://github.com/hashicorp/terraform/issues/27712

### PR DESCRIPTION
**Pull request by jordiprats**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This PR updates the datasource **aws_security_groups** to make it compliant with [terraform's Provider Design guidalines](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/provider-design.md): It returns an empty list when the tags won't match any SG

Closes #8302.
Closes #17540.
Relates #20433.
Relates #22776.

Output from acceptance testing:

```
$ docker run --rm -v "$PWD":/usr/src/myapp -w /usr/src/myapp golang:1.17 make testacc TESTARGS='-run=TestAcc21219'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAcc21219 -timeout 180m
go: downloading github.com/aws/aws-sdk-go v1.40.56
go: downloading github.com/beevik/etree v1.1.0
go: downloading github.com/hashicorp/aws-sdk-go-base v1.0.0
go: downloading github.com/hashicorp/go-cleanhttp v0.5.2
go: downloading github.com/hashicorp/go-cty v1.4.1-0.20200414143053-d3edf31b6320
go: downloading github.com/hashicorp/aws-cloudformation-resource-schema-sdk-go v0.12.0
go: downloading github.com/hashicorp/go-version v1.3.0
go: downloading github.com/gdavison/terraform-plugin-sdk/v2 v2.7.1-0.20210913224932-c7c2dbd9e010
go: downloading github.com/hashicorp/go-multierror v1.1.1
go: downloading github.com/jen20/awspolicyequivalence v1.1.0
go: downloading github.com/mattbaird/jsonpatch v0.0.0-20200820163806-098863c1fc24
go: downloading github.com/mitchellh/copystructure v1.2.0
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading github.com/shopspring/decimal v1.2.0
go: downloading gopkg.in/yaml.v2 v2.4.0
go: downloading github.com/pquerna/otp v1.3.0
go: downloading golang.org/x/crypto v0.0.0-20210421170649-83a5a9bb288b
go: downloading github.com/jmespath/go-jmespath v0.4.0
go: downloading github.com/hashicorp/errwrap v1.0.0
go: downloading github.com/xeipuuv/gojsonschema v1.2.0
go: downloading github.com/mitchellh/mapstructure v1.1.2
go: downloading github.com/mitchellh/reflectwalk v1.0.2
go: downloading golang.org/x/text v0.3.6
go: downloading github.com/mitchellh/go-testing-interface v1.14.1
go: downloading github.com/keybase/go-crypto v0.0.0-20161004153544-93f5b35093ba
go: downloading github.com/hashicorp/logutils v1.0.0
go: downloading github.com/apparentlymart/go-cidr v1.0.1
go: downloading github.com/davecgh/go-spew v1.1.1
go: downloading github.com/hashicorp/go-hclog v0.15.0
go: downloading github.com/hashicorp/terraform-exec v0.14.0
go: downloading github.com/hashicorp/terraform-json v0.12.0
go: downloading github.com/hashicorp/terraform-plugin-go v0.3.0
go: downloading github.com/hashicorp/go-uuid v1.0.1
go: downloading github.com/boombuler/barcode v1.0.1-0.20190219062509-6c824513bacc
go: downloading github.com/xeipuuv/gojsonreference v0.0.0-20180127040603-bd5ef7bd5415
go: downloading github.com/hashicorp/hcl/v2 v2.3.0
go: downloading github.com/zclconf/go-cty v1.8.4
go: downloading github.com/hashicorp/go-plugin v1.4.1
go: downloading google.golang.org/grpc v1.32.0
go: downloading github.com/vmihailenco/msgpack v4.0.4+incompatible
go: downloading github.com/fatih/color v1.9.0
go: downloading github.com/mattn/go-isatty v0.0.12
go: downloading github.com/xeipuuv/gojsonpointer v0.0.0-20180127040702-4e3ac2762d5f
go: downloading github.com/hashicorp/go-checkpoint v0.5.0
go: downloading github.com/hashicorp/go-getter v1.5.3
go: downloading github.com/agl/ed25519 v0.0.0-20170116200512-5312a6153412
go: downloading github.com/mattn/go-colorable v0.1.7
go: downloading golang.org/x/sys v0.0.0-20210502180810-71e4cd670f79
go: downloading github.com/golang/protobuf v1.4.2
go: downloading google.golang.org/protobuf v1.25.0
go: downloading github.com/hashicorp/yamux v0.0.0-20181012175058-2f1d1f20f75d
go: downloading github.com/oklog/run v1.0.0
go: downloading golang.org/x/net v0.0.0-20210614182718-04defd469f4e
go: downloading cloud.google.com/go/storage v1.10.0
go: downloading github.com/bgentry/go-netrc v0.0.0-20140422174119-9fd32a8b3d3d
go: downloading github.com/hashicorp/go-safetemp v1.0.0
go: downloading github.com/klauspost/compress v1.11.2
go: downloading github.com/ulikunitz/xz v0.5.8
go: downloading google.golang.org/api v0.29.0
go: downloading github.com/agext/levenshtein v1.2.2
go: downloading github.com/apparentlymart/go-textseg v1.0.0
go: downloading github.com/mitchellh/go-wordwrap v1.0.0
go: downloading google.golang.org/genproto v0.0.0-20200711021454-869866162049
go: downloading github.com/apparentlymart/go-textseg/v13 v13.0.0
go: downloading cloud.google.com/go v0.61.0
go: downloading github.com/googleapis/gax-go/v2 v2.0.5
go: downloading go.opencensus.io v0.22.4
go: downloading github.com/golang/groupcache v0.0.0-20200121045136-8c9f03a8e57e
go: downloading golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.226s [no tests to run]
make: *** wait: No child processes.  Stop.
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.053s [no tests to run]
...
```

### CODE REVIEW

**Comment by jordiprats** [comment]
Hi @zhelding,
I have updated the PR to remove the merge conflicts

kind regards,

**Comment by ewbankkit** [comment]
```console
% make testacc TESTS=TestAccEC2SecurityGroupsDataSource_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2SecurityGroupsDataSource_'  -timeout 180m
=== RUN   TestAccEC2SecurityGroupsDataSource_tag
=== PAUSE TestAccEC2SecurityGroupsDataSource_tag
=== RUN   TestAccEC2SecurityGroupsDataSource_filter
=== PAUSE TestAccEC2SecurityGroupsDataSource_filter
=== CONT  TestAccEC2SecurityGroupsDataSource_filter
=== CONT  TestAccEC2SecurityGroupsDataSource_tag
--- PASS: TestAccEC2SecurityGroupsDataSource_tag (29.15s)
--- PASS: TestAccEC2SecurityGroupsDataSource_filter (29.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	34.612s
% make testacc TESTS=TestAccEC2InstancesDataSource_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstancesDataSource_'  -timeout 180m
=== RUN   TestAccEC2InstancesDataSource_basic
=== PAUSE TestAccEC2InstancesDataSource_basic
=== RUN   TestAccEC2InstancesDataSource_tags
=== PAUSE TestAccEC2InstancesDataSource_tags
=== RUN   TestAccEC2InstancesDataSource_instanceStateNames
=== PAUSE TestAccEC2InstancesDataSource_instanceStateNames
=== RUN   TestAccEC2InstancesDataSource_empty
=== PAUSE TestAccEC2InstancesDataSource_empty
=== CONT  TestAccEC2InstancesDataSource_basic
=== CONT  TestAccEC2InstancesDataSource_instanceStateNames
=== CONT  TestAccEC2InstancesDataSource_empty
=== CONT  TestAccEC2InstancesDataSource_tags
--- PASS: TestAccEC2InstancesDataSource_empty (13.42s)
--- PASS: TestAccEC2InstancesDataSource_instanceStateNames (111.19s)
--- PASS: TestAccEC2InstancesDataSource_basic (119.68s)
--- PASS: TestAccEC2InstancesDataSource_tags (121.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	126.560s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2SecurityGroupsDataSource_\|TestAccEC2InstancesDataSource_\|TestAccEC2RouteTablesDataSource_\|TestAccEC2NetworkInterfacesDataSource_\|TestAccEC2NetworkACLsDataSource_\|TestAccEC2TransitGatewayDataSource_serial/RouteTables' PKG=ec2 ACCTEST_PARALLELISM=5
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 5  -run=TestAccEC2SecurityGroupsDataSource_\|TestAccEC2InstancesDataSource_\|TestAccEC2RouteTablesDataSource_\|TestAccEC2NetworkInterfacesDataSource_\|TestAccEC2NetworkACLsDataSource_\|TestAccEC2TransitGatewayDataSource_serial/RouteTables -timeout 180m
=== RUN   TestAccEC2InstancesDataSource_basic
=== PAUSE TestAccEC2InstancesDataSource_basic
=== RUN   TestAccEC2InstancesDataSource_tags
=== PAUSE TestAccEC2InstancesDataSource_tags
=== RUN   TestAccEC2InstancesDataSource_instanceStateNames
=== PAUSE TestAccEC2InstancesDataSource_instanceStateNames
=== RUN   TestAccEC2InstancesDataSource_empty
=== PAUSE TestAccEC2InstancesDataSource_empty
=== RUN   TestAccEC2NetworkACLsDataSource_basic
=== PAUSE TestAccEC2NetworkACLsDataSource_basic
=== RUN   TestAccEC2NetworkACLsDataSource_filter
=== PAUSE TestAccEC2NetworkACLsDataSource_filter
=== RUN   TestAccEC2NetworkACLsDataSource_tags
=== PAUSE TestAccEC2NetworkACLsDataSource_tags
=== RUN   TestAccEC2NetworkACLsDataSource_vpcID
=== PAUSE TestAccEC2NetworkACLsDataSource_vpcID
=== RUN   TestAccEC2NetworkACLsDataSource_empty
=== PAUSE TestAccEC2NetworkACLsDataSource_empty
=== RUN   TestAccEC2NetworkInterfacesDataSource_filter
=== PAUSE TestAccEC2NetworkInterfacesDataSource_filter
=== RUN   TestAccEC2NetworkInterfacesDataSource_tags
=== PAUSE TestAccEC2NetworkInterfacesDataSource_tags
=== RUN   TestAccEC2NetworkInterfacesDataSource_empty
=== PAUSE TestAccEC2NetworkInterfacesDataSource_empty
=== RUN   TestAccEC2RouteTablesDataSource_basic
=== PAUSE TestAccEC2RouteTablesDataSource_basic
=== RUN   TestAccEC2SecurityGroupsDataSource_tag
=== PAUSE TestAccEC2SecurityGroupsDataSource_tag
=== RUN   TestAccEC2SecurityGroupsDataSource_filter
=== PAUSE TestAccEC2SecurityGroupsDataSource_filter
=== RUN   TestAccEC2SecurityGroupsDataSource_empty
=== PAUSE TestAccEC2SecurityGroupsDataSource_empty
=== RUN   TestAccEC2TransitGatewayDataSource_serial
=== RUN   TestAccEC2TransitGatewayDataSource_serial/RouteTables
=== RUN   TestAccEC2TransitGatewayDataSource_serial/RouteTables/Tags
=== RUN   TestAccEC2TransitGatewayDataSource_serial/RouteTables/Empty
=== RUN   TestAccEC2TransitGatewayDataSource_serial/RouteTables/basic
=== RUN   TestAccEC2TransitGatewayDataSource_serial/RouteTables/Filter
--- PASS: TestAccEC2TransitGatewayDataSource_serial (1048.47s)
    --- PASS: TestAccEC2TransitGatewayDataSource_serial/RouteTables (1048.47s)
        --- PASS: TestAccEC2TransitGatewayDataSource_serial/RouteTables/Tags (346.42s)
        --- PASS: TestAccEC2TransitGatewayDataSource_serial/RouteTables/Empty (10.04s)
        --- PASS: TestAccEC2TransitGatewayDataSource_serial/RouteTables/basic (333.84s)
        --- PASS: TestAccEC2TransitGatewayDataSource_serial/RouteTables/Filter (358.17s)
=== CONT  TestAccEC2InstancesDataSource_basic
=== CONT  TestAccEC2NetworkACLsDataSource_empty
=== CONT  TestAccEC2NetworkACLsDataSource_basic
=== CONT  TestAccEC2NetworkACLsDataSource_tags
=== CONT  TestAccEC2RouteTablesDataSource_basic
--- PASS: TestAccEC2NetworkACLsDataSource_empty (9.76s)
=== CONT  TestAccEC2InstancesDataSource_instanceStateNames
--- PASS: TestAccEC2NetworkACLsDataSource_basic (22.23s)
=== CONT  TestAccEC2InstancesDataSource_empty
--- PASS: TestAccEC2NetworkACLsDataSource_tags (22.31s)
=== CONT  TestAccEC2NetworkInterfacesDataSource_tags
--- PASS: TestAccEC2RouteTablesDataSource_basic (24.23s)
=== CONT  TestAccEC2NetworkInterfacesDataSource_empty
--- PASS: TestAccEC2InstancesDataSource_empty (9.61s)
=== CONT  TestAccEC2InstancesDataSource_tags
--- PASS: TestAccEC2NetworkInterfacesDataSource_empty (10.11s)
=== CONT  TestAccEC2NetworkInterfacesDataSource_filter
--- PASS: TestAccEC2NetworkInterfacesDataSource_tags (27.75s)
=== CONT  TestAccEC2NetworkACLsDataSource_vpcID
--- PASS: TestAccEC2NetworkInterfacesDataSource_filter (27.36s)
=== CONT  TestAccEC2NetworkACLsDataSource_filter
--- PASS: TestAccEC2NetworkACLsDataSource_vpcID (21.78s)
=== CONT  TestAccEC2SecurityGroupsDataSource_filter
--- PASS: TestAccEC2NetworkACLsDataSource_filter (21.27s)
=== CONT  TestAccEC2SecurityGroupsDataSource_empty
--- PASS: TestAccEC2SecurityGroupsDataSource_empty (9.14s)
=== CONT  TestAccEC2SecurityGroupsDataSource_tag
--- PASS: TestAccEC2SecurityGroupsDataSource_filter (25.45s)
--- PASS: TestAccEC2InstancesDataSource_instanceStateNames (97.45s)
--- PASS: TestAccEC2SecurityGroupsDataSource_tag (26.25s)
--- PASS: TestAccEC2InstancesDataSource_basic (138.83s)
--- PASS: TestAccEC2InstancesDataSource_tags (125.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1209.232s
% make testacc TESTARGS='-run=TestAccEC2CoIPPoolsDataSource_\|TestAccEC2LocalGatewayRouteTablesDataSource_\|TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_\|TestAccEC2LocalGatewaysDataSource_\|TestAccEC2EBSVolumesDataSource_' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2CoIPPoolsDataSource_\|TestAccEC2LocalGatewayRouteTablesDataSource_\|TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_\|TestAccEC2LocalGatewaysDataSource_\|TestAccEC2EBSVolumesDataSource_ -timeout 180m
=== RUN   TestAccEC2CoIPPoolsDataSource_basic
=== PAUSE TestAccEC2CoIPPoolsDataSource_basic
=== RUN   TestAccEC2CoIPPoolsDataSource_filter
=== PAUSE TestAccEC2CoIPPoolsDataSource_filter
=== RUN   TestAccEC2EBSVolumesDataSource_basic
=== PAUSE TestAccEC2EBSVolumesDataSource_basic
=== RUN   TestAccEC2LocalGatewayRouteTablesDataSource_basic
=== PAUSE TestAccEC2LocalGatewayRouteTablesDataSource_basic
=== RUN   TestAccEC2LocalGatewayRouteTablesDataSource_filter
=== PAUSE TestAccEC2LocalGatewayRouteTablesDataSource_filter
=== RUN   TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_basic
=== PAUSE TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_basic
=== RUN   TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_filter
=== PAUSE TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_filter
=== RUN   TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_tags
=== PAUSE TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_tags
=== RUN   TestAccEC2LocalGatewaysDataSource_basic
=== PAUSE TestAccEC2LocalGatewaysDataSource_basic
=== CONT  TestAccEC2CoIPPoolsDataSource_basic
=== CONT  TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_basic
=== CONT  TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_tags
=== CONT  TestAccEC2LocalGatewayRouteTablesDataSource_basic
=== CONT  TestAccEC2CoIPPoolsDataSource_filter
=== CONT  TestAccEC2LocalGatewaysDataSource_basic
=== CONT  TestAccEC2LocalGatewayRouteTablesDataSource_filter
=== CONT  TestAccEC2EBSVolumesDataSource_basic
=== CONT  TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_filter
=== CONT  TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_basic
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_basic (1.92s)
=== CONT  TestAccEC2LocalGatewayRouteTablesDataSource_filter
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2LocalGatewayRouteTablesDataSource_filter (1.97s)
=== CONT  TestAccEC2LocalGatewaysDataSource_basic
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2LocalGatewaysDataSource_basic (2.00s)
=== CONT  TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_filter
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_filter (2.01s)
=== CONT  TestAccEC2CoIPPoolsDataSource_basic
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2CoIPPoolsDataSource_basic (2.03s)
=== CONT  TestAccEC2LocalGatewayRouteTablesDataSource_basic
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2LocalGatewayRouteTablesDataSource_basic (2.03s)
=== CONT  TestAccEC2CoIPPoolsDataSource_filter
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2CoIPPoolsDataSource_filter (2.07s)
=== CONT  TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_tags
    acctest.go:1264: skipping since no Outposts found
--- SKIP: TestAccEC2LocalGatewayVirtualInterfaceGroupsDataSource_tags (5.63s)
--- PASS: TestAccEC2EBSVolumesDataSource_basic (32.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	35.617s
% make testacc TESTS=TestAccCognitoIDPUserPoolsDataSource_ PKG=cognitoidp
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cognitoidp/... -v -count 1 -parallel 20 -run='TestAccCognitoIDPUserPoolsDataSource_'  -timeout 180m
=== RUN   TestAccCognitoIDPUserPoolsDataSource_basic
=== PAUSE TestAccCognitoIDPUserPoolsDataSource_basic
=== CONT  TestAccCognitoIDPUserPoolsDataSource_basic
--- PASS: TestAccCognitoIDPUserPoolsDataSource_basic (16.60s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp	20.217s
% make testacc TESTS=TestAccMetaIPRangesDataSource_ PKG=meta
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20 -run='TestAccMetaIPRangesDataSource_'  -timeout 180m
=== RUN   TestAccMetaIPRangesDataSource_basic
=== PAUSE TestAccMetaIPRangesDataSource_basic
=== RUN   TestAccMetaIPRangesDataSource_url
=== PAUSE TestAccMetaIPRangesDataSource_url
=== CONT  TestAccMetaIPRangesDataSource_basic
=== CONT  TestAccMetaIPRangesDataSource_url
--- PASS: TestAccMetaIPRangesDataSource_url (11.46s)
--- PASS: TestAccMetaIPRangesDataSource_basic (11.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	15.373s
% make testacc TESTS=TestAccEFSAccessPointsDataSource_ PKG=efs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/efs/... -v -count 1 -parallel 20 -run='TestAccEFSAccessPointsDataSource_'  -timeout 180m
=== RUN   TestAccEFSAccessPointsDataSource_basic
=== PAUSE TestAccEFSAccessPointsDataSource_basic
=== RUN   TestAccEFSAccessPointsDataSource_empty
=== PAUSE TestAccEFSAccessPointsDataSource_empty
=== CONT  TestAccEFSAccessPointsDataSource_basic
=== CONT  TestAccEFSAccessPointsDataSource_empty
--- PASS: TestAccEFSAccessPointsDataSource_empty (22.56s)
--- PASS: TestAccEFSAccessPointsDataSource_basic (28.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/efs	32.289s
% make testacc TESTS=TestAccEMRReleaseLabels_ PKG=emr
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/emr/... -v -count 1 -parallel 20 -run='TestAccEMRReleaseLabels_'  -timeout 180m
=== RUN   TestAccEMRReleaseLabels_basic
=== PAUSE TestAccEMRReleaseLabels_basic
=== RUN   TestAccEMRReleaseLabels_prefix
=== PAUSE TestAccEMRReleaseLabels_prefix
=== RUN   TestAccEMRReleaseLabels_application
=== PAUSE TestAccEMRReleaseLabels_application
=== RUN   TestAccEMRReleaseLabels_full
=== PAUSE TestAccEMRReleaseLabels_full
=== RUN   TestAccEMRReleaseLabels_empty
=== PAUSE TestAccEMRReleaseLabels_empty
=== CONT  TestAccEMRReleaseLabels_basic
=== CONT  TestAccEMRReleaseLabels_full
=== CONT  TestAccEMRReleaseLabels_empty
=== CONT  TestAccEMRReleaseLabels_prefix
=== CONT  TestAccEMRReleaseLabels_application
--- PASS: TestAccEMRReleaseLabels_prefix (12.83s)
--- PASS: TestAccEMRReleaseLabels_full (12.89s)
--- PASS: TestAccEMRReleaseLabels_empty (12.94s)
--- PASS: TestAccEMRReleaseLabels_application (13.41s)
--- PASS: TestAccEMRReleaseLabels_basic (14.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/emr	18.580s
% make testacc TESTS=TestAccInspectorRulesPackagesDataSource_ PKG=inspector
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/inspector/... -v -count 1 -parallel 20 -run='TestAccInspectorRulesPackagesDataSource_'  -timeout 180m
=== RUN   TestAccInspectorRulesPackagesDataSource_basic
=== PAUSE TestAccInspectorRulesPackagesDataSource_basic
=== CONT  TestAccInspectorRulesPackagesDataSource_basic
--- PASS: TestAccInspectorRulesPackagesDataSource_basic (9.55s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/inspector	13.141s
% make testacc TESTS=TestAccRDSEventCategoriesDataSource_ PKG=rds
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSEventCategoriesDataSource_'  -timeout 180m
=== RUN   TestAccRDSEventCategoriesDataSource_basic
=== PAUSE TestAccRDSEventCategoriesDataSource_basic
=== RUN   TestAccRDSEventCategoriesDataSource_sourceType
=== PAUSE TestAccRDSEventCategoriesDataSource_sourceType
=== CONT  TestAccRDSEventCategoriesDataSource_basic
=== CONT  TestAccRDSEventCategoriesDataSource_sourceType
--- PASS: TestAccRDSEventCategoriesDataSource_sourceType (12.60s)
--- PASS: TestAccRDSEventCategoriesDataSource_basic (12.63s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	16.116s
% make testacc TESTS=TestAccSSOAdminInstancesDataSource_ PKG=ssoadmin
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ssoadmin/... -v -count 1 -parallel 20 -run='TestAccSSOAdminInstancesDataSource_'  -timeout 180m
=== RUN   TestAccSSOAdminInstancesDataSource_basic
=== PAUSE TestAccSSOAdminInstancesDataSource_basic
=== CONT  TestAccSSOAdminInstancesDataSource_basic
--- PASS: TestAccSSOAdminInstancesDataSource_basic (11.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ssoadmin	15.657s
```

**Comment by ewbankkit** [comment]
@jordiprats Thanks for the contribution :tada: :clap:.

**Pull request merged**
