### PR TITLE
14324 - Fix kafka_versions being a required field

### LINKED ISSUE #14324: Unable to create MSK configuration with no kafka_versions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

+ Terraform v0.12.23
+ provider.aws v2.56.0

### Affected Resource(s)

* aws_msk_configuration

### Terraform Configuration Files

```hcl
#No kafka_versions property

resource aws_msk_configuration no_arg_config {
  name                     = "no_arg_config"
  server_properties = <<PROPERTIES
auto.create.topics.enable = true
delete.topic.enable = true
PROPERTIES
}
```

```hcl
# kafka_versions null property

resource aws_msk_configuration null_kafka_versions_config {
  name              = "null_kafka_versions_config"
  kafka_versions    = null
  server_properties = <<PROPERTIES
auto.create.topics.enable = true
delete.topic.enable = true
PROPERTIES
}
```

### Debug Output

```
#No kafka_versions property output

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
cd "msk-configs"; \
        terraform plan 
Error: Missing required argument
  on .terraform/modules/msk-configs/modules/msk-configs/main.tf line 23, in resource "aws_msk_configuration" "no_arg_config":
  23: resource aws_msk_configuration no_arg_config {
The argument "kafka_versions" is required, but no definition was found.
```

```
#kafka_versions null property output 

cd "msk-configs"; \
        terraform plan 
Error: "kafka_versions": required field is not set
  on .terraform/modules/msk-configs/modules/msk-configs/main.tf line 23, in resource "aws_msk_configuration" "null_kafka_versions_config":
  23: resource aws_msk_configuration null_kafka_versions_config {
```

### Panic Output

N/A

### Expected Behaviour

I expected to create MSK configuration without specifying any Kafka Versions (see actual behaviour) but this property is currently mandatory on Terraform level even though it is optional on SDK level. 

FTR it is fine that empty list and/or null fail but I expected that at least unset kafka_versions would get through

### Actual Behavior

AWS UI and CLI allow to create MSK configuration without specifying Kafka version
- AWS CLI see https://docs.aws.amazon.com/cli/latest/reference/kafka/create-configuration.html) 
- UI console in AWS MSK service allows to specify None for Kafka versions

In CLI --kafka-versions is optional parameter however Terraform resource requires this parameter to be set (see https://www.terraform.io/docs/providers/aws/r/msk_configuration.html#kafka_versions)

I tried following settings on terraform level: 
1) Leave kafka_versions unset in TF resource - this does not work, see first output above for details 
2) Set kafka_versions to null - this does not work either, see second output
3) Set kafka_versions to empty list ([]) - unfortunately this does not work either. I checked the cloudtrails and it shows following trace:
```
"requestParameters": {
        "name": "ConfigEmptyVersion",
        "kafkaVersions": [],
        "serverProperties": "YXV0by5jcmVhdGUudG9waWNzLmVuYWJsZSA9IHRydWUKZGVsZXRlLnRvcGljLmVuYWJsZSA9IHRydWUK"
    },
    "responseElements": {
        "message": "The provided value is not valid.",
        "invalidParameter": "kafkaVersions"
    }
```

I also created configuration without versions using UI just to check how should the request look like and got following results:

```
"requestParameters": {
        "name": "NoneConfigTest",
        "description": "Some desc",
        "serverProperties": "YXV0by5jcmVhdGUudG9waWNzLmVuYWJsZT1mYWxzZQ=="
    },
    "responseElements": {
        "name": "NoneConfigTest",
        "creationTime": "2020-07-23T14:49:11.474Z",
        "arn": "arn:aws:kafka:us-west-2:942795021942:configuration/NoneConfigTest/d97b9c42-9500-4f45-906d-9e86fe8bc2d7-4",
        "latestRevision": {
            "creationTime": "2020-07-23T14:49:11.474Z",
            "revision": 1,
            "description": "Some desc"
        }
    },
```

So it looks like the request works as long as kafka_versions is not specified, however given that null, empty list and property omissions don't work I am not able to achieve that from Terraform level.

This is can be useful when creating cluster with some config and then upgrading it to higher version when it becomes available (config is not version specific so chances are high that it will apply to higher version as well).

I think kafka_versions property should be optional on Terraform level as it is on AWS SDK level. 

### Steps to Reproduce

Try to create aws_msk_configuration with either:
1) Unset kafka_versions
2) kafka_versions set to null
3) kafka_versions set to []

Given that kafka_versions is optional on SDK level I would expect that 1) should be supported. I am fine with 2) and 3) not working

### Important Factoids

It looks like AWS is actively working on providing more features WRT MSK configurations so it may be that kafka_versions property was mandatory at some point

### PR DESCRIPTION
**Pull request by ryan-dyer-sp**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14324

Output from acceptance testing:
```
make testacc TESTARGS='-run=TestAccAWSMskConfiguration'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMskConfiguration -timeout 120m
=== RUN   TestAccAWSMskConfigurationDataSource_Name
=== PAUSE TestAccAWSMskConfigurationDataSource_Name
=== RUN   TestAccAWSMskConfiguration_basic
=== PAUSE TestAccAWSMskConfiguration_basic
=== RUN   TestAccAWSMskConfiguration_disappears
=== PAUSE TestAccAWSMskConfiguration_disappears
=== RUN   TestAccAWSMskConfiguration_Description
=== PAUSE TestAccAWSMskConfiguration_Description
=== RUN   TestAccAWSMskConfiguration_KafkaVersions
=== PAUSE TestAccAWSMskConfiguration_KafkaVersions
=== RUN   TestAccAWSMskConfiguration_ServerProperties
=== PAUSE TestAccAWSMskConfiguration_ServerProperties
=== CONT  TestAccAWSMskConfigurationDataSource_Name
=== CONT  TestAccAWSMskConfiguration_KafkaVersions
=== CONT  TestAccAWSMskConfiguration_ServerProperties
=== CONT  TestAccAWSMskConfiguration_disappears
=== CONT  TestAccAWSMskConfiguration_Description
=== CONT  TestAccAWSMskConfiguration_basic
--- PASS: TestAccAWSMskConfiguration_KafkaVersions (42.42s)
--- PASS: TestAccAWSMskConfigurationDataSource_Name (42.77s)
--- PASS: TestAccAWSMskConfiguration_disappears (50.25s)
--- PASS: TestAccAWSMskConfiguration_basic (50.45s)
--- PASS: TestAccAWSMskConfiguration_Description (54.28s)
--- PASS: TestAccAWSMskConfiguration_ServerProperties (76.16s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       76.265s
```

### CODE REVIEW

**Comment by ryan-dyer-sp** [comment]
For updating the changelog to I create a file in the .changelog directory corresponding to the issue ID or PR ID?  And then do I do something else to render the CHANGELOG.md?

**Comment by ryan-dyer-sp** [comment]
Need feedback

**Comment by ryan-dyer-sp** [comment]
Still need feedback

**Comment by ewbankkit** [comment]
@ryan-dyer-sp Thanks for the contribution 👏.
The CHANGELOG entry process is documented [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process).
The actual changes to `CHANGELOG.md` are performed by a GitHub action.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSMskConfiguration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMskConfiguration_ -timeout 120m
=== RUN   TestAccAWSMskConfiguration_basic
=== PAUSE TestAccAWSMskConfiguration_basic
=== RUN   TestAccAWSMskConfiguration_disappears
=== PAUSE TestAccAWSMskConfiguration_disappears
=== RUN   TestAccAWSMskConfiguration_Description
=== PAUSE TestAccAWSMskConfiguration_Description
=== RUN   TestAccAWSMskConfiguration_KafkaVersions
=== PAUSE TestAccAWSMskConfiguration_KafkaVersions
=== RUN   TestAccAWSMskConfiguration_ServerProperties
=== PAUSE TestAccAWSMskConfiguration_ServerProperties
=== CONT  TestAccAWSMskConfiguration_basic
=== CONT  TestAccAWSMskConfiguration_KafkaVersions
=== CONT  TestAccAWSMskConfiguration_Description
=== CONT  TestAccAWSMskConfiguration_ServerProperties
=== CONT  TestAccAWSMskConfiguration_disappears
--- PASS: TestAccAWSMskConfiguration_disappears (12.14s)
--- PASS: TestAccAWSMskConfiguration_KafkaVersions (21.48s)
--- PASS: TestAccAWSMskConfiguration_basic (22.88s)
--- PASS: TestAccAWSMskConfiguration_ServerProperties (26.26s)
--- PASS: TestAccAWSMskConfiguration_Description (31.01s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	34.448s                          
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSMskConfiguration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMskConfiguration_ -timeout 120m
=== RUN   TestAccAWSMskConfiguration_basic
=== PAUSE TestAccAWSMskConfiguration_basic
=== RUN   TestAccAWSMskConfiguration_disappears
=== PAUSE TestAccAWSMskConfiguration_disappears
=== RUN   TestAccAWSMskConfiguration_Description
=== PAUSE TestAccAWSMskConfiguration_Description
=== RUN   TestAccAWSMskConfiguration_KafkaVersions
=== PAUSE TestAccAWSMskConfiguration_KafkaVersions
=== RUN   TestAccAWSMskConfiguration_ServerProperties
=== PAUSE TestAccAWSMskConfiguration_ServerProperties
=== CONT  TestAccAWSMskConfiguration_basic
=== CONT  TestAccAWSMskConfiguration_KafkaVersions
=== CONT  TestAccAWSMskConfiguration_Description
=== CONT  TestAccAWSMskConfiguration_ServerProperties
=== CONT  TestAccAWSMskConfiguration_disappears
--- PASS: TestAccAWSMskConfiguration_KafkaVersions (35.21s)
--- PASS: TestAccAWSMskConfiguration_ServerProperties (37.94s)
--- PASS: TestAccAWSMskConfiguration_basic (38.60s)
--- PASS: TestAccAWSMskConfiguration_disappears (39.50s)
--- PASS: TestAccAWSMskConfiguration_Description (41.94s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	44.796s
```

**Comment by ewbankkit** [comment]
@ryan-dyer-sp I added the CHANGELOG entry in order to get this merged quicker.

**Comment by ryan-dyer-sp** [comment]
@ewbankkit Thanks! its been a crazy week.

**Pull request merged**
