### PR TITLE
r/aws_fms_policy: Added policy_option config block for FMS policy

### LINKED ISSUE #25088: Support PolicyOption for AWS Firewall Manager Policies
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
For AWS Firewall Manager Network Firewall Policies, a new attribute PolicyOption has been added to SecurityServicePolicyData. Please add support for this attribute.

Excerpt from AWS CLI documentation: https://docs.aws.amazon.com/cli/latest/reference/fms/put-policy.html
**"SecurityServicePolicyData**": {
    **"Type":** 
"WAF"|"WAFV2"|"SHIELD_ADVANCED"|"SECURITY_GROUPS_COMMON"|"SECURITY_GROUPS_CONTENT_AUDIT"|"SECURITY_GROUPS_USAGE_AUDIT"|"NETWORK_FIREWALL"|"DNS_FIREWALL"|"THIRD_PARTY_FIREWALL",
    **"ManagedServiceData"**: "string",
    **"PolicyOption":** {
              "NetworkFirewallPolicy": {
                 "FirewallDeploymentModel": "CENTRALIZED"|"DISTRIBUTED"
                  },
              "ThirdPartyFirewallPolicy": {
                  "FirewallDeploymentModel": "CENTRALIZED"|"DISTRIBUTED"
                 }
          }
      }

### New or Affected Resource(s)

aws_fms_policy 
### Potential Terraform Configuration

```hcl
resource "aws_fms_policy" "example" {
  name                  = "FMS-Policy-Example"
  exclude_resource_tags = false
  remediation_enabled   = false
  resource_type_list    = ["AWS::EC2::VPC"]

  security_service_policy_data {
    type = "NETWORK_FIREWALL"
    managed_service_data = jsonencode(var.managed_service_data)
    policy_option = var.policy_option
  }

  tags = {
    Name = "example-fms-policy"
  }
}
```

### References

* https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_SecurityServicePolicyData.html
* https://docs.aws.amazon.com/fms/2018-01-01/APIReference/API_PutPolicy.html

### PR DESCRIPTION
**Pull request by daftkid**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #25088

Output from acceptance testing:
Sorry, I'm not able to run Acceptance Tests right now, could you please run them for this PR?

```
$ make testacc TESTS=testAccPolicy_policyOption PKG=fms
$ make testacc TESTS=testAccPolicy_ PKG=fms

...
```

### CODE REVIEW

**Comment by mrtnfchs** [comment]
Are there plans to merge this PR any time soon ?

**Comment by stevec1980** [comment]
are there any plans to merge this soon?

**Comment by mgomezzul** [comment]
any update on this topic?

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀

**Comment by johnsonaj** [comment]
@daftkid thank you for the contribution! 🎉

**Pull request merged**
