### PR TITLE
New Resource Service Catalog AppRegistry AttributeGroup

### PR DESCRIPTION
**Pull request by drewtul**
### Description
New resource to manage Service Catalog AppRegistry Attribute Groups

### Output from Acceptance Testing

```console
%  make testacc TESTS=TestAccServiceCatalogAppRegistryAttributeGroup_ PKG=servicecatalogappregistry
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.4 test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryAttributeGroup_'  -timeout 360m
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_null
    attribute_group_tags_gen_test.go:192: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccServiceCatalogAppRegistryAttributeGroup_tags_null (0.00s)
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_AddOnUpdate
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_AddOnUpdate
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnCreate
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnCreate
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Add
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Replace
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Replace
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_providerOnly
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_providerOnly
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nonOverlapping
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_overlapping
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_overlapping
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyResourceTag
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyResourceTag
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyProviderOnlyTag
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyProviderOnlyTag
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nullOverlappingResourceTag
    attribute_group_tags_gen_test.go:1448: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nullOverlappingResourceTag (0.00s)
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nullNonOverlappingResourceTag
    attribute_group_tags_gen_test.go:1512: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nullNonOverlappingResourceTag (0.00s)
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnCreate
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnCreate
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Add
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Add
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Replace
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Replace
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_basic
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_basic
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_update
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_update
=== RUN   TestAccServiceCatalogAppRegistryAttributeGroup_disappears
=== PAUSE TestAccServiceCatalogAppRegistryAttributeGroup_disappears
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToResourceOnly
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Replace
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnCreate
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnCreate
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Replace
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_AddOnUpdate
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_disappears
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_basic
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_update
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToProviderOnly
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_overlapping
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_providerOnly
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Add
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nonOverlapping
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Add
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyProviderOnlyTag
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyResourceTag
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_disappears (35.99s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_basic (41.97s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnCreate (49.62s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyResourceTag (50.78s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyProviderOnlyTag (55.56s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_update (63.81s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_AddOnUpdate (68.00s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToResourceOnly (69.32s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Replace (69.95s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Replace (73.99s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToProviderOnly (74.03s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Add (78.31s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnCreate (81.63s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Add (86.96s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nonOverlapping (94.39s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_overlapping (99.51s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_providerOnly (112.03s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags (114.94s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry  119.242s
```

### CODE REVIEW

**Comment by YakDriver** [comment]
I'm getting an error:

```
Error: Value Conversion Error
        
          with aws_servicecatalogappregistry_attribute_group.test,
          on main_gen.tf line 19, in resource "aws_servicecatalogappregistry_attribute_group" "test":
          19:   tags = var.resource_tags
        
        An unexpected error was encountered trying to convert into a Terraform value.
        This is always an error in the provider. Please report the following to the
        provider developer:
        
        Cannot use attr.Value basetypes.MapValue, only tags.Map is supported because
        tags.mapType is the type in the schema
```

**Comment by drewtul** [comment]
Hey, sorry, missed this notification, I'll get this PR updated and come back to you.

**Comment by drewtul** [comment]
I've rebased this and updated the issues you've found, it should pass now, the type for tags in the model had changed since I raised this.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=servicecatalogappregistry TESTS=TestAccServiceCatalogAppRegistryAttributeGroup_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryAttributeGroup_'  -timeout 360m
2024/12/05 10:30:59 Initializing Terraform AWS Provider...

--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_disappears (33.81s)
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnCreate
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_basic (39.19s)
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyMap
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nullNonOverlappingResourceTag (47.90s)
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_null
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nullOverlappingResourceTag (48.08s)
=== CONT  TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_providerOnly
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnCreate (48.56s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyProviderOnlyTag (48.81s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_emptyResourceTag (51.22s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_update (57.13s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToResourceOnly (70.18s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_AddOnUpdate (71.43s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Replace (72.50s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_updateToProviderOnly (73.08s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Add (74.10s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_ComputedTag_OnUpdate_Replace (74.50s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyMap (35.37s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_null (31.45s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_IgnoreTags_Overlap_DefaultTag (82.05s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_IgnoreTags_Overlap_ResourceTag (85.43s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnUpdate_Add (88.43s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_EmptyTag_OnCreate (56.19s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_nonOverlapping (91.72s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_overlapping (93.31s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags (103.90s)
--- PASS: TestAccServiceCatalogAppRegistryAttributeGroup_tags_DefaultTags_providerOnly (72.05s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry  125.182s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @drewtul! 👍

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Pull request merged**
