### PR TITLE
Introduce new resource for Cognito User Pool to add new custom attribute "aws_cognito_user_pool_schema_custom_attribute", (Since existing resource forces to destroy user pool on addition of new custom attribute.)

### PR DESCRIPTION
**Pull request by mmritesh**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Solves #3891

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

- `aws_cognito_user_pool` resource has support for adding custom attributes to the user pool only at the time of creation of the pool. If we try to add the attribute to the pool after creation it forces to destroy the pool. Moreover we don't have support to update custom attributes in `aws cognito-id update-user-pool` api. https://docs.aws.amazon.com/cli/latest/reference/cognito-idp/update-user-pool.html
- We have `aws cognito-idp add-custom-attribute` api to add new custom attributes after pool creation. BUT still we cannot update or delete the custom attribute schema from the pool once the attribute is created. 
- So with all this, the solution for the problem is to introduce a new reosurce: `aws_cognito_user_pool_schema_custom_attributes` which use the api and add the custom attributes to the existing user pool without destroying it. BUT we cannot update the existing custom attribute.
- We need to decouple  `schema` attribute from `aws_cognito_user_pool` and use it from the new resource: `aws_cognito_user_pool_schema_custom_attributes`.

- the current config looks like:
```
resource "aws_cognito_user_pool" "main" {
  name = "cool-pool"

  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = false
    name                     = "email"
    required                 = true

    string_attribute_constraints {
      min_length = 5
      max_length = 10
    }
  }

  schema {
    attribute_data_type      = "Boolean"
    developer_only_attribute = true
    mutable                  = false
    name                     = "mybool"
    required                 = false
  }
}
```
- After the change we have to remove the existing schema attribute to the new resource if we have pool already created with standard/custom attributes. 
NOTE1: This will not affect the existing attributes, it will just update the tf state (i.e. remove `schema` from the user-pool resource and just update the new resource state with the existing attributes.)
NOTE2: This will only add non existing attributes to the userpool

```
resource "aws_cognito_user_pool" "pool" {
   name = "cool-pool"
}

resource "aws_cognito_user_pool_schema_custom_attributes" "cognito_attributes" {
  schema {
    attribute_data_type      = "String"
    developer_only_attribute = false
    mutable                  = false
    name                     = "email"
    required                 = true

    string_attribute_constraints {
      min_length = 5
      max_length = 10
    }
  }

  schema {
    attribute_data_type      = "Boolean"
    developer_only_attribute = true
    mutable                  = false
    name                     = "mybool"
    required                 = false
  }
}
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSCognitoUserPoolClient_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSCognitoUserPoolClient_basic -timeout 120m
=== RUN   TestAccAWSCognitoUserPoolClient_basic
=== PAUSE TestAccAWSCognitoUserPoolClient_basic
=== CONT  TestAccAWSCognitoUserPoolClient_basic
--- PASS: TestAccAWSCognitoUserPoolClient_basic (47.91s)
PASS

...
```

### CODE REVIEW

**Comment by pazmarianoj** [comment]
@terraform-providers/aws-provider any definition about this task? Please let us know if we can do something to help.
Thank you in advance.

**Comment by bflad** [comment]
Hi @mmritesh 👋  Thank you for submitting this pull request.

Please note that I'm not providing a long-form code review right now as the maintainer team focus is elsewhere, but I did want to provide some insights for you and anyone following here:

* I have marked this pull request as `breaking-change` since it removes existing functionality used in production by many Terraform configurations. The only potential time a change like this would be accepted as-is is during a major release when it is impossible to provide operators with a deprecation warning about the upcoming change beforehand. However, the Terraform Plugin SDK supports marking attributes as `Deprecated: "message"` and there is a [guide you can follow about deprecating attributes](https://www.terraform.io/docs/extend/best-practices/deprecations.html) so we would recommend looking through and following that guidance. That being said, deprecating/removing the existing functionality has not been approved as a necessary path forward by the maintainers in #3891, so it might be best to leave existing `aws_cognito_user_pool` functionality (adding `Computed: true` to the existing attribute) or encourage additional discussion there.
* You likely have found (or will find with properly refreshing the Terraform state via `d.Set("schema", ...)` 😄 ) that attempting to manage multiple attributes across multiple resources doesn't work as expected (e.g. two `aws_cognito_user_pool_schema_custom_attributes` resources for the same Cognito User Pool). Terraform is inherently not designed to work in this type of management scenario -- either Terraform expects to manage all of children resources for a parent resource or individual child resources unless we completely disable drift detection as currently done here. In our experience, operators typically expect Terraform to perform drift detection where possible and we would not likely accept a new resource that explicitly behaves outside the typical model of other Terraform AWS Provider resources. If this is to be implemented as a separate resource (note: I'm not explicitly saying this is correct or incorrect at the moment), then the best path would be to only manage a single attribute in the new resource.

Please reach out with any questions.

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by ewbankkit** [comment]
Superseded by #18512.

**Pull request closed without merging**
