### PR TITLE
New resource aws_quicksight_dashboard

### LINKED ISSUE #11835: Additional QuickSight resource: aws_quicksight_dashboard
<!--- Please keep this note for the community --->                                                                                                                                                                                                                                                                                                                         

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

<!--- Thank you for keeping this note for the community --->

### Description

On 2019-10-20, AWS released new APIs for QuickSight that allow for configuration management.  This request is in response to https://github.com/terraform-providers/terraform-provider-aws/issues/10990#issuecomment-558244278, requesting that a feature request per resource be created.

### New or Affected Resource(s)

* aws_quicksight_dashboard

### References

* https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-quicksight-adds-api-support-for-data-dashboard-spice-and-permissions/
* https://github.com/aws/aws-sdk-go/blob/master/CHANGELOG.md#release-v12539-2019-11-20

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/10990

### PR DESCRIPTION
**Pull request by comtef**
### Description
New resource for Quicksight Dashboard.

-  Definition mostly reuse underlying resources shared with Template. (Helper method for template renamed for clarity).
- Tests for basic usage, update, dashboard specific attributes

Includes fixes to existing Template resource :

- Missing attribute and optional fields issues
- The source entity and definition attributes cannot be both sent to the API on updates. Fixed behaviour to only send source entity when it has been used to create the resource initially
- Source entity or definition are expected on update calls even if they are not updated
- Resource update seems to use the status ResourceStatusCreationInProgress, updated waiter helper accordingly

### Relations
Relates #10990
Closes #11835 

### References
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateDashboard.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateDashboard.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeDashboard.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeDashboardDefinition.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeDashboardPermissions.html
https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteDashboard.html

### Output from Acceptance Testing
```
$ make testacc TESTS=TestAccQuickSightTemplate PKG=quicksight
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightTemplate'  -timeout 180m
=== RUN   TestAccQuickSightTemplateAlias_basic
=== PAUSE TestAccQuickSightTemplateAlias_basic
=== RUN   TestAccQuickSightTemplateAlias_disappears
=== PAUSE TestAccQuickSightTemplateAlias_disappears
=== RUN   TestAccQuickSightTemplate_basic
=== PAUSE TestAccQuickSightTemplate_basic
=== RUN   TestAccQuickSightTemplate_disappears
=== PAUSE TestAccQuickSightTemplate_disappears
=== RUN   TestAccQuickSightTemplate_barChart
=== PAUSE TestAccQuickSightTemplate_barChart
=== RUN   TestAccQuickSightTemplate_table
=== PAUSE TestAccQuickSightTemplate_table
=== RUN   TestAccQuickSightTemplate_sourceEntity
=== PAUSE TestAccQuickSightTemplate_sourceEntity
=== RUN   TestAccQuickSightTemplate_tags
=== PAUSE TestAccQuickSightTemplate_tags
=== RUN   TestAccQuickSightTemplate_update
=== PAUSE TestAccQuickSightTemplate_update
=== CONT  TestAccQuickSightTemplateAlias_basic
=== CONT  TestAccQuickSightTemplate_table
=== CONT  TestAccQuickSightTemplate_update
=== CONT  TestAccQuickSightTemplate_tags
=== CONT  TestAccQuickSightTemplate_sourceEntity
=== CONT  TestAccQuickSightTemplate_disappears
=== CONT  TestAccQuickSightTemplate_barChart
=== CONT  TestAccQuickSightTemplate_basic
=== CONT  TestAccQuickSightTemplateAlias_disappears
--- PASS: TestAccQuickSightTemplate_disappears (111.72s)
--- PASS: TestAccQuickSightTemplate_barChart (117.94s)
--- PASS: TestAccQuickSightTemplateAlias_disappears (118.72s)
--- PASS: TestAccQuickSightTemplate_basic (123.96s)
--- PASS: TestAccQuickSightTemplateAlias_basic (125.63s)
--- PASS: TestAccQuickSightTemplate_sourceEntity (143.07s)
--- PASS: TestAccQuickSightTemplate_table (164.41s)
--- PASS: TestAccQuickSightTemplate_update (190.49s)
--- PASS: TestAccQuickSightTemplate_tags (196.43s)
PASS



$ make testacc TESTS=TestAccQuickSightDashboard PKG=quicksight
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDashboard'  -timeout 180m
=== RUN   TestAccQuickSightDashboard_basic
=== PAUSE TestAccQuickSightDashboard_basic
=== RUN   TestAccQuickSightDashboard_disappears
=== PAUSE TestAccQuickSightDashboard_disappears
=== RUN   TestAccQuickSightDashboard_sourceEntity
=== PAUSE TestAccQuickSightDashboard_sourceEntity
=== RUN   TestAccQuickSightDashboard_updateVersionNumber
=== PAUSE TestAccQuickSightDashboard_updateVersionNumber
=== RUN   TestAccQuickSightDashboard_dashboardSpecificConfig
=== PAUSE TestAccQuickSightDashboard_dashboardSpecificConfig
=== CONT  TestAccQuickSightDashboard_basic
=== CONT  TestAccQuickSightDashboard_updateVersionNumber
=== CONT  TestAccQuickSightDashboard_sourceEntity
=== CONT  TestAccQuickSightDashboard_disappears
=== CONT  TestAccQuickSightDashboard_dashboardSpecificConfig
--- PASS: TestAccQuickSightDashboard_disappears (81.84s)
--- PASS: TestAccQuickSightDashboard_dashboardSpecificConfig (85.23s)
--- PASS: TestAccQuickSightDashboard_basic (90.75s)
--- PASS: TestAccQuickSightDashboard_sourceEntity (97.55s)
--- PASS: TestAccQuickSightDashboard_updateVersionNumber (131.48s)
PASS
```

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightDashboard_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDashboard_'  -timeout 180m
?       github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema  [no test files]

--- PASS: TestAccQuickSightDashboard_disappears (41.29s)
--- PASS: TestAccQuickSightDashboard_dashboardSpecificConfig (46.03s)
--- PASS: TestAccQuickSightDashboard_basic (46.93s)
--- PASS: TestAccQuickSightDashboard_sourceEntity (49.92s)
--- PASS: TestAccQuickSightDashboard_updateVersionNumber (85.52s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 88.721s
```

```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightTemplate_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightTemplate_'  -timeout 180m
?       github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema  [no test files]

--- PASS: TestAccQuickSightTemplate_disappears (37.77s)
--- PASS: TestAccQuickSightTemplate_barChart (41.82s)
--- PASS: TestAccQuickSightTemplate_basic (41.85s)
--- PASS: TestAccQuickSightTemplate_sourceEntity (44.16s)
--- PASS: TestAccQuickSightTemplate_table (66.25s)
--- PASS: TestAccQuickSightTemplate_update (72.28s)
--- PASS: TestAccQuickSightTemplate_tags (88.91s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 92.167s
```

**Comment by jar-b** [comment]
This looks great, thanks @comtef!

As a heads up, `main` is currently only merging breaking changes and deprecations in preparation for the v5.0.0 major release this week. I've added the `v5.1.0` label so this can go into the first subsequent minor release, tentatively the week of 5/29. Thanks again!

**Comment by comtef** [comment]
@jar-b Thanks for your help.
In the meantime, before v5 is released, I'll continue from this branch to start working on analysis resource.

**Comment by jar-b** [comment]
Thanks for your contribution once again, @comtef! 🎸

**Pull request merged**
