### PR TITLE
r/sagemaker_app_image_config - new resource

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSagemakerAppImageConfig_'
--- PASS: TestAccAWSSagemakerAppImageConfig_basic (36.17s)
--- PASS: TestAccAWSSagemakerAppImageConfig_disappears (21.47s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig (60.59s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs (59.63s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Tags test is being weird and causes a loop of InternalFailure errors. does not reproduce for other tests. possibly related to https://github.com/hashicorp/terraform-provider-aws/issues/15572

**Review by ewbankkit — APPROVED** [review]
LGTM.

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSagemakerAppImageConfig_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerAppImageConfig_ -timeout 120m
=== RUN   TestAccAWSSagemakerAppImageConfig_basic
=== PAUSE TestAccAWSSagemakerAppImageConfig_basic
=== RUN   TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
=== PAUSE TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
=== RUN   TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== PAUSE TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== RUN   TestAccAWSSagemakerAppImageConfig_tags
    resource_aws_sagemaker_app_image_config_test.go:193: Flaky Test, possibly related to https://github.com/hashicorp/terraform-provider-aws/issues/15572
--- SKIP: TestAccAWSSagemakerAppImageConfig_tags (0.00s)
=== RUN   TestAccAWSSagemakerAppImageConfig_disappears
=== PAUSE TestAccAWSSagemakerAppImageConfig_disappears
=== CONT  TestAccAWSSagemakerAppImageConfig_basic
=== CONT  TestAccAWSSagemakerAppImageConfig_disappears
=== CONT  TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== CONT  TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
--- PASS: TestAccAWSSagemakerAppImageConfig_disappears (12.95s)
--- PASS: TestAccAWSSagemakerAppImageConfig_basic (18.16s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig (28.82s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs (31.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	31.369s
```

**Comment by ewbankkit** [comment]
If deleting a previously tagged App Image Config causes problems - I get that with the CLI too:

```console
$ aws --region us-west-2 sagemaker delete-app-image-config --app-image-config-name tf-acc-test-8058719989336263580

An error occurred (InternalFailure) when calling the DeleteAppImageConfig operation (reached max retries: 4):
```

do you think it would be better to remove the `tags` attribute and associated logic for now, open a new Issue here and also an AWS Support issue? This would prevent problems for operators.

**Comment by DrFaust92** [comment]
Thanks @ewbankkit, opened a follow up issue and remove tagging logic for now:

```
--- PASS: TestAccAWSSagemakerAppImageConfig_basic (32.83s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig (52.96s)
--- PASS: TestAccAWSSagemakerAppImageConfig_disappears (20.76s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs (53.68s)
```

**Review by ewbankkit — APPROVED** [review]
LGTM.

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSagemakerAppImageConfig_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerAppImageConfig_ -timeout 120m
=== RUN   TestAccAWSSagemakerAppImageConfig_basic
=== PAUSE TestAccAWSSagemakerAppImageConfig_basic
=== RUN   TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
=== PAUSE TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
=== RUN   TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== PAUSE TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== RUN   TestAccAWSSagemakerAppImageConfig_disappears
=== PAUSE TestAccAWSSagemakerAppImageConfig_disappears
=== CONT  TestAccAWSSagemakerAppImageConfig_basic
=== CONT  TestAccAWSSagemakerAppImageConfig_disappears
=== CONT  TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== CONT  TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
--- PASS: TestAccAWSSagemakerAppImageConfig_disappears (12.66s)
--- PASS: TestAccAWSSagemakerAppImageConfig_basic (17.78s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig (27.71s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs (32.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	32.550s
```

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @DrFaust92 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSagemakerAppImageConfig_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSagemakerAppImageConfig_ -timeout 120m
=== RUN   TestAccAWSSagemakerAppImageConfig_basic
=== PAUSE TestAccAWSSagemakerAppImageConfig_basic
=== RUN   TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
=== PAUSE TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
=== RUN   TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== PAUSE TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== RUN   TestAccAWSSagemakerAppImageConfig_disappears
=== PAUSE TestAccAWSSagemakerAppImageConfig_disappears
=== CONT  TestAccAWSSagemakerAppImageConfig_basic
=== CONT  TestAccAWSSagemakerAppImageConfig_disappears
=== CONT  TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig
=== CONT  TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs
--- PASS: TestAccAWSSagemakerAppImageConfig_disappears (10.07s)
--- PASS: TestAccAWSSagemakerAppImageConfig_basic (13.19s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_fileSystemConfig (21.64s)
--- PASS: TestAccAWSSagemakerAppImageConfig_kernelGatewayImageConfig_kernalSpecs (24.82s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	26.431s
```

As this feature is part of Sagemaker studio, this will not work in GovCloud. I will create an issue and link back to cover enabling the test to skip in that region.

**Pull request merged**
