### PR TITLE
aws_lambda_event_source_mapping: Add Kafka config blocks + consumer_group_id

### LINKED ISSUE #26559: Self-Managed Kafka Event Source Mapping: Optionally specify consumer_group_id upon resource creation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adds "self_managed_kafka_config" (`SelfManagedKafkaEventSourceConfig`) and "amazon_managed_kafka_config" (`AmazonManagedKafkaEventSourceConfig`) blocks to "aws_lambda_event_source_mapping" resource

Enables setting Kafka `ConsumerGroupId` upon resource creation

* "The identifier for the Kafka consumer group to join. The consumer group ID must be unique among all your Kafka event sources. After creating a Kafka event source mapping with the consumer group ID specified, you cannot update this value."

### New or Affected Resource(s)

* aws_lambda_event_source_mapping

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "self_managed" {
  function_name     = aws_lambda_function.example.arn
  topics            = ["Example"]
  starting_position = "TRIM_HORIZON"

  # begin new syntax
  self_managed_kafka_config {
    consumer_group_id = "some-id"
  }
  # end

  self_managed_event_source {
    endpoints = {
      KAFKA_BOOTSTRAP_SERVERS = "kafka1.example.com:9092,kafka2.example.com:9092"
    }
  }

  source_access_configuration {
    type = "VPC_SUBNET"
    uri  = "subnet:subnet-example1"
  }
}
```

```hcl
resource "aws_lambda_event_source_mapping" "msk" {
  event_source_arn  = aws_msk_cluster.example.arn
  function_name     = aws_lambda_function.example.arn
  topics            = ["Example"]
  starting_position = "TRIM_HORIZON"

  # begin new syntax
  amazon_managed_kafka_config {
    consumer_group_id = "some-id"
  }
  # end
}
```

### References

* [2022/08 feature release announcement](https://aws.amazon.com/blogs/compute/using-custom-consumer-group-id-support-for-the-aws-lambda-event-sources-for-msk-and-self-managed-kafka/)
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/lambda/create-event-source-mapping.html (search for `ConsumerGroupId`)
* [SelfManagedKafkaEventSourceConfig](https://docs.aws.amazon.com/lambda/latest/dg/API_SelfManagedKafkaEventSourceConfig.html)
* [AmazonManagedKafkaEventSourceConfig](https://docs.aws.amazon.com/lambda/latest/dg/API_AmazonManagedKafkaEventSourceConfig.html)

### Discussion

* Despite sharing `ConsumerGroupId`, the Amazon-managed Kafka event source does not interface with `SelfManagedKafkaEventSourceConfig`, it uses `AmazonManagedKafkaEventSourceConfig`.

### PR DESCRIPTION
**Pull request by A122943**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #26559

Output from acceptance testing:

```
$ make testacc PKG=lambda TESTS=TestAccLambdaEventSourceMapping_selfManagedKafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaEventSourceMapping_selfManagedKafka'  -timeout 180m
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafka
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafka
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafka
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafka (49.90s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	53.075s
```

```
$ make testacc PKG=lambda TESTS=TestAccLambdaEventSourceMapping_msk
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaEventSourceMapping_msk'  -timeout 180m
=== RUN   TestAccLambdaEventSourceMapping_msk
=== PAUSE TestAccLambdaEventSourceMapping_msk
=== CONT  TestAccLambdaEventSourceMapping_msk
--- PASS: TestAccLambdaEventSourceMapping_msk (3214.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	3217.450s
```

### CODE REVIEW

**Comment by A122943** [comment]
Does anyone know why dependency checks / `go mod` is failing? I haven't touched dependencies

**Comment by justinretzolk** [comment]
Hey @A122943 👋 Thank you for your contribution! I believe that the failing check was something on our end. If you rebase, it should clear up the failing check.

**Comment by A122943** [comment]
Hi @justinretzolk! That worked, thank you 😃 I'm happy to answer any questions you or another maintainer might have about these changes.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLambdaEventSourceMapping_msk' PKG=lambda      
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaEventSourceMapping_msk -timeout 180m
=== RUN   TestAccLambdaEventSourceMapping_msk
=== PAUSE TestAccLambdaEventSourceMapping_msk
=== RUN   TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
=== PAUSE TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
=== CONT  TestAccLambdaEventSourceMapping_msk
=== CONT  TestAccLambdaEventSourceMapping_mskWithEventSourceConfig
--- PASS: TestAccLambdaEventSourceMapping_mskWithEventSourceConfig (3481.30s)
--- PASS: TestAccLambdaEventSourceMapping_msk (3638.39s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	3642.258s
% make testacc TESTARGS='-run=TestAccLambdaEventSourceMapping_selfManagedKafka' PKG=lambda
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaEventSourceMapping_selfManagedKafka -timeout 180m
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafka
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafka
=== RUN   TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig
=== PAUSE TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafka
=== CONT  TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafkaWithEventSourceConfig (53.85s)
--- PASS: TestAccLambdaEventSourceMapping_selfManagedKafka (59.01s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	62.775s
% make testacc TESTARGS='-run=TestAccLambdaEventSourceMapping_SQS_' PKG=lambda ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 3  -run=TestAccLambdaEventSourceMapping_SQS_ -timeout 180m
=== RUN   TestAccLambdaEventSourceMapping_SQS_basic
=== PAUSE TestAccLambdaEventSourceMapping_SQS_basic
=== RUN   TestAccLambdaEventSourceMapping_SQS_batchWindow
=== PAUSE TestAccLambdaEventSourceMapping_SQS_batchWindow
=== RUN   TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== PAUSE TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== RUN   TestAccLambdaEventSourceMapping_SQS_filterCriteria
=== PAUSE TestAccLambdaEventSourceMapping_SQS_filterCriteria
=== CONT  TestAccLambdaEventSourceMapping_SQS_basic
=== CONT  TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected
=== CONT  TestAccLambdaEventSourceMapping_SQS_filterCriteria
--- PASS: TestAccLambdaEventSourceMapping_SQS_changesInEnabledAreDetected (93.91s)
=== CONT  TestAccLambdaEventSourceMapping_SQS_batchWindow
--- PASS: TestAccLambdaEventSourceMapping_SQS_basic (114.10s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_batchWindow (66.82s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_filterCriteria (188.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	192.527s
```

**Comment by ewbankkit** [comment]
@A122943 Thanks for the contribution :tada: :clap:.
Overall everything was great. I tweaked the new attribute names to match the underling AWS API structure names and made then `ForceNew` and `Computed` as they cannot be updated after creation and as you mention in the documentation, if not specified, generated values are returned.

**Comment by A122943** [comment]
> @A122943 Thanks for the contribution 🎉 👏. Overall everything was great. I tweaked the new attribute names to match the underling AWS API structure names and made them `ForceNew` and `Computed` as they cannot be updated after creation and as you mention in the documentation, if not specified, generated values are returned.

@ewbankkit A huge thanks for polishing and merging this PR :-) 

I have one question: 

* Does the presence of `ForceNew` alongside `Computed` allow users to specify a specific value for this property upon resource creation? 

Consumer_group_id should be specifiable upon creation of the resource. But in [the docs](https://www.terraform.io/plugin/sdkv2/schemas/schema-behaviors), I read that

> Computed is often used to represent values that are not user configurable [...] Computed can be combined with other attributes to achieve specific behaviors [...]

Thank you -- just double checking 🦅

**Comment by ewbankkit** [comment]
@A122943 You are correct that an attribute marked with just `Computed` cannot be specified by the user but with an additional `Optional` (which these new attributes do have), they can be configured.

**Pull request merged**
