### PR TITLE
F/aws_sns_topic_subscription: Provide full support to HTTP/HTTPS/EMAIL/EMAIL-JSON protocols / SQS Subscription without Assume Role in both Accounts

### LINKED ISSUE #7782: aws_sns_topic_subscription doesn't support unconfirmed endpoints
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.11
+ provider.aws v1.60.0

### Affected Resource(s)

* aws_sns_topic_subscription

### Expected Behavior

A subscription is created with an email endpoint (or non-auto-confirming HTTP endpoint). If the subscription is not confirmed, then the endpoint simply doesn't receive any messages.

### Actual Behavior

The resource doesn't allow these subscriptions. The resource docs note that 

> These are unsupported because the endpoint needs to be authorized and does not generate an ARN until the target email address has been validated. This breaks the Terraform model and as a result are not currently supported.

However the SNS API includes a parameter `ReturnSubscriptionArn` which can be set to `true` to request that the ARN is returned even if the subscription isn't confirmed. As such, an ARN _is_ generated before the target email address has been validated, and this should then fit into Terraform's model.

### PR DESCRIPTION
**Pull request by smailli**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #10225.
Closes #7782.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Provide full support to HTTP/HTTPS/EMAIL/EMAIL-JSON protocols
SQS Subscription without Assume Role in both Accounts
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSNSTopicSubscription_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSNSTopicSubscription_basic -timeout 120m
=== RUN   TestAccAWSSNSTopicSubscription_basic
=== PAUSE TestAccAWSSNSTopicSubscription_basic
=== CONT  TestAccAWSSNSTopicSubscription_basic
--- PASS: TestAccAWSSNSTopicSubscription_basic (51.38s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       51.437s

$ make testacc TESTARGS='-run=TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint -timeout 120m
=== RUN   TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint
=== PAUSE TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint
=== CONT  TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint (95.15s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       95.194s
```

### CODE REVIEW

**Comment by smailli** [comment]
How the best way to deprecate a optional parameter ?

**Comment by smailli** [comment]
Any chance of getting this merged in? I could really use this.

**Review by juliane-mazucki-ifood — APPROVED** [review]

**Comment by YakDriver** [comment]
@smailli Thank you for this pull request! The `aws_sns_topic_subscription` recently underwent substantial modernization in #14923. We apologize for the inconvenience that will cause with this PR. However, we look forward to reviewing these improvements rebased on the modernization.

**Comment by smailli** [comment]
That's ok, I'll wait for that

**Comment by smailli** [comment]
Conflicts resolved

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by kalyc** [comment]
Any update on this PR? We want to use this feature for integrating custom events with pager duty.

**Comment by ewbankkit** [comment]
Superseded by https://github.com/hashicorp/terraform-provider-aws/pull/14923.

**Pull request closed without merging**
