### PR TITLE
Lake Formation Permissions

### PR DESCRIPTION
**Pull request by gmazelier**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #9700
Depends on #13250 and #13267

**AWS Lake Formation support:** manages the permissions that a principal has on an AWS Glue Data Catalog resource (such as AWS Glue database or AWS Glue tables).

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* **New Resource**: `aws_lakeformation_permissions` (#13396)
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSLakeFormationPerm'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLakeFormationPerm -timeout 120m
=== RUN   TestAccAWSLakeFormationPermissions_full
=== PAUSE TestAccAWSLakeFormationPermissions_full
=== CONT  TestAccAWSLakeFormationPermissions_full
--- PASS: TestAccAWSLakeFormationPermissions_full (210.49s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	211.898s
```

### CODE REVIEW

**Comment by gmazelier** [comment]
@robertstettner: proposal for Lake Formation permissions support. Feedbacks are welcome :)

**Comment by kinghuang** [comment]
Is there anything the community can do to help move this and the related PRs along? I'm very eager to configure Lake Formation permissions via Terraform!

**Comment by tuannguyen0901** [comment]
Intersted in this feature as we're building data lake. Any ETA this will be released?

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by YakDriver** [comment]
@gmazelier I'm currently working on tweaks to this PR so please avoid changes for the next few days without giving me a heads up. Thanks for all your work on this!

**Comment by gmazelier** [comment]
@YakDriver yes sure.

**Review by YakDriver — APPROVED** [review]
### GovCloud acceptance tests

```
--- PASS: TestAccAWSLakeFormation_serial (312.87s)
    --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings (60.03s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/basic (15.79s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/disappears (14.63s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/withoutCatalogId (14.03s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/dataSource (15.58s)
    --- PASS: TestAccAWSLakeFormation_serial/Permissions (252.84s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/basic (24.38s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/database (24.02s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/dataLocationDataSource (25.12s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/tableDataSource (25.93s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/tableWithColumnsDataSource (23.38s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/dataLocation (26.07s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/table (26.22s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/tableWithColumns (22.81s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/basicDataSource (24.81s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/databaseDataSource (30.11s)
--- PASS: TestAccAWSLakeFormationResource_disappears (24.59s)
--- PASS: TestAccAWSLakeFormationResource_serviceLinkedRole (24.61s)
--- PASS: TestAccAWSLakeFormationResource_basic (24.95s)
--- PASS: TestAccAWSLakeFormationResourceDataSource_basic (26.08s)
--- PASS: TestAccAWSLakeFormationResource_updateSLRToRole (45.98s)
--- PASS: TestAccAWSLakeFormationResource_updateRoleToRole (47.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	361.305s
```

### Commercial acceptance tests

```
--- PASS: TestAccAWSLakeFormation_serial (330.49s)
    --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings (44.39s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/withoutCatalogId (10.73s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/dataSource (11.24s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/basic (11.85s)
        --- PASS: TestAccAWSLakeFormation_serial/DataLakeSettings/disappears (10.57s)
    --- PASS: TestAccAWSLakeFormation_serial/Permissions (286.10s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/table (26.87s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/tableWithColumns (24.02s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/basicDataSource (20.32s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/dataLocationDataSource (26.85s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/databaseDataSource (25.62s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/basic (19.28s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/database (33.18s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/tableDataSource (27.81s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/tableWithColumnsDataSource (25.21s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/dataLocation (56.93s)
--- PASS: TestAccAWSLakeFormationResource_disappears (22.29s)
--- PASS: TestAccAWSLakeFormationResource_basic (22.83s)
--- PASS: TestAccAWSLakeFormationResource_serviceLinkedRole (23.56s)
--- PASS: TestAccAWSLakeFormationResourceDataSource_basic (24.00s)
--- PASS: TestAccAWSLakeFormationResource_updateRoleToRole (40.91s)
--- PASS: TestAccAWSLakeFormationResource_updateSLRToRole (42.13s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	373.755s
```

**Pull request merged**
