### PR TITLE
resource/aws_sns_topic_subscription: Add redrive_policy argument fixes #10931

### LINKED ISSUE #10931: Resource aws_sns_topic_subscription, new argument redrive_policy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS implemented a new feature for SNS subscription: support for Dead-Letter Queues
https://aws.amazon.com/about-aws/whats-new/2019/11/amazon-sns-adds-support-for-dead-letter-queues-dlq/
The request is to implement it in resource _aws_sns_topic_subscription_, please add _redrive_policy_ as argument of this resource.

### New or Affected Resource

* aws_sns_topic_subscription

### Potential Terraform Configuration

```hcl
resource "aws_sns_topic_subscription" "lamda_function_sns_subscription" {
  topic_arn       = "arn:aws:sns:us-east-1:***:TOPIC_NAME"
  protocol        = "lambda"
  endpoint        = "arn:aws:lambda:us-east-1:***:function:function-name"
  redrive_policy = <<EOF
    {
      "deadLetterTargetArn": "arn:aws:sqs:us-east-1:***:queue-dlq"
    }
  EOF
}
```

### PR DESCRIPTION
**Pull request by Ricool06**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10931

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_sns_topic_subscription: add `redrive_policy` argument.
```

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSSNSTopicSubscription_redrivePolicy'

==> Checking that code complies with gofmt requirements...

TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSNSTopicSubscription_redrivePolicy -timeout 120m

=== RUN   TestAccAWSSNSTopicSubscription_redrivePolicy

=== PAUSE TestAccAWSSNSTopicSubscription_redrivePolicy

=== CONT  TestAccAWSSNSTopicSubscription_redrivePolicy

--- PASS: TestAccAWSSNSTopicSubscription_redrivePolicy (182.14s)

PASS

ok      github.com/terraform-providers/terraform-provider-aws/aws       185.013s
```

### CODE REVIEW

**Comment by Ricool06** [comment]
Sorry, I've opened the PR from my phone, I will fill out the rest of the description when I have access to a better text editor. I need help writing the tests for this as I have never written Go before. 😊

**Comment by Ricool06** [comment]
Tests are complete now.

**Comment by jamesanto** [comment]
Hi, is there anything I can do to speed it up?

**Comment by Ricool06** [comment]
> Hi, is there anything I can do to speed it up?

If you are part of the terraform team, please review the changes. If not, they recommend 👍 ing the PR and referenced issue. I'm sure the notification for my PR or the issue has bugged out for some reason.

**Comment by kabo** [comment]
ping @bflad maybe ?

**Comment by Ricool06** [comment]
I don't know who the active reviewers are, or how to ping them directly. It's also probably a bit of an overreach to go DMing them all over Twitter. I posted on the terraform gitter, but nobody has responded to me.

**Comment by kabo** [comment]
Yeah, to be clear I'm not asking you to ping them, I'm pinging them to hopefully get them to have a look.

**Comment by Ricool06** [comment]
Ah okay, thank you.

**Comment by anGie44** [comment]
Hi @Ricool06 -- thanks again for your contributions to this resource enhancement. Overall looks great 👍 I've rebased and will be making the folllowing updates to get this merged and added into our next release:

* add .changelog file
* pass redrive_policy argument on Create
* update test check to generalize the queue ARN so we don't have hardcoded regions

**Review by anGie44 — APPROVED** [review]
Thanks again @Ricool06 🚀 ! 

Output of acceptance tests:
```
--- PASS: TestSuppressEquivalentSnsTopicSubscriptionDeliveryPolicy (0.00s)
--- PASS: TestObfuscateEndpointPassword (0.00s)
--- PASS: TestAccAWSSNSTopicSubscription_basic (23.05s)
--- PASS: TestAccAWSSNSTopicSubscription_rawMessageDelivery (45.12s)
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint (45.63s)
--- PASS: TestAccAWSSNSTopicSubscription_filterPolicy (45.71s)
--- PASS: TestAccAWSSNSTopicSubscription_deliveryPolicy (46.63s)
--- PASS: TestAccAWSSNSTopicSubscription_redrivePolicy (47.62s)
--- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingSecuredEndpoint (76.27s)
```

**Comment by Ricool06** [comment]
> Thanks again @Ricool06 🚀 ! 
> 
> Output of acceptance tests:
> ```
> --- PASS: TestSuppressEquivalentSnsTopicSubscriptionDeliveryPolicy (0.00s)
> --- PASS: TestObfuscateEndpointPassword (0.00s)
> --- PASS: TestAccAWSSNSTopicSubscription_basic (23.05s)
> --- PASS: TestAccAWSSNSTopicSubscription_rawMessageDelivery (45.12s)
> --- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingEndpoint (45.63s)
> --- PASS: TestAccAWSSNSTopicSubscription_filterPolicy (45.71s)
> --- PASS: TestAccAWSSNSTopicSubscription_deliveryPolicy (46.63s)
> --- PASS: TestAccAWSSNSTopicSubscription_redrivePolicy (47.62s)
> --- PASS: TestAccAWSSNSTopicSubscription_autoConfirmingSecuredEndpoint (76.27s)
> ```

Thanks for getting to this! Feeling lots of relief knowing this issue is coming close to resolution 😊

**Pull request merged**
