### PR TITLE
r/aws_eks_identity_provider_config - Adds a new resource for EKS OIDC Identity Provider Config

### LINKED ISSUE #17607: EKS support for authentication using identity providers
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

EKS now supports OIDC identity providers as a mechanism of Kubernetes API authentication. This is really great news as it makes kubectl access and end user experience similar to the self managed clusters using the identity provider of choice instead of requiring IAM credentials. 

The annoucement is [here](https://github.com/aws/containers-roadmap/issues/166#issuecomment-778519901) and AWS have introduced three new API calls:
* [AssociateIdentityProviderConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_AssociateIdentityProviderConfig.html)
* [DescribeIdentityProviderConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_DescribeIdentityProviderConfig.html)
* [DisassociateIdentityProviderConfig](https://docs.aws.amazon.com/eks/latest/APIReference/API_DisassociateIdentityProviderConfig.html)

### New or Affected Resource(s)

* aws_eks_identity_provider_config

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_eks_identity_provider_config" "config" {
    oidc {
        client_id = ""
        groups_claim = ""
        groups_prefix = ""
        identity_provider_config_name = ""
        issuer_url = ""
        required_claims = {
            "key" = "value"
        }  
       username_claim = ""
       username_prefix = ""
    }
   tags = {
   }
}
```

### References

* [Launch blog](https://aws.amazon.com/about-aws/whats-new/2021/02/amazon-eks-clusters-support-user-authentication-oidc-compatible-identity-providers/)

### PR DESCRIPTION
**Pull request by willvrny**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17607

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_basic -timeout 120m
=== RUN   TestAccAWSEksIdentityProviderConfig_basic
=== PAUSE TestAccAWSEksIdentityProviderConfig_basic
=== CONT  TestAccAWSEksIdentityProviderConfig_basic
--- PASS: TestAccAWSEksIdentityProviderConfig_basic (3542.20s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3544.777s

$ make testacc TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_disappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_disappears -timeout 120m
=== RUN   TestAccAWSEksIdentityProviderConfig_disappears
=== PAUSE TestAccAWSEksIdentityProviderConfig_disappears
=== CONT  TestAccAWSEksIdentityProviderConfig_disappears
--- PASS: TestAccAWSEksIdentityProviderConfig_disappears (3554.95s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3558.570s

$ make testacc TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_Oidc_Group'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_Oidc_Group -timeout 120m
=== RUN   TestAccAWSEksIdentityProviderConfig_Oidc_Group
=== PAUSE TestAccAWSEksIdentityProviderConfig_Oidc_Group
=== CONT  TestAccAWSEksIdentityProviderConfig_Oidc_Group
--- PASS: TestAccAWSEksIdentityProviderConfig_Oidc_Group (2975.67s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2978.136s

$ make testacc TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_Oidc_Username'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_Oidc_Username -timeout 120m
=== RUN   TestAccAWSEksIdentityProviderConfig_Oidc_Username
=== PAUSE TestAccAWSEksIdentityProviderConfig_Oidc_Username
=== CONT  TestAccAWSEksIdentityProviderConfig_Oidc_Username
--- PASS: TestAccAWSEksIdentityProviderConfig_Oidc_Username (3748.44s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3751.742s

$ make testacc TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_Oidc_RequiredClaims'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_Oidc_RequiredClaims -timeout 120m
=== RUN   TestAccAWSEksIdentityProviderConfig_Oidc_RequiredClaims
=== PAUSE TestAccAWSEksIdentityProviderConfig_Oidc_RequiredClaims
=== CONT  TestAccAWSEksIdentityProviderConfig_Oidc_RequiredClaims
--- PASS: TestAccAWSEksIdentityProviderConfig_Oidc_RequiredClaims (3588.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3591.398s

$ make testacc TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_Tags'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_Tags -timeout 120m
=== RUN   TestAccAWSEksIdentityProviderConfig_Tags
=== PAUSE TestAccAWSEksIdentityProviderConfig_Tags
=== CONT  TestAccAWSEksIdentityProviderConfig_Tags
--- PASS: TestAccAWSEksIdentityProviderConfig_Tags (3701.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3704.366s
```

Questions:

1. I've not done a test per attribute as I'm seeing a single test take as long as `3832.718s`. Is this okay or would you prefer a single test per attribute? I think the length is due to spinning up an EKS cluster and then I imagine the identity provider config requires rolling the master nodes.
2. The AWS SDK put the name of the identity provider inside the OIDC struct. I've mirrored this in the resource but I'm not sure if it would be more consistent to move it out and have it as a top level field in the resource like other similar resources?
3. I'm having to check an exception message for a particular case. This feels brittle but I can see this convention used in other areas. Is this okay?
4. I've tried to use the newer `funcs` that allow for passing in a context e.g. CreateContext to avoid using deprecated code. In the tests I've just used `context.Background()`. I haven't written too much Go so I'm not too sure if this is correct?
5. I've left the commits separate but I'm happy to rebase into a single commit?

### CODE REVIEW

**Comment by xabinapal** [comment]
Is there anything missing on this PR prior to removing the draft flag? I'd be happy to help if necessary, this would be a great feature to have!

**Comment by willvrny** [comment]
Hi @xabinapal. I was just hoping to get some clarification on my questions above. Aside from any changes from those answers I think functionality wise it's ready.

**Comment by jfdoube** [comment]
Any plan to release this feature soon ?

**Comment by ewbankkit** [comment]
@willvrny Thanks for the contribution :tada: :clap:.
In response to your questions above:

1. The acceptance tests you have are sufficient given the length of time required to create all the pre-requisite resources
2. We always prefer to mimic the AWS API structure, so lets leave the IdP name where it is
3. Yes, checking AWS error message text is an unfortunate fact of life...
4. It looks like we prefer `context.TODO()` in the acceptance tests: https://github.com/hashicorp/terraform-provider-aws/blob/b063e4f577ef4626d66662bd6f752e696460c8ed/aws/resource_aws_eks_addon_test.go#L87-L93
5. Don't worry about rebasing

**Comment by willvrny** [comment]
Thank you @ewbankkit. I've made the change to use `context.TODO()`.

**Comment by alexandr-its** [comment]
Any plan to merge this feature? It will be great if I can use this feature

**Comment by ewbankkit** [comment]
@willvrny Once you remove _[WIP]_ I can start review and get this one merged.

**Comment by willvrny** [comment]
@ewbankkit Done. Thank you.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_'     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_ -timeout 180m
=== RUN   TestAccAWSEksIdentityProviderConfig_basic
=== PAUSE TestAccAWSEksIdentityProviderConfig_basic
=== RUN   TestAccAWSEksIdentityProviderConfig_disappears
=== PAUSE TestAccAWSEksIdentityProviderConfig_disappears
=== RUN   TestAccAWSEksIdentityProviderConfig_AllOidcOptions
=== PAUSE TestAccAWSEksIdentityProviderConfig_AllOidcOptions
=== RUN   TestAccAWSEksIdentityProviderConfig_Tags
=== PAUSE TestAccAWSEksIdentityProviderConfig_Tags
=== CONT  TestAccAWSEksIdentityProviderConfig_basic
=== CONT  TestAccAWSEksIdentityProviderConfig_Tags
=== CONT  TestAccAWSEksIdentityProviderConfig_AllOidcOptions
=== CONT  TestAccAWSEksIdentityProviderConfig_disappears
--- PASS: TestAccAWSEksIdentityProviderConfig_AllOidcOptions (2208.99s)
--- PASS: TestAccAWSEksIdentityProviderConfig_disappears (2226.30s)
--- PASS: TestAccAWSEksIdentityProviderConfig_basic (2226.77s)
=== CONT  TestAccAWSEksIdentityProviderConfig_Tags        
--- PASS: TestAccAWSEksIdentityProviderConfig_Tags (2320.02s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2323.155s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSEksIdentityProviderConfig_' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEksIdentityProviderConfig_ -timeout 180m
=== RUN   TestAccAWSEksIdentityProviderConfig_basic
=== PAUSE TestAccAWSEksIdentityProviderConfig_basic
=== RUN   TestAccAWSEksIdentityProviderConfig_disappears
=== PAUSE TestAccAWSEksIdentityProviderConfig_disappears
=== RUN   TestAccAWSEksIdentityProviderConfig_AllOidcOptions
=== PAUSE TestAccAWSEksIdentityProviderConfig_AllOidcOptions
=== RUN   TestAccAWSEksIdentityProviderConfig_Tags
=== PAUSE TestAccAWSEksIdentityProviderConfig_Tags
=== CONT  TestAccAWSEksIdentityProviderConfig_basic
=== CONT  TestAccAWSEksIdentityProviderConfig_Tags
=== CONT  TestAccAWSEksIdentityProviderConfig_disappears
=== CONT  TestAccAWSEksIdentityProviderConfig_AllOidcOptions
--- PASS: TestAccAWSEksIdentityProviderConfig_basic (2123.50s)
--- PASS: TestAccAWSEksIdentityProviderConfig_disappears (2169.43s)
--- PASS: TestAccAWSEksIdentityProviderConfig_AllOidcOptions (2259.97s)
--- PASS: TestAccAWSEksIdentityProviderConfig_Tags (2292.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2295.438s
```

**Comment by ewbankkit** [comment]
@willvrny Thanks for the contribution :tada: :clap:.
In order to get this merged quicker I went ahead and made a few minor additions:
* add `arn` attribute
* `tags` can be updated
* add `tags_all` attribute

**Comment by willvrny** [comment]
Ah thank you.

**Pull request merged**
