### PR TITLE
Cloudwatch EventRule to support partner eventbus names

### PR DESCRIPTION
**Pull request by gopiio**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestValidateCloudWatchEventRuleBusName -timeout 180m
=== RUN   TestValidateCloudWatchEventRuleBusName
--- PASS: TestValidateCloudWatchEventRuleBusName (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       3.408s
...
```
This is to support `CloudWatchEventRuleBusName`  pattern as defined in AWS docs: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-events-rule.html#cfn-events-rule-eventbusname

### CODE REVIEW

**Comment by ewbankkit** [comment]
@gopiio Thanks for the contribution 👏.

According to the [AWS API Reference](https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_PutRule.html#eventbridge-PutRule-request-EventBusName) the `event_bus_name` can be an ARN or an event bus name.
A better validator could be

```go
validation.Any(
    validateArn,
    validateCloudWatchEventBusName,
)
```

**Comment by ewbankkit** [comment]
Relates:

* https://github.com/hashicorp/terraform-provider-aws/pull/16815

**Comment by gopiio** [comment]
@ewbankkit Thank you for the suggestion.  Totalluy missed it :(.  I have pushed the changes.  Updated the test.
`make testacc TESTARGS='-run=TestValidateCloudWatchEventRuleBusName'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestValidateCloudWatchEventRuleBusName -timeout 180m
=== RUN   TestValidateCloudWatchEventRuleBusName
--- PASS: TestValidateCloudWatchEventRuleBusName (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       3.451s`

**Comment by gdavison** [comment]
Thanks for the PR, @gopiio. This same validation rule can be applied to all of the resources where `validateCloudWatchEventBusName` is currently used: `aws_cloudwatch_event_permission`, `aws_cloudwatch_event_rule`, and `aws_cloudwatch_event_target`.

I would suggest changing the definition of `validateCloudWatchEventBusName` to match your new validation rule, and possibly rename it to `validateCloudWatchEventBusNameOrARN` to correctly match the rule.

**Comment by gopiio** [comment]
@gdavison thanks for the suggestion.  My bad missed the target and permisson.  Updated and pushed.
` make testacc TESTARGS='-run=TestValidateCloudWatchEventBusNameOrARN'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestValidateCloudWatchEventBusNameOrARN -timeout 180m
=== RUN   TestValidateCloudWatchEventBusNameOrARN
--- PASS: TestValidateCloudWatchEventBusNameOrARN (0.00s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       3.621s`

**Comment by gopiio** [comment]
`awsproviderlint` error exist on `main` branch too.  
`make awsproviderlint
/tmp/terraform-provider-aws/aws/resource_aws_config_configuration_aggregator_test.go:209:36: XAT001: missing ErrorCheck
208
209		resource.ParallelTest(t, resource.TestCase{
210			PreCheck:     func() { testAccPreCheck(t) },
/tmp/terraform-provider-aws/aws/resource_aws_ecr_repository_policy_test.go:84:36: XAT001: missing ErrorCheck
83
84		resource.ParallelTest(t, resource.TestCase{
85			PreCheck:     func() { testAccPreCheck(t) },
/tmp/terraform-provider-aws/aws/resource_aws_ecr_repository_policy_test.go:105:36: XAT001: missing ErrorCheck
104
105		resource.ParallelTest(t, resource.TestCase{
106			PreCheck:     func() { testAccPreCheck(t) },
/tmp/terraform-provider-aws/aws/resource_aws_sns_topic_subscription_test.go:444:36: XAT001: missing ErrorCheck
443
444		resource.ParallelTest(t, resource.TestCase{
445			PreCheck:     func() { testAccPreCheck(t) },
/tmp/terraform-provider-aws/aws/resource_aws_sns_topic_subscription_test.go:466:36: XAT001: missing ErrorCheck
465
466		resource.ParallelTest(t, resource.TestCase{
467			PreCheck:     func() { testAccPreCheck(t) },
make: *** [awsproviderlint] Error 3`

Should I wait for it to be fixed on main branch? @gdavison

**Comment by gopiio** [comment]
ok, `awsproviderlint` is passing now.

**Review by gdavison — APPROVED** [review]
Looks good 🚀 

Acceptance test results

--- PASS: TestAccAWSCloudWatchEventRule_Name_Generated (67.96s)
--- PASS: TestAccAWSCloudWatchEventPermission_EventBusName (69.17s)
--- PASS: TestAccAWSCloudWatchEventRule_NamePrefix (70.11s)
--- PASS: TestAccAWSCloudWatchEventRule_ScheduleAndPattern (70.62s)
--- PASS: TestAccAWSCloudWatchEventRule_role (80.26s)
--- PASS: TestAccAWSCloudWatchEventPermission_Action (93.89s)
--- PASS: TestAccAWSCloudWatchEventTarget_RetryPolicy_DeadLetterConfig (103.28s)
--- PASS: TestAccAWSCloudWatchEventPermission_Multiple (104.95s)
--- PASS: TestAccAWSCloudWatchEventRule_pattern (110.96s)
--- PASS: TestAccAWSCloudWatchEventRule_description (112.87s)
--- PASS: TestAccAWSCloudWatchEventPermission_Condition (113.27s)
--- PASS: TestAccAWSCloudWatchEventTarget_disappears (53.15s)
--- FAIL: TestAccAWSCloudWatchEventTarget_ecsWithBlankTaskCount (67.49s)
--- PASS: TestAccAWSCloudWatchEventRule_IsEnabled (140.00s)
--- PASS: TestAccAWSCloudWatchEventRule_EventBusName (141.93s)
--- PASS: TestAccAWSCloudWatchEventRule_basic (142.76s)
--- PASS: TestAccAWSCloudWatchEventPermission_basic (149.49s)
--- PASS: TestAccAWSCloudWatchEventRule_tags (153.73s)
--- PASS: TestAccAWSCloudWatchEventTarget_inputTransformerJsonString (47.82s)
--- PASS: TestAccAWSCloudWatchEventPermission_Disappears (162.10s)

The failure in `TestAccAWSCloudWatchEventTarget_ecsWithBlankTaskCount` is unrelated

**Pull request merged**
