### PR TITLE
Add support for EFA enabled Lustre

### LINKED ISSUE #40381: FSx for Lustre file systems EFA support
> [Amazon FSx for Lustre](https://aws.amazon.com/fsx/lustre/), a service that provides high-performance, cost-effective, and scalable file storage for compute workloads, now supports Elastic Fabric Adapter (EFA) and NVIDIA GPUDirect Storage (GDS).

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-fsx-lustre-elastic-fabric-adapter-nvidia-gpudirect-storage/)
* [Blog post](https://aws.amazon.com/blogs/aws/amazon-fsx-for-lustre-unlocks-full-network-bandwidth-and-gpu-performance/)

Requires https://github.com/hashicorp/terraform-provider-aws/pull/40380.

### PR DESCRIPTION
**Pull request by SamuelDoud**
### Description

Adds EFA-enabled Lustre drives. This requires that the drive be `PERSISTENT_2` and have configured metadata IOPS. Also required is an [EFA enabled security group](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/efa-start.html#efa-start-security).

Per the [announcement](https://aws.amazon.com/blogs/aws/amazon-fsx-for-lustre-unlocks-full-network-bandwidth-and-gpu-performance/) adding this functionality.

When these conditions are met and `efa_enabled` is set to `true`, the drive will be created with this option in Terraform.

### Relations

Closes #40381

### Output from Acceptance Testing
This fails because the drive takes a significant amount of time to launch (this is often something we see in prod).
```console
samueldoud@samueldoud-mac terraform-provider-aws % make testacc TESTS=TestAccFSxLustreFileSystem_EfaEnabled  PKG=fsx
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestAccFSxLustreFileSystem_EfaEnabled'  -timeout 360m
2024/12/13 23:38:05 Initializing Terraform AWS Provider...
=== RUN   TestAccFSxLustreFileSystem_EfaEnabled
=== PAUSE TestAccFSxLustreFileSystem_EfaEnabled
=== CONT  TestAccFSxLustreFileSystem_EfaEnabled
    lustre_file_system_test.go:846: Step 1/3 error: Error running apply: exit status 1
        
        Error: waiting for FSx for Lustre File System (fs-0c051c2d216f6108a) create: couldn't find resource (21 retries)
        
          with aws_fsx_lustre_file_system.efa_enabled_lustre,
          on terraform_plugin_test.tf line 66, in resource "aws_fsx_lustre_file_system" "efa_enabled_lustre":
          66: resource "aws_fsx_lustre_file_system" "efa_enabled_lustre" {
        
--- FAIL: TestAccFSxLustreFileSystem_EfaEnabled (448.78s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/fsx        453.680s
FAIL
make: *** [testacc] Error 1
....
```
efa

This was eventually successfully created and deleted.

### CODE REVIEW

**Comment by SamuelDoud** [comment]
Tagging @ewbankkit since he is the original opener of this issue. Since we are locked in to having this or not, we need this functionality by the new year (or earlier) so we can begin testing this feature and deploy it.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccFSxLustreFileSystem_basic\|TestAccFSxLustreFileSystem_efaEnabled' PKG=fsx
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/fsx/... -v -count 1 -parallel 20  -run=TestAccFSxLustreFileSystem_basic\|TestAccFSxLustreFileSystem_efaEnabled -timeout 360m
2024/12/18 10:23:41 Initializing Terraform AWS Provider...
=== RUN   TestAccFSxLustreFileSystem_basic
=== PAUSE TestAccFSxLustreFileSystem_basic
=== RUN   TestAccFSxLustreFileSystem_efaEnabled
=== PAUSE TestAccFSxLustreFileSystem_efaEnabled
=== CONT  TestAccFSxLustreFileSystem_basic
=== CONT  TestAccFSxLustreFileSystem_efaEnabled
--- PASS: TestAccFSxLustreFileSystem_basic (1030.18s)
--- PASS: TestAccFSxLustreFileSystem_efaEnabled (1041.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	1047.370s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@SamuelDoud Thanks for the contribution :tada: :clap:.

**Comment by SamuelDoud** [comment]
Thanks for the quick review and getting this into the next release!

**Pull request merged**
