### PR TITLE
Fix static_ip_attachment attribute reference

### PR DESCRIPTION
**Pull request by a14m**
The `aws_lightsail_static_ip_attachment` doesn't expose the `
ip_address`, `support_code`, or `arn`

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Fix the documentation of `aws_lightsail_static_ip_attachment` resource (attribute reference)
```

### CODE REVIEW

**Comment by blckct** [comment]
Have you tried running `terraform show`? I can see those attributes when I run it.

**Comment by a14m** [comment]
No I haven't... but I got an error when I tried using them

here is the code

```
resource "aws_route53_record" "domain_name" {
  zone_id = var.hosted_zone_id
  type    = "A"
  name    = var.domain_name
  ttl     = "300"
  records = [aws_lightsail_static_ip_attachment.ip-attachment.ip_address]
}
```

and here is the error

```
Error: Unsupported attribute

  on ../../../modules/lightsail/main.tf line 28, in resource "aws_route53_record" "domain_name":
  28:   records = [aws_lightsail_static_ip_attachment.ip-attachment.ip_address]

This object has no argument, nested block, or exported attribute named
"ip_address".
```

**Comment by blckct** [comment]
You seem to have misread this line:

> The following attributes are exported in addition to the arguments listed above

That means those attributes are read-only and you can't specify them, they are generated automagically and you can read them and use elsewhere.

**Comment by a14m** [comment]
yeah true, I miss read the line, and I saw them when I ran `terraform show` but I wasn't able to use them (as shown in the attached example code/error)

**Comment by blckct** [comment]
Or maybe I misread it, it seems that static_ip has those not static_ip_attachment :/

**Comment by breathingdust** [comment]
Hi @a14m! 👋  Apologies for the long wait! It looks like another PR resolved the documentation error so closing this.

**Pull request closed without merging**
