### PR TITLE
tests/resource/sagemaker_endpoint: Make region agnostic

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #16061
Relates #12995 [Phase 2](https://github.com/hashicorp/terraform-provider-aws/issues/12995#issuecomment-730680494)

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

### Acceptance Tests in GovCloud (`us-gov-west-1`)

See #16632 for tracking the remaining issues.

```
    resource_aws_sagemaker_endpoint_test.go:125: Step 1/3 error: Error running pre-apply refresh: 
        Error: no registry ID available for region (us-gov-west-1) and repository (sagemaker-tensorflow-serving)
        
        
=== CONT  TestAccAWSSagemakerEndpoint_basic
    resource_aws_sagemaker_endpoint_test.go:64: Step 1/2 error: Error running pre-apply refresh: 
        Error: no registry ID available for region (us-gov-west-1) and repository (sagemaker-tensorflow-serving)
        
        
=== CONT  TestAccAWSSagemakerEndpoint_EndpointConfigName
    resource_aws_sagemaker_endpoint_test.go:93: Step 1/3 error: Error running pre-apply refresh: 
        Error: no registry ID available for region (us-gov-west-1) and repository (sagemaker-tensorflow-serving)
        
        
--- FAIL: TestAccAWSSagemakerEndpoint_Tags (4.29s)
--- FAIL: TestAccAWSSagemakerEndpoint_basic (4.34s)
--- FAIL: TestAccAWSSagemakerEndpoint_EndpointConfigName (4.34s)
```

### Acceptance Tests in `us-west-2`

```
--- PASS: TestAccAWSSagemakerEndpoint_basic (411.03s)
--- PASS: TestAccAWSSagemakerEndpoint_Tags (567.27s)
--- PASS: TestAccAWSSagemakerEndpoint_EndpointConfigName (997.87s)
```

### Acceptance Tests in `us-east-1`

(This would not have worked previously.)

```
--- PASS: TestAccAWSSagemakerEndpoint_basic (588.91s)
--- PASS: TestAccAWSSagemakerEndpoint_Tags (604.01s)
--- PASS: TestAccAWSSagemakerEndpoint_EndpointConfigName (1061.27s)
```

### CODE REVIEW

**Comment by YakDriver** [comment]
@DrFaust92 I updated these tests to use the `aws_sagemaker_prebuilt_ecr_image` data source. I also added TensorFlow serving as an option. Unfortunately, I haven't been able to find an image in GovCloud. We either need to find an image ID for GovCloud or switch this test to not use TensorFlow serving, which will require a new testing fixture. Any thoughts?

**Comment by DrFaust92** [comment]
I was tried to look for a solution but I can only say that we can change the test image to something that exists in gov and commercial regions. for example: `sagemaker-sparkml-serving:2.4` based on https://docs.aws.amazon.com/sagemaker/latest/dg/pre-built-docker-containers-scikit-learn-spark.html

**Comment by DrFaust92** [comment]
Also optionally move the error up and validate use ecr api as suggested in the article above:

```
 ecr describe-images \    
    --region ca-central-1 \
    --registry-id 341280168497 \
    --repository-name sagemaker-sparkml-serving
``` 

maybe via `data_source_aws_ecr_image` but it doesn't solve the root issue. it will just fail in a different place.

**Comment by YakDriver** [comment]
@DrFaust92 Do you know how the test model works? Can we get/make a new one for `sagemaker-sparkml-serving`?

The test references this `tar.gz`:
```
resource "aws_s3_bucket_object" "test" {
  bucket = aws_s3_bucket.test.id
  key    = "model.tar.gz"
  source = "test-fixtures/sagemaker-tensorflow-serving-test-model.tar.gz"
}
```

**Comment by YakDriver** [comment]
The test model data comes from here: https://github.com/aws/sagemaker-tensorflow-serving-container/tree/7d64ac5e2fe999cd76991e28557dd45abd2290fd/test/data

**Review by bflad — APPROVED** [review]
Looks good to me 🚀 

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSSageMakerPrebuiltECRImage_basic (21.15s)
--- PASS: TestAccAWSSageMakerPrebuiltECRImage_region (21.68s)

--- PASS: TestAccAWSSagemakerEndpoint_Tags (484.84s)
--- PASS: TestAccAWSSagemakerEndpoint_basic (526.63s)
--- PASS: TestAccAWSSagemakerEndpoint_EndpointConfigName (941.29s)
```

**Pull request merged**
