### PR TITLE
r/aws_apigatewayv2_domain_name: Support mutual TLS authentication

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/terraform-providers/terraform-provider-aws/issues/15220.
Relates #13527.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_apigatewayv2_domain_name: Add `mutual_tls_authentication` attribute to support mutual TLS authentication
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2DomainName_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2DomainName_basic
=== PAUSE TestAccAWSAPIGatewayV2DomainName_basic
=== RUN   TestAccAWSAPIGatewayV2DomainName_disappears
=== PAUSE TestAccAWSAPIGatewayV2DomainName_disappears
=== RUN   TestAccAWSAPIGatewayV2DomainName_Tags
=== PAUSE TestAccAWSAPIGatewayV2DomainName_Tags
=== RUN   TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== PAUSE TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== RUN   TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== PAUSE TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_basic
=== CONT  TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== CONT  TestAccAWSAPIGatewayV2DomainName_Tags
=== CONT  TestAccAWSAPIGatewayV2DomainName_disappears
=== CONT  TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
    resource_aws_apigatewayv2_domain_name_test.go:273: Step 1/3 error: terraform failed: exit status 1
        
        stderr:
        
        Error: error creating API Gateway v2 domain name: BadRequestException: The certificate provided must be issued by ACM and not imported. (Service: APIGateway; Status Code: 400; Error Code: BadRequestException; Request ID: TOopqAEdPHcEJsw=; Proxy: null)
        
        
--- FAIL: TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication (19.79s)
=== CONT  TestAccAWSAPIGatewayV2DomainName_disappears
    resource_aws_apigatewayv2_domain_name_test.go:115: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAWSAPIGatewayV2DomainName_disappears (25.41s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_basic (65.41s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_Tags (115.63s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_UpdateCertificate (392.86s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	393.417s
FAIL
GNUmakefile:27: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Investigating acceptance test failure...

**Comment by ewbankkit** [comment]
Mutual TLS requires that the API Gateway domain name be configured with an `Amazon Issued` ACM certificate.
To run the acceptance test specify the domain name of such a certificate:

```console
$ AWS_APIGATEWAYV2_CERTIFICATE_DOMAIN_NAME=<domain name> make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== PAUSE TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
--- PASS: TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication (109.89s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	109.939s
```

**Comment by ewbankkit** [comment]
Investigate creating public ACM certificates in acceptance tests: #16139, #16140.

**Comment by ewbankkit** [comment]
Rebased to remove merge conflict.
Refactored acceptance test to create a public ACM certificate (similar to #16139).

```console
$ ACM_CERTIFICATE_ROOT_DOMAIN=<domain name> make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2DomainName_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2DomainName_basic
=== PAUSE TestAccAWSAPIGatewayV2DomainName_basic
=== RUN   TestAccAWSAPIGatewayV2DomainName_disappears
=== PAUSE TestAccAWSAPIGatewayV2DomainName_disappears
=== RUN   TestAccAWSAPIGatewayV2DomainName_Tags
=== PAUSE TestAccAWSAPIGatewayV2DomainName_Tags
=== RUN   TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== PAUSE TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== RUN   TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== PAUSE TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_basic
=== CONT  TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== CONT  TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_Tags
=== CONT  TestAccAWSAPIGatewayV2DomainName_disappears
--- PASS: TestAccAWSAPIGatewayV2DomainName_disappears (22.46s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_Tags (83.52s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication (207.72s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_basic (240.48s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_UpdateCertificate (758.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	758.484s
```

**Review by DrFaust92 — APPROVED** [review]
LGTM (for what im able to test :D)

```
--- PASS: TestAccAWSAPIGatewayV2DomainName_disappears (83.31s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_Tags (143.04s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_basic (318.41s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_UpdateCertificate (547.88s)
```

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @ewbankkit 

Verified Acceptance Tests in Commercial (us-west-2)

```console
ACM_CERTIFICATE_ROOT_DOMAIN=terraform-provider-aws-acctest-acm.com make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2DomainName_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2DomainName_basic
=== PAUSE TestAccAWSAPIGatewayV2DomainName_basic
=== RUN   TestAccAWSAPIGatewayV2DomainName_disappears
=== PAUSE TestAccAWSAPIGatewayV2DomainName_disappears
=== RUN   TestAccAWSAPIGatewayV2DomainName_Tags
=== PAUSE TestAccAWSAPIGatewayV2DomainName_Tags
=== RUN   TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== PAUSE TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== RUN   TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== PAUSE TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_basic
=== CONT  TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== CONT  TestAccAWSAPIGatewayV2DomainName_disappears
=== CONT  TestAccAWSAPIGatewayV2DomainName_Tags
=== CONT  TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
--- PASS: TestAccAWSAPIGatewayV2DomainName_Tags (65.70s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_disappears (106.27s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication (256.00s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_UpdateCertificate (403.07s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_basic (527.07s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	529.209s
```

`TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication` test fails in GovCloud, ticket to track issue here #TBC

```console
ACM_CERTIFICATE_ROOT_DOMAIN=terraform-provider-aws-acctest-acm.com make testacc TEST=./aws TESTARGS='-run=TestAccAWSAPIGatewayV2DomainName_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2DomainName_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2DomainName_basic
=== PAUSE TestAccAWSAPIGatewayV2DomainName_basic
=== RUN   TestAccAWSAPIGatewayV2DomainName_disappears
=== PAUSE TestAccAWSAPIGatewayV2DomainName_disappears
=== RUN   TestAccAWSAPIGatewayV2DomainName_Tags
=== PAUSE TestAccAWSAPIGatewayV2DomainName_Tags
=== RUN   TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== PAUSE TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== RUN   TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== PAUSE TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
=== CONT  TestAccAWSAPIGatewayV2DomainName_basic
=== CONT  TestAccAWSAPIGatewayV2DomainName_UpdateCertificate
=== CONT  TestAccAWSAPIGatewayV2DomainName_Tags
=== CONT  TestAccAWSAPIGatewayV2DomainName_disappears
=== CONT  TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication
    resource_aws_apigatewayv2_domain_name_test.go:273: Step 1/4 error: Error running pre-apply refresh: 2020/12/01 10:54:22 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0

        Error: no matching Route53Zone found


--- FAIL: TestAccAWSAPIGatewayV2DomainName_MutualTlsAuthentication (2.30s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_disappears (18.60s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_basic (192.99s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_Tags (371.29s)
--- PASS: TestAccAWSAPIGatewayV2DomainName_UpdateCertificate (446.56s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	448.539s
FAIL
make: *** [testacc] Error 1
```

**Pull request merged**
