### PR TITLE
r/aws_db_instance: Fix error modifying `allocated_storage` when `storage_type` is `"gp3"`

### LINKED ISSUE #28160: [Bug]: With gp3 storage_type for aws_db_instance cannot increase storage with gp3, or change to gp3, with storage < 400GB
### Terraform Core Version

1.2.9

### AWS Provider Version

4.45.0

### Affected Resource(s)

aws_db_instance

### Expected Behavior

Should be able to make change to an RDS with gp3 storage (recently added) with < 400GB storage.

### Actual Behavior

If `iops` is not provided, the following error is thrown:

> api error InvalidParameterCombination: The storage type gp3 requires `iops` to be specified.

If the default 3000 IOPS for gp3 is provided in the `iops` attribute, but the storage size is smaller than 400GB, the following error is thrown:

> api error InvalidParameterCombination: You can't specify IOPS or storage throughput for engine postgres and a storage size less than 400.

Most interestingly, it's possible to create an RDS instance with gp3 and minimal storage (20GB) but increasing that (e.g. to 30GB) throws the above errors, and if the RDS already exists but with another storage type like gp2, it's not possible to upgrade to a gp3 in place.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files
```
terraform {
  # Note: this should match the version in `.tool-versions`
  required_version = "~> 1.2"

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.9"
    }
    random = {
      source  = "hashicorp/random"
      version = "~> 3.3"
    }
  }
}

provider "aws" {
}


resource "aws_vpc" "vpc" {
  cidr_block           = "10.0.0.0/16" 
  enable_dns_support   = true
  enable_dns_hostnames = true
}

resource "aws_subnet" "public_subnet1" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.0.1.0/24"
  availability_zone = "ap-southeast-2a" 
}
resource "aws_subnet" "public_subnet2" {
  vpc_id            = aws_vpc.vpc.id
  cidr_block        = "10.0.2.0/24"
  availability_zone = "ap-southeast-2b" 
}

resource "aws_db_subnet_group" "rds" {
  name       = "rds"
  subnet_ids = [aws_subnet.public_subnet1.id, aws_subnet.public_subnet2.id]
}

resource "aws_db_instance" "rds" {
  identifier     = "mydb"
  engine         = "postgres"
  engine_version = "14.5" 
  instance_class = "db.m6g.large"
  multi_az       = true
  storage_type   = "gp3"

  db_name  = "mydb"
  username = "myuser"
  password = "abcdefgh" 

  db_subnet_group_name = aws_db_subnet_group.rds.name
  apply_immediately    = true

  allocated_storage     = 20
  max_allocated_storage = 1000
  storage_encrypted     = true
  skip_final_snapshot   = true
}
```

### Steps to Reproduce

Create the resources as described , then change allocated_storage to a larger number and apply, observe the failures as noted in the Actual Behavior section.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

Relates https://github.com/hashicorp/terraform-provider-aws/issues/27702.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/27670.

https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/CHAP_Storage.html

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by ewbankkit**
### Description

Prevents errors like

```
 Error: updating RDS DB Instance (tf-acc-test-5977403606277891875): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: 6086d274-e75b-445c-afc5-8f6b14bbba02, api error InvalidParameterCombination: You can't specify IOPS or storage throughput for engine mysql and a storage size less than 400.
```

modifying `allocated_storage` when `storage_type` is `"gp3"` and `allocated_storage` is below a per-engine threshold.

### Relations

Closes #28160.

### Output from Acceptance Testing

```console
% make testacc TESTARGS='-run=TestAccRDSInstance_storageTypePostgres' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_storageTypePostgres -timeout 180m
=== RUN   TestAccRDSInstance_storageTypePostgres
=== PAUSE TestAccRDSInstance_storageTypePostgres
=== CONT  TestAccRDSInstance_storageTypePostgres
--- PASS: TestAccRDSInstance_storageTypePostgres (796.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	801.356s
% make testacc TESTARGS='-run=TestAccRDSInstance_gp3SQLServer' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_gp3SQLServer -timeout 180m
=== RUN   TestAccRDSInstance_gp3SQLServer
=== PAUSE TestAccRDSInstance_gp3SQLServer
=== CONT  TestAccRDSInstance_gp3SQLServer
--- PASS: TestAccRDSInstance_gp3SQLServer (1061.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	1066.408s

% make testacc TESTARGS='-run=TestAccRDSInstance_storageThroughput' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_storageThroughput -timeout 180m
=== RUN   TestAccRDSInstance_storageThroughput
=== PAUSE TestAccRDSInstance_storageThroughput
=== CONT  TestAccRDSInstance_storageThroughput
--- PASS: TestAccRDSInstance_storageThroughput (783.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	788.368s
% make testacc TESTARGS='-run=TestAccRDSInstance_gp3' PKG=rds ACCTEST_PARALLELISM=3     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_gp3 -timeout 180m
=== RUN   TestAccRDSInstance_gp3MySQL
=== PAUSE TestAccRDSInstance_gp3MySQL
=== RUN   TestAccRDSInstance_gp3Postgres
=== PAUSE TestAccRDSInstance_gp3Postgres
=== CONT  TestAccRDSInstance_gp3MySQL
=== CONT  TestAccRDSInstance_gp3Postgres
--- PASS: TestAccRDSInstance_gp3Postgres (693.72s)
--- PASS: TestAccRDSInstance_gp3MySQL (860.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	865.392s
% make testacc TESTARGS='-run=TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops\|TestAccRDSInstance_basic\|TestAccRDSInstance_ReplicateSourceDB_iops\|TestAccRDSInstance_SnapshotIdentifier_io1Storage' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops\|TestAccRDSInstance_basic\|TestAccRDSInstance_ReplicateSourceDB_iops\|TestAccRDSInstance_SnapshotIdentifier_io1Storage -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_ReplicateSourceDB_iops
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_iops
=== RUN   TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== RUN   TestAccRDSInstance_SnapshotIdentifier_io1Storage
=== PAUSE TestAccRDSInstance_SnapshotIdentifier_io1Storage
=== CONT  TestAccRDSInstance_basic
=== CONT  TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== CONT  TestAccRDSInstance_ReplicateSourceDB_iops
--- PASS: TestAccRDSInstance_basic (367.23s)
=== CONT  TestAccRDSInstance_SnapshotIdentifier_io1Storage
--- PASS: TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops (1467.13s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_iops (1548.51s)
--- PASS: TestAccRDSInstance_SnapshotIdentifier_io1Storage (1418.08s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	1790.471s
```

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
+ make testacc TESTARGS=-run=TestAccRDSInstance_gp3SQLServer PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_gp3SQLServer -timeout 180m
=== RUN   TestAccRDSInstance_gp3SQLServer
=== PAUSE TestAccRDSInstance_gp3SQLServer
=== CONT  TestAccRDSInstance_gp3SQLServer
--- PASS: TestAccRDSInstance_gp3SQLServer (1095.72s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        1098.790s
+ make testacc TESTARGS=-run=TestAccRDSInstance_storageThroughput PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_storageThroughput -timeout 180m
=== RUN   TestAccRDSInstance_storageThroughput
=== PAUSE TestAccRDSInstance_storageThroughput
=== CONT  TestAccRDSInstance_storageThroughput
--- PASS: TestAccRDSInstance_storageThroughput (732.48s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        735.380s
+ make testacc TESTARGS=-run=TestAccRDSInstance_gp3 PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_gp3 -timeout 180m
=== RUN   TestAccRDSInstance_gp3MySQL
=== PAUSE TestAccRDSInstance_gp3MySQL
=== RUN   TestAccRDSInstance_gp3Postgres
=== PAUSE TestAccRDSInstance_gp3Postgres
=== RUN   TestAccRDSInstance_gp3SQLServer
=== PAUSE TestAccRDSInstance_gp3SQLServer
=== CONT  TestAccRDSInstance_gp3MySQL
=== CONT  TestAccRDSInstance_gp3SQLServer
=== CONT  TestAccRDSInstance_gp3Postgres
--- PASS: TestAccRDSInstance_gp3Postgres (817.02s)
--- PASS: TestAccRDSInstance_gp3MySQL (832.30s)
--- PASS: TestAccRDSInstance_gp3SQLServer (1062.37s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        1065.288s
+ make testacc 'TESTARGS=-run=TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops\|TestAccRDSInstance_basic\|TestAccRDSInstance_ReplicateSourceDB_iops\|TestAccRDSInstance_SnapshotIdentifier_io1Storage' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops\|TestAccRDSInstance_basic\|TestAccRDSInstance_ReplicateSourceDB_iops\|TestAccRDSInstance_SnapshotIdentifier_io1Storage -timeout 180m
=== RUN   TestAccRDSInstance_basic
=== PAUSE TestAccRDSInstance_basic
=== RUN   TestAccRDSInstance_ReplicateSourceDB_iops
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_iops
=== RUN   TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== PAUSE TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== RUN   TestAccRDSInstance_SnapshotIdentifier_io1Storage
=== PAUSE TestAccRDSInstance_SnapshotIdentifier_io1Storage
=== CONT  TestAccRDSInstance_basic
=== CONT  TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops
=== CONT  TestAccRDSInstance_SnapshotIdentifier_io1Storage
--- PASS: TestAccRDSInstance_basic (530.24s)
=== CONT  TestAccRDSInstance_ReplicateSourceDB_iops
--- PASS: TestAccRDSInstance_SnapshotIdentifier_io1Storage (1301.87s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_allocatedStorageAndIops (1654.60s)
--- PASS: TestAccRDSInstance_ReplicateSourceDB_iops (1502.45s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        2035.613s
```

**Comment by etiennechabert** [comment]
@ewbankkit thanks again for your effort, I was able to switch my RDS instance from `gp2` to `gp3` thanks to this PR.

But my pipelines are now blocked from further applies, if I don't specify `iops`, see: https://github.com/hashicorp/terraform-provider-aws/issues/28271

**Comment by etiennechabert** [comment]
@cdl-danielchapman maybe you want to give a 👍 to this issue I created: https://github.com/hashicorp/terraform-provider-aws/issues/28271

Sounds like exactly the problem I am having ?

I like your proposal to have the provider setting the values by default based on what is documented regarding gp3

**Comment by cdl-danielchapman** [comment]
@etiennechabert  - done. Apologies I missed your earlier comment.

**Pull request merged**
