### PR TITLE
New resource: `aws_route53_cidr_collection` + support IP based routing

### LINKED ISSUE #25321: Add support for Route 53 IP Based Routing Policy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has introduced a new Route 53 IP Based Routing Policy, see: https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ip-based-routing-for-amazon-route-53/

It seems there is a pre-step to using it though. 
First you have to create a CIDR Collection, and associate some CIDRs with it
Then you can create a Route 53 record with a value for the above collection, and another value for '*'. 

### New or Affected Resource(s)

* aws_route53_record

### References

* https://aws.amazon.com/blogs/networking-and-content-delivery/introducing-ip-based-routing-for-amazon-route-53/
* https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/routing-policy-ipbased.html

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #25321

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=route53

...
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Still quite some work to be done here, putting the draft out already.

**Comment by bschaatsbergen** [comment]
On hold for a moment; checking together with @ewbankkit on how to nicely integrate this with the existing Route53 CidrCollection API.

**Comment by JoeAshworth** [comment]
Hey, how is progress going with this?

**Comment by bschaatsbergen** [comment]
Closing this PR, we can reopen it later..

**Comment by JoeAshworth** [comment]
So this is just being given up on?

**Comment by bschaatsbergen** [comment]
It's definitely not @JoeAshworth, we aim to pick this up whenever it lands on the roadmap. Feel free to take a stab at it if you like, I'm happy to help. The reason I didn't invest more time into the PR is because the API spec at the time was very poor, I haven't had time to revisit it yet.

**Comment by bschaatsbergen** [comment]
I'll revisit the API spec somewhere next week and get back to you.

**Pull request closed without merging**
