### PR TITLE
Fix typo in `aws_medialive_channel` documentation

### LINKED ISSUE #33407: [Docs]:
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel#input-loss-failover-settings

### Description

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel#input-loss-failover-settings

automatic_failover_conditions should be automatic_failover_condition

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #33550: [Bug]: Error creating aws_medialive_channel input attachment failover: setting AWS Elemental MediaLive Channel (*******): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}
### Terraform Core Version

1.5.7, 1.5.0

### AWS Provider Version

5.17.0, 5.16.0

### Affected Resource(s)

aws_medialive_channel

### Expected Behavior

Adding an `automatic_input_failover_settings` block should create an automatic failover with no errors

### Actual Behavior

`terraform apply` error out with error: 

`ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}`

Going over the UI. I can see that the failover condition was created, but created incorrectly. After the apply all terraform operations  (apply, plan, init, destroy) error out with the above error.

### Relevant Error/Panic Output Snippet

```shell
ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}
```

### Terraform Configuration Files
```tf
resource "aws_medialive_channel" "test_channel" {
  name          = "test_channel"
  channel_class = "SINGLE_PIPELINE"
  role_arn      = aws_iam_role.medialive_iam_role.arn
  tags = {

  }

  destinations {
    id = "dest-full"
    media_package_settings {
      channel_id = aws_media_package_channel.test_channel.id
    }
  }
  destinations {
    id = "dest-ambient"
    settings {
      password_param = aws_ssm_parameter.ssm_ambient.name
      url = aws_media_package_channel.test_channel_ambient.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_ambient.hls_ingest[0].ingest_endpoints[0].username
    }
  }
  destinations {
    id = "dest-pa"
    settings {
      password_param = aws_ssm_parameter.ssm_pa.name
      url = aws_media_package_channel.test_channel_pa.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_pa.hls_ingest[0].ingest_endpoints[0].username
    }
  }
  destinations {
    id = "dest-pa-ambient"
    settings {
      password_param = aws_ssm_parameter.ssm_pa_ambient.name
      url = aws_media_package_channel.test_channel_pa_ambient.hls_ingest[0].ingest_endpoints[0].url
      username = aws_media_package_channel.test_channel_pa_ambient.hls_ingest[0].ingest_endpoints[0].username
    }
  }


  input_specification {
    codec            = "HEVC"
    input_resolution = "HD"
    maximum_bitrate  = "MAX_20_MBPS"
  }

  # primary input
  input_attachments {
    input_attachment_name = "input_attachment"
    input_id              = aws_medialive_input.test_input.id
    automatic_input_failover_settings {
      secondary_input_id    = aws_medialive_input.test_input_b.id
      input_preference      = "PRIMARY_INPUT_PREFERRED"
      error_clear_time_msec = 30000
      failover_condition {
        failover_condition_settings {
          video_black_settings {
            black_detect_threshold = 0.5
            video_black_threshold_msec = 3000
          }
        }
      }
    } # input failover
   ... rest of attatchment
   }
   input_attachments {
    input_attachment_name = "test_input_attachment_b"
    input_id              = aws_medialive_input.test_input_b.id
   # no failover
   ... rest of attatchment
  }
```

### Steps to Reproduce

1. `terraform apply`
After the terraform apply, all main terraform operations (apply, plan, init, destroy) error out

### Debug Output

ERROR: setting AWS Elemental MediaLive Channel (*****): Invalid address to set: []string{"input_attachments", "1", "automatic_input_failover_settings", "0", "failover_conditions"}

### Panic Output

_No response_

### Important Factoids

The failover incorrectly gets created in my medialive channel as an input loss failover condition. Only way to resolve this is to manually disable the automatic failover in the AWS UI, and then remove the failover code from the IaC.

Additionally, I tried just enabling the automatic failover without any conditions:
```tf
automatic_input_failover_settings {
      secondary_input_id    = aws_medialive_input.input_example.id
      input_preference      = "PRIMARY_INPUT_PREFERRED"
      error_clear_time_msec = 3000
      }
} # input failover
```

Finally, the secondary input I am trying to failover is attached properly. If I take out the automatic failover, everything works as expected

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by justinretzolk**
### Description

This PR fixes a typo in the `aws_medialive_channel` documentation, so that the docs match the underlying schema.

> [!IMPORTANT]
> As called out in the [comments below](https://github.com/hashicorp/terraform-provider-aws/pull/33410#issuecomment-1714515719), the field in the SDK is actually `FailoverConditions`, as the docs currently list. If I'm not mistaken, making that change would be considered breaking, so I'm interested in input on which way to go with this.

### Relations

Closes #33407
Closes #33550

### References

[Schema](https://github.com/hashicorp/terraform-provider-aws/blob/73a8fec0016e086ea69d4823197f036a70ea5a05/internal/service/medialive/channel.go#L168)

### Output from Acceptance Testing

N/a, docs

### CODE REVIEW

**Comment by gbw** [comment]
Looks like the schema should be updated to match docs. https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/medialive/types#AutomaticInputFailoverSettings

**Comment by gbw** [comment]
Sounds good to me. Just for reference the flatten/expand for this type was only just added in 5.16.0.

**Review by jar-b — APPROVED** [review]
LGTM 👍 

For arguments which are arrays in the AWS API, but represented as blocks in the AWS Provider, we often adopt singular versions of the attribute name for improved readability. In this instance,

```hcl
resource "aws_medialive_channel" "example" {
  # this would be nested in a real configuration, but for simplicity is represented as a root argument here
  failover_condition {
    # condition 1
  }
  failover_condition {
    # condition 2  
  }
}
```

Reads slightly better than having multiple blocks titled `failure_conditions`

```hcl
resource "aws_medialive_channel" "example" {
  failover_conditions {
    # condition 1
  }
  failover_conditions {
    # condition 2  
  }
}
```

In this case my personal opinion is that the documentation update is sufficient.

**Comment by gbw** [comment]
Please update the other `failure_conditions` references in support of this change.

**Comment by gbw** [comment]
Thanks for the context @jar-b. I think this case is a little odd since within a failure conditions block multiple conditions can be set (i.e. audio, input, and/or video).

**Comment by evelynhathaway** [comment]
I don't think this is a typo in the documentation, or at least not only the documentation. The field doesn't work because half of the code uses the the old value and half uses the new value.

We've the opportunity to pick the pluralization that we want here since I don't think this field ever worked, so would not be a breaking change in my book.

See my comment on a related issue https://github.com/hashicorp/terraform-provider-aws/issues/33550#issuecomment-1728583383

**Review by gdavison — APPROVED** [review]

**Comment by gbw** [comment]
@justinretzolk could you add this [change](https://github.com/hashicorp/terraform-provider-aws/commit/6d77d2ee5f3ae72595723761c1d387042af5f702.diff) or would you prefer a separate pull request to fix?

**Comment by justinretzolk** [comment]
Hey @gbw @evelynhathaway 👋 Thank you for the additional input here! I've pushed additional changes to address those points as well.

**Pull request merged**
