### PR TITLE
r/aws_ecs_account_setting_default : Adds resource for default ECS account settings

### LINKED ISSUE #10168: Support for account settings flags
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are several new AWS features for ECS which depend on settings being enabled. I have a workaround for the default running local-exec but it'd be nice if there was a way to do this with the usual Terraform niceties such as change detection:

```hcl
resource "null_resource" "enable_new_ecs_features" {
  provisioner "local-exec" {
    command = <<EOF
aws ecs put-account-setting-default --name awsvpcTrunking --value enabled
aws ecs put-account-setting-default --name containerInstanceLongArnFormat --value enabled
aws ecs put-account-setting-default --name serviceLongArnFormat --value enabled
aws ecs put-account-setting-default --name taskLongArnFormat --value enabled
EOF
  }
}
```

### New or Affected Resource(s)

* PutAccountSettingDefault

### Potential Terraform Configuration

It'd be nice if something like this could work:

```hcl
resource "aws_ecs_account_setting_default" "vpc_trunking" {
   name = "awsvpcTrunking" 
   value = "enabled"
}
```

### References

* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_PutAccountSettingDefault.html
* https://docs.aws.amazon.com/cli/latest/reference/ecs/put-account-setting-default.html

### PR DESCRIPTION
**Pull request by robh007**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #10168

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adds new resource: aws_ecs_account_setting_default
```

Output from acceptance testing:

```
$make testacc TEST=./aws TESTARGS='-run=TestAccAWSEcsAccountDefaultSetting'
--- PASS: TestAccAWSEcsAccountDefaultSetting_serviceLongArnFormat (25.95s)
--- PASS: TestAccAWSEcsAccountDefaultSetting_containerInsights (26.28s)
--- PASS: TestAccAWSEcsAccountDefaultSetting_containerInstanceLongArnFormat (26.29s)
--- PASS: TestAccAWSEcsAccountDefaultSetting_awsvpcTrunking (26.29s)
--- PASS: TestAccAWSEcsAccountDefaultSetting_taskLongArnFormat (26.37s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       27.906s
...
```

### CODE REVIEW

**Comment by jayzalowitz** [comment]
I could in fact use this!

**Comment by e-moshaya** [comment]
Is there any way I could use this resource in our code from your branch? I can't find a way to use aws providers from git branches..Do we have to wait for this to get merged before we can adopt it?

**Comment by dennisroche** [comment]
Any reason why this can't be merged?

**Comment by ijin** [comment]
I need to enable Container Insights by default for ECS. Looking forward to have this merged!

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 Thanks for your work on this.

Output from acceptance tests (`us-west-2`):
```console
% make testacc TESTS=TestAccECSAccountSettingDefault_ PKG=ecs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSAccountSettingDefault_' -timeout 180m
--- PASS: TestAccECSAccountSettingDefault_taskLongARNFormat (14.02s)
--- PASS: TestAccECSAccountSettingDefault_serviceLongARNFormat (14.37s)
--- PASS: TestAccECSAccountSettingDefault_containerInstanceLongARNFormat (14.55s)
--- PASS: TestAccECSAccountSettingDefault_containerInsights (14.97s)
--- PASS: TestAccECSAccountSettingDefault_awsvpcTrunking (15.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	16.979s
```

Output from acceptance tests (GovCloud):
```console
% make testacc TESTS=TestAccECSAccountSettingDefault_ PKG=ecs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSAccountSettingDefault_' -timeout 180m
--- PASS: TestAccECSAccountSettingDefault_taskLongARNFormat (19.75s)
--- PASS: TestAccECSAccountSettingDefault_containerInstanceLongARNFormat (19.79s)
--- PASS: TestAccECSAccountSettingDefault_awsvpcTrunking (19.90s)
--- PASS: TestAccECSAccountSettingDefault_serviceLongARNFormat (19.90s)
--- PASS: TestAccECSAccountSettingDefault_containerInsights (21.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	22.346s
```

**Comment by ALLFIVE** [comment]
@YakDriver - sorry didn't see any of this. Put thanks for fixing it up...

**Pull request merged**
