### PR TITLE
Adding new resource aws_msk_cluster_policy

### LINKED ISSUE #31062: Amazon MSK multi-VPC private connectivity and cross-account access
Amazon MSK now offers multi-VPC private connectivity and cross-account access.

[Announcement](https://aws.amazon.com/about-aws/whats-new/2023/04/amazon-msk-multi-vpc-private-connectivity-cross-account-access/).
[Blog post](https://aws.amazon.com/blogs/big-data/connect-kafka-client-applications-securely-to-your-amazon-msk-cluster-from-different-vpcs-and-aws-accounts/).

#### New Resources

* `aws_msk_vpc_connection`
* `aws_msk_cluster_policy`

Requires [AWS SDK for Go v1.44.252](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.252): https://github.com/hashicorp/terraform-provider-aws/pull/31028.

### PR DESCRIPTION
**Pull request by nrajb**
### Description
Adds support for MSK Resource Policy

### Relations
Closes #31062.

### References
go reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/kafka
api reference: https://docs.aws.amazon.com/msk/1.0/apireference/clusters-clusterarn-policy.html

### Output from Acceptance Testing

```console
make testacc TESTARGS='-run=TestAccKafkaClusterPolicy_basic' PKG=kafka  ACCTEST_PARALLELISM=2                                       

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 2  -run=TestAccKafkaClusterPolicy_basic -timeout 180m
=== RUN   TestAccKafkaClusterPolicy_basic
=== PAUSE TestAccKafkaClusterPolicy_basic
=== CONT  TestAccKafkaClusterPolicy_basic
--- PASS: TestAccKafkaClusterPolicy_basic (41.25s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      44.285s

...
```

### CODE REVIEW

**Comment by nrajb** [comment]
@ewbankkit Happy to resubmit the PR with clean branch now that https://github.com/hashicorp/terraform-provider-aws/pull/32775 is merged, please let me know.. 🙏

**Comment by ewbankkit** [comment]
@nrajb Don't worry -- I'll do the merge tomorrow and push the branch.

**Comment by vishwa-trulioo** [comment]
Looking forward to the `aws_msk_cluster_policy` resource soon. You rock!

**Comment by ewbankkit** [comment]
```console
% make testacc TESTARGS='-run=TestAccKafkaClusterPolicy_' PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20  -run=TestAccKafkaClusterPolicy_ -timeout 180m
=== RUN   TestAccKafkaClusterPolicy_basic
=== PAUSE TestAccKafkaClusterPolicy_basic
=== RUN   TestAccKafkaClusterPolicy_disappears
=== PAUSE TestAccKafkaClusterPolicy_disappears
=== CONT  TestAccKafkaClusterPolicy_basic
=== CONT  TestAccKafkaClusterPolicy_disappears
=== NAME  TestAccKafkaClusterPolicy_basic
    cluster_policy_test.go:29: Step 1/2 error: Error running apply: exit status 1
        
        Error: setting MSK Cluster Policy (arn:aws:kafka:us-west-2:187416307283:cluster/tf-acc-test-5857099149822587167/ceefe3b8-6bfe-4ee2-8b15-d6dabb49c660-12): operation error Kafka: PutClusterPolicy, https response error StatusCode: 400, RequestID: da71570f-4bd1-436b-ac53-19def7536c45, BadRequestException: The cluster must have multi-VPC private connectivity enabled for its cluster policy.
        
          with aws_msk_cluster_policy.test,
          on terraform_plugin_test.tf line 62, in resource "aws_msk_cluster_policy" "test":
          62: resource "aws_msk_cluster_policy" "test" {
        
=== NAME  TestAccKafkaClusterPolicy_disappears
    cluster_policy_test.go:62: Step 1/1 error: Error running apply: exit status 1
        
        Error: setting MSK Cluster Policy (arn:aws:kafka:us-west-2:187416307283:cluster/tf-acc-test-2225640158714645767/eeaf73af-5bc9-4772-a3ba-654701643429-12): operation error Kafka: PutClusterPolicy, https response error StatusCode: 400, RequestID: 3397791b-439b-46a4-8fcf-d4735abd15f4, BadRequestException: The cluster must have multi-VPC private connectivity enabled for its cluster policy.
        
          with aws_msk_cluster_policy.test,
          on terraform_plugin_test.tf line 62, in resource "aws_msk_cluster_policy" "test":
          62: resource "aws_msk_cluster_policy" "test" {
        
--- FAIL: TestAccKafkaClusterPolicy_basic (2417.74s)
--- FAIL: TestAccKafkaClusterPolicy_disappears (2428.68s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	2434.239s
FAIL
make: *** [testacc] Error 1
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=360m make testacc TESTARGS='-run=TestAccKafkaClusterPolicy_' PKG=kafka ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 1  -run=TestAccKafkaClusterPolicy_ -timeout 360m
=== RUN   TestAccKafkaClusterPolicy_basic
=== PAUSE TestAccKafkaClusterPolicy_basic
=== RUN   TestAccKafkaClusterPolicy_disappears
=== PAUSE TestAccKafkaClusterPolicy_disappears
=== CONT  TestAccKafkaClusterPolicy_basic
--- PASS: TestAccKafkaClusterPolicy_basic (6802.15s)
=== CONT  TestAccKafkaClusterPolicy_disappears
--- PASS: TestAccKafkaClusterPolicy_disappears (6762.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	13844.376s
```

**Comment by ewbankkit** [comment]
@nrajb Thanks for the contribution :tada: :clap:.

**Pull request merged**
