### PR TITLE
Draft: Add Public IPv4 Pools data source

### PR DESCRIPTION
**Pull request by gatsbysghost**
### Description
Presently, there are some gaps in coverage relating to IPv4 Pools. #17425 raises the following user story (among others):

> As an IaC engineer, I want to be able to get a list of IPv4 address pools we've added to a specific AWS account via BYOIP so that we can utilise the ranges programatically in the remaining infrastructure.

This gap impacted my org as well (and I have seen several random users on various sites requesting this particular feature), which is why I am submitting this PR, in part-fulfillment of the needs of #17425.

This PR therefore adds the following items:
1. A new data source (located in the VPC section of the docs, but in the ec2 service directory) called `aws_vpc_public_ipv4_pools`
2. Tests and docs for the foregoing data source.

A substantial question in my mind when I was writing this code was: **does it go too far for a data source?** Most data sources that can read & provide data on a _range_ of resources only include, as output:
- The IDs of those resources
- An ID for the data source itself (generally, just a meta call back to the region).

This is obviously going a step further in providing structured output according to the [DescribePublicIpv4Pools](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/ec2#Client.DescribePublicIpv4Pools) API method. I would appreciate any feedback on whether or not that is, categorically, too much output to include in a Data Source. But on the other hand, users (including myself) have need of a method that simply takes one or more IPv4 pool IDs and returns information about those pools. This is how I chose to implement that, but I am open to requests for changes.

A further question I have for reviewers would be: Have I correctly inferred the error type for my Finder in `internal/service/ec2/find.go:1234`? I could not find much in the way of documentation about writing Finders in general.

Finally: I am working on acceptance testing, and this has Draft status until I get tests passing. However, due to the nature of this particular resource, it is quite difficult to run Acceptance Tests; we would need to be able to provision a BYOIP pool of public IPs (and this is kinda cost-prohibitive, as well as requiring a manual step to sign and attach a CIDR Authorization Context to the IPAM pool in order to create an IPAM pool CIDR. **Any input on how to test this in the existing framework...I am open to your thoughts.**

I should note here that **all existing tests for BYOIP AND all IPAM variations simply skip any kind of AccTest for public IPv4 addresses, for obvious reasons.** There's really nothing I can see in the existing framework to to pattern this approach off of, and I'm struggling to think how we would do this--apart from, e.g., spoofing the existence of public IPv4 pools in the tfstate.

### Relations
Relates #17425

### Output from Acceptance Testing
```
$ make testacc TESTS=TestAccVPCPublicIpv4PoolsDataSource PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCPublicIpv4PoolsDataSource'  -timeout 180m
=== RUN   TestAccVPCPublicIpv4PoolsDataSource_filter
    public_ipv4_pools_data_source_test.go:16: Step 1/1 error: Error running apply: exit status 1

        Error: creating IPAM Pool (ipam-pool-0bce7e0554f54c98c) CIDR: InvalidParameterCombination: The request must contain a CIDR Authorization Context for ipam-pool-0bce7e0554f54c98c. The specified pool belongs to a public scope where the specified CIDR has not previously been provisioned.
        	status code: 400, request id: 8805a3a8-9ed2-4ef6-a9df-ed6ffff12639

          with aws_vpc_ipam_pool_cidr.test_cidr_1,
          on terraform_plugin_test.tf line 29, in resource "aws_vpc_ipam_pool_cidr" "test_cidr_1":
          29: resource "aws_vpc_ipam_pool_cidr" "test_cidr_1" {


        Error: creating IPAM Pool (ipam-pool-0bce7e0554f54c98c) CIDR: InvalidParameterCombination: The request must contain a CIDR Authorization Context for ipam-pool-0bce7e0554f54c98c. The specified pool belongs to a public scope where the specified CIDR has not previously been provisioned.
        	status code: 400, request id: bf9f7023-9429-484a-a26d-f0630f4ef76e

          with aws_vpc_ipam_pool_cidr.test_cidr_2,
          on terraform_plugin_test.tf line 34, in resource "aws_vpc_ipam_pool_cidr" "test_cidr_2":
          34: resource "aws_vpc_ipam_pool_cidr" "test_cidr_2" {


        Error: creating IPAM Pool (ipam-pool-0c4c11e0a0f45f1be) CIDR: InvalidParameterCombination: The request must contain a CIDR Authorization Context for ipam-pool-0c4c11e0a0f45f1be. The specified pool belongs to a public scope where the specified CIDR has not previously been provisioned.
        	status code: 400, request id: 1de43236-1e53-43c5-bf9c-39c0ea701528

          with aws_vpc_ipam_pool_cidr.test_cidr_3,
          on terraform_plugin_test.tf line 39, in resource "aws_vpc_ipam_pool_cidr" "test_cidr_3":
          39: resource "aws_vpc_ipam_pool_cidr" "test_cidr_3" {


        Error: creating IPAM Pool (ipam-pool-0c4c11e0a0f45f1be) CIDR: InvalidParameterCombination: The request must contain a CIDR Authorization Context for ipam-pool-0c4c11e0a0f45f1be. The specified pool belongs to a public scope where the specified CIDR has not previously been provisioned.
        	status code: 400, request id: 6a99e112-ee23-46e4-9d4b-9a47df84b42f

          with aws_vpc_ipam_pool_cidr.test_cidr_4,
          on terraform_plugin_test.tf line 44, in resource "aws_vpc_ipam_pool_cidr" "test_cidr_4":
          44: resource "aws_vpc_ipam_pool_cidr" "test_cidr_4" {

--- FAIL: TestAccVPCPublicIpv4PoolsDataSource_filter (73.49s)
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@gatsbysghost Drive-by review comment: I suggest adding another, singular, data source `aws_vpc_public_ipv4_pool` that returns the properties that you have in the `pools` map in the `aws_vpc_public_ipv4_pools` data source. That is our standard pattern and there seems to be nothing special about this resource type to consider an exception.
Thanks.

**Comment by gatsbysghost** [comment]
> @gatsbysghost Drive-by review comment: I suggest adding another, singular, data source `aws_vpc_public_ipv4_pool` that returns the properties that you have in the `pools` map in the `aws_vpc_public_ipv4_pools` data source. That is our standard pattern and there seems to be nothing special about this resource type to consider an exception. Thanks.

@ewbankkit I have integrated the singular data source in my last 2 patches; thank you so much for the feedback! :)

Do you have any thoughts on the best way to test this, given the problem of the resource requiring an IPv4 block from ARIN to test?

Should I perhaps do something in the style of [ipam_byoip_test.go](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ec2/ipam_byoip_test.go)? I'm afraid that, as an individual, I don't have the ability to reserve IP addresses from ARIN in order to test this myself, so I'm really in a pickle on testing strategy here.

**Comment by ewbankkit** [comment]
@gatsbysghost The HashiCorp maintainers don't have access to BYOIP functionality so in such cases we will:

1. Make sure that if the changes affect other resources, ensure there are no regressions
2. Do a code review
3. Solicit the community for testing
4. Release the functionality "as-is" (with text in the release notes) and encourage practitioner feedback

**Comment by gatsbysghost** [comment]
@ewbankkit ah--that makes sense 😄  In that case, should I remove my testfiles?

I believe I can patch this change into my corpo terraform for a pretty basic field test, if we get it past the CR stage.

**Comment by gatsbysghost** [comment]
Oh, and should I strike "Draft:" from the title when it's ready for CR?

**Comment by gatsbysghost** [comment]
Sorry, created a small gitastrophe trying to rebase.

**Comment by gatsbysghost** [comment]
Honestly not worth it to fix this branch, I'm just going to kill it & start a new one. Sorry for being a doofus with git!

**Pull request closed without merging**
