### PR TITLE
[New Resource] TimestreamInfluxDB DB Instance

### LINKED ISSUE #36398: [Enhancement]: Support Timestream for InfluxDB
### Description

It's now possible to select a different engine for a Timestream database in the aws console. The previous engine is now called LiveAnalytics and a new engine was added called InfluxDB. Terraform has no support for the InfluxDB engine or for its configuration options.

If you plan to add the new engine as an option to the pre existing aws_timestreamwrite_database you could just add new parameters for it as shown in the example. At least the parameter group needs its own new resource. 

Not much is shared between the engines so maybe a whole new resource for InfluxDB type Timestream would be better. For example the RDS resource handles engine types all in the same resource but RDS engine types at least share some configuration options between them as opposed to Timestream for LiveAnalytics vs InfluxDB.

### Affected Resource(s) and/or Data Source(s)

* `aws_timestreamwrite_database`

### Potential Terraform Configuration

```terraform
resource "aws_timestreamwrite_database" "example" {
  database_name = "database-example"
  engine        = "influxdb"

  db_name           = "db-name-example"
  username          = "example-username"
  password          = "example-password"
  organization_name = "example-org"
  bucket_name       = "example-bucket"

  instance_class    = "db.influx.medium"
  storage_type      = "included-3000"
  allocated_storage = 200
  multi_az          = true

  db_subnet_group_name   = aws_db_subnet_group.example.name
  vpc_security_group_ids = [aws_security_group.example.id]
  publicly_accessible    = false

  parameter_group_name = aws_timestreamwrite_parametergroup.example.name
  s3_logs_location     = aws_s3_bucket.example.id

  tags = {
    Name = "value"
  }
}

resource "aws_timestreamwrite_parametergroup" "example" {
  name        = "example-name"
  description = "example-description"

  parameter {
    name  = "flux-log-enabled"
    value = "TRUE"
  }

  parameter {
    name  = "log-level"
    value = "error"
  }

  tags = {
    Name = "value"
  }

}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/03/amazon-timestream-influxdb-available/)
* [Blog post](https://aws.amazon.com/blogs/aws/run-and-manage-open-source-influxdb-databases-with-amazon-timestream/)
* [Developer Guide](https://docs.aws.amazon.com/timestream/latest/developerguide/timestream-for-influx-configuring.html#timestream-for-influx-configuring-create-db-settings)
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/timestreamwrite_database

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by trevorbonas**
### Description

- `aws_timestreaminfluxdb_db_instance` resource added.
- Acceptance tests added for `aws_timestreaminfluxdb_db_instance`.
- Sweeper added for `aws_timestreaminfluxdb_db_instance`.
- Website documentation added for `aws_timestreaminfluxdb_db_instance`.

### Relations

Closes #36398

### References

TimestreamInfluxDB AWS SDK Go v2 package: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/timestreaminfluxdb@v1.0.5#pkg-index

Timestream for InfluxDB documentation: https://docs.aws.amazon.com/timestream/latest/developerguide/timestream-for-influxdb.html

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccTimestreamInfluxDBDBInstance PKG=timestreaminfluxdb ACCTEST_PARALLELISM=1
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/timestreaminfluxdb/... -v -count 1 -parallel 1 -run='TestAccTimestreamInfluxDBDBInstance'  -timeout 360m
=== RUN   TestAccTimestreamInfluxDBDBInstance_basic
=== PAUSE TestAccTimestreamInfluxDBDBInstance_basic
=== RUN   TestAccTimestreamInfluxDBDBInstance_disappears
=== PAUSE TestAccTimestreamInfluxDBDBInstance_disappears
=== RUN   TestAccTimestreamInfluxDBDBInstance_logDeliveryConfiguration
=== PAUSE TestAccTimestreamInfluxDBDBInstance_logDeliveryConfiguration
=== RUN   TestAccTimestreamInfluxDBDBInstance_publiclyAccessible
=== PAUSE TestAccTimestreamInfluxDBDBInstance_publiclyAccessible
=== RUN   TestAccTimestreamInfluxDBDBInstance_deploymentTypeMultiAzStandby
=== PAUSE TestAccTimestreamInfluxDBDBInstance_deploymentTypeMultiAzStandby
=== RUN   TestAccTimestreamInfluxDBDBInstance_username
=== PAUSE TestAccTimestreamInfluxDBDBInstance_username
=== RUN   TestAccTimestreamInfluxDBDBInstance_bucket
=== PAUSE TestAccTimestreamInfluxDBDBInstance_bucket
=== RUN   TestAccTimestreamInfluxDBDBInstance_organization
=== PAUSE TestAccTimestreamInfluxDBDBInstance_organization
=== RUN   TestAccTimestreamInfluxDBDBInstance_tags
=== PAUSE TestAccTimestreamInfluxDBDBInstance_tags
=== RUN   TestAccTimestreamInfluxDBDBInstance_dbInstanceType
=== PAUSE TestAccTimestreamInfluxDBDBInstance_dbInstanceType
=== RUN   TestAccTimestreamInfluxDBDBInstance_dbStorageType
=== PAUSE TestAccTimestreamInfluxDBDBInstance_dbStorageType
=== CONT  TestAccTimestreamInfluxDBDBInstance_basic
--- PASS: TestAccTimestreamInfluxDBDBInstance_basic (960.79s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_bucket
--- PASS: TestAccTimestreamInfluxDBDBInstance_bucket (826.30s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_dbStorageType
--- PASS: TestAccTimestreamInfluxDBDBInstance_dbStorageType (1692.93s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_dbInstanceType
--- PASS: TestAccTimestreamInfluxDBDBInstance_dbInstanceType (5692.87s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_tags
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags (849.57s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_organization
--- PASS: TestAccTimestreamInfluxDBDBInstance_organization (855.72s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_publiclyAccessible
--- PASS: TestAccTimestreamInfluxDBDBInstance_publiclyAccessible (956.25s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_username
--- PASS: TestAccTimestreamInfluxDBDBInstance_username (917.59s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_deploymentTypeMultiAzStandby
--- PASS: TestAccTimestreamInfluxDBDBInstance_deploymentTypeMultiAzStandby (1220.48s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_logDeliveryConfiguration
--- PASS: TestAccTimestreamInfluxDBDBInstance_logDeliveryConfiguration (977.41s)
=== CONT  TestAccTimestreamInfluxDBDBInstance_disappears
--- PASS: TestAccTimestreamInfluxDBDBInstance_disappears (904.06s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/timestreaminfluxdb 15858.121s
```

### CODE REVIEW

**Comment by trevorbonas** [comment]
I am currently working on fixing all failing checks.

**Comment by trevorbonas** [comment]
I have addressed all failing checks. I have updated the output of the acceptance tests after the latest changes. This PR is ready for review.

**Comment by Sharu95** [comment]
Hi! Are there any updates on this PR? 😄

**Comment by AlexandrSher** [comment]
@hc-github-team-terraform-aws Hi! any updates?

**Comment by mfoti** [comment]
Hi all, this could be merged?

**Comment by trevorbonas** [comment]
This PR is complete and needs assistance to review and merge.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 


```console
% make testacc TESTARGS="-run=TestAccTimestreamInfluxDBDBInstance_" PKG=timestreaminfluxdb ACCTEST_PARALLELISM=3

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/timestreaminfluxdb/... -v -count 1 -parallel 3  -run=TestAccTimestreamInfluxDBDBInstance_ -timeout 360m
    db_instance_tags_gen_test.go:204: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccTimestreamInfluxDBDBInstance_tags_null (0.00s)
    db_instance_tags_gen_test.go:1523: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_nullOverlappingResourceTag (0.00s)
    db_instance_tags_gen_test.go:1590: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_nullNonOverlappingResourceTag (0.00s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_providerOnly (878.56s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags (882.29s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_emptyResourceTag (991.37s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_updateToProviderOnly (609.35s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_updateToResourceOnly (1349.81s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_EmptyTag_OnUpdate_Add (1936.40s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_EmptyTag_OnUpdate_Replace (1862.04s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_basic (1892.17s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_deploymentTypeMultiAzStandby (1692.02s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_publiclyAccessible (557.90s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_overlapping (2206.01s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_logDeliveryConfiguration (1496.61s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_disappears (753.26s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_ComputedTag_OnUpdate_Add (661.75s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_nonOverlapping (2319.23s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_ComputedTag_OnUpdate_Replace (845.38s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_ComputedTag_OnCreate (970.87s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_EmptyTag_OnCreate (2264.00s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_AddOnUpdate (799.56s)
--- PASS: TestAccTimestreamInfluxDBDBInstance_tags_DefaultTags_emptyProviderOnlyTag (1904.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/timestreaminfluxdb	9596.592s
```

**Comment by johnsonaj** [comment]
@trevorbonas thank you for the contribution! 🎉

**Pull request merged**
