### PR TITLE
[New Resource] DMS Serverless Replication resource

### LINKED ISSUE #32920: [New]: Need DMS Serverless Replication
### Description

AWS has introduce DMS Serverless Replication, currently we are unable to terraform the serverless.

### Requested Resource(s) and/or Data Source(s)

aws_dms_serverless_replication

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by DanielRieske**
### Description

This PR adds the `aws_dms_serverless_replication` resource.

This resource is a serverless option in DMS that automatically sets up, scales, and manages the migration of resources for your database migrations.

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/32162
Closes #32920

### Output from Acceptance Testing

```console
terraform-provider-aws git:(f-aws_dms_serverless_replication_resource) ✗ make testacc TESTS=TestAccDMSServerlessReplication_ PKG=dms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSServerlessReplication_'  -timeout 180m
=== RUN   TestAccDMSServerlessReplication_basic
=== PAUSE TestAccDMSServerlessReplication_basic
=== RUN   TestAccDMSServerlessReplication_update
=== PAUSE TestAccDMSServerlessReplication_update
=== RUN   TestAccDMSServerlessReplication_startReplication
=== PAUSE TestAccDMSServerlessReplication_startReplication
=== CONT  TestAccDMSServerlessReplication_basic
=== CONT  TestAccDMSServerlessReplication_startReplication
=== CONT  TestAccDMSServerlessReplication_update
--- PASS: TestAccDMSServerlessReplication_basic (1493.10s)
--- PASS: TestAccDMSServerlessReplication_update (1504.35s)
--- PASS: TestAccDMSServerlessReplication_startReplication (3114.44s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        3116.427s

...
```

### CODE REVIEW

**Comment by csbain** [comment]
Hi @DanielRieske  I was really wanting to test this MR (i.e. get early access) , could you possibly point me to any instructions on compiling and using this within terraform?

cheers

**Comment by DanielRieske** [comment]
Hiya @csbain 👋 , you should be able to clone my fork and checkout the branch.
From there on you can follow these [instructions](https://hashicorp.github.io/terraform-provider-aws/development-environment/) to build and test it.

Keep in mind that this isn't final and might be changed during code review.

**Comment by bschaatsbergen** [comment]
It's impressive to see your involvement in this 👏🏼 , @DanielRieske. Since we are direct colleagues, I'm more than willing to provide feedback, but I would recommend having someone like @ewbankkit formally review and approve this.

**Comment by Oden-Allfader** [comment]
Hi @DanielRieske ! 
Thank you for picking up my issue! Great job 🙏 
Any idea of ETA when this would be released? 
Much appreciated !

**Comment by DanielRieske** [comment]
Hiya @Oden-Allfader :wave:, loved working on the issue so not a problem at all.
Regarding the timeline, this is unfortunately not something I can estimate.

These contributions are reviewed based [among factors](https://hashicorp.github.io/terraform-provider-aws/prioritization/) like community response, etc.

The maintainers are working hard on the background on many other features that right now got a higher priority than this one.
All we can do is add an 👍 to the original post and wait till it gets reviewed.

**Comment by ewbankkit** [comment]
@DanielRieske Thanks for the contribution :tada: :clap:.
I have renamed the new resource to `aws_dms_replication_config` to match the underlying [AWS API](https://docs.aws.amazon.com/dms/latest/APIReference/API_ReplicationConfig.html).
In general everything looks great -- I just want to add a few more acceptance tests before merging.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccDMSReplicationConfig_disappears\|TestAccDMSReplicationConfig_tags' PKG=dms ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 2  -run=TestAccDMSReplicationConfig_disappears\|TestAccDMSReplicationConfig_tags -timeout 360m
=== RUN   TestAccDMSReplicationConfig_disappears
=== PAUSE TestAccDMSReplicationConfig_disappears
=== RUN   TestAccDMSReplicationConfig_tags
=== PAUSE TestAccDMSReplicationConfig_tags
=== CONT  TestAccDMSReplicationConfig_disappears
=== CONT  TestAccDMSReplicationConfig_tags
--- PASS: TestAccDMSReplicationConfig_tags (1644.31s)
--- PASS: TestAccDMSReplicationConfig_disappears (1599.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	1687.788s
```
```console
% make testacc TESTARGS='-run=TestAccDMSReplicationConfig_basic\|TestAccDMSReplicationConfig_update\|TestAccDMSReplicationConfig_startReplication' PKG=dms ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 2  -run=TestAccDMSReplicationConfig_basic\|TestAccDMSReplicationConfig_update\|TestAccDMSReplicationConfig_startReplication -timeout 360m
=== RUN   TestAccDMSReplicationConfig_basic
=== PAUSE TestAccDMSReplicationConfig_basic
=== RUN   TestAccDMSReplicationConfig_update
=== PAUSE TestAccDMSReplicationConfig_update
=== RUN   TestAccDMSReplicationConfig_startReplication
=== PAUSE TestAccDMSReplicationConfig_startReplication
=== CONT  TestAccDMSReplicationConfig_basic
=== CONT  TestAccDMSReplicationConfig_startReplication
--- PASS: TestAccDMSReplicationConfig_basic (1503.43s)
=== CONT  TestAccDMSReplicationConfig_update
--- PASS: TestAccDMSReplicationConfig_startReplication (3061.71s)
--- PASS: TestAccDMSReplicationConfig_update (1562.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	3097.219s
```

**Comment by tim-mcmurray** [comment]
I see this was completed. Was the registry documentation updated for this provider on the Terraform website?

**Comment by ewbankkit** [comment]
Will be [released](https://hashicorp.github.io/terraform-provider-aws/faq/#how-often-do-you-release) tomorrow, September 28th in Terraform AWS Provider **v5.19.0**. Registry documentation is updated as part of the release.

**Pull request merged**
