### PR TITLE
docs: Refer to AWS doc for allocation_strategy valid values for aws_batch_compute_environment

### LINKED ISSUE #36040: [Docs]: SPOT_PRICE_CAPACITY_OPTIMIZED value for aws_batch_compute_environment's compute resources
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/batch_compute_environment

### Description

Add value `SPOT_PRICE_CAPACITY_OPTIMIZED` for aws_batch_compute_environment

Since August 2023, AWS Batch supports the price-capacity optimized allocation strategy for Spot Instances. This feature was also released in AWS Go SDK v1.44.314. 

### References

aws-sdk-go release note: https://github.com/aws/aws-sdk-go/releases/tag/v1.44.314

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by acwwat**
### Description

This PR provides a link to the AWS documentation for the full list of valid values for the `allocation_strategy` argument of the for the `aws_batch_compute_environment` resource, following recent documentation conventions to avoid constant updates to new values.

### Relations

Closes #36040

### References

Referred to [ComputeResource](https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeResource.html#Batch-Type-ComputeResource-allocationStrategy) in the API reference.

### Output from Acceptance Testing

n/a

### CODE REVIEW

**Comment by chinh-pd** [comment]
@acwwat The latest version of Terraform still using [aws-sdk-go v1.44.122](https://github.com/hashicorp/terraform/blob/main/go.mod) which not support `SPOT_PRICE_CAPACITY_OPTIMIZED` value (support from v1.44.314)

**Review by jar-b — APPROVED** [review]
LGTM 👍

**Comment by jar-b** [comment]
Thanks for your contribution, @acwwat! 👍

**Comment by acwwat** [comment]
@chinh-pd I believe the link you referred to is for Terraform itself. The version used by the Terraform AWS Provider is[ v1.50.28](https://github.com/hashicorp/terraform-provider-aws/blob/b0a56462c40a1c59dd3442fb8fe498d00f9b1990/go.mod#L9).

**Pull request merged**
