### PR TITLE
aws_ec2_fleet: support in-place update of launch template config

### LINKED ISSUE #14946: r/aws_ec2_fleet: Support in-place update of instance types and weights
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

You now have an option to modify instance types and weights for a running EC2 Fleet or Spot Fleet.

### New or Affected Resource(s)

* [`aws_ec2_fleet`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ec2_fleet)

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-ec2-spot-fleet-support-modifying-instance-types-weights-on-run/).
[API Reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_ModifyFleet.html).

Requires [AWS SDK v1.34.14](https://github.com/aws/aws-sdk-go/releases/tag/v1.34.14):

* https://github.com/terraform-providers/terraform-provider-aws/pull/14936

### PR DESCRIPTION
**Pull request by idubinskiy**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14946

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws_ec2_fleet: Support in-place update of Launch Template config
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSEc2Fleet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEc2Fleet -timeout 120m
=== RUN   TestAccAWSEc2Fleet_basic
=== PAUSE TestAccAWSEc2Fleet_basic
=== RUN   TestAccAWSEc2Fleet_disappears
=== PAUSE TestAccAWSEc2Fleet_disappears
=== RUN   TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy
=== PAUSE TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_MaxPrice
    provider_test.go:31: EC2 API is not correctly returning MaxPrice override
--- SKIP: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_MaxPrice (0.00s)
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
=== RUN   TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
=== PAUSE TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
=== RUN   TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy
=== PAUSE TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy
=== RUN   TestAccAWSEc2Fleet_ReplaceUnhealthyInstances
=== PAUSE TestAccAWSEc2Fleet_ReplaceUnhealthyInstances
=== RUN   TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy
=== PAUSE TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy
=== RUN   TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior
=== PAUSE TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior
=== RUN   TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount
=== PAUSE TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount
=== RUN   TestAccAWSEc2Fleet_Tags
=== PAUSE TestAccAWSEc2Fleet_Tags
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot
=== RUN   TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity
=== PAUSE TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity
=== RUN   TestAccAWSEc2Fleet_TerminateInstancesWithExpiration
=== PAUSE TestAccAWSEc2Fleet_TerminateInstancesWithExpiration
=== RUN   TestAccAWSEc2Fleet_Type
=== PAUSE TestAccAWSEc2Fleet_Type
=== RUN   TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces
=== PAUSE TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces
=== CONT  TestAccAWSEc2Fleet_basic
=== CONT  TestAccAWSEc2Fleet_ReplaceUnhealthyInstances
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType
=== CONT  TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType
=== CONT  TestAccAWSEc2Fleet_Tags
=== CONT  TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount
=== CONT  TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity
=== CONT  TestAccAWSEc2Fleet_TerminateInstancesWithExpiration
=== CONT  TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity
=== CONT  TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy
=== CONT  TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot
=== CONT  TestAccAWSEc2Fleet_Type
2020/09/29 00:58:51 [DEBUG] Reading EC2 Fleet (fleet-ac7c2d49-8903-4e20-8987-859b9b112ba0): {
  FleetIds: ["fleet-ac7c2d49-8903-4e20-8987-859b9b112ba0"]
}
2020/09/29 00:59:09 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2020/09/29 00:59:18 [DEBUG] Reading EC2 Fleet (fleet-17a8ad49-4cb1-4e14-a363-8c0c9b664ced): {
  FleetIds: ["fleet-17a8ad49-4cb1-4e14-a363-8c0c9b664ced"]
}
2020/09/29 00:59:57 [DEBUG] Trying to get account information via sts:GetCallerIdentity
--- PASS: TestAccAWSEc2Fleet_Type (144.73s)
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone
--- PASS: TestAccAWSEc2Fleet_basic (147.58s)
=== CONT  TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_OnDemand (147.60s)
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType_Spot (148.93s)
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version
2020/09/29 01:00:28 [DEBUG] aws_ami - adding block device mapping: map[device_name:/dev/xvda ebs:map[delete_on_termination:true encrypted:false iops:0 snapshot_id:snap-039944fa8c365b7e1 volume_size:8 volume_type:gp2] virtual_name:]
2020/09/29 01:00:32 [TRACE] Waiting 800ms before next try
2020/09/29 01:01:14 [DEBUG] Reading EC2 Fleet (fleet-bd602444-327c-4004-8bd0-c2296908fe5a): {
  FleetIds: ["fleet-bd602444-327c-4004-8bd0-c2296908fe5a"]
}
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_DefaultTargetCapacityType (208.63s)
=== CONT  TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName
2020/09/29 01:01:26 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2020/09/29 01:01:39 [DEBUG] Reading launch template lt-0d2777ea1846eabd9
--- PASS: TestAccAWSEc2Fleet_ReplaceUnhealthyInstances (233.23s)
=== CONT  TestAccAWSEc2Fleet_disappears
--- PASS: TestAccAWSEc2Fleet_OnDemandOptions_AllocationStrategy (233.83s)
2020/09/29 01:01:51 [DEBUG] Deleting EC2 Fleet (fleet-ac7c2d49-8903-4e20-8987-859b9b112ba0): {
  FleetIds: ["fleet-ac7c2d49-8903-4e20-8987-859b9b112ba0"],
  TerminateInstances: false
}
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity_Multiple (238.26s)
--- PASS: TestAccAWSEc2Fleet_Tags (240.06s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority_Multiple (240.54s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_Priority (240.64s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_InstanceType (241.13s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_WeightedCapacity (241.29s)
--- PASS: TestAccAWSEc2Fleet_SpotOptions_AllocationStrategy (242.06s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_SubnetId (242.68s)
--- PASS: TestAccAWSEc2Fleet_SpotOptions_InstanceInterruptionBehavior (244.59s)
--- PASS: TestAccAWSEc2Fleet_SpotOptions_InstancePoolsToUseCount (246.12s)
--- PASS: TestAccAWSEc2Fleet_TerminateInstancesWithExpiration (260.78s)
=== CONT  TestAccAWSEc2Fleet_disappears
    resource_aws_ec2_fleet_test.go:69: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAWSEc2Fleet_disappears (66.21s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_Override_AvailabilityZone (190.35s)
--- PASS: TestAccAWSEc2Fleet_ExcessCapacityTerminationPolicy (187.50s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateId (187.89s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_Version (188.86s)
--- PASS: TestAccAWSEc2Fleet_LaunchTemplateConfig_LaunchTemplateSpecification_LaunchTemplateName (138.90s)
--- PASS: TestAccAWSEc2Fleet_TemplateMultipleNetworkInterfaces (616.86s)
--- PASS: TestAccAWSEc2Fleet_TargetCapacitySpecification_TotalTargetCapacity (643.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	647.230s
```

### CODE REVIEW

**Comment by idubinskiy** [comment]
Any chance of this getting a look anytime soon? I know there's quite a backlog of PRs, but I see quite a few things being merged most days and this one is fairly minimal as far as resource changes go. My team has had to do do this kind of modification pretty often the last couple of months, and it's a bit difficult to manage a custom build of an official provider across multiple users and modules.

@bflad @ewbankkit @gdavison @YakDriver

**Comment by idubinskiy** [comment]
Hopefully a check-in after three months isn't too much noise. Managing a custom version of the provider, especially rebuilding to keep up with upstream changes, continues to cause us pain in using Terraform in production. Any chance someone could look at this change? Is there any more information I need to provide?

@bflad @ewbankkit @gdavison @YakDriver @anGie44

**Comment by aircraft-cerier** [comment]
Have been following this PR for a while, any progress in the review? Thanks

@bflad @ewbankkit @gdavison @YakDriver @anGie44 @breathingdust

**Review by YakDriver — APPROVED** [review]
Looks great! Thank you for your contribution and patience. 🎉 

Output from acceptance tests (`us-west-2`):
```console
% make testacc TESTS=TestAccEC2Fleet PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Fleet' -timeout 180m
--- SKIP: TestAccEC2Fleet_LaunchTemplateOverride_maxPrice (0.00s)
--- PASS: TestAccEC2Fleet_SpotOptions_capacityRebalance (51.39s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecificationDefaultTargetCapacityType_spot (52.17s)
--- PASS: TestAccEC2Fleet_basic (53.58s)
--- PASS: TestAccEC2Fleet_type (54.25s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecificationDefaultTargetCapacityType_onDemand (54.62s)
--- PASS: TestAccEC2Fleet_SpotOptions_allocationStrategy (89.74s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecification_defaultTargetCapacityType (89.94s)
--- PASS: TestAccEC2Fleet_terminateInstancesWithExpiration (94.04s)
--- PASS: TestAccEC2Fleet_replaceUnhealthyInstances (94.25s)
--- PASS: TestAccEC2Fleet_SpotOptions_instancePoolsToUseCount (94.28s)
--- PASS: TestAccEC2Fleet_SpotOptions_instanceInterruptionBehavior (94.67s)
--- PASS: TestAccEC2Fleet_LaunchTemplateLaunchTemplateSpecification_launchTemplateName (101.54s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_availabilityZone (101.95s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_weightedCapacity (102.24s)
--- PASS: TestAccEC2Fleet_tags (103.81s)
--- PASS: TestAccEC2Fleet_LaunchTemplateLaunchTemplateSpecification_version (104.81s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_instanceType (109.85s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_subnetID (111.31s)
--- PASS: TestAccEC2Fleet_disappears (41.67s)
--- PASS: TestAccEC2Fleet_OnDemandOptions_allocationStrategy (84.26s)
--- PASS: TestAccEC2Fleet_excessCapacityTerminationPolicy (105.91s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverridePriority_multiple (106.70s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_priority (104.65s)
--- PASS: TestAccEC2Fleet_LaunchTemplateLaunchTemplateSpecification_launchTemplateID (107.87s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverrideWeightedCapacity_multiple (102.65s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecification_totalTargetCapacity (473.62s)
--- PASS: TestAccEC2Fleet_templateMultipleNetworkInterfaces (554.46s)
```

Output from acceptance tests (GovCloud):
```console
% make testacc TESTS=TestAccEC2Fleet PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2Fleet' -timeout 180m
--- SKIP: TestAccEC2Fleet_LaunchTemplateOverride_maxPrice (0.00s)
--- PASS: TestAccEC2Fleet_SpotOptions_capacityRebalance (62.51s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecificationDefaultTargetCapacityType_onDemand (62.59s)
--- PASS: TestAccEC2Fleet_type (62.59s)
--- PASS: TestAccEC2Fleet_basic (62.66s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecification_defaultTargetCapacityType (96.38s)
--- PASS: TestAccEC2Fleet_replaceUnhealthyInstances (104.87s)
--- PASS: TestAccEC2Fleet_terminateInstancesWithExpiration (104.93s)
--- PASS: TestAccEC2Fleet_SpotOptions_instancePoolsToUseCount (105.07s)
--- PASS: TestAccEC2Fleet_SpotOptions_allocationStrategy (105.12s)
--- PASS: TestAccEC2Fleet_OnDemandOptions_allocationStrategy (105.12s)
--- PASS: TestAccEC2Fleet_SpotOptions_instanceInterruptionBehavior (105.12s)
--- PASS: TestAccEC2Fleet_LaunchTemplateLaunchTemplateSpecification_launchTemplateName (108.33s)
--- PASS: TestAccEC2Fleet_LaunchTemplateLaunchTemplateSpecification_launchTemplateID (113.88s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverrideWeightedCapacity_multiple (114.31s)
--- PASS: TestAccEC2Fleet_excessCapacityTerminationPolicy (114.48s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_instanceType (114.54s)
--- PASS: TestAccEC2Fleet_tags (114.54s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_weightedCapacity (114.56s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_subnetID (119.48s)
--- PASS: TestAccEC2Fleet_disappears (40.59s)
--- PASS: TestAccEC2Fleet_TargetCapacitySpecificationDefaultTargetCapacityType_spot (43.68s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_priority (105.16s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverridePriority_multiple (105.45s)
--- PASS: TestAccEC2Fleet_LaunchTemplateOverride_availabilityZone (105.38s)
--- PASS: TestAccEC2Fleet_LaunchTemplateLaunchTemplateSpecification_version (106.48s)
```

**Pull request merged**
