### PR TITLE
New resource: `aws_verifiedaccess_group`

### PR DESCRIPTION
**Pull request by sQu4rks**
### Description
Adds support for the Verified Access Group resource. 

This PR is a draft since, for proper acceptance testing, the verified access instance and verified access trust provider resources are required. Currently acceptance testing is done by deploying a trust provider and verified access instance in the console and then setting the id in the tests. 

### Relations

Relates #29689 
Depends on #33195 
Depends on #29742 

### References
[Link to API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVerifiedAccessGroup.html)

### Output from Acceptance Testing
```console
% make testacc TESTS="TestAccVerifiedAccessAccessGroup_*" PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVerifiedAccessAccessGroup_*'  -timeout 180m
=== RUN   TestAccVerifiedAccessAccessGroup_basic
=== PAUSE TestAccVerifiedAccessAccessGroup_basic
=== RUN   TestAccVerifiedAccessAccessGroup_policy
=== PAUSE TestAccVerifiedAccessAccessGroup_policy
=== RUN   TestAccVerifiedAccessAccessGroup_tags
=== PAUSE TestAccVerifiedAccessAccessGroup_tags
=== CONT  TestAccVerifiedAccessAccessGroup_basic
=== CONT  TestAccVerifiedAccessAccessGroup_tags
=== CONT  TestAccVerifiedAccessAccessGroup_policy
--- PASS: TestAccVerifiedAccessAccessGroup_tags (33.43s)
--- PASS: TestAccVerifiedAccessAccessGroup_basic (33.57s)
--- PASS: TestAccVerifiedAccessAccessGroup_policy (33.73s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        37.414s
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Requires https://github.com/hashicorp/terraform-provider-aws/pull/33459.

**Comment by ewbankkit** [comment]
```console
% make testacc TESTARGS='-run=TestAccVerifiedAccessGroup_basic' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVerifiedAccessGroup_basic -timeout 180m
=== RUN   TestAccVerifiedAccessGroup_basic
=== PAUSE TestAccVerifiedAccessGroup_basic
=== CONT  TestAccVerifiedAccessGroup_basic
    verifiedaccess_group_test.go:25: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Verified Access Group: operation error EC2: CreateVerifiedAccessGroup, https response error StatusCode: 400, RequestID: 2312b462-547e-4588-9f1b-f00d9ffe30a7, api error InvalidParameterValue: Must attach a TrustProvider to Instance vai-0f22af219faae53fa before you can create a Group
        
          with aws_verifiedaccess_group.test,
          on terraform_plugin_test.tf line 8, in resource "aws_verifiedaccess_group" "test":
           8: resource "aws_verifiedaccess_group" "test" {
        
--- FAIL: TestAccVerifiedAccessGroup_basic (12.26s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	17.603s
FAIL
make: *** [testacc] Error 1
```

**Comment by sQu4rks** [comment]
Also requires #33734 since the verified access group can't be created without a trust provider being attached to the instance.

Relevant error message:
```
Error: creating Verified Access Group: 
operation error EC2: CreateVerifiedAccessGroup,
https response error StatusCode: 400,
RequestID: <REDACTED>,
api error InvalidParameterValue: Must attach a TrustProvider to Instance vai-<REDACTED> before you can create a Group
```

With the `aws_verifiedaccess_trust_provider_attachment` resource from #33734 the following config should work for the tests:

```
resource "aws_verifiedaccess_trust_provider" "test" {
  oidc_options {
	authorization_endpoint = "https://authorization.example.com"
	client_id              = "r4nd0mst1n9"
	client_secret          = "r4nd0ms3cr3t"
	issuer                 = "https://isser.example.com"
	scope                  = "r4nd0msc0p3"
	token_endpoint         = "https://token.example.com"
	user_info_endpoint     = "https://user.example.com"
  }
  policy_reference_name    = "test"
  trust_provider_type      = "user"
  user_trust_provider_type = "oidc"
}

resource "aws_verifiedaccess_instance" "test" {
	tags = {
	  Name = %[1]q
	}
}

resource "aws_verifiedaccess_trust_provider_attachment" "test" {
	instance_id       = aws_verifiedaccess_instance.test.id
	trust_provider_id = aws_verifiedaccess_trust_provider.test.id
}

resource "aws_verifiedaccess_group" "test" {
  verifiedaccess_instance_id = aws_verifiedaccess_instance.test.id
}
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVerifiedAccessGroup_' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVerifiedAccessGroup_ -timeout 360m
=== RUN   TestAccVerifiedAccessGroup_basic
=== PAUSE TestAccVerifiedAccessGroup_basic
=== RUN   TestAccVerifiedAccessGroup_disappears
=== PAUSE TestAccVerifiedAccessGroup_disappears
=== RUN   TestAccVerifiedAccessGroup_tags
=== PAUSE TestAccVerifiedAccessGroup_tags
=== RUN   TestAccVerifiedAccessGroup_policy
=== PAUSE TestAccVerifiedAccessGroup_policy
=== CONT  TestAccVerifiedAccessGroup_basic
=== CONT  TestAccVerifiedAccessGroup_tags
--- PASS: TestAccVerifiedAccessGroup_basic (31.18s)
=== CONT  TestAccVerifiedAccessGroup_disappears
--- PASS: TestAccVerifiedAccessGroup_disappears (25.03s)
=== CONT  TestAccVerifiedAccessGroup_policy
--- PASS: TestAccVerifiedAccessGroup_tags (68.59s)
--- PASS: TestAccVerifiedAccessGroup_policy (28.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	90.212s
```

**Comment by evilr00t** [comment]
When a group is created and we want to add policy I have below error message:

```hcl
  # aws_verifiedaccess_group.monitoring will be updated in-place
  ~ resource "aws_verifiedaccess_group" "monitoring" {
        id                         = "vagr-XYZ"
      + policy_document            = <<-EOT
            permit(principal,action,resource)
                  when {
                  context.test.groups has "XYZ" || context.test.user.email.address like "*@FOOBAR"
                };
        EOT
        tags                       = {
            "Environment" = "monitoring"
            "Name"        = "monitoring-ava-group"
            "system"      = "core"
        }
        # (7 unchanged attributes hidden)
    }

...

│ Error: updating Verified Access Group (vagr-043f49684c52f3afb) policy: operation error EC2: ModifyVerifiedAccessGroupPolicy, https response error StatusCode: 400, RequestID: ed72eee9-3fcc-4c2b-8a7b-d492d16d7a4e, api error InvalidParameterValue: Policy Document cannot be provided when Policy Enabled is false or missing
```

When I create group with policy already included, there is no problem. There is no variable to enable/disable policy so I'd assume it's a bug atm?

**Comment by sQu4rks** [comment]
Having a look @evilr00t - I can reproduce the behavior.

**Comment by evilr00t** [comment]
@sQu4rks sure thing: https://github.com/hashicorp/terraform-provider-aws/issues/34052 here it is. Sorry for a delay.

**Pull request merged**
