### PR TITLE
r/customer_gateway - cleanup + `certificate_arn`

### LINKED ISSUE #10548: `aws_customer_gateway` certificate authentication support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Site-to-Site VPN now supports [certificate authentication](https://aws.amazon.com/about-aws/whats-new/2019/08/aws-site-to-site-vpn-now-supports-certificate-authentication/) besides pre-shared keys, but I don't see support for this in [`aws_customer_gateway`](https://www.terraform.io/docs/providers/aws/r/customer_gateway.html).

### New or Affected Resource(s)

* `aws_customer_gateway`
* `aws_vpn_connection`

### Potential Terraform Configuration

```hcl
resource "aws_customer_gateway" "cgtw" {
  bgp_asn         = 65000
  ip_address      = "${var.partner_ip_address}"
  type            = "ipsec.1"
  certificate_arn = "${config.vpn_certificate_arn}"
}
```

### References

- https://docs.aws.amazon.com/cli/latest/reference/ec2/create-customer-gateway.html
- https://aws.amazon.com/about-aws/whats-new/2019/08/aws-site-to-site-vpn-now-supports-certificate-authentication

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #10548.
I don't think this closes the issue as there is work required in `aws_vpn_connection`.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccEC2CustomerGateway_ PKG=ec2
--- PASS: TestAccEC2CustomerGateway_disappears (81.73s)
--- PASS: TestAccEC2CustomerGateway_deviceName (105.66s)
--- PASS: TestAccEC2CustomerGateway_4ByteASN (108.74s)
--- PASS: TestAccEC2CustomerGateway_similarAlreadyExists (126.87s)
--- PASS: TestAccEC2CustomerGateway_basic (158.66s)
--- PASS: TestAccEC2CustomerGateway_tags (176.13s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
cert arn test failing with:

```
        Error: Error creating customer gateway: InvalidParameterValue: An error was encountered during validation of your certificate chain. An error was encountered during certificate chain validation. Please ensure that your End Entity certificate was generated by your Subordinate CA. See our documentation for assistance with proper CA setup and validation.
        	status code: 400
```

Leaving this as baseline to support cert arn /:

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for this.
I have also been looking at this (as an intro to some changes to `aws_vpn_connection` for **v4.0.0**) and eventually did get a test case passing (have to create 2 CAs, one subordinate to the other, activate them both and then issue a certificate).
I have hijacked this PR with my changes 😄.

**Comment by DrFaust92** [comment]
@ewbankkit Awesome! i played with 2 ACM PCA but didnt find the right combo.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTARGS='-run=TestAccEC2CustomerGateway_basic\|TestAccEC2CustomerGatewayDataSource_\|TestAccEC2VPNGateway_\|TestAccEC2VPNGatewayAttachment_\|TestAccEC2VPNGatewayDataSource_' PKG_NAME=internal/service/ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2CustomerGateway_basic\|TestAccEC2CustomerGatewayDataSource_\|TestAccEC2VPNGateway_\|TestAccEC2VPNGatewayAttachment_\|TestAccEC2VPNGatewayDataSource_ -timeout 180m
=== RUN   TestAccEC2CustomerGatewayDataSource_filter
=== PAUSE TestAccEC2CustomerGatewayDataSource_filter
=== RUN   TestAccEC2CustomerGatewayDataSource_id
=== PAUSE TestAccEC2CustomerGatewayDataSource_id
=== RUN   TestAccEC2CustomerGateway_basic
=== PAUSE TestAccEC2CustomerGateway_basic
=== RUN   TestAccEC2VPNGatewayAttachment_basic
=== PAUSE TestAccEC2VPNGatewayAttachment_basic
=== RUN   TestAccEC2VPNGatewayAttachment_disappears
=== PAUSE TestAccEC2VPNGatewayAttachment_disappears
=== RUN   TestAccEC2VPNGatewayDataSource_unattached
=== PAUSE TestAccEC2VPNGatewayDataSource_unattached
=== RUN   TestAccEC2VPNGatewayDataSource_attached
=== PAUSE TestAccEC2VPNGatewayDataSource_attached
=== RUN   TestAccEC2VPNGateway_basic
=== PAUSE TestAccEC2VPNGateway_basic
=== RUN   TestAccEC2VPNGateway_withAvailabilityZoneSetToState
=== PAUSE TestAccEC2VPNGateway_withAvailabilityZoneSetToState
=== RUN   TestAccEC2VPNGateway_withAmazonSideASN
=== PAUSE TestAccEC2VPNGateway_withAmazonSideASN
=== RUN   TestAccEC2VPNGateway_disappears
=== PAUSE TestAccEC2VPNGateway_disappears
=== RUN   TestAccEC2VPNGateway_reattach
=== PAUSE TestAccEC2VPNGateway_reattach
=== RUN   TestAccEC2VPNGateway_tags
=== PAUSE TestAccEC2VPNGateway_tags
=== CONT  TestAccEC2CustomerGatewayDataSource_filter
=== CONT  TestAccEC2VPNGateway_basic
=== CONT  TestAccEC2VPNGateway_withAmazonSideASN
=== CONT  TestAccEC2VPNGatewayDataSource_unattached
=== CONT  TestAccEC2CustomerGatewayDataSource_id
=== CONT  TestAccEC2VPNGateway_reattach
=== CONT  TestAccEC2VPNGateway_tags
=== CONT  TestAccEC2VPNGateway_withAvailabilityZoneSetToState
=== CONT  TestAccEC2VPNGatewayAttachment_disappears
=== CONT  TestAccEC2VPNGatewayDataSource_attached
=== CONT  TestAccEC2CustomerGateway_basic
=== CONT  TestAccEC2VPNGatewayAttachment_basic
=== CONT  TestAccEC2VPNGateway_disappears
--- PASS: TestAccEC2VPNGatewayDataSource_unattached (22.98s)
--- PASS: TestAccEC2CustomerGatewayDataSource_id (33.26s)
--- PASS: TestAccEC2CustomerGateway_basic (33.59s)
--- PASS: TestAccEC2CustomerGatewayDataSource_filter (33.94s)
--- PASS: TestAccEC2VPNGatewayAttachment_disappears (50.02s)
--- PASS: TestAccEC2VPNGatewayAttachment_basic (50.57s)
--- PASS: TestAccEC2VPNGateway_withAmazonSideASN (56.21s)
--- PASS: TestAccEC2VPNGateway_disappears (57.21s)
--- PASS: TestAccEC2VPNGateway_withAvailabilityZoneSetToState (57.85s)
--- PASS: TestAccEC2VPNGatewayDataSource_attached (59.75s)
--- PASS: TestAccEC2VPNGateway_basic (93.40s)
--- PASS: TestAccEC2VPNGateway_tags (96.76s)
--- PASS: TestAccEC2VPNGateway_reattach (143.79s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	147.200s
```

##### GovCloud

```console
% make testacc TESTARGS='-run=TestAccEC2CustomerGateway_basic\|TestAccEC2CustomerGatewayDataSource_\|TestAccEC2VPNGateway_\|TestAccEC2VPNGatewayAttachment_\|TestAccEC2VPNGatewayDataSource_' PKG_NAME=internal/service/ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2CustomerGateway_basic\|TestAccEC2CustomerGatewayDataSource_\|TestAccEC2VPNGateway_\|TestAccEC2VPNGatewayAttachment_\|TestAccEC2VPNGatewayDataSource_ -timeout 180m
=== RUN   TestAccEC2CustomerGatewayDataSource_filter
=== PAUSE TestAccEC2CustomerGatewayDataSource_filter
=== RUN   TestAccEC2CustomerGatewayDataSource_id
=== PAUSE TestAccEC2CustomerGatewayDataSource_id
=== RUN   TestAccEC2CustomerGateway_basic
=== PAUSE TestAccEC2CustomerGateway_basic
=== RUN   TestAccEC2VPNGatewayAttachment_basic
=== PAUSE TestAccEC2VPNGatewayAttachment_basic
=== RUN   TestAccEC2VPNGatewayAttachment_disappears
=== PAUSE TestAccEC2VPNGatewayAttachment_disappears
=== RUN   TestAccEC2VPNGatewayDataSource_unattached
=== PAUSE TestAccEC2VPNGatewayDataSource_unattached
=== RUN   TestAccEC2VPNGatewayDataSource_attached
=== PAUSE TestAccEC2VPNGatewayDataSource_attached
=== RUN   TestAccEC2VPNGateway_basic
=== PAUSE TestAccEC2VPNGateway_basic
=== RUN   TestAccEC2VPNGateway_withAvailabilityZoneSetToState
=== PAUSE TestAccEC2VPNGateway_withAvailabilityZoneSetToState
=== RUN   TestAccEC2VPNGateway_withAmazonSideASN
=== PAUSE TestAccEC2VPNGateway_withAmazonSideASN
=== RUN   TestAccEC2VPNGateway_disappears
=== PAUSE TestAccEC2VPNGateway_disappears
=== RUN   TestAccEC2VPNGateway_reattach
=== PAUSE TestAccEC2VPNGateway_reattach
=== RUN   TestAccEC2VPNGateway_tags
=== PAUSE TestAccEC2VPNGateway_tags
=== CONT  TestAccEC2CustomerGatewayDataSource_filter
=== CONT  TestAccEC2VPNGateway_basic
=== CONT  TestAccEC2VPNGateway_tags
=== CONT  TestAccEC2VPNGatewayAttachment_disappears
=== CONT  TestAccEC2VPNGatewayDataSource_attached
=== CONT  TestAccEC2VPNGateway_disappears
=== CONT  TestAccEC2VPNGatewayDataSource_unattached
=== CONT  TestAccEC2VPNGateway_withAmazonSideASN
=== CONT  TestAccEC2VPNGateway_reattach
=== CONT  TestAccEC2CustomerGateway_basic
=== CONT  TestAccEC2VPNGateway_withAvailabilityZoneSetToState
=== CONT  TestAccEC2CustomerGatewayDataSource_id
=== CONT  TestAccEC2VPNGatewayAttachment_basic
--- PASS: TestAccEC2VPNGatewayDataSource_unattached (25.47s)
--- PASS: TestAccEC2CustomerGatewayDataSource_id (35.14s)
--- PASS: TestAccEC2CustomerGatewayDataSource_filter (35.39s)
--- PASS: TestAccEC2CustomerGateway_basic (35.93s)
--- PASS: TestAccEC2VPNGatewayAttachment_disappears (49.01s)
--- PASS: TestAccEC2VPNGateway_disappears (54.96s)
--- PASS: TestAccEC2VPNGatewayDataSource_attached (61.65s)
--- PASS: TestAccEC2VPNGatewayAttachment_basic (65.27s)
--- PASS: TestAccEC2VPNGateway_withAmazonSideASN (74.62s)
--- PASS: TestAccEC2VPNGateway_withAvailabilityZoneSetToState (82.10s)
--- PASS: TestAccEC2VPNGateway_basic (94.70s)
--- PASS: TestAccEC2VPNGateway_tags (112.04s)
--- PASS: TestAccEC2VPNGateway_reattach (156.99s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	160.716s
```

##### Sweeper

```console
% make sweep SWEEPARGS=-sweep-run=aws_vpn_gateway,aws_customer_gateway SWEEP=us-west-1
# make sweep SWEEPARGS=-sweep-run=aws_example_thing
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./internal/sweep -v -tags=sweep -sweep=us-west-1 -sweep-run=aws_vpn_gateway,aws_customer_gateway -timeout 60m
2022/01/06 13:57:51 [DEBUG] Running Sweepers for region (us-west-1):
2022/01/06 13:57:51 [DEBUG] Sweeper (aws_vpn_gateway) has dependency (aws_dx_gateway_association), running..
2022/01/06 13:57:51 [DEBUG] Sweeper (aws_dx_gateway_association) has dependency (aws_dx_gateway_association_proposal), running..
2022/01/06 13:57:51 [DEBUG] Running Sweeper (aws_dx_gateway_association_proposal) in region (us-west-1)
2022/01/06 13:57:51 [INFO] AWS Auth provider used: "EnvProvider"
2022/01/06 13:57:51 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/06 13:57:51 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/06 13:57:52 [DEBUG] Completed Sweeper (aws_dx_gateway_association_proposal) in region (us-west-1) in 1.171974349s
2022/01/06 13:57:52 [DEBUG] Running Sweeper (aws_dx_gateway_association) in region (us-west-1)
2022/01/06 13:57:53 [DEBUG] Completed Sweeper (aws_dx_gateway_association) in region (us-west-1) in 783.119411ms
2022/01/06 13:57:53 [DEBUG] Sweeper (aws_vpn_gateway) has dependency (aws_vpn_connection), running..
2022/01/06 13:57:53 [DEBUG] Running Sweeper (aws_vpn_connection) in region (us-west-1)
2022/01/06 13:57:54 [DEBUG] Completed Sweeper (aws_vpn_connection) in region (us-west-1) in 428.346217ms
2022/01/06 13:57:54 [DEBUG] Running Sweeper (aws_vpn_gateway) in region (us-west-1)
2022/01/06 13:57:54 [DEBUG] Waiting for state to become: [success]
2022/01/06 13:57:54 [DEBUG] Waiting for state to become: [success]
2022/01/06 13:57:54 [INFO] Deleting EC2 VPN Gateway: vgw-0635427cd09d9283e
2022/01/06 13:57:54 [DEBUG] Waiting for state to become: [success]
2022/01/06 13:57:54 [INFO] Detaching EC2 VPN Gateway (vgw-0f9e40710e8b75fb2) from VPC (vpc-032af5ec8d23ef28e)
2022/01/06 13:57:55 [DEBUG] Waiting for state to become: []
2022/01/06 13:57:56 [INFO] Deleting EC2 VPN Gateway: vgw-0f9e40710e8b75fb2
2022/01/06 13:57:56 [DEBUG] Waiting for state to become: [success]
2022/01/06 13:57:56 [DEBUG] Completed Sweeper (aws_vpn_gateway) in region (us-west-1) in 2.919310439s
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_dx_gateway_association) has dependency (aws_dx_gateway_association_proposal), running..
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_dx_gateway_association_proposal) already ran in region (us-west-1)
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_dx_gateway_association) already ran in region (us-west-1)
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_dx_gateway_association_proposal) already ran in region (us-west-1)
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_vpn_connection) already ran in region (us-west-1)
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_customer_gateway) has dependency (aws_vpn_connection), running..
2022/01/06 13:57:56 [DEBUG] Sweeper (aws_vpn_connection) already ran in region (us-west-1)
2022/01/06 13:57:56 [DEBUG] Running Sweeper (aws_customer_gateway) in region (us-west-1)
2022/01/06 13:57:57 [DEBUG] Waiting for state to become: [success]
2022/01/06 13:57:57 [INFO] Deleting EC2 Customer Gateway: cgw-08204f3a1404061c4
2022/01/06 13:57:57 [DEBUG] Waiting for state to become: []
2022/01/06 13:57:58 [DEBUG] Completed Sweeper (aws_customer_gateway) in region (us-west-1) in 1.426989975s
2022/01/06 13:57:58 Completed Sweepers for region (us-west-1) in 6.730240462s
2022/01/06 13:57:58 Sweeper Tests for region (us-west-1) ran successfully:
	- aws_dx_gateway_association_proposal
	- aws_dx_gateway_association
	- aws_vpn_connection
	- aws_vpn_gateway
	- aws_customer_gateway
ok  	github.com/hashicorp/terraform-provider-aws/internal/sweep	9.968s
```

**Pull request merged**
