### PR TITLE
New resource: aws_lightsail_domain_entry

### LINKED ISSUE #2731: Add AWS Lightsail DNS Entry Support
Hi there,

Would it be possible to add support for adding/removing DNS records to Lightsail domains?

API references:
https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_CreateDomainEntry.html
https://docs.aws.amazon.com/lightsail/2016-11-28/api-reference/API_DeleteDomainEntry.html

Thank you,
John

### PR DESCRIPTION
**Pull request by blckct**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Add new resource `aws_lightsail_domain_entry`
Closes #2731

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
aws/lightsail_domain_entry: New resource
```

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSLightsailDomainEntry_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSLightsailDomainEntry_basic -timeout 120m
=== RUN   TestAccAWSLightsailDomainEntry_basic
=== PAUSE TestAccAWSLightsailDomainEntry_basic
=== CONT  TestAccAWSLightsailDomainEntry_basic
--- PASS: TestAccAWSLightsailDomainEntry_basic (33.33s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	33.357s

make testacc TEST=./aws TESTARGS='-run=TestAccAWSLightsailDomainEntry_disappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSLightsailDomainEntry_disappears -timeout 120m
=== RUN   TestAccAWSLightsailDomainEntry_disappears
=== PAUSE TestAccAWSLightsailDomainEntry_disappears
=== CONT  TestAccAWSLightsailDomainEntry_disappears
--- PASS: TestAccAWSLightsailDomainEntry_disappears (31.78s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	31.807s
...
```

### CODE REVIEW

**Comment by blckct** [comment]
I had some trouble wrapping my head around the tests so please take extra care with them :worried: 
Regarding the #9080, the provider has to be hardcoded in tests same as in `aws_lightsail_domain`

**Comment by blckct** [comment]
@aeschright Hey, any chance that someone could look at this PR?

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by blckct** [comment]
Regarding the automated message, I'm willing to make the changes but I'd prefer if someone from the team confirmed this feature is needed.

**Comment by reticentnz** [comment]
is there an update on this? I've been playing around with Lightsail deployments but it's somewhat limited without being to provision the DNS records alongside the creation of the lightsail instance itself.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by brittandeyoung** [comment]
@reticentnz 

For Awareness I have begun work on creating a separate AWS lightsail provider in order to help with Speeding up contributions and to give it dedicated attention. 

The Github repo is located here: https://github.com/DeYoungTech/terraform-provider-awslightsail

The provider and documentation is published here: https://registry.terraform.io/providers/DeYoungTech/awslightsail/latest

With the most recent version, I have added support for the `domain_entry`  resource.

If you want to start using this resource now, feel free to check it out and provide feedback.

**Comment by brittandeyoung** [comment]
@blckct If I where to put in the time to make a Pull request against your branch to bring this change up to date, would you be available to merge it?

**Comment by blckct** [comment]
@brittandeyoung Hey, yes. I could even update it myself if I knew there's a  chance it will be merged.

**Comment by brittandeyoung** [comment]
@blckct I have opened a Pull request against the branch you have created this PR from: https://github.com/blckct/terraform-provider-aws/pull/2 

Merging this should bring this PR up to speed with the newest changes from `main`. I attempted to run all the validations I could locally, so hopefully we will have passing tests the first try =). If not, I will raise additional PRs to resolve. 

Once we have passing tests I will see how I can bug to get a review =).

**Comment by brittandeyoung** [comment]
After speaking with provider maintainers, I have been recommended to open up a new PR and pull in the commits from this PR.

**Pull request merged**
