### PR TITLE
r/aws_lakeformation_permissions: Fix bug where SELECT permissions are not properly read in from AWS

### LINKED ISSUE #17299: Lakeformation SELECT table permission always shows as a change
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform: v0.13.16
Provider: v3.25.0

### Affected Resource(s)

* aws_lakeformation_permissions

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals {
  db_name    = "test-db"
  table_name = "test-table"
  principal  = "arn:aws:iam::367740853123:role/TestRole"
}

resource "aws_glue_catalog_database" "test" {
  name = local.db_name
}

resource "aws_glue_catalog_table" "test" {
  name          = local.table_name
  database_name = aws_glue_catalog_database.test.name
}

resource "aws_lakeformation_permissions" "test" {
  principal                     = local.principal
  permissions                   = ["ALL", "ALTER", "DELETE", "DESCRIBE", "DROP", "INSERT", "SELECT"]
  permissions_with_grant_option = ["ALL", "ALTER", "DELETE", "DESCRIBE", "DROP", "INSERT", "SELECT"]
  table {
    database_name = aws_glue_catalog_table.test.database_name
    name          = aws_glue_catalog_table.test.name
  }
}
```

### Expected Behavior

The table permissions have not changed since the last successful apply so running a new plan should show no changes

### Actual Behavior

Running a new plan always shows that the SELECT permission needs to be added. Running this apply is successful and the permissions are recreated but next time a plan is run it again shows this as a change.

This is because AWS Lakeformation treats the SELECT permission differently to the other table permissions and creates it as a column permission. This column permission is not correctly evaluated by the plan.

```
# module.infrastructure.aws_lakeformation_permissions.test must be replaced
-/+ resource "aws_lakeformation_permissions" "test" {
        catalog_resource              = false
      ~ id                            = "238539814" -> (known after apply)
      ~ permissions                   = [ # forces replacement
            "ALL",
            "ALTER",
            "DELETE",
            "DESCRIBE",
            "DROP",
            "INSERT",
          + "SELECT",
        ]
      ~ permissions_with_grant_option = [ # forces replacement
            "ALL",
            "ALTER",
            "DELETE",
            "DESCRIBE",
            "DROP",
            "INSERT",
          + "SELECT",
        ]
```
image

### Steps to Reproduce

1. Run `terraform apply`
2. Run `terraform apply` or `terraform plan`

### PR DESCRIPTION
**Pull request by brunhil**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17299 

Output from acceptance testing:

=== RUN   TestAccAWSLakeFormation_serial
=== RUN   TestAccAWSLakeFormation_serial/Permissions
=== RUN   TestAccAWSLakeFormation_serial/Permissions/selectPermissions
--- PASS: TestAccAWSLakeFormation_serial (38.65s)
    --- PASS: TestAccAWSLakeFormation_serial/Permissions (38.65s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/selectPermissions (38.65s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       43.488s

```
$ make testacc TESTARGS='-run= TestAccAWSLakeFormation_serial'

...
```

### CODE REVIEW

**Comment by YakDriver** [comment]
@brunhil Thanks for this contribution! I'll look at this in the near future. Let me know when this is complete. To save time, if there we need minor changes, I will make them directly so make sure to check the box to allow edits by maintainers.

**Comment by brunhil** [comment]
Thanks for checking in @YakDriver , this should be ready for your review. I believe I covered most of the steps as defined in the CONTRIBUTING readme. Let me know if I missed anything! 

I added a test for this case that should fail on current the current `main` branch to confirm the referenced issue.

**Comment by YakDriver** [comment]
@brunhil If you have further interest in this resource, we could use some help! Lake Formation, and permissions in particular, seem to have especially bad eventual consistency problems (for example, "AccessDeniedException: Resource does not exist" type errors). If you're interested in tackling asynchronous challenges, this documentation will get you started: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md. Because of these AWS challenges, the AWS provider Lake Formation resources are only marginally stable.

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

Acceptance tests in GovCloud:
```
    --- PASS: TestAccAWSLakeFormation_serial/Permissions (100.76s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/basic (26.80s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/dataLocation (24.90s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/database (22.21s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/selectPermissions (26.85s)
```

Acceptance tests on Commercial:
```
    --- PASS: TestAccAWSLakeFormation_serial/Permissions (102.99s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/dataLocation (27.37s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/database (21.15s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/selectPermissions (25.43s)
        --- PASS: TestAccAWSLakeFormation_serial/Permissions/basic (29.04s)
```

**Comment by brunhil** [comment]
> Because of these AWS challenges, the AWS provider Lake Formation resources are only marginally stable.

This sounds interesting and fun @YakDriver ! Looking at the existing resource it already has retry logic in place. Is there something different we wanted to do here?

**Pull request merged**
