### PR TITLE
add node_repair_config to aws_eks_node_group

### LINKED ISSUE #40641: [Enhancement]: support EKS node auto repair config on aws_eks_node_group
### Description

AWS just released a new addon and node group config.

The `CreateNodeGroup` API has a new `nodeRepairConfig` feature that should get exposed to the `aws_eks_node_group` resource.

### Affected Resource(s) and/or Data Source(s)

- aws_eks_node_group

### Potential Terraform Configuration

```terraform
resource "aws_eks_node_group" {
  # ... snip
  node_repair_config {
    enabled = true
  }
}
```

### References

- https://aws.amazon.com/about-aws/whats-new/2024/12/node-health-monitoring-auto-repair-amazon-eks/
- https://docs.aws.amazon.com/eks/latest/userguide/node-health.html
- https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateNodegroup.html#AmazonEKS-CreateNodegroup-request-nodeRepairConfig

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by hjoshi123**
### Description

This PR introduces node_repair_config to aws_eks_node_group resource which was introduced recently in the EKS CreateNodeGroup API. As part of this PR create, update and read have been update along with a new acceptance test to account for the option.

### Relations

Closes #40641

### Output from Acceptance Testing

```console
%  make testacc TESTS=TestAccEKSNodeGroup_RepairConfig PKG=eks
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSNodeGroup_nodeRepairConfig'  -timeout 360m
2024/12/26 08:21:22 Initializing Terraform AWS Provider...
=== RUN   TestAccEKSNodeGroup_nodeRepairConfig
=== PAUSE TestAccEKSNodeGroup_nodeRepairConfig
=== CONT  TestAccEKSNodeGroup_nodeRepairConfig
--- PASS: TestAccEKSNodeGroup_nodeRepairConfig (1018.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	1022.770s
...
```

### CODE REVIEW

**Comment by hjoshi123** [comment]
@ewbankkit I am running the acceptance tests in my local.. will update the comment once it runs

**Comment by hjoshi123** [comment]
Added the acceptance test passing

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEKSNodeGroup_' PKG=eks ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/eks/... -v -count 1 -parallel 4  -run=TestAccEKSNodeGroup_ -timeout 360m
2024/12/26 08:36:44 Initializing Terraform AWS Provider...
=== RUN   TestAccEKSNodeGroup_basic
=== PAUSE TestAccEKSNodeGroup_basic
=== RUN   TestAccEKSNodeGroup_Name_generated
=== PAUSE TestAccEKSNodeGroup_Name_generated
=== RUN   TestAccEKSNodeGroup_namePrefix
=== PAUSE TestAccEKSNodeGroup_namePrefix
=== RUN   TestAccEKSNodeGroup_disappears
=== PAUSE TestAccEKSNodeGroup_disappears
=== RUN   TestAccEKSNodeGroup_amiType
=== PAUSE TestAccEKSNodeGroup_amiType
=== RUN   TestAccEKSNodeGroup_CapacityType_spot
=== PAUSE TestAccEKSNodeGroup_CapacityType_spot
=== RUN   TestAccEKSNodeGroup_diskSize
=== PAUSE TestAccEKSNodeGroup_diskSize
=== RUN   TestAccEKSNodeGroup_forceUpdateVersion
=== PAUSE TestAccEKSNodeGroup_forceUpdateVersion
=== RUN   TestAccEKSNodeGroup_InstanceTypes_multiple
=== PAUSE TestAccEKSNodeGroup_InstanceTypes_multiple
=== RUN   TestAccEKSNodeGroup_InstanceTypes_single
=== PAUSE TestAccEKSNodeGroup_InstanceTypes_single
=== RUN   TestAccEKSNodeGroup_labels
=== PAUSE TestAccEKSNodeGroup_labels
=== RUN   TestAccEKSNodeGroup_LaunchTemplate_id
=== PAUSE TestAccEKSNodeGroup_LaunchTemplate_id
=== RUN   TestAccEKSNodeGroup_LaunchTemplate_name
=== PAUSE TestAccEKSNodeGroup_LaunchTemplate_name
=== RUN   TestAccEKSNodeGroup_LaunchTemplate_version
=== PAUSE TestAccEKSNodeGroup_LaunchTemplate_version
=== RUN   TestAccEKSNodeGroup_nodeRepairConfig
=== PAUSE TestAccEKSNodeGroup_nodeRepairConfig
=== RUN   TestAccEKSNodeGroup_releaseVersion
=== PAUSE TestAccEKSNodeGroup_releaseVersion
=== RUN   TestAccEKSNodeGroup_RemoteAccess_ec2SSHKey
=== PAUSE TestAccEKSNodeGroup_RemoteAccess_ec2SSHKey
=== RUN   TestAccEKSNodeGroup_RemoteAccess_sourceSecurityGroupIDs
=== PAUSE TestAccEKSNodeGroup_RemoteAccess_sourceSecurityGroupIDs
=== RUN   TestAccEKSNodeGroup_Scaling_desiredSize
=== PAUSE TestAccEKSNodeGroup_Scaling_desiredSize
=== RUN   TestAccEKSNodeGroup_Scaling_maxSize
=== PAUSE TestAccEKSNodeGroup_Scaling_maxSize
=== RUN   TestAccEKSNodeGroup_Scaling_minSize
=== PAUSE TestAccEKSNodeGroup_Scaling_minSize
=== RUN   TestAccEKSNodeGroup_ScalingZeroDesiredSize_minSize
=== PAUSE TestAccEKSNodeGroup_ScalingZeroDesiredSize_minSize
=== RUN   TestAccEKSNodeGroup_tags
=== PAUSE TestAccEKSNodeGroup_tags
=== RUN   TestAccEKSNodeGroup_taints
=== PAUSE TestAccEKSNodeGroup_taints
=== RUN   TestAccEKSNodeGroup_update
=== PAUSE TestAccEKSNodeGroup_update
=== RUN   TestAccEKSNodeGroup_version
=== PAUSE TestAccEKSNodeGroup_version
=== CONT  TestAccEKSNodeGroup_basic
=== CONT  TestAccEKSNodeGroup_LaunchTemplate_version
=== CONT  TestAccEKSNodeGroup_forceUpdateVersion
=== CONT  TestAccEKSNodeGroup_LaunchTemplate_name
--- PASS: TestAccEKSNodeGroup_basic (1225.11s)
=== CONT  TestAccEKSNodeGroup_LaunchTemplate_id
--- PASS: TestAccEKSNodeGroup_LaunchTemplate_version (1499.99s)
=== CONT  TestAccEKSNodeGroup_labels
--- PASS: TestAccEKSNodeGroup_LaunchTemplate_name (1504.65s)
=== CONT  TestAccEKSNodeGroup_InstanceTypes_single
--- PASS: TestAccEKSNodeGroup_forceUpdateVersion (1895.12s)
=== CONT  TestAccEKSNodeGroup_InstanceTypes_multiple
--- PASS: TestAccEKSNodeGroup_InstanceTypes_single (1106.04s)
=== CONT  TestAccEKSNodeGroup_amiType
--- PASS: TestAccEKSNodeGroup_labels (1114.11s)
=== CONT  TestAccEKSNodeGroup_diskSize
--- PASS: TestAccEKSNodeGroup_LaunchTemplate_id (1796.41s)
=== CONT  TestAccEKSNodeGroup_Scaling_minSize
--- PASS: TestAccEKSNodeGroup_InstanceTypes_multiple (1098.36s)
=== CONT  TestAccEKSNodeGroup_CapacityType_spot
--- PASS: TestAccEKSNodeGroup_diskSize (1233.28s)
=== CONT  TestAccEKSNodeGroup_version
--- PASS: TestAccEKSNodeGroup_Scaling_minSize (1143.58s)
=== CONT  TestAccEKSNodeGroup_taints
--- PASS: TestAccEKSNodeGroup_CapacityType_spot (1309.07s)
=== CONT  TestAccEKSNodeGroup_tags
--- PASS: TestAccEKSNodeGroup_taints (933.49s)
=== CONT  TestAccEKSNodeGroup_update
--- PASS: TestAccEKSNodeGroup_amiType (1249.75s)
=== CONT  TestAccEKSNodeGroup_ScalingZeroDesiredSize_minSize
--- PASS: TestAccEKSNodeGroup_tags (1322.67s)
=== CONT  TestAccEKSNodeGroup_RemoteAccess_sourceSecurityGroupIDs
--- PASS: TestAccEKSNodeGroup_update (1260.35s)
=== CONT  TestAccEKSNodeGroup_releaseVersion
--- PASS: TestAccEKSNodeGroup_ScalingZeroDesiredSize_minSize (930.51s)
=== CONT  TestAccEKSNodeGroup_Scaling_maxSize
--- PASS: TestAccEKSNodeGroup_version (2535.18s)
=== CONT  TestAccEKSNodeGroup_RemoteAccess_ec2SSHKey
--- PASS: TestAccEKSNodeGroup_RemoteAccess_sourceSecurityGroupIDs (1266.83s)
=== CONT  TestAccEKSNodeGroup_Scaling_desiredSize
--- PASS: TestAccEKSNodeGroup_RemoteAccess_ec2SSHKey (993.01s)
=== CONT  TestAccEKSNodeGroup_nodeRepairConfig
--- PASS: TestAccEKSNodeGroup_Scaling_maxSize (1304.63s)
=== CONT  TestAccEKSNodeGroup_namePrefix
--- PASS: TestAccEKSNodeGroup_Scaling_desiredSize (1022.75s)
=== CONT  TestAccEKSNodeGroup_disappears
--- PASS: TestAccEKSNodeGroup_releaseVersion (1987.35s)
=== CONT  TestAccEKSNodeGroup_Name_generated
--- PASS: TestAccEKSNodeGroup_namePrefix (485.11s)
--- PASS: TestAccEKSNodeGroup_nodeRepairConfig (709.72s)
--- PASS: TestAccEKSNodeGroup_disappears (425.93s)
--- PASS: TestAccEKSNodeGroup_Name_generated (560.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	8606.553s
```

**Review by nam054 — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@hjoshi123 Thanks for the contribution :tada: :clap:.

**Comment by hjoshi123** [comment]
@ewbankkit thank you for pushing necessary changes and making the PR more cleaner.. will keep a note and make my next contribution better

**Review by nam054 — APPROVED** [review]
LGTM 🚀

**Pull request merged**
