### PR TITLE
Add aws_mskconnect_custom_plugin resource

### PR DESCRIPTION
**Pull request by rtim75**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #20942

Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafkaconnect/... -v -count 1 -parallel 20 -run=TestAcc.* -timeout 180m
=== RUN   TestAccKafkaConnectCustomPluginDataSource_basic
=== PAUSE TestAccKafkaConnectCustomPluginDataSource_basic
=== RUN   TestAccKafkaConnectCustomPlugin_basic
=== PAUSE TestAccKafkaConnectCustomPlugin_basic
=== RUN   TestAccKafkaConnectCustomPlugin_description
=== PAUSE TestAccKafkaConnectCustomPlugin_description
=== RUN   TestAccKafkaConnectCustomPlugin_contentType
=== PAUSE TestAccKafkaConnectCustomPlugin_contentType
=== RUN   TestAccKafkaConnectCustomPlugin_objectVersion
=== PAUSE TestAccKafkaConnectCustomPlugin_objectVersion
=== CONT  TestAccKafkaConnectCustomPluginDataSource_basic
=== CONT  TestAccKafkaConnectCustomPlugin_contentType
=== CONT  TestAccKafkaConnectCustomPlugin_objectVersion
=== CONT  TestAccKafkaConnectCustomPlugin_description
=== CONT  TestAccKafkaConnectCustomPlugin_basic
--- PASS: TestAccKafkaConnectCustomPlugin_basic (87.22s)
--- PASS: TestAccKafkaConnectCustomPlugin_description (88.05s)
--- PASS: TestAccKafkaConnectCustomPlugin_objectVersion (91.40s)
--- PASS: TestAccKafkaConnectCustomPluginDataSource_basic (92.45s)
--- PASS: TestAccKafkaConnectCustomPlugin_contentType (175.87s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafkaconnect       177.752s
```

### CODE REVIEW

**Comment by rtim75** [comment]
I'm looking at the [Kafka Connect API reference](https://docs.aws.amazon.com/MCK/latest/mck/Welcome.html), and the thing that stands up the most is the fact that custom plugins and worker configurations don't have update and delete methods. While it's ok for the update, I'm not really sure how should be handled for the delete. Currently I just have an empty method that basically does nothing.

**Comment by rtim75** [comment]
> Currently I just have an empty method that basically does nothing.

And looking at the `CertificateAuthorityCertificate` implementation I assume it's ok.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTARGS='-run=TestAccKafkaConnectCustomPlugin_\|TestAccKafkaConnectCustomPluginDataSource_' PKG_NAME=internal/service/kafkaconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafkaconnect/... -v -count 1 -parallel 20 -run=TestAccKafkaConnectCustomPlugin_\|TestAccKafkaConnectCustomPluginDataSource_ -timeout 180m
=== RUN   TestAccKafkaConnectCustomPluginDataSource_basic
=== PAUSE TestAccKafkaConnectCustomPluginDataSource_basic
=== RUN   TestAccKafkaConnectCustomPlugin_basic
=== PAUSE TestAccKafkaConnectCustomPlugin_basic
=== RUN   TestAccKafkaConnectCustomPlugin_description
=== PAUSE TestAccKafkaConnectCustomPlugin_description
=== RUN   TestAccKafkaConnectCustomPlugin_contentType
=== PAUSE TestAccKafkaConnectCustomPlugin_contentType
=== RUN   TestAccKafkaConnectCustomPlugin_objectVersion
=== PAUSE TestAccKafkaConnectCustomPlugin_objectVersion
=== CONT  TestAccKafkaConnectCustomPluginDataSource_basic
=== CONT  TestAccKafkaConnectCustomPlugin_contentType
=== CONT  TestAccKafkaConnectCustomPlugin_description
=== CONT  TestAccKafkaConnectCustomPlugin_basic
=== CONT  TestAccKafkaConnectCustomPlugin_objectVersion
--- PASS: TestAccKafkaConnectCustomPlugin_objectVersion (76.10s)
--- PASS: TestAccKafkaConnectCustomPlugin_description (82.20s)
--- PASS: TestAccKafkaConnectCustomPlugin_basic (82.43s)
--- PASS: TestAccKafkaConnectCustomPluginDataSource_basic (84.47s)
--- PASS: TestAccKafkaConnectCustomPlugin_contentType (130.55s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafkaconnect	135.948s
```

##### GovCloud

```console
% make testacc TESTARGS='-run=TestAccKafkaConnectCustomPlugin_\|TestAccKafkaConnectCustomPluginDataSource_' PKG_NAME=internal/service/kafkaconnect
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafkaconnect/... -v -count 1 -parallel 20 -run=TestAccKafkaConnectCustomPlugin_\|TestAccKafkaConnectCustomPluginDataSource_ -timeout 180m
=== RUN   TestAccKafkaConnectCustomPluginDataSource_basic
=== PAUSE TestAccKafkaConnectCustomPluginDataSource_basic
=== RUN   TestAccKafkaConnectCustomPlugin_basic
=== PAUSE TestAccKafkaConnectCustomPlugin_basic
=== RUN   TestAccKafkaConnectCustomPlugin_description
=== PAUSE TestAccKafkaConnectCustomPlugin_description
=== RUN   TestAccKafkaConnectCustomPlugin_contentType
=== PAUSE TestAccKafkaConnectCustomPlugin_contentType
=== RUN   TestAccKafkaConnectCustomPlugin_objectVersion
=== PAUSE TestAccKafkaConnectCustomPlugin_objectVersion
=== CONT  TestAccKafkaConnectCustomPluginDataSource_basic
=== CONT  TestAccKafkaConnectCustomPlugin_contentType
=== CONT  TestAccKafkaConnectCustomPlugin_description
=== CONT  TestAccKafkaConnectCustomPlugin_basic
=== CONT  TestAccKafkaConnectCustomPlugin_objectVersion
=== CONT  TestAccKafkaConnectCustomPluginDataSource_basic
    acctest.go:608: skipping tests; partition aws-us-gov does not support kafkaconnect service
=== CONT  TestAccKafkaConnectCustomPlugin_contentType
    acctest.go:608: skipping tests; partition aws-us-gov does not support kafkaconnect service
--- SKIP: TestAccKafkaConnectCustomPluginDataSource_basic (1.48s)
=== CONT  TestAccKafkaConnectCustomPlugin_description
    acctest.go:608: skipping tests; partition aws-us-gov does not support kafkaconnect service
--- SKIP: TestAccKafkaConnectCustomPlugin_contentType (1.48s)
--- SKIP: TestAccKafkaConnectCustomPlugin_description (1.48s)
=== CONT  TestAccKafkaConnectCustomPlugin_objectVersion
    acctest.go:608: skipping tests; partition aws-us-gov does not support kafkaconnect service
--- SKIP: TestAccKafkaConnectCustomPlugin_objectVersion (1.48s)
=== CONT  TestAccKafkaConnectCustomPlugin_basic
    acctest.go:608: skipping tests; partition aws-us-gov does not support kafkaconnect service
--- SKIP: TestAccKafkaConnectCustomPlugin_basic (1.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafkaconnect	7.157s
```

**Comment by ewbankkit** [comment]
@rtim75 Thanks for the contribution :tada: :clap:.

**Pull request merged**
