### PR TITLE
New Data Sources: aws_apigatewayv2_api(s) 

### LINKED ISSUE #12954: New data source: aws_apigatewayv2_api
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a new data source for a single API Gateway v2 API (HTTP or WebSocket API).

Arguments could be:
* `api_id`
* `name`
* `tags`

### New or Affected Resource(s)

* `aws_apigatewayv2_api`

### Potential Terraform Configuration

```hcl
data "aws_apigatewayv2_api" "example" {
  api_id = "abcd1234"
}
```

### References

Related:
* https://github.com/terraform-providers/terraform-provider-aws/pull/8842
* https://github.com/terraform-providers/terraform-provider-aws/issues/7004
* https://github.com/terraform-providers/terraform-provider-aws/issues/11148

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12954.

Output from acceptance testing:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2ApiDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2ApiDataSource_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2ApiDataSource_Http
=== PAUSE TestAccAWSAPIGatewayV2ApiDataSource_Http
=== RUN   TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== PAUSE TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== CONT  TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== CONT  TestAccAWSAPIGatewayV2ApiDataSource_Http
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_WebSocket (27.25s)
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_Http (27.26s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	27.315s
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2ApisDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2ApisDataSource_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_Name
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Name (28.61s)
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType (27.14s)
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_Tags
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Tags (28.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	83.933s
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
@ewbankkit can you rebase?

**Comment by michaelmerrill** [comment]
@ewbankkit any update on this?

**Review by DrFaust92 — APPROVED** [review]
LGTM :rocket: 

```
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Name (42.07s)
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType (33.09s)
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Tags (37.05s)
--- PASS: TestAccAWSAPIGatewayV2ApiMapping_basic (194.66s)
    --- PASS: TestAccAWSAPIGatewayV2ApiMapping_basic/createCertificate (4.24s)
    --- PASS: TestAccAWSAPIGatewayV2ApiMapping_basic/basic (54.27s)
    --- PASS: TestAccAWSAPIGatewayV2ApiMapping_basic/disappears (47.45s)
    --- PASS: TestAccAWSAPIGatewayV2ApiMapping_basic/ApiMappingKey (88.70s)
--- PASS: TestAccAWSAPIGatewayV2Api_disappears (27.47s)
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_WebSocket (33.08s)
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_Http (35.00s)
--- PASS: TestAccAWSAPIGatewayV2Api_basicHttp (38.15s)
--- PASS: TestAccAWSAPIGatewayV2Api_basicWebSocket (39.52s)
--- PASS: TestAccAWSAPIGatewayV2Api_QuickCreate (41.62s)
--- PASS: TestAccAWSAPIGatewayV2Api_Tags (64.60s)
--- PASS: TestAccAWSAPIGatewayV2Api_Openapi_WithTags (79.89s)
--- PASS: TestAccAWSAPIGatewayV2Api_Openapi (80.65s)
--- PASS: TestAccAWSAPIGatewayV2Api_OpenapiWithMoreFields (83.20s)
--- PASS: TestAccAWSAPIGatewayV2Api_CorsConfiguration (89.98s)
--- PASS: TestAccAWSAPIGatewayV2Api_Openapi_WithCorsConfiguration (100.33s)
--- PASS: TestAccAWSAPIGatewayV2Api_AllAttributesWebSocket (110.92s)
--- PASS: TestAccAWSAPIGatewayV2Api_AllAttributesHttp (114.23s)
```

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @ewbankkit!

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2ApiDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2ApiDataSource_ -timeout 120m
go: downloading github.com/hashicorp/terraform-exec v0.13.0
=== RUN   TestAccAWSAPIGatewayV2ApiDataSource_Http
=== PAUSE TestAccAWSAPIGatewayV2ApiDataSource_Http
=== RUN   TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== PAUSE TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== CONT  TestAccAWSAPIGatewayV2ApiDataSource_Http
=== CONT  TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_Http (15.03s)
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_WebSocket (15.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       22.761s

make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2ApisDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2ApisDataSource_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_Name
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Name (15.25s)
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType (12.66s)
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_Tags
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Tags (25.22s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       56.303s
```

Verified Acceptance Tests in GovCloud (us-gov-west-1)

```console
make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2ApiDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2ApiDataSource_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2ApiDataSource_Http
=== PAUSE TestAccAWSAPIGatewayV2ApiDataSource_Http
=== RUN   TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== PAUSE TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
=== CONT  TestAccAWSAPIGatewayV2ApiDataSource_Http
=== CONT  TestAccAWSAPIGatewayV2ApiDataSource_WebSocket
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_Http (10.14s)
--- PASS: TestAccAWSAPIGatewayV2ApiDataSource_WebSocket (10.62s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       13.733s

make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSAPIGatewayV2ApisDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayV2ApisDataSource_ -timeout 120m
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_Name
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Name (10.22s)
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType
x--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_ProtocolType (10.98s)
=== RUN   TestAccAWSAPIGatewayV2ApisDataSource_Tags
--- PASS: TestAccAWSAPIGatewayV2ApisDataSource_Tags (12.56s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       36.993s
```

**Pull request merged**
