### PR TITLE
r/cloudfront_distribution - plan time validations

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloudFrontDistribution_'
--- PASS: TestAccAWSCloudFrontDistribution_disappears (247.95s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_TrustedSigners (261.96s)
--- PASS: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn (262.35s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (291.10s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Headers (293.11s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_TrustedKeyGroups (300.68s)
--- PASS: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn_ConflictsWithCloudFrontDefaultCertificate (303.78s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_RealtimeLogConfigArn (303.95s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyOriginID (8.62s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_RealtimeLogConfigArn (312.38s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyDomainName (8.82s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (357.68s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Headers (357.95s)
--- PASS: TestAccAWSCloudFrontDistribution_RetainOnDelete (391.55s)
--- PASS: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (413.54s)
--- PASS: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (414.89s)
--- PASS: TestAccAWSCloudFrontDistribution_OriginGroups (418.05s)
--- PASS: TestAccAWSCloudFrontDistribution_HTTP11Config (421.73s)
--- PASS: TestAccAWSCloudFrontDistribution_originPolicyOrdered (442.64s)
--- PASS: TestAccAWSCloudFrontDistribution_WaitForDeployment (493.02s)
--- PASS: TestAccAWSCloudFrontDistribution_Enabled (576.60s)
--- PASS: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (371.81s)
--- PASS: TestAccAWSCloudFrontDistribution_forwardedValuesToCachePolicy (620.52s)
--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (359.87s)
--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehaviorCachePolicy (359.49s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_ConnectionTimeout (450.69s)
--- PASS: TestAccAWSCloudFrontDistribution_originPolicyDefault (386.27s)
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (434.75s)
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (387.30s)
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (434.43s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_OriginShield (523.10s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_ConnectionAttempts (483.23s)
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (668.31s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
rebased + tested

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Comment by danholesinsky** [comment]
Hi @DrFaust92 , plz one question - what if we have increased quota for origin_read_timeout in aws? We are facing error: expected origin.4.custom_origin_config.0.origin_read_timeout to be in the range (1 - 60), got 180. Tf aws provider version 3.71.0

**Comment by tlamr** [comment]
Hello @DrFaust92 @ewbankkit, as @danholesinsky points out, this causes the regression to those that have this value overridden. AWS support allows it to be set up to 180 seconds. Shouldn't the validation be able to respect that settings?
Cheers,
Tomas

**Comment by DrFaust92** [comment]
Hi,

Values were determined according to aws docs https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_CustomOriginConfig.html

it seems we need to remove that validation /:. ill open a ticket to remove unless someone can tell me whats the hard limit? 180? so we can set it to that.

**Comment by tlamr** [comment]
Hi @DrFaust92, thanks for looking into this. Yep, the hard limit is indeed 180s. We confirmed this multiple times with them.
Cheers,
Toams

**Comment by DrFaust92** [comment]
Ill open a follow up PR

**Pull request merged**
