### PR TITLE
aws_autoscaling_group `initial_lifecycle_hook` set `ForceNew: true`

### LINKED ISSUE #4714: changes to initial_lifecycle_hook block of ASG aren't triggering a recreate
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.3
+ provider.aws v1.21.0

### Affected Resource(s)

* aws_autoscaling_group

### Terraform Configuration Files

```hcl
resource "aws_autoscaling_group" "asg" {
...

  initial_lifecycle_hook {
    name                 = "instance_launch"
    default_result       = "ABANDON"
    heartbeat_timeout    = 30
    lifecycle_transition = "autoscaling:EC2_INSTANCE_LAUNCHING"

    notification_target_arn = "<some SNS ARN here>"
    role_arn                = "<some IAM role arn here>"
  }

  lifecycle {
    create_before_destroy = true
  }
}
```

### Expected Behavior

When attempting to set/update a initial_lifecycle_hook in an existing auto scaling group, I would expect that ASG to be recreated, as to apply said hook configuration.

### Actual Behavior

A Terraform plan produces an inline update for the hook configuration, which actually does nothing, as this block is only intended for newly created ASGs.

### Steps to Reproduce

1. Have an existing auto scaling group without an initial_lifecycle_hook block
2. `terraform apply` it
3. Modify ASG to have an initial_lifecycle_hook block
2. `terraform plan` produces an inline update, and applying it results in nothing getting done.

### LINKED ISSUE #19714: Change to aws_autoscaling_group removed lifecycle hook
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.13.6
provider.aws 3.34.0

### Affected Resource(s)

* aws_autoscaling_group

### Expected Behavior

The lifecycle hook was added via the initial_lifecycle_hook argument on the aws_autoscaling_group resource.

When updating the auto scaling group (in this case, by updating the launch template by updating instance type, which results in updating the auto scaling group to reference the newer version of the launch template, I expect the lifecycle hook to remain on the auto scaling group. Subsequent runs do not recreate the lifecycle hook.

What is also odd is I'm not sure how the lifecycle hook got added in the first place via an update operation. I see nothing in the code (https://github.com/hashicorp/terraform-provider-aws/blob/bf230a0d3debf5f769b7a238f7af451f34a320db/aws/resource_aws_autoscaling_group.go#L984) that would suggest it would add the lifecycle hook, only on a create operation.

### Actual Behavior

The lifecycle hook no longer exists in AWS console. 

* #0000

### PR DESCRIPTION
**Pull request by nitrocode**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19714
Closes #4714

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by nitrocode** [comment]
cc: @breathingdust Friendly ping for this small PR. Could I please get a review or what I can do to get this approved?

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by nitrocode** [comment]
@zhelding @breathingdust hi all, just a friendly bump. is there anything else i can do to get this in the next release?

**Comment by zhelding** [comment]
Hi @nitrocode! 

No further action is required on your part. We will now review your PR as part of our standard triage prioritization process ([see here](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/faq.md#how-do-you-decide-what-gets-merged-for-each-release)). Unfortunately, we can't guarantee that your PR will get a review in a timely manner, but we will get to it as soon as we have capacity.

Thanks again for your contribution!

**Review by YakDriver — APPROVED** [review]
Thank you 🎉 

```console
% make testacc TESTS=TestAccAutoScalingGroup PKG=autoscaling
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 20 -run='TestAccAutoScalingGroup'  -timeout 180m
--- PASS: TestAccAutoScalingGroupDataSource_basic (47.33s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandAllocationStrategy (50.20s)
--- PASS: TestAccAutoScalingGroup_launchTemplate (54.07s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_launchTemplateName (59.79s)
--- PASS: TestAccAutoScalingGroup_LaunchTemplate_iamInstanceProfile (68.90s)
--- PASS: TestAccAutoScalingGroup_launchTempPartitionNum (72.32s)
--- PASS: TestAccAutoScalingGroup_classicVPCZoneIdentifier (76.04s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_updateToZeroOnDemandBaseCapacity (77.72s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceType (82.61s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateLaunchTemplateSpecification_version (88.10s)
--- PASS: TestAccAutoScalingGroup_mixedInstancesPolicy (47.59s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicy_capacityRebalance (46.60s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandPercentageAboveBaseCapacity (100.92s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotAllocationStrategy (53.29s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_instanceTypeWithLaunchTemplateSpecification (115.87s)
--- PASS: TestAccAutoScalingGroup_withPlacementGroup (128.40s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotMaxPrice (84.57s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_spotInstancePools (61.53s)
--- PASS: TestAccAutoScalingGroup_serviceLinkedRoleARN (40.75s)
--- PASS: TestAccAutoScalingGroup_Destroy_whenProtectedFromScaleIn (150.83s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyInstancesDistribution_onDemandBaseCapacity (154.99s)
--- PASS: TestAccAutoScalingGroup_namePrefix (48.50s)
--- PASS: TestAccAutoScalingGroup_maxInstanceLifetime (71.40s)
--- PASS: TestAccAutoScalingGroup_withMetrics (85.55s)
--- PASS: TestAccAutoScalingGroup_MixedInstancesPolicyLaunchTemplateOverride_weightedCapacity (195.36s)
--- PASS: TestAccAutoScalingGroup_LaunchTemplate_update (196.85s)
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_triggers (201.62s)
--- PASS: TestAccAutoScalingGroup_vpcUpdates (78.86s)
--- PASS: TestAccAutoScalingGroup_ALB_targetGroups (129.71s)
--- PASS: TestAccAutoScalingGroupTag_value (66.13s)
--- PASS: TestAccAutoScalingGroup_Name_generated (65.48s)
--- PASS: TestAccAutoScalingGroup_targetGroupARNs (142.47s)
--- PASS: TestAccAutoScalingGroupTag_basic (51.04s)
--- PASS: TestAccAutoScalingGroupTag_disappears (48.72s)
--- PASS: TestAccAutoScalingGroupDataSource_launchTemplate (55.33s)
--- PASS: TestAccAutoScalingGroup_warmPool (283.03s)
--- PASS: TestAccAutoScalingGroup_enablingMetrics (171.11s)
--- PASS: TestAccAutoScalingGroup_terminationPolicies (120.62s)
--- PASS: TestAccAutoScalingGroup_suspendingProcesses (184.32s)
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_start (259.28s)
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_basic (260.41s)
--- PASS: TestAccAutoScalingGroup_tags (238.03s)
--- PASS: TestAccAutoScalingGroup_withLoadBalancer (254.34s)
--- PASS: TestAccAutoScalingGroup_basic (232.32s)
--- PASS: TestAccAutoScalingGroup_ALBTargetGroups_elbCapacity (333.71s)
--- PASS: TestAccAutoScalingGroup_initialLifecycleHook (203.23s)
--- PASS: TestAccAutoScalingGroup_WithLoadBalancer_toTargetGroup (350.95s)
--- PASS: TestAccAutoScalingGroup_loadBalancers (402.54s)
--- PASS: TestAccAutoScalingGroupsDataSource_basic (43.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	472.730s
```

**Pull request merged**
