### PR TITLE
Added point_in_time_restore to aws_rds_cluster

### LINKED ISSUE #2321: Feature request: AWS RDS Clone
_This issue was originally opened by @gotoadmin as hashicorp/terraform#16671. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

The RDS instance clone functionality has been introduced by AWS. When could we expect such possibility in Terraform?

### PR DESCRIPTION
**Pull request by tkawachi**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #2321

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- resource/aws_rds_cluster: Add `point_in_time_restore` attribute.
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSRDSCluster_pointInTimeRestore'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSRDSCluster_pointInTimeRestore -timeout 120m
=== RUN   TestAccAWSRDSCluster_pointInTimeRestore
=== PAUSE TestAccAWSRDSCluster_pointInTimeRestore
=== CONT  TestAccAWSRDSCluster_pointInTimeRestore
--- PASS: TestAccAWSRDSCluster_pointInTimeRestore (370.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	370.342s
```

### CODE REVIEW

**Comment by GryshchenkoAndrii** [comment]
@tkawachi what's the situation on this? Are we going forward with the change?

**Comment by tkawachi** [comment]
Unfortunately, there are too many conflicts to simply rebase. It would be great if someone could take over as I don't have the time to do so.

**Comment by lorengordon** [comment]
Is this pr duplicating the feature this one is implementing? https://github.com/hashicorp/terraform-provider-aws/pull/7031?

**Comment by anGie44** [comment]
I believe so @lorengordon. @tkawachi please note #7031 is currently under review and aims to add the argument presented here.

**Comment by tkawachi** [comment]
@lorengordon @anGie44 It seems that #7031 is tackling the same feature (and still alive 😄 ).

**Pull request closed without merging**
