### PR TITLE
fix route table for Amazon FSx for NetApp ONTAP routes and tag

### LINKED ISSUE #20285: Assigning prefixes to Amazon EC2 network interfaces
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon Virtual Private Cloud (VPC) now allows you to assign IPv4 and IPv6 prefixes to your EC2 instances, enabling you to scale and simplify the management of your container and networking applications that require multiple IP addresses on an instance. 

### New or Affected Resource(s)

* [`aws_network_interface`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/network_interface)

### Potential Terraform Configuration

```hcl
resource "aws_network_interface" "example" {
  ipv4_prefix_count = 1
}
```

### References

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-virtual-private-cloud-vpc-customers-can-assign-ip-prefixes-ec2-instances/)
* [User Guide](https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-prefix-eni.html)

Requires [AWS SDK v1.40.6](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.6):

* #20281

### LINKED ISSUE #21246: bug: route_table reports Amazon FSx for NetApp ONTAP service routes and tag as configuration change
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.0.8
aws v3.62.0

### Affected Resource(s)

* aws_route_table

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_route_table" "PrivateRT" {    
    vpc_id = var.vpc
    route {
    cidr_block = "0.0.0.0/0"             
    nat_gateway_id = aws_nat_gateway.NATgw.id
    }
 }

resource "aws_fsx_ontap_file_system" "fsxontap" {
    storage_capacity    = 1024
    subnet_ids          = [var.privatesubnet_1, var.privatesubnet_2]
    deployment_type     = "MULTI_AZ_1"
    throughput_capacity = 512
    preferred_subnet_id = var.privatesubnet_1
    route_table_ids = [aws_route_table.PrivateRT.id]
}
```

### Expected Behavior

When running a `terraform plan` after deploying an aws_fsx_ontap_file_system resource and specifying a terraform managed route_table the output should be **"No changes. Your infrastructure matches the configuration."**

### Actual Behavior

FSx route that is managed by the Amazon FSx for NetApp ONTAP in route table and FSX tag shows as changed. 

"aws_route_table.PrivateRT will be updated in-place"
~ resource "aws_route_table" "PrivateRT" {
 ~ route            = [
 ~ tags             = {
 ~ tags_all         = {

**"Plan: 0 to add, 1 to change, 0 to destroy."**

### Steps to Reproduce

1. `terraform apply`
2. `terraform plan`

### References

* #20778

### PR DESCRIPTION
**Pull request by awsaxeman**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21246.
Relates #20951.
Relates #21406.
Closes #20285.

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccAWSRouteTable_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSRouteTable_basic -timeout 180m
=== RUN   TestAccAWSRouteTable_basic
=== PAUSE TestAccAWSRouteTable_basic
=== CONT  TestAccAWSRouteTable_basic
--- PASS: TestAccAWSRouteTable_basic (26.17s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       30.686s
...
```

### CODE REVIEW

**Comment by awsaxeman** [comment]
Output from new acceptance tests:

TF_ACC=1 go test ./internal/service/ec2 -v -count 1 -parallel 1 -run='TestAccEC2RouteTable_fsxRouteAndTag' -timeout=180m
=== RUN   TestAccEC2RouteTable_fsxRouteAndTag
=== PAUSE TestAccEC2RouteTable_fsxRouteAndTag
=== CONT  TestAccEC2RouteTable_fsxRouteAndTag
--- PASS: TestAccEC2RouteTable_fsxRouteAndTag (2461.82s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        2465.175s


TF_ACC=1 go test ./internal/service/ec2 -v -count 1 -parallel 1 -run='TestAccEC2RouteTableDataSource_fsxRouteAndTag' -timeout=180m 
=== RUN   TestAccEC2RouteTableDataSource_fsxRouteAndTag
=== PAUSE TestAccEC2RouteTableDataSource_fsxRouteAndTag
=== CONT  TestAccEC2RouteTableDataSource_fsxRouteAndTag
--- PASS: TestAccEC2RouteTableDataSource_fsxRouteAndTag (2294.85s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        2298.306s

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by awsaxeman** [comment]
@ewbankkit I already raised the tag naming to our FSx service team to see if it was possible to use the `aws:` tag going forward but that is still TBD. Two thoughts here, 1/would it makes sense for us to fold this logic into the `ignoreAWS()` function or create an `ignoreFSX()` function in `key_value_tags.go`? There seems to be some other service specific ignores such as `ignoreRds()` already there. 2/I would be concerned with customers having to add that to the `ignore_tags` for the provider because they would have to be aware of this ahead of time, it could be different teams working on provider config, fsx, and route tables, and it could be prone to errors.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc PKG_NAME=internal/service/fsx TESTARGS='-run=TestAccFSxOntapFileSystem_routeTableIDs'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run=TestAccFSxOntapFileSystem_routeTableIDs -timeout 180m
=== RUN   TestAccFSxOntapFileSystem_routeTableIDs
=== PAUSE TestAccFSxOntapFileSystem_routeTableIDs
=== CONT  TestAccFSxOntapFileSystem_routeTableIDs
--- PASS: TestAccFSxOntapFileSystem_routeTableIDs (2442.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	2444.924s
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2RouteTableDataSource_\|TestAccEC2RouteTable_' ACCTEST_PARALLELISM=5
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 5 -run=TestAccEC2RouteTableDataSource_\|TestAccEC2RouteTable_ -timeout 180m
=== RUN   TestAccEC2RouteTableDataSource_basic
=== PAUSE TestAccEC2RouteTableDataSource_basic
=== RUN   TestAccEC2RouteTableDataSource_main
=== PAUSE TestAccEC2RouteTableDataSource_main
=== RUN   TestAccEC2RouteTable_basic
=== PAUSE TestAccEC2RouteTable_basic
=== RUN   TestAccEC2RouteTable_disappears
=== PAUSE TestAccEC2RouteTable_disappears
=== RUN   TestAccEC2RouteTable_Disappears_subnetAssociation
=== PAUSE TestAccEC2RouteTable_Disappears_subnetAssociation
=== RUN   TestAccEC2RouteTable_ipv4ToInternetGateway
=== PAUSE TestAccEC2RouteTable_ipv4ToInternetGateway
=== RUN   TestAccEC2RouteTable_ipv4ToInstance
=== PAUSE TestAccEC2RouteTable_ipv4ToInstance
=== RUN   TestAccEC2RouteTable_ipv6ToEgressOnlyInternetGateway
=== PAUSE TestAccEC2RouteTable_ipv6ToEgressOnlyInternetGateway
=== RUN   TestAccEC2RouteTable_tags
=== PAUSE TestAccEC2RouteTable_tags
=== RUN   TestAccEC2RouteTable_requireRouteDestination
=== PAUSE TestAccEC2RouteTable_requireRouteDestination
=== RUN   TestAccEC2RouteTable_requireRouteTarget
=== PAUSE TestAccEC2RouteTable_requireRouteTarget
=== RUN   TestAccEC2RouteTable_Route_mode
=== PAUSE TestAccEC2RouteTable_Route_mode
=== RUN   TestAccEC2RouteTable_ipv4ToTransitGateway
=== PAUSE TestAccEC2RouteTable_ipv4ToTransitGateway
=== RUN   TestAccEC2RouteTable_ipv4ToVPCEndpoint
=== PAUSE TestAccEC2RouteTable_ipv4ToVPCEndpoint
=== RUN   TestAccEC2RouteTable_ipv4ToCarrierGateway
=== PAUSE TestAccEC2RouteTable_ipv4ToCarrierGateway
=== RUN   TestAccEC2RouteTable_ipv4ToLocalGateway
=== PAUSE TestAccEC2RouteTable_ipv4ToLocalGateway
=== RUN   TestAccEC2RouteTable_ipv4ToVPCPeeringConnection
=== PAUSE TestAccEC2RouteTable_ipv4ToVPCPeeringConnection
=== RUN   TestAccEC2RouteTable_vgwRoutePropagation
=== PAUSE TestAccEC2RouteTable_vgwRoutePropagation
=== RUN   TestAccEC2RouteTable_conditionalCIDRBlock
=== PAUSE TestAccEC2RouteTable_conditionalCIDRBlock
=== RUN   TestAccEC2RouteTable_ipv4ToNatGateway
=== PAUSE TestAccEC2RouteTable_ipv4ToNatGateway
=== RUN   TestAccEC2RouteTable_IPv6ToNetworkInterface_unattached
=== PAUSE TestAccEC2RouteTable_IPv6ToNetworkInterface_unattached
=== RUN   TestAccEC2RouteTable_IPv4ToNetworkInterfaces_unattached
=== PAUSE TestAccEC2RouteTable_IPv4ToNetworkInterfaces_unattached
=== RUN   TestAccEC2RouteTable_vpcMultipleCIDRs
=== PAUSE TestAccEC2RouteTable_vpcMultipleCIDRs
=== RUN   TestAccEC2RouteTable_vpcClassicLink
=== PAUSE TestAccEC2RouteTable_vpcClassicLink
=== RUN   TestAccEC2RouteTable_gatewayVPCEndpoint
=== PAUSE TestAccEC2RouteTable_gatewayVPCEndpoint
=== RUN   TestAccEC2RouteTable_multipleRoutes
=== PAUSE TestAccEC2RouteTable_multipleRoutes
=== RUN   TestAccEC2RouteTable_prefixListToInternetGateway
=== PAUSE TestAccEC2RouteTable_prefixListToInternetGateway
=== CONT  TestAccEC2RouteTableDataSource_basic
=== CONT  TestAccEC2RouteTable_ipv4ToLocalGateway
=== CONT  TestAccEC2RouteTable_prefixListToInternetGateway
=== CONT  TestAccEC2RouteTable_tags
=== CONT  TestAccEC2RouteTable_multipleRoutes
=== CONT  TestAccEC2RouteTable_ipv4ToLocalGateway
    acctest.go:1955: skipping since no Outposts found
--- SKIP: TestAccEC2RouteTable_ipv4ToLocalGateway (1.42s)
=== CONT  TestAccEC2RouteTable_gatewayVPCEndpoint
--- PASS: TestAccEC2RouteTableDataSource_basic (38.52s)
=== CONT  TestAccEC2RouteTable_vpcClassicLink
--- PASS: TestAccEC2RouteTable_prefixListToInternetGateway (40.35s)
=== CONT  TestAccEC2RouteTable_vpcMultipleCIDRs
--- PASS: TestAccEC2RouteTable_gatewayVPCEndpoint (39.27s)
=== CONT  TestAccEC2RouteTable_IPv4ToNetworkInterfaces_unattached
--- PASS: TestAccEC2RouteTable_tags (61.12s)
=== CONT  TestAccEC2RouteTable_IPv6ToNetworkInterface_unattached
--- PASS: TestAccEC2RouteTable_vpcClassicLink (25.52s)
=== CONT  TestAccEC2RouteTable_ipv4ToNatGateway
--- PASS: TestAccEC2RouteTable_vpcMultipleCIDRs (47.87s)
=== CONT  TestAccEC2RouteTable_conditionalCIDRBlock
--- PASS: TestAccEC2RouteTable_IPv6ToNetworkInterface_unattached (64.22s)
=== CONT  TestAccEC2RouteTable_vgwRoutePropagation
--- PASS: TestAccEC2RouteTable_conditionalCIDRBlock (61.23s)
=== CONT  TestAccEC2RouteTable_ipv4ToVPCPeeringConnection
--- PASS: TestAccEC2RouteTable_IPv4ToNetworkInterfaces_unattached (141.08s)
=== CONT  TestAccEC2RouteTable_ipv4ToTransitGateway
--- PASS: TestAccEC2RouteTable_ipv4ToVPCPeeringConnection (32.68s)
=== CONT  TestAccEC2RouteTable_ipv4ToCarrierGateway
--- PASS: TestAccEC2RouteTable_ipv4ToCarrierGateway (29.48s)
=== CONT  TestAccEC2RouteTable_ipv4ToVPCEndpoint
--- PASS: TestAccEC2RouteTable_vgwRoutePropagation (95.98s)
=== CONT  TestAccEC2RouteTable_Disappears_subnetAssociation
--- PASS: TestAccEC2RouteTable_Disappears_subnetAssociation (28.74s)
=== CONT  TestAccEC2RouteTable_ipv6ToEgressOnlyInternetGateway
--- PASS: TestAccEC2RouteTable_multipleRoutes (253.11s)
=== CONT  TestAccEC2RouteTable_ipv4ToInstance
--- PASS: TestAccEC2RouteTable_ipv4ToNatGateway (212.28s)
=== CONT  TestAccEC2RouteTable_ipv4ToInternetGateway
--- PASS: TestAccEC2RouteTable_ipv6ToEgressOnlyInternetGateway (45.39s)
=== CONT  TestAccEC2RouteTable_basic
--- PASS: TestAccEC2RouteTable_basic (27.68s)
=== CONT  TestAccEC2RouteTable_disappears
--- PASS: TestAccEC2RouteTable_ipv4ToInternetGateway (66.24s)
=== CONT  TestAccEC2RouteTable_requireRouteTarget
--- PASS: TestAccEC2RouteTable_ipv4ToVPCEndpoint (338.15s)
=== CONT  TestAccEC2RouteTable_Route_mode
--- PASS: TestAccEC2RouteTable_disappears (21.45s)
=== CONT  TestAccEC2RouteTableDataSource_main
--- PASS: TestAccEC2RouteTable_requireRouteTarget (14.70s)
=== CONT  TestAccEC2RouteTable_requireRouteDestination
--- PASS: TestAccEC2RouteTableDataSource_main (21.31s)
--- PASS: TestAccEC2RouteTable_ipv4ToInstance (123.71s)
--- PASS: TestAccEC2RouteTable_Route_mode (79.30s)
--- PASS: TestAccEC2RouteTable_ipv4ToTransitGateway (397.96s)
--- PASS: TestAccEC2RouteTable_requireRouteDestination (332.92s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	693.028s
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2NetworkInterfaceSgAttachment_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2NetworkInterfaceSgAttachment_ -timeout 180m
=== RUN   TestAccEC2NetworkInterfaceSgAttachment_SG_basic
=== PAUSE TestAccEC2NetworkInterfaceSgAttachment_SG_basic
=== RUN   TestAccEC2NetworkInterfaceSgAttachment_SG_disappears
=== PAUSE TestAccEC2NetworkInterfaceSgAttachment_SG_disappears
=== RUN   TestAccEC2NetworkInterfaceSgAttachment_SG_instance
=== PAUSE TestAccEC2NetworkInterfaceSgAttachment_SG_instance
=== RUN   TestAccEC2NetworkInterfaceSgAttachment_SG_multiple
=== PAUSE TestAccEC2NetworkInterfaceSgAttachment_SG_multiple
=== CONT  TestAccEC2NetworkInterfaceSgAttachment_SG_basic
=== CONT  TestAccEC2NetworkInterfaceSgAttachment_SG_multiple
=== CONT  TestAccEC2NetworkInterfaceSgAttachment_SG_instance
=== CONT  TestAccEC2NetworkInterfaceSgAttachment_SG_disappears
--- PASS: TestAccEC2NetworkInterfaceSgAttachment_SG_basic (29.52s)
--- PASS: TestAccEC2NetworkInterfaceSgAttachment_SG_disappears (29.61s)
--- PASS: TestAccEC2NetworkInterfaceSgAttachment_SG_multiple (41.81s)
--- PASS: TestAccEC2NetworkInterfaceSgAttachment_SG_instance (129.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	132.286s
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2NetworkInterfaceAttachment_'     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2NetworkInterfaceAttachment_ -timeout 180m
=== RUN   TestAccEC2NetworkInterfaceAttachment_basic
=== PAUSE TestAccEC2NetworkInterfaceAttachment_basic
=== CONT  TestAccEC2NetworkInterfaceAttachment_basic
--- PASS: TestAccEC2NetworkInterfaceAttachment_basic (325.33s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	329.262s
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2NetworkInterfaceDataSource_'  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2NetworkInterfaceDataSource_ -timeout 180m
=== RUN   TestAccEC2NetworkInterfaceDataSource_basic
=== PAUSE TestAccEC2NetworkInterfaceDataSource_basic
=== RUN   TestAccEC2NetworkInterfaceDataSource_filters
=== PAUSE TestAccEC2NetworkInterfaceDataSource_filters
=== RUN   TestAccEC2NetworkInterfaceDataSource_carrierIPAssociation
=== PAUSE TestAccEC2NetworkInterfaceDataSource_carrierIPAssociation
=== RUN   TestAccEC2NetworkInterfaceDataSource_publicIPAssociation
=== PAUSE TestAccEC2NetworkInterfaceDataSource_publicIPAssociation
=== CONT  TestAccEC2NetworkInterfaceDataSource_basic
=== CONT  TestAccEC2NetworkInterfaceDataSource_publicIPAssociation
=== CONT  TestAccEC2NetworkInterfaceDataSource_carrierIPAssociation
=== CONT  TestAccEC2NetworkInterfaceDataSource_filters
--- PASS: TestAccEC2NetworkInterfaceDataSource_filters (32.03s)
--- PASS: TestAccEC2NetworkInterfaceDataSource_basic (32.63s)
--- PASS: TestAccEC2NetworkInterfaceDataSource_carrierIPAssociation (36.03s)
--- PASS: TestAccEC2NetworkInterfaceDataSource_publicIPAssociation (42.38s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	45.285s
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2NetworkInterfacesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2NetworkInterfacesDataSource_ -timeout 180m
=== RUN   TestAccEC2NetworkInterfacesDataSource_filter
=== PAUSE TestAccEC2NetworkInterfacesDataSource_filter
=== RUN   TestAccEC2NetworkInterfacesDataSource_tags
=== PAUSE TestAccEC2NetworkInterfacesDataSource_tags
=== CONT  TestAccEC2NetworkInterfacesDataSource_filter
=== CONT  TestAccEC2NetworkInterfacesDataSource_tags
--- PASS: TestAccEC2NetworkInterfacesDataSource_tags (29.56s)
--- PASS: TestAccEC2NetworkInterfacesDataSource_filter (29.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	34.858s
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2NetworkInterface_'                   
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2NetworkInterface_ -timeout 180m
=== RUN   TestAccEC2NetworkInterface_ENI_basic
=== PAUSE TestAccEC2NetworkInterface_ENI_basic
=== RUN   TestAccEC2NetworkInterface_ENI_ipv6
=== PAUSE TestAccEC2NetworkInterface_ENI_ipv6
=== RUN   TestAccEC2NetworkInterface_ENI_tags
=== PAUSE TestAccEC2NetworkInterface_ENI_tags
=== RUN   TestAccEC2NetworkInterface_ENI_ipv6Count
=== PAUSE TestAccEC2NetworkInterface_ENI_ipv6Count
=== RUN   TestAccEC2NetworkInterface_ENI_disappears
=== PAUSE TestAccEC2NetworkInterface_ENI_disappears
=== RUN   TestAccEC2NetworkInterface_ENI_description
=== PAUSE TestAccEC2NetworkInterface_ENI_description
=== RUN   TestAccEC2NetworkInterface_ENI_attachment
=== PAUSE TestAccEC2NetworkInterface_ENI_attachment
=== RUN   TestAccEC2NetworkInterface_ENI_ignoreExternalAttachment
=== PAUSE TestAccEC2NetworkInterface_ENI_ignoreExternalAttachment
=== RUN   TestAccEC2NetworkInterface_ENI_sourceDestCheck
=== PAUSE TestAccEC2NetworkInterface_ENI_sourceDestCheck
=== RUN   TestAccEC2NetworkInterface_ENI_privateIPsCount
=== PAUSE TestAccEC2NetworkInterface_ENI_privateIPsCount
=== RUN   TestAccEC2NetworkInterface_ENIInterfaceType_efa
=== PAUSE TestAccEC2NetworkInterface_ENIInterfaceType_efa
=== RUN   TestAccEC2NetworkInterface_ENI_ipv4Prefix
=== PAUSE TestAccEC2NetworkInterface_ENI_ipv4Prefix
=== RUN   TestAccEC2NetworkInterface_ENI_ipv4PrefixCount
=== PAUSE TestAccEC2NetworkInterface_ENI_ipv4PrefixCount
=== RUN   TestAccEC2NetworkInterface_ENI_ipv6Prefix
=== PAUSE TestAccEC2NetworkInterface_ENI_ipv6Prefix
=== RUN   TestAccEC2NetworkInterface_ENI_ipv6PrefixCount
=== PAUSE TestAccEC2NetworkInterface_ENI_ipv6PrefixCount
=== CONT  TestAccEC2NetworkInterface_ENI_basic
=== CONT  TestAccEC2NetworkInterface_ENI_sourceDestCheck
=== CONT  TestAccEC2NetworkInterface_ENI_disappears
=== CONT  TestAccEC2NetworkInterface_ENI_tags
=== CONT  TestAccEC2NetworkInterface_ENI_ipv6
=== CONT  TestAccEC2NetworkInterface_ENI_ipv4PrefixCount
=== CONT  TestAccEC2NetworkInterface_ENI_ipv6PrefixCount
=== CONT  TestAccEC2NetworkInterface_ENI_ipv6Prefix
=== CONT  TestAccEC2NetworkInterface_ENIInterfaceType_efa
=== CONT  TestAccEC2NetworkInterface_ENI_ipv4Prefix
=== CONT  TestAccEC2NetworkInterface_ENI_description
=== CONT  TestAccEC2NetworkInterface_ENI_ipv6Count
=== CONT  TestAccEC2NetworkInterface_ENI_privateIPsCount
=== CONT  TestAccEC2NetworkInterface_ENI_ignoreExternalAttachment
=== CONT  TestAccEC2NetworkInterface_ENI_attachment
--- PASS: TestAccEC2NetworkInterface_ENI_disappears (48.88s)
--- PASS: TestAccEC2NetworkInterface_ENI_basic (54.46s)
--- PASS: TestAccEC2NetworkInterface_ENIInterfaceType_efa (55.39s)
--- PASS: TestAccEC2NetworkInterface_ENI_description (79.83s)
--- PASS: TestAccEC2NetworkInterface_ENI_sourceDestCheck (100.99s)
--- PASS: TestAccEC2NetworkInterface_ENI_tags (101.36s)
--- PASS: TestAccEC2NetworkInterface_ENI_ipv6 (105.92s)
--- PASS: TestAccEC2NetworkInterface_ENI_ipv6Prefix (105.92s)
--- PASS: TestAccEC2NetworkInterface_ENI_ipv4Prefix (105.94s)
--- PASS: TestAccEC2NetworkInterface_ENI_ipv4PrefixCount (122.78s)
--- PASS: TestAccEC2NetworkInterface_ENI_ipv6Count (127.57s)
--- PASS: TestAccEC2NetworkInterface_ENI_ipv6PrefixCount (127.58s)
--- PASS: TestAccEC2NetworkInterface_ENI_privateIPsCount (131.80s)
--- PASS: TestAccEC2NetworkInterface_ENI_ignoreExternalAttachment (302.54s)
--- PASS: TestAccEC2NetworkInterface_ENI_attachment (335.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	338.767s
% make testacc PKG_NAME=internal/service/lambda TESTARGS='-run=TestAccLambdaFunction_vpc'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run=TestAccLambdaFunction_vpc -timeout 180m
=== RUN   TestAccLambdaFunction_vpc
=== PAUSE TestAccLambdaFunction_vpc
=== RUN   TestAccLambdaFunction_vpcRemoval
=== PAUSE TestAccLambdaFunction_vpcRemoval
=== RUN   TestAccLambdaFunction_vpcUpdate
=== PAUSE TestAccLambdaFunction_vpcUpdate
=== CONT  TestAccLambdaFunction_vpc
=== CONT  TestAccLambdaFunction_vpcUpdate
=== CONT  TestAccLambdaFunction_vpcRemoval
--- PASS: TestAccLambdaFunction_vpc (412.33s)
--- PASS: TestAccLambdaFunction_vpcRemoval (813.06s)
--- PASS: TestAccLambdaFunction_vpcUpdate (843.20s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	846.176s
```

**Comment by ewbankkit** [comment]
@awsaxeman Thanks for the contribution :tada: :clap:.

**Pull request merged**
