### PR TITLE
added option to toggle default standards on Security Hub 

### LINKED ISSUE #13100: AWS SecurityHub: Add support to EnableDefaultStandards option in aws_securityhub_account resource
### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

#### Support for `EnableDefaultStandards` parameter in the resource [aws_securityhub_account](https://www.terraform.io/docs/providers/aws/r/securityhub_account.html).
When SecurityHub is enabled, the `CIS AWS Foundations Standard` and `AWS Foundational Security Best Practices Standard` standards are automatically enabled, but some people may not want this.
To be able to disable this behaviour i am requesting the addition of an "enable_default_standards" parameter for the resource.

### New or Affected Resource(s)

* aws_securityhub_account

### References

* https://docs.aws.amazon.com/securityhub/latest/userguide/securityhub-settingup.html#securityhub-enable
* https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_EnableSecurityHub.html

### PR DESCRIPTION
**Pull request by doublefelix7**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13100

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
added the "enable_default_standards" flag to resource aws_securityhub_account
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```
Would someone be able to run the acceptance tests? I don't currently have a personal AWS account, but I can confirm that the `make test` passes.

### CODE REVIEW

**Comment by doublefelix7** [comment]
Hi, seems like it's been a while since I opened this PR. Any additional reviews on this? Or is there something preventing this from being merged?

**Comment by anGie44** [comment]
Hi @doublefelix7 , thank you for this PR and apologies for the delay! I've had a look at code changes and ran the acceptance tests and came across errors when disabling Standard Defaults i.e. setting `enable_default_standards=false`. In short, to support disabling, we need to disable each standard individually. Similarly, to support enabling on update, we must enable each standard. To get this in shape for an upcoming release, I've added some changes in forthcoming commit to incorporate the changes you've provided in addition to changes i've made to account for the enable/disable behavior, and added test coverage to verify the new behavior and an update to the documentation.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by kclinden** [comment]
I opened a related ticket with AWS support to update the Go SDK to either default to false or update it to be under CIS v1.4.0 vs v1.2.0.

https://docs.aws.amazon.com/securityhub/1.0/APIReference/API_EnableSecurityHub.html

**Pull request closed without merging**
