### PR TITLE
fix(vpc): added support for different size ipv6 cidrs

### LINKED ISSUE #34992: [Bug]: VPC IPv6 CIDR Block Association only allows /56 netmask
### Terraform Core Version

v1.6.6-dev

### AWS Provider Version

v5.31.0

### Affected Resource(s)

aws_vpc_ipv6_cidr_block_association

### Expected Behavior

I expect to be able to provision an IPv6 CIDR block association from an IPAM pool, that has a netmask length of `/60`. For example:

```terraform
resource "aws_vpc_ipv6_cidr_block_association" "test" {
  vpc_id              = resource.aws_vpc.test.id
  ipv6_ipam_pool_id   = data.aws_vpc_ipam_pool.test.id
  ipv6_netmask_length = 60
}
```

### Actual Behavior

I get the following error:

```
expected ipv6_netmask_length to be one of [56], got 60
```

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: expected ipv6_netmask_length to be one of [56], got 60
│ 
│   with aws_vpc_ipv6_cidr_block_association.test,
│   on main.tf line 28, in resource "aws_vpc_ipv6_cidr_block_association" "test":
│   28:   ipv6_netmask_length = 60
│ 
╵
```

### Terraform Configuration Files

`main.tf`

```terraform
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 5.31"
    }
  }

  required_version = ">= 1.6.1"
}

provider "aws" {
  region  = "us-east-1"
}

data "aws_vpc_ipam_pool" "test" {
  filter {
    name   = "address-family"
    values = ["ipv6"]
  }
}

resource "aws_vpc" "test" {}

resource "aws_vpc_ipv6_cidr_block_association" "test" {
  vpc_id              = resource.aws_vpc.test.id
  ipv6_ipam_pool_id   = data.aws_vpc_ipam_pool.test.id
  ipv6_netmask_length = 60
}
```

### Steps to Reproduce

An IPv6 IPAM pool must exist in the current region. I can't easily show this in the repro example, since there is an account-wide quota limit of 1 for htis resource.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

This is caused by the check [here](https://github.com/hashicorp/terraform-provider-aws/blob/ba227957595c95ef5f5c2b7a34b5c1c7c65a0210/internal/service/ec2/vpc_ipv6_cidr_block_association.go#L62C18-L70), which only allows a `/56` CIDR. [AWS's documentation](https://docs.aws.amazon.com/vpc/latest/userguide/modify-vpcs.html#vpc-associate-ipv6-cidr) however states that values betwen `/44` and `/60` in increments of `/4` are permitted when allocating an IPv6 CIDR from an IPAM pool:

> If there is no default netmask length selected for the IPAM pool, choose a netmask length that's more specific than the netmask length of the IPAM pool CIDR. For example, if the IPAM pool CIDR is /50, you can choose a netmask length between /52 to /60 for the VPC. **Possible netmask lengths are between /44 and /60 in increments of /4.**

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by k1rk**
### Description
AWS added support for different sizes of IPv6 blocks, from `/44` to `/60`

### Relations

Closes #34992.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/38552.

### References
Announcement [here](https://aws.amazon.com/about-aws/whats-new/2023/11/vpcs-subnets-support-more-sizes-ipv6-cidrs/) and docs [here](https://docs.aws.amazon.com/vpc/latest/userguide/vpc-ip-addressing.html)

### Output from Acceptance Testing
N/A

### CODE REVIEW

**Comment by k1rk** [comment]
hi @justinretzolk 
any chance to get this reviewed soon? we are currently blocked by this, and can't proceed with anything else until network is done 😢

**Comment by fideloper** [comment]
Need this as well!

**Comment by sebltm** [comment]
@justinretzolk / @johnsonaj could this one get reviewed to bring up to date with the capabilities of the SDK ?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPC_\|TestAccVPCDefaultVPCAndSubnet_serial' PKG=ec2 ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/ec2/... -v -count 1 -parallel 4  -run=TestAccVPC_\|TestAccVPCDefaultVPCAndSubnet_serial -timeout 360m
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial
=== PAUSE TestAccVPCDefaultVPCAndSubnet_serial
=== RUN   TestAccVPC_basic
=== PAUSE TestAccVPC_basic
=== RUN   TestAccVPC_disappears
=== PAUSE TestAccVPC_disappears
=== RUN   TestAccVPC_DynamicResourceTagsMergedWithLocals_ignoreChanges
=== PAUSE TestAccVPC_DynamicResourceTagsMergedWithLocals_ignoreChanges
=== RUN   TestAccVPC_DynamicResourceTags_ignoreChanges
=== PAUSE TestAccVPC_DynamicResourceTags_ignoreChanges
=== RUN   TestAccVPC_tags_defaultAndIgnoreTags
=== PAUSE TestAccVPC_tags_defaultAndIgnoreTags
=== RUN   TestAccVPC_tags_ignoreTags
=== PAUSE TestAccVPC_tags_ignoreTags
=== RUN   TestAccVPC_tenancy
=== PAUSE TestAccVPC_tenancy
=== RUN   TestAccVPC_updateDNSHostnames
=== PAUSE TestAccVPC_updateDNSHostnames
=== RUN   TestAccVPC_bothDNSOptionsSet
=== PAUSE TestAccVPC_bothDNSOptionsSet
=== RUN   TestAccVPC_disabledDNSSupport
=== PAUSE TestAccVPC_disabledDNSSupport
=== RUN   TestAccVPC_enableNetworkAddressUsageMetrics
=== PAUSE TestAccVPC_enableNetworkAddressUsageMetrics
=== RUN   TestAccVPC_assignGeneratedIPv6CIDRBlock
=== PAUSE TestAccVPC_assignGeneratedIPv6CIDRBlock
=== RUN   TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup
=== PAUSE TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup
=== RUN   TestAccVPC_IPAMIPv4BasicNetmask
=== PAUSE TestAccVPC_IPAMIPv4BasicNetmask
=== RUN   TestAccVPC_IPAMIPv4BasicExplicitCIDR
=== PAUSE TestAccVPC_IPAMIPv4BasicExplicitCIDR
=== RUN   TestAccVPC_IPAMIPv6
=== PAUSE TestAccVPC_IPAMIPv6
=== CONT  TestAccVPCDefaultVPCAndSubnet_serial
=== CONT  TestAccVPC_bothDNSOptionsSet
=== CONT  TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup
=== CONT  TestAccVPC_enableNetworkAddressUsageMetrics
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet/notFound.basic
    vpc_default_subnet_test.go:257: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet/notFound.ipv6Native
    vpc_default_subnet_test.go:303: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.basic
    vpc_default_subnet_test.go:90: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.forceDestroy
    vpc_default_subnet_test.go:136: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.ipv6
    vpc_default_subnet_test.go:163: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.privateDnsNameOptionsOnLaunch
    vpc_default_subnet_test.go:210: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.assignGeneratedIPv6CIDRBlock
    vpc_default_vpc_test.go:134: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.forceDestroy
    vpc_default_vpc_test.go:181: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.basic
    vpc_default_vpc_test.go:209: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlock
    vpc_default_vpc_test.go:256: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.forceDestroy
    vpc_default_vpc_test.go:303: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption
    vpc_default_vpc_test.go:332: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.basic
    vpc_default_vpc_test.go:87: skipping tests; AWS_DEFAULT_REGION (us-west-2) not supported
--- PASS: TestAccVPCDefaultVPCAndSubnet_serial (0.42s)
    --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/Subnet (0.41s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/Subnet/notFound.basic (0.41s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/Subnet/notFound.ipv6Native (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.basic (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.forceDestroy (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.ipv6 (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/Subnet/existing.privateDnsNameOptionsOnLaunch (0.00s)
    --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC (0.01s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.assignGeneratedIPv6CIDRBlock (0.01s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.forceDestroy (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.basic (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlock (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.forceDestroy (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption (0.00s)
        --- SKIP: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.basic (0.00s)
=== CONT  TestAccVPC_IPAMIPv4BasicExplicitCIDR
--- PASS: TestAccVPC_enableNetworkAddressUsageMetrics (26.09s)
=== CONT  TestAccVPC_IPAMIPv6
--- PASS: TestAccVPC_bothDNSOptionsSet (26.14s)
=== CONT  TestAccVPC_assignGeneratedIPv6CIDRBlock
--- PASS: TestAccVPC_assignGeneratedIPv6CIDRBlockWithNetworkBorderGroup (59.99s)
=== CONT  TestAccVPC_tags_defaultAndIgnoreTags
--- PASS: TestAccVPC_tags_defaultAndIgnoreTags (20.66s)
=== CONT  TestAccVPC_updateDNSHostnames
--- PASS: TestAccVPC_assignGeneratedIPv6CIDRBlock (65.56s)
=== CONT  TestAccVPC_tenancy
--- PASS: TestAccVPC_updateDNSHostnames (31.89s)
=== CONT  TestAccVPC_tags_ignoreTags
--- PASS: TestAccVPC_tenancy (37.03s)
=== CONT  TestAccVPC_DynamicResourceTagsMergedWithLocals_ignoreChanges
--- PASS: TestAccVPC_tags_ignoreTags (21.19s)
=== CONT  TestAccVPC_DynamicResourceTags_ignoreChanges
--- PASS: TestAccVPC_DynamicResourceTagsMergedWithLocals_ignoreChanges (23.57s)
=== CONT  TestAccVPC_disabledDNSSupport
--- PASS: TestAccVPC_DynamicResourceTags_ignoreChanges (23.29s)
=== CONT  TestAccVPC_IPAMIPv4BasicNetmask
--- PASS: TestAccVPC_disabledDNSSupport (25.52s)
=== CONT  TestAccVPC_basic
--- PASS: TestAccVPC_basic (15.61s)
=== CONT  TestAccVPC_disappears
--- PASS: TestAccVPC_disappears (12.24s)
--- PASS: TestAccVPC_IPAMIPv4BasicExplicitCIDR (1151.40s)
--- PASS: TestAccVPC_IPAMIPv6 (1185.58s)
--- PASS: TestAccVPC_IPAMIPv4BasicNetmask (1177.34s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1339.459s
```
```console
% make testacc TESTARGS='-run=TestAccVPCSecurityGroupIngressRule_\|TestAccVPCSecurityGroupEgressRule_' PKG=ec2 ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/ec2/... -v -count 1 -parallel 4  -run=TestAccVPCSecurityGroupIngressRule_\|TestAccVPCSecurityGroupEgressRule_ -timeout 360m
=== RUN   TestAccVPCSecurityGroupEgressRule_tags
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_null
    vpc_security_group_egress_rule_tags_gen_test.go:192: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccVPCSecurityGroupEgressRule_tags_null (0.00s)
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_AddOnUpdate
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_AddOnUpdate
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnCreate
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnCreate
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Add
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Replace
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Replace
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_providerOnly
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_providerOnly
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nonOverlapping
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_overlapping
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_overlapping
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyResourceTag
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyResourceTag
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyProviderOnlyTag
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyProviderOnlyTag
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nullOverlappingResourceTag
    vpc_security_group_egress_rule_tags_gen_test.go:1448: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nullOverlappingResourceTag (0.00s)
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nullNonOverlappingResourceTag
    vpc_security_group_egress_rule_tags_gen_test.go:1512: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nullNonOverlappingResourceTag (0.00s)
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnCreate
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnCreate
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Add
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Add
=== RUN   TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Replace
=== PAUSE TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Replace
=== RUN   TestAccVPCSecurityGroupEgressRule_basic
=== PAUSE TestAccVPCSecurityGroupEgressRule_basic
=== RUN   TestAccVPCSecurityGroupEgressRule_disappears
=== PAUSE TestAccVPCSecurityGroupEgressRule_disappears
=== RUN   TestAccVPCSecurityGroupIngressRule_tags
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_null
    vpc_security_group_ingress_rule_tags_gen_test.go:192: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccVPCSecurityGroupIngressRule_tags_null (0.00s)
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_AddOnUpdate
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_AddOnUpdate
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnCreate
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnCreate
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Add
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Replace
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Replace
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_providerOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_providerOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nonOverlapping
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_overlapping
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_overlapping
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyResourceTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyResourceTag
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyProviderOnlyTag
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyProviderOnlyTag
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nullOverlappingResourceTag
    vpc_security_group_ingress_rule_tags_gen_test.go:1448: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nullOverlappingResourceTag (0.00s)
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nullNonOverlappingResourceTag
    vpc_security_group_ingress_rule_tags_gen_test.go:1512: Tags with null values are not correctly handled with the Plugin Framework
--- SKIP: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nullNonOverlappingResourceTag (0.00s)
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnCreate
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnCreate
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Add
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Add
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Replace
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Replace
=== RUN   TestAccVPCSecurityGroupIngressRule_basic
=== PAUSE TestAccVPCSecurityGroupIngressRule_basic
=== RUN   TestAccVPCSecurityGroupIngressRule_disappears
=== PAUSE TestAccVPCSecurityGroupIngressRule_disappears
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_defaultAndIgnoreTags
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_defaultAndIgnoreTags
=== RUN   TestAccVPCSecurityGroupIngressRule_tags_ignoreTags
=== PAUSE TestAccVPCSecurityGroupIngressRule_tags_ignoreTags
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv4
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv4
=== RUN   TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== PAUSE TestAccVPCSecurityGroupIngressRule_cidrIPv6
=== RUN   TestAccVPCSecurityGroupIngressRule_description
=== PAUSE TestAccVPCSecurityGroupIngressRule_description
=== RUN   TestAccVPCSecurityGroupIngressRule_prefixListID
=== PAUSE TestAccVPCSecurityGroupIngressRule_prefixListID
=== RUN   TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
=== PAUSE TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
=== RUN   TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
=== PAUSE TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
=== RUN   TestAccVPCSecurityGroupIngressRule_updateSourceType
=== PAUSE TestAccVPCSecurityGroupIngressRule_updateSourceType
=== CONT  TestAccVPCSecurityGroupEgressRule_tags
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_providerOnly
=== CONT  TestAccVPCSecurityGroupIngressRule_disappears
=== CONT  TestAccVPCSecurityGroupIngressRule_description
--- PASS: TestAccVPCSecurityGroupIngressRule_disappears (18.59s)
=== CONT  TestAccVPCSecurityGroupIngressRule_updateSourceType
--- PASS: TestAccVPCSecurityGroupIngressRule_description (29.52s)
=== CONT  TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC
    vpc_security_group_ingress_rule_test.go:477: skipping test because at least one environment variable of [AWS_ALTERNATE_PROFILE AWS_ALTERNATE_ACCESS_KEY_ID] must be set. Usage: credentials for running acceptance testing in alternate AWS account.
--- SKIP: TestAccVPCSecurityGroupIngressRule_ReferencedSecurityGroupID_peerVPC (0.00s)
=== CONT  TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID
--- PASS: TestAccVPCSecurityGroupIngressRule_updateSourceType (28.01s)
=== CONT  TestAccVPCSecurityGroupIngressRule_prefixListID
--- PASS: TestAccVPCSecurityGroupEgressRule_tags (58.31s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccVPCSecurityGroupIngressRule_referencedSecurityGroupID (30.87s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_providerOnly (65.59s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Add
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyProviderOnlyTag (19.74s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnCreate
--- PASS: TestAccVPCSecurityGroupIngressRule_prefixListID (39.48s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_AddOnUpdate
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Replace (30.12s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnUpdate_Add (42.32s)
=== CONT  TestAccVPCSecurityGroupEgressRule_disappears
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_EmptyTag_OnCreate (32.69s)
=== CONT  TestAccVPCSecurityGroupEgressRule_basic
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_AddOnUpdate (29.98s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Replace
--- PASS: TestAccVPCSecurityGroupEgressRule_disappears (18.85s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccVPCSecurityGroupEgressRule_basic (19.08s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnCreate
--- PASS: TestAccVPCSecurityGroupIngressRule_tags (57.14s)
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv4
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Replace (32.86s)
=== CONT  TestAccVPCSecurityGroupIngressRule_cidrIPv6
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnCreate (21.78s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nonOverlapping
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_ComputedTag_OnUpdate_Add (32.14s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyResourceTag
--- PASS: TestAccVPCSecurityGroupIngressRule_cidrIPv4 (28.68s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_cidrIPv6 (28.22s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_emptyResourceTag (20.11s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_overlapping
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_nonOverlapping (48.71s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToResourceOnly (31.47s)
=== CONT  TestAccVPCSecurityGroupIngressRule_basic
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_updateToProviderOnly (31.56s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Replace
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyProviderOnlyTag (19.99s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccVPCSecurityGroupIngressRule_basic (19.24s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnCreate
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_overlapping (50.63s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_ignoreTags
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Replace (32.81s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToProviderOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnCreate (22.45s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyResourceTag
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_ComputedTag_OnUpdate_Add (32.93s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Add
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_ignoreTags (26.59s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_emptyResourceTag (19.84s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_providerOnly
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToProviderOnly (32.34s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnCreate
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_updateToResourceOnly (33.42s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_overlapping
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Add (43.62s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_defaultAndIgnoreTags
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnCreate (31.42s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_AddOnUpdate
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_defaultAndIgnoreTags (26.15s)
=== CONT  TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nonOverlapping
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_AddOnUpdate (30.25s)
=== CONT  TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_DefaultTags_providerOnly (66.46s)
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_overlapping (51.96s)
--- PASS: TestAccVPCSecurityGroupEgressRule_tags_EmptyTag_OnUpdate_Replace (30.15s)
--- PASS: TestAccVPCSecurityGroupIngressRule_tags_DefaultTags_nonOverlapping (49.87s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	377.617s
```

**Comment by ewbankkit** [comment]
@k1rk Thanks for the contribution :tada: :clap:.

**Pull request merged**
