### PR TITLE
Add cidrs attribute to aws_lightsail_instance_public_ports resource

### LINKED ISSUE #700: aws_lightsail provider should support open port management
_This issue was originally opened by @sean-brandt as hashicorp/terraform#13759. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Run `terraform -v` to show the version. If you are not running the latest version of Terraform, please upgrade because your issue may have already been fixed.

Terraform v0.9.3

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_lightsail

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Expected Behavior
What should have happened?

aws_lightsail provider should allow for managing open ports

### PR DESCRIPTION
**Pull request by kurtmc**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Add cidrs attribute to aws_lightsail_instance_public_ports resource
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSLightsailInstancePublicPorts'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLightsailInstancePublicPorts -timeout 180m
=== RUN   TestAccAWSLightsailInstancePublicPorts_basic
=== PAUSE TestAccAWSLightsailInstancePublicPorts_basic
=== RUN   TestAccAWSLightsailInstancePublicPorts_multiple
=== PAUSE TestAccAWSLightsailInstancePublicPorts_multiple
=== RUN   TestAccAWSLightsailInstancePublicPorts_cidrs
=== PAUSE TestAccAWSLightsailInstancePublicPorts_cidrs
=== CONT  TestAccAWSLightsailInstancePublicPorts_basic
=== CONT  TestAccAWSLightsailInstancePublicPorts_cidrs
=== CONT  TestAccAWSLightsailInstancePublicPorts_multiple
--- PASS: TestAccAWSLightsailInstancePublicPorts_cidrs (71.71s)
--- PASS: TestAccAWSLightsailInstancePublicPorts_multiple (74.38s)
--- PASS: TestAccAWSLightsailInstancePublicPorts_basic (93.91s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       93.955s
```

### CODE REVIEW

**Comment by YakDriver** [comment]
@kurtmc Thank you for this PR! Some of this functionality will be merged as part of #8611. However, please consider rebasing and adding the additional attributes after that merges. Thank you!

**Comment by kurtmc** [comment]
@YakDriver Awesome! Thanks for the heads up.

**Comment by kurtmc** [comment]
@YakDriver I have rebased now, and just added my `cidrs` attribute to the resource that exists in the main branch, but I am having trouble with the acceptance tests.

**Review by YakDriver — APPROVED** [review]
Looks great! @kurtmc Thank you! 🎉 

Acceptance tests on commercial:
```
--- PASS: TestAccAWSLightsailInstancePublicPorts_basic (44.70s)
--- PASS: TestAccAWSLightsailInstancePublicPorts_cidrs (55.74s)
--- PASS: TestAccAWSLightsailInstancePublicPorts_multiple (58.41s)
```

Acceptance tests on GovCloud:
```
--- SKIP: TestAccAWSLightsailInstancePublicPorts_basic (1.29s)
--- SKIP: TestAccAWSLightsailInstancePublicPorts_cidrs (1.29s)
--- SKIP: TestAccAWSLightsailInstancePublicPorts_multiple (1.29s)
```

**Comment by YakDriver** [comment]
@kurtmc Rather than perform the sorts, I switched `cidrs` to type `schema.TypeSet`. It seems to work okay. I'm not 100% certain AWS will always provide the CIDRs in the same order so the acceptance test may flaky fail every now and then. I tried it many times in a row and always got the same order. The resource itself won't show diffs based on order since it is a set but since the test has a hardcoded index, there's the possibility of issues.

**Pull request merged**
