### PR TITLE
Datasync: Add missing option object_tags to aws_datasync_task

### PR DESCRIPTION
**Pull request by rickard-von-essen**
### Description
This adds the missing option `objectTags` to _DataSync task_. See [API docs - DataSync Options](  https://docs.aws.amazon.com/datasync/latest/userguide/API_Options.html).

Closes https://github.com/hashicorp/terraform-provider-aws/issues/31301.

### Output from Acceptance Testing
```
make testacc TESTS=TestAccDataSyncTask_DefaultSyncOptions_objectTags PKG=datasync
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 20 -run='TestAccDataSyncTask_DefaultSyncOptions_objectTags'  -timeout 180m
=== RUN   TestAccDataSyncTask_DefaultSyncOptions_objectTags
=== PAUSE TestAccDataSyncTask_DefaultSyncOptions_objectTags
=== CONT  TestAccDataSyncTask_DefaultSyncOptions_objectTags
--- PASS: TestAccDataSyncTask_DefaultSyncOptions_objectTags (246.46s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datasync   246.528s
```

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
missing changelog but otherwise LGTM

**Comment by rickard-von-essen** [comment]
Sorry for dropping the ball on this..

Fixed the changelog, rebased, and re-runned the IT's:

```
$ make testacc TESTS=TestAccDataSyncTask_DefaultSyncOptions_objectTags PKG=datasync
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 20 -run='TestAccDataSyncTask_DefaultSyncOptions_objectTags'  -timeout 180m
=== RUN   TestAccDataSyncTask_DefaultSyncOptions_objectTags
=== PAUSE TestAccDataSyncTask_DefaultSyncOptions_objectTags
=== CONT  TestAccDataSyncTask_DefaultSyncOptions_objectTags
--- PASS: TestAccDataSyncTask_DefaultSyncOptions_objectTags (231.19s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datasync   231.274s
$ date
Thu Apr 13 01:12:24 PM CEST 2023

**Comment by rickard-von-essen** [comment]
@DrFaust92 can we get this merged 🙏🏻 . I fixed the changelog.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccDataSyncTask_DefaultSyncOptions_objectTags\|TestAccDataSyncTask_basic$$' PKG=datasync
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 20  -run=TestAccDataSyncTask_DefaultSyncOptions_objectTags\|TestAccDataSyncTask_basic$ -timeout 180m
=== RUN   TestAccDataSyncTask_basic
=== PAUSE TestAccDataSyncTask_basic
=== RUN   TestAccDataSyncTask_DefaultSyncOptions_objectTags
=== PAUSE TestAccDataSyncTask_DefaultSyncOptions_objectTags
=== CONT  TestAccDataSyncTask_basic
=== CONT  TestAccDataSyncTask_DefaultSyncOptions_objectTags
--- PASS: TestAccDataSyncTask_basic (170.13s)
--- PASS: TestAccDataSyncTask_DefaultSyncOptions_objectTags (212.45s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datasync	219.737s
```
```console
% make testacc TESTARGS='-run=TestAccDataSyncLocationObjectStorage_' PKG=datasync ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/datasync/... -v -count 1 -parallel 2  -run=TestAccDataSyncLocationObjectStorage_ -timeout 180m
=== RUN   TestAccDataSyncLocationObjectStorage_basic
=== PAUSE TestAccDataSyncLocationObjectStorage_basic
=== RUN   TestAccDataSyncLocationObjectStorage_disappears
=== PAUSE TestAccDataSyncLocationObjectStorage_disappears
=== RUN   TestAccDataSyncLocationObjectStorage_tags
=== PAUSE TestAccDataSyncLocationObjectStorage_tags
=== RUN   TestAccDataSyncLocationObjectStorage_serverCertificate
=== PAUSE TestAccDataSyncLocationObjectStorage_serverCertificate
=== CONT  TestAccDataSyncLocationObjectStorage_basic
=== CONT  TestAccDataSyncLocationObjectStorage_tags
--- PASS: TestAccDataSyncLocationObjectStorage_basic (115.55s)
=== CONT  TestAccDataSyncLocationObjectStorage_disappears
--- PASS: TestAccDataSyncLocationObjectStorage_tags (174.17s)
=== CONT  TestAccDataSyncLocationObjectStorage_serverCertificate
--- PASS: TestAccDataSyncLocationObjectStorage_serverCertificate (104.84s)
--- PASS: TestAccDataSyncLocationObjectStorage_disappears (123.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/datasync	896.463s
```

**Comment by ewbankkit** [comment]
@rickard-von-essen Thanks for the contribution :tada: :clap:.

**Pull request merged**
