### PR TITLE
Add retry when publishing lambda functions that uses images

### LINKED ISSUE #17153: Error publishing version when lambda using container updates code
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform:  v0.13.3
Terraform AWS Provider: 3.24.1
```

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

For simplicity, using public module with additional `source_code_hash` argument. Module from: https://github.com/terraform-aws-modules/terraform-aws-lambda/

```hcl
module "lambda_function_from_container_image" {
  source = "../.."

  function_name = "${random_pet.this.id}-lambda-from-container-image"
  description   = "My awesome lambda function from container image"

  create_package = false
  source_code_hash = trimprefix(data.aws_ecr_image.ecr_lambda_image.id, "sha256:")

  ##################
  # Container Image
  ##################
  image_uri    = docker_registry_image.app.name
  package_type = "Image"
}
```

### Expected Behavior

Changes should have been applied without error.

### Actual Behavior
```
Error: Error publishing Lambda Function (bursting-deer-lambda-from-container-image) version: ResourceConflictException: The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image
{
  RespMetadata: {
    StatusCode: 409,
    RequestID: "a11bc6ec-1586-4a1f-bf7b-17ae01e861b6"
  },
  Message_: "The operation cannot be performed at this time. An update is in progress for resource: arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image",
  Type: "User"
}

```
### Steps to Reproduce

1. Create lambda resource using container.
2. Update ECR repository with new change. (this will trigger lambda UpdateFunctionCode using `source_code_hash` with ECR latest digest.)
3. `terraform plan`
4. `terraform apply`
### References

* #0000

I was able to reproduce the problem by setting the publish argument to true and the source_code_hash argument with the latest digest from the ECR repository (so the latest change of the image is used). Since source_code_hash has changed, terraform will trigger the UpdateFunctionCode method causing the lambda to move to pending state while [the image undergoes an optimization process for running on Lambda](https://docs.aws.amazon.com/lambda/latest/dg/configuration-images.html#configuration-images-optimization). 
Once the image is updated, terraform will try to publish the version. However it will fail because the lambda is still in pending state.
Here are some logs of the plan:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # module.lambda_function_from_container_image.aws_lambda_function.this[0] will be updated in-place
  ~ resource "aws_lambda_function" "this" {
        arn                            = "arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image"
        description                    = "My awesome lambda function from container image"
        function_name                  = "bursting-deer-lambda-from-container-image"
        id                             = "bursting-deer-lambda-from-container-image"
        image_uri                      = "xxx.dkr.ecr.us-east-1.amazonaws.com/bursting-deer:1.0"
        invoke_arn                     = "arn:aws:apigateway:us-east-1:lambda:path/2015-03-31/functions/arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image/invocations"
      ~ last_modified                  = "2021-01-18T00:08:53.000+0000" -> (known after apply)
        layers                         = []
        memory_size                    = 128
        package_type                   = "Image"
        publish                        = true
      ~ qualified_arn                  = "arn:aws:lambda:us-east-1:xxx:function:bursting-deer-lambda-from-container-image:$LATEST" -> (known after apply)
        reserved_concurrent_executions = -1
        role                           = "arn:aws:iam::xxx:role/bursting-deer-lambda-from-container-image"
      ~ source_code_hash               = "6c4f42f959e3d6471b4128a4f3806e43a8aaa36dc1ca7e67b30ecf994a0439f8" -> "d09bd32a66fb7747aa2d180c4326011822cf1195704f2ca24c07f6ea8351bc96"
        source_code_size               = 0
        tags                           = {}
        timeout                        = 3
      ~ version                        = "$LATEST" -> (known after apply)

        tracing_config {
            mode = "PassThrough"
        }
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
Once the apply has finished (with Error publishing Lambda Function message), you can check that the lambda status is still in pending:
```aws lambda get-function-configuration --function-name bursting-deer-lambda-from-container-image```
```
{
    "FunctionName": "bursting-deer-lambda-from-container-image",
    "FunctionArn": "arn:aws:lambda:us-east-1:xxxx:function:bursting-deer-lambda-from-container-image",
    "Role": "arn:aws:iam::xxx:role/bursting-deer-lambda-from-container-image",
    "CodeSize": 0,
    "Description": "My awesome lambda function from container image",
    "Timeout": 3,
    "MemorySize": 128,
    "LastModified": "2021-01-18T00:13:05.000+0000",
    "CodeSha256": "6c4f42f959e3d6471b4128a4f3806e43a8aaa36dc1ca7e67b30ecf994a0439f8",
    "Version": "$LATEST",
    "TracingConfig": {
        "Mode": "PassThrough"
    },
    "RevisionId": "bc691819-b517-42a4-85ad-ba9b2e828449",
    "State": "Active",
    "LastUpdateStatus": "InProgress",
    "LastUpdateStatusReason": "The function is being created.",
    "LastUpdateStatusReasonCode": "Creating"
}
```

### PR DESCRIPTION
**Pull request by mauriciocm9**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17153

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSLambdaFunction_imageConfig'


```

### CODE REVIEW

**Comment by mauriciocm9** [comment]
This is a WIP. However i would like some feedback and any improvements or request are welcome. I'm still working on getting my acceptance testing to work in my environment. Also i will include an additional acceptance test for this particular case.

**Review by juanhenaoparra — APPROVED** [review]

**Comment by mauriciocm9** [comment]
I've run the acceptance tests locally, however some tests are failing due to limitations of my aws account. It would be helpful if someone can help me with this.

**Review by sguzmanm — APPROVED** [review]

**Comment by BNMetrics** [comment]
@mauriciocm9 
First of all, Thanks for volunteer to fix this! 🙌 

We just started using docker images for lambda. Would love for this PR to get into the next release. 
If you could let me know what you'd need, I'm happy to help. 👍

**Comment by YakDriver** [comment]
@mauriciocm9 Thank you for your work on this PR! I will be working on this before long. In order to expedite the process, I will likely make some changes. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

GovCloud:
```
--- PASS: TestAccAWSLambdaFunction_basic (50.25s)
--- PASS: TestAccAWSLambdaFunction_concurrency (592.32s)
--- PASS: TestAccAWSLambdaFunction_concurrencyCycle (635.09s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfig (653.65s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfigUpdated (358.24s)
--- PASS: TestAccAWSLambdaFunction_disablePublish (640.47s)
--- PASS: TestAccAWSLambdaFunction_disappears (345.20s)
--- PASS: TestAccAWSLambdaFunction_EmptyVpcConfig (42.16s)
--- PASS: TestAccAWSLambdaFunction_enablePublish (663.39s)
--- PASS: TestAccAWSLambdaFunction_encryptedEnvVariables (643.85s)
--- PASS: TestAccAWSLambdaFunction_Environment_Variables_NoValue (594.07s)
--- PASS: TestAccAWSLambdaFunction_envVariables (649.99s)
--- PASS: TestAccAWSLambdaFunction_expectFilenameAndS3Attributes (16.53s)
--- PASS: TestAccAWSLambdaFunction_FileSystemConfig (1766.36s)
--- PASS: TestAccAWSLambdaFunction_KmsKeyArn_NoEnvironmentVariables (387.18s)
--- PASS: TestAccAWSLambdaFunction_Layers (579.34s)
--- PASS: TestAccAWSLambdaFunction_LayersUpdate (415.54s)
--- PASS: TestAccAWSLambdaFunction_localUpdate (49.30s)
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (56.35s)
--- PASS: TestAccAWSLambdaFunction_nilDeadLetterConfig (17.64s)
--- PASS: TestAccAWSLambdaFunction_runtimes (447.59s)
--- PASS: TestAccAWSLambdaFunction_s3 (37.39s)
--- PASS: TestAccAWSLambdaFunction_s3Update_basic (65.46s)
--- PASS: TestAccAWSLambdaFunction_s3Update_unversioned (65.13s)
--- PASS: TestAccAWSLambdaFunction_tags (84.37s)
--- PASS: TestAccAWSLambdaFunction_UnpublishedCodeUpdate (434.00s)
--- PASS: TestAccAWSLambdaFunction_versioned (628.13s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (720.12s)
--- PASS: TestAccAWSLambdaFunction_VPC (835.68s)
--- PASS: TestAccAWSLambdaFunction_VPC_withInvocation (367.80s)
--- PASS: TestAccAWSLambdaFunction_VpcConfig_ProperIamDependencies (297.18s)
--- PASS: TestAccAWSLambdaFunction_VPCRemoval (659.57s)
--- PASS: TestAccAWSLambdaFunction_VPCUpdate (710.84s)
--- PASS: TestAccAWSLB_ALB_AccessLogs (387.52s)
--- PASS: TestAccAWSLB_ALB_AccessLogs_Prefix (308.42s)
--- PASS: TestAccAWSLB_ALB_basic (176.27s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateDeletionProtection (290.27s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateDropInvalidHeaderFields (297.37s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateHttp2 (300.19s)
--- PASS: TestAccAWSLB_BackwardsCompatibility (210.27s)
--- PASS: TestAccAWSLB_generatedName (186.77s)
--- PASS: TestAccAWSLB_generatesNameForZeroValue (186.50s)
--- PASS: TestAccAWSLB_IPv6SubnetMapping (236.84s)
--- PASS: TestAccAWSLB_namePrefix (201.92s)
--- PASS: TestAccAWSLB_networkLoadbalancer_subnet_change (250.23s)
--- PASS: TestAccAWSLB_networkLoadbalancer_updateCrossZone (369.09s)
--- PASS: TestAccAWSLB_networkLoadbalancerEIP (244.75s)
--- PASS: TestAccAWSLB_NLB_AccessLogs (445.94s)
--- PASS: TestAccAWSLB_NLB_AccessLogs_Prefix (376.90s)
--- PASS: TestAccAWSLB_NLB_basic (223.99s)
--- PASS: TestAccAWSLB_NLB_privateipv4address (251.82s)
--- PASS: TestAccAWSLB_noSecurityGroup (177.83s)
--- PASS: TestAccAWSLB_tags (312.52s)
--- PASS: TestAccAWSLB_updatedIpAddressType (246.65s)
--- PASS: TestAccAWSLB_updatedSecurityGroups (246.36s)
--- PASS: TestAccAWSLB_updatedSubnets (255.55s)
--- PASS: TestAccAWSLBTargetGroup_BackwardsCompatibility (29.51s)
--- PASS: TestAccAWSLBTargetGroup_basic (31.81s)
--- PASS: TestAccAWSLBTargetGroup_basicUdp (37.08s)
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (56.30s)
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (60.77s)
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (69.59s)
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (58.86s)
--- PASS: TestAccAWSLBTargetGroup_defaults_application (27.97s)
--- PASS: TestAccAWSLBTargetGroup_defaults_network (33.46s)
--- PASS: TestAccAWSLBTargetGroup_enableHealthCheck (36.61s)
--- PASS: TestAccAWSLBTargetGroup_generatedName (29.12s)
--- PASS: TestAccAWSLBTargetGroup_namePrefix (28.74s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (99.10s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroupWithProxy (55.52s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tcp_HealthCheck_Protocol (58.47s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tls (25.19s)
--- PASS: TestAccAWSLBTargetGroup_ProtocolVersion (30.97s)
--- PASS: TestAccAWSLBTargetGroup_ProtocolVersion_GRPC_HealthCheck (30.33s)
--- PASS: TestAccAWSLBTargetGroup_ProtocolVersion_HTTP_GRPC_Update (50.38s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultALB (31.20s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultNLB (84.69s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidALB (57.93s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidNLB (35.35s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidALB (59.02s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidNLB (143.66s)
--- PASS: TestAccAWSLBTargetGroup_tags (87.76s)
--- PASS: TestAccAWSLBTargetGroup_TCP_HTTPHealthCheck (55.45s)
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (65.84s)
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (84.14s)
--- PASS: TestAccAWSLBTargetGroup_withoutHealthcheck (18.50s)
--- SKIP: TestAccAWSLambdaFunction_codeSigningConfig (0.44s)
--- SKIP: TestAccAWSLambdaFunction_imageConfig (0.00s)
--- SKIP: TestAccAWSLambdaFunction_tracingConfig (0.00s)
--- SKIP: TestAccAWSLB_ALB_outpost (1.93s)
--- SKIP: TestAccAWSLB_LoadBalancerType_Gateway (1.65s)
--- SKIP: TestAccAWSLB_LoadBalancerType_Gateway_EnableCrossZoneLoadBalancing (1.65s)
--- SKIP: TestAccAWSLBTargetGroup_Protocol_Geneve (0.35s)
```

`us-west-2`:
```
--- PASS: TestAccAWSLambdaFunction_basic (57.05s)
--- PASS: TestAccAWSLambdaFunction_concurrency (67.51s)
--- PASS: TestAccAWSLambdaFunction_concurrencyCycle (76.70s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfig (202.57s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfigUpdated (201.23s)
--- PASS: TestAccAWSLambdaFunction_disablePublish (73.95s)
--- PASS: TestAccAWSLambdaFunction_disappears (48.15s)
--- PASS: TestAccAWSLambdaFunction_EmptyVpcConfig (168.48s)
--- PASS: TestAccAWSLambdaFunction_enablePublish (74.01s)
--- PASS: TestAccAWSLambdaFunction_encryptedEnvVariables (94.28s)
--- PASS: TestAccAWSLambdaFunction_Environment_Variables_NoValue (43.33s)
--- PASS: TestAccAWSLambdaFunction_envVariables (131.65s)
--- PASS: TestAccAWSLambdaFunction_expectFilenameAndS3Attributes (15.16s)
--- PASS: TestAccAWSLambdaFunction_FileSystemConfig (1992.40s)
--- PASS: TestAccAWSLambdaFunction_KmsKeyArn_NoEnvironmentVariables (118.71s)
--- PASS: TestAccAWSLambdaFunction_Layers (147.24s)
--- PASS: TestAccAWSLambdaFunction_LayersUpdate (234.57s)
--- PASS: TestAccAWSLambdaFunction_localUpdate (49.31s)
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (50.44s)
--- PASS: TestAccAWSLambdaFunction_nilDeadLetterConfig (36.73s)
--- PASS: TestAccAWSLambdaFunction_runtimes (420.01s)
--- PASS: TestAccAWSLambdaFunction_s3 (38.54s)
--- PASS: TestAccAWSLambdaFunction_s3Update_basic (59.95s)
--- PASS: TestAccAWSLambdaFunction_s3Update_unversioned (62.73s)
--- PASS: TestAccAWSLambdaFunction_tags (82.28s)
--- PASS: TestAccAWSLambdaFunction_tags (97.28s)
--- PASS: TestAccAWSLambdaFunction_tracingConfig (144.94s)
--- PASS: TestAccAWSLambdaFunction_UnpublishedCodeUpdate (803.67s)
--- PASS: TestAccAWSLambdaFunction_versioned (35.72s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (824.18s)
--- PASS: TestAccAWSLambdaFunction_VPC (244.30s)
--- PASS: TestAccAWSLambdaFunction_VPC_withInvocation (825.23s)
--- PASS: TestAccAWSLambdaFunction_VpcConfig_ProperIamDependencies (256.93s)
--- PASS: TestAccAWSLambdaFunction_VPCRemoval (448.94s)
--- PASS: TestAccAWSLB_ALB_AccessLogs (377.79s)
--- PASS: TestAccAWSLB_ALB_AccessLogs_Prefix (297.86s)
--- PASS: TestAccAWSLB_ALB_basic (187.27s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateDeletionProtection (283.48s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateDropInvalidHeaderFields (284.73s)
--- PASS: TestAccAWSLB_applicationLoadBalancer_updateHttp2 (283.80s)
--- PASS: TestAccAWSLB_BackwardsCompatibility (186.96s)
--- PASS: TestAccAWSLB_generatedName (175.52s)
--- PASS: TestAccAWSLB_generatesNameForZeroValue (176.84s)
--- PASS: TestAccAWSLB_IPv6SubnetMapping (240.99s)
--- PASS: TestAccAWSLB_LoadBalancerType_Gateway (109.03s)
--- PASS: TestAccAWSLB_LoadBalancerType_Gateway_EnableCrossZoneLoadBalancing (156.78s)
--- PASS: TestAccAWSLB_namePrefix (175.55s)
--- PASS: TestAccAWSLB_networkLoadbalancer_subnet_change (250.94s)
--- PASS: TestAccAWSLB_networkLoadbalancer_updateCrossZone (340.80s)
--- PASS: TestAccAWSLB_networkLoadbalancerEIP (241.70s)
--- PASS: TestAccAWSLB_NLB_AccessLogs (407.80s)
--- PASS: TestAccAWSLB_NLB_AccessLogs_Prefix (376.60s)
--- PASS: TestAccAWSLB_NLB_basic (236.95s)
--- PASS: TestAccAWSLB_NLB_privateipv4address (229.74s)
--- PASS: TestAccAWSLB_noSecurityGroup (176.45s)
--- PASS: TestAccAWSLB_tags (289.48s)
--- PASS: TestAccAWSLB_updatedIpAddressType (251.06s)
--- PASS: TestAccAWSLB_updatedSecurityGroups (339.79s)
--- PASS: TestAccAWSLB_updatedSubnets (266.88s)
--- PASS: TestAccAWSLBTargetGroup_BackwardsCompatibility (27.27s)
--- PASS: TestAccAWSLBTargetGroup_basic (34.52s)
--- PASS: TestAccAWSLBTargetGroup_basicUdp (34.48s)
--- PASS: TestAccAWSLBTargetGroup_changeNameForceNew (48.60s)
--- PASS: TestAccAWSLBTargetGroup_changePortForceNew (52.96s)
--- PASS: TestAccAWSLBTargetGroup_changeProtocolForceNew (54.79s)
--- PASS: TestAccAWSLBTargetGroup_changeVpcForceNew (52.47s)
--- PASS: TestAccAWSLBTargetGroup_defaults_application (32.94s)
--- PASS: TestAccAWSLBTargetGroup_defaults_network (29.53s)
--- PASS: TestAccAWSLBTargetGroup_enableHealthCheck (27.33s)
--- PASS: TestAccAWSLBTargetGroup_generatedName (23.99s)
--- PASS: TestAccAWSLBTargetGroup_namePrefix (25.24s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroup (91.70s)
--- PASS: TestAccAWSLBTargetGroup_networkLB_TargetGroupWithProxy (57.72s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Geneve (37.28s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tcp_HealthCheck_Protocol (61.69s)
--- PASS: TestAccAWSLBTargetGroup_Protocol_Tls (27.92s)
--- PASS: TestAccAWSLBTargetGroup_ProtocolVersion (32.77s)
--- PASS: TestAccAWSLBTargetGroup_ProtocolVersion_GRPC_HealthCheck (40.84s)
--- PASS: TestAccAWSLBTargetGroup_ProtocolVersion_HTTP_GRPC_Update (52.35s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultALB (27.07s)
--- PASS: TestAccAWSLBTargetGroup_stickinessDefaultNLB (74.96s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidALB (47.31s)
--- PASS: TestAccAWSLBTargetGroup_stickinessInvalidNLB (32.22s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidALB (51.96s)
--- PASS: TestAccAWSLBTargetGroup_stickinessValidNLB (122.04s)
--- PASS: TestAccAWSLBTargetGroup_tags (67.79s)
--- PASS: TestAccAWSLBTargetGroup_TCP_HTTPHealthCheck (55.58s)
--- PASS: TestAccAWSLBTargetGroup_updateHealthCheck (53.91s)
--- PASS: TestAccAWSLBTargetGroup_updateSticknessEnabled (72.67s)
--- PASS: TestAccAWSLBTargetGroup_withoutHealthcheck (21.50s)
--- SKIP: TestAccAWSLambdaFunction_imageConfig (0.00s)
--- SKIP: TestAccAWSLB_ALB_outpost (0.72s)
```

**Pull request merged**
