### PR TITLE
Codecommit approval rule template

### LINKED ISSUE #11461: Add resource for CodeCommit approval rule templates
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added approval rule templates to CodeCommit to improve the pull request process. Need to add a resource for this.

### New or Affected Resource(s)

* aws_codecommit_approval_rule_template

### References

* https://docs.aws.amazon.com/codecommit/latest/APIReference/API_CreateApprovalRuleTemplate.html
* https://docs.aws.amazon.com/codecommit/latest/APIReference/API_GetApprovalRuleTemplate.html

### PR DESCRIPTION
**Pull request by carthewd**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11461

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```
New Resource: aws_codecommit_approval_rule_template
```
### Example
```hcl
resource "aws_codecommit_approval_rule_template" "test" {
    name = "MyTestApprovalRule"
    description = "This is a test approval rule template"
    
    content = <<EOF
{
    "Version": "2018-11-08",
    "DestinationReferences": ["refs/heads/master"],
    "Statements": [{
        "Type": "Approvers",
        "NumberOfApprovalsNeeded": 2,
        "ApprovalPoolMembers": ["arn:aws:sts::123456789012:assumed-role/CodeCommitReview/*"]}]
}
EOF
}
```
```hcl
data "aws_codecommit_approval_rule_template" "test" {
  name = "MyTestApprovalRule"
}
```

### Testing
Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSCodeCommitApprovalRule'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCodeCommitApprovalRule -timeout 120m                    
=== RUN   TestAccAWSCodeCommitApprovalRuleTemplateDataSource_basic                                                     
=== PAUSE TestAccAWSCodeCommitApprovalRuleTemplateDataSource_basic                                                     
=== RUN   TestAccAWSCodeCommitApprovalRule_basic
=== PAUSE TestAccAWSCodeCommitApprovalRule_basic
=== RUN   TestAccAWSCodeCommitApprovalRule_withChanges
=== PAUSE TestAccAWSCodeCommitApprovalRule_withChanges
=== CONT  TestAccAWSCodeCommitApprovalRuleTemplateDataSource_basic                                                     
=== CONT  TestAccAWSCodeCommitApprovalRule_withChanges
=== CONT  TestAccAWSCodeCommitApprovalRule_basic
--- PASS: TestAccAWSCodeCommitApprovalRuleTemplateDataSource_basic (54.73s)                                            
--- PASS: TestAccAWSCodeCommitApprovalRule_basic (56.16s)
--- PASS: TestAccAWSCodeCommitApprovalRule_withChanges (84.27s)                                                        
PASS                                                       
ok      github.com/terraform-providers/terraform-provider-aws/aws       84.294s 
...
```
### Notes
I'm also working on an aws_codecommit_approval_rule_association resource to manage associating rules with repositories.

### CODE REVIEW

**Comment by InTheKeyOfCSharp** [comment]
+1

**Comment by jValdron** [comment]
Hey @carthewd, how's the work on `aws_codecommit_approval_rule_association` going? This can't really use without the association to its repo. I can look into it if you need someone to help out with that part.

**Comment by carthewd** [comment]
Hey @jValdron - it's mostly done, to be honest I let it languish a bit in case some feedback here contradicted the implementation. I'll wrap it up and post in the next 2 days or so.

**Comment by jValdron** [comment]
Thanks @carthewd! Let me know if there's anything I can do to help.

**Comment by carthewd** [comment]
> Thanks @carthewd! Let me know if there's anything I can do to help.

Ok, I've created a separate PR for the association resource (I thought it maybe easier to review that way).

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by goraxe** [comment]
@bflad @ewbankkit Hey Guys I have seen that you folks were recent reviewers / mergers for things in the codecommit area.  Looking at the attached PR   https://github.com/hashicorp/terraform-provider-aws/pull/13467 would also be required to make use of the feature.  It looks to me like the PRs have docs + tests is there anything else @carthewd would need to do to get these merged?  Many thanks

**Comment by DaKaZ** [comment]
@bflad @ewbankkit Not trying to be overly noisy - but its been another month... is there anything the rest of us can do to help this PR land?

**Comment by anGie44** [comment]
Hi @carthewd , thank you for this PR! I'm going to be reviewing this PR and in the meantime, I recommend setting this PR to `allow maintainers to edit` so that we can help you update this PR for service packages (see #20000). If edits are possible, I will resolve merge conflicts on my end.

**Comment by anGie44** [comment]
Output of acceptance tests (AWS commercial):
```
--- PASS: TestAccCodeCommitApprovalRuleTemplate_disappears (12.36s)
--- PASS: TestAccCodeCommitApprovalRuleTemplateDataSource_basic (14.28s)
--- PASS: TestAccCodeCommitApprovalRuleTemplate_basic (15.65s)
--- PASS: TestAccCodeCommitApprovalRuleTemplate_updateName (25.01s)
--- PASS: TestAccCodeCommitApprovalRuleTemplate_updateContentAndDescription (25.54s)
```

**Review by anGie44 — APPROVED** [review]
Thank you again @carthewd for this PR! I've added in the required changes to get this up-to-date with our service packages restructure.

**Comment by carthewd** [comment]
Thank you @anGie44  ! Really appreciate the help here - I had been hoping to make some time over the break to wrap this up with the new requirements

**Comment by anGie44** [comment]
Of course, happy to help @carthewd ! Appreciate all your work and for checking back in as it's been quite some time since you initially created the PR .

**Pull request merged**
