### PR TITLE
Adding support for table resource

### PR DESCRIPTION
**Pull request by pranayw333**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes https://github.com/hashicorp/terraform-provider-aws/issues/11221.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Similar: #24265.

**Comment by ewbankkit** [comment]
##### TODO

* Add documentation
* Additional acceptance tests, especially for `schema_definition`

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccKeyspacesTable_ PKG=keyspaces ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/keyspaces/... -v -count 1 -parallel 2 -run='TestAccKeyspacesTable_'  -timeout 180m
=== RUN   TestAccKeyspacesTable_basic
=== PAUSE TestAccKeyspacesTable_basic
=== RUN   TestAccKeyspacesTable_disappears
=== PAUSE TestAccKeyspacesTable_disappears
=== RUN   TestAccKeyspacesTable_tags
=== PAUSE TestAccKeyspacesTable_tags
=== RUN   TestAccKeyspacesTable_multipleColumns
=== PAUSE TestAccKeyspacesTable_multipleColumns
=== RUN   TestAccKeyspacesTable_update
=== PAUSE TestAccKeyspacesTable_update
=== RUN   TestAccKeyspacesTable_addColumns
=== PAUSE TestAccKeyspacesTable_addColumns
=== RUN   TestAccKeyspacesTable_delColumns
=== PAUSE TestAccKeyspacesTable_delColumns
=== CONT  TestAccKeyspacesTable_basic
=== CONT  TestAccKeyspacesTable_update
--- PASS: TestAccKeyspacesTable_basic (105.06s)
=== CONT  TestAccKeyspacesTable_delColumns
--- PASS: TestAccKeyspacesTable_delColumns (143.91s)
=== CONT  TestAccKeyspacesTable_addColumns
--- PASS: TestAccKeyspacesTable_addColumns (114.99s)
=== CONT  TestAccKeyspacesTable_tags
--- PASS: TestAccKeyspacesTable_tags (126.74s)
=== CONT  TestAccKeyspacesTable_multipleColumns
--- PASS: TestAccKeyspacesTable_multipleColumns (102.18s)
=== CONT  TestAccKeyspacesTable_disappears
--- PASS: TestAccKeyspacesTable_disappears (89.17s)
--- PASS: TestAccKeyspacesTable_update (957.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/keyspaces	961.556s
```

**Comment by ewbankkit** [comment]
@pranayw333 Thanks for the contribution :tada: :clap:.

**Comment by pranayw333** [comment]
> @pranayw333 Thanks for the contribution 🎉 👏.

@ewbankkit Thank you so much for help :)

**Pull request merged**
