### PR TITLE
LF-Tag support for aws_lakeformation_permissions

### PR DESCRIPTION
**Pull request by danielcmessias**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #19640 

### Updates

21/04/2022: PR has been refactored into Service Packages (https://github.com/hashicorp/terraform-provider-aws/pull/21306). Massive thanks to @stevenayers for his work on this!

04/08/2021: I have added the next step for TBAC which is to support LFTagPolicy resource, allowing principals to be assigned permissions based on tag policy expression (as described [here](https://docs.aws.amazon.com/lake-formation/latest/dg/granting-catalog-perms-TBAC.html)). Since this PR is still awaiting triage, I've comitted the new functionality here instead of opening a new PR because, personally, I think it's easier to review together. Happy to split this new functionality into a subsequent branch if you'd prefer! The addition is made in [this commit](https://github.com/hashicorp/terraform-provider-aws/pull/19648/commits/75d7bc5e12a6d20727fbdcbb366bc83c838fb78b). 

03/08/2021:  I have renamed 'policy tag' to 'LF Tag' everywhere, to ensure consistency with the AWS API and Console. The change is made in [this commit.](https://github.com/hashicorp/terraform-provider-aws/pull/19648/commits/924eb29f9c5ff815e8965ccf76481c22ca475f37)

---

**To be reviewed AFTER https://github.com/hashicorp/terraform-provider-aws/pull/19523**
This work depends on the `aws_lakeformation_lf_tag` resource in the linked PR, so this branch is a continuation of that one. Files Changed is going to be wrong, relevant commits are downstream of https://github.com/hashicorp/terraform-provider-aws/pull/19648/commits/5bf3443d991335a36e350717140e8162e9e1b1b6 (inclusive). Let me know if there's a different preferred practice for dependant PRs. 

---

Adds the two new resources to aws_lakeformation_permissions that were made available with the TBAC workflow, LFTag and LFTagPolicy. This is essentially steps 4 and 5 in [AWS TBAC documentation](https://docs.aws.amazon.com/lake-formation/latest/dg/TBAC-overview.html#how-TBAC-works). 

#### lf_tag
Allows granting ASSOCIATE and DESCRIBE permissions to Lake Formation Policy Tags, and reading those permissions from a data source.

Example:
```terraform
resource "aws_lakeformation_permissions" "environment" {
  principal = aws_iam_role.some_role.arn

  permissions = ["ASSOCIATE", "DESCRIBE"]

  lf_tag {
    key = "Team"
    values = ["Sales", "Marketing"]
  }
}
```

#### lf_tag_resource
Allows granting LF-Tag policies that give permissions to principals based on a set of tag expressions.

Example:
```terraform
resource "aws_lakeformation_permissions" "sales" {
  principal = aws_iam_role.sales_role.arn

  permissions = ["CREATE_TABLE", "DROP"]

  lf_tag_policy {
    resource_type = "DATABASE"

    expression {
      key = "Team"
      values = ["Sales"]
    }

    expression {
      key = "Environment"
      values = ["Dev", "Production"]
    }

  }
}
```

Output from acceptance testing:

```
$ make testacc TESTS=TestAccLakeFormation_serial PKG=lakeformation
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20 -run='TestAccLakeFormation_serial'  -timeout 180m
=== RUN   TestAccLakeFormation_serial
=== RUN   TestAccLakeFormation_serial/PermissionsBasic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/disappears
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTag
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/basic
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/database
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple
=== RUN   TestAccLakeFormation_serial/PermissionsBasic/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/basic
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/database
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/dataLocation
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTag
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/table
=== RUN   TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTable
=== RUN   TestAccLakeFormation_serial/PermissionsTable/multipleRoles
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTable/basic
=== RUN   TestAccLakeFormation_serial/PermissionsTable/iamAllowed
=== RUN   TestAccLakeFormation_serial/PermissionsTable/implicit
=== RUN   TestAccLakeFormation_serial/PermissionsTable/selectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTable/selectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/basic
=== RUN   TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit
=== RUN   TestAccLakeFormation_serial/LFTags
=== RUN   TestAccLakeFormation_serial/LFTags/basic
=== RUN   TestAccLakeFormation_serial/LFTags/disappears
=== RUN   TestAccLakeFormation_serial/LFTags/values
=== RUN   TestAccLakeFormation_serial/DataLakeSettings
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/basic
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/dataSource
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/disappears
=== RUN   TestAccLakeFormation_serial/DataLakeSettings/withoutCatalogId
--- PASS: TestAccLakeFormation_serial (1156.95s)
    --- PASS: TestAccLakeFormation_serial/PermissionsBasic (306.83s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/disappears (90.26s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTag (27.24s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy (27.40s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/basic (27.02s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/database (27.54s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed (48.14s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple (27.91s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataLocation (31.32s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (223.20s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (36.85s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (30.48s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (33.84s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (29.10s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (28.95s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (32.47s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (31.50s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTable (287.18s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/multipleRoles (29.34s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardNoSelect (27.58s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectOnly (28.95s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/wildcardSelectPlus (29.35s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/basic (29.57s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/iamAllowed (50.94s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/implicit (29.93s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectOnly (31.91s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTable/selectPlus (29.60s)
    --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns (197.43s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardExcludedColumns (29.93s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectOnly (29.65s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/wildcardSelectPlus (30.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/basic (77.82s)
        --- PASS: TestAccLakeFormation_serial/PermissionsTableWithColumns/implicit (30.00s)
    --- PASS: TestAccLakeFormation_serial/LFTags (73.22s)
        --- PASS: TestAccLakeFormation_serial/LFTags/basic (20.11s)
        --- PASS: TestAccLakeFormation_serial/LFTags/disappears (17.62s)
        --- PASS: TestAccLakeFormation_serial/LFTags/values (35.49s)
    --- PASS: TestAccLakeFormation_serial/DataLakeSettings (69.10s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/basic (16.77s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/dataSource (18.53s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/disappears (17.01s)
        --- PASS: TestAccLakeFormation_serial/DataLakeSettings/withoutCatalogId (16.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	1158.457s
```

### CODE REVIEW

**Comment by danielcmessias** [comment]
Hi @zhelding @breathingdust! Any way I can find out where this sits with you guys in terms of prioritisation? Cheers :)

**Comment by WarFox** [comment]
Super critical feature from AWS to have in terraform. We've tested a build from this branch and it works great!! It would be awesome to get this merged into an official release 🚀 🚀 🚀

**Comment by jvirdee-gh** [comment]
@danielcmessias - Thank you for working on this feature.

Could you please rebase the code so that it can be merged?

**Comment by stevenayers** [comment]
Starting work to supersede #19523 following #21306 at #24314. Once I have completed that, I will move on to supersede this.

**Comment by stevenayers** [comment]
Superseded by https://github.com/hashicorp/terraform-provider-aws/pull/24315

**Comment by stevenayers** [comment]
@zhelding conflicts sorted when you get a chance, thank you! ❤️

**Comment by stevenayers** [comment]
@justinretzolk did a review of this PR make it into Q2?

**Comment by justinretzolk** [comment]
Hey @stevenayers 👋 I can confirm this did make it into the [roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md) 🎉. One note: it looks like this PR may be a duplicate of #19640, which is _technically_ the one that got prioritized, but the functionality is on the roadmap either way.

**Comment by YakDriver** [comment]
@danielcmessias @stevenayers You asked about the preferred practice for adding large features like this. I think what you've done is exactly right: breaking into manageable chunks and clear communication about what is going. For any design discussion about the new functionality generally, let's use issue #19640.

**Comment by danielcmessias** [comment]
> @danielcmessias @stevenayers Do you mind rebasing this now that #19523 is merged?

@YakDriver Rebased!

**Comment by YakDriver** [comment]
@danielcmessias @stevenayers It looks like only a little cleanup is needed. Basically, this looks really after a brief look. If it's good with you, I'll clean it up and we'll see if we can get it merged. If you are planning to make any changes, please coordinate with me. Thanks for all the great work!

**Comment by stevenayers** [comment]
> @danielcmessias @stevenayers It looks like only a little cleanup is needed. Basically, this looks really good after a brief look. If it's good with you, I'll clean it up and we'll see if we can get it merged. If you are planning to make any changes, please coordinate with me. Thanks for all the great work!

No objections from me, go for it!

**Comment by YakDriver** [comment]
My impression is that this closes #19640 and I changed it to close it. If anyone objects or I'm missing something, let me know.

**Comment by danielcmessias** [comment]
> My impression is that this closes #19640 and I changed it to close it. If anyone objects or I'm missing something, let me know.

The only bit of that issue that isn't covered by the two PRs @stevenayers and I worked on is the bit that applies LF tags to Glue resources, e.g.

```terraform
resource "aws_lakeformation_tag_resource" "" {
  catalog_id = "123456789"

  # A block to identify the Data Catalog Resource that the tag is being assigned to. Similar to aws_lakeformation_permissions
  database {
    #similar to aws_lakeformation_permissions
  }
  table {
    #similar to aws_lakeformation_permissions
  }
  table_with_columns {
    #similar to aws_lakeformation_permissions
  }

  # The tags that are being assigned
  lf_tags = [
    {
        catalog_id = "123456789"
        tag_key = "module"
        tag_values = ["A"]
      },
      {
        catalog_id = "123456789"
        tag_key = "region"
        tag_values = ["west"]
      }
  ]
}
```

To my knowledge, there is no open PR that adds that functionality. 

But regarding this PR, no incoming changes from me, looking forward to getting it merged. Thanks for reviewing! :)

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

```console
% make testacc TESTS="TestAccLakeFormation_serial/LFTags|TestAccLakeFormation_serial/PermissionsDataSource|TestAccLakeFormation_serial/PermissionsBasic" PKG=lakeformation
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lakeformation/... -v -count 1 -parallel 20 -run='TestAccLakeFormation_serial/LFTags|TestAccLakeFormation_serial/PermissionsDataSource|TestAccLakeFormation_serial/PermissionsBasic'  -timeout 180m
--- PASS: TestAccLakeFormation_serial (546.83s)
    --- PASS: TestAccLakeFormation_serial/PermissionsBasic (288.59s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/disappears (87.15s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTag (23.81s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/lfTagPolicy (25.10s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/basic (24.03s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/database (23.92s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseIAMAllowed (45.17s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/databaseMultiple (33.22s)
        --- PASS: TestAccLakeFormation_serial/PermissionsBasic/dataLocation (26.18s)
    --- PASS: TestAccLakeFormation_serial/PermissionsDataSource (198.13s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/basic (24.15s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/database (34.09s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/dataLocation (27.75s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTag (24.42s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/lfTagPolicy (24.42s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/table (28.31s)
        --- PASS: TestAccLakeFormation_serial/PermissionsDataSource/tableWithColumns (34.99s)
    --- PASS: TestAccLakeFormation_serial/LFTags (60.11s)
        --- PASS: TestAccLakeFormation_serial/LFTags/basic (17.10s)
        --- PASS: TestAccLakeFormation_serial/LFTags/disappears (14.17s)
        --- PASS: TestAccLakeFormation_serial/LFTags/values (28.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation	548.288s
```

**Comment by zerfahp** [comment]
Excuse my ignorance but I can't see this brilliant enhancement on the changelog. I can see docs have been updated and I can't wait to get stuck into using this capability. Thanks for all the work to enable this. Ahead of cloudformation again.

**Pull request merged**
