### PR TITLE
r/cloud9_environment_ec2 - validations + refactor to use finder and waiter packages + sweeper

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloud9EnvironmentEc2_'
--- PASS: TestAccAWSCloud9EnvironmentEc2_disappears (219.23s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_basic (280.01s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_tags (352.82s)
--- PASS: TestAccAWSCloud9EnvironmentEc2_allFields (383.01s)
```

### CODE REVIEW

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccCloud9EnvironmentEC2_ PKG=cloud9
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloud9/... -v -count 1 -parallel 20 -run='TestAccCloud9EnvironmentEC2_' -timeout 180m
=== RUN   TestAccCloud9EnvironmentEC2_basic
=== PAUSE TestAccCloud9EnvironmentEC2_basic
=== RUN   TestAccCloud9EnvironmentEC2_allFields
=== PAUSE TestAccCloud9EnvironmentEC2_allFields
=== RUN   TestAccCloud9EnvironmentEC2_tags
=== PAUSE TestAccCloud9EnvironmentEC2_tags
=== RUN   TestAccCloud9EnvironmentEC2_disappears
=== PAUSE TestAccCloud9EnvironmentEC2_disappears
=== CONT  TestAccCloud9EnvironmentEC2_basic
=== CONT  TestAccCloud9EnvironmentEC2_allFields
=== CONT  TestAccCloud9EnvironmentEC2_disappears
=== CONT  TestAccCloud9EnvironmentEC2_tags
--- PASS: TestAccCloud9EnvironmentEC2_disappears (168.15s)
--- PASS: TestAccCloud9EnvironmentEC2_basic (194.42s)
--- PASS: TestAccCloud9EnvironmentEC2_tags (215.75s)
--- PASS: TestAccCloud9EnvironmentEC2_allFields (308.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloud9	311.574s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Comment by DrFaust92** [comment]
@ewbankkit i think i messed up the sweeper here, checking quickly.

**Comment by ewbankkit** [comment]
@DrFaust92 I also fixed it:

```console
% make sweep SWEEPARGS=-sweep-run=aws_cloud9_environment_ec2 SWEEP=us-east-1,us-east-2,us-west-1,us-west-2
# make sweep SWEEPARGS=-sweep-run=aws_example_thing
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./internal/sweep -v -tags=sweep -sweep=us-east-1,us-east-2,us-west-1,us-west-2 -sweep-run=aws_cloud9_environment_ec2 -timeout 60m
2022/01/05 10:07:11 [DEBUG] Running Sweepers for region (us-east-1):
2022/01/05 10:07:11 [DEBUG] Running Sweeper (aws_cloud9_environment_ec2) in region (us-east-1)
2022/01/05 10:07:11 [INFO] AWS Auth provider used: "EnvProvider"
2022/01/05 10:07:11 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:12 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:14 [DEBUG] Completed Sweeper (aws_cloud9_environment_ec2) in region (us-east-1) in 3.148965918s
2022/01/05 10:07:14 Completed Sweepers for region (us-east-1) in 3.14921326s
2022/01/05 10:07:14 Sweeper Tests for region (us-east-1) ran successfully:
	- aws_cloud9_environment_ec2
2022/01/05 10:07:14 [DEBUG] Running Sweepers for region (us-east-2):
2022/01/05 10:07:14 [DEBUG] Running Sweeper (aws_cloud9_environment_ec2) in region (us-east-2)
2022/01/05 10:07:14 [INFO] AWS Auth provider used: "EnvProvider"
2022/01/05 10:07:14 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:14 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:15 [DEBUG] Completed Sweeper (aws_cloud9_environment_ec2) in region (us-east-2) in 622.911541ms
2022/01/05 10:07:15 Completed Sweepers for region (us-east-2) in 622.953124ms
2022/01/05 10:07:15 Sweeper Tests for region (us-east-2) ran successfully:
	- aws_cloud9_environment_ec2
2022/01/05 10:07:15 [DEBUG] Running Sweepers for region (us-west-1):
2022/01/05 10:07:15 [DEBUG] Running Sweeper (aws_cloud9_environment_ec2) in region (us-west-1)
2022/01/05 10:07:15 [INFO] AWS Auth provider used: "EnvProvider"
2022/01/05 10:07:15 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:15 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:16 [DEBUG] Completed Sweeper (aws_cloud9_environment_ec2) in region (us-west-1) in 977.456993ms
2022/01/05 10:07:16 Completed Sweepers for region (us-west-1) in 977.485434ms
2022/01/05 10:07:16 Sweeper Tests for region (us-west-1) ran successfully:
	- aws_cloud9_environment_ec2
2022/01/05 10:07:16 [DEBUG] Running Sweepers for region (us-west-2):
2022/01/05 10:07:16 [DEBUG] Running Sweeper (aws_cloud9_environment_ec2) in region (us-west-2)
2022/01/05 10:07:16 [INFO] AWS Auth provider used: "EnvProvider"
2022/01/05 10:07:16 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:16 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/01/05 10:07:17 [DEBUG] Completed Sweeper (aws_cloud9_environment_ec2) in region (us-west-2) in 1.057558192s
2022/01/05 10:07:17 Completed Sweepers for region (us-west-2) in 1.057577266s
2022/01/05 10:07:17 Sweeper Tests for region (us-west-2) ran successfully:
	- aws_cloud9_environment_ec2
ok  	github.com/hashicorp/terraform-provider-aws/internal/sweep	14.569s
```

**Pull request merged**
