### PR TITLE
r/neptune_cluster - add `copy_snapshot_to_tags` and refactor to use waiters

### LINKED ISSUE #19835: Add copy_tags_to_snapshot parameter to the aws_neptune_cluster
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Use-cases
Currently, aws_neptune_cluster is not supporting copy_tags_to_snapshot argument

### Attempted Solutions
copy_tags_to_snapshot argument is already implemented under aws_db_instance
https://www.terraform.io/docs/providers/aws/r/db_instance.html#copy_tags_to_snapshot

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19835

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSNeptuneCluster_'
--- PASS: TestAccAWSNeptuneCluster_disappears (199.05s)
--- PASS: TestAccAWSNeptuneCluster_basic (207.84s)
--- PASS: TestAccAWSNeptuneCluster_kmsKey (208.65s)
--- PASS: TestAccAWSNeptuneCluster_iamAuth (209.52s)
--- PASS: TestAccAWSNeptuneCluster_namePrefix (212.36s)
--- PASS: TestAccAWSNeptuneCluster_encrypted (229.47s)
--- PASS: TestAccAWSNeptuneCluster_tags (232.61s)
--- PASS: TestAccAWSNeptuneCluster_backupsUpdate (247.25s)
--- PASS: TestAccAWSNeptuneCluster_updateIamRoles (272.47s)
--- PASS: TestAccAWSNeptuneCluster_takeFinalSnapshot (277.15s)
--- PASS: TestAccAWSNeptuneCluster_deleteProtection (316.66s)
--- PASS: TestAccAWSNeptuneCluster_updateCloudwatchLogsExports (350.35s)
--- PASS: TestAccAWSNeptuneCluster_copyTagsToSnapshot (350.36s)
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSNeptuneCluster_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSNeptuneCluster_ -timeout 180m
=== RUN   TestAccAWSNeptuneCluster_basic
=== PAUSE TestAccAWSNeptuneCluster_basic
=== RUN   TestAccAWSNeptuneCluster_copyTagsToSnapshot
=== PAUSE TestAccAWSNeptuneCluster_copyTagsToSnapshot
=== RUN   TestAccAWSNeptuneCluster_namePrefix
=== PAUSE TestAccAWSNeptuneCluster_namePrefix
=== RUN   TestAccAWSNeptuneCluster_takeFinalSnapshot
=== PAUSE TestAccAWSNeptuneCluster_takeFinalSnapshot
=== RUN   TestAccAWSNeptuneCluster_tags
=== PAUSE TestAccAWSNeptuneCluster_tags
=== RUN   TestAccAWSNeptuneCluster_updateIamRoles
=== PAUSE TestAccAWSNeptuneCluster_updateIamRoles
=== RUN   TestAccAWSNeptuneCluster_kmsKey
=== PAUSE TestAccAWSNeptuneCluster_kmsKey
=== RUN   TestAccAWSNeptuneCluster_encrypted
=== PAUSE TestAccAWSNeptuneCluster_encrypted
=== RUN   TestAccAWSNeptuneCluster_backupsUpdate
=== PAUSE TestAccAWSNeptuneCluster_backupsUpdate
=== RUN   TestAccAWSNeptuneCluster_iamAuth
=== PAUSE TestAccAWSNeptuneCluster_iamAuth
=== RUN   TestAccAWSNeptuneCluster_updateCloudwatchLogsExports
=== PAUSE TestAccAWSNeptuneCluster_updateCloudwatchLogsExports
=== RUN   TestAccAWSNeptuneCluster_deleteProtection
=== PAUSE TestAccAWSNeptuneCluster_deleteProtection
=== RUN   TestAccAWSNeptuneCluster_disappears
=== PAUSE TestAccAWSNeptuneCluster_disappears
=== CONT  TestAccAWSNeptuneCluster_basic
=== CONT  TestAccAWSNeptuneCluster_encrypted
=== CONT  TestAccAWSNeptuneCluster_disappears
=== CONT  TestAccAWSNeptuneCluster_updateCloudwatchLogsExports
=== CONT  TestAccAWSNeptuneCluster_iamAuth
=== CONT  TestAccAWSNeptuneCluster_takeFinalSnapshot
=== CONT  TestAccAWSNeptuneCluster_tags
=== CONT  TestAccAWSNeptuneCluster_kmsKey
=== CONT  TestAccAWSNeptuneCluster_namePrefix
=== CONT  TestAccAWSNeptuneCluster_backupsUpdate
=== CONT  TestAccAWSNeptuneCluster_updateIamRoles
=== CONT  TestAccAWSNeptuneCluster_copyTagsToSnapshot
=== CONT  TestAccAWSNeptuneCluster_deleteProtection
--- PASS: TestAccAWSNeptuneCluster_namePrefix (144.52s)
--- PASS: TestAccAWSNeptuneCluster_iamAuth (161.84s)
--- PASS: TestAccAWSNeptuneCluster_basic (162.25s)
--- PASS: TestAccAWSNeptuneCluster_encrypted (162.29s)
--- PASS: TestAccAWSNeptuneCluster_kmsKey (164.44s)
--- PASS: TestAccAWSNeptuneCluster_disappears (175.22s)
--- PASS: TestAccAWSNeptuneCluster_tags (185.24s)
--- PASS: TestAccAWSNeptuneCluster_backupsUpdate (205.84s)
--- PASS: TestAccAWSNeptuneCluster_updateIamRoles (210.50s)
--- PASS: TestAccAWSNeptuneCluster_takeFinalSnapshot (225.08s)
--- PASS: TestAccAWSNeptuneCluster_updateCloudwatchLogsExports (232.74s)
--- PASS: TestAccAWSNeptuneCluster_copyTagsToSnapshot (270.12s)
--- PASS: TestAccAWSNeptuneCluster_deleteProtection (271.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	276.680s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSNeptuneCluster_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSNeptuneCluster_ -timeout 180m
=== RUN   TestAccAWSNeptuneCluster_basic
=== PAUSE TestAccAWSNeptuneCluster_basic
=== RUN   TestAccAWSNeptuneCluster_copyTagsToSnapshot
=== PAUSE TestAccAWSNeptuneCluster_copyTagsToSnapshot
=== RUN   TestAccAWSNeptuneCluster_namePrefix
=== PAUSE TestAccAWSNeptuneCluster_namePrefix
=== RUN   TestAccAWSNeptuneCluster_takeFinalSnapshot
=== PAUSE TestAccAWSNeptuneCluster_takeFinalSnapshot
=== RUN   TestAccAWSNeptuneCluster_tags
=== PAUSE TestAccAWSNeptuneCluster_tags
=== RUN   TestAccAWSNeptuneCluster_updateIamRoles
=== PAUSE TestAccAWSNeptuneCluster_updateIamRoles
=== RUN   TestAccAWSNeptuneCluster_kmsKey
=== PAUSE TestAccAWSNeptuneCluster_kmsKey
=== RUN   TestAccAWSNeptuneCluster_encrypted
=== PAUSE TestAccAWSNeptuneCluster_encrypted
=== RUN   TestAccAWSNeptuneCluster_backupsUpdate
=== PAUSE TestAccAWSNeptuneCluster_backupsUpdate
=== RUN   TestAccAWSNeptuneCluster_iamAuth
=== PAUSE TestAccAWSNeptuneCluster_iamAuth
=== RUN   TestAccAWSNeptuneCluster_updateCloudwatchLogsExports
=== PAUSE TestAccAWSNeptuneCluster_updateCloudwatchLogsExports
=== RUN   TestAccAWSNeptuneCluster_deleteProtection
=== PAUSE TestAccAWSNeptuneCluster_deleteProtection
=== RUN   TestAccAWSNeptuneCluster_disappears
=== PAUSE TestAccAWSNeptuneCluster_disappears
=== CONT  TestAccAWSNeptuneCluster_basic
=== CONT  TestAccAWSNeptuneCluster_encrypted
=== CONT  TestAccAWSNeptuneCluster_tags
=== CONT  TestAccAWSNeptuneCluster_kmsKey
=== CONT  TestAccAWSNeptuneCluster_deleteProtection
=== CONT  TestAccAWSNeptuneCluster_backupsUpdate
=== CONT  TestAccAWSNeptuneCluster_namePrefix
=== CONT  TestAccAWSNeptuneCluster_iamAuth
=== CONT  TestAccAWSNeptuneCluster_copyTagsToSnapshot
=== CONT  TestAccAWSNeptuneCluster_takeFinalSnapshot
=== CONT  TestAccAWSNeptuneCluster_updateIamRoles
=== CONT  TestAccAWSNeptuneCluster_updateCloudwatchLogsExports
=== CONT  TestAccAWSNeptuneCluster_disappears
--- PASS: TestAccAWSNeptuneCluster_disappears (123.26s)
--- PASS: TestAccAWSNeptuneCluster_iamAuth (139.29s)
--- PASS: TestAccAWSNeptuneCluster_encrypted (149.79s)
--- PASS: TestAccAWSNeptuneCluster_kmsKey (152.20s)
--- PASS: TestAccAWSNeptuneCluster_namePrefix (155.80s)
--- PASS: TestAccAWSNeptuneCluster_basic (158.61s)
--- PASS: TestAccAWSNeptuneCluster_updateIamRoles (177.83s)
--- PASS: TestAccAWSNeptuneCluster_backupsUpdate (192.48s)
--- PASS: TestAccAWSNeptuneCluster_tags (217.31s)
--- PASS: TestAccAWSNeptuneCluster_takeFinalSnapshot (220.12s)
--- PASS: TestAccAWSNeptuneCluster_updateCloudwatchLogsExports (239.56s)
--- PASS: TestAccAWSNeptuneCluster_deleteProtection (258.25s)
--- PASS: TestAccAWSNeptuneCluster_copyTagsToSnapshot (260.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	263.444s
```

**Comment by uadev** [comment]
It would be great to rename this to **copy_tags_to_snapshot** to avoid confusion.

**Comment by ewbankkit** [comment]
@uadev The new argument _is_ named `copy_tags_to_snapshot` 😄. It looks like a typo in the PR title and Release Notes (which I will fix).
Thanks.

**Comment by DrFaust92** [comment]
Don’t drink and code…

**Pull request merged**
