### PR TITLE
Improve changelog

### PR DESCRIPTION
**Pull request by Veetaha**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This PR fix inconsistencies in naming and punctuation in `CHANGELOG.md`

I would also like to use an IDE regex search-and-replace to surround all `(data-source/resource)/\w+:` patterns with backticks or `**` (**bold**) to make them stand out, because it is difficult to read the changelog when they are not highlighted, but that will be a huge-diff change. WDYT guys? I think it is worth it

### CODE REVIEW

**Comment by michimani** [comment]
I am very sorry. This was not a mistake.

I will make sure to check it carefully before creating a PR. Our apologies.

I apologize for the inconvenience, but I hope you will close this PR.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@Veetaha Thanks for the contribution :tada: :clap:.
The `CHANGELOG.md` lines are generated by https://github.com/hashicorp/go-changelog, so please open Issues/PRs there for any formatting changes.

**Comment by Veetaha** [comment]
Thanks for the pointer. Though is this PR allowed for merging, if is changing a generated file?

**Comment by ewbankkit** [comment]
Yes, I will merge this as only the `Unreleased` section of the CHANGELOG is generated on each merge.

**Pull request merged**
