### PR TITLE
r/aws_redshiftserverless_custom_domain_association: implement new resource

### LINKED ISSUE #35288: [Enhancement]: Add support to create/update/delete custom domain association for Amazon Redshift Serverless
### Description

Add support to create/update/delete custom domain name association for Amazon Redshift Serverless

### Affected Resource(s) and/or Data Source(s)

This would likely be a new resource

### Potential Terraform Configuration

```terraform
resource "aws_redshiftserverless_custom_domain_association" "example" {
  workgroup_name = "example"
  domain_name = "redshift.example.com"
  certificate_arn = "arn:aws:acm:region:account-id:certificate/certificate-id"
}
```

### References

- [AWS docs on custom domain name creation](https://docs.aws.amazon.com/redshift/latest/mgmt/connecting-connection-CNAME-connect.html)
- [AWS SDK for Go: CreateCustomDomainNameAssociation](https://docs.aws.amazon.com/sdk-for-go/api/service/redshiftserverless/#RedshiftServerless.CreateCustomDomainAssociation)
- [AWS SDK for Go: UpdateCustomDomainNameAssociation](https://docs.aws.amazon.com/sdk-for-go/api/service/redshiftserverless/#RedshiftServerless.UpdateCustomDomainAssociation)
- [AWS SDK for Go: DeleteCustomDomainNameAssociation](https://docs.aws.amazon.com/sdk-for-go/api/service/redshiftserverless/#RedshiftServerless.DeleteCustomDomainAssociation)

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by marcinbelczewski**
### Description

This PR implements aws_redshiftserverless_custom_domain_association to configure custom domain name for Amazon Redshift Serverless Workgroup.

### Relations

Closes #35288

### Output from Acceptance Testing

```console
make testacc TESTS=TestAccRedshiftServerlessCustomDomainAssociation PKG=redshiftserverless
```

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by marcinbelczewski** [comment]
Please let me know if I should do anything to get this merged?

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACM_CERTIFICATE_ROOT_DOMAIN=terraform-provider-aws-acctest-acm.com make testacc TESTARGS='-run=TestAccRedshiftServerlessCustomDomainAssociation_' PKG=redshiftserverless ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/redshiftserverless/... -v -count 1 -parallel 2  -run=TestAccRedshiftServerlessCustomDomainAssociation_ -timeout 360m
=== RUN   TestAccRedshiftServerlessCustomDomainAssociation_basic
=== PAUSE TestAccRedshiftServerlessCustomDomainAssociation_basic
=== RUN   TestAccRedshiftServerlessCustomDomainAssociation_disappears
=== PAUSE TestAccRedshiftServerlessCustomDomainAssociation_disappears
=== CONT  TestAccRedshiftServerlessCustomDomainAssociation_basic
=== CONT  TestAccRedshiftServerlessCustomDomainAssociation_disappears
--- PASS: TestAccRedshiftServerlessCustomDomainAssociation_disappears (300.57s)
--- PASS: TestAccRedshiftServerlessCustomDomainAssociation_basic (314.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless	325.167s
```

**Comment by ewbankkit** [comment]
@marcinbelczewski Thanks for the contribution :tada: :clap:.

**Pull request merged**
