### PR TITLE
Add VPC Lattice Listener resource

### LINKED ISSUE #30494: [New Resource]: aws_vpclattice_listener
### Description

AWS VPC Lattice reached GA recently. A listener checks for connection requests, and routes them to targets in a target group. A service can have up to two listeners, using the HTTP and HTTPS protocols and port numbers from 1 to 65535.

### Requested Resource(s) and/or Data Source(s)

* aws_vpclattice_listener

### Potential Terraform Configuration

```terraform
resource "aws_vpclattice_listener" "example" {
   defaultAction { 
      fixedResponse { 
         statusCode = 200
      }

      forward { 
         targetGroup { 
            { 
               targetGroupIdentifier = "myTGID"
               weight = 1
            }
         }
      }
   }

   name     = "mytargetgroup"
   port     = 443
   protocol = "HTTPS"

   tags { 
      tag1 = "value1" 
   }
}
```

### References

* API Reference: https://docs.aws.amazon.com/vpc-lattice/latest/APIReference/API_CreateListener.html
* API docs: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice
* User Guide: https://docs.aws.amazon.com/vpc-lattice/latest/ug/

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by ddericco**
### Description
Adds support for the VPC Lattice listener resource.

### Relations
Closes #30494 
Relates #30380 

### References

SDK: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/vpclattice@v1.0.2
API: https://docs.aws.amazon.com/sdk-for-go/api/service/vpclattice/
Documentation: https://docs.aws.amazon.com/vpc-lattice/latest/ug/listeners.html

### Output from Acceptance Testing

```
$ make testacc TESTARGS='-run=TestAccVPCLatticeListener_' PKG=vpclattice ACCTEST_PARALLELISM=3                                                                <aws:ddericco+netops-AdminAccess>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 3  -run=TestAccVPCLatticeListener_ -timeout 180m
=== RUN   TestAccVPCLatticeListener_defaultActionUpdate
=== PAUSE TestAccVPCLatticeListener_defaultActionUpdate
=== RUN   TestAccVPCLatticeListener_fixedResponsehttp
=== PAUSE TestAccVPCLatticeListener_fixedResponsehttp
=== RUN   TestAccVPCLatticeListener_fixedResponsehttps
=== PAUSE TestAccVPCLatticeListener_fixedResponsehttps
=== RUN   TestAccVPCLatticeListener_forwardhttpTargetGroup
=== PAUSE TestAccVPCLatticeListener_forwardhttpTargetGroup
=== RUN   TestAccVPCLatticeListener_forwardhttpTargetGroupCustomPort
=== PAUSE TestAccVPCLatticeListener_forwardhttpTargetGroupCustomPort
=== RUN   TestAccVPCLatticeListener_forwardhttpsTargetGroupArn
=== PAUSE TestAccVPCLatticeListener_forwardhttpsTargetGroupArn
=== RUN   TestAccVPCLatticeListener_forwardhttpsTargetGroupCustomPort
=== PAUSE TestAccVPCLatticeListener_forwardhttpsTargetGroupCustomPort
=== RUN   TestAccVPCLatticeListener_forwardhttpMultipleTargetGroups
=== PAUSE TestAccVPCLatticeListener_forwardhttpMultipleTargetGroups
=== RUN   TestAccVPCLatticeListener_disappears
=== PAUSE TestAccVPCLatticeListener_disappears
=== RUN   TestAccVPCLatticeListener_tags
=== PAUSE TestAccVPCLatticeListener_tags
=== CONT  TestAccVPCLatticeListener_defaultActionUpdate
=== CONT  TestAccVPCLatticeListener_forwardhttpTargetGroup
=== CONT  TestAccVPCLatticeListener_forwardhttpsTargetGroupArn
--- PASS: TestAccVPCLatticeListener_forwardhttpsTargetGroupArn (61.06s)
=== CONT  TestAccVPCLatticeListener_disappears
--- PASS: TestAccVPCLatticeListener_forwardhttpTargetGroup (77.55s)
=== CONT  TestAccVPCLatticeListener_forwardhttpMultipleTargetGroups
--- PASS: TestAccVPCLatticeListener_defaultActionUpdate (95.08s)
=== CONT  TestAccVPCLatticeListener_tags
--- PASS: TestAccVPCLatticeListener_disappears (56.21s)
=== CONT  TestAccVPCLatticeListener_forwardhttpsTargetGroupCustomPort
--- PASS: TestAccVPCLatticeListener_forwardhttpMultipleTargetGroups (82.18s)
=== CONT  TestAccVPCLatticeListener_fixedResponsehttp
--- PASS: TestAccVPCLatticeListener_forwardhttpsTargetGroupCustomPort (62.27s)
=== CONT  TestAccVPCLatticeListener_forwardhttpTargetGroupCustomPort
--- PASS: TestAccVPCLatticeListener_tags (107.21s)
=== CONT  TestAccVPCLatticeListener_fixedResponsehttps
--- PASS: TestAccVPCLatticeListener_fixedResponsehttp (56.93s)
--- PASS: TestAccVPCLatticeListener_forwardhttpTargetGroupCustomPort (71.80s)
--- PASS: TestAccVPCLatticeListener_fixedResponsehttps (70.02s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice 275.553s
```

### CODE REVIEW

**Comment by ddericco** [comment]
For some reason the PR isn't showing the latest commits from here: https://github.com/ddericco/terraform-provider-aws/commits/f-aws_vpclattice_listener_resource

**Review by ewbankkit — COMMENTED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCLatticeListener_' PKG=vpclattice ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 3  -run=TestAccVPCLatticeListener_ -timeout 180m
=== RUN   TestAccVPCLatticeListener_defaultActionUpdate
=== PAUSE TestAccVPCLatticeListener_defaultActionUpdate
=== RUN   TestAccVPCLatticeListener_fixedResponseHTTP
=== PAUSE TestAccVPCLatticeListener_fixedResponseHTTP
=== RUN   TestAccVPCLatticeListener_fixedResponseHTTPS
=== PAUSE TestAccVPCLatticeListener_fixedResponseHTTPS
=== RUN   TestAccVPCLatticeListener_forwardHTTPTargetGroup
=== PAUSE TestAccVPCLatticeListener_forwardHTTPTargetGroup
=== RUN   TestAccVPCLatticeListener_forwardHTTPTargetGroupCustomPort
=== PAUSE TestAccVPCLatticeListener_forwardHTTPTargetGroupCustomPort
=== RUN   TestAccVPCLatticeListener_forwardHTTPSTargetGroupARN
=== PAUSE TestAccVPCLatticeListener_forwardHTTPSTargetGroupARN
=== RUN   TestAccVPCLatticeListener_forwardHTTPSTargetGroupCustomPort
=== PAUSE TestAccVPCLatticeListener_forwardHTTPSTargetGroupCustomPort
=== RUN   TestAccVPCLatticeListener_forwardHTTPMultipleTargetGroups
=== PAUSE TestAccVPCLatticeListener_forwardHTTPMultipleTargetGroups
=== RUN   TestAccVPCLatticeListener_disappears
=== PAUSE TestAccVPCLatticeListener_disappears
=== RUN   TestAccVPCLatticeListener_tags
=== PAUSE TestAccVPCLatticeListener_tags
=== CONT  TestAccVPCLatticeListener_defaultActionUpdate
=== CONT  TestAccVPCLatticeListener_forwardHTTPSTargetGroupARN
=== CONT  TestAccVPCLatticeListener_disappears
--- PASS: TestAccVPCLatticeListener_defaultActionUpdate (73.18s)
=== CONT  TestAccVPCLatticeListener_forwardHTTPTargetGroup
--- PASS: TestAccVPCLatticeListener_disappears (73.29s)
=== CONT  TestAccVPCLatticeListener_forwardHTTPTargetGroupCustomPort
--- PASS: TestAccVPCLatticeListener_forwardHTTPSTargetGroupARN (113.43s)
=== CONT  TestAccVPCLatticeListener_tags
--- PASS: TestAccVPCLatticeListener_forwardHTTPTargetGroup (74.26s)
=== CONT  TestAccVPCLatticeListener_forwardHTTPMultipleTargetGroups
--- PASS: TestAccVPCLatticeListener_forwardHTTPTargetGroupCustomPort (93.88s)
=== CONT  TestAccVPCLatticeListener_forwardHTTPSTargetGroupCustomPort
--- PASS: TestAccVPCLatticeListener_tags (92.33s)
=== CONT  TestAccVPCLatticeListener_fixedResponseHTTPS
--- PASS: TestAccVPCLatticeListener_forwardHTTPSTargetGroupCustomPort (63.55s)
=== CONT  TestAccVPCLatticeListener_fixedResponseHTTP
--- PASS: TestAccVPCLatticeListener_forwardHTTPMultipleTargetGroups (83.62s)
--- PASS: TestAccVPCLatticeListener_fixedResponseHTTPS (58.47s)
--- PASS: TestAccVPCLatticeListener_fixedResponseHTTP (59.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice	296.008s
```

**Review by ewbankkit — APPROVED** [review]

**Comment by ewbankkit** [comment]
@ddericco Thanks for the contribution :tada: :clap:.

**Comment by meetreks** [comment]
Thanks a million @ddericco & @ewbankkit

**Pull request merged**
