### PR TITLE
F aws bedrock custom model

### LINKED ISSUE #33718: [New Resource]: `aws_bedrock_model_customization_job`
### Description

Add BedRock as a new Terraform Resource / Data Source so users with IaC requirements in their production environments can effectively start using the service.

### Requested Resource(s) and/or Data Source(s)

Resources:
- aws_bedrock_model_customization_job

Data Sources:
- aws_bedrock_model_customization_job

### Potential Terraform Configuration

```terraform
resource "aws_bedrock_model_customization_job" "example" {
  base_model_identifier = "asdf"
  client_request_token  = "c9a0b34f-877c-4cee-9fa6-e7d08d04f4fd"
  kms_key_id            = "arn:aws:kms:..."
  model_name            = "Custom Model"
  role_arn              = "arn:aws:iam:..."
  job_name              = "example"

  model_tags {
    "tag1" = "value1"
    "tag2" = "value2"
  }

  hyper_parameters {
    "param1" = "pvalue2"
  }

  job_tags {
    "tag1" = "value1"
    "tag2" = "value2"
  }

  output_data_config = {
    s3_uri = "s3://..."
  }

  training_data_config = {
    s3_uri = "s3://..."
  }

  validation_data_config = {
    s3_uri = "s3://..."
  }

  vpc_config = {
    security_group_ids = [
      "sg-123",
      "sg-456",
    ]

    subnet_ids = [
      "x",
      "y",
    ]
  }
}
```

### References

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_CreateModelCustomizationJob.html
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonbedrock.html

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by skyscrapr**
### Description

add aws_bedrock_custom_model resource and datasources

### Relations
Relates #34148
Closes #33718

### References

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_CreateModelCustomizationJob.html
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_GetCustomModel.html
https://docs.aws.amazon.com/bedrock/latest/APIReference/API_DeleteCustomModel.html

### Output from Acceptance Testing
```console
% make testacc TESTS=TestAccBedrockCustomModel_ PKG=bedrock

TBD...
```

### CODE REVIEW

**Comment by skyscrapr** [comment]
@wellsiau-aws @AdamTylerLynch Can you get this tested please? I no longer have an account with access to the Titan Express preview model required to test fine-tuning.

**Comment by silvaalbert** [comment]
> @wellsiau-aws @AdamTylerLynch Can you get this tested please? I no longer have an account with access to the Titan Express preview model required to test fine-tuning.

I'll run these today

**Comment by silvaalbert** [comment]
@skyscrapr - I was able to run tests but am getting failures. See below. Happy to collaborate on fixes if you like.

```
TF_ACC=1 go test ./internal/service/bedrock/... -v -count 1 -parallel 5 -run='TestAccBedrockCustomModelDataSource'  -timeout 360m
=== RUN   TestAccBedrockCustomModelDataSource_basic
=== PAUSE TestAccBedrockCustomModelDataSource_basic
=== CONT  TestAccBedrockCustomModelDataSource_basic
    custom_model_data_source_test.go:21: Step 1/1 error: Error running apply: exit status 1

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_bedrock_custom_model.test.base_model_arn. All values must be known after
        apply, so this is always a bug in the provider and should be reported in the
        provider's own repository. Terraform will still save the other known object
        values in the state.

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_bedrock_custom_model.test.creation_time. All values must be known after
        apply, so this is always a bug in the provider and should be reported in the
        provider's own repository. Terraform will still save the other known object
        values in the state.

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_bedrock_custom_model.test.model_arn. All values must be known after
        apply, so this is always a bug in the provider and should be reported in the
        provider's own repository. Terraform will still save the other known object
        values in the state.

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_bedrock_custom_model.test.model_kms_key_arn. All values must be known
        after apply, so this is always a bug in the provider and should be reported
        in the provider's own repository. Terraform will still save the other known
        object values in the state.

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_bedrock_custom_model.test.model_name. All values must be known after
        apply, so this is always a bug in the provider and should be reported in the
        provider's own repository. Terraform will still save the other known object
        values in the state.

        Error: Provider returned invalid result object after apply

        After the apply operation, the provider still indicated an unknown value for
        aws_bedrock_custom_model.test.tags_all. All values must be known after apply,
        so this is always a bug in the provider and should be reported in the
        provider's own repository. Terraform will still save the other known object
        values in the state.

        Error: Value Conversion Error

          with aws_bedrock_custom_model.test,
          on terraform_plugin_test.tf line 123, in resource "aws_bedrock_custom_model" "test":
         123: resource "aws_bedrock_custom_model" "test" {

        An unexpected error was encountered trying to convert from value. This is
        always an error in the provider. Please report the following to the provider
        developer:

        cannot use type bedrock.validationDataConfig as schema type
        basetypes.ListType; basetypes.ListType must be an attr.TypeWithAttributeTypes
        to hold bedrock.validationDataConfig
--- FAIL: TestAccBedrockCustomModelDataSource_basic (3873.56s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/bedrock	3876.854s
FAIL
make: *** [testacc] Error 1
```

**Comment by skyscrapr** [comment]
@silvaalbert ... hi, thanks for the output. Let me take a look at this today and I'll confirm if we need to connect to resolve.

**Comment by AdamTylerLynch** [comment]
@skyscrapr can you please contact me directly? awstyler [@] amazon.com

**Comment by AdamTylerLynch** [comment]
Current outputs:

```
make testacc TESTS=TestAccBedrockCustomModel_ PKG=bedrock
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/bedrock/... -v -count 1 -parallel 20 -run='TestAccBedrockCustomModel_'  -timeout 360m
=== RUN   TestAccBedrockCustomModel_basic
=== PAUSE TestAccBedrockCustomModel_basic
=== CONT  TestAccBedrockCustomModel_basic
    custom_model_test.go:20: Step 1/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_bedrock_custom_model.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: .training_metrics: block count changed from 0 to 1.
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccBedrockCustomModel_basic (4369.05s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/bedrock	4372.322s
FAIL
make: *** [testacc] Error 1
```

**Comment by AdamTylerLynch** [comment]
@skyscrapr has provided me access to their repo, and I am currently working on this PR. I expect to push more commits before the end of the year (2023).

**Comment by ewbankkit** [comment]
@AdamTylerLynch @skyscrapr I will pick this up as I gather you are busy with other tasks and this is a high priority roadmap item.

**Comment by ewbankkit** [comment]
This Terraform resource interacts with two Amazon Bedrock entities:

1. A Continued Pre-training or Fine-tuning job which is started when the Terraform resource is created. The customization job can take several hours to run to completion. The duration of the job depends on the size of the training data (number of records, input tokens, and output tokens), and [hyperparameters](https://docs.aws.amazon.com/bedrock/latest/userguide/custom-models-hp.html) (number of epochs, and batch size).
2. The custom model output on successful completion of the customization job.

This resource's [behaviors](https://developer.hashicorp.com/terraform/language/resources/behavior) correspond to operations on these Amazon Bedrock entities:

* [_Create_](https://developer.hashicorp.com/terraform/plugin/framework/resources/create) starts the customization job and immediately returns.
* [_Read_](https://developer.hashicorp.com/terraform/plugin/framework/resources/read) returns the status and results of the customization job. If the customization job has completed, the output model's properties are returned.
* [_Update_](https://developer.hashicorp.com/terraform/plugin/framework/resources/update) updates the customization job's [tags](https://docs.aws.amazon.com/bedrock/latest/userguide/tagging.html).
* [_Delete_](https://developer.hashicorp.com/terraform/plugin/framework/resources/delete) stops the customization job if it is still active. If the customization job has completed, the custom model output by the job is deleted.

**Comment by skyscrapr** [comment]
@ewbankkit @AdamTylerLynch  Hey gents. Apologies for dropping this. The customer I was working with put this on hold end of last year. I've been away for all of January and AFK. I'm back on the ground from Monday. Thanks for picking this up. Let me know if there's more to do, and I can continue to work on this.

**Review by ewbankkit — APPROVED** [review]
LGTM 🚀.

```console
% make testacc TESTARGS='-run=TestAccBedrockCustomModel_validationDataConfigWaitForCompletion' PKG=bedrock
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/bedrock/... -v -count 1 -parallel 20  -run=TestAccBedrockCustomModel_validationDataConfigWaitForCompletion -timeout 360m
=== RUN   TestAccBedrockCustomModel_validationDataConfigWaitForCompletion
=== PAUSE TestAccBedrockCustomModel_validationDataConfigWaitForCompletion
=== CONT  TestAccBedrockCustomModel_validationDataConfigWaitForCompletion
--- PASS: TestAccBedrockCustomModel_validationDataConfigWaitForCompletion (4376.29s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bedrock	4389.235s
```
```console
% make testacc TESTARGS='-run=TestAccBedrockFoundationModel' PKG=bedrock ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/bedrock/... -v -count 1 -parallel 2  -run=TestAccBedrockFoundationModel -timeout 360m
=== RUN   TestAccBedrockFoundationModelDataSource_basic
=== PAUSE TestAccBedrockFoundationModelDataSource_basic
=== RUN   TestAccBedrockFoundationModelsDataSource_basic
=== PAUSE TestAccBedrockFoundationModelsDataSource_basic
=== RUN   TestAccBedrockFoundationModelsDataSource_byCustomizationType
=== PAUSE TestAccBedrockFoundationModelsDataSource_byCustomizationType
=== RUN   TestAccBedrockFoundationModelsDataSource_byInferenceType
=== PAUSE TestAccBedrockFoundationModelsDataSource_byInferenceType
=== RUN   TestAccBedrockFoundationModelsDataSource_byOutputModality
=== PAUSE TestAccBedrockFoundationModelsDataSource_byOutputModality
=== CONT  TestAccBedrockFoundationModelDataSource_basic
=== CONT  TestAccBedrockFoundationModelsDataSource_byInferenceType
--- PASS: TestAccBedrockFoundationModelsDataSource_byInferenceType (14.20s)
=== CONT  TestAccBedrockFoundationModelsDataSource_byOutputModality
--- PASS: TestAccBedrockFoundationModelDataSource_basic (14.41s)
=== CONT  TestAccBedrockFoundationModelsDataSource_byCustomizationType
--- PASS: TestAccBedrockFoundationModelsDataSource_byCustomizationType (13.11s)
=== CONT  TestAccBedrockFoundationModelsDataSource_basic
--- PASS: TestAccBedrockFoundationModelsDataSource_byOutputModality (13.34s)
--- PASS: TestAccBedrockFoundationModelsDataSource_basic (11.82s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bedrock	50.205s
```
```console
% make testacc-short TESTARGS='-run=TestAccBedrockCustomModel_' PKG=bedrock ACCTEST_PARALLELISM=1   
==> Checking that code complies with gofmt requirements...
Running acceptance tests with -short flag
TF_ACC=1 go test ./internal/service/bedrock/... -v -short -count 1 -parallel 1  -run=TestAccBedrockCustomModel_ -timeout 360m
=== RUN   TestAccBedrockCustomModel_basic
=== PAUSE TestAccBedrockCustomModel_basic
=== RUN   TestAccBedrockCustomModel_disappears
=== PAUSE TestAccBedrockCustomModel_disappears
=== RUN   TestAccBedrockCustomModel_tags
=== PAUSE TestAccBedrockCustomModel_tags
=== RUN   TestAccBedrockCustomModel_kmsKey
=== PAUSE TestAccBedrockCustomModel_kmsKey
=== RUN   TestAccBedrockCustomModel_validationDataConfig
=== PAUSE TestAccBedrockCustomModel_validationDataConfig
=== RUN   TestAccBedrockCustomModel_validationDataConfigWaitForCompletion
    custom_model_test.go:209: skipping long-running test in short mode
--- SKIP: TestAccBedrockCustomModel_validationDataConfigWaitForCompletion (0.00s)
=== RUN   TestAccBedrockCustomModel_vpcConfig
=== PAUSE TestAccBedrockCustomModel_vpcConfig
=== CONT  TestAccBedrockCustomModel_basic
--- PASS: TestAccBedrockCustomModel_basic (60.77s)
=== CONT  TestAccBedrockCustomModel_kmsKey
--- PASS: TestAccBedrockCustomModel_kmsKey (59.36s)
=== CONT  TestAccBedrockCustomModel_vpcConfig
--- PASS: TestAccBedrockCustomModel_vpcConfig (56.68s)
=== CONT  TestAccBedrockCustomModel_validationDataConfig
--- PASS: TestAccBedrockCustomModel_validationDataConfig (58.70s)
=== CONT  TestAccBedrockCustomModel_tags
--- PASS: TestAccBedrockCustomModel_tags (57.94s)
=== CONT  TestAccBedrockCustomModel_disappears
--- PASS: TestAccBedrockCustomModel_disappears (76.31s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bedrock	380.208s
```
```console
% make testacc TESTARGS='-run=TestAccBedrockCustomModelDataSource_basic' PKG=bedrock
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/bedrock/... -v -count 1 -parallel 20  -run=TestAccBedrockCustomModelDataSource_basic -timeout 360m
=== RUN   TestAccBedrockCustomModelDataSource_basic
=== PAUSE TestAccBedrockCustomModelDataSource_basic
=== CONT  TestAccBedrockCustomModelDataSource_basic
--- PASS: TestAccBedrockCustomModelDataSource_basic (4298.45s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/bedrock	4309.648s
```

**Comment by ewbankkit** [comment]
@skyscrapr @AdamTylerLynch Thanks for the contribution :tada: :clap:.

**Pull request merged**
