### PR TITLE
F/resource aws dynamodb table: restore from point in time

### LINKED ISSUE #4558: Feature request: support restoration of DynamoDB Continuous Backups and Point-In-Time Recovery (PITR)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since the support of [Point-in-Time-Revocery](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#point_in_time_recovery) added with #4063, it is now possible to save continuous backups via Terraform, but restoring them is still only possible through the [Console](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html#restoretabletopointintime_console) or [AWS API](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html#restorepointintime_cli). It would be great to be able to also restore a dynamodb_table as a new resource created from the latest restorable time or a specific restorable time, similarly to what can be done with the [`snapshot_identifier` for rds instances](https://www.terraform.io/docs/providers/aws/r/db_instance.html#snapshot_identifier)

### New or Affected Resource(s)

* [aws_dynamodb_table](https://www.terraform.io/docs/providers/aws/r/dynamodb_table.html#point_in_time_recovery)

### Potential Terraform Configuration

An example usage in a DynamoDB module would possible look like this:
```hcl
resource "aws_dynamodb_table" "default" {
  name           = "example"
  hash_key       = "${var.hash_key}"
  range_key      = "${var.range_key}"

  point_in_time_recovery {
    restore_date_time = "${var.point_in_time_recovery_date_time}"
  }
```

### References

* #3927 : Feature request: support DynamoDB Continuous Backups and Point-In-Time Recovery (PITR) 
* #3775 : DynamoDB backup functionality?
* https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/PointInTimeRecovery.Tutorial.html#restorepointintime_cli

### PR DESCRIPTION
**Pull request by nikhil-goenka**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #4558

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSDynamoDbTable_backup_encryption'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDynamoDbTable_backup_encryption -timeout 180m
=== RUN   TestAccAWSDynamoDbTable_backup_encryption
=== PAUSE TestAccAWSDynamoDbTable_backup_encryption
=== CONT  TestAccAWSDynamoDbTable_backup_encryption
--- PASS: TestAccAWSDynamoDbTable_backup_encryption (880.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	884.651s
...
```

### CODE REVIEW

**Comment by nikhil-goenka** [comment]
Hi Guys,

written a small logic to support restore from point in time in dynamodb, tried to follow the approach from RDS cluster, please let me know if this is the right approach, then I can go ahead and add other test cases

**Comment by nikhil-goenka** [comment]
@ewbankkit : can you please review it once and let me know if this works ?

**Comment by AshishDadhich4h2** [comment]
Do you know when do we expect this change to be released in https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table

**Comment by AshishDadhich4h2** [comment]
> @ewbankkit : can you please review it once and let me know if this works ?

Why it's not being merged yet ?

**Comment by AshishDadhich4h2** [comment]
@ewbankkit would you please provide an update on this?

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Review by gdavison — APPROVED** [review]
Thanks for the PR, @nikhil-goenka. I've rebased the PR to account for the refactor in #20000. I've also made some tweaks to the code

Acceptance test results in Commercial partition

--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (43.75s)
--- PASS: TestAccDynamoDBTable_TTL_enabled (126.50s)
--- PASS: TestAccDynamoDBTable_lsiNonKeyAttributes (134.38s)
--- PASS: TestAccDynamoDBTable_basic (134.81s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned (201.05s)
--- PASS: TestAccDynamoDBTable_disappears (96.89s)
--- PASS: TestAccDynamoDBTable_enablePITR (232.94s)
--- PASS: TestAccDynamoDBTable_tableClassInfrequentAccess (234.41s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_payPerRequestToProvisioned (238.49s)
--- PASS: TestAccDynamoDBTable_streamSpecificationValidation (18.38s)
--- PASS: TestAccDynamoDBTable_Disappears_payPerRequestWithGSI (243.03s)
--- PASS: TestAccDynamoDBTable_lsiUpdate (208.63s)
--- PASS: TestAccDynamoDBTable_GsiUpdateNonKeyAttributes_emptyPlan (143.11s)
--- PASS: TestAccDynamoDBTable_TTL_disabled (148.57s)
--- PASS: TestAccDynamoDBTable_tags (93.92s)
--- PASS: TestAccDynamoDBTable_encryption (325.08s)
--- PASS: TestAccDynamoDBTable_gsiUpdateCapacity (98.44s)
--- PASS: TestAccDynamoDBTable_streamSpecification (103.49s)
--- PASS: TestAccDynamoDBTable_backup_encryption (372.73s)
--- PASS: TestAccDynamoDBTable_Replica_singleWithCMK (372.97s)
--- PASS: TestAccDynamoDBTable_gsiUpdateNonKeyAttributes (488.02s)
--- PASS: TestAccDynamoDBTable_extended (490.33s)
--- PASS: TestAccDynamoDBTable_Replica_single (589.03s)
--- PASS: TestAccDynamoDBTable_attributeUpdate (883.17s)
--- PASS: TestAccDynamoDBTable_BillingMode_provisionedToPayPerRequest (883.84s)
--- PASS: TestAccDynamoDBTable_backup_overrideEncryption (943.43s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_provisionedToPayPerRequest (1014.70s)
--- PASS: TestAccDynamoDBTable_Replica_multiple (1122.95s)
--- PASS: TestAccDynamoDBTable_gsiUpdateOtherAttributes (1171.49s)

Acceptance test results in GovCloud partition

--- PASS: TestAccDynamoDBTable_streamSpecificationValidation (20.12s)
--- SKIP: TestAccDynamoDBTable_tableClassInfrequentAccess (32.08s)
--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (33.73s)
--- PASS: TestAccDynamoDBTable_basic (83.21s)
--- PASS: TestAccDynamoDBTable_lsiNonKeyAttributes (92.32s)
--- PASS: TestAccDynamoDBTable_TTL_enabled (93.74s)
--- PASS: TestAccDynamoDBTable_tags (111.72s)
--- PASS: TestAccDynamoDBTable_GsiUpdateNonKeyAttributes_emptyPlan (140.63s)
--- PASS: TestAccDynamoDBTable_TTL_disabled (141.06s)
--- PASS: TestAccDynamoDBTable_streamSpecification (147.79s)
--- PASS: TestAccDynamoDBTable_gsiUpdateCapacity (157.28s)
--- PASS: TestAccDynamoDBTable_lsiUpdate (170.10s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_payPerRequestToProvisioned (146.78s)
--- PASS: TestAccDynamoDBTable_enablePITR (166.72s)
--- PASS: TestAccDynamoDBTable_disappears (77.04s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned (186.07s)
--- PASS: TestAccDynamoDBTable_Replica_singleWithCMK (302.40s)
--- PASS: TestAccDynamoDBTable_gsiUpdateNonKeyAttributes (303.36s)
--- PASS: TestAccDynamoDBTable_encryption (320.26s)
--- PASS: TestAccDynamoDBTable_Disappears_payPerRequestWithGSI (242.81s)
--- PASS: TestAccDynamoDBTable_extended (485.38s)
--- PASS: TestAccDynamoDBTable_attributeUpdate (579.89s)
--- PASS: TestAccDynamoDBTable_gsiUpdateOtherAttributes (580.11s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_provisionedToPayPerRequest (796.83s)
--- PASS: TestAccDynamoDBTable_BillingMode_provisionedToPayPerRequest (824.41s)
--- PASS: TestAccDynamoDBTable_backup_overrideEncryption (887.01s)
--- PASS: TestAccDynamoDBTable_backup_encryption (889.73s)
--- PASS: TestAccDynamoDBTable_Replica_single (1048.63s)

**Pull request merged**
