### PR TITLE
docdbelastic: Support backup_retention_period

### PR DESCRIPTION
**Pull request by ayumitamai97**
### Description

- Support `backup_retention_period` for DocumentDB Elastic Cluster
- Update the day of the week format for the acceptance test data
  - The first character of the day of the week should be upper case e.g. `Mon`
  - The acceptance tests don't pass without this change

### Relations

N/A

### References

- `backup_retention_period`
  - API specification https://docs.aws.amazon.com/documentdb/latest/developerguide/API_elastic_CreateCluster.html
  - The number should be between 1 and 35 https://docs.aws.amazon.com/documentdb/latest/developerguide/backup_restore.html
- Day of the week format
  - https://docs.aws.amazon.com/documentdb/latest/developerguide/db-cluster-modify.html

### Output from Acceptance Testing

```console
$ make testacc TESTS=TestAccDocDBElasticCluster_update PKG=docdbelastic
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/docdbelastic/... -v -count 1 -parallel 20 -run='TestAccDocDBElasticCluster_update'  -timeout 360m
=== RUN   TestAccDocDBElasticCluster_update
=== PAUSE TestAccDocDBElasticCluster_update
=== CONT  TestAccDocDBElasticCluster_update
--- PASS: TestAccDocDBElasticCluster_update (3854.77s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/docdbelastic       3858.935s

```

### CODE REVIEW

**Comment by ayumitamai97** [comment]
Thank you for prioritization, I'll resolve conflicts soon.

**Comment by johnsonaj** [comment]
> Thank you for prioritization, I'll resolve conflicts soon.

@ayumitamai97 Thanks for the followup! I am in the process of resolving the conflicts and will push updates shortly

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS="-run=TestAccDocDBElasticCluster_basic\|TestAccDocDBElasticCluster_update\|TestAccDocDBElasticCluster_disappears" PKG=docdbelastic

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/docdbelastic/... -v -count 1 -parallel 20  -run=TestAccDocDBElasticCluster_basic\|TestAccDocDBElasticCluster_update\|TestAccDocDBElasticCluster_disappears -timeout 360m
--- PASS: TestAccDocDBElasticCluster_basic (2430.48s)
--- PASS: TestAccDocDBElasticCluster_disappears (2484.99s)
--- PASS: TestAccDocDBElasticCluster_update (4160.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/docdbelastic	4166.958s
```

**Comment by johnsonaj** [comment]
@ayumitamai97 thank you for the contribution! 🎉

**Pull request merged**
