### PR TITLE
Add support for r/aws_appflow_flow

### PR DESCRIPTION
**Pull request by zhelding**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #23892 and #16253

### CODE REVIEW

**Comment by zhelding** [comment]
### Summary

This pull request adds support for the management Amazon AppFlow flow resources. The latest commit, 79239624a1ebf7ff1d880b5f21fb9bb50303f8bd, has passing acceptance tests: 

* `TestAccAppFlowFlow_basic`
* `TestAccAppFlowFlow_update`
* `TestAccAppFlowFlow_tags`
* `TestAccAppFlowFlow_disappears`

The test config used is an instance of a flow from an S3 bucket source to an S3 bucket destination; this is because further sources / destinations either require credential configuration via a forthcoming `aws_appflow_flow_connector_profile` resource (see #23892) _or_ a connection to a non-AWS service.

We will likely add additional tests covering connections between AWS resources, e.g. Redshift, once connector profile support has been added.

### Code Comments

#### Generic Destination Properties / Generic Source Properties:

A number of `appflow.DestinationProperties` structs have identical underlying attributes -- as do a number of `appflow.SourcePropeties`. These instances are labeled in this PR's docs as "Generic Destination Properties" and "Generic Source Properties" respectively.

As a result, there is a fair amount of repeating logic in the flatten / expand functions for these structs; the code could likely be made more DRY / elegant if we replaced these with a set of generic flatten / expand functions. However, I was personally unable to get the type conversion / assertion working correctly, i.e. without build errors.

#### `LookoutMetricsDestinationProperties`:

AWS' API reference does not list the valid attributes for [`LookoutMetricsDestinationProperties`](https://docs.aws.amazon.com/appflow/1.0/APIReference/API_LookoutMetricsDestinationProperties.html) -- simply stating that "the members of this structure are context-dependent". As such, we cannot support Amazon Lookout for Metrics as a flow destination for the time being.

**Comment by zhelding** [comment]
Acceptance tests passing on latest commit (https://github.com/hashicorp/terraform-provider-aws/pull/24017/commits/d27ee2841816d228189ba8a1855043bae2a5253a).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccAppFlowFlow_ PKG=appflow ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 2 -run='TestAccAppFlowFlow_'  -timeout 180m
=== RUN   TestAccAppFlowFlow_basic
=== PAUSE TestAccAppFlowFlow_basic
=== RUN   TestAccAppFlowFlow_update
=== PAUSE TestAccAppFlowFlow_update
=== RUN   TestAccAppFlowFlow_tags
=== PAUSE TestAccAppFlowFlow_tags
=== RUN   TestAccAppFlowFlow_disappears
=== PAUSE TestAccAppFlowFlow_disappears
=== CONT  TestAccAppFlowFlow_basic
=== CONT  TestAccAppFlowFlow_tags
--- PASS: TestAccAppFlowFlow_basic (29.03s)
=== CONT  TestAccAppFlowFlow_update
--- PASS: TestAccAppFlowFlow_tags (64.04s)
=== CONT  TestAccAppFlowFlow_disappears
--- PASS: TestAccAppFlowFlow_update (41.81s)
--- PASS: TestAccAppFlowFlow_disappears (23.09s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	91.041s
```

**Comment by zhelding** [comment]
Acceptance tests passing on latest commit https://github.com/hashicorp/terraform-provider-aws/pull/24017/commits/17b5b277049622bd80592fb3a4c82ec5be632e36. Merging! 🚀

**Pull request merged**
