### PR TITLE
add resource for aws_controltower_control

### LINKED ISSUE #26612: Add resources for controling Control Tower Guardrails
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We got API support for AWS Control Tower Guardrails: https://docs.aws.amazon.com/controltower/latest/userguide/guardrail-api-examples-short.html

### New or Affected Resource(s)

* aws_controltower_enable_control
* aws_controltower_disable_control
* aws_controltower_get_control

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

### PR DESCRIPTION
**Pull request by silvaalbert**
Closes #26612
Dependent on #26975, #26978

### Output from Acceptance Testing

```
$ TF_ACC=1 make testacc TESTS=TestAccControlTowerControl_serial PKG=controltower
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/controltower/... -v -count 1 -parallel 20 -run='TestAccControlTowerControl_serial'  -timeout 180m
=== RUN   TestAccControlTowerControl_serial
=== RUN   TestAccControlTowerControl_serial/ControlTowerControl
=== RUN   TestAccControlTowerControl_serial/ControlTowerControl/disappears
=== RUN   TestAccControlTowerControl_serial/ControlTowerControl/basic
--- PASS: TestAccControlTowerControl_serial (420.26s)
    --- PASS: TestAccControlTowerControl_serial/ControlTowerControl (420.26s)
        --- PASS: TestAccControlTowerControl_serial/ControlTowerControl/disappears (208.78s)
        --- PASS: TestAccControlTowerControl_serial/ControlTowerControl/basic (211.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/controltower	422.911s
...
```

### CODE REVIEW

**Comment by silvaalbert** [comment]
This PR adds a resource for aws_controltower_control, as described in #26612

**Comment by mrwacky42** [comment]
Amazing! I was just looking for this feature today.

**Comment by lossanarch** [comment]
> Amazing! I was just looking for this feature today. What's the canonical source for the ARNs of the controls ?

They can be found here @mrwacky42 
https://docs.aws.amazon.com/controltower/latest/userguide/control-identifiers.html

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccControlTowerControl_serial PKG=controltower
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/controltower/... -v -count 1 -parallel 20 -run='TestAccControlTowerControl_serial'  -timeout 180m
=== RUN   TestAccControlTowerControl_serial
=== RUN   TestAccControlTowerControl_serial/Control
=== RUN   TestAccControlTowerControl_serial/Control/basic
=== RUN   TestAccControlTowerControl_serial/Control/disappears
--- PASS: TestAccControlTowerControl_serial (440.40s)
    --- PASS: TestAccControlTowerControl_serial/Control (440.40s)
        --- PASS: TestAccControlTowerControl_serial/Control/basic (222.66s)
        --- PASS: TestAccControlTowerControl_serial/Control/disappears (217.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/controltower	445.133s
```

**Comment by ewbankkit** [comment]
@silvaalbert Thanks for the contribution :tada: :clap:.

**Pull request merged**
