### PR TITLE
Add new data source: `iam_access_keys`

### LINKED ISSUE #25585: Data Source for aws_iam_access_key
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The scenario: We need to create some AWS IAM user and access key in the process of creation of an EKS cluster. When there is an update in the cluster config and ran the TF a new aws_iam_access_key is created for the aws_iam_user and we get an error for exceeding quota for AccessKeyPerUser. The only way to skip this iam_access_key creation is by having a count attribute which is based on the condition if the access_key exists or not. But there is no aws_iam_access_key data source.

### New or Affected Resource(s)

aws_iam_access_key

### Potential Terraform Configuration

```hcl
data "aws_iam_access_key" "admin_user_key" {
  user_name = var.admin_user
}
resource "aws_iam_access_key" "admin_user_key" {
  count = data.aws_iam_access_key.admin_user_key.id != ""? 1 : 0
  user     = aws_iam_user.admin_user.name
  provider = aws.region
  status = var.status
  lifecycle {
    ignore_changes = all
  }
}
```

### PR DESCRIPTION
**Pull request by tmatilai**
### Description

The `aws_iam_access_keys` data source can be used to fetch information about IAM access keys of a specific IAM user.

One use case would be to conditionally create access keys (with the `aws_iam_access_key` resource) for a user only if none exist yet, and pass the created keys to a service which will then rotate them. This way there are no active keys in the Terraform state, nor anywhere outside the service.

### Relations

Closes #25585

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccIAMAccessKeysDataSource PKG=iam
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMAccessKeysDataSource'  -timeout 180m
=== RUN   TestAccIAMAccessKeysDataSource_basic
=== PAUSE TestAccIAMAccessKeysDataSource_basic
=== RUN   TestAccIAMAccessKeysDataSource_twoKeys
=== PAUSE TestAccIAMAccessKeysDataSource_twoKeys
=== CONT  TestAccIAMAccessKeysDataSource_basic
=== CONT  TestAccIAMAccessKeysDataSource_twoKeys
--- PASS: TestAccIAMAccessKeysDataSource_basic (22.36s)
--- PASS: TestAccIAMAccessKeysDataSource_twoKeys (22.41s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        24.459s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIAMAccessKeysDataSource_' PKG=iam
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20  -run=TestAccIAMAccessKeysDataSource_ -timeout 180m
=== RUN   TestAccIAMAccessKeysDataSource_basic
=== PAUSE TestAccIAMAccessKeysDataSource_basic
=== RUN   TestAccIAMAccessKeysDataSource_twoKeys
=== PAUSE TestAccIAMAccessKeysDataSource_twoKeys
=== CONT  TestAccIAMAccessKeysDataSource_basic
=== CONT  TestAccIAMAccessKeysDataSource_twoKeys
--- PASS: TestAccIAMAccessKeysDataSource_basic (19.56s)
--- PASS: TestAccIAMAccessKeysDataSource_twoKeys (19.63s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	26.131s
```

**Comment by ewbankkit** [comment]
@tmatilai Thanks for the contribution :tada: :clap:.

**Comment by tmatilai** [comment]
Thanks for merging! 🤗 

Btw, the changelog item was not included in the release notes or changelog, maybe [because of this failure](https://github.com/hashicorp/terraform-provider-aws/actions/runs/4747276554/jobs/8431974129)?
Of course this is not the most significant feature. 😅

**Comment by ewbankkit** [comment]
@tmatilai Actually the problem is there are only 2 backtick characters at the start of `.changelog/29278.txt`, not 3 😄.
I'll make sure that the **v4.64.0** CHANGELOG section is updated.

**Comment by tmatilai** [comment]
Oh my 🤦 😂

**Pull request merged**
