### PR TITLE
Elastic Inference Accelerators for SageMaker

### LINKED ISSUE #10208: Enhancement: Elastic Inference Accelerators for SageMaker
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Sagemaker on the CLI and Console support attaching an elastic inference accelerator to notebooks. This is a far cheaper option when creating your notebook than a full size P2 instance.

### New or Affected Resource(s)

* aws_sagemaker_notebook_instance

### Potential Terraform Configuration

* The configuration available under [launch templates](https://www.terraform.io/docs/providers/aws/r/launch_template.html#elastic_inference_accelerator) can be used as a reference for this functionality

### References

* [Elastic Inference](https://aws.amazon.com/machine-learning/elastic-inference/)
* [Resource aws_sagemaker_notebook_instance](https://github.com/terraform-providers/terraform-provider-aws/pull/2999)

### PR DESCRIPTION
**Pull request by WriteCodeEveryday**
Adds Elastic Inference Accelerators as an option for SageMaker notebooks.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #10208

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adds Elastic Inference as
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'
MISSING
...
```

### CODE REVIEW

**Comment by WriteCodeEveryday** [comment]
This change is missing go fmt as it was created a large change (30+ files). I'm trying to get my test suite up and running but it appears to be having issues.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMakerNotebookInstance_' PKG=sagemaker ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 3  -run=TestAccSageMakerNotebookInstance_ -timeout 180m
=== RUN   TestAccSageMakerNotebookInstance_basic
=== PAUSE TestAccSageMakerNotebookInstance_basic
=== RUN   TestAccSageMakerNotebookInstance_imds
=== PAUSE TestAccSageMakerNotebookInstance_imds
=== RUN   TestAccSageMakerNotebookInstance_update
=== PAUSE TestAccSageMakerNotebookInstance_update
=== RUN   TestAccSageMakerNotebookInstance_volumeSize
=== PAUSE TestAccSageMakerNotebookInstance_volumeSize
=== RUN   TestAccSageMakerNotebookInstance_lifecycleName
=== PAUSE TestAccSageMakerNotebookInstance_lifecycleName
=== RUN   TestAccSageMakerNotebookInstance_tags
=== PAUSE TestAccSageMakerNotebookInstance_tags
=== RUN   TestAccSageMakerNotebookInstance_kms
=== PAUSE TestAccSageMakerNotebookInstance_kms
=== RUN   TestAccSageMakerNotebookInstance_disappears
=== PAUSE TestAccSageMakerNotebookInstance_disappears
=== RUN   TestAccSageMakerNotebookInstance_Root_access
=== PAUSE TestAccSageMakerNotebookInstance_Root_access
=== RUN   TestAccSageMakerNotebookInstance_Platform_identifier
=== PAUSE TestAccSageMakerNotebookInstance_Platform_identifier
=== RUN   TestAccSageMakerNotebookInstance_DirectInternet_access
=== PAUSE TestAccSageMakerNotebookInstance_DirectInternet_access
=== RUN   TestAccSageMakerNotebookInstance_DefaultCode_repository
=== PAUSE TestAccSageMakerNotebookInstance_DefaultCode_repository
=== RUN   TestAccSageMakerNotebookInstance_AdditionalCode_repositories
=== PAUSE TestAccSageMakerNotebookInstance_AdditionalCode_repositories
=== RUN   TestAccSageMakerNotebookInstance_DefaultCodeRepository_sageMakerRepo
=== PAUSE TestAccSageMakerNotebookInstance_DefaultCodeRepository_sageMakerRepo
=== RUN   TestAccSageMakerNotebookInstance_acceleratorTypes
=== PAUSE TestAccSageMakerNotebookInstance_acceleratorTypes
=== CONT  TestAccSageMakerNotebookInstance_basic
=== CONT  TestAccSageMakerNotebookInstance_Root_access
=== CONT  TestAccSageMakerNotebookInstance_AdditionalCode_repositories
--- PASS: TestAccSageMakerNotebookInstance_basic (428.98s)
=== CONT  TestAccSageMakerNotebookInstance_acceleratorTypes
--- PASS: TestAccSageMakerNotebookInstance_acceleratorTypes (1142.76s)
=== CONT  TestAccSageMakerNotebookInstance_DirectInternet_access
--- PASS: TestAccSageMakerNotebookInstance_DirectInternet_access (759.71s)
=== CONT  TestAccSageMakerNotebookInstance_DefaultCode_repository
=== CONT  TestAccSageMakerNotebookInstance_Platform_identifier
--- PASS: TestAccSageMakerNotebookInstance_Root_access (795.57s)
--- PASS: TestAccSageMakerNotebookInstance_AdditionalCode_repositories (1533.78s)
=== CONT  TestAccSageMakerNotebookInstance_DefaultCodeRepository_sageMakerRepo
--- PASS: TestAccSageMakerNotebookInstance_Platform_identifier (765.05s)
=== CONT  TestAccSageMakerNotebookInstance_lifecycleName
--- PASS: TestAccSageMakerNotebookInstance_DefaultCode_repository (1188.18s)
=== CONT  TestAccSageMakerNotebookInstance_disappears
--- PASS: TestAccSageMakerNotebookInstance_disappears (420.78s)
=== CONT  TestAccSageMakerNotebookInstance_kms
--- PASS: TestAccSageMakerNotebookInstance_DefaultCodeRepository_sageMakerRepo (1151.62s)
=== CONT  TestAccSageMakerNotebookInstance_tags
--- PASS: TestAccSageMakerNotebookInstance_lifecycleName (1149.72s)
=== CONT  TestAccSageMakerNotebookInstance_update
--- PASS: TestAccSageMakerNotebookInstance_kms (314.78s)
=== CONT  TestAccSageMakerNotebookInstance_volumeSize
--- PASS: TestAccSageMakerNotebookInstance_tags (438.12s)
=== CONT  TestAccSageMakerNotebookInstance_imds
--- PASS: TestAccSageMakerNotebookInstance_update (726.20s)
--- PASS: TestAccSageMakerNotebookInstance_volumeSize (1036.36s)
--- PASS: TestAccSageMakerNotebookInstance_imds (862.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	3997.506s
```

**Comment by ewbankkit** [comment]
@WriteCodeEveryday Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
```console
% make providerlint golangci-lint                                                                           
==> Checking source code with providerlint...
==> Checking source code with golangci-lint...
```

**Pull request merged**
