### PR TITLE
Add recovery control config resources

### PR DESCRIPTION
**Pull request by ankita10051991**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes [#20566](https://github.com/hashicorp/terraform-provider-aws/issues/20566)

Output from acceptance testing:

**TO-DO**

### CODE REVIEW

**Comment by YakDriver** [comment]
Because the Meridian cluster limits are currently very low, I converted the tests to serial. When we get accounts and limits worked out, it would be great to change these back to parallel.

**Comment by ankita10051991** [comment]
> Because the Meridian cluster limits are currently very low, I converted the tests to serial. When we get accounts and limits worked out, it would be great to change these back to parallel.

We have default limit is 2 clusters for all accounts and I am not aware of any plans to change that. If there is a specific account id that you are using to run tests in parallel, I can get the limits increased for it tomorrow. Let me know

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

I made changes to get these working and bring them in alignment. Let me know if you have any questions.

Output from acceptance tests on `us-west-2`:
```
--- PASS: TestAccAWSRoute53RecoveryControlConfig_serial (753.90s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster (73.58s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster/basic (44.21s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster/disappears (29.37s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel (121.86s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel/basic (57.13s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel/disappears (64.73s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl (217.52s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/nonDefaultControlPane (85.87s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/basic (69.53s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/disappears (62.12s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule (340.94s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/assertionRule (106.92s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/gatingRule (127.20s)
        --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/disappears (106.82s)
```

Output from acceptance tests on `GovCloud`:
```
--- PASS: TestAccAWSRoute53RecoveryControlConfig_serial (1.53s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster (1.53s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster/basic (1.53s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster/disappears (0.00s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel/basic (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel/disappears (0.00s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/basic (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/disappears (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/nonDefaultControlPane (0.00s)
    --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/gatingRule (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/disappears (0.00s)
        --- SKIP: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/assertionRule (0.00s)
```

**Comment by ankita10051991** [comment]
> Looks good! 🎉
> 
> I made changes to get these working and bring them in alignment. Let me know if you have any questions.
> 
> Output from acceptance tests on `us-west-2`:
> 
> ```
> --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial (753.90s)
>     --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster (73.58s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster/basic (44.21s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/Cluster/disappears (29.37s)
>     --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel (121.86s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel/basic (57.13s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/ControlPanel/disappears (64.73s)
>     --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl (217.52s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/nonDefaultControlPane (85.87s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/basic (69.53s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/RoutingControl/disappears (62.12s)
>     --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule (340.94s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/assertionRule (106.92s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/gatingRule (127.20s)
>         --- PASS: TestAccAWSRoute53RecoveryControlConfig_serial/SafetyRule/disappears (106.82s)
> ```

Awesome. Looks good to me. Thank you so much Dirk. Appreciate it

**Pull request merged**
