### PR TITLE
r/aws_sagemaker_domain: add studio_web_portal_settings  and default_s…

### LINKED ISSUE #38150: [Enhancement]:  Add jupyter_lab_app_settings block to default_space_settings in aws_sagemaker_domain
### Description

SageMaker Studio now supports Shared JupyterLab spaces. In order to configure custom lifecycle configuration scripts, images etc. for shared spaces, a `jupyter_lab_app_settings` block needs to be added to the `aws_sagemaker_domain.default_space_settings` block.

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_domain" "this" {
  # other attributes ...
  
  default_space_settings {
    jupyter_lab_app_settings {
      code_repository {
        repository_url = "https://github.com/my_repo"
      }
      default_resource_spec {
        instance_type        = "ml.t3.medium"
        lifecycle_config_arn = aws_sagemaker_studio_lifecycle_config.jupyterlab.arn
        # sagemaker_image_arn
        # sagemaker_image_version_alias
        # sagemaker_image_version_arn
      }
      lifecycle_config_arns = [aws_sagemaker_studio_lifecycle_config.jupyterlab.arn]
      custom_image {
        app_image_config_name = aws_sagemaker_app_image_config.jupyterlab.id
        image_name            = aws_sagemaker_image.jupyterlab.id
      }
    }
  }
}
```

### References

1. https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.54.9/service/sagemaker#DefaultSpaceSettings
2. https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_domain.html

### Would you like to implement a fix?

No

### LINKED ISSUE #38240: [Enhancement]: aws_sagemaker_domain customize user interface
### Description

You can now customize the sagemaker domain user interface at either the domain level or the user profile level, this request is specifically for the aws_sagemaker_domain level. boto3 equivalent [create](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_domain.html) & [update](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/update_domain.html) command has the new argument under DefaultUserSettings 
 > StudioWebPortalSettings

This allows you to "hide" UI elements from your sagemaker domain instance.

```
        'StudioWebPortalSettings': {
            'HiddenMlTools': [
                'DataWrangler'|'FeatureStore'|'EmrClusters'|'AutoMl'|'Experiments'|'Training'|'ModelEvaluation'|'Pipelines'|'Models'|'JumpStart'|'InferenceRecommender'|'Endpoints'|'Projects',
            ],
            'HiddenAppTypes': [
                'JupyterServer'|'KernelGateway'|'DetailedProfiler'|'TensorBoard'|'CodeEditor'|'JupyterLab'|'RStudioServerPro'|'RSessionGateway'|'Canvas',
            ]
        }
```

https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-ui-customize.html

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_domain" "example" {
  domain_name = "example"
  auth_mode   = "IAM"
  vpc_id      = aws_vpc.example.id
  subnet_ids  = [aws_subnet.example.id]

  default_user_settings {
    execution_role = aws_iam_role.example.arn
    studio_web_portal_settings {
      hidden_ml_tools = ['DataWrangler', 'FeatureStore']
      hidden_app_types = ['Canvas', 'TensorBoard']
    }
  }
}
```

### References

[AWS Docs Here](https://docs.aws.amazon.com/sagemaker/latest/dg/studio-updated-ui-customize.html)

boto3 comparable commands here:
- [update domain](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/update_domain.html)
- [create domain](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/sagemaker/client/create_domain.html)

go comparable references here:
- [CreateDomain](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.CreateDomain)
-- [CreateDomainInput](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#CreateDomainInput)
--- [UserSettings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker@v1.149.1/types#UserSettings)
--- [StudioWebPortalSettings](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker@v1.149.1/types#StudioWebPortalSettings)

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by deepakbshetty**
### Description
`r/aws_sagemaker_domain`
Add `default_user_settings.studio_web_portal_settings` block
Add `default_space_settings.jupyter_lab_app_settings` block
Add `default_space_settings.space_storage_settings` block
Add `default_space_settings.custom_posix_user_config` block
Add `default_space_settings.custom_file_system_config` block

### Relations
Closes #38240
Closes #38150

### References
[StudioWebPortalSettings API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_UserSettings.html#sagemaker-Type-UserSettings-StudioWebPortalSettings)
[DefaultSpaceSettings API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_DefaultSpaceSettings.html)

### Output from Acceptance Testing
```
$ make testacc TESTS=TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenAppTypes PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenAppTypes'  -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenAppTypes
--- PASS: TestAccSageMaker_serial (387.69s)
    --- PASS: TestAccSageMaker_serial/Domain (387.69s)
        --- PASS: TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenAppTypes (387.68s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  413.998s

$ make testacc TESTS=TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenMlTools PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenMlTools'  -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenMlTools
--- PASS: TestAccSageMaker_serial (390.62s)
    --- PASS: TestAccSageMaker_serial/Domain (390.62s)
        --- PASS: TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenMlTools (390.61s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  425.121s

$ make testacc TESTS=TestAccSageMaker_serial/Domain/spaceSettingsJupyterLabAppSettings PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/spaceSettingsJupyterLabAppSettings'  -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsJupyterLabAppSettings
--- PASS: TestAccSageMaker_serial (394.52s)
    --- PASS: TestAccSageMaker_serial/Domain (394.52s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsJupyterLabAppSettings (394.52s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  428.117s

$ make testacc TESTS=TestAccSageMaker_serial/Domain/spaceSettingsSpaceStorageSettings PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/spaceSettingsSpaceStorageSettings'  -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsSpaceStorageSettings
--- PASS: TestAccSageMaker_serial (394.16s)
    --- PASS: TestAccSageMaker_serial/Domain (394.16s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsSpaceStorageSettings (394.15s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  425.158s

$ make testacc TESTS=TestAccSageMaker_serial/Domain/spaceSettingsCustomPosixUserConfig PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/spaceSettingsCustomPosixUserConfig'  -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsCustomPosixUserConfig
--- PASS: TestAccSageMaker_serial (391.35s)
    --- PASS: TestAccSageMaker_serial/Domain (391.35s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsCustomPosixUserConfig (391.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  422.740s

$ make testacc TESTS=TestAccSageMaker_serial/Domain/spaceSettingsCustomFileSystemConfigs PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMaker_serial/Domain/spaceSettingsCustomFileSystemConfigs'  -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsCustomFileSystemConfigs
--- PASS: TestAccSageMaker_serial (595.84s)
    --- PASS: TestAccSageMaker_serial/Domain (595.84s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsCustomFileSystemConfigs (595.83s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  625.961s
...
```

### CODE REVIEW

**Comment by deepakbshetty** [comment]
Dear @DrFaust92 , For your kind review.

**Comment by deepakbshetty** [comment]
Hi @jar-b, test issues are fixed now. Appreciate if you cam retrigger

**Comment by deepakbshetty** [comment]
Dear @DrFaust92, if you can approve this one for domain please.

**Comment by jmeisele** [comment]
Hello @deepakbshetty is there anyone on the AWS Provider team that can review & approve this PR?

**Comment by deepakbshetty** [comment]
> Hello @deepakbshetty is there anyone on the AWS Provider team that can review & approve this PR?

I would rely DrFaust92 in first place given maintainer for sagemaker and ultimately ewbankkit

**Review by DrFaust92 — APPROVED** [review]

**Comment by DrFaust92** [comment]
LGTM, i would add the same params for user_profile resource as well as it shared some of the expand functions. can be done in a different PR

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccSageMaker_serial/Domain' PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/sagemaker/... -v -count 1 -parallel 20  -run=TestAccSageMaker_serial/Domain -timeout 720m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/directDeploySettings
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsSpaceStorageSettings
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsCustomFileSystemConfigs
=== RUN   TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenAppTypes
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage
    domain_test.go:868: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/generativeAi
=== RUN   TestAccSageMaker_serial/Domain/kendraSettings
=== RUN   TestAccSageMaker_serial/Domain/efs
=== RUN   TestAccSageMaker_serial/Domain/jupyterLabAppSettings
=== RUN   TestAccSageMaker_serial/Domain/canvas
=== RUN   TestAccSageMaker_serial/Domain/codeEditorAppSettings_defaultResourceSpecAndCustomImage
    domain_test.go:762: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/kms
=== RUN   TestAccSageMaker_serial/Domain/securityGroup
=== RUN   TestAccSageMaker_serial/Domain/rStudioServerProAppSettings
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated
=== RUN   TestAccSageMaker_serial/Domain/disappears
=== RUN   TestAccSageMaker_serial/Domain/sharingSettings
=== RUN   TestAccSageMaker_serial/Domain/tags
=== RUN   TestAccSageMaker_serial/Domain/code
=== RUN   TestAccSageMaker_serial/Domain/domainSettings
=== RUN   TestAccSageMaker_serial/Domain/rStudioServerProDomainSettings
    acctest.go:1727: skipping test for aws/us-west-2: Error running apply: exit status 1
        
        Error: creating SageMaker Domain (d-phv6lvn91ohh): waiting for completion: unexpected state 'Failed', wanted target 'InService'. last error: ConfigurationError: Domain-level App [arn:aws:sagemaker:us-west-2:123456789012:app/d-phv6lvn91ohh/domain-shared/RStudioServerPro/default] failed to start: [ResourceNotFoundError: No available licenses were found. Validate that a license for RStudio Workbench exists in AWS License Manager that is in Active state.].
        
          with aws_sagemaker_domain.test,
          on terraform_plugin_test.tf line 86, in resource "aws_sagemaker_domain" "test":
          86: resource "aws_sagemaker_domain" "test" {
        
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsCustomPOSIXUserConfig
=== RUN   TestAccSageMaker_serial/Domain/spaceStorageSettings
=== RUN   TestAccSageMaker_serial/Domain/codeEditorAppSettings
=== RUN   TestAccSageMaker_serial/Domain/modelRegisterSettings
=== RUN   TestAccSageMaker_serial/Domain/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/Domain/identityProviderOauthSettings
=== RUN   TestAccSageMaker_serial/Domain/workspaceSettings
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsJupyterLabAppSettings
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage
    domain_test.go:907: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/codeEditorAppSettings_customImage
    domain_test.go:723: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/rSessionAppSettings
=== RUN   TestAccSageMaker_serial/Domain/posix
=== RUN   TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenMlTools
=== RUN   TestAccSageMaker_serial/Domain/basic
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage
--- PASS: TestAccSageMaker_serial (9939.48s)
    --- PASS: TestAccSageMaker_serial/Domain (9939.48s)
        --- PASS: TestAccSageMaker_serial/Domain/directDeploySettings (331.80s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsSpaceStorageSettings (262.68s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsCustomFileSystemConfigs (467.70s)
        --- PASS: TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenAppTypes (261.72s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/generativeAi (239.32s)
        --- PASS: TestAccSageMaker_serial/Domain/kendraSettings (249.19s)
        --- PASS: TestAccSageMaker_serial/Domain/efs (349.28s)
        --- PASS: TestAccSageMaker_serial/Domain/jupyterLabAppSettings (240.68s)
        --- PASS: TestAccSageMaker_serial/Domain/canvas (250.51s)
        --- SKIP: TestAccSageMaker_serial/Domain/codeEditorAppSettings_defaultResourceSpecAndCustomImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/kms (239.27s)
        --- PASS: TestAccSageMaker_serial/Domain/securityGroup (265.68s)
        --- PASS: TestAccSageMaker_serial/Domain/rStudioServerProAppSettings (277.65s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings (261.79s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettings (249.73s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings (250.12s)
        --- PASS: TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated (258.10s)
        --- PASS: TestAccSageMaker_serial/Domain/disappears (271.86s)
        --- PASS: TestAccSageMaker_serial/Domain/sharingSettings (249.68s)
        --- PASS: TestAccSageMaker_serial/Domain/tags (247.48s)
        --- PASS: TestAccSageMaker_serial/Domain/code (251.49s)
        --- PASS: TestAccSageMaker_serial/Domain/domainSettings (251.44s)
        --- SKIP: TestAccSageMaker_serial/Domain/rStudioServerProDomainSettings (654.60s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsCustomPOSIXUserConfig (254.57s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceStorageSettings (251.89s)
        --- PASS: TestAccSageMaker_serial/Domain/codeEditorAppSettings (250.20s)
        --- PASS: TestAccSageMaker_serial/Domain/modelRegisterSettings (249.57s)
        --- PASS: TestAccSageMaker_serial/Domain/jupyterServerAppSettings (239.78s)
        --- PASS: TestAccSageMaker_serial/Domain/identityProviderOauthSettings (250.87s)
        --- PASS: TestAccSageMaker_serial/Domain/workspaceSettings (240.54s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsJupyterLabAppSettings (251.21s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig (249.22s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage (0.00s)
        --- SKIP: TestAccSageMaker_serial/Domain/codeEditorAppSettings_customImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/rSessionAppSettings (250.09s)
        --- PASS: TestAccSageMaker_serial/Domain/posix (249.54s)
        --- PASS: TestAccSageMaker_serial/Domain/studioWebPortalSettings_hiddenMlTools (262.66s)
        --- PASS: TestAccSageMaker_serial/Domain/basic (249.30s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage (308.28s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	9944.342s
```

**Comment by ewbankkit** [comment]
@deepakbshetty Thanks for the contribution :tada: :clap:.

**Pull request merged**
