### PR TITLE
Appstream elastic fleet

### LINKED ISSUE #22587: AppStream Elastic fleets
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_appstream_appblock
* aws_appstream_application
* aws_appstream_fleet

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-appstream-2-0-launches-elastic-fleets-serverless-fleet-type/

* #6508

### PR DESCRIPTION
**Pull request by greasy-weasel**
This change adds support for the Appstream Elastic fleet type.    

It added two new variables:
-   platform
-   max_concurrent_sessions

These variables are both required to support elastic fleets.  The variable compute_capacity is no longer required, as this is not valid for elastic fleets.

Further support for applications and blocks can be added by using the awscc provider as suggested by Shkarlatov in #22587

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22587

Output from acceptance testing:

```
$ make testacc TESTS=TestAccAppStreamFleet_ PKG=appstream
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appstream/... -v -count 1 -parallel 20 -run='TestAccAppStreamFleet_'  -timeout 180m
=== RUN   TestAccAppStreamFleet_basic
=== PAUSE TestAccAppStreamFleet_basic
=== RUN   TestAccAppStreamFleet_disappears
=== PAUSE TestAccAppStreamFleet_disappears
=== RUN   TestAccAppStreamFleet_completeWithStop
=== PAUSE TestAccAppStreamFleet_completeWithStop
=== RUN   TestAccAppStreamFleet_completeWithoutStop
=== PAUSE TestAccAppStreamFleet_completeWithoutStop
=== RUN   TestAccAppStreamFleet_elasticWithTags
=== PAUSE TestAccAppStreamFleet_elasticWithTags
=== CONT  TestAccAppStreamFleet_basic
=== CONT  TestAccAppStreamFleet_completeWithoutStop
=== CONT  TestAccAppStreamFleet_elasticWithTags
=== CONT  TestAccAppStreamFleet_disappears
=== CONT  TestAccAppStreamFleet_completeWithStop
--- PASS: TestAccAppStreamFleet_elasticWithTags (310.91s)
--- PASS: TestAccAppStreamFleet_basic (833.88s)
--- PASS: TestAccAppStreamFleet_disappears (943.69s)
--- PASS: TestAccAppStreamFleet_completeWithoutStop (1060.04s)
--- PASS: TestAccAppStreamFleet_completeWithStop (2252.03s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appstream  2252.076s

...
```

I modified the TestAccAppStreamFleet_withTags to TestAccAppStreamFleet_elasticWithTags, this now creates an Elastic fleet instead of an ondemand stack.   Most AWS accounts can only support 5 Appstream fleets at the same time so this streamlines things a little.   We still get to test the creation of a stack with tags but now also the Elastic stack type.

### CODE REVIEW

**Comment by meijason** [comment]
All, 
We are planning to use Terraform provisioning AWS AppStream Elastic Fleet. The current Terraform AWS Provider(4.3.0) does not support Elastic Fleet. Can someone provide a timeline when Elastic Fleet will be supported in future version AWS Provider?

Thanks.
-Jason

**Comment by dylanl321** [comment]
Is this something that can be merged? What are we waiting on for this?

**Comment by alexandrepatrin** [comment]
Hello, is there any update on the implementation of these features? 2 years is a bit long...

**Comment by greasy-weasel** [comment]
Closed pull, I no longer have a need for this and it has conflicts with the main codebase which I do not have time to resolve.

**Pull request closed without merging**
