### PR TITLE
AWS_CE_COST_CATEGORY: be able to use nested operands like you can via aws api

### LINKED ISSUE #30810: [Bug]: Usage of 'not' block in aws_ce_cost_category throws error
### Terraform Core Version

1.4.5

### AWS Provider Version

4.63.0

### Affected Resource(s)

aws_ce_cost_category

### Expected Behavior

A cost category should be created havin the following structure:

_AWS JSON syntax directly taken from a cost category created manually using the AWS console_
```json
{
  "RuleVersion": "CostCategoryExpression.v1",
  "Rules": [
    {
      "Type": "REGULAR",
      "Value": "taxexcluded",
      "Rule": {
        "And": [
          {
            "Dimensions": {
              "Key": "LINKED_ACCOUNT",
              "Values": [
                "############",
                "############"
              ],
              "MatchOptions": [
                "EQUALS"
              ]
            }
          },
          {
            "Not": {
              "Dimensions": {
                "Key": "RECORD_TYPE",
                "Values": [
                  "Tax"
                ],
                "MatchOptions": [
                  "EQUALS"
                ]
              }
            }
          }
        ]
      }
    },
    {
      "Type": "REGULAR",
      "Value": "onlytax",
      "Rule": {
        "And": [
          {
            "Dimensions": {
              "Key": "LINKED_ACCOUNT",
              "Values": [
                "############",
                "############"
              ],
              "MatchOptions": [
                "EQUALS"
              ]
            }
          },
          {
            "Dimensions": {
              "Key": "RECORD_TYPE",
              "Values": [
                "Tax"
              ],
              "MatchOptions": [
                "EQUALS"
              ]
            }
          }
        ]
      }
    }
  ]
}
```

### Actual Behavior

Errors are being thrown.

### Relevant Error/Panic Output Snippet

```shell
> Error: updating AWS CE (Cost Explorer) Cost Category (arn:aws:ce::############:costcategory/###########################): ValidationException: Failed to update Cost Category: Expression has more than one roots. Only one root operator is allowed for each expression: And, Or, Not, Dimensions, Tags, CostCategories
```

### Terraform Configuration Files

```hcl
resource "aws_ce_cost_category" "test" {
  name            = "excludevat"
  rule_version    = "CostCategoryExpression.v1"
  effective_start = local.effective_start_date

  rule {
    type  = "REGULAR"
    value = "onlytax"

    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT"
          values        = ["###########", "###########"]
          match_options = [
            "EQUALS"
          ]
        }
      }
      and {
        dimension {
          key           = "RECORD_TYPE"
          values        = ["Tax"]
          match_options = [
            "EQUALS"
          ]
        }
      }
    }
  }

  rule {
    type  = "REGULAR"
    value = "taxexcluded"

    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT"
          values        = ["###########", "###########"]
          match_options = [
            "EQUALS"
          ]
        }
      }
      not {
        dimension {
          key           = "RECORD_TYPE"
          values        = ["Tax"]
          match_options = [
            "EQUALS"
          ]
        }
      }
    }
  }
}
```

### Steps to Reproduce

The documentation [1] says that on the inner rule level it is possible to set a `not`. But no matter what we always get the error mentioned above. It's also not possible to set the `not` anywhere else.

### Debug Output

Interesting is what terraform does if we import the manually created cost category. The state looks completely incorrect to me. Leaving the essential exlcuding part in the rule that is named "taxexcluded"

```json
  {
      "mode": "managed",
      "type": "aws_ce_cost_category",
      "name": "test",
      "provider": "provider[\"registry.terraform.io/hashicorp/aws\"]",
      "instances": [
        {
          "schema_version": 0,
          "attributes": {
            "arn": "arn:aws:ce::#######:costcategory/#######",
            "default_value": "",
            "effective_end": "",
            "effective_start": "2023-03-01T00:00:00Z",
            "id": "arn:aws:ce::######:costcategory/#######",
            "name": "excludevat",
            "rule": [
              {
                "inherited_value": [],
                "rule": [
                  {
                    "and": [
                      {
                        "cost_category": [],
                        "dimension": [
                          {
                            "key": "LINKED_ACCOUNT",
                            "match_options": [
                              "EQUALS"
                            ],
                            "values": [
                              "######",
                              "######"
                            ]
                          }
                        ],
                        "tags": []
                      },
                      {
                        "cost_category": [],
                        "dimension": [
                          {
                            "key": "RECORD_TYPE",
                            "match_options": [
                              "EQUALS"
                            ],
                            "values": [
                              "Tax"
                            ]
                          }
                        ],
                        "tags": []
                      }
                    ],
                    "cost_category": [],
                    "dimension": [],
                    "not": [],
                    "or": [],
                    "tags": []
                  }
                ],
                "type": "REGULAR",
                "value": "onlytax"
              },
              {
                "inherited_value": [],
                "rule": [
                  {
                    "and": [
                      {
                        "cost_category": [],
                        "dimension": [
                          {
                            "key": "LINKED_ACCOUNT",
                            "match_options": [
                              "EQUALS"
                            ],
                            "values": [
                              "######",
                              "######"
                            ]
                          }
                        ],
                        "tags": []
                      },
                      {
                        "cost_category": [],
                        "dimension": [],
                        "tags": []
                      }
                    ],
                    "cost_category": [],
                    "dimension": [],
                    "not": [],
                    "or": [],
                    "tags": []
                  }
                ],
                "type": "REGULAR",
                "value": "taxexcluded"
              }
            ],
            "rule_version": "CostCategoryExpression.v1",
            "split_charge_rule": [],
            "tags": {},
            "tags_all": {}
          },
          "sensitive_attributes": [],
          "private": "#########"
        }
      ]
    },
```

### Panic Output

_No response_

### Important Factoids

There are no examples regarding `not`, `or` and `and` and there are only unit tests covering `and`.
The whole structure seems to be different compared to the JSON used by AWS.
Why not change the implementation so that you just pass the original AWS JSON here, instead of creating this individual structure using blocks?

### References

1. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ce_cost_category#rule
2. https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ce/cost_category_test.go

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by huetterma**
### Description
AWS Cost Categories allows nested operands by default. Confirmed by their [source code](https://pkg.go.dev/github.com/aws/aws-sdk-go/service/costexplorer#Expression):
```
type Expression struct {
	_ struct{} `type:"structure"`

	// Return results that match both Dimension objects.
	And []*Expression `type:"list"`

	// The filter that's based on CostCategory values.
	CostCategories *CostCategoryValues `type:"structure"`

	// The specific Dimension to use for Expression.
	Dimensions *DimensionValues `type:"structure"`

	// Return results that don't match a Dimension object.
	Not *Expression `type:"structure"`

	// Return results that match either Dimension object.
	Or []*Expression `type:"list"`

	// The specific Tag to use for Expression.
	Tags *TagValues `type:"structure"`
}
```

As you can see all three operands `not`, `and` and `or` having the `Expression` type which allows for combination like this via AWS API

```json
"Rules":[{
  "Rule":{
    "And":[
      {"Not":{"Dimensions":{"Key":"RECORD_TYPE","MatchOptions":["EQUALS"],"Values":["Tax"]}}},
      {"Dimensions":{"Key":"LINKED_ACCOUNT","MatchOptions":["EQUALS"],"Values":["##########","########"]}}
    ]
  },
 "Type":"REGULAR","Value":"taxexclusion"}]
```
This example could not be created via Terraform because the schema for the operand only allows to be of `tags`, `dimension` or `cost_category`, [schema](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ce/cost_category.go#L174), [eligible expression for and/or/not](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/ce/cost_category.go#L280)

This PR would allow to create the corresponding AWS API JSON and constructs like this:
```
rule {
    value = "taxexclusion"
    rule {
      and {
        dimension {
          key           = "LINKED_ACCOUNT_NAME"
          values      = ["########", "######"]
          match_options = ["EQUALS"]
        }
      }
      and {
        not {
          dimension {
            key           = "RECORD_TYPE"
            values        = ["Tax"]
            match_options = ["EQUALS"]
          }
        }
	  }
    }
    type = "REGULAR"
```

### TODO
Correct value for maximum operand nesting, code variable `costCategoryRuleMaxNesting`

### Relations
Closes #30810 

### References
References are included in the Description

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by porqueoutai** [comment]
Hey,
@ewbankkit @justinretzolk 

Would be glad, if we could work out a solution together to implement this. It is actually blocking for us.

We have to decide the max nesting factor, or come up with another solution. Glad to hear your ideas.

**Comment by bebold-jhr** [comment]
Hello @justinretzolk,

any chance someone can have a look at this PR?

**Comment by justinretzolk** [comment]
Hey @bebold-jhr 👋 Thank you for checking in on this! Unfortunately I can't provide an ETA on when this will be reviewed/merged due to the potential of shifting priorities. We prioritize by count of :+1: reactions and a few other things (more information on our [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/) if you're interested).

**Comment by smokingroosters** [comment]
Any update on this?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCE' PKG=ce ACCTEST_PARALLELISM=2        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/ce/... -v -count 1 -parallel 2  -run=TestAccCE -timeout 360m
=== RUN   TestAccCEAnomalyMonitor_basic
=== PAUSE TestAccCEAnomalyMonitor_basic
=== RUN   TestAccCEAnomalyMonitor_disappears
=== PAUSE TestAccCEAnomalyMonitor_disappears
=== RUN   TestAccCEAnomalyMonitor_update
=== PAUSE TestAccCEAnomalyMonitor_update
=== RUN   TestAccCEAnomalyMonitor_tags
=== PAUSE TestAccCEAnomalyMonitor_tags
=== RUN   TestAccCEAnomalyMonitor_Dimensional
=== PAUSE TestAccCEAnomalyMonitor_Dimensional
=== RUN   TestAccCEAnomalySubscription_basic
=== PAUSE TestAccCEAnomalySubscription_basic
=== RUN   TestAccCEAnomalySubscription_disappears
=== PAUSE TestAccCEAnomalySubscription_disappears
=== RUN   TestAccCEAnomalySubscription_Frequency
=== PAUSE TestAccCEAnomalySubscription_Frequency
=== RUN   TestAccCEAnomalySubscription_MonitorARNList
=== PAUSE TestAccCEAnomalySubscription_MonitorARNList
=== RUN   TestAccCEAnomalySubscription_Subscriber
=== PAUSE TestAccCEAnomalySubscription_Subscriber
=== RUN   TestAccCEAnomalySubscription_Tags
=== PAUSE TestAccCEAnomalySubscription_Tags
=== RUN   TestAccCECostAllocationTag_basic
=== PAUSE TestAccCECostAllocationTag_basic
=== RUN   TestAccCECostAllocationTag_disappears
=== PAUSE TestAccCECostAllocationTag_disappears
=== RUN   TestAccCECostCategoryDataSource_basic
=== PAUSE TestAccCECostCategoryDataSource_basic
=== RUN   TestAccCECostCategory_basic
=== PAUSE TestAccCECostCategory_basic
=== RUN   TestAccCECostCategory_effectiveStart
=== PAUSE TestAccCECostCategory_effectiveStart
=== RUN   TestAccCECostCategory_disappears
=== PAUSE TestAccCECostCategory_disappears
=== RUN   TestAccCECostCategory_complete
=== PAUSE TestAccCECostCategory_complete
=== RUN   TestAccCECostCategory_notWithAnd
=== PAUSE TestAccCECostCategory_notWithAnd
=== RUN   TestAccCECostCategory_splitCharge
=== PAUSE TestAccCECostCategory_splitCharge
=== RUN   TestAccCECostCategory_tags
=== PAUSE TestAccCECostCategory_tags
=== RUN   TestAccCETagsDataSource_basic
=== PAUSE TestAccCETagsDataSource_basic
=== RUN   TestAccCETagsDataSource_filter
=== PAUSE TestAccCETagsDataSource_filter
=== CONT  TestAccCEAnomalyMonitor_basic
=== CONT  TestAccCECostAllocationTag_disappears
--- PASS: TestAccCECostAllocationTag_disappears (17.73s)
=== CONT  TestAccCECostCategory_notWithAnd
--- PASS: TestAccCEAnomalyMonitor_basic (20.82s)
=== CONT  TestAccCETagsDataSource_filter
--- PASS: TestAccCETagsDataSource_filter (18.06s)
=== CONT  TestAccCETagsDataSource_basic
--- PASS: TestAccCECostCategory_notWithAnd (21.40s)
=== CONT  TestAccCECostCategory_tags
--- PASS: TestAccCETagsDataSource_basic (17.80s)
=== CONT  TestAccCECostCategory_splitCharge
--- PASS: TestAccCECostCategory_tags (48.39s)
=== CONT  TestAccCECostCategory_complete
--- PASS: TestAccCECostCategory_splitCharge (38.68s)
=== CONT  TestAccCEAnomalySubscription_disappears
--- PASS: TestAccCEAnomalySubscription_disappears (24.32s)
=== CONT  TestAccCECostAllocationTag_basic
--- PASS: TestAccCECostCategory_complete (42.97s)
=== CONT  TestAccCEAnomalySubscription_Tags
--- PASS: TestAccCECostAllocationTag_basic (49.41s)
=== CONT  TestAccCEAnomalySubscription_Subscriber
--- PASS: TestAccCEAnomalySubscription_Tags (50.47s)
=== CONT  TestAccCEAnomalySubscription_MonitorARNList
--- PASS: TestAccCEAnomalySubscription_MonitorARNList (38.38s)
=== CONT  TestAccCEAnomalySubscription_Frequency
--- PASS: TestAccCEAnomalySubscription_Subscriber (76.40s)
=== CONT  TestAccCECostCategory_basic
--- PASS: TestAccCEAnomalySubscription_Frequency (40.98s)
=== CONT  TestAccCECostCategoryDataSource_basic
--- PASS: TestAccCECostCategory_basic (26.32s)
=== CONT  TestAccCECostCategory_disappears
--- PASS: TestAccCECostCategoryDataSource_basic (20.93s)
=== CONT  TestAccCEAnomalyMonitor_tags
--- PASS: TestAccCECostCategory_disappears (20.40s)
=== CONT  TestAccCEAnomalySubscription_basic
--- PASS: TestAccCEAnomalySubscription_basic (23.99s)
=== CONT  TestAccCEAnomalyMonitor_Dimensional
--- PASS: TestAccCEAnomalyMonitor_tags (53.34s)
=== CONT  TestAccCEAnomalyMonitor_update
--- PASS: TestAccCEAnomalyMonitor_Dimensional (25.53s)
=== CONT  TestAccCEAnomalyMonitor_disappears
--- PASS: TestAccCEAnomalyMonitor_disappears (18.06s)
=== CONT  TestAccCECostCategory_effectiveStart
--- PASS: TestAccCEAnomalyMonitor_update (35.88s)
--- PASS: TestAccCECostCategory_effectiveStart (35.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ce	406.679s
```

**Comment by ewbankkit** [comment]
@huetterma Thanks for the contribution :tada: :clap:.

**Pull request merged**
