### PR TITLE
Fix s3 third party provider error on creating bucket without object lock

### PR DESCRIPTION
**Pull request by cristiGuranIonos**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Problem description

Error when trying to create bucket without lock configuration on 3rd party provider:
```
"error ObjectLockConfigurationNotFound: Object Lock configuration does not exist for this bucket"
```
#### Cause: 
S3 provider returns `ObjectLockConfigurationNotFound` instead of `ObjectLockConfigurationNotFoundError`, so the strict check `ErrCodeEquals` in `bucket.go` does not work.

Also, the check if it's an aws region(partition) below returns true, because the region even though it's not aws has the same format eg: `eu-west-2` and the regex check in the terraform-aws-provider is satisfied.

Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3BucketObjectLockConfiguration*'  -timeout 180m
=== RUN   TestAccS3BucketObjectLockConfiguration_basic
=== PAUSE TestAccS3BucketObjectLockConfiguration_basic
=== RUN   TestAccS3BucketObjectLockConfiguration_disappears
=== PAUSE TestAccS3BucketObjectLockConfiguration_disappears
=== RUN   TestAccS3BucketObjectLockConfiguration_update
=== PAUSE TestAccS3BucketObjectLockConfiguration_update
=== RUN   TestAccS3BucketObjectLockConfiguration_migrate_noChange
=== PAUSE TestAccS3BucketObjectLockConfiguration_migrate_noChange
=== RUN   TestAccS3BucketObjectLockConfiguration_migrate_withChange
=== PAUSE TestAccS3BucketObjectLockConfiguration_migrate_withChange
=== CONT  TestAccS3BucketObjectLockConfiguration_basic
=== CONT  TestAccS3BucketObjectLockConfiguration_migrate_noChange
=== CONT  TestAccS3BucketObjectLockConfiguration_update
=== CONT  TestAccS3BucketObjectLockConfiguration_migrate_withChange
=== CONT  TestAccS3BucketObjectLockConfiguration_disappears
--- PASS: TestAccS3BucketObjectLockConfiguration_disappears (34.94s)
--- PASS: TestAccS3BucketObjectLockConfiguration_basic (38.44s)
--- PASS: TestAccS3BucketObjectLockConfiguration_migrate_withChange (57.96s)
--- PASS: TestAccS3BucketObjectLockConfiguration_migrate_noChange (59.55s)
--- PASS: TestAccS3BucketObjectLockConfiguration_update (63.63s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3 63.738s

:~/surse/terraform-provider-aws$ make testacc TESTS=TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled'  -timeout 180m
=== RUN   TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled
=== PAUSE TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled
=== CONT  TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled
--- PASS: TestAccS3Bucket_Basic_forceDestroyWithObjectLockEnabled (38.77s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3 38.849s

make testacc TESTS=TestAccS3Bucket_Basic_basic PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_Basic_basic'  -timeout 180m
=== RUN   TestAccS3Bucket_Basic_basic
=== PAUSE TestAccS3Bucket_Basic_basic
=== CONT  TestAccS3Bucket_Basic_basic
--- PASS: TestAccS3Bucket_Basic_basic (38.21s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3 38.292s

...
```

### CODE REVIEW

**Comment by cristiGuranIonos** [comment]
Added enhancement changelog to the PR. Thanks for taking a look!

**Comment by cristiGuranIonos** [comment]
@justinretzolk Would there be anything else to add to the PR?

**Comment by justinretzolk** [comment]
Hey @cristiGuranIonos 👋 Thank you for your contribution, and for checking in! On a quick glance, everything seems to be in order. At this point, we'll just need to wait for this PR to be [prioritized](https://hashicorp.github.io/terraform-provider-aws/prioritization/), at which point one of the maintainers will do a full review before merging.

**Comment by martinwieczorekionos** [comment]
:+1:

**Comment by cristiGuranIonos** [comment]
Any updates? Thanks!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccS3BucketObjectLockConfiguration_\|TestAccS3Bucket_Manage_objectLock' PKG=s3 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 3  -run=TestAccS3BucketObjectLockConfiguration_\|TestAccS3Bucket_Manage_objectLock -timeout 180m
=== RUN   TestAccS3BucketObjectLockConfiguration_basic
=== PAUSE TestAccS3BucketObjectLockConfiguration_basic
=== RUN   TestAccS3BucketObjectLockConfiguration_disappears
=== PAUSE TestAccS3BucketObjectLockConfiguration_disappears
=== RUN   TestAccS3BucketObjectLockConfiguration_update
=== PAUSE TestAccS3BucketObjectLockConfiguration_update
=== RUN   TestAccS3BucketObjectLockConfiguration_migrate_noChange
=== PAUSE TestAccS3BucketObjectLockConfiguration_migrate_noChange
=== RUN   TestAccS3BucketObjectLockConfiguration_migrate_withChange
=== PAUSE TestAccS3BucketObjectLockConfiguration_migrate_withChange
=== RUN   TestAccS3BucketObjectLockConfiguration_noRule
=== PAUSE TestAccS3BucketObjectLockConfiguration_noRule
=== RUN   TestAccS3Bucket_Manage_objectLock
=== PAUSE TestAccS3Bucket_Manage_objectLock
=== RUN   TestAccS3Bucket_Manage_objectLock_deprecatedEnabled
=== PAUSE TestAccS3Bucket_Manage_objectLock_deprecatedEnabled
=== RUN   TestAccS3Bucket_Manage_objectLock_migrate
=== PAUSE TestAccS3Bucket_Manage_objectLock_migrate
=== RUN   TestAccS3Bucket_Manage_objectLockWithVersioning
=== PAUSE TestAccS3Bucket_Manage_objectLockWithVersioning
=== RUN   TestAccS3Bucket_Manage_objectLockWithVersioning_deprecatedEnabled
=== PAUSE TestAccS3Bucket_Manage_objectLockWithVersioning_deprecatedEnabled
=== CONT  TestAccS3BucketObjectLockConfiguration_basic
=== CONT  TestAccS3Bucket_Manage_objectLock
=== CONT  TestAccS3BucketObjectLockConfiguration_update
--- PASS: TestAccS3BucketObjectLockConfiguration_basic (25.43s)
=== CONT  TestAccS3BucketObjectLockConfiguration_migrate_noChange
--- PASS: TestAccS3BucketObjectLockConfiguration_update (40.01s)
=== CONT  TestAccS3BucketObjectLockConfiguration_noRule
--- PASS: TestAccS3Bucket_Manage_objectLock (42.00s)
=== CONT  TestAccS3BucketObjectLockConfiguration_migrate_withChange
--- PASS: TestAccS3BucketObjectLockConfiguration_migrate_noChange (34.23s)
=== CONT  TestAccS3BucketObjectLockConfiguration_disappears
--- PASS: TestAccS3BucketObjectLockConfiguration_noRule (22.75s)
=== CONT  TestAccS3Bucket_Manage_objectLockWithVersioning
--- PASS: TestAccS3BucketObjectLockConfiguration_migrate_withChange (34.48s)
=== CONT  TestAccS3Bucket_Manage_objectLockWithVersioning_deprecatedEnabled
--- PASS: TestAccS3BucketObjectLockConfiguration_disappears (20.30s)
=== CONT  TestAccS3Bucket_Manage_objectLock_migrate
--- PASS: TestAccS3Bucket_Manage_objectLockWithVersioning (26.35s)
=== CONT  TestAccS3Bucket_Manage_objectLock_deprecatedEnabled
--- PASS: TestAccS3Bucket_Manage_objectLockWithVersioning_deprecatedEnabled (28.60s)
--- PASS: TestAccS3Bucket_Manage_objectLock_migrate (30.69s)
--- PASS: TestAccS3Bucket_Manage_objectLock_deprecatedEnabled (24.91s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	119.538s
```

**Comment by ewbankkit** [comment]
@cristiGuranIonos Thanks for the contribution :tada: :clap:.

**Pull request merged**
