### PR TITLE
r/aws_s3_bucket_object: Add source_hash attribute

### LINKED ISSUE #6668: r/aws_s3_bucket_object: Use own hash to track object changes (move away from the etag md5 value)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

While discussing an issue with the etag that s3 objects receive from AWS
(https://github.com/terraform-providers/terraform-provider-aws/issues/5033) and how that is not working when using encryption I came to wonder why the etag value of an S3 object is so naturally used to track local changes of a file compared to the object on S3.

Using the etag is unsafe in multiple cases - https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html !

My proposition is to move away from having the user provide the file md5 hash as an
etag value at all to recognize that the file has changed and instead to use a (md5 or rather sha256) hash of the local file and to store that in the terraform state after a successful upload? 

This way doing the checksum on the source and comparing it to the terraform state should be enough to recognize a changed file and the requirement to update the S3 object. 

Or am I missing anything / a certain use case of the etag to recognize file changes here?
Certainly the etag as a value provided by Amazon S3 allows to determine if the file has changed without terraform somehow, but that is not really an issue, as resources managed by terraform and their state must no be manipulated independently anyways. And certainly a refresh of the hash is always possible by simply downloading the file.

### New or Affected Resource(s)

* aws_s3_bucket_object

### Potential Terraform Configuration

Adding a hash / changing the way a changed file is recognized should be transparent to the existing code. The referenced issue about incomplete documentation of the etag when using service side encryption is still valid though.

### References

* https://docs.aws.amazon.com/AmazonS3/latest/API/RESTCommonResponseHeaders.html
* https://github.com/terraform-providers/terraform-provider-aws/issues/5033
* https://github.com/terraform-providers/terraform-provider-aws/pull/5938

### PR DESCRIPTION
**Pull request by theophilechevalier**
Add `source_hash` to `resource_aws_s3_bucket_object`.
Allows one to trigger resource update based on local changes instead of `etag`. Especially useful when `etag` cannot be used (e.g.  with `kms_key_id` or `server_side_encryption = "aws:kms"`).

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #6668
Relates #14900
Relates #9575
Relates #5033

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_s3_bucket_object: Add source_hash attribute
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3BucketObject'        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSS3BucketObject -timeout 120m
=== RUN   TestAccAWSS3BucketObject_noNameNoKey
=== PAUSE TestAccAWSS3BucketObject_noNameNoKey
=== RUN   TestAccAWSS3BucketObject_empty
=== PAUSE TestAccAWSS3BucketObject_empty
=== RUN   TestAccAWSS3BucketObject_source
=== PAUSE TestAccAWSS3BucketObject_source
=== RUN   TestAccAWSS3BucketObject_content
=== PAUSE TestAccAWSS3BucketObject_content
=== RUN   TestAccAWSS3BucketObject_etagEncryption
=== PAUSE TestAccAWSS3BucketObject_etagEncryption
=== RUN   TestAccAWSS3BucketObject_contentBase64
=== PAUSE TestAccAWSS3BucketObject_contentBase64
=== RUN   TestAccAWSS3BucketObject_SourceHashTrigger
=== PAUSE TestAccAWSS3BucketObject_SourceHashTrigger
=== RUN   TestAccAWSS3BucketObject_withContentCharacteristics
=== PAUSE TestAccAWSS3BucketObject_withContentCharacteristics
=== RUN   TestAccAWSS3BucketObject_NonVersioned
=== PAUSE TestAccAWSS3BucketObject_NonVersioned
=== RUN   TestAccAWSS3BucketObject_updates
=== PAUSE TestAccAWSS3BucketObject_updates
=== RUN   TestAccAWSS3BucketObject_updateSameFile
=== PAUSE TestAccAWSS3BucketObject_updateSameFile
=== RUN   TestAccAWSS3BucketObject_updatesWithVersioning
=== PAUSE TestAccAWSS3BucketObject_updatesWithVersioning
=== RUN   TestAccAWSS3BucketObject_kms
=== PAUSE TestAccAWSS3BucketObject_kms
=== RUN   TestAccAWSS3BucketObject_sse
=== PAUSE TestAccAWSS3BucketObject_sse
=== RUN   TestAccAWSS3BucketObject_acl
=== PAUSE TestAccAWSS3BucketObject_acl
=== RUN   TestAccAWSS3BucketObject_metadata
=== PAUSE TestAccAWSS3BucketObject_metadata
=== RUN   TestAccAWSS3BucketObject_storageClass
=== PAUSE TestAccAWSS3BucketObject_storageClass
=== RUN   TestAccAWSS3BucketObject_tags
=== PAUSE TestAccAWSS3BucketObject_tags
=== RUN   TestAccAWSS3BucketObject_tagsLeadingSlash
=== PAUSE TestAccAWSS3BucketObject_tagsLeadingSlash
=== RUN   TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithNone
=== PAUSE TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithNone
=== RUN   TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithOn
=== PAUSE TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithOn
=== RUN   TestAccAWSS3BucketObject_ObjectLockRetentionStartWithNone
=== PAUSE TestAccAWSS3BucketObject_ObjectLockRetentionStartWithNone
=== RUN   TestAccAWSS3BucketObject_ObjectLockRetentionStartWithSet
=== PAUSE TestAccAWSS3BucketObject_ObjectLockRetentionStartWithSet
=== CONT  TestAccAWSS3BucketObject_noNameNoKey
=== CONT  TestAccAWSS3BucketObject_kms
=== CONT  TestAccAWSS3BucketObject_ObjectLockRetentionStartWithSet
=== CONT  TestAccAWSS3BucketObject_metadata
=== CONT  TestAccAWSS3BucketObject_tags
=== CONT  TestAccAWSS3BucketObject_tagsLeadingSlash
=== CONT  TestAccAWSS3BucketObject_acl
=== CONT  TestAccAWSS3BucketObject_storageClass
=== CONT  TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithOn
=== CONT  TestAccAWSS3BucketObject_sse
=== CONT  TestAccAWSS3BucketObject_SourceHashTrigger
=== CONT  TestAccAWSS3BucketObject_ObjectLockRetentionStartWithNone
=== CONT  TestAccAWSS3BucketObject_content
=== CONT  TestAccAWSS3BucketObject_updatesWithVersioning
=== CONT  TestAccAWSS3BucketObject_contentBase64
=== CONT  TestAccAWSS3BucketObject_updateSameFile
=== CONT  TestAccAWSS3BucketObject_updates
=== CONT  TestAccAWSS3BucketObject_NonVersioned
=== CONT  TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithNone
=== CONT  TestAccAWSS3BucketObject_etagEncryption
--- PASS: TestAccAWSS3BucketObject_noNameNoKey (4.02s)
=== CONT  TestAccAWSS3BucketObject_withContentCharacteristics
--- SKIP: TestAccAWSS3BucketObject_NonVersioned (4.09s)
    provider_test.go:1192: skipping tests; TF_ACC_ASSUME_ROLE_ARN must be set
=== CONT  TestAccAWSS3BucketObject_source
--- PASS: TestAccAWSS3BucketObject_sse (58.27s)
=== CONT  TestAccAWSS3BucketObject_empty
--- PASS: TestAccAWSS3BucketObject_content (58.58s)
--- PASS: TestAccAWSS3BucketObject_contentBase64 (59.11s)
--- PASS: TestAccAWSS3BucketObject_source (55.06s)
--- PASS: TestAccAWSS3BucketObject_etagEncryption (59.21s)
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (56.28s)
--- PASS: TestAccAWSS3BucketObject_kms (85.09s)
--- PASS: TestAccAWSS3BucketObject_SourceHashTrigger (96.60s)
--- PASS: TestAccAWSS3BucketObject_updateSameFile (98.13s)
--- PASS: TestAccAWSS3BucketObject_updates (98.15s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithOn (99.04s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (99.69s)
--- PASS: TestAccAWSS3BucketObject_empty (55.46s)
--- PASS: TestAccAWSS3BucketObject_metadata (132.65s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockRetentionStartWithNone (137.95s)
--- PASS: TestAccAWSS3BucketObject_acl (140.12s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockLegalHoldStartWithNone (141.01s)
--- PASS: TestAccAWSS3BucketObject_ObjectLockRetentionStartWithSet (177.68s)
--- PASS: TestAccAWSS3BucketObject_tags (178.98s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingSlash (180.29s)
--- PASS: TestAccAWSS3BucketObject_storageClass (222.33s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       223.615s
```

### CODE REVIEW

**Comment by jacobisaliveandwell** [comment]
@jen20 could someone take a look at this?

**Comment by frittentheke** [comment]
@jacobisaliveandwell  awesome that you started implementing this!

I also opened an issue /suggestion about this a while ago: https://github.com/terraform-providers/terraform-provider-aws/issues/6668

**Comment by jacobisaliveandwell** [comment]
@frittentheke all credit goes to @theophilechevalier, I just came here to complain. I want this feature and don't see what the hold up is.

@YakDriver Any hope?

**Comment by theophilechevalier** [comment]
Seems that https://github.com/terraform-providers/terraform-provider-aws/issues/9575 is related

**Comment by wernerb** [comment]
This depends on #14900 to be there otherwise diffs will not ensure a new version_id is created.

**Comment by frittentheke** [comment]
> This depends on #14900 to be there otherwise diffs will not ensure a new version_id is created.

@wernerb That PR is now merged. Would be great to get the source hashing in as well.

**Comment by jacobisaliveandwell** [comment]
@YakDriver @bflad Any chance you could look at this now?

**Comment by emachnic** [comment]
Looks like there hasn't been any movement on this since November 23rd and it's definitely still an issue. What's the status? Is this going to be merged?

**Comment by frittentheke** [comment]
> Looks like there hasn't been any movement on this since November 23rd and it's definitely still an issue. What's the status? Is this going to be merged?

I second this question.

**Comment by frittentheke** [comment]
@YakDriver @bflad you did review a few S3 related PRs lately. Is there any chance you could look at this one?

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

Output from acceptance tests (`us-west-2`):
```
--- PASS: TestAccAWSS3BucketObject_noNameNoKey (6.04s)
=== CONT  TestAccAWSS3BucketObject_updateSameFile
--- PASS: TestAccAWSS3BucketObject_sse (38.77s)
=== CONT  TestAccAWSS3BucketObject_nonVersioned
    provider_test.go:2223: skipping test; environment variable TF_ACC_ASSUME_ROLE_ARN must be set. Usage: Amazon Resource Name (ARN) of existing IAM Role to assume for testing restricted permissions
--- SKIP: TestAccAWSS3BucketObject_nonVersioned (0.00s)
=== CONT  TestAccAWSS3BucketObject_withContentCharacteristics
--- PASS: TestAccAWSS3BucketObject_objectBucketKeyEnabled (44.98s)
=== CONT  TestAccAWSS3BucketObject_objectLockRetentionStartWithSet
--- PASS: TestAccAWSS3BucketObject_kms (48.06s)
=== CONT  TestAccAWSS3BucketObject_content
--- PASS: TestAccAWSS3BucketObject_bucketBucketKeyEnabled (49.93s)
=== CONT  TestAccAWSS3BucketObject_objectLockRetentionStartWithNone
--- PASS: TestAccAWSS3BucketObject_defaultBucketSSE (50.05s)
=== CONT  TestAccAWSS3BucketObject_contentBase64
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (38.33s)
=== CONT  TestAccAWSS3BucketObject_etagEncryption
--- PASS: TestAccAWSS3BucketObject_objectLockLegalHoldStartWithOn (84.52s)
--- PASS: TestAccAWSS3BucketObject_sourceHashTrigger (87.43s)
--- PASS: TestAccAWSS3BucketObject_updates (88.05s)
--- PASS: TestAccAWSS3BucketObject_updateSameFile (82.06s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (88.51s)
--- PASS: TestAccAWSS3BucketObject_content (40.56s)
--- PASS: TestAccAWSS3BucketObject_contentBase64 (38.80s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioningViaAccessPoint (89.26s)
--- PASS: TestAccAWSS3BucketObject_ignoreTags (89.54s)
--- PASS: TestAccAWSS3BucketObject_metadata (101.47s)
--- PASS: TestAccAWSS3BucketObject_etagEncryption (32.49s)
--- PASS: TestAccAWSS3BucketObject_objectLockLegalHoldStartWithNone (110.24s)
--- PASS: TestAccAWSS3BucketObject_source (28.23s)
--- PASS: TestAccAWSS3BucketObject_acl (113.16s)
--- PASS: TestAccAWSS3BucketObject_empty (27.02s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingMultipleSlashes (133.42s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingSingleSlash (133.54s)
--- PASS: TestAccAWSS3BucketObject_tagsMultipleSlashes (133.66s)
--- PASS: TestAccAWSS3BucketObject_tags (133.67s)
--- PASS: TestAccAWSS3BucketObject_objectLockRetentionStartWithNone (84.53s)
--- PASS: TestAccAWSS3BucketObject_objectLockRetentionStartWithSet (101.83s)
--- PASS: TestAccAWSS3BucketObject_storageClass (149.09s)
```

Output from acceptance tests (GovCloud):
```
=== CONT  TestAccAWSS3BucketObject_nonVersioned
    provider_test.go:2223: skipping test; environment variable TF_ACC_ASSUME_ROLE_ARN must be set. Usage: Amazon Resource Name (ARN) of existing IAM Role to assume for testing restricted permissions
--- SKIP: TestAccAWSS3BucketObject_nonVersioned (1.15s)
=== CONT  TestAccAWSS3BucketObject_sse
--- PASS: TestAccAWSS3BucketObject_noNameNoKey (5.10s)
=== CONT  TestAccAWSS3BucketObject_updatesWithVersioningViaAccessPoint
=== CONT  TestAccAWSS3BucketObject_source
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (41.39s)
--- PASS: TestAccAWSS3BucketObject_sse (41.13s)
=== CONT  TestAccAWSS3BucketObject_acl
=== CONT  TestAccAWSS3BucketObject_content
--- PASS: TestAccAWSS3BucketObject_contentBase64 (42.46s)
--- PASS: TestAccAWSS3BucketObject_etagEncryption (42.65s)
=== CONT  TestAccAWSS3BucketObject_empty
--- PASS: TestAccAWSS3BucketObject_objectBucketKeyEnabled (43.13s)
=== CONT  TestAccAWSS3BucketObject_updateSameFile
--- PASS: TestAccAWSS3BucketObject_bucketBucketKeyEnabled (48.25s)
=== CONT  TestAccAWSS3BucketObject_kms
--- PASS: TestAccAWSS3BucketObject_defaultBucketSSE (48.36s)
=== CONT  TestAccAWSS3BucketObject_updates
--- PASS: TestAccAWSS3BucketObject_objectLockLegalHoldStartWithOn (76.94s)
=== CONT  TestAccAWSS3BucketObject_updatesWithVersioning
--- PASS: TestAccAWSS3BucketObject_sourceHashTrigger (83.29s)
--- PASS: TestAccAWSS3BucketObject_source (45.08s)
--- PASS: TestAccAWSS3BucketObject_content (45.40s)
--- PASS: TestAccAWSS3BucketObject_empty (45.41s)
--- PASS: TestAccAWSS3BucketObject_kms (40.88s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioningViaAccessPoint (84.45s)
--- PASS: TestAccAWSS3BucketObject_ignoreTags (89.87s)
--- PASS: TestAccAWSS3BucketObject_metadata (116.27s)
--- PASS: TestAccAWSS3BucketObject_objectLockLegalHoldStartWithNone (117.07s)
--- PASS: TestAccAWSS3BucketObject_objectLockRetentionStartWithNone (117.26s)
--- PASS: TestAccAWSS3BucketObject_updateSameFile (74.28s)
--- PASS: TestAccAWSS3BucketObject_updates (71.20s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingSingleSlash (135.52s)
--- PASS: TestAccAWSS3BucketObject_objectLockRetentionStartWithSet (142.54s)
--- PASS: TestAccAWSS3BucketObject_tags (143.42s)
--- PASS: TestAccAWSS3BucketObject_tagsMultipleSlashes (143.50s)
--- PASS: TestAccAWSS3BucketObject_tagsLeadingMultipleSlashes (143.60s)
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (67.37s)
--- PASS: TestAccAWSS3BucketObject_acl (102.53s)
--- PASS: TestAccAWSS3BucketObject_storageClass (165.06s)
```

**Pull request merged**
