### PR TITLE
r/aws_rds_cluster_role_association - New resource

### LINKED ISSUE #9552: Support for RDS AddRoleToDBCluster with FeatureName
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Resource object exists [aws_rds_cluster](https://www.terraform.io/docs/providers/aws/r/rds_cluster.html) which supports optional IAM Role attachments to the cluster via the argument iam_roles. 

The implementation leverages [AddRoleToDBCLuster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_AddRoleToDBCluster.html) to accomplish this task. 

_FeatureName_ is not listed as a required argument. For Amazon Aurora PostgreSQL attaching an IAM Role without a feature name results in `The feature-name parameter must be provided with the current operation for the Aurora (PostgreSQL) engine.`

Currently there is not a mechanism for attaching feature-name on the existing _aws_rds_cluster_ resource. There is an [aws_db_instance_role_association](https://www.terraform.io/docs/providers/aws/r/db_instance_role_association.html) resource which accepts feature_name for attaching a role to an instance.

This request is to add a resource for associating a role to an RDS cluster.

### New or Affected Resource(s)

* aws_rds_cluster_role_association

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_role_association" "example" {
  cluster_identifier = "${aws_rds_cluster.example.id}"
  feature_name           = "s3Import"
  role_arn               = "${aws_iam_role.example.arn}"
}
```

### References

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_AddRoleToDBCluster.html

https://aws.amazon.com/about-aws/whats-new/2019/06/amazon-aurora-with-postgresql-compatibility-supports-data-import-from-amazon-s3/

https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DBEngineVersion.html
SupportedFeatureNames:
- s3Import

https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraPostgreSQL.Migrating.html#USER_PostgreSQL.S3Import

### LINKED ISSUE #13641: Support Attaching and Detaching IAM Roles to RDS Clusters
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since https://github.com/terraform-providers/terraform-provider-aws/issues/8038 Terraform supports attaching IAM roles to RDS instances. However, for an S3 integration with Aurora clusters, the roles should be attached to the cluster and rather than an individual instance.

### New or Affected Resource(s)
* aws_rds_cluster
* aws_db_instance_role_association (existing resource with reciprocal function for DB instances)
* aws_rds_cluster_role_association (new)

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster_role_association" "example" {
  cluster_identifier = "${aws_rds_cluster.example.id}"
  feature_name = "s3Import"
  role_arn = "${aws_iam_role.example.arn}"
}
```

Note: AFAIK, the attached role (`${aws_iam_role.example.arn}`) should also be added to the `iam_roles` list for the `aws_rds_cluster`.

### References

* https://github.com/terraform-providers/terraform-provider-aws/issues/8038
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/AuroraMySQL.Integrating.LoadFromS3.html

### PR DESCRIPTION
**Pull request by thehunt33r**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9552
Closes #13641

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* **New Resource**: `aws_db_cluster_role_association` (#12370)
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSDbClusterRoleAssociation_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSDbClusterRoleAssociation_basic -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSDbClusterRoleAssociation_basic
=== PAUSE TestAccAWSDbClusterRoleAssociation_basic
=== CONT  TestAccAWSDbClusterRoleAssociation_basic
--- FAIL: TestAccAWSDbClusterRoleAssociation_basic (145.77s)
    testing.go:654: Step 0 error: After applying this step and refreshing, the plan was not empty:
        
        DIFF:
        
        UPDATE: aws_rds_cluster.test
          arn:                                 "arn:aws:rds:us-west-2:335060465476:cluster:tf-acc-test-5141842218216975802" => "arn:aws:rds:us-west-2:335060465476:cluster:tf-acc-test-5141842218216975802"
          availability_zones.#:                "3" => "3"
          availability_zones.0:                "us-west-2a" => "us-west-2a"
          availability_zones.1:                "us-west-2b" => "us-west-2b"
          availability_zones.2:                "us-west-2c" => "us-west-2c"
          backtrack_window:                    "0" => "0"
          backup_retention_period:             "5" => "5"
          cluster_identifier:                  "tf-acc-test-5141842218216975802" => "tf-acc-test-5141842218216975802"
          cluster_members.#:                   "0" => "0"
          cluster_resource_id:                 "cluster-YPHXLKR7QXJN4VTFQQUM6HVETQ" => "cluster-YPHXLKR7QXJN4VTFQQUM6HVETQ"
          copy_tags_to_snapshot:               "false" => "false"
          database_name:                       "mydb" => "mydb"
          db_cluster_parameter_group_name:     "default.aurora-postgresql10" => "default.aurora-postgresql10"
          db_subnet_group_name:                "default" => "default"
          deletion_protection:                 "false" => "false"
          enable_http_endpoint:                "false" => "false"
          enabled_cloudwatch_logs_exports.#:   "0" => "0"
          endpoint:                            "tf-acc-test-5141842218216975802.cluster-cskifp8xdxvd.us-west-2.rds.amazonaws.com" => "tf-acc-test-5141842218216975802.cluster-cskifp8xdxvd.us-west-2.rds.amazonaws.com"
          engine:                              "aurora-postgresql" => "aurora-postgresql"
          engine_mode:                         "provisioned" => "provisioned"
          engine_version:                      "10.7" => "10.7"
          global_cluster_identifier:           "" => ""
          hosted_zone_id:                      "Z1PVIF0B656C1W" => "Z1PVIF0B656C1W"
          iam_database_authentication_enabled: "false" => "false"
          iam_roles.#:                         "1" => "0"
          iam_roles.0:                         "arn:aws:iam::335060465476:role/tf-acc-test-5141842218216975802" => ""
          id:                                  "tf-acc-test-5141842218216975802" => "tf-acc-test-5141842218216975802"
          kms_key_id:                          "" => ""
          master_password:                     "foobarfoobarfoobar" => "foobarfoobarfoobar"
          master_username:                     "foo" => "foo"
          port:                                "5432" => "5432"
          preferred_backup_window:             "07:00-09:00" => "07:00-09:00"
          preferred_maintenance_window:        "fri:13:12-fri:13:42" => "fri:13:12-fri:13:42"
          reader_endpoint:                     "tf-acc-test-5141842218216975802.cluster-ro-cskifp8xdxvd.us-west-2.rds.amazonaws.com" => "tf-acc-test-5141842218216975802.cluster-ro-cskifp8xdxvd.us-west-2.rds.amazonaws.com"
          replication_source_identifier:       "" => ""
          s3_import.#:                         "0" => "0"
          scaling_configuration.#:             "0" => "0"
          skip_final_snapshot:                 "true" => "true"
          storage_encrypted:                   "false" => "false"
          vpc_security_group_ids.#:            "1" => "1"
          vpc_security_group_ids.0:            "sg-01cc8f45" => "sg-01cc8f45"
        
        
        
        STATE:
        
        data.aws_iam_policy_document.rds_assume_role_policy:
          ID = 1077238154
          provider = provider.aws
          json = {
          "Version": "2012-10-17",
          "Statement": [
            {
              "Sid": "",
              "Effect": "Allow",
              "Action": "sts:AssumeRole",
              "Principal": {
                "Service": "rds.amazonaws.com"
              }
            }
          ]
        }
          statement.# = 1
          statement.0.actions.# = 1
          statement.0.actions.0 = sts:AssumeRole
          statement.0.effect = Allow
          statement.0.principals.# = 1
          statement.0.principals.0.identifiers.# = 1
          statement.0.principals.0.identifiers.0 = rds.amazonaws.com
          statement.0.principals.0.type = Service
          statement.0.sid = 
          version = 2012-10-17
        aws_db_cluster_role_association.test:
          ID = tf-acc-test-5141842218216975802,arn:aws:iam::335060465476:role/tf-acc-test-5141842218216975802
          provider = provider.aws
          db_cluster_identifier = tf-acc-test-5141842218216975802
          feature_name = s3Import
          role_arn = arn:aws:iam::335060465476:role/tf-acc-test-5141842218216975802
        
          Dependencies:
            aws_iam_role.test
            aws_rds_cluster.test
        aws_iam_role.test:
          ID = tf-acc-test-5141842218216975802
          provider = provider.aws
          arn = arn:aws:iam::335060465476:role/tf-acc-test-5141842218216975802
          assume_role_policy = {"Version":"2012-10-17","Statement":[{"Sid":"","Effect":"Allow","Principal":{"Service":"rds.amazonaws.com"},"Action":"sts:AssumeRole"}]}
          create_date = 2020-03-12T15:29:02Z
          description = 
          force_detach_policies = false
          max_session_duration = 3600
          name = tf-acc-test-5141842218216975802
          path = /
          unique_id = AROAU4AZI65CJXCNSES36
        
          Dependencies:
            data.aws_iam_policy_document.rds_assume_role_policy
        aws_rds_cluster.test:
          ID = tf-acc-test-5141842218216975802
          provider = provider.aws
          arn = arn:aws:rds:us-west-2:335060465476:cluster:tf-acc-test-5141842218216975802
          availability_zones.# = 3
          availability_zones.0 = us-west-2a
          availability_zones.1 = us-west-2b
          availability_zones.2 = us-west-2c
          backtrack_window = 0
          backup_retention_period = 5
          cluster_identifier = tf-acc-test-5141842218216975802
          cluster_resource_id = cluster-YPHXLKR7QXJN4VTFQQUM6HVETQ
          copy_tags_to_snapshot = false
          database_name = mydb
          db_cluster_parameter_group_name = default.aurora-postgresql10
          db_subnet_group_name = default
          deletion_protection = false
          enable_http_endpoint = false
          endpoint = tf-acc-test-5141842218216975802.cluster-cskifp8xdxvd.us-west-2.rds.amazonaws.com
          engine = aurora-postgresql
          engine_mode = provisioned
          engine_version = 10.7
          global_cluster_identifier = 
          hosted_zone_id = Z1PVIF0B656C1W
          iam_database_authentication_enabled = false
          iam_roles.# = 1
          iam_roles.0 = arn:aws:iam::335060465476:role/tf-acc-test-5141842218216975802
          kms_key_id = 
          master_password = foobarfoobarfoobar
          master_username = foo
          port = 5432
          preferred_backup_window = 07:00-09:00
          preferred_maintenance_window = fri:13:12-fri:13:42
          reader_endpoint = tf-acc-test-5141842218216975802.cluster-ro-cskifp8xdxvd.us-west-2.rds.amazonaws.com
          replication_source_identifier = 
          skip_final_snapshot = true
          storage_encrypted = false
          vpc_security_group_ids.# = 1
          vpc_security_group_ids.0 = sg-01cc8f45
    testing.go:715: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: Check failed: DBClusterNotFoundFault: DBCluster tf-acc-test-5141842218216975802 not found.
                status code: 404, request id: b8033c62-46ec-4c15-972d-d779c0968fc1
        
        State: <no state>
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       147.225s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.079s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.241s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/naming       0.551s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency    0.213s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token    0.293s [no tests to run]
?       github.com/terraform-providers/terraform-provider-aws/awsproviderlint   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes    0.300s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001   0.780s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001    0.125s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr 0.129s [no tests to run]
FAIL
make: *** [testacc] Error 1
```

There seems to a problem with the `iam_roles` argument in `aws_rds_cluster`, which can also be used to associate a role but only with Aurora MySQL (and doesn't allow passing a feature with the role) and I'd love to have feedback / advice on this. 

I have two ideas on how to fix this, but both would be breaking changes:

* Abandon this resource and modify `iam_roles` structure in `aws_rds_cluster` to be `list(object({role_arn=string,feature=string}))` which would allow for it to work on both MySQL and PostgreSQL.
  * Pro: No need for an additional resource
* Keep this resource and delete `iam_roles` argument from `aws_rds_cluster`
  * Pro: Making the implementation similar to what is done for `aws_db_instance` and `aws_db_instance_role_association` 

Additionally, I am not sure on the naming. Of course, Aurora clusters use the `aws_rds_*` namespace for most of their resources, but there are some using `aws_db_cluster_*`. Happy either way.

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by shiron-babi** [comment]
@breathingdust - do you think you will be able to merge it somewhen soon? we really need this feature

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSRDSClusterRoleAssociation_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSRDSClusterRoleAssociation_ -timeout 180m
=== RUN   TestAccAWSRDSClusterRoleAssociation_basic
=== PAUSE TestAccAWSRDSClusterRoleAssociation_basic
=== RUN   TestAccAWSRDSClusterRoleAssociation_disappears
=== PAUSE TestAccAWSRDSClusterRoleAssociation_disappears
=== RUN   TestAccAWSRDSClusterRoleAssociation_disappears_cluster
=== PAUSE TestAccAWSRDSClusterRoleAssociation_disappears_cluster
=== RUN   TestAccAWSRDSClusterRoleAssociation_disappears_role
=== PAUSE TestAccAWSRDSClusterRoleAssociation_disappears_role
=== CONT  TestAccAWSRDSClusterRoleAssociation_basic
=== CONT  TestAccAWSRDSClusterRoleAssociation_disappears_role
=== CONT  TestAccAWSRDSClusterRoleAssociation_disappears
=== CONT  TestAccAWSRDSClusterRoleAssociation_disappears_cluster
--- PASS: TestAccAWSRDSClusterRoleAssociation_disappears_cluster (131.22s)
--- PASS: TestAccAWSRDSClusterRoleAssociation_disappears (163.37s)
--- PASS: TestAccAWSRDSClusterRoleAssociation_disappears_role (163.77s)
--- PASS: TestAccAWSRDSClusterRoleAssociation_basic (165.71s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	168.798s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSRDSClusterRoleAssociation_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSRDSClusterRoleAssociation_ -timeout 180m
=== RUN   TestAccAWSRDSClusterRoleAssociation_basic
=== PAUSE TestAccAWSRDSClusterRoleAssociation_basic
=== RUN   TestAccAWSRDSClusterRoleAssociation_disappears
=== PAUSE TestAccAWSRDSClusterRoleAssociation_disappears
=== RUN   TestAccAWSRDSClusterRoleAssociation_disappears_cluster
=== PAUSE TestAccAWSRDSClusterRoleAssociation_disappears_cluster
=== RUN   TestAccAWSRDSClusterRoleAssociation_disappears_role
=== PAUSE TestAccAWSRDSClusterRoleAssociation_disappears_role
=== CONT  TestAccAWSRDSClusterRoleAssociation_basic
=== CONT  TestAccAWSRDSClusterRoleAssociation_disappears_role
=== CONT  TestAccAWSRDSClusterRoleAssociation_disappears
=== CONT  TestAccAWSRDSClusterRoleAssociation_disappears_cluster
--- PASS: TestAccAWSRDSClusterRoleAssociation_disappears (124.68s)
--- PASS: TestAccAWSRDSClusterRoleAssociation_disappears_cluster (135.43s)
--- PASS: TestAccAWSRDSClusterRoleAssociation_disappears_role (146.71s)
--- PASS: TestAccAWSRDSClusterRoleAssociation_basic (147.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	150.454s
```

**Comment by ewbankkit** [comment]
@thehunt33r Thanks for the contribution :tada: :clap:.
 To get this merged more quickly, I went ahead and renamed the resource to `aws_rds_cluster_role_association` to match our [new resource naming guidelines](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/contribution-checklists.md#new-resource) and added a couple more acceptance tests.

**Comment by thehunt33r** [comment]
Thank you @ewbankkit for all the work you've poured in this PR! I had indeed hesitated on the naming of the resource, and I also agree with `aws_rds_cluster_role_association` :+1:

Looking forward to getting this PR merged and to start using it!

**Comment by shiron-babi** [comment]
@ewbankkit & @thehunt33r - Thanks for the hard work, this will be very useful for us!

**Pull request merged**
