### PR TITLE
F/aws fsx ontap file system

### LINKED ISSUE #24231: Resource aws_fsx_ontap_file_system allow deployment type Single AZ
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As per the update to FSx for NetApp ONTAP, the file system now supports Single AZ deployment mode.

Currently, the option for selecting the deployment type in the provider is limited to MULTI_AZ_1.

### New or Affected Resource(s)

* aws_fsx_ontap_file_system

### Potential Terraform Configuration

```hcl
resource "aws_fsx_ontap_file_system" "fsx_ontap_fs" {
  storage_capacity    = 1024
  subnet_ids          = [aws_subnet.fsxsubnet01.id]
  deployment_type     = "SINGLE_AZ_1"
  throughput_capacity = 128
  preferred_subnet_id = aws_subnet.fsxsubnet01.id
}
```

### References
[Release News](https://aws.amazon.com/about-aws/whats-new/2022/04/amazon-fsx-netapp-ontap-single-availability-zone-deployment/)
[Documentation](https://docs.aws.amazon.com/fsx/latest/ONTAPGuide/high-availability-AZ.html)

### PR DESCRIPTION
**Pull request by nikhil-goenka**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #24231

Output from acceptance testing:

```
$ make testacc TESTS=TestAccFSxOntapFileSystem_fsxSingleAz PKG=fsx 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run='TestAccFSxOntapFileSystem_fsxSingleAz'  -timeout 180m
=== RUN   TestAccFSxOntapFileSystem_fsxSingleAz
=== PAUSE TestAccFSxOntapFileSystem_fsxSingleAz
=== CONT  TestAccFSxOntapFileSystem_fsxSingleAz
--- PASS: TestAccFSxOntapFileSystem_fsxSingleAz (2119.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	2124.575s

...
```

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Review by DrFaust92 — APPROVED** [review]
@nikhil-goenka please add changelog entry, otherwise LGTM

**Comment by nikhil-goenka** [comment]
> @nikhil-goenka please add changelog entry, otherwise LGTM

updated changelog

**Review by DrFaust92 — APPROVED** [review]

**Comment by ewbankkit** [comment]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@nikhil-goenka Thanks for the contribution :tada: :clap:.

**Pull request merged**
