### PR TITLE
feat: add support for single scram secret association

### LINKED ISSUE #16791: aws_msk_scram_secret_association overrides/removes existing secret associations
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
> terraform -v 

Terraform v0.13.5 
+ provider registry.terraform.io/hashicorp/aws v3.21.0 
```

### Affected Resource(s)

* aws_msk_scram_secret_association

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_msk_scram_secret_association" "attach_to_cluster" {
  cluster_arn     = 'my-cluster'
  secret_arn_list = [arn:aws:secretsmanager:us-west-1:XXX:secret:AmazonMSK_Tf-Module_Test_20201216135753890700000001-ybcWM3]
}
```

### Expected Behavior

Existing resources that are not defined in this terraform stack (or in another stack) should not be removed.
This is needed to avoid a centralized management of secrets associated to a MSK cluster.

```
  # aws_msk_scram_secret_association.attach_to_cluster will be updated in-place
  ~ resource "aws_msk_scram_secret_association" "attach_to_cluster" {
        cluster_arn     = "arn:aws:kafka:us-west-1:XXX:cluster/my-custer/9999-9999-9999-9"
        id              = "arn:aws:kafka:us-west-1:XXX:cluster/my-custer/9999-9999-9999-9"
      ~ secret_arn_list = [
           + "arn:aws:secretsmanager:us-west-1:XXX:secret:AmazonMSK_Tf-Module_Test_20201216135753890700000001-ybcWM3",
        ]
    }
```

### Actual Behavior

Existing secrets are removed from the MSK Cluster in the plan:

```
  # aws_msk_scram_secret_association.attach_to_cluster will be updated in-place
  ~ resource "aws_msk_scram_secret_association" "attach_to_cluster" {
        cluster_arn     = "arn:aws:kafka:us-west-1:XXX:cluster/my-custer/9999-9999-9999-9"
        id              = "arn:aws:kafka:us-west-1:XXX:cluster/my-custer/9999-9999-9999-9"
      ~ secret_arn_list = [
          - "arn:aws:secretsmanager:us-west-1:XXX:secret:AmazonMSK_ST_Akhq_20201013111302148600000001-ATFaph",
          - "arn:aws:secretsmanager:us-west-1:XXX:secret:AmazonMSK_ST_Schema-Registry_20201013111302148900000002-dTOIjg",
            "arn:aws:secretsmanager:us-west-1:XXX:secret:AmazonMSK_Tf-Module_Test_20201216135753890700000001-ybcWM3",
        ]
    }
```
Looks like the provider is trying to remove all the secrets that are not defined in this `aws_msk_scram_secret_association`. 

### Steps to Reproduce

1. Create a MSK cluster with some secrets associated on it in a first terraform stack
2. Create another terraform stack that associate new secrets to new previously created MSK cluster
3. `terraform apply`
4. `terraform plan`

### References

Pull request:

* #15302

### PR DESCRIPTION
**Pull request by dstrates**
### Description

The current [`aws_msk_scram_secret_association`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_scram_secret_association) resource is not flexible and tightly couples the management of secret associations to MSK clusters. This causes issues when attempting to manage secret associations separately from the cluster creation, as it removes all existing secret associations created out of band.

The proposed change implements @bflad's suggestions in  https://github.com/hashicorp/terraform-provider-aws/pull/16832#pullrequestreview-566606854, adding an optional `secret_arn` argument to the `aws_msk_scram_secret_association` resource.

### Relations

Closes #16791.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/40217.
Relates #16832.

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by SuSaiGit** [comment]
When will this be merged?

**Comment by sbrnunes** [comment]
Hi everyone.

This is causing serious problems in our case, and considering the upvotes in this issue and in https://github.com/hashicorp/terraform-provider-aws/issues/16791, it appears to be affecting a lot of people.

If this PR fixes it, when can we see it reviewed, merged and released?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccKafkaSCRAMSecretAssociation_\|TestAccKafkaSingleSCRAMSecretAssociation_' PKG=kafka ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/kafka/... -v -count 1 -parallel 3  -run=TestAccKafkaSCRAMSecretAssociation_\|TestAccKafkaSingleSCRAMSecretAssociation_ -timeout 720m
2024/12/11 06:00:54 Initializing Terraform AWS Provider...
=== RUN   TestAccKafkaSCRAMSecretAssociation_basic
=== PAUSE TestAccKafkaSCRAMSecretAssociation_basic
=== RUN   TestAccKafkaSCRAMSecretAssociation_update
=== PAUSE TestAccKafkaSCRAMSecretAssociation_update
=== RUN   TestAccKafkaSCRAMSecretAssociation_disappears
=== PAUSE TestAccKafkaSCRAMSecretAssociation_disappears
=== RUN   TestAccKafkaSCRAMSecretAssociation_Disappears_cluster
=== PAUSE TestAccKafkaSCRAMSecretAssociation_Disappears_cluster
=== RUN   TestAccKafkaSingleSCRAMSecretAssociation_basic
=== PAUSE TestAccKafkaSingleSCRAMSecretAssociation_basic
=== RUN   TestAccKafkaSingleSCRAMSecretAssociation_multiple
=== PAUSE TestAccKafkaSingleSCRAMSecretAssociation_multiple
=== RUN   TestAccKafkaSingleSCRAMSecretAssociation_disappears
=== PAUSE TestAccKafkaSingleSCRAMSecretAssociation_disappears
=== CONT  TestAccKafkaSCRAMSecretAssociation_basic
=== CONT  TestAccKafkaSingleSCRAMSecretAssociation_basic
=== CONT  TestAccKafkaSingleSCRAMSecretAssociation_disappears
--- PASS: TestAccKafkaSCRAMSecretAssociation_basic (676.66s)
=== CONT  TestAccKafkaSCRAMSecretAssociation_disappears
--- PASS: TestAccKafkaSingleSCRAMSecretAssociation_basic (678.48s)
=== CONT  TestAccKafkaSCRAMSecretAssociation_Disappears_cluster
=== CONT  TestAccKafkaSCRAMSecretAssociation_update
--- PASS: TestAccKafkaSingleSCRAMSecretAssociation_disappears (685.36s)
--- PASS: TestAccKafkaSCRAMSecretAssociation_disappears (291.45s)
=== CONT  TestAccKafkaSingleSCRAMSecretAssociation_multiple
--- PASS: TestAccKafkaSCRAMSecretAssociation_Disappears_cluster (300.89s)
--- PASS: TestAccKafkaSCRAMSecretAssociation_update (325.08s)
--- PASS: TestAccKafkaSingleSCRAMSecretAssociation_multiple (325.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	1298.437s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

I think the resource name is reasonable given the misnaming of the original, which should have been an "exclusive" variant had it not predated us publishing a formal definition for those resource types.

**Comment by ewbankkit** [comment]
@dstrates Thanks for the contribution :tada: :clap:.
We decided to implement this single association functionality as a new resource, `aws_msk_single_scram_secret_association`.

**Pull request merged**
