### PR TITLE
Add timeout to aws_redshiftserverless_workgroup

### LINKED ISSUE #31048: [Bug]: aws_redshiftserverless_workgroup times out creating nearly 100% of the time
### Terraform Core Version

1.4.5

### AWS Provider Version

4.64.0

### Affected Resource(s)

aws_redshiftserverless_workgroup

### Expected Behavior

Resource creates successfully

### Actual Behavior

The resource will nearly always timeout during creation while waiting for the resource to become `Available`. This appears to happen because the resource is created then immediately modified, and the timeout is not long enough to account for the modification to complete.

`waiting for Redshift Serverless Workgroup (redshift-serverless-88-workspace) to be created: timeout while waiting for state to become 'AVAILABLE' (last state: 'MODIFYING', timeout: 10m0s)`

### Relevant Error/Panic Output Snippet

```shell
╷
│ Error: waiting for Redshift Serverless Workgroup (redshift-serverless-88-workspace) to be created: timeout while waiting for state to become 'AVAILABLE' (last state: 'MODIFYING', timeout: 10m0s)
│ 
│   with aws_redshiftserverless_workgroup.redshift_db_workgroup,
│   on redshift.tf line 22, in resource "aws_redshiftserverless_workgroup" "redshift_db_workgroup":
│   22: resource "aws_redshiftserverless_workgroup" "redshift_db_workgroup" {
│
```

### Terraform Configuration Files

```hcl


resource "aws_redshiftserverless_workgroup" "redshift_db_workgroup" {
  namespace_name = aws_redshiftserverless_namespace.redshift_db_namespace.id

  workgroup_name = "redshift-serverless-${var.usage}-workspace"
  base_capacity  = var.base_redshift_capacity

  // This is intention for business reasons, and is protected by the security group.
  publicly_accessible = true
  security_group_ids  = [aws_security_group.redshift_sg.id]
  subnet_ids          = data.aws_subnets.redshift_subnets.ids
}

````

There are obviously some resources that are populated by data sources or variables, but it's a relatively minimal configuration.

### Steps to Reproduce

Simply apply the configuration and wait 10 minutes.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

The resource does reach `Available` eventually, it just takes longer than the timeout provides. The resource will occasionally succeed as a result, since the resource will occasionally reach `Available` quickly enough.

Simply allowing for configuring the timeout will resolve this bug, though it's likely increasing the default timeout would also be good to cover a majority of user's cases.

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by PatrickRice-KSC**
### Description
This pull request adds support to define the `timeouts` block within the `aws_redshiftserverless_workgroup` resource. It also updates the default timeout from 10 Minutes to 20 Minutes to align to [default terraform resource timeout behaviors](https://developer.hashicorp.com/terraform/plugin/sdkv2/resources/retries-and-customizable-timeouts#default-timeouts-and-deadline-exceeded-errors).

### Relations

Closes #31048

### Output from Acceptance Testing

Since the timeout doesn't modify the logic of the resource inherently, a `timeouts` block was added to the basic test to ensure that removal of the timeout logic would break the `basic` test.

```
$ make testacc TESTS=TestAccRedshiftServerlessWorkgroup_basic PKG=redshiftserverless
```

### CODE REVIEW

**Comment by PatrickRice-KSC** [comment]
Evidence of passing test (though of course it'll run in the CI/CD too 😄 ): 

image

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by PatrickRice-KSC** [comment]
Fixed 1 issue I found doing a self-review where the `wait` wasn't being passed properly; just FYI.

Also, rebasing branch just to stay up-to-date :)

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRedshiftServerlessWorkgroup_basic$$' PKG=redshiftserverless
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/redshiftserverless/... -v -count 1 -parallel 20  -run=TestAccRedshiftServerlessWorkgroup_basic$ -timeout 180m
=== RUN   TestAccRedshiftServerlessWorkgroup_basic
=== PAUSE TestAccRedshiftServerlessWorkgroup_basic
=== CONT  TestAccRedshiftServerlessWorkgroup_basic
--- PASS: TestAccRedshiftServerlessWorkgroup_basic (529.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless	534.770s
```

**Comment by ewbankkit** [comment]
@PatrickRice-KSC Thanks for the contribution :tada: :clap:.

**Pull request merged**
