### PR TITLE
`s3`: reference storage classes from SDK and AWS docs

### LINKED ISSUE #22098: Please add support for S3 Glacier Instant Retrieval storage class
### Description

Announcement: https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-s3-glacier-instant-retrieval-storage-class/

### New or Affected Resource(s)

`aws_s3_bucket` and `aws_s3_bucket_object`

### PR DESCRIPTION
**Pull request by bendrucker**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This PR moves hardcoded names of S3 storage classes to:

* Code: Enums provided by the SDK
* Docs: Links to the appropriate AWS docs

There are subtle differences between the available storage classes in different situations so each enum/link is specific to the resource where it's used. This makes it easier for the provider to fully support new storage classes, including the new `GLACIER_IR`.

Closes #22098

Output from acceptance testing:

```
$ make testacc TESTS=TestAccS3Bucket_Manage_lifecycle PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run='TestAccS3Bucket_Manage_lifecycle' -timeout 180m
=== RUN   TestAccS3Bucket_Manage_lifecycleBasic
=== PAUSE TestAccS3Bucket_Manage_lifecycleBasic
=== RUN   TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly
=== PAUSE TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly
=== RUN   TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock
=== PAUSE TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock
=== RUN   TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration
=== PAUSE TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration
=== CONT  TestAccS3Bucket_Manage_lifecycleBasic
=== CONT  TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock
=== CONT  TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration
=== CONT  TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock (292.05s)
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration (378.98s)
--- PASS: TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly (696.80s)
--- PASS: TestAccS3Bucket_Manage_lifecycleBasic (1056.75s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	1059.022s
```

### CODE REVIEW

**Comment by bendrucker** [comment]
I did a search through `docs/` for the string `STANDARD_IA` to make sure I found all the cases where storage classes are listed. The only remaining match is in a code example. This is also what led me to find/update the docs for the Storage Gateway service.

**Comment by bendrucker** [comment]
Passing acceptance test output added. Took >15 mins for a small number of cases so I ended up running tests only where there was actually coverage for customizing the storage class. The `object_copy` resource doesn't test for setting the storage class. If you'd like me to add coverage I can.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccS3ObjectCopy_\|TestAccS3Bucket_Manage_lifecycle' PKG=s3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run=TestAccS3ObjectCopy_\|TestAccS3Bucket_Manage_lifecycle -timeout 180m
=== RUN   TestAccS3Bucket_Manage_lifecycleBasic
=== PAUSE TestAccS3Bucket_Manage_lifecycleBasic
=== RUN   TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly
=== PAUSE TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly
=== RUN   TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock
=== PAUSE TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock
=== RUN   TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration
=== PAUSE TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration
=== RUN   TestAccS3ObjectCopy_basic
=== PAUSE TestAccS3ObjectCopy_basic
=== RUN   TestAccS3ObjectCopy_BucketKeyEnabled_bucket
=== PAUSE TestAccS3ObjectCopy_BucketKeyEnabled_bucket
=== RUN   TestAccS3ObjectCopy_BucketKeyEnabled_object
=== PAUSE TestAccS3ObjectCopy_BucketKeyEnabled_object
=== CONT  TestAccS3Bucket_Manage_lifecycleBasic
=== CONT  TestAccS3ObjectCopy_basic
=== CONT  TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration
=== CONT  TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly
=== CONT  TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock
=== CONT  TestAccS3ObjectCopy_BucketKeyEnabled_object
=== CONT  TestAccS3ObjectCopy_BucketKeyEnabled_bucket
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleExpirationEmptyBlock (27.21s)
--- PASS: TestAccS3ObjectCopy_basic (30.80s)
--- PASS: TestAccS3ObjectCopy_BucketKeyEnabled_object (30.86s)
--- PASS: TestAccS3ObjectCopy_BucketKeyEnabled_bucket (33.01s)
--- PASS: TestAccS3Bucket_Manage_lifecycleRuleAbortIncompleteMultipartUploadDaysNoExpiration (35.17s)
--- PASS: TestAccS3Bucket_Manage_lifecycleExpireMarkerOnly (60.73s)
--- PASS: TestAccS3Bucket_Manage_lifecycleBasic (87.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	91.138s
```

**Comment by ewbankkit** [comment]
@bendrucker Thanks for the contribution :tada: :clap:.

**Pull request merged**
