### PR TITLE
Add aws_s3_bucket_cors_configuration resource

### PR DESCRIPTION
**Pull request by drexler**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #4418
Relates #22776 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
**New Resource:** `aws_s3_bucket_cors_configuration`
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSS3BucketCorsConfiguration'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSS3BucketCorsConfiguration -timeout 120m
=== RUN   TestAccAWSS3BucketCorsConfiguration_CreationWithMissingField
=== PAUSE TestAccAWSS3BucketCorsConfiguration_CreationWithMissingField
=== RUN   TestAccAWSS3BucketCorsConfiguration_UpdateWithMissingCorsField
=== PAUSE TestAccAWSS3BucketCorsConfiguration_UpdateWithMissingCorsField
=== RUN   TestAccAWSS3BucketCorsConfiguration_CorsPolicyCreation
=== PAUSE TestAccAWSS3BucketCorsConfiguration_CorsPolicyCreation
=== RUN   TestAccAWSS3BucketCorsConfiguration_CorsPolicyUpdate
=== PAUSE TestAccAWSS3BucketCorsConfiguration_CorsPolicyUpdate
=== CONT  TestAccAWSS3BucketCorsConfiguration_CreationWithMissingField
=== CONT  TestAccAWSS3BucketCorsConfiguration_CorsPolicyCreation
=== CONT  TestAccAWSS3BucketCorsConfiguration_CorsPolicyUpdate
=== CONT  TestAccAWSS3BucketCorsConfiguration_UpdateWithMissingCorsField
--- PASS: TestAccAWSS3BucketCorsConfiguration_UpdateWithMissingCorsField (2.49s)
--- PASS: TestAccAWSS3BucketCorsConfiguration_CreationWithMissingField (2.66s)
--- PASS: TestAccAWSS3BucketCorsConfiguration_CorsPolicyUpdate (21.59s)
--- PASS: TestAccAWSS3BucketCorsConfiguration_CorsPolicyCreation (22.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	22.212s
...
```

### CODE REVIEW

**Comment by drexler** [comment]
The failed check is due to a code lint problem from the most recent merge into master. I will rebase this PR once that's been resolved. @bflad let me know if you want me to fold a fix to that here.

**Comment by bflad** [comment]
@drexler thanks for the heads up -- fixed on master and will re-run CI for this pull request.

**Comment by drexler** [comment]
@bflad mind reviewing this?

**Comment by pgmillon** [comment]
Since there's no changes on the aws_s3_bucket resource, wouldn't there be a lifecycle conflict between aws_s3_bucket that deletes any existing CORS rules (since cors_rules isn't set) and aws_s3_bucket_cors_configuration that expects CORS rule to be present ?

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by anGie44** [comment]
Output of acceptance tests (commercial):
```
--- PASS: TestAccS3BucketCorsConfiguration_disappears (26.74s)
--- PASS: TestAccS3BucketCorsConfiguration_MultipleRules (29.61s)
--- PASS: TestAccS3BucketCorsConfiguration_basic (29.61s)
--- PASS: TestAccS3BucketCorsConfiguration_SingleRule (30.52s)
--- PASS: TestAccS3BucketCorsConfiguration_update (73.78s)
```

Output of acceptance tests (gov cloud):
```
--- PASS: TestAccS3BucketCorsConfiguration_disappears (28.17s)
--- PASS: TestAccS3BucketCorsConfiguration_MultipleRules (31.30s)
--- PASS: TestAccS3BucketCorsConfiguration_basic (31.41s)
--- PASS: TestAccS3BucketCorsConfiguration_SingleRule (31.44s)
--- PASS: TestAccS3BucketCorsConfiguration_update (76.20s)
```

**Review by anGie44 — APPROVED** [review]
Thanks again @drexler , LGTM 🎸

**Pull request merged**
