### PR TITLE
New resource: aws_cloudformaton_stack_instances

### LINKED ISSUE #24752: Feature request: support multiple regions and accounts CloudFormation StackSets
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

CloudFormation StackSets has options to specify multiple region and accounts. 
But, `aws_cloudformation_stack_set_instance` only accept 1 account and 1 region.
`aws_cloudformation_stack_set_instance` may accept multiple region or accounts.

example from [docs](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/stacksets-getting-started-create.html) , cli accept multiple.

```sh
aws cloudformation create-stack-instances \
  --stack-set-name my-awsconfig-stackset \
  --accounts '["account_ID_1","account_ID_2"]' \
  --regions '["region_1","region_2"]' \
  --operation-preferences FailureToleranceCount=0,MaxConcurrentCount=1
```

This is reference source code
* https://github.com/hashicorp/terraform-provider-aws/blob/3cdebe9581b24f1fb9f059af76f6e2e36d520776/internal/service/cloudformation/stack_set_instance.go#L163
* https://github.com/aws/aws-sdk-go/blob/ec3763d8d5abacbf47c0b4296fb5d27821297508/service/cloudformation/api.go#L8732

### New or Affected Resource(s)

* aws_cloudformation_stack_set_instance

### Potential Terraform Configuration

I have 3 ideas.

* add `regions` which accept list of regions
  * ```hcl
    resource "aws_cloudformation_stack_set_instance" "example" {
      deployment_targets {
      organizational_unit_ids = [aws_organizations_organization.example.roots[0].id]
    }
      regions         = ["us-east-1", "ap-northeast-1"]
      stack_set_name = aws_cloudformation_stack_set.example.name
    }
    ```
* region accept list of regions
  * ```hcl
    resource "aws_cloudformation_stack_set_instance" "example" {
      deployment_targets {
      organizational_unit_ids = [aws_organizations_organization.example.roots[0].id]
    }
      region         = ["us-east-1", "ap-northeast-1"]
      stack_set_name = aws_cloudformation_stack_set.example.name
    }
    ```
* region accept comma delimited region
  * ```hcl
    resource "aws_cloudformation_stack_set_instance" "example" {
      deployment_targets {
      organizational_unit_ids = [aws_organizations_organization.example.roots[0].id]
    }
      region         = "us-east-1,ap-northeast-1"
      stack_set_name = aws_cloudformation_stack_set.example.name
    }
    ```


### References

<!---
Information about referencing Github Issues: https://help.github.com/articles/basic-writing-and-formatting-syntax/#referencing-issues-and-pull-requests

Are there any other GitHub issues (open or closed) or pull requests that should be linked here? Vendor blog posts or documentation? For example:

* https://aws.amazon.com/about-aws/whats-new/2018/04/introducing-amazon-ec2-fleet/
--->

### PR DESCRIPTION
**Pull request by alexknez**
### Description
Introduces `regions` parameter (List of strings) as a list of regions where stack set instance should be created instead of `region`.

- [x] Move from `aws_cloudformation_stack_set_instance` to `aws_cloudformation_stack_instances`
- [x] Update new `aws_cloudformation_stack_instances` to AWS SDK v2
- [ ] ~~Create Sweeper that will work for multi-region, multi-account~~ (Not urgent since sweeping the stack set removes the stack instances)
- [ ] ~~Add state move functionality~~ (Requires framework, this resource is plugin SDK v2)

### Relations

Closes #24752

### Output from Acceptance Testing

```console
% make t T=TestAccCloudFormationStackInstances_ K=cloudformation
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/cloudformation/... -v -count 1 -parallel 20 -run='TestAccCloudFormationStackInstances_'  -timeout 360m
=== RUN   TestAccCloudFormationStackInstances_basic
=== PAUSE TestAccCloudFormationStackInstances_basic
=== RUN   TestAccCloudFormationStackInstances_disappears
=== PAUSE TestAccCloudFormationStackInstances_disappears
=== RUN   TestAccCloudFormationStackInstances_Disappears_stackSet
=== PAUSE TestAccCloudFormationStackInstances_Disappears_stackSet
=== RUN   TestAccCloudFormationStackInstances_Multi_increaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_increaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_swapRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_swapRegions
=== RUN   TestAccCloudFormationStackInstances_parameterOverrides
=== PAUSE TestAccCloudFormationStackInstances_parameterOverrides
=== RUN   TestAccCloudFormationStackInstances_deploymentTargets
=== PAUSE TestAccCloudFormationStackInstances_deploymentTargets
=== RUN   TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== PAUSE TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== RUN   TestAccCloudFormationStackInstances_operationPreferences
=== PAUSE TestAccCloudFormationStackInstances_operationPreferences
=== RUN   TestAccCloudFormationStackInstances_concurrencyMode
=== PAUSE TestAccCloudFormationStackInstances_concurrencyMode
=== RUN   TestAccCloudFormationStackInstances_delegatedAdministrator
=== PAUSE TestAccCloudFormationStackInstances_delegatedAdministrator
=== CONT  TestAccCloudFormationStackInstances_basic
=== CONT  TestAccCloudFormationStackInstances_parameterOverrides
=== CONT  TestAccCloudFormationStackInstances_operationPreferences
=== CONT  TestAccCloudFormationStackInstances_Multi_increaseRegions
=== CONT  TestAccCloudFormationStackInstances_deploymentTargets
=== CONT  TestAccCloudFormationStackInstances_Multi_swapRegions
=== CONT  TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== CONT  TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== CONT  TestAccCloudFormationStackInstances_delegatedAdministrator
=== CONT  TestAccCloudFormationStackInstances_Disappears_stackSet
=== CONT  TestAccCloudFormationStackInstances_concurrencyMode
=== CONT  TestAccCloudFormationStackInstances_disappears
=== NAME  TestAccCloudFormationStackInstances_deploymentTargets
    stack_instances_test.go:321: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_deploymentTargets (1.64s)
=== NAME  TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
    stack_instances_test.go:370: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU (1.73s)
=== NAME  TestAccCloudFormationStackInstances_operationPreferences
    stack_instances_test.go:416: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_operationPreferences (1.83s)
=== NAME  TestAccCloudFormationStackInstances_concurrencyMode
    stack_instances_test.go:451: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_concurrencyMode (12.92s)
=== NAME  TestAccCloudFormationStackInstances_delegatedAdministrator
    stack_instances_test.go:502: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_delegatedAdministrator (23.97s)
--- PASS: TestAccCloudFormationStackInstances_Disappears_stackSet (75.82s)
--- PASS: TestAccCloudFormationStackInstances_basic (76.71s)
--- PASS: TestAccCloudFormationStackInstances_disappears (84.93s)
--- PASS: TestAccCloudFormationStackInstances_Multi_increaseRegions (116.15s)
--- PASS: TestAccCloudFormationStackInstances_Multi_decreaseRegions (124.94s)
--- PASS: TestAccCloudFormationStackInstances_Multi_swapRegions (127.58s)
--- PASS: TestAccCloudFormationStackInstances_parameterOverrides (150.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	155.489s
```

In organization account:

```console
% make t T=TestAccCloudFormationStackInstances_ K=cloudformation P=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/cloudformation/... -v -count 1 -parallel 3 -run='TestAccCloudFormationStackInstances_'  -timeout 360m
=== RUN   TestAccCloudFormationStackInstances_basic
=== PAUSE TestAccCloudFormationStackInstances_basic
=== RUN   TestAccCloudFormationStackInstances_disappears
=== PAUSE TestAccCloudFormationStackInstances_disappears
=== RUN   TestAccCloudFormationStackInstances_Disappears_stackSet
=== PAUSE TestAccCloudFormationStackInstances_Disappears_stackSet
=== RUN   TestAccCloudFormationStackInstances_Multi_increaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_increaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_swapRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_swapRegions
=== RUN   TestAccCloudFormationStackInstances_parameterOverrides
=== PAUSE TestAccCloudFormationStackInstances_parameterOverrides
=== RUN   TestAccCloudFormationStackInstances_deploymentTargets
=== PAUSE TestAccCloudFormationStackInstances_deploymentTargets
=== RUN   TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== PAUSE TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== RUN   TestAccCloudFormationStackInstances_operationPreferences
=== PAUSE TestAccCloudFormationStackInstances_operationPreferences
=== RUN   TestAccCloudFormationStackInstances_concurrencyMode
=== PAUSE TestAccCloudFormationStackInstances_concurrencyMode
=== RUN   TestAccCloudFormationStackInstances_delegatedAdministrator
=== PAUSE TestAccCloudFormationStackInstances_delegatedAdministrator
=== CONT  TestAccCloudFormationStackInstances_basic
=== CONT  TestAccCloudFormationStackInstances_parameterOverrides
=== CONT  TestAccCloudFormationStackInstances_Multi_increaseRegions
--- PASS: TestAccCloudFormationStackInstances_basic (74.77s)
=== CONT  TestAccCloudFormationStackInstances_Multi_swapRegions
--- PASS: TestAccCloudFormationStackInstances_Multi_increaseRegions (114.69s)
=== CONT  TestAccCloudFormationStackInstances_delegatedAdministrator
    stack_instances_test.go:488: this AWS account must not be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_delegatedAdministrator (1.25s)
=== CONT  TestAccCloudFormationStackInstances_Disappears_stackSet
--- PASS: TestAccCloudFormationStackInstances_parameterOverrides (150.56s)
=== CONT  TestAccCloudFormationStackInstances_disappears
--- PASS: TestAccCloudFormationStackInstances_Disappears_stackSet (72.29s)
=== CONT  TestAccCloudFormationStackInstances_Multi_decreaseRegions
--- PASS: TestAccCloudFormationStackInstances_Multi_swapRegions (115.30s)
=== CONT  TestAccCloudFormationStackInstances_concurrencyMode
--- PASS: TestAccCloudFormationStackInstances_disappears (83.30s)
=== CONT  TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
--- PASS: TestAccCloudFormationStackInstances_concurrencyMode (83.36s)
=== CONT  TestAccCloudFormationStackInstances_deploymentTargets
--- PASS: TestAccCloudFormationStackInstances_Multi_decreaseRegions (112.44s)
=== CONT  TestAccCloudFormationStackInstances_operationPreferences
--- PASS: TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU (70.29s)
--- PASS: TestAccCloudFormationStackInstances_deploymentTargets (96.43s)
--- PASS: TestAccCloudFormationStackInstances_operationPreferences (83.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	391.038s
```

### CODE REVIEW

**Comment by agandrabur** [comment]
I did some tests for this version,
`resourceStackSetInstanceDelete` function needs to use the `operation_preferences` block otherwise the operations are run sequentially, even though I set 
```
  operation_preferences {
    region_concurrency_type      = "PARALLEL"
    max_concurrent_count         = 20
    failure_tolerance_percentage = 100
  }
```

**Comment by alexknez** [comment]
> I did some tests for this version, `resourceStackSetInstanceDelete` function needs to use the `operation_preferences` block otherwise the operations are run sequentially, even though I set
> 
> ```
>   operation_preferences {
>     region_concurrency_type      = "PARALLEL"
>     max_concurrent_count         = 20
>     failure_tolerance_percentage = 100
>   }
> ```

Good point @agandrabur. Added in the last commit.

**Comment by AdamTylerLynch** [comment]
🔴 Flagging this PR as it breaks compatibility buy changing the schema. We can not beak compatibility of existing resources/datasources.

**Comment by ewbankkit** [comment]
We can have both `region` and `regions` (with a check that both are not set, e.g. via `ExactlyOneOf`) and then over time deprecate `region`.

**Comment by YakDriver** [comment]
@alexknez I'm working on this PR, doing the items in the op ☝️ above. Let me know if you are going to work on this so we can coordinate and not overwrite each other.

**Comment by 0xVak** [comment]
Is this still being worked on? Last update was a month ago.

**Comment by nkraemer-sysdig** [comment]
Any updates here? We are currently using multiple `aws_cloudformation_stack_set_instance` objects with `managed_execution = true` on the `aws_cloudformation_stack_set` as a workaround, but it would be great to be able to properly leverage multi-region stackset instances, and hence make use of `region_concurrency_type`.

**Comment by nzjoseph** [comment]
@YakDriver is this change still on your radar?

**Comment by ronhanson** [comment]
Hope this will make the cut. 
This would be great to have that feature as the actual doc is confusing, with such existing `region_concurrency_type` or `region_order` parameters letting us think we can do multi region deployment when we cannot.

**Review by YakDriver — APPROVED** [review]
LGTM 🎉 

Regular account:
```console
% make t T=TestAccCloudFormationStackInstances_ K=cloudformation
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/cloudformation/... -v -count 1 -parallel 20 -run='TestAccCloudFormationStackInstances_'  -timeout 360m
=== RUN   TestAccCloudFormationStackInstances_basic
=== PAUSE TestAccCloudFormationStackInstances_basic
=== RUN   TestAccCloudFormationStackInstances_disappears
=== PAUSE TestAccCloudFormationStackInstances_disappears
=== RUN   TestAccCloudFormationStackInstances_Disappears_stackSet
=== PAUSE TestAccCloudFormationStackInstances_Disappears_stackSet
=== RUN   TestAccCloudFormationStackInstances_Multi_increaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_increaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_swapRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_swapRegions
=== RUN   TestAccCloudFormationStackInstances_parameterOverrides
=== PAUSE TestAccCloudFormationStackInstances_parameterOverrides
=== RUN   TestAccCloudFormationStackInstances_deploymentTargets
=== PAUSE TestAccCloudFormationStackInstances_deploymentTargets
=== RUN   TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== PAUSE TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== RUN   TestAccCloudFormationStackInstances_operationPreferences
=== PAUSE TestAccCloudFormationStackInstances_operationPreferences
=== RUN   TestAccCloudFormationStackInstances_concurrencyMode
=== PAUSE TestAccCloudFormationStackInstances_concurrencyMode
=== RUN   TestAccCloudFormationStackInstances_delegatedAdministrator
=== PAUSE TestAccCloudFormationStackInstances_delegatedAdministrator
=== CONT  TestAccCloudFormationStackInstances_basic
=== CONT  TestAccCloudFormationStackInstances_parameterOverrides
=== CONT  TestAccCloudFormationStackInstances_operationPreferences
=== CONT  TestAccCloudFormationStackInstances_Multi_increaseRegions
=== CONT  TestAccCloudFormationStackInstances_delegatedAdministrator
=== CONT  TestAccCloudFormationStackInstances_Disappears_stackSet
=== CONT  TestAccCloudFormationStackInstances_concurrencyMode
=== CONT  TestAccCloudFormationStackInstances_Multi_swapRegions
=== CONT  TestAccCloudFormationStackInstances_disappears
=== CONT  TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== CONT  TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== CONT  TestAccCloudFormationStackInstances_deploymentTargets
    stack_instances_test.go:321: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_deploymentTargets (1.71s)
=== NAME  TestAccCloudFormationStackInstances_operationPreferences
    stack_instances_test.go:416: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_operationPreferences (1.82s)
=== NAME  TestAccCloudFormationStackInstances_delegatedAdministrator
    stack_instances_test.go:502: this AWS account must be the management account of an AWS Organization
=== NAME  TestAccCloudFormationStackInstances_concurrencyMode
    stack_instances_test.go:451: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_concurrencyMode (11.50s)
--- SKIP: TestAccCloudFormationStackInstances_delegatedAdministrator (12.25s)
=== NAME  TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
    stack_instances_test.go:370: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU (12.44s)
--- PASS: TestAccCloudFormationStackInstances_basic (77.51s)
--- PASS: TestAccCloudFormationStackInstances_Disappears_stackSet (81.00s)
--- PASS: TestAccCloudFormationStackInstances_disappears (82.98s)
--- PASS: TestAccCloudFormationStackInstances_Multi_increaseRegions (115.82s)
--- PASS: TestAccCloudFormationStackInstances_Multi_decreaseRegions (116.66s)
--- PASS: TestAccCloudFormationStackInstances_Multi_swapRegions (121.40s)
--- PASS: TestAccCloudFormationStackInstances_parameterOverrides (149.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	154.691s
```

Org account:
```console
% make t T=TestAccCloudFormationStackInstances_ K=cloudformation P=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/cloudformation/... -v -count 1 -parallel 3 -run='TestAccCloudFormationStackInstances_'  -timeout 360m
=== RUN   TestAccCloudFormationStackInstances_basic
=== PAUSE TestAccCloudFormationStackInstances_basic
=== RUN   TestAccCloudFormationStackInstances_disappears
=== PAUSE TestAccCloudFormationStackInstances_disappears
=== RUN   TestAccCloudFormationStackInstances_Disappears_stackSet
=== PAUSE TestAccCloudFormationStackInstances_Disappears_stackSet
=== RUN   TestAccCloudFormationStackInstances_Multi_increaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_increaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_decreaseRegions
=== RUN   TestAccCloudFormationStackInstances_Multi_swapRegions
=== PAUSE TestAccCloudFormationStackInstances_Multi_swapRegions
=== RUN   TestAccCloudFormationStackInstances_parameterOverrides
=== PAUSE TestAccCloudFormationStackInstances_parameterOverrides
=== RUN   TestAccCloudFormationStackInstances_deploymentTargets
=== PAUSE TestAccCloudFormationStackInstances_deploymentTargets
=== RUN   TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== PAUSE TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
=== RUN   TestAccCloudFormationStackInstances_operationPreferences
=== PAUSE TestAccCloudFormationStackInstances_operationPreferences
=== RUN   TestAccCloudFormationStackInstances_concurrencyMode
=== PAUSE TestAccCloudFormationStackInstances_concurrencyMode
=== RUN   TestAccCloudFormationStackInstances_delegatedAdministrator
=== PAUSE TestAccCloudFormationStackInstances_delegatedAdministrator
=== CONT  TestAccCloudFormationStackInstances_basic
=== CONT  TestAccCloudFormationStackInstances_parameterOverrides
=== CONT  TestAccCloudFormationStackInstances_operationPreferences
--- PASS: TestAccCloudFormationStackInstances_basic (82.38s)
=== CONT  TestAccCloudFormationStackInstances_delegatedAdministrator
    stack_instances_test.go:488: this AWS account must not be the management account of an AWS Organization
--- SKIP: TestAccCloudFormationStackInstances_delegatedAdministrator (1.20s)
=== CONT  TestAccCloudFormationStackInstances_Multi_increaseRegions
--- PASS: TestAccCloudFormationStackInstances_operationPreferences (136.01s)
=== CONT  TestAccCloudFormationStackInstances_Multi_swapRegions
--- PASS: TestAccCloudFormationStackInstances_parameterOverrides (153.74s)
=== CONT  TestAccCloudFormationStackInstances_Multi_decreaseRegions
--- PASS: TestAccCloudFormationStackInstances_Multi_increaseRegions (111.55s)
=== CONT  TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU
--- PASS: TestAccCloudFormationStackInstances_Multi_swapRegions (114.01s)
=== CONT  TestAccCloudFormationStackInstances_concurrencyMode
--- PASS: TestAccCloudFormationStackInstances_DeploymentTargets_emptyOU (70.74s)
=== CONT  TestAccCloudFormationStackInstances_disappears
--- PASS: TestAccCloudFormationStackInstances_Multi_decreaseRegions (112.24s)
=== CONT  TestAccCloudFormationStackInstances_deploymentTargets
--- PASS: TestAccCloudFormationStackInstances_concurrencyMode (82.23s)
=== CONT  TestAccCloudFormationStackInstances_Disappears_stackSet
--- PASS: TestAccCloudFormationStackInstances_disappears (83.00s)
--- PASS: TestAccCloudFormationStackInstances_deploymentTargets (96.68s)
--- PASS: TestAccCloudFormationStackInstances_Disappears_stackSet (71.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation	409.239s
```

**Comment by YakDriver** [comment]
Sorry for the delays on this new resource!

**Pull request merged**
