### PR TITLE
remove toolchain directive

### PR DESCRIPTION
**Pull request by johnsonaj**
### Description

causes CHANGELOG gen failure
https://github.com/hashicorp/terraform-provider-aws/actions/runs/7935960516/job/21670211092

```
Run cd .ci/tools && go install github.com/hashicorp/go-changelog/cmd/changelog-build
  cd .ci/tools && go install github.com/hashicorp/go-changelog/cmd/changelog-build
  shell: /usr/bin/bash -e {0}
go: errors parsing go.mod:
/home/runner/work/terraform-provider-aws/terraform-provider-aws/.ci/tools/go.mod:3: invalid go version '1.[2](https://github.com/hashicorp/terraform-provider-aws/actions/runs/7935960516/job/21670211092#step:3:2)1.1': must match format 1.2[3](https://github.com/hashicorp/terraform-provider-aws/actions/runs/7935960516/job/21670211092#step:3:3)
/home/runner/work/terraform-provider-aws/terraform-provider-aws/.ci/tools/go.mod:[5](https://github.com/hashicorp/terraform-provider-aws/actions/runs/7935960516/job/21670211092#step:3:6): unknown directive: toolchain
Error: Process completed with exit code 1.
```

### Relations

Relates https://github.com/hashicorp/terraform-provider-aws/pull/35847.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/35837.

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
I think the real fix here is to add:

```yaml
      - uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version-file: .ci/tools/go.mod
```

to `.github/workflows/generate_changelog.yml`.

**Comment by ewbankkit** [comment]
I think you'll need to run `make cleantidy`?

**Comment by johnsonaj** [comment]
> I think you'll need to run `make cleantidy`?

Yeah. Looks like `main` needs a tidy, which is causing this to lose it's mind.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Pull request merged**
