### PR TITLE
Implement object lambda access points for S3

### LINKED ISSUE #12235: Add a `aws_s3_access_point_policy` resource to prevent cycle errors
_This issue was originally opened by @AlexEshoo as hashicorp/terraform#24258. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Current Terraform Version
```
Terraform v0.12.21
+ provider.aws v2.51.0
```

### Use-cases
When creating an AWS S3 Access Point, a common task is to attach a policy to the access point. 
Terraform provides this with the `policy` attribute of the `aws_s3_access_point` resource, but it cannot be used with the `aws_iam_policy_document` datasource when the document references the ARN of the access point without causing cycle errors.

### Attempted Solutions
```

resource "aws_s3_access_point" "test_access_point" {
  bucket = aws_s3_bucket.my_bucket.id
  name   = "test"
  policy = data.aws_iam_policy_document.test_access_point_policy_doc.json
}

data "aws_iam_policy_document" "test_access_point_policy_doc" {
  statement {
    principals {
      type        = "AWS"
      identifiers = [aws_iam_role.my_role.arn]
    }
    effect    = "Allow"
    actions   = ["s3:ListBucket"]
    resources = [aws_s3_access_point.test_access_point.arn]
    condition {
      test     = "StringLike"
      variable = "s3:prefix"
      values   = ["test/*"]
    }
  }
}
```
This causes cycle errors due to the circular reference.

### Proposal
This problem is resolved for the `aws_s3_bucket` resource by having a separate resource named `aws_s3_bucket_policy` that can be used to link the two resources without circular references. An example is demonstrated [here](https://github.com/hashicorp/terraform/issues/5612#issuecomment-275912351)

The proposal would be to create a similar `aws_s3_access_point_policy` resource that would handle updating the policy on the access point after creation.

### References
- hashicorp/terraform#5612

### LINKED ISSUE #18132: aws_s3_access_point not changing VPC when 'edited in place'
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_s3_access_point

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_s3_access_point" "example" {
  bucket = aws_s3control_bucket.example.arn
  name   = "example"
  vpc_configuration {
    vpc_id = aws_vpc.example.id
  }
}
```

### Expected Behavior

Access point is re-created with new VPC configuration (this parameter can't be edited in place).

### Actual Behavior

Access point is changed with success according to terraform, however VPC id remains from old version.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### LINKED ISSUE #18206: Amazon S3 Object Lambda
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> With S3 Object Lambda you can add your own code to S3 GET requests to modify and process data as it is returned to an application.

### New or Affected Resource(s)

* `aws_s3_access_point_for_object_lambda`

### Potential Terraform Configuration

```hcl
resource "aws_s3_access_point_for_object_lambda" "example" {
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/03/s3-object-lambda-allows-you-to-add-your-own-code-to-s3-get-requests-to-modify-and-process-data-as-it-is-returned-to-an-application/).
[Blog post](https://aws.amazon.com/blogs/aws/introducing-amazon-s3-object-lambda-use-your-code-to-process-data-as-it-is-being-retrieved-from-s3/).

Requires [AWS SDK v1.38.0](https://github.com/aws/aws-sdk-go/releases/tag/v1.38.0).

### LINKED ISSUE #20325: Amazon S3 Access Points aliases
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Amazon S3 Access Points aliases allow any application that requires an S3 bucket name to easily use an access point.

### New or Affected Resource(s)

* [`aws_s3_access_point`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/s3_access_point)

### Potential Terraform Configuration

```hcl
resource "aws_s3_access_point" "example" {
  ...
}

data "aws_s3_bucket_object" "example" {
  bucket = aws_s3_access_point.example.alias
  key    = "example.txt"
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/07/amazon-s3-access-points-aliases-allow-application-requires-s3-bucket-name-easily-use-access-point/).
[User Guide](https://docs.aws.amazon.com/AmazonS3/latest/userguide/access-points-alias.html).

Requires [AWS SDK v1.40.8](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.8):

* #20322

### PR DESCRIPTION
**Pull request by gijzelaerr**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions; they generate extra noise for pull request followers and do not help prioritize the request

Closes #18206.
Closes #12235.
Closes #18132.
Closes #20325.

<!--
Output from acceptance testing:

Replace TestAccXXX with a pattern that matches the tests affected by this PR.

For more information on the `-run` flag, see the `go test` documentation at https://tip.golang.org/cmd/go/#hdr-Testing_flags.

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```-->

### Notes about this PR
 
 * I'm basing the code on the s3 access point module since that seems to be the most similar.

### CODE REVIEW

**Comment by damogallagher** [comment]
I was wondering if this functionality will be available in terraform anytime soon?

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Comment by gijzelaerr** [comment]
this is great news! I ran out of time for working on this, and it was a bit of a deep dive for me since I never worked with go before. I didn't get far, so it could be even better to just start over. Please do whatever is required to complete this PR. I'm also happy to test the PR at some point.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc PKG_NAME=internal/service/s3control TESTARGS='-run=TestAccS3ControlObjectLambdaAccessPointPolicy_\|TestAccS3ControlObjectLambdaAccessPoint_\|TestAccS3ControlAccessPoint_\|TestAccS3ControlAccessPointPolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3control/... -v -count 1 -parallel 20 -run=TestAccS3ControlObjectLambdaAccessPointPolicy_\|TestAccS3ControlObjectLambdaAccessPoint_\|TestAccS3ControlAccessPoint_\|TestAccS3ControlAccessPointPolicy_ -timeout 180m
=== RUN   TestAccS3ControlAccessPointPolicy_basic
=== PAUSE TestAccS3ControlAccessPointPolicy_basic
=== RUN   TestAccS3ControlAccessPointPolicy_disappears
=== PAUSE TestAccS3ControlAccessPointPolicy_disappears
=== RUN   TestAccS3ControlAccessPointPolicy_disappears_AccessPoint
=== PAUSE TestAccS3ControlAccessPointPolicy_disappears_AccessPoint
=== RUN   TestAccS3ControlAccessPointPolicy_update
=== PAUSE TestAccS3ControlAccessPointPolicy_update
=== RUN   TestAccS3ControlAccessPoint_basic
=== PAUSE TestAccS3ControlAccessPoint_basic
=== RUN   TestAccS3ControlAccessPoint_disappears
=== PAUSE TestAccS3ControlAccessPoint_disappears
=== RUN   TestAccS3ControlAccessPoint_Bucket_arn
=== PAUSE TestAccS3ControlAccessPoint_Bucket_arn
=== RUN   TestAccS3ControlAccessPoint_policy
=== PAUSE TestAccS3ControlAccessPoint_policy
=== RUN   TestAccS3ControlAccessPoint_publicAccessBlock
=== PAUSE TestAccS3ControlAccessPoint_publicAccessBlock
=== RUN   TestAccS3ControlAccessPoint_vpc
=== PAUSE TestAccS3ControlAccessPoint_vpc
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_basic
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_basic
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_disappears
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_disappears
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_update
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_update
=== RUN   TestAccS3ControlObjectLambdaAccessPoint_basic
=== PAUSE TestAccS3ControlObjectLambdaAccessPoint_basic
=== RUN   TestAccS3ControlObjectLambdaAccessPoint_disappears
=== PAUSE TestAccS3ControlObjectLambdaAccessPoint_disappears
=== RUN   TestAccS3ControlObjectLambdaAccessPoint_update
=== PAUSE TestAccS3ControlObjectLambdaAccessPoint_update
=== CONT  TestAccS3ControlAccessPointPolicy_basic
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_basic
=== CONT  TestAccS3ControlObjectLambdaAccessPoint_disappears
=== CONT  TestAccS3ControlObjectLambdaAccessPoint_basic
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint
=== CONT  TestAccS3ControlAccessPoint_policy
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_update
=== CONT  TestAccS3ControlAccessPointPolicy_update
=== CONT  TestAccS3ControlAccessPointPolicy_disappears_AccessPoint
=== CONT  TestAccS3ControlAccessPoint_disappears
=== CONT  TestAccS3ControlObjectLambdaAccessPoint_update
=== CONT  TestAccS3ControlAccessPoint_publicAccessBlock
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_disappears
=== CONT  TestAccS3ControlAccessPoint_Bucket_arn
=== CONT  TestAccS3ControlAccessPointPolicy_disappears
=== CONT  TestAccS3ControlAccessPoint_basic
=== CONT  TestAccS3ControlAccessPoint_vpc
=== CONT  TestAccS3ControlAccessPoint_Bucket_arn
    acctest.go:1250: skipping since no Outposts found
--- SKIP: TestAccS3ControlAccessPoint_Bucket_arn (1.58s)
--- PASS: TestAccS3ControlAccessPoint_disappears (51.99s)
--- PASS: TestAccS3ControlAccessPoint_publicAccessBlock (57.89s)
--- PASS: TestAccS3ControlAccessPoint_vpc (58.08s)
--- PASS: TestAccS3ControlAccessPoint_basic (58.28s)
--- PASS: TestAccS3ControlAccessPointPolicy_disappears_AccessPoint (59.89s)
--- PASS: TestAccS3ControlAccessPointPolicy_disappears (60.64s)
--- PASS: TestAccS3ControlAccessPointPolicy_basic (65.05s)
--- PASS: TestAccS3ControlObjectLambdaAccessPoint_basic (82.57s)
--- PASS: TestAccS3ControlObjectLambdaAccessPoint_disappears (87.94s)
--- PASS: TestAccS3ControlAccessPointPolicy_update (95.94s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_basic (99.01s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_disappears (102.15s)
--- PASS: TestAccS3ControlObjectLambdaAccessPoint_update (103.06s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_update (107.04s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint (109.53s)
--- PASS: TestAccS3ControlAccessPoint_policy (117.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3control	121.246s
```

##### GovCloud

```console
% make testacc PKG_NAME=internal/service/s3control TESTARGS='-run=TestAccS3ControlObjectLambdaAccessPointPolicy_\|TestAccS3ControlObjectLambdaAccessPoint_\|TestAccS3ControlAccessPoint_\|TestAccS3ControlAccessPointPolicy_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3control/... -v -count 1 -parallel 20 -run=TestAccS3ControlObjectLambdaAccessPointPolicy_\|TestAccS3ControlObjectLambdaAccessPoint_\|TestAccS3ControlAccessPoint_\|TestAccS3ControlAccessPointPolicy_ -timeout 180m
=== RUN   TestAccS3ControlAccessPointPolicy_basic
=== PAUSE TestAccS3ControlAccessPointPolicy_basic
=== RUN   TestAccS3ControlAccessPointPolicy_disappears
=== PAUSE TestAccS3ControlAccessPointPolicy_disappears
=== RUN   TestAccS3ControlAccessPointPolicy_disappears_AccessPoint
=== PAUSE TestAccS3ControlAccessPointPolicy_disappears_AccessPoint
=== RUN   TestAccS3ControlAccessPointPolicy_update
=== PAUSE TestAccS3ControlAccessPointPolicy_update
=== RUN   TestAccS3ControlAccessPoint_basic
=== PAUSE TestAccS3ControlAccessPoint_basic
=== RUN   TestAccS3ControlAccessPoint_disappears
=== PAUSE TestAccS3ControlAccessPoint_disappears
=== RUN   TestAccS3ControlAccessPoint_Bucket_arn
=== PAUSE TestAccS3ControlAccessPoint_Bucket_arn
=== RUN   TestAccS3ControlAccessPoint_policy
=== PAUSE TestAccS3ControlAccessPoint_policy
=== RUN   TestAccS3ControlAccessPoint_publicAccessBlock
=== PAUSE TestAccS3ControlAccessPoint_publicAccessBlock
=== RUN   TestAccS3ControlAccessPoint_vpc
=== PAUSE TestAccS3ControlAccessPoint_vpc
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_basic
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_basic
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_disappears
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_disappears
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint
=== RUN   TestAccS3ControlObjectLambdaAccessPointPolicy_update
=== PAUSE TestAccS3ControlObjectLambdaAccessPointPolicy_update
=== RUN   TestAccS3ControlObjectLambdaAccessPoint_basic
=== PAUSE TestAccS3ControlObjectLambdaAccessPoint_basic
=== RUN   TestAccS3ControlObjectLambdaAccessPoint_disappears
=== PAUSE TestAccS3ControlObjectLambdaAccessPoint_disappears
=== RUN   TestAccS3ControlObjectLambdaAccessPoint_update
=== PAUSE TestAccS3ControlObjectLambdaAccessPoint_update
=== CONT  TestAccS3ControlAccessPointPolicy_basic
=== CONT  TestAccS3ControlAccessPoint_vpc
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint
=== CONT  TestAccS3ControlObjectLambdaAccessPoint_basic
=== CONT  TestAccS3ControlObjectLambdaAccessPoint_update
=== CONT  TestAccS3ControlObjectLambdaAccessPoint_disappears
=== CONT  TestAccS3ControlAccessPoint_policy
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_disappears
=== CONT  TestAccS3ControlAccessPoint_publicAccessBlock
=== CONT  TestAccS3ControlAccessPointPolicy_update
=== CONT  TestAccS3ControlAccessPoint_basic
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_basic
=== CONT  TestAccS3ControlAccessPoint_disappears
=== CONT  TestAccS3ControlAccessPointPolicy_disappears
=== CONT  TestAccS3ControlObjectLambdaAccessPointPolicy_update
=== CONT  TestAccS3ControlAccessPoint_Bucket_arn
=== CONT  TestAccS3ControlAccessPointPolicy_disappears_AccessPoint
=== CONT  TestAccS3ControlAccessPoint_Bucket_arn
    acctest.go:1250: skipping since no Outposts found
--- SKIP: TestAccS3ControlAccessPoint_Bucket_arn (2.46s)
--- PASS: TestAccS3ControlAccessPointPolicy_disappears_AccessPoint (58.70s)
--- PASS: TestAccS3ControlAccessPoint_disappears (58.78s)
--- PASS: TestAccS3ControlAccessPointPolicy_disappears (61.42s)
--- PASS: TestAccS3ControlAccessPoint_basic (62.08s)
--- PASS: TestAccS3ControlAccessPoint_vpc (63.58s)
--- PASS: TestAccS3ControlAccessPoint_publicAccessBlock (64.03s)
--- PASS: TestAccS3ControlAccessPointPolicy_basic (65.63s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_basic (72.16s)
--- PASS: TestAccS3ControlObjectLambdaAccessPoint_disappears (73.60s)
--- PASS: TestAccS3ControlObjectLambdaAccessPoint_basic (83.52s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_disappears (87.14s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_disappears_AccessPoint (92.20s)
--- PASS: TestAccS3ControlAccessPointPolicy_update (98.65s)
--- PASS: TestAccS3ControlAccessPoint_policy (124.01s)
--- PASS: TestAccS3ControlObjectLambdaAccessPoint_update (131.49s)
--- PASS: TestAccS3ControlObjectLambdaAccessPointPolicy_update (131.65s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3control	140.152s
```

**Comment by ewbankkit** [comment]
@gijzelaerr Thanks for the contribution :tada: :clap:.

**Pull request merged**
