### PR TITLE
aws_cloudfront_origin_request_policy docs fixes

### PR DESCRIPTION
**Pull request by stefansundin**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

---

Found that the links don't work properly on the docs on https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy.

While fixing that, I looked around and found some other links that don't work either, which is why some more pages are receiving fixes.

There's one more issue that I don't know how to fix. There are two `access_control_max_age_sec` on the page. One under [Cors Config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy#cors-config) and one under [Strict Transport Security](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy#strict-transport-security). When you click on the one under `Strict Transport Security`, it takes you to the one under `Cors Config` (because it occurs first in the document).

Honestly I am really annoyed that all the properties are links. It makes it super annoying to copy paste. I think a lot of people would agree with me on this. Please consider stop creating links for these.

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@stefansundin Thanks for the contribution :tada: :clap:.

**Comment by stefansundin** [comment]
@ewbankkit Just wanted to ask if you read the last part of the post? Any ideas if this can be improved?

> There's one more issue that I don't know how to fix. There are two `access_control_max_age_sec` on the page. One under [Cors Config](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy#cors-config) and one under [Strict Transport Security](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudfront_response_headers_policy#strict-transport-security). When you click on the one under `Strict Transport Security`, it takes you to the one under `Cors Config` (because it occurs first in the document).
> 
> Honestly I am really annoyed that all the properties are links. It makes it super annoying to copy paste. I think a lot of people would agree with me on this. Please consider stop creating links for these.

**Comment by ewbankkit** [comment]
@stefansundin Please open a new Issue for the properties-as-links item.

**Pull request merged**
