### PR TITLE
Fix errors in JSON produced not matching service expectations

### LINKED ISSUE #38134: [Bug]: data.aws_networkmanager_core_network_policy_document attribute with_edge_override.use_edge instead of with_edge_override.use_edge_location
### Terraform Core Version

1.3.0

### AWS Provider Version

5.55.0

### Affected Resource(s)

* data.aws_networkmanager_core_network_policy_document

### Expected Behavior

Attribute should be with_edge_override.use_edge_location

### Actual Behavior

As attribute to configure is with_edge_override.use_edge, it translates bad to JSON, giving an error in the service.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
locals {
  aws_regions = {
    ireland   = "eu-west-1"
    london    = "eu-west-2"
    nvirginia = "us-east-1"
    sydney    = "ap-southeast-2"
  }

  segments = {
    production = {
      require_attachment_acceptance = false
      isolate_attachments           = true
    }
    development = {
      require_attachment_acceptance = false
      isolate_attachments           = false
    }
  }
}

data "aws_networkmanager_core_network_policy_document" "policy" {
  core_network_configuration {
    vpn_ecmp_support = false
    asn_ranges       = ["64520-65525"]

    dynamic "edge_locations" {
      for_each = local.aws_regions
      iterator = region

      content {
        location = region.value
      }
    }
  }

  dynamic "segments" {
    for_each = local.segments
    iterator = segment

    content {
      name                          = segment.key
      require_attachment_acceptance = segment.value.require_attachment_acceptance
      isolate_attachments           = segment.value.isolate_attachments
    }
  }

  network_function_groups {
    name                          = "inspectionVpcs"
    require_attachment_acceptance = false
  }

  dynamic "segment_actions" {
    for_each = local.segments
    iterator = segment

    content {
      action  = "send-to"
      segment = segment.key
      via {
        network_function_groups = ["inspectionVpcs"]
        with_edge_override {
          edge_sets = [ 
            [var.aws_regions.london] 
          ]
          use_edge  = var.aws_regions.ireland
        }
      }
    }
  }

  attachment_policies {
    rule_number     = 100
    condition_logic = "or"

    conditions {
      type     = "tag-value"
      operator = "equals"
      key      = "inspection"
      value    = "true"
    }
    action {
      add_to_network_function_group = "inspectionVpcs"
    }
  }

  attachment_policies {
    rule_number     = 200
    condition_logic = "or"

    conditions {
      type = "tag-exists"
      key  = "domain"
    }
    action {
      association_method = "tag"
      tag_value_of_key   = "domain"
    }
  }
}

data "aws_networkmanager_core_network_policy_document" "base_policy" {
  core_network_configuration {
    vpn_ecmp_support = false
    asn_ranges       = ["64520-65525"]

    dynamic "edge_locations" {
      for_each = var.aws_regions
      iterator = region

      content {
        location = region.value
      }
    }
  }

  dynamic "segments" {
    for_each = local.segments
    iterator = segment

    content {
      name                          = segment.key
      require_attachment_acceptance = segment.value.require_attachment_acceptance
      isolate_attachments           = segment.value.isolate_attachments
    }
  }

  network_function_groups {
    name                          = "inspectionVpcs"
    require_attachment_acceptance = false
  }

  attachment_policies {
    rule_number     = 100
    condition_logic = "or"

    conditions {
      type     = "tag-value"
      operator = "equals"
      key      = "inspection"
      value    = "true"
    }
    action {
      add_to_network_function_group = "inspectionVpcs"
    }
  }

  attachment_policies {
    rule_number     = 200
    condition_logic = "or"

    conditions {
      type = "tag-exists"
      key  = "domain"
    }
    action {
      association_method = "tag"
      tag_value_of_key   = "domain"
    }
  }
}

# Global Network
resource "aws_networkmanager_global_network" "global_network" {
  provider = aws.awsnvirginia

  description = "Global Network - ${var.identifier}"

  tags = {
    Name = "Global Network - ${var.identifier}"
  }
}

# Core Network
resource "aws_networkmanager_core_network" "core_network" {
  provider = aws.awsnvirginia

  description       = "Core Network - ${var.identifier}"
  global_network_id = aws_networkmanager_global_network.global_network.id

  create_base_policy = true
  #base_policy_document = local.base_policy
  base_policy_document = data.aws_networkmanager_core_network_policy_document.base_policy.json

  tags = {
    Name = "Core Network - ${var.identifier}"
  }
}

# Core Network Policy Attachment
resource "aws_networkmanager_core_network_policy_attachment" "core_network_policy_attachment" {
  provider = aws.awsnvirginia

  core_network_id = aws_networkmanager_core_network.core_network.id
  policy_document = data.aws_networkmanager_core_network_policy_document.policy.json
}
```

### Steps to Reproduce

Terraform apply of above should be enough

### Debug Output

```
Error: putting Network Manager Core Network (core-network-06fd2373b3367cdb0) policy: CoreNetworkPolicyException: Incorrect policy.
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "662b7f20-6c33-410d-bb28-63569cd0bd04"
│   },
│   Errors: [
│     {
│       ErrorCode: "TYPE_MISMATCH",
│       Message: "$.segment-actions[0].via.with-edge-overrides[0].edge-sets[0]: string found, array expected",
│       Path: "$.segment-actions[0].via.with-edge-overrides[0].edge-sets[0]"
│     },
│     {
│       ErrorCode: "REQUIRED_PROPERTY",
│       Message: "$.segment-actions[0].via.with-edge-overrides[0].use-edge-location: is missing but it is required",
│       Path: "$.segment-actions[0].via.with-edge-overrides[0]"
│     },
│     {
│       ErrorCode: "ADDITIONAL_PROPERTIES",
│       Message: "$.segment-actions[0].via.with-edge-overrides[0].use-edge: is not defined in the schema and the schema does not allow additional properties",
│       Path: "$.segment-actions[0].via.with-edge-overrides[0]"
│     },
│     {
│       ErrorCode: "TYPE_MISMATCH",
│       Message: "$.segment-actions[1].via.with-edge-overrides[0].edge-sets[0]: string found, array expected",
│       Path: "$.segment-actions[1].via.with-edge-overrides[0].edge-sets[0]"
│     },
│     {
│       ErrorCode: "REQUIRED_PROPERTY",
│       Message: "$.segment-actions[1].via.with-edge-overrides[0].use-edge-location: is missing but it is required",
│       Path: "$.segment-actions[1].via.with-edge-overrides[0]"
│     },
│     {
│       ErrorCode: "ADDITIONAL_PROPERTIES",
│       Message: "$.segment-actions[1].via.with-edge-overrides[0].use-edge: is not defined in the schema and the schema does not allow additional properties",
│       Path: "$.segment-actions[1].via.with-edge-overrides[0]"
│     }
│   ],
│   Message_: "Incorrect policy."
│ }
│ 
│   with aws_networkmanager_core_network_policy_attachment.core_network_policy_attachment,
│   on main.tf line 40, in resource "aws_networkmanager_core_network_policy_attachment" "core_network_policy_attachment":
│   40: resource "aws_networkmanager_core_network_policy_attachment" "core_network_policy_attachment" {
```

### Panic Output

_No response_

### Important Factoids

_No response_

### References

Relates https://github.com/hashicorp/terraform-provider-aws/pull/38013.

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by drewtul**
Fixes schema and generated JSON to match expectations of service per the bug in #38134 

### Relations

Closes #38134

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_ PKG=networkmanager
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_'  -timeout 360m
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion (13.37s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic (13.38s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo (13.43s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via (14.13s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager     18.260s

```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@drewtul Thanks for the contribution :tada: :clap:.
As this PR is renaming an attribute we will need to follow best practices -- https://developer.hashicorp.com/terraform/plugin/sdkv2/best-practices/deprecations#provider-attribute-rename -- to avoid backwards compatibility problems.

**Comment by drewtul** [comment]
@ewbankkit The only reason I didn't do that as the attribute never worked previously, so no working configuration could've been used by either of the attributes I changed per the bug I linked do. The generated JSON is rejected by the service and always has been.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_' PKG=networkmanager
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/networkmanager/... -v -count 1 -parallel 20  -run=TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_ -timeout 360m
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via
=== RUN   TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_viaCompat
=== PAUSE TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_viaCompat
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion
=== CONT  TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_viaCompat
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_whenSentTo (8.73s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_viaCompat (8.75s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_serviceInsertion (8.75s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_basic (8.80s)
--- PASS: TestAccNetworkManagerCoreNetworkPolicyDocumentDataSource_via (8.80s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	13.648s
```

**Comment by ewbankkit** [comment]
@drewtul Thanks for the contribution :tada: :clap:.

**Pull request merged**
