### PR TITLE
Add support for Eventbridge Schema Registry, Discoverer and Schema resources

### LINKED ISSUE #11088: Support Amazon EventBridge Schema Registry
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon EventBridge schema registry and discovery announced - **In preview**.

### New or Affected Resource(s)

It looks like an initial set of resources could be:

* `aws_schemas_discoverer`
* `aws_schemas_registry`
* `aws_schemas_schema`

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/introducing-amazon-eventbridge-schema-registry-now-in-preview/).
[Blog post](https://aws.amazon.com/blogs/compute/introducing-amazon-eventbridge-schema-registry-and-discovery-in-preview/).
[User guide](https://docs.aws.amazon.com/eventbridge/latest/userguide/eventbridge-schemas.html).
[API reference](https://docs.aws.amazon.com/eventbridge/latest/schema-reference/what-is-eventbridge-schemas.html).

Requires [AWS SDK v1.25.44](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.44):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11083

### PR DESCRIPTION
**Pull request by jordanfinners**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11088

Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSchemas -timeout 180m
=== RUN   TestAccAWSSchemasDiscoverer_basic
=== PAUSE TestAccAWSSchemasDiscoverer_basic
=== RUN   TestAccAWSSchemasDiscoverer_tags
=== PAUSE TestAccAWSSchemasDiscoverer_tags
=== RUN   TestAccAWSSchemasDiscoverer_disappears
=== PAUSE TestAccAWSSchemasDiscoverer_disappears
=== RUN   TestAccAWSSchemasRegistry_basic
=== PAUSE TestAccAWSSchemasRegistry_basic
=== RUN   TestAccAWSSchemasRegistry_tags
=== PAUSE TestAccAWSSchemasRegistry_tags
=== RUN   TestAccAWSSchemasRegistry_disappears
=== PAUSE TestAccAWSSchemasRegistry_disappears
=== RUN   TestAccAWSSchemasSchema_basic
=== PAUSE TestAccAWSSchemasSchema_basic
=== RUN   TestAccAWSSchemasSchema_tags
=== PAUSE TestAccAWSSchemasSchema_tags
=== RUN   TestAccAWSSchemasSchema_disappears
=== PAUSE TestAccAWSSchemasSchema_disappears
=== CONT  TestAccAWSSchemasDiscoverer_basic
=== CONT  TestAccAWSSchemasRegistry_disappears
=== CONT  TestAccAWSSchemasSchema_disappears
=== CONT  TestAccAWSSchemasSchema_tags
=== CONT  TestAccAWSSchemasSchema_basic
=== CONT  TestAccAWSSchemasRegistry_tags
=== CONT  TestAccAWSSchemasDiscoverer_disappears
=== CONT  TestAccAWSSchemasDiscoverer_tags
=== CONT  TestAccAWSSchemasRegistry_basic
--- PASS: TestAccAWSSchemasRegistry_disappears (80.59s)
--- PASS: TestAccAWSSchemasDiscoverer_disappears (87.24s)
--- PASS: TestAccAWSSchemasSchema_disappears (87.34s)
--- PASS: TestAccAWSSchemasRegistry_basic (124.27s)
--- PASS: TestAccAWSSchemasSchema_basic (132.50s)
--- PASS: TestAccAWSSchemasDiscoverer_basic (132.63s)
--- PASS: TestAccAWSSchemasRegistry_tags (139.56s)
--- PASS: TestAccAWSSchemasSchema_tags (149.44s)
--- PASS: TestAccAWSSchemasDiscoverer_tags (151.75s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       151.830s
```

### CODE REVIEW

**Comment by jordanfinners** [comment]
@YakDriver I've also opened this one with some more eventbridge related resources :)

**Comment by jordanfinners** [comment]
Hey @YakDriver would you mind reviewing this please 🙏  Would be great to get the builds approved to see if I need to make other changes 😃

**Comment by jordanfinners** [comment]
Hey @sthulb , @heitorlessa mentioned you would be the person to speak to about this, would you be able to review the PR and let me know your thoughts please 🙏

**Comment by sthulb** [comment]
@jordanfinners at a quick glance, this looks fine. I'll finish my initial review today.

**Review by sthulb — APPROVED** [review]

**Comment by jordanfinners** [comment]
@ewbankkit would it be possible to have your review of this PR too for merging please 🙏

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSSchemasSchema_\|TestAccAWSSchemasRegistry_\|TestAccAWSSchemasDiscoverer_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSchemasSchema_\|TestAccAWSSchemasRegistry_\|TestAccAWSSchemasDiscoverer_ -timeout 180m
=== RUN   TestAccAWSSchemasDiscoverer_basic
=== PAUSE TestAccAWSSchemasDiscoverer_basic
=== RUN   TestAccAWSSchemasDiscoverer_disappears
=== PAUSE TestAccAWSSchemasDiscoverer_disappears
=== RUN   TestAccAWSSchemasDiscoverer_Description
=== PAUSE TestAccAWSSchemasDiscoverer_Description
=== RUN   TestAccAWSSchemasDiscoverer_Tags
=== PAUSE TestAccAWSSchemasDiscoverer_Tags
=== RUN   TestAccAWSSchemasRegistry_basic
=== PAUSE TestAccAWSSchemasRegistry_basic
=== RUN   TestAccAWSSchemasRegistry_disappears
=== PAUSE TestAccAWSSchemasRegistry_disappears
=== RUN   TestAccAWSSchemasRegistry_Description
=== PAUSE TestAccAWSSchemasRegistry_Description
=== RUN   TestAccAWSSchemasRegistry_Tags
=== PAUSE TestAccAWSSchemasRegistry_Tags
=== RUN   TestAccAWSSchemasSchema_basic
=== PAUSE TestAccAWSSchemasSchema_basic
=== RUN   TestAccAWSSchemasSchema_disappears
=== PAUSE TestAccAWSSchemasSchema_disappears
=== RUN   TestAccAWSSchemasSchema_ContentDescription
=== PAUSE TestAccAWSSchemasSchema_ContentDescription
=== RUN   TestAccAWSSchemasSchema_Tags
=== PAUSE TestAccAWSSchemasSchema_Tags
=== CONT  TestAccAWSSchemasDiscoverer_basic
=== CONT  TestAccAWSSchemasRegistry_Tags
=== CONT  TestAccAWSSchemasSchema_Tags
=== CONT  TestAccAWSSchemasSchema_ContentDescription
=== CONT  TestAccAWSSchemasSchema_disappears
=== CONT  TestAccAWSSchemasRegistry_basic
=== CONT  TestAccAWSSchemasSchema_basic
=== CONT  TestAccAWSSchemasRegistry_disappears
=== CONT  TestAccAWSSchemasRegistry_Description
=== CONT  TestAccAWSSchemasDiscoverer_Description
=== CONT  TestAccAWSSchemasDiscoverer_Tags
=== CONT  TestAccAWSSchemasDiscoverer_disappears
--- PASS: TestAccAWSSchemasRegistry_disappears (14.95s)
--- PASS: TestAccAWSSchemasRegistry_basic (21.08s)
--- PASS: TestAccAWSSchemasDiscoverer_disappears (21.43s)
--- PASS: TestAccAWSSchemasSchema_disappears (21.47s)
--- PASS: TestAccAWSSchemasDiscoverer_basic (24.94s)
--- PASS: TestAccAWSSchemasSchema_basic (25.01s)
--- PASS: TestAccAWSSchemasRegistry_Description (43.05s)
--- PASS: TestAccAWSSchemasRegistry_Tags (43.05s)
--- PASS: TestAccAWSSchemasSchema_Tags (47.14s)
--- PASS: TestAccAWSSchemasDiscoverer_Description (49.91s)
--- PASS: TestAccAWSSchemasDiscoverer_Tags (50.05s)
--- PASS: TestAccAWSSchemasSchema_ContentDescription (50.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	53.189s              
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSSchemasSchema_\|TestAccAWSSchemasRegistry_\|TestAccAWSSchemasDiscoverer_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSchemasSchema_\|TestAccAWSSchemasRegistry_\|TestAccAWSSchemasDiscoverer_ -timeout 180m
=== RUN   TestAccAWSSchemasDiscoverer_basic
=== PAUSE TestAccAWSSchemasDiscoverer_basic
=== RUN   TestAccAWSSchemasDiscoverer_disappears
=== PAUSE TestAccAWSSchemasDiscoverer_disappears
=== RUN   TestAccAWSSchemasDiscoverer_Description
=== PAUSE TestAccAWSSchemasDiscoverer_Description
=== RUN   TestAccAWSSchemasDiscoverer_Tags
=== PAUSE TestAccAWSSchemasDiscoverer_Tags
=== RUN   TestAccAWSSchemasRegistry_basic
=== PAUSE TestAccAWSSchemasRegistry_basic
=== RUN   TestAccAWSSchemasRegistry_disappears
=== PAUSE TestAccAWSSchemasRegistry_disappears
=== RUN   TestAccAWSSchemasRegistry_Description
=== PAUSE TestAccAWSSchemasRegistry_Description
=== RUN   TestAccAWSSchemasRegistry_Tags
=== PAUSE TestAccAWSSchemasRegistry_Tags
=== RUN   TestAccAWSSchemasSchema_basic
=== PAUSE TestAccAWSSchemasSchema_basic
=== RUN   TestAccAWSSchemasSchema_disappears
=== PAUSE TestAccAWSSchemasSchema_disappears
=== RUN   TestAccAWSSchemasSchema_ContentDescription
=== PAUSE TestAccAWSSchemasSchema_ContentDescription
=== RUN   TestAccAWSSchemasSchema_Tags
=== PAUSE TestAccAWSSchemasSchema_Tags
=== CONT  TestAccAWSSchemasDiscoverer_basic
=== CONT  TestAccAWSSchemasRegistry_Tags
=== CONT  TestAccAWSSchemasSchema_Tags
=== CONT  TestAccAWSSchemasRegistry_basic
=== CONT  TestAccAWSSchemasSchema_basic
=== CONT  TestAccAWSSchemasDiscoverer_Description
=== CONT  TestAccAWSSchemasSchema_ContentDescription
=== CONT  TestAccAWSSchemasDiscoverer_Tags
=== CONT  TestAccAWSSchemasDiscoverer_disappears
=== CONT  TestAccAWSSchemasSchema_disappears
=== CONT  TestAccAWSSchemasRegistry_Description
=== CONT  TestAccAWSSchemasRegistry_disappears
=== CONT  TestAccAWSSchemasDiscoverer_basic
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasDiscoverer_basic (1.52s)
=== CONT  TestAccAWSSchemasRegistry_Tags
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasRegistry_Tags (1.52s)
=== CONT  TestAccAWSSchemasSchema_Tags
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasSchema_Tags (1.52s)
=== CONT  TestAccAWSSchemasDiscoverer_Tags
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasDiscoverer_Tags (1.52s)
=== CONT  TestAccAWSSchemasDiscoverer_disappears
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasDiscoverer_disappears (1.52s)
=== CONT  TestAccAWSSchemasSchema_basic
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasSchema_basic (1.52s)
=== CONT  TestAccAWSSchemasRegistry_basic
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
=== CONT  TestAccAWSSchemasSchema_ContentDescription
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
=== CONT  TestAccAWSSchemasRegistry_Description
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasRegistry_basic (1.52s)
=== CONT  TestAccAWSSchemasRegistry_disappears
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasSchema_ContentDescription (1.52s)
--- SKIP: TestAccAWSSchemasRegistry_Description (1.52s)
=== CONT  TestAccAWSSchemasDiscoverer_Description
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasRegistry_disappears (1.52s)
--- SKIP: TestAccAWSSchemasDiscoverer_Description (1.52s)
=== CONT  TestAccAWSSchemasSchema_disappears
    provider_test.go:734: skipping tests; partition aws-us-gov does not support schemas service
--- SKIP: TestAccAWSSchemasSchema_disappears (1.52s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.543s
```

**Comment by ewbankkit** [comment]
@jordanfinners Thanks for the contribution 🎉 👏.
Everything looks great.
In order to get this merged quickly I made a few changes:
* Added `tags_all` attributes for `default_tags` support
* Removed `discoverer_id` attribute (duplicative of `id`)
* In `aws_schemas_schema` renamed `registry` to `registry_name`

**Comment by jordanfinners** [comment]
> @jordanfinners Thanks for the contribution 🎉 👏.
> Everything looks great.
> In order to get this merged quickly I made a few changes:
> 
> * Added `tags_all` attributes for `default_tags` support
> * Removed `discoverer_id` attribute (duplicative of `id`)
> * In `aws_schemas_schema` renamed `registry` to `registry_name`

Thank you for sorting those bits! 😊

**Pull request merged**
