### PR TITLE
f/provider - Add validation for provider session-name

### PR DESCRIPTION
**Pull request by pierre-borckmans**
This PR adds validation for the provider `session-name`.
The regex was found on this AWS documentation page:
https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSProvider'

...
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAcctestProvider_AssumeRole_' PKG_NAME=internal/acctest
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/acctest/... -v -count 1 -parallel 20 -run=TestAccAcctestProvider_AssumeRole_ -timeout 180m
=== RUN   TestAccAcctestProvider_AssumeRole_empty
=== PAUSE TestAccAcctestProvider_AssumeRole_empty
=== CONT  TestAccAcctestProvider_AssumeRole_empty
--- PASS: TestAccAcctestProvider_AssumeRole_empty (9.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/acctest	13.048s
```

**Comment by ewbankkit** [comment]
@pierre-borckmans Thanks for the contribution :tada: :clap:.

**Comment by n0rig** [comment]
@pierre-borckmans / @ewbankkit 

I am not getting these sort of errors:
image

with the following terragrunt.hcl code:
```
locals {
  service_name = "foobar"

  # Automatically load environment-level variables
  account_vars = read_terragrunt_config(find_in_parent_folders("foobar-account.hcl"))

  # Extract the variables we need for easy access
  account_name = local.account_vars.locals.account_name
  account_id   = local.account_vars.locals.aws_account_id
  aws_region   = local.account_vars.locals.aws_region

  # Running in CICD or not
  #
  # Allows overriding of the AWS Role which is assumed to let CICD service accounts use different Roles.
  assume_role_name = get_env("VSS_ASSUME_ROLE_NAME", "")

  # Assume role as a service (atlantis)
  external_id = get_env("VSS_ASSUME_ROLE_EXTERNAL_ID", "")
}

provider "aws" {
  alias  = "us_west_2"
  region = "us-west-2"
  ignore_tags {
    key_prefixes = ["kubernetes.io/"]
  }
  assume_role {
    role_arn = "arn:aws:iam::${local.account_id}:role/${local.assume_role_name}"
    external_id = "${local.external_id}"
  }
}
```

**Comment by n0rig** [comment]
@pierre-borckmans / @ewbankkit 

I am now getting these sort of errors and I believe this is leading to our cicd pipelines to fail:
image

with the following terragrunt.hcl code:
```
locals {
  service_name = "foobar"

  # Automatically load environment-level variables
  account_vars = read_terragrunt_config(find_in_parent_folders("foobar-account.hcl"))

  # Extract the variables we need for easy access
  account_name = local.account_vars.locals.account_name
  account_id   = local.account_vars.locals.aws_account_id
  aws_region   = local.account_vars.locals.aws_region

  # Running in CICD or not
  #
  # Allows overriding of the AWS Role which is assumed to let CICD service accounts use different Roles.
  assume_role_name = get_env("VSS_ASSUME_ROLE_NAME", "")

  # Assume role as a service (atlantis)
  external_id = get_env("VSS_ASSUME_ROLE_EXTERNAL_ID", "")
}

provider "aws" {
  alias  = "us_west_2"
  region = "us-west-2"
  ignore_tags {
    key_prefixes = ["kubernetes.io/"]
  }
  assume_role {
    role_arn = "arn:aws:iam::${local.account_id}:role/${local.assume_role_name}"
    external_id = "${local.external_id}"
  }
}
```

**Comment by n0rig** [comment]
I think I am okay by setting a default value which can be overridden if the env_var is present:
```
  external_id = get_env("ASSUME_ROLE_EXTERNAL_ID", "some-value")
```

**Comment by Shanshan-Qu** [comment]
> This PR adds validation for the provider `session-name`. The regex was found on this AWS documentation page: https://docs.aws.amazon.com/STS/latest/APIReference/API_AssumeRole.html
> 
> ### Community Note
> * Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
> * Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request
> 
> Output from acceptance testing:
> 
> ```
> $ make testacc TESTARGS='-run=TestAccAWSProvider'
> 
> ...
> ```

Hi @pierre-borckmans 

The current issue we have is:
Previously, we leave the value empty as default for ExternalId and RoleSessionName. After this release, we have the erorr:

> Error: expected length of assume_role.0.session_name to be in the range (2 - 64), got 

> Error: expected length of assume_role.0.external_id to be in the range (2 - 1224), got 

The error above leads me to this PR. And I am thinking about what the logic should the code be rather than remove these two values from our various code repos which previously works well.

As the AWS docs mentioned, ExternalId and RoleSessionName are not required. Shall the code have the logic as AWS docs:
1. If there is no value, it is still allowed it is an empty value. 
2. If there is a value, then, use the validation that has been added.

Also another suggestion:
For a new release feature, shall we give some clue in the error like feature changed in PR18085 to make troubleshooting a bit more efficient? 

It will be appreciated to hear your feedback.

Thanks
shanshan

**Pull request merged**
