### PR TITLE
r/aws_dx_gateway_association: Remove ForceNew from proposal_id attribute

### LINKED ISSUE #9209: aws_dx_gateway_association_proposal recreated
## Terraform bug

It happens when associating a virtual private gateway with a direct connect gateway in a separate account ([See AWS doc](https://docs.aws.amazon.com/directconnect/latest/UserGuide/multi-account-associate-vgw.html)). There is a [terraform resource](https://www.terraform.io/docs/providers/aws/r/dx_gateway_association_proposal.html) for the proposal. But this resource is not permanent, so terraform will try to recreate it.

### Terraform Version

- terraform 0.11.10
- terraform-provider-aws 2.12.0

### Affected Resource(s)

* aws_dx_gateway_association_proposal
* aws_dx_gateway_association

### Terraform Configuration Files

```hcl
resource "aws_dx_gateway_association_proposal" "dcgw_association_proposal" {
  depends_on                  = ["aws_vpn_gateway_attachment.vpn_attachment"]
  dx_gateway_id               = "${local.dcgw_id}"
  dx_gateway_owner_account_id = "${local.shared_services_account_id}"
  associated_gateway_id       = "${aws_vpn_gateway.vpn_gw.id}"
}

resource "aws_dx_gateway_association" "dcgw_association" {
  provider = "aws.shared_services"

  proposal_id                         = "${aws_dx_gateway_association_proposal.dcgw_association_proposal.id}"
  dx_gateway_id                       = "${local.dcgw_id}"
  associated_gateway_owner_account_id = "${local.account_id}"

  timeouts {
    delete = "30m"
    create = "30m"
  }
}
```
### Expected Behavior

- Apply: create proposal, associate in other account, networks are connected
- Any apply after that: No change

### Actual Behavior

- Apply: create proposal, associate in other account
- Apply immediately: No change
- Apply after a few days once the proposal has been removed by AWS: create proposal, force recreation of association, networks are disconnected for up to 20min -> **DOWNTIME**

### Steps to Reproduce

1. `terraform apply`
2. Wait for a few days or delete the proposal ([Example](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/directconnect.html#DirectConnect.Client.delete_direct_connect_gateway_association_proposal))
3. `terraform plan`: shows creation of the proposal and recreation of the association

### Important Factoids

Raised a support case with AWS to understand the behaviour. Here is the response:

*I relayed the same question to the service team and they have informed me that the proposal will be available as long as the "accepter" has not accepted the proposal. Once the proposal is accepted, it will disappear after some time. There is no defined time duration as to how long the proposal is available after acceptance through CLI. As we use a distributed and eventual consistency model, I would highly recommend you to not use the time the proposal remains in the CLI output after acceptance to make any design, architectural, or application decisions.*

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9209.
Replaces https://github.com/terraform-providers/terraform-provider-aws/pull/12221.

Output from acceptance testing:

```console
$ ACCTEST_TIMEOUT=600m ACCTEST_PARALLELISM=2 make testacc TEST=./aws/ TESTARGS='-run=TestAccAwsDxGatewayAssociation_\|TestAccAwsDxGateway_complex'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAwsDxGatewayAssociation_\|TestAccAwsDxGateway_complex -timeout 600m
=== RUN   TestAccAwsDxGatewayAssociation_V0StateUpgrade
=== PAUSE TestAccAwsDxGatewayAssociation_V0StateUpgrade
=== RUN   TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount
=== RUN   TestAccAwsDxGatewayAssociation_basicTransitGatewaySingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicTransitGatewaySingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount
=== RUN   TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount
=== PAUSE TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount
=== RUN   TestAccAwsDxGatewayAssociation_recreateProposal
=== PAUSE TestAccAwsDxGatewayAssociation_recreateProposal
=== RUN   TestAccAwsDxGateway_complex
=== PAUSE TestAccAwsDxGateway_complex
=== CONT  TestAccAwsDxGatewayAssociation_V0StateUpgrade
=== CONT  TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount
=== CONT  TestAccAwsDxGateway_complex
--- PASS: TestAccAwsDxGatewayAssociation_V0StateUpgrade (1254.75s)
--- PASS: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount (1674.29s)
=== CONT  TestAccAwsDxGatewayAssociation_recreateProposal
--- PASS: TestAccAwsDxGateway_complex (1358.19s)
=== CONT  TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount
--- PASS: TestAccAwsDxGatewayAssociation_recreateProposal (1666.97s)
=== CONT  TestAccAwsDxGatewayAssociation_basicTransitGatewaySingleAccount
--- PASS: TestAccAwsDxGatewayAssociation_basicTransitGatewaySingleAccount (1146.25s)
=== CONT  TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount
--- PASS: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount (2003.59s)
=== CONT  TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount
--- PASS: TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount (1079.22s)
=== CONT  TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount
--- PASS: TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount (1721.43s)
=== CONT  TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount
--- PASS: TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount (1520.37s)
--- PASS: TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount (1420.51s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	7629.774s
```

### CODE REVIEW

**Comment by blckct** [comment]
Hey, is there any update on this one?

**Comment by hhh0505** [comment]
Been waiting on this as well, would love to have an update.

**Review by bill-rich — CHANGES_REQUESTED** [review]
Looks good overall, but there are some merge conflicts that need to be resolved.

**Review by bill-rich — APPROVED** [review]
LGTM

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsDxGateway_ -timeout 120m
=== RUN   TestAccAwsDxGateway_basic
=== PAUSE TestAccAwsDxGateway_basic
=== RUN   TestAccAwsDxGateway_complex
=== PAUSE TestAccAwsDxGateway_complex
=== CONT  TestAccAwsDxGateway_basic
=== CONT  TestAccAwsDxGateway_complex
--- PASS: TestAccAwsDxGateway_basic (44.23s)
--- PASS: TestAccAwsDxGateway_complex (1391.40s)
=== RUN   TestAccAwsDxGatewayAssociation_V0StateUpgrade
=== PAUSE TestAccAwsDxGatewayAssociation_V0StateUpgrade
=== RUN   TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount
=== RUN   TestAccAwsDxGatewayAssociation_basicTransitGatewaySingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicTransitGatewaySingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount
=== PAUSE TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount
=== RUN   TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount
=== PAUSE TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount
=== RUN   TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount
=== PAUSE TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount
=== RUN   TestAccAwsDxGatewayAssociation_recreateProposal
=== PAUSE TestAccAwsDxGatewayAssociation_recreateProposal
--- PASS: TestAccAwsDxGatewayAssociation_V0StateUpgrade (1326.57s)
--- PASS: TestAccAwsDxGatewayAssociation_multiVpnGatewaysSingleAccount (1327.76s)
--- PASS: TestAccAwsDxGatewayAssociation_basicVpnGatewaySingleAccount (1419.81s)
--- PASS: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewaySingleAccount (2027.74s)
--- PASS: TestAccAwsDxGatewayAssociation_basicTransitGatewayCrossAccount (1252.75s)
--- PASS: TestAccAwsDxGatewayAssociation_basicVpnGatewayCrossAccount (1491.80s)
--- PASS: TestAccAwsDxGatewayAssociation_recreateProposal (1496.30s)
--- PASS: TestAccAwsDxGatewayAssociation_allowedPrefixesVpnGatewayCrossAccount (2162.51s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2162.636s
```

**Pull request merged**
