### PR TITLE
Find aws_lb by tags in data source

### LINKED ISSUE #12265: Add tags argument into aws lb data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is a feature request to ask for adding the "tags" argument into aws lb data source.

Quoting exactly from @mbyrdziak in https://github.com/terraform-providers/terraform-provider-aws/pull/6458:
> Some tools, like kubernetes, creates cloud resources with random names hence you are unable to find them by current possibilities of this data source. Finding load balancers by specifying tags will solve this issue.

There is already a PR for this, but I'm creating an issue as it seems that this PR is lost in the wild without an issue to track this.

### New or Affected Resource(s)

* aws_lb (or the aliased aws_alb)

### Potential Terraform Configuration

```hcl
data "aws_lb" "k8s_ingress_lb" {
  tags = "k8s-ingress-lb"
}
```

### References

* https://github.com/terraform-providers/terraform-provider-aws/pull/6458
* https://www.terraform.io/docs/providers/aws/d/lb.html

### PR DESCRIPTION
**Pull request by mbyrdziak**
Closes #12265.

Changes proposed in this pull request:

* Add tags argument into aws lb data source (some tools, like kubernetes, creates cloud resources with random names hence you are unable to find them by current possibilities of this data source. Finding load balancers by specifying tags will solve this issue)

Output from acceptance testing:

```
$make testacc TESTARGS='-run="TestAccDataSourceAWSLB_basic|TestAccDataSourceAWSLBBackwardsCompatibility"'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run="TestAccDataSourceAWSLB_basic|TestAccDataSourceAWSLBBackwardsCompatibility" -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccDataSourceAWSLB_basic
=== PAUSE TestAccDataSourceAWSLB_basic
=== RUN   TestAccDataSourceAWSLBBackwardsCompatibility
=== PAUSE TestAccDataSourceAWSLBBackwardsCompatibility
=== CONT  TestAccDataSourceAWSLB_basic
=== CONT  TestAccDataSourceAWSLBBackwardsCompatibility
--- PASS: TestAccDataSourceAWSLBBackwardsCompatibility (244.02s)
--- PASS: TestAccDataSourceAWSLB_basic (255.54s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	255.558s

...
```

### CODE REVIEW

**Comment by mbyrdziak** [comment]
@bflad Have a moment to take a look at this enhancement and give some feedback if this have a chance to be merged soon? Thanks in advance.

**Comment by mbyrdziak** [comment]
@bflad Any chance to review and merge this? I would like to remove custom provider in our provision process. Thanks!

**Comment by mbyrdziak** [comment]
@ewbankkit Hey, could you find time to review this? It would be a great simplification for our stack.

**Comment by sebolabs** [comment]
any chance to resurrect this? this enhancement would be very useful

**Comment by MaxFlanders** [comment]
Would love to see this get added!

**Comment by ofirshtrull** [comment]
would also like to see this go in, now I have my k8s cluster create load balancers so I need to have a way to connect to terraform via tag only because the k8s creates lbs with wired names

**Comment by ofirshtrull** [comment]
@mbyrdziak is there a chance to add this to the next release?

**Comment by wambozi** [comment]
> would also like to see this go in, now I have my k8s cluster create load balancers so I need to have a way to connect to terraform via tag only because the k8s creates lbs with wired names

You can use the kubernetes provider to get the load balancers, if waiting for this is holding you up. e.g.

```
terraform {
  required_version = ">= 0.12"
  backend "s3" {}
}

// instantiating an empty kubernetes provider will pick up your kube config from 
// ~/.kube/config. Works out well for local dev and the runners.
provider "kubernetes" {}

provider "aws" {
  version = "~>2.0"
  region  = "us-east-1"
}

variable "service_name" {
    description = "name of the service in kubernetes"
    type = string
}

data "kubernetes_service" "_" {
  metadata {
    name      = "${var.service_name}-nlb"
    namespace = var.kubernetes_namespace
  }
}

data "aws_lb" "_" {
  name = split("-", "${data.kubernetes_service._.load_balancer_ingress.0.hostname}")[0]
}
```

**Comment by ofirshtrull** [comment]
thanks @wambozi but it dosnet help i tried this with 
```hcl
data "kubernetes_ingress" "example" {
  metadata {
    name = "foo.bar.com"
    namespace = "develop"
  }
}
```
but i am getting errors that it cannot find the ingress 
such as Error: Failed to read Ingress '/' because: ingresses.extensions "foo.bar.com" not found

**Review by BrunoChauvet — APPROVED** [review]

**Comment by stibi** [comment]
Hello, is there anything I can help with to get this merged?

**Comment by AndrewChubatiuk** [comment]
Any progress on it?

**Comment by ofirshtrull** [comment]
@antonbabenko maybe you can help move this forward?

**Comment by antonbabenko** [comment]
I wish I can do anything related to the processing speed of the pull-request but I can't.

**Comment by ckdarby** [comment]
@BrunoChauvet Any idea what is blocking this from being merged and moving forward?

**Comment by ckdarby** [comment]
@gdavison Any idea what is blocking this from being merged and moving forward?

Just noticed that @BrunoChauvet doesn't work at HashiCorp.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTARGS='-run=TestAccDataSourceAWSLB_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAWSLB_ -timeout 180m
=== RUN   TestAccDataSourceAWSLB_basic
=== PAUSE TestAccDataSourceAWSLB_basic
=== RUN   TestAccDataSourceAWSLB_outpost
=== PAUSE TestAccDataSourceAWSLB_outpost
=== RUN   TestAccDataSourceAWSLB_BackwardsCompatibility
=== PAUSE TestAccDataSourceAWSLB_BackwardsCompatibility
=== CONT  TestAccDataSourceAWSLB_basic
=== CONT  TestAccDataSourceAWSLB_BackwardsCompatibility
=== CONT  TestAccDataSourceAWSLB_outpost
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccDataSourceAWSLB_outpost (1.89s)
--- PASS: TestAccDataSourceAWSLB_basic (244.75s)
--- PASS: TestAccDataSourceAWSLB_BackwardsCompatibility (249.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	252.614s
```

##### GovCloud

```console
% make testacc TESTARGS='-run=TestAccDataSourceAWSLB_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAWSLB_ -timeout 180m
=== RUN   TestAccDataSourceAWSLB_basic
=== PAUSE TestAccDataSourceAWSLB_basic
=== RUN   TestAccDataSourceAWSLB_outpost
=== PAUSE TestAccDataSourceAWSLB_outpost
=== RUN   TestAccDataSourceAWSLB_BackwardsCompatibility
=== PAUSE TestAccDataSourceAWSLB_BackwardsCompatibility
=== CONT  TestAccDataSourceAWSLB_basic
=== CONT  TestAccDataSourceAWSLB_BackwardsCompatibility
=== CONT  TestAccDataSourceAWSLB_outpost
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccDataSourceAWSLB_outpost (2.20s)
--- PASS: TestAccDataSourceAWSLB_BackwardsCompatibility (224.70s)
--- PASS: TestAccDataSourceAWSLB_basic (234.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	239.327s
```

**Comment by ewbankkit** [comment]
@mbyrdziak Thanks for the contribution :tada: :clap:.
To get this merged more quickly I went ahead and pushed a couple of changes, most significantly using `keyvaluetags.ContainsAll` instead of `reflect` to do the filtering.

**Pull request merged**
