### PR TITLE
[New Resource]: aws_verifiedpermissions_policy_store

### PR DESCRIPTION
**Pull request by nolotz**
### Description

This merge request is an extension to our ongoing efforts to support Amazon's VerifiedPermissions service in the Terraform AWS provider. The aim here is to include the `aws_verifiedpermissions_policy_store` resource, which provides users with the ability to manage their VerifiedPermissions policy stores directly through Terraform.

This merge request includes:

- new terraform resource
- tests
- documentation
- generated files
- release note

### Relations

Relates #32198
Relates #32158

### Potential Terraform Configuration

```terraform
resource "aws_verifiedpermissions_policy_store" "test" {
	validation_settings {
		mode = ""
	}
	schema {
		cedar_json = ""
	}
}
```

### References

- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/verifiedpermissions
- https://aws.amazon.com/verified-permissions/

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccVerifiedPermissionsPolicyStore PKG=verifiedpermissions

TF_ACC=1 go test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20 -run='TestAccVerifiedPermissionsPolicyStore'  -timeout 180m
=== RUN   TestAccVerifiedPermissionsPolicyStore_basic
=== PAUSE TestAccVerifiedPermissionsPolicyStore_basic
=== RUN   TestAccVerifiedPermissionsPolicyStore_disappears
=== PAUSE TestAccVerifiedPermissionsPolicyStore_disappears
=== CONT  TestAccVerifiedPermissionsPolicyStore_basic
=== CONT  TestAccVerifiedPermissionsPolicyStore_disappears
--- PASS: TestAccVerifiedPermissionsPolicyStore_disappears (48.24s)
--- PASS: TestAccVerifiedPermissionsPolicyStore_basic (128.89s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions        132.299s
```

### CODE REVIEW

**Comment by Pigius** [comment]
I would like to somehow to help, but I have no much experience in Terraform 😓

**Comment by jonbrouse** [comment]
> Requires #32198

Looks like this jawn was merged. Wondering if there are any other blockers.

**Comment by mrkresnofatih** [comment]
Are there any updates on this? Is it waiting on this PR #32208 ?
Would love to know how close this is from being released. 

Thanks

**Comment by Pigius** [comment]
Any update on that @nolotz ? Maybe we can help?

**Review by ritikagarwal2209 — APPROVED** [review]

**Review by ritikagarwal2209 — APPROVED** [review]

**Review by piotrekpasciak — APPROVED** [review]

**Comment by luisordaz-ibotta** [comment]
hi everyone! 

it looks like the PR has been approved. Will this new resource be available at next release?

**Comment by luisordaz-ibotta** [comment]
> Any update on that @nolotz ? Maybe we can help?

+1

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS='-run=TestAccVerifiedPermissions' PKG=verifiedpermissions

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20  -run=TestAccVerifiedPermissions -timeout 360m
--- PASS: TestAccVerifiedPermissionsPolicyStoreDataSource_basic (12.09s)
--- PASS: TestAccVerifiedPermissionsPolicyStore_disappears (12.41s)
--- PASS: TestAccVerifiedPermissionsPolicyStore_basic (14.53s)
--- PASS: TestAccVerifiedPermissionsSchema_disappears (14.62s)
--- PASS: TestAccVerifiedPermissionsPolicyStore_update (18.17s)
--- PASS: TestAccVerifiedPermissionsSchema_basic (18.92s)
--- PASS: TestAccVerifiedPermissionsSchema_update (23.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions	27.059s
```

**Comment by johnsonaj** [comment]
@nolotz thank you for the contribution! 🎉

**Pull request merged**
