### PR TITLE
r/aws_ecs_service: add triggers attribute to force update in-place

### LINKED ISSUE #13931: force_new_deployment argument for aws_ecs_service resources doesn't "force new deployment on each apply"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

- provider.aws v2.66.0

### Affected Resource(s)

* aws_ecs_service

### Terraform Configuration Files

```hcl
resource "aws_ecs_service" "main" {
  name                               = var.service_name
  cluster                            = var.ecs_cluster_module_ecs_arn
  task_definition                    = aws_ecs_task_definition.main.arn
  desired_count                      = 1
  deployment_minimum_healthy_percent = 100
  deployment_maximum_percent         = 200
  force_new_deployment               = true
  scheduling_strategy                = "REPLICA"
  deployment_controller {
    type = "ECS"
  }
  capacity_provider_strategy {
    capacity_provider = "FARGATE"
    base              = 0
    weight            = 1
  }
  network_configuration {
    security_groups  = [aws_security_group.main.id]
    subnets          = var.service_subnet_ids
  }
  enable_ecs_managed_tags = true
  propagate_tags          = "TASK_DEFINITION"
  tags                    = var.tags
}
```

### Expected Behavior

Enabling the `force_new_deployment` option in aws_ecs_service should force service re-deployment on each `terraform apply`, even if there is no change in the resource configuration. In this way, even if you are in dev mode with always the same Docker tag for your container image (ex: "latest"), it will force ECS to pull again the Docker image.
From [AWS API documentation](https://docs.aws.amazon.com/goto/WebAPI/ecs-2014-11-13/UpdateService):
`forceNewDeployment: Whether to force a new deployment of the service. Deployments are not forced by default. You can use this option to trigger a new deployment with no service definition changes. For example, you can update a service's tasks to use a newer Docker image with the same image/tag combination (my_image:latest) or to roll Fargate tasks onto a newer platform version.`

### Actual Behavior

There is no difference with or without the `force_new_deployment` option enabled

### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

### PR DESCRIPTION
**Pull request by obataku**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13931 #13528

Output from acceptance testing:

TODO

### CODE REVIEW

**Comment by obataku** [comment]
would like some input regarding this approach to resolving the aforementioned issues and guidance with the PR process. thanks!

**Comment by obataku** [comment]
bump?

**Comment by tony-engineering** [comment]
+1

**Comment by YakDriver** [comment]
This makes perfect sense. At present, the `force_new_deployment` argument will only cause a new deployment _if_ there are also changes to the `capacity_provider_strategy`. If you want a new deployment without those changes, this is a solution used elsewhere.

**Review by YakDriver — APPROVED** [review]
LGTM 🎉 

```console
% make testacc TESTS=TestAccECSService_ PKG=ecs                          
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSService_'  -timeout 180m
--- PASS: TestAccECSService_PlacementStrategy_missing (7.03s)
--- PASS: TestAccECSService_DaemonSchedulingStrategy_basic (55.16s)
--- PASS: TestAccECSService_iamRole (71.14s)
--- PASS: TestAccECSService_DeploymentValues_minZeroMaxOneHundred (97.94s)
--- PASS: TestAccECSService_DeploymentControllerType_external (44.82s)
--- PASS: TestAccECSService_DeploymentValues_basic (104.16s)
--- PASS: TestAccECSService_deploymentCircuitBreaker (105.90s)
--- PASS: TestAccECSService_clusterName (106.01s)
--- PASS: TestAccECSService_PlacementConstraints_emptyExpression (106.14s)
--- PASS: TestAccECSService_forceNewDeployment (121.77s)
--- PASS: TestAccECSService_forceNewDeploymentTriggers (123.29s)
--- PASS: TestAccECSService_basic (125.27s)
--- PASS: TestAccECSService_renamedCluster (130.23s)
--- PASS: TestAccECSService_familyAndRevision (143.08s)
--- PASS: TestAccECSService_PlacementStrategy_basic (147.82s)
--- PASS: TestAccECSService_PlacementStrategy_unnormalized (81.46s)
--- PASS: TestAccECSService_LaunchTypeFargate_basic (193.95s)
--- PASS: TestAccECSService_LaunchTypeEC2_network (110.21s)
--- PASS: TestAccECSService_executeCommand (93.87s)
--- PASS: TestAccECSService_alb (248.66s)
--- PASS: TestAccECSService_multipleTargetGroups (249.23s)
--- PASS: TestAccECSService_loadBalancerChanges (252.00s)
--- PASS: TestAccECSService_CapacityProviderStrategy_forceNewDeployment (153.12s)
--- PASS: TestAccECSService_LaunchTypeFargate_updateWaitForSteadyState (175.60s)
--- PASS: TestAccECSService_Tags_managed (89.69s)
--- PASS: TestAccECSService_DaemonSchedulingStrategy_setDeploymentMinimum (34.52s)
--- PASS: TestAccECSService_LaunchTypeFargate_waitForSteadyState (157.43s)
--- PASS: TestAccECSService_disappears (189.93s)
--- PASS: TestAccECSService_healthCheckGracePeriodSeconds (291.13s)
--- PASS: TestAccECSService_Tags_propagate (111.49s)
--- PASS: TestAccECSService_CapacityProviderStrategy_basic (195.77s)
--- PASS: TestAccECSService_LaunchTypeFargate_platformVersion (172.75s)
--- PASS: TestAccECSService_basicImport (201.58s)
--- PASS: TestAccECSService_PlacementConstraints_basic (83.94s)
--- PASS: TestAccECSService_replicaSchedulingStrategy (77.56s)
--- PASS: TestAccECSService_Tags_basic (113.02s)
--- PASS: TestAccECSService_DeploymentControllerType_codeDeploy (274.41s)
--- PASS: TestAccECSService_ServiceRegistries_basic (161.40s)
--- PASS: TestAccECSService_ServiceRegistries_container (161.00s)
--- PASS: TestAccECSService_ServiceRegistries_changes (287.61s)
--- PASS: TestAccECSService_DeploymentControllerType_codeDeployUpdateDesiredCountAndHealthCheckGracePeriod (418.60s)
--- PASS: TestAccECSService_CapacityProviderStrategy_multiple (879.55s)
--- PASS: TestAccECSService_CapacityProviderStrategy_update (1007.88s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	1009.677s
```

**Pull request merged**
