### PR TITLE
Launch Template support for Autoscaling Group data source

### PR DESCRIPTION
**Pull request by afrazkhan**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
The data source `aws_autoscaling_group` should also provide information on the ASGs Launch Templates. This patch adds `launch_template_version` and `launch_template_name`.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccXXX -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       0.078s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.007s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.016s [no tests to run]
```

### CODE REVIEW

**Comment by gdavison** [comment]
Thanks for the PR, @afrazkhan. Can you re-run your acceptance tests using the command make testacc TESTARGS='-run=TestAccAWSAppautoscalingPolicyDataSource', please? The -run=TestAccXXX in the instructions is a placeholder, and the value of -run is a regex for the names of the tests to run.

For more information on -run and other test flags, you can check the documentation at https://tip.golang.org/cmd/go/#hdr-Testing_flags.

Please also add to the documentation that the data source will also output either Launch Configuration or Launch Template information.

**Comment by afrazkhan** [comment]
Haha, yeah sorry I just cut and pasted like a madman.

Here you go:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAppautoscalingPolicyDataSource -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       0.093s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.014s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.021s [no tests to run]
```

**Comment by afrazkhan** [comment]
Haha yeah sorry, I just cut and pasted like a madman.

Here you go:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAppautoscalingPolicyDataSource -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       0.093s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.014s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.021s [no tests to run]
```

Doesn't look like it ran any tests here either though. I did find `TestAccAwsAutoScalingGroupDataSource_basic` in there, so I also tried running with `TestAccAwsAutoScalingGroupDataSource_.*`, but same result.

**Comment by walterheck** [comment]
@gdavison is this okay now? The conflicts are they supposed to be solved by us or by one of the maintainers?

**Comment by afrazkhan** [comment]
I've resolved the conflicts, just in case that's up to me. Hope this gets some love soon! ;)

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by ewbankkit** [comment]
@afrazkhan Thanks for the contribution :tada: :clap:.
This support was added via #16297.

**Pull request closed without merging**
