### PR TITLE
ec2: Allow customizable timeouts for various resources and data sources

### LINKED ISSUE #11342: Add possibility to retry/delay/timeout on data sources
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

First of all, I was not sure if I needed to post this feature request here or in terraform core itself but as we are using AWS provider intensely in the first place and considering that this is also requiring changes in its corresponding code, I thought this was the best place to post this FR

Second, do not flame me right away as I know this is not really matching the "philosophical" way terraform and providers are supposed to work, but considering all others questions I have seen here and there concerning similar things I thought there is room/legitimity for this enhancement

Third, as I did look at the source code and more specifically [ aws/data_source_aws_instances.go](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/data_source_aws_instances.go), I think this could be done quite easily/effortlessly

OK so here is my concern: let's assume we are using Autoscaling group and need to specify a dedicated target group rule for each instance (like a monitoring agent, ...). This could be done via Lambda code plugged to autoscaling events of course or also within the HCL code using a workaround/hack with null_resources, local-exec, sleep and data sources but as far as what I read so far:

1. null_resources + local_exec + sleep are highly discouraged
2. if the sleep time you specify is too short, you need to write another identical section and this is very painful

### New or Affected Resource(s)

All data sources concerning dynamic resources

### Potential Terraform Configuration

```hcl
data "aws_instances" "asg_instances" {
  instance_state_names = ["running", "pending"]

  filter = {
    name   = "instance.group-id"
    values = ["${aws_security_group.cluster.id}"]
  }

  poll = {
    delay = 20
    interval = 10
    retry_count = 10
    timeout = 60
  }
}
```

### References

* [#3128](https://github.com/terraform-providers/terraform-provider-aws/issues/3128)
* [#10715](https://github.com/terraform-providers/terraform-provider-aws/issues/10715)
* [#10769](https://github.com/terraform-providers/terraform-provider-aws/issues/10769)

### LINKED ISSUE #15921: aws_s3_bucket timeouts block support (deletion)
### Description

Terraform can not delete s3 bucket if it contains files (force_destroy Default:false) and it's absolutely ok.

But "apply" phase retry deletion infinitely

```
module.alb.aws_s3_bucket.xxx[0]: Still destroying... [id=xxx, 1h58m41s elapsed]
module.alb.aws_s3_bucket.xxx[0]: Still destroying... [id=xxx, 1h58m51s elapsed]
module.alb.aws_s3_bucket.xxx[0]: Still destroying... [id=xxx, 1h59m1s elapsed]
module.alb.aws_s3_bucket.xxx[0]: Still destroying... [id=xxx, 1h59m11s elapsed]
...
```

in our case Bitbucket CI has 2 hour max build time, after that time Terraform forcely stopped - part of applied stated was lost :(  

```
resource "aws_s3_bucket" "s3_bucket" {
  ...
  timeouts {
    create = "60m"
    delete = "60m"
    update = "60m"
  }
}
```

>> 

```
Error: Unsupported block type
 in resource "aws_s3_bucket" "s3_bucket":
  92:   timeouts {
Blocks of type "timeouts" are not expected here.
```

not supported by "aws_s3_bucket"

### New or Affected Resource(s)

* aws_s3_bucket

### References

- https://www.terraform.io/docs/configuration/resources.html#operation-timeouts

### LINKED ISSUE #16500: aws_internet_gateway doesn't support timeouts block
_This issue was originally opened by @Zogoo as hashicorp/terraform#27060. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    
### Terraform Version
```
terraform 12.0.6
```

### Error Output
15 minutes are not enough to get destroyed. When I try destroy 2nd time it was get destroyed.
```
Error: Error waiting for internet gateway (igw-03*********3) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)
Error: timeout while waiting for state to become 'INACTIVE' (last state: 'DRAINING', timeout: 10m0s)
```

### Expected Behavior
timeouts block should support and able to extend destroy wait time.

```
terraform destroy
```

### Actual Behavior
```
terraform plan
Error: Unsupported block type
  on ../modules/vpc/main.tf line 23, in resource "aws_internet_gateway" "ecs_ig":
  23:   timeouts {
Blocks of type "timeouts" are not expected here.
```

### Steps to Reproduce
1. Create VPC with internet gateway
2. Destroy them

### LINKED ISSUE #26026: Ability to add retries on data "aws_lb"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform is rarely the only system/tool that we use for managing infrastructure and when multiple systems are running independently it can be good to link their processes together. I would like to suggest that aws_lb data resources can have an optional retry period to allow the Terraform apply to "wait" for a resource that is being provisioned by another tool/process.

For my use-case, I am attempting to coordinate the creation of the Route53 record for a Load Balancer that is created by an EKS Service. The process for the deployment of the Ingress controller into EKS (and therefore creation of the Load Balancer) is loosely triggered by the Terraform project, but it is difficult to know when exactly the Load Balancer will be ready. Once the Load Balancer is ready it is easy to configure the Route53 record using the `data "aws_lb"` resource.

There can be timeouts for resources, but it seems not yet for data resources.

Using something like `time_sleep` is inefficient since it waits the total time every apply.

I would like to add the ability to do retries  (via a timeout) on the aws_lb data resource to wait until it is has been provisioned by the parallel process.

### New or Affected Resource(s)

* aws_lb (data resource)

### Potential Terraform Configuration

```hcl
data "aws_lb" "ingress_load_balancer" {
  tags = {
    "service.k8s.aws/resource" = "LoadBalancer"
    "service.k8s.aws/stack"    = "ingress-nginx/ingress-nginx-controller"
    "elbv2.k8s.aws/cluster"    = "my-eks-cluster"
  }

  timeouts {
    read = "10m"
  }
}
```

Result: `Blocks of type "timeouts" are not expected here.`

### References

* https://www.terraform.io/plugin/sdkv2/resources/retries-and-customizable-timeouts
* https://www.terraform.io/language/resources/syntax#operation-timeouts
* https://registry.terraform.io/providers/hashicorp/time/latest/docs/resources/sleep

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #26026
Closes #11342
Closes #16500
Closes #15921

Output from acceptance testing:

```console
% make testacc TESTS=TestAccEC2InstanceDataSource_timeout PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstanceDataSource_timeout'  -timeout 180m
--- PASS: TestAccEC2InstanceDataSource_timeout (125.24s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	126.925s
% make testacc TESTS=TestAccEC2InstancesDataSource_timeout PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstancesDataSource_timeout'  -timeout 180m
--- PASS: TestAccEC2InstancesDataSource_timeout (122.64s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	124.032s
```

### CODE REVIEW

**Comment by jwfh** [comment]
Seeing issues with v4.25.0 provider with hanging plans and crashes, wondering if it could be related to this change. Reverting to v4.24.0 fixes the issues.


MicrosoftTeams-image (8)
MicrosoftTeams-image (9)

**Comment by Jpk518** [comment]
> Seeing issues with v4.25.0 provider with hanging plans and crashes, wondering if it could be related to this change. Reverting to v4.24.0 fixes the issues.
> 
> MicrosoftTeams-image (8) MicrosoftTeams-image (9)

We narrowed this down to be a specific issue with any data lookup performed on provider v4.25.0 with terraform v0.13.1. Other Terraform versions seem to be fine but this specific TF version panics with these new changes.

**Comment by ewbankkit** [comment]
@jwfh @Jpk518 Could you please raise a new Issue for this? Thanks.

**Comment by vavdoshka** [comment]
Hello @YakDriver @ewbankkit 

I'm trying to understand what this feature does, please help. Based on the description of the linked issues and what I understood, it now should allow to "wait" for the data resource to come up and fail it won't after 20 minutes (by default).
And so either my understanding is not correct, or it does not work as planned:


```hcl
terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "4.25.0"
    }
  }
}

provider "aws" {
  region = "us-east-1"
}


resource "aws_vpc" "this" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
    tags                 = {
        Name = "test"
    }
}

data "aws_vpc" "this" {
  filter {
    name   = "tag:Name"
    values = ["test"]
  }
}
```

```sh
➜  test git:(master) ✗ terraform --version
Terraform v1.2.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.25.0
➜  test git:(master) ✗ terraform plan     
data.aws_vpc.this: Reading...
╷
│ Error: no matching EC2 VPC found
│ 
│   with data.aws_vpc.this,
│   on main.tf line 23, in data "aws_vpc" "this":
│   23: data "aws_vpc" "this" {
│ 
```

**Pull request merged**
