### PR TITLE
F aws acm data source tags filter

### LINKED ISSUE #1918: Add tags as search criteria for aws_acm_certificate data source
We are currently attempting to add more domains to our certificate and need to rotate it out across our ALBs. However, the aws_acm_certificate data source functionally only accepts the domain for discovery.  Discovery with tags allows matching on similar domain certificates through a method that is commonly accepted with other data sources.

There is another issue that is similar to this: https://github.com/terraform-providers/terraform-provider-aws/issues/546
However, tagged resources are immune to users creating new certificates and could allow for more than two ACM resources with the same name at once.

### PR DESCRIPTION
**Pull request by rromic**
### Description
This PR adds option to filter acm certificates by tags.
Now domain attribute is not required any more but either domain or tags or both needs to be provided to get certificates.

Added acceptance tests to cover new cases and adjusted previous ones to ensure previous logic remains the same.

### Relations

Closes #1918 

### Output from Acceptance Testing

```
export AWS_DEFAULT_REGION=eu-central-1
export ACM_CERTIFICATE_SINGLE_ISSUED_DOMAIN=test.single.domain
export ACM_CERTIFICATE_MULTIPLE_ISSUED_DOMAIN=test.multi.domain
export ACM_CERTIFICATE_ROOT_DOMAIN=domain
export ACM_CERTIFICATE_SINGLE_ISSUED_TAG_NAME=Name
export ACM_CERTIFICATE_SINGLE_ISSUED_TAG_VALUE=test.single.domain
export ACM_CERTIFICATE_MULTIPLE_ISSUED_TAG_NAME=Name
export ACM_CERTIFICATE_MULTIPLE_ISSUED_TAG_VALUE=test.multi.domain
export ACM_CERTIFICATE_TYPE=IMPORTED
make testacc TESTS=TestAccACMCertificateDataSource PKG=acm  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/acm/... -v -count 1 -parallel 20 -run='TestAccACMCertificateDataSource'  -timeout 180m
=== RUN   TestAccACMCertificateDataSource_singleIssued
=== PAUSE TestAccACMCertificateDataSource_singleIssued
=== RUN   TestAccACMCertificateDataSource_multipleIssued
=== PAUSE TestAccACMCertificateDataSource_multipleIssued
=== RUN   TestAccACMCertificateDataSource_noMatchReturnsError
=== PAUSE TestAccACMCertificateDataSource_noMatchReturnsError
=== RUN   TestAccACMCertificateDataSource_keyTypes
=== PAUSE TestAccACMCertificateDataSource_keyTypes
=== CONT  TestAccACMCertificateDataSource_singleIssued
=== CONT  TestAccACMCertificateDataSource_noMatchReturnsError
=== CONT  TestAccACMCertificateDataSource_multipleIssued
=== CONT  TestAccACMCertificateDataSource_keyTypes
--- PASS: TestAccACMCertificateDataSource_noMatchReturnsError (27.84s)
--- PASS: TestAccACMCertificateDataSource_keyTypes (30.41s)
--- PASS: TestAccACMCertificateDataSource_multipleIssued (119.36s)
--- PASS: TestAccACMCertificateDataSource_singleIssued (199.69s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/acm        203.077s

...
```

### CODE REVIEW

**Comment by rromic** [comment]
@ewbankkit any plans for this PR? :)

**Comment by ewbankkit** [comment]
@rromic Yes, I'll take a look and migrate to _transparent tagging_. Thanks.

**Comment by vishwa-trulioo** [comment]
Can we please get this merged?

**Comment by rromic** [comment]
> @rromic Yes, I'll take a look and migrate to _transparent tagging_. Thanks.

@ewbankkit can I help with _transparent tagging_? Can you please provide some example so I can try to put it in to get this PR to be merged faster?

**Comment by vishwa-trulioo** [comment]
Any update? Thanks.

**Comment by rromic** [comment]
> Any update? Thanks.

@vishwa-trulioo nothing from my side. I have resolved all conflicts and made linter fixes that got in with main branch.

**Comment by vishwa-trulioo** [comment]
@ewbankkit if the work is good, are you able to get this into the next release? Thank you in advance.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccACMCertificateDataSource_' PKG=acm ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/acm/... -v -count 1 -parallel 3  -run=TestAccACMCertificateDataSource_ -timeout 360m
=== RUN   TestAccACMCertificateDataSource_tags
=== PAUSE TestAccACMCertificateDataSource_tags
=== RUN   TestAccACMCertificateDataSource_byDomain
=== PAUSE TestAccACMCertificateDataSource_byDomain
=== RUN   TestAccACMCertificateDataSource_byDomainNoMatch
=== PAUSE TestAccACMCertificateDataSource_byDomainNoMatch
=== RUN   TestAccACMCertificateDataSource_byDomainMultiple
=== PAUSE TestAccACMCertificateDataSource_byDomainMultiple
=== RUN   TestAccACMCertificateDataSource_byDomainAndTags
=== PAUSE TestAccACMCertificateDataSource_byDomainAndTags
=== RUN   TestAccACMCertificateDataSource_byDomainAndStatuses
=== PAUSE TestAccACMCertificateDataSource_byDomainAndStatuses
=== RUN   TestAccACMCertificateDataSource_byDomainAndKeyTypes
=== PAUSE TestAccACMCertificateDataSource_byDomainAndKeyTypes
=== RUN   TestAccACMCertificateDataSource_byDomainAndTypes
=== PAUSE TestAccACMCertificateDataSource_byDomainAndTypes
=== RUN   TestAccACMCertificateDataSource_byDomainAndTypesNoMatch
=== PAUSE TestAccACMCertificateDataSource_byDomainAndTypesNoMatch
=== RUN   TestAccACMCertificateDataSource_byDomainAndKeyTypesMostRecent
=== PAUSE TestAccACMCertificateDataSource_byDomainAndKeyTypesMostRecent
=== RUN   TestAccACMCertificateDataSource_byTags
=== PAUSE TestAccACMCertificateDataSource_byTags
=== RUN   TestAccACMCertificateDataSource_byTagsNoMatch
=== PAUSE TestAccACMCertificateDataSource_byTagsNoMatch
=== RUN   TestAccACMCertificateDataSource_byTagsAndKeyTypes
=== PAUSE TestAccACMCertificateDataSource_byTagsAndKeyTypes
=== CONT  TestAccACMCertificateDataSource_tags
=== CONT  TestAccACMCertificateDataSource_byDomainAndTypes
=== CONT  TestAccACMCertificateDataSource_byDomainAndTags
--- PASS: TestAccACMCertificateDataSource_byDomainAndTags (14.45s)
=== CONT  TestAccACMCertificateDataSource_byDomainNoMatch
--- PASS: TestAccACMCertificateDataSource_tags (14.98s)
=== CONT  TestAccACMCertificateDataSource_byDomainMultiple
--- PASS: TestAccACMCertificateDataSource_byDomainAndTypes (19.90s)
=== CONT  TestAccACMCertificateDataSource_byDomain
--- PASS: TestAccACMCertificateDataSource_byDomainMultiple (9.12s)
=== CONT  TestAccACMCertificateDataSource_byDomainAndKeyTypes
--- PASS: TestAccACMCertificateDataSource_byDomain (13.26s)
=== CONT  TestAccACMCertificateDataSource_byTags
--- PASS: TestAccACMCertificateDataSource_byDomainAndKeyTypes (13.81s)
=== CONT  TestAccACMCertificateDataSource_byTagsAndKeyTypes
--- PASS: TestAccACMCertificateDataSource_byTags (14.64s)
=== CONT  TestAccACMCertificateDataSource_byTagsNoMatch
--- PASS: TestAccACMCertificateDataSource_byTagsNoMatch (7.56s)
=== CONT  TestAccACMCertificateDataSource_byDomainAndKeyTypesMostRecent
--- PASS: TestAccACMCertificateDataSource_byTagsAndKeyTypes (16.01s)
=== CONT  TestAccACMCertificateDataSource_byDomainAndTypesNoMatch
--- PASS: TestAccACMCertificateDataSource_byDomainNoMatch (66.26s)
=== CONT  TestAccACMCertificateDataSource_byDomainAndStatuses
--- PASS: TestAccACMCertificateDataSource_byDomainAndStatuses (14.64s)
--- PASS: TestAccACMCertificateDataSource_byDomainAndTypesNoMatch (66.33s)
--- PASS: TestAccACMCertificateDataSource_byDomainAndKeyTypesMostRecent (200.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/acm	263.625s
```

**Comment by ewbankkit** [comment]
@rromic Thanks for the contribution :tada: :clap:.

**Comment by rromic** [comment]
> @rromic Thanks for the contribution 🎉 👏.

awesome! Thank you for all the support!

**Pull request merged**
