### PR TITLE
Allow "/" in aws_glue_crawler name

### LINKED ISSUE #19159: aws_glue_crawler: name reported as invalid against regex when AWS accepts the name
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

* Terraform v0.15.0
* on windows_amd64
* provider registry.terraform.io/hashicorp/aws v3.35.0

### Affected Resource(s)

* aws_glue_crawler

### Terraform Configuration Files

This has to do with the import process and the act of _not_ writing some HCL, so I won't include the HCL here, but am happy to paste what's relevant with a little guidance.

### Steps to reproduce

* Create a crawler manually within AWS with a name that contains `/` characters, e.g. `Crawler-business-solutions-data/s3path/contact/rawdata/`
* Create HCL with the intent of importing the resource and working backward, e.g. 

```hcl
resource "aws_glue_crawler" "raw_data_crawler" {
  database_name = aws_glue_catalog_database.aws_glue_catalog_database.name
  name          = "Crawler-business-solutions-data/s3path/contact/rawdata/"
  role = "TBD"
}
```

NOTE: the import will complete successfully

* Run `terraform plan` with the appropriate variables

### Expected Behavior

Expect to see the drift between our defined configuration and the current resource's state so that I can work backward.

### Actual Behavior

I see an error: 

> expected value of name to match regular expression "[a-zA-Z0-9-_$#]+$", got Crawler-business-solutions-data/s3path/contact/rawdata/

### Important Factoids

* I am still new enough to AWS and Terraform that I very much accept this may be an issue of my understanding rather than a bug. If this is a question of my mistaken understanding, I am happy to bring my inquiry to the forum for more general resolution.
* It appears that AWS has possibly relaxed its rules around names and the terraform provider may need to follow suit.

### PR DESCRIPTION
**Pull request by SeanKilleen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19159

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
LGTM

```
--- PASS: TestAccAWSGlueCrawler_Role_Name_Path (62.24s)
--- PASS: TestAccAWSGlueCrawler_disappears (63.26s)
--- PASS: TestAccAWSGlueCrawler_Role_ARN_NoPath (66.88s)
--- PASS: TestAccAWSGlueCrawler_Role_ARN_Path (67.30s)
--- PASS: TestAccAWSGlueCrawler_SchemaChangePolicy (102.53s)
--- PASS: TestAccAWSGlueCrawler_DynamodbTarget (102.94s)
--- PASS: TestAccAWSGlueCrawler_RemoveTablePrefix (104.40s)
--- PASS: TestAccAWSGlueCrawler_Description (104.94s)
--- PASS: TestAccAWSGlueCrawler_TablePrefix (105.50s)
--- PASS: TestAccAWSGlueCrawler_mongoDBTarget (106.41s)
--- PASS: TestAccAWSGlueCrawler_SecurityConfiguration (106.94s)
--- PASS: TestAccAWSGlueCrawler_Configuration (107.70s)
--- PASS: TestAccAWSGlueCrawler_Classifiers (131.46s)
--- PASS: TestAccAWSGlueCrawler_lineageConfig (137.58s)
--- PASS: TestAccAWSGlueCrawler_S3Target_Multiple (137.81s)
--- PASS: TestAccAWSGlueCrawler_Tags (143.57s)
--- PASS: TestAccAWSGlueCrawler_Schedule (144.32s)
--- PASS: TestAccAWSGlueCrawler_recrawlPolicy (145.38s)
--- PASS: TestAccAWSGlueCrawler_S3Target_ConnectionName (88.33s)
--- PASS: TestAccAWSGlueCrawler_S3Target (97.16s)
--- PASS: TestAccAWSGlueCrawler_CatalogTarget (159.95s)
--- PASS: TestAccAWSGlueCrawler_DynamodbTarget_scanRate (122.54s)
--- PASS: TestAccAWSGlueCrawler_mongoDBTarget_scan_all (129.35s)
--- PASS: TestAccAWSGlueCrawler_JdbcTarget (93.15s)
--- PASS: TestAccAWSGlueCrawler_S3Target_Exclusions (89.41s)
--- PASS: TestAccAWSGlueCrawler_JdbcTarget_Exclusions (90.79s)
--- PASS: TestAccAWSGlueCrawler_DynamodbTarget_scanAll (123.02s)
--- PASS: TestAccAWSGlueCrawler_mongoDBTarget_multiple (124.25s)
--- PASS: TestAccAWSGlueCrawler_JdbcTarget_Multiple (125.44s)
--- PASS: TestAccAWSGlueCrawler_CatalogTarget_Multiple (236.85s)
```

**Review by DrFaust92 — APPROVED** [review]

**Comment by SeanKilleen** [comment]
@DrFaust92 Thanks for the speedy review! 

Do you have any insight on how long it typically takes from PR approval to provider release? Any amount of time is fine, but I'd like to set my team's expectations for when this change will become available.

**Comment by SeanKilleen** [comment]
Hi @ewbankkit, not sure if this is the intended behavior, but your force push of my PR branch now seems to have GitHub thinking that 3,000+ files were modified.

**Comment by ewbankkit** [comment]
@SeanKilleen I see what the problem is - You need to change the PR to be against `main`, not `master` (the default branch changed a while back).
I rebased onto the latest `main` and those 3000+ files are all new on the old `master` 😄.

**Comment by SeanKilleen** [comment]
Hi @ewbankkit I updated the PR. Odd because I did it by editing the file on GitHub and creating the PR which I assume would have gone against the default branch by, well, default. 😆 Not sure why it wound up on the old name.

You may need to add your changelog commit one more time -- apologies!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Pull request merged**
