### PR TITLE
[#19966] - aws_elasticsearch_domain_saml_options subject_key default differs from AWS

### LINKED ISSUE #19966: aws_elasticsearch_domain_saml_options subject_key default differs from AWS
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```bash
Terraform v1.0.0
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.47.0
+ provider registry.terraform.io/hashicorp/azuread v1.5.1
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0
+ provider registry.terraform.io/phillbaker/elasticsearch v1.5.7
```

### Affected Resource(s)

* aws_elasticsearch_domain_saml_options (new in 3.47.0)

### Terraform Configuration Files

Broken configuration:
```hcl
resource "aws_elasticsearch_domain_saml_options" "main" {
  domain_name = module.elasticsearch.domain_name

  saml_options {
    enabled = true
    roles_key = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"

    idp {
      entity_id = local.saml_entity_id
      metadata_content = chomp(local.config.saml_metadata)
    }
  }
}
```

Working configuration:
```hcl
resource "aws_elasticsearch_domain_saml_options" "main" {
  domain_name = module.elasticsearch.domain_name

  saml_options {
    enabled = true
    roles_key = "http://schemas.microsoft.com/ws/2008/06/identity/claims/role"
    subject_key = ""

    idp {
      entity_id = local.saml_entity_id
      metadata_content = chomp(local.config.saml_metadata)
    }
  }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The new resource sets `NameID` as the [default value](https://github.com/hashicorp/terraform-provider-aws/pull/19497/files#diff-d0a4b19035d79de10be50979509d0dd73c24d2edd958c42f9b35f853b06f7bebR89) which at a glance appears to match the AWS configuration, but is actually different. Here's what AWS says:
image

The difference is the usage of the words `element` and `attribute`.

### Actual Behavior

This module's default behavior is to look for an attribute named `NameID` rather than letting AWS default to looking at an `element` called `NameID`. This caused our Kibana to 500 consistently after the SAML response because it was looking for an attribute that didnt exist.

### Steps to Reproduce

1. Make an AWS ES Cluster
2. Grab some SAML federation data from a SAML provider that uses the NameID element to identify users such as AzureAD
3. Attempt to configure SAML using `aws_elasticsearch_domain_saml_options` and note how the default behavior of the resource results in 500s, but inputting the same exact data on AWS directly results in successful attempts
4. Set `aws_elasticsearch_domain_saml_options::saml_options.subject_key = ""` and see that the terraform resource now allows successful SAML auth

### Important Factoids

Nothing important to know

### References

None that haven't been cited already.

### PR DESCRIPTION
**Pull request by jc-asdf**
Fixed by making the subject_key's default value be `""` - an empty string - to match the default on the AWS side.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19966

Output from acceptance testing:

```
 AWS_REGION=us-east-1 AWS_PROFILE=sandbox make testacc TESTARGS='-run=TestAccAWSElasticSearchDomainSAMLOptions'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticSearchDomainSAMLOptions -timeout 180m
=== RUN   TestAccAWSElasticSearchDomainSAMLOptions_basic
=== PAUSE TestAccAWSElasticSearchDomainSAMLOptions_basic
=== RUN   TestAccAWSElasticSearchDomainSAMLOptions_disappears
=== PAUSE TestAccAWSElasticSearchDomainSAMLOptions_disappears
=== RUN   TestAccAWSElasticSearchDomainSAMLOptions_disappears_Domain
=== PAUSE TestAccAWSElasticSearchDomainSAMLOptions_disappears_Domain
=== RUN   TestAccAWSElasticSearchDomainSAMLOptions_Update
=== PAUSE TestAccAWSElasticSearchDomainSAMLOptions_Update
=== RUN   TestAccAWSElasticSearchDomainSAMLOptions_Disabled
=== PAUSE TestAccAWSElasticSearchDomainSAMLOptions_Disabled
=== CONT  TestAccAWSElasticSearchDomainSAMLOptions_basic
=== CONT  TestAccAWSElasticSearchDomainSAMLOptions_Update
=== CONT  TestAccAWSElasticSearchDomainSAMLOptions_Disabled
=== CONT  TestAccAWSElasticSearchDomainSAMLOptions_disappears_Domain
=== CONT  TestAccAWSElasticSearchDomainSAMLOptions_disappears
--- PASS: TestAccAWSElasticSearchDomainSAMLOptions_disappears_Domain (1263.67s)
--- PASS: TestAccAWSElasticSearchDomainSAMLOptions_basic (1323.29s)
--- PASS: TestAccAWSElasticSearchDomainSAMLOptions_Update (1380.93s)
--- PASS: TestAccAWSElasticSearchDomainSAMLOptions_disappears (1580.45s)
--- PASS: TestAccAWSElasticSearchDomainSAMLOptions_Disabled (1713.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1716.013s
```

### CODE REVIEW

**Comment by jc-asdf** [comment]
To verify the AWS-side default, I created a working Elasticsearch cluster via the AWS UI, enabling SAML and testing it with Okta.

I verified that the SAML assertion had a `NameID` element in the `Subject` section - it did. I used the CLI to do a `describe`:

```
aws es describe-elasticsearch-domain --domain-name=audit-app-staging --profile=sandbox --region=us-east-1

{
    "DomainStatus": {
        "DomainId": "XXXXXXXX/terraform-test-saml",
        "DomainName": "terraform-test-saml",
        "ARN": "arn:aws:es:us-east-1:XXXXXXXX:domain/terraform-test-saml",
        "Created": true,
        "Deleted": false,

... <cut out the bulk> ...

        "AdvancedSecurityOptions": {
            "Enabled": true,
            "InternalUserDatabaseEnabled": false,
            "SAMLOptions": {
                "Enabled": true,
                "Idp": {
                    ... <cut out the XML idP metadata> ...
                },
                "SubjectKey": "",
                "RolesKey": "roles",
                "SessionTimeoutMinutes": 60
            }
        },
        "AutoTuneOptions": {
            "State": "ENABLE_IN_PROGRESS"
        }
    }
}

From here I could see that `SubjectKey` was in fact an empty string.  I replicated the original bug by setting the SubjectKey to `NameID` (which, incidentally, can NOT be done in the AWS UI - it says that this is an invalid option; and so one must use the API to set it to this value). Once it was changed, I received a `500` error from Kibana; unfortunately I could not get useful error logs from it. The errors went away once this was changed back to a `""`, whether in the UI or via the API.

**Comment by Jacendb** [comment]
I'm seeing the same issue when creating a new ES domain. Does subject_key need a default value? In the AWS console I currently have to remove `NameID` and leave the `Subject key` box empty for SSO/Okta to work. I'm wondering if not setting anything in `default` will leave the field untouched/undefined on the AWS side so it works.

**Comment by YakDriver** [comment]
I agree that normally, changing the default value is a breaking change. However, in this case, the old and new default values are equivalent. Thus, I don't see this as a breaking change.

**Review by YakDriver — APPROVED** [review]
Thank you 🎉 

```console
% make testacc TESTS=TestAccElasticsearchDomainSAMLOptions PKG=elasticsearch
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elasticsearch/... -v -count 1 -parallel 20 -run='TestAccElasticsearchDomainSAMLOptions'  -timeout 180m
--- PASS: TestAccElasticsearchDomainSAMLOptions_disappears (1178.57s)
--- PASS: TestAccElasticsearchDomainSAMLOptions_Update (1202.84s)
--- PASS: TestAccElasticsearchDomainSAMLOptions_disappears_Domain (1268.98s)
--- PASS: TestAccElasticsearchDomainSAMLOptions_Disabled (1373.32s)
--- PASS: TestAccElasticsearchDomainSAMLOptions_basic (1450.98s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch	1452.310s
```

**Pull request merged**
