### PR TITLE
Add Multi-AZ support for RDS clusters

### LINKED ISSUE #23475: aws_rds_cluster add new multi-AZ cluster deployment options
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add the ability to provision Multi-AZ cluster deployment MySQL or PostgreSQL instances.

It looks like aws-sdk-go added this in `1.43.9`.

```
To create a Multi-AZ DB cluster by using the RDS API, call the [CreateDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) operation. Specify the DBClusterIdentifier. For the Engine parameter, specify either mysql or postgresql.
```

### New or Affected Resource(s)

aws_rds_cluster

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster" "asdf" {
  # ....
  engine = "postgres"
  # ....
}
```

### References
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html
* https://aws.amazon.com/blogs/aws/amazon-rds-multi-az-db-cluster/
* https://github.com/aws/aws-sdk-go/commit/4adef3588ff234c55aa0afb9cb33772660906758

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23475

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=rds

...
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Having some issues with existing and new acceptance tests not being ran properly, I believe that @YakDriver is fixing a similiar issue under https://github.com/hashicorp/terraform-provider-aws/pull/23560

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.
Could you please rebase now that https://github.com/hashicorp/terraform-provider-aws/pull/23560 has been merged.

**Comment by YakDriver** [comment]
@bschaatsbergen Thank you for your work on RDS! It's one of the most used services but has a lot of code that needs some love. My apologies for the conflicts.

Unfortunately, I did not fix all of the acceptance tests. There are some long standing failures that I not get around to. I already included more than I should in my PR. As far as I know, these 7 are broken and have been for a while 🙀 .

--- FAIL: TestAccRDSCluster_s3Restore (1518.86s)
--- FAIL: TestAccRDSInstance_DBSubnetGroupName_ramShared (35.16s)
--- FAIL: TestAccRDSInstance_S3Import_basic (18.75s)
--- FAIL: TestAccRDSInstance_S3Import_nameDeprecated (18.25s)
--- FAIL: TestAccRDSInstance_S3Import_nameGenerated (19.91s)
--- FAIL: TestAccRDSInstance_S3Import_namePrefix (19.18s)
--- FAIL: TestAccRDSInstance_SnapshotIdentifier_dbSubnetGroupNameRAMShared (512.42s)

**Comment by bschaatsbergen** [comment]
Rebasing the PR turned it into a mess, I'll see if I can recreate it. My bad. 

See: #23684 23684

**Pull request closed without merging**
