### PR TITLE
[Docs]: Code Example for aws_sesv2_email_identity (BYODKIM) is misleading

### PR DESCRIPTION
**Pull request by Asteao**
https://github.com/hashicorp/terraform-provider-aws/issues/29729

### CODE REVIEW

**Review by kamilturek — APPROVED** [review]
LGTM! That's an important note.

**Comment by Asteao** [comment]
@kamilturek The note helps, but the code example is still misleading. Do you have any suggestions on how this could be made more clear?
The only thing that comes to mind is using a local with the expected value and calling that variable for the attribute.

**Comment by kamilturek** [comment]
@Asteao I think what you suggested will be fine and very explanatory. Another idea would be to use a variable without explicitly specifying its value. It's simpler but seems to be less clear.

```terraform
resource "aws_sesv2_email_identity" "example" {
  email_identity = "example.com"

  dkim_signing_attributes {
    domain_signing_private_key = base64encode(var.private_key)
    domain_signing_selector    = "example"
  }
}
```

**Comment by Asteao** [comment]
@kamilturek I have update the example with an example text, since none of the other attributes reference variables it seems strange to use a var for this attribute. If you're okay with this change I can merge it after your approval.

**Comment by jar-b** [comment]
Thanks for your contribution, @Asteao!

**Pull request merged**
