### PR TITLE
Secrets Manager Secret Replication

### LINKED ISSUE #17943: Secrets Manager: Support Secret Replication
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has launched support for replicating secrets between regions. We should add the ability to configure this in Terraform

### New or Affected Resource(s)

* aws_secretsmanager_secret

### References

* https://aws.amazon.com/blogs/security/how-to-replicate-secrets-aws-secrets-manager-multiple-regions/
* https://aws.amazon.com/about-aws/whats-new/2021/03/aws-secrets-manager-provides-supp[…]icate-secrets-in-aws-secrets-manager-to-multiple-aws-regions/
* https://docs.aws.amazon.com/secretsmanager/latest/userguide/create-manage-multi-region-secrets.html

### PR DESCRIPTION
**Pull request by TomTucka**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17943

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by generalov** [comment]
Just a naming thing: [aws_dynamodb_table](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/dynamodb_table) has a similar `replica` option:
```hcl
replica {
    region_name = "us-east-2"
}
```

**Comment by shubydo** [comment]
Hi @TomTucka, I'm working on a team that is looking forward to utilizing this feature and was wondering if there have been any updates on this?

Quick question: If our team wanted to replicate a secret in another region (ex. `us-east-2`), but then needed to run a `terraform destroy`, would this teardown both the secret created in the primary region and the replicated regions(s)?

**Comment by kgosietsileM** [comment]
+1

**Comment by YakDriver** [comment]
@TomTucka Is this something that you are interested in continuing?

**Comment by TomTucka** [comment]
@YakDriver I'm super busy with work right now and won't get round to this for a few more weeks. Happy for someone else to take what I've done and finish it off 😄

**Comment by YakDriver** [comment]
@TomTucka Thanks for your work on this! 

I moved your commits over to another branch. You still get credit for them. Because your branch was named "main," it was easier to just cherry pick them to a new branch.

**Pull request closed without merging**
