### PR TITLE
New Resource: ElastiCache Redis - User Group

### PR DESCRIPTION
**Pull request by drarnold**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates to https://github.com/hashicorp/terraform-provider-aws/issues/16327
Blocked by https://github.com/hashicorp/terraform-provider-aws/pull/16629

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_elasticache_user_group: add elasticache_user_group resource [GH-16504]
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSElasticacheUserGroup_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheUserGroup_ -timeout 120m
=== RUN   TestAccAWSElasticacheUserGroup_basic
=== PAUSE TestAccAWSElasticacheUserGroup_basic
=== RUN   TestAccAWSElasticacheUserGroup_addUserId
=== PAUSE TestAccAWSElasticacheUserGroup_addUserId
=== RUN   TestAccAWSElasticacheUserGroup_changeUserId
=== PAUSE TestAccAWSElasticacheUserGroup_changeUserId
=== RUN   TestAccAWSElasticacheUserGroup_removeUserId
=== PAUSE TestAccAWSElasticacheUserGroup_removeUserId
=== CONT  TestAccAWSElasticacheUserGroup_basic
=== CONT  TestAccAWSElasticacheUserGroup_removeUserId
=== CONT  TestAccAWSElasticacheUserGroup_addUserId
=== CONT  TestAccAWSElasticacheUserGroup_changeUserId
--- PASS: TestAccAWSElasticacheUserGroup_basic (107.68s)
=== CONT  TestAccAWSElasticacheUserGroup_changeUserId
    resource_aws_elasticache_user_group_test.go:83: Step 2/2 error: After applying this test step and performing a `terraform refresh`, the plan was not empty.
        stdout


        An execution plan has been generated and is shown below.
        Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_elasticache_user_group.test-user-id-change will be updated in-place
          ~ resource "aws_elasticache_user_group" "test-user-id-change" {
                engine        = "redis"
                id            = "a-user-group-test-tf-change-user-id"
                user_group_id = "a-user-group-test-tf-change-user-id"
              ~ user_ids      = [
                    "default",
                    "test-user-1",
                  - "test-user-2",
                    "test-user-3",
                ]
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- PASS: TestAccAWSElasticacheUserGroup_removeUserId (171.22s)
--- FAIL: TestAccAWSElasticacheUserGroup_changeUserId (181.52s)
--- PASS: TestAccAWSElasticacheUserGroup_addUserId (202.25s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	203.946s
FAIL
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by drarnold** [comment]
Going to open a new branch with less confusion

**Comment by drarnold** [comment]
This is still a work in progress FYI

**Comment by ajendrex** [comment]
Hello @drarnold,

you changed status to ready for review, but the title still says WIP...

Also, I'm wondering if you are planning to implement the same for users (I understand this only allows to manage user groups)

Thanks for your work!

Hector.

**Comment by drarnold** [comment]
Hey Hector,

Thank you for following up!  So while I have been developing this change, I was running into issues with being able to import user groups as a resource.  But this is my first Pull Request, so I wanted someone to take a first look at it and see if it is up to par with being able to get merged soon once I am able to figure out how to get importing the resource working.

I will remove the WIP so it removes some of the confusion.

Thanks

Drew

**Comment by stevehipwell** [comment]
Any progress on this?

**Comment by drarnold** [comment]
Sorry for the radio silence with this project. I will start working on it again during the evenings and should try to get something out shortly.

**Review by bill-rich — APPROVED** [review]
LGTM
```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheUserGroup_ -timeout 180m
=== RUN   TestAccAWSElasticacheUserGroup_basic
=== PAUSE TestAccAWSElasticacheUserGroup_basic
=== RUN   TestAccAWSElasticacheUserGroup_update
=== PAUSE TestAccAWSElasticacheUserGroup_update
=== RUN   TestAccAWSElasticacheUserGroup_tags
=== PAUSE TestAccAWSElasticacheUserGroup_tags
=== RUN   TestAccAWSElasticacheUserGroup_disappears
=== PAUSE TestAccAWSElasticacheUserGroup_disappears
=== CONT  TestAccAWSElasticacheUserGroup_basic
=== CONT  TestAccAWSElasticacheUserGroup_disappears
=== CONT  TestAccAWSElasticacheUserGroup_tags
=== CONT  TestAccAWSElasticacheUserGroup_update
--- PASS: TestAccAWSElasticacheUserGroup_basic (357.56s)
--- PASS: TestAccAWSElasticacheUserGroup_tags (363.33s)
--- PASS: TestAccAWSElasticacheUserGroup_disappears (364.78s)
--- PASS: TestAccAWSElasticacheUserGroup_update (671.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	671.822s
```

**Pull request merged**
