### PR TITLE
New Resource: aws_cloudfront_vpc_origin

### LINKED ISSUE #40234: [Enhancement]: Support for CloudFront VPC Origins
### Description

Announcement: https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-cloudfront-vpc-origins/
Docs: https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/private-content-vpc-origins.html

This will need a new resource/data source as well as an update to the CF distribution resource/data source.

### Affected Resource(s) and/or Data Source(s)

* aws_cloudfront_distribution

### Potential Terraform Configuration

_No response_

### References

https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.CreateVpcOrigin
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.DeleteVpcOrigin
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.GetVpcOrigin
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.ListVpcOrigins
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.UpdateVpcOrigin

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by itsnicksia**
### Description
This change adds the new "Cloudfront VPC Origin" resource.

### Relations
Closes #40234.

### References
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.CreateVpcOrigin
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.DeleteVpcOrigin
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.GetVpcOrigin
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.ListVpcOrigins
https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudfront#Client.UpdateVpcOrigin

### Output from Acceptance Testing
TODO

### CODE REVIEW

**Comment by itsnicksia** [comment]
Create working:
image

**Comment by itsnicksia** [comment]
Added simple implementations of Read, Update and Delete.

These are still fragile and needs proper error handling.

Test and documentation are not yet done.

**Comment by nicksia-vgw** [comment]
Fixing up the SSL Origin Protocol syntax then going onto Tests and Docs.

**Comment by nicksia-vgw** [comment]
Docs updated.

Working on acceptance tests...

**Comment by itsnicksia** [comment]
basic acceptance test is working, just need to add some attribute checks and a few other tests.

aiming to move to review this week, please let me know (anyone) if you notice any issues as this is my first PR.

**Comment by ewbankkit** [comment]
@itsnicksia Thanks for the contribution :tada: :clap:.
I intend to start taking a look at this PR this week with the goal of getting it into the final Terraform AWS Provider release of the year (19th December).

**Comment by nicksia-vgw** [comment]
Thanks Kit! 

The post-destroy check is failing with EntityNotFound at the moment, which I'm looking into tonight.

I'll fix up the linting issues as well.

Cheers

**Review by ewbankkit — DISMISSED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloudFrontVPCOrigin_' PKG=cloudfront ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/cloudfront/... -v -count 1 -parallel 4  -run=TestAccCloudFrontVPCOrigin_ -timeout 360m
2024/12/17 16:47:16 Initializing Terraform AWS Provider...
=== RUN   TestAccCloudFrontVPCOrigin_basic
=== PAUSE TestAccCloudFrontVPCOrigin_basic
=== RUN   TestAccCloudFrontVPCOrigin_disappears
=== PAUSE TestAccCloudFrontVPCOrigin_disappears
=== RUN   TestAccCloudFrontVPCOrigin_update
=== PAUSE TestAccCloudFrontVPCOrigin_update
=== RUN   TestAccCloudFrontVPCOrigin_tags
=== PAUSE TestAccCloudFrontVPCOrigin_tags
=== CONT  TestAccCloudFrontVPCOrigin_basic
=== CONT  TestAccCloudFrontVPCOrigin_update
=== CONT  TestAccCloudFrontVPCOrigin_disappears
=== CONT  TestAccCloudFrontVPCOrigin_tags
--- PASS: TestAccCloudFrontVPCOrigin_basic (738.19s)
--- PASS: TestAccCloudFrontVPCOrigin_update (740.90s)
--- PASS: TestAccCloudFrontVPCOrigin_tags (741.42s)
--- PASS: TestAccCloudFrontVPCOrigin_disappears (746.68s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	752.020s
```
```console
% make testacc TESTARGS='-run=TestAccCloudFrontDistribution_noOptionalItems\|TestAccCloudFrontDistribution_vpcOriginConfig' PKG=cloudfront
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/cloudfront/... -v -count 1 -parallel 20  -run=TestAccCloudFrontDistribution_noOptionalItems\|TestAccCloudFrontDistribution_vpcOriginConfig -timeout 360m
2024/12/18 08:31:18 Initializing Terraform AWS Provider...
=== RUN   TestAccCloudFrontDistribution_noOptionalItems
=== PAUSE TestAccCloudFrontDistribution_noOptionalItems
=== RUN   TestAccCloudFrontDistribution_vpcOriginConfig
=== PAUSE TestAccCloudFrontDistribution_vpcOriginConfig
=== CONT  TestAccCloudFrontDistribution_noOptionalItems
=== CONT  TestAccCloudFrontDistribution_vpcOriginConfig
--- PASS: TestAccCloudFrontDistribution_noOptionalItems (671.02s)
--- PASS: TestAccCloudFrontDistribution_vpcOriginConfig (921.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	927.226s
```

**Comment by ewbankkit** [comment]
#### TODO

Need to add `aws_cloudfront_distribution.origin.vpc_origin_config`.

**Comment by nicksia-vgw** [comment]
Thanks for the fixes Kit! 

Will review those so I don't make the same mistakes in future.

Did you want 

`aws_cloudfront_distribution.origin.vpc_origin_config`

In this PR or a separate one?

**Comment by ewbankkit** [comment]
@nicksia-vgw I will add the change to this PR so that we can get it released this week. Thanks.

**Comment by ewbankkit** [comment]
@itsnicksia Thanks for the contribution :tada: :clap:.

**Pull request merged**
