### PR TITLE
r/redshift_cluster - add `aqua_configuration_status` argument

### LINKED ISSUE #18869: Redshift Cluster AQUA Support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS announced some time back in 2020 - Redshift AQUA. As of today it has now been [officially released](https://aws.amazon.com/blogs/aws/new-aqua-advanced-query-accelerator-for-amazon-redshift/), with roll out pending in the first half of this year. 

The functionality is already present in the UI for certain node types as well as the Redshift API as [AquaConfigurationStatus](https://docs.aws.amazon.com/redshift/latest/APIReference/API_CreateCluster.html).

### New or Affected Resource(s)

* `aws_redshift_cluster`

### Potential Terraform Configuration

```hcl
resource "aws_redshift_cluster" "default" {
  cluster_identifier = "tf-redshift-cluster"
  database_name      = "mydb"
  master_username    = "foo"
  master_password    = "Mustbe8characters"
  node_type          = "dc1.large"
  cluster_type       = "single-node"
  aqua_status        = "enabled"  # other options include "disabled" and "auto"
}
```

### References

* [AQUA (Advanced Query Accelerator) – A Speed Boost for Your Amazon Redshift Queries](https://aws.amazon.com/blogs/aws/new-aqua-advanced-query-accelerator-for-amazon-redshift/)
* [YouTube: AWS re:Invent 2020: Introduction to AQUA for Amazon Redshift (Preview)](https://www.youtube.com/watch?v=0LVyd-kqpdE)
* [Golang AWS SDK - CreateClusterInput](https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#CreateClusterInput) - New Clusters
* [Golang AWS SDK - ModifyAquaConfiguration](https://docs.aws.amazon.com/sdk-for-go/api/service/redshift/#Redshift.ModifyAquaConfiguration) - Toggling existing resources

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18869

Output from acceptance testing:

```
$ make testacc TESTS=TestAccRedshiftCluster_aqua PKG=redshift
--- PASS: TestAccRedshiftCluster_aqua (550.51s)
--- PASS: TestAccRedshiftCluster_basic (249.70s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
rebased and found some issues

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRedshiftCluster_\|TestAccRedshiftClusterDataSource_' PKG=redshift ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/redshift/... -v -count 1 -parallel 2  -run=TestAccRedshiftCluster_\|TestAccRedshiftClusterDataSource_ -timeout 180m
=== RUN   TestAccRedshiftClusterDataSource_basic
=== PAUSE TestAccRedshiftClusterDataSource_basic
=== RUN   TestAccRedshiftClusterDataSource_vpc
=== PAUSE TestAccRedshiftClusterDataSource_vpc
=== RUN   TestAccRedshiftClusterDataSource_logging
=== PAUSE TestAccRedshiftClusterDataSource_logging
=== RUN   TestAccRedshiftClusterDataSource_availabilityZoneRelocationEnabled
=== PAUSE TestAccRedshiftClusterDataSource_availabilityZoneRelocationEnabled
=== RUN   TestAccRedshiftCluster_basic
=== PAUSE TestAccRedshiftCluster_basic
=== RUN   TestAccRedshiftCluster_aqua
=== PAUSE TestAccRedshiftCluster_aqua
=== RUN   TestAccRedshiftCluster_disappears
=== PAUSE TestAccRedshiftCluster_disappears
=== RUN   TestAccRedshiftCluster_withFinalSnapshot
=== PAUSE TestAccRedshiftCluster_withFinalSnapshot
=== RUN   TestAccRedshiftCluster_kmsKey
=== PAUSE TestAccRedshiftCluster_kmsKey
=== RUN   TestAccRedshiftCluster_enhancedVPCRoutingEnabled
=== PAUSE TestAccRedshiftCluster_enhancedVPCRoutingEnabled
=== RUN   TestAccRedshiftCluster_loggingEnabled
=== PAUSE TestAccRedshiftCluster_loggingEnabled
=== RUN   TestAccRedshiftCluster_snapshotCopy
=== PAUSE TestAccRedshiftCluster_snapshotCopy
=== RUN   TestAccRedshiftCluster_iamRoles
=== PAUSE TestAccRedshiftCluster_iamRoles
=== RUN   TestAccRedshiftCluster_publiclyAccessible
=== PAUSE TestAccRedshiftCluster_publiclyAccessible
=== RUN   TestAccRedshiftCluster_updateNodeCount
=== PAUSE TestAccRedshiftCluster_updateNodeCount
=== RUN   TestAccRedshiftCluster_updateNodeType
=== PAUSE TestAccRedshiftCluster_updateNodeType
=== RUN   TestAccRedshiftCluster_tags
=== PAUSE TestAccRedshiftCluster_tags
=== RUN   TestAccRedshiftCluster_forceNewUsername
=== PAUSE TestAccRedshiftCluster_forceNewUsername
=== RUN   TestAccRedshiftCluster_changeAvailabilityZone
=== PAUSE TestAccRedshiftCluster_changeAvailabilityZone
=== RUN   TestAccRedshiftCluster_changeAvailabilityZoneAndSetAvailabilityZoneRelocation
=== PAUSE TestAccRedshiftCluster_changeAvailabilityZoneAndSetAvailabilityZoneRelocation
=== RUN   TestAccRedshiftCluster_changeAvailabilityZone_availabilityZoneRelocationNotSet
=== PAUSE TestAccRedshiftCluster_changeAvailabilityZone_availabilityZoneRelocationNotSet
=== RUN   TestAccRedshiftCluster_changeEncryption1
=== PAUSE TestAccRedshiftCluster_changeEncryption1
=== RUN   TestAccRedshiftCluster_changeEncryption2
=== PAUSE TestAccRedshiftCluster_changeEncryption2
=== RUN   TestAccRedshiftCluster_availabilityZoneRelocation
=== PAUSE TestAccRedshiftCluster_availabilityZoneRelocation
=== RUN   TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible
=== PAUSE TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible
=== RUN   TestAccRedshiftCluster_restoreFromSnapshot
=== PAUSE TestAccRedshiftCluster_restoreFromSnapshot
=== CONT  TestAccRedshiftClusterDataSource_basic
=== CONT  TestAccRedshiftCluster_publiclyAccessible
--- PASS: TestAccRedshiftClusterDataSource_basic (259.61s)
=== CONT  TestAccRedshiftCluster_withFinalSnapshot
--- PASS: TestAccRedshiftCluster_publiclyAccessible (288.73s)
=== CONT  TestAccRedshiftCluster_iamRoles
--- PASS: TestAccRedshiftCluster_iamRoles (274.88s)
=== CONT  TestAccRedshiftCluster_snapshotCopy
--- PASS: TestAccRedshiftCluster_snapshotCopy (229.02s)
=== CONT  TestAccRedshiftCluster_loggingEnabled
--- PASS: TestAccRedshiftCluster_withFinalSnapshot (563.25s)
=== CONT  TestAccRedshiftCluster_enhancedVPCRoutingEnabled
--- PASS: TestAccRedshiftCluster_loggingEnabled (262.91s)
=== CONT  TestAccRedshiftCluster_kmsKey
--- PASS: TestAccRedshiftCluster_kmsKey (238.58s)
=== CONT  TestAccRedshiftCluster_basic
--- PASS: TestAccRedshiftCluster_enhancedVPCRoutingEnabled (399.00s)
=== CONT  TestAccRedshiftCluster_disappears
--- PASS: TestAccRedshiftCluster_basic (243.99s)
=== CONT  TestAccRedshiftCluster_aqua
--- PASS: TestAccRedshiftCluster_disappears (404.76s)
=== CONT  TestAccRedshiftClusterDataSource_logging
--- PASS: TestAccRedshiftCluster_aqua (350.11s)
=== CONT  TestAccRedshiftClusterDataSource_availabilityZoneRelocationEnabled
--- PASS: TestAccRedshiftClusterDataSource_logging (268.10s)
=== CONT  TestAccRedshiftCluster_changeAvailabilityZone_availabilityZoneRelocationNotSet
--- PASS: TestAccRedshiftCluster_changeAvailabilityZone_availabilityZoneRelocationNotSet (303.50s)
=== CONT  TestAccRedshiftCluster_restoreFromSnapshot
--- PASS: TestAccRedshiftClusterDataSource_availabilityZoneRelocationEnabled (548.54s)
=== CONT  TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible
--- PASS: TestAccRedshiftCluster_availabilityZoneRelocation_publiclyAccessible (2.85s)
=== CONT  TestAccRedshiftCluster_availabilityZoneRelocation
--- PASS: TestAccRedshiftCluster_availabilityZoneRelocation (569.62s)
=== CONT  TestAccRedshiftCluster_changeEncryption2
--- PASS: TestAccRedshiftCluster_changeEncryption2 (1708.83s)
=== CONT  TestAccRedshiftCluster_changeEncryption1
--- PASS: TestAccRedshiftCluster_restoreFromSnapshot (1245.52s)
=== CONT  TestAccRedshiftCluster_forceNewUsername
--- PASS: TestAccRedshiftCluster_forceNewUsername (540.52s)
=== CONT  TestAccRedshiftCluster_changeAvailabilityZoneAndSetAvailabilityZoneRelocation
--- PASS: TestAccRedshiftCluster_changeEncryption1 (1219.85s)
=== CONT  TestAccRedshiftCluster_changeAvailabilityZone
--- PASS: TestAccRedshiftCluster_changeAvailabilityZoneAndSetAvailabilityZoneRelocation (904.06s)
=== CONT  TestAccRedshiftClusterDataSource_vpc
=== CONT  TestAccRedshiftCluster_updateNodeType
--- PASS: TestAccRedshiftClusterDataSource_vpc (224.60s)
--- PASS: TestAccRedshiftCluster_changeAvailabilityZone (1587.51s)
=== CONT  TestAccRedshiftCluster_tags
--- PASS: TestAccRedshiftCluster_tags (336.27s)
=== CONT  TestAccRedshiftCluster_updateNodeCount
--- PASS: TestAccRedshiftCluster_updateNodeType (1465.55s)
--- PASS: TestAccRedshiftCluster_updateNodeCount (1250.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshift	7202.260s
```

**Comment by ewbankkit** [comment]
```console
% make providerlint
==> Checking source code with providerlint...
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Pull request merged**
