### PR TITLE
Adding IAM SAML Provider Data source

### LINKED ISSUE #7283: [Feature] data source for aws_iam_saml_provider
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is already a resource for `aws_iam_saml_provider.` I'd like to be able to lookup existing resources outside of terraform using a data source for `aws_iam_saml_provider` to use a single provider in multiple terraform states.

### PR DESCRIPTION
**Pull request by alpacamybags118**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #7283

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Data Source: aws_iam_saml_provider
```

Output from acceptance testing:

```
C02XR4BHJGH5:terraform-provider-aws krobertson1$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataSourceSAMLProvider_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSourceSAMLProvider_basic -timeout 120m
=== RUN   TestAccAWSDataSourceSAMLProvider_basic
=== PAUSE TestAccAWSDataSourceSAMLProvider_basic
=== CONT  TestAccAWSDataSourceSAMLProvider_basic
--- PASS: TestAccAWSDataSourceSAMLProvider_basic (14.81s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	15.738s

...
```

The scenarios for using this would the following:

* Look up SAML providers not added via Terraform
* Easily obtain information about provider (valid_until date, metadata document, etc.) and perform logic based on these

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by yzguy** [comment]
Hey @alpacamybags118 , just found this PR for this data source that I'm looking to use, and glad someone has already started the work for it.

It seems like it went stale, and there is a bunch of changes required to it to bring it up to meet the Plugin SDK v2 (and other) requirements listed above. Is this something you might have time to do, if not I'm more than happy to do it. Your work so far would be hugely helpful in doing so.

**Comment by alpacamybags118** [comment]
@yzguy thanks for bringing this back up. I honestly totally forgot about this PR after so much time! I'll take a look at this over the weekend to see if i can migrate it to the updated format.

**Comment by alpacamybags118** [comment]
@yzguy i updated this to meet their new format and checks. i do hope someone gets to reviewing this. I can't seem to add the `needs-triage` tag myself and the automation skipped adding it for some reason. I'm commenting in the original issue as well

**Comment by yzguy** [comment]
@ewbankkit Do you mind adding the necessary labels so this PR can get reviewed? Quick turnaround from @alpacamybags118 updating it to V2 :)

**Comment by KarstenSiemer** [comment]
Whats left to be done here? I'd appreciate this PR a lot :-)
Looks good according to the [Pull Request Submission and Lifecycle](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md).

**Comment by alpacamybags118** [comment]
Rebased to keep this PR up to date. Would there be any chance this could be reviewed @ewbankkit ? Thank you!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccIAMSAMLProvider PKG=iam ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 3 -run='TestAccIAMSAMLProvider'  -timeout 180m
=== RUN   TestAccIAMSAMLProviderDataSource_basic
=== PAUSE TestAccIAMSAMLProviderDataSource_basic
=== RUN   TestAccIAMSAMLProvider_basic
=== PAUSE TestAccIAMSAMLProvider_basic
=== RUN   TestAccIAMSAMLProvider_tags
=== PAUSE TestAccIAMSAMLProvider_tags
=== RUN   TestAccIAMSAMLProvider_disappears
=== PAUSE TestAccIAMSAMLProvider_disappears
=== CONT  TestAccIAMSAMLProviderDataSource_basic
=== CONT  TestAccIAMSAMLProvider_tags
=== CONT  TestAccIAMSAMLProvider_disappears
--- PASS: TestAccIAMSAMLProvider_disappears (12.90s)
=== CONT  TestAccIAMSAMLProvider_basic
--- PASS: TestAccIAMSAMLProviderDataSource_basic (15.13s)
--- PASS: TestAccIAMSAMLProvider_tags (37.24s)
--- PASS: TestAccIAMSAMLProvider_basic (24.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	41.675s
```

**Pull request merged**
