### PR TITLE
ds/hosted_zones: New data source

### PR DESCRIPTION
**Pull request by lingrino**
👋 Hello! This PR creates a new data resource that provides static AWS hosted zone values for all supported services. Prior discussion was in issue https://github.com/hashicorp/terraform-provider-aws/issues/19395. This is modeled off existing data providers [data_source_aws_elastic_beanstalk_hosted_zone](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_elastic_beanstalk_hosted_zone.go) and [data_source_aws_elb_hosted_zone_id](https://github.com/hashicorp/terraform-provider-aws/blob/main/aws/data_source_aws_elb_hosted_zone_id.go).

**Some questions:**
- Currently `alb` and `elb` alias to the same value. They have the same hosted zone in AWS. Is that preferred or should I choose one over the other for the attribute name?
- I'm not sure the right way to expose this data. Some services (cloudfront and global accelerator) have global values while others (s3, alb, nlb, beanstalk) have per-region values. Currently I expose everything regionally and just duplicate data for the global services. But there's other approaches. I could add a fake "global" region for example. What's the best way to expose both?
- Currently I expose each service as its own attribute. Is that the right way? Another option is to not even take `region` as an input and just return the entire map as an attribute named `hosted_zones`. Is there another approach?
- Some services are not supported in some regions (china). Currently in this case I output `""`. Should I instead omit the value or return some other sentinel value?

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

closes https://github.com/hashicorp/terraform-provider-aws/issues/19395

Output from acceptance testing:

```shell
$ make testacc TESTARGS='-run=TestAccAWSHostedZones'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSHostedZones -timeout 180m
=== RUN   TestAccAWSHostedZones_basic
=== PAUSE TestAccAWSHostedZones_basic
=== CONT  TestAccAWSHostedZones_basic
--- PASS: TestAccAWSHostedZones_basic (17.08s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	19.719s
```

### CODE REVIEW

**Comment by lingrino** [comment]
Hello! I'd love to get some feedback on what's left to do for this PR. Does this feel like the right way to expose hosted zone data? cc @YakDriver who commented on the original issue. Thank you 🙇

**Comment by lingrino** [comment]
👋 I still haven't heard back on this PR. Is there anything missing? cc @YakDriver 

Thank you!

**Comment by lingrino** [comment]
Hello @breathingdust I saw you added some new labels. Is there anything else I can do to move this PR forward? Thanks!

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by breathingdust** [comment]
Hi @lingrino! Thanks for the contribution. We use community upvotes to determine priority for maintainer review, as we are constrained on maintainer bandwidth sometimes PR's can sit for some time until they build support. The is no expectation for you to keep the branch up to date and it does not affect prioritization. Once the PR is prioritized the maintainers will either make the changes or work with you to get the PR into shape.

**Comment by lingrino** [comment]
Great! Thanks for the response.

**Pull request closed without merging**
