### PR TITLE
add data source for aws_controltower_controls

### PR DESCRIPTION
**Pull request by silvaalbert**
Relates #26612
Dependent on #26975

Output from acceptance testing:

```
$ TF_ACC=1 make testacc TESTS=TestAccControlTowerControlsDataSource_id PKG=controltower
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/controltower/... -v -count 1 -parallel 20 -run='TestAccControlTowerControlsDataSource_id'  -timeout 180m
=== RUN   TestAccControlTowerControlsDataSource_id
=== PAUSE TestAccControlTowerControlsDataSource_id
=== CONT  TestAccControlTowerControlsDataSource_id
--- PASS: TestAccControlTowerControlsDataSource_id (10.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/controltower	13.702s
...
```

### CODE REVIEW

**Comment by silvaalbert** [comment]
Dependent on #26975

**Comment by silvaalbert** [comment]
This PR adds a data source for aws_controltower_controls, as described in #26612

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccControlTowerControlsDataSource_' PKG=controltower
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/controltower/... -v -count 1 -parallel 20  -run=TestAccControlTowerControlsDataSource_ -timeout 180m
=== RUN   TestAccControlTowerControlsDataSource_basic
=== PAUSE TestAccControlTowerControlsDataSource_basic
=== CONT  TestAccControlTowerControlsDataSource_basic
--- PASS: TestAccControlTowerControlsDataSource_basic (21.91s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/controltower	26.410s
```

**Comment by ewbankkit** [comment]
@silvaalbert Thanks for the contribution :tada: :clap:.

**Pull request merged**
