### PR TITLE
Use s3manager.Uploader for creating S3 bucket objects

### LINKED ISSUE #788: EntityTooLarge: Your proposed upload exceeds the maximum allowed size
_This issue was originally opened by @dragan as hashicorp/terraform#14693. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

When using the `aws_s3_bucket_object` resource, I'm not able to upload large files. However, using the aws cli, I am without any changes to the bucket policy.

### Terraform Version

v0.8.8

### Affected Resource(s)
Please list the resources as a list, for example:
- aws_s3_bucket_object

### Terraform Configuration Files
```hcl
resource "aws_s3_bucket_object" "monolith_development_0_0_2" {
  bucket  = "${aws_s3_bucket.my_bucket.bucket}"
  key     = "path/to/large/file.bin"
  source = "${format("%s/path/to/large/file.bin", path.cwd)}"
}
```

### Debug Output

https://gist.github.com/dragan/bd658a64fe8db87fb880410ed7b190a1

### Expected Behavior

Upload the file

### Actual Behavior

```
Error applying plan:

1 error(s) occurred:

* aws_s3_bucket_object.monolith_development_0_0_2: Error putting object in S3 bucket (concur-faraday-integration-backup): EntityTooLarge: Your proposed upload exceeds the maximum allowed size
        status code: 400, request id: F9D925AB9BA31A72

Terraform does not automatically rollback in the face of errors.
Instead, your Terraform state file has been partially updated with
any resources that successfully completed. Please address the error
above and apply again to incrementally change your infrastructure.
```

### Steps to Reproduce

1. `terraform plan -out=plan.bin`
2. `terraform apply plan.bin`

### Important Factoids

None

### References

Not that I know of

### LINKED ISSUE #19336: Uploading large files to AWS with aws_s3_bucket_object
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
2021-05-12T09:50:18.204+0200 [DEBUG] Adding temp file log sink: /var/folders/18/h1984hd95ms_l22lvpwzc57r0000gn/T/terraform-log131399222
2021-05-12T09:50:18.204+0200 [INFO]  Terraform version: 0.15.3
2021-05-12T09:50:18.204+0200 [INFO]  Go runtime version: go1.16.3
2021-05-12T09:50:18.204+0200 [INFO]  CLI args: []string{"/usr/local/homebrew/bin/terraform", "-v"}
2021-05-12T09:50:18.205+0200 [TRACE] Stdout is a terminal of width 174
2021-05-12T09:50:18.205+0200 [TRACE] Stderr is a terminal of width 174
2021-05-12T09:50:18.205+0200 [TRACE] Stdin is a terminal
2021-05-12T09:50:18.205+0200 [DEBUG] Attempting to open CLI config file: /Users/nsowatsk/.terraformrc
2021-05-12T09:50:18.205+0200 [DEBUG] File doesn't exist, but doesn't need to. Ignoring.
2021-05-12T09:50:18.207+0200 [DEBUG] ignoring non-existing provider search directory terraform.d/plugins
2021-05-12T09:50:18.207+0200 [DEBUG] ignoring non-existing provider search directory /Users/nsowatsk/.terraform.d/plugins
2021-05-12T09:50:18.207+0200 [DEBUG] ignoring non-existing provider search directory /Users/nsowatsk/Library/Application Support/io.terraform/plugins
2021-05-12T09:50:18.207+0200 [DEBUG] ignoring non-existing provider search directory /Library/Application Support/io.terraform/plugins
2021-05-12T09:50:18.208+0200 [INFO]  CLI command args: []string{"version", "-v"}
Terraform v0.15.3
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.39.0
```

### Affected Resource(s)

aws_s3_bucket_object

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket_object" "object" {
  bucket = "dnac-ova"
  key    = "dnac/dnac.ova"
  source = "/Users/x/Virtual Machines.localized/dnac.ova"

  # See Re: [hashicorp/terraform] Uploading a large file to AWS with Resource: aws_s3_bucket_object (#28678)
  # etag = filemd5("/Users/x/Virtual Machines.localized/dnac.ova")
}
```

Note that dnac.ova is ~80GB

Also note that this command works, in that the `test.txt` file appears in the bucket.

```
echo test > test.txt; aws s3api put-object --bucket dnac-ova --key test/test.txt --region us-east-1 --body test.txt
```

As a further test, I also tried:

```
resource "aws_s3_bucket_object" "object" {
  bucket = "dnac-ova"
  key    = "test2/test2"
  source = "test2.txt"
}
```

That also worked as expected, in that the file was uploaded to the bucket.

### Debug Output

https://gist.github.com/NathanDotTo/22c53af50e5eace1836fed7206eeedc1

### Panic Output

NA

### Expected Behavior

The dnac.ova file should have been uploaded to the s3 bucket.

### Actual Behavior

The dnac.ova file was not uploaded to the s3 bucket.

### Steps to Reproduce

`rm -rf .terraform*; terraform init; terraform apply`

### Important Factoids

See https://github.com/hashicorp/terraform/issues/28678#issuecomment-839167251

The dnac.ova file is ~80GB.

### References

https://github.com/hashicorp/terraform/issues/28678
https://github.com/hashicorp/terraform/issues/14693

### PR DESCRIPTION
**Pull request by cpcloud**
This PR is equivalent to #14382, but conforms to the new directory layout
resulting from #21306.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #788.
Closes #19336.
Supersedes #14382.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by cpcloud** [comment]
@justinretzolk Is there anything I should do in the meantime while awaiting review?

**Comment by cpcloud** [comment]
@justinretzolk Any updates here? Anything I can do to help move this along?

**Review by IronLung7 — APPROVED** [review]

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccS3BucketObject_' PKG_NAME=internal/service/s3     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run=TestAccS3BucketObject_ -timeout 180m
=== RUN   TestAccS3BucketObject_noNameNoKey
=== PAUSE TestAccS3BucketObject_noNameNoKey
=== RUN   TestAccS3BucketObject_empty
=== PAUSE TestAccS3BucketObject_empty
=== RUN   TestAccS3BucketObject_source
=== PAUSE TestAccS3BucketObject_source
=== RUN   TestAccS3BucketObject_content
=== PAUSE TestAccS3BucketObject_content
=== RUN   TestAccS3BucketObject_etagEncryption
=== PAUSE TestAccS3BucketObject_etagEncryption
=== RUN   TestAccS3BucketObject_contentBase64
=== PAUSE TestAccS3BucketObject_contentBase64
=== RUN   TestAccS3BucketObject_sourceHashTrigger
=== PAUSE TestAccS3BucketObject_sourceHashTrigger
=== RUN   TestAccS3BucketObject_withContentCharacteristics
=== PAUSE TestAccS3BucketObject_withContentCharacteristics
=== RUN   TestAccS3BucketObject_nonVersioned
=== PAUSE TestAccS3BucketObject_nonVersioned
=== RUN   TestAccS3BucketObject_updates
=== PAUSE TestAccS3BucketObject_updates
=== RUN   TestAccS3BucketObject_updateSameFile
=== PAUSE TestAccS3BucketObject_updateSameFile
=== RUN   TestAccS3BucketObject_updatesWithVersioning
=== PAUSE TestAccS3BucketObject_updatesWithVersioning
=== RUN   TestAccS3BucketObject_updatesWithVersioningViaAccessPoint
=== PAUSE TestAccS3BucketObject_updatesWithVersioningViaAccessPoint
=== RUN   TestAccS3BucketObject_kms
=== PAUSE TestAccS3BucketObject_kms
=== RUN   TestAccS3BucketObject_sse
=== PAUSE TestAccS3BucketObject_sse
=== RUN   TestAccS3BucketObject_acl
=== PAUSE TestAccS3BucketObject_acl
=== RUN   TestAccS3BucketObject_metadata
=== PAUSE TestAccS3BucketObject_metadata
=== RUN   TestAccS3BucketObject_storageClass
=== PAUSE TestAccS3BucketObject_storageClass
=== RUN   TestAccS3BucketObject_tags
=== PAUSE TestAccS3BucketObject_tags
=== RUN   TestAccS3BucketObject_tagsLeadingSingleSlash
=== PAUSE TestAccS3BucketObject_tagsLeadingSingleSlash
=== RUN   TestAccS3BucketObject_tagsLeadingMultipleSlashes
=== PAUSE TestAccS3BucketObject_tagsLeadingMultipleSlashes
=== RUN   TestAccS3BucketObject_tagsMultipleSlashes
=== PAUSE TestAccS3BucketObject_tagsMultipleSlashes
=== RUN   TestAccS3BucketObject_objectLockLegalHoldStartWithNone
=== PAUSE TestAccS3BucketObject_objectLockLegalHoldStartWithNone
=== RUN   TestAccS3BucketObject_objectLockLegalHoldStartWithOn
=== PAUSE TestAccS3BucketObject_objectLockLegalHoldStartWithOn
=== RUN   TestAccS3BucketObject_objectLockRetentionStartWithNone
=== PAUSE TestAccS3BucketObject_objectLockRetentionStartWithNone
=== RUN   TestAccS3BucketObject_objectLockRetentionStartWithSet
=== PAUSE TestAccS3BucketObject_objectLockRetentionStartWithSet
=== RUN   TestAccS3BucketObject_objectBucketKeyEnabled
=== PAUSE TestAccS3BucketObject_objectBucketKeyEnabled
=== RUN   TestAccS3BucketObject_bucketBucketKeyEnabled
=== PAUSE TestAccS3BucketObject_bucketBucketKeyEnabled
=== RUN   TestAccS3BucketObject_defaultBucketSSE
=== PAUSE TestAccS3BucketObject_defaultBucketSSE
=== RUN   TestAccS3BucketObject_ignoreTags
=== PAUSE TestAccS3BucketObject_ignoreTags
=== CONT  TestAccS3BucketObject_noNameNoKey
=== CONT  TestAccS3BucketObject_metadata
=== CONT  TestAccS3BucketObject_withContentCharacteristics
=== CONT  TestAccS3BucketObject_nonVersioned
=== CONT  TestAccS3BucketObject_acl
=== CONT  TestAccS3BucketObject_sse
=== CONT  TestAccS3BucketObject_kms
=== CONT  TestAccS3BucketObject_updatesWithVersioningViaAccessPoint
=== CONT  TestAccS3BucketObject_updatesWithVersioning
=== CONT  TestAccS3BucketObject_updateSameFile
=== CONT  TestAccS3BucketObject_updates
=== CONT  TestAccS3BucketObject_empty
=== CONT  TestAccS3BucketObject_etagEncryption
=== CONT  TestAccS3BucketObject_content
=== CONT  TestAccS3BucketObject_defaultBucketSSE
=== CONT  TestAccS3BucketObject_ignoreTags
=== CONT  TestAccS3BucketObject_source
=== CONT  TestAccS3BucketObject_tagsLeadingMultipleSlashes
=== CONT  TestAccS3BucketObject_sourceHashTrigger
=== CONT  TestAccS3BucketObject_objectLockRetentionStartWithNone
=== CONT  TestAccS3BucketObject_nonVersioned
    acctest.go:1114: skipping test; environment variable TF_ACC_ASSUME_ROLE_ARN must be set. Usage: Amazon Resource Name (ARN) of existing IAM Role to assume for testing restricted permissions
--- SKIP: TestAccS3BucketObject_nonVersioned (1.12s)
=== CONT  TestAccS3BucketObject_objectLockLegalHoldStartWithOn
--- PASS: TestAccS3BucketObject_noNameNoKey (6.68s)
=== CONT  TestAccS3BucketObject_objectLockLegalHoldStartWithNone
--- PASS: TestAccS3BucketObject_withContentCharacteristics (42.04s)
=== CONT  TestAccS3BucketObject_tagsMultipleSlashes
--- PASS: TestAccS3BucketObject_etagEncryption (42.09s)
=== CONT  TestAccS3BucketObject_tagsLeadingSingleSlash
--- PASS: TestAccS3BucketObject_content (49.85s)
=== CONT  TestAccS3BucketObject_tags
--- PASS: TestAccS3BucketObject_kms (54.47s)
=== CONT  TestAccS3BucketObject_storageClass
--- PASS: TestAccS3BucketObject_sse (54.69s)
=== CONT  TestAccS3BucketObject_contentBase64
--- PASS: TestAccS3BucketObject_source (55.93s)
=== CONT  TestAccS3BucketObject_objectBucketKeyEnabled
--- PASS: TestAccS3BucketObject_empty (55.96s)
=== CONT  TestAccS3BucketObject_bucketBucketKeyEnabled
--- PASS: TestAccS3BucketObject_defaultBucketSSE (56.70s)
=== CONT  TestAccS3BucketObject_objectLockRetentionStartWithSet
--- PASS: TestAccS3BucketObject_updates (86.13s)
--- PASS: TestAccS3BucketObject_updateSameFile (90.13s)
--- PASS: TestAccS3BucketObject_sourceHashTrigger (91.09s)
--- PASS: TestAccS3BucketObject_objectLockLegalHoldStartWithOn (90.06s)
--- PASS: TestAccS3BucketObject_contentBase64 (38.91s)
--- PASS: TestAccS3BucketObject_objectBucketKeyEnabled (38.24s)
--- PASS: TestAccS3BucketObject_ignoreTags (94.96s)
--- PASS: TestAccS3BucketObject_updatesWithVersioning (95.07s)
--- PASS: TestAccS3BucketObject_updatesWithVersioningViaAccessPoint (96.07s)
--- PASS: TestAccS3BucketObject_bucketBucketKeyEnabled (41.99s)
--- PASS: TestAccS3BucketObject_metadata (113.64s)
--- PASS: TestAccS3BucketObject_objectLockRetentionStartWithNone (118.80s)
--- PASS: TestAccS3BucketObject_objectLockLegalHoldStartWithNone (113.18s)
--- PASS: TestAccS3BucketObject_acl (121.92s)
--- PASS: TestAccS3BucketObject_tagsLeadingMultipleSlashes (146.50s)
--- PASS: TestAccS3BucketObject_tagsMultipleSlashes (118.95s)
--- PASS: TestAccS3BucketObject_tagsLeadingSingleSlash (121.63s)
--- PASS: TestAccS3BucketObject_tags (115.85s)
--- PASS: TestAccS3BucketObject_objectLockRetentionStartWithSet (115.02s)
--- PASS: TestAccS3BucketObject_storageClass (139.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	197.055s
```

**Comment by ewbankkit** [comment]
@cpcloud Thanks for the contribution :tada: :clap:.

**Pull request merged**
