### PR TITLE
r/aws_backup_restore_testing_plan: Adding resource for managing AWS Backup Restore Testing plans

### PR DESCRIPTION
**Pull request by bkumar5-atlassian**
### Description
Adding resource to manage AWS Backup Restore Testing plans: aws_backup_restore_testing_plan

### Relations
Relates #34699 

### Output from Acceptance Testing

```console
make testacc TESTS=TestAccRestoreTestingPlan PKG=backup
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/backup/... -v -count 1 -parallel 20 -run='TestAccRestoreTestingPlan'  -timeout 360m
=== RUN   TestAccRestoreTestingPlan_basic
=== PAUSE TestAccRestoreTestingPlan_basic
=== RUN   TestAccRestoreTestingPlan_disappears
=== PAUSE TestAccRestoreTestingPlan_disappears
=== RUN   TestAccRestoreTestingPlan_withTags
=== PAUSE TestAccRestoreTestingPlan_withTags
=== RUN   TestAccRestoreTestingPlan_updateRecoveryPointSelection
=== PAUSE TestAccRestoreTestingPlan_updateRecoveryPointSelection
=== RUN   TestAccRestoreTestingPlan_withOptionalArguments
=== PAUSE TestAccRestoreTestingPlan_withOptionalArguments
=== CONT  TestAccRestoreTestingPlan_basic
=== CONT  TestAccRestoreTestingPlan_updateRecoveryPointSelection
=== CONT  TestAccRestoreTestingPlan_withTags
=== CONT  TestAccRestoreTestingPlan_disappears
=== CONT  TestAccRestoreTestingPlan_withOptionalArguments
--- PASS: TestAccRestoreTestingPlan_disappears (19.25s)
--- PASS: TestAccRestoreTestingPlan_basic (22.74s)
--- PASS: TestAccRestoreTestingPlan_withTags (47.81s)
--- PASS: TestAccRestoreTestingPlan_updateRecoveryPointSelection (47.87s)
--- PASS: TestAccRestoreTestingPlan_withOptionalArguments (48.06s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/backup     54.161s
...
```

### CODE REVIEW

**Comment by Thomas-Franklin** [comment]
Hi @bkumar5-atlassian , I had also started work on this last week https://github.com/hashicorp/terraform-provider-aws/pull/37039 and submitted it this morning only to see you've already proposed it as a resource, not sure if this causes problems and hopefully we can get traction on _one of them_.

**Comment by mervin-hemaraju-cko** [comment]
Heyy, when is this getting merged?

**Comment by jeroenhabets** [comment]
Please be aware there are two open PRs on this. This one and https://github.com/hashicorp/terraform-provider-aws/pull/37039

**Comment by jeroenhabets** [comment]
It seems competing PR https://github.com/hashicorp/terraform-provider-aws/pull/37039 is about to get merged...

**Pull request closed without merging**
