### PR TITLE
r/cognito_user_pool_client - Access and ID token validity

### LINKED ISSUE #13154: aws_cognito_user_pool add support for SES ConfigurationSet
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The AWS [CreateUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html) and [UpdateUserPool](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html) APIs now support a [ConfigurationSet EmailConfiguration option](https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_EmailConfigurationType.html#CognitoUserPools-Type-EmailConfigurationType-ConfigurationSet). It would be great to incorporate this into the existing `aws_cognito_user_pool` resource.

### New or Affected Resource(s)

* `aws_cognito_user_pool`

### Potential Terraform Configuration

```hcl
resource aws_ses_email_identity example {
  email = "cognito@example.com"
}
resource aws_ses_configuration_set cognito_config {
  name = "cognito-config"
}
resource aws_cognito_user_pool example {
  name = "example-user-pool"
  email_configuration {
    source_arn = aws_ses_email_identity.example.arn
    from_email_address = "Example <${aws_ses_email_identity.example.email}>"
    email_sending_account = "DEVELOPER"
    configuration_set = aws_ses_configuration_set.cognito_config.name
  }
}

```

### References

* https://forums.aws.amazon.com/thread.jspa?threadID=302169&tstart=0&messageID=940659#940659
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_EmailConfigurationType.html#CognitoUserPools-Type-EmailConfigurationType-ConfigurationSet
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPool.html
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPool.html

### LINKED ISSUE #14626: AWS Cognito User Pool - Ability to set Remember User Device to Always
_This issue was originally opened by @lama-ank as hashicorp/terraform#25841. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Current Terraform Version

```
Terraform v0.12.29

```

### Use-cases

```
Setting Remember Device to "Always" in AWS Cognito User Pool
```

### Attempted Solutions

```
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cognito_user_pool
The cognito_user_pool provider has these options for devices, but not one to always remember the user device.
challenge_required_on_new_device 
device_only_remembered_on_user_prompt 
```
### Proposal

```
Adding an argument to set the remember user device option of Cognito user pools to 'Always'
```

### LINKED ISSUE #14919: AWS Cognito: support token validity units
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Cognito allows configuring the token validity units of tokens for each User Pool Client.

### New or Affected Resource(s)

* aws_cognito_user_pool_client

### Potential Terraform Configuration
```hcl
// the Console user pool client
resource "aws_cognito_user_pool_client" "this" {
  // other attributes
 
  token_validity_units {
     access_token  = "hours"
     id_token      = "hours"
     refresh_token = "days"
     // the above are defaults; valid values are: seconds | minutes | hours | days
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/08/amazon-cognito-user-pools-supports-customization-of-token-expiration/
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_CreateUserPoolClient.html#CognitoUserPools-CreateUserPoolClient-request-TokenValidityUnits
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_UpdateUserPoolClient.html#CognitoUserPools-UpdateUserPoolClient-request-TokenValidityUnits
* https://docs.aws.amazon.com/cognito-user-identity-pools/latest/APIReference/API_TokenValidityUnitsType.html

### LINKED ISSUE #15722: tests/provider: TestAccAWSCognitoUserPoolClient_analyticsConfig InvalidParameterException
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The `TestAccAWSCognitoUserPoolClient_analyticsConfig` test on GovCloud is failing. It fails because the `integration with Pinpoint is not supported` in `us-gov-west-1`. Existing PreChecks can check for Cognito Identity and Pinpoint App support but not for the integration. This would be another excellent place for skipping the test with the functionality in hashicorp/terraform-plugin-sdk#592.

### New or Affected Resource(s)

* aws_cognito_user_pool_client

### Terraform Configuration Files

```hcl
data "aws_caller_identity" "current" {}

resource "aws_cognito_user_pool" "test" {
  name = "tf-acc-cognito-user-pool"
}

resource "aws_pinpoint_app" "test" {
  name = "yakdriver"
}

resource "aws_iam_role" "test" {
  name = "yakdriver"

  assume_role_policy = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": "sts:AssumeRole",
      "Principal": {
        "Service": "cognito-idp.amazonaws.com"
      },
      "Effect": "Allow",
      "Sid": ""
    }
  ]
}
EOF
}

resource "aws_iam_role_policy" "test" {
  name = "yakdriver"
  role = aws_iam_role.test.id

  policy = <<-EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "mobiletargeting:UpdateEndpoint",
        "mobiletargeting:PutItems"
      ],
      "Effect": "Allow",
      "Resource": "arn:aws:mobiletargeting:*:${data.aws_caller_identity.current.account_id}:apps/${aws_pinpoint_app.test.application_id}*"
    }
  ]
}
EOF
}

resource "aws_cognito_user_pool_client" "test" {
  name         = "tf-acc-cognito-user-pool"
  user_pool_id = aws_cognito_user_pool.test.id

  analytics_configuration {
    application_id = aws_pinpoint_app.test.application_id
    external_id    = "tf-acc-cognito-user-pool"
    role_arn       = aws_iam_role.test.arn
  }
}
```

### Debug Output

```
    TestAccAWSCognitoUserPoolClient_analyticsConfig: resource_aws_cognito_user_pool_client_test.go:235: Step 1/4 error: Error running apply: 2020/10/19 21:23:22 [DEBUG] Using modified User-Agent: Terraform/0.12.29 HashiCorp-terraform-exec/0.10.0
        
        Error: Error creating Cognito User Pool Client: InvalidParameterException: The integration with Pinpoint is not supported in this region.

--- FAIL: TestAccAWSCognitoUserPoolClient_analyticsConfig (34.82s)
```

### References

* #15720
* #15662

### LINKED ISSUE #16799: AWS Cognito User Pool - Unable to set remember user's devices to "No"
In the AWS Console, there are 3 options. Here only two are currently available in the `device_configuration` block since this is a boolean.

```
device_only_remembered_on_user_prompt = true (console shows "User Opt In" selected)
device_only_remembered_on_user_prompt = false (console shows "Always" selected)
```

I would propose something like this to match the AWS Cognito console:
```
rememer_device = "ALWAYS | USEROPTIN | NO"
```

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13154
Closes #13156
Closes #14353
Closes #14626
Closes #14919
Closes #15722
Closes #16749
Closes #16799

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_cognito_user_pool_client - add plan time validation to `name`, `default_redirect_uri`, `supported_identity_providers`.
resource_aws_cognito_user_pool_client - add `access_token_validity` and `id_token_validity`, `token_validity_units`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCognitoUserPoolClient_'
--- PASS: TestAccAWSCognitoUserPoolClient_basic (57.99s)
--- PASS: TestAccAWSCognitoUserPoolClient_refreshTokenValidity (89.07s)
--- PASS: TestAccAWSCognitoUserPoolClient_accessTokenValidity (96.61s)
--- PASS: TestAccAWSCognitoUserPoolClient_idTokenValidity (89.44s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnits (103.17s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnitsWTokenValidity (93.19s)
--- PASS: TestAccAWSCognitoUserPoolClient_Name (93.26s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFields (58.63s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFieldsUpdatingOneField (86.95s)
--- PASS: TestAccAWSCognitoUserPoolClient_analyticsConfig (142.59s)
--- PASS: TestAccAWSCognitoUserPoolClient_disappears (51.30s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Ready to review!

**Comment by jangolano** [comment]
Just curios when this will be merged and what release it will be in.  This will be a big help!

**Comment by jangolano** [comment]
Any update on when this might be merged?

**Comment by jangolano** [comment]
Any update?

**Comment by Shadrack1701** [comment]
We have any idea when this will get merged?

**Comment by karlismelderis** [comment]
Any plans to merge this PR?

**Comment by karlismelderis** [comment]
Guys, 

Today if we use `refresh_token_validity = 60` we end up with 60 days 🤯
and if I go to AWS console and change it to 60 minutes terraform thinks nothing changed. 🐛

**Comment by DrFaust92** [comment]
Rebased and retested:

```
--- PASS: TestAccAWSCognitoUserPoolClient_disappears_userPool (33.87s)
--- PASS: TestAccAWSCognitoUserPoolClient_disappears (40.20s)
--- PASS: TestAccAWSCognitoUserPoolClient_basic (47.76s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFields (48.20s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnitsWTokenValidity (76.57s)
--- PASS: TestAccAWSCognitoUserPoolClient_refreshTokenValidity (76.73s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnits (76.94s)
--- PASS: TestAccAWSCognitoUserPoolClient_Name (77.23s)
--- PASS: TestAccAWSCognitoUserPoolClient_accessTokenValidity (77.73s)
--- PASS: TestAccAWSCognitoUserPoolClient_idTokenValidity (78.98s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFieldsUpdatingOneField (80.30s)
--- PASS: TestAccAWSCognitoUserPoolClient_analyticsConfig (118.34s)
```

**Review by fifarafa — APPROVED** [review]

**Comment by fifarafa** [comment]
Hey guys, any updates?

**Comment by JoannaWilk** [comment]
Hello, are there any updates?

**Comment by Shadrack1701** [comment]
So it's been 4 months...what needs to happen for this to get merged.  Clearly **at least** 29 people want this update.  Do we need to start a petition on change.org?  Do we need to bribe someone?  Seriously though what does it take to make small incremental improvements like this?

**Comment by jangolano** [comment]
Opened a petition on change.org for Hashicorp. 

http://chng.it/mYvf6hfj4k

**Comment by fgrillo** [comment]
Hey folks, any updates regarding this PR?

**Comment by kyle-thedelta** [comment]
@YakDriver seems like a formatting issue: 
```
-	configuration_set      = aws_ses_configuration_set.test.name
+    configuration_set      = aws_ses_configuration_set.test.name
```

**Review by YakDriver — APPROVED** [review]
Looks great! Thank you @DrFaust92, @johngallagher, @mbordas09!

Acceptance tests in GovCloud:
```
--- PASS: TestAccAWSCognitoUserPool_basic (48.97s)
--- PASS: TestAccAWSCognitoUserPool_disappears (31.33s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SmsConfiguration (85.59s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SmsConfigurationAndSoftwareTokenMfaConfiguration (90.08s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SmsConfigurationToSoftwareTokenMfaConfiguration (68.03s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SoftwareTokenMfaConfiguration (92.47s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SoftwareTokenMfaConfigurationToSmsConfiguration (79.53s)
--- PASS: TestAccAWSCognitoUserPool_recovery (114.99s)
--- PASS: TestAccAWSCognitoUserPool_SmsAuthenticationMessage (65.53s)
--- PASS: TestAccAWSCognitoUserPool_SmsConfiguration (96.43s)
--- PASS: TestAccAWSCognitoUserPool_SmsConfiguration_ExternalId (94.05s)
--- PASS: TestAccAWSCognitoUserPool_SmsConfiguration_SnsCallerArn (99.83s)
--- PASS: TestAccAWSCognitoUserPool_SmsVerificationMessage (76.25s)
--- PASS: TestAccAWSCognitoUserPool_update (137.00s)
--- PASS: TestAccAWSCognitoUserPool_withAdminCreateUserConfiguration (75.10s)
--- PASS: TestAccAWSCognitoUserPool_withAdminCreateUserConfigurationAndPasswordPolicy (41.63s)
--- PASS: TestAccAWSCognitoUserPool_withAliasAttributes (76.25s)
--- PASS: TestAccAWSCognitoUserPool_withDeviceConfiguration (73.12s)
--- PASS: TestAccAWSCognitoUserPool_withEmailConfiguration (40.82s)
--- PASS: TestAccAWSCognitoUserPool_withEmailConfigurationSource (37.27s)
--- PASS: TestAccAWSCognitoUserPool_withEmailVerificationMessage (57.81s)
--- PASS: TestAccAWSCognitoUserPool_withLambdaConfig (105.36s)
--- PASS: TestAccAWSCognitoUserPool_withPasswordPolicy (75.21s)
--- PASS: TestAccAWSCognitoUserPool_withSchemaAttributes (82.32s)
--- PASS: TestAccAWSCognitoUserPool_withTags (114.99s)
--- PASS: TestAccAWSCognitoUserPool_withUsernameConfiguration (69.81s)
--- PASS: TestAccAWSCognitoUserPool_withVerificationMessageTemplate (76.15s)
--- PASS: TestAccAWSCognitoUserPoolClient_accessTokenValidity (73.14s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFields (47.01s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFieldsUpdatingOneField (83.06s)
--- PASS: TestAccAWSCognitoUserPoolClient_basic (43.71s)
--- PASS: TestAccAWSCognitoUserPoolClient_disappears (43.88s)
--- PASS: TestAccAWSCognitoUserPoolClient_disappears_userPool (39.58s)
--- PASS: TestAccAWSCognitoUserPoolClient_idTokenValidity (84.25s)
--- PASS: TestAccAWSCognitoUserPoolClient_Name (84.18s)
--- PASS: TestAccAWSCognitoUserPoolClient_refreshTokenValidity (69.41s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnits (81.34s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnitsWTokenValidity (81.58s)
--- SKIP: TestAccAWSCognitoUserPool_withAdvancedSecurityMode (11.59s)
--- SKIP: TestAccAWSCognitoUserPoolClient_analyticsConfig (20.86s)
--- SKIP: TestAccAWSCognitoUserPoolClient_analyticsConfigWithArn (27.33s)
```

In commercial partition (`us-west-2`):
```
    resource_aws_cognito_user_pool_test.go:758: 'TEST_AWS_SES_VERIFIED_EMAIL_ARN' not set, skipping test.
--- PASS: TestAccAWSCognitoUserPool_basic (30.80s)
--- PASS: TestAccAWSCognitoUserPool_disappears (30.27s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SmsConfiguration (95.26s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SmsConfigurationAndSoftwareTokenMfaConfiguration (125.74s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SmsConfigurationToSoftwareTokenMfaConfiguration (76.80s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SoftwareTokenMfaConfiguration (86.10s)
--- PASS: TestAccAWSCognitoUserPool_MfaConfiguration_SoftwareTokenMfaConfigurationToSmsConfiguration (89.14s)
--- PASS: TestAccAWSCognitoUserPool_recovery (83.97s)
--- PASS: TestAccAWSCognitoUserPool_SmsAuthenticationMessage (75.06s)
--- PASS: TestAccAWSCognitoUserPool_SmsConfiguration (125.79s)
--- PASS: TestAccAWSCognitoUserPool_SmsConfiguration_ExternalId (104.90s)
--- PASS: TestAccAWSCognitoUserPool_SmsConfiguration_SnsCallerArn (105.79s)
--- PASS: TestAccAWSCognitoUserPool_SmsVerificationMessage (74.18s)
--- PASS: TestAccAWSCognitoUserPool_update (130.29s)
--- PASS: TestAccAWSCognitoUserPool_withAdminCreateUserConfiguration (72.82s)
--- PASS: TestAccAWSCognitoUserPool_withAdminCreateUserConfigurationAndPasswordPolicy (43.11s)
--- PASS: TestAccAWSCognitoUserPool_withAdvancedSecurityMode (80.21s)
--- PASS: TestAccAWSCognitoUserPool_withAliasAttributes (75.49s)
--- PASS: TestAccAWSCognitoUserPool_withDeviceConfiguration (71.70s)
--- PASS: TestAccAWSCognitoUserPool_withEmailConfiguration (42.19s)
--- PASS: TestAccAWSCognitoUserPool_withEmailVerificationMessage (52.00s)
--- PASS: TestAccAWSCognitoUserPool_withLambdaConfig (123.02s)
--- PASS: TestAccAWSCognitoUserPool_withPasswordPolicy (74.31s)
--- PASS: TestAccAWSCognitoUserPool_withSchemaAttributes (80.20s)
--- PASS: TestAccAWSCognitoUserPool_withTags (102.91s)
--- PASS: TestAccAWSCognitoUserPool_withUsernameConfiguration (75.83s)
--- PASS: TestAccAWSCognitoUserPool_withVerificationMessageTemplate (74.41s)
--- PASS: TestAccAWSCognitoUserPoolClient_accessTokenValidity (54.39s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFields (46.95s)
--- PASS: TestAccAWSCognitoUserPoolClient_allFieldsUpdatingOneField (80.92s)
--- PASS: TestAccAWSCognitoUserPoolClient_analyticsConfig (109.04s)
--- PASS: TestAccAWSCognitoUserPoolClient_analyticsConfigWithArn (46.22s)
--- PASS: TestAccAWSCognitoUserPoolClient_basic (43.69s)
--- PASS: TestAccAWSCognitoUserPoolClient_disappears (40.48s)
--- PASS: TestAccAWSCognitoUserPoolClient_disappears_userPool (25.80s)
--- PASS: TestAccAWSCognitoUserPoolClient_idTokenValidity (74.85s)
--- PASS: TestAccAWSCognitoUserPoolClient_Name (76.96s)
--- PASS: TestAccAWSCognitoUserPoolClient_refreshTokenValidity (54.61s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnits (72.92s)
--- PASS: TestAccAWSCognitoUserPoolClient_tokenValidityUnitsWTokenValidity (73.92s)
--- SKIP: TestAccAWSCognitoUserPool_withEmailConfigurationSource (0.00s)
```

**Pull request merged**
