### PR TITLE
New Datasource for AWS Timestream Database

### PR DESCRIPTION
**Pull request by hunttom**
### Description
This pull request creates a data resource for AWS Timestream Database.

### Relations
Relates #26865

### References
* https://github.com/hashicorp/terraform-provider-aws/pull/19354

### Output from Acceptance Testing
```console
%  make fmt && make build && make testacc PKG=timestreamwrite TESTS=TestAccTimestreamWriteDatabaseDataSource
make: fixing source code with gofmt...
gofmt -s -w ./internal ./names ./.ci/providerlint/helper ./.ci/providerlint/main.go ./.ci/providerlint/passes
==> Checking that code complies with gofmt requirements...
go1.21.8 install
make: build complete
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/timestreamwrite/... -v -count 1 -parallel 20 -run='TestAccTimestreamWriteDatabaseDataSource'  -timeout 360m
=== RUN   TestAccTimestreamWriteDatabaseDataSource_basic
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_basic
=== RUN   TestAccTimestreamWriteDatabaseDataSource_kmsKey
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_kmsKey
=== RUN   TestAccTimestreamWriteDatabaseDataSource_updateKMSKey
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_updateKMSKey
=== RUN   TestAccTimestreamWriteDatabaseDataSource_tags
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_tags
=== CONT  TestAccTimestreamWriteDatabaseDataSource_basic
=== CONT  TestAccTimestreamWriteDatabaseDataSource_updateKMSKey
=== CONT  TestAccTimestreamWriteDatabaseDataSource_kmsKey
=== CONT  TestAccTimestreamWriteDatabaseDataSource_tags
--- PASS: TestAccTimestreamWriteDatabaseDataSource_basic (13.62s)
--- PASS: TestAccTimestreamWriteDatabaseDataSource_kmsKey (18.20s)
--- PASS: TestAccTimestreamWriteDatabaseDataSource_tags (30.02s)
--- PASS: TestAccTimestreamWriteDatabaseDataSource_updateKMSKey (34.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite    40.186s
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @hunttom 👋 Thanks for checking in here! Based on a quick look, I don't believe there's any further action needed from you at this time. Unfortunately, I can't speak to when this will be prioritized just yet, though. We base our prioritization on the count of :+1: reactions and a few other considerations (more information: [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/)).

**Comment by ThomasZalewski** [comment]
make testacc PKG=timestreamwrite TESTS=TestAccTimestreamWriteDatabaseDataSource  

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/timestreamwrite/... -v -count 1 -parallel 20 -run='TestAccTimestreamWriteDatabaseDataSource'  -timeout 360m
=== RUN   TestAccTimestreamWriteDatabaseDataSource_basic
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_basic
=== RUN   TestAccTimestreamWriteDatabaseDataSource_kmsKey
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_kmsKey
=== RUN   TestAccTimestreamWriteDatabaseDataSource_updateKMSKey
=== PAUSE TestAccTimestreamWriteDatabaseDataSource_updateKMSKey
=== CONT  TestAccTimestreamWriteDatabaseDataSource_basic
=== CONT  TestAccTimestreamWriteDatabaseDataSource_updateKMSKey
=== CONT  TestAccTimestreamWriteDatabaseDataSource_kmsKey
--- PASS: TestAccTimestreamWriteDatabaseDataSource_basic (11.40s)
--- PASS: TestAccTimestreamWriteDatabaseDataSource_kmsKey (17.46s)
--- PASS: TestAccTimestreamWriteDatabaseDataSource_updateKMSKey (33.03s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite    37.886s

**Comment by johnsonaj** [comment]
LGTM 🚀

**Review by ThomasZalewski — APPROVED** [review]
LGTM 🚀

**Pull request merged**
