### PR TITLE
d/security_groups - add `arns` attribute

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #13624

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
data_source_security_groups: add `arns` attribute
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccDataSourceAwsSecurityGroups_'
--- PASS: TestAccDataSourceAwsSecurityGroups_tag (65.16s)
--- PASS: TestAccDataSourceAwsSecurityGroups_filter (65.36s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
@bflad / @ewbankkit having some trouble tests getting persistent dependency violation with VPC not able to delete. event without the changes. is it something weird im doing?

**Comment by bflad** [comment]
Hey @DrFaust92 👋  We would love to pick this up on Thursday as part of some gardening work. If you could rebase this and add a changelog file that would be awesome. Thank you!

**Comment by DrFaust92** [comment]
Done

```
$ make testacc TESTARGS='-run=TestAccDataSourceAwsSecurityGroups_'
--- PASS: TestAccDataSourceAwsSecurityGroups_tag (65.16s)
--- PASS: TestAccDataSourceAwsSecurityGroups_filter (65.36s)
```
```

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

Acceptance tests in GovCloud:
```
--- PASS: TestAccDataSourceAwsSecurityGroups_filter (26.63s)
--- PASS: TestAccDataSourceAwsSecurityGroups_tag (26.88s)
```

In `us-west-2`:
```
--- PASS: TestAccDataSourceAwsSecurityGroups_tag (23.12s)
--- PASS: TestAccDataSourceAwsSecurityGroups_filter (23.18s)
```

**Pull request merged**
