### PR TITLE
New resource: `aws_drs_replication_configuration_template`

### LINKED ISSUE #21865: New resource: `aws_drs_replication_configuration_template` AWS Elastic Disaster Recovery Service
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Service doc:
"AWS Elastic Disaster Recovery (AWS DRS) minimizes downtime and data loss with fast, reliable recovery of on-premises and cloud-based applications using affordable storage, minimal compute, and point-in-time recovery."

### New or Affected Resource(s)

* aws_drs_replication_configuration_template

### Potential Terraform Configuration

```hcl
resource "aws_drs_replication_configuration_template" "this" {
  associate_default_security_group = true
  bandwidth_throttling = 1000
  create_public_ip = false
  data_plane_routing = "PRIVATE_IP"
  default_large_staging_disk_type = "gp3"
  ebs_encryption = "DEFAULT"
  ebs_encryption_key_arn = ""

  pit_policy { 
  enabled = false
  interval = 1
  retention_duration = 7
  rule_id = 0
  units = "DAY"
}

  pit_policy { 
  enabled = true
  interval = 7
  retention_duration = 24
  rule_id = 1
  units = "HOUR"
}
  replication_server_instance_type = "t3.medium"
  replication_servers_security_groups_ids = [ "sg-123456" ]
  staging_area_subnet_id = "subnet-123456"
  staging_area_tags = { 
      "Env" : "Dev"
      "StagingArea" : "true" 
   }
  tags = { 
      "Env" : "Dev"
   }
  use_dedicated_replication_server = true
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/11/aws-elastic-disaster-recovery-available/?nc1=h_ls
* https://docs.aws.amazon.com/sdk-for-go/api/service/drs/#CreateReplicationConfigurationTemplateInput
* https://docs.aws.amazon.com/drs/latest/userguide/what-is-drs.html
* https://docs.aws.amazon.com/cli/latest/reference/drs/create-replication-configuration-template.html
* https://docs.aws.amazon.com/drs/latest/APIReference/API_CreateReplicationConfigurationTemplate.html

### PR DESCRIPTION
**Pull request by lewinkedrs**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21865
Relates #37816 

Output from acceptance testing:

Need assistance/guidance in creating an acceptance test for the new resource. I was hoping for some community help/support in creating the test.

### Current Status (4 June 2024): ~90% there

@lewinkedrs Thank you for your work on this! I have reworked your PR significantly so make sure to pull your branch if you happen to work on it again.

- [x] Convert to AWS SDK v2
- [x] Convert to Framework
- [ ] Get basic acceptance test working (current error: `Invalid request body`)
- [ ] Add disappears test
- [x] Docs: Add timeouts and import sections
- [x] Docs: Revise formatting to standard
- [x] Docs: "Basic configuration" is not in TF standard format
- [x] Docs: Add valid values (currently listed in example)

### CODE REVIEW

**Comment by lewinkedrs** [comment]
I had been using the git hub actions to fix formatting issues and one of them said to run #make gen and then commit. I did this and now there are merge conflicts due to the .semgrep-service-name.yml files since DRS is a new service. What is the proper path forward here? Revert that commit?

**Comment by k-brooks** [comment]
Bump - would like to see this completed, could anyone detail what work remains?

**Comment by YakDriver** [comment]
@k-brooks Thanks for your interest! Please see the op.

**Comment by YakDriver** [comment]
Unfortunately, additional resources or functionality may be needed before this is useful. This is a best-effort first step.

**Review by YakDriver — APPROVED** [review]
Looks good to me!

**Pull request merged**
