### PR TITLE
Implement Group attribute for aws_snapshot_create_volume_permission

### LINKED ISSUE #13198: Create public EBS snapshot
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS support public EBS snapshots. To create a public EBS snapshot, AWS requires you to set the CreateVolumePermission group attribute to 'all'. [aws docs](https://docs.aws.amazon.com/en_us/AWSEC2/latest/WindowsGuide/ebs-modifying-snapshot-permissions.html#share-snapshot-cli) 
This attribute is not currently supported in the the `aws_snapshot_create_volume_permission` resource [tf docs](https://www.terraform.io/docs/providers/aws/r/snapshot_create_volume_permission.html).

### New or Affected Resource(s)

* aws_snapshot_create_volume_permission

### Potential Terraform Configuration

```hcl
resource "aws_snapshot_create_volume_permission" "example_perm" {
  snapshot_id = aws_ebs_snapshot.ubuntu18_public_snapshot.id
  account_id  = "123456"
  group = "all"
}
```

### References

* #0000

### PR DESCRIPTION
**Pull request by jasbroek**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13198 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Allow `group` attribute to be set for aws_snapshot_create_volume_permission
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSnapshotCreateVolumePermission_Basic'     
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSnapshotCreateVolumePermission_Basic -timeout 120m
=== RUN   TestAccAWSSnapshotCreateVolumePermission_Basic
=== PAUSE TestAccAWSSnapshotCreateVolumePermission_Basic
=== CONT  TestAccAWSSnapshotCreateVolumePermission_Basic
--- PASS: TestAccAWSSnapshotCreateVolumePermission_Basic (106.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	107.019s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSnapshotCreateVolumePermission_disappears'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSnapshotCreateVolumePermission_disappears -timeout 120m
=== RUN   TestAccAWSSnapshotCreateVolumePermission_disappears
=== PAUSE TestAccAWSSnapshotCreateVolumePermission_disappears
=== CONT  TestAccAWSSnapshotCreateVolumePermission_disappears
--- PASS: TestAccAWSSnapshotCreateVolumePermission_disappears (91.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	91.655s

...
```

### CODE REVIEW

**Comment by jasbroek** [comment]
@breathingdust Any update on this? Would love to get this merged so the feature can be used in one of my projects.

**Comment by breathingdust** [comment]
Thanks for your contribution and for getting in touch @jasbroek 👋  At this time this feature doesn’t have enough community support for the internal team to prioritize. We will continue to monitor the community interest in the feature, and once enough support is demonstrated, the team will queue this PR up for review.

**Comment by jcyriac-synamedia** [comment]
Please share an update on this PR. I'm waiting for this feature. Thanks

**Comment by gh9411** [comment]
I'm also waiting for this function to be added.Thank you.

**Pull request closed without merging**
