### PR TITLE
Fix Quotas `service_code`/`quota_code` validation

### LINKED ISSUE #17970: `aws_servicequotas_service_quota` requires modifying tfstate if whitespace is accidently added in `quota_code`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/aws v3.31.0
+ provider registry.terraform.io/hashicorp/external v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_servicequotas_service_quota

### Terraform Configuration Files

```hcl
resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
  quota_code   = " L-83CA0A9D"
  service_code = "vpc"
  value        = 20
}
```

### Expected Behavior

Run terraform apply:

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_servicequotas_service_quota.max_ipv4_per_vpc will be created
  + resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
      + adjustable     = (known after apply)
      + arn            = (known after apply)
      + default_value  = (known after apply)
      + id             = (known after apply)
      + quota_code     = " L-83CA0A9D"
      + quota_name     = (known after apply)
      + request_id     = (known after apply)
      + request_status = (known after apply)
      + service_code   = "vpc"
      + service_name   = (known after apply)
      + value          = 20
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "quota-bug"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_servicequotas_service_quota.max_ipv4_per_vpc: Creating...

Error: error getting Service Quotas Service Quota (vpc/ L-83CA0A9D): ValidationException: 1 validation error detected: Value ' L-83CA0A9D' at 'quotaCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][a-zA-Z0-9-]{1,128}
	status code: 400, request id: 09a634c4-8653-412f-bab9-df3ff033c5ff

  on quotas.tf line 1, in resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc":
   1: resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
```

Fix the resource by removing the whitespace:

```hcl
resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
  quota_code   = "L-83CA0A9D"
  service_code = "vpc"
  value        = 20
}
```

Run terraform apply again:

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_servicequotas_service_quota.max_ipv4_per_vpc will be created
  + resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
      + adjustable     = (known after apply)
      + arn            = (known after apply)
      + default_value  = (known after apply)
      + id             = (known after apply)
      + quota_code     = "L-83CA0A9D"
      + quota_name     = (known after apply)
      + request_id     = (known after apply)
      + request_status = (known after apply)
      + service_code   = "vpc"
      + service_name   = (known after apply)
      + value          = 20
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "quota-bug"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value:
```

### Actual Behaviour

Run terraform apply:

```
$ terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # aws_servicequotas_service_quota.max_ipv4_per_vpc will be created
  + resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
      + adjustable     = (known after apply)
      + arn            = (known after apply)
      + default_value  = (known after apply)
      + id             = (known after apply)
      + quota_code     = " L-83CA0A9D"
      + quota_name     = (known after apply)
      + request_id     = (known after apply)
      + request_status = (known after apply)
      + service_code   = "vpc"
      + service_name   = (known after apply)
      + value          = 20
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions in workspace "quota-bug"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_servicequotas_service_quota.max_ipv4_per_vpc: Creating...

Error: error getting Service Quotas Service Quota (vpc/ L-83CA0A9D): ValidationException: 1 validation error detected: Value ' L-83CA0A9D' at 'quotaCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][a-zA-Z0-9-]{1,128}
	status code: 400, request id: 09a634c4-8653-412f-bab9-df3ff033c5ff

  on quotas.tf line 1, in resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc":
   1: resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
```

Fix the resource by removing the whitespace:

```hcl
resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
  quota_code   = "L-83CA0A9D"
  service_code = "vpc"
  value        = 20
}
```

Run terraform apply again:

```
$ terraform apply
aws_servicequotas_service_quota.max_ipv4_per_vpc: Refreshing state... [id=vpc/ L-83CA0A9D]

Error: error getting Service Quotas Service Quota (vpc/ L-83CA0A9D): ValidationException: 1 validation error detected: Value ' L-83CA0A9D' at 'quotaCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][a-zA-Z0-9-]{1,128}
	status code: 400, request id: dc5ed91f-131c-4356-95c9-59e5c65b2778
```

Try untainting and applying:

```
$ terraform untaint aws_servicequotas_service_quota.max_ipv4_per_vpc
Resource instance aws_servicequotas_service_quota.max_ipv4_per_vpc has been successfully untainted.

$ terraform apply
aws_servicequotas_service_quota.max_ipv4_per_vpc: Refreshing state... [id=vpc/ L-83CA0A9D]

Error: error getting Service Quotas Service Quota (vpc/ L-83CA0A9D): ValidationException: 1 validation error detected: Value ' L-83CA0A9D' at 'quotaCode' failed to satisfy constraint: Member must satisfy regular expression pattern: [a-zA-Z][a-zA-Z0-9-]{1,128}
	status code: 400, request id: 90379c2a-4024-4e0f-939c-c06dd5807dc7
```

`terraform plan` has the same result

The resource can only be destroyed

Once fixing the `id` and `quota_code` in the tfstate, terraform apply works:

```
$ terraform apply
aws_servicequotas_service_quota.max_ipv4_per_vpc: Refreshing state... [id=vpc/L-83CA0A9D]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
-/+ destroy and then create replacement

Terraform will perform the following actions:

  # aws_servicequotas_service_quota.max_ipv4_per_vpc is tainted, so must be replaced
-/+ resource "aws_servicequotas_service_quota" "max_ipv4_per_vpc" {
      ~ adjustable     = true -> (known after apply)
      ~ arn            = "arn:aws:servicequotas:eu-west-2:XXXXXXXXXXXX:vpc/L-83CA0A9D" -> (known after apply)
      ~ default_value  = 5 -> (known after apply)
      ~ id             = "vpc/L-83CA0A9D" -> (known after apply)
      ~ quota_name     = "IPv4 CIDR blocks per VPC" -> (known after apply)
      + request_id     = (known after apply)
      + request_status = (known after apply)
      ~ service_name   = "Amazon Virtual Private Cloud (Amazon VPC)" -> (known after apply)
      ~ value          = 5 -> 20
        # (2 unchanged attributes hidden)
    }

Plan: 1 to add, 0 to change, 1 to destroy.

Do you want to perform these actions in workspace "quota-bug"?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: 
```

### Steps to Reproduce

Introduce whitespace into the `quota_code`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/servicequotas_service_quota

### PR DESCRIPTION
**Pull request by Stretch96**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

# Fix Quotas `service_code`/`quota_code` validation

Closes #17970

### CODE REVIEW

**Review by anGie44 — CHANGES_REQUESTED** [review]
Hi @Stretch96 , thank you for this PR! While the custom validation funcs look great and tests are fantastic, the current convention is to use the Terraform Plugin SDK's `validation` package's helper methods e.g. `validation.StringLenBetween()`. Apologies for not providing guidance beforehand!
 
So with that said, refactoring the 2 validationFuncs would be the best next step. To encompass the validation requirements we can use something like:
```go
ValidateFunc: validation.All(
    validation.StringLenBetween(1, 128),
    validation.StringMatch(regexp.MustCompile(`^[A-Za-z][A-Za-z0-9-]*$`), "must begin with a letter and contain only alphanumeric or hyphen characters"),
),
```
```go
ValidateFunc: validation.All(
    validation.StringLenBetween(1, 63),
    validation.StringMatch(regexp.MustCompile(`^[A-Za-z][A-Za-z0-9-]*$`), "must begin with a letter and contain only alphanumeric or hyphen characters"),
),
```
With this refactoring, the tests will no longer be needed as the validation package is unit testing in the SDK.

Reach out if you have questions :)

**Comment by Stretch96** [comment]
Cool cool, I'll refactor using those 👍

I just copied from the (I think) security group validations and tests

Maybe that'll be my next PR if they need refactoring too Lol

**Comment by anGie44** [comment]
Hi @Stretch96 👋 , circling back here since it's been some time since my initial review. If it's possible to edit your PR, I'll try to push up the requested changes to get this into an upcoming release. If not, let me know if you'll be available to finish up the PR .. no worries if you can't at this time!

**Review by anGie44 — APPROVED** [review]
Thanks again @Stretch96 🚀 ! 

Output of acceptance tests:
```
--- SKIP: TestAccAwsServiceQuotasServiceQuota_Value_IncreaseOnCreate (0.00s)
--- SKIP: TestAccAwsServiceQuotasServiceQuota_Value_IncreaseOnUpdate (0.00s)
--- PASS: TestAccAwsServiceQuotasServiceQuotaDataSource_QuotaCode (12.99s)
--- PASS: TestAccAwsServiceQuotasServiceQuotaDataSource_QuotaName (15.00s)
--- PASS: TestAccAwsServiceQuotasServiceQuota_basic (17.13s)
```

**Pull request merged**
