### PR TITLE
Enhancement: add `copy_tags_to_snapshot` argument to resource/`aws_docdb_cluster_instance`

### LINKED ISSUE #31018: [Enhancement]: copy_tags_to_snapshot on docdb_cluster_instance
### Description

Add copy_tags_to_snapshot to aws_docdb_cluster_instance

### Affected Resource(s) and/or Data Source(s)

aws_docdb_cluster_instance

### Potential Terraform Configuration

```terraform
resource "aws_docdb_cluster_instance" "cluster_instances" {
  count                 = 2
  identifier            = "docdb-cluster-demo-${count.index}"
  cluster_identifier    = aws_docdb_cluster.default.id
  instance_class        = "db.r5.large"
  copy_tags_to_snapshot = true
}
```

### References

https://docs.aws.amazon.com/documentdb/latest/developerguide/API_DBInstance.html

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by tamiros**
### Description

This PR adds the argument `copy_tags_to_snapshot` to the resource `aws_docdb_cluster_instance`.

This feature flag seems to be available/visible only via CLI, API and CloudFormation. Can't seem to find it in the Web Console.

### Relations

Closes #31018.

### Output from Acceptance Testing

```
make testacc TESTS='TestAccDocDBClusterInstance_copyTagsToSnapshot' PKG=docdb
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/docdb/... -v -count 1 -parallel 20 -run='TestAccDocDBClusterInstance_copyTagsToSnapshot'  -timeout 180m
=== RUN   TestAccDocDBClusterInstance_copyTagsToSnapshot
=== PAUSE TestAccDocDBClusterInstance_copyTagsToSnapshot
=== CONT  TestAccDocDBClusterInstance_copyTagsToSnapshot
--- PASS: TestAccDocDBClusterInstance_copyTagsToSnapshot (825.01s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/docdb      825.085s
```

### CODE REVIEW

**Comment by skoulouris-dpg** [comment]
👍

**Comment by DaanVleugels** [comment]
👍

**Comment by WaleedAshraf** [comment]
Hi,

Thanks for fixing this issue.
Can this be merged? Or is there rough timeline?

**Comment by Villaver** [comment]
👍

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccDocDBClusterInstance_' PKG=docdb ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/docdb/... -v -count 1 -parallel 3  -run=TestAccDocDBClusterInstance_ -timeout 720m
=== RUN   TestAccDocDBClusterInstance_basic
=== PAUSE TestAccDocDBClusterInstance_basic
=== RUN   TestAccDocDBClusterInstance_performanceInsights
=== PAUSE TestAccDocDBClusterInstance_performanceInsights
=== RUN   TestAccDocDBClusterInstance_az
=== PAUSE TestAccDocDBClusterInstance_az
=== RUN   TestAccDocDBClusterInstance_namePrefix
=== PAUSE TestAccDocDBClusterInstance_namePrefix
=== RUN   TestAccDocDBClusterInstance_generatedName
=== PAUSE TestAccDocDBClusterInstance_generatedName
=== RUN   TestAccDocDBClusterInstance_kmsKey
=== PAUSE TestAccDocDBClusterInstance_kmsKey
=== RUN   TestAccDocDBClusterInstance_disappears
=== PAUSE TestAccDocDBClusterInstance_disappears
=== RUN   TestAccDocDBClusterInstance_copyTagsToSnapshot
=== PAUSE TestAccDocDBClusterInstance_copyTagsToSnapshot
=== CONT  TestAccDocDBClusterInstance_basic
=== CONT  TestAccDocDBClusterInstance_generatedName
=== CONT  TestAccDocDBClusterInstance_az
--- PASS: TestAccDocDBClusterInstance_az (1069.26s)
=== CONT  TestAccDocDBClusterInstance_disappears
--- PASS: TestAccDocDBClusterInstance_basic (1088.30s)
=== CONT  TestAccDocDBClusterInstance_copyTagsToSnapshot
--- PASS: TestAccDocDBClusterInstance_generatedName (1127.13s)
=== CONT  TestAccDocDBClusterInstance_performanceInsights
--- PASS: TestAccDocDBClusterInstance_disappears (1092.69s)
=== CONT  TestAccDocDBClusterInstance_kmsKey
--- PASS: TestAccDocDBClusterInstance_copyTagsToSnapshot (1076.12s)
=== CONT  TestAccDocDBClusterInstance_namePrefix
--- PASS: TestAccDocDBClusterInstance_performanceInsights (1443.29s)
--- PASS: TestAccDocDBClusterInstance_kmsKey (1016.71s)
--- PASS: TestAccDocDBClusterInstance_namePrefix (1126.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/docdb	3296.191s
```

**Comment by ewbankkit** [comment]
@tamiros Thanks for the contribution :tada: :clap:.

**Pull request merged**
