### PR TITLE
New Service: EventBridge Pipes

### PR DESCRIPTION
**Pull request by roberth-k**
### Relations

Relates https://github.com/hashicorp/terraform-provider-aws/issues/28153

### Output from Acceptance Testing

```
n/a
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@roberth-k Thanks for the contribution :tada: :clap:.

**Comment by roberth-k** [comment]
> I can't find #28214 in the release notes of v4.46.0

Hi @roimor --

This PR adds internal service scaffolding rather than practitioner-facing changes, which is why it's not shown in the release notes.

Individual resources (such as `aws_pipes_pipe`) arrive as separate changes.

**Comment by roimor** [comment]
Thanks @roberth-k!!, when do you think we will be able to see the new practitioner-facing pipes resource?
Thanks again 🙏

**Comment by roberth-k** [comment]
> Thanks @roberth-k!!, when do you think we will be able to see the new practitioner-facing pipes resource?
> Thanks again 🙏

Hi @roimor --

Probably in about two weeks' time.

**Pull request merged**
