### PR TITLE
aws_ami_launch_permission: support group permissions

### LINKED ISSUE #11101: Missing public for aws_ami and aws_ami_from_instance
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently there's no way to mark created AMI image as available public. Proposal is to add `public` parameter that defaults to `false`. Setting to true would mark AMI public and accessible for all.

### New or Affected Resource(s)

* aws_ami
* aws_ami_from_instance
* aws_ami_copy (nice-to-have)

### Potential Terraform Configuration

```hcl
resource "aws_ami_from_instance" "my_ami" {
  name               = "my-ami"
  source_instance_id = aws_instance.ami_source.id
  public             = true
}
```

### PR DESCRIPTION
**Pull request by grahamc**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11101

```
$ time make fmt testacc TESTARGS='-run=TestAccAWSAMILaunchPermission'
==> Fixing source code with gofmt...
gofmt -s -w ./aws ./awsproviderlint/helper ./awsproviderlint/main.go ./awsproviderlint/passes
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAMILaunchPermission -timeout 180m
=== RUN   TestAccAWSAMILaunchPermission_Account_basic
=== PAUSE TestAccAWSAMILaunchPermission_Account_basic
=== RUN   TestAccAWSAMILaunchPermission_Group_basic
=== PAUSE TestAccAWSAMILaunchPermission_Group_basic
=== RUN   TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission
=== PAUSE TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission
=== RUN   TestAccAWSAMILaunchPermission_Group_Disappears_LaunchPermission
=== PAUSE TestAccAWSAMILaunchPermission_Group_Disappears_LaunchPermission
=== RUN   TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission_Public
=== PAUSE TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission_Public
=== RUN   TestAccAWSAMILaunchPermission_Account_Disappears_AMI
=== PAUSE TestAccAWSAMILaunchPermission_Account_Disappears_AMI
=== RUN   TestAccAWSAMILaunchPermission_Group_Disappears_AMI
=== PAUSE TestAccAWSAMILaunchPermission_Group_Disappears_AMI
=== CONT  TestAccAWSAMILaunchPermission_Account_basic
=== CONT  TestAccAWSAMILaunchPermission_Group_Disappears_AMI
=== CONT  TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission
=== CONT  TestAccAWSAMILaunchPermission_Group_Disappears_LaunchPermission
=== CONT  TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission_Public
=== CONT  TestAccAWSAMILaunchPermission_Account_Disappears_AMI
=== CONT  TestAccAWSAMILaunchPermission_Group_basic
--- PASS: TestAccAWSAMILaunchPermission_Group_Disappears_LaunchPermission (361.20s)
--- PASS: TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission (361.62s)
--- PASS: TestAccAWSAMILaunchPermission_Account_Disappears_LaunchPermission_Public (362.57s)
--- PASS: TestAccAWSAMILaunchPermission_Group_basic (366.17s)
--- PASS: TestAccAWSAMILaunchPermission_Account_basic (374.68s)
--- PASS: TestAccAWSAMILaunchPermission_Account_Disappears_AMI (404.18s)
--- PASS: TestAccAWSAMILaunchPermission_Group_Disappears_AMI (404.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	404.495s

real	6m55.521s
user	1m54.557s
sys	0m8.773s
```

### CODE REVIEW

**Comment by grahamc** [comment]
fwiw I've deployed this to my prod env via `curl -L https://github.com/hashicorp/terraform-provider-aws/pull/20677.patch > public-amis.patch` and:

```nix
pkgs.mkShell {
  buildInputs = [
    pkgs.awscli2
    pkgs.jq
    (pkgs.terraform_1_0.withPlugins (p: [
      (p.aws.overrideAttrs ({ patches ? [], ... }: {
        patches = patches ++ [ ./public-amis.patch ];
      }))
      p.local
    ]))
  ];
}
```

**Comment by grahamc** [comment]
One side effect of this PR is it causes `aws_ami`'s `public` attribute to change, which Terraform is a bit unhappy about:

```
Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_ami.ami["21.11pre311304.71b3d18-zfs-arm64"] has been changed
  ~ resource "aws_ami" "ami" {
        id                  = "ami-0ee39fc86f37d667b"
        name                = "21.11pre311304.71b3d18-zfs-arm64"
      ~ public              = true -> false
        tags                = {
            "architecture" = "arm64"
            "built"        = "2021-08-25T15:40:16Z"
            "os"           = "NixOS"
            "root_fs"      = "zfs"
        }
        # (14 unchanged attributes hidden)


        # (6 unchanged blocks hidden)
    }
  # aws_ami.ami["21.11pre311304.71b3d18-zfs-x86_64"] has been changed
  ~ resource "aws_ami" "ami" {
        id                  = "ami-063d1014ff68c9adf"
        name                = "21.11pre311304.71b3d18-zfs-x86_64"
      ~ public              = true -> false
        tags                = {
            "architecture" = "x86_64"
            "built"        = "2021-08-25T15:40:16Z"
            "os"           = "NixOS"
            "root_fs"      = "zfs"
        }
        # (14 unchanged attributes hidden)


        # (6 unchanged blocks hidden)
    }
```

I'm not totally sure what to do about that, if anything.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by ewbankkit** [comment]
This functionality has been rolled into #21694.

**Pull request closed without merging**
