### PR TITLE
Support for Redshift settings in DMS target endpoint

### LINKED ISSUE #13162: AWS DMS Endpoint - Support for redshift settings
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The resource `aws_dms_endpoint` when used as a target with an engine type of `redshift` needs a temporary s3 bucket when loading into redshift. An S3 bucket is by default created if one isn't specified. This follows the form dms-[hash]. Since the bucket wasn't managed by terraform, it isn't removed if system is destroyed and it may have default policies that are not what is desired.

The DMS endpoint for redshift can have a `redshift_settings` property that defines the bucket name to be used (as well as a path; allowing multiple DMS tasks to redshift to use the same bucket). However, the resource `aws_dms_endpoint` does not support these. Using the `extra_connection_attributes` does not work as an alternative.

### New or Affected Resource(s)

* aws_dms_endpoint

### Potential Terraform Configuration

```hcl
resource "aws_dms_endpoint" "target" {
   endpoint_id   = "${var.stack}-endpoint-target"
   endpoint_type = "target"
   engine_name   = "redshift"
   server_name   = var.redshift.dns_name
   port          = var.redshift.port
   database_name = var.redshift.database_name
   username      = var.redshift.master_username
   password      = var.redshift.master_password

   redshift_settings = {
      encryption_mode=SSE_S3
      bucket_folder=foo
      bucket_name=${aws_s3_bucket.this    .bucket};
      service_access_role_arn=${aws_iam_role.this.arn}"
}
```

### References

* [Redshift settings](https://docs.aws.amazon.com/dms/latest/APIReference/API_RedshiftSettings.html)
* [aws_dms_endpoint](https://www.terraform.io/docs/providers/aws/r/dms_endpoint.html) terraform documentation (other targets have settings but redshift does not).

### PR DESCRIPTION
**Pull request by toini**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13162

Output from acceptance testing:

```
$ make testacc TESTS=TestAccDMSEndpoint_redshift PKG=dms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_redshift' -timeout 180m
=== RUN   TestAccDMSEndpoint_redshift
=== PAUSE TestAccDMSEndpoint_redshift
=== CONT  TestAccDMSEndpoint_redshift
2021/11/19 16:32:56 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:33:08 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:08 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:08 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:33:10 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:10 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:13 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:13 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:14 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:33:16 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:16 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:33:19 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:33:22 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:33:33 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:33:44 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:33:55 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:34:06 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:34:17 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:34:28 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:34:39 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:34:50 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:35:00 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:35:11 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:35:22 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:35:33 [INFO] Reading Redshift Cluster Information: tftest
2021/11/19 16:35:42 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:42 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:42 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:35:45 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:45 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:48 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:48 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:48 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:35:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:55 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:55 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:55 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:35:57 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:35:57 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:03 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:09 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:09 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:09 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:11 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:11 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:16 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:16 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:16 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:18 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:18 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:20 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:30 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:30 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:30 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:32 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:32 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:34 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:34 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:34 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:36 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:36 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:42 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:42 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:42 [INFO] AWS Auth provider used: "EnvProvider"
2021/11/19 16:36:43 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:43 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:47 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:47 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2021/11/19 16:36:48 [INFO] AWS Auth provider used: "EnvProvider"
--- PASS: TestAccDMSEndpoint_redshift (301.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        301.849s
```

### CODE REVIEW

**Comment by Tiri1992** [comment]
When will this be merged?

**Comment by toini** [comment]
@Tiri1992 I guess we need to people to upvote it with 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to get priority. See https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md

**Comment by toini** [comment]
@ags2121 I'm using a custom build from this PR...

**Comment by ewbankkit** [comment]
@toini Thanks for the contribution :tada: :clap:.
I have rolled these changes into #25143.

**Pull request closed without merging**
