### PR TITLE
s/sagemaker Add support repository_auth_config in image_config

### PR DESCRIPTION
**Pull request by neitomic**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTS=TestAccSageMakerModel_primaryContainerPrivateDockerRegistry PKG=sagemaker
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerModel_primaryContainerPrivateDockerRegistry'  -timeout 180m
=== RUN   TestAccSageMakerModel_primaryContainerPrivateDockerRegistry
=== PAUSE TestAccSageMakerModel_primaryContainerPrivateDockerRegistry
=== CONT  TestAccSageMakerModel_primaryContainerPrivateDockerRegistry
--- PASS: TestAccSageMakerModel_primaryContainerPrivateDockerRegistry (50.18s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  53.342s

...
```

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by neitomic** [comment]
@DrFaust92  thanks for reviewing. Could you please help approve the workflows as well?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMakerModel_' PKG=sagemaker ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 2  -run=TestAccSageMakerModel_ -timeout 180m
=== RUN   TestAccSageMakerModel_basic
=== PAUSE TestAccSageMakerModel_basic
=== RUN   TestAccSageMakerModel_inferenceExecution
=== PAUSE TestAccSageMakerModel_inferenceExecution
=== RUN   TestAccSageMakerModel_tags
=== PAUSE TestAccSageMakerModel_tags
=== RUN   TestAccSageMakerModel_primaryContainerModelDataURL
=== PAUSE TestAccSageMakerModel_primaryContainerModelDataURL
=== RUN   TestAccSageMakerModel_primaryContainerHostname
=== PAUSE TestAccSageMakerModel_primaryContainerHostname
=== RUN   TestAccSageMakerModel_primaryContainerImage
=== PAUSE TestAccSageMakerModel_primaryContainerImage
=== RUN   TestAccSageMakerModel_primaryContainerEnvironment
=== PAUSE TestAccSageMakerModel_primaryContainerEnvironment
=== RUN   TestAccSageMakerModel_primaryContainerModeSingle
=== PAUSE TestAccSageMakerModel_primaryContainerModeSingle
=== RUN   TestAccSageMakerModel_containers
=== PAUSE TestAccSageMakerModel_containers
=== RUN   TestAccSageMakerModel_vpc
=== PAUSE TestAccSageMakerModel_vpc
=== RUN   TestAccSageMakerModel_primaryContainerPrivateDockerRegistry
=== PAUSE TestAccSageMakerModel_primaryContainerPrivateDockerRegistry
=== RUN   TestAccSageMakerModel_networkIsolation
=== PAUSE TestAccSageMakerModel_networkIsolation
=== RUN   TestAccSageMakerModel_disappears
=== PAUSE TestAccSageMakerModel_disappears
=== CONT  TestAccSageMakerModel_basic
=== CONT  TestAccSageMakerModel_primaryContainerModeSingle
--- PASS: TestAccSageMakerModel_primaryContainerModeSingle (36.40s)
=== CONT  TestAccSageMakerModel_primaryContainerHostname
--- PASS: TestAccSageMakerModel_basic (41.92s)
=== CONT  TestAccSageMakerModel_primaryContainerEnvironment
--- PASS: TestAccSageMakerModel_primaryContainerHostname (39.73s)
=== CONT  TestAccSageMakerModel_primaryContainerPrivateDockerRegistry
--- PASS: TestAccSageMakerModel_primaryContainerEnvironment (40.90s)
=== CONT  TestAccSageMakerModel_disappears
--- PASS: TestAccSageMakerModel_disappears (30.28s)
=== CONT  TestAccSageMakerModel_networkIsolation
--- PASS: TestAccSageMakerModel_primaryContainerPrivateDockerRegistry (39.26s)
=== CONT  TestAccSageMakerModel_primaryContainerImage
--- PASS: TestAccSageMakerModel_networkIsolation (36.99s)
=== CONT  TestAccSageMakerModel_tags
--- PASS: TestAccSageMakerModel_primaryContainerImage (39.50s)
=== CONT  TestAccSageMakerModel_primaryContainerModelDataURL
--- PASS: TestAccSageMakerModel_primaryContainerModelDataURL (40.71s)
=== CONT  TestAccSageMakerModel_vpc
--- PASS: TestAccSageMakerModel_tags (74.95s)
=== CONT  TestAccSageMakerModel_inferenceExecution
--- PASS: TestAccSageMakerModel_vpc (37.30s)
=== CONT  TestAccSageMakerModel_containers
--- PASS: TestAccSageMakerModel_inferenceExecution (34.05s)
--- PASS: TestAccSageMakerModel_containers (38.91s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	279.562s
```

**Comment by ewbankkit** [comment]
@neitomic Thanks for the contribution :tada: :clap:.

**Pull request merged**
