### PR TITLE
feat: Add missing functionality for AppFlow Custom Connector

### LINKED ISSUE #26780: AppFlow missing support for custom connectors
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.1.7
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v4.30.0
```

### Affected Resource(s)

* aws_appflow_connector_profile

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_appflow_connector_profile" "test" {
  name            = "salesforce_marketing_cloud"
  connector_type  = "CustomConnector"
  connection_mode = "Public"
  connector_label = "SalesforceMarketingCloud"
  connector_profile_config {
    connector_profile_credentials {
      custom_connector {
        authentication_type = "OAUTH2"
        oauth2 {
          client_id     = "testID"
          client_secret = "testSecret"
          oauth_request {
            redirect_uri = "https://test1234.rest.marketingcloudapis.com/"
          }
        }
      }
    }
    connector_profile_properties {
      custom_connector {
        oauth2_properties {
          oauth2_grant_type = "CLIENT_CREDENTIALS"
          token_url         = "https://test1234.auth.marketingcloudapis.com/v2/token"
        }
        profile_properties = {
          "instanceUrl" = "https://test1234.rest.marketingcloudapis.com/"
        }
      }
    }
  }
}

```

### Expected Behavior

Resource created according to documentation

### Actual Behavior

Error: creating AppFlow Connector Profile: ValidationException: connectorProfileConfig: properties/credentials is null for ConnectorType: CUSTOMCONNECTOR

Debug JSON

```json
{
    "connectionMode": "Public",
    "connectorLabel": "SalesforceMarketingCloud",
    "connectorProfileConfig": {
        "connectorProfileCredentials": {
            "CustomConnector": {
                "authenticationType": "OAUTH2"
            }
        },
        "connectorProfileProperties": {}
    },
    "connectorProfileName": "salesforce_marketing_cloud",
    "connectorType": "CustomConnector"
}

```

### Steps to Reproduce

1. `terraform apply`

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appflow_connector_profile#custom-connector-profile-credentials

* #26665 
* #26766

### PR DESCRIPTION
**Pull request by daniepett**
Adding functionality of AppFlow Custom Connector to match the docs. In the current state the Custom Connector resource always returns empty values and fails on create.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #26665
Closes #26780 

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Relates #26665

**Comment by dude0001** [comment]
What is needed to move this PR forward?

**Comment by johnr-odusa** [comment]
Would love to see this released.

**Comment by johnr-odusa** [comment]
What more is required for this to be merged?

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTARGS='-run=TestAccAppFlowConnectorProfile_' PKG=appflow

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20  -run=TestAccAppFlowConnectorProfile_ -timeout 180m
=== RUN   TestAccAppFlowConnectorProfile_basic
=== PAUSE TestAccAppFlowConnectorProfile_basic
=== RUN   TestAccAppFlowConnectorProfile_update
=== PAUSE TestAccAppFlowConnectorProfile_update
=== RUN   TestAccAppFlowConnectorProfile_disappears
=== PAUSE TestAccAppFlowConnectorProfile_disappears
=== CONT  TestAccAppFlowConnectorProfile_basic
=== CONT  TestAccAppFlowConnectorProfile_disappears
=== CONT  TestAccAppFlowConnectorProfile_update
--- PASS: TestAccAppFlowConnectorProfile_disappears (241.82s)
--- PASS: TestAccAppFlowConnectorProfile_update (251.30s)
--- PASS: TestAccAppFlowConnectorProfile_basic (298.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	301.382s
```

**Comment by johnsonaj** [comment]
@daniepett thanks for the contribution 👏🏾 🎉

**Pull request merged**
