### PR TITLE
Remove force new on eks vpc change

### PR DESCRIPTION
**Pull request by danquack**
### Description

Removes the force new components. The update api now allows for it.

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34090.

### References

https://aws.amazon.com/about-aws/whats-new/2023/10/amazon-eks-modification-cluster-subnets-security/
https://github.com/aws/containers-roadmap/issues/170

### Output from Acceptance Testing

```console
%  make testacc TESTS=TestAccEKSCluster_VPC_securityGroupIDs_update PKG=eks
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSCluster_VPC_securityGroupIDs_update'  -timeout 360m
=== RUN   TestAccEKSCluster_VPC_securityGroupIDs_update
=== PAUSE TestAccEKSCluster_VPC_securityGroupIDs_update
=== CONT  TestAccEKSCluster_VPC_securityGroupIDs_update
--- PASS: TestAccEKSCluster_VPC_securityGroupIDs_update (953.54s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/eks	956.809s
```

Note for maintainer:
Due to an API restriction, each of the API calls requires a different update call, which utilizes the provided timeout. I am unsure if this break convention, but the alternative approach is erroring out initially if more than one update is made. Open to either approach.

### CODE REVIEW

**Comment by danquack** [comment]
```
make testacc TESTS=TestAccEKSCluster_VPC_securityGroupIDs_update PKG=eks                                                                                                                    <aws:sandbox> <region:us-east-1>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSCluster_VPC_securityGroupIDs_update'  -timeout 360m
=== RUN   TestAccEKSCluster_VPC_securityGroupIDs_update
=== PAUSE TestAccEKSCluster_VPC_securityGroupIDs_update
=== CONT  TestAccEKSCluster_VPC_securityGroupIDs_update





    cluster_test.go:387: Step 3/3 error: Error running apply: exit status 1
        
        Error: updating EKS Cluster (tf-acc-test-1396362340970208905) VPC config: InvalidParameterException: Only one type of update can be allowed.
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "2fcb26f5-493d-4d18-ba27-38af9ca19145"
          },
          Message_: "Only one type of update can be allowed."
        }
        
          with aws_eks_cluster.test,
          on terraform_plugin_test.tf line 81, in resource "aws_eks_cluster" "test":
          81: resource "aws_eks_cluster" "test" {
        
```

I'm not sure how to fix this api error. Similar to https://github.com/aws/aws-cdk/issues/21439

**Comment by danquack** [comment]
```
make testacc TESTS=TestAccEKSCluster_VPC_securityGroupIDs_update PKG=eks                                                                                                                   
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 20 -run='TestAccEKSCluster_VPC_securityGroupIDs_update'  -timeout 360m
=== RUN   TestAccEKSCluster_VPC_securityGroupIDs_update
=== PAUSE TestAccEKSCluster_VPC_securityGroupIDs_update
=== CONT  TestAccEKSCluster_VPC_securityGroupIDs_update

    cluster_test.go:387: Step 3/3 error: Error running apply: exit status 1
        
        Error: updating EKS Cluster (tf-acc-test-1396362340970208905) VPC config: InvalidParameterException: Only one type of update can be allowed.
        {
          RespMetadata: {
            StatusCode: 400,
            RequestID: "2fcb26f5-493d-4d18-ba27-38af9ca19145"
          },
          Message_: "Only one type of update can be allowed."
        }
        
          with aws_eks_cluster.test,
          on terraform_plugin_test.tf line 81, in resource "aws_eks_cluster" "test":
          81: resource "aws_eks_cluster" "test" {
        
```

I'm not sure how to fix this api error. Similar to https://github.com/aws/aws-cdk/issues/21439

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEKSCluster_VPC\|TestAccEKSCluster_basic' PKG=eks ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/eks/... -v -count 1 -parallel 2  -run=TestAccEKSCluster_VPC\|TestAccEKSCluster_basic -timeout 360m
=== RUN   TestAccEKSCluster_basic
=== PAUSE TestAccEKSCluster_basic
=== RUN   TestAccEKSCluster_VPC_securityGroupIDs
=== PAUSE TestAccEKSCluster_VPC_securityGroupIDs
=== RUN   TestAccEKSCluster_VPC_securityGroupIDsAndSubnetIDs_update
=== PAUSE TestAccEKSCluster_VPC_securityGroupIDsAndSubnetIDs_update
=== RUN   TestAccEKSCluster_VPC_endpointPrivateAccess
=== PAUSE TestAccEKSCluster_VPC_endpointPrivateAccess
=== RUN   TestAccEKSCluster_VPC_endpointPublicAccess
=== PAUSE TestAccEKSCluster_VPC_endpointPublicAccess
=== RUN   TestAccEKSCluster_VPC_publicAccessCIDRs
=== PAUSE TestAccEKSCluster_VPC_publicAccessCIDRs
=== CONT  TestAccEKSCluster_basic
=== CONT  TestAccEKSCluster_VPC_endpointPrivateAccess
--- PASS: TestAccEKSCluster_basic (644.54s)
=== CONT  TestAccEKSCluster_VPC_publicAccessCIDRs
--- PASS: TestAccEKSCluster_VPC_endpointPrivateAccess (1479.10s)
=== CONT  TestAccEKSCluster_VPC_endpointPublicAccess
--- PASS: TestAccEKSCluster_VPC_publicAccessCIDRs (951.38s)
=== CONT  TestAccEKSCluster_VPC_securityGroupIDsAndSubnetIDs_update
--- PASS: TestAccEKSCluster_VPC_securityGroupIDsAndSubnetIDs_update (1507.49s)
=== CONT  TestAccEKSCluster_VPC_securityGroupIDs
--- PASS: TestAccEKSCluster_VPC_endpointPublicAccess (1344.08s)
--- PASS: TestAccEKSCluster_VPC_securityGroupIDs (625.32s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/eks        2841.829s
```

**Comment by ewbankkit** [comment]
@danquack Thanks for the contribution :tada: :clap:.

**Pull request merged**
