### PR TITLE
Fix expired statements during redshift-data state update

### LINKED ISSUE #25882: Refreshing aws_redshiftdata_statement after query result expires fails
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
terraform -v
Terraform v1.2.5
on darwin_arm64
+ provider registry.terraform.io/hashicorp/aws v4.22.0
+ provider registry.terraform.io/hashicorp/local v2.2.3
```

### Affected Resource(s)

* aws_redshiftdata_statement

### Terraform Configuration Files

```hcl
provider "aws" {
  profile = "my_aws_profile"
  region  = "us-east-1"
  assume_role {
    role_arn = "assumed_role_arn"
  }
}

data "local_file" "foo" {
  filename = "${path.module}/foo.sql"
}

resource "aws_redshiftdata_statement" "example" {
  cluster_identifier = "redshift_cluster"
  database           = "redshift_db"
  db_user            = "redshift_user"
  sql                = data.local_file.foo.content
}
```

### Expected Behavior

`terraform plan` should work correctly.

### Actual Behavior

`terraform plan` throws an error after the initial statement query result expires.

```
terraform plan
data.local_file.foo: Reading...
data.local_file.foo: Read complete after 0s [id=a20f78b1806718fc9b70c7b91fb7ba07f6b2dd46]
aws_redshiftdata_statement.example: Refreshing state... [id=284bfee4-49dc-4ad1-ac90-0bba0580d568]
╷
│ Error: reading Redshift Data Statement (284bfee4-49dc-4ad1-ac90-0bba0580d568): ValidationException: Could not retrieve the query result as it has expired after 1658071606.
│
│   with aws_redshiftdata_statement.example,
│   on main.tf line 17, in resource "aws_redshiftdata_statement" "example":
│   17: resource "aws_redshiftdata_statement" "example" {
│
╵
```

### Steps to Reproduce

1. `terraform apply`
2. wait until the query result expires (3 days, it looks like), or change id in state to an already expired query result id (this is what I did in order to test this).
3. `terraform plan`

### References

* #https://github.com/pulumi/pulumi-aws/issues/2055

### PR DESCRIPTION
**Pull request by rockpunk**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #25882

After a redshift data statement is created, `aws redshift-data describe-statement` will only return a result for a short period of time when refreshing terraform state.  After a while, it doesn't actually find the old statement, so terraform plan will fail trying to refresh the state: 

```console
❯ aws redshift-data describe-statement --id 346a11c9-9e89-476b-a68a-995a1d3f3a39

An error occurred (ValidationException) when calling the DescribeStatement operation: Could not retrieve the query result as it has expired after 1660423725.
```

This PR attempts to fix the issue by catching `ValidationExceptions` related to expired statements, and returning a dummy response that allows terraform state refresh to continue.

One impact of this change is that all expired statements will NOW BE REPLACED (the statements will be re-run) on next plan application.

If you don't want the statements to be re-run, use the `ignore_changes` lifecycle: 

```terraform

locals { 
  schemas = [ "schema1", "schema2", "schema3" ]
}

resource "aws_redshiftdata_statement" "create_schema" {
  for_each           = local.schemas
  cluster_identifier = "your-instance"
  database           = "yourdb"
  db_user            = "you"
  sql                = "create schema ${each.key}"

  lifecycle {
    ignore_changes = all
  }
}
```

Output from acceptance testing:

```
❯ make testacc TESTS=TestAccRedshiftDataStatement_basic PKG=redshiftdata
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/redshiftdata/... -v -count 1 -parallel 20 -run='TestAccRedshiftDataStatement_basic'  -timeout 180m
=== RUN   TestAccRedshiftDataStatement_basic
=== PAUSE TestAccRedshiftDataStatement_basic
=== CONT  TestAccRedshiftDataStatement_basic

--- PASS: TestAccRedshiftDataStatement_basic (332.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftdata	335.469s
```

### CODE REVIEW

**Comment by wolfm89** [comment]
Is there a reason why this doesn't get merged?

**Comment by rockpunk** [comment]
> Is there a reason why this doesn't get merged?

Probably a lack of community votes. I have raised this to our internal aws reps and will ping them again about it. In the meantime, future readers should continue to add a 👍 to the pr description above if they want this merged.

**Comment by ZMarouani** [comment]
please merge this , the `aws_redshiftdata_statement `resource is literally unusable !! or at least mention this in terraform documentation

**Comment by Lincon-Freitas** [comment]
Any news on this? It is a big issue!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRedshiftDataStatement_' PKG=redshiftdata ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/redshiftdata/... -v -count 1 -parallel 2  -run=TestAccRedshiftDataStatement_ -timeout 180m
=== RUN   TestAccRedshiftDataStatement_basic
=== PAUSE TestAccRedshiftDataStatement_basic
=== RUN   TestAccRedshiftDataStatement_workgroup
=== PAUSE TestAccRedshiftDataStatement_workgroup
=== CONT  TestAccRedshiftDataStatement_basic
=== CONT  TestAccRedshiftDataStatement_workgroup
--- PASS: TestAccRedshiftDataStatement_basic (505.04s)
--- PASS: TestAccRedshiftDataStatement_workgroup (621.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/redshiftdata	626.763s
```

**Comment by ewbankkit** [comment]
@rockpunk Thanks for the contribution :tada: :clap:.

**Pull request merged**
