### PR TITLE
feat: add new resource aws_ebs_snapshot_block_public_access

### LINKED ISSUE #34347: Block Public Sharing of Amazon EBS Snapshots
> Amazon Elastic Block Store (EBS) now supports Block Public Access for EBS Snapshots, an account-wide security setting that allows customers to block public sharing of EBS Snapshots in an AWS Region.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-elastic-block-store-public-access-ebs-snapshots/)
* [Blog post](https://aws.amazon.com/blogs/aws/new-block-public-sharing-of-amazon-ebs-snapshots/)

Requires [AWS SDK for Go v1.47.8](https://github.com/aws/aws-sdk-go/releases/tag/v1.47.8): https://github.com/hashicorp/terraform-provider-aws/pull/34332.

### New Resource(s)

* `aws_ebs_snapshot_block_public_access`

### PR DESCRIPTION
**Pull request by stefanfreitag**
### Description

Add a new resource allowing to block the public sharing of EBS snapshots.

### Relations

- Closes #34347 
- Closes #37436 
  The pull request created by  @obounaim  was moved into draft status a few days ago. I used it as starting point added a few bits here and there.
 

### References

#34347 contains links to the AWS announcement and blog posts

### Output from Acceptance Testing
```console
❯ make  testacc TESTS=TestAccEC2EBSSnapshotBlockPublicAccess_ PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EBSSnapshotBlockPublicAccess_'  -timeout 360m
=== RUN   TestAccEC2EBSSnapshotBlockPublicAccess_basic
=== PAUSE TestAccEC2EBSSnapshotBlockPublicAccess_basic
=== CONT  TestAccEC2EBSSnapshotBlockPublicAccess_basic
--- PASS: TestAccEC2EBSSnapshotBlockPublicAccess_basic (20.76s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        21.054s
```

### CODE REVIEW

**Comment by stefanfreitag** [comment]
One check is failing, but not sure what needs to  be fixed here.
 I checked the raw logs and noticed on unrelated resources
 ```plain
2024-08-01T18:46:23.5187111Z   [✖] https://docs.aws.amazon.com/transfer/latest/userguide/API_SftpConnectorConfig.html → Status: 404
2024-08-01T18:46:23.5187125Z 
2024-08-01T18:46:23.5187731Z   ERROR: 1 dead links found in website/docs/r/transfer_connector.html.markdown !
2024-08-01T18:46:23.5188701Z   [✖] https://docs.aws.amazon.com/transfer/latest/userguide/API_SftpConnectorConfig.html → Status: 404
 ```

**Comment by justinretzolk** [comment]
Hey @stefanfreitag 👋 Thank you for taking the time to raise this! I think there was a docs outage related to Transfer this morning that seemed like it could have been related, so I queued the job to re-run.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2EBSSnapshotBlockPublicAccess_' PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2EBSSnapshotBlockPublicAccess_ -timeout 360m
=== RUN   TestAccEC2EBSSnapshotBlockPublicAccess_basic
=== PAUSE TestAccEC2EBSSnapshotBlockPublicAccess_basic
=== CONT  TestAccEC2EBSSnapshotBlockPublicAccess_basic
--- PASS: TestAccEC2EBSSnapshotBlockPublicAccess_basic (24.73s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	29.896s
```

**Comment by ewbankkit** [comment]
@stefanfreitag Thanks for the contribution :tada: :clap:.

**Pull request merged**
