### PR TITLE
New resource: aws_cloudfront_cache_policy

### LINKED ISSUE #15172: Support for Brotli compression on Cloudfront
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have announced support for Brotli on Cloudfront: https://aws.amazon.com/about-aws/whats-new/2020/09/cloudfront-brotli-compression/ which in theory enables smaller file sizes, and is widely supported by Chrome and Firefox.

It would be great to be able to enable this across our CloudFront distributions.

### New or Affected Resource(s)

* aws_cloudfront_distribution

### Potential Terraform Configuration

Currently the default_cache_behavior just has `compress` with a boolean value:

```hcl
  default_cache_behavior {
    compress = true
}
```

Perhaps:

```hcl
  default_cache_behavior {
    compress = ['gzip', 'br']
}
```

would be better, if possible, to enable users to make a decision on which compression types to support? I'd personally be happy with just `compress = true` supporting both gzip and br, but I'm not sure if that's universal and would change existing distributions.

### References

* https://aws.amazon.com/about-aws/whats-new/2020/09/cloudfront-brotli-compression/
* https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/ServingCompressedFiles.html

### PR DESCRIPTION
**Pull request by roberth-k**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #14373
Closes #15172

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
FEATURES:
- **New Resource:** `aws_cloudfront_cache_policy`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsCloudFrontCachePolicy_'
==> Checking that code complies with gofmt requirements...
--- PASS: TestAccAwsCloudFrontCachePolicy_disappears (11.96s)
--- PASS: TestAccAwsCloudFrontCachePolicy_basic (29.12s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       30.577s
```

### CODE REVIEW

**Comment by akamac** [comment]
Any chance on getting this merged?

**Comment by ewbankkit** [comment]
@akamac Support for CloudFront Cache Policies is is on the [roadmap](https://github.com/terraform-providers/terraform-provider-aws/pull/15898) for the upcoming quarter.

**Comment by sdevope** [comment]
Please, any chance on moving this a bit, guys?

**Comment by ewbankkit** [comment]
This PR has been replaced by #17336.

**Pull request closed without merging**
