### PR TITLE
Fix for 35897

### LINKED ISSUE #35660: [Bug]: aws_elasticache_serverless_cache: ecpu_per_second without a limit block count changed from 1 to 0.
### Terraform Core Version

1.5.7

### AWS Provider Version

5.35.0

### Affected Resource(s)

aws_elasticache_serverless_cache

### Expected Behavior

Setting ecpu to 0 would mean unlimited

### Actual Behavior

Its set it to unlimited but I run into an error after apply

### Relevant Error/Panic Output Snippet

```shell
│ Error: Provider produced inconsistent result after apply
│ 
│ When applying changes to aws_elasticache_serverless_cache.nhb-redis-staging-1, provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected new value:
│ .cache_usage_limits[0].ecpu_per_second: block count changed from 1 to 0.
│ 
│ This is a bug in the provider, which should be reported in the provider's own issue tracker.
```

### Terraform Configuration Files

```
resource "aws_elasticache_serverless_cache" "xx-redis-staging-1" {
  engine = "redis"
  name   = "xx-redis-staging-1"
  cache_usage_limits {
    data_storage {
      maximum = 5
      unit    = "GB"
    }
    ecpu_per_second {
      maximum = 0
    }
  }
  daily_snapshot_time      = "09:00"
  description              = "Redis for xx Staging"
  major_engine_version     = "7"
  snapshot_retention_limit = 1
  security_group_ids = [aws_security_group.elasticache_sg.id]
  subnet_ids = ["subnet-xx","subnet-xx", "subnet-xx"]
  user_group_id = aws_elasticache_user_group.nhbGroup.user_group_id
}
```

### Steps to Reproduce

apply a aws_elasticache_serverless_cache resource with
    ecpu_per_second {
      maximum = 0
    }

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #35897: [Bug]: modification of cache_usage_limits (ecpu_per_second or data_storage maximum) in aws_elasticache_serverless_cache results in InvalidParameterCombination: Serverless Cache modifications only support modifying one field per request.
### Terraform Core Version

1.3.7

### AWS Provider Version

5.37.0

### Affected Resource(s)

* aws_elasticache_serverless_cache

### Expected Behavior

Modification of cache usage limits should be possible, in aws console modifing both limits of storage and ecpu at the same time works. 

In the module no modification is possible.

### Actual Behavior

plan:
`      ~ cache_usage_limits {

          ~ ecpu_per_second {
              ~ maximum = 1000 -> 2000
            }
`

result:
`InvalidParameterCombination: Serverless Cache modifications only support modifying one field per request.`

plan:
`      ~ cache_usage_limits {
          ~ data_storage {
              ~ maximum = 1 -> 2
                # (1 unchanged attribute hidden)
            }`
            
result:
`InvalidParameterCombination: Serverless Cache modifications only support modifying one field per request.`
            
            

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

resource "aws_elasticache_serverless_cache" "example" {
  engine = "redis"
  name   = "example"
  cache_usage_limits {
    data_storage {
      maximum = 10
      unit    = "GB"
    }
    ecpu_per_second {
      maximum = 5
    }
  }
  daily_snapshot_time      = "09:00"
  description              = "Test Server"
  kms_key_id               = aws_kms_key.test.arn
  major_engine_version     = "7"
  snapshot_retention_limit = 1
  security_group_ids       = [aws_security_group.test.id]
  subnet_ids               = aws_subnet.test[*].id
}

### Steps to Reproduce

- create a redis_serverless_module
- try to define or change cache_usage_limits

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by meetreks**
### Description

This change is for fixing the issue related to #35897 . The  issue arises due to cache usage limits updates were not being handled properly and hence had to fix it. 

### Relations

Closes #35897 
Closes #35660

### Output from Acceptance Testing

```console
[ec2-user@ip-172-31-29-38 terraform-provider-aws]$ make testacc PKG=elasticache TESTS=TestAccElastiCacheServerlessCache_update
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheServerlessCache_update'  -timeout 360m
=== RUN   TestAccElastiCacheServerlessCache_update
=== PAUSE TestAccElastiCacheServerlessCache_update
=== CONT  TestAccElastiCacheServerlessCache_update
--- PASS: TestAccElastiCacheServerlessCache_update (350.08s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        350.206s
[ec2-user@ip-172-31-29-38 terraform-provider-aws]$ make testacc PKG=elasticache TESTS=TestAccElastiCacheServerlessCache_updatesc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 20 -run='TestAccElastiCacheServerlessCache_updatesc'  -timeout 360m
=== RUN   TestAccElastiCacheServerlessCache_updatesc
=== PAUSE TestAccElastiCacheServerlessCache_updatesc
=== CONT  TestAccElastiCacheServerlessCache_updatesc
--- PASS: TestAccElastiCacheServerlessCache_updatesc (730.82s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        730.958s

...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @meetreks 👋 Thank you for another contribution! I was looking over the related issue and saw #35660 mentioned, but couldn't quite tell -- would this PR close that one as well?

**Comment by meetreks** [comment]
@justinretzolk yes it would.

**Comment by mshahmoradi87** [comment]
@justinretzolk any idea when this will be merged ?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccElastiCacheServerlessCache_' PKG=elasticache ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elasticache/... -v -count 1 -parallel 3  -run=TestAccElastiCacheServerlessCache_ -timeout 360m
=== RUN   TestAccElastiCacheServerlessCache_basic
=== PAUSE TestAccElastiCacheServerlessCache_basic
=== RUN   TestAccElastiCacheServerlessCache_basicRedis
=== PAUSE TestAccElastiCacheServerlessCache_basicRedis
=== RUN   TestAccElastiCacheServerlessCache_full
=== PAUSE TestAccElastiCacheServerlessCache_full
=== RUN   TestAccElastiCacheServerlessCache_fullRedis
=== PAUSE TestAccElastiCacheServerlessCache_fullRedis
=== RUN   TestAccElastiCacheServerlessCache_update
=== PAUSE TestAccElastiCacheServerlessCache_update
=== RUN   TestAccElastiCacheServerlessCache_updatesc
=== PAUSE TestAccElastiCacheServerlessCache_updatesc
=== RUN   TestAccElastiCacheServerlessCache_disappears
=== PAUSE TestAccElastiCacheServerlessCache_disappears
=== RUN   TestAccElastiCacheServerlessCache_tags
=== PAUSE TestAccElastiCacheServerlessCache_tags
=== CONT  TestAccElastiCacheServerlessCache_basic
=== CONT  TestAccElastiCacheServerlessCache_updatesc
=== CONT  TestAccElastiCacheServerlessCache_fullRedis
--- PASS: TestAccElastiCacheServerlessCache_basic (385.48s)
=== CONT  TestAccElastiCacheServerlessCache_tags
--- PASS: TestAccElastiCacheServerlessCache_fullRedis (422.55s)
=== CONT  TestAccElastiCacheServerlessCache_disappears
--- PASS: TestAccElastiCacheServerlessCache_updatesc (687.23s)
=== CONT  TestAccElastiCacheServerlessCache_update
--- PASS: TestAccElastiCacheServerlessCache_disappears (284.89s)
=== CONT  TestAccElastiCacheServerlessCache_full
--- PASS: TestAccElastiCacheServerlessCache_tags (453.47s)
=== CONT  TestAccElastiCacheServerlessCache_basicRedis
--- PASS: TestAccElastiCacheServerlessCache_full (407.71s)
--- PASS: TestAccElastiCacheServerlessCache_basicRedis (298.81s)
--- PASS: TestAccElastiCacheServerlessCache_update (457.70s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elasticache	1151.825s
```

**Comment by ewbankkit** [comment]
@meetreks Thanks for the contribution :tada: :clap:.

**Pull request merged**
