### PR TITLE
#13994: Attempt to allow usage of service principals for KMS grants.

### LINKED ISSUE #13994: aws_kms_grant doesn't accept service principals in grantee_principal fiend
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

0.12.28

### Affected Resource(s)

* aws_kms_grant

### Terraform Configuration Files

```
resource aws_kms_grant grant_input_sns {
   name              = "AllowCMKManagementToInputSNS"
   key_id            = aws_kms_key.cmk.key_id
   grantee_principal = "sns.amazonaws.com"
   operations        = ["Encrypt", "Decrypt"]
 }
```

### Debug Output

https://gist.github.com/arcones/7bc62c94ac8f66a0714683f549aa9939

### Expected Behavior

Service principals are accepted grantees in KMS grants, as per [AWS docs](https://docs.aws.amazon.com/kms/latest/developerguide/grants.html). The grant should have been created.

### Actual Behavior

It says:
`Error: "grantee_principal" doesn't look like a valid ARN ("^arn:[\\w-]+:([a-zA-Z0-9\\-])+:([a-z]{2}-(gov-)?[a-z]+-\\d{1})?:(\\d{12})?:(.*)$"): "sns.amazonaws.com"
`

### Steps to Reproduce

1. Create a KMS key 
2. Try to add a KMS grant like the above with any service principal instead of regular ARN with `terraform apply` command

### PR DESCRIPTION
**Pull request by RonaldTechnative**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13994

Output from acceptance testing:

```
ronald@Ronalds-MacBook-Pro terraform-provider-aws % make testacc TESTS=TestAccKMSGrant_service PKG=kms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 20 -run='TestAccKMSGrant_service'  -timeout 180m
=== RUN   TestAccKMSGrant_service
=== PAUSE TestAccKMSGrant_service
=== CONT  TestAccKMSGrant_service
--- PASS: TestAccKMSGrant_service (27.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kms        29.064s
ronald@Ronalds-MacBook-Pro terraform-provider-aws % make testacc TESTS=TestAccKMSGrant_basic PKG=kms  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kms/... -v -count 1 -parallel 20 -run='TestAccKMSGrant_basic'  -timeout 180m
=== RUN   TestAccKMSGrant_basic
=== PAUSE TestAccKMSGrant_basic
=== CONT  TestAccKMSGrant_basic
--- PASS: TestAccKMSGrant_basic (43.55s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kms        45.616s
ronald@Ronalds-MacBook-Pro terraform-provider-aws % go test github.com/hashicorp/terraform-provider-aws/internal/verify
ok      github.com/hashicorp/terraform-provider-aws/internal/verify     0.360s
ronald@Ronalds-MacBook-Pro terraform-provider-aws % go test github.com/hashicorp/terraform-provider-aws/internal/service/kms

ok      github.com/hashicorp/terraform-provider-aws/internal/service/kms        2.053s
...
```

### CODE REVIEW

**Comment by RonaldTechnative** [comment]
> Hey @RonaldTechnative 👋 Thank you very much for your contribution! At times, our maintainers need to make direct edits to pull requests in order to help get it ready to be merged. Your current settings do not allow maintainers to make such edits. To help facilitate this, update your pull request to allow such edits as described in GitHub's [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) documentation. (If you're using a fork owned by an organization, your organization may not allow you to change this setting. If that is the case, let us know.)

It appears that I'm unable to grant access to allow anyone here to push. I think we can work around by giving people write access to the forked repository which I'm ok with.

This is my first contribution so please let me know if I missed anything.

**Comment by im-dim** [comment]
Hello all,
When would it be released?
We are on v4.19.0 and can't grant access to encryption keys to services like "backup.us-east-1.amazonaws.com"...

**Comment by mad-it** [comment]
@ewbankkit sorry for pinging you directly, but it seems like you are the latest active contributor. 
Is there any way this fix can be reviewed/merged? Its a small validation fix.

**Comment by mad-it** [comment]
@RonaldTechnative there is a small fix that needs to be made in reading the resource on this line: https://github.com/hashicorp/terraform-provider-aws/pull/25360/files#diff-d07eb791766a340751ea762e950c2b06b06d77a6dcb7112209a365745c765e7dR330

The read operation also needs to use the new `ValidARNOrServicePrincipal`.

**Comment by nam054** [comment]
Hey @RonaldTechnative :wave: Given the permissions difficulties, I've opened a separate pull request that covers this and a couple of other minor changes. With that in mind, we'll close this one out in favor of that one. Thank you for taking the time to contribute; we really appreciate it!

**Pull request closed without merging**
