### PR TITLE
resource/aws_elasticache_replication_group: Add MultiAZ support

### LINKED ISSUE #13706: Elasticache Redis Multi AZ not enabled
Hi,

I am trying to get an Elasticache (Redis) instance up and running (cluster mode disabled) and for that I was starting with the first two examples from documentation: 
https://www.terraform.io/docs/providers/aws/r/elasticache_replication_group.html

but it seems that even if everything is provisioned and working, the Multi AZ is still Disabled. I have the Failover enabled. Any idea what is wrong? 

I am 90% sure I tried these two examples a few weeks ago and Multi AZ was enabled, as far as I remember. After having the cluster up & running I can enable Multi AZ from AWS console, but I would like to have it in terraform, of course.

Thank you very much!

Here is the code I am using:
~~~
resource "aws_elasticache_replication_group" "example-1" {
  automatic_failover_enabled    = true
  availability_zones            = ["eu-central-1a", "eu-central-1b"]
  replication_group_id          = "tf-rep-group-1"
  replication_group_description = "test description"
  node_type                     = "cache.t3.micro"
  number_cache_clusters         = 2
  parameter_group_name          = "default.redis5.0"
  port                          = 6379
}

resource "aws_elasticache_replication_group" "example-2" {
  automatic_failover_enabled    = true
  availability_zones            = ["eu-central-1a", "eu-central-1b"]
  replication_group_id          = "tf-rep-group-2"
  replication_group_description = "test description"
  node_type                     = "cache.t3.micro"
  number_cache_clusters         = 2
  parameter_group_name          = "default.redis5.0"
  port                          = 6379

  lifecycle {
    ignore_changes = ["number_cache_clusters"]
  }
}

resource "aws_elasticache_cluster" "replica" {
  count = 1

  cluster_id           = "tf-rep-group-1-${count.index}"
  replication_group_id = "${aws_elasticache_replication_group.example-2.id}"
}
~~~

And here are two screenshots after terraform created the resources:

ElastiCache Management Console 2020-06-10 16-18-43

ElastiCache Management Console 2020-06-10 16-09-37

### PR DESCRIPTION
**Pull request by goodspellar**
Closes #13706 

Add `multi_az_enabled` parameter to `aws_elasticache_replication_group` 

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13706 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_elasticache_replication_group: Add `multi_az` argument 
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by sc250024** [comment]
Possible to get this merged please? 🙏

**Comment by Type1J** [comment]
Please assign a reviewer to this PR, and get this PR merged. I'm stuck with hacks until then that I've been having to defend in code reviews.

**Comment by ankithriday** [comment]
Need this merged, don't want to have to do the provisioner workaround

**Comment by ppapishe** [comment]
hope this gets merged soon so that we do not have to use in-efficient workarounds

**Review by bflad — CHANGES_REQUESTED** [review]
Hi @goodspellar 👋 Apologies for the delayed review here and thank you for the contribution. Overall this is looking good.

This was going to be looked at next week as part of our [freshly updated Roadmap](https://github.com/terraform-providers/terraform-provider-aws/blob/master/ROADMAP.md#elasticache), but to jump ahead and give you something actionable now -- it looks like the only thing might be to create new testing (functions and configurations) instead of modifying the existing testing. Copy-paste-modify if fine/encouraged. This helps us ensure there are no regressions with existing functionality before we release it.

Please reach out if you have any questions or do not have time to adjust this. Should hopefully be a quick merge after that change. 👍

**Comment by goodspellar** [comment]
@bflad Thanks for the review, sorry it took me so long to get around to it, I have some free time this week to work on this. I updated the `TestAccAWSElasticacheReplicationGroup_multiAzInVpc` test because, as the name implies, it tests multi-az support. I will create new tests for the other two I updated, however, for the first one would you still like me to create a new test or can I update the existing?

**Comment by metroshica** [comment]
Could we get a review on this? Seems like it's a pretty popular request.

**Comment by sc250024** [comment]
Seriously, almost 8 months now.

**Pull request closed without merging**
