### PR TITLE
New resource: aws_ec2_transit_gateway_multicast_domain

### LINKED ISSUE #11120: Transit Gateway multicast support
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Transit Gateway now supports routing internet protocol (IP) multicast traffic between attached Amazon Virtual Private Cloud (VPC) connections.

### New or Affected Resource(s)

* `aws_ec2_transit_gateway_multicast_domain`

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2019/12/run-ip-multicast-workloads-aws-transit-gateway/).
[Blog post](https://aws.amazon.com/blogs/aws/aws-transit-gateway-adds-multicast-and-inter-regional-peering/).

Requires [AWS SDK v1.25.46](https://github.com/aws/aws-sdk-go/releases/tag/v1.25.46):
* https://github.com/terraform-providers/terraform-provider-aws/pull/11116

### PR DESCRIPTION
**Pull request by windy1**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11120 

### Description

This pull requests adds support for EC2 Transit Gateway Multicast Domains.

New resource: `aws_ec2_transit_gateway_multicast_domain`
Modified resource: `aws_ec2_transit_gateway`

> *Why didn't you create separate resources for members/sources/associations?*

Multicast groups and associations do not have unique identifiers, I looked to the route table and security group implementations as a reference for how I implemented these elements. I saw that the standalone route resource, fakes an ID for convenience, but I figured that could be implemented similarly down the line. For now, embedding these within the resource seemed like the most reasonable solution.

### TODO
* [x] Acceptance tests
* [x] Documentation

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
FEATURES:
* *New resource:* `aws_ec2_transit_gateway_multicast_domain` [GH-11474]
ENHANCEMENTS:
* resource/aws_ec2_transit_gateway: Add `multicast_support` argument
```

Output from acceptance testing:

```
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run TestAccAWSEc2TransitGatewayMulticastDomain -timeout 120m
=== RUN   TestAccAWSEc2TransitGatewayMulticastDomain_basic
=== PAUSE TestAccAWSEc2TransitGatewayMulticastDomain_basic
=== RUN   TestAccAWSEc2TransitGatewayMulticastDomain_disappears
=== PAUSE TestAccAWSEc2TransitGatewayMulticastDomain_disappears
=== RUN   TestAccAWSEc2TransitGatewayMulticastDomain_Tags
=== PAUSE TestAccAWSEc2TransitGatewayMulticastDomain_Tags
=== RUN   TestAccAWSEc2TransitGatewayMulticastDomain_Associations
=== PAUSE TestAccAWSEc2TransitGatewayMulticastDomain_Associations
=== RUN   TestAccAWSEc2TransitGatewayMulticastDomain_Groups
=== PAUSE TestAccAWSEc2TransitGatewayMulticastDomain_Groups
=== CONT  TestAccAWSEc2TransitGatewayMulticastDomain_basic
=== CONT  TestAccAWSEc2TransitGatewayMulticastDomain_Associations
=== CONT  TestAccAWSEc2TransitGatewayMulticastDomain_Groups
=== CONT  TestAccAWSEc2TransitGatewayMulticastDomain_Tags
=== CONT  TestAccAWSEc2TransitGatewayMulticastDomain_disappears
--- PASS: TestAccAWSEc2TransitGatewayMulticastDomain_Tags (273.25s)
--- PASS: TestAccAWSEc2TransitGatewayMulticastDomain_disappears (274.94s)
--- PASS: TestAccAWSEc2TransitGatewayMulticastDomain_basic (277.85s)
--- PASS: TestAccAWSEc2TransitGatewayMulticastDomain_Groups (640.97s)
--- PASS: TestAccAWSEc2TransitGatewayMulticastDomain_Associations (822.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	824.377s
```

### CODE REVIEW

**Comment by windy1** [comment]
Alright--I've removed the WIP from this PR; I believe it is ready for merge. Let me know if anything else is required!

**Comment by ryno75** [comment]
@bflad any ideas when we might expect this feature to land?

**Comment by chrisbnorman** [comment]
is there something blocking this getting merged out of interest, would be great to start using this.

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by stemcc** [comment]
This would be a great feature to finally have merged!

**Comment by windy1** [comment]
Rebased and updated for breaking change - would be nice to get some feedback soon as this PR has been open for quite some time. Thanks.

**Comment by smckay-signifyd** [comment]
I'm trying out this PR and ran into some odd behavior. Changing the subnets associated to a domain was reported failed by Terraform, but when I reran there was no diff and the AWS console agrees that the change happened. I think the error must be spurious if my change gets applied eventually.

The first diff:

```
~ resource "aws_ec2_transit_gateway_vpc_attachment" "attach" {
      id                                              = "tgw-attach-5"
    ~ subnet_ids                                      = [
        - "subnet-1",
        - "subnet-7",
        + "subnet-c",
        + "subnet-4",
        + "subnet-9",
        - "subnet-8",
        - "subnet-2",
        + "subnet-e",
      ]
      tags                                            = {}
      # (8 unchanged attributes hidden)
  }

~ resource "aws_ec2_transit_gateway_multicast_domain" "mcd" {
    ~ association        = [
        - {
            - subnet_ids                    = [
                - "subnet-1",
                - "subnet-7",
                - "subnet-8",
                - "subnet-2",
              ]
            - transit_gateway_attachment_id = "tgw-attach-5"
          },
        + {
            + subnet_ids                    = [
                + "subnet-c",
                + "subnet-4",
                + "subnet-9",
                + "subnet-e",
              ]
            + transit_gateway_attachment_id = "tgw-attach-5"
          },
      ]
      id                 = "tgw-mcast-domain-5"
      tags               = {}
      # (3 unchanged attributes hidden)
  }
```

And the terraform output:

```
aws_ec2_transit_gateway_vpc_attachment.attach: Modifying... [id=tgw-attach-5]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 10s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 20s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 30s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 40s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 50s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 1m0s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 1m10s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 1m20s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 1m30s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 1m40s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 1m50s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 2m0s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Still modifying... [id=tgw-attach-5, 2m10s elapsed]
aws_ec2_transit_gateway_vpc_attachment.attach: Modifications complete after 2m19s [id=tgw-attach-5]
aws_ec2_transit_gateway_multicast_domain.mcd: Modifying... [id=tgw-mcast-domain-5]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 10s elapsed]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 20s elapsed]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 30s elapsed]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 40s elapsed]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 50s elapsed]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 1m0s elapsed]
aws_ec2_transit_gateway_multicast_domain.mcd: Still modifying... [id=tgw-mcast-domain-5, 1m10s elapsed]

Error: error waiting for EC2 Transit Gateway Multicast Domain (tgw-mcast-domain-5) associations: received conflicting association states
```

**Comment by hodur** [comment]
@breathingdust Will this PR get reviewed anytime soon? 

@windy1 The logs for the failing terrafmt check have expired and are no longer available. Did you ever check what was wrong? There are some conflicts by now, is there any chance you'll get around to solving the conflicts and fixing the build?

**Comment by windy1** [comment]
This MR has been opened for well over a year now, without any kind of review. I have very little motivation to devote anymore time towards it lol.

**Comment by hodur** [comment]
I totally understand that. It's a shame that HashiCorp has been completely silent since January.

@breathingdust Can someone get around to reviewing this? Or can you at least say whether a review will happen?

**Comment by breathingdust** [comment]
Hi @hodur! 👋  We generally queue PRs for maintainer review based on upvotes on the Issue and Linked PRs. There is a little more detail on how the process works in our [FAQ](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/FAQ.md). 

Unfortunately this does mean that for some PR's without a lot of +1's, they can sit for some time. Merge conflicts will typically be solved by the maintainers at review time, we have no expectation for contributors to keep their PR's up to date as time goes on and it doesn't affect their prioritization.

**Comment by happosade** [comment]
@breathingdust Do you have any idea or guestimate on what might be the queue to main?

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by NetDevAutomate** [comment]
@windy1 If you aren't working on this PR, would you be willing to let me pick it up from where you left off?

**Comment by windy1** [comment]
Of course @NetDevAutomate, go for it.

**Comment by NetDevAutomate** [comment]
> Of course @NetDevAutomate, go for it.

@windy1 Thank you very much, very kind of you since you've done a lot on this already.

**Comment by NetDevAutomate** [comment]
Added PR https://github.com/hashicorp/terraform-provider-aws/pull/22756 with modified code. Final test results to follow shortly.

**Comment by ewbankkit** [comment]
Superseded by #22756.

**Comment by ewbankkit** [comment]
@windy1 Thanks for the contribution :tada: :clap:.

**Comment by NetDevAutomate** [comment]
> @windy1 Thanks for the contribution 🎉 👏.

+1 and for giving me permission to reuse much of your code. Very much appreciated as still quite new to contributing to the provider.

**Pull request closed without merging**
