### PR TITLE
resource/aws_iot_policy: Delete oldest policy version when max number of versions is reached

### LINKED ISSUE #9540: aws_iot_policy.X: VersionsLimitExceededException: The policy X already has the maximum number of versions (5)
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.14
provider.aws v2.21.1

### Affected Resource(s)

* aws_iot_policy

### Terraform Configuration Files

```hcl
terraform {}

provider "aws" {}

resource "aws_iot_policy" "test" {
  name = "testJean"

  policy = <<POLICY
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Effect": "Allow",
      "Action": "iot:Publish",
      "Resource": "arn:aws:iot:*:*:topic/topic6"
    }
  ]
}
POLICY
}
```

### Output

> 1 error occurred:
>         * aws_iot_policy.test: 1 error occurred:
>         * aws_iot_policy.test: VersionsLimitExceededException: The policy testJean already has the maximum number of versions (5)
>         status code: 409, request id: 34c184cc-b256-11e9-8ec0-a331a0a34c0e
> 

### Expected Behavior

I would expect the same behaviour as with aws_iam_policy. The oldest non-default policy version should be deleted to make room for the new one.

### Steps to Reproduce

Just copy and paste the TF configuration I posted above and run `terraform apply` six times. (You can change the topic number, for instance.)

### PR DESCRIPTION
**Pull request by jeandek**
* This change adds a function call that deletes the oldest non-default IoT policy version when the creation of a new version would result in a breach of the max number of versions (5).
* Note that due to a bug in the Go SDK (+ CLI + Python SDK), all versions of the policy have the same creation date. Thus, I could not use it to find the oldest version (like in the _aws_iam_policy_ resource) and I decided to use the version IDs instead.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9540.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/30314.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24979.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_iot_policy: Prune oldest non-default version of IoT policies when required to create a new version
```

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSIoTPolicy'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSIoTPolicy -timeout 120m
=== RUN   TestAccAWSIoTPolicy_basic
=== PAUSE TestAccAWSIoTPolicy_basic
=== RUN   TestAccAWSIoTPolicy_invalidJson
=== PAUSE TestAccAWSIoTPolicy_invalidJson
=== RUN   TestAccAWSIoTPolicy_update
=== PAUSE TestAccAWSIoTPolicy_update
=== CONT  TestAccAWSIoTPolicy_basic
=== CONT  TestAccAWSIoTPolicy_update
=== CONT  TestAccAWSIoTPolicy_invalidJson
--- PASS: TestAccAWSIoTPolicy_invalidJson (10.78s)
--- PASS: TestAccAWSIoTPolicy_basic (22.19s)
--- PASS: TestAccAWSIoTPolicy_update (109.06s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       109.101s
```

### CODE REVIEW

**Comment by jeandek** [comment]
The pull request's code is now working as expected and contains a proper acceptance test. However, it's rather long to run. This is most likely due to the number of steps in the test case, since we have to update the resource 6 times to replicate the issue/fix...

If there's some way to optimize it, I'm all ears and willing to learn !

**Comment by yerida** [comment]
When is this issue released?

**Comment by jeandek** [comment]
I'm not sure. I haven't had any feedback for over 6 months...

I'm not doing IoT work anymore, so I'm in no hurry I guess.

**Comment by ewbankkit** [comment]
@jeandek Thanks for the contribution :tada: :clap:.
This functionality has been included in #34329.

**Pull request closed without merging**
