### PR TITLE
F codecatalyst devenv

### LINKED ISSUE #31286: [New Service]: AWS Codecatalyst
### Description

Hi,

I am writing to request support for AWS Code Catalyst resources in Terraform. Currently, there is no support for Code Catalyst resources in Terraform, which makes it difficult to use Terraform to manage Code Catalyst projects.

Code Catalyst is a service that helps developers build, test, and deploy cloud applications more quickly and easily. It provides a number of features that can be helpful for Terraform users, such as:

    A centralized repository for storing Terraform modules and configurations
    A built-in CI/CD pipeline for testing and deploying Terraform code
    A set of tools for managing Terraform state

I believe that adding support for Code Catalyst resources to Terraform would be a valuable addition to the Terraform ecosystem. It would make it easier for Terraform users to take advantage of the features that Code Catalyst provides.

I would be happy to help with the development of this feature. Please let me know if you have any questions.

Thank you,
Stefen Orban

### Requested Resource(s) and/or Data Source(s)

aws_codecatalyst_Project
aws_codecatalyst_Space
aws_codecatalyst_AccessToken
aws_codecatalyst_SourceRepositoryBranch
aws_codecatalyst_DevEnvironment

### Potential Terraform Configuration

```terraform
resource "aws_codecatalyst_space" "default" {
  name = "Terraform CodeCatalyst"
  account_id = "111122223333"
}

resource "aws_codecatalyst_project" "default" {
  name = "My Terraform Project"
  space_id = aws_codecatalyst_space.default.id
}

resource "aws_codecatalyst_repo" "default" {
  name = "My Terraform Repository"
  project_id = aws_codecatalyst_project.default.id
  url = "https://github.com/my-username/my-terraform-repo"
}

resource "aws_codecatalyst_environment" "default" {
  name = "My Terraform Environment"
  project_id = aws_codecatalyst_project.default.id
  repo_id = aws_codecatalyst_repo.default.id
  compute_type = "t3.medium"
  memory = 512
  instance_count = 1
}
```

### References

go reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codecatalyst
sdk reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codecatalyst/

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by markoskandylis**
### Description

Adds support for CodeCatalyst Dev Environment

### Relations

Closes #31286

### References

go reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codecatalyst
sdk reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codecatalyst/

### Output from Acceptance Testing

```
$  make testacc TESTARGS='-run=TestAccCodeCatalystDevenvironment_' PKG=codecatalyst  ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/codecatalyst/... -v -count 1 -parallel 2  -run=TestAccCodeCatalystDevenvironment_ -timeout 180m
=== RUN   TestAccCodeCatalystDevenvironment_basic
=== PAUSE TestAccCodeCatalystDevenvironment_basic
=== RUN   TestAccCodeCatalystDevenvironment_withRepositories
=== PAUSE TestAccCodeCatalystDevenvironment_withRepositories
=== RUN   TestAccCodeCatalystDevenvironment_disappears
=== PAUSE TestAccCodeCatalystDevenvironment_disappears
=== CONT  TestAccCodeCatalystDevenvironment_basic
=== CONT  TestAccCodeCatalystDevenvironment_disappears
--- PASS: TestAccCodeCatalystDevenvironment_disappears (35.51s)
=== CONT  TestAccCodeCatalystDevenvironment_withRepositories
--- PASS: TestAccCodeCatalystDevenvironment_basic (39.53s)
--- PASS: TestAccCodeCatalystDevenvironment_withRepositories (353.36s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codecatalyst       392.338s

...
```

### CODE REVIEW

**Comment by markoskandylis** [comment]
hi @ewbankkit  do you want me to create a new pull request for this new service to fix all those conflics in a cleaner code?

**Comment by ewbankkit** [comment]
@markoskandylis Thanks for the contribution :tada: :clap:.
In general everything looks great.
I think we should rename the resource type to `aws_codecatalyst_dev_environment` to match the AWS CLI commands (e.g. [`aws codecatalyst list-dev-environments`](https://docs.aws.amazon.com/cli/latest/reference/codecatalyst/list-dev-environments.html)).

**Comment by markoskandylis** [comment]
@ewbankkit  thanks i will do this change tomorrow there are couple of more resources coming for this service as well :) thanks for the help :)

**Comment by markoskandylis** [comment]
make testacc TESTARGS='-run=TestAccCodeCatalystDevEnvironment_' PKG=codecatalyst  ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/codecatalyst/... -v -count 1 -parallel 3  -run=TestAccCodeCatalystDevEnvironment_ -timeout 180m
=== RUN   TestAccCodeCatalystDevEnvironment_basic
=== PAUSE TestAccCodeCatalystDevEnvironment_basic
=== RUN   TestAccCodeCatalystDevEnvironment_withRepositories
=== PAUSE TestAccCodeCatalystDevEnvironment_withRepositories
=== RUN   TestAccCodeCatalystDevEnvironment_disappears
=== PAUSE TestAccCodeCatalystDevEnvironment_disappears
=== CONT  TestAccCodeCatalystDevEnvironment_basic
=== CONT  TestAccCodeCatalystDevEnvironment_disappears
=== CONT  TestAccCodeCatalystDevEnvironment_withRepositories
--- PASS: TestAccCodeCatalystDevEnvironment_disappears (38.36s)
--- PASS: TestAccCodeCatalystDevEnvironment_basic (42.48s)
--- PASS: TestAccCodeCatalystDevEnvironment_withRepositories (374.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codecatalyst	377.520s

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCodeCatalystDevEnvironment_' PKG=codecatalyst 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/codecatalyst/... -v -count 1 -parallel 20  -run=TestAccCodeCatalystDevEnvironment_ -timeout 180m
=== RUN   TestAccCodeCatalystDevEnvironment_basic
=== PAUSE TestAccCodeCatalystDevEnvironment_basic
=== RUN   TestAccCodeCatalystDevEnvironment_withRepositories
=== PAUSE TestAccCodeCatalystDevEnvironment_withRepositories
=== RUN   TestAccCodeCatalystDevEnvironment_disappears
=== PAUSE TestAccCodeCatalystDevEnvironment_disappears
=== CONT  TestAccCodeCatalystDevEnvironment_basic
=== CONT  TestAccCodeCatalystDevEnvironment_disappears
=== CONT  TestAccCodeCatalystDevEnvironment_withRepositories
=== NAME  TestAccCodeCatalystDevEnvironment_disappears
    dev_environment_test.go:190: skipping acceptance testing: runtime error: invalid memory address or nil pointer dereference
=== NAME  TestAccCodeCatalystDevEnvironment_withRepositories
    dev_environment_test.go:190: skipping acceptance testing: runtime error: invalid memory address or nil pointer dereference
--- SKIP: TestAccCodeCatalystDevEnvironment_withRepositories (0.44s)
--- SKIP: TestAccCodeCatalystDevEnvironment_disappears (0.44s)
=== NAME  TestAccCodeCatalystDevEnvironment_basic
    dev_environment_test.go:190: skipping acceptance testing: runtime error: invalid memory address or nil pointer dereference
--- SKIP: TestAccCodeCatalystDevEnvironment_basic (0.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codecatalyst	6.013s
```

**Comment by ewbankkit** [comment]
@markoskandylis Thanks for the contribution :tada: :clap:.
Maintainers don't have the ability to test this.
I modified `testAccPreCheck` to skip the acceptance tests if no Amazon CodeCatalyst token is available.

**Pull request merged**
