### PR TITLE
[new service] applicationsignals

### LINKED ISSUE #37935: [New Service]: Amazon CloudWatch Application Signals
### Description

- [AWS Announcmenet](https://aws.amazon.com/about-aws/whats-new/2024/06/amazon-cloudwatch-application-signals-application-monitoring/)
- [Amazon CloudWatch Application Signals welcome docs](https://docs.aws.amazon.com/applicationsignals/latest/APIReference/Welcome.html)

### Requested Resource(s) and/or Data Source(s)

`aws_applicationsignals_`

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by GlennChia**
### Description

Create new service for Amazon CloudWatch Application Signals

### Relations

Closes #37935

### References

- AWS CLI V2 Command: `application-signals`. Ref: https://awscli.amazonaws.com/v2/documentation/api/latest/reference/application-signals/index.html
- Go V1 Package: `applicationsignals`. Ref: https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.53.21/service/applicationsignals
- Go V2 Package: `applicationsignals`. Ref: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/applicationsignals
- API reference: `Application Signals`. Ref: https://docs.aws.amazon.com/applicationsignals/latest/APIReference/API_Operations.html

### Output from Acceptance Testing

```console
% make test
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
make: Running unit tests...
go test -count 1 ./...  -timeout=5m
?       github.com/hashicorp/terraform-provider-aws     [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/acctest/const      [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/acctest/generate   [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/acctest/statecheck [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/attrmap    [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/acctest    0.411s
?       github.com/hashicorp/terraform-provider-aws/internal/experimental/sync  [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/framework  [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/acctestconsts     [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/allowsubcats      [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/attrconsts        [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/checknames        [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/customends        [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/issuelabels       [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/namescapslist     [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/prlabels  [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/serviceendpointtests      [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/servicelabels     [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/servicesemgrep    [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/tags/templates/v1 [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/tags/templates/v2 [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/generate/teamcity  [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/logging    [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/conns      2.113s
ok      github.com/hashicorp/terraform-provider-aws/internal/create     0.012s
ok      github.com/hashicorp/terraform-provider-aws/internal/enum       0.005s
ok      github.com/hashicorp/terraform-provider-aws/internal/envvar     0.002s
ok      github.com/hashicorp/terraform-provider-aws/internal/errs       0.008s
ok      github.com/hashicorp/terraform-provider-aws/internal/errs/fwdiag        0.008s
ok      github.com/hashicorp/terraform-provider-aws/internal/errs/sdkdiag       0.010s
ok      github.com/hashicorp/terraform-provider-aws/internal/experimental/depgraph      0.010s
ok      github.com/hashicorp/terraform-provider-aws/internal/flex       0.013s
ok      github.com/hashicorp/terraform-provider-aws/internal/framework/flex     0.027s
ok      github.com/hashicorp/terraform-provider-aws/internal/framework/types    0.015s
ok      github.com/hashicorp/terraform-provider-aws/internal/framework/validators       0.045s
ok      github.com/hashicorp/terraform-provider-aws/internal/function   0.487s
ok      github.com/hashicorp/terraform-provider-aws/internal/generate/common    0.021s
ok      github.com/hashicorp/terraform-provider-aws/internal/generate/namevaluesfilters 0.331s
ok      github.com/hashicorp/terraform-provider-aws/internal/generate/namevaluesfiltersv2       0.041s
ok      github.com/hashicorp/terraform-provider-aws/internal/json       0.022s
ok      github.com/hashicorp/terraform-provider-aws/internal/json/ujson 0.042s
ok      github.com/hashicorp/terraform-provider-aws/internal/maps       0.020s
?       github.com/hashicorp/terraform-provider-aws/internal/provider/fwprovider        [no test files]
ok      github.com/hashicorp/terraform-provider-aws/internal/provider   6.710s
ok      github.com/hashicorp/terraform-provider-aws/internal/retry      1.023s
ok      github.com/hashicorp/terraform-provider-aws/internal/sdkv2      0.039s
ok      github.com/hashicorp/terraform-provider-aws/internal/sdkv2/types        0.035s
ok      github.com/hashicorp/terraform-provider-aws/internal/sdkv2/types/nullable       0.027s
ok      github.com/hashicorp/terraform-provider-aws/internal/semver     0.014s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/accessanalyzer     2.876s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/account    3.084s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/acm        12.659s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/acmpca     12.820s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/amp        5.447s
?       github.com/hashicorp/terraform-provider-aws/internal/service/neptunegraph       [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema  [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/sweep/awsv1        [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/sweep/awsv2        [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/sweep/sdk  [no test files]
?       github.com/hashicorp/terraform-provider-aws/internal/sweep/framework    [no test files]
?       github.com/hashicorp/terraform-provider-aws/names/data  [no test files]
?       github.com/hashicorp/terraform-provider-aws/names/generate      [no test files]
?       github.com/hashicorp/terraform-provider-aws/version     [no test files]
panic: test timed out after 5m0s
running tests:
        TestAccAmplify_serial (4m57s)
        TestAccAmplify_serial/Branch (27s)
        TestAccAmplify_serial/Branch/tags (27s)

goroutine 221 [running]:
testing.(*M).startAlarm.func1()
        /usr/local/go/src/testing/testing.go:2366 +0x385
created by time.goFunc
        /usr/local/go/src/time/sleep.go:177 +0x2d

goroutine 1 [chan receive, 4 minutes]:
testing.tRunner.func1()
        /usr/local/go/src/testing/testing.go:1650 +0x4ab
testing.tRunner(0xc0046a9d40, 0xc0031ffc70)
        /usr/local/go/src/testing/testing.go:1695 +0x134
testing.runTests(0xc003d8a360, {0x1ebda1e0, 0x2, 0x2}, {0x1?, 0x51898e?, 0x1ec0dfc0?})
        /usr/local/go/src/testing/testing.go:2159 +0x445
testing.(*M).Run(0xc000098a00)
        /usr/local/go/src/testing/testing.go:2027 +0x68b
main.main()
        _testmain.go:51 +0x16c

goroutine 54 [chan receive]:
testing.(*T).Run(0xc00472a000, {0x139eb07f?, 0xc0001cdda8?}, 0xc001ba08a0)
        /usr/local/go/src/testing/testing.go:1750 +0x3ab
github.com/hashicorp/terraform-provider-aws/internal/acctest.RunSerialTests2Levels(0xc00472a000, 0xc0001cdf30, 0x3edd410c00)
        /terraform-provider-aws/internal/acctest/acctest.go:2633 +0x9a
github.com/hashicorp/terraform-provider-aws/internal/service/amplify_test.TestAccAmplify_serial(0xc00472a000)
        /terraform-provider-aws/internal/service/amplify/amplify_test.go:59 +0x8fa
testing.tRunner(0xc00472a000, 0x13d5e4a8)
        /usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 1
        /usr/local/go/src/testing/testing.go:1742 +0x390

goroutine 200 [chan receive]:
testing.(*T).Run(0xc002a6f380, {0x139e7aa6?, 0xc0001f7ed8?}, 0xc001ba0a20)
        /usr/local/go/src/testing/testing.go:1750 +0x3ab
github.com/hashicorp/terraform-provider-aws/internal/acctest.RunSerialTests1Level(0xc002a6f380, 0xc002a67050, 0x3edd410c00)
        /terraform-provider-aws/internal/acctest/acctest.go:2620 +0x9a
github.com/hashicorp/terraform-provider-aws/internal/acctest.RunSerialTests2Levels.func1(0xc002a6f380?)
        /terraform-provider-aws/internal/acctest/acctest.go:2634 +0x1b
testing.tRunner(0xc002a6f380, 0xc001ba08a0)
        /usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 54
        /usr/local/go/src/testing/testing.go:1742 +0x390

goroutine 203 [sleep]:
time.Sleep(0x3edd410c00)
        /usr/local/go/src/runtime/time.go:195 +0x115
github.com/hashicorp/terraform-provider-aws/internal/acctest.RunSerialTests1Level.func1(0xc002a6fa00?)
       /terraform-provider-aws/internal/acctest/acctest.go:2622 +0x2c
testing.tRunner(0xc002a6fa00, 0xc001ba0a20)
        /usr/local/go/src/testing/testing.go:1689 +0xfb
created by testing.(*T).Run in goroutine 200
        /usr/local/go/src/testing/testing.go:1742 +0x390
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/amplify    300.329s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apigateway 11.220s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apigatewayv2       9.905s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling     3.777s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appconfig  2.865s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appfabric  3.068s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appflow    3.125s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appintegrations    3.722s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/applicationinsights        2.857s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/applicationsignals 3.082s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appmesh    2.773s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apprunner  2.884s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appstream  2.727s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appsync    2.943s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/athena     3.066s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/auditmanager       2.663s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling        2.812s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/autoscalingplans   2.589s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/backup     2.457s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/batch      4.556s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/bcmdataexports     2.527s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/bedrock    2.568s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/bedrockagent       2.622s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/budgets    2.847s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ce 3.829s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/chatbot    2.740s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/chime      2.841s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/chimesdkmediapipelines     2.618s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/chimesdkvoice      2.770s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cleanrooms 2.691s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloud9     2.633s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudcontrol       3.893s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudformation     3.024s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront 4.686s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudfrontkeyvaluestore    0.310s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudhsmv2 3.775s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudsearch        2.773s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail 2.738s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch 2.864s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codeartifact       2.661s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codebuild  2.841s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codecatalyst       0.400s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codecommit 2.713s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codeguruprofiler   2.525s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codegurureviewer   2.636s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline       2.578s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codestarconnections        2.567s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/codestarnotifications      2.643s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidentity    2.539s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cognitoidp 3.871s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/comprehend 2.808s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/computeoptimizer   2.753s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/configservice      3.338s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    2.842s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connectcases       2.657s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/controltower       2.793s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/costoptimizationhub        2.789s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cur        3.615s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/customerprofiles   3.124s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dataexchange       2.598s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datapipeline       2.609s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datasync   3.059s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/datazone   2.734s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dax        2.733s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/deploy     3.780s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/detective  2.578s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/devicefarm 2.781s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/devopsguru 2.801s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/directconnect      2.849s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dlm        2.794s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        4.616s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/docdb      2.842s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/docdbelastic       2.640s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/drs        2.669s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ds 6.965s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb   4.343s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        21.907s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        2.483s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecrpublic  2.626s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecs        5.297s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/efs        3.115s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/eks        2.799s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        5.118s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticbeanstalk   3.571s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticsearch      5.027s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elastictranscoder  2.704s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elb        7.887s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      20.801s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/emr        5.201s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/emrcontainers      3.014s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/emrserverless      2.724s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/events     5.456s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/evidently  3.861s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/finspace   2.845s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/firehose   5.964s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fis        2.538s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fms        2.551s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fsx        2.844s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/gamelift   2.714s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glacier    2.695s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/globalaccelerator  2.684s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       2.969s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/grafana    4.858s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/greengrass 2.358s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/groundstation      2.525s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/guardduty  4.943s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/healthlake 2.557s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        15.234s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/identitystore      3.063s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder       2.686s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/inspector  2.610s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/inspector2 5.054s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/internetmonitor    2.521s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iot        3.740s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iotanalytics       2.730s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iotevents  2.556s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ivs        2.621s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ivschat    2.740s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      3.706s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafkaconnect       2.789s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kendra     2.785s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/keyspaces  2.581s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesis    2.896s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalytics   2.682s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesisanalyticsv2 2.703s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesisvideo       2.700s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kms        2.642s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lakeformation      2.699s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lambda     2.649s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/launchwizard       2.486s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lexmodels  5.868s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lexv2models        6.442s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/licensemanager     2.630s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lightsail  2.601s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/location   3.815s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/logs       4.684s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lookoutmetrics     2.741s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/m2 2.621s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/macie2     2.497s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediaconnect       2.506s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediaconvert       2.703s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/medialive  2.529s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediapackage       2.567s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediapackagev2     2.356s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mediastore 2.392s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/memorydb   2.380s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/meta       0.329s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mq 2.578s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/mwaa       0.319s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/neptune    2.608s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall    2.635s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager     2.736s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/oam        3.504s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearch 3.420s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless       2.682s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opsworks   2.603s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/organizations      2.543s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/osis       3.420s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/outposts   2.463s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/paymentcryptography        0.372s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pcaconnectorad     2.298s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint   2.281s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pipes      2.617s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/polly      2.411s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pricing    2.432s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/qbusiness  2.341s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/qldb       2.611s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 2.829s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ram        2.591s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rbin       3.419s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        5.464s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshift   4.969s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshiftdata       3.488s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/redshiftserverless 5.226s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rekognition        2.861s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourceexplorer2  2.525s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups     2.589s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroupstaggingapi   3.601s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rolesanywhere      4.526s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53    2.964s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53domains     2.638s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53recoverycontrolconfig       2.625s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53recoveryreadiness   2.825s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53resolver    2.697s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rum        3.761s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3 11.107s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3control  0.378s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/s3outposts 2.900s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  2.649s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/scheduler  2.683s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/schemas    2.562s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager     2.631s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/securityhub        4.405s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/securitylake       2.710s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/serverlessrepo     4.571s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog     2.558s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry  3.467s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicediscovery   2.824s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicequotas      2.751s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ses        2.616s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sesv2      3.487s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sfn        3.685s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/shield     2.658s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/signer     2.564s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/simpledb   3.785s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sns        2.735s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sqs        2.777s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssm        2.330s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssmcontacts        2.135s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssmincidents       2.069s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssmsap     2.016s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sso        2.034s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ssoadmin   2.005s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/storagegateway     1.892s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sts        2.847s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/swf        1.808s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/synthetics 1.691s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/timestreaminfluxdb 1.636s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/timestreamwrite    0.199s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/transcribe 2.264s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/transfer   4.160s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions        1.487s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice 1.544s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/waf        1.538s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/wafregional        1.451s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/wafv2      1.330s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/wellarchitected    1.213s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/worklink   1.228s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/workspaces 1.236s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/workspacesweb      1.193s
ok      github.com/hashicorp/terraform-provider-aws/internal/service/xray       1.214s
ok      github.com/hashicorp/terraform-provider-aws/internal/slices     0.004s
ok      github.com/hashicorp/terraform-provider-aws/internal/sweep      0.055s [no tests to run]
ok      github.com/hashicorp/terraform-provider-aws/internal/tags       0.017s
ok      github.com/hashicorp/terraform-provider-aws/internal/tfresource 5.628s
ok      github.com/hashicorp/terraform-provider-aws/internal/types      0.012s
ok      github.com/hashicorp/terraform-provider-aws/internal/types/duration     0.004s
ok      github.com/hashicorp/terraform-provider-aws/internal/types/option       0.007s
ok      github.com/hashicorp/terraform-provider-aws/internal/types/stack        0.007s
ok      github.com/hashicorp/terraform-provider-aws/internal/types/timestamp    0.004s
ok      github.com/hashicorp/terraform-provider-aws/internal/vault/helper/pgpkeys       0.847s
ok      github.com/hashicorp/terraform-provider-aws/internal/vault/sdk/helper/jsonutil  0.002s
ok      github.com/hashicorp/terraform-provider-aws/internal/verify     0.032s
ok      github.com/hashicorp/terraform-provider-aws/names       0.008s
FAIL
make: *** [test] Error 1
...
```

- Note: Error looks unrelated to changes

### CODE REVIEW

**Comment by GlennChia** [comment]
Question: Is there any advice on the value to set in `names.csv` for `SDKID`? Could not find any guidance from the contributing guides here
- https://breathingdust.github.io/terraform-provider-aws/add-a-new-service/
- https://breathingdust.github.io/terraform-provider-aws/naming/#service-identifier

**Comment by ewbankkit** [comment]
@ThomasZalewski I'll take this one; thanks.

**Comment by ewbankkit** [comment]
The failing unit tests should be fixed via https://github.com/hashicorp/aws-sdk-go-base/pull/1094.

**Comment by ewbankkit** [comment]
@GlennChia Thanks for the contribution :tada: :clap:.

**Review by breathingdust — APPROVED** [review]

**Pull request merged**
