### PR TITLE
New resource `aws_ec2_transit_gateway_policy_table` and `aws_ec2_transit_gateway_policy_table_association`

### LINKED ISSUE #26093: New resource: Transit Gateway policy table
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Transit gateway dynamic routing uses policy tables to route network traffic for AWS Cloud WAN.

### New or Affected Resource(s)

* `aws_ec2_transit_gateway_policy_table`
* `aws_ec2_transit_gateway_policy_table_association`

### Potential Terraform Configuration

```hcl
resource "aws_ec2_transit_gateway_policy_table" "example" {
  transit_gateway_id = aws_ec2_transit_gateway.example.id
}

resource "aws_ec2_transit_gateway_policy_table_association" "example" {
  transit_gateway_policy_table_id = aws_ec2_transit_gateway_policy_table.example.id
  transit_gateway_attachment_id   = aws_ec2_transit_gateway_vpc_attachment.example.id
}
```

### References

Relates https://github.com/hashicorp/terraform-provider-aws/issues/25835.
[User Guide](https://docs.aws.amazon.com/vpc/latest/tgw/tgw-policy-tables.html).
[API reference](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateTransitGatewayPolicyTable.html).

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #26093.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26222.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/25835.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccTransitGatewayPolicyTable_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccTransitGatewayPolicyTable_'  -timeout 180m
=== RUN   TestAccTransitGatewayPolicyTable_basic
--- PASS: TestAccTransitGatewayPolicyTable_basic (214.53s)
=== RUN   TestAccTransitGatewayPolicyTable_disappears
--- PASS: TestAccTransitGatewayPolicyTable_disappears (193.38s)
=== RUN   TestAccTransitGatewayPolicyTable_disappears_TransitGateway
--- PASS: TestAccTransitGatewayPolicyTable_disappears_TransitGateway (208.86s)
=== RUN   TestAccTransitGatewayPolicyTable_Tags
--- PASS: TestAccTransitGatewayPolicyTable_Tags (206.53s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        825.031s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Almost ready for review - busy figuring out the resources I need to create for the `aws_ec2_transit_gateway_policy_table_association` tests.

**Comment by ewbankkit** [comment]
The TGW association ID for the Policy Table association is the Core Network Transit Gateway Peering Attachment ID, now [made available](https://github.com/aws/aws-sdk-go/commit/b28bc2fb2763de116b097ba97ea2834f38280be5#diff-54dec482e56983b896d372f3b29b330f4bfc283de14ad4baad55a621ae607232) in [AWS SDK for Go v1.44.80](https://github.com/aws/aws-sdk-go/releases/tag/v1.44.80).

**Comment by ewbankkit** [comment]
##### TODO

* `aws_networkmanager_transit_gateway_route_table_attachment` tests
* `aws_ec2_transit_gateway_policy_table_association` tests failing:
```console
% make testacc TESTARGS='-run=TestAccTransitGateway_serial/PolicyTableAssociation' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccTransitGateway_serial/PolicyTableAssociation -timeout 180m
=== RUN   TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation/basic
    transitgateway_policy_table_association_test.go:24: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating EC2 Transit Gateway Policy Table Association (tgw-ptb-0efaa494af10fe4bc_tgw-attach-01b775162fbdc77af): IncorrectState: Cannot have both PolicyTableAssociation and RouteTableAssociation on the same TransitGateway Attachment: tgw-attach-01b775162fbdc77af
        	status code: 400, request id: 4671a2b0-18a3-48b3-a7dd-2e7754c0e067
        
          with aws_ec2_transit_gateway_policy_table_association.test,
          on terraform_plugin_test.tf line 55, in resource "aws_ec2_transit_gateway_policy_table_association" "test":
          55: resource "aws_ec2_transit_gateway_policy_table_association" "test" {
        
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation/disappears
    transitgateway_policy_table_association_test.go:54: Step 1/1 error: Error running apply: exit status 1
        
        Error: creating EC2 Transit Gateway Policy Table Association (tgw-ptb-0851ac8b6c2094a7a_tgw-attach-027fe679d0b1e8052): IncorrectState: Cannot have both PolicyTableAssociation and RouteTableAssociation on the same TransitGateway Attachment: tgw-attach-027fe679d0b1e8052
        	status code: 400, request id: 32cf1996-718d-4e56-9401-13d90cea9ed1
        
          with aws_ec2_transit_gateway_policy_table_association.test,
          on terraform_plugin_test.tf line 55, in resource "aws_ec2_transit_gateway_policy_table_association" "test":
          55: resource "aws_ec2_transit_gateway_policy_table_association" "test" {
        
--- FAIL: TestAccTransitGateway_serial (2705.07s)
    --- FAIL: TestAccTransitGateway_serial/PolicyTableAssociation (2705.07s)
        --- FAIL: TestAccTransitGateway_serial/PolicyTableAssociation/basic (1346.42s)
        --- FAIL: TestAccTransitGateway_serial/PolicyTableAssociation/disappears (1358.66s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	2711.107s
FAIL
make: *** [testacc] Error 1
```
* Revisit `aws_ec2_transit_gateway_policy_table_association` documentation

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccNetworkManagerTransitGatewayRouteTableAttachment_' PKG=networkmanager ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 2  -run=TestAccNetworkManagerTransitGatewayRouteTableAttachment_ -timeout 180m
=== RUN   TestAccNetworkManagerTransitGatewayRouteTableAttachment_basic
=== PAUSE TestAccNetworkManagerTransitGatewayRouteTableAttachment_basic
=== RUN   TestAccNetworkManagerTransitGatewayRouteTableAttachment_disappears
=== PAUSE TestAccNetworkManagerTransitGatewayRouteTableAttachment_disappears
=== RUN   TestAccNetworkManagerTransitGatewayRouteTableAttachment_tags
=== PAUSE TestAccNetworkManagerTransitGatewayRouteTableAttachment_tags
=== CONT  TestAccNetworkManagerTransitGatewayRouteTableAttachment_basic
--- PASS: TestAccNetworkManagerTransitGatewayRouteTableAttachment_tags (1973.85s)
=== CONT  TestAccNetworkManagerTransitGatewayRouteTableAttachment_disappears
--- PASS: TestAccNetworkManagerTransitGatewayRouteTableAttachment_basic (2113.93s)
--- PASS: TestAccNetworkManagerTransitGatewayRouteTableAttachment_disappears (1678.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	3345.295s
% make testacc TESTARGS='-run=TestAccTransitGateway_serial/PolicyTableAssociation/basic' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccTransitGateway_serial/PolicyTableAssociation/basic -timeout 180m
=== RUN   TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation/basic
--- PASS: TestAccTransitGateway_serial (1388.22s)
    --- PASS: TestAccTransitGateway_serial/PolicyTableAssociation (1388.22s)
        --- PASS: TestAccTransitGateway_serial/PolicyTableAssociation/basic (1388.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1392.618s
% make testacc TESTARGS='-run=TestAccTransitGateway_serial/PolicyTableAssociation/disappears' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccTransitGateway_serial/PolicyTableAssociation/disappears -timeout 180m
=== RUN   TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation/disappears
--- PASS: TestAccTransitGateway_serial (1450.77s)
    --- PASS: TestAccTransitGateway_serial/PolicyTableAssociation (1450.77s)
        --- PASS: TestAccTransitGateway_serial/PolicyTableAssociation/disappears (1450.77s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1454.645s
% make testacc TESTARGS='-run=TestAccNetworkManagerTransitGatewayPeering_' PKG=networkmanager ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 2  -run=TestAccNetworkManagerTransitGatewayPeering_ -timeout 180m
=== RUN   TestAccNetworkManagerTransitGatewayPeering_basic
=== PAUSE TestAccNetworkManagerTransitGatewayPeering_basic
=== RUN   TestAccNetworkManagerTransitGatewayPeering_disappears
=== PAUSE TestAccNetworkManagerTransitGatewayPeering_disappears
=== RUN   TestAccNetworkManagerTransitGatewayPeering_tags
=== PAUSE TestAccNetworkManagerTransitGatewayPeering_tags
=== CONT  TestAccNetworkManagerTransitGatewayPeering_basic
=== CONT  TestAccNetworkManagerTransitGatewayPeering_tags
--- PASS: TestAccNetworkManagerTransitGatewayPeering_tags (1487.08s)
=== CONT  TestAccNetworkManagerTransitGatewayPeering_disappears
--- PASS: TestAccNetworkManagerTransitGatewayPeering_basic (1627.88s)
--- PASS: TestAccNetworkManagerTransitGatewayPeering_disappears (1279.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	2770.823s
% make testacc TESTARGS='-run=TestAccTransitGateway_serial/PolicyTable/basic' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccTransitGateway_serial/PolicyTable/basic -timeout 180m
=== RUN   TestAccTransitGateway_serial
=== RUN   TestAccTransitGateway_serial/PolicyTable
=== RUN   TestAccTransitGateway_serial/PolicyTable/basic
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation
=== RUN   TestAccTransitGateway_serial/PolicyTableAssociation/basic
--- PASS: TestAccTransitGateway_serial (1724.02s)
    --- PASS: TestAccTransitGateway_serial/PolicyTable (200.15s)
        --- PASS: TestAccTransitGateway_serial/PolicyTable/basic (200.15s)
    --- PASS: TestAccTransitGateway_serial/PolicyTableAssociation (1523.87s)
        --- PASS: TestAccTransitGateway_serial/PolicyTableAssociation/basic (1523.87s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1728.558s
```

**Pull request merged**
