### PR TITLE
r/memorydb_user: Support IAM authentication mode

### PR DESCRIPTION
**Pull request by exoego**
### Description
Allow IAM authentication support for `aws_memorydb_user`

### Relations
Closes https://github.com/hashicorp/terraform-provider-aws/issues/31528

### References

I've followed the styles in docs and implementation for `elasticache_user`  
- Doc:  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/elasticache_user#authentication_mode
- Impl: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elasticache/user.go

### Output from Acceptance Testing

```bash
$ make testacc TESTS=TestAccMemoryDBUser PKG=memorydb

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBUser'  -timeout 180m
=== RUN   TestAccMemoryDBUserDataSource_basic
=== PAUSE TestAccMemoryDBUserDataSource_basic
=== RUN   TestAccMemoryDBUserDataSource_iam
=== PAUSE TestAccMemoryDBUserDataSource_iam
=== RUN   TestAccMemoryDBUser_basic
=== PAUSE TestAccMemoryDBUser_basic
=== RUN   TestAccMemoryDBUser_iam_auth_mode
=== PAUSE TestAccMemoryDBUser_iam_auth_mode
=== RUN   TestAccMemoryDBUser_disappears
=== PAUSE TestAccMemoryDBUser_disappears
=== RUN   TestAccMemoryDBUser_update_accessString
=== PAUSE TestAccMemoryDBUser_update_accessString
=== RUN   TestAccMemoryDBUser_update_passwords
=== PAUSE TestAccMemoryDBUser_update_passwords
=== RUN   TestAccMemoryDBUser_tags
=== PAUSE TestAccMemoryDBUser_tags
=== CONT  TestAccMemoryDBUserDataSource_basic
=== CONT  TestAccMemoryDBUser_disappears
=== CONT  TestAccMemoryDBUser_update_passwords
=== CONT  TestAccMemoryDBUser_update_accessString
=== CONT  TestAccMemoryDBUser_tags
=== CONT  TestAccMemoryDBUser_basic
=== CONT  TestAccMemoryDBUser_iam_auth_mode
=== CONT  TestAccMemoryDBUserDataSource_iam
--- PASS: TestAccMemoryDBUser_disappears (47.06s)
--- PASS: TestAccMemoryDBUser_tags (92.96s)
--- PASS: TestAccMemoryDBUserDataSource_iam (97.35s)
--- PASS: TestAccMemoryDBUserDataSource_basic (97.57s)
--- PASS: TestAccMemoryDBUser_iam_auth_mode (102.17s)
--- PASS: TestAccMemoryDBUser_basic (102.85s)
--- PASS: TestAccMemoryDBUser_update_accessString (164.18s)
--- PASS: TestAccMemoryDBUser_update_passwords (222.22s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/memorydb   225.004s
```

### CODE REVIEW

**Comment by bigwheels16** [comment]
What needs to happen for this to get merged in?

**Comment by GilUpstream** [comment]
We're needing this support for our current project. Anything I can do to help get this merged in?

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=memorydb TESTS="TestAccMemoryDBUser|TestAccMemoryDBUserDataSource"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/memorydb/... -v -count 1 -parallel 20 -run='TestAccMemoryDBUser|TestAccMemoryDBUserDataSource'  -timeout 360m

--- PASS: TestAccMemoryDBUser_tags (45.96s)
--- PASS: TestAccMemoryDBUserDataSource_authenticationModeIAM (49.38s)
--- PASS: TestAccMemoryDBUserDataSource_basic (49.38s)
--- PASS: TestAccMemoryDBUser_basic (52.16s)
--- PASS: TestAccMemoryDBUser_authenticationModeIAM (52.20s)
--- PASS: TestAccMemoryDBUser_disappears (58.02s)
--- PASS: TestAccMemoryDBUser_update_accessString (105.60s)
--- PASS: TestAccMemoryDBUser_update_passwords (173.49s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/memorydb   178.422s
```

**Comment by jar-b** [comment]
Thank you for your contribution, @exoego!

**Pull request merged**
