### PR TITLE
[New Resource] aws_servicecatalogappregistry_application

### PR DESCRIPTION
**Pull request by fatbasstard**
### Description
This PR adds a new resource: `aws_servicecatalogappregistry_application`

In AWS this is now also launched as `myApplications`([announcement](https://aws.amazon.com/about-aws/whats-new/2023/11/myapplications-view-manage-applications-aws/), [documentation](https://docs.aws.amazon.com/awsconsolehelpdocs/latest/gsg/aws-myApplications.html))

So the naming can be "confusing", since the application itself technically is a "Service Catalog App Registry Application" (and I wanted to stick with the naming convention). But to somehow make clear it's the base of `myApplication` added it as a note to the documentation (so it's clear and findable if you search for TF and myApplications)

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34702
Closes https://github.com/hashicorp/terraform-provider-aws/pull/35255.

### References

PR https://github.com/hashicorp/terraform-provider-aws/pull/35255 was created but I decided to recreate it for multiple reasons: This one uses Terraform Plugin SDK V2, naming convention is "off" and there has been no reaction from the author (and I want/need this feature to get insights on our platform).

There might be more options to the resource but this PR enables the core functionality to start implementing the `myApplications` feature.

Also planning to add a datasource later (in a separate PR)

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccServiceCatalogAppRegistryApplication_ PKG=servicecatalogappregistry 

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryApplication_'  -timeout 360m
=== RUN   TestAccServiceCatalogAppRegistryApplication_basic
=== PAUSE TestAccServiceCatalogAppRegistryApplication_basic
=== RUN   TestAccServiceCatalogAppRegistryApplication_disappears
=== PAUSE TestAccServiceCatalogAppRegistryApplication_disappears
=== CONT  TestAccServiceCatalogAppRegistryApplication_basic
=== CONT  TestAccServiceCatalogAppRegistryApplication_disappears
--- PASS: TestAccServiceCatalogAppRegistryApplication_disappears (7.71s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_basic (8.68s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry	11.876s
...
```

### CODE REVIEW

**Comment by hbjydev** [comment]
@fatbasstard Could you look into implementing a `data "aws_servicecatalogappregistry_application"` resource too? It would be really useful for people like my team who deploy one application with multiple TF repos.

**Comment by hbjydev** [comment]
Awesome! Look forward to it.

**Comment by fatbasstard** [comment]
@ewbankkit Hi!

My previous 2 PR's went trough really fast, this one has been open for a while. Any specific reason why it's not processed? Anything I can do to speed up the process?

**Comment by fatbasstard** [comment]
@YakDriver  @DrFaust92 @ewbankkit @johnsonaj @jar-b Hi all, can somebody take a look at this PR? We're really looking forward to this feature ever since it was announced in November. Any feedback would be very appreciated

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=servicecatalogappregistry TESTS=TestAccServiceCatalogAppRegistryApplication_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryApplication_'  -timeout 360m

--- PASS: TestAccServiceCatalogAppRegistryApplication_disappears (11.48s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_basic (13.42s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_update (28.16s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry  32.857s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @fatbasstard! 👍

**Comment by kevindesao** [comment]
Hello, 
I was really excited to try this out but it turns out I'm not able to make it work smoothly.

The creation of the resource worked fine but the implementation of the ARN as a tag fails to link the resource to the app.

The doc is mentioning the following:
```
resource "aws_servicecatalogappregistry_application" "example" {
  name = "example-app"
}

resource "aws_s3_bucket" "bucket" {
  bucket = "example-bucket"

  tags = {
    awsApplication = aws_servicecatalogappregistry_application.example.arn
  }
}
```

But by looking into the created myApp in the console the tags is not simply the ARN of the myApplication resources.

  - ARN myApplication : `arn:aws:servicecatalog:<region>:<account-id>:/applications/<ramdom_ARN_ID>`
  - Application tag value: `arn:aws:resource-groups:<region>:<account-id>:group/<myApplication_name>/<ramdom_ARN_ID>`

Tag Value tried unsuccessfully:
  - simply the myApplication id : `<ramdom_ARN_ID>`
  - The ARN `arn:aws:servicecatalog:<region>:<account-id>:/applications/<ramdom_ARN_ID>`

So to resume, I think a new attribute is required: 
  - `application_tag_value` =  `Application tag value` (similare to [awscc_servicecatalogappregistry_application](https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/servicecatalogappregistry_application#:~:text=application_tag_value)).

**SOLUTION:** In the meantime the ARN can be reconstructed like this: (Tested)
```
  common_tags = {
    awsApplication = "arn:aws:resource-groups:${data.aws_region.myApplication.name}:${data.aws_caller_identity.myApplication.id}:group/${aws_servicecatalogappregistry_application.this.name}/${aws_servicecatalogappregistry_application.this.id}"
  }
```

**Comment by kevindesao** [comment]
Good afternoon @fatbasstard @jar-b !

Really hyped by this new feature thanks for implementing it, I have created a [issue](https://github.com/hashicorp/terraform-provider-aws/issues/36697) following my precedent feedback.
If you can have a look while doing the data module it would be lovely :)

But in the meantime since it works with the crafted tags thanks again !

**Pull request merged**
