### PR TITLE
r/neptune_cluster - fix major version upgrade

### LINKED ISSUE #27998: [Bug]: Neptune upgrade fails while upgrading from 1.0.4.1 to 1.1.1.0
### Terraform Core Version

0.15.3

### AWS Provider Version

4.39.0

### Affected Resource(s)

aws_neptune_cluster

### Expected Behavior

When upgrading neptune cluster from 1.0.4.1 to 1.1.1.0, it should not throw any error message and upgrade will proceed and succeed after some time. 

### Actual Behavior

Failed with following error.
aws_neptune_cluster.neptune_cluster: Modifying... [id=test]
╷
│ Error: Failed to modify Neptune Cluster (test): InvalidParameterCombination: The current DB instance parameter group test-parameter-group is custom. You must explicitly specify a new DB instance parameter group, either default or custom, for the engine version upgrade.
│       status code: 400, request id: 123456789-4f5a-4b46-ae99-1248056f5ea6
│ 
│   with aws_neptune_cluster.neptune_cluster,
│   on main.tf line 21, in resource "aws_neptune_cluster" "neptune_cluster":
│   21: resource "aws_neptune_cluster" "neptune_cluster" {
│ 
╵
ERRO[0059] Hit multiple errors:

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

NA

### Steps to Reproduce

1. Create Neptune cluster with neptune engine version 1.0.4.1.
2. Upgrade the neptune version to 1.1.1.0 and start apply. 
3. It will fail with error.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

Looks like aws had modified the API signature to have the DB parameter group needs to be sent while major upgrade. 
That parameter is currently not checked by the terraform module and there is no property sent to the modify_cluster API input.

In cluster_update only cluster_parameter_group change is detected but not for neptune_parameter_group.

https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/neptune/cluster.go#L638

Let me know if I can raise the pull request. I will be happy to do that.

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by DrFaust92**
### Relations

Closes #27998.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/25982.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/11752.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/25972.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/23601.

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccNeptuneCluster_updateEngineMajorVersion  PKG=neptune

--- PASS: TestAccNeptuneCluster_updateEngineMajorVersion (1930.03s)
```

### CODE REVIEW

**Review by ran2806 — COMMENTED** [review]
According to the documentation. New requirement for modifyCluster API in major version upgrade is DBInstanceParameterGroupName  https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/neptune#ModifyDBClusterInput. Actually both the parameters are required.

https://docs.aws.amazon.com/neptune/latest/userguide/engine-releases-1.1.0.0.html

**Comment by ran2806** [comment]
You might be having confusion between DBClusterParameterGroupName  and DBInstanceParameterGroupName. Please add both the parameter group names while major upgrade.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccNeptuneCluster_' PKG=neptune ACCTEST_PARALLELISM=2           
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 2  -run=TestAccNeptuneCluster_ -timeout 180m
=== RUN   TestAccNeptuneCluster_basic
=== PAUSE TestAccNeptuneCluster_basic
=== RUN   TestAccNeptuneCluster_copyTagsToSnapshot
=== PAUSE TestAccNeptuneCluster_copyTagsToSnapshot
=== RUN   TestAccNeptuneCluster_namePrefix
=== PAUSE TestAccNeptuneCluster_namePrefix
=== RUN   TestAccNeptuneCluster_serverlessConfiguration
=== PAUSE TestAccNeptuneCluster_serverlessConfiguration
=== RUN   TestAccNeptuneCluster_takeFinalSnapshot
=== PAUSE TestAccNeptuneCluster_takeFinalSnapshot
=== RUN   TestAccNeptuneCluster_tags
=== PAUSE TestAccNeptuneCluster_tags
=== RUN   TestAccNeptuneCluster_updateIAMRoles
=== PAUSE TestAccNeptuneCluster_updateIAMRoles
=== RUN   TestAccNeptuneCluster_kmsKey
=== PAUSE TestAccNeptuneCluster_kmsKey
=== RUN   TestAccNeptuneCluster_encrypted
=== PAUSE TestAccNeptuneCluster_encrypted
=== RUN   TestAccNeptuneCluster_backupsUpdate
=== PAUSE TestAccNeptuneCluster_backupsUpdate
=== RUN   TestAccNeptuneCluster_iamAuth
=== PAUSE TestAccNeptuneCluster_iamAuth
=== RUN   TestAccNeptuneCluster_updateCloudWatchLogsExports
=== PAUSE TestAccNeptuneCluster_updateCloudWatchLogsExports
=== RUN   TestAccNeptuneCluster_updateEngineVersion
=== PAUSE TestAccNeptuneCluster_updateEngineVersion
=== RUN   TestAccNeptuneCluster_updateEngineMajorVersion
=== PAUSE TestAccNeptuneCluster_updateEngineMajorVersion
=== RUN   TestAccNeptuneCluster_deleteProtection
=== PAUSE TestAccNeptuneCluster_deleteProtection
=== RUN   TestAccNeptuneCluster_disappears
=== PAUSE TestAccNeptuneCluster_disappears
=== CONT  TestAccNeptuneCluster_basic
=== CONT  TestAccNeptuneCluster_encrypted
--- PASS: TestAccNeptuneCluster_encrypted (134.83s)
=== CONT  TestAccNeptuneCluster_updateEngineVersion
--- PASS: TestAccNeptuneCluster_basic (154.82s)
=== CONT  TestAccNeptuneCluster_disappears
--- PASS: TestAccNeptuneCluster_disappears (148.03s)
=== CONT  TestAccNeptuneCluster_deleteProtection
--- PASS: TestAccNeptuneCluster_deleteProtection (221.45s)
=== CONT  TestAccNeptuneCluster_updateEngineMajorVersion
--- PASS: TestAccNeptuneCluster_updateEngineVersion (1533.70s)
=== CONT  TestAccNeptuneCluster_iamAuth
--- PASS: TestAccNeptuneCluster_iamAuth (131.35s)
=== CONT  TestAccNeptuneCluster_updateCloudWatchLogsExports
--- PASS: TestAccNeptuneCluster_updateCloudWatchLogsExports (240.32s)
=== CONT  TestAccNeptuneCluster_takeFinalSnapshot
--- PASS: TestAccNeptuneCluster_takeFinalSnapshot (223.48s)
=== CONT  TestAccNeptuneCluster_kmsKey
--- PASS: TestAccNeptuneCluster_kmsKey (128.11s)
=== CONT  TestAccNeptuneCluster_updateIAMRoles
--- PASS: TestAccNeptuneCluster_updateIAMRoles (184.17s)
=== CONT  TestAccNeptuneCluster_tags
--- PASS: TestAccNeptuneCluster_tags (200.49s)
=== CONT  TestAccNeptuneCluster_backupsUpdate
--- PASS: TestAccNeptuneCluster_backupsUpdate (206.87s)
=== CONT  TestAccNeptuneCluster_namePrefix
--- PASS: TestAccNeptuneCluster_updateEngineMajorVersion (2493.73s)
=== CONT  TestAccNeptuneCluster_serverlessConfiguration
--- PASS: TestAccNeptuneCluster_namePrefix (120.58s)
=== CONT  TestAccNeptuneCluster_copyTagsToSnapshot
--- PASS: TestAccNeptuneCluster_serverlessConfiguration (130.71s)
--- PASS: TestAccNeptuneCluster_copyTagsToSnapshot (270.87s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	3379.413s
```

**Comment by ewbankkit** [comment]
Currently `DBInstanceParameterGroupName` cannot be configured for the `aws_neptune_cluster` resource.

**Comment by ran2806** [comment]
How to solve the issue for major version upgrade then when using custom parameterGroup for DBInstance, if we can not use DBInstanceParameterGroupName?

**Comment by DrFaust92** [comment]
@ewbankkit should i rebase?

**Comment by ewbankkit** [comment]
```console
% make testacc TESTARGS='-run=TestAccNeptuneClusterSnapshot_' PKG=neptune ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 3  -run=TestAccNeptuneClusterSnapshot_ -timeout 180m
=== RUN   TestAccNeptuneClusterSnapshot_basic
=== PAUSE TestAccNeptuneClusterSnapshot_basic
=== RUN   TestAccNeptuneClusterSnapshot_disappears
=== PAUSE TestAccNeptuneClusterSnapshot_disappears
=== CONT  TestAccNeptuneClusterSnapshot_basic
=== CONT  TestAccNeptuneClusterSnapshot_disappears
--- PASS: TestAccNeptuneClusterSnapshot_disappears (295.28s)
--- PASS: TestAccNeptuneClusterSnapshot_basic (298.38s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	303.749s
% make testacc TESTARGS='-run=TestAccNeptuneGlobalCluster_' PKG=neptune ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 3  -run=TestAccNeptuneGlobalCluster_ -timeout 180m
=== RUN   TestAccNeptuneGlobalCluster_basic
=== PAUSE TestAccNeptuneGlobalCluster_basic
=== RUN   TestAccNeptuneGlobalCluster_completeBasic
=== PAUSE TestAccNeptuneGlobalCluster_completeBasic
=== RUN   TestAccNeptuneGlobalCluster_disappears
=== PAUSE TestAccNeptuneGlobalCluster_disappears
=== RUN   TestAccNeptuneGlobalCluster_DeletionProtection
=== PAUSE TestAccNeptuneGlobalCluster_DeletionProtection
=== RUN   TestAccNeptuneGlobalCluster_Engine
=== PAUSE TestAccNeptuneGlobalCluster_Engine
=== RUN   TestAccNeptuneGlobalCluster_EngineVersion
=== PAUSE TestAccNeptuneGlobalCluster_EngineVersion
=== RUN   TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
=== PAUSE TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
=== RUN   TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
=== PAUSE TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
=== RUN   TestAccNeptuneGlobalCluster_StorageEncrypted
=== PAUSE TestAccNeptuneGlobalCluster_StorageEncrypted
=== CONT  TestAccNeptuneGlobalCluster_basic
=== CONT  TestAccNeptuneGlobalCluster_EngineVersion
=== CONT  TestAccNeptuneGlobalCluster_DeletionProtection
--- PASS: TestAccNeptuneGlobalCluster_basic (19.46s)
=== CONT  TestAccNeptuneGlobalCluster_Engine
--- PASS: TestAccNeptuneGlobalCluster_Engine (16.56s)
=== CONT  TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted
--- PASS: TestAccNeptuneGlobalCluster_DeletionProtection (60.19s)
=== CONT  TestAccNeptuneGlobalCluster_StorageEncrypted
--- PASS: TestAccNeptuneGlobalCluster_StorageEncrypted (30.49s)
=== CONT  TestAccNeptuneGlobalCluster_disappears
--- PASS: TestAccNeptuneGlobalCluster_disappears (13.04s)
=== CONT  TestAccNeptuneGlobalCluster_completeBasic
--- PASS: TestAccNeptuneGlobalCluster_EngineVersion (1719.98s)
=== CONT  TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic
--- PASS: TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_storageEncrypted (151.49s)
--- PASS: TestAccNeptuneGlobalCluster_completeBasic (154.27s)
--- PASS: TestAccNeptuneGlobalCluster_SourceDBClusterIdentifier_basic (141.40s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	1725.286s
% ACCTEST_TIMEOUT=360m make testacc TESTARGS='-run=TestAccNeptuneCluster_' PKG=neptune ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 3  -run=TestAccNeptuneCluster_ -timeout 360m
=== RUN   TestAccNeptuneCluster_basic
=== PAUSE TestAccNeptuneCluster_basic
=== RUN   TestAccNeptuneCluster_copyTagsToSnapshot
=== PAUSE TestAccNeptuneCluster_copyTagsToSnapshot
=== RUN   TestAccNeptuneCluster_namePrefix
=== PAUSE TestAccNeptuneCluster_namePrefix
=== RUN   TestAccNeptuneCluster_serverlessConfiguration
=== PAUSE TestAccNeptuneCluster_serverlessConfiguration
=== RUN   TestAccNeptuneCluster_takeFinalSnapshot
=== PAUSE TestAccNeptuneCluster_takeFinalSnapshot
=== RUN   TestAccNeptuneCluster_tags
=== PAUSE TestAccNeptuneCluster_tags
=== RUN   TestAccNeptuneCluster_updateIAMRoles
=== PAUSE TestAccNeptuneCluster_updateIAMRoles
=== RUN   TestAccNeptuneCluster_kmsKey
=== PAUSE TestAccNeptuneCluster_kmsKey
=== RUN   TestAccNeptuneCluster_encrypted
=== PAUSE TestAccNeptuneCluster_encrypted
=== RUN   TestAccNeptuneCluster_backupsUpdate
=== PAUSE TestAccNeptuneCluster_backupsUpdate
=== RUN   TestAccNeptuneCluster_iamAuth
=== PAUSE TestAccNeptuneCluster_iamAuth
=== RUN   TestAccNeptuneCluster_updateCloudWatchLogsExports
=== PAUSE TestAccNeptuneCluster_updateCloudWatchLogsExports
=== RUN   TestAccNeptuneCluster_updateEngineVersion
=== PAUSE TestAccNeptuneCluster_updateEngineVersion
=== RUN   TestAccNeptuneCluster_updateEngineMajorVersion
=== PAUSE TestAccNeptuneCluster_updateEngineMajorVersion
=== RUN   TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
=== PAUSE TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
=== RUN   TestAccNeptuneCluster_deleteProtection
=== PAUSE TestAccNeptuneCluster_deleteProtection
=== RUN   TestAccNeptuneCluster_disappears
=== PAUSE TestAccNeptuneCluster_disappears
=== CONT  TestAccNeptuneCluster_basic
=== CONT  TestAccNeptuneCluster_backupsUpdate
=== CONT  TestAccNeptuneCluster_updateEngineMajorVersion
--- PASS: TestAccNeptuneCluster_basic (193.90s)
=== CONT  TestAccNeptuneCluster_tags
--- PASS: TestAccNeptuneCluster_backupsUpdate (227.60s)
=== CONT  TestAccNeptuneCluster_encrypted
--- PASS: TestAccNeptuneCluster_tags (180.02s)
=== CONT  TestAccNeptuneCluster_kmsKey
--- PASS: TestAccNeptuneCluster_encrypted (171.27s)
=== CONT  TestAccNeptuneCluster_disappears
--- PASS: TestAccNeptuneCluster_kmsKey (177.91s)
=== CONT  TestAccNeptuneCluster_deleteProtection
--- PASS: TestAccNeptuneCluster_disappears (177.48s)
=== CONT  TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters
--- PASS: TestAccNeptuneCluster_deleteProtection (221.62s)
=== CONT  TestAccNeptuneCluster_serverlessConfiguration
--- PASS: TestAccNeptuneCluster_serverlessConfiguration (129.39s)
=== CONT  TestAccNeptuneCluster_updateIAMRoles
--- PASS: TestAccNeptuneCluster_updateIAMRoles (171.19s)
=== CONT  TestAccNeptuneCluster_takeFinalSnapshot
--- PASS: TestAccNeptuneCluster_takeFinalSnapshot (223.40s)
=== CONT  TestAccNeptuneCluster_namePrefix
--- PASS: TestAccNeptuneCluster_namePrefix (149.11s)
=== CONT  TestAccNeptuneCluster_updateEngineVersion
--- PASS: TestAccNeptuneCluster_updateEngineMajorVersion (1974.41s)
=== CONT  TestAccNeptuneCluster_copyTagsToSnapshot
--- PASS: TestAccNeptuneCluster_copyTagsToSnapshot (228.62s)
=== CONT  TestAccNeptuneCluster_iamAuth
--- PASS: TestAccNeptuneCluster_iamAuth (141.64s)
=== CONT  TestAccNeptuneCluster_updateCloudWatchLogsExports
--- PASS: TestAccNeptuneCluster_updateCloudWatchLogsExports (249.87s)
--- PASS: TestAccNeptuneCluster_updateEngineVersion (1778.42s)
--- PASS: TestAccNeptuneCluster_GlobalClusterIdentifier_PrimarySecondaryClusters (3163.49s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	3744.706s
% make testacc TESTARGS='-run=TestAccNeptuneClusterInstance_' PKG=neptune ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/neptune/... -v -count 1 -parallel 3  -run=TestAccNeptuneClusterInstance_ -timeout 180m
=== RUN   TestAccNeptuneClusterInstance_basic
=== PAUSE TestAccNeptuneClusterInstance_basic
=== RUN   TestAccNeptuneClusterInstance_disappears
=== PAUSE TestAccNeptuneClusterInstance_disappears
=== RUN   TestAccNeptuneClusterInstance_nameGenerated
=== PAUSE TestAccNeptuneClusterInstance_nameGenerated
=== RUN   TestAccNeptuneClusterInstance_namePrefix
=== PAUSE TestAccNeptuneClusterInstance_namePrefix
=== RUN   TestAccNeptuneClusterInstance_tags
=== PAUSE TestAccNeptuneClusterInstance_tags
=== RUN   TestAccNeptuneClusterInstance_withAZ
=== PAUSE TestAccNeptuneClusterInstance_withAZ
=== RUN   TestAccNeptuneClusterInstance_withSubnetGroup
=== PAUSE TestAccNeptuneClusterInstance_withSubnetGroup
=== RUN   TestAccNeptuneClusterInstance_kmsKey
=== PAUSE TestAccNeptuneClusterInstance_kmsKey
=== CONT  TestAccNeptuneClusterInstance_basic
=== CONT  TestAccNeptuneClusterInstance_tags
=== CONT  TestAccNeptuneClusterInstance_nameGenerated
--- PASS: TestAccNeptuneClusterInstance_basic (1309.76s)
=== CONT  TestAccNeptuneClusterInstance_disappears
--- PASS: TestAccNeptuneClusterInstance_nameGenerated (1384.45s)
=== CONT  TestAccNeptuneClusterInstance_withSubnetGroup
--- PASS: TestAccNeptuneClusterInstance_tags (1410.31s)
--- PASS: TestAccNeptuneClusterInstance_kmsKey (1354.95s)
=== CONT  TestAccNeptuneClusterInstance_withAZ
--- PASS: TestAccNeptuneClusterInstance_withSubnetGroup (1228.83s)
--- PASS: TestAccNeptuneClusterInstance_disappears (1224.74s)
=== CONT  TestAccNeptuneClusterInstance_namePrefix
--- PASS: TestAccNeptuneClusterInstance_withAZ (1219.66s)
--- PASS: TestAccNeptuneClusterInstance_namePrefix (1456.29s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/neptune	3902.197s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Pull request merged**
