### PR TITLE
dms: New resource aws_dms_s3_endpoint

### LINKED ISSUE #27852: [Bug]: compressionType is not a valid parameter in extra connection attributes
### Terraform Core Version

1.0.5

### AWS Provider Version

4.8.0

### Affected Resource(s)

aws_dms_endpoint

### Expected Behavior

Terraform should not send the default value for compressionType and Resource is created

### Actual Behavior

Endpoint fails to create as aws has removed the compressionType attribute for dms s3 as source endpoint . Terraform is sending default value of compressionType=None causing the call to fail.

          + cdc_path                         = "changedata"
          + compression_type                 = "NONE"
          + csv_delimiter                    = "|"
          + csv_row_delimiter                = "\\n"
          + data_format                      = "csv"
          + data_page_size                   = 1048576
          + date_partition_delimiter         = "slash"
          + date_partition_enabled           = false
          + date_partition_sequence          = "yyyymmdd"

### Relevant Error/Panic Output Snippet

```shell
Error: Error creating DMS endpoint: InvalidParameterValueException: Unsupported value 'compressionType' for extra connection attributes
	status code: 400, request id: 89916c08-3fa2-454e-affb-2c69c6572df1

  with module.data-lake.module.sources.module.source_activities[0].aws_dms_endpoint.main[0],
  on ../../main/data-sources/s3-data-source/main.tf line 5, in resource "aws_dms_endpoint" "main":
   5: resource "aws_dms_endpoint" "main" {
```

### Terraform Configuration Files

resource "aws_dms_endpoint" "main" {

  endpoint_id   = var.resource_prefix
  endpoint_type = "source"
  ssl_mode      = "none"
  tags          = var.application_tags
  engine_name   = "s3"

  s3_settings {
    bucket_name               = var.source_bucket_id
    bucket_folder             = var.source_bucket_folder
    service_access_role_arn   = var.activities_dms_s3_role_arn
    external_table_definition = var.external_table_mappings
    csv_delimiter             = var.csv_delimiter
    cdc_path                  = var.cdc_path
    csv_null_value            = var.csv_null_value
    csv_row_delimiter         = var.csv_row_delimiter
  }

### Steps to Reproduce

Create a DMS source endpoint with S3 as source

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

* #23506

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by YakDriver**
### Description

This PR addresses at least 3 challenges currently swirling around DMS endpoints.

1. **Extra connection attributes** aren't scaling well for AWS and all the endpoint types available. Correspondingly, the `aws_dms_endpoint` resource is not well suited to handling the many endpoint types, and their unique attributes, without the use of **extra connection attributes**.  The resource is stretched thin (read it's a mess) already with attempts to handle so many endpoints and all the variious edge cases associated with each.
1. As AWS moves closer to deprecating **extra connection attributes**, it appears that they are dropping support for some attributes, like `compression_type`. You _can_ still use `compression_type` but not through **extra connection attributes**.
2. AWS seems to have tightened up some validation rules. For example, previously, including `data_partition_delimiter` in a request to create a `source` endpoint did not cause problems. Now, it causes an error.

### Relations

Closes #27852
Closes #27980 
Relates #23507 

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by sbuzan** [comment]
I tried the new aws_dms_s3_endpoint, and I am still getting the "compressionType...errror (see details below).

terraform version = 1.3.6
aws provider version = 4.45.0

from main.tf = 

`terraform {
    required_version = ">= 1.3.6"

    required_providers {
        aws      = ">= 4.45.0"
    }
}

provider "aws" { region = "us-east-2" }

resource "aws_dms_s3_endpoint" "my_endpoint" {
    endpoint_id                 = "my-test"
    endpoint_type               = "source"
    bucket_folder               = "my-folder/"
    bucket_name                 ="my-bucket"
    csv_delimiter               =","
    csv_row_delimiter           ="\n"
    date_partition_delimiter    ="SLASH"
    date_partition_enabled      =false
    date_partition_sequence      ="YYYYMMDD"
    service_access_role_arn   = "arn:aws:iam::12345:role/my/role"
    cdc_path                  = "my-cdc-path"
    external_table_definition = file("./reader_table_definition.json")
} `

Console output:

`aws_dms_s3_endpoint.my_endpoint: Creating...
╷
│ Error: creating AWS DMS (Database Migration) S3 Endpoint (my-test): InvalidParameterValueException: Unsupported value 'compressionType' for extra connection attributes
│ 	status code: 400, request id: 10f9cc6d-59d7-4dbf-a90b-8afd327c5958
│ 
│   with aws_dms_s3_endpoint.my_endpoint,
│   on main.tf line 11, in resource "aws_dms_s3_endpoint" "my_endpoint":
│   11: resource "aws_dms_s3_endpoint" "my_endpoint" {`

**Comment by YakDriver** [comment]
@sbuzan @BrandonF8181 It turns out that the error is region specific. It works fine in `us-west-2`, where I tested it, but I'm also seeing it fail in `us-east-2`. 😞

**Comment by YakDriver** [comment]
This should be resolved with #28220 @sbuzan @BrandonF8181. Let us know if not.

**Comment by narnaldo** [comment]
failing also on us-east-1

**Comment by sbuzan** [comment]
@YakDriver I tested 4.45.0 in us-west-2 and confirmed that the aws_dms_s3_endpoint deploys.  However, the aws_dms_replication_task cannot read the new endpoint type as a valid source.  Cdc tasks fail when validating the endpoint parameters.  It is looking for "Parameter cdcPath."  I believe that it is checking the extra connection attributes which do not exist on the new endpoint.

resource "aws_dms_s3_endpoint" "my_endpoint" {
endpoint_id = "my-test"
endpoint_type = "source"
bucket_folder = "my-folder/"
bucket_name ="my-bucket"
csv_delimiter =","
csv_row_delimiter ="\n"
date_partition_delimiter ="SLASH"
date_partition_enabled =false
date_partition_sequence ="YYYYMMDD"
service_access_role_arn = "arn:aws:iam::12345:role/my/role"
cdc_path = "my-cdc-path"
external_table_definition = file("./reader_table_definition.json")
} `

`resource "aws_dms_replication_task" "reader_cdc_replication_task" {
    migration_type            = "cdc"
    ...
    source_endpoint_arn       = aws_dms_s3_endpoint.my_endpoint.endpoint_arn 
    ...
}`

console output with task added:

`aws_dms_s3_endpoint.source: Creation complete after 0s [id=dms-s3-source-endpoint-test]
aws_dms_replication_task.reader_cdc_replication_task: Creating...
╷
│ Error: error creating DMS Replication Task (dms-test-cdc): **InvalidParameterValueException**: **Parameter cdcPath** is required when task is configured for ongoing replication with Amazon S3 as a source.
│ 	status code: 400, request id: 736fc34f-10be-4250-8547-630827bf5cd6
│ 
│   with aws_dms_replication_task.reader_cdc_replication_task,
│   on main.tf line 45, in resource "aws_dms_replication_task" "reader_cdc_replication_task":
│   45: resource "aws_dms_replication_task" "reader_cdc_replication_task" {`

**Comment by sbuzan** [comment]
@YakDriver , I just tested 4.46.0.  I get the same error above when attaching a "cdc" task to the endpoint.  The the task appears to be looking for cdcPath in the ExtraConnectionAttributes, which we no longer populate.  (I duplicated this behavior with a CloudFormation deployment).


Condition:

Deploy the following:
(abbreviated tag)
resource **aws_dms_replication_task** {
**migration_type**            = "cdc"
**source_endpoint_arn**       = **aws_dms_s3_endpoint**.source.endpoint_arn
}


console output:

aws_dms_replication_task.reader_cdc_replication_task: Creating...
╷
│ Error: error creating DMS Replication Task (dms-test-cdc): InvalidParameterValueException: Parameter cdcPath is required when task is configured for ongoing replication with Amazon S3 as a source.
│ 	status code: 400, request id: f4a8d0dc-decc-4450-b874-f4840a4db9a9

**Comment by thundermann** [comment]
I also noticed that documentation for the attribute `ignore_headers_row` in the new `aws_dms_s3_endpoint` is actually named `ignore_header_rows` when creating a new endpoint.

**Comment by narnaldo** [comment]
for `source` type some of the parameters shouldn't be sent and not set with default value.

**Pull request merged**
