### PR TITLE
added eks cluster_name validation

### LINKED ISSUE #18806: Improve EKS cluster name validation
[AWS API documentation](https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html#API_CreateCluster_RequestSyntax) describes the format for an EKS cluster name is `^[0-9A-Za-z][A-Za-z0-9\-_]*`, with 1 to 100 characters.

Current validation in the provider is `validation.NoZeroValues`.

Update validation for `aws_eks_cluster` and other resources and data sources where the name is used.

### Affected Resource

* aws_eks_cluster
* aws_eks_addon (#16972)
* aws_eks_fargate_profile
* aws_eks_node_group
* data.aws_eks_addon (#16972)
* data.aws_eks_cluster

### PR DESCRIPTION
**Pull request by philnichol**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18806

Output from acceptance testing:

```
$ TF_ACC=1 go test ./aws -v -count 1 -run=TestResourceAWSEKSClusterNameValidation
=== RUN   TestResourceAWSEKSClusterNameValidation
--- PASS: TestResourceAWSEKSClusterNameValidation (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.690s
```
Thanks in advance for your review!

The regex listed in the documentation is actually incorrect, I've left feedback on that page so hopefully it gets corrected
https://docs.aws.amazon.com/eks/latest/APIReference/API_CreateCluster.html
Listed as `^[0-9A-Za-z][A-Za-z0-9\-_]*` but should be `^[0-9A-Za-z][A-Za-z0-9\-_]+$`.

Wasn't sure if I had to run acc tests for the resources themselves so please let me know if I do, I just skipped them since it will be expensive and long, but can run them if required 😄

### CODE REVIEW

**Comment by bflad** [comment]
Hi @philnichol 👋  Thank you for submitting this. Just a drive-by comment about the unit test failure that if you rebase against the main branch, it should be resolved. 👍

**Comment by philnichol** [comment]
Thanks @bflad , and apologies for incorrect branch name and missing CHANGELOG stuff, haven't contributed in a while and submitted before reading updated contributing guidelines, should probably be named td-.

**Review by gdavison — APPROVED** [review]
Looks good 🚀 

I've updated the changelog file to have one `release-note` block per change.

Acceptance test results

--- PASS: TestAccAWSEksFargateProfile_disappears (1316.49s)
--- PASS: TestAccAWSEksFargateProfile_Multi_Profile (1682.64s)

**Comment by philnichol** [comment]
> Looks good 🚀 
> 
> 
> 
> I've updated the changelog file to have one `release-note` block per change.
> 
> 
> 
> Acceptance test results
> 
> 
> 
> --- PASS: TestAccAWSEksFargateProfile_disappears (1316.49s)
> 
> --- PASS: TestAccAWSEksFargateProfile_Multi_Profile (1682.64s)
> 
> 

Thanks for that!

**Pull request merged**
