### PR TITLE
Add support for include filters in AWS DataSync task

### LINKED ISSUE #20849: Add support for include filters in AWS DataSync task
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS DataSync task supports include filters as well as exclude filters.

This enhancement enables us to have greater control over how data is transferred.  Additionally, we can queue multiple executions of a task when the filter settings differ between executions.

### New or Affected Resource(s)

* aws_datasync_task

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "sync_subset" {
  excludes {
    filter_type = "SIMPLE_PATTERN"
    value       = "/dir_A|/dir_B"
  }
  includes {
    filter_type = "SIMPLE_PATTERN"
    value       = "/dir_C|/dir_D"
  }
} 
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/08/aws-datasync-task-filtering-queuing/

### PR DESCRIPTION
**Pull request by shuichiro-makigaki**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #20849

Output from acceptance testing:

```
$ make testacc TESTARGS="-run=TestAccAWSDataSyncTask_Includes"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSyncTask_Includes -timeout 180m
=== RUN   TestAccAWSDataSyncTask_Includes
=== PAUSE TestAccAWSDataSyncTask_Includes
=== CONT  TestAccAWSDataSyncTask_Includes
--- PASS: TestAccAWSDataSyncTask_Includes (303.66s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       305.091s
```

### CODE REVIEW

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Review by marc-pensa — CHANGES_REQUESTED** [review]
In _website/docs/r/datasync_task_html.markdown_, one of two things needs to occur: 

- add an _includes Argument Refeference_ section identical to _excludes Argument Reference_
- alter the existing _excludes Argument Reference_ section to be _include and exclude filters Arguments Reference_ and link both the _includes_ and _excludes_ parameter descriptions to that section

**Comment by shuichiro-makigaki** [comment]
> In _website/docs/r/datasync_task_html.markdown_, one of two things needs to occur:
> 
> * add an _includes Argument Refeference_ section identical to _excludes Argument Reference_
> * alter the existing _excludes Argument Reference_ section to be _include and exclude filters Arguments Reference_ and link both the _includes_ and _excludes_ parameter descriptions to that section

fixed

**Comment by swiatek25** [comment]
Please merge :)

**Comment by ellaqezi** [comment]
> > In _website/docs/r/datasync_task_html.markdown_, one of two things needs to occur:
> > 
> > * add an _includes Argument Refeference_ section identical to _excludes Argument Reference_
> > * alter the existing _excludes Argument Reference_ section to be _include and exclude filters Arguments Reference_ and link both the _includes_ and _excludes_ parameter descriptions to that section
> 
> fixed

@marc-pensa kindly approve, your request for changes might be blocking this PR from getting merged.

**Review by marc-pensa — APPROVED** [review]

**Comment by ewbankkit** [comment]
Superseded by #25929.

**Comment by ewbankkit** [comment]
@shuichiro-makigaki Thanks for the contribution :tada: :clap:.

**Pull request closed without merging**
