### PR TITLE
d/aws_ecr_image: Add image URI attribute

### LINKED ISSUE #13671: ECR: Add Image URI as an Attribute for the image data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Expose Image URI as an output attribute for the `aws_ecr_image` data source since it would be useful in many areas.  For example, passing it to ECS for a task def, or Kubernetes as the image in a pod.

While it's absolutely possible to construct it yourself, it feels like this is a common enough use case that it'd be nice to expose it for users.

### New or Affected Resource(s)

* `aws_ecr_image`

### PR DESCRIPTION
**Pull request by weaversam8**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13671.

- Adds `image_uri` attribute to `aws_ecr_image` datasource.
    - The image URI will point to the version of the image specified by the `image_tag` or `image_digest` argument.
    - The URI generated will always be of the form `{RepositoryUri}@{ImageDigest}`, even if a tag is provided, since a URI with the digest is the canonical URI and is functionally equivalent to `{RepositoryUri}@{ImageTag}` at the time the tag is provided.
- Updates `TestAccECRImageDataSource_ecrImage` acceptance test
- Updates `aws_ecr_image` documentation

Output from acceptance testing:
```
$ make testacc TESTS=TestAccECRImageDataSource_ecrImage PKG=ecr
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRImageDataSource_ecrImage'  -timeout 180m
=== RUN   TestAccECRImageDataSource_ecrImage
=== PAUSE TestAccECRImageDataSource_ecrImage
=== CONT  TestAccECRImageDataSource_ecrImage
--- PASS: TestAccECRImageDataSource_ecrImage (16.10s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        17.985s
```

### CODE REVIEW

**Comment by Lianite** [comment]
This PR has been open for over a year. Are there any updates on when this could be expected to be merged in and released?

**Comment by TxMat** [comment]
any news ?

**Comment by marcaurele** [comment]
It's rather a small PR, could it get some attention to improve the ECR image resource.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS="-run=TestAccECRImageDataSource_basic" PKG=ecr

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20  -run=TestAccECRImageDataSource_basic -timeout 360m
=== RUN   TestAccECRImageDataSource_basic
=== PAUSE TestAccECRImageDataSource_basic
=== CONT  TestAccECRImageDataSource_basic
--- PASS: TestAccECRImageDataSource_basic (45.02s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	48.469s
```

**Comment by johnsonaj** [comment]
@weaversam8 thank you for the contribution! 🎉

**Pull request merged**
