### PR TITLE
Add possibility for compute_limit maximum_ondemand_capacity_units = 0  to emr_managed_scaling_policy

### LINKED ISSUE #17113: aws_emr_managed_scaling_policy doesn't support maximum_ondemand_capacity_units = 0
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

terraform 0.13.5
aws-provider 3.23

### Affected Resource(s)

* aws_emr_managed_scaling_policy

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_emr_cluster" "sample" {
  name          = "emr-sample-cluster"
  release_label = "emr-5.30.0"

  # skip ...
}

resource "aws_emr_managed_scaling_policy" "cluster_scaling" {
  cluster_id = aws_emr_cluster.sample.id
  compute_limits {
    unit_type                       = "InstanceFleetUnits"
    minimum_capacity_units          = 1
    maximum_capacity_units          = 10
    maximum_ondemand_capacity_units = 0
    maximum_core_capacity_units     = 4
  }
}
```

### Expected Behavior

The cluster should be created with a Managed Scaling policy with MaximumOnDemandCapacityUnits = 0 limit set. This means the cluster only starts spot instances for core and task nodes.

### Actual Behavior
There is no MaximumOnDemandCapacityUnits set. The cluster starts with on demand nodes only since no limit is set for on demand nodes.

### Steps to Reproduce

1. `terraform apply`

### References
*AWS explicitly offers the possibility to start an EMR cluster with spot nodes only (setting MaximumOnDemandCapacityUnits to 0) see [documentation](https://docs.aws.amazon.com/emr/latest/ManagementGuide/managed-scaling-allocation-strategy.html)

### PR DESCRIPTION
**Pull request by jdiebold**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17113

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
maximum_ondemand_capacity_units can be set to 0 for emr_managed_scaling_policy.compute_limits 
```

Output from acceptance testing:
Cluster is started with correct Managed Scaling Policy. There is a problem with the destroy apparently

```
$ make testacc TESTARGS='-run=TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly -timeout 120m
=== RUN   TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly
=== PAUSE TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly
=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly
    testing_new.go:63: Error running post-test destroy, there may be dangling resources: Error: EMR Managed Scaling Policy still exists
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly (514.49s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       516.565s
FAIL
make: *** [testacc] Error 1

$make testacc TESTARGS='-run=TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits -timeout 120m
=== RUN   TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits
=== PAUSE TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits
=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits
    testing_new.go:63: Error running post-test destroy, there may be dangling resources: Error: EMR Managed Scaling Policy still exists
--- FAIL: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits (488.65s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       491.090s
FAIL
make: *** [testacc] Error 1

```

### CODE REVIEW

**Review by anGie44 — CHANGES_REQUESTED** [review]
Hi @jdiebold , thank you for this PR! code changes look great, only request would be to uncommit the tools/* files when you have a chance 👍 

Regarding the failing tests, looking at the debug output from `GetManagedScalingPolicy`, it seems to be returning a non-nil response (perhaps a change in the API) even when the policy has been successfully deleted so a quick remedy would be to update L197 of the test file to:
```
resp != nil && resp.ManagedScalingPolicy != nil
```
This would still ensure the policy does not exist (and fix all the tests 😄 ) 👍 

https://github.com/hashicorp/terraform-provider-aws/blob/73e0fe06df88bba281b08d073e81708c53c5a2b0/aws/resource_aws_emr_managed_scaling_policy_test.go#L174-L198

**Comment by jdiebold** [comment]
output of the additional changes: 
```
$make testacc TESTARGS='-run=TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly'==> Checking that code complies with gofmt requirements...TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly -timeout 120m
=== RUN   TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly
=== PAUSE TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly
=== CONT  TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly
--- PASS: TestAccAwsEmrManagedScalingPolicy_ComputeLimits_MaximumOndemandCapacityUnits_SpotOnly (559.96s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       562.228s
```

**Comment by jdiebold** [comment]
@anGie44 would it be possible to merge it? I added the requested changes.

**Comment by applike-ss** [comment]
Is this still being worked on?

**Comment by jdiebold** [comment]
> Is this still being worked on?

if this bug still exists I can try to get the conflicts resolved

**Comment by mebuffet** [comment]
> > Is this still being worked on?
> 
> if this bug still exists I can try to get the conflicts resolved

Yes, the bug still exists. There's any ETA?

**Comment by jdiebold** [comment]
> > > Is this still being worked on?
> > 
> > 
> > if this bug still exists I can try to get the conflicts resolved
> 
> Yes, the bug still exists. There's any ETA?

I merged the refactorings of the main branch and transferred the changes. ETA depends on review by the maintainers.

**Comment by rankol** [comment]
> > Is this still being worked on?
> 
> if this bug still exists I can try to get the conflicts resolved

Thanks for working on this. I've been having a similar issue the past couple of days when attempting to use all instance types as spot Instance Fleets with `maximum_ondemand_capacity_units = 0`. Current "workaround" is to set that value to 1. AWS support has also mentioned that on their end they see `Max OnDemand is Null` when in my TF code that value is set to 0.

**Comment by ewbankkit** [comment]
@jdiebold Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
```console
% make semall providerlint golangci-lint                      
==> Running Semgrep checks locally (must have semgrep installed)...
Scanning 4056 files with 37 go rules.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|4056/4056 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 37 rules on 4056 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
Scanning 4056 files with 24 go rules.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|4056/4056 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 24 rules on 4056 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
Scanning 1541 files with 4 go rules.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1541/1541 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 4 rules on 1541 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
Scanning 924 files with 201 go rules.
  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|924/924 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 201 rules on 924 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
Scanning 1072 files with 200 go rules.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1072/1072 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 201 rules on 1072 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
Scanning 833 files with 197 go rules.
  100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|833/833 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 201 rules on 833 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
Scanning 1115 files with 201 go rules.
  100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|1115/1115 tasks

Some files were skipped or only partially analyzed.
  Scan was limited to files tracked by git.
  Scan skipped: 1613 files matching .semgrepignore patterns
  For a full list of skipped files, run semgrep with the --verbose flag.

Ran 201 rules on 1115 files: 0 findings.
If Semgrep missed a finding, please send us feedback to let us know!
  $ semgrep shouldafound --help
==> Checking source code with providerlint...
==> Checking source code with golangci-lint...
```

**Pull request merged**
