### PR TITLE
Add associated resource ARNs to `aws_ram_resource_share` data source

### LINKED ISSUE #21159: RAM resource share data source doesn't expose underlying resource_arn
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There isn't currently anyway to get the ARN of the underlying resource of a ram_resource_share via terraform. There is an existing ram_resource_share data source, but the attributes only relate to the share itself, not the underlying resource.

For example we've shared a an ACM Private CA in our org and we want to provide engineers a clean way of issuing certificates via terraform. To do that they need to provide the ARN of the Private CA. The only way we can do this right now is hard coding the arn, which is nasty.

### New or Affected Resource(s)

* aws_ram_resource_share (data source) 

### Potential Terraform Configuration

Would like to be able to do something like this:

```hcl
data "aws_ram_resource_share" "example" {
  name           = "my-private-ca"
  resource_owner = "OTHER-ACCOUNTS"
}

output "private_ca_arn" {
  value = data.aws_ram_resource_share.example.resource_arn
}
```

### References

* #0000

### PR DESCRIPTION
**Pull request by nicolaei**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

## Acceptance Testing

Output from acceptance testing:

```
$ make testacc TESTS=TestAccRAMResourceShareDataSource PKG=ram

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ram/... -v -count 1 -parallel 20 -run='TestAccRAMResourceShareDataSource'  -timeout 180m
=== RUN   TestAccRAMResourceShareDataSource_basic
=== PAUSE TestAccRAMResourceShareDataSource_basic
=== RUN   TestAccRAMResourceShareDataSource_tags
=== PAUSE TestAccRAMResourceShareDataSource_tags
=== RUN   TestAccRAMResourceShareDataSource_resources
=== PAUSE TestAccRAMResourceShareDataSource_resources
=== CONT  TestAccRAMResourceShareDataSource_basic
=== CONT  TestAccRAMResourceShareDataSource_resources
=== CONT  TestAccRAMResourceShareDataSource_tags
--- PASS: TestAccRAMResourceShareDataSource_tags (47.17s)
--- PASS: TestAccRAMResourceShareDataSource_basic (52.45s)
--- PASS: TestAccRAMResourceShareDataSource_resources (72.85s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ram        73.037s
```

## About This Change

This PR implements the change requested in #21159. The attribute name was chosen based on the attribute from `aws_ram_resource_share_accepter`.

I'm also quite new to go, so if I'm missing something that is typical for idiomatic go, I'd love to get some feedback on that 😄

---

Closes #21159.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29547.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28927.

### CODE REVIEW

**Comment by briantist** [comment]
would be great to see this merged

**Comment by taliesins** [comment]
@nicolaei fix the merge conflicts. It would be great to see this merged in.

**Comment by nicolaei** [comment]
The PR should be good to go again now 👌

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRAMResourceShareDataSource_' PKG=ram ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ram/... -v -count 1 -parallel 2  -run=TestAccRAMResourceShareDataSource_ -timeout 180m
=== RUN   TestAccRAMResourceShareDataSource_basic
=== PAUSE TestAccRAMResourceShareDataSource_basic
=== RUN   TestAccRAMResourceShareDataSource_tags
=== PAUSE TestAccRAMResourceShareDataSource_tags
=== RUN   TestAccRAMResourceShareDataSource_resources
=== PAUSE TestAccRAMResourceShareDataSource_resources
=== RUN   TestAccRAMResourceShareDataSource_status
=== PAUSE TestAccRAMResourceShareDataSource_status
=== CONT  TestAccRAMResourceShareDataSource_basic
=== CONT  TestAccRAMResourceShareDataSource_resources
--- PASS: TestAccRAMResourceShareDataSource_basic (27.87s)
=== CONT  TestAccRAMResourceShareDataSource_status
--- PASS: TestAccRAMResourceShareDataSource_resources (38.88s)
=== CONT  TestAccRAMResourceShareDataSource_tags
--- PASS: TestAccRAMResourceShareDataSource_status (25.92s)
--- PASS: TestAccRAMResourceShareDataSource_tags (25.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ram	69.634s
```

**Comment by ewbankkit** [comment]
@nicolaei Thanks for the contribution :tada: :clap:.
I changed the new attribute name to `resource_arns`.

**Pull request merged**
