### PR TITLE
B sbe ec2 deploy fix

### LINKED ISSUE #19068: Snowball Edge EC2 Deploy Fails -- Func resourceAwsInstanceRead Error
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.15.0 on darwin_amd64

### Affected Resource(s)

* aws_instance

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output

Due to the nature of my project, I may not be able to post this information. Checking with team and will post if I receive approval.

### Panic Output

Due to the nature of my project, I may not be able to post this information. Checking with team and will post if I receive approval. Can post this little snippet for now...

https://gist.github.com/bjsheppa/ec2b0ccc6879ed57a710a3cad86454d7

### Expected Behavior

Upon running the Terraform apply cli command on aws_instance code against a Snowball Edge custom EC2 endpoint, an EC2 instance should be deployed to the Snowball Edge and instance metadata should be reflected in Terraform state. The command should finish successfully.

### Actual Behavior

Upon running the Terraform apply cli command on aws_instance code against a Snowball Edge custom EC2 endpoint, an EC2 instance is deployed to the Snowball Edge but the instance metadata in not reflected in Terraform state. The command errors out with a resourceAwsInstanceRead function error.

### Steps to Reproduce

1.	Set custom EC2 endpoint to deploy to Snowball Edge 
2.	Run `terraform apply` to deploy an aws_instance onto the Snowball Edge
3.	The ‘terraform apply’ command will throw the error described in this issue.

### References

NA

### PR DESCRIPTION
**Pull request by bjsheppa**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19068

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by bjsheppa** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/19068

**Comment by bjsheppa** [comment]
Getting ready to push some updated code. Removed explicitly setting disable_api_termination and added a log statement instead. Think this is better and provides some indication in logs of what happened.

**Review by SebTardif — APPROVED** [review]

**Comment by dsmithbauer** [comment]
This worked for me too! Verified this using an AWS Snowball Edge device on premises.  Previously, we were unable to create EC2 instances. Terraform would crash. After building the Terraform AWS Provider from this PR, we were able to create an EC2 instance on the snowball. Thank you!

Can we get this promoted/merged soon?

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by ewbankkit** [comment]
This functionality has been rolled into #24283.

**Pull request closed without merging**
