### PR TITLE
Add HTTP datasource authorization_config fields.

### LINKED ISSUE #12721: Add authorization_config to http_config for aws_appsync_datasource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The HTTP appsync datasource can have an additional config causing all requests to be signed and opening up access to a much wider range of aws services which use http endpoints - this is setup by adding an authorization config to the endpoint. Would be great to support this in terraform.

### New or Affected Resource(s)

* aws_appsync_datasource

### Potential Terraform Configuration

```hcl
resource "aws_appsync_datasource" "example" {
  api_id           = "${aws_appsync_graphql_api.example.id}"
  name             = "tf_appsync_example"
  service_role_arn = "${aws_iam_role.example.arn}"
  type             = "HTTP"

  http_config {
    endpoint = "https://s3.amazonaws.com"
    
    authorization_config {
      authorization_type = "AWS_IAM"
      aws_iam_config {
        signing_region = "ap-southeast-2"
        signing_service_name = "s3"
      }
    }
  }
}
```

### References

* https://docs.aws.amazon.com/appsync/latest/APIReference/API_HttpDataSourceConfig.html

### PR DESCRIPTION
**Pull request by maddijoyce**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12721 #9628

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_appsync_graphql_api: Add `authorization_config` block to `http_config`
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAwsAppsyncDatasource_HTTPConfig'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAppsyncDatasource_HTTPConfig -timeout 120m
=== RUN   TestAccAwsAppsyncDatasource_HTTPConfig_AuthorizationConfig
=== PAUSE TestAccAwsAppsyncDatasource_HTTPConfig_AuthorizationConfig
=== RUN   TestAccAwsAppsyncDatasource_HTTPConfig_Endpoint
=== PAUSE TestAccAwsAppsyncDatasource_HTTPConfig_Endpoint
=== CONT  TestAccAwsAppsyncDatasource_HTTPConfig_AuthorizationConfig
=== CONT  TestAccAwsAppsyncDatasource_HTTPConfig_Endpoint
--- PASS: TestAccAwsAppsyncDatasource_HTTPConfig_AuthorizationConfig (45.24s)
--- PASS: TestAccAwsAppsyncDatasource_HTTPConfig_Endpoint (65.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	66.791s
```

### CODE REVIEW

**Comment by Callumccr** [comment]
This is definitely needed!

**Comment by maddijoyce** [comment]
@bflad Sorry if you're the wrong person to ping on this, but I'm wondering what the chances of this getting into the aws provider are?

**Comment by ignaciopeixoto** [comment]
Is this stuck just because some linting failed?

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by ewbankkit** [comment]
Superseded by #22411.

**Pull request closed without merging**
