### PR TITLE
r/aws_appautoscaling_scheduled_action: Fix bugs

### PR DESCRIPTION
**Pull request by stefansundin**
Do not default max_capacity and min_capacity to 0. Allow them to be left undefined to allow either one to be used individually.

Basically, it is currently impossible to use Terraform to create the following:
```
$ aws application-autoscaling put-scheduled-action --service-namespace rds --scalable-dimension rds:cluster:ReadReplicaCount --resource-id cluster:xxx --scheduled-action-name scale-down --schedule "cron(0 22 ? * MON-FRI *)" --scalable-target-action MinCapacity=0

$ aws application-autoscaling describe-scheduled-actions --service-namespace rds
{
    "ScheduledActions": [
        {
            "ScheduledActionName": "scale-down",
            "ScheduledActionARN": "arn:aws:autoscaling:xxxxxxx",
            "ServiceNamespace": "rds",
            "Schedule": "cron(0 22 ? * MON-FRI *)",
            "ResourceId": "cluster:xxx",
            "ScalableDimension": "rds:cluster:ReadReplicaCount",
            "ScalableTargetAction": {
                "MinCapacity": 0
            }
        }
    ]
}
```

Basically, this provider would set `max_capacity = 0`, which would very likely trigger the following error:
```
Error: ValidationException: Maximum capacity cannot be less than minimum capacity
```

This change allows for specifying only `min_capacity`, or only `max_capacity`.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
- resource/aws_appautoscaling_scheduled_action: Do not default `max_capacity` and `min_capacity` to `0`, allow either to be used on its own.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAppautoscalingScheduledAction_dynamo'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAppautoscalingScheduledAction_dynamo -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAppautoscalingScheduledAction_dynamo
=== PAUSE TestAccAWSAppautoscalingScheduledAction_dynamo
=== CONT  TestAccAWSAppautoscalingScheduledAction_dynamo
--- PASS: TestAccAWSAppautoscalingScheduledAction_dynamo (127.86s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	127.916s
```

With only the test change, the following happened:

```$ make testacc TESTARGS='-run=TestAccAWSAppautoscalingScheduledAction_dynamo'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAppautoscalingScheduledAction_dynamo -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAppautoscalingScheduledAction_dynamo
=== PAUSE TestAccAWSAppautoscalingScheduledAction_dynamo
=== CONT  TestAccAWSAppautoscalingScheduledAction_dynamo
--- FAIL: TestAccAWSAppautoscalingScheduledAction_dynamo (112.68s)
    testing.go:568: Step 0 error: errors during apply:

        Error: ValidationException: Maximum capacity cannot be less than minimum capacity
        	status code: 400, request id: xxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx

          on /var/folders/h6/r59_wnd905g_8s6x2mt7w0ch0000gn/T/tf-test995279429/main.tf line 22:
          (source code not available)


FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	112.733s
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by stefansundin** [comment]
@bflad If you have time, this one also needs a review.

**Comment by stefansundin** [comment]
I have found more bugs in this resource.. For example, it does not detect changes (e.g. updated `schedule`), so it's currently only usable for the initial resource creation since it can't update any changes made.

Do you want me to add more fixes to this PR, or open two new smaller PRs?

**Comment by stefansundin** [comment]
Okay, I decided to put it all in here since it's all kind of dependent on each other. I tried to be as descriptive as possible in my commit messages. Let me know what needs tweaking.

And the test is still passing!

```
$ make testacc TESTARGS='-run=TestAccAWSAppautoscalingScheduledAction_dynamo'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSAppautoscalingScheduledAction_dynamo -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAppautoscalingScheduledAction_dynamo
=== PAUSE TestAccAWSAppautoscalingScheduledAction_dynamo
=== CONT  TestAccAWSAppautoscalingScheduledAction_dynamo
--- PASS: TestAccAWSAppautoscalingScheduledAction_dynamo (41.27s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	41.327s
```

**Comment by stefansundin** [comment]
@ewbankkit @bflad This PR needs ~~some love~~ a review, please. :)

I think it's done and from what I remember everything was working when I created this PR (over 250 days ago!).

**Review by gdavison — APPROVED** [review]
Thanks for the PR, @stefansundin. I've made some updates to the acceptance tests and made the Update call only update parameters that have changed 🚀

**Pull request merged**
