### PR TITLE
resource/aws_datasync_task: Add `excludes` argument, missing `options` arguments

### LINKED ISSUE #10995: AWS DataSync Scheduling
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS have announced support for scheduled tasks for AWS Datasync: https://aws.amazon.com/about-aws/whats-new/2019/11/aws-datasync-adds-the-ability-to-schedule-data-transfers/

> You can now schedule AWS DataSync transfers between NFS servers, SMB servers, Amazon S3, and Amazon Elastic File System (Amazon EFS). DataSync task scheduling enables you to periodically execute a transfer task to detect and copy changes from your source storage system to the destination.

### New or Affected Resource(s)

- [`aws_datasync_task`](https://www.terraform.io/docs/providers/aws/r/datasync_task.html)

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "example" {
  destination_location_arn = "${aws_datasync_location_s3.destination.arn}"
  name                     = "example"
  source_location_arn      = "${aws_datasync_location_nfs.source.arn}"

  schedule {
    schedule_expression = "<cron expression>"
  }
}
```

### References

* https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateTask.html
* https://docs.aws.amazon.com/datasync/latest/userguide/API_UpdateTask.html
* https://docs.aws.amazon.com/datasync/latest/userguide/API_TaskSchedule.html

### LINKED ISSUE #11153: AWS DataSync Filter
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
AWS have  support for filtering data for datasync tasks for AWS Datasync:
https://aws.amazon.com/about-aws/whats-new/2019/05/aws-datasync-adds-filtering-for-data-transfers/

https://docs.aws.amazon.com/datasync/latest/userguide/filtering.html
Filtering the Data Transferred by AWS DataSync
When you transfer data from your source to your destination location, you can apply filters to transfer only a subset of the files in your source location. For example, if your source location includes temporary files that end with .tmp, you can create an exclude filter that ensures that these files are not transferred to the destination.

Filtering is an optional configuration to specify if you want to transfer a subset of your source files. You can leave the filter configuration empty if you want all files from the source to be transferred to the destination location.

### New or Affected Resource(s)

* [aws_datasync_task](https://www.terraform.io/docs/providers/aws/r/datasync_task.html)

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "example" {
  destination_location_arn = "${aws_datasync_location_s3.destination.arn}"
  name                     = "example"
  source_location_arn      = "${aws_datasync_location_nfs.source.arn}"

  filter_exclude {
    filter_expression = "<filter expression>"
  }
}
```

### References

- https://docs.aws.amazon.com/datasync/latest/userguide/API_CreateTask.html
- https://docs.aws.amazon.com/datasync/latest/userguide/API_UpdateTask.html
- https://docs.aws.amazon.com/datasync/latest/userguide/API_TaskSchedule.html

### LINKED ISSUE #14666: aws_datasync_task accepts a CloudWatch log group but does not enable logging
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.12.26
+ provider.aws v2.67.0
```

I'm a little out of date but I have verified from [the source](https://github.com/terraform-providers/terraform-provider-aws/blob/master/aws/resource_aws_datasync_task.go) that the same issue would exist as the ability to set the `LogLevel` option doesn't exist and the AWS default is `OFF`.

### Affected Resource(s)

* [aws_datasync_task](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_task)

### Terraform Configuration Files

```hcl
resource "aws_datasync_task" "main" {
  name = "my-task"

  source_location_arn      = aws_datasync_location_nfs.source.arn
  destination_location_arn = aws_datasync_location_efs.destination.arn

  cloudwatch_log_group_arn = replace(aws_cloudwatch_log_group.main.arn, "/:\\*$/", "") # NOTE: The :* suffix fix isn't needed beyond v3.0.0
}

resource "aws_cloudwatch_log_group" "main" {
  name = "my-task"
}
```

### Expected Behavior

Datasync task is created with logging enabled to the supplied CloudWatch log group.

### Actual Behavior

Datasync task is created, but logging is disabled:

image

The CloudWatch log group ARN _is_ saved, but user must manually enable logging via the CLI (or AWS console) afterwards, eg.:

```bash
aws datasync update-task --task-arn arn:aws:datasync:REGION:ACCOUNT:task/task-TASK-ID --options LogLevel=OFF|BASIC|TRANSFER
```

### Steps to Reproduce

1. `terraform apply`
2. Check log settings on created task.

### Important Factoids

This is technically a request for supporting the LogLevel option, and could be implemented as follows:

```
  options {
    # Suggested configuration, not implemented.
    log_level = "BASIC" # Potential values: OFF, BASIC, TRANSFER
  }
```

I've logged it as a bug rather than a feature as it was unexpected behaviour to be able to provide a `cloudwatch_log_group_arn` but have logging turned `OFF` and not be able to be configured via Terraform. Apologies if this should have been a feature instead, I think it could go both ways really!

### References

Other `aws_datasync_task` feature requests:

* #10995 (scheduling)
* #11153 (filtering)

### LINKED ISSUE #14667: AWS Datasync Task Queueing & Overwrite Mode
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for configuring Datasync task queueing & file overwrite functionality.

### New or Affected Resource(s)

* [aws_datasync_task](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/datasync_task)

### Potential Terraform Configuration

```hcl
resource "aws_datasync_task" "main" {
  name = "my-task"

  source_location_arn      = aws_datasync_location_nfs.source.arn
  destination_location_arn = aws_datasync_location_efs.destination.arn

  options {
    # NEW OPTIONS
    task_queueing  = "ENABLED" # Potential values: ENABLED, DISABLED
    overwrite_mode = "ALWAYS"  # Potential values: ALWAYS, NEVER
  }
}
```

### References

Along with #14666, this would complete Terraform support of all the available Datasync task options.

That is, other than `TaskQueueing`, `OverwriteMode` and `LogLevel`, Terraform already supports the rest of the available options:

```bash
$ aws datasync update-task help
...
       --options (structure)
          ...
          {
            "VerifyMode": "POINT_IN_TIME_CONSISTENT"|"ONLY_FILES_TRANSFERRED"|"NONE",
            "OverwriteMode": "ALWAYS"|"NEVER",
            "Atime": "NONE"|"BEST_EFFORT",
            "Mtime": "NONE"|"PRESERVE",
            "Uid": "NONE"|"INT_VALUE"|"NAME"|"BOTH",
            "Gid": "NONE"|"INT_VALUE"|"NAME"|"BOTH",
            "PreserveDeletedFiles": "PRESERVE"|"REMOVE",
            "PreserveDevices": "NONE"|"PRESERVE",
            "PosixPermissions": "NONE"|"PRESERVE",
            "BytesPerSecond": long,
            "TaskQueueing": "ENABLED"|"DISABLED",
            "LogLevel": "OFF"|"BASIC"|"TRANSFER"
          }
...
```

Other aws_datasync_task feature requests:

- #10995 (scheduling)
- #11153 (filtering)

### PR DESCRIPTION
**Pull request by gazoakley**
This builds on the changes by @DrFaust92 in #14452 and adds support for other arguments recently added to DataSync tasks.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11153
Closes #14667

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_datasync_task: Add `excludes` argument, add `log_level`,`overwrite_mode`,task_queueing`,`transfer_mode` to `options` argument ([#16204](https://github.com/hashicorp/terraform-provider-aws/issues/16204))
```

Output from acceptance testing:

```
% make testacc TESTARGS='-run=TestAccAWSDataSyncTask_DefaultSyncOptions_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSyncTask_DefaultSyncOptions_ -timeout 120m
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime (306.95s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_Gid (308.42s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing (324.90s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_Uid (333.71s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles (338.09s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel (343.44s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices (351.59s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions (357.55s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond (365.78s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode (369.86s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode (405.12s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode (422.19s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	423.833s

% make testacc TESTARGS='-run=TestAccAWSDataSyncTask_basic'              
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSyncTask_basic -timeout 120m
=== RUN   TestAccAWSDataSyncTask_basic
=== PAUSE TestAccAWSDataSyncTask_basic
=== CONT  TestAccAWSDataSyncTask_basic
--- PASS: TestAccAWSDataSyncTask_basic (274.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	276.010s

% make testacc TESTARGS='-run=TestAccAWSDataSyncTask_Excludes'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSyncTask_Excludes -timeout 120m
=== RUN   TestAccAWSDataSyncTask_Excludes
=== PAUSE TestAccAWSDataSyncTask_Excludes
=== CONT  TestAccAWSDataSyncTask_Excludes
--- PASS: TestAccAWSDataSyncTask_Excludes (359.49s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	361.295s
```

### CODE REVIEW

**Comment by mehfuzh** [comment]
These are very useful updates, especially automation is not done, without the support for scheduling. Thanks for doing these!

**Comment by johnl2323** [comment]
How soon before this PR will get merged?  

Trying to use datasync with terraform but the datasync task never logs anything to the logging group since there is no support for log_level until this is merged.

**Comment by rorysedgwick** [comment]
Any update on when this may be merged?
Slightly in limbo at the moment as the ` aws_datasync_task` can be defined within TF, but triggering an execution via the web console adds these default parameters which forces a recreation of the resource on next `terraform plan`

**Comment by dspv** [comment]
Great update. Need it :) 
Any plans to merge?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataSyncTask_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSyncTask_ -timeout 180m
=== RUN   TestAccAWSDataSyncTask_basic
=== PAUSE TestAccAWSDataSyncTask_basic
=== RUN   TestAccAWSDataSyncTask_disappears
=== PAUSE TestAccAWSDataSyncTask_disappears
=== RUN   TestAccAWSDataSyncTask_schedule
=== PAUSE TestAccAWSDataSyncTask_schedule
=== RUN   TestAccAWSDataSyncTask_CloudWatchLogGroupARN
=== PAUSE TestAccAWSDataSyncTask_CloudWatchLogGroupARN
=== RUN   TestAccAWSDataSyncTask_Excludes
=== PAUSE TestAccAWSDataSyncTask_Excludes
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== RUN   TestAccAWSDataSyncTask_Tags
    provider_test.go:55: Tagging on creation is inconsistent
--- SKIP: TestAccAWSDataSyncTask_Tags (0.00s)
=== CONT  TestAccAWSDataSyncTask_basic
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== CONT  TestAccAWSDataSyncTask_CloudWatchLogGroupARN
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== CONT  TestAccAWSDataSyncTask_Excludes
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== CONT  TestAccAWSDataSyncTask_disappears
=== CONT  TestAccAWSDataSyncTask_schedule
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
--- PASS: TestAccAWSDataSyncTask_basic (269.61s)
--- PASS: TestAccAWSDataSyncTask_disappears (287.47s)
--- PASS: TestAccAWSDataSyncTask_schedule (321.44s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_Gid (324.56s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_Uid (327.15s)
--- PASS: TestAccAWSDataSyncTask_CloudWatchLogGroupARN (327.48s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel (332.43s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles (343.10s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime (357.65s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices (358.26s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode (359.06s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing (363.15s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond (363.87s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode (365.15s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions (365.46s)
--- PASS: TestAccAWSDataSyncTask_Excludes (374.24s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode (389.90s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	392.804s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataSyncTask_' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataSyncTask_ -timeout 180m
=== RUN   TestAccAWSDataSyncTask_basic
=== PAUSE TestAccAWSDataSyncTask_basic
=== RUN   TestAccAWSDataSyncTask_disappears
=== PAUSE TestAccAWSDataSyncTask_disappears
=== RUN   TestAccAWSDataSyncTask_schedule
=== PAUSE TestAccAWSDataSyncTask_schedule
=== RUN   TestAccAWSDataSyncTask_CloudWatchLogGroupARN
=== PAUSE TestAccAWSDataSyncTask_CloudWatchLogGroupARN
=== RUN   TestAccAWSDataSyncTask_Excludes
=== PAUSE TestAccAWSDataSyncTask_Excludes
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== RUN   TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== PAUSE TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== RUN   TestAccAWSDataSyncTask_Tags
    provider_test.go:55: Tagging on creation is inconsistent
--- SKIP: TestAccAWSDataSyncTask_Tags (0.00s)
=== CONT  TestAccAWSDataSyncTask_basic
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_Uid
=== CONT  TestAccAWSDataSyncTask_disappears
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_Gid
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond
=== CONT  TestAccAWSDataSyncTask_CloudWatchLogGroupARN
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles
=== CONT  TestAccAWSDataSyncTask_schedule
=== CONT  TestAccAWSDataSyncTask_Excludes
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing
=== CONT  TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices
--- PASS: TestAccAWSDataSyncTask_basic (242.60s)
--- PASS: TestAccAWSDataSyncTask_disappears (269.93s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_AtimeMtime (271.55s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_BytesPerSecond (275.03s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_Uid (291.40s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_TaskQueueing (293.64s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDevices (300.06s)
--- PASS: TestAccAWSDataSyncTask_Excludes (309.14s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_Gid (322.80s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_VerifyMode (324.54s)
--- PASS: TestAccAWSDataSyncTask_CloudWatchLogGroupARN (325.62s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_LogLevel (328.24s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PosixPermissions (330.22s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_OverwriteMode (331.32s)
--- PASS: TestAccAWSDataSyncTask_schedule (336.34s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_TransferMode (336.66s)
--- PASS: TestAccAWSDataSyncTask_DefaultSyncOptions_PreserveDeletedFiles (339.42s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	342.402s
```

**Pull request merged**
