### PR TITLE
fix typo in arib_captions_pid and arib_captions_pid_control

### PR DESCRIPTION
**Pull request by quartercastle**
### Description

Change `arib_caption_pid` to `arib_captions_pid` and `arib_caption_pid_control` to `arib_captions_pid_control` so the parameters can be assigned

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccMediaLiveChannel_m2ts_settings PKG=medialive
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_m2ts_settings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_m2ts_settings
=== PAUSE TestAccMediaLiveChannel_m2ts_settings
=== CONT  TestAccMediaLiveChannel_m2ts_settings
--- PASS: TestAccMediaLiveChannel_m2ts_settings (85.36s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	87.405s
```

### CODE REVIEW

**Comment by quartercastle** [comment]
> Hey @quartercastle 👋 Thank you very much for your contribution! At times, our maintainers need to make direct edits to pull requests in order to help get it ready to be merged. Your current settings do not allow maintainers to make such edits. To help facilitate this, update your pull request to allow such edits as described in GitHub's [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) documentation. (If you're using a fork owned by an organization, your organization may not allow you to change this setting. If that is the case, let us know.)

The org i'm contributing from does not allow this at the moment.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ make testacc PKG=medialive TESTS=TestAccMediaLiveChannel_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_basic
=== PAUSE TestAccMediaLiveChannel_basic
=== RUN   TestAccMediaLiveChannel_m2ts_settings
=== PAUSE TestAccMediaLiveChannel_m2ts_settings
=== RUN   TestAccMediaLiveChannel_audioDescriptions_codecSettings
=== PAUSE TestAccMediaLiveChannel_audioDescriptions_codecSettings
=== RUN   TestAccMediaLiveChannel_hls
=== PAUSE TestAccMediaLiveChannel_hls
=== RUN   TestAccMediaLiveChannel_status
=== PAUSE TestAccMediaLiveChannel_status
=== RUN   TestAccMediaLiveChannel_update
=== PAUSE TestAccMediaLiveChannel_update
=== RUN   TestAccMediaLiveChannel_updateTags
=== PAUSE TestAccMediaLiveChannel_updateTags
=== RUN   TestAccMediaLiveChannel_disappears
=== PAUSE TestAccMediaLiveChannel_disappears
=== CONT  TestAccMediaLiveChannel_basic
=== CONT  TestAccMediaLiveChannel_status
=== CONT  TestAccMediaLiveChannel_updateTags
=== CONT  TestAccMediaLiveChannel_disappears
=== CONT  TestAccMediaLiveChannel_m2ts_settings
=== CONT  TestAccMediaLiveChannel_update
=== CONT  TestAccMediaLiveChannel_audioDescriptions_codecSettings
=== CONT  TestAccMediaLiveChannel_hls
--- PASS: TestAccMediaLiveChannel_m2ts_settings (76.27s)
--- PASS: TestAccMediaLiveChannel_hls (82.12s)
--- PASS: TestAccMediaLiveChannel_basic (85.65s)
--- PASS: TestAccMediaLiveChannel_update (118.64s)
--- PASS: TestAccMediaLiveChannel_disappears (151.02s)
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (155.05s)
--- PASS: TestAccMediaLiveChannel_updateTags (176.40s)
--- PASS: TestAccMediaLiveChannel_status (184.72s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/medialive  187.756s
```

**Comment by jar-b** [comment]
@quartercastle - can you add a changelog entry to `.changelog/29467.txt`:

~~~
```release-note:bug
resource/aws_medialive_channel: Fix setting of `m2ts_settings` `arib_captions_pid` and `arib_captions_pid_control` attributes
```
~~~

**Comment by quartercastle** [comment]
@jar-b thanks for the review, i have added the changelog in 5ce2a919a4.

**Pull request merged**
