### PR TITLE
Force Delete Service Discovery Service

### LINKED ISSUE #4853: ResourceInUse: Service contains registered instances; delete the instances before deleting the service
_This issue was originally opened by @tuaris as hashicorp/terraform#18264. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Terraform Version
```
0.11.5
```

### Terraform Configuration Files
```hcl
resource "aws_service_discovery_private_dns_namespace" "app_service" {
	name = "app.service"
	vpc = "vcp-12345678"
}

resource "aws_service_discovery_service" "worker" {
	name = "worker"
	dns_config {
		namespace_id = "${aws_service_discovery_private_dns_namespace.app_service.id}"
		dns_records {
			ttl = 10
			type = "A"
		}
		routing_policy = "MULTIVALUE"
	}

	health_check_custom_config {
		failure_threshold = 1
	}
}

resource "aws_ecs_service" "worker" {
        ...
	service_registries {
		registry_arn = "${aws_service_discovery_service.worker.arn}"
                container_name = "worker"
	}
}
```

### Debug Output
```
Error: Error applying plan:

1 error(s) occurred:

* aws_service_discovery_service.worker(destroy): 1 error(s) occurred:

* aws_service_discovery_service.worker: ResourceInUse: Service contains registered instances; delete the instances before deleting the service 

```

### Expected Behavior

Removing the resource `aws_service_discovery_service.worker` should first stop the service `aws_ecs_service.worker`, then proceed to delete the resource.

### Actual Behavior

Process fails with `ResourceInUse: Service contains registered instances; delete the instances before deleting the service`

### Steps to Reproduce

To reproduce the issue, for example:
1. Use the configuration above
2. `terraform apply`
3. Remove the resource `aws_service_discovery_service.worker`
4. `terraform apply`

### PR DESCRIPTION
**Pull request by Tremualin**
Added an option to force delete the services by removing all the registered instances before deleting the services. Based the PR on the s3 removal code.

Tested only locally (and make test).
This is my first PR for a terraform provider, please let me know if there's anything missing.

Closes #4853.

### CODE REVIEW

**Comment by gomezsan** [comment]
Please check this PR.

**Comment by ewbankkit** [comment]
It looks like this closes #4853.

**Comment by mkielar** [comment]
I know I'm just bumping this up, but is there anything that stops this from being merged?
The [original issue](https://github.com/hashicorp/terraform-provider-aws/issues/4853) is now two and a half years old, and there's a working solution. Why not merge it?

**Comment by leonsmith** [comment]
(This is the 15th oldest unmerged MR)

Guessing some acceptance tests might speed this up getting it merged?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% TEST=./aws SWEEP=us-west-2 SWEEPARGS=-sweep-run=aws_service_discovery_service make sweep 
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-west-2 -sweep-run=aws_service_discovery_service -timeout 60m
2021/09/01 09:18:25 [DEBUG] Running Sweepers for region (us-west-2):
2021/09/01 09:18:25 [DEBUG] Running Sweeper (aws_service_discovery_service) in region (us-west-2)
2021/09/01 09:18:25 [INFO] AWS Auth provider used: "EnvProvider"
2021/09/01 09:18:25 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/09/01 09:18:25 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/09/01 09:18:26 [DEBUG] Waiting for state to become: [success]
2021/09/01 09:18:27 [INFO] Deregistering Service Discovery Service (srv-jtm4m2mpyzy53nwe) Instance: ewbankkit-instance-1
2021/09/01 09:18:27 [DEBUG] Waiting for state to become: [SUCCESS]
2021/09/01 09:18:28 [TRACE] Waiting 200ms before next try
2021/09/01 09:18:28 [INFO] Deregistering Service Discovery Service (srv-jtm4m2mpyzy53nwe) Instance: ewbankkit-instance-2
2021/09/01 09:18:29 [DEBUG] Waiting for state to become: [SUCCESS]
2021/09/01 09:18:29 [TRACE] Waiting 200ms before next try
2021/09/01 09:18:29 [TRACE] Waiting 400ms before next try
2021/09/01 09:18:30 [DEBUG] Deleting Service Discovery Service: (srv-jtm4m2mpyzy53nwe)
2021/09/01 09:18:31 [DEBUG] Completed Sweeper (aws_service_discovery_service) in region (us-west-2) in 5.370342067s
2021/09/01 09:18:31 Completed Sweepers for region (us-west-2) in 5.370593443s
2021/09/01 09:18:31 Sweeper Tests for region (us-west-2) ran successfully:
	- aws_service_discovery_service
ok  	github.com/terraform-providers/terraform-provider-aws/aws	8.560s
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSServiceDiscoveryService_\|TestAccAWSServiceDiscoveryHttpNamespace_\|TestAccAWSServiceDiscoveryPrivateDnsNamespace_\|TestAccAWSServiceDiscoveryPublicDnsNamespace_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSServiceDiscoveryService_\|TestAccAWSServiceDiscoveryHttpNamespace_\|TestAccAWSServiceDiscoveryPrivateDnsNamespace_\|TestAccAWSServiceDiscoveryPublicDnsNamespace_ -timeout 180m
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_basic
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_basic
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_disappears
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_disappears
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_Description
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_Description
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_Tags
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_Tags
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
=== RUN   TestAccAWSServiceDiscoveryService_private
=== PAUSE TestAccAWSServiceDiscoveryService_private
=== RUN   TestAccAWSServiceDiscoveryService_public
=== PAUSE TestAccAWSServiceDiscoveryService_public
=== RUN   TestAccAWSServiceDiscoveryService_http
=== PAUSE TestAccAWSServiceDiscoveryService_http
=== RUN   TestAccAWSServiceDiscoveryService_disappears
=== PAUSE TestAccAWSServiceDiscoveryService_disappears
=== RUN   TestAccAWSServiceDiscoveryService_Tags
=== PAUSE TestAccAWSServiceDiscoveryService_Tags
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_basic
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_Description
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
=== CONT  TestAccAWSServiceDiscoveryService_http
=== CONT  TestAccAWSServiceDiscoveryService_public
=== CONT  TestAccAWSServiceDiscoveryService_private
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_Tags
=== CONT  TestAccAWSServiceDiscoveryService_Tags
=== CONT  TestAccAWSServiceDiscoveryService_disappears
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_disappears
--- PASS: TestAccAWSServiceDiscoveryHttpNamespace_disappears (93.52s)
--- PASS: TestAccAWSServiceDiscoveryHttpNamespace_basic (99.28s)
--- PASS: TestAccAWSServiceDiscoveryHttpNamespace_Description (99.29s)
--- PASS: TestAccAWSServiceDiscoveryService_http (100.99s)
--- PASS: TestAccAWSServiceDiscoveryService_disappears (109.18s)
--- PASS: TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears (113.93s)
--- PASS: TestAccAWSServiceDiscoveryPublicDnsNamespace_Description (118.59s)
--- PASS: TestAccAWSServiceDiscoveryPublicDnsNamespace_basic (120.48s)
--- PASS: TestAccAWSServiceDiscoveryHttpNamespace_Tags (123.49s)
--- PASS: TestAccAWSServiceDiscoveryService_Tags (126.52s)
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic (129.26s)
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears (133.71s)
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description (135.99s)
--- PASS: TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags (142.66s)
--- PASS: TestAccAWSServiceDiscoveryService_public (149.10s)
--- PASS: TestAccAWSServiceDiscoveryService_private (161.45s)
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags (164.62s)
--- PASS: TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap (193.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	197.309s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSServiceDiscoveryService_\|TestAccAWSServiceDiscoveryHttpNamespace_\|TestAccAWSServiceDiscoveryPrivateDnsNamespace_\|TestAccAWSServiceDiscoveryPublicDnsNamespace_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSServiceDiscoveryService_\|TestAccAWSServiceDiscoveryHttpNamespace_\|TestAccAWSServiceDiscoveryPrivateDnsNamespace_\|TestAccAWSServiceDiscoveryPublicDnsNamespace_ -timeout 180m
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_basic
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_basic
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_disappears
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_disappears
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_Description
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_Description
=== RUN   TestAccAWSServiceDiscoveryHttpNamespace_Tags
=== PAUSE TestAccAWSServiceDiscoveryHttpNamespace_Tags
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
=== RUN   TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
=== PAUSE TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
=== RUN   TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
=== PAUSE TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
=== RUN   TestAccAWSServiceDiscoveryService_private
=== PAUSE TestAccAWSServiceDiscoveryService_private
=== RUN   TestAccAWSServiceDiscoveryService_public
=== PAUSE TestAccAWSServiceDiscoveryService_public
=== RUN   TestAccAWSServiceDiscoveryService_http
=== PAUSE TestAccAWSServiceDiscoveryService_http
=== RUN   TestAccAWSServiceDiscoveryService_disappears
=== PAUSE TestAccAWSServiceDiscoveryService_disappears
=== RUN   TestAccAWSServiceDiscoveryService_Tags
=== PAUSE TestAccAWSServiceDiscoveryService_Tags
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_basic
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
=== CONT  TestAccAWSServiceDiscoveryService_http
=== CONT  TestAccAWSServiceDiscoveryService_Tags
=== CONT  TestAccAWSServiceDiscoveryService_private
=== CONT  TestAccAWSServiceDiscoveryService_disappears
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_Tags
=== CONT  TestAccAWSServiceDiscoveryService_public
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_Description
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_disappears
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_basic
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryPublicDnsNamespace_disappears (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryHttpNamespace_basic (1.45s)
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryPublicDnsNamespace_Tags (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_disappears (1.45s)
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_basic
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryService_http
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryPublicDnsNamespace_basic (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryService_http (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_Description (1.45s)
=== CONT  TestAccAWSServiceDiscoveryService_private
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryService_disappears
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryService_private (1.45s)
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_Tags
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryPublicDnsNamespace_Description
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryService_disappears (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryHttpNamespace_Tags (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryPublicDnsNamespace_Description (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_error_Overlap (1.45s)
=== CONT  TestAccAWSServiceDiscoveryService_public
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryService_Tags
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryService_public (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_basic (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryService_Tags (1.45s)
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_Description
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
=== CONT  TestAccAWSServiceDiscoveryHttpNamespace_disappears
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryHttpNamespace_Description (1.45s)
--- SKIP: TestAccAWSServiceDiscoveryHttpNamespace_disappears (1.45s)
=== CONT  TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags
    provider_test.go:735: skipping tests; partition aws-us-gov does not support servicediscovery service
--- SKIP: TestAccAWSServiceDiscoveryPrivateDnsNamespace_Tags (1.45s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.701s
```

**Comment by ewbankkit** [comment]
@Tremualin Thanks for the contribution :tada: :clap:.

**Pull request merged**
