### PR TITLE
Add support for aws_datapipeline_definition resource

### PR DESCRIPTION
**Pull request by teraken0509**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Reference #1538 #9291 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Features:
- resource/aws_datapipeline_definition: Add support aws_datapipeline_definition resource
```

Output from acceptance testing:

```
$  make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipelineDefinition_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataPipelineDefinition_ -timeout 120m
=== RUN   TestAccAWSDataPipelineDefinition_basic
=== PAUSE TestAccAWSDataPipelineDefinition_basic
=== RUN   TestAccAWSDataPipelineDefinition_options
=== PAUSE TestAccAWSDataPipelineDefinition_options
=== RUN   TestAccAWSDataPipelineDefinition_disappears
=== PAUSE TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_basic
=== CONT  TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_options
--- PASS: TestAccAWSDataPipelineDefinition_disappears (50.03s)
--- PASS: TestAccAWSDataPipelineDefinition_basic (66.97s)
--- PASS: TestAccAWSDataPipelineDefinition_options (102.23s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	102.315s
```

### CODE REVIEW

**Comment by kterada0509** [comment]
split pr from #9291 .

**Comment by kterada0509** [comment]
Re-run acctest.

```
$  make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipelineDefinition_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataPipelineDefinition_ -timeout 120m
go: finding github.com/terraform-providers/terraform-provider-tls v2.1.0+incompatible
go: downloading github.com/terraform-providers/terraform-provider-tls v2.1.0+incompatible
go: extracting github.com/terraform-providers/terraform-provider-tls v2.1.0+incompatible
=== RUN   TestAccAWSDataPipelineDefinition_basic
=== PAUSE TestAccAWSDataPipelineDefinition_basic
=== RUN   TestAccAWSDataPipelineDefinition_options
=== PAUSE TestAccAWSDataPipelineDefinition_options
=== RUN   TestAccAWSDataPipelineDefinition_disappears
=== PAUSE TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_basic
=== CONT  TestAccAWSDataPipelineDefinition_options
=== CONT  TestAccAWSDataPipelineDefinition_disappears
--- PASS: TestAccAWSDataPipelineDefinition_disappears (58.96s)
--- PASS: TestAccAWSDataPipelineDefinition_basic (81.08s)
--- PASS: TestAccAWSDataPipelineDefinition_options (120.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	120.243s
```

**Comment by LionKinger** [comment]
when to release this feature?

**Comment by kterada0509** [comment]
Re-run acctest.

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipelineDefinition_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSDataPipelineDefinition_ -timeout 120m
=== RUN   TestAccAWSDataPipelineDefinition_basic
=== PAUSE TestAccAWSDataPipelineDefinition_basic
=== RUN   TestAccAWSDataPipelineDefinition_options
=== PAUSE TestAccAWSDataPipelineDefinition_options
=== RUN   TestAccAWSDataPipelineDefinition_disappears
=== PAUSE TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_basic
=== CONT  TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_options
--- PASS: TestAccAWSDataPipelineDefinition_disappears (46.26s)
--- PASS: TestAccAWSDataPipelineDefinition_basic (66.34s)
--- PASS: TestAccAWSDataPipelineDefinition_options (102.99s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	103.140s
```

**Comment by YishaiPL** [comment]
Kindly review & release the feature.

**Comment by kterada0509** [comment]
@bflad  Update to use terraform-provider-sdk & Re-run acctest.

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDataPipelineDefinition_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataPipelineDefinition_ -timeout 120m
=== RUN   TestAccAWSDataPipelineDefinition_basic
=== PAUSE TestAccAWSDataPipelineDefinition_basic
=== RUN   TestAccAWSDataPipelineDefinition_options
=== PAUSE TestAccAWSDataPipelineDefinition_options
=== RUN   TestAccAWSDataPipelineDefinition_disappears
=== PAUSE TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_basic
=== CONT  TestAccAWSDataPipelineDefinition_disappears
=== CONT  TestAccAWSDataPipelineDefinition_options
--- PASS: TestAccAWSDataPipelineDefinition_disappears (44.01s)
--- PASS: TestAccAWSDataPipelineDefinition_basic (62.51s)
--- PASS: TestAccAWSDataPipelineDefinition_options (104.73s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	104.812s
```

**Comment by achilds-vela** [comment]
Any updates on this? I'm having to manipulate json templates and use a null_resource provider to upload the definition because we don't have this functionality, so I definitely support getting this reviewed and merged in.

**Comment by jayzalowitz** [comment]
Any update on this. Im horribly blocked on datapipeline unless this happens

**Comment by mwhipple** [comment]
It looks like this only supports configuration of some of the pipeline level metadata rather than the definition of objects within the pipeline?

It feels like it may be better to split out the objects into separate resources which can be composed into the definition so that the objects can produce the required JSON and the definition resource calls the API with that serialized data. (I'll look to tinker if I scrounge up the time)

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by ZsoltPath** [comment]
It feels like missing the most important part. Uploading the JSON definition of the whole pipeline.

I agree it'd be nicer to have the resource definitions detailed like in aws_iam_policy_document data source, but a simple JSON input would be a good start.

**Comment by mwhipple** [comment]
FWIW I started on this last year and creating enough to address my immediate concerns and then continued to build things out but have since changed jobs and am no longer involved with similar work.

https://github.com/mwhipple/terraform-provider-aws/blob/dp/aws/resource_aws_datapipeline_definition.go

It supports defining pipeline components using a form along the lines of (I think):
```
  ...
  object {
    rds_database {
      ...config
    }
  }
```
If there's an interest in wider use (and especially any form of taking it over or contributing) I could look at dusting it off and making sure it handles identified use cases

Using JSON would *certainly* be more economical given how much many objects are involved, but I think I ended up going the full schema route due to the fact that the JSON couldn't be passed directly through the SDK and I think in particular conversions for the `datapipeline.Field` types seemed annoying enough to prefer going in the other direction. The service itself also seems fairly limited in terms of being able to modify existing definitions where typically replacement of the pipeline seems to be required; if there's any desire to modify when possible then having a more strongly defined definition could be helpful.

**Comment by ZsoltPath** [comment]
I see what you mean. I was looking at the AWS CLI where you can upload a JSON definition file.
But checking the SDK it requires PipelineObject structures.

I guess it'd be still quicker to just get it from a terraform list(map(any)) variable.
Of course it'd lack the syntax checking. But that seems to be very adventurous for me.

```
locals {
pipeline = [
  { 
    id = "database",
    name = "name",
    type = "rdsDb",
    param1 = "something"
  },
  { 
    id = "action",
    name = "actionName",
    type = "copy",
    param1 = "some other thing"
  }
]
}

resource "aws_datapipeline_defintion" {
  id = aws_datapipeline_pipeline.test.id
  pipeline_objects = local.pipeline
}
```

**Comment by mwhipple** [comment]
It feels as though Data Pipeline is fairly neglected by AWS also (they seem to have a large number of overlapping similar projects and this one seems to have not been one of the lucky winners). While that makes building out support potentially less attractive and likely helps explain its current absence, it also lends itself to the prospect that the API will remain fairly static. The breadth of the functionality seems more likely to incur maintenance costs from TF changes (which may have supporting tooling) as opposed to also chasing a moving target.

**Comment by ZsoltPath** [comment]
I've looked at the API docs and you're right. It isn't simple to import the JSON. 
I was mistaken it with the CLI.

If you don't mind @mwhipple I'd copy over your code, add a few more objects and prepare the PR.

**Comment by mwhipple** [comment]
@ZsoltPath that works for me: let me know if there's anything in particular I can help with. I think I'd somewhat pivoted to getting the skeletal code together for tests so things were likely left in a place where both the objects and the corresponding tests were ready to be filled in but had yet to acquire too much mass.

**Comment by Jahsis** [comment]
@ZsoltPath maybe you have any updates on this issue?

**Comment by ZsoltPath** [comment]
> @ZsoltPath maybe you have any updates on this issue?

Sorry, I have looked at it, but then sidetracked with my main job.
At the moment I won't have time to work on it any time soon.

**Pull request closed without merging**
