### PR TITLE
tests/resource/aws_default_security_group: Remove hardcoded us-east-1 handling

### PR DESCRIPTION
**Pull request by bflad**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Reference: https://github.com/hashicorp/terraform-provider-aws/issues/8316
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15737
Reference: https://github.com/hashicorp/terraform-provider-aws/issues/15791

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Previously in AWS GovCloud (US):

```
=== RUN   TestAccAWSDefaultSecurityGroup_Classic_basic
TestAccAWSDefaultSecurityGroup_Classic_basic: provider_test.go:196: [{0 error configuring Terraform AWS Provider: error validating provider credentials: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
  status code: 403, request id: fc6cf64f-8c40-4e8b-a37c-a82d8c6a69c9  []}]
--- FAIL: TestAccAWSDefaultSecurityGroup_Classic_basic (0.40s)
```

Output from acceptance testing in AWS Commercial:

```
--- PASS: TestAccAWSDefaultSecurityGroup_Classic_basic (16.47s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_basic (2.90s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
```

### CODE REVIEW

**Comment by YakDriver** [comment]
Going to investigate this failure more:

Commercial:
```
--- PASS: TestAWSDefaultSecurityGroupMigrateState (0.14s)
--- PASS: TestAWSDefaultSecurityGroupMigrateState_empty (0.16s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_basic (0.00s)
--- FAIL: TestAccAWSDefaultSecurityGroup_Vpc_basic (7.88s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_empty (15.24s)
```

**Review by YakDriver — CHANGES_REQUESTED** [review]
`TestAccAWSDefaultSecurityGroup_Vpc_basic` is consistently failing. It looks like it wasn't directly changed but is expecting `us-east-1`.

```
Attribute 'arn' expected "arn:aws:ec2:us-east-1:187416307283:security-group/sg-08749b1cfe35c9563",
got "arn:aws:ec2:us-west-2:187416307283:security-group/sg-08749b1cfe35c9563"
```

**Comment by bflad** [comment]
The new commit should fix that issue -- both the regular region test and EC2-Classic region test were using the ARN checking function. 🤦  Please note that this resource testing needs to be run with no parallelism locally until https://github.com/hashicorp/terraform-provider-aws/pull/16018 is reviewed and merged.

Output from acceptance testing in AWS Commercial:

```
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (54.56s)
--- PASS: TestAccAWSDefaultSecurityGroup_Classic_basic (16.91s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_empty (33.82s)
```

Output from acceptance testing in AWS GovCloud (US):

```
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_basic (2.96s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_empty (38.18s)
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (62.71s)
```

**Review by YakDriver — APPROVED** [review]
Looking great! 💯 

GovCloud:
```
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (55.09s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_basic (2.79s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
```

Commercial:
```
--- PASS: TestAccAWSDefaultSecurityGroup_Vpc_basic (47.26s)
--- SKIP: TestAccAWSDefaultSecurityGroup_Classic_empty (0.00s)
--- PASS: TestAccAWSDefaultSecurityGroup_Classic_basic (12.43s)
```

**Pull request merged**
