### PR TITLE
sweeper/backup_vault: add sweeper with concurrency

### LINKED ISSUE #19847: Implement `aws_backup_vault` sweeper
The resource `aws_backup_vault` does not have a sweeper, while `aws_backup_vault_notifications` and `aws_backup_vault_policy` do.

Add a sweeper for `aws_backup_vault`

### Affected Resource

* aws_backup_vault

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19847 
Relates #15334

Output from acceptance testing:

```
will be covered by nightly runs
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
```
2021/06/18 13:05:38 [DEBUG] Running Sweeper (aws_backup_vault) in region (us-west-2)
2021/06/18 13:05:39 [INFO] Skipping Backup Vault: Default
2021/06/18 13:05:39 [ERROR] Error running Sweeper (aws_backup_vault) in region (us-west-2): 1 error occurred:
	* error sweeping Backup Vaults for us-west-2: 10 errors occurred:
	* error deleting Backup Vault (tf_acc_test_backup_vault_7012118647341857814): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (aws/efs/automatic-backup-vault): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf-testacc-backup-ek8qgokzsov9of): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf-testacc-backup-dylv32dfdsk22m): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf_acc_test_backup_vault_1840574367621608621): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf_acc_test_backup_vault_4582763099159887277): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf_acc_test_backup_plan_6658497300030569382): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf_acc_test_backup_vault_1164508845823305797): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf_acc_test_backup_plan_9005306000506772449): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.

	* error deleting Backup Vault (tf_acc_test_backup_plan_2922497242099078929): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteBackupVaultInput.BackupVaultName.
```

https://github.com/hashicorp/terraform-provider-aws/blob/00c665ddb600941ad8a22bb40d1cae785c0be6ae/aws/resource_aws_backup_vault.go#L139-L152

I'd suggest changing the Delete handler code to

```go
	input := &backup.DeleteBackupVaultInput{
		BackupVaultName: aws.String(d.Id()),
	}
```

**Comment by anGie44** [comment]
@ewbankkit , also added in a condition to catch skip over backups created by EFS. or do you think there are acceptance tests related to EFS that could be adjusted to make sure their backups can be deleted later on?

**Comment by ewbankkit** [comment]
Support for automated EFS backups are requested in https://github.com/hashicorp/terraform-provider-aws/issues/14372.
I'll add a link to this PR in the PR that addresses that issue and we can leave what you have for now.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% TEST=./aws SWEEP=us-east-1,us-east-2,us-west-1,us-west-2 SWEEPARGS=-sweep-run=aws_backup_vault make sweep
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-east-1,us-east-2,us-west-1,us-west-2 -sweep-run=aws_backup_vault -timeout 60m
2021/06/18 14:16:05 [DEBUG] Running Sweepers for region (us-east-1):
2021/06/18 14:16:05 [DEBUG] Running Sweeper (aws_backup_vault_notifications) in region (us-east-1)
2021/06/18 14:16:05 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 14:16:05 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:05 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:06 [INFO] Deleting Backup Vault Notifications Default
2021/06/18 14:16:06 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_notifications), running..
2021/06/18 14:16:06 [DEBUG] Sweeper (aws_backup_vault_notifications) already ran in region (us-east-1)
2021/06/18 14:16:06 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_policy), running..
2021/06/18 14:16:06 [DEBUG] Running Sweeper (aws_backup_vault_policy) in region (us-east-1)
2021/06/18 14:16:06 [INFO] Deleting Backup Vault Policies Default
2021/06/18 14:16:06 [DEBUG] Running Sweeper (aws_backup_vault) in region (us-east-1)
2021/06/18 14:16:06 [INFO] Skipping Backup Vault: Default
2021/06/18 14:16:06 [DEBUG] Sweeper (aws_backup_vault_policy) already ran in region (us-east-1)
2021/06/18 14:16:06 Sweeper Tests ran successfully:
	- aws_backup_vault_notifications
	- aws_backup_vault_policy
	- aws_backup_vault
2021/06/18 14:16:06 [DEBUG] Running Sweepers for region (us-east-2):
2021/06/18 14:16:06 [DEBUG] Running Sweeper (aws_backup_vault_policy) in region (us-east-2)
2021/06/18 14:16:06 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 14:16:06 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:06 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:08 [DEBUG] No Backup Vault Policies to sweep
2021/06/18 14:16:08 [DEBUG] Running Sweeper (aws_backup_vault_notifications) in region (us-east-2)
2021/06/18 14:16:08 [DEBUG] No Backup Vault Notifications to sweep
2021/06/18 14:16:08 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_notifications), running..
2021/06/18 14:16:08 [DEBUG] Sweeper (aws_backup_vault_notifications) already ran in region (us-east-2)
2021/06/18 14:16:08 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_policy), running..
2021/06/18 14:16:08 [DEBUG] Sweeper (aws_backup_vault_policy) already ran in region (us-east-2)
2021/06/18 14:16:08 [DEBUG] Running Sweeper (aws_backup_vault) in region (us-east-2)
2021/06/18 14:16:08 Sweeper Tests ran successfully:
	- aws_backup_vault_policy
	- aws_backup_vault_notifications
	- aws_backup_vault
2021/06/18 14:16:08 [DEBUG] Running Sweepers for region (us-west-1):
2021/06/18 14:16:08 [DEBUG] Running Sweeper (aws_backup_vault_policy) in region (us-west-1)
2021/06/18 14:16:08 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 14:16:08 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:08 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:09 [DEBUG] No Backup Vault Policies to sweep
2021/06/18 14:16:09 [DEBUG] Running Sweeper (aws_backup_vault_notifications) in region (us-west-1)
2021/06/18 14:16:10 [DEBUG] No Backup Vault Notifications to sweep
2021/06/18 14:16:10 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_notifications), running..
2021/06/18 14:16:10 [DEBUG] Sweeper (aws_backup_vault_notifications) already ran in region (us-west-1)
2021/06/18 14:16:10 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_policy), running..
2021/06/18 14:16:10 [DEBUG] Sweeper (aws_backup_vault_policy) already ran in region (us-west-1)
2021/06/18 14:16:10 [DEBUG] Running Sweeper (aws_backup_vault) in region (us-west-1)
2021/06/18 14:16:10 Sweeper Tests ran successfully:
	- aws_backup_vault_policy
	- aws_backup_vault_notifications
	- aws_backup_vault
2021/06/18 14:16:10 [DEBUG] Running Sweepers for region (us-west-2):
2021/06/18 14:16:10 [DEBUG] Running Sweeper (aws_backup_vault_policy) in region (us-west-2)
2021/06/18 14:16:10 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 14:16:10 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:10 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 14:16:12 [INFO] Deleting Backup Vault Policies Default
2021/06/18 14:16:12 [INFO] Deleting Backup Vault Policies aws/efs/automatic-backup-vault
2021/06/18 14:16:13 [DEBUG] Running Sweeper (aws_backup_vault_notifications) in region (us-west-2)
2021/06/18 14:16:13 [INFO] Deleting Backup Vault Notifications Default
2021/06/18 14:16:14 [INFO] Deleting Backup Vault Notifications aws/efs/automatic-backup-vault
2021/06/18 14:16:14 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_notifications), running..
2021/06/18 14:16:14 [DEBUG] Sweeper (aws_backup_vault_notifications) already ran in region (us-west-2)
2021/06/18 14:16:14 [DEBUG] Sweeper (aws_backup_vault) has dependency (aws_backup_vault_policy), running..
2021/06/18 14:16:14 [DEBUG] Sweeper (aws_backup_vault_policy) already ran in region (us-west-2)
2021/06/18 14:16:14 [DEBUG] Running Sweeper (aws_backup_vault) in region (us-west-2)
2021/06/18 14:16:14 [INFO] Skipping Backup Vault: Default
2021/06/18 14:16:14 [INFO] Skipping Backup Vault: aws/efs/automatic-backup-vault
2021/06/18 14:16:14 Sweeper Tests ran successfully:
	- aws_backup_vault
	- aws_backup_vault_policy
	- aws_backup_vault_notifications
ok  	github.com/terraform-providers/terraform-provider-aws/aws	13.916s
```

**Pull request merged**
