### PR TITLE
Add MWAA service client

### PR DESCRIPTION
**Pull request by shuheiktgw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/hashicorp/terraform-provider-aws/issues/16432

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
None
```

Output from acceptance testing:

```
None
```

For the first step to support MWAA, I added an MWAA service client. Thank you for your review! 👍

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM.

```console
$ go test ./aws
go: downloading github.com/aws/aws-sdk-go v1.35.35
ok  	github.com/terraform-providers/terraform-provider-aws/aws	25.137s
```

**Review by bflad — CHANGES_REQUESTED** [review]
Hi @shuheiktgw 👋  Thank you for submitting this. Can you please also add the new service to `infrastructure/repository/labels-service.tf`? See also [Contributing Guide](https://github.com/hashicorp/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#new-service). Thanks!

**Comment by shuheiktgw** [comment]
@bflad Sorry, I missed that. I fixed it now so would you mind reviewing the PR again? 🙏 

```
go test ./aws
ok  	github.com/terraform-providers/terraform-provider-aws/aws	16.996s
```

**Review by bflad — APPROVED** [review]
Looks good to me, thank you @shuheiktgw 🚀

**Pull request merged**
