### PR TITLE
Add aws_codestarconnections_host resource

### PR DESCRIPTION
**Pull request by shuheiktgw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/hashicorp/terraform-provider-aws/issues/15453

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* **New Resource:** `aws_codestarconnections_host`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCodeStarConnectionsHost_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCodeStarConnectionsHost_* -timeout 120m
=== RUN   TestAccAWSCodeStarConnectionsHost_basic
=== PAUSE TestAccAWSCodeStarConnectionsHost_basic
=== RUN   TestAccAWSCodeStarConnectionsHost_disappears
=== PAUSE TestAccAWSCodeStarConnectionsHost_disappears
=== RUN   TestAccAWSCodeStarConnectionsHost_vpcConfig
=== PAUSE TestAccAWSCodeStarConnectionsHost_vpcConfig
=== CONT  TestAccAWSCodeStarConnectionsHost_basic
=== CONT  TestAccAWSCodeStarConnectionsHost_vpcConfig
=== CONT  TestAccAWSCodeStarConnectionsHost_disappears
--- PASS: TestAccAWSCodeStarConnectionsHost_disappears (87.31s)
--- PASS: TestAccAWSCodeStarConnectionsHost_basic (96.56s)
--- PASS: TestAccAWSCodeStarConnectionsHost_vpcConfig (483.70s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	485.633s
```

Thank you for your review! 👍

### CODE REVIEW

**Comment by Meroje** [comment]
Eager to see this land, thank you for doing this :)

Anyway, shouldn't the host arn be made available as a parameter to the connection resource as it is required on the API side ? https://docs.aws.amazon.com/codestar-connections/latest/APIReference/API_CreateConnection.html#codestarconnections-CreateConnection-request-HostArn

**Comment by shuheiktgw** [comment]
Hi, @Meroje. Thank you for your comment! I guess you are talking about CodeStar Connection, not CodeStar Host. You may want to check the PR below!

- https://github.com/hashicorp/terraform-provider-aws/pull/15990

**Comment by shuheiktgw** [comment]
Oh, wait. I think I understood what you mean. Since this PR adds `aws_codestarconnections_host`, we can add the host_arn parameter to `aws_codestarconnections_connection`. Let me fix that.

**Comment by Meroje** [comment]
Yes absolutely! But when I tried it out today it was not working because of this HostArn param, the aws api actually gives an error about it. So I figured I actually need this here PR because the connection needs the host and the host don't do anything alone.
Is it intended that #15990 was merged as what appears to me in a broken state and when should the fix be done ? I could open the PR if it will not be done here (I get it, related PR but not actually the same resource) but I've seen this kind take too long to get any review and land.

**Comment by shuheiktgw** [comment]
Hmm, I recommend you file an issue to explain the situation. In order to add the `host_arn` attribute to `aws_codestarconnections_connection`, this PR needs to be reviewed and merged first.

**Review by bflad — APPROVED** [review]
Thank you so much for this, @shuheiktgw, bringing this in with some modernization of using `waiter` package, `_Values()` for validation, and adding a changelog file 🚀 

Output from acceptance testing:

```
--- PASS: TestAccAWSCodeStarConnectionsHost_disappears (111.09s)
--- PASS: TestAccAWSCodeStarConnectionsHost_basic (115.11s)
--- PASS: TestAccAWSCodeStarConnectionsHost_vpcConfig (581.12s)
```

**Pull request merged**
