### PR TITLE
r/aws_imagebuilder_container_recipe - new resource

### LINKED ISSUE #16839: EC2 Image Builder container images
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> Customers of EC2 Image Builder can now build and test container images compliant with the Open Container Initiative (OCI) specification.

### New or Affected Resource(s)

* `aws_imagebuilder_container_recipe`
* `aws_imagebuilder_container_recipe_policy`

### Potential Terraform Configuration

```hcl
resource "aws_imagebuilder_container_recipe" "example" {
  name             = "example-recipe"
  container_type   = "DOCKER"
  semantic_version = "1.0.0"
  ...
}

resource "aws_imagebuilder_container_recipe_policy" "example" {
  container_recipe_arn = aws_imagebuilder_container_recipe.example.arn

  policy = jsonencode({
  ...
  })
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/12/ec2-image-builder-supports-container-images/).
[User Guide](https://docs.aws.amazon.com/imagebuilder/latest/userguide/start-build-container-pipeline.html).

Requires [AWS SDK v1.36.11](https://github.com/aws/aws-sdk-go/releases/tag/v1.36.11):

* https://github.com/hashicorp/terraform-provider-aws/pull/16834

### PR DESCRIPTION
**Pull request by kamilturek**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16839.

Output from acceptance testing:

```
$ make testacc PKG_NAME=internal/service/imagebuilder TESTARGS="-run=TestAccImageBuilderContainerRecipe_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20  -run=TestAccImageBuilderContainerRecipe_ -timeout 180m
=== RUN   TestAccImageBuilderContainerRecipe_basic
=== PAUSE TestAccImageBuilderContainerRecipe_basic
=== RUN   TestAccImageBuilderContainerRecipe_disappears
=== PAUSE TestAccImageBuilderContainerRecipe_disappears
=== RUN   TestAccImageBuilderContainerRecipe_component
=== PAUSE TestAccImageBuilderContainerRecipe_component
=== RUN   TestAccImageBuilderContainerRecipe_componentParameter
=== PAUSE TestAccImageBuilderContainerRecipe_componentParameter
=== RUN   TestAccImageBuilderContainerRecipe_description
=== PAUSE TestAccImageBuilderContainerRecipe_description
=== RUN   TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== PAUSE TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== RUN   TestAccImageBuilderContainerRecipe_kmsKeyID
=== PAUSE TestAccImageBuilderContainerRecipe_kmsKeyID
=== RUN   TestAccImageBuilderContainerRecipe_tags
=== PAUSE TestAccImageBuilderContainerRecipe_tags
=== RUN   TestAccImageBuilderContainerRecipe_workingDirectory
=== PAUSE TestAccImageBuilderContainerRecipe_workingDirectory
=== CONT  TestAccImageBuilderContainerRecipe_basic
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== CONT  TestAccImageBuilderContainerRecipe_workingDirectory
=== CONT  TestAccImageBuilderContainerRecipe_tags
=== CONT  TestAccImageBuilderContainerRecipe_kmsKeyID
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== CONT  TestAccImageBuilderContainerRecipe_componentParameter
=== CONT  TestAccImageBuilderContainerRecipe_description
=== CONT  TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== CONT  TestAccImageBuilderContainerRecipe_component
=== CONT  TestAccImageBuilderContainerRecipe_disappears
--- PASS: TestAccImageBuilderContainerRecipe_disappears (42.46s)
--- PASS: TestAccImageBuilderContainerRecipe_workingDirectory (46.10s)
--- PASS: TestAccImageBuilderContainerRecipe_componentParameter (46.69s)
--- PASS: TestAccImageBuilderContainerRecipe_description (46.69s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops (46.78s)
--- PASS: TestAccImageBuilderContainerRecipe_component (46.94s)
--- PASS: TestAccImageBuilderContainerRecipe_basic (46.95s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize (48.43s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted (48.43s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice (48.62s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination (48.78s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName (49.06s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName (49.97s)
--- PASS: TestAccImageBuilderContainerRecipe_kmsKeyID (50.09s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType (50.24s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID (50.70s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image (52.38s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID (63.54s)
--- PASS: TestAccImageBuilderContainerRecipe_dockerfileTemplateURI (71.89s)
--- PASS: TestAccImageBuilderContainerRecipe_tags (102.37s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder       104.009s
```
```
$ SWEEPARGS="-sweep-run=aws_imagebuilder_container_recipe" make sweep
# make sweep SWEEPARGS=-sweep-run=aws_example_thing
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./internal/sweep -v -tags=sweep -sweep=us-west-2,us-east-1,us-east-2 -sweep-run=aws_imagebuilder_container_recipe -timeout 60m
2022/02/06 20:06:23 [DEBUG] Running Sweepers for region (us-west-2):
2022/02/06 20:06:23 [DEBUG] Running Sweeper (aws_imagebuilder_container_recipe) in region (us-west-2)
2022/02/06 20:06:23 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/06 20:06:24 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/06 20:06:27 [DEBUG] Completed Sweeper (aws_imagebuilder_container_recipe) in region (us-west-2) in 3.817512416s
2022/02/06 20:06:27 Completed Sweepers for region (us-west-2) in 3.817783833s
2022/02/06 20:06:27 Sweeper Tests for region (us-west-2) ran successfully:
        - aws_imagebuilder_container_recipe
2022/02/06 20:06:27 [DEBUG] Running Sweepers for region (us-east-1):
2022/02/06 20:06:27 [DEBUG] Running Sweeper (aws_imagebuilder_container_recipe) in region (us-east-1)
2022/02/06 20:06:27 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/06 20:06:27 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/06 20:06:29 [DEBUG] Completed Sweeper (aws_imagebuilder_container_recipe) in region (us-east-1) in 2.606706875s
2022/02/06 20:06:29 Completed Sweepers for region (us-east-1) in 2.606784333s
2022/02/06 20:06:29 Sweeper Tests for region (us-east-1) ran successfully:
        - aws_imagebuilder_container_recipe
2022/02/06 20:06:29 [DEBUG] Running Sweepers for region (us-east-2):
2022/02/06 20:06:29 [DEBUG] Running Sweeper (aws_imagebuilder_container_recipe) in region (us-east-2)
2022/02/06 20:06:29 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/06 20:06:30 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2022/02/06 20:06:32 [DEBUG] Completed Sweeper (aws_imagebuilder_container_recipe) in region (us-east-2) in 2.625379166s
2022/02/06 20:06:32 Completed Sweepers for region (us-east-2) in 2.625513917s
2022/02/06 20:06:32 Sweeper Tests for region (us-east-2) ran successfully:
        - aws_imagebuilder_container_recipe
ok      github.com/hashicorp/terraform-provider-aws/internal/sweep      10.623s
```

### CODE REVIEW

**Comment by mrobinson-anaplan** [comment]
Thanks for adding this featue.  I've been testing it out by building from your fork.
One issue.  https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/imagebuilder_image_pipeline doesn't accept a container recipe, so I think an update to that resource (possibly just the regex used to validate the arn) is required to make use of this new resource
```
│ Error: invalid value for image_recipe_arn (valid image recipe ARN must be provided)
│ 
│   with module.ecs_agents.aws_imagebuilder_image_pipeline.image,
│   on ../tf-module-aws-tfe-agents/image.tf line 119, in resource "aws_imagebuilder_image_pipeline" "image":
│  119:   image_recipe_arn                 = aws_imagebuilder_container_recipe.image.arn
│ 
╵

**Comment by kamilturek** [comment]
@mrobinson-anaplan You're right! Thanks for noticing it. I will add a necessary change.

**Comment by kamilturek** [comment]
Regarding the a`container_recipe_arn` in the Image Pipeline resource, I will add it in a separate PR to keep every PR focused on a single resource. It's here: https://github.com/hashicorp/terraform-provider-aws/pull/23111

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTS=TestAccImageBuilderContainerRecipe_ PKG=imagebuilder
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderContainerRecipe_'  -timeout 180m
=== RUN   TestAccImageBuilderContainerRecipe_basic
=== PAUSE TestAccImageBuilderContainerRecipe_basic
=== RUN   TestAccImageBuilderContainerRecipe_disappears
=== PAUSE TestAccImageBuilderContainerRecipe_disappears
=== RUN   TestAccImageBuilderContainerRecipe_component
=== PAUSE TestAccImageBuilderContainerRecipe_component
=== RUN   TestAccImageBuilderContainerRecipe_componentParameter
=== PAUSE TestAccImageBuilderContainerRecipe_componentParameter
=== RUN   TestAccImageBuilderContainerRecipe_description
=== PAUSE TestAccImageBuilderContainerRecipe_description
=== RUN   TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== PAUSE TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== RUN   TestAccImageBuilderContainerRecipe_kmsKeyID
=== PAUSE TestAccImageBuilderContainerRecipe_kmsKeyID
=== RUN   TestAccImageBuilderContainerRecipe_tags
=== PAUSE TestAccImageBuilderContainerRecipe_tags
=== RUN   TestAccImageBuilderContainerRecipe_workingDirectory
=== PAUSE TestAccImageBuilderContainerRecipe_workingDirectory
=== CONT  TestAccImageBuilderContainerRecipe_basic
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== CONT  TestAccImageBuilderContainerRecipe_tags
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== CONT  TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== CONT  TestAccImageBuilderContainerRecipe_componentParameter
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== CONT  TestAccImageBuilderContainerRecipe_workingDirectory
=== CONT  TestAccImageBuilderContainerRecipe_description
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== CONT  TestAccImageBuilderContainerRecipe_kmsKeyID
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== CONT  TestAccImageBuilderContainerRecipe_disappears
=== CONT  TestAccImageBuilderContainerRecipe_component
--- PASS: TestAccImageBuilderContainerRecipe_disappears (60.02s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID (65.39s)
--- PASS: TestAccImageBuilderContainerRecipe_basic (67.97s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType (69.53s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName (71.93s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize (72.02s)
--- PASS: TestAccImageBuilderContainerRecipe_component (72.31s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination (72.50s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted (72.54s)
--- PASS: TestAccImageBuilderContainerRecipe_kmsKeyID (72.57s)
--- PASS: TestAccImageBuilderContainerRecipe_componentParameter (72.61s)
--- PASS: TestAccImageBuilderContainerRecipe_workingDirectory (72.71s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops (72.75s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName (72.77s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice (72.78s)
--- PASS: TestAccImageBuilderContainerRecipe_description (72.82s)
--- PASS: TestAccImageBuilderContainerRecipe_dockerfileTemplateURI (77.43s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image (84.47s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID (89.44s)
--- PASS: TestAccImageBuilderContainerRecipe_tags (123.92s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder	130.285s
```

##### GovCloud

```console
% make testacc TESTS=TestAccImageBuilderContainerRecipe_ PKG=imagebuilder
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/imagebuilder/... -v -count 1 -parallel 20 -run='TestAccImageBuilderContainerRecipe_'  -timeout 180m
=== RUN   TestAccImageBuilderContainerRecipe_basic
=== PAUSE TestAccImageBuilderContainerRecipe_basic
=== RUN   TestAccImageBuilderContainerRecipe_disappears
=== PAUSE TestAccImageBuilderContainerRecipe_disappears
=== RUN   TestAccImageBuilderContainerRecipe_component
=== PAUSE TestAccImageBuilderContainerRecipe_component
=== RUN   TestAccImageBuilderContainerRecipe_componentParameter
=== PAUSE TestAccImageBuilderContainerRecipe_componentParameter
=== RUN   TestAccImageBuilderContainerRecipe_description
=== PAUSE TestAccImageBuilderContainerRecipe_description
=== RUN   TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== PAUSE TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== RUN   TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== PAUSE TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== RUN   TestAccImageBuilderContainerRecipe_kmsKeyID
=== PAUSE TestAccImageBuilderContainerRecipe_kmsKeyID
=== RUN   TestAccImageBuilderContainerRecipe_tags
=== PAUSE TestAccImageBuilderContainerRecipe_tags
=== RUN   TestAccImageBuilderContainerRecipe_workingDirectory
=== PAUSE TestAccImageBuilderContainerRecipe_workingDirectory
=== CONT  TestAccImageBuilderContainerRecipe_basic
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName
=== CONT  TestAccImageBuilderContainerRecipe_workingDirectory
=== CONT  TestAccImageBuilderContainerRecipe_tags
=== CONT  TestAccImageBuilderContainerRecipe_kmsKeyID
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image
=== CONT  TestAccImageBuilderContainerRecipe_dockerfileTemplateURI
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted
=== CONT  TestAccImageBuilderContainerRecipe_componentParameter
=== CONT  TestAccImageBuilderContainerRecipe_description
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName
=== CONT  TestAccImageBuilderContainerRecipe_component
=== CONT  TestAccImageBuilderContainerRecipe_disappears
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice
=== CONT  TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID
--- PASS: TestAccImageBuilderContainerRecipe_disappears (43.47s)
--- PASS: TestAccImageBuilderContainerRecipe_kmsKeyID (54.28s)
--- PASS: TestAccImageBuilderContainerRecipe_component (54.67s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_deviceName (55.08s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeType (58.18s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_iops (60.64s)
--- PASS: TestAccImageBuilderContainerRecipe_description (60.66s)
--- PASS: TestAccImageBuilderContainerRecipe_workingDirectory (61.10s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_noDevice (61.10s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMapping_virtualName (61.55s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_encrypted (61.75s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_deleteOnTermination (61.75s)
--- PASS: TestAccImageBuilderContainerRecipe_componentParameter (62.28s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_kmsKeyID (62.28s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_Image (62.61s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_volumeSize (62.65s)
--- PASS: TestAccImageBuilderContainerRecipe_basic (62.79s)
--- PASS: TestAccImageBuilderContainerRecipe_dockerfileTemplateURI (67.63s)
--- PASS: TestAccImageBuilderContainerRecipe_InstanceConfiguration_BlockDeviceMappingEBS_snapshotID (75.72s)
--- PASS: TestAccImageBuilderContainerRecipe_tags (95.50s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/imagebuilder	100.143s
```

**Comment by ewbankkit** [comment]
@kamilturek Thanks for the contribution :tada: :clap:.

**Pull request merged**
