### PR TITLE
service/dms: add data source for dms_replication_instance

### PR DESCRIPTION
**Pull request by snypelife**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates to #12713

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* data/aws_dms_replication_instance: Adds data source for DMS Replication instance
```

Output from acceptance testing:

```
I currently don't have authorization to run the acceptance tests under my companies account 😞
```

### CODE REVIEW

**Comment by snypelife** [comment]
Sorry, I know it's only a single data source, instead of all of them for DMS. I'm fairly unfamiliar with Go, and I wanted to keep the pull request as small as possible to make reviewing easier.

**Comment by elijah-ward** [comment]
Nice work Brett.

**Comment by elijah-ward** [comment]
Nice work @snypelife

**Comment by stpierre** [comment]
What's blocking this? This is a pretty significant gap and we'd love for it to be closed.

**Comment by snypelife** [comment]
Heyo! Any uptake on this by any chance? I know it's probably not the most requested feature, but it's intentionally small to make review and acceptance (hopefully) easier.

Thanks!

**Review by nam054 — COMMENTED** [review]
Thank you for contributing! 🚀

**Comment by nam054** [comment]
> make testacc TESTARGS='-run=TestAccDMSReplicationInstanceDataSource_basic' PKG=dms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20  -run=TestAccDMSReplicationInstanceDataSource_basic -timeout 180m
=== RUN   TestAccDMSReplicationInstanceDataSource_basic
=== PAUSE TestAccDMSReplicationInstanceDataSource_basic
=== CONT  TestAccDMSReplicationInstanceDataSource_basic
--- PASS: TestAccDMSReplicationInstanceDataSource_basic (883.52s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        886.578s

**Comment by snypelife** [comment]
🎉 Thanks for merging this @nam054!

**Pull request merged**
