### PR TITLE
New Resource aws_rds_integration

### PR DESCRIPTION
**Pull request by showwin**
### Description
This PR is to add a new resource aws_rds_integration to the RDS Family.

### Relations
Closes https://github.com/hashicorp/terraform-provider-aws/issues/34179

### References
* https://docs.aws.amazon.com/AmazonRDS/latest/AuroraUserGuide/zero-etl.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateIntegration.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DescribeIntegrations.html
* https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_DeleteIntegration.html

### Output from Acceptance Testing

```console
$ make testacc TESTS=TestAccRDSIntegration_basic PKG=rds
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSIntegration_basic'  -timeout 360m
=== RUN   TestAccRDSIntegration_basic
=== PAUSE TestAccRDSIntegration_basic
=== CONT  TestAccRDSIntegration_basic
Current DB instance status: available
--- PASS: TestAccRDSIntegration_basic (2948.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	2951.012s

$ make testacc TESTS=TestAccRDSIntegration_optional PKG=rds
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSIntegration_optional'  -timeout 360m
=== RUN   TestAccRDSIntegration_optional
=== PAUSE TestAccRDSIntegration_optional
=== CONT  TestAccRDSIntegration_optional
Current DB instance status: available
--- PASS: TestAccRDSIntegration_optional (3005.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	3007.416s
```

### CODE REVIEW

**Comment by zwallacedev** [comment]
I wanted to check in here to see if anyone is able to prioritize this request?

**Comment by EthanJStark** [comment]
Adding my vote to prioritize this PR. Thanks! 🙏🏼

**Comment by rfornea** [comment]
My organization really needs this, would love this to be prioritized.

**Comment by masaki-hirose-kinto** [comment]
It would be wonderful if it could be given priority.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccRDSIntegration_basic' PKG=rds
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSIntegration_basic -timeout 720m
=== RUN   TestAccRDSIntegration_basic
=== PAUSE TestAccRDSIntegration_basic
=== CONT  TestAccRDSIntegration_basic
--- PASS: TestAccRDSIntegration_basic (1977.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	1982.537s
```
```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccRDSIntegration_optional\|TestAccRDSIntegration_disappears' PKG=rds
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 20  -run=TestAccRDSIntegration_optional\|TestAccRDSIntegration_disappears -timeout 720m
=== RUN   TestAccRDSIntegration_disappears
=== PAUSE TestAccRDSIntegration_disappears
=== RUN   TestAccRDSIntegration_optional
=== PAUSE TestAccRDSIntegration_optional
=== CONT  TestAccRDSIntegration_disappears
=== CONT  TestAccRDSIntegration_optional
--- PASS: TestAccRDSIntegration_disappears (2006.63s)
--- PASS: TestAccRDSIntegration_optional (2078.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	2083.470s
```
```console
% make testacc TESTARGS='-run=TestAccRDSOrderableInstanceDataSource_' PKG=rds ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSOrderableInstanceDataSource_ -timeout 360m
=== RUN   TestAccRDSOrderableInstanceDataSource_basic
=== PAUSE TestAccRDSOrderableInstanceDataSource_basic
=== RUN   TestAccRDSOrderableInstanceDataSource_preferredClass
=== PAUSE TestAccRDSOrderableInstanceDataSource_preferredClass
=== RUN   TestAccRDSOrderableInstanceDataSource_preferredVersion
=== PAUSE TestAccRDSOrderableInstanceDataSource_preferredVersion
=== RUN   TestAccRDSOrderableInstanceDataSource_preferredClassAndVersion
=== PAUSE TestAccRDSOrderableInstanceDataSource_preferredClassAndVersion
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsEnhancedMonitoring
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsEnhancedMonitoring
=== RUN   TestAccRDSOrderableInstanceDataSource_latestVersion
=== PAUSE TestAccRDSOrderableInstanceDataSource_latestVersion
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsGlobalDatabases
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsGlobalDatabases
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsClusters
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsClusters
=== RUN   TestAccRDSOrderableInstanceDataSource_readReplicaCapable
=== PAUSE TestAccRDSOrderableInstanceDataSource_readReplicaCapable
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsMultiAZ
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsMultiAZ
=== RUN   TestAccRDSOrderableInstanceDataSource_supportedEngineModes
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportedEngineModes
=== RUN   TestAccRDSOrderableInstanceDataSource_supportedNetworkTypes
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportedNetworkTypes
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsIAMDatabaseAuthentication
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsIAMDatabaseAuthentication
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsIops
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsIops
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsKerberosAuthentication
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsKerberosAuthentication
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsPerformanceInsights
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsPerformanceInsights
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsStorageAutoScaling
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsStorageAutoScaling
=== RUN   TestAccRDSOrderableInstanceDataSource_supportsStorageEncryption
=== PAUSE TestAccRDSOrderableInstanceDataSource_supportsStorageEncryption
=== CONT  TestAccRDSOrderableInstanceDataSource_basic
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsMultiAZ
=== CONT  TestAccRDSOrderableInstanceDataSource_latestVersion
--- PASS: TestAccRDSOrderableInstanceDataSource_basic (16.14s)
=== CONT  TestAccRDSOrderableInstanceDataSource_preferredClassAndVersion
--- PASS: TestAccRDSOrderableInstanceDataSource_latestVersion (35.00s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsEnhancedMonitoring
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsMultiAZ (40.15s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsClusters
--- PASS: TestAccRDSOrderableInstanceDataSource_preferredClassAndVersion (51.97s)
=== CONT  TestAccRDSOrderableInstanceDataSource_readReplicaCapable
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsEnhancedMonitoring (43.55s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsGlobalDatabases
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsClusters (41.37s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsKerberosAuthentication
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsGlobalDatabases (19.70s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsStorageEncryption
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsStorageEncryption (44.45s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsStorageAutoScaling
--- PASS: TestAccRDSOrderableInstanceDataSource_readReplicaCapable (105.68s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsPerformanceInsights
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsStorageAutoScaling (46.92s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportedNetworkTypes
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsKerberosAuthentication (131.31s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsIops
--- PASS: TestAccRDSOrderableInstanceDataSource_supportedNetworkTypes (27.86s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportedEngineModes
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsPerformanceInsights (48.52s)
=== CONT  TestAccRDSOrderableInstanceDataSource_preferredVersion
--- PASS: TestAccRDSOrderableInstanceDataSource_supportedEngineModes (33.82s)
=== CONT  TestAccRDSOrderableInstanceDataSource_preferredClass
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsIops (42.99s)
=== CONT  TestAccRDSOrderableInstanceDataSource_supportsIAMDatabaseAuthentication
--- PASS: TestAccRDSOrderableInstanceDataSource_preferredClass (13.96s)
--- PASS: TestAccRDSOrderableInstanceDataSource_preferredVersion (43.01s)
--- PASS: TestAccRDSOrderableInstanceDataSource_supportsIAMDatabaseAuthentication (44.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	305.354s
```
```console
% make testacc TESTARGS='-run=TestAccRDSEngineVersionDataSource_' PKG=rds ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSEngineVersionDataSource_ -timeout 360m
=== RUN   TestAccRDSEngineVersionDataSource_basic
=== PAUSE TestAccRDSEngineVersionDataSource_basic
=== RUN   TestAccRDSEngineVersionDataSource_upgradeTargets
=== PAUSE TestAccRDSEngineVersionDataSource_upgradeTargets
=== RUN   TestAccRDSEngineVersionDataSource_preferred
=== PAUSE TestAccRDSEngineVersionDataSource_preferred
=== RUN   TestAccRDSEngineVersionDataSource_preferredVersionsPreferredUpgradeTargets
=== PAUSE TestAccRDSEngineVersionDataSource_preferredVersionsPreferredUpgradeTargets
=== RUN   TestAccRDSEngineVersionDataSource_preferredUpgradeTargetsVersion
=== PAUSE TestAccRDSEngineVersionDataSource_preferredUpgradeTargetsVersion
=== RUN   TestAccRDSEngineVersionDataSource_preferredMajorTargets
=== PAUSE TestAccRDSEngineVersionDataSource_preferredMajorTargets
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== RUN   TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== PAUSE TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
=== RUN   TestAccRDSEngineVersionDataSource_includeAll
=== PAUSE TestAccRDSEngineVersionDataSource_includeAll
=== RUN   TestAccRDSEngineVersionDataSource_filter
=== PAUSE TestAccRDSEngineVersionDataSource_filter
=== RUN   TestAccRDSEngineVersionDataSource_latest
=== PAUSE TestAccRDSEngineVersionDataSource_latest
=== RUN   TestAccRDSEngineVersionDataSource_hasMinorMajor
=== PAUSE TestAccRDSEngineVersionDataSource_hasMinorMajor
=== CONT  TestAccRDSEngineVersionDataSource_basic
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyImplicit
=== CONT  TestAccRDSEngineVersionDataSource_filter
--- PASS: TestAccRDSEngineVersionDataSource_basic (8.06s)
=== CONT  TestAccRDSEngineVersionDataSource_preferredVersionsPreferredUpgradeTargets
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyImplicit (8.06s)
=== CONT  TestAccRDSEngineVersionDataSource_preferredMajorTargets
--- PASS: TestAccRDSEngineVersionDataSource_preferredVersionsPreferredUpgradeTargets (13.19s)
=== CONT  TestAccRDSEngineVersionDataSource_preferredUpgradeTargetsVersion
--- PASS: TestAccRDSEngineVersionDataSource_filter (13.87s)
=== CONT  TestAccRDSEngineVersionDataSource_preferred
--- PASS: TestAccRDSEngineVersionDataSource_preferredUpgradeTargetsVersion (6.96s)
=== CONT  TestAccRDSEngineVersionDataSource_upgradeTargets
--- PASS: TestAccRDSEngineVersionDataSource_upgradeTargets (6.88s)
=== CONT  TestAccRDSEngineVersionDataSource_hasMinorMajor
--- PASS: TestAccRDSEngineVersionDataSource_preferred (12.51s)
=== CONT  TestAccRDSEngineVersionDataSource_includeAll
--- PASS: TestAccRDSEngineVersionDataSource_preferredMajorTargets (20.84s)
=== CONT  TestAccRDSEngineVersionDataSource_latest
--- PASS: TestAccRDSEngineVersionDataSource_includeAll (6.92s)
=== CONT  TestAccRDSEngineVersionDataSource_defaultOnlyExplicit
--- PASS: TestAccRDSEngineVersionDataSource_defaultOnlyExplicit (6.92s)
--- PASS: TestAccRDSEngineVersionDataSource_hasMinorMajor (28.55s)
--- PASS: TestAccRDSEngineVersionDataSource_latest (30.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	64.367s
```
```console
% make testacc TESTARGS='-run=TestAccRDSCertificateDataSource_' PKG=rds ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSCertificateDataSource_ -timeout 360m
=== RUN   TestAccRDSCertificateDataSource_id
=== PAUSE TestAccRDSCertificateDataSource_id
=== RUN   TestAccRDSCertificateDataSource_latestValidTill
=== PAUSE TestAccRDSCertificateDataSource_latestValidTill
=== CONT  TestAccRDSCertificateDataSource_id
=== CONT  TestAccRDSCertificateDataSource_latestValidTill
--- PASS: TestAccRDSCertificateDataSource_latestValidTill (7.97s)
--- PASS: TestAccRDSCertificateDataSource_id (10.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	15.536s
```
```console
% make testacc TESTARGS='-run=TestAccRDSParameterGroupDataSource_' PKG=rds ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSParameterGroupDataSource_ -timeout 360m
=== RUN   TestAccRDSParameterGroupDataSource_basic
=== PAUSE TestAccRDSParameterGroupDataSource_basic
=== CONT  TestAccRDSParameterGroupDataSource_basic
--- PASS: TestAccRDSParameterGroupDataSource_basic (11.49s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	16.415s
```

**Pull request merged**
