### PR TITLE
Add parameter build_type to codebuild_webhook

### LINKED ISSUE #16824: CodeBuild WebHook for Batch Builds
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the `build_type` field to the `aws_codebuild_webhook` resource. This can be set to either 'BUILD', or 'BUILD_BATCH'.

### New or Affected Resource(s)

* aws_codebuild_webhook

### Potential Terraform Configuration

```hcl
resource "aws_codebuild_webhook" "build_hook" {
  project_name = aws_codebuild_project.build_project.name

  // ...

  build_type = "BUILD_BATCH"
}
```

### References

* #14472
* https://docs.aws.amazon.com/codebuild/latest/APIReference/API_Webhook.html#CodeBuild-Type-Webhook-buildType
* https://github.com/aws/aws-cdk/issues/11663

### PR DESCRIPTION
**Pull request by tatsuya-ogawa**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$make testacc TESTARGS='-run=TestAccAWSCodeBuildWebhook_BuildType'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCodeBuildWebhook_BuildType -timeout 180m
=== RUN   TestAccAWSCodeBuildWebhook_BuildType
=== PAUSE TestAccAWSCodeBuildWebhook_BuildType
=== CONT  TestAccAWSCodeBuildWebhook_BuildType
--- PASS: TestAccAWSCodeBuildWebhook_BuildType (92.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	93.776s
```

Closes #16824

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
AWS_CODEBUILD_GITHUB_SOURCE_LOCATION=... make testacc TESTARGS='-run=TestAccAWSCodeBuildWebhook_GitHub\|TestAccAWSCodeBuildWebhook_BuildType'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCodeBuildWebhook_GitHub\|TestAccAWSCodeBuildWebhook_BuildType -timeout 180m
=== RUN   TestAccAWSCodeBuildWebhook_GitHub
=== PAUSE TestAccAWSCodeBuildWebhook_GitHub
=== RUN   TestAccAWSCodeBuildWebhook_BuildType
=== PAUSE TestAccAWSCodeBuildWebhook_BuildType
=== CONT  TestAccAWSCodeBuildWebhook_GitHub
=== CONT  TestAccAWSCodeBuildWebhook_BuildType
--- PASS: TestAccAWSCodeBuildWebhook_GitHub (27.28s)
--- PASS: TestAccAWSCodeBuildWebhook_BuildType (37.59s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws       42.761s
```

**Comment by ewbankkit** [comment]
@tatsuya-ogawa Thanks for the contribution :tada: :clap:.

**Comment by jebl01** [comment]
@ewbankkit not specifying `build_type` (optional according to the doc) produces an invalid request to AWS (`"buildType":""`) making the apply fail :-(

I started writing a bug report,  but gave up at trying to provide a full working example...

**Comment by tatsuya-ogawa** [comment]
> @ewbankkit not specifying `build_type` (optional according to the doc) produces an invalid request to AWS (`"buildType":""`) making the apply fail :-(
> 
> I started writing a bug report, but gave up at trying to provide a full working example...

It seems `d.Get("build_type")` return blank string if key does not exists.
I created a bugfix pr to check the key `build_type` exists.
https://github.com/hashicorp/terraform-provider-aws/pull/20671

**Pull request merged**
