### PR TITLE
Use trail `arn` instead of `name` to get organization trails from a delegated account

### LINKED ISSUE #15553: Terraform fails to import a CloudTrail with 'Organization Trail' set to true
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
Terraform v0.13.4
+ provider registry.terraform.io/hashicorp/aws v3.9.0
```

### Affected Resource(s)

* aws_cloudtrail

### Terraform Configuration Files

```hcl
provider "aws" {
  alias   = "va"
  region  = "us-east-1"
  version = ">= 3.9.0"
}

resource "aws_cloudtrail" "events" {
  provider       = aws.va
  is_organization_trail = true
  name           = "events"
  s3_bucket_name = "events"
}
```

### Expected Behavior

Trail imported

### Actual Behavior

```
$ terraform state import aws_cloudtrail.events events                                    
aws_cloudtrail.events: Importing from ID "events"...
aws_cloudtrail.events: Import prepared!
  Prepared aws_cloudtrail for import
aws_cloudtrail.events: Refreshing state... [id=events]

Error: Cannot import non-existent remote object

While attempting to import an existing object to
aws_cloudtrail.events, the provider detected that no object exists
with the given id. Only pre-existing objects can be imported; check that the
id is correct and that it is associated with the provider's configured region
or endpoint, or use "terraform apply" to create a new remote object for this
resource.

Releasing state lock. This may take a few moments...
```

### Steps to Reproduce

1.  manually create the CloudTrail trail with name trail-organizations
3. set Apply trail to my organization to yes
4. select/create an S3 bucket
5. try to import the resource

### Important Factoids

A trail with `"IsOrganizationTrail": true` cannot be described by the name, only by the arn. However, import relies on `Name` field

```
$ aws cloudtrail describe-trails --trail-name-list='["events"]' --region=us-east-1                                                
{
    "trailList": []
}
$ aws cloudtrail describe-trails --trail-name-list='["arn:aws:cloudtrail:us-east-1:<AWS_ACCOUNT_ID>:trail/events"]' --region=us-east-1
{
    "trailList": [
        {
            "Name": "events",
            "S3BucketName": "events",
            "IncludeGlobalServiceEvents": true,
            "IsMultiRegionTrail": true,
            "HomeRegion": "us-east-1",
            "TrailARN": "arn:aws:cloudtrail:us-east-1:<AWS_ACCOUNT_ID>:trail/events",
            "LogFileValidationEnabled": true,
            "HasCustomEventSelectors": false,
            "HasInsightSelectors": false,
            "IsOrganizationTrail": true
        }
    ]
}
```

### References

* #6561

### LINKED ISSUE #27945: [Docs]: Race Condition in Example Cloudtrail Creation
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudtrail

### Description

When following the example you can hit a race condition - if terraform tries to create the Cloudtrail resource before the aws_s3_bucket_policy has finished creating, the creation of the cloudtrail resource fails with an "InsufficientS3BucketPolicyException".

In my own use of this, I have added the following to the cloudtrail resource:

  depends_on = [
    aws_s3_bucket_policy.foo
  ]

That ensures that it waits till the policy is in place before trying to create it.

That would mean the fix here would be changing the Basic example to the following:

```data "aws_caller_identity" "current" {}

resource "aws_cloudtrail" "foobar" {
  name                          = "tf-trail-foobar"
  s3_bucket_name                = aws_s3_bucket.foo.id
  s3_key_prefix                 = "prefix"
  include_global_service_events = false
  depends_on = [
    aws_s3_bucket_policy.foo
  ]
}

resource "aws_s3_bucket" "foo" {
  bucket        = "tf-test-trail"
  force_destroy = true
}

resource "aws_s3_bucket_policy" "foo" {
  bucket = aws_s3_bucket.foo.id
  policy = <<POLICY
{
    "Version": "2012-10-17",
    "Statement": [
        {
            "Sid": "AWSCloudTrailAclCheck",
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:GetBucketAcl",
            "Resource": "${aws_s3_bucket.foo.arn}"
        },
        {
            "Sid": "AWSCloudTrailWrite",
            "Effect": "Allow",
            "Principal": {
              "Service": "cloudtrail.amazonaws.com"
            },
            "Action": "s3:PutObject",
            "Resource": "${aws_s3_bucket.foo.arn}/prefix/AWSLogs/${data.aws_caller_identity.current.account_id}/*",
            "Condition": {
                "StringEquals": {
                    "s3:x-amz-acl": "bucket-owner-full-control"
                }
            }
        }
    ]
}
POLICY
}```

### References

_No response_

### Would you like to implement a fix?

_No response_

### LINKED ISSUE #28440: [Bug]: Org Trail resource creation failed for CloudTrail Delegated Administrator
### Terraform Core Version

1.3.6

### AWS Provider Version

4.47.0

### Affected Resource(s)

aws_cloudtrail

### Expected Behavior

1. We choose a Delegated Administrator for the CloudTrail Service (see [AWS doc](https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-delegated-administrator.html)). **All CloudTrail resources remain in the Management Account, even if they are created by the Delegated Account.** (the ARN show the Account ID of the Management Account).
2. We deploy a new organization trail on this Delegated Account with Terraform.
3. The organization trail is fully **created and enabled** in the Management Account.

### Actual Behavior

When Terraform applies, it's failed when it try to enable logging it in the Delegated Account because it's did not find the trail.

After successfully creation, The AWS provider seems try to enable the trail locally (in the Delegated account) instead to referer to the trail 'stored' in the Management Account. The ARN in the below log explains the bug.

### Relevant Error/Panic Output Snippet

_'111111111111' is the Delegated Account ID._

```shell
aws_cloudtrail.org_main: Creating...
╷
│ Error: Error starting logging on CloudTrail (org-cloudtrail): TrailNotFoundException: Unknown trail: arn:aws:cloudtrail:us-east-1:111111111111:trail/org-cloudtrail for the user: 111111111111
│ 
│   with aws_cloudtrail.org_main,
│   on 01-cloudtrail.tf line 4, in resource "aws_cloudtrail" "org_main":
│    4: resource "aws_cloudtrail" "org_main" {
│ 
╵
Operation failed: failed running terraform apply (exit 1)
```

### Terraform Configuration Files

```terraform
resource "aws_cloudtrail" "org_main" {
  name                          = "org-cloudtrail"
  enable_logging                = true
  s3_bucket_name                = aws_s3_bucket.cloudtrail.id
  s3_key_prefix                 = ""
  include_global_service_events = true
  enable_log_file_validation    = false
  is_multi_region_trail         = true
  is_organization_trail         = true

  event_selector {
    read_write_type                  = "WriteOnly"
    include_management_events        = true
    exclude_management_event_sources = ["kms.amazonaws.com", "rdsdata.amazonaws.com"]
  }
}
```

### Steps to Reproduce

1. TF plan (ok)
2. TF apply (failed)

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/cloudtrail-delegated-administrator.html

### Would you like to implement a fix?

No

### LINKED ISSUE #30387: [Bug]: AWS Organization - Cloud Trail Central - Delegated Administrator
### Terraform Core Version

1.3.7

### AWS Provider Version

4.61.0

### Affected Resource(s)

aws_cloudtrail

### Expected Behavior

Cloud trail should correctly started & created in delegated administrator account .

### Actual Behavior

 Error: creating CloudTrail: starting logging: TrailNotFoundException: Unknown trail:

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

  + resource "aws_cloudtrail" "default" {
      cloud_watch_logs_group_arn    = "XXXX"
      + cloud_watch_logs_role_arn     = "XXXX"
      + enable_log_file_validation    = true
      + enable_logging                = true
      + include_global_service_events = true
      + is_multi_region_trail         = true
      + is_organization_trail         = true
      + kms_key_id                    = "XXXX"
      + name                          = "XXXX"
      + s3_bucket_name                = "XXXX"
    }

### Steps to Reproduce

1.Enable Cloud Trail trusted service in AWS Organization in master account
2.Delegate Administrator to member account
3.Create Cloud Trail in member account

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by sbldevnet**
### Description

- Getting the list of existing CloudTrail organization trails from a delegated account only works using the `arn`. This change will use trail `arn` instead of `name` as ID during creation to avoid that.

- Updating docs basic example adding the recommended AWS S3 policy condition to avoid confused deputy issue.
- Updating docs basic example adding `depends_on` to avoid race condition.

### Relations

Closes #15553
Closes #27945
Closes #28440
Closes #30387

### References

https://docs.aws.amazon.com/awscloudtrail/latest/userguide/create-s3-bucket-policy-for-cloudtrail.html

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccCloudTrail_ PKG=cloudtrail
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudtrail/... -v -count 1 -parallel 20 -run='TestAccCloudTrail_'  -timeout 180m
=== RUN   TestAccCloudTrail_serial
=== PAUSE TestAccCloudTrail_serial
=== CONT  TestAccCloudTrail_serial
=== RUN   TestAccCloudTrail_serial/Trail
=== RUN   TestAccCloudTrail_serial/Trail/organization
    acctest.go:883: skipping tests; this AWS account must not be an existing member of an AWS Organization
=== RUN   TestAccCloudTrail_serial/Trail/eventSelectorDynamoDB
=== RUN   TestAccCloudTrail_serial/Trail/eventSelectorExclude
=== RUN   TestAccCloudTrail_serial/Trail/insightSelector
=== RUN   TestAccCloudTrail_serial/Trail/advancedEventSelector
=== RUN   TestAccCloudTrail_serial/Trail/disappears
=== RUN   TestAccCloudTrail_serial/Trail/multiRegion
=== RUN   TestAccCloudTrail_serial/Trail/logValidation
=== RUN   TestAccCloudTrail_serial/Trail/eventSelector
=== RUN   TestAccCloudTrail_serial/Trail/cloudwatch
=== RUN   TestAccCloudTrail_serial/Trail/kmsKey
=== RUN   TestAccCloudTrail_serial/Trail/tags
=== RUN   TestAccCloudTrail_serial/Trail/basic
=== RUN   TestAccCloudTrail_serial/Trail/enableLogging
=== RUN   TestAccCloudTrail_serial/Trail/globalServiceEvents
--- PASS: TestAccCloudTrail_serial (1353.81s)
    --- PASS: TestAccCloudTrail_serial/Trail (1353.81s)
        --- SKIP: TestAccCloudTrail_serial/Trail/organization (1.73s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelectorDynamoDB (47.41s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelectorExclude (123.43s)
        --- PASS: TestAccCloudTrail_serial/Trail/insightSelector (150.39s)
        --- PASS: TestAccCloudTrail_serial/Trail/advancedEventSelector (50.84s)
        --- PASS: TestAccCloudTrail_serial/Trail/disappears (45.74s)
        --- PASS: TestAccCloudTrail_serial/Trail/multiRegion (118.79s)
        --- PASS: TestAccCloudTrail_serial/Trail/logValidation (83.23s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelector (172.92s)
        --- PASS: TestAccCloudTrail_serial/Trail/cloudwatch (111.31s)
        --- PASS: TestAccCloudTrail_serial/Trail/kmsKey (54.16s)
        --- PASS: TestAccCloudTrail_serial/Trail/tags (117.78s)
        --- PASS: TestAccCloudTrail_serial/Trail/basic (94.77s)
        --- PASS: TestAccCloudTrail_serial/Trail/enableLogging (130.06s)
        --- PASS: TestAccCloudTrail_serial/Trail/globalServiceEvents (51.24s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail	1358.005s
...
```

### CODE REVIEW

**Comment by sherifkayad** [comment]
Can we get this one merged soon? we are kinda blocked by it 😄

**Comment by lostdignity** [comment]
> Can we get this one merged soon? we are kinda blocked by it 😄

same for us... I've built an workaround with Lambda but I'm longing for this fix.

**Comment by ahembree** [comment]
Any update on this?

**Comment by Dgadavin** [comment]
Can someone merge this. This is super usefull thing.

**Comment by NaelMachal** [comment]
Hello there, is this prioritised? There is currently no other way to deploy an organisation trail from a delegated admin account from terraform which is a very basic aws feature.

**Comment by twelsh-aw** [comment]
Bump. Share sentiment above that we need this

**Comment by twelsh-aw** [comment]
@YakDriver sorry to ping you out of band, but can you please give this one a look. 🙇 

A few simple fixes that address some important issues.

**Comment by anddreit** [comment]
bump

**Comment by popsicleslayer** [comment]
Please merge this 🥺 It's extremely annoying to work with as of now and it just blocks work. You can't create it with the resource and if you create it with the CLI it can't be imported

**Review by jake-naughton — APPROVED** [review]

**Review by zahorniak — APPROVED** [review]

**Comment by andredms** [comment]
@justinretzolk do we have a timeline for getting this merged in? This is blocking our workflows and its not a change we'd like to revert.

**Comment by popsicleslayer** [comment]
A month later I would like to ask the same question as @andredms: @justinretzolk is there a timeline for merging this? I have been stuck with this problem since July and am constantly having faith in this being merged.

**Comment by rapides** [comment]
Bump! Also upvoting for this! ✋🏻

**Comment by twelsh-aw** [comment]
@ewbankkit It seems like you are mostly maintaining this repo now. Can you give a quick review?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloudTrail_serial/Trail' PKG=cloudtrail
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudtrail/... -v -count 1 -parallel 20  -run=TestAccCloudTrail_serial/Trail -timeout 360m
=== RUN   TestAccCloudTrail_serial
=== PAUSE TestAccCloudTrail_serial
=== CONT  TestAccCloudTrail_serial
=== RUN   TestAccCloudTrail_serial/Trail
=== RUN   TestAccCloudTrail_serial/Trail/kmsKey
=== RUN   TestAccCloudTrail_serial/Trail/tags
=== RUN   TestAccCloudTrail_serial/Trail/eventSelector
=== RUN   TestAccCloudTrail_serial/Trail/eventSelectorExclude
=== RUN   TestAccCloudTrail_serial/Trail/disappears
=== RUN   TestAccCloudTrail_serial/Trail/cloudwatch
=== RUN   TestAccCloudTrail_serial/Trail/globalServiceEvents
=== RUN   TestAccCloudTrail_serial/Trail/organization
    acctest.go:989: this AWS account must be the management account of an AWS Organization
=== RUN   TestAccCloudTrail_serial/Trail/migrateV0
=== RUN   TestAccCloudTrail_serial/Trail/basic
=== RUN   TestAccCloudTrail_serial/Trail/logValidation
=== RUN   TestAccCloudTrail_serial/Trail/enableLogging
    acctest.go:1475: skipping test for aws/us-west-2: Error running apply: exit status 1
        
        Error: stopping CloudTrail Trail (arn:aws:cloudtrail:us-west-2:123456789012:trail/tf-acc-test-1022396321005908609) logging: AccessDeniedException: User: arn:aws:sts::123456789012:assumed-role/terraform_team1_dev-developer/kewbank@hashicorp.com is not authorized to perform: cloudtrail:StopLogging on resource: arn:aws:cloudtrail:us-west-2:123456789012:trail/tf-acc-test-1022396321005908609 with an explicit deny in a service control policy
                status code: 400, request id: d13ddd18-ea14-424d-8d6f-c23c0e2fcc7d
        
          with aws_cloudtrail.test,
          on terraform_plugin_test.tf line 51, in resource "aws_cloudtrail" "test":
          51: resource "aws_cloudtrail" "test" {
        
=== RUN   TestAccCloudTrail_serial/Trail/insightSelector
=== RUN   TestAccCloudTrail_serial/Trail/multiRegion
=== RUN   TestAccCloudTrail_serial/Trail/eventSelectorDynamoDB
=== RUN   TestAccCloudTrail_serial/Trail/advancedEventSelector
--- PASS: TestAccCloudTrail_serial (1116.89s)
    --- PASS: TestAccCloudTrail_serial/Trail (1116.89s)
        --- PASS: TestAccCloudTrail_serial/Trail/kmsKey (49.37s)
        --- PASS: TestAccCloudTrail_serial/Trail/tags (84.98s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelector (123.85s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelectorExclude (88.77s)
        --- PASS: TestAccCloudTrail_serial/Trail/disappears (45.66s)
        --- PASS: TestAccCloudTrail_serial/Trail/cloudwatch (84.26s)
        --- PASS: TestAccCloudTrail_serial/Trail/globalServiceEvents (46.91s)
        --- SKIP: TestAccCloudTrail_serial/Trail/organization (0.34s)
        --- PASS: TestAccCloudTrail_serial/Trail/migrateV0 (109.15s)
        --- PASS: TestAccCloudTrail_serial/Trail/basic (72.46s)
        --- PASS: TestAccCloudTrail_serial/Trail/logValidation (67.26s)
        --- SKIP: TestAccCloudTrail_serial/Trail/enableLogging (56.25s)
        --- PASS: TestAccCloudTrail_serial/Trail/insightSelector (106.26s)
        --- PASS: TestAccCloudTrail_serial/Trail/multiRegion (86.43s)
        --- PASS: TestAccCloudTrail_serial/Trail/eventSelectorDynamoDB (47.88s)
        --- PASS: TestAccCloudTrail_serial/Trail/advancedEventSelector (47.05s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail 1122.001s
```
```console
% make testacc TESTARGS='-run=TestAccCloudTrail_serial/Trail/organization' PKG=cloudtrail
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudtrail/... -v -count 1 -parallel 20  -run=TestAccCloudTrail_serial/Trail/organization -timeout 360m
=== RUN   TestAccCloudTrail_serial
=== PAUSE TestAccCloudTrail_serial
=== CONT  TestAccCloudTrail_serial
=== RUN   TestAccCloudTrail_serial/Trail
=== RUN   TestAccCloudTrail_serial/Trail/organization
--- PASS: TestAccCloudTrail_serial (70.63s)
    --- PASS: TestAccCloudTrail_serial/Trail (70.63s)
        --- PASS: TestAccCloudTrail_serial/Trail/organization (70.63s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail 75.943s
```

**Comment by ewbankkit** [comment]
@sbldevnet Thanks for the contribution :tada: :clap:.
We went ahead and changed the `id` to always be the trail ARN which simplified the changes somewhat.

**Pull request merged**
