### PR TITLE
d/aws_ecs_task_definition: add execution_role_arn attribute

### PR DESCRIPTION
**Pull request by ei-grad**
### Description

Add `execution_role_arn` attribute for data-source `aws_ecs_task_definition`. It was missing for some reason.

### Relations

No relations.

### References

https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DescribeTaskDefinition.html

### Output from Acceptance Testing

```
[ ei-grad@ei-grad-x1 ~/repos/github.com/hashicorp/terraform-provider-aws git:f-data-aws_ecs_task_definition-execution_role_arn ]
→ make testacc TESTS=TaskDefinitionDataSource PKG=ecs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TaskDefinitionDataSource'  -timeout 180m
=== RUN   TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
=== PAUSE TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
=== CONT  TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
--- PASS: TestAccECSTaskDefinitionDataSource_ecsTaskDefinition (34.07s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	34.119s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Hi @ei-grad, thanks for your first contribution :rocket: !

**Review by bschaatsbergen — APPROVED** [review]
LGTM :rocket: 

Great first contribution, I would love to see more from you in the future @ei-grad :clap: 

```
make testacc TESTS=TaskDefinitionDataSource PKG=ecs                                          (base) 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TaskDefinitionDataSource'  -timeout 180m
=== RUN   TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
=== PAUSE TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
=== CONT  TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
--- PASS: TestAccECSTaskDefinitionDataSource_ecsTaskDefinition (23.42s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecs        23.498s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccECSTaskDefinitionDataSource_' PKG=ecs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20  -run=TestAccECSTaskDefinitionDataSource_ -timeout 180m
=== RUN   TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
=== PAUSE TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
=== CONT  TestAccECSTaskDefinitionDataSource_ecsTaskDefinition
--- PASS: TestAccECSTaskDefinitionDataSource_ecsTaskDefinition (15.65s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	21.752s
```

**Comment by ewbankkit** [comment]
@ei-grad Thanks for the contribution :tada: :clap:.

**Pull request merged**
