### PR TITLE
feat: add aws_verifiedpermissions_policy

### LINKED ISSUE #35412: [New Resource]: aws_verifiedpermissions_policy
### Description

Adding Verified Permission Policy

### Requested Resource(s) and/or Data Source(s)

aws_verifiedpermissions_policy

### Potential Terraform Configuration

```terraform
resource "aws_verifiedpermissions_policy" "test" {
  policy_store_id = aws_verifiedpermissions_policy_store.test.id

  definition {
    static {
      description = ""
      statement   = ""
    }

    template_linked {
      policy_template_id = aws_verifiedpermissions_policy_template.test.id

      principal {
        entity_id   = ""
        entity_type = ""
      }

      resource {
        entity_id   = ""
        entity_type = ""
      }
    }
  }
}
```

### References

Relates https://github.com/hashicorp/terraform-provider-aws/issues/32158.

* https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicy.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-policy.html

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by filol**
### Description
Adding Verified Permission Policy
 WIP - Need help

### Relations
Relates #32158
Closes #35412

### References
https://docs.aws.amazon.com/verifiedpermissions/latest/apireference/API_CreatePolicy.html
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-verifiedpermissions-policy.html

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by hanoj-budime** [comment]
Hey, we're eagerly awaiting this. When will it be generally available (GA)?

**Comment by dguisinger** [comment]
Is this ever going to get released?

**Comment by hanoj-budime** [comment]
> Hey, we're eagerly awaiting this. When will it be generally available (GA)?
> 
> @ewbankkit @justinretzolk @johnsonaj

Guy's ? Update please.. we're in Q2 Roadmap planning wait for your PR

**Comment by hanoj-budime** [comment]
Hi @johnsonaj,

I'm glad to see some progress here. thanks.

> Please make sure to test scenarios where it can update in-place and where it needs to recreate the policy based on a modification.

What's the estimation roadmap for this feature?

**Comment by johnsonaj** [comment]
```console
% make sweep SWEEPARGS='-sweep-run=aws_verifiedpermissions_ -sweep-allow-failures'

# make sweep SWEEPARGS=-sweep-run=aws_example_thing
# set SWEEPARGS=-sweep-allow-failures to continue after first failure
WARNING: This will destroy infrastructure. Use only in development accounts.
go1.21.8 test ./internal/sweep -v -sweep=us-west-2,us-east-1,us-east-2,us-west-1 -sweep-run=aws_verifiedpermissions_ -sweep-allow-failures -timeout 360m
2024/04/16 14:02:04 [DEBUG] Running Sweepers for region (us-west-2):
2024/04/16 14:02:04 [DEBUG] Running Sweeper (aws_verifiedpermissions_policy_store) in region (us-west-2)
2024/04/16 14:02:04 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-west-2
2024-04-16T14:02:04.909-0500 [DEBUG] sweeper.aws-base: Resolving credentials provider: sweeper_region=us-west-2
2024-04-16T14:02:04.910-0500 [DEBUG] sweeper.aws-base: Using profile: tf_aws.profile.source=envvar sweeper_region=us-west-2 tf_aws.profile=default
2024-04-16T14:02:04.910-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-west-2
2024-04-16T14:02:04.911-0500 [DEBUG] sweeper.aws-base: Retrieving credentials: sweeper_region=us-west-2
2024-04-16T14:02:04.911-0500 [INFO]  sweeper.aws-base: Retrieved credentials: sweeper_region=us-west-2 tf_aws.credentials_source="SharedConfigCredentials: /Users/adrianjohnson/.aws/credentials"
2024-04-16T14:02:04.911-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-west-2
2024/04/16 14:02:04 [DEBUG] sweeper: Creating AWS SDK v1 session: sweeper_region=us-west-2
2024/04/16 14:02:04 [DEBUG] sweeper: Retrieving AWS account details: sweeper_region=us-west-2
2024-04-16T14:02:04.912-0500 [DEBUG] sweeper.aws-base: Retrieving caller identity from STS: sweeper_region=us-west-2
2024-04-16T14:02:05.210-0500 [INFO]  sweeper.aws-base: Retrieved caller identity from STS: sweeper_region=us-west-2
2024/04/16 14:02:05 [INFO]  sweeper: No resources to sweep: sweeper_region=us-west-2
2024/04/16 14:02:05 [DEBUG] Completed Sweeper (aws_verifiedpermissions_policy_store) in region (us-west-2) in 622.552542ms
2024/04/16 14:02:05 Completed Sweepers for region (us-west-2) in 622.695292ms
2024/04/16 14:02:05 Sweeper Tests for region (us-west-2) ran successfully:
2024/04/16 14:02:05 	- aws_verifiedpermissions_policy_store
2024/04/16 14:02:05 [DEBUG] Running Sweepers for region (us-east-1):
2024/04/16 14:02:05 [DEBUG] Running Sweeper (aws_verifiedpermissions_policy_store) in region (us-east-1)
2024/04/16 14:02:05 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-east-1
2024-04-16T14:02:05.531-0500 [DEBUG] sweeper.aws-base: Resolving credentials provider: sweeper_region=us-east-1
2024-04-16T14:02:05.531-0500 [DEBUG] sweeper.aws-base: Using profile: sweeper_region=us-east-1 tf_aws.profile=default tf_aws.profile.source=envvar
2024-04-16T14:02:05.531-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-east-1
2024-04-16T14:02:05.532-0500 [DEBUG] sweeper.aws-base: Retrieving credentials: sweeper_region=us-east-1
2024-04-16T14:02:05.532-0500 [INFO]  sweeper.aws-base: Retrieved credentials: sweeper_region=us-east-1 tf_aws.credentials_source="SharedConfigCredentials: /Users/adrianjohnson/.aws/credentials"
2024-04-16T14:02:05.532-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-east-1
2024/04/16 14:02:05 [DEBUG] sweeper: Creating AWS SDK v1 session: sweeper_region=us-east-1
2024/04/16 14:02:05 [DEBUG] sweeper: Retrieving AWS account details: sweeper_region=us-east-1
2024-04-16T14:02:05.534-0500 [DEBUG] sweeper.aws-base: Retrieving caller identity from STS: sweeper_region=us-east-1
2024-04-16T14:02:05.747-0500 [INFO]  sweeper.aws-base: Retrieved caller identity from STS: sweeper_region=us-east-1
2024/04/16 14:02:06 [INFO]  sweeper: No resources to sweep: sweeper_region=us-east-1
2024/04/16 14:02:06 [DEBUG] Completed Sweeper (aws_verifiedpermissions_policy_store) in region (us-east-1) in 505.086916ms
2024/04/16 14:02:06 Completed Sweepers for region (us-east-1) in 505.156958ms
2024/04/16 14:02:06 Sweeper Tests for region (us-east-1) ran successfully:
2024/04/16 14:02:06 	- aws_verifiedpermissions_policy_store
2024/04/16 14:02:06 [DEBUG] Running Sweepers for region (us-east-2):
2024/04/16 14:02:06 [DEBUG] Running Sweeper (aws_verifiedpermissions_policy_store) in region (us-east-2)
2024/04/16 14:02:06 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-east-2
2024-04-16T14:02:06.037-0500 [DEBUG] sweeper.aws-base: Resolving credentials provider: sweeper_region=us-east-2
2024-04-16T14:02:06.037-0500 [DEBUG] sweeper.aws-base: Using profile: tf_aws.profile=default tf_aws.profile.source=envvar sweeper_region=us-east-2
2024-04-16T14:02:06.037-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-east-2
2024-04-16T14:02:06.038-0500 [DEBUG] sweeper.aws-base: Retrieving credentials: sweeper_region=us-east-2
2024-04-16T14:02:06.038-0500 [INFO]  sweeper.aws-base: Retrieved credentials: tf_aws.credentials_source="SharedConfigCredentials: /Users/adrianjohnson/.aws/credentials" sweeper_region=us-east-2
2024-04-16T14:02:06.038-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-east-2
2024/04/16 14:02:06 [DEBUG] sweeper: Creating AWS SDK v1 session: sweeper_region=us-east-2
2024/04/16 14:02:06 [DEBUG] sweeper: Retrieving AWS account details: sweeper_region=us-east-2
2024-04-16T14:02:06.040-0500 [DEBUG] sweeper.aws-base: Retrieving caller identity from STS: sweeper_region=us-east-2
2024-04-16T14:02:06.321-0500 [INFO]  sweeper.aws-base: Retrieved caller identity from STS: sweeper_region=us-east-2
2024/04/16 14:02:06 [INFO]  sweeper: No resources to sweep: sweeper_region=us-east-2
2024/04/16 14:02:06 [DEBUG] Completed Sweeper (aws_verifiedpermissions_policy_store) in region (us-east-2) in 487.411208ms
2024/04/16 14:02:06 Completed Sweepers for region (us-east-2) in 487.451833ms
2024/04/16 14:02:06 Sweeper Tests for region (us-east-2) ran successfully:
2024/04/16 14:02:06 	- aws_verifiedpermissions_policy_store
2024/04/16 14:02:06 [DEBUG] Running Sweepers for region (us-west-1):
2024/04/16 14:02:06 [DEBUG] Running Sweeper (aws_verifiedpermissions_policy_store) in region (us-west-1)
2024/04/16 14:02:06 [DEBUG] sweeper: Configuring Terraform AWS Provider: sweeper_region=us-west-1
2024-04-16T14:02:06.524-0500 [DEBUG] sweeper.aws-base: Resolving credentials provider: sweeper_region=us-west-1
2024-04-16T14:02:06.524-0500 [DEBUG] sweeper.aws-base: Using profile: sweeper_region=us-west-1 tf_aws.profile=default tf_aws.profile.source=envvar
2024-04-16T14:02:06.524-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-west-1
2024-04-16T14:02:06.525-0500 [DEBUG] sweeper.aws-base: Retrieving credentials: sweeper_region=us-west-1
2024-04-16T14:02:06.525-0500 [INFO]  sweeper.aws-base: Retrieved credentials: tf_aws.credentials_source="SharedConfigCredentials: /Users/adrianjohnson/.aws/credentials" sweeper_region=us-west-1
2024-04-16T14:02:06.526-0500 [DEBUG] sweeper.aws-base: Loading configuration: sweeper_region=us-west-1
2024/04/16 14:02:06 [DEBUG] sweeper: Creating AWS SDK v1 session: sweeper_region=us-west-1
2024/04/16 14:02:06 [DEBUG] sweeper: Retrieving AWS account details: sweeper_region=us-west-1
2024-04-16T14:02:06.527-0500 [DEBUG] sweeper.aws-base: Retrieving caller identity from STS: sweeper_region=us-west-1
2024-04-16T14:02:06.828-0500 [INFO]  sweeper.aws-base: Retrieved caller identity from STS: sweeper_region=us-west-1
2024/04/16 14:02:07 [INFO]  sweeper: No resources to sweep: sweeper_region=us-west-1
2024/04/16 14:02:07 [DEBUG] Completed Sweeper (aws_verifiedpermissions_policy_store) in region (us-west-1) in 550.828917ms
2024/04/16 14:02:07 Completed Sweepers for region (us-west-1) in 550.868292ms
2024/04/16 14:02:07 Sweeper Tests for region (us-west-1) ran successfully:
2024/04/16 14:02:07 	- aws_verifiedpermissions_policy_store
ok  	github.com/hashicorp/terraform-provider-aws/internal/sweep	7.175s
```

**Comment by johnsonaj** [comment]
```console
% make testacc TESTARGS='-run=TestAccVerifiedPermissionsPolicy_' PKG=verifiedpermissions

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20  -run=TestAccVerifiedPermissionsPolicy_ -timeout 360m
--- PASS: TestAccVerifiedPermissionsPolicy_disappears (11.82s)
--- PASS: TestAccVerifiedPermissionsPolicy_basic (13.54s)
--- PASS: TestAccVerifiedPermissionsPolicy_templateLinked (14.70s)
--- PASS: TestAccVerifiedPermissionsPolicy_update (24.30s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions	29.577s
```

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀

**Comment by johnsonaj** [comment]
@filol thank you for the contribution! 🎉

**Pull request merged**
