### PR TITLE
Add serde support to csv_classifier

### LINKED ISSUE #33787: [Enhancement]: Serde property missing in aws_glue_classifier of type CsvClassifier
### Description

Currently, aws_glue_classifier of type CsvClassifier does not allow specifying the Serde property ("OpenCSVSerDe"|"LazySimpleSerDe"|"None"). 

By default it is set to None and the crawler detects the format automatically.

It would be interesting to have this property to force the type.

Provider: v5.19.0

### Affected Resource(s) and/or Data Source(s)

aws_glue_classifier

### Potential Terraform Configuration

```terraform
resource "aws_glue_classifier" "example" {
  name = "example"

  csv_classifier {
    allow_single_column    = false
    contains_header        = "PRESENT"
    delimiter              = ","
    disable_value_trimming = false
    header                 = ["example1", "example2"]
    quote_symbol           = "'"
    serde                  = "OpenCSVSerDe"|"LazySimpleSerDe"|"None"
  }
}
```

### References

https://docs.aws.amazon.com/cli/latest/reference/glue/create-classifier.html

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by PatrickRice-KSC**
### Description

This PR adds support for defining the `serde` attribute when creating a `aws_glue_classifier` with a `csv_classifier` block, allowing users to define the exact serde they want to use for a classifier instead of relying on Glue's inferrence.

### Relations

Closes #33787 

### Output from Acceptance Testing

Pending

### CODE REVIEW

**Comment by PatrickRice-KSC** [comment]
Acceptance test now passes:

image

**Comment by PatrickRice-KSC** [comment]
To ensure that this PR had good hygiene for merge, I rebased (since it's been open for a while), and squashed the commits into one. Let me know if there's anything else I can do to help facilitate review and merge!

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS='-run=TestAccGlueClassifier_' PKG=glue

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/glue/... -v -count 1 -parallel 20  -run=TestAccGlueClassifier_ -timeout 360m
--- PASS: TestAccGlueClassifier_disappears (52.46s)
--- PASS: TestAccGlueClassifier_GrokClassifier_customPatterns (83.48s)
--- PASS: TestAccGlueClassifier_grokClassifier (84.00s)
--- PASS: TestAccGlueClassifier_jsonClassifier (84.00s)
--- PASS: TestAccGlueClassifier_xmlClassifier (84.43s)
--- PASS: TestAccGlueClassifier_CSVClassifier_custom (84.44s)
--- PASS: TestAccGlueClassifier_csvClassifier (84.47s)
--- PASS: TestAccGlueClassifier_CSVClassifier_quoteSymbol (84.61s)
--- PASS: TestAccGlueClassifier_csvClassifierCustomSerde (86.25s)
--- PASS: TestAccGlueClassifier_typeChange (113.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glue	117.490s
```

**Comment by johnsonaj** [comment]
@PatrickRice-KSC thank you for the contribution! 🎉

**Pull request merged**
