### PR TITLE
New Resource aws_route53domains_domain

### LINKED ISSUE #88: Feature Request: Support Route53 Domains
_This issue was originally opened by @garyp as hashicorp/terraform#5368. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

It'd be really useful if Terraform could automatically update the whois nameserver records for a domain registered through AWS Route 53 when that domain's zone is being managed via Route 53.

That is, the current `aws_route53_zone` resource defines a `name_servers` attribute for getting the list of nameservers that AWS assigned to the zone. For domains that are registered via Route 53 (http://docs.aws.amazon.com/Route53/latest/DeveloperGuide/registrar.html), I'd like Terraform to use the [UpdateDomainNameservers API](https://docs.aws.amazon.com/Route53/latest/APIReference/api-update-domain-name-servers.html) to update the domain's nameservers using the `aws_route53_zone.name_servers` attribute.

It would probably make sense to model a new `aws_route53_domain` resource that supports the registered domain API: https://docs.aws.amazon.com/Route53/latest/APIReference/actions-on-domain-registrations.html.

### PR DESCRIPTION
**Pull request by gazoakley**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #88
Relates #12797

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
**New Resource**: `aws_route53domains_domain` (#12711)
```

Output from acceptance testing:

```
$ ROUTE53DOMAINS_DOMAIN=gazoakleytest.net make testacc TESTARGS='-run=TestAccAWSRoute53DomainsDomain_'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSRoute53DomainsDomain_ -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSRoute53DomainsDomain_Basic
--- PASS: TestAccAWSRoute53DomainsDomain_Basic (24.60s)
=== RUN   TestAccAWSRoute53DomainsDomain_Tags
    TestAccAWSRoute53DomainsDomain_Tags: testing.go:669: Step 0 error: Check failed: Check 1/2 error: aws_route53domains_domain.test: Attribute 'tags.%' expected "1", got "2"
--- FAIL: TestAccAWSRoute53DomainsDomain_Tags (14.55s)
=== RUN   TestAccAWSRoute53DomainsDomain_AutoRenew
    TestAccAWSRoute53DomainsDomain_AutoRenew: testing.go:669: Step 0 error: Check failed: Check 1/1 error: aws_route53domains_domain.test: Attribute 'auto_renew' expected "false", got "true"
--- FAIL: TestAccAWSRoute53DomainsDomain_AutoRenew (12.27s)
=== RUN   TestAccAWSRoute53DomainsDomain_TransferLock
    TestAccAWSRoute53DomainsDomain_TransferLock: testing.go:669: Step 0 error: Check failed: Check 1/1 error: aws_route53domains_domain.test: Attribute 'transfer_lock' expected "false", got "true"
--- FAIL: TestAccAWSRoute53DomainsDomain_TransferLock (13.56s)
=== RUN   TestAccAWSRoute53DomainsDomain_Privacy
--- PASS: TestAccAWSRoute53DomainsDomain_Privacy (261.85s)
=== RUN   TestAccAWSRoute53DomainsDomain_NameServers
--- PASS: TestAccAWSRoute53DomainsDomain_NameServers (177.30s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	507.409s
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by breathingdust** [comment]
Hi all 👋  Just letting you know that this is issue is featured on this quarters roadmap. If a PR exists to close the issue a maintainer will review and either make changes directly, or work with the original author to get the contribution merged. If you have written a PR to resolve the issue please ensure the "Allow edits from maintainers" box is checked. Thanks for your patience and we are looking forward to getting this merged soon!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% AWS_DEFAULT_REGION=us-east-1 ROUTE53DOMAINS_DOMAIN_NAME=terraform-provider-aws-acctest-acm.com make testacc TESTS=TestAccRoute53Domains_serial PKG=route53domains
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/route53domains/... -v -count 1 -parallel 20 -run='TestAccRoute53Domains_serial'  -timeout 180m
=== RUN   TestAccRoute53Domains_serial
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain/contactPrivacy
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain/nameservers
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain/transferLock
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain/tags
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain/autoRenew
=== RUN   TestAccRoute53Domains_serial/RegisteredDomain/contacts
--- PASS: TestAccRoute53Domains_serial (767.58s)
    --- PASS: TestAccRoute53Domains_serial/RegisteredDomain (767.58s)
        --- PASS: TestAccRoute53Domains_serial/RegisteredDomain/contactPrivacy (78.74s)
        --- PASS: TestAccRoute53Domains_serial/RegisteredDomain/nameservers (126.92s)
        --- PASS: TestAccRoute53Domains_serial/RegisteredDomain/transferLock (141.80s)
        --- PASS: TestAccRoute53Domains_serial/RegisteredDomain/tags (20.01s)
        --- PASS: TestAccRoute53Domains_serial/RegisteredDomain/autoRenew (13.39s)
        --- PASS: TestAccRoute53Domains_serial/RegisteredDomain/contacts (386.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/route53domains	771.075s
```

**Comment by ewbankkit** [comment]
@gazoakley Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
The AWS Provider team at HashiCorp has used the introduction of a new AWS service in this PR to prototype use of the [AWS SDK for Go v2](https://aws.github.io/aws-sdk-go-v2/docs/).
Support is very much still experimental and we **DO NOT** recommend that new contributions use AWS SDK for Go v2 until the team has gained more experience with its use.

**Pull request merged**
