### PR TITLE
r/aws_pinpointsmsvoicev2_phone_number - new resource

### PR DESCRIPTION
**Pull request by JamesMarino**
This PR adds a new AWS service `pinpointsmsvoicev2` and new resources `aws_pinpointsmsvoicev2_phone_number` and `aws_pinpointsmsvoicev2_opt_out_list`. 

Note: `aws_pinpointsmsvoicev2_opt_out_list` was added as it is a dependant of `aws_pinpointsmsvoicev2_phone_number` in its tests.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes https://github.com/hashicorp/terraform-provider-aws/issues/24855

Output from acceptance testing:

```
$ make testacc PKG=pinpointsmsvoicev2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/pinpointsmsvoicev2/... -v -count 1 -parallel 20   -timeout 180m
=== RUN   TestAccPinpointSMSVoiceV2OptOutList_basic
=== PAUSE TestAccPinpointSMSVoiceV2OptOutList_basic
=== RUN   TestAccPinpointSMSVoiceV2OptOutList_disappears
=== PAUSE TestAccPinpointSMSVoiceV2OptOutList_disappears
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_full
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_full
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== CONT  TestAccPinpointSMSVoiceV2OptOutList_basic
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_full
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== CONT  TestAccPinpointSMSVoiceV2OptOutList_disappears
--- PASS: TestAccPinpointSMSVoiceV2OptOutList_disappears (10.15s)
--- PASS: TestAccPinpointSMSVoiceV2OptOutList_basic (14.02s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_full (24.11s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_basic (25.03s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_disappears (31.44s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pinpointsmsvoicev2 33.707s
```

### CODE REVIEW

**Comment by JamesMarino** [comment]
Any news on wether we can get this merged in or if there was any feedback? Happy to fix up the conflicts.

**Comment by cemo** [comment]
@jar-b can you please assign this for review? I would like to send PRs to close other missing resources on pinpoint. Thanks

**Comment by dabmajor** [comment]
Is someone going to pick this back up? I've currently implemented a solution using null_resources and external data resources; however, bringing this back to a standard terraform provider would be fantastic :)

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccPinpointSMSVoiceV2OptOutList_' PKG=pinpointsmsvoicev2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/pinpointsmsvoicev2/... -v -count 1 -parallel 20  -run=TestAccPinpointSMSVoiceV2OptOutList_ -timeout 360m
=== RUN   TestAccPinpointSMSVoiceV2OptOutList_basic
=== PAUSE TestAccPinpointSMSVoiceV2OptOutList_basic
=== RUN   TestAccPinpointSMSVoiceV2OptOutList_disappears
=== PAUSE TestAccPinpointSMSVoiceV2OptOutList_disappears
=== RUN   TestAccPinpointSMSVoiceV2OptOutList_tags
=== PAUSE TestAccPinpointSMSVoiceV2OptOutList_tags
=== CONT  TestAccPinpointSMSVoiceV2OptOutList_basic
=== CONT  TestAccPinpointSMSVoiceV2OptOutList_tags
=== CONT  TestAccPinpointSMSVoiceV2OptOutList_disappears
--- PASS: TestAccPinpointSMSVoiceV2OptOutList_disappears (11.53s)
--- PASS: TestAccPinpointSMSVoiceV2OptOutList_basic (14.10s)
--- PASS: TestAccPinpointSMSVoiceV2OptOutList_tags (30.27s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpointsmsvoicev2	35.355s
```
```console
% make testacc TESTARGS='-run=TestAccPinpointSMSVoiceV2PhoneNumber_' PKG=pinpointsmsvoicev2 ACCTEST_PARALLELISM=2 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/pinpointsmsvoicev2/... -v -count 1 -parallel 2  -run=TestAccPinpointSMSVoiceV2PhoneNumber_ -timeout 360m
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_full
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_full
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_disappears
=== RUN   TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== PAUSE TestAccPinpointSMSVoiceV2PhoneNumber_tags
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_basic
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_disappears
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_basic (17.39s)
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_tags
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_disappears (21.77s)
=== CONT  TestAccPinpointSMSVoiceV2PhoneNumber_full
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_full (29.72s)
--- PASS: TestAccPinpointSMSVoiceV2PhoneNumber_tags (36.11s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpointsmsvoicev2	58.481s
```

**Pull request merged**
