### PR TITLE
Added data source 'aws_eips'.

### LINKED ISSUE #6997: aws_eip data source missing support to return multiple eips
### Description

We are trying to get multiple eips back to be able to whitelist them.
We are filtering them by tag and we expect to have multiple EIPs returned by the datasource but 
we are getting this error:

**data.aws_eip.revproxy[0]: data.aws_eip.revproxy.0: multiple Elastic IPs matched; use additional constraints to reduce matches to a single Elastic IP**

### PR DESCRIPTION
**Pull request by Dchamard**
Fixes #6997.
Relates #20433.

Added aws_eips resource.

### CODE REVIEW

**Comment by Dchamard** [comment]
@tomelliff I think I addressed your concerns. I just left tags for filters.
I ran the acceptance tests successfully.

**Comment by satya2art** [comment]
This would be great for us to use, if you can merge it.

**Comment by jghamburg** [comment]
I'd love to see this feature because I am trying to configure an aws_route53_record type TXT with multiple aws_eip records.

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by ngolding** [comment]
is there an ETA for this to be merged?

**Comment by jav-12** [comment]
Do you know guys when this is going to be merged?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTS=TestAccEC2EIPsDataSource_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EIPsDataSource_'  -timeout 180m
=== RUN   TestAccEC2EIPsDataSource_vpcDomain
=== PAUSE TestAccEC2EIPsDataSource_vpcDomain
=== RUN   TestAccEC2EIPsDataSource_standardDomain
=== PAUSE TestAccEC2EIPsDataSource_standardDomain
=== CONT  TestAccEC2EIPsDataSource_vpcDomain
=== CONT  TestAccEC2EIPsDataSource_standardDomain
--- PASS: TestAccEC2EIPsDataSource_standardDomain (19.58s)
--- PASS: TestAccEC2EIPsDataSource_vpcDomain (20.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	29.172s
```

##### GovCloud

```console
% make testacc TESTS=TestAccEC2EIPsDataSource_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2EIPsDataSource_'  -timeout 180m
=== RUN   TestAccEC2EIPsDataSource_vpcDomain
=== PAUSE TestAccEC2EIPsDataSource_vpcDomain
=== RUN   TestAccEC2EIPsDataSource_standardDomain
=== PAUSE TestAccEC2EIPsDataSource_standardDomain
=== CONT  TestAccEC2EIPsDataSource_vpcDomain
=== CONT  TestAccEC2EIPsDataSource_standardDomain
    ec2_classic.go:56: this test can only run in EC2-Classic, platforms available in us-gov-west-1: ["VPC"]
--- SKIP: TestAccEC2EIPsDataSource_standardDomain (2.53s)
--- PASS: TestAccEC2EIPsDataSource_vpcDomain (20.97s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	27.214s
```

**Comment by ewbankkit** [comment]
@Dchamard Thanks for the contribution :tada: :clap:.

**Pull request merged**
