### PR TITLE
Upgrade to v0.12.0 of `tflint-ruleset-aws`

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by PatMyron** [comment]
Fixed most of the doc examples in https://github.com/hashicorp/terraform-provider-aws/pull/23346

1) not sure you all want to handle `Invalid function argument: Invalid value for "path" parameter: no file exists at`

2) the multiline strings not matching `.*` has me considering removing [those mappings](https://github.com/terraform-linters/tflint-ruleset-aws/tree/master/rules/models/mappings) altogether

3) Not sure if my `aws_s3_object_copy_invalid_source` / `aws_servicecatalog_portfolio_share_invalid_type` mappings are correct or not, advice appreciated

cc @wata727

**Comment by DrFaust92** [comment]
Thanks @PatMyron, ill try to take a look at the other validations or add exceptions.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Pull request merged**
