### PR TITLE
data source/service: Add data source for service 

### LINKED ISSUE #16641: data source/service: Add a service data source
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to have a data source to help with service names such as `com.amazonaws.us-east-1.s3`. While these components can be composed from existing data sources, a new data source would be convenient for practitioners and provide a way to work backwards from a service name to regions, service prefixes, and service IDs.

This allows practitioners and maintainers to create configurations that can move more easily between partitions. This is a next step following on with data sources such as `aws_region` and `aws_partition`.

### New or Affected Resource(s)

* aws_service

### Potential Terraform Configuration

```hcl
resource "aws_vpc" "test" {
  cidr_block = "10.0.0.0/16"

  tags = {
    Name = %[1]q
  }
}

data "aws_service" "s3" {
  service_id = "s3"
}

resource "aws_vpc_endpoint" "test" {
  vpc_id       = aws_vpc.test.id
  service_name = data.aws_service_name.s3.reverse_dns_name
}
```

### References

* #16639

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16641

Output from acceptance tests (`us-west-2`):

```console
% make testacc TESTS=TestAccMetaService_ PKG=meta
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20 -run='TestAccMetaService_'  -timeout 180m
--- PASS: TestAccMetaService_unsupported (12.21s)
--- PASS: TestAccMetaService_byParts (12.21s)
--- PASS: TestAccMetaService_byDNSName (12.21s)
--- PASS: TestAccMetaService_basic (12.21s)
--- PASS: TestAccMetaService_byReverseDNSName (12.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	13.586s
% make testacc TESTS=TestInvert PKG=meta
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20 -run='TestInvert'  -timeout 180m
--- PASS: TestInvertStringSlice (0.00s)
    --- PASS: TestInvertStringSlice/DNS_Suffix (0.00s)
    --- PASS: TestInvertStringSlice/Ordered_List (0.00s)
    --- PASS: TestInvertStringSlice/Unordered_List (0.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	1.309s
```

Output from acceptance tests (GovCloud):

```console
% make testacc TESTS='TestAccMetaService_|TestInvert' PKG=meta
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/meta/... -v -count 1 -parallel 20 -run='TestAccMetaService_|TestInvert'  -timeout 180m
--- PASS: TestInvertStringSlice (0.00s)
    --- PASS: TestInvertStringSlice/DNS_Suffix (0.00s)
    --- PASS: TestInvertStringSlice/Ordered_List (0.00s)
    --- PASS: TestInvertStringSlice/Unordered_List (0.00s)
--- PASS: TestAccMetaService_byDNSName (12.10s)
--- PASS: TestAccMetaService_byReverseDNSName (12.10s)
--- PASS: TestAccMetaService_unsupported (12.10s)
--- PASS: TestAccMetaService_basic (12.11s)
--- PASS: TestAccMetaService_byParts (12.11s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/meta	13.423s
```

### CODE REVIEW

**Comment by bflad** [comment]
Let's clear up https://github.com/hashicorp/terraform-provider-aws/issues/16641#issuecomment-755529479 before continuing here. We may also want to clarify the attributes better since this should not be EC2 specific and support forward and reverse DNS information.

**Comment by YakDriver** [comment]
> Let's clear up [#16641 (comment)](https://github.com/hashicorp/terraform-provider-aws/issues/16641#issuecomment-755529479) before continuing here. We may also want to clarify the attributes better since this should not be EC2 specific and support forward and reverse DNS information.

All of these items have been addressed.

**Review by gdavison — COMMENTED** [review]
Looks good! 🚀 

One comment

**Comment by antonbabenko** [comment]
Can we also have `dns_prefix` added (value - `amazonaws.com`)? It would be helpful to generate global AWS Service Names like this - https://github.com/kubernetes-sigs/aws-load-balancer-controller/blob/694a0b14184e388806f9f34be0dd9075aa8fb0a7/docs/install/iam_policy.json#L12

**Pull request merged**
