### PR TITLE
added segmentation_mode attribute for aws_medialive_channel hls_group…

### PR DESCRIPTION
**Pull request by peletv2**
…_settings

### Description

Added missing attribute `segmentation_mode` to `hls_group_settings`.

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccMediaLiveChannel_hls PKG=medialive
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_hls'  -timeout 360m
 === RUN   TestAccMediaLiveChannel_hls
=== PAUSE TestAccMediaLiveChannel_hls
=== CONT  TestAccMediaLiveChannel_hls
--- PASS: TestAccMediaLiveChannel_hls (68.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	70.588s
...
```

### CODE REVIEW

**Comment by gbw** [comment]
According to the [docs](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/medialive@v1.37.0/types#HlsGroupSettings) this setting can only be use segment duration as the other setting is deprecated.

**Comment by peletv2** [comment]
Due to our organization policy, we aren't able to allow you to make direct edits.

**Comment by peletv2** [comment]
I just rebased in order to stay up to date with main, making sure there are no conflicts.

**Comment by peletv2** [comment]
Rebase gone wrong. Fixing shortly

**Comment by peletv2** [comment]
Closing this as it isn't needed

**Pull request closed without merging**
