### PR TITLE
Add MSK Node Data source

### LINKED ISSUE #15731: data source aws_msk_node
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Adds a way of getting MSK node information

### New or Affected Resource(s)

* aws_msk_node

### Potential Terraform Configuration

```hcl
data "aws_msk_node" "test" {
  cluster_arn     = aws_msk_cluster.test.arn
  broker_endpoint = trimsuffix(split(",", aws_msk_cluster.test.bootstrap_brokers_tls)[0], ":9094")
}
```

### References

#15163

### PR DESCRIPTION
**Pull request by dblooman**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15731

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Data Source: aws_msk_node
```

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccAWSMskNodes_ClientIp'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMskNodes_ClientIp -timeout 120m
=== RUN   TestAccAWSMskNodes_ClientIp
=== PAUSE TestAccAWSMskNodes_ClientIp
=== CONT  TestAccAWSMskNodes_ClientIp
--- PASS: TestAccAWSMskNodes_ClientIp (1242.97s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1245.482s
```

### CODE REVIEW

**Comment by dblooman** [comment]
@anGie44

**Comment by anGie44** [comment]
Hi @dblooman, thank you for opening this PR! Since I don't see a related issue already created by the community, would you mind creating one so we can keep track of the community support for this new data source?  We use the community reactions for the internal team to prioritize requests. Once the issue is created, we will continue to monitor the community interest in the feature, and once enough support is demonstrated, the team will queue this PR up for review.

**Comment by marcelobartsch** [comment]
any chance we can get this into the providers? this is something we really we need , currently we are using a dirty hack with dns data , for , count and other tricks to get the names nodes when we could have used this to make it a lot simpler.

**Comment by dblooman** [comment]
gonna close this as it doesn't look likely to get merged

**Pull request closed without merging**
