### PR TITLE
add initial codeconnections resources

### PR DESCRIPTION
**Pull request by silvaalbert**
### Description
This PR adds `aws_codeconnections_connection` and `aws_codeconnections_host` resources. While there are still resources to be developed for CodeConnections, these 2 are the main ones needed to replace CodeStar connections.

### Relations
Relates #36671

### References
https://docs.aws.amazon.com/codeconnections/latest/APIReference/API_CreateConnection.html
https://docs.aws.amazon.com/codeconnections/latest/APIReference/API_CreateHost.html

### Output from Acceptance Testing

```console
make testacc TESTS=TestAccCodeConnectionsConnection_ PKG=codeconnections 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/codeconnections/... -v -count 1 -parallel 20 -run='TestAccCodeConnectionsConnection_'  -timeout 360m
2024/11/25 14:23:00 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeConnectionsConnection_basic
=== PAUSE TestAccCodeConnectionsConnection_basic
=== RUN   TestAccCodeConnectionsConnection_hostARN
=== PAUSE TestAccCodeConnectionsConnection_hostARN
=== RUN   TestAccCodeConnectionsConnection_disappears
=== PAUSE TestAccCodeConnectionsConnection_disappears
=== RUN   TestAccCodeConnectionsConnection_tags
=== PAUSE TestAccCodeConnectionsConnection_tags
=== CONT  TestAccCodeConnectionsConnection_basic
=== CONT  TestAccCodeConnectionsConnection_disappears
=== CONT  TestAccCodeConnectionsConnection_tags
=== CONT  TestAccCodeConnectionsConnection_hostARN
--- PASS: TestAccCodeConnectionsConnection_disappears (13.72s)
--- PASS: TestAccCodeConnectionsConnection_basic (15.66s)
--- PASS: TestAccCodeConnectionsConnection_hostARN (16.42s)
--- PASS: TestAccCodeConnectionsConnection_tags (29.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codeconnections	33.707s
```

```console
make testacc TESTS=TestAccCodeConnectionsHost_ PKG=codeconnections
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/codeconnections/... -v -count 1 -parallel 20 -run='TestAccCodeConnectionsHost_'  -timeout 360m
2024/11/25 14:25:33 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeConnectionsHost_basic
=== PAUSE TestAccCodeConnectionsHost_basic
=== RUN   TestAccCodeConnectionsHost_disappears
=== PAUSE TestAccCodeConnectionsHost_disappears
=== RUN   TestAccCodeConnectionsHost_vpc
=== PAUSE TestAccCodeConnectionsHost_vpc
=== RUN   TestAccCodeConnectionsHost_tags
=== PAUSE TestAccCodeConnectionsHost_tags
=== CONT  TestAccCodeConnectionsHost_basic
=== CONT  TestAccCodeConnectionsHost_vpc
=== CONT  TestAccCodeConnectionsHost_disappears
=== CONT  TestAccCodeConnectionsHost_tags
--- PASS: TestAccCodeConnectionsHost_disappears (12.09s)
--- PASS: TestAccCodeConnectionsHost_basic (14.09s)
=== NAME  TestAccCodeConnectionsHost_tags
    host_test.go:128: Step 3/4 error: Error running apply: exit status 1

        Error: Provider produced inconsistent result after apply

        When applying changes to aws_codeconnections_host.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: .tags["key1"]: was cty.StringVal("value1updated"), but now
        cty.StringVal("value1").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.

        Error: Provider produced inconsistent result after apply

        When applying changes to aws_codeconnections_host.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: .tags: element "key2" has vanished.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.

        Error: Provider produced inconsistent result after apply

        When applying changes to aws_codeconnections_host.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: .tags_all["key1"]: was cty.StringVal("value1updated"), but now
        cty.StringVal("value1").

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.

        Error: Provider produced inconsistent result after apply

        When applying changes to aws_codeconnections_host.test, provider
        "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an unexpected
        new value: .tags_all: element "key2" has vanished.

        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccCodeConnectionsHost_tags (16.90s)
--- PASS: TestAccCodeConnectionsHost_vpc (547.61s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/codeconnections	552.182s
FAIL
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by silvaalbert** [comment]
Thanks for your assistance @ewbankkit! I think this PR is now ready for final review/merging.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCodeConnectionsConnection_\|TestAccCodeConnectionsHost_' PKG=codeconnections ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/codeconnections/... -v -count 1 -parallel 3  -run=TestAccCodeConnectionsConnection_\|TestAccCodeConnectionsHost_ -timeout 360m
2024/12/03 12:47:38 Initializing Terraform AWS Provider...
=== RUN   TestAccCodeConnectionsConnection_basic
=== PAUSE TestAccCodeConnectionsConnection_basic
=== RUN   TestAccCodeConnectionsConnection_hostARN
=== PAUSE TestAccCodeConnectionsConnection_hostARN
=== RUN   TestAccCodeConnectionsConnection_disappears
=== PAUSE TestAccCodeConnectionsConnection_disappears
=== RUN   TestAccCodeConnectionsConnection_tags
=== PAUSE TestAccCodeConnectionsConnection_tags
=== RUN   TestAccCodeConnectionsHost_basic
=== PAUSE TestAccCodeConnectionsHost_basic
=== RUN   TestAccCodeConnectionsHost_disappears
=== PAUSE TestAccCodeConnectionsHost_disappears
=== RUN   TestAccCodeConnectionsHost_vpc
=== PAUSE TestAccCodeConnectionsHost_vpc
=== RUN   TestAccCodeConnectionsHost_tags
=== PAUSE TestAccCodeConnectionsHost_tags
=== CONT  TestAccCodeConnectionsConnection_basic
=== CONT  TestAccCodeConnectionsHost_basic
=== CONT  TestAccCodeConnectionsConnection_disappears
--- PASS: TestAccCodeConnectionsConnection_disappears (11.73s)
=== CONT  TestAccCodeConnectionsConnection_tags
--- PASS: TestAccCodeConnectionsConnection_basic (13.59s)
=== CONT  TestAccCodeConnectionsConnection_hostARN
--- PASS: TestAccCodeConnectionsHost_basic (13.76s)
=== CONT  TestAccCodeConnectionsHost_vpc
--- PASS: TestAccCodeConnectionsConnection_hostARN (13.82s)
=== CONT  TestAccCodeConnectionsHost_tags
--- PASS: TestAccCodeConnectionsConnection_tags (27.51s)
=== CONT  TestAccCodeConnectionsHost_disappears
--- PASS: TestAccCodeConnectionsHost_disappears (10.70s)
--- PASS: TestAccCodeConnectionsHost_tags (27.45s)
--- PASS: TestAccCodeConnectionsHost_vpc (541.20s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codeconnections	560.267s
```

**Review by jar-b — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@silvaalbert Thanks for the contribution :tada: :clap:.

**Pull request merged**
