### PR TITLE
Added the opensearch with standby functionality 

### LINKED ISSUE #31373: [Enhancement]: Support Opensearch domains with standby config
### Description

Support new _Multi-AZ with Standby_ deployment option for AWS Opensearch domains, seems like this is already available in the aws-sdk (see link below).

### Affected Resource(s) and/or Data Source(s)

* aws_opensearch_domain

### Potential Terraform Configuration

```terraform
vpc_options {
// probably here
}
```

### References

* [aws docs](https://docs.aws.amazon.com/opensearch-service/latest/developerguide/managedomains-multiaz.html#managedomains-za-standby)
* [aws sdk](https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.44.262/service/opensearchservice#ClusterConfig.SetMultiAZWithStandbyEnabled)

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by mikekinlock**
### Change
- Added the opensearch with standby functionality 

### Description
- Added the option to configure an opensearch cluster with standby

### Relations

Closes #31373

### References
As a reference to this change I've used the [AWS-CLI](https://docs.aws.amazon.com/cli/latest/reference/opensearch/create-domain.html) documentations and followed their setup structure. Meaning other than requested in the issue, I've added the `MultiAZWithStandbyEnabled` configuration under `cluster-config` and not under `vpc_options`

### Output from Acceptance Testing
The following test is currently failing and I'm not sure how to solve it yet, point is that the created resource is already deleted once the test is trying to verify its configuration. Here I would kindly ask for support. In this case I'm leaning on the `best effort` clause in your [contributor guide](https://hashicorp.github.io/terraform-provider-aws/#4-write-tests)

```console
% make testacc TESTS=TestAccDomainConfig_multiAzWithStandby PKG=opensearch
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccOpenSearchDomainDataSource_Data_advanced\|TestAccOpenSearchDomain_Cluster_multiAzWithStandbyEnabled\|TestAccOpenSearchDomain_basic\|TestAccOpenSearchDomain_Cluster_' PKG=opensearch ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearch/... -v -count 1 -parallel 3  -run=TestAccOpenSearchDomainDataSource_Data_advanced\|TestAccOpenSearchDomain_Cluster_multiAzWithStandbyEnabled\|TestAccOpenSearchDomain_basic\|TestAccOpenSearchDomain_Cluster_ -timeout 720m
=== RUN   TestAccOpenSearchDomainDataSource_Data_advanced
=== PAUSE TestAccOpenSearchDomainDataSource_Data_advanced
=== RUN   TestAccOpenSearchDomain_basic
=== PAUSE TestAccOpenSearchDomain_basic
=== RUN   TestAccOpenSearchDomain_Cluster_zoneAwareness
=== PAUSE TestAccOpenSearchDomain_Cluster_zoneAwareness
=== RUN   TestAccOpenSearchDomain_Cluster_coldStorage
=== PAUSE TestAccOpenSearchDomain_Cluster_coldStorage
=== RUN   TestAccOpenSearchDomain_Cluster_warm
=== PAUSE TestAccOpenSearchDomain_Cluster_warm
=== RUN   TestAccOpenSearchDomain_Cluster_dedicatedMaster
=== PAUSE TestAccOpenSearchDomain_Cluster_dedicatedMaster
=== RUN   TestAccOpenSearchDomain_Cluster_update
=== PAUSE TestAccOpenSearchDomain_Cluster_update
=== RUN   TestAccOpenSearchDomain_Cluster_multiAzWithStandbyEnabled
=== PAUSE TestAccOpenSearchDomain_Cluster_multiAzWithStandbyEnabled
=== CONT  TestAccOpenSearchDomainDataSource_Data_advanced
=== CONT  TestAccOpenSearchDomain_Cluster_warm
=== CONT  TestAccOpenSearchDomain_Cluster_zoneAwareness
--- PASS: TestAccOpenSearchDomainDataSource_Data_advanced (2493.19s)
=== CONT  TestAccOpenSearchDomain_basic
--- PASS: TestAccOpenSearchDomain_basic (1923.63s)
=== CONT  TestAccOpenSearchDomain_Cluster_coldStorage
--- PASS: TestAccOpenSearchDomain_Cluster_warm (5251.12s)
=== CONT  TestAccOpenSearchDomain_Cluster_update
--- PASS: TestAccOpenSearchDomain_Cluster_zoneAwareness (7575.42s)
=== CONT  TestAccOpenSearchDomain_Cluster_multiAzWithStandbyEnabled
--- PASS: TestAccOpenSearchDomain_Cluster_coldStorage (3621.94s)
=== CONT  TestAccOpenSearchDomain_Cluster_dedicatedMaster
--- PASS: TestAccOpenSearchDomain_Cluster_update (4570.21s)
--- PASS: TestAccOpenSearchDomain_Cluster_multiAzWithStandbyEnabled (2958.39s)
--- PASS: TestAccOpenSearchDomain_Cluster_dedicatedMaster (6241.02s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearch	14285.490s
```

**Comment by ewbankkit** [comment]
@mikekinlock Thanks for the contribution :tada: :clap:.

**Comment by amiryoni** [comment]
This bug might have been fixed but the latest documentations are not updated, so I am at a loss here how to use it.
Thanks,

**Comment by AnanyaBanerjee01** [comment]
I think documentation is not updated yet [ewbankkit](https://github.com/ewbankkit) [mikekinlock](https://github.com/mikekinlock)

**Comment by jasonwbarnett** [comment]
Thanks @mikekinlock. I really appreciate the contribution. ❤️

**Pull request merged**
