### PR TITLE
r/aws_guardduty_organization_configuration: Adds datasource/s3_logs a…

### LINKED ISSUE #15106: resource/aws_guardduty_organization_configuration: Guardduty S3 Protection Auto Enable for Member Accounts not available
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* aws_guardduty

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

No data-sources S3Logs autoenable option in Resource: aws_guardduty_organization_configuration similar to provided in aws cli at https://awscli.amazonaws.com/v2/documentation/api/latest/reference/guardduty/update-organization-configuration.html

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by ian-d**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15106

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):
```release-note
resource/aws_guardduty_organization_configuration: Adds s3_logs auto_enable attribute.
```

Output from acceptance testing:
```
$ make testacc TESTARGS='-run=TestAccAWSGuardDuty_serial/OrganizationConfiguration'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSGuardDuty_serial/OrganizationConfiguration -timeout 120m
=== RUN   TestAccAWSGuardDuty_serial
=== RUN   TestAccAWSGuardDuty_serial/OrganizationConfiguration
=== RUN   TestAccAWSGuardDuty_serial/OrganizationConfiguration/basic
=== RUN   TestAccAWSGuardDuty_serial/OrganizationConfiguration/s3Logs
--- PASS: TestAccAWSGuardDuty_serial (103.00s)
    --- PASS: TestAccAWSGuardDuty_serial/OrganizationConfiguration (103.00s)
        --- PASS: TestAccAWSGuardDuty_serial/OrganizationConfiguration/basic (47.72s)
        --- PASS: TestAccAWSGuardDuty_serial/OrganizationConfiguration/s3Logs (55.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	105.249s
```

### CODE REVIEW

**Comment by 0x91** [comment]
any update on this?

**Comment by aldegoeij** [comment]
@bflad could you take a look at this PR? thanks!

**Review by ewbankkit — COMMENTED** [review]
TODO

**Comment by ewbankkit** [comment]
@ian-d Thanks for the contribution :tada: :clap:.

**Pull request merged**
