### PR TITLE
[New Resource]: aws_verifiedpermissions_policy_template

### PR DESCRIPTION
**Pull request by nolotz**
### Description

This merge request seeks to incorporate the `aws_verifiedpermissions_policy_template` resource into the Terraform AWS provider. 

The following elements are included in this merge request:
- Development of the `aws_verifiedpermissions_policy_template` resource in Go.
- Creation of tests to ensure the functionality and reliability of the new resource.
- Compilation of release notes to inform users about the addition of this new resource.
- Generation of a documentation page providing guidance for using the new resource.
- Production of all necessary files via build scripts.

### Relations

Relates #32198
Relates #32158

### References

- https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/verifiedpermissions
- https://aws.amazon.com/verified-permissions/

### Potential Terraform Configuration

```terraform
resource "aws_verifiedpermissions_policy_template" "test" {
	policy_store_id = aws_verifiedpermissions_policy_store.test.id

	description = ""
	statement = ""
}
```

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccVerifiedPermissionsPolicyTemplate PKG=verifiedpermissions

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20 -run='TestAccVerifiedPermissionsPolicyTemplate'  -timeout 180m
=== RUN   TestAccVerifiedPermissionsPolicyTemplate_basic
=== PAUSE TestAccVerifiedPermissionsPolicyTemplate_basic
=== RUN   TestAccVerifiedPermissionsPolicyTemplate_disappears
=== PAUSE TestAccVerifiedPermissionsPolicyTemplate_disappears
=== CONT  TestAccVerifiedPermissionsPolicyTemplate_basic
=== CONT  TestAccVerifiedPermissionsPolicyTemplate_disappears
--- PASS: TestAccVerifiedPermissionsPolicyTemplate_disappears (48.53s)
--- PASS: TestAccVerifiedPermissionsPolicyTemplate_basic (92.40s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions        95.579s
```

### CODE REVIEW

**Comment by euan-cowie** [comment]
Is there an ETA of when this and the related resources might be available in the main release? Thanks!

**Comment by mrkresnofatih** [comment]
Are there any updates on this? Is it waiting on this PR #32208 ?
Would love to know how close this is from being released. 

Thanks

**Comment by luisordaz-ibotta** [comment]
hi @nolotz !

is there any update atm around this new resource?

thanks!

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS='-run=TestAccVerifiedPermissionsPolicyTemplate_' PKG=verifiedpermissions

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/verifiedpermissions/... -v -count 1 -parallel 20  -run=TestAccVerifiedPermissionsPolicyTemplate_ -timeout 360m
--- PASS: TestAccVerifiedPermissionsPolicyTemplate_disappears (10.29s)
--- PASS: TestAccVerifiedPermissionsPolicyTemplate_basic (11.91s)
--- PASS: TestAccVerifiedPermissionsPolicyTemplate_update (17.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/verifiedpermissions	21.019s
```

**Comment by johnsonaj** [comment]
@nolotz thank you for the contribution! 🎉

**Pull request merged**
