### PR TITLE
F msk-vpc-connection

### LINKED ISSUE #31286: [New Service]: AWS Codecatalyst
### Description

Hi,

I am writing to request support for AWS Code Catalyst resources in Terraform. Currently, there is no support for Code Catalyst resources in Terraform, which makes it difficult to use Terraform to manage Code Catalyst projects.

Code Catalyst is a service that helps developers build, test, and deploy cloud applications more quickly and easily. It provides a number of features that can be helpful for Terraform users, such as:

    A centralized repository for storing Terraform modules and configurations
    A built-in CI/CD pipeline for testing and deploying Terraform code
    A set of tools for managing Terraform state

I believe that adding support for Code Catalyst resources to Terraform would be a valuable addition to the Terraform ecosystem. It would make it easier for Terraform users to take advantage of the features that Code Catalyst provides.

I would be happy to help with the development of this feature. Please let me know if you have any questions.

Thank you,
Stefen Orban

### Requested Resource(s) and/or Data Source(s)

aws_codecatalyst_Project
aws_codecatalyst_Space
aws_codecatalyst_AccessToken
aws_codecatalyst_SourceRepositoryBranch
aws_codecatalyst_DevEnvironment

### Potential Terraform Configuration

```terraform
resource "aws_codecatalyst_space" "default" {
  name = "Terraform CodeCatalyst"
  account_id = "111122223333"
}

resource "aws_codecatalyst_project" "default" {
  name = "My Terraform Project"
  space_id = aws_codecatalyst_space.default.id
}

resource "aws_codecatalyst_repo" "default" {
  name = "My Terraform Repository"
  project_id = aws_codecatalyst_project.default.id
  url = "https://github.com/my-username/my-terraform-repo"
}

resource "aws_codecatalyst_environment" "default" {
  name = "My Terraform Environment"
  project_id = aws_codecatalyst_project.default.id
  repo_id = aws_codecatalyst_repo.default.id
  compute_type = "t3.medium"
  memory = 512
  instance_count = 1
}
```

### References

go reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/codecatalyst
sdk reference: https://docs.aws.amazon.com/AWSJavaScriptSDK/v3/latest/clients/client-codecatalyst/

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by markoskandylis**
### Description

Adds support for MSK VPC-Connection

### Relations

Relates #31062

### References

go reference: https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/kafka
api reference: https://docs.aws.amazon.com/msk/1.0/apireference/vpc-connection.html

### Output from Acceptance Testing

```
make testacc TESTARGS='-run=TestAccKafkaVPCConnection_' PKG=kafka  ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 2  -run=TestAccKafkaVPCConnection_ -timeout 180m
=== RUN   TestAccKafkaVPCConnection_basic
=== PAUSE TestAccKafkaVPCConnection_basic
=== RUN   TestAccKafkaVPCConnection_disappears
=== PAUSE TestAccKafkaVPCConnection_disappears
=== CONT  TestAccKafkaVPCConnection_basic
=== CONT  TestAccKafkaVPCConnection_disappears
--- PASS: TestAccKafkaVPCConnection_basic (474.67s)
--- PASS: TestAccKafkaVPCConnection_disappears (494.92s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	498.030s
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@markoskandylis Thanks for the contribution 👏.

It looks like we'll have to add `broker_node_group_info.connectivity_info.vpc_connectivity` to the `aws_msk_broker` resource to get the tests working. Currently:

```console
% make testacc TESTARGS='-run=TestAccKafkaVPCConnection_' PKG=kafka ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 2  -run=TestAccKafkaVPCConnection_ -timeout 180m
=== RUN   TestAccKafkaVPCConnection_basic
=== PAUSE TestAccKafkaVPCConnection_basic
=== RUN   TestAccKafkaVPCConnection_disappears
=== PAUSE TestAccKafkaVPCConnection_disappears
=== CONT  TestAccKafkaVPCConnection_basic
=== CONT  TestAccKafkaVPCConnection_disappears
    vpc_connection_test.go:59: Step 1/1 error: Error running apply: exit status 1
        
        Error: creating Amazon Managed Streaming for Kafka VPC Connection (): operation error Kafka: CreateVpcConnection, https response error StatusCode: 400, RequestID: 7ec182fa-505a-422c-b1e3-2bc9e207b467, BadRequestException: SASL/IAM client authentication must be enabled for the cluster.
        
          with aws_msk_vpc_connection.test,
          on terraform_plugin_test.tf line 137, in resource "aws_msk_vpc_connection" "test":
         137: resource "aws_msk_vpc_connection" "test" {
        
=== NAME  TestAccKafkaVPCConnection_basic
    vpc_connection_test.go:28: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Amazon Managed Streaming for Kafka VPC Connection (): operation error Kafka: CreateVpcConnection, https response error StatusCode: 400, RequestID: 7e52bb5b-0039-4484-854f-365076a32429, BadRequestException: SASL/IAM client authentication must be enabled for the cluster.
        
          with aws_msk_vpc_connection.test,
          on terraform_plugin_test.tf line 137, in resource "aws_msk_vpc_connection" "test":
         137: resource "aws_msk_vpc_connection" "test" {
        
--- FAIL: TestAccKafkaVPCConnection_basic (2026.07s)
--- FAIL: TestAccKafkaVPCConnection_disappears (2033.02s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	2038.193s
FAIL
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
I _think_ policy is only required for cross-account connections.

**Comment by markoskandylis** [comment]
Hmm ye probably you are right i  will check and fix it tomorrow :) , Also if you can advice for the tags because they are map[string]string instead of map[string]*string (that all the other resources are) will be best practice to add new block on tags_gen.go or change the type in the vpc_connection.go?

**Comment by markoskandylis** [comment]
New tests passed:

make testacc TESTARGS='-run=TestAccKafkaVPCConnection_' PKG=kafka  ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 2  -run=TestAccKafkaVPCConnection_ -timeout 180m
=== RUN   TestAccKafkaVPCConnection_basic
=== PAUSE TestAccKafkaVPCConnection_basic
=== RUN   TestAccKafkaVPCConnection_disappears
=== PAUSE TestAccKafkaVPCConnection_disappears
=== CONT  TestAccKafkaVPCConnection_basic
=== CONT  TestAccKafkaVPCConnection_disappears
--- PASS: TestAccKafkaVPCConnection_disappears (3901.80s)
--- PASS: TestAccKafkaVPCConnection_basic (3905.39s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	3908.563s

**Comment by markoskandylis** [comment]
The Successfull data test with the code i pushed:
make testacc TESTARGS='-run=TestAccKafkaVpcConnectionDataSource_basic' PKG=kafka  ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 2  -run=TestAccKafkaVpcConnectionDataSource_basic -timeout 180m
=== RUN   TestAccKafkaVpcConnectionDataSource_basic
=== PAUSE TestAccKafkaVpcConnectionDataSource_basic
=== CONT  TestAccKafkaVpcConnectionDataSource_basic
--- PASS: TestAccKafkaVpcConnectionDataSource_basic (6448.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	6451.670s

**Comment by ewbankkit** [comment]
@markoskandylis I'll take care of the merge conflict tomorrow. Thanks 👏.

**Comment by ewbankkit** [comment]
```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccKafkaCluster_' PKG=kafka ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 3  -run=TestAccKafkaCluster_ -timeout 720m
=== RUN   TestAccKafkaCluster_basic
=== PAUSE TestAccKafkaCluster_basic
=== RUN   TestAccKafkaCluster_disappears
=== PAUSE TestAccKafkaCluster_disappears
=== RUN   TestAccKafkaCluster_tags
=== PAUSE TestAccKafkaCluster_tags
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_storageInfo
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_storageInfo
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIAM
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIAM
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_vpcConnectivity
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_vpcConnectivity
=== RUN   TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== PAUSE TestAccKafkaCluster_ClientAuthenticationSASL_scram
=== RUN   TestAccKafkaCluster_ClientAuthenticationSASL_iam
=== PAUSE TestAccKafkaCluster_ClientAuthenticationSASL_iam
=== RUN   TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs
=== PAUSE TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs
=== RUN   TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
=== PAUSE TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
=== RUN   TestAccKafkaCluster_Info_revision
=== PAUSE TestAccKafkaCluster_Info_revision
=== RUN   TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN
=== PAUSE TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN
=== RUN   TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker
=== PAUSE TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker
=== RUN   TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster
=== PAUSE TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster
=== RUN   TestAccKafkaCluster_enhancedMonitoring
=== PAUSE TestAccKafkaCluster_enhancedMonitoring
=== RUN   TestAccKafkaCluster_numberOfBrokerNodes
=== PAUSE TestAccKafkaCluster_numberOfBrokerNodes
=== RUN   TestAccKafkaCluster_openMonitoring
=== PAUSE TestAccKafkaCluster_openMonitoring
=== RUN   TestAccKafkaCluster_storageMode
=== PAUSE TestAccKafkaCluster_storageMode
=== RUN   TestAccKafkaCluster_loggingInfo
=== PAUSE TestAccKafkaCluster_loggingInfo
=== RUN   TestAccKafkaCluster_kafkaVersionUpgrade
=== PAUSE TestAccKafkaCluster_kafkaVersionUpgrade
=== RUN   TestAccKafkaCluster_kafkaVersionDowngrade
=== PAUSE TestAccKafkaCluster_kafkaVersionDowngrade
=== RUN   TestAccKafkaCluster_kafkaVersionUpgradeWithInfo
=== PAUSE TestAccKafkaCluster_kafkaVersionUpgradeWithInfo
=== CONT  TestAccKafkaCluster_basic
=== CONT  TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_vpcConnectivity
--- PASS: TestAccKafkaCluster_basic (2070.60s)
=== CONT  TestAccKafkaCluster_storageMode
--- PASS: TestAccKafkaCluster_EncryptionInfo_encryptionAtRestKMSKeyARN (2072.89s)
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_storageInfo
--- PASS: TestAccKafkaCluster_storageMode (3035.92s)
=== CONT  TestAccKafkaCluster_kafkaVersionUpgradeWithInfo
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_storageInfo (2247.99s)
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIAM
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_vpcConnectivity (6260.84s)
=== CONT  TestAccKafkaCluster_kafkaVersionDowngrade
--- PASS: TestAccKafkaCluster_kafkaVersionUpgradeWithInfo (6874.66s)
=== CONT  TestAccKafkaCluster_kafkaVersionUpgrade
--- PASS: TestAccKafkaCluster_kafkaVersionDowngrade (4318.38s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIAM (6293.44s)
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType
--- PASS: TestAccKafkaCluster_ClientAuthenticationTLS_certificateAuthorityARNs (2231.34s)
=== CONT  TestAccKafkaCluster_loggingInfo
--- PASS: TestAccKafkaCluster_loggingInfo (2770.44s)
=== CONT  TestAccKafkaCluster_Info_revision
--- PASS: TestAccKafkaCluster_kafkaVersionUpgrade (6817.77s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_instanceType (6869.62s)
=== CONT  TestAccKafkaCluster_enhancedMonitoring
--- PASS: TestAccKafkaCluster_Info_revision (3254.13s)
=== CONT  TestAccKafkaCluster_openMonitoring
--- PASS: TestAccKafkaCluster_enhancedMonitoring (2407.59s)
=== CONT  TestAccKafkaCluster_numberOfBrokerNodes
--- PASS: TestAccKafkaCluster_ClientAuthenticationTLS_initiallyNoAuthentication (4826.71s)
=== CONT  TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster
--- PASS: TestAccKafkaCluster_openMonitoring (3031.32s)
=== CONT  TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker
--- PASS: TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_inCluster (2075.66s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationSASL_iam
--- PASS: TestAccKafkaCluster_numberOfBrokerNodes (3280.01s)
=== CONT  TestAccKafkaCluster_ClientAuthenticationSASL_scram
--- PASS: TestAccKafkaCluster_EncryptionInfoEncryptionInTransit_clientBroker (2429.11s)
=== CONT  TestAccKafkaCluster_disappears
--- PASS: TestAccKafkaCluster_disappears (1913.35s)
=== CONT  TestAccKafkaCluster_tags
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_scram (3742.33s)
--- PASS: TestAccKafkaCluster_ClientAuthenticationSASL_iam (4224.93s)
--- PASS: TestAccKafkaCluster_tags (2230.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	28445.227s
```
```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccKafkaVPCConnectionDataSource_\|TestAccKafkaVPCConnection_' PKG=kafka ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 1  -run=TestAccKafkaVPCConnectionDataSource_\|TestAccKafkaVPCConnection_ -timeout 720m
=== RUN   TestAccKafkaVPCConnectionDataSource_basic
=== PAUSE TestAccKafkaVPCConnectionDataSource_basic
=== RUN   TestAccKafkaVPCConnection_basic
=== PAUSE TestAccKafkaVPCConnection_basic
=== RUN   TestAccKafkaVPCConnection_disappears
=== PAUSE TestAccKafkaVPCConnection_disappears
=== CONT  TestAccKafkaVPCConnectionDataSource_basic
=== CONT  TestAccKafkaVPCConnection_disappears
--- PASS: TestAccKafkaVPCConnectionDataSource_basic (6975.36s)
--- PASS: TestAccKafkaVPCConnection_disappears (6379.56s)
=== CONT  TestAccKafkaVPCConnection_basic
--- PASS: TestAccKafkaVPCConnection_basic (7065.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	20426.234s
```

**Comment by markoskandylis** [comment]
The Tags test:
make testacc TESTARGS='-run=TestAccKafkaVPCConnectionDataSource_' PKG=kafka  ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 3  -run=TestAccKafkaVPCConnectionDataSource_ -timeout 180m
=== RUN   TestAccKafkaVPCConnectionDataSource_basic
=== PAUSE TestAccKafkaVPCConnectionDataSource_basic
=== CONT  TestAccKafkaVPCConnectionDataSource_basic
--- PASS: TestAccKafkaVPCConnectionDataSource_basic (6847.04s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	6850.268s

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccKafkaVPCConnection_tags' PKG=kafka ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 1  -run=TestAccKafkaVPCConnection_tags -timeout 720m
=== RUN   TestAccKafkaVPCConnection_tags
=== PAUSE TestAccKafkaVPCConnection_tags
=== CONT  TestAccKafkaVPCConnection_tags
--- PASS: TestAccKafkaVPCConnection_tags (7365.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	7366.695s
```

**Comment by ewbankkit** [comment]
@markoskandylis Thanks for the contribution :tada: :clap:.

**Pull request merged**
