### PR TITLE
r/aws_elasticsearchdomain: add support for saml_options

### LINKED ISSUE #16259: Feature Request: ElasticSearch - native SAML Authentication for Kibana
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

_"Amazon Elasticsearch Service now natively supports using Security Assertion Markup Language (SAML) to offer single sign-on (SSO) for Kibana. SAML authentication for Kibana enables users to integrate directly with third-party identity providers (IDP) such as Okta, Ping Identity, OneLogin, Auth0, Active Directory Federation Services (ADFS) and Azure Active Directory. With this feature, your users can leverage their existing usernames and passwords to log in to Kibana, and roles from your IDP can be used for controlling privileges in Elasticsearch and Kibana, including what operations they can perform and what data they can search and visualize. "_

### New or Affected Resource(s)

* aws_elasticsearch_domain

### Potential Terraform Configuration

```hcl


resource "aws_elasticsearch_domain" "test" {
    advanced_security_options {
        saml_options {
            enabled  = true
            master_user_name = "my-idp-user"
            master_backend_role = "my-idp-group-or-role"
            idp {
                entity_id = "entity-id"
                metadata_content = "metadata-content-with-quotes-escaped"
            }
            roles_key =optional-roles-key
            session_timeout_minutes = 180
            subject_key = "optional-subject-key"
        }
    }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/10/amazon-elasticsearch-service-adds-native-saml-authentication-kibana/
* https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/saml.html

### PR DESCRIPTION
**Pull request by philof**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #16259 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_elasticsearch_domain: Support `saml_options` advanced_security_option ([#16259](https://github.com/hashicorp/terraform-provider-aws/issues/16259))
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_SAML'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_SAML -timeout 120m
=== RUN   TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_SAML
=== PAUSE TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_SAML
=== CONT  TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_SAML
--- PASS: TestAccAWSElasticSearchDomain_AdvancedSecurityOptions_SAML (985.80s)
PASS
ok           github.com/terraform-providers/terraform-provider-aws/aws     987.358s
...
```

The overall structure is ready, but I still have an issue with `You cannot specify SAML options during domain creation`.  The second apply in the create test results in a non-empty plan.  I couldn't find another resource in the repo which restricts parameters on creation.  I would greatly appreciate any guidance for this two-step creation process.

### CODE REVIEW

**Comment by jbvmio** [comment]
When will this be merged?

**Comment by thameezb** [comment]
bump

**Comment by JeffAshton** [comment]
Did you consider making the SAML options be there own resource so that it could be combined with the Okta terraform provider

https://registry.terraform.io/providers/oktadeveloper/okta/latest/docs/resources/app_saml

Elasticsearch -> Okta -> Elasticsearch SAML

This would also solve the issue that SAML config cannot be specified until after the domain is created.

**Comment by philof** [comment]
I have a new custom resource for aws_elasticsearch_domain_saml_options. Would you like a new pull request or to edit this one?

**Comment by JeffAshton** [comment]
> aws_elasticsearch_domain_saml_options

I would probably create a new pull request.  The separate resource should be perfect.

**Pull request closed without merging**
