### PR TITLE
fix: Skip listing tags on `aws_vpclattice_service_network` data source when shared via RAM

### LINKED ISSUE #32938: [Bug]: `aws_vpclattice_service_network` and `aws_vpclattice_service` do not return tags in the describe API call
### Terraform Core Version

1.3.0

### AWS Provider Version

5.11.0

### Affected Resource(s)

* aws_vpclattice_service
* aws_vpclattice_service_network

### Expected Behavior

Using the data sources should not result in errors when using RAM shared service or service network

### Actual Behavior

When using the data sources, errors are thrown when querying the resources that have been provided via RAM resource share

### Relevant Error/Panic Output Snippet

```shell
│ Error: reading Amazon VPC Lattice Service Network Data Source (sn-xxx): operation error VPC Lattice: ListTagsForResource, https response error StatusCode: 403, RequestID: 8f7b5422-00a2-44c7-a05b-5cc1235f87f7, api error AccessDeniedException: User: arn:aws:sts::11111111111:assumed-role/CFTerraformRole/aws-go-sdk-1691535031721424000 is not authorized to perform: vpc-lattice:ListTagsForResource on resource: arn:aws:vpc-lattice:us-west-2:222222222222:servicenetwork/sn-xxxx
```

### Terraform Configuration Files

# Create in parent account and share via RAM resource association
resource "aws_vpclattice_service" "example" {
  name               = "example"
  auth_type          = "AWS_IAM"
  custom_domain_name = "example.com"
}

# Query in account that service has been shared with
data "aws_vpclattice_service" "example" {
  name = "example"
}

### Steps to Reproduce

1. Deploy a service or service network in account A
2. Share service or service network with account B using RAM resource sharing
3. In account B, attempt to use the data source to query the shared resource - you should observe a similar error message to what is shared above

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

- VPC Lattice service network `getServiceNetwork` function call output struct does not contain tags, the API response does not return tags https://docs.aws.amazon.com/sdk-for-go/api/service/vpclattice/#GetServiceNetworkOutput

- VPC Lattice service `getService` function call output struct does not contain tags, the API response does not return tags https://docs.aws.amazon.com/sdk-for-go/api/service/vpclattice/#GetServiceOutput

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by bryantbiggs**
### Relations

Closes #32938.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/26695.

### Output from Acceptance Testing

```console
make testacc TESTARGS='-run=TestAccVPCLatticeServiceNetwork' PKG=vpclattice ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 2  -run=TestAccVPCLatticeServiceNetwork -timeout 180m
=== RUN   TestAccVPCLatticeServiceNetworkDataSource_basic
=== PAUSE TestAccVPCLatticeServiceNetworkDataSource_basic
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_arn
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_arn
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_tags
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_tags
=== RUN   TestAccVPCLatticeServiceNetwork_basic
=== PAUSE TestAccVPCLatticeServiceNetwork_basic
=== RUN   TestAccVPCLatticeServiceNetwork_disappears
=== PAUSE TestAccVPCLatticeServiceNetwork_disappears
=== RUN   TestAccVPCLatticeServiceNetwork_full
=== PAUSE TestAccVPCLatticeServiceNetwork_full
=== RUN   TestAccVPCLatticeServiceNetwork_tags
=== PAUSE TestAccVPCLatticeServiceNetwork_tags
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_basic
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_basic
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_arn
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_arn
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_disappears
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_disappears
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_full
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_full
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_tags
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_tags
=== CONT  TestAccVPCLatticeServiceNetworkDataSource_basic
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_full
--- PASS: TestAccVPCLatticeServiceNetworkDataSource_basic (39.14s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_tags
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_tags (149.51s)
=== CONT  TestAccVPCLatticeServiceNetwork_disappears
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_full (218.81s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_disappears
--- PASS: TestAccVPCLatticeServiceNetwork_disappears (32.55s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_arn
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_disappears (110.73s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_basic
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_arn (186.19s)
=== CONT  TestAccVPCLatticeServiceNetwork_full
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_basic (98.01s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
--- PASS: TestAccVPCLatticeServiceNetwork_full (43.06s)
=== CONT  TestAccVPCLatticeServiceNetwork_basic
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_disappears (47.09s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_tags
--- PASS: TestAccVPCLatticeServiceNetwork_basic (42.71s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_arn
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_arn (53.92s)
=== CONT  TestAccVPCLatticeServiceNetwork_tags
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_tags (111.34s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_basic
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_basic (55.63s)
--- PASS: TestAccVPCLatticeServiceNetwork_tags (101.55s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice	648.799s
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@bryantbiggs Thanks for looking into this 👏.
Removing the `tags` attributes would be a breaking change.
We had a similar issue with shared AppMesh resources -- take a look at e.g. `internal/service/appmesh/mesh_data_source.go` for how to determine whether or not to call `listTags`.

**Comment by bryantbiggs** [comment]
```console
make testacc TESTARGS='-run=TestAccVPCLatticeServiceNetwork' PKG=vpclattice ACCTEST_PARALLELISM=2               
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/vpclattice/... -v -count 1 -parallel 2  -run=TestAccVPCLatticeServiceNetwork -timeout 180m
=== RUN   TestAccVPCLatticeServiceNetworkDataSource_basic
=== PAUSE TestAccVPCLatticeServiceNetworkDataSource_basic
=== RUN   TestAccVPCLatticeServiceNetworkDataSource_tags
=== PAUSE TestAccVPCLatticeServiceNetworkDataSource_tags
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_basic
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_arn
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_arn
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
=== RUN   TestAccVPCLatticeServiceNetworkServiceAssociation_tags
=== PAUSE TestAccVPCLatticeServiceNetworkServiceAssociation_tags
=== RUN   TestAccVPCLatticeServiceNetwork_basic
=== PAUSE TestAccVPCLatticeServiceNetwork_basic
=== RUN   TestAccVPCLatticeServiceNetwork_disappears
=== PAUSE TestAccVPCLatticeServiceNetwork_disappears
=== RUN   TestAccVPCLatticeServiceNetwork_full
=== PAUSE TestAccVPCLatticeServiceNetwork_full
=== RUN   TestAccVPCLatticeServiceNetwork_tags
=== PAUSE TestAccVPCLatticeServiceNetwork_tags
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_basic
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_basic
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_arn
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_arn
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_disappears
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_disappears
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_full
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_full
=== RUN   TestAccVPCLatticeServiceNetworkVPCAssociation_tags
=== PAUSE TestAccVPCLatticeServiceNetworkVPCAssociation_tags
=== CONT  TestAccVPCLatticeServiceNetworkDataSource_basic
=== CONT  TestAccVPCLatticeServiceNetwork_full
--- PASS: TestAccVPCLatticeServiceNetworkDataSource_basic (39.01s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_disappears
--- PASS: TestAccVPCLatticeServiceNetwork_full (44.32s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_tags
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_disappears (100.75s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_full
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_tags (160.48s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_disappears
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_full (100.93s)
=== CONT  TestAccVPCLatticeServiceNetwork_disappears
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_disappears (46.57s)
=== CONT  TestAccVPCLatticeServiceNetwork_basic
--- PASS: TestAccVPCLatticeServiceNetwork_disappears (38.10s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_tags
--- PASS: TestAccVPCLatticeServiceNetwork_basic (43.31s)
=== CONT  TestAccVPCLatticeServiceNetwork_tags
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_tags (112.94s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_basic
--- PASS: TestAccVPCLatticeServiceNetwork_tags (101.11s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_basic
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_basic (52.36s)
=== CONT  TestAccVPCLatticeServiceNetworkServiceAssociation_arn
--- PASS: TestAccVPCLatticeServiceNetworkServiceAssociation_arn (51.14s)
=== CONT  TestAccVPCLatticeServiceNetworkVPCAssociation_arn
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_basic (107.87s)
=== CONT  TestAccVPCLatticeServiceNetworkDataSource_tags
--- PASS: TestAccVPCLatticeServiceNetworkDataSource_tags (37.99s)
--- PASS: TestAccVPCLatticeServiceNetworkVPCAssociation_arn (97.34s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/vpclattice	596.804s
```

**Comment by ewbankkit** [comment]
@bryantbiggs Thanks for the contribution :tada: :clap:.
I added some tests and added the same logic to the `aws_vpclattice_service` data source.

**Comment by bryantbiggs** [comment]
thank you - I appreciate it!

**Pull request merged**
