### PR TITLE
Fix/doc kinesis firehose delivery stream

### PR DESCRIPTION
**Pull request by chroju**
Fix a document about kinesis firehose delivery stream `http_endpoint_configuration.s3_backup_mode` . see: https://docs.aws.amazon.com/ja_jp/firehose/latest/APIReference/API_HttpEndpointDestinationConfiguration.html

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

N/A

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Relevant `aws_kinesis_firehose_delivery_stream` resource code:

https://github.com/hashicorp/terraform-provider-aws/blob/1a465255d69c8037d232846616b250c899b2fac8/aws/resource_aws_kinesis_firehose_delivery_stream.go#L1494-L1499

Relevant AWS SDK code:

https://github.com/aws/aws-sdk-go/blob/d265de10614f7d6dda84a81d3befb8bff9eb61f0/service/firehose/api.go#L8464-L8478

**Comment by ewbankkit** [comment]
@chroju Thanks for the contribution :clap:.
It looks like the documentation is doubly (or triply) wrong 😄.
Valid values are `FailedDataOnly` and `AllData`, with `FailedDataOnly` as the default. Could you please update this PR?
[AWS API Reference](https://docs.aws.amazon.com/firehose/latest/APIReference/API_HttpEndpointDestinationConfiguration.html#Firehose-Type-HttpEndpointDestinationConfiguration-S3BackupMode).

**Comment by chroju** [comment]
@ewbankkit Thanks for your review and comment 👍 I have updated.

**Review by ewbankkit — APPROVED** [review]
LGTM 🚀.

**Pull request merged**
