### PR TITLE
Add SecretsManager support for DB2 LUW

### PR DESCRIPTION
**Pull request by j2clerck**
### Description

This PR adds support for SecretsManager when setting up an aws_dms_endpoint source with DB2 engine. Currently if specifying the DB2 engine and SecretsManager, terraform will fail complaining about password being a mandatory field.

### Relations

Closes #0000

### Output from Acceptance Testing

```
make testacc TESTS=TestAccDMSEndpoint_db2_secretID PKG=dms                                        24s 16:53:00
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_db2_secretID'  -timeout 180m
=== RUN   TestAccDMSEndpoint_db2_secretID
=== PAUSE TestAccDMSEndpoint_db2_secretID
=== CONT  TestAccDMSEndpoint_db2_secretID
--- PASS: TestAccDMSEndpoint_db2_secretID (132.04s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dms        132.130s

...
```

### CODE REVIEW

**Comment by AdamTylerLynch** [comment]
I would like to see a bit more AccTests run:
`TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_db2'  -timeout 180m`

**Comment by j2clerck** [comment]
```
❯ TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_db2'  -timeout 180m
=== RUN   TestAccDMSEndpoint_db2_basic
=== PAUSE TestAccDMSEndpoint_db2_basic
=== RUN   TestAccDMSEndpoint_db2_secretID
=== PAUSE TestAccDMSEndpoint_db2_secretID
=== CONT  TestAccDMSEndpoint_db2_basic
=== CONT  TestAccDMSEndpoint_db2_secretID
--- PASS: TestAccDMSEndpoint_db2_secretID (126.93s)
--- PASS: TestAccDMSEndpoint_db2_basic (135.60s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	138.839s
```

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccDMSEndpoint_basic\|TestAccDMSEndpoint_db2' PKG=dms ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 3  -run=TestAccDMSEndpoint_basic\|TestAccDMSEndpoint_db2 -timeout 180m
=== RUN   TestAccDMSEndpoint_basic
=== PAUSE TestAccDMSEndpoint_basic
=== RUN   TestAccDMSEndpoint_db2_basic
=== PAUSE TestAccDMSEndpoint_db2_basic
=== RUN   TestAccDMSEndpoint_db2_secretID
=== PAUSE TestAccDMSEndpoint_db2_secretID
=== CONT  TestAccDMSEndpoint_basic
=== CONT  TestAccDMSEndpoint_db2_secretID
=== CONT  TestAccDMSEndpoint_db2_basic
--- PASS: TestAccDMSEndpoint_db2_secretID (38.59s)
--- PASS: TestAccDMSEndpoint_db2_basic (48.52s)
--- PASS: TestAccDMSEndpoint_basic (48.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/dms	53.943s
```

**Comment by ewbankkit** [comment]
@j2clerck Thanks for the contribution :tada: :clap:.

**Pull request merged**
