### PR TITLE
r/aws_autoscaling_policy: Support metric math for target tracking policy

### PR DESCRIPTION
**Pull request by jungseoklee**
### Description

This PR supports metric math for EC2 Auto Scaling target tracking policy, which was released on Dec 8, 2022: https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ec2-auto-scaling-supports-metric-math-target-tracking-policies/

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/pull/29148.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29145.

### References

- https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-ec2-auto-scaling-supports-metric-math-target-tracking-policies/
- https://docs.aws.amazon.com/autoscaling/ec2/userguide/ec2-auto-scaling-target-tracking-metric-math.html
- https://docs.aws.amazon.com/autoscaling/ec2/APIReference/API_CustomizedMetricSpecification.html

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccAutoScalingPolicy PKG=autoscaling
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 20 -run='TestAccAutoScalingPolicy'  -timeout 180m
=== RUN   TestAccAutoScalingPolicy_basic
=== PAUSE TestAccAutoScalingPolicy_basic
=== RUN   TestAccAutoScalingPolicy_disappears
=== PAUSE TestAccAutoScalingPolicy_disappears
=== RUN   TestAccAutoScalingPolicy_predictiveScalingPredefined
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingPredefined
=== RUN   TestAccAutoScalingPolicy_predictiveScalingCustom
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingCustom
=== RUN   TestAccAutoScalingPolicy_predictiveScalingRemoved
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingRemoved
=== RUN   TestAccAutoScalingPolicy_predictiveScalingUpdated
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingUpdated
=== RUN   TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== PAUSE TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== RUN   TestAccAutoScalingPolicy_TargetTrack_predefined
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_predefined
=== RUN   TestAccAutoScalingPolicy_TargetTrack_custom
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_custom
=== RUN   TestAccAutoScalingPolicy_TargetTrack_metricMath
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_metricMath
=== RUN   TestAccAutoScalingPolicy_zeroValue
=== PAUSE TestAccAutoScalingPolicy_zeroValue
=== CONT  TestAccAutoScalingPolicy_basic
=== CONT  TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== CONT  TestAccAutoScalingPolicy_predictiveScalingCustom
=== CONT  TestAccAutoScalingPolicy_predictiveScalingUpdated
=== CONT  TestAccAutoScalingPolicy_predictiveScalingRemoved
=== CONT  TestAccAutoScalingPolicy_TargetTrack_metricMath
=== CONT  TestAccAutoScalingPolicy_predictiveScalingPredefined
=== CONT  TestAccAutoScalingPolicy_TargetTrack_custom
=== CONT  TestAccAutoScalingPolicy_zeroValue
=== CONT  TestAccAutoScalingPolicy_disappears
=== CONT  TestAccAutoScalingPolicy_TargetTrack_predefined
--- PASS: TestAccAutoScalingPolicy_simpleScalingStepAdjustment (37.41s)
--- PASS: TestAccAutoScalingPolicy_TargetTrack_custom (46.77s)
--- PASS: TestAccAutoScalingPolicy_TargetTrack_metricMath (49.11s)
--- PASS: TestAccAutoScalingPolicy_TargetTrack_predefined (49.31s)
--- PASS: TestAccAutoScalingPolicy_disappears (53.24s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingCustom (55.54s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingPredefined (56.88s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingUpdated (60.31s)
--- PASS: TestAccAutoScalingPolicy_zeroValue (60.72s)
--- PASS: TestAccAutoScalingPolicy_basic (68.31s)
--- PASS: TestAccAutoScalingPolicy_predictiveScalingRemoved (69.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	69.969s
```

### CODE REVIEW

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAutoScalingPolicy_' PKG=autoscaling ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 3  -run=TestAccAutoScalingPolicy_ -timeout 180m
=== RUN   TestAccAutoScalingPolicy_basic
=== PAUSE TestAccAutoScalingPolicy_basic
=== RUN   TestAccAutoScalingPolicy_disappears
=== PAUSE TestAccAutoScalingPolicy_disappears
=== RUN   TestAccAutoScalingPolicy_predictiveScalingPredefined
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingPredefined
=== RUN   TestAccAutoScalingPolicy_predictiveScalingResourceLabel
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingResourceLabel
=== RUN   TestAccAutoScalingPolicy_predictiveScalingCustom
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingCustom
=== RUN   TestAccAutoScalingPolicy_predictiveScalingRemoved
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingRemoved
=== RUN   TestAccAutoScalingPolicy_predictiveScalingUpdated
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingUpdated
=== RUN   TestAccAutoScalingPolicy_predictiveScalingFloatTargetValue
=== PAUSE TestAccAutoScalingPolicy_predictiveScalingFloatTargetValue
=== RUN   TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== PAUSE TestAccAutoScalingPolicy_simpleScalingStepAdjustment
=== RUN   TestAccAutoScalingPolicy_TargetTrack_predefined
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_predefined
=== RUN   TestAccAutoScalingPolicy_TargetTrack_custom
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_custom
=== RUN   TestAccAutoScalingPolicy_TargetTrack_metricMath
=== PAUSE TestAccAutoScalingPolicy_TargetTrack_metricMath
=== RUN   TestAccAutoScalingPolicy_zeroValue
=== PAUSE TestAccAutoScalingPolicy_zeroValue
=== CONT  TestAccAutoScalingPolicy_basic
=== CONT  TestAccAutoScalingPolicy_predictiveScalingFloatTargetValue
=== CONT  TestAccAutoScalingPolicy_TargetTrack_custom
--- PASS: TestAccAutoScalingPolicy_TargetTrack_custom (49.39s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingCustom
--- PASS: TestAccAutoScalingPolicy_predictiveScalingFloatTargetValue (67.73s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingUpdated
--- PASS: TestAccAutoScalingPolicy_basic (100.45s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingRemoved
--- PASS: TestAccAutoScalingPolicy_predictiveScalingCustom (62.73s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingPredefined
--- PASS: TestAccAutoScalingPolicy_predictiveScalingUpdated (83.54s)
=== CONT  TestAccAutoScalingPolicy_predictiveScalingResourceLabel
--- PASS: TestAccAutoScalingPolicy_predictiveScalingRemoved (70.24s)
=== CONT  TestAccAutoScalingPolicy_zeroValue
--- PASS: TestAccAutoScalingPolicy_predictiveScalingPredefined (65.21s)
=== CONT  TestAccAutoScalingPolicy_TargetTrack_predefined
--- PASS: TestAccAutoScalingPolicy_predictiveScalingResourceLabel (64.28s)
=== CONT  TestAccAutoScalingPolicy_disappears
--- PASS: TestAccAutoScalingPolicy_zeroValue (57.50s)
=== CONT  TestAccAutoScalingPolicy_TargetTrack_metricMath
--- PASS: TestAccAutoScalingPolicy_TargetTrack_predefined (51.81s)
=== CONT  TestAccAutoScalingPolicy_simpleScalingStepAdjustment
--- PASS: TestAccAutoScalingPolicy_disappears (50.22s)
--- PASS: TestAccAutoScalingPolicy_TargetTrack_metricMath (50.94s)
--- PASS: TestAccAutoScalingPolicy_simpleScalingStepAdjustment (54.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	288.629s
```

**Comment by ewbankkit** [comment]
@jungseoklee @gungoren Thanks for the contribution :tada: :clap:.

**Comment by jungseoklee** [comment]
@AdamTylerLynch @ewbankkit Great thanks for reviewing and taking care of this PR!

**Pull request merged**
