### PR TITLE
d/aws_route: Refactor acceptance tests in preparation for future fixes/enhancements

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Refactoring `aws_route` data source acceptance tests in preparation for future fixes/enhancements.

Output from acceptance testing:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRouteDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws/ -v -count 1 -parallel 2 -run=TestAccAWSRouteDataSource_ -timeout 120m
=== RUN   TestAccAWSRouteDataSource_basic
=== PAUSE TestAccAWSRouteDataSource_basic
=== RUN   TestAccAWSRouteDataSource_TransitGatewayID
=== PAUSE TestAccAWSRouteDataSource_TransitGatewayID
=== RUN   TestAccAWSRouteDataSource_IPv6DestinationCidr
=== PAUSE TestAccAWSRouteDataSource_IPv6DestinationCidr
=== CONT  TestAccAWSRouteDataSource_TransitGatewayID
=== CONT  TestAccAWSRouteDataSource_basic
--- PASS: TestAccAWSRouteDataSource_basic (131.62s)
=== CONT  TestAccAWSRouteDataSource_IPv6DestinationCidr
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (54.91s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (338.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	338.691s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Rebased to fix merge conflicts.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRouteDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSRouteDataSource_ -timeout 120m
=== RUN   TestAccAWSRouteDataSource_basic
=== PAUSE TestAccAWSRouteDataSource_basic
=== RUN   TestAccAWSRouteDataSource_TransitGatewayID
=== PAUSE TestAccAWSRouteDataSource_TransitGatewayID
=== RUN   TestAccAWSRouteDataSource_IPv6DestinationCidr
=== PAUSE TestAccAWSRouteDataSource_IPv6DestinationCidr
=== CONT  TestAccAWSRouteDataSource_basic
=== CONT  TestAccAWSRouteDataSource_IPv6DestinationCidr
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (31.03s)
=== CONT  TestAccAWSRouteDataSource_TransitGatewayID
--- PASS: TestAccAWSRouteDataSource_basic (137.72s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (336.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	367.721s
```

**Comment by ewbankkit** [comment]
##### TODO

Merge https://github.com/terraform-providers/terraform-provider-aws/pull/14864 and revisit.

**Comment by ewbankkit** [comment]
Rebased and fixed merge conflicts.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRouteDataSource_' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSRouteDataSource_ -timeout 120m
=== RUN   TestAccAWSRouteDataSource_basic
=== PAUSE TestAccAWSRouteDataSource_basic
=== RUN   TestAccAWSRouteDataSource_TransitGatewayID
=== PAUSE TestAccAWSRouteDataSource_TransitGatewayID
=== RUN   TestAccAWSRouteDataSource_IPv6DestinationCidr
=== PAUSE TestAccAWSRouteDataSource_IPv6DestinationCidr
=== RUN   TestAccAWSRouteDataSource_LocalGatewayID
=== PAUSE TestAccAWSRouteDataSource_LocalGatewayID
=== CONT  TestAccAWSRouteDataSource_basic
=== CONT  TestAccAWSRouteDataSource_LocalGatewayID
    data_source_aws_outposts_outposts_test.go:66: skipping since no Outposts Outpost found
=== CONT  TestAccAWSRouteDataSource_IPv6DestinationCidr
=== CONT  TestAccAWSRouteDataSource_LocalGatewayID
--- SKIP: TestAccAWSRouteDataSource_LocalGatewayID (2.23s)
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (27.32s)
=== CONT  TestAccAWSRouteDataSource_TransitGatewayID
--- PASS: TestAccAWSRouteDataSource_basic (119.98s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (276.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	306.551s
```

**Comment by ewbankkit** [comment]
Rebased and fixed merge conflicts.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRouteDataSource_' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSRouteDataSource_ -timeout 120m
=== RUN   TestAccAWSRouteDataSource_basic
=== PAUSE TestAccAWSRouteDataSource_basic
=== RUN   TestAccAWSRouteDataSource_TransitGatewayID
=== PAUSE TestAccAWSRouteDataSource_TransitGatewayID
=== RUN   TestAccAWSRouteDataSource_IPv6DestinationCidr
=== PAUSE TestAccAWSRouteDataSource_IPv6DestinationCidr
=== RUN   TestAccAWSRouteDataSource_LocalGatewayID
=== PAUSE TestAccAWSRouteDataSource_LocalGatewayID
=== CONT  TestAccAWSRouteDataSource_basic
=== CONT  TestAccAWSRouteDataSource_LocalGatewayID
    data_source_aws_outposts_outposts_test.go:66: skipping since no Outposts found
--- SKIP: TestAccAWSRouteDataSource_LocalGatewayID (1.76s)
=== CONT  TestAccAWSRouteDataSource_IPv6DestinationCidr
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (27.25s)
=== CONT  TestAccAWSRouteDataSource_TransitGatewayID
--- PASS: TestAccAWSRouteDataSource_basic (101.36s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (372.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	401.404s
```

**Comment by ewbankkit** [comment]
Rebased and fixed merge conflicts.
Re-ran acceptance tests:

```console
$ make testacc TEST=./aws/ TESTARGS='-run=TestAccAWSRouteDataSource_' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSRouteDataSource_ -timeout 120m
=== RUN   TestAccAWSRouteDataSource_basic
=== PAUSE TestAccAWSRouteDataSource_basic
=== RUN   TestAccAWSRouteDataSource_TransitGatewayID
=== PAUSE TestAccAWSRouteDataSource_TransitGatewayID
=== RUN   TestAccAWSRouteDataSource_IPv6DestinationCidr
=== PAUSE TestAccAWSRouteDataSource_IPv6DestinationCidr
=== RUN   TestAccAWSRouteDataSource_LocalGatewayID
=== PAUSE TestAccAWSRouteDataSource_LocalGatewayID
=== CONT  TestAccAWSRouteDataSource_basic
=== CONT  TestAccAWSRouteDataSource_LocalGatewayID
    data_source_aws_outposts_outposts_test.go:66: skipping since no Outposts found
--- SKIP: TestAccAWSRouteDataSource_LocalGatewayID (1.87s)
=== CONT  TestAccAWSRouteDataSource_IPv6DestinationCidr
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (27.59s)
=== CONT  TestAccAWSRouteDataSource_TransitGatewayID
--- PASS: TestAccAWSRouteDataSource_basic (69.69s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (373.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	402.510s
```

**Review by YakDriver — APPROVED** [review]
Looks great 🎉 

GovCloud:
```
--- SKIP: TestAccAWSRouteDataSource_LocalGatewayID (1.84s)
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (27.36s)
--- PASS: TestAccAWSRouteDataSource_basic (131.31s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (352.35s)
```

`us-west-2`:
```
--- SKIP: TestAccAWSRouteDataSource_LocalGatewayID (1.35s)
--- PASS: TestAccAWSRouteDataSource_IPv6DestinationCidr (24.13s)
--- PASS: TestAccAWSRouteDataSource_TransitGatewayID (296.29s)
--- PASS: TestAccAWSRouteDataSource_basic (312.04s)
```

**Pull request merged**
