### PR TITLE
Add AWS MSK Public Access Support

### LINKED ISSUE #21859: MSK public access feature
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a new API from AWS that enables public connectivity to MSK: https://docs.aws.amazon.com/msk/latest/developerguide/public-access.html

### New or Affected Resource(s)

* aws_msk_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.

resource "aws_msk_cluster" "example" {
  ...
  public_access {
    type = "SERVICE_PROVIDED_EIPS" 
  }
  ...
}

resource "aws_msk_cluster" "example" {
  ...
  public_access {
    type = "DISABLED" 
  }
  ...
}

```

### References

* #0000

### PR DESCRIPTION
**Pull request by nuttmeister**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

## Explanation

Adds support for the new public access feature for aws msk.

This cannot be enabled on cluster creation, but must be enabled once the cluster has been created.

To enable it add the following block to the `broker_node_group_info` block.

```hcl
broker_node_group_info {
  ...
  public_access {
    type = "SERVICE_PROVIDED_EIPS"
  }
}
```

### Issues

Closes #21859 

### Acceptance tests

Output from acceptance testing:

```
make testacc TESTS=TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccess PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccess' -timeout 180m
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIam
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIam
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLScram
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLScram
=== RUN   TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessTLS
=== PAUSE TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessTLS
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIam
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLScram
=== CONT  TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessTLS
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLIam (6117.27s)
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessSASLScram (6117.58s)
--- PASS: TestAccKafkaCluster_BrokerNodeGroupInfo_publicAccessTLS (8831.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	8833.087s

make testacc TESTS=TestAccKafkaClusterDataSource_publicAccess PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaClusterDataSource_publicAccess' -timeout 180m
=== RUN   TestAccKafkaClusterDataSource_publicAccessSASLIam
=== PAUSE TestAccKafkaClusterDataSource_publicAccessSASLIam
=== RUN   TestAccKafkaClusterDataSource_publicAccessSASLScram
=== PAUSE TestAccKafkaClusterDataSource_publicAccessSASLScram
=== RUN   TestAccKafkaClusterDataSource_publicAccessTLS
=== PAUSE TestAccKafkaClusterDataSource_publicAccessTLS
=== CONT  TestAccKafkaClusterDataSource_publicAccessSASLIam
=== CONT  TestAccKafkaClusterDataSource_publicAccessTLS
=== CONT  TestAccKafkaClusterDataSource_publicAccessSASLScram
--- PASS: TestAccKafkaClusterDataSource_publicAccessSASLScram (4200.14s)
--- PASS: TestAccKafkaClusterDataSource_publicAccessSASLIam (4207.97s)
--- PASS: TestAccKafkaClusterDataSource_publicAccessTLS (5831.51s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	5833.062s
```

### CODE REVIEW

**Comment by nuttmeister** [comment]
Depends on `github.com/aws/aws-sdk-go` version `v1.42.10` and above. Waiting for it to be merged into main.

**Comment by nuttmeister** [comment]
aws sdk dependency fixed, will merge in main and finalize this during the coming weekend.

**Comment by nuttmeister** [comment]
Sorry for not doing what I promised to do last weekend. But real life hit and I had to do some extensive traveling. Will sort this out this coming weekend. Cheers.

**Comment by jgrossmac** [comment]
would be awesome to have this 🍒

**Comment by nuttmeister** [comment]
Seems like I totally forgot this PR. I will get to work on it again now that the aws sdk version is up-to-date.

**Comment by ewbankkit** [comment]
@nuttmeister Thanks for the contribution :tada: :clap:.
This work has been rolled into #21005.

**Comment by nuttmeister** [comment]
Thank you @ewbankkit . Sorry for being a bit slow on this, but lots happening here. Cheers

**Pull request closed without merging**
