### PR TITLE
f-aws_networkfirewall_firewall_policy-tlsinspectionpolicyarn-add

### LINKED ISSUE #35078: [Enhancement]: aws_networkfirewall_firewall_policy support for TLSInspectionConfigurationArn
### Description

[TLSInspectionConfigurationArn] Was added to the API.

This support is required as there is a limitation with the API that the policy must be created with the TLS inspection ARN attached as tls inspection cant be attached to existing policies. 

https://docs.aws.amazon.com/network-firewall/latest/developerguide/managing-tls-configuration.html

> You can only add a TLS inspection configuration to a new policy, not to an existing policy. However, you can replace an existing TLS inspection configuration with another TLS inspection configuration in a firewall policy. To add a TLS inspection configuration to a firewall policy or update an existing TLS inspection configuration, see [Managing your firewall policy](https://docs.aws.amazon.com/network-firewall/latest/developerguide/firewall-policy-managing.html).

(https://docs.aws.amazon.com/network-firewall/latest/APIReference/API_FirewallPolicy.html#networkfirewall-Type-FirewallPolicy-TLSInspectionConfigurationArn)": "string"

### Affected Resource(s) and/or Data Source(s)

aws_networkfirewall_firewall_policy

### Potential Terraform Configuration

```terraform
tls_inspection_configuration_arn = $ARN
```

### References

31154

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by bsaurusrex**
### Relations

Closes #35078.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/31154.

### Output from Acceptance Testing

```console
make testacc TESTS=TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationArn PKG=networkfirewall P=19
make testacc TESTS="TestAccNetworkFirewallFirewallPolicyDataSource_*" PKG=networkfirewall P=1

...
```

### CODE REVIEW

**Comment by bsaurusrex** [comment]
make testacc TESTS="TestAccNetworkFirewallFirewallPolicyDataSource_*" PKG=networkfirewall P=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 1 -run='TestAccNetworkFirewallFirewallPolicyDataSource_*'  -timeout 360m
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_arn
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_arn
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_name
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_name
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_withOverriddenManagedRuleGroup
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_withOverriddenManagedRuleGroup
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_arn
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_arn (139.91s)
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN (137.97s)
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_withOverriddenManagedRuleGroup
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_withOverriddenManagedRuleGroup (128.26s)
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_name
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_name (138.80s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall    548.279s

**Comment by bsaurusrex** [comment]
make testacc TESTS=TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationArn PKG=networkfirewall P=19
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 19 -run='TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationArn'  -timeout 360m
=== RUN   TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationArn
--- PASS: TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationArn (159.66s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall    163.334s

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccNetworkFirewallFirewallPolicyDataSource_arn\|TestAccNetworkFirewallFirewallPolicyDataSource_name\|TestAccNetworkFirewallFirewallPolicy_basic\|TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationARN' PKG=networkfirewall ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkfirewall/... -v -count 1 -parallel 2  -run=TestAccNetworkFirewallFirewallPolicyDataSource_arn\|TestAccNetworkFirewallFirewallPolicyDataSource_name\|TestAccNetworkFirewallFirewallPolicy_basic\|TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationARN -timeout 360m
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_arn
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_arn
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_name
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_name
=== RUN   TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN
=== PAUSE TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN
=== RUN   TestAccNetworkFirewallFirewallPolicy_basic
=== PAUSE TestAccNetworkFirewallFirewallPolicy_basic
=== RUN   TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationARN
    acctest.go:2479: Environment variable AWS_NETWORKFIREWALL_TLS_INSPECTION_CONFIGURATION_ARN_1 is not set, skipping test
--- SKIP: TestAccNetworkFirewallFirewallPolicy_tlsInspectionConfigurationARN (0.00s)
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_arn
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_arn (141.27s)
=== CONT  TestAccNetworkFirewallFirewallPolicy_basic
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_nameAndARN (142.52s)
=== CONT  TestAccNetworkFirewallFirewallPolicyDataSource_name
--- PASS: TestAccNetworkFirewallFirewallPolicyDataSource_name (142.75s)
--- PASS: TestAccNetworkFirewallFirewallPolicy_basic (166.96s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkfirewall	321.944s
```

**Comment by ewbankkit** [comment]
@bsaurusrex Thanks for the contribution :tada: :clap:.

**Pull request merged**
