### PR TITLE
Fix for Resource Access Management edge case involving VPC Classic Link

### PR DESCRIPTION
**Pull request by johnbarney**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Fix issue with describing VpcClassicLink on VPC shared by Resource Access Manager by passing WARN
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSVpc_classiclink'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSVpc_classiclink -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSVpc_classiclinkOptionSet
=== PAUSE TestAccAWSVpc_classiclinkOptionSet
=== RUN   TestAccAWSVpc_classiclinkDnsSupportOptionSet
=== PAUSE TestAccAWSVpc_classiclinkDnsSupportOptionSet
=== CONT  TestAccAWSVpc_classiclinkOptionSet
=== CONT  TestAccAWSVpc_classiclinkDnsSupportOptionSet
--- PASS: TestAccAWSVpc_classiclinkOptionSet (83.11s)
--- PASS: TestAccAWSVpc_classiclinkDnsSupportOptionSet (83.12s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	84.138s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.028s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.289s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	0.197s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	0.104s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	0.087s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	0.207s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	0.163s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	0.057s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr	0.031s [no tests to run]

...
```

DescribeVpcClassicLink and DescribeVpcClassicLinkDnsSupport return "InvalidVpcId" if resource is shared via Resource Access Manager from another account. Instead of failing, warn and continue.

### CODE REVIEW

**Comment by ewbankkit** [comment]
@johnbarney Thanks for this. I'm trying to think of a scenario to test.
You create a VPC in 1 account and then RAM share it to the 2nd and in that 2nd account are doing a `terraform import` on the `aws_vpc_resource` when you hit the errors?

**Comment by johnbarney** [comment]
That's similar to the scenario that lead me to find this, yes. I ran terraform apply in one account, then transferred the state file and shared the resources to the child account. Hit this issue during a terraform plan. I suspect terraform import would trigger a similar issue despite me not using it directly.

**Comment by ewbankkit** [comment]
If I create a VPC in one account

```hcl
resource "aws_vpc" "test" {
  cidr_block = "172.2.0.0/16"

  enable_classiclink             = true
  enable_classiclink_dns_support = true
}
```

and share a subnet from that VPC into a second account, from that second account I see:

```console
$ aws --region us-west-2 ec2 describe-vpcs --vpc-ids=vpc-0e52fc1f3433f7d77
{
    "Vpcs": [
        {
            "CidrBlock": "172.2.0.0/16",
            "DhcpOptionsId": "dopt-249eba40",
            "State": "available",
            "VpcId": "vpc-0e52fc1f3433f7d77",
            "OwnerId": "<Account ID of creating account>",
            "InstanceTenancy": "default",
            "CidrBlockAssociationSet": [
                {
                    "AssociationId": "vpc-cidr-assoc-01ab28f3c18e8504d",
                    "CidrBlock": "172.2.0.0/16",
                    "CidrBlockState": {
                        "State": "associated"
                    }
                }
            ],
            "IsDefault": false
        }
    ]
}
$ aws --region us-west-2 ec2 describe-vpc-classic-link --vpc-ids=vpc-0e52fc1f3433f7d77

An error occurred (InvalidVpcID.NotFound) when calling the DescribeVpcClassicLink operation: The vpc ID 'vpc-0e52fc1f3433f7d77' does not exist
$ aws --region us-west-2 ec2 describe-vpc-classic-link-dns-support --vpc-ids=vpc-0e52fc1f3433f7d77
{
    "Vpcs": []
}
```

**Comment by johnbarney** [comment]
This is the same behavior I observed. This happens regardless of the classiclink settings on the VPC.

**Comment by johnbarney** [comment]
I've heard back from internal support. The API responses are working as intended. This change is required to import VPCs/Subnets shared via RAM.

**Comment by rogerhu** [comment]
Ran into this same issue with a share VPC - can we patch soon?

**Pull request merged**
