### PR TITLE
Updated Amazon MQ functionality

### PR DESCRIPTION
**Pull request by lucastetreault**
- Add support for RabbitMQ
- Add support for LDAP Authentication
- Add support for EBS storage type
- Make security groups optional since it will use the default one if omitted

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_mq_broker: Support RabbitMQ, LDAP Authentication and EBS storage.
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSMqBroker'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMqBroker -timeout 120m
=== RUN   TestAccAWSMqBroker_basic
=== PAUSE TestAccAWSMqBroker_basic
=== RUN   TestAccAWSMqBroker_EBS
=== PAUSE TestAccAWSMqBroker_EBS
=== RUN   TestAccAWSMqBroker_basicRabbitMQ
=== PAUSE TestAccAWSMqBroker_basicRabbitMQ
=== RUN   TestAccAWSMqBroker_clusterRabbitMQ
=== PAUSE TestAccAWSMqBroker_clusterRabbitMQ
=== RUN   TestAccAWSMqBroker_ldap
=== PAUSE TestAccAWSMqBroker_ldap
=== RUN   TestAccAWSMqBroker_basicDefaultSecurityGroup
=== PAUSE TestAccAWSMqBroker_basicDefaultSecurityGroup
=== RUN   TestAccAWSMqBroker_allFieldsDefaultVpc
=== PAUSE TestAccAWSMqBroker_allFieldsDefaultVpc
=== RUN   TestAccAWSMqBroker_allFieldsCustomVpc
=== PAUSE TestAccAWSMqBroker_allFieldsCustomVpc
=== RUN   TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== RUN   TestAccAWSMqBroker_updateUsers
=== PAUSE TestAccAWSMqBroker_updateUsers
=== RUN   TestAccAWSMqBroker_updateTags
=== PAUSE TestAccAWSMqBroker_updateTags
=== RUN   TestAccAWSMqBroker_updateSecurityGroup
=== PAUSE TestAccAWSMqBroker_updateSecurityGroup
=== RUN   TestAccAWSMqBroker_disappears
=== PAUSE TestAccAWSMqBroker_disappears
=== CONT  TestAccAWSMqBroker_basic
=== CONT  TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== CONT  TestAccAWSMqBroker_updateSecurityGroup
=== CONT  TestAccAWSMqBroker_ldap
=== CONT  TestAccAWSMqBroker_basicDefaultSecurityGroup
=== CONT  TestAccAWSMqBroker_basicRabbitMQ
=== CONT  TestAccAWSMqBroker_allFieldsDefaultVpc
=== CONT  TestAccAWSMqBroker_clusterRabbitMQ
=== CONT  TestAccAWSMqBroker_allFieldsCustomVpc
=== CONT  TestAccAWSMqBroker_updateTags
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== CONT  TestAccAWSMqBroker_updateUsers
=== CONT  TestAccAWSMqBroker_disappears
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== CONT  TestAccAWSMqBroker_EBS
2020/11/17 13:28:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2020/11/17 13:28:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2020/11/17 13:28:50 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
2020/11/17 13:28:53 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
--- PASS: TestAccAWSMqBroker_basicRabbitMQ (628.99s)
--- PASS: TestAccAWSMqBroker_clusterRabbitMQ (734.59s)
2020/11/17 13:41:31 [WARN] Truncating attribute path of 0 diagnostics for TypeSet
--- PASS: TestAccAWSMqBroker_EBS (835.84s)
--- PASS: TestAccAWSMqBroker_basicDefaultSecurityGroup (1114.85s)
--- PASS: TestAccAWSMqBroker_disappears (1151.17s)
--- PASS: TestAccAWSMqBroker_ldap (1172.08s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1182.22s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1205.41s)
--- PASS: TestAccAWSMqBroker_basic (1213.00s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1253.00s)
--- PASS: TestAccAWSMqBroker_updateTags (1271.10s)
--- PASS: TestAccAWSMqBroker_updateUsers (1445.56s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1452.81s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (1867.78s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (1882.72s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1886.075s


...
```

### CODE REVIEW

**Comment by lucastetreault** [comment]
I didn't actually look for open issues or PRs before starting work on this... just got bored on the weekend and didn't see these features. Looks like there's another PR for the RabbitMQ engine type [#16108](https://github.com/hashicorp/terraform-provider-aws/issues/16108) and another for the EBS storage type [#11325](https://github.com/hashicorp/terraform-provider-aws/issues/11325)

**Comment by yardensachs** [comment]
@lucastetreault Once they merge the PR, you can pull and update

**Review by grigorov — APPROVED** [review]

**Comment by YakDriver** [comment]
@lucastetreault Thank you for this PR! We have performed significant reworking in #16108, which has been merged. While some of the same features were merged with that PR, you have **excellent acceptance tests** we'd love to be able to merge. If you have a chance, please rebase and give the code a once over to see if there are additional improvements.

**Review by YakDriver — APPROVED** [review]
Looks great! Thank you.

Acceptance tests on commercial partition (`us-west-2`):
```
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (1587.35s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (1649.70s)
--- PASS: TestAccAWSMqBroker_basic (1098.21s)
--- PASS: TestAccAWSMqBroker_clusterRabbitMQ (698.27s)
--- PASS: TestAccAWSMqBroker_disappears (1176.88s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1099.69s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1091.11s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1091.33s)
--- PASS: TestAccAWSMqBroker_ldap (1096.64s)
--- PASS: TestAccAWSMqBroker_rabbitmq (577.41s)
--- PASS: TestAccAWSMqBroker_tags (1109.23s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (627.94s)
--- PASS: TestAccAWSMqBroker_updateEngineVersion (1188.06s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1189.04s)
--- PASS: TestAccAWSMqBroker_updateUsers (1191.79s)
```

**Comment by YakDriver** [comment]
Note: I added a note to the documentation also but for future travelers, I'll explain more here. After trying both `UpdateBroker` and `ForceNew`, I could not get AWS to update LDAP server metadata information. Hopefully they will patch the issue and all will work as it should. In the meantime, you may or may not be able to change any LDAP server metadata for an MQ broker. The specific field I attempt to change was `ldap_server_metadata.service_account_username`.

**Pull request merged**
