### PR TITLE
Fix aws_iam_policy_document order

### LINKED ISSUE #22274: Order lost in `aws_iam_role` causing endless plan updates due to ordering of principals in `aws_iam_policy_document`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v1.1.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/archive v2.2.0
+ provider registry.terraform.io/hashicorp/aws v3.70.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* aws_iam_policy_document

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

locals {
  ingress_account_list = [
    "XXXXXXXXXXXX",
    "YYYYYYYYYYYY",
    "XXXXXXXXXXXX",
  ]
}

data "aws_iam_policy_document" "workspace_ingress_role_trust" {
  statement {
    actions = ["sts:AssumeRole"]
    principals {
      identifiers = formatlist("arn:aws:iam::%s:root", local.ingress_account_list)
      type        = "AWS"
    }
  }
}

resource "aws_iam_role" "workspace_ingress" {
  name               = "aws_amp_ingest_role"
  assume_role_policy = data.aws_iam_policy_document.workspace_ingress_role_trust.json
}

output "workspace_ingress_role" {
  sensitive = false
  value     = aws_iam_role.workspace_ingress
}
```

### Expected Behavior

When running multiple plans with no changes to the terraform code terraform should detect no changes
### Actual Behavior

When running multiple plans the outputs are updated on every plan due to reordering of the principals

### Steps to Reproduce

1. `terraform plan`
2. `terraform apply`
3. `terraform plan`

### References

* #11801
* #21016
* #22259

### PR DESCRIPTION
**Pull request by Synohara**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22274

Output from acceptance testing(us-west-2):

```
$ make testacc TESTS=TestAccIAMRole_basic PKG=iam
=== RUN   TestAccIAMRole_basic
=== PAUSE TestAccIAMRole_basic
=== RUN   TestAccIAMRole_basicWithDescription
=== PAUSE TestAccIAMRole_basicWithDescription
=== CONT  TestAccIAMRole_basicWithDescription
=== CONT  TestAccIAMRole_basic
--- PASS: TestAccIAMRole_basic (38.51s)
--- PASS: TestAccIAMRole_basicWithDescription (89.66s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iam        104.877s
```

### CODE REVIEW

**Comment by imaginarynik** [comment]
@justinretzolk  Could you please provide an update as to when will this be merged?!

**Comment by justinretzolk** [comment]
Hey @imaginarynik 👋 Thank you for checking in on this. Unfortunately, I'm not able to provide an estimate on when this will be merged due to the potential of shifting priorities. We prioritize work by count of ":+1:" reactions, as well as a few other things. A larger prioritization document is in the works, but in the meantime additional information may be found in the [FAQ](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/faq.md#why-isnt-my-pr-merged-yet).

**Comment by jw-maynard** [comment]
@justinretzolk This being de-prioritized seem a little odd to me since this prevents Terraform from converging on a stable state. Reporting that an apply is needed when the IaC matches the infrastructure that's deployed seems like the antithesis of what Terraform aims to accomplish. It seems like this should be a pretty high priority for the team no matter how many or how few thumbs up requests are there.

If you need a direct example, I have a workspace in Terraform cloud impacted by this and I cannot easily look at the Run history and determine when the infrastructure was *actually* changed because every plan creates a "update" that needs is applied. Every run looks like a change. In addition, I can't run a refresh only plan to easily spot differences between the infra and the IaC because *every* refresh plan indicates things have been changed due to this bug.

**Comment by justinretzolk** [comment]
Hey @jw-maynard (and everyone else) -- apologies for the bit of delay in getting back to you on this one. I wanted to wait until I had a bit of a firmer idea of next steps here before replying so that I could get you the best information possible. We are currently working on Q2 prioritization, and based on that planning, I'm fairly confident in saying that this one will be included in that roadmap.

To whomever picks this up for review, I believe #6107 would be closed by this as well. Not linking in the "Closed by" yet, in case my read is off.

**Comment by imaginarynik** [comment]
@justinretzolk thank you so much for the confirmation. I was wondering when would the Q2 be? Estimate?

**Comment by justinretzolk** [comment]
@imaginarynik 👋 While I can't comment on exactly when it'll be reviewed and merged during the quarter, we've entered Q2 as of this week 🙂.

**Comment by imaginarynik** [comment]
@justinretzolk that is such a relief! THANK YOU SO MUCH! :)

**Comment by justinretzolk** [comment]
As a quick update: now that it's published, I can confirm that this is [on the roadmap](https://github.com/hashicorp/terraform-provider-aws/blob/main/ROADMAP.md) for this quarter 🎉

**Review by YakDriver — APPROVED** [review]
LGTM! 🎉 

```console
% make testacc TESTS=TestAccIAMRole_ PKG=iam
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iam/... -v -count 1 -parallel 20 -run='TestAccIAMRole_'  -timeout 180m
=== CONT  TestAccIAMRole_basic
=== CONT  TestAccIAMRole_InlinePolicy_ignoreOrder
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionRemoved
=== CONT  TestAccIAMRole_disappears
=== CONT  TestAccIAMRole_InlinePolicy_basic
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemoved
=== CONT  TestAccIAMRole_nameGenerated
=== CONT  TestAccIAMRole_InlinePolicy_empty
=== CONT  TestAccIAMRole_tags
=== CONT  TestAccIAMRole_description
=== CONT  TestAccIAMRole_namePrefix
=== CONT  TestAccIAMRole_badJSON
=== CONT  TestAccIAMRole_testNameChange
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack
=== CONT  TestAccIAMRole_permissionsBoundary
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandRemovalAddedBack
=== CONT  TestAccIAMRole_ManagedPolicy_basic
=== CONT  TestAccIAMRole_maxSessionDuration
=== CONT  TestAccIAMRole_policiesForceDetach
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty
--- PASS: TestAccIAMRole_badJSON (15.10s)
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemovedEmpty
--- PASS: TestAccIAMRole_disappears (80.53s)
=== CONT  TestAccIAMRole_ManagedPolicy_outOfBandAdditionIgnored
--- PASS: TestAccIAMRole_InlinePolicy_empty (95.19s)
=== CONT  TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored
--- PASS: TestAccIAMRole_namePrefix (113.21s)
--- PASS: TestAccIAMRole_policiesForceDetach (113.56s)
--- PASS: TestAccIAMRole_nameGenerated (113.62s)
--- PASS: TestAccIAMRole_basic (125.61s)
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandRemovalAddedBack (171.36s)
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandRemovalAddedBack (171.90s)
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemovedEmpty (166.31s)
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandAdditionRemovedEmpty (181.83s)
--- PASS: TestAccIAMRole_tags (181.95s)
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandAdditionRemoved (182.24s)
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandAdditionRemoved (182.26s)
--- PASS: TestAccIAMRole_testNameChange (182.55s)
--- PASS: TestAccIAMRole_maxSessionDuration (195.78s)
--- PASS: TestAccIAMRole_ManagedPolicy_outOfBandAdditionIgnored (126.67s)
--- PASS: TestAccIAMRole_InlinePolicy_ignoreOrder (212.51s)
--- PASS: TestAccIAMRole_InlinePolicy_basic (213.57s)
--- PASS: TestAccIAMRole_description (217.49s)
--- PASS: TestAccIAMRole_ManagedPolicy_basic (223.60s)
--- PASS: TestAccIAMRole_InlinePolicy_outOfBandAdditionIgnored (137.41s)
--- PASS: TestAccIAMRole_permissionsBoundary (270.60s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iam	272.739s
```

**Pull request merged**
