### PR TITLE
fix KMS name validation check

### LINKED ISSUE #12891: aws_kms_alias API ValidationException
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.12.24

### Affected Resource(s)

provider.aws v2.58.0

### Terraform Configuration Files

```hcl
resource "aws_kms_alias" "example" {
  name          = "alias/Service.Test"
  target_key_id = aws_kms_key.a.key_id
}


# Error: "name" must begin with 'alias/' and be comprised of only [a-zA-Z0-9:/_-]


resource "aws_kms_alias" "another_ example" {
  name          = "alias/Service:Test"
  target_key_id = aws_kms.another.key_id
}

# Error: ValidationException: alias/Service:Test contains invalid characters for an alias status code: 400
```

### Expected Behavior

Terraform validation should be congruent to AWS API validation.

### Actual Behavior

The validation seems to allow characters which are rejected by API.

_I'm creating this issue mainly as a reminder for me to fix this and submit a PR :-)_

### PR DESCRIPTION
**Pull request by drexler**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12891

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
fix KMS name validation check
```

Output from acceptance testing:

```
$  make testacc TEST=./aws TESTARGS='-run=TestValidateAwsKmsName'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestValidateAwsKmsName -timeout 120m
=== RUN   TestValidateAwsKmsName
--- PASS: TestValidateAwsKmsName (0.00s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	0.069s

...
```

### CODE REVIEW

**Comment by anGie44** [comment]
Output of acceptance tests:
```
--- PASS: TestAccKMSAliasDataSource_awsService (15.30s)
--- PASS: TestAccKMSAlias_disappears (20.19s)
--- PASS: TestAccKMSAliasDataSource_cmk (20.68s)
--- PASS: TestAccKMSAlias_basic (22.71s)
--- PASS: TestAccKMSAlias_namePrefix (22.99s)
--- PASS: TestAccKMSAlias_Name_generated (23.00s)
--- PASS: TestAccKMSAlias_multipleAliasesForSameKey (23.09s)
--- PASS: TestAccKMSAlias_arnDiffSuppress (30.79s)
--- PASS: TestAccKMSAlias_updateKeyID (35.19s)

--- PASS: TestValidNameForResource (0.00s)

```

**Review by anGie44 — APPROVED** [review]
Thanks for this contribution @drexler , LGTM 🚀

**Comment by ArchiFleKs** [comment]
I think the PR checks against `alias/aws` and not `alias/aws/` I have a KMS key : 

```
│ Error: "name" cannot begin with reserved AWS CMK prefix 'alias/aws'
│ 
│   with aws_kms_alias.aws-ebs-csi-driver[0],
│   on aws-ebs-csi-driver.tf line 212, in resource "aws_kms_alias" "aws-ebs-csi-driver":
│  212:   name          = "alias/aws-ebs-csi-driver-${local.aws-ebs-csi-driver.override_kms_alias != null ? local.aws-ebs-csi-driver.override_kms_alias : var.cluster-name}"
```

Which failed. Is the AWS API enforce `alias/aws/*` or `alias/aws*`

**Comment by anGie44** [comment]
Hi @ArchiFleKs , thanks for commenting here! The API enforces `alias/aws/*` , though I could of sworn i read in the docs yesterday it was `alias/aws*`. Apologies for the regression. Will add a PR shortly to address this.

**Comment by anGie44** [comment]
@ArchiFleKs , just wanted to let you know the fix was released recently in `v4.12.1`

**Pull request merged**
