### PR TITLE
aws_iam_role name_prefix size

### PR DESCRIPTION
**Pull request by caiodelgadonew**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This PR aims to increase the `name_prefix` size of `aws_iam_role` to 64 characters as described as a maximum of the [documentation](https://docs.aws.amazon.com/IAM/latest/APIReference/API_CreateRole.html)

Right now we have 26 characters being randomly generated for `name_prefix` that gives us just 6 characters to work.

There's 2 possible solutions:
1. Increase the size of `name_prefix` to 64 characters.
2. Add the limit info into the documentation

### CODE REVIEW

**Comment by caiodelgadonew** [comment]
For hashicorp mantainers:

We can either adopt solution 1 or 2.

Just let me know and I can change the values of it based on whatever you think is best, right now the PR has both solutions so it need to be changed.

**Comment by caiodelgadonew** [comment]
@breathingdust , what do you think about it? Can we change to 64 characters or should we just add the description of the character limit?

**Comment by ewbankkit** [comment]
@caiodelgadonew Thanks for working on this.
You should be able to use a range of 1 to 64 - resource.UniqueIDSuffixLength for the `name_prefix` length.

**Comment by caiodelgadonew** [comment]
Hello @ewbankkit   , I've just set the modifications expected, could you please verify it to merge?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTARGS='-run=TestAccAWSIAMRole_\|TestAccAWSDataSourceIAMSessionContext_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSIAMRole_\|TestAccAWSDataSourceIAMSessionContext_ -timeout 180m
=== RUN   TestAccAWSDataSourceIAMSessionContext_basic
=== PAUSE TestAccAWSDataSourceIAMSessionContext_basic
=== RUN   TestAccAWSDataSourceIAMSessionContext_withPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_withPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== RUN   TestAccAWSIAMRole_basic
=== PAUSE TestAccAWSIAMRole_basic
=== RUN   TestAccAWSIAMRole_basicWithDescription
=== PAUSE TestAccAWSIAMRole_basicWithDescription
=== RUN   TestAccAWSIAMRole_NameGenerated
=== PAUSE TestAccAWSIAMRole_NameGenerated
=== RUN   TestAccAWSIAMRole_NamePrefix
=== PAUSE TestAccAWSIAMRole_NamePrefix
=== RUN   TestAccAWSIAMRole_testNameChange
=== PAUSE TestAccAWSIAMRole_testNameChange
=== RUN   TestAccAWSIAMRole_badJSON
=== PAUSE TestAccAWSIAMRole_badJSON
=== RUN   TestAccAWSIAMRole_disappears
=== PAUSE TestAccAWSIAMRole_disappears
=== RUN   TestAccAWSIAMRole_force_detach_policies
=== PAUSE TestAccAWSIAMRole_force_detach_policies
=== RUN   TestAccAWSIAMRole_MaxSessionDuration
=== PAUSE TestAccAWSIAMRole_MaxSessionDuration
=== RUN   TestAccAWSIAMRole_PermissionsBoundary
=== PAUSE TestAccAWSIAMRole_PermissionsBoundary
=== RUN   TestAccAWSIAMRole_tags
=== PAUSE TestAccAWSIAMRole_tags
=== RUN   TestAccAWSIAMRole_policyBasicInline
=== PAUSE TestAccAWSIAMRole_policyBasicInline
=== RUN   TestAccAWSIAMRole_policyBasicInlineEmpty
=== PAUSE TestAccAWSIAMRole_policyBasicInlineEmpty
=== RUN   TestAccAWSIAMRole_policyBasicManaged
=== PAUSE TestAccAWSIAMRole_policyBasicManaged
=== RUN   TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty
=== CONT  TestAccAWSDataSourceIAMSessionContext_basic
=== CONT  TestAccAWSIAMRole_PermissionsBoundary
=== CONT  TestAccAWSIAMRole_NameGenerated
=== CONT  TestAccAWSIAMRole_basicWithDescription
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty
=== CONT  TestAccAWSIAMRole_policyBasicInlineEmpty
=== CONT  TestAccAWSIAMRole_policyBasicInline
=== CONT  TestAccAWSIAMRole_tags
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent
=== CONT  TestAccAWSIAMRole_policyBasicManaged
=== CONT  TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty
=== CONT  TestAccAWSIAMRole_disappears
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== CONT  TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (28.70s)
=== CONT  TestAccAWSIAMRole_MaxSessionDuration
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (31.85s)
=== CONT  TestAccAWSIAMRole_badJSON
--- PASS: TestAccAWSIAMRole_disappears (34.54s)
=== CONT  TestAccAWSIAMRole_testNameChange
--- PASS: TestAccAWSIAMRole_policyBasicInlineEmpty (35.79s)
=== CONT  TestAccAWSIAMRole_NamePrefix
--- PASS: TestAccAWSIAMRole_badJSON (6.54s)
=== CONT  TestAccAWSDataSourceIAMSessionContext_withPath
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (38.80s)
=== CONT  TestAccAWSIAMRole_force_detach_policies
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (38.81s)
=== CONT  TestAccAWSIAMRole_basic
--- PASS: TestAccAWSIAMRole_NameGenerated (45.44s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent (61.31s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty (68.60s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty (69.57s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty (70.44s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty (70.88s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty (71.39s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty (72.68s)
--- PASS: TestAccAWSIAMRole_tags (74.00s)
--- PASS: TestAccAWSIAMRole_NamePrefix (38.57s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (36.03s)
--- PASS: TestAccAWSIAMRole_basic (35.82s)
--- PASS: TestAccAWSIAMRole_force_detach_policies (38.18s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent (81.10s)
--- PASS: TestAccAWSIAMRole_basicWithDescription (86.73s)
--- PASS: TestAccAWSIAMRole_policyBasicManaged (88.46s)
--- PASS: TestAccAWSIAMRole_policyBasicInline (89.03s)
--- PASS: TestAccAWSIAMRole_testNameChange (54.89s)
--- PASS: TestAccAWSIAMRole_MaxSessionDuration (61.48s)
--- PASS: TestAccAWSIAMRole_PermissionsBoundary (105.29s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	108.464s
```

##### GovCloud

```console
% make testacc TESTARGS='-run=TestAccAWSIAMRole_\|TestAccAWSDataSourceIAMSessionContext_' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSIAMRole_\|TestAccAWSDataSourceIAMSessionContext_ -timeout 180m
=== RUN   TestAccAWSDataSourceIAMSessionContext_basic
=== PAUSE TestAccAWSDataSourceIAMSessionContext_basic
=== RUN   TestAccAWSDataSourceIAMSessionContext_withPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_withPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRole
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
=== RUN   TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== PAUSE TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== RUN   TestAccAWSIAMRole_basic
=== PAUSE TestAccAWSIAMRole_basic
=== RUN   TestAccAWSIAMRole_basicWithDescription
=== PAUSE TestAccAWSIAMRole_basicWithDescription
=== RUN   TestAccAWSIAMRole_NameGenerated
=== PAUSE TestAccAWSIAMRole_NameGenerated
=== RUN   TestAccAWSIAMRole_NamePrefix
=== PAUSE TestAccAWSIAMRole_NamePrefix
=== RUN   TestAccAWSIAMRole_testNameChange
=== PAUSE TestAccAWSIAMRole_testNameChange
=== RUN   TestAccAWSIAMRole_badJSON
=== PAUSE TestAccAWSIAMRole_badJSON
=== RUN   TestAccAWSIAMRole_disappears
=== PAUSE TestAccAWSIAMRole_disappears
=== RUN   TestAccAWSIAMRole_force_detach_policies
=== PAUSE TestAccAWSIAMRole_force_detach_policies
=== RUN   TestAccAWSIAMRole_MaxSessionDuration
=== PAUSE TestAccAWSIAMRole_MaxSessionDuration
=== RUN   TestAccAWSIAMRole_PermissionsBoundary
=== PAUSE TestAccAWSIAMRole_PermissionsBoundary
=== RUN   TestAccAWSIAMRole_tags
=== PAUSE TestAccAWSIAMRole_tags
=== RUN   TestAccAWSIAMRole_policyBasicInline
=== PAUSE TestAccAWSIAMRole_policyBasicInline
=== RUN   TestAccAWSIAMRole_policyBasicInlineEmpty
=== PAUSE TestAccAWSIAMRole_policyBasicInlineEmpty
=== RUN   TestAccAWSIAMRole_policyBasicManaged
=== PAUSE TestAccAWSIAMRole_policyBasicManaged
=== RUN   TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty
=== RUN   TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty
=== PAUSE TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty
=== CONT  TestAccAWSDataSourceIAMSessionContext_basic
=== CONT  TestAccAWSIAMRole_PermissionsBoundary
=== CONT  TestAccAWSIAMRole_policyBasicManaged
=== CONT  TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent
=== CONT  TestAccAWSIAMRole_policyBasicInline
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty
=== CONT  TestAccAWSIAMRole_tags
=== CONT  TestAccAWSIAMRole_NameGenerated
=== CONT  TestAccAWSIAMRole_MaxSessionDuration
=== CONT  TestAccAWSIAMRole_force_detach_policies
=== CONT  TestAccAWSIAMRole_disappears
=== CONT  TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty
=== CONT  TestAccAWSIAMRole_badJSON
=== CONT  TestAccAWSIAMRole_testNameChange
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser
=== CONT  TestAccAWSIAMRole_policyBasicInlineEmpty
--- PASS: TestAccAWSIAMRole_badJSON (9.94s)
=== CONT  TestAccAWSIAMRole_NamePrefix
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleUser (28.70s)
=== CONT  TestAccAWSIAMRole_basicWithDescription
--- PASS: TestAccAWSIAMRole_disappears (35.27s)
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRole
--- PASS: TestAccAWSIAMRole_policyBasicInlineEmpty (43.57s)
=== CONT  TestAccAWSIAMRole_basic
--- PASS: TestAccAWSDataSourceIAMSessionContext_basic (43.88s)
=== CONT  TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath
--- PASS: TestAccAWSIAMRole_NameGenerated (48.44s)
=== CONT  TestAccAWSDataSourceIAMSessionContext_withPath
--- PASS: TestAccAWSIAMRole_NamePrefix (39.97s)
=== CONT  TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty
--- PASS: TestAccAWSIAMRole_force_detach_policies (54.26s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_managedNonExistent (61.96s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRole (32.92s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineEmpty (74.61s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedEmpty (75.18s)
--- PASS: TestAccAWSIAMRole_tags (76.02s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_notAssumedRoleWithPath (32.31s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_inlineNonEmpty (76.70s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_inlineNonEmpty (77.17s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionRemoved_managedNonEmpty (78.53s)
--- PASS: TestAccAWSIAMRole_MaxSessionDuration (80.01s)
--- PASS: TestAccAWSDataSourceIAMSessionContext_withPath (32.31s)
--- PASS: TestAccAWSIAMRole_basic (37.82s)
--- PASS: TestAccAWSIAMRole_testNameChange (82.19s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandAdditionIgnored_inlineNonExistent (86.72s)
--- PASS: TestAccAWSIAMRole_policyBasicInline (99.18s)
--- PASS: TestAccAWSIAMRole_policyBasicManaged (99.43s)
--- PASS: TestAccAWSIAMRole_policyOutOfBandRemovalAddedBack_managedNonEmpty (51.05s)
--- PASS: TestAccAWSIAMRole_basicWithDescription (72.86s)
--- PASS: TestAccAWSIAMRole_PermissionsBoundary (118.23s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	121.414s
```

**Comment by ewbankkit** [comment]
@caiodelgadonew Thanks for the contribution :tada: :clap:.
I included changes from #12436 and #19532.

**Pull request merged**
