### PR TITLE
Feature/ds key pair 

### LINKED ISSUE #15590: Add a data source for aws_key_pair
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add a data source to find EC2 key pairs by name.

### New or Affected Resource(s)

* aws_key_pair

### Potential Terraform Configuration

```hcl
data "aws_key_pair" "my_key_pair" {
  name = "my_key_pair"
}

resource "aws_launch_configuration" "example" {
  key_name = data.aws_key_pair.my_key_pair.name
  ...
}
```

### PR DESCRIPTION
**Pull request by pkruk**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15590 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
☁  terraform-provider-aws [feature/ds_key_pair] ⚡  AWS_PROFILE=default make testacc TESTARGS='-run=TestAccDataSourceAwsKeyPair_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsKeyPair_basic -timeout 120m

=== RUN   TestAccDataSourceAwsKeyPair_basic
=== PAUSE TestAccDataSourceAwsKeyPair_basic
=== CONT  TestAccDataSourceAwsKeyPair_basic
--- PASS: TestAccDataSourceAwsKeyPair_basic (35.10s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       37.831s
...
```

This is my first PR here, I will be very happy for feedback and if you spot anything missing in PR :)

### CODE REVIEW

**Comment by andrzej-jedrzejewski** [comment]
When this will be merged and released?

**Comment by andrzej-jedrzejewski** [comment]
merge and release, please :)

**Comment by evandam** [comment]
Hey folks, anything holding this PR back? Seems like it's ready to go and would be helpful!

**Comment by bneigher** [comment]
looking forward to this!

**Comment by fabriciomariani** [comment]
Is there anything blockthing this from getting released? Seems like everything is ready to go

**Comment by pkruk** [comment]
Hi,
Any chance to get it merged :)? There is anything I can do ?

**Comment by mboogerd** [comment]
Code makes sense, documentation and tests are provided. All automated lights are green. Could we get this small but useful feature merged, or an ETA on when it'll be looked into? Thanks in advance :)

**Comment by alexbricepalo** [comment]
Whats the holdup here?

**Comment by mbainter** [comment]
See the [contributions file](https://github.com/hashicorp/terraform/blob/main/.github/CONTRIBUTING.md), specifically:

> Note: Due to current low staffing on the Terraform Core team at HashiCorp, we are not routinely reviewing and merging community-submitted pull requests. We do hope to begin processing them again soon once we're back up to full staffing again, but for the moment we need to ask for patience. Thanks!

**Comment by justinretzolk** [comment]
Hi all :wave: Thank you all for your patience here. We use the ":+1:" reactions on a given issue/pull request in order to aid in prioritizing community contributions (thank you to everyone who has reacted to this one so far!). While I can't promise any sort of timeline for review/merge, the team is aware of this pull request, and will work on it as soon as time permits. Please keep adding ":+1:" if this pull request would help you; the more votes it receives, the more likely it is that it will be included in an upcoming release.

I'd be remiss if I didn't mention the quote that @mbainter provided. That update applies only to Terraform Core, not the separate provider repositories. We are still reviewing and accepting community contributions to the individual providers, including the AWS provider.

**Comment by pkruk** [comment]
I just resolved the merge conflict, so we will have a clean state for merging ;)

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2KeyPair_\|TestAccEC2KeyPairDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2KeyPair_\|TestAccEC2KeyPairDataSource_ -timeout 180m
=== RUN   TestAccEC2KeyPairDataSource_basic
=== PAUSE TestAccEC2KeyPairDataSource_basic
=== RUN   TestAccEC2KeyPair_basic
=== PAUSE TestAccEC2KeyPair_basic
=== RUN   TestAccEC2KeyPair_tags
=== PAUSE TestAccEC2KeyPair_tags
=== RUN   TestAccEC2KeyPair_nameGenerated
=== PAUSE TestAccEC2KeyPair_nameGenerated
=== RUN   TestAccEC2KeyPair_namePrefix
=== PAUSE TestAccEC2KeyPair_namePrefix
=== RUN   TestAccEC2KeyPair_disappears
=== PAUSE TestAccEC2KeyPair_disappears
=== CONT  TestAccEC2KeyPairDataSource_basic
=== CONT  TestAccEC2KeyPair_nameGenerated
=== CONT  TestAccEC2KeyPair_disappears
=== CONT  TestAccEC2KeyPair_namePrefix
=== CONT  TestAccEC2KeyPair_tags
=== CONT  TestAccEC2KeyPair_basic
--- PASS: TestAccEC2KeyPair_disappears (13.90s)
--- PASS: TestAccEC2KeyPairDataSource_basic (16.08s)
--- PASS: TestAccEC2KeyPair_basic (16.57s)
--- PASS: TestAccEC2KeyPair_namePrefix (18.78s)
--- PASS: TestAccEC2KeyPair_nameGenerated (18.93s)
--- PASS: TestAccEC2KeyPair_tags (39.36s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	43.226s
```

##### GovCloud

```console
% make testacc PKG_NAME=internal/service/ec2 TESTARGS='-run=TestAccEC2KeyPair_\|TestAccEC2KeyPairDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run=TestAccEC2KeyPair_\|TestAccEC2KeyPairDataSource_ -timeout 180m
=== RUN   TestAccEC2KeyPairDataSource_basic
=== PAUSE TestAccEC2KeyPairDataSource_basic
=== RUN   TestAccEC2KeyPair_basic
=== PAUSE TestAccEC2KeyPair_basic
=== RUN   TestAccEC2KeyPair_tags
=== PAUSE TestAccEC2KeyPair_tags
=== RUN   TestAccEC2KeyPair_nameGenerated
=== PAUSE TestAccEC2KeyPair_nameGenerated
=== RUN   TestAccEC2KeyPair_namePrefix
=== PAUSE TestAccEC2KeyPair_namePrefix
=== RUN   TestAccEC2KeyPair_disappears
=== PAUSE TestAccEC2KeyPair_disappears
=== CONT  TestAccEC2KeyPairDataSource_basic
=== CONT  TestAccEC2KeyPair_namePrefix
=== CONT  TestAccEC2KeyPair_tags
=== CONT  TestAccEC2KeyPair_basic
=== CONT  TestAccEC2KeyPair_disappears
=== CONT  TestAccEC2KeyPair_nameGenerated
--- PASS: TestAccEC2KeyPair_disappears (18.06s)
--- PASS: TestAccEC2KeyPairDataSource_basic (20.76s)
--- PASS: TestAccEC2KeyPair_nameGenerated (23.55s)
--- PASS: TestAccEC2KeyPair_basic (23.58s)
--- PASS: TestAccEC2KeyPair_namePrefix (23.63s)
--- PASS: TestAccEC2KeyPair_tags (49.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	53.100s
```

**Comment by ewbankkit** [comment]
@pkruk Thanks for the contribution :tada: :clap:.

**Pull request merged**
