### PR TITLE
Adds check for duplicate buckets and throws error if needed

### LINKED ISSUE #6490: Terraform does not error if an S3 bucket already exists
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
terraform-provider-aws v1.45.0
```

### Affected Resource(s)

`aws_s3_bucket`

### Terraform Configuration Files

```hcl
resource "aws_s3_bucket" "bucket" {
  bucket = "bucket-name-that-already-exists"
  acl    = "private"
}
```

### Expected Behavior

`Error: S3 bucket with name "bucket-name-that-already-exists" already exists`

### Actual Behavior

Upon plan/apply, Terraform acts as if it created the resource and begins managing it in state, leaving the bucket under two different Terraform configurations management/state files.

### Steps to Reproduce

Define two resources with the same bucket name.  Can be in the same Terraform configuration or different ones.

### Important Factoids

We keep all SDLC environments in separate Terraform workspaces.  When develops work locally, they get a workspace with the name of their git branch.  This was discovered by a developer copy/pasting the name of an existing bucket while testing into a resource within their branch that already existed.

After that we were able to confirm if we simply copy/paste the resource N times and change the resource name (but not the bucket name), they all create successfully.

### PR DESCRIPTION
**Pull request by GBrawl**
Fixes #6490 

When trying to create a bucket that already exists the response doesn't give an error, that's why I added an extra check to see if it is already there.

There is still one acceptance test failing, but I don't think it is because of these changes

Changes proposed in this pull request:

* Performs a HEAD request to check if a bucket already exists before creating it
* Adds a lock so only one bucket can be created at a time, because otherwise terraform won't fail when creating two s3 bucket resources with the same name at the same time

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccAWSS3Bucket'              
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -parallel 20 -run=TestAccAWSS3Bucket -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSS3BucketInventory_basic
=== PAUSE TestAccAWSS3BucketInventory_basic
=== RUN   TestAccAWSS3BucketInventory_encryptWithSSES3
=== PAUSE TestAccAWSS3BucketInventory_encryptWithSSES3
=== RUN   TestAccAWSS3BucketInventory_encryptWithSSEKMS
=== PAUSE TestAccAWSS3BucketInventory_encryptWithSSEKMS
=== RUN   TestAccAWSS3BucketMetric_basic
=== PAUSE TestAccAWSS3BucketMetric_basic
=== RUN   TestAccAWSS3BucketMetric_WithFilterPrefix
=== PAUSE TestAccAWSS3BucketMetric_WithFilterPrefix
=== RUN   TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags
=== PAUSE TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags
=== RUN   TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag
=== PAUSE TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag
=== RUN   TestAccAWSS3BucketMetric_WithFilterMultipleTags
=== PAUSE TestAccAWSS3BucketMetric_WithFilterMultipleTags
=== RUN   TestAccAWSS3BucketMetric_WithFilterSingleTag
=== PAUSE TestAccAWSS3BucketMetric_WithFilterSingleTag
=== RUN   TestAccAWSS3BucketNotification_importBasic
--- PASS: TestAccAWSS3BucketNotification_importBasic (218.10s)
=== RUN   TestAccAWSS3BucketNotification_basic
=== PAUSE TestAccAWSS3BucketNotification_basic
=== RUN   TestAccAWSS3BucketNotification_withoutFilter
=== PAUSE TestAccAWSS3BucketNotification_withoutFilter
=== RUN   TestAccAWSS3BucketObject_source
=== PAUSE TestAccAWSS3BucketObject_source
=== RUN   TestAccAWSS3BucketObject_content
=== PAUSE TestAccAWSS3BucketObject_content
=== RUN   TestAccAWSS3BucketObject_contentBase64
=== PAUSE TestAccAWSS3BucketObject_contentBase64
=== RUN   TestAccAWSS3BucketObject_withContentCharacteristics
=== PAUSE TestAccAWSS3BucketObject_withContentCharacteristics
=== RUN   TestAccAWSS3BucketObject_updates
=== PAUSE TestAccAWSS3BucketObject_updates
=== RUN   TestAccAWSS3BucketObject_updatesWithVersioning
=== PAUSE TestAccAWSS3BucketObject_updatesWithVersioning
=== RUN   TestAccAWSS3BucketObject_kms
=== PAUSE TestAccAWSS3BucketObject_kms
=== RUN   TestAccAWSS3BucketObject_sse
=== PAUSE TestAccAWSS3BucketObject_sse
=== RUN   TestAccAWSS3BucketObject_acl
=== PAUSE TestAccAWSS3BucketObject_acl
=== RUN   TestAccAWSS3BucketObject_storageClass
=== PAUSE TestAccAWSS3BucketObject_storageClass
=== RUN   TestAccAWSS3BucketObject_tags
=== PAUSE TestAccAWSS3BucketObject_tags
=== RUN   TestAccAWSS3BucketPolicy_basic
=== PAUSE TestAccAWSS3BucketPolicy_basic
=== RUN   TestAccAWSS3BucketPolicy_policyUpdate
=== PAUSE TestAccAWSS3BucketPolicy_policyUpdate
=== RUN   TestAccAWSS3Bucket_importBasic
=== PAUSE TestAccAWSS3Bucket_importBasic
=== RUN   TestAccAWSS3Bucket_importWithPolicy
=== PAUSE TestAccAWSS3Bucket_importWithPolicy
=== RUN   TestAccAWSS3Bucket_basic
=== PAUSE TestAccAWSS3Bucket_basic
=== RUN   TestAccAWSS3Bucket_namePrefix
=== PAUSE TestAccAWSS3Bucket_namePrefix
=== RUN   TestAccAWSS3Bucket_generatedName
=== PAUSE TestAccAWSS3Bucket_generatedName
=== RUN   TestAccAWSS3Bucket_region
=== PAUSE TestAccAWSS3Bucket_region
=== RUN   TestAccAWSS3Bucket_acceleration
=== PAUSE TestAccAWSS3Bucket_acceleration
=== RUN   TestAccAWSS3Bucket_RequestPayer
=== PAUSE TestAccAWSS3Bucket_RequestPayer
=== RUN   TestAccAWSS3Bucket_Policy
=== PAUSE TestAccAWSS3Bucket_Policy
=== RUN   TestAccAWSS3Bucket_UpdateAcl
=== PAUSE TestAccAWSS3Bucket_UpdateAcl
=== RUN   TestAccAWSS3Bucket_Website_Simple
=== PAUSE TestAccAWSS3Bucket_Website_Simple
=== RUN   TestAccAWSS3Bucket_WebsiteRedirect
=== PAUSE TestAccAWSS3Bucket_WebsiteRedirect
=== RUN   TestAccAWSS3Bucket_WebsiteRoutingRules
=== PAUSE TestAccAWSS3Bucket_WebsiteRoutingRules
=== RUN   TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical
=== PAUSE TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical
=== RUN   TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed
=== PAUSE TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed
=== RUN   TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled
=== PAUSE TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled
=== RUN   TestAccAWSS3Bucket_shouldFailNotFound
=== PAUSE TestAccAWSS3Bucket_shouldFailNotFound
=== RUN   TestAccAWSS3Bucket_Versioning
=== PAUSE TestAccAWSS3Bucket_Versioning
=== RUN   TestAccAWSS3Bucket_Cors_Update
=== PAUSE TestAccAWSS3Bucket_Cors_Update
=== RUN   TestAccAWSS3Bucket_Cors_Delete
=== PAUSE TestAccAWSS3Bucket_Cors_Delete
=== RUN   TestAccAWSS3Bucket_Cors_EmptyOrigin
=== PAUSE TestAccAWSS3Bucket_Cors_EmptyOrigin
=== RUN   TestAccAWSS3Bucket_Logging
=== PAUSE TestAccAWSS3Bucket_Logging
=== RUN   TestAccAWSS3Bucket_Lifecycle
=== PAUSE TestAccAWSS3Bucket_Lifecycle
=== RUN   TestAccAWSS3Bucket_LifecycleExpireMarkerOnly
=== PAUSE TestAccAWSS3Bucket_LifecycleExpireMarkerOnly
=== RUN   TestAccAWSS3Bucket_Replication
=== PAUSE TestAccAWSS3Bucket_Replication
=== RUN   TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation
=== PAUSE TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation
=== RUN   TestAccAWSS3Bucket_ReplicationWithoutStorageClass
=== PAUSE TestAccAWSS3Bucket_ReplicationWithoutStorageClass
=== RUN   TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError
=== PAUSE TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError
=== RUN   TestAccAWSS3Bucket_ReplicationWithoutPrefix
=== PAUSE TestAccAWSS3Bucket_ReplicationWithoutPrefix
=== RUN   TestAccAWSS3Bucket_ReplicationSchemaV2
=== PAUSE TestAccAWSS3Bucket_ReplicationSchemaV2
=== CONT  TestAccAWSS3BucketInventory_basic
=== CONT  TestAccAWSS3Bucket_generatedName
=== CONT  TestAccAWSS3BucketObject_tags
=== CONT  TestAccAWSS3BucketObject_withContentCharacteristics
=== CONT  TestAccAWSS3BucketObject_storageClass
=== CONT  TestAccAWSS3BucketObject_acl
=== CONT  TestAccAWSS3BucketObject_sse
=== CONT  TestAccAWSS3BucketObject_kms
=== CONT  TestAccAWSS3BucketObject_updatesWithVersioning
=== CONT  TestAccAWSS3BucketObject_updates
=== CONT  TestAccAWSS3Bucket_importWithPolicy
=== CONT  TestAccAWSS3Bucket_namePrefix
=== CONT  TestAccAWSS3Bucket_basic
=== CONT  TestAccAWSS3BucketPolicy_policyUpdate
=== CONT  TestAccAWSS3Bucket_importBasic
=== CONT  TestAccAWSS3BucketPolicy_basic
=== CONT  TestAccAWSS3BucketMetric_WithFilterMultipleTags
=== CONT  TestAccAWSS3BucketObject_contentBase64
=== CONT  TestAccAWSS3BucketObject_content
=== CONT  TestAccAWSS3BucketObject_source
--- PASS: TestAccAWSS3Bucket_basic (49.21s)
=== CONT  TestAccAWSS3BucketNotification_withoutFilter
--- PASS: TestAccAWSS3Bucket_namePrefix (50.00s)
=== CONT  TestAccAWSS3BucketNotification_basic
--- PASS: TestAccAWSS3Bucket_generatedName (50.50s)
=== CONT  TestAccAWSS3BucketMetric_WithFilterSingleTag
--- PASS: TestAccAWSS3BucketObject_source (56.43s)
=== CONT  TestAccAWSS3BucketMetric_WithFilterPrefix
--- PASS: TestAccAWSS3BucketObject_content (56.44s)
=== CONT  TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag
--- PASS: TestAccAWSS3BucketObject_tags (57.00s)
=== CONT  TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags
--- PASS: TestAccAWSS3BucketObject_withContentCharacteristics (57.16s)
=== CONT  TestAccAWSS3Bucket_Cors_Update
--- PASS: TestAccAWSS3BucketObject_contentBase64 (58.13s)
=== CONT  TestAccAWSS3Bucket_ReplicationSchemaV2
--- PASS: TestAccAWSS3BucketInventory_basic (60.04s)
=== CONT  TestAccAWSS3Bucket_ReplicationWithoutPrefix
=== CONT  TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError
--- PASS: TestAccAWSS3BucketObject_sse (60.26s)
--- PASS: TestAccAWSS3BucketPolicy_basic (60.54s)
=== CONT  TestAccAWSS3Bucket_ReplicationWithoutStorageClass
--- PASS: TestAccAWSS3Bucket_importBasic (62.16s)
=== CONT  TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation
--- PASS: TestAccAWSS3Bucket_importWithPolicy (65.71s)
=== CONT  TestAccAWSS3Bucket_Replication
--- PASS: TestAccAWSS3BucketObject_kms (86.02s)
=== CONT  TestAccAWSS3Bucket_LifecycleExpireMarkerOnly
--- PASS: TestAccAWSS3BucketMetric_WithFilterMultipleTags (94.43s)
=== CONT  TestAccAWSS3Bucket_Lifecycle
--- PASS: TestAccAWSS3BucketObject_updates (95.12s)
=== CONT  TestAccAWSS3Bucket_Logging
--- PASS: TestAccAWSS3BucketPolicy_policyUpdate (95.31s)
=== CONT  TestAccAWSS3Bucket_Cors_EmptyOrigin
--- PASS: TestAccAWSS3BucketObject_acl (96.34s)
=== CONT  TestAccAWSS3Bucket_Cors_Delete
--- PASS: TestAccAWSS3BucketObject_storageClass (97.92s)
=== CONT  TestAccAWSS3Bucket_WebsiteRedirect
--- PASS: TestAccAWSS3Bucket_ReplicationExpectVersioningValidationError (39.67s)
=== CONT  TestAccAWSS3Bucket_Versioning
--- PASS: TestAccAWSS3BucketObject_updatesWithVersioning (100.12s)
=== CONT  TestAccAWSS3Bucket_shouldFailNotFound
--- PASS: TestAccAWSS3BucketNotification_withoutFilter (69.47s)
=== CONT  TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled
--- PASS: TestAccAWSS3Bucket_shouldFailNotFound (28.84s)
=== CONT  TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutPrefix (79.96s)
=== CONT  TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical
--- PASS: TestAccAWSS3Bucket_ReplicationWithoutStorageClass (80.57s)
=== CONT  TestAccAWSS3Bucket_WebsiteRoutingRules
--- PASS: TestAccAWSS3BucketMetric_WithFilterSingleTag (95.75s)
=== CONT  TestAccAWSS3BucketInventory_encryptWithSSEKMS
--- PASS: TestAccAWSS3Bucket_Cors_EmptyOrigin (52.88s)
=== CONT  TestAccAWSS3BucketMetric_basic
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndSingleTag (93.47s)
=== CONT  TestAccAWSS3BucketInventory_encryptWithSSES3
--- PASS: TestAccAWSS3Bucket_Cors_Delete (54.36s)
=== CONT  TestAccAWSS3Bucket_Policy
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefixAndMultipleTags (94.12s)
=== CONT  TestAccAWSS3Bucket_Website_Simple
--- PASS: TestAccAWSS3BucketMetric_WithFilterPrefix (94.85s)
=== CONT  TestAccAWSS3Bucket_UpdateAcl
--- PASS: TestAccAWSS3Bucket_Cors_Update (100.86s)
=== CONT  TestAccAWSS3Bucket_acceleration
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenAES256IsUsed (51.18s)
=== CONT  TestAccAWSS3Bucket_RequestPayer
--- PASS: TestAccAWSS3Bucket_LifecycleExpireMarkerOnly (96.97s)
=== CONT  TestAccAWSS3Bucket_region
--- PASS: TestAccAWSS3Bucket_Logging (88.21s)
--- FAIL: TestAccAWSS3Bucket_region (15.78s)
    testing.go:538: Step 0 error: Check failed: Check 1/2 error: BucketRegionError: incorrect region, the bucket is not in 'us-west-2' region
                status code: 301, request id: , host id:
--- PASS: TestAccAWSS3BucketMetric_basic (58.38s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSES3 (59.30s)
--- PASS: TestAccAWSS3Bucket_disableDefaultEncryption_whenDefaultEncryptionIsEnabled (92.50s)
--- PASS: TestAccAWSS3BucketNotification_basic (165.92s)
--- PASS: TestAccAWSS3Bucket_ReplicationConfiguration_Rule_Destination_AccessControlTranslation (166.61s)
--- PASS: TestAccAWSS3BucketInventory_encryptWithSSEKMS (82.99s)
--- PASS: TestAccAWSS3Bucket_enableDefaultEncryption_whenTypical (92.39s)
--- PASS: TestAccAWSS3Bucket_Lifecycle (138.69s)
--- PASS: TestAccAWSS3Bucket_Versioning (140.55s)
--- PASS: TestAccAWSS3Bucket_WebsiteRoutingRules (101.37s)
--- PASS: TestAccAWSS3Bucket_WebsiteRedirect (147.71s)
--- PASS: TestAccAWSS3Bucket_UpdateAcl (97.19s)
--- PASS: TestAccAWSS3Bucket_acceleration (105.10s)
--- PASS: TestAccAWSS3Bucket_Replication (208.48s)
--- PASS: TestAccAWSS3Bucket_RequestPayer (95.10s)
--- PASS: TestAccAWSS3Bucket_Policy (129.15s)
--- PASS: TestAccAWSS3Bucket_Website_Simple (145.62s)
--- PASS: TestAccAWSS3Bucket_ReplicationSchemaV2 (260.25s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       536.614s
make: *** [testacc] Error 1

...
```

### CODE REVIEW

**Comment by bflad** [comment]
Hi @GBrawl 👋 Thanks for submitting this!

Historically, we have avoided adding logic like this into Terraform AWS provider resources because AWS service eventual consistency can thwart even this type of logic since the problem is at the API level. There's no guarantee that S3 API will return a successful `HeadBucket` request even with the mutex since the API eventual consistency can take up to a minute or two (even after one or two successful/unsuccessful responses). If you look around the various S3 resources, you'll see that many places we have to constantly check for `BucketNotFound` errors even after we get an initial successful response. Attempting to reimplement that type of consistency checking generally winds up being more problematic than helpful unfortunately.

Ideally, this is a problem that could be better solved with some improvements either at the Terraform AWS provider level or the Terraform provider SDK to cache all expectedly unique resource names and check that cache during plan-time validation. This would preferably enabled by a Terraform schema attribute flag of some sort to simplify the implementation. Neither of these mechanisms exist today unfortunately and I'm not sure if there is a good Terraform core (where the provider SDK currently lives) issue that captures this enhancement. It might be worth taking a look though: https://github.com/hashicorp/terraform/issues?q=is%3Aopen+is%3Aissue+label%3Aprovider-sdk

**Comment by GBrawl** [comment]
Hi, thanks for the helpful feedback

I agree that a solution where all names in the plans could be checked beforehand would be way better than implementing a mutex lock, so hopefully this feature will come in the near future. This would solve the problem of two buckets with the same name in the same Terraform plan.

Besides that I don't see any other way of checking if a bucket already exists except for a HEAD request and I'm afraid this can only be checked in the resource itself.

**Comment by matthewduren** [comment]
Solving the "eventually consistent" race condition is a lot harder. I think this check is at least a good sanity check for bucket resources that create "successfully despite actually being created  hours/days/months prior. Seems to me that there would be no harm in implementing this partial fix from @GBrawl.

**Comment by gdavison** [comment]
Hi @GBrawl, thanks for the PR. Now that S3 is[ strongly consistent](https://aws.amazon.com/blogs/aws/amazon-s3-update-strong-read-after-write-consistency/), we won't run into race conditions like this.

**Pull request closed without merging**
