### PR TITLE
Add support for Shield ProactiveEngagement

### PR DESCRIPTION
**Pull request by chasse-code**
### Description
Add support for Shield Proactive Enagagement

### Output from Acceptance Testing

```console
make testacc  PKG=shield  TESTS=TestAccShieldProactiveEngagementAssociation
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20 -run='TestAccShieldProactiveEngagementAssociation'  -timeout 360m
=== RUN   TestAccShieldProactiveEngagementAssociation_basic
--- PASS: TestAccShieldProactiveEngagementAssociation_basic (102.79s)
=== RUN   TestAccShieldProactiveEngagementAssociation_disabled
--- PASS: TestAccShieldProactiveEngagementAssociation_disabled (108.21s)
=== RUN   TestAccShieldProactiveEngagementAssociation_disappears
--- PASS: TestAccShieldProactiveEngagementAssociation_disappears (108.52s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/shield     322.697s
```

### CODE REVIEW

**Comment by AdamTylerLynch** [comment]
References:

- https://docs.aws.amazon.com/waf/latest/developerguide/ddos-srt-proactive-engagement.html
- CLI https://awscli.amazonaws.com/v2/documentation/api/latest/reference/shield/enable-proactive-engagement.html
- API https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_EnableProactiveEngagement.html

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀 

I did not run the AccTests. Requesting Hashi to run the tests/linters

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccShieldProtection_' PKG=shield ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 2  -run=TestAccShieldProtection_ -timeout 360m
=== RUN   TestAccShieldProtection_globalAccelerator
=== PAUSE TestAccShieldProtection_globalAccelerator
=== RUN   TestAccShieldProtection_elasticIPAddress
=== PAUSE TestAccShieldProtection_elasticIPAddress
=== RUN   TestAccShieldProtection_disappears
=== PAUSE TestAccShieldProtection_disappears
=== RUN   TestAccShieldProtection_alb
=== PAUSE TestAccShieldProtection_alb
=== RUN   TestAccShieldProtection_elb
=== PAUSE TestAccShieldProtection_elb
=== RUN   TestAccShieldProtection_cloudFront
=== PAUSE TestAccShieldProtection_cloudFront
=== RUN   TestAccShieldProtection_CloudFront_tags
=== PAUSE TestAccShieldProtection_CloudFront_tags
=== RUN   TestAccShieldProtection_route53
=== PAUSE TestAccShieldProtection_route53
=== CONT  TestAccShieldProtection_globalAccelerator
=== CONT  TestAccShieldProtection_elb
--- PASS: TestAccShieldProtection_elb (68.44s)
=== CONT  TestAccShieldProtection_disappears
--- PASS: TestAccShieldProtection_globalAccelerator (92.58s)
=== CONT  TestAccShieldProtection_alb
--- PASS: TestAccShieldProtection_disappears (34.33s)
=== CONT  TestAccShieldProtection_elasticIPAddress
--- PASS: TestAccShieldProtection_elasticIPAddress (39.24s)
=== CONT  TestAccShieldProtection_CloudFront_tags
--- PASS: TestAccShieldProtection_alb (215.96s)
=== CONT  TestAccShieldProtection_route53
--- PASS: TestAccShieldProtection_route53 (62.69s)
=== CONT  TestAccShieldProtection_cloudFront
--- PASS: TestAccShieldProtection_CloudFront_tags (267.64s)
--- PASS: TestAccShieldProtection_cloudFront (251.28s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/shield	638.219s
```
```console
% make testacc TESTARGS='-run=TestAccShield_serial/DRTAccessLogBucketAssociation' PKG=shield
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20  -run=TestAccShield_serial/DRTAccessLogBucketAssociation -timeout 360m
=== RUN   TestAccShield_serial
=== PAUSE TestAccShield_serial
=== CONT  TestAccShield_serial
=== RUN   TestAccShield_serial/DRTAccessLogBucketAssociation
=== RUN   TestAccShield_serial/DRTAccessLogBucketAssociation/basic
=== RUN   TestAccShield_serial/DRTAccessLogBucketAssociation/multibucket
=== RUN   TestAccShield_serial/DRTAccessLogBucketAssociation/disappears
--- PASS: TestAccShield_serial (64.87s)
    --- PASS: TestAccShield_serial/DRTAccessLogBucketAssociation (64.87s)
        --- PASS: TestAccShield_serial/DRTAccessLogBucketAssociation/basic (23.17s)
        --- PASS: TestAccShield_serial/DRTAccessLogBucketAssociation/multibucket (21.48s)
        --- PASS: TestAccShield_serial/DRTAccessLogBucketAssociation/disappears (20.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/shield	71.539s
```
```console
% make testacc TESTARGS='-run=TestAccShield_serial/DRTAccessRoleARNAssociation' PKG=shield
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20  -run=TestAccShield_serial/DRTAccessRoleARNAssociation -timeout 360m
=== RUN   TestAccShield_serial
=== PAUSE TestAccShield_serial
=== CONT  TestAccShield_serial
=== RUN   TestAccShield_serial/DRTAccessRoleARNAssociation
=== RUN   TestAccShield_serial/DRTAccessRoleARNAssociation/basic
=== RUN   TestAccShield_serial/DRTAccessRoleARNAssociation/disappears
--- PASS: TestAccShield_serial (46.89s)
    --- PASS: TestAccShield_serial/DRTAccessRoleARNAssociation (46.89s)
        --- PASS: TestAccShield_serial/DRTAccessRoleARNAssociation/basic (31.62s)
        --- PASS: TestAccShield_serial/DRTAccessRoleARNAssociation/disappears (15.27s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/shield	55.060s
```
```console
% make testacc TESTARGS='-run=TestAccShield_serial/ProactiveEngagement' PKG=shield
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/shield/... -v -count 1 -parallel 20  -run=TestAccShield_serial/ProactiveEngagement -timeout 360m
=== RUN   TestAccShield_serial
=== PAUSE TestAccShield_serial
=== CONT  TestAccShield_serial
=== RUN   TestAccShield_serial/ProactiveEngagement
=== RUN   TestAccShield_serial/ProactiveEngagement/basic
=== RUN   TestAccShield_serial/ProactiveEngagement/disabled
=== RUN   TestAccShield_serial/ProactiveEngagement/disappears
--- PASS: TestAccShield_serial (52.00s)
    --- PASS: TestAccShield_serial/ProactiveEngagement (52.00s)
        --- PASS: TestAccShield_serial/ProactiveEngagement/basic (19.57s)
        --- PASS: TestAccShield_serial/ProactiveEngagement/disabled (16.28s)
        --- PASS: TestAccShield_serial/ProactiveEngagement/disappears (16.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/shield	58.692s
```

**Comment by ewbankkit** [comment]
@chasse-code Thanks for the contribution :tada: :clap:.

**Pull request merged**
