### PR TITLE
feat: add cloudwatch output config support for run command tasks

### LINKED ISSUE #14136: Allow output logs to CloudWatch for aws_ssm_maintenance_window_task resource
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In AWS a system manager maintenance window task can define two different modes for the output of the commands executed in the task: S3 or CloudWatch. 

The AWS CLI allows this functionallity with the parameter `--task-invocation-parameters` in the `register-task-with-maintenance-window` action.

```json
...
"CloudWatchOutputConfig": {
  "CloudWatchLogGroupName": "string",
  "CloudWatchOutputEnabled": true|false
},
...
```

The terraform provider only allows the s3 bucket options under the `run_command_parameters` argument.

My proposal is to add a new argument `cloudwatch_log_group_name` under the `run_command_parameters` argument.

### New or Affected Resource(s)

* aws_ssm_maintenance_window_task

### Potential Terraform Configuration

Example of the proposal
```hcl
resource "aws_ssm_maintenance_window_task" "run_patch_baseline" {
  max_concurrency  = 2
  max_errors       = 1
  priority         = 2
  service_role_arn = aws_iam_role.aws_role_ssm.arn
  task_arn         = "AWS-RunPatchBaseline"
  task_type        = "RUN_COMMAND"
  window_id        = aws_ssm_maintenance_window.window.id

  targets {
    key    = "WindowTargetIds"
    values = [aws_ssm_maintenance_window_target.targets.id]
  }

  task_invocation_parameters {
    run_command_parameters {
      cloudwatch_log_group_name = "ssm-log-group"
  
      parameter {
        name   = "Operation"
        values = ["Install"]
      }
    }
  }
}
```

### References

* https://docs.aws.amazon.com/cli/latest/reference/ssm/register-task-with-maintenance-window.html

### PR DESCRIPTION
**Pull request by mycodeself**
I have added support for output the logs of run command in a maintenance window tasks to cloudwatch. I've done this based on the PR #12167 that it's inactive for some time. I simply split the tests as proposed in the other PR.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #14136
Other PR Related #12167 

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Add support for CloudWatch output configuration in run command maintenance window tasks 
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParametersCloudWatchOutputConfig'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParametersCloudWatchOutputConfig -timeout 120m
=== RUN   TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParametersCloudWatchOutputConfig
=== PAUSE TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParametersCloudWatchOutputConfig
=== CONT  TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParametersCloudWatchOutputConfig
--- PASS: TestAccAWSSSMMaintenanceWindowTask_TaskInvocationRunCommandParametersCloudWatchOutputConfig (24.50s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       24.548s
```

### CODE REVIEW

**Comment by tzvifriedman** [comment]
Just checking in on this PR. It would be really great if we could get this in place, I'm kind of depending on it for SSM patch compliance reporting. Thanks!

**Comment by mycodeself** [comment]
> Just checking in on this PR. It would be really great if we could get this in place, I'm kind of depending on it for SSM patch compliance reporting. Thanks!

I have fixed the existing conflicts, I am still waiting for a review by a maintainer in order to merge the PR.

I hope someone will give me feedback soon

**Comment by mycodeself** [comment]
I don't know exactly what is happening with the checks, when I launch terrafmt locally I get many errors not related to my PR. 

When I have some time I will give another look, if someone wants to contribute to my PR welcome

**Comment by tzvifriedman** [comment]
was wondering if you ever got any time to take another swing at this. I probably don't know enough go to make a meaningful contribution but this would be an amazing feature to get active!

**Comment by tlaukkan** [comment]
This would be really good to have.

**Comment by mycodeself** [comment]
Finally I have had some time and I think I have managed to fix all the issues :crossed_fingers: 

I hope that someone can review it soon :)

**Comment by tzvifriedman** [comment]
Thanks so much for Congress back to this!

**Comment by bflad** [comment]
Hi @mycodeself  👋  Thank you for working on this. This functionality is being merged in from the earlier #11774 and will be available in version 3.28.0 of the Terraform AWS Provider releasing later today.

**Pull request closed without merging**
