### PR TITLE
fix: fix typo in mapping for cascading_control_configuration

### LINKED ISSUE #39139: [Bug]: Creating dashboard from a template using cascading controls
### Terraform Core Version

1.5.7

### AWS Provider Version

5.60

### Affected Resource(s)

aws_quicksight_dashboard

### Expected Behavior

No error should be thrown since the dashboard is created properly and accessible from the quicksight interface (with all the working functionalities of the template)

### Actual Behavior

The ressource "aws_quicksight_dashboard" is throwing an error in terraform when a template using cascading control configuration is used. 
However the dashboard is correctly created and accessible from the Quicksight interface (and the cascading between the controls work fine). 

If the dashboard resource doesn't exist yet then the error is thrown during the creation of apply plan but if it already exist then is it thrown during the terraform plan part. 

### Relevant Error/Panic Output Snippet

```console
aws_quicksight_dashboard.cm_tracker_dashboard: Creating...
╷
│ Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "parameter_controls", "3", "list", "0", "cacading_control_configuration"}
│ 
│   with aws_quicksight_dashboard.cm_tracker_dashboard,
│   on quicksight_dashboard.tf line 2, in resource "aws_quicksight_dashboard" "cm_tracker_dashboard":
│    2: resource "aws_quicksight_dashboard" "cm_tracker_dashboard" {
│ 
╵
```

### Terraform Configuration Files

```hcl
# This file is maintained automatically by "terraform init".
# Manual edits may be lost in future updates.

provider "registry.terraform.io/hashicorp/aws" {
  version     = "5.61.0"
  constraints = "~> 5.60"
  hashes = [
    "h1:qYXhPfMOxgOYuSjfe7+P2wdqx4oMkPYgH4XUN3fJb54=",
    "zh:1a0a150b6adaeacc8f56763182e76c6219ac67de1217b269d24b770067b7bab0",
    "zh:1d9c3a8ac3934a147569254d6e2e6ea5293974d0595c02c9e1aa31499a8f0042",
    "zh:1f4d1d5e2e02fd5cccafa28dade8735a3059ed1ca3284fb40116cdb67d0e7ee4",
    "zh:26be6f759bded469de477f54c7eb7a9ca9f137a3b52f9fd26cbd864f16973912",
    "zh:276e308ae7aa281fe24f7275673aa05f00cb830b83c2b9797f9aa55f10769c52",
    "zh:45c09beeadb4269d518de0bd341cbe9f061157ab54c543d39168ecefff40bbe2",
    "zh:58fb5ef076dc63e284ce28b47b7cc35a17d2596f11e2373fe568c6140277e9d8",
    "zh:64d51cc1ad412379f64b75883a881a5d682a8e9737ad14479f6a2d62e77f7dbe",
    "zh:71e2e332317cf095288d65a801e95b65fd696204997b2db5250862d6c5669518",
    "zh:9864014aa4716b5bfb3b27d009f158dd6a67c215fd0dfbe3a5d1a7cee72c5677",
    "zh:9b12af85486a96aedd8d7984b0ff811a4b42e3d88dad1a3fb4c0b580d04fa425",
    "zh:d8bf9ba43bd938faab37d8fb515c32a905d6dace60f5ff2663b06ffdc89a62e9",
    "zh:e654be9d3980e7cc70f9825fe0d0205e254edd87832f18b2d7f9c72b09b776cd",
    "zh:ee5ce6fbe75be3e90cabba3fad76fcfde50ab795e523b4ee917cfe8ba8ad42fe",
    "zh:ef12098e7b3ddf9ab286bb209de87dfa8e52106049ced0841e3e6487dbff3659",
  ]
}

provider "registry.terraform.io/hashicorp/null" {
  version = "3.2.2"
  hashes = [
    "h1:IMVAUHKoydFrlPrl9OzasDnw/8ntZFerCC9iXw1rXQY=",
    "zh:3248aae6a2198f3ec8394218d05bd5e42be59f43a3a7c0b71c66ec0df08b69e7",
    "zh:32b1aaa1c3013d33c245493f4a65465eab9436b454d250102729321a44c8ab9a",
    "zh:38eff7e470acb48f66380a73a5c7cdd76cc9b9c9ba9a7249c7991488abe22fe3",
    "zh:4c2f1faee67af104f5f9e711c4574ff4d298afaa8a420680b0cb55d7bbc65606",
    "zh:544b33b757c0b954dbb87db83a5ad921edd61f02f1dc86c6186a5ea86465b546",
    "zh:696cf785090e1e8cf1587499516b0494f47413b43cb99877ad97f5d0de3dc539",
    "zh:6e301f34757b5d265ae44467d95306d61bef5e41930be1365f5a8dcf80f59452",
    "zh:78d5eefdd9e494defcb3c68d282b8f96630502cac21d1ea161f53cfe9bb483b3",
    "zh:913a929070c819e59e94bb37a2a253c228f83921136ff4a7aa1a178c7cce5422",
    "zh:aa9015926cd152425dbf86d1abdbc74bfe0e1ba3d26b3db35051d7b9ca9f72ae",
    "zh:bb04798b016e1e1d49bcc76d62c53b56c88c63d6f2dfe38821afef17c416a0e1",
    "zh:c23084e1b23577de22603cff752e59128d83cfecc2e6819edadd8cf7a10af11e",
  ]
}
```

### Steps to Reproduce

json representation of template used (for the dashboard creation we use the arn of the template but this json is the result of the 'aws quicksight describe-template-definition' command  [template-definition.json](https://github.com/user-attachments/files/16869930/template-definition.json)

Definition of the ressource: 

```hcl
resource "aws_quicksight_dashboard" "cm_tracker_dashboard" {
  aws_account_id      = var.account_id
  dashboard_id        = "${var.namespace}-dashboard-id"
  name                = "CM Tracker Dashboard"
  version_description = "Initial version of CM Tracker Dashboard"

  source_entity {
    source_template {
      arn = "arn:aws:quicksight:${var.region}:${var.account_id}:template/${var.quicksight_template_id}/version/${var.quicksight_template_version}"
      data_set_references {
        data_set_placeholder = "DataSetPlaceholderName"
        data_set_arn         = "arn:aws:quicksight:${var.region}:${var.account_id}:dataset/${var.namespace}-data-set-eu"
      }
    }
  }

  permissions {...}

  permissions {...}
}
```

### Debug Output

```console
aws_quicksight_dashboard.cm_tracker_dashboard: Creating...
╷
│ Error: setting definition: Invalid address to set: []string{"definition", "0", "sheets", "0", "parameter_controls", "3", "list", "0", "cacading_control_configuration"}
│ 
│   with aws_quicksight_dashboard.cm_tracker_dashboard,
│   on quicksight_dashboard.tf line 2, in resource "aws_quicksight_dashboard" "cm_tracker_dashboard":
│    2: resource "aws_quicksight_dashboard" "cm_tracker_dashboard" {
│ 
╵
```

### Panic Output

_No response_

### Important Factoids

Is this coming from a typo here ? 'cacading_control_configuration'

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by stefanfreitag**
### Description

The internally used key `cacading_control_configuration` contains a typo, so that the mapping fails.

### Relations

Closes #39139 

### References

- [Cloudformation User Guide](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-quicksight-template-cascadingcontrolconfiguration.html)

### Output from Acceptance Testing

TDB - I would need to check how to provide a test for the fix.

### CODE REVIEW

**Comment by stefanfreitag** [comment]
I would need some guidance on the testing part:
- The dashboard definition is part of the initial issue, but I think it needs to be stripped down to the minimum for the test. For this the access to Quicksight somehow makes sense.
- At the moment I do not have access to Quicksight itself and there seems to be cost involved when it comes to creation of the dashboards/ being an Admin in that service.

How would I need to proceed here?

**Comment by ewbankkit** [comment]
It looks like there's another one in `internal/service/quicksight/schema/template_control.go`.

**Comment by stefanfreitag** [comment]
Agree, I missed that one - thanks for taking time and doing this consistency check!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccQuickSightDashboard_' PKG=quicksight ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/quicksight/... -v -count 1 -parallel 3  -run=TestAccQuickSightDashboard_ -timeout 360m
=== RUN   TestAccQuickSightDashboard_basic
=== PAUSE TestAccQuickSightDashboard_basic
=== RUN   TestAccQuickSightDashboard_disappears
=== PAUSE TestAccQuickSightDashboard_disappears
=== RUN   TestAccQuickSightDashboard_sourceEntity
=== PAUSE TestAccQuickSightDashboard_sourceEntity
=== RUN   TestAccQuickSightDashboard_updateVersionNumber
=== PAUSE TestAccQuickSightDashboard_updateVersionNumber
=== RUN   TestAccQuickSightDashboard_dashboardSpecificConfig
=== PAUSE TestAccQuickSightDashboard_dashboardSpecificConfig
=== CONT  TestAccQuickSightDashboard_basic
=== CONT  TestAccQuickSightDashboard_updateVersionNumber
=== CONT  TestAccQuickSightDashboard_sourceEntity
--- PASS: TestAccQuickSightDashboard_basic (39.94s)
=== CONT  TestAccQuickSightDashboard_dashboardSpecificConfig
--- PASS: TestAccQuickSightDashboard_sourceEntity (41.68s)
=== CONT  TestAccQuickSightDashboard_disappears
--- PASS: TestAccQuickSightDashboard_updateVersionNumber (74.14s)
--- PASS: TestAccQuickSightDashboard_disappears (34.95s)
--- PASS: TestAccQuickSightDashboard_dashboardSpecificConfig (38.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	83.703s
testing: warning: no tests to run
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	0.593s [no tests to run]
```

**Comment by ewbankkit** [comment]
@stefanfreitag Thanks for the contribution :tada: :clap:.

**Pull request merged**
