### PR TITLE
supporting S3 providers that don't implement acceleration, payer or lock configuration

### LINKED ISSUE #13726: Acceleration NotImplemented error with third party S3 implementation
When using a different S3 implementation (here Cloudian), the bucket gets created but the terraform states still fails, due to Acceleration not being implemented server side.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.12.24
+ provider.aws v2.66.0
```

### Affected Resource(s)

* aws_s3_bucket

### Terraform Configuration Files

```hcl
provider "aws" {
  endpoints {
    s3 = "https://object-fr.antemeta.net"
  }
  region = "fr"
  skip_region_validation = true
  skip_get_ec2_platforms = true
  s3_force_path_style = true
  skip_credentials_validation = true
  skip_metadata_api_check     = true
  skip_requesting_account_id  = true
}

resource "aws_s3_bucket" "test-bucket" {
  bucket = "test-bucket"
  acl    = "private"
  acceleration_status = null
}
```

### Debug Output

https://gist.github.com/dr4Ke/b27bdf40fa54dbe9da92a9085380cdeb

### Panic Output

N/A

### Expected Behavior

The bucket gets created and `terraform apply` succeeds.

### Actual Behavior

The bucket gets created but the `terraform apply` fails with error:
```
Error: error getting S3 Bucket acceleration configuration: NotImplemented: A header you provided implies functionality that is not implemented.
	status code: 501, request id: , host id:
```

It is due to the Acceleration not being implemented. Subsequents run of `terraform plan` gives the same error.

Detailed output:
```
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: -----------------------------------------------------
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 2020/06/12 08:58:16 [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?><VersioningConfiguration xmlns="http://s3.amazonaws.com/doc/2006-03-01/"></VersioningConfiguration>
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 2020/06/12 08:58:16 [DEBUG] Waiting for state to become: [success]
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 2020/06/12 08:58:16 [DEBUG] [aws-sdk-go] DEBUG: Request s3/GetBucketAccelerateConfiguration Details:
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: ---[ REQUEST POST-SIGN ]-----------------------------
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: GET /test-bucket?accelerate= HTTP/1.1
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Host: object-fr.antemeta.net
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: User-Agent: aws-sdk-go/1.31.2 (go1.13.7; linux; amd64) APN/1.0 HashiCorp/1.0 Terraform/0.12.24 (+https://www.terraform.io)
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Authorization: AWS4-HMAC-SHA256 Credential=XXXXXXXXXXXXXXX/20200612/fr/s3/aws4_request, SignedHeaders=host;x-amz-content-sha256;x-amz-date, Signature=791ca9bfd2fee30397381f6c31463ddb9497f255b336e2ae5227b50a44665d22
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: X-Amz-Content-Sha256: e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: X-Amz-Date: 20200612T085816Z
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Accept-Encoding: gzip
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 
2020-06-12T08:58:16.839Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: -----------------------------------------------------
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 2020/06/12 08:58:17 [DEBUG] [aws-sdk-go] DEBUG: Response s3/GetBucketAccelerateConfiguration Details:
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: ---[ RESPONSE ]--------------------------------------
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: HTTP/1.1 501 Not Implemented
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Connection: close
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Content-Length: 286
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Content-Type: application/xml
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Date: Fri, 12 Jun 2020 08:58:17 GMT
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Server: CloudianS3
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: Strict-Transport-Security: max-age=31536000
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: X-Gmt-Error-Code: NotImplemented
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: X-Gmt-Message: A header you provided implies functionality that is not implemented.
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: 
2020-06-12T08:58:17.053Z [DEBUG] plugin.terraform-provider-aws_v2.66.0_x4: -----------------------------------------------------

```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Please note this is happening on a S3 implementation that's not Amazon's.

### References

* Similar to #11556 but does not get fixed by using `acceleration_status = null` parameter
* See [comment](https://github.com/terraform-providers/terraform-provider-aws/pull/12049#issuecomment-636225241) by @gdavison

### PR DESCRIPTION
**Pull request by mflorin**
### Change Description

In order to support third party S3 providers that do not support acceleration, request payer or lock configuration when
managing buckets, we need to be able to skip those operations. For that, we've implemented three new attributes on the `aws_s3_bucket` resource:
- skip_acceleration_config
- skip_payer_config
- skip_lock_config

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13726

Output from acceptance testing:

```
$ AWS_PROFILE=default AWS_DEFAULT_REGION=eu-central-1 make testacc TESTARGS='-run=TestAccAWSS3Bucket_SkipConfig'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSS3Bucket_SkipConfig -timeout 120m
=== RUN   TestAccAWSS3Bucket_SkipConfig
=== PAUSE TestAccAWSS3Bucket_SkipConfig
=== CONT  TestAccAWSS3Bucket_SkipConfig
--- PASS: TestAccAWSS3Bucket_SkipConfig (28.72s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	30.553s
```

### CODE REVIEW

**Comment by dabo-devconsole** [comment]
There are also providers which do not support versioning e.g. Strato HiDrive S3.
It would be great that also skip_versioning can be implemented.

**Comment by mneverov** [comment]
@mflorin i tried to resolve the conflicts after the refactoring and I think it is easier to reimplement this using the new code structure. Do you plan to do that or may i take a stab at it?

**Comment by mflorin** [comment]
> @mflorin i tried to resolve the conflicts after the refactoring and I think it is easier to reimplement this using the new code structure. Do you plan to do that or may i take a stab at it?

Hello, I don't think I'll be able to do that in the near future. Feel free to give it a try. Thanks :)

**Comment by anGie44** [comment]
Hi @mflorin 👋 , thank you for raising this PR. Are these skip conditions implemented to avoid the specific `NotImplemented` or `XNotImplemented` error returned from the `aws_s3_bucket` resource? If so, it's possible the PR, https://github.com/hashicorp/terraform-provider-aws/pull/23278, already skips errors for some of the arguments

**Comment by rslinckx** [comment]
@anGie44 the referenced PR is indeed solving those use cases. I still have one issue with bucket tags which are apparently not implemented in my flavor of S3:

```
│ Error: error listing tags for S3 Bucket (xxxxxx): NotImplemented: A header you provided implies functionality that is not implemented.
│ 	status code: 501, request id: 8296f17fa1448f9570ff, host id: 8296f17fa1448f9570ff
```

I think the tags could have the same treatment and ignore NotImplemented responses ?

**Comment by anGie44** [comment]
Hi @MPV , just wanted to note here that the PR in reference https://github.com/hashicorp/terraform-provider-aws/pull/23278, accounts for the `NotImplemented` error, but not the unique `XNotImplemented` your are seeing. We ignored `XNotImplented` errors only when retrieving the bucket website.

**Comment by MPV** [comment]
> Hi @MPV , just wanted to note here that the PR in reference https://github.com/hashicorp/terraform-provider-aws/pull/23278, accounts for the `NotImplemented` error, but not the unique `XNotImplemented` your are seeing. We ignored `XNotImplented` errors only when retrieving the bucket website. 

@anGie44 Thanks for the clarification, that makes sense. Any thoughts on how to move forward with support for aforementioned `XNotImplemented`?

**Pull request closed without merging**
