### PR TITLE
Handle KMS updates with replica tables.

### LINKED ISSUE #21726: Changing KMS key on Dynamodb replicas fails
When changing the KMS key for a replica from the default key to a CMK the following error is reported:

> Error: error updating DynamoDB Table (test-table) SSE: ValidationException: Invalid operation: Customer Managed CMKs on Global Table Version 2019.11.21 replicas cannot be updated through SSESpecification parameter and can only be updated through ReplicaUpdates parameter

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
terraform 1.0.0
aws provider version 3.45.0

### Affected Resource(s)

* aws_dynamodb_table

### Terraform Configuration Files

Given the original table creation

```hcl
resource "aws_dynamodb_table" "test" {
  name = "test-table"
  attribute {
    name = "test"
    type = "S"
  }
  attribute {
    name = "test2"
    type = "S"
  }
  hash_key         = "test"
  range_key        = "test2"
  billing_mode     = "PAY_PER_REQUEST"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
  server_side_encryption {
    enabled = true
  }
  replica {
    region_name = "eu-west-1"
  }

  replica {
    region_name = "eu-central-1"
  }
  lifecycle {
    prevent_destroy = true
  }
}
```

Update to the following produces the error

```hcl
resource "aws_dynamodb_table" "test" {
  name = "test-table"
  attribute {
    name = "test"
    type = "S"
  }
  attribute {
    name = "test2"
    type = "S"
  }
  hash_key         = "test"
  range_key        = "test2"
  billing_mode     = "PAY_PER_REQUEST"
  stream_enabled   = true
  stream_view_type = "NEW_AND_OLD_IMAGES"
  server_side_encryption {
    enabled = true
    kms_key_arn = aws_kms_key.dynamodb_us_east_1.arn
  }
  replica {
    region_name = "eu-west-1"
    kms_key_arn = aws_kms_key.dynamodb_eu_west_1.arn
  }

  replica {
    region_name = "eu-central-1"
    kms_key_arn = aws_kms_key.dynamodb_eu_central_1.arn
  }
  lifecycle {
    prevent_destroy = true
  }
}

resource "aws_kms_key" "dynamodb_us_east_1" {
  enable_key_rotation = true
  is_enabled          = true
  policy                  = <redacted>
}

resource "aws_kms_key" "dynamodb_eu_west_1" {
  enable_key_rotation = true
  is_enabled          = true
  policy                  = <redacted>
  provider              = aws.euwest1         
}

resource "aws_kms_key" "dynamodb_eu_central_1" {
  enable_key_rotation = true
  is_enabled          = true
  policy                  = <redacted>
  provider              = aws.eucentral1         
}
```

### Expected Behavior

The KMS key should have been updated from the default to the CMK

### Actual Behavior

The apply failed with the following error

### Steps to Reproduce

1. `terraform apply` # with first code block
2. `terraform apply` # after updating code to be like that in second block

### PR DESCRIPTION
**Pull request by grahamhar**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21726

Output from acceptance testing replica related tests:

```
➜ make testacc  TESTS='TestAccDynamoDBTable_Replica_' PKG=dynamodb
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_Replica_'  -timeout 180m
=== RUN   TestAccDynamoDBTable_Replica_multiple
=== PAUSE TestAccDynamoDBTable_Replica_multiple
=== RUN   TestAccDynamoDBTable_Replica_single
=== PAUSE TestAccDynamoDBTable_Replica_single
=== RUN   TestAccDynamoDBTable_Replica_singleWithCMK
=== PAUSE TestAccDynamoDBTable_Replica_singleWithCMK
=== RUN   TestAccDynamoDBTable_Replica_singleUpdateToUseCMK
=== PAUSE TestAccDynamoDBTable_Replica_singleUpdateToUseCMK
=== CONT  TestAccDynamoDBTable_Replica_multiple
=== CONT  TestAccDynamoDBTable_Replica_singleWithCMK
=== CONT  TestAccDynamoDBTable_Replica_singleUpdateToUseCMK
=== CONT  TestAccDynamoDBTable_Replica_single
--- PASS: TestAccDynamoDBTable_Replica_singleWithCMK (342.53s)
--- PASS: TestAccDynamoDBTable_Replica_singleUpdateToUseCMK (459.36s)
--- PASS: TestAccDynamoDBTable_Replica_single (463.40s)
--- PASS: TestAccDynamoDBTable_Replica_multiple (724.64s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb   726.839s

```
Output from acceptance testing encryption related tests:
```

➜ make testacc  TESTS='TestAccDynamoDBTable_encryption' PKG=dynamodb
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dynamodb/... -v -count 1 -parallel 20 -run='TestAccDynamoDBTable_encryption'  -timeout 180m
=== RUN   TestAccDynamoDBTable_encryption
=== PAUSE TestAccDynamoDBTable_encryption
=== CONT  TestAccDynamoDBTable_encryption
--- PASS: TestAccDynamoDBTable_encryption (137.80s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/dynamodb   139.694s

```

### CODE REVIEW

**Comment by pat-humphreys** [comment]
Anyone know which release this bug might make it into? v1.1.8?

**Comment by grahamhar** [comment]
> Anyone know which release this bug might make it into? v1.1.8?

@pat-humphreys as I am a community contributor the PRs tend not to get looked at quickly unless there are a large number of reaction on the original message at the top, adding a thumbs up reaction is the beast way of helping to get this prioritised

**Comment by grahamhar** [comment]
@gdavison do I need to do anything to resolve the conflicts on this PR?

**Review by gdavison — APPROVED** [review]
Thanks for the PR, @grahamhar. I've been trying to fix a perpetual diff when the default keys are used (#27850), but that's going to take a lot more work and it isn't worth delaying this PR any longer.

--- PASS: TestAccDynamoDBTable_attributeUpdateValidation (40.05s)
--- PASS: TestAccDynamoDBTable_TTL_enabled (148.44s)
--- PASS: TestAccDynamoDBTable_basic (148.45s)
--- PASS: TestAccDynamoDBTable_lsiNonKeyAttributes (162.16s)
--- PASS: TestAccDynamoDBTable_tags (167.64s)
--- PASS: TestAccDynamoDBTable_GsiUpdateNonKeyAttributes_emptyPlan (227.47s)
--- PASS: TestAccDynamoDBTable_TTL_disabled (233.44s)
--- PASS: TestAccDynamoDBTable_lsiUpdate (253.67s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestToProvisioned (257.70s)
--- PASS: TestAccDynamoDBTable_streamSpecificationValidation (14.20s)
--- PASS: TestAccDynamoDBTable_tableClassInfrequentAccess (268.40s)
--- PASS: TestAccDynamoDBTable_encryption (382.82s)
--- PASS: TestAccDynamoDBTable_gsiUpdateCapacity (230.33s)
--- PASS: TestAccDynamoDBTable_backup_overrideEncryption (406.05s)
--- PASS: TestAccDynamoDBTable_Replica_singleWithCMK (429.92s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_payPerRequestToProvisioned (236.99s)
--- PASS: TestAccDynamoDBTable_disappears (107.37s)
--- PASS: TestAccDynamoDBTable_BillingMode_payPerRequestToProvisionedIgnoreChanges (189.85s)
--- PASS: TestAccDynamoDBTable_Disappears_payPerRequestWithGSI (234.46s)
--- PASS: TestAccDynamoDBTable_enablePITR (154.28s)
--- PASS: TestAccDynamoDBTable_Replica_tagsTwoOfTwo (465.41s)
--- PASS: TestAccDynamoDBTable_streamSpecification (168.92s)
--- PASS: TestAccDynamoDBTable_streamSpecificationDiffs (501.32s)
--- PASS: TestAccDynamoDBTable_Replica_tagsOneOfTwo (518.72s)
--- PASS: TestAccDynamoDBTable_gsiUpdateNonKeyAttributes (762.87s)
--- PASS: TestAccDynamoDBTable_Replica_singleAddCMK (786.43s)
--- PASS: TestAccDynamoDBTable_BillingMode_provisionedToPayPerRequest (558.90s)
--- PASS: TestAccDynamoDBTable_Replica_tagsUpdate (913.00s)
--- PASS: TestAccDynamoDBTable_Replica_single (921.50s)
--- PASS: TestAccDynamoDBTable_Replica_multiple (924.06s)
--- PASS: TestAccDynamoDBTable_Replica_pitr (548.79s)
--- PASS: TestAccDynamoDBTable_BillingMode_provisionedToPayPerRequestIgnoreChanges (736.58s)
--- PASS: TestAccDynamoDBTable_BillingModeGSI_provisionedToPayPerRequest (1002.36s)
--- PASS: TestAccDynamoDBTable_Replica_tagsNext (912.50s)
--- PASS: TestAccDynamoDBTable_backupEncryption (1145.25s)
--- PASS: TestAccDynamoDBTable_attributeUpdate (1232.55s)
--- PASS: TestAccDynamoDBTable_gsiUpdateOtherAttributes (1086.53s)
--- PASS: TestAccDynamoDBTable_extended (615.45s)

**Pull request merged**
