### PR TITLE
resource/aws_ses_configuration_set: Add delivery options to allow a TlsPolicy of Require to be specified

### LINKED ISSUE #11197: Feature request: SES configuration set delivery options
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hi, I'd like to request a new resource for creating Amazon SES Configuration Sets "DeliveryOptions": https://docs.aws.amazon.com/ses/latest/APIReference/API_DeliveryOptions.html

### New or Affected Resource(s)

aws_ses_configuration_set

### Potential Terraform Configuration

```hcl
resource "aws_ses_configuration_set" "enforce-tls" {
  name = "enforce-tls"

  delivery_options {
    tls_policy = "Require"
  }
}
```

### References

- https://docs.aws.amazon.com/ses/latest/APIReference/API_DeliveryOptions.html

### PR DESCRIPTION
**Pull request by marcjay**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #11197

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_ses_configuration_set: Add `tls_policy` attribute to support requiring TLS as a `delivery_option`
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSESConfigurationSet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSESConfigurationSet -timeout 120m
=== RUN   TestAccAWSSESConfigurationSet_basic
=== PAUSE TestAccAWSSESConfigurationSet_basic
=== RUN   TestAccAWSSESConfigurationSet_deliveryOptions
=== PAUSE TestAccAWSSESConfigurationSet_deliveryOptions
=== RUN   TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== PAUSE TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== CONT  TestAccAWSSESConfigurationSet_basic
=== CONT  TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== CONT  TestAccAWSSESConfigurationSet_deliveryOptions
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptions (19.28s)
--- PASS: TestAccAWSSESConfigurationSet_basic (19.53s)
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptionsUpdate (32.71s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	32.772s
```

### CODE REVIEW

**Comment by marcjay** [comment]
This is based on the potential syntax on #11197 - if there is a preference for a different syntax, I'm happy to update this PR

**Comment by marcjay** [comment]
Many thanks @richmidwinter for the approval. What's the next step for getting this merged? Cheers

**Comment by marcjay** [comment]
Any chance of an update on this please? Appreciate that some PRs are more important than others but this is fairly small all things considered. Would really appreciate this being merged. Many thanks

**Comment by bmoylan** [comment]
We would love to see this get in as well. @bflad are you the right reviewer here? Thanks in advance!

**Comment by marcjay** [comment]
Re-ran the acceptance tests after resolving the merge conflicts:
```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSSESConfigurationSet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSESConfigurationSet -timeout 120m
=== RUN   TestAccAWSSESConfigurationSet_basic
=== PAUSE TestAccAWSSESConfigurationSet_basic
=== RUN   TestAccAWSSESConfigurationSet_deliveryOptions
=== PAUSE TestAccAWSSESConfigurationSet_deliveryOptions
=== RUN   TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== PAUSE TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== CONT  TestAccAWSSESConfigurationSet_basic
=== CONT  TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== CONT  TestAccAWSSESConfigurationSet_deliveryOptions
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptions (16.81s)
--- PASS: TestAccAWSSESConfigurationSet_basic (16.92s)
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptionsUpdate (27.18s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	28.632s
```

**Comment by nyetsche** [comment]
@richmidwinter are you able to review and merge? We're very interested in seeing this reach mainline. Thanks.

**Comment by marcjay** [comment]
Re-ran the acceptance tests after merging master and adopting `TestCheckTypeSetElemNestedAttrs`:

```
$ make testacc TESTARGS='-run=TestAccAWSSESConfigurationSet'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSESConfigurationSet -timeout 120m
=== RUN   TestAccAWSSESConfigurationSet_basic
=== PAUSE TestAccAWSSESConfigurationSet_basic
=== RUN   TestAccAWSSESConfigurationSet_deliveryOptions
=== PAUSE TestAccAWSSESConfigurationSet_deliveryOptions
=== RUN   TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== PAUSE TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== CONT  TestAccAWSSESConfigurationSet_basic
=== CONT  TestAccAWSSESConfigurationSet_deliveryOptionsUpdate
=== CONT  TestAccAWSSESConfigurationSet_deliveryOptions
--- PASS: TestAccAWSSESConfigurationSet_basic (9.93s)
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptions (9.98s)
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptionsUpdate (15.92s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	17.482s
```

**Comment by marcjay** [comment]
Hi @richmidwinter / @bflad - is there any chance this could be looked at/merged? It's not much fun dealing with merge conflicts when they pop up and it's been open for 9 months now. Many thanks

**Comment by voycey** [comment]
Any update on this? We have a pretty heavy requirement for this configuration set to be enabled

**Comment by anGie44** [comment]
Hi @marcjay 👋 Thank you for your work on this PR! In order to expedite the process and get this into our upcoming release, I will likely make some minor adjustments. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Review by anGie44 — COMMENTED** [review]
Output of acceptance tests (commercial):
```
--- PASS: TestAccAWSSESConfigurationSet_basic (12.87s)
--- PASS: TestAccAWSSESConfigurationSet_deliveryOptions (13.18s)
--- PASS: TestAccAWSSESConfigurationSet_update_emptyDeliveryOptions (22.53s)
--- PASS: TestAccAWSSESConfigurationSet_update_deliveryOptions (37.61s)
```

**Review by anGie44 — APPROVED** [review]
Thanks again @marcjay! 🚀

**Comment by marcjay** [comment]
> Thanks again @marcjay! 🚀 

@anGie44 thanks for getting it merged! Great to have it in at last

**Pull request merged**
