### PR TITLE
[New Data Source] d/aws_vpc_ipam_pool_cidrs

### LINKED ISSUE #27040: [New Data Source]: aws_vpc_ipam_pool_cidrs
### Description

Requesting a data source that will basically run `get-ipam-pool-cidrs` on a particular pool and return a list of all provisioned CIDRs. Then you could use this in your child accounts to attach to the route table etc.

### Requested Resource(s) and/or Data Source(s)

data aws_vpc_ipam_pool_cidrs

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by drewmullen**
### Description

Adds a new data source to list all cidrs provisioned into a pool. This is especially helpful for those who receive a pool via ram sharing and want to add all CIDRs from a pool to route tables.

### Relations

Closes #27040

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccIPAMPoolCidrsDataSource_basic PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolCidrsDataSource_basic'  -timeout 180m
=== RUN   TestAccIPAMPoolCidrsDataSource_basic
=== PAUSE TestAccIPAMPoolCidrsDataSource_basic
=== CONT  TestAccIPAMPoolCidrsDataSource_basic
--- PASS: TestAccIPAMPoolCidrsDataSource_basic (123.34s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        127.394s
```

### CODE REVIEW

**Comment by drewmullen** [comment]
hey @YakDriver what is this semgrep looking for? 
name of test: `testAccIPAMPoolCIDRsDataSourceConfig_BasicOneCIDRs`
requirement: `testAcc<Resource>Config_<testDetail>`

new ds:
```hcl
data "aws_vpc_ipam_pool_cidrs" "" {}
```

**Comment by drewmullen** [comment]
had to update the name. receipt:

```shell
$ make testacc TESTS=TestAccIPAMPoolCIDRsDataSource_basic PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolCIDRsDataSource_basic'  -timeout 180m
=== RUN   TestAccIPAMPoolCIDRsDataSource_basic
=== PAUSE TestAccIPAMPoolCIDRsDataSource_basic
=== CONT  TestAccIPAMPoolCIDRsDataSource_basic
--- PASS: TestAccIPAMPoolCIDRsDataSource_basic (141.25s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        145.022s
```

**Comment by drewmullen** [comment]
added pagination

```
make testacc TESTS=TestAccIPAMPoolCIDRsDataSource_basic PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccIPAMPoolCIDRsDataSource_basic'  -timeout 180m
=== RUN   TestAccIPAMPoolCIDRsDataSource_basic
=== PAUSE TestAccIPAMPoolCIDRsDataSource_basic
=== CONT  TestAccIPAMPoolCIDRsDataSource_basic
--- PASS: TestAccIPAMPoolCIDRsDataSource_basic (124.37s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        126.806s
```

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIPAMPoolCIDRsDataSource_' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccIPAMPoolCIDRsDataSource_ -timeout 180m
=== RUN   TestAccIPAMPoolCIDRsDataSource_basic
=== PAUSE TestAccIPAMPoolCIDRsDataSource_basic
=== CONT  TestAccIPAMPoolCIDRsDataSource_basic
--- PASS: TestAccIPAMPoolCIDRsDataSource_basic (94.44s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	98.742s
```

**Comment by ewbankkit** [comment]
@drewmullen Thanks for the contribution :tada: :clap:.

**Pull request merged**
