### PR TITLE
Add missing notification channel

### LINKED ISSUE #33174: [Docs]: Missing information about ssmcontacts_plan
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/ssmcontacts_plan

### Description

on published docs there are nothing about using notification channel. 
but i managed to find it in sources: 
https://github.com/hashicorp/terraform-provider-aws/blob/v5.13.1/internal/service/ssmcontacts/plan.go#L59C1-L60C1

and it helped me to create setting
```
target {
      channel_target_info {
        retry_interval_in_minutes = 2
        contact_channel_id        = aws_ssmcontacts_contact_channel.channel.arn
      }
    }
``` 
which is adding missing piece to be able to trigger calls. 

### References

https://discuss.hashicorp.com/t/ssm-incident-manager-doesnt-create-engament-plan-hence-no-call-triggered/57579

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by xyq175com**
### Description

add missing notification channel

### Relations

Closes #33174 

### References

https://discuss.hashicorp.com/t/ssm-incident-manager-doesnt-create-engament-plan-hence-no-call-triggered/57579

### CODE REVIEW

**Comment by xyq175com** [comment]
Hi, Is there anyting for my PR missing here, Can someone help review the PR? Thank you

**Comment by xyq175com** [comment]
> Welcome @xyq175com 👋
> 
> It looks like this is your first Pull Request submission to the [Terraform AWS Provider](https://github.com/hashicorp/terraform-provider-aws)! If you haven’t already done so please make sure you have checked out our [CONTRIBUTOR](https://hashicorp.github.io/terraform-provider-aws/) guide and [FAQ](https://hashicorp.github.io/terraform-provider-aws/faq/) to make sure your contribution is adhering to best practice and has all the necessary elements in place for a successful approval.
> 
> Also take a look at our [FAQ](https://hashicorp.github.io/terraform-provider-aws/faq/) which details how we prioritize Pull Requests for inclusion.
> 
> Thanks again, and welcome to the community! 😃

Hi is there any step im missing here. can you help review the PR

**Review by justinretzolk — APPROVED** [review]
Looks good to me! Thank you very much for your contribution! I'll get this merged once the checks finish up 🚀

**Comment by justinretzolk** [comment]
Hey @xyq175com 👋 Thank you for your pull request! As mentioned above, this looks good to me, but there's a merge conflict that I'm not able to resolve, given the permissions issue mentioned above. Can you resolve the conflict on your side? It looks like #34258 added additional information in the docs section, so you should be able to just accept those changes 🙂. Once the conflict is resolved and the tests re-run, I'll get this merged.

**Comment by xyq175com** [comment]
Hi @justinretzolk can you help look at this and approve the flow? Thank you!

**Review by justinretzolk — APPROVED** [review]
Thanks for the follow up! I've approved the workflows, so assuming they all pass, I'll get this merged in as soon as I can 🙂

**Pull request merged**
