### PR TITLE
semgrep: add rule to remove extraneous value wrapping in d.Set()

### LINKED ISSUE #16554: provider: Remove extraneous AWS Go SDK value wrapping in d.Set()
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The [`(*schema.ResourceData).Set()` receiver method](https://pkg.go.dev/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema#ResourceData.Set) automatically handles pointer types and `nil` values, so wrapping the values with the AWS Go SDK pointer conversion functions, e.g. `aws.StringValue()` is extraneous.

Note: This should _not_ include slice/map functions calls such as `aws.StringValueSlice()` since those conversions are not automatic.

### Example semgrep Rule

```yaml
rules:
  - id: helper-schema-ResourceData-Set-extraneous-value-pointer-conversion
    languages: [go]
    message: AWS Go SDK pointer conversion function for `d.Set()` value is extraneous
    paths:
      include:
        - aws/
    patterns:
      - pattern-either:
        - pattern: d.Set($ATTRIBUTE, aws.BoolValue($APIOBJECT))
        - pattern: d.Set($ATTRIBUTE, aws.Int64Value($APIOBJECT))
        - pattern: d.Set($ATTRIBUTE, int(aws.Int64Value($APIOBJECT)))
        - pattern: d.Set($ATTRIBUTE, aws.StringValue($APIOBJECT))
    severity: WARNING
```

### Example Reports

```
aws/resource_aws_wafv2_rule_group.go
severity:warning rule:helper-schema-ResourceData-Set-extraneous-value-wrapping: AWS Go SDK value wrapping in `d.Set()` is extraneous
188:	d.Set("name", aws.StringValue(resp.RuleGroup.Name))
189:	d.Set("capacity", aws.Int64Value(resp.RuleGroup.Capacity))
190:	d.Set("description", aws.StringValue(resp.RuleGroup.Description))
191:	d.Set("arn", aws.StringValue(resp.RuleGroup.ARN))
192:	d.Set("lock_token", aws.StringValue(resp.LockToken))

aws/resource_aws_wafv2_web_acl.go
severity:warning rule:helper-schema-ResourceData-Set-extraneous-value-wrapping: AWS Go SDK value wrapping in `d.Set()` is extraneous
215:	d.Set("name", aws.StringValue(resp.WebACL.Name))
216:	d.Set("capacity", aws.Int64Value(resp.WebACL.Capacity))
217:	d.Set("description", aws.StringValue(resp.WebACL.Description))
218:	d.Set("arn", aws.StringValue(resp.WebACL.ARN))
219:	d.Set("lock_token", aws.StringValue(resp.LockToken))

aws/resource_aws_worklink_fleet.go
severity:warning rule:helper-schema-ResourceData-Set-extraneous-value-wrapping: AWS Go SDK value wrapping in `d.Set()` is extraneous
176:	d.Set("name", aws.StringValue(resp.FleetName))
177:	d.Set("display_name", aws.StringValue(resp.DisplayName))
178:	d.Set("optimize_for_end_user_location", aws.BoolValue(resp.OptimizeForEndUserLocation))
179:	d.Set("company_code", aws.StringValue(resp.CompanyCode))
```

### Affected Resources

TBD

### Definition of Done

* Rule added to `.semgrep.yml` with no reports on main branch and CI passes

### PR DESCRIPTION
**Pull request by anGie44**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Preceded by #16655 
Preceded by #16671 
Closes #16554 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
N/A
```

Output from acceptance testing:

```
CI should not report warnings in main branch
```

### CODE REVIEW

**Comment by bflad** [comment]
Let's remove all the existing reports before merging this so the main branch is clear except for new reports. 😄

**Comment by anGie44** [comment]
@bflad existing error reports addressed in #16671 and #16655 👍

**Review by bflad — APPROVED** [review]
Pre-approving this after rebase 👍  If there are lingering reports please feel free to throw them in here as well. It might also be good to include the autofix line in here (e.g. `fix: d.Set($ATTRIBUTE, $APIOBJECT)`) so anyone can run it. 🚀

**Comment by anGie44** [comment]
Confirming no lingering reports 🎉 And fix statement added 👍  

```bash
 $ semgrep
running 17 rules...
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████|17/17
ran 17 rules on 2394 files: 0 findings
```

**Pull request merged**
