### PR TITLE
r/aws_connect_bot_association - add new resource

### LINKED ISSUE #21044: Add new resource/data_source for aws_connect_bot_association
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_connect_bot_association
* data/aws_connect_bot_association

### Potential Terraform Configuration

```hcl
resource "aws_connect_bot_association" "test" {
  instance_id = "97afc98d-101a-ba98-ab97-ae114fc115ec"
  name = "OrderFlowers"
  region = "us-east-1"
}
```

Data Resource

By name

```hcl
data "aws_connect_bot_association" "test" {
  instance_id = "97afc98d-101a-ba98-ab97-ae114fc115ec"
  name = "OrderFlowers"
}
```

### References

* https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateBot.html
* https://docs.aws.amazon.com/connect/latest/APIReference/API_ListBots.html
* https://docs.aws.amazon.com/connect/latest/APIReference/API_DisassociateBot.html

### PR DESCRIPTION
**Pull request by thornleyk**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #21044

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_connect_bot_association - add new resource
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsConnectBotAssociationDataSource_basic'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsConnectBotAssociationDataSource_basic -timeout 180m
=== RUN   TestAccAwsConnectBotAssociationDataSource_basic
--- PASS: TestAccAwsConnectBotAssociationDataSource_basic (64.44s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	67.325s
...
```

```
$ make testacc TESTARGS='-run=TestAccAwsConnectBotAssociation_serial'
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsConnectBotAssociation_serial -timeout 180m
=== RUN   TestAccAwsConnectBotAssociation_serial
=== RUN   TestAccAwsConnectBotAssociation_serial/basic
=== PAUSE TestAccAwsConnectBotAssociation_serial/basic
=== RUN   TestAccAwsConnectBotAssociation_serial/disappears
=== PAUSE TestAccAwsConnectBotAssociation_serial/disappears
=== CONT  TestAccAwsConnectBotAssociation_serial/basic
=== CONT  TestAccAwsConnectBotAssociation_serial/disappears
--- PASS: TestAccAwsConnectBotAssociation_serial (0.00s)
    --- PASS: TestAccAwsConnectBotAssociation_serial/disappears (64.75s)
    --- PASS: TestAccAwsConnectBotAssociation_serial/basic (68.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	71.950s
```

### CODE REVIEW

**Comment by AdamTylerLynch** [comment]
make testacc TESTARGS='-run=TestAccAwsConnectBot' ACCTEST PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsConnectBot -timeout 180m
=== RUN   TestAccAwsConnectBotAssociationDataSource_basic
--- PASS: TestAccAwsConnectBotAssociationDataSource_basic (95.34s)
=== RUN   TestAccAwsConnectBotAssociation_serial
=== RUN   TestAccAwsConnectBotAssociation_serial/basic
=== PAUSE TestAccAwsConnectBotAssociation_serial/basic
=== RUN   TestAccAwsConnectBotAssociation_serial/disappears
=== PAUSE TestAccAwsConnectBotAssociation_serial/disappears
=== CONT  TestAccAwsConnectBotAssociation_serial/basic
=== CONT  TestAccAwsConnectBotAssociation_serial/disappears
--- PASS: TestAccAwsConnectBotAssociation_serial (0.00s)
    --- PASS: TestAccAwsConnectBotAssociation_serial/disappears (91.24s)
    --- PASS: TestAccAwsConnectBotAssociation_serial/basic (95.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	192.526s
make: *** No rule to make target `ACCTEST'.  Stop.

**Comment by AdamTylerLynch** [comment]
Depends on https://github.com/hashicorp/terraform-provider-aws/pull/21049

**Comment by AdamTylerLynch** [comment]
LGTM.

make testacc TESTARGS='-run=TestAccBotAssociation' PKG_NAME=internal/service/connect ACCTEST PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run=TestAccBotAssociation -timeout 180m
=== RUN   TestAccBotAssociationDataSource_basic
--- PASS: TestAccBotAssociationDataSource_basic (134.60s)
=== RUN   TestAccBotAssociation_serial
=== RUN   TestAccBotAssociation_serial/disappears
=== PAUSE TestAccBotAssociation_serial/disappears
=== RUN   TestAccBotAssociation_serial/basic
=== PAUSE TestAccBotAssociation_serial/basic
=== CONT  TestAccBotAssociation_serial/disappears
=== CONT  TestAccBotAssociation_serial/basic
--- PASS: TestAccBotAssociation_serial (0.00s)
    --- PASS: TestAccBotAssociation_serial/disappears (88.98s)
    --- PASS: TestAccBotAssociation_serial/basic (96.45s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	234.090s

**Comment by AdamTylerLynch** [comment]
LGTM

make testacc TESTARGS='-run=TestAccBotAssociation' PKG_NAME=internal/service/connect ACCTEST PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run=TestAccBotAssociation -timeout 180m
=== RUN   TestAccBotAssociationDataSource_basic
--- PASS: TestAccBotAssociationDataSource_basic (86.77s)
=== RUN   TestAccBotAssociation_serial
=== RUN   TestAccBotAssociation_serial/basic
=== PAUSE TestAccBotAssociation_serial/basic
=== RUN   TestAccBotAssociation_serial/disappears
=== PAUSE TestAccBotAssociation_serial/disappears
=== CONT  TestAccBotAssociation_serial/basic
=== CONT  TestAccBotAssociation_serial/disappears
--- PASS: TestAccBotAssociation_serial (0.00s)
    --- PASS: TestAccBotAssociation_serial/disappears (85.21s)
    --- PASS: TestAccBotAssociation_serial/basic (89.14s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	177.461s

**Comment by AdamTylerLynch** [comment]
Review Requested.

**Comment by anGie44** [comment]
Output of acceptance tests after updating the schema to align with AWS API (still limited to Lex V1 usage):
```
--- PASS: TestAccConnectBotAssociationDataSource_basic (102.72s)
--- PASS: TestAccConnectBotAssociation_serial (167.34s)
    --- PASS: TestAccConnectBotAssociation_serial/disappears (82.86s)
    --- PASS: TestAccConnectBotAssociation_serial/basic (84.47s)
```

**Review by anGie44 — APPROVED** [review]
Thank you @thornleyk and @AdamTylerLynch for working on this feature! Overall, looked great 👍 To align with the Connect API methods used, i've updated the schema to reflect the Lex V1 input parameters, while leaving the possibility for V2 compatibility in a future enhancement request. A couple cosmetic fixes to the tests, otherwise this looks ready to go 🚀

**Pull request merged**
