### PR TITLE
Enhancement: snowflake destination addition in firehose kinesis stream

### PR DESCRIPTION
**Pull request by mayank0202**
### Description
Addition of snowflake destination in firehose kinesis stream 

Release notes for Kinesis Firehose direct to Snowflake streaming: https://aws.amazon.com/about-aws/whats-new/2024/01/stream-data-snowflake-kinesis-data-firehose-snowpipe-streaming-preview/

See the --snowflake-destination-configuration flag in the AWS CLI Docs here: https://docs.aws.amazon.com/cli/latest/reference/firehose/create-delivery-stream.html

Closes https://github.com/hashicorp/terraform-provider-aws/issues/35647.

### CODE REVIEW

**Comment by mayank0202** [comment]
I have contributed first time in go lang and have a minimal knowledge of this language so any modifications are much appreciated . Thanks!

**Comment by vkarthyk** [comment]
Hi, any update on this PR. This is a feature we are also blocked on for building our streaming pipeline. Thanks!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccFirehoseDeliveryStream_snowflakeUpdates' PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/firehose/... -v -count 1 -parallel 20  -run=TestAccFirehoseDeliveryStream_snowflakeUpdates -timeout 360m
=== RUN   TestAccFirehoseDeliveryStream_snowflakeUpdates
=== PAUSE TestAccFirehoseDeliveryStream_snowflakeUpdates
=== CONT  TestAccFirehoseDeliveryStream_snowflakeUpdates
--- PASS: TestAccFirehoseDeliveryStream_snowflakeUpdates (102.16s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	114.313s
```
```console
% make testacc TESTARGS='-run=TestAccFirehoseDeliveryStream_basic' PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/firehose/... -v -count 1 -parallel 20  -run=TestAccFirehoseDeliveryStream_basic -timeout 360m
=== RUN   TestAccFirehoseDeliveryStream_basic
=== PAUSE TestAccFirehoseDeliveryStream_basic
=== CONT  TestAccFirehoseDeliveryStream_basic
--- PASS: TestAccFirehoseDeliveryStream_basic (80.27s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	92.235s
```

**Comment by ewbankkit** [comment]
@mayank0202 Thanks for the contribution :tada: :clap:.

**Comment by mayank0202** [comment]
> @mayank0202 Thanks for the contribution 🎉 👏.

Thanks for the help @ewbankkit 💯

**Comment by mayank0202** [comment]
@ewbankkit When this will be released? on thursday?

**Pull request merged**
