### PR TITLE
Add examples of aws_iam_access_key v3 upgrade paths

### PR DESCRIPTION
**Pull request by jdheyburn**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
N/A
```

Adding more examples of upgrade paths for `aws_iam_access_key` from v2 -> v3 to the upgrade documentation.

### CODE REVIEW

**Comment by Porkepix** [comment]
Does that mean there's no way to update `iam_access_key` in-place to just add the missing attribute?

**Comment by jdheyburn** [comment]
@Porkepix I'm not sure - I would have though if it was possible those steps would be included in the documentation. I haven't read enough of the resource to understand exactly what the values are, I just wanted to provide a real-world example of an upgrade path for those who created the resource on an old provider version.

**Comment by gileri** [comment]
Thank you @jdheyburn for this PR ! That would clarify the current situation for end-users.
Could you update your first post to indicate

>Closes #14529 

So that it's closed in case your PR is merged ?

**Comment by Porkepix** [comment]
Well I'm not sure this completely close it.

It sure helps, but I'm currently in a situation where even that solution would be painful: taint the resource would render the currently used keys in production infrastructure completely ineffective for some times, up until  a new one is created and deployed.

I still think it should be possible to upgrade existing `iam_access_key` to have file the new attributes in the state, rather than having to completely replace the resource.

**Comment by jdheyburn** [comment]
I would agree it does not close it out. The issue would still persist even if the PR is there. It is an issue of the `aws_iam_access_key` resource being created prior to that attribute existing.

@Porkepix - if you are looking for a seamless switch then the second paragraph added in the PR should suffice for you:

> Alternatively, you can stage the change by creating a new `aws_iam_access_key` resource and change any downstream dependencies to use the new `ses_smtp_password_v4` attribute. Once dependents have been updated with the new resource you can remove the old one.

One way this can be accomplished is by performing a `terraform state rm aws_iam_access_key.resource_name`.  Then your subsequent `terraform plan` will update the downstream dependencies in place.

IAM Access keys are supposed to be short-lived anyway. I believe this is a good compromise IMO.

**Comment by breathingdust** [comment]
LGTM 🚀 Thanks @jdheyburn for the contribution!

**Pull request merged**
