### PR TITLE
Add metric name filtering to AWS Metric Streams

### PR DESCRIPTION
**Pull request by nyumaguzhin**
### Description
[Amazon CloudWatch](https://aws.amazon.com/cloudwatch/) announces support for filtering by metric name on CloudWatch Metric Streams. With Metric Streams, you can create a continuous, near real-time stream of metrics to a destination of your choice. With this new capability you can now select the specific metrics you want to stream, providing additional filtering controls.

### References
* [The new feature](https://aws.amazon.com/about-aws/whats-new/2023/05/amazon-cloudwatch-metric-streams-filtering-name/)
* [AWS CloudFormation documentation](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-cloudwatch-metricstream-metricstreamfilter.html)
* [AWS CloudWatch MetricStreams documentation](https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/CloudWatch-metric-streams-setup-datalake.html)

### Output from Acceptance Testing
```
➜  terraform-provider-aws git:(f-metric_stream_metric_name_filtering) make testacc TESTS=TestAccCloudWatchMetricStream PKG=cloudwatch
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudwatch/... -v -count 1 -parallel 20 -run='TestAccCloudWatchMetricStream'  -timeout 180m
=== RUN   TestAccCloudWatchMetricStream_basic
=== PAUSE TestAccCloudWatchMetricStream_basic
=== RUN   TestAccCloudWatchMetricStream_disappears
=== PAUSE TestAccCloudWatchMetricStream_disappears
=== RUN   TestAccCloudWatchMetricStream_nameGenerated
=== PAUSE TestAccCloudWatchMetricStream_nameGenerated
=== RUN   TestAccCloudWatchMetricStream_namePrefix
=== PAUSE TestAccCloudWatchMetricStream_namePrefix
=== RUN   TestAccCloudWatchMetricStream_includeFilters
=== PAUSE TestAccCloudWatchMetricStream_includeFilters
=== RUN   TestAccCloudWatchMetricStream_includeFiltersWithMetricNames
=== PAUSE TestAccCloudWatchMetricStream_includeFiltersWithMetricNames
=== RUN   TestAccCloudWatchMetricStream_excludeFilters
=== PAUSE TestAccCloudWatchMetricStream_excludeFilters
=== RUN   TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames
=== PAUSE TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames
=== RUN   TestAccCloudWatchMetricStream_update
=== PAUSE TestAccCloudWatchMetricStream_update
=== RUN   TestAccCloudWatchMetricStream_tags
=== PAUSE TestAccCloudWatchMetricStream_tags
=== RUN   TestAccCloudWatchMetricStream_additional_statistics
=== PAUSE TestAccCloudWatchMetricStream_additional_statistics
=== RUN   TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics
=== PAUSE TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics
=== CONT  TestAccCloudWatchMetricStream_basic
=== CONT  TestAccCloudWatchMetricStream_excludeFilters
=== CONT  TestAccCloudWatchMetricStream_namePrefix
=== CONT  TestAccCloudWatchMetricStream_disappears
=== CONT  TestAccCloudWatchMetricStream_nameGenerated
=== CONT  TestAccCloudWatchMetricStream_includeFiltersWithMetricNames
=== CONT  TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics
=== CONT  TestAccCloudWatchMetricStream_tags
=== CONT  TestAccCloudWatchMetricStream_additional_statistics
=== CONT  TestAccCloudWatchMetricStream_includeFilters
=== CONT  TestAccCloudWatchMetricStream_update
=== CONT  TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames
--- PASS: TestAccCloudWatchMetricStream_includeFiltersWithMetricNames (29.87s)
--- PASS: TestAccCloudWatchMetricStream_excludeFilters (30.09s)
--- PASS: TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames (30.29s)
--- PASS: TestAccCloudWatchMetricStream_includeFilters (30.50s)
--- PASS: TestAccCloudWatchMetricStream_additional_statistics (84.59s)
--- PASS: TestAccCloudWatchMetricStream_update (97.01s)
--- PASS: TestAccCloudWatchMetricStream_nameGenerated (190.91s)
--- PASS: TestAccCloudWatchMetricStream_disappears (284.92s)
--- PASS: TestAccCloudWatchMetricStream_basic (288.39s)
--- PASS: TestAccCloudWatchMetricStream_namePrefix (353.34s)
--- PASS: TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics (373.24s)
--- PASS: TestAccCloudWatchMetricStream_tags (377.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch	380.279s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloudWatchMetricStream_' PKG=cloudwatch ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudwatch/... -v -count 1 -parallel 2  -run=TestAccCloudWatchMetricStream_ -timeout 180m
=== RUN   TestAccCloudWatchMetricStream_basic
=== PAUSE TestAccCloudWatchMetricStream_basic
=== RUN   TestAccCloudWatchMetricStream_disappears
=== PAUSE TestAccCloudWatchMetricStream_disappears
=== RUN   TestAccCloudWatchMetricStream_nameGenerated
=== PAUSE TestAccCloudWatchMetricStream_nameGenerated
=== RUN   TestAccCloudWatchMetricStream_namePrefix
=== PAUSE TestAccCloudWatchMetricStream_namePrefix
=== RUN   TestAccCloudWatchMetricStream_includeFilters
=== PAUSE TestAccCloudWatchMetricStream_includeFilters
=== RUN   TestAccCloudWatchMetricStream_includeFiltersWithMetricNames
=== PAUSE TestAccCloudWatchMetricStream_includeFiltersWithMetricNames
=== RUN   TestAccCloudWatchMetricStream_excludeFilters
=== PAUSE TestAccCloudWatchMetricStream_excludeFilters
=== RUN   TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames
=== PAUSE TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames
=== RUN   TestAccCloudWatchMetricStream_update
=== PAUSE TestAccCloudWatchMetricStream_update
=== RUN   TestAccCloudWatchMetricStream_tags
=== PAUSE TestAccCloudWatchMetricStream_tags
=== RUN   TestAccCloudWatchMetricStream_additional_statistics
=== PAUSE TestAccCloudWatchMetricStream_additional_statistics
=== RUN   TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics
=== PAUSE TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics
=== CONT  TestAccCloudWatchMetricStream_basic
=== CONT  TestAccCloudWatchMetricStream_excludeFilters
--- PASS: TestAccCloudWatchMetricStream_excludeFilters (18.40s)
=== CONT  TestAccCloudWatchMetricStream_tags
--- PASS: TestAccCloudWatchMetricStream_basic (205.43s)
=== CONT  TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics
--- PASS: TestAccCloudWatchMetricStream_tags (257.71s)
=== CONT  TestAccCloudWatchMetricStream_additional_statistics
--- PASS: TestAccCloudWatchMetricStream_additional_statistics (55.76s)
=== CONT  TestAccCloudWatchMetricStream_namePrefix
--- PASS: TestAccCloudWatchMetricStream_includeLinkedAccountsMetrics (207.11s)
=== CONT  TestAccCloudWatchMetricStream_includeFiltersWithMetricNames
--- PASS: TestAccCloudWatchMetricStream_includeFiltersWithMetricNames (17.83s)
=== CONT  TestAccCloudWatchMetricStream_includeFilters
--- PASS: TestAccCloudWatchMetricStream_includeFilters (17.98s)
=== CONT  TestAccCloudWatchMetricStream_update
--- PASS: TestAccCloudWatchMetricStream_update (66.48s)
=== CONT  TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames
--- PASS: TestAccCloudWatchMetricStream_excludeFiltersWithMetricNames (18.29s)
=== CONT  TestAccCloudWatchMetricStream_nameGenerated
--- PASS: TestAccCloudWatchMetricStream_namePrefix (216.13s)
=== CONT  TestAccCloudWatchMetricStream_disappears
--- PASS: TestAccCloudWatchMetricStream_nameGenerated (160.10s)
--- PASS: TestAccCloudWatchMetricStream_disappears (156.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudwatch	710.307s
```

**Comment by ewbankkit** [comment]
@nyumaguzhin Thanks for the contribution :tada: :clap:.

**Comment by yuklia** [comment]
@nyumaguzhin Thanks a lot for the contribution! This feature is what we need too!
@ewbankkit, do you know when we can expect it in the official aws terraform provider?

**Comment by ewbankkit** [comment]
@yuklia See https://hashicorp.github.io/terraform-provider-aws/faq/#how-often-do-you-release. Terraform AWS Provider **v4.67.0** should be released tomorrow.

**Pull request merged**
