### PR TITLE
Fix casting bitrate for eac3

### PR DESCRIPTION
**Pull request by LasseEmilHildebrandt**
### Description

Bitrate was missing for ac3 encodings.

### Relations

Relates to #29807
Relates #27824
### Output from Acceptance Testing

```
make testacc TESTS=TestAccMediaLiveChannel_audioDescriptions_codecSettings PKG=medialive
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_audioDescriptions_codecSettings'  -timeout 180m
=== RUN   TestAccMediaLiveChannel_audioDescriptions_codecSettings
=== PAUSE TestAccMediaLiveChannel_audioDescriptions_codecSettings
=== CONT  TestAccMediaLiveChannel_audioDescriptions_codecSettings
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (103.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	105.775s
...
```

### CODE REVIEW

**Comment by LasseEmilHildebrandt** [comment]
> Hey @LasseEmilHildebrandt 👋 Thank you very much for your contribution! At times, our maintainers need to make direct edits to pull requests in order to help get it ready to be merged. Your current settings do not allow maintainers to make such edits. To help facilitate this, update your pull request to allow such edits as described in GitHub's [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) documentation. (If you're using a fork owned by an organization, your organization may not allow you to change this setting. If that is the case, let us know.)

We are aware of this issue, and are currently unable to fix it.

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thanks for the contribution! Overall the PR looks good. Before I run test, can you merge/rebase this PR with main? A few dependencies have been added since last week.

**Comment by LasseEmilHildebrandt** [comment]
Thanks for the review, @johnsonaj - The PR has been rebased unto master.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTS=TestAccMediaLiveChannel_ PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 180m
--- PASS: TestAccMediaLiveChannel_disappears (67.83s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (75.41s)
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (83.97s)
--- PASS: TestAccMediaLiveChannel_m2ts_settings (87.95s)
--- PASS: TestAccMediaLiveChannel_hls (133.48s)
--- PASS: TestAccMediaLiveChannel_basic (145.75s)
--- PASS: TestAccMediaLiveChannel_updateTags (173.07s)
--- PASS: TestAccMediaLiveChannel_status (184.81s)
--- PASS: TestAccMediaLiveChannel_update (206.50s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	209.499s
```

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thank you for the contribution! 🎉

**Pull request merged**
