### PR TITLE
r/vpc_endpoint_policy - new resource

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSVpcEndpointPolicy_'
--- PASS: TestAccEC2VPCEndpointPolicy_disappears_endpoint (80.19s)
--- PASS: TestAccEC2VPCEndpointPolicy_disappears (97.00s)
--- PASS: TestAccEC2VPCEndpointPolicy_basic (154.88s)
...
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
rebased: 

```
--- PASS: TestAccAWSVpcEndpointPolicy_disappears_vpcEndpoint (160.49s)
--- PASS: TestAccAWSVpcEndpointPolicy_disappears (170.60s)
--- PASS: TestAccAWSVpcEndpointPolicy_basic (236.82s)
```

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTS=TestAccEC2VPCEndpointPolicy_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2VPCEndpointPolicy_'  -timeout 180m
=== RUN   TestAccEC2VPCEndpointPolicy_basic
=== PAUSE TestAccEC2VPCEndpointPolicy_basic
=== RUN   TestAccEC2VPCEndpointPolicy_disappears
=== PAUSE TestAccEC2VPCEndpointPolicy_disappears
=== RUN   TestAccEC2VPCEndpointPolicy_disappears_endpoint
=== PAUSE TestAccEC2VPCEndpointPolicy_disappears_endpoint
=== CONT  TestAccEC2VPCEndpointPolicy_basic
=== CONT  TestAccEC2VPCEndpointPolicy_disappears_endpoint
=== CONT  TestAccEC2VPCEndpointPolicy_disappears
--- PASS: TestAccEC2VPCEndpointPolicy_disappears_endpoint (53.23s)
--- PASS: TestAccEC2VPCEndpointPolicy_disappears (65.75s)
--- PASS: TestAccEC2VPCEndpointPolicy_basic (93.09s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	98.658s
```

##### GovCloud

```console
% make testacc TESTS=TestAccEC2VPCEndpointPolicy_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2VPCEndpointPolicy_'  -timeout 180m
=== RUN   TestAccEC2VPCEndpointPolicy_basic
=== PAUSE TestAccEC2VPCEndpointPolicy_basic
=== RUN   TestAccEC2VPCEndpointPolicy_disappears
=== PAUSE TestAccEC2VPCEndpointPolicy_disappears
=== RUN   TestAccEC2VPCEndpointPolicy_disappears_endpoint
=== PAUSE TestAccEC2VPCEndpointPolicy_disappears_endpoint
=== CONT  TestAccEC2VPCEndpointPolicy_basic
=== CONT  TestAccEC2VPCEndpointPolicy_disappears_endpoint
=== CONT  TestAccEC2VPCEndpointPolicy_disappears
--- PASS: TestAccEC2VPCEndpointPolicy_disappears_endpoint (46.47s)
--- PASS: TestAccEC2VPCEndpointPolicy_disappears (58.85s)
--- PASS: TestAccEC2VPCEndpointPolicy_basic (83.27s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	86.815s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Pull request merged**
