### PR TITLE
Feature/8801 iot thing group

### LINKED ISSUE #8801: Add IoT Thing Group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Groups are helpful administrating policies across large numbers of iot things.

### New or Affected Resource(s)

New resource based on:
https://docs.aws.amazon.com/cli/latest/reference/iot/create-thing-group.html

### PR DESCRIPTION
**Pull request by jhole89**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #8801

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New resource: aws_iot_thing_group
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSIotThingGroup_'
=== RUN   TestAccAWSIotThingGroup_base
=== PAUSE TestAccAWSIotThingGroup_base
=== RUN   TestAccAWSIotThingGroup_full
=== PAUSE TestAccAWSIotThingGroup_full
=== RUN   TestAccAWSIotThingGroup_name
=== PAUSE TestAccAWSIotThingGroup_name
=== RUN   TestAccAWSIotThingGroup_tags
=== PAUSE TestAccAWSIotThingGroup_tags
=== RUN   TestAccAWSIotThingGroup_propsAttr
=== PAUSE TestAccAWSIotThingGroup_propsAttr
=== RUN   TestAccAWSIotThingGroup_propsDesc
=== PAUSE TestAccAWSIotThingGroup_propsDesc
=== RUN   TestAccAWSIotThingGroup_propsAll
=== PAUSE TestAccAWSIotThingGroup_propsAll
=== RUN   TestAccAWSIotThingGroup_parent
=== PAUSE TestAccAWSIotThingGroup_parent
=== CONT  TestAccAWSIotThingGroup_base
=== CONT  TestAccAWSIotThingGroup_propsDesc
=== CONT  TestAccAWSIotThingGroup_parent
=== CONT  TestAccAWSIotThingGroup_propsAttr
=== CONT  TestAccAWSIotThingGroup_tags
=== CONT  TestAccAWSIotThingGroup_full
=== CONT  TestAccAWSIotThingGroup_name
=== CONT  TestAccAWSIotThingGroup_propsAll
--- PASS: TestAccAWSIotThingGroup_base (27.22s)
--- PASS: TestAccAWSIotThingGroup_name (44.71s)
--- PASS: TestAccAWSIotThingGroup_full (61.87s)
--- PASS: TestAccAWSIotThingGroup_propsAttr (77.77s)
--- PASS: TestAccAWSIotThingGroup_propsAll (77.79s)
--- PASS: TestAccAWSIotThingGroup_propsDesc (78.30s)
--- PASS: TestAccAWSIotThingGroup_tags (79.17s)
--- PASS: TestAccAWSIotThingGroup_parent (79.85s)

```

### CODE REVIEW

**Comment by jhole89** [comment]
I've had this PR open for a while now - is there anything I can do to help it get reviewed?

**Comment by jamescrowley** [comment]
@jhole89 would be great to include support for attaching policies to this too. But until we hear anything from our Hashicorp friends I'd understand not bothering right now... 🤔

**Comment by jhole89** [comment]
@jamescrowley absolutely - my intention was to keep this small and do the policy attachments separately once this was merged, because AFAIK attachments would require an additional `thing_group_attachment` resource

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by ewbankkit** [comment]
Superseded by #16863.

**Comment by ewbankkit** [comment]
@jhole89 Thanks for the contribution :tada: :clap:.

**Pull request closed without merging**
