### PR TITLE
Fix docs for aws_config_delivery_channel resource

### PR DESCRIPTION
**Pull request by posquit0**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

`delivery_frequency` is required, not optional.

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @posquit0 👋 Thank you for taking the time to raise this. I took a look at the [provider code](https://github.com/hashicorp/terraform-provider-aws/blob/fec3fc1d15f72daa9a9ddf7ed90ec79bfca6c140/internal/service/configservice/delivery_channel.go#L64-L68) as well as the [AWS API documentation](https://docs.aws.amazon.com/config/latest/APIReference/API_ConfigSnapshotDeliveryProperties.html#API_ConfigSnapshotDeliveryProperties_Contents) and the [Go SDK](https://docs.aws.amazon.com/sdk-for-go/api/service/configservice/#ConfigSnapshotDeliveryProperties) and everything seems to indicate that this is indeed an optional parameter. Did you experience something different that led you to believe this was a required parameter?

**Comment by posquit0** [comment]
@justinretzolk yes, `snapshot_delivery_properties` is optional, but not `delivery_frequency`.

```hcl
# Works
resource "aws_config_delivery_channel" "foo" {
  name           = "example"
  s3_bucket_name = aws_s3_bucket.b.bucket
}

# Works
resource "aws_config_delivery_channel" "foo" {
  name           = "example"
  s3_bucket_name = aws_s3_bucket.b.bucket

  snapshot_delivery_properties {
    delivery_frequency = "One_Hour"
  }
}

# Not works
resource "aws_config_delivery_channel" "foo" {
  name           = "example"
  s3_bucket_name = aws_s3_bucket.b.bucket

  snapshot_delivery_properties {
    delivery_frequency = null
  }
}

# Not works
resource "aws_config_delivery_channel" "foo" {
  name           = "example"
  s3_bucket_name = aws_s3_bucket.b.bucket

  snapshot_delivery_properties {}
}
```

When I try without the definition of `delivery_frequency`, the following error occured. `module.config_recorder` is just wrapper module.
  - https://github.com/tedilabs/terraform-aws-security/blob/main/modules/config-recorder/main.tf

```
module.config_recorder__master.aws_config_delivery_channel.this: Modifying... [id=master]
╷
│ Error: Plugin did not respond
│
│   with module.config_recorder__master.aws_config_delivery_channel.this,
│   on ../../../../terraform-aws-security/modules/config-recorder/main.tf line 64, in resource "aws_config_delivery_channel" "this":
│   64: resource "aws_config_delivery_channel" "this" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ApplyResourceChange call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-aws_v3.69.0_x5 plugin:

panic: interface conversion: interface {} is nil, not map[string]interface {}

goroutine 77 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/configservice.resourceDeliveryChannelPut(0xc00196e680, 0x8cea6e0, 0xc000793600, 0x0, 0xffffffffffffffff)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/hashicorp/terraform-provider-aws/internal/service/configservice/delivery_channel.go:97 +0x84d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xc000ca0d20, 0xaf56ae8, 0xc0018ff1c0, 0xc00196e680, 0x8cea6e0, 0xc000793600, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:363 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000ca0d20, 0xaf56ae8, 0xc0018ff1c0, 0xc0019625b0, 0xc00196e500, 0x8cea6e0, 0xc000793600, 0x0, 0x0, 0x0, ...)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/resource.go:475 +0x390
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000310f18, 0xaf56ae8, 0xc0018ff1c0, 0xc001960780, 0xc0018ff1c0, 0x9d2e4a0, 0xc00194b800)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-sdk/v2@v2.9.0/helper/schema/grpc_provider.go:977 +0xacf
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc001fd1460, 0xaf56b90, 0xc0018ff1c0, 0xc00012a930, 0xc001fd1460, 0xc00194b800, 0xc002010ba0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/tf5server/server.go:332 +0xb5
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x9d2e4a0, 0xc001fd1460, 0xaf56b90, 0xc00194b800, 0xc001607f20, 0x0, 0xaf56b90, 0xc00194b800, 0xc001952240, 0x20e)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/github.com/hashicorp/terraform-plugin-go@v0.4.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000233880, 0xaf832d8, 0xc00178f380, 0xc000122500, 0xc00179ac30, 0xfa43ea0, 0x0, 0x0, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1194 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000233880, 0xaf832d8, 0xc00178f380, 0xc000122500, 0x0)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:1517 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc0011ab500, 0xc000233880, 0xaf832d8, 0xc00178f380, 0xc000122500)
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:859 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
	/opt/teamcity-agent/work/5d79fe75d4460a2f/pkg/mod/google.golang.org/grpc@v1.32.0/server.go:857 +0x1fd

Error: The terraform-provider-aws_v3.69.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
```

**Comment by posquit0** [comment]
@justinretzolk Please check my comment. :)

**Comment by justinretzolk** [comment]
Hey @posquit0 👋 Thanks for the additional clarification. In the case of the two not working examples you provided, you _are_ passing `delivery_frequency` and `snapshot_delivery_properties` respectively, however, you are passing null values. This behaves differently than omitting the declaration entirely, which is what "optional" means in this context.

While it's not _exactly_ the same thing as you're seeing here, some of this behavior is mentioned in the [attributes as blocks](https://www.terraform.io/language/attr-as-blocks#arbitrary-expressions-with-argument-syntax) documentation. I tried to find a more specific documentation page, but haven't been able to yet. Given that this is expected behavior, I'm going to close this PR. If you feel I've done this in error, please do let me know, and we can continue the discussion.

**Comment by posquit0** [comment]
@justinretzolk I understand first case is expected. However, is the second case also expected behavior?

```hcl
# Not Working
resource "aws_config_delivery_channel" "foo" {
  name           = "example"
  s3_bucket_name = aws_s3_bucket.b.bucket

  snapshot_delivery_properties {}
}
```

I cannot agree because the following code is working when I tried with another similar resource [`aws_config_config_rule`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule). `aws_config_config_rule` resource also has `scope` block which includes only `optional` attributes.

```hcl
resource "aws_config_config_rule" "this" {
  name        = "test"

  source {
    owner             = "AWS"
    source_identifier = "ROOT_ACCOUNT_MFA_ENABLED"
  }

  scope {}
}
```

**Comment by posquit0** [comment]
@justinretzolk Could you check my comment? 😄

**Comment by posquit0** [comment]
@justinretzolk Could you check my comment? :)

**Comment by justinretzolk** [comment]
Hey @posquit0 👋 Thanks for following up, and happy new year! Apologies for the delays! I've been out on holiday, but absolutely wanted to circle back to this. I dug a bit and I believe I've found why there's a difference here. That said, I want to make sure to mention that I would not consider myself a Go developer;  I'm the community manager for this provider. If you feel I've misinterpreted my findings, I'd be happy to loop someone else in to take a look, because I want to make sure the provider is behaving how you -- the one _using_ the provider -- expects it to!

Looking at `aws_config_config_rule`, the `scope` argument is pulled in from the configuration [here](https://github.com/hashicorp/terraform-provider-aws/blob/8eef5183e995f2247ede51da48916d2197fdfb67/internal/service/configservice/config_rule.go#L159). This uses a function that returns `nil` anyways if the value is not set ([function definition here](https://github.com/hashicorp/terraform-provider-aws/blob/8eef5183e995f2247ede51da48916d2197fdfb67/internal/service/configservice/flex.go#L72-L74)), so explicitly setting it to a `nil` value (by way of `scope {}` in the configuration) ultimately does the same thing as not setting it at all. 

On the other hand, `aws_config_delivery_channel` handles the `snapshot_delivery_properties` a bit differently. Specifically, I believe the error from the stack trace is coming from [this bit of code](https://github.com/hashicorp/terraform-provider-aws/blob/8eef5183e995f2247ede51da48916d2197fdfb67/internal/service/configservice/delivery_channel.go#L95-L97), where: 

```go
if p, ok := d.GetOk("snapshot_delivery_properties"); ok
```

...will have `ok` set to `true` (`snapshot_delivery_properties` _is_ set within the config, just explicitly to a `nil` value), so the process proceeds. Upon proceeding:

```go
propertiesBlocks := p.([]interface{})
block := propertiesBlocks[0].(map[string]interface{})
```

...will panic, as `propertiesBlock[0]` does not contain a `map[string]interface{}`; it's `nil` (admittedly, this is bumping up against the edge of my Go knowledge, I'm referencing the [type assertion](https://go.dev/tour/methods/15) section of the Tour of Go to brush up on my knowledge of how this works). This panic is then what you're seeing in the Terraform output.

Thank you again for taking the time to follow up, and for providing the other example of `aws_config_config_rule`; that gave me a bit more to go on in digging into this, and forced me to brush up on some things I haven't thought about in a while! I appreciate the discussion, and would be happy to continue it if you'd like.

**Pull request closed without merging**
