### PR TITLE
update the list of blueprint IDs supported by aws_lightsail_instance

### PR DESCRIPTION
**Pull request by poxrud**
Update the outdated list of Blueprint IDs supported by aws_lightsail_instance. The new list is based on the `aws lightsail get-blueprints` command.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by poxrud** [comment]
Looks like one of the checks failed but I don't think that it is related to my PR, since my change only touches one markdown file.

**Review by bflad — CHANGES_REQUESTED** [review]
Hi @poxrud 👋  Thank you for submitting this documentation update. Rather than manually updating this blueprint ID listing, which will continually be out of date and potentially invalid across differing AWS Regions, can you please change this page to:

* Remove the Blueprints section altogether
* Add the AWS CLI command to the `blueprint_id` argument description as a new sentence at the end

Thanks!

**Comment by poxrud** [comment]
done

**Review by bflad — APPROVED** [review]
Looks great, thanks @poxrud 🚀

**Pull request merged**
