### PR TITLE
resource/aws_ec2_client_vpn_endpoint: self service portal options

### LINKED ISSUE #16019: Client VPN Endpoint - Add Optional Self-Service Portal Arguments
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This request asks for the ability to add the _**optional**_ Self-service SAML provider ARN within the authentication option for a Client VPN (CVPN) endpoint using Federated authentication as well as the option to enable the self-service portal.

Based on the release by AWS today (11/4/20), Client VPN now supports a self-service portal to download VPN profiles and desktop applications. 

### New or Affected Resource(s)

* aws_ec2_client_vpn_endpoint

```hcl
self_service_portal

authentication_options {
    self_service_saml_provider_arn
  }

```

### Potential Terraform Configuration

```hcl
resource "aws_ec2_client_vpn_endpoint" "example" {
  description            = "terraform-clientvpn-example"
  server_certificate_arn = aws_acm_certificate.cert.arn
  client_cidr_block      = "10.0.0.0/16"
  split_tunnel = true
  self_service_portal = true

  authentication_options {
    type                       = "federated-authentication"
    saml_provider_arn          = aws_iam_saml_provider.okta.arn
    self_service_saml_provider_arn = aws_iam_saml_provider.okta_self_service.arn
  }

  connection_log_options {
    enabled               = true
    cloudwatch_log_group  = aws_cloudwatch_log_group.lg.name
    cloudwatch_log_stream = aws_cloudwatch_log_stream.ls.name
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2020/11/aws-client-vpn-announces-self-service-portal/
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateClientVpnEndpoint.html
* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_FederatedAuthenticationRequest.html

### PR DESCRIPTION
**Pull request by nbsdan**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #16019

Output from acceptance testing:

Need help with running acceptance tests

**Unable to run acceptance tests as I do not have an AWS account I can use**

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by guilhermeblanco** [comment]
Any luck into getting this reviewed/merged? It's been hanging around for over a quarter without any feedback.
It's been so long that it's staling and now conflicts are happening.

**Comment by antgel** [comment]
@nbsdan Shame that this was hanging around for so long and now there's a conflict. Can you rebase your commit in the meantime and hopefully someone from the Terraform team will be along at some point?

**Review by jeremiah-norris-champ — APPROVED** [review]

**Comment by aidan-mundy** [comment]
@breathingdust I created #20846 as a replacement for this MR with the merge conflict resolved.

**Comment by ewbankkit** [comment]
Replaced by #20846.

@nbsdan Thanks for the contribution :tada: :clap:.

**Pull request closed without merging**
