### PR TITLE
Add the option to preserve the source data type for S3 output format…

### LINKED ISSUE #26372: appflow_flow resources misses 'preserveSourceDataTyping ' configuration option for  'S3 Output Format Config'
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v1.1.6
on linux_amd64                                                                                                          
+ provider registry.terraform.io/hashicorp/aws v4.26.0 

### Affected Resource(s)

* appflow_flow

### Expected Behavior

appflow_flow resources contains 'preserveSourceDataTyping ' configuration option for  'S3 Output Format Config' for 'PARQUET' file_type.

### Actual Behavior

appflow_flow resources  **misses** 'preserveSourceDataTyping ' configuration option for  'S3 Output Format Config' for 'PARQUET' file_type[1].

### References
[1] - https://registry.terraform.io/providers/hashicorp/aws/4.26.0/docs/resources/appflow_flow

### PR DESCRIPTION
**Pull request by kristofmartens**
APPFLOW: Add support for preserving source data types in S3 outputs for Parquet file types

Enhancement resolving ([#26372](https://github.com/hashicorp/terraform-provider-aws/issues/26372))

### Description
Add `preserve_source_data_typing` parameter in the `s3_output_format_config` option block that was missing in the current implementation.

### Relations
Closes #26372

### Output from Acceptance Testing
```
❯ make testacc TESTS=TestAccAppFlowFlow PKG=appflow
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20 -run='TestAccAppFlowFlow'  -timeout 180m
=== RUN   TestAccAppFlowFlow_basic
=== PAUSE TestAccAppFlowFlow_basic
=== RUN   TestAccAppFlowFlow_update
=== PAUSE TestAccAppFlowFlow_update
=== RUN   TestAccAppFlowFlow_TaskProperties
=== PAUSE TestAccAppFlowFlow_TaskProperties
=== RUN   TestAccAppFlowFlow_tags
=== PAUSE TestAccAppFlowFlow_tags
=== RUN   TestAccAppFlowFlow_disappears
=== PAUSE TestAccAppFlowFlow_disappears
=== CONT  TestAccAppFlowFlow_basic
=== CONT  TestAccAppFlowFlow_disappears
=== CONT  TestAccAppFlowFlow_tags
=== CONT  TestAccAppFlowFlow_TaskProperties
=== CONT  TestAccAppFlowFlow_update
--- PASS: TestAccAppFlowFlow_disappears (47.72s)
--- PASS: TestAccAppFlowFlow_TaskProperties (48.29s)
--- PASS: TestAccAppFlowFlow_basic (54.83s)
--- PASS: TestAccAppFlowFlow_update (88.06s)
--- PASS: TestAccAppFlowFlow_tags (128.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	145.714s
```

### CODE REVIEW

**Comment by kristofmartens** [comment]
Any idea when this PR could be reviewed/merged/released?

**Comment by rpawlaszek** [comment]
> Any idea when this PR could be reviewed/merged/released?

Is there an ETA on this PR?

**Comment by dernat71** [comment]
That'd be awesome to merge this PR as we need it in my team!

**Comment by kristofmartens** [comment]
Guess this PR is here to die as long as there does not seem to be a way to get their attention... I rather have the devs decline it...

**Comment by HannesDS** [comment]
+ 1

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTARGS='-run=TestAccAppFlowFlow_' PKG=appflow

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appflow/... -v -count 1 -parallel 20  -run=TestAccAppFlowFlow_ -timeout 180m
--- PASS: TestAccAppFlowFlow_disappears (18.06s)
--- PASS: TestAccAppFlowFlow_TaskProperties (18.67s)
--- PASS: TestAccAppFlowFlow_basic (20.96s)
--- PASS: TestAccAppFlowFlow_update (30.93s)
--- PASS: TestAccAppFlowFlow_S3_outputFormatConfig_ParquetFileType (32.91s)
--- PASS: TestAccAppFlowFlow_tags (47.46s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appflow	50.402s
```

**Pull request merged**
