### PR TITLE
Adds `metrics_config` to aws_lambda_event_source_mapping

### LINKED ISSUE #40275: CloudWatch metrics for Lambda Event Source Mappings
> AWS Lambda announces new Amazon CloudWatch metrics for Lambda Event Source Mappings (ESMs), which provide customers visibility into the processing state of events read by ESMs that subscribe to Amazon SQS, Amazon Kinesis, and Amazon DynamoDB event sources.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-cloudwatch-metrics-aws-lambda-esms/)
* [Blog post](https://aws.amazon.com/blogs/compute/introducing-new-event-source-mapping-esm-metrics-for-aws-lambda/)

### Affected Resource(s) and/or Data Source(s)

* `aws_lambda_event_source_mapping`

### Potential Terraform Configuration

```terraform
resource "aws_lambda_event_source_mapping" "example" {
  metrics_config {
    metrics = ["EventCount"]
  }
}
```

### PR DESCRIPTION
**Pull request by amardatar**
### Description

This PR adds support for `metrics_config` in the `aws_lambda_event_source_mapping` resource. Copied from the related issue:

-----

> AWS Lambda announces new Amazon CloudWatch metrics for Lambda Event Source Mappings (ESMs), which provide customers visibility into the processing state of events read by ESMs that subscribe to Amazon SQS, Amazon Kinesis, and Amazon DynamoDB event sources.

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/11/amazon-cloudwatch-metrics-aws-lambda-esms/)

* [Blog post](https://aws.amazon.com/blogs/compute/introducing-new-event-source-mapping-esm-metrics-for-aws-lambda/)

### Affected Resource(s) and/or Data Source(s)

* `aws_lambda_event_source_mapping`

### Potential Terraform Configuration

```hcl
resource "aws_lambda_event_source_mapping" "example" {
  metrics_config {
    metrics = ["EventCount"]
  }
}
```

-----

### Relations

Closes #40275 

### References

[Docs](https://docs.aws.amazon.com/lambda/latest/dg/monitoring-metrics-types.html#event-source-mapping-metrics) for Event Source Mapping Metrics

[API Reference](https://docs.aws.amazon.com/lambda/latest/api/API_EventSourceMappingMetricsConfig.html) for the EventSourceMappingMetricsConfig

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccLambdaEventSourceMapping_SQS_metricsConfig PKG=lambda
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaEventSourceMapping_SQS_metricsConfig'  -timeout 360m
2024/11/26 23:53:31 Initializing Terraform AWS Provider...
=== RUN   TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== PAUSE TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== CONT  TestAccLambdaEventSourceMapping_SQS_metricsConfig
--- PASS: TestAccLambdaEventSourceMapping_SQS_metricsConfig (96.66s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lambda     101.640s
```

### CODE REVIEW

**Comment by amardatar** [comment]
Created a PR for this as it looked straight-forward enough, and something I'm looking to use. That said - I'm new to Go and to this project so please call out if I should be changing anything in here or am not following standards.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLambdaEventSourceMapping_Kinesis_basic\|TestAccLambdaEventSourceMapping_SQS_metricsConfig' PKG=lambda
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaEventSourceMapping_Kinesis_basic\|TestAccLambdaEventSourceMapping_SQS_metricsConfig -timeout 360m
2024/11/27 09:08:57 Initializing Terraform AWS Provider...
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_basic
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_basic
=== RUN   TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== PAUSE TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_basic
=== CONT  TestAccLambdaEventSourceMapping_SQS_metricsConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_basic (67.84s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_metricsConfig (97.77s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	103.267s
```

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS='-run=TestAccLambdaEventSourceMapping_Kinesis_basic\|TestAccLambdaEventSourceMapping_SQS_metricsConfig' PKG=lambda

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/lambda/... -v -count 1 -parallel 20  -run=TestAccLambdaEventSourceMapping_Kinesis_basic\|TestAccLambdaEventSourceMapping_SQS_metricsConfig -timeout 360m
2024/11/27 10:32:29 Initializing Terraform AWS Provider...
=== RUN   TestAccLambdaEventSourceMapping_Kinesis_basic
=== PAUSE TestAccLambdaEventSourceMapping_Kinesis_basic
=== RUN   TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== PAUSE TestAccLambdaEventSourceMapping_SQS_metricsConfig
=== CONT  TestAccLambdaEventSourceMapping_Kinesis_basic
=== CONT  TestAccLambdaEventSourceMapping_SQS_metricsConfig
--- PASS: TestAccLambdaEventSourceMapping_Kinesis_basic (75.07s)
--- PASS: TestAccLambdaEventSourceMapping_SQS_metricsConfig (109.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	116.254s
```

**Comment by ewbankkit** [comment]
@amardatar Thanks for the contribution :tada: :clap:.

**Pull request merged**
