### PR TITLE
Audio normalization and remix not computed

### PR DESCRIPTION
**Pull request by LasseEmilHildebrandt**
### Description

The audio normalization and audio remix settings are not actually computed. 

These fields have to be actively set, in order to be populated. This causes the 'creation-diff' to be unnecessary confusing. 

### Relations

Relates #29825
Relates #27824

### CODE REVIEW

**Comment by LasseEmilHildebrandt** [comment]
> Hey @LasseEmilHildebrandt 👋 Thank you very much for your contribution! At times, our maintainers need to make direct edits to pull requests in order to help get it ready to be merged. Your current settings do not allow maintainers to make such edits. To help facilitate this, update your pull request to allow such edits as described in GitHub's [Allowing changes to a pull request branch created from a fork](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/allowing-changes-to-a-pull-request-branch-created-from-a-fork) documentation. (If you're using a fork owned by an organization, your organization may not allow you to change this setting. If that is the case, let us know.)

We are aware of this issue, and are currently unable to fix this.

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thanks for the contribution! Overall the PR looks good. Before I run test, can you merge/rebase this PR with main? A few dependencies have been added since last week.

**Comment by LasseEmilHildebrandt** [comment]
Thanks for the review, @johnsonaj - The PR has been rebased unto master.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTS=TestAccMediaLiveChannel_ PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20 -run='TestAccMediaLiveChannel_'  -timeout 180m
--- PASS: TestAccMediaLiveChannel_disappears (71.42s)
--- PASS: TestAccMediaLiveChannel_hls (87.21s)
--- PASS: TestAccMediaLiveChannel_audioDescriptions_codecSettings (100.72s)
--- PASS: TestAccMediaLiveChannel_basic (150.37s)
--- PASS: TestAccMediaLiveChannel_m2ts_settings (155.12s)
--- PASS: TestAccMediaLiveChannel_update (164.37s)
 --- PASS: TestAccMediaLiveChannel_updateTags (205.26s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (216.16s)
--- PASS: TestAccMediaLiveChannel_status (219.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	222.791s
```

**Comment by johnsonaj** [comment]
@LasseEmilHildebrandt thank you for the contribution 🎉

**Pull request merged**
