### PR TITLE
RDS - Throw error when name or username supplied on DB snapshot restore

### LINKED ISSUE #17037: RDS instance got recreated after another apply without any change
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/aws v3.23.0
+ provider registry.terraform.io/hashicorp/local v1.4.0
+ provider registry.terraform.io/hashicorp/null v2.1.2
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

* RDS instance

### Terraform Configuration Files

The output of `terraform plan`:
```hcl
-/+ resource "aws_db_instance" "default" {
      ~ address                               = "a-staging-test-rds.xxxx.us-east-1.rds.amazonaws.com" -> (known after apply)
        allocated_storage                     = 20
        allow_major_version_upgrade           = false
        apply_immediately                     = true
      ~ arn                                   = "arn:aws:rds:us-east-1:xxx:db:a-staging-test-rds" -> (known after apply)
        auto_minor_version_upgrade            = true
      ~ availability_zone                     = "us-east-1b" -> (known after apply)
        backup_retention_period               = 0
        backup_window                         = "22:00-03:00"
        ca_cert_identifier                    = "rds-ca-2019"
      + character_set_name                    = (known after apply)
        copy_tags_to_snapshot                 = true
        db_subnet_group_name                  = "a-staging-test-rds"
        delete_automated_backups              = true
        deletion_protection                   = false
      - enabled_cloudwatch_logs_exports       = [] -> null
      ~ endpoint                              = "a-staging-test-rds.xxx.us-east-1.rds.amazonaws.com:3306" -> (known after apply)
        engine                                = "mysql"
        engine_version                        = "8.0.20"
        final_snapshot_identifier             = "a-staging-test-rds-final-snapshot"
      ~ hosted_zone_id                        = "xxx" -> (known after apply)
        iam_database_authentication_enabled   = false
      ~ id                                    = "a-staging-test-rds" -> (known after apply)
        identifier                            = "a-staging-test-rds"
      + identifier_prefix                     = (known after apply)
        instance_class                        = "db.t2.small"
        iops                                  = 0
      + kms_key_id                            = (known after apply)
      ~ latest_restorable_time                = "0001-01-01T00:00:00Z" -> (known after apply)
      ~ license_model                         = "general-public-license" -> (known after apply)
        maintenance_window                    = "mon:03:00-mon:04:00"
        max_allocated_storage                 = 1000
        monitoring_interval                   = 0
      + monitoring_role_arn                   = (known after apply)
        multi_az                              = false
      + name                                  = "teststage" # forces replacement
        option_group_name                     = "a-staging-test-rds"
        parameter_group_name                  = "a-staging-test-rds"
        password                              = (sensitive value)
        performance_insights_enabled          = false
      + performance_insights_kms_key_id       = (known after apply)
      ~ performance_insights_retention_period = 0 -> (known after apply)
        port                                  = 3306
        publicly_accessible                   = false
      ~ replicas                              = [] -> (known after apply)
      ~ resource_id                           = "db-xxx" -> (known after apply)
      - security_group_names                  = [] -> null
        skip_final_snapshot                   = true
        snapshot_identifier                   = "orig-stage-database"
      ~ status                                = "available" -> (known after apply)
        storage_encrypted                     = false
        storage_type                          = "gp2"
        tags                                  = {
            "Attributes"  = "rds"
            "Environment" = "staging"
            "Name"        = "a-staging-test-rds"
            "Namespace"   = "a"
        }
      + timezone                              = (known after apply)
        username                              = "admin"
        vpc_security_group_ids                = [
            "sg-xxx",
        ]
    }
```

### Expected Behavior
RDS instance wouldn't be recreated if no change on tf files

### Actual Behavior

RDS instance got recreated after another apply without any change

### Steps to Reproduce

1. Use snapshot_identifier for create a RDS instance
2. `terraform apply`
3. RDS instance got created
4. `terraform apply` without any change
5. RDS instance got recreated

### PR DESCRIPTION
**Pull request by brent-au**
This PR will introduce a behaviour to throw an error when restoring from a MySQL, PostgreSQL or MariaDB RDS snapshot and a `name` or `username` attribute is supplied as part of a template.

This is to change the current behaviour where the RDS instance is restored from snapshot, but subsequent applies of the same template cause the RDS to be recreated because the `name` and/or `username` attribute has not been honoured during creation.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17037 

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
An error will now be thrown when supplying a name and/or username attribute when restoring a snapshot to a MySQL, PostgreSQL or MariaDB to an RDS instance.
```

Output from acceptance testing:

I modifed the MySQL snapshot restore with engine version test template [here](https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_db_instance_test.go#L4523-L4540) to include a `name` attribute for the `mysql_restore` resource, to provoke an error

```
$ make testacc TESTARGS='-run=TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion -timeout 120m
=== RUN   TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
=== PAUSE TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
=== CONT  TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion
    resource_aws_db_instance_test.go:2193: Step 1/1 error: Error running apply: 
        Error: Error restoring database from AWS DB Snapshot: tf-acc-test-4765336381358846440: name attribute is not supported when engine is mysql
        
        

--- FAIL: TestAccAWSDBInstance_MySQL_SnapshotRestoreWithEngineVersion (590.06s)
FAIL
FAIL    github.com/terraform-providers/terraform-provider-aws/aws       590.092s
FAIL
make: *** [GNUmakefile:28: testacc] Error 1
...
```

### CODE REVIEW

**Review by gdavison — APPROVED** [review]
Thanks for the PR, @brent-au! I've moved the validation to plan-time and fixed an acceptance test that now causes an error

**Comment by konstl000** [comment]
It seems, that raising an error is not enough, since the name of the DB instance is present in the state after it is created from the snapshot. It seems that this PR introduces https://github.com/hashicorp/terraform-provider-aws/issues/17722.

**Comment by JeremyPDC** [comment]
> It seems, that raising an error is not enough, since the name of the DB instance is present in the state after it is created from the snapshot. It seems that this PR introduces #17722.

Yeah we are having this problem now.

**Comment by aleon1220** [comment]
is happenning to me now and i am on terraform cloud. I believe the conflict is in
the duplicate use of the var.snapshot_identifier

Take a look at line 63 and 139

https://github.com/terraform-aws-modules/terraform-aws-rds/blob/master/modules/db_instance/main.tf#L139

**Comment by aleon1220** [comment]
I think the majority of the community is tracking the issue at https://github.com/hashicorp/terraform-provider-aws/issues/17712

**Pull request merged**
