### PR TITLE
r/aws_default_vpc: Fix adoption of default VPC with generated IPv6

### LINKED ISSUE #29077: [Bug]: Tries to disassociate IPv6 network on initial adoption of default VPC
### Terraform Core Version

1.3.7

### AWS Provider Version

4.51.0

### Affected Resource(s)

* aws_default_vpc

### Expected Behavior

The default VPC can be adopted even with subnets and IPv6 CIDR already assigned.

### Actual Behavior

The provider tries to disassociate the provided IPv6 block, which fails at it is used by subnets.

### Relevant Error/Panic Output Snippet

```shell
│ Error: creating EC2 Default VPC: disassociating IPv6 CIDR block (vpc-cidr-assoc-009dd142bb1b2b2a4): InvalidCidrBlock.InUse: The vpc vpc-0fbe24f0d3c0c1f67 currently has a subnet within CIDR block 2600:1f18:0000:0000::/56
│ 	status code: 400, request id: b8dbc589-e118-4f75-a773-2b79c83b87ba
```

### Terraform Configuration Files

```terraform
resource "aws_default_vpc" "default" {
  assign_generated_ipv6_cidr_block = true
}
```

### Steps to Reproduce

* Have a default VPC available, assigned with a generated IPv6 block and subnets (for example from an earlier Terraform run)
* Try adopting into Terraform with `aws_default_vpc`

### Debug Output

```
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: [DEBUG] [aws-sdk-go] DEBUG: Request ec2/DisassociateVpcCidrBlock Details:
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: ---[ REQUEST POST-SIGN ]-----------------------------
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: POST / HTTP/1.1
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Host: ec2.us-east-1.amazonaws.com
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: User-Agent: APN/1.0 HashiCorp/1.0 Terraform/1.3.7 (+https://www.terraform.io) terraform-provider-aws/4.51.0 (+https://registry.terraform.io/providers/hashicorp/aws) aws-sdk-go/1.44.182 (go1.19.3; linux; amd64)
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Content-Length: 97
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Content-Type: application/x-www-form-urlencoded; charset=utf-8
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: X-Amz-Date: 20230124T173008Z
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Accept-Encoding: gzip
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5:
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Action=DisassociateVpcCidrBlock&AssociationId=vpc-cidr-assoc-009dd142bb1b2b2a4&Version=2016-11-15
2023-01-24T18:30:08.426+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: -----------------------------------------------------
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: [DEBUG] [aws-sdk-go] DEBUG: Response ec2/DisassociateVpcCidrBlock Details:
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: ---[ RESPONSE ]--------------------------------------
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: HTTP/1.1 400 Bad Request
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Connection: close
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Transfer-Encoding: chunked
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Cache-Control: no-cache, no-store
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Content-Type: text/xml;charset=UTF-8
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Date: Tue, 24 Jan 2023 17:30:08 GMT
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Server: AmazonEC2   
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Strict-Transport-Security: max-age=31536000; includeSubDomains
2023-01-24T18:30:08.590+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: Vary: accept-encoding
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: X-Amzn-Requestid: e5e318c9-7815-4218-837a-a960d5bc029a
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5:
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5:
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: -----------------------------------------------------
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: [DEBUG] [aws-sdk-go] <?xml version="1.0" encoding="UTF-8"?>
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: <Response><Errors><Error><Code>InvalidCidrBlock.InUse</Code><Message>The vpc vpc-0fbe24f0d3c0c1f67 currently has a subnet within CIDR block 2600:1f18:000:0000::/56</Message></Error></Errors><RequestID>e5e318c9-7815-4218-837a-a960d5bc029a</RequestID></Response>
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5: [DEBUG] [aws-sdk-go] DEBUG: Validate Response ec2/DisassociateVpcCidrBlock failed, attempt 0/25, error InvalidCidrBlock.InUse: The vpc vpc-0fbe24f0d3c0c1f67 currently has a subnet within CIDR block 2600:1f18:0000:0000::/56
2023-01-24T18:30:08.591+0100 [DEBUG] provider.terraform-provider-aws_v4.51.0_x5:        status code: 400, request id: e5e318c9-7815-4218-837a-a960d5bc029a
2023-01-24T18:30:08.591+0100 [ERROR] provider.terraform-provider-aws_v4.51.0_x5: Response contains error diagnostic: diagnostic_detail= diagnostic_severity=ERROR diagnostic_summary="creating EC2 Default VPC: disassociating IPv6 CIDR block (vpc-cidr-assoc-009dd142bb1b2b2a4): InvalidCidrBlock.InUse: The vpc vpc-0fbe24f0d3c0c1f67 currently has a subnet within CIDR block 2600:1f18:0000:0000::/56
        status code: 400, request id: e5e318c9-7815-4218-837a-a960d5bc029a" tf_proto_version=5.3 tf_req_id=f173acd9-3e21-c2a1-215d-cfbebd2bcca0 tf_rpc=ApplyResourceChange @module=sdk.proto tf_provider_addr=registry.terraform.io/hashicorp/aws tf_resource_type=aws_default_vpc @caller=github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/diag/diagnostics.go:55 timestamp=2023-01-24T18:30:08.591+0100
2023-01-24T18:30:08.596+0100 [ERROR] vertex "module.account_region.aws_default_vpc.default" error: creating EC2 Default VPC: disassociating IPv6 CIDR block (vpc-cidr-assoc-009dd142bb1b2b2a4): InvalidCidrBlock.InUse: The vpc vpc-0fbe24f0d3c0c1f67 currently has a subnet within CIDR block 2600:1f18:0000:0000::/56
        status code: 400, request id: e5e318c9-7815-4218-837a-a960d5bc029a
```

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by waldiTM**
### Description

Adoption of a default VPC with generated IPv6 assigned fails in two different locations, where it tries to disassociate the IPv6 network instead of just accepting it.

### Relations
Closes #29077 

### Output from Acceptance Testing

```
$ TF_ACC=1 go test ./internal/service/ec2 -v -run TestAccVPCDefaultVPCAndSubnet_serial/VPC
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial
=== PAUSE TestAccVPCDefaultVPCAndSubnet_serial
=== CONT  TestAccVPCDefaultVPCAndSubnet_serial
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.assignGeneratedIPv6CIDRBlock
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.forceDestroy
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.basic
    vpc_default_vpc_test.go:54: Deleting existing default VPC: vpc-0db606da84a08dc33
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlock
    vpc_default_vpc_test.go:54: Deleting existing default VPC: vpc-01747dadcd2666107
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.forceDestroy
    vpc_default_vpc_test.go:54: Deleting existing default VPC: vpc-091a473f20dde148b
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.basic
--- PASS: TestAccVPCDefaultVPCAndSubnet_serial (174.93s)
    --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC (174.93s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.assignGeneratedIPv6CIDRBlock (14.28s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.forceDestroy (38.54s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.basic (26.79s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlock (39.73s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.forceDestroy (31.23s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.basic (24.37s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        175.015s
```

### CODE REVIEW

**Comment by waldiTM** [comment]
I have no idea how to test that condition.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% AWS_DEFAULT_REGION=eu-west-1 make testacc TESTARGS='-run=TestAccVPCDefaultVPCAndSubnet_serial/VPC' PKG=ec2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCDefaultVPCAndSubnet_serial/VPC -timeout 180m
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial
=== PAUSE TestAccVPCDefaultVPCAndSubnet_serial
=== CONT  TestAccVPCDefaultVPCAndSubnet_serial
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.forceDestroy
    vpc_default_vpc_test.go:55: Deleting existing default VPC: vpc-056e68158bc93f8d0
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption
    vpc_default_vpc_test.go:55: Deleting existing default VPC: vpc-0eb83b274f8e13fc8
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.basic
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.assignGeneratedIPv6CIDRBlock
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.forceDestroy
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.basic
    vpc_default_vpc_test.go:55: Deleting existing default VPC: vpc-091a82c426920f6e8
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlock
    vpc_default_vpc_test.go:55: Deleting existing default VPC: vpc-001969c117ec3d4a9
--- PASS: TestAccVPCDefaultVPCAndSubnet_serial (272.19s)
    --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC (272.19s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.forceDestroy (26.15s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption (81.82s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.basic (37.60s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.assignGeneratedIPv6CIDRBlock (27.46s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/existing.forceDestroy (42.06s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.basic (24.58s)
        --- PASS: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlock (32.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	277.834s
```

**Comment by ewbankkit** [comment]
Previously the new test case failed:

```console
% AWS_DEFAULT_REGION=eu-west-1 make testacc TESTARGS='-run=TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption -timeout 180m
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial
=== PAUSE TestAccVPCDefaultVPCAndSubnet_serial
=== CONT  TestAccVPCDefaultVPCAndSubnet_serial
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC
=== RUN   TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption
    vpc_default_vpc_test.go:55: Deleting existing default VPC: vpc-0bdd1e5fa648a833b
    vpc_default_vpc_test.go:333: Step 3/3 error: Error running apply: exit status 1
        
        Error: creating EC2 Default VPC: disassociating IPv6 CIDR block (vpc-cidr-assoc-0909683ed86d3f1d0): InvalidCidrBlock.InUse: The vpc vpc-01ea446519052aad3 currently has a subnet within CIDR block 2a05:d018:1715:9400::/56
        	status code: 400, request id: e9e27a73-638f-4cbb-885f-579e48f62a49
        
          with aws_default_vpc.test,
          on terraform_plugin_test.tf line 2, in resource "aws_default_vpc" "test":
           2: resource "aws_default_vpc" "test" {
        
--- FAIL: TestAccVPCDefaultVPCAndSubnet_serial (74.24s)
    --- FAIL: TestAccVPCDefaultVPCAndSubnet_serial/VPC (74.24s)
        --- FAIL: TestAccVPCDefaultVPCAndSubnet_serial/VPC/notFound.assignGeneratedIPv6CIDRBlockAdoption (74.24s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	80.229s
FAIL
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
@waldiTM Thanks for the contribution :tada: :clap:.

**Pull request merged**
