### PR TITLE
r/aws_connect_contact_flow - add new resource

### PR DESCRIPTION
**Pull request by thornleyk**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #16392 #16854

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_connect_contact_flow - add new resource
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsConnectContactFlow_'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsConnectContactFlow_ -timeout 120m
=== RUN   TestAccAwsConnectContactFlow_basic
=== PAUSE TestAccAwsConnectContactFlow_basic
=== RUN   TestAccAwsConnectContactFlow_filename
=== PAUSE TestAccAwsConnectContactFlow_filename
=== RUN   TestAccAwsConnectContactFlow_disappears
=== PAUSE TestAccAwsConnectContactFlow_disappears
=== CONT  TestAccAwsConnectContactFlow_basic
=== CONT  TestAccAwsConnectContactFlow_disappears
=== CONT  TestAccAwsConnectContactFlow_filename
--- PASS: TestAccAwsConnectContactFlow_disappears (108.34s)
--- PASS: TestAccAwsConnectContactFlow_basic (130.08s)
--- PASS: TestAccAwsConnectContactFlow_filename (153.91s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	154.043s
...
```

```
$ make testacc TESTARGS='-run=TestAccDataSourceAwsConnectContactFlow_'

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsConnectContactFlow_ -timeout 120m
=== RUN   TestAccDataSourceAwsConnectContactFlow_basic
--- PASS: TestAccDataSourceAwsConnectContactFlow_basic (107.32s)
=== RUN   TestAccDataSourceAwsConnectContactFlow_byname
--- PASS: TestAccDataSourceAwsConnectContactFlow_byname (106.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	213.692s
...
```

### CODE REVIEW

**Comment by tms2018** [comment]
Even though it doesn't strictly match the AWS API, it might be worth considering turning this into two separate resources: the contact flow and the flow actions.  It's a common pattern for two contact flows to reference each other (eg. go back to menu).  As currently implemented, this results in a cycle.

**Comment by thornleyk** [comment]
> Even though it doesn't strictly match the AWS API, it might be worth considering turning this into two separate resources: the contact flow and the flow actions. It's a common pattern for two contact flows to reference each other (eg. go back to menu). As currently implemented, this results in a cycle.

Hi, I'm unsure of what you mean by "flow actions" as a resource, this cyclic dependency will always be an issue, unless you think we run through contacts flows on initial create its an empty contact flow and then add the content?  Do you have examples of where this is implemented as an AWS pattern in the provider?

**Comment by tms2018** [comment]
By "flow actions" I mean the individual blocks which make up the flow (Disconnect, Play Prompt, etc.).  In the JSON for a contact flow, they are in an array called "Actions".

I don't know of a place where something is implemented like this in the provider, as I've only started using Terraform due to client requirements and found this pull request during my research.  But I have implemented a custom resource for the AWS CDK (which my company normally uses) to solve the same problem.

The only gotcha is, due to the API publishing the contact flow when it's created, any call to `createContactFlow` does have to have valid content for the flow.  In our case, we use the minimum valid flow with a single Disconnect action.  Then, as a second step, the flow is updated to the full flow.  This allows the flow content to link to other flows, guaranteeing that the flows are created first and no cycles are created.

I anticipate it would look something like this 

```tf
resource "aws_connect_contact_flow" "example" {
    instance_id = "aaaaaaaa-bbbb-cccc-dddd-111111111111"
    name        = "Test"
    description = "Test Contact Flow Description"
    type        = "CONTACT_FLOW"
    # content = file("flowFile")      # Possibly leave content here to optionally be filled if cycles aren't an issue  
}

resource "aws_connect_contact_flow_content" "example_content" {
    instance_id = "aaaaaaaa-bbbb-cccc-dddd-111111111111"
    contact_flow_id = aws_connect_contact_flow.example.id
    content = templatefile("flowFileWithDependencies", { otherFlowArn = aws_connect_contact_flow.other.arn })
}
```

I don't like that it requires the workaround of creating the initial minimal flow, but it's a limitation of the API that an empty flow can't be created.  Not solving the cycle issue, though, makes it ultimately unusable in a lot of cases.

**Comment by thornleyk** [comment]
> By "flow actions" I mean the individual blocks which make up the flow (Disconnect, Play Prompt, etc.). In the JSON for a contact flow, they are in an array called "Actions".
> 
> I don't know of a place where something is implemented like this in the provider, as I've only started using Terraform due to client requirements and found this pull request during my research. But I have implemented a custom resource for the AWS CDK (which my company normally uses) to solve the same problem.
> 
> The only gotcha is, due to the API publishing the contact flow when it's created, any call to `createContactFlow` does have to have valid content for the flow. In our case, we use the minimum valid flow with a single Disconnect action. Then, as a second step, the flow is updated to the full flow. This allows the flow content to link to other flows, guaranteeing that the flows are created first and no cycles are created.
> 
> I anticipate it would look something like this
> 
> ```terraform
> resource "aws_connect_contact_flow" "example" {
>     instance_id = "aaaaaaaa-bbbb-cccc-dddd-111111111111"
>     name        = "Test"
>     description = "Test Contact Flow Description"
>     type        = "CONTACT_FLOW"
>     # content = file("flowFile")      # Possibly leave content here to optionally be filled if cycles aren't an issue  
> }
> 
> resource "aws_connect_contact_flow_content" "example_content" {
>     instance_id = "aaaaaaaa-bbbb-cccc-dddd-111111111111"
>     contact_flow_id = aws_connect_contact_flow.example.id
>     content = templatefile("flowFileWithDependencies", { otherFlowArn = aws_connect_contact_flow.other.arn })
> }
> ```
> 
> I don't like that it requires the workaround of creating the initial minimal flow, but it's a limitation of the API that an empty flow can't be created. Not solving the cycle issue, though, makes it ultimately unusable in a lot of cases.

Thats going to be really difficult to synchronise the state to the remote terraform state as there is not resource id for logical parts of a contact flow definition so that your can remerge the individual actions back to an update request.  I use the API at the moment in the grain defined here very effectively, it's just not managed in the terraform lifecycle, also I cannot easily reference lambda and lex resources managed by terraform, which is what this will allow

**Comment by AdamTylerLynch** [comment]
@thornleyk did you merge in the other PR from @abebars  ? I see substantially similar code in your PR to theirs (https://github.com/hashicorp/terraform-provider-aws/pull/16709)

**Comment by thornleyk** [comment]
> @thornleyk did you merge in the other PR from @abebars  ? I see substantially similar code in your PR to theirs (https://github.com/hashicorp/terraform-provider-aws/pull/16709)

Yeah I'm still waiting on terraform to merge @abebars original PR once that happens I'll rebase and finish this PR I'm dependent on that PR

**Comment by AdamTylerLynch** [comment]
> > @thornleyk did you merge in the other PR from @abebars  ? I see substantially similar code in your PR to theirs (#16709)
> 
> Yeah I'm still waiting on terraform to merge @abebars original PR once that happens I'll rebase and finish this PR I'm dependent on that PR

I'm going to fetch upstream/main and then port some of your changes into PR #16709.

**Comment by AdamTylerLynch** [comment]
`tfproviderdocs` linter error unrelated.

**Comment by AdamTylerLynch** [comment]
```
make testacc TESTARGS='-run=TestAccDataSourceAwsConnectContact' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccDataSourceAwsConnectContact -timeout 180m
=== RUN   TestAccDataSourceAwsConnectContactFlow_basic
--- PASS: TestAccDataSourceAwsConnectContactFlow_basic (87.58s)
=== RUN   TestAccDataSourceAwsConnectContactFlow_byname
--- PASS: TestAccDataSourceAwsConnectContactFlow_byname (87.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	176.482s




make testacc TESTARGS='-run=TestAccAwsConnectContact' ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAwsConnectContact -timeout 180m
=== RUN   TestAccAwsConnectContactFlow_basic
=== PAUSE TestAccAwsConnectContactFlow_basic
=== RUN   TestAccAwsConnectContactFlow_filename
=== PAUSE TestAccAwsConnectContactFlow_filename
=== RUN   TestAccAwsConnectContactFlow_disappears
=== PAUSE TestAccAwsConnectContactFlow_disappears
=== CONT  TestAccAwsConnectContactFlow_basic
=== CONT  TestAccAwsConnectContactFlow_disappears
    resource_aws_connect_contact_flow_test.go:121: Step 1/1 error: Expected a non-empty plan, but got an empty plan
--- FAIL: TestAccAwsConnectContactFlow_disappears (86.15s)
=== CONT  TestAccAwsConnectContactFlow_filename
--- PASS: TestAccAwsConnectContactFlow_basic (109.16s)
--- PASS: TestAccAwsConnectContactFlow_filename (106.87s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	194.868s
FAIL
make: *** [testacc] Error 1

```

Need to finish the `disappears` test.

**Comment by AdamTylerLynch** [comment]
@thornleyk  can you remove the WIP prefix?

**Comment by anGie44** [comment]
Hi @thornleyk 👋 I'm giving this PR another pass before we merge. Overall it's looking great, just a couple small updates in the data source for now e.g. marking fields as `Computed` when not used as input.

**Comment by thornleyk** [comment]
> Hi @thornleyk 👋 I'm giving this PR another pass before we merge. Overall it's looking great, just a couple small updates in the data source for now e.g. marking fields as `Computed` when not used as input.

Thanks a bunch angie!!, I'll keep these updates in mind for the other resources

**Review by anGie44 — APPROVED** [review]
Thanks for contributing to this PR @thornleyk @AdamTylerLynch 🚀 ! I've added a couple finishing touches to the resource to get this into our upcoming release. 

Output of acceptance tests:
```
--- PASS: TestAccAwsConnectContactFlowDataSource_Name (87.75s)
--- PASS: TestAccAwsConnectContactFlowDataSource_ContactFlowId (123.12s)

--- PASS: TestAccAwsConnectContactFlow_serial (0.00s)
    --- PASS: TestAccAwsConnectContactFlow_serial/basic (100.41s)
    --- PASS: TestAccAwsConnectContactFlow_serial/disappears (77.36s)
    --- PASS: TestAccAwsConnectContactFlow_serial/filename (101.17s)
```

**Pull request merged**
