### PR TITLE
Add aws_amplify_app resource

### PR DESCRIPTION
**Pull request by ashishmohite**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #6917 and #11928 

AWS Amplify service client has been merged by #9874.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Resource: aws_amplify_app
```

Output from acceptance testing:

```
$ ╭─ashishmohite@Ashishs-MacBook-Pro ~/development/terraform-providers/terraform-provider-aws  ‹f-amplify-app*›
╰─$ export AWS_PROFILE=my-profile &&  make testacc TEST=./aws TESTARGS='-run=TestAccAWSAmplifyApp'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 1 -run=TestAccAWSAmplifyApp -timeout 120m
=== RUN   TestAccAWSAmplifyApp_basic
=== PAUSE TestAccAWSAmplifyApp_basic
=== RUN   TestAccAWSAmplifyApp_rename
=== PAUSE TestAccAWSAmplifyApp_rename
=== RUN   TestAccAWSAmplifyApp_description
=== PAUSE TestAccAWSAmplifyApp_description
=== RUN   TestAccAWSAmplifyApp_repository
=== PAUSE TestAccAWSAmplifyApp_repository
=== RUN   TestAccAWSAmplifyApp_buildSpec
=== PAUSE TestAccAWSAmplifyApp_buildSpec
=== RUN   TestAccAWSAmplifyApp_customRules
=== PAUSE TestAccAWSAmplifyApp_customRules
=== RUN   TestAccAWSAmplifyApp_environmentVariables
=== PAUSE TestAccAWSAmplifyApp_environmentVariables
=== RUN   TestAccAWSAmplifyApp_autoBranchCreationConfig
=== PAUSE TestAccAWSAmplifyApp_autoBranchCreationConfig
=== RUN   TestAccAWSAmplifyApp_basicAuthConfig
=== PAUSE TestAccAWSAmplifyApp_basicAuthConfig
=== RUN   TestAccAWSAmplifyApp_enableBranchAutoBuild
=== PAUSE TestAccAWSAmplifyApp_enableBranchAutoBuild
=== RUN   TestAccAWSAmplifyApp_iamServiceRoleArn
=== PAUSE TestAccAWSAmplifyApp_iamServiceRoleArn
=== RUN   TestAccAWSAmplifyApp_tags
=== PAUSE TestAccAWSAmplifyApp_tags
=== CONT  TestAccAWSAmplifyApp_basic
--- PASS: TestAccAWSAmplifyApp_basic (65.94s)
=== CONT  TestAccAWSAmplifyApp_autoBranchCreationConfig
--- PASS: TestAccAWSAmplifyApp_autoBranchCreationConfig (252.12s)
=== CONT  TestAccAWSAmplifyApp_buildSpec
--- PASS: TestAccAWSAmplifyApp_buildSpec (130.53s)
=== CONT  TestAccAWSAmplifyApp_environmentVariables
--- PASS: TestAccAWSAmplifyApp_environmentVariables (165.49s)
=== CONT  TestAccAWSAmplifyApp_customRules
--- PASS: TestAccAWSAmplifyApp_customRules (107.23s)
=== CONT  TestAccAWSAmplifyApp_tags
--- PASS: TestAccAWSAmplifyApp_tags (195.11s)
=== CONT  TestAccAWSAmplifyApp_iamServiceRoleArn
--- PASS: TestAccAWSAmplifyApp_iamServiceRoleArn (151.35s)
=== CONT  TestAccAWSAmplifyApp_enableBranchAutoBuild
--- PASS: TestAccAWSAmplifyApp_enableBranchAutoBuild (116.87s)
=== CONT  TestAccAWSAmplifyApp_basicAuthConfig
--- PASS: TestAccAWSAmplifyApp_basicAuthConfig (155.08s)
=== CONT  TestAccAWSAmplifyApp_description
--- PASS: TestAccAWSAmplifyApp_description (115.52s)
=== CONT  TestAccAWSAmplifyApp_repository
--- PASS: TestAccAWSAmplifyApp_repository (69.54s)
=== CONT  TestAccAWSAmplifyApp_rename
--- PASS: TestAccAWSAmplifyApp_rename (124.16s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1650.676s

...
```

### CODE REVIEW

**Comment by ashishmohite** [comment]
@ewbankkit who can review this PR? I need to raise subsequent PRs for various Amplify resources but those will need `aws_amplify_app` resource to be present in the core

**Comment by smorimoto** [comment]
Sorry for the sudden mention, could you review this? @DrFaust92 @bflad

**Comment by Gowiem** [comment]
@ewbankkit sorry to do it, but any chance this can get reviewed / on the roadmap? The original code for Amplify support is approaching 1 year old at this point. Appreciate taking a look! 🙏

**Comment by kierancrown** [comment]
Is anything happening with this?

**Comment by ewbankkit** [comment]
@kierancrown See #19187.

**Comment by mihaiplesa** [comment]
Looking forward to this getting in!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% AMPLIFY_GITHUB_ACCESS_TOKEN="..." AMPLIFY_GITHUB_REPOSITORY="https://github.com/ewbankkit/terraform-aws-provider-testing" make testacc TEST=./aws TESTARGS='-run=TestAccAWSAmplify_'                        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAmplify_ -timeout 180m
=== RUN   TestAccAWSAmplify_serial
=== RUN   TestAccAWSAmplify_serial/App
=== RUN   TestAccAWSAmplify_serial/App/Tags
=== PAUSE TestAccAWSAmplify_serial/App/Tags
=== RUN   TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
=== PAUSE TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
=== RUN   TestAccAWSAmplify_serial/App/BasicAuthCredentials
=== PAUSE TestAccAWSAmplify_serial/App/BasicAuthCredentials
=== RUN   TestAccAWSAmplify_serial/App/Name
=== PAUSE TestAccAWSAmplify_serial/App/Name
=== RUN   TestAccAWSAmplify_serial/App/Repository
=== PAUSE TestAccAWSAmplify_serial/App/Repository
=== RUN   TestAccAWSAmplify_serial/App/disappears
=== PAUSE TestAccAWSAmplify_serial/App/disappears
=== RUN   TestAccAWSAmplify_serial/App/BuildSpec
=== PAUSE TestAccAWSAmplify_serial/App/BuildSpec
=== RUN   TestAccAWSAmplify_serial/App/CustomRules
=== PAUSE TestAccAWSAmplify_serial/App/CustomRules
=== RUN   TestAccAWSAmplify_serial/App/Description
=== PAUSE TestAccAWSAmplify_serial/App/Description
=== RUN   TestAccAWSAmplify_serial/App/EnvironmentVariables
=== PAUSE TestAccAWSAmplify_serial/App/EnvironmentVariables
=== RUN   TestAccAWSAmplify_serial/App/IamServiceRole
=== PAUSE TestAccAWSAmplify_serial/App/IamServiceRole
=== RUN   TestAccAWSAmplify_serial/App/basic
=== PAUSE TestAccAWSAmplify_serial/App/basic
=== CONT  TestAccAWSAmplify_serial/App/Tags
=== CONT  TestAccAWSAmplify_serial/App/IamServiceRole
=== CONT  TestAccAWSAmplify_serial/App/BasicAuthCredentials
=== CONT  TestAccAWSAmplify_serial/App/BuildSpec
=== CONT  TestAccAWSAmplify_serial/App/Description
=== CONT  TestAccAWSAmplify_serial/App/EnvironmentVariables
=== CONT  TestAccAWSAmplify_serial/App/basic
=== CONT  TestAccAWSAmplify_serial/App/CustomRules
=== CONT  TestAccAWSAmplify_serial/App/Name
=== CONT  TestAccAWSAmplify_serial/App/disappears
=== CONT  TestAccAWSAmplify_serial/App/Repository
=== CONT  TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
--- PASS: TestAccAWSAmplify_serial (57.63s)
    --- PASS: TestAccAWSAmplify_serial/App (0.00s)
        --- PASS: TestAccAWSAmplify_serial/App/disappears (22.83s)
        --- PASS: TestAccAWSAmplify_serial/App/Repository (32.26s)
        --- PASS: TestAccAWSAmplify_serial/App/Name (39.13s)
        --- PASS: TestAccAWSAmplify_serial/App/Tags (48.31s)
        --- PASS: TestAccAWSAmplify_serial/App/CustomRules (49.94s)
        --- PASS: TestAccAWSAmplify_serial/App/basic (51.08s)
        --- PASS: TestAccAWSAmplify_serial/App/BuildSpec (53.59s)
        --- PASS: TestAccAWSAmplify_serial/App/IamServiceRole (53.79s)
        --- PASS: TestAccAWSAmplify_serial/App/EnvironmentVariables (56.12s)
        --- PASS: TestAccAWSAmplify_serial/App/Description (56.80s)
        --- PASS: TestAccAWSAmplify_serial/App/BasicAuthCredentials (57.00s)
        --- PASS: TestAccAWSAmplify_serial/App/AutoBranchCreationConfig (57.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	60.642s
```

##### GovCloud

```console
% AMPLIFY_GITHUB_ACCESS_TOKEN="..." AMPLIFY_GITHUB_REPOSITORY="https://github.com/ewbankkit/terraform-aws-provider-testing" make testacc TEST=./aws TESTARGS='-run=TestAccAWSAmplify_'
=== RUN   TestAccAWSAmplify_serial
=== RUN   TestAccAWSAmplify_serial/App
=== RUN   TestAccAWSAmplify_serial/App/basic
=== PAUSE TestAccAWSAmplify_serial/App/basic
=== RUN   TestAccAWSAmplify_serial/App/disappears
=== PAUSE TestAccAWSAmplify_serial/App/disappears
=== RUN   TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
=== PAUSE TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
=== RUN   TestAccAWSAmplify_serial/App/BasicAuthCredentials
=== PAUSE TestAccAWSAmplify_serial/App/BasicAuthCredentials
=== RUN   TestAccAWSAmplify_serial/App/IamServiceRole
=== PAUSE TestAccAWSAmplify_serial/App/IamServiceRole
=== RUN   TestAccAWSAmplify_serial/App/Tags
=== PAUSE TestAccAWSAmplify_serial/App/Tags
=== RUN   TestAccAWSAmplify_serial/App/BuildSpec
=== PAUSE TestAccAWSAmplify_serial/App/BuildSpec
=== RUN   TestAccAWSAmplify_serial/App/CustomRules
=== PAUSE TestAccAWSAmplify_serial/App/CustomRules
=== RUN   TestAccAWSAmplify_serial/App/Description
=== PAUSE TestAccAWSAmplify_serial/App/Description
=== RUN   TestAccAWSAmplify_serial/App/EnvironmentVariables
=== PAUSE TestAccAWSAmplify_serial/App/EnvironmentVariables
=== RUN   TestAccAWSAmplify_serial/App/Name
=== PAUSE TestAccAWSAmplify_serial/App/Name
=== RUN   TestAccAWSAmplify_serial/App/Repository
=== PAUSE TestAccAWSAmplify_serial/App/Repository
=== CONT  TestAccAWSAmplify_serial/App/basic
=== CONT  TestAccAWSAmplify_serial/App/BuildSpec
=== CONT  TestAccAWSAmplify_serial/App/Description
=== CONT  TestAccAWSAmplify_serial/App/EnvironmentVariables
=== CONT  TestAccAWSAmplify_serial/App/Repository
=== CONT  TestAccAWSAmplify_serial/App/Name
=== CONT  TestAccAWSAmplify_serial/App/CustomRules
=== CONT  TestAccAWSAmplify_serial/App/BasicAuthCredentials
=== CONT  TestAccAWSAmplify_serial/App/Tags
=== CONT  TestAccAWSAmplify_serial/App/IamServiceRole
=== CONT  TestAccAWSAmplify_serial/App/disappears
=== CONT  TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
=== CONT  TestAccAWSAmplify_serial/App/basic
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/BuildSpec
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/EnvironmentVariables
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/CustomRules
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/Description
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/Name
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/Repository
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/Tags
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/IamServiceRole
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/BasicAuthCredentials
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/disappears
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
=== CONT  TestAccAWSAmplify_serial/App/AutoBranchCreationConfig
    resource_aws_amplify_app_test.go:681: AWS Amplify is not supported in GovCloud partition
--- PASS: TestAccAWSAmplify_serial (1.37s)
    --- PASS: TestAccAWSAmplify_serial/App (0.00s)
        --- SKIP: TestAccAWSAmplify_serial/App/basic (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/BuildSpec (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/CustomRules (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/EnvironmentVariables (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/Description (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/Name (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/Repository (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/Tags (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/IamServiceRole (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/BasicAuthCredentials (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/disappears (1.37s)
        --- SKIP: TestAccAWSAmplify_serial/App/AutoBranchCreationConfig (1.37s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	4.367s
```

**Comment by ewbankkit** [comment]
@ashishmohite @k24d Thanks for the contribution 👏.
In general everything was in great shape.
I made a few modifications to get this merged quicker:

* Made tests run serially so as not to hit API rate-limiting errors
* Modified some of the arguments to better match the AWS API structure - the main change here was removing the `basic_auth_config` block and flattening to `basic_auth_enabled` and `basic_auth_credentials`. Documentation updated

**Pull request merged**
