### PR TITLE
Add aws_identitystore_groups data source

### PR DESCRIPTION
**Pull request by liath**
### Description

Adds a data source for listing all groups in an Identity Store instance. Part of a few PRs to cover https://github.com/hashicorp/terraform-provider-aws/issues/26770.

The acceptance test is weird and I'd appreciate guidance on what to do there. The issue is that Identity Store instances are account wide so we can't guarantee there's only one group in the results or the order of the results. As far as I could find there isn't a way to say in the AttrPair checks "check these nested fields in any item of this list and compare those to these attributes on this other resource". So we're left with doing that in a custom test function.

Of course, server-side filter would likely help here but aws-sdk says that functionality is deprecated. :(

### Relations

Relates #26770 

### References

https://docs.aws.amazon.com/singlesignon/latest/IdentityStoreAPIReference/API_ListGroups.html

Wrt to server-side filtering being deprecated in the SDK:
https://github.com/aws/aws-sdk-go-v2/blob/service/identitystore/v1.16.11/service/identitystore/api_op_ListGroups.go#L46

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccIdentityStoreGroupsDataSource PKG=identitystore                                                                                           <aws:personal> <region:us-east-1>
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/identitystore/... -v -count 1 -parallel 20 -run='TestAccIdentityStoreGroupsDataSource'  -timeout 180m
=== RUN   TestAccIdentityStoreGroupsDataSource_basic
=== PAUSE TestAccIdentityStoreGroupsDataSource_basic
=== CONT  TestAccIdentityStoreGroupsDataSource_basic
--- PASS: TestAccIdentityStoreGroupsDataSource_basic (40.47s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/identitystore      45.534s
```

### CODE REVIEW

**Comment by AndreasSko** [comment]
Hi @liath, thanks for your work here! :slightly_smiling_face:  We are also interested in having a datasource that can list all groups in the identity center, so I appreciate that you opened this PR! :sparkles: 
I was just wondering what the state of this PR is, as it is still shown as a "draft". If understood the [contributing docs](https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request) right, PRs will only be reviewed when they are in the "ready" state. So maybe we could push the PR forward like this? But no worries if you are currently busy with other stuff :slightly_smiling_face:

**Comment by liath** [comment]
> Hi @liath, thanks for your work here! 🙂 We are also interested in having a datasource that can list all groups in the identity center, so I appreciate that you opened this PR! ✨ I was just wondering what the state of this PR is, as it is still shown as a "draft". If understood the [contributing docs](https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request) right, PRs will only be reviewed when they are in the "ready" state. So maybe we could push the PR forward like this? But no worries if you are currently busy with other stuff 🙂

Was hoping for feedback from Hashicorp on how to proceed with the tests. I'll move it out of drafts if that's what needs to happen to get that.

**Comment by alexbacchin-asx** [comment]
Is there any chance this PR gets merged?

**Comment by liath** [comment]
> Is there any chance this PR gets merged?

Supposedly you can get Hashicorp to pay attention to PRs if you're a paying customer but we aren't lol, if you are then please send this to your account rep :)

**Comment by aristosvo** [comment]
@bschaatsbergen Could we by any chance collaborate on this one or find a way to get this moving? I don't mind migrating this to the latest and greatest versions of framework and all, but it's now in "no man's land"

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen Could we by any chance collaborate on this one or find a way to get this moving? I don't mind migrating this to the latest and greatest versions of framework and all, but it's now in "no man's land"

Hey @aristosvo, happy to pick it up together - ideally we migrate it to the new plugin framework indeed.

**Comment by aristosvo** [comment]
If @liath is okay with it and allows me, I'd like to push a new version with the plugin framework to this or a new PR. I have to figure out the framework a bit too as well, but that would already be a great start.

**Comment by liath** [comment]
> If @liath is okay with it and allows me, I'd like to push a new version with the plugin framework to this or a new PR. I have to figure out the framework a bit too as well, but that would already be a great start.
> 
> If there is a way to open up a Slack chat that would be awesome, but last time I applied for the Slack channel nothing happened 😇

No worries here, take any of my PRs on this project lol

**Comment by liath** [comment]
> Hi @liath! I've taken this PR and migrated the code to framework, would you prefer me to open up a different PR or do you prefer to give me push permissions on your branch?
> 
> Rebased version of it all can be found here: https://github.com/aristosvo/terraform-provider-aws/tree/f-aws_identitystore_groups-data-source

I have no idea how to do that but either way lol

**Comment by aristosvo** [comment]
Created a new PR covering this, this one can be closed 🎉

**Comment by bschaatsbergen** [comment]
Closing in favor of continuing with https://github.com/hashicorp/terraform-provider-aws/pull/36993 - thanks for picking this up @aristosvo and thanks for making sure that @liath's commits are part of it.

**Pull request closed without merging**
