### PR TITLE
add ip_address_type to lb_target_group

### PR DESCRIPTION
**Pull request by ogonzalez-sd**
Add `ip_address_type` to `lb_target_group` resource and data source.
From https://docs.aws.amazon.com/elasticloadbalancing/latest/network/load-balancer-target-groups.html#target-group-ip-address-type

IP address type

When creating a new target group, you can select the IP address type of your target group. This controls the IP version used to communicate with targets and check their health status.

Network Load Balancers support both IPv4 and IPv6 target groups. The default selection is IPv4. IPv6 target groups can only be associated with dualstack Network Load Balancers.

Considerations

- All IP addresses within a target group must have the same IP address type. For example, you can't register an IPv4 target with an IPv6 target group.

- IPv6 target groups can only be used with dualstack load balancers with TCP or a TLS listeners.
- IPv6 target groups only support IP type targets.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release notes for CHANGELOG:
```
release-note:enhancement
resource/aws_lb_target_group: Add `ip_address_type` attribute
```
Output from acceptance testing:

```
$ TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 3 -run='TestAccELBV2TargetGroup' -timeout 500m
=== RUN   TestAccELBV2TargetGroupAttachment_basic
=== PAUSE TestAccELBV2TargetGroupAttachment_basic
=== RUN   TestAccELBV2TargetGroupAttachment_disappears
=== PAUSE TestAccELBV2TargetGroupAttachment_disappears
=== RUN   TestAccELBV2TargetGroupAttachment_backwardsCompatibility
=== PAUSE TestAccELBV2TargetGroupAttachment_backwardsCompatibility
=== RUN   TestAccELBV2TargetGroupAttachment_port
=== PAUSE TestAccELBV2TargetGroupAttachment_port
=== RUN   TestAccELBV2TargetGroupAttachment_ipAddress
=== PAUSE TestAccELBV2TargetGroupAttachment_ipAddress
=== RUN   TestAccELBV2TargetGroupAttachment_lambda
=== PAUSE TestAccELBV2TargetGroupAttachment_lambda
=== RUN   TestAccELBV2TargetGroupDataSource_basic
=== PAUSE TestAccELBV2TargetGroupDataSource_basic
=== RUN   TestAccELBV2TargetGroupDataSource_appCookie
=== PAUSE TestAccELBV2TargetGroupDataSource_appCookie
=== RUN   TestAccELBV2TargetGroupDataSource_backwardsCompatibility
=== PAUSE TestAccELBV2TargetGroupDataSource_backwardsCompatibility
=== RUN   TestAccELBV2TargetGroup_backwardsCompatibility
=== PAUSE TestAccELBV2TargetGroup_backwardsCompatibility
=== RUN   TestAccELBV2TargetGroup_protocolVersion
=== PAUSE TestAccELBV2TargetGroup_protocolVersion
=== RUN   TestAccELBV2TargetGroup_ProtocolVersionGRPC_healthCheck
=== PAUSE TestAccELBV2TargetGroup_ProtocolVersionGRPC_healthCheck
=== RUN   TestAccELBV2TargetGroup_ProtocolVersionHTTPGRPC_update
=== PAUSE TestAccELBV2TargetGroup_ProtocolVersionHTTPGRPC_update
=== RUN   TestAccELBV2TargetGroup_ProtocolTCPHealthCheck_protocol
=== PAUSE TestAccELBV2TargetGroup_ProtocolTCPHealthCheck_protocol
=== RUN   TestAccELBV2TargetGroup_Protocol_tls
=== PAUSE TestAccELBV2TargetGroup_Protocol_tls
=== RUN   TestAccELBV2TargetGroup_TCP_httpHealthCheck
=== PAUSE TestAccELBV2TargetGroup_TCP_httpHealthCheck
=== RUN   TestAccELBV2TargetGroup_attrsOnCreate
=== PAUSE TestAccELBV2TargetGroup_attrsOnCreate
=== RUN   TestAccELBV2TargetGroup_basic
=== PAUSE TestAccELBV2TargetGroup_basic
=== RUN   TestAccELBV2TargetGroup_basicUdp
=== PAUSE TestAccELBV2TargetGroup_basicUdp
=== RUN   TestAccELBV2TargetGroup_basicIPv6
=== PAUSE TestAccELBV2TargetGroup_basicIPv6
=== RUN   TestAccELBV2TargetGroup_changeIPAddressTypeForceNew
=== PAUSE TestAccELBV2TargetGroup_changeIPAddressTypeForceNew
=== RUN   TestAccELBV2TargetGroup_targetTypeInvalidWithIPv6
=== PAUSE TestAccELBV2TargetGroup_targetTypeInvalidWithIPv6
=== RUN   TestAccELBV2TargetGroup_changeNameForceNew
=== PAUSE TestAccELBV2TargetGroup_changeNameForceNew
=== RUN   TestAccELBV2TargetGroup_changePortForceNew
=== PAUSE TestAccELBV2TargetGroup_changePortForceNew
=== RUN   TestAccELBV2TargetGroup_changeProtocolForceNew
=== PAUSE TestAccELBV2TargetGroup_changeProtocolForceNew
=== RUN   TestAccELBV2TargetGroup_changeVPCForceNew
=== PAUSE TestAccELBV2TargetGroup_changeVPCForceNew
=== RUN   TestAccELBV2TargetGroup_Defaults_application
=== PAUSE TestAccELBV2TargetGroup_Defaults_application
=== RUN   TestAccELBV2TargetGroup_Defaults_network
=== PAUSE TestAccELBV2TargetGroup_Defaults_network
=== RUN   TestAccELBV2TargetGroup_enableHealthCheck
=== PAUSE TestAccELBV2TargetGroup_enableHealthCheck
=== RUN   TestAccELBV2TargetGroup_generatedName
=== PAUSE TestAccELBV2TargetGroup_generatedName
=== RUN   TestAccELBV2TargetGroup_namePrefix
=== PAUSE TestAccELBV2TargetGroup_namePrefix
=== RUN   TestAccELBV2TargetGroup_NetworkLB_targetGroup
=== PAUSE TestAccELBV2TargetGroup_NetworkLB_targetGroup
=== RUN   TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination
=== PAUSE TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination
=== RUN   TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy
=== PAUSE TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy
=== RUN   TestAccELBV2TargetGroup_preserveClientIPValid
=== PAUSE TestAccELBV2TargetGroup_preserveClientIPValid
=== RUN   TestAccELBV2TargetGroup_protocolGeneve
=== PAUSE TestAccELBV2TargetGroup_protocolGeneve
=== RUN   TestAccELBV2TargetGroup_protocolGeneveNotSticky
=== PAUSE TestAccELBV2TargetGroup_protocolGeneveNotSticky
=== RUN   TestAccELBV2TargetGroup_stickinessDefaultALB
=== PAUSE TestAccELBV2TargetGroup_stickinessDefaultALB
=== RUN   TestAccELBV2TargetGroup_stickinessDefaultNLB
=== PAUSE TestAccELBV2TargetGroup_stickinessDefaultNLB
=== RUN   TestAccELBV2TargetGroup_stickinessInvalidALB
=== PAUSE TestAccELBV2TargetGroup_stickinessInvalidALB
=== RUN   TestAccELBV2TargetGroup_stickinessInvalidNLB
=== PAUSE TestAccELBV2TargetGroup_stickinessInvalidNLB
=== RUN   TestAccELBV2TargetGroup_stickinessValidALB
=== PAUSE TestAccELBV2TargetGroup_stickinessValidALB
=== RUN   TestAccELBV2TargetGroup_stickinessValidNLB
=== PAUSE TestAccELBV2TargetGroup_stickinessValidNLB
=== RUN   TestAccELBV2TargetGroup_tags
=== PAUSE TestAccELBV2TargetGroup_tags
=== RUN   TestAccELBV2TargetGroup_updateAppStickinessEnabled
=== PAUSE TestAccELBV2TargetGroup_updateAppStickinessEnabled
=== RUN   TestAccELBV2TargetGroup_updateHealthCheck
=== PAUSE TestAccELBV2TargetGroup_updateHealthCheck
=== RUN   TestAccELBV2TargetGroup_updateStickinessEnabled
=== PAUSE TestAccELBV2TargetGroup_updateStickinessEnabled
=== RUN   TestAccELBV2TargetGroup_withoutHealthCheck
=== PAUSE TestAccELBV2TargetGroup_withoutHealthCheck
=== RUN   TestAccELBV2TargetGroup_A_basic
=== PAUSE TestAccELBV2TargetGroup_A_basic
=== RUN   TestAccELBV2TargetGroup_A_changeNameForceNew
=== PAUSE TestAccELBV2TargetGroup_A_changeNameForceNew
=== RUN   TestAccELBV2TargetGroup_A_changePortForceNew
=== PAUSE TestAccELBV2TargetGroup_A_changePortForceNew
=== RUN   TestAccELBV2TargetGroup_A_changeProtocolForceNew
=== PAUSE TestAccELBV2TargetGroup_A_changeProtocolForceNew
=== RUN   TestAccELBV2TargetGroup_A_changeVPCForceNew
=== PAUSE TestAccELBV2TargetGroup_A_changeVPCForceNew
=== RUN   TestAccELBV2TargetGroup_A_generatedName
=== PAUSE TestAccELBV2TargetGroup_A_generatedName
=== RUN   TestAccELBV2TargetGroup_A_lambda
=== PAUSE TestAccELBV2TargetGroup_A_lambda
=== RUN   TestAccELBV2TargetGroup_A_lambdaMultiValueHeadersEnabled
=== PAUSE TestAccELBV2TargetGroup_A_lambdaMultiValueHeadersEnabled
=== RUN   TestAccELBV2TargetGroup_A_missingPortProtocolVPC
=== PAUSE TestAccELBV2TargetGroup_A_missingPortProtocolVPC
=== RUN   TestAccELBV2TargetGroup_A_namePrefix
=== PAUSE TestAccELBV2TargetGroup_A_namePrefix
=== RUN   TestAccELBV2TargetGroup_A_setAndUpdateSlowStart
=== PAUSE TestAccELBV2TargetGroup_A_setAndUpdateSlowStart
=== RUN   TestAccELBV2TargetGroup_A_tags
=== PAUSE TestAccELBV2TargetGroup_A_tags
=== RUN   TestAccELBV2TargetGroup_A_updateHealthCheck
=== PAUSE TestAccELBV2TargetGroup_A_updateHealthCheck
=== RUN   TestAccELBV2TargetGroup_A_updateLoadBalancingAlgorithmType
=== PAUSE TestAccELBV2TargetGroup_A_updateLoadBalancingAlgorithmType
=== RUN   TestAccELBV2TargetGroup_A_updateStickinessEnabled
=== PAUSE TestAccELBV2TargetGroup_A_updateStickinessEnabled
=== CONT  TestAccELBV2TargetGroupAttachment_basic
=== CONT  TestAccELBV2TargetGroup_attrsOnCreate
=== CONT  TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination
=== CONT  TestAccELBV2TargetGroup_changeProtocolForceNew
--- PASS: TestAccELBV2TargetGroup_attrsOnCreate (32.21s)
--- PASS: TestAccELBV2TargetGroup_networkLB_TargetGroupWithConnectionTermination (32.22s)
=== CONT  TestAccELBV2TargetGroup_NetworkLB_targetGroup
--- PASS: TestAccELBV2TargetGroup_changeProtocolForceNew (33.90s)
=== CONT  TestAccELBV2TargetGroup_namePrefix
--- PASS: TestAccELBV2TargetGroup_NetworkLB_targetGroup (49.59s)
=== CONT  TestAccELBV2TargetGroup_generatedName
--- PASS: TestAccELBV2TargetGroup_namePrefix (16.80s)
=== CONT  TestAccELBV2TargetGroup_enableHealthCheck
--- PASS: TestAccELBV2TargetGroup_generatedName (16.87s)
=== CONT  TestAccELBV2TargetGroup_Defaults_network
--- PASS: TestAccELBV2TargetGroupAttachment_basic (100.34s)
=== CONT  TestAccELBV2TargetGroup_Defaults_application
--- PASS: TestAccELBV2TargetGroup_enableHealthCheck (21.78s)
=== CONT  TestAccELBV2TargetGroup_changeVPCForceNew
--- PASS: TestAccELBV2TargetGroup_Defaults_application (17.42s)
=== CONT  TestAccELBV2TargetGroup_A_updateStickinessEnabled
--- PASS: TestAccELBV2TargetGroup_Defaults_network (20.95s)
=== CONT  TestAccELBV2TargetGroup_updateStickinessEnabled
--- PASS: TestAccELBV2TargetGroup_changeVPCForceNew (29.50s)
=== CONT  TestAccELBV2TargetGroup_updateHealthCheck
--- PASS: TestAccELBV2TargetGroup_A_updateStickinessEnabled (44.11s)
=== CONT  TestAccELBV2TargetGroup_updateAppStickinessEnabled
--- PASS: TestAccELBV2TargetGroup_updateHealthCheck (30.97s)
=== CONT  TestAccELBV2TargetGroup_tags
--- PASS: TestAccELBV2TargetGroup_updateStickinessEnabled (45.65s)
=== CONT  TestAccELBV2TargetGroup_stickinessValidNLB
--- PASS: TestAccELBV2TargetGroup_updateAppStickinessEnabled (44.32s)
=== CONT  TestAccELBV2TargetGroup_stickinessValidALB
--- PASS: TestAccELBV2TargetGroup_tags (44.84s)
=== CONT  TestAccELBV2TargetGroup_stickinessInvalidNLB
--- PASS: TestAccELBV2TargetGroup_stickinessInvalidNLB (23.38s)
=== CONT  TestAccELBV2TargetGroup_stickinessInvalidALB
--- PASS: TestAccELBV2TargetGroup_stickinessValidNLB (71.48s)
=== CONT  TestAccELBV2TargetGroup_stickinessDefaultNLB
--- PASS: TestAccELBV2TargetGroup_stickinessValidALB (31.54s)
=== CONT  TestAccELBV2TargetGroup_stickinessDefaultALB
--- PASS: TestAccELBV2TargetGroup_stickinessDefaultALB (16.83s)
=== CONT  TestAccELBV2TargetGroup_protocolGeneveNotSticky
--- PASS: TestAccELBV2TargetGroup_stickinessInvalidALB (34.32s)
=== CONT  TestAccELBV2TargetGroup_changeIPAddressTypeForceNew
--- PASS: TestAccELBV2TargetGroup_stickinessDefaultNLB (46.28s)
=== CONT  TestAccELBV2TargetGroup_changePortForceNew
--- PASS: TestAccELBV2TargetGroup_protocolGeneveNotSticky (31.31s)
=== CONT  TestAccELBV2TargetGroup_withoutHealthCheck
--- PASS: TestAccELBV2TargetGroup_withoutHealthCheck (11.81s)
=== CONT  TestAccELBV2TargetGroup_A_updateLoadBalancingAlgorithmType
--- PASS: TestAccELBV2TargetGroup_changeIPAddressTypeForceNew (31.46s)
=== CONT  TestAccELBV2TargetGroup_A_updateHealthCheck
--- PASS: TestAccELBV2TargetGroup_changePortForceNew (31.51s)
=== CONT  TestAccELBV2TargetGroup_A_tags
--- PASS: TestAccELBV2TargetGroup_A_updateHealthCheck (31.64s)
=== CONT  TestAccELBV2TargetGroup_A_setAndUpdateSlowStart
--- PASS: TestAccELBV2TargetGroup_A_updateLoadBalancingAlgorithmType (43.43s)
=== CONT  TestAccELBV2TargetGroup_A_namePrefix
--- PASS: TestAccELBV2TargetGroup_A_tags (30.65s)
=== CONT  TestAccELBV2TargetGroup_A_missingPortProtocolVPC
--- PASS: TestAccELBV2TargetGroup_A_namePrefix (17.01s)
=== CONT  TestAccELBV2TargetGroup_protocolGeneve
--- PASS: TestAccELBV2TargetGroup_A_setAndUpdateSlowStart (30.41s)
=== CONT  TestAccELBV2TargetGroup_preserveClientIPValid
--- PASS: TestAccELBV2TargetGroup_A_missingPortProtocolVPC (18.28s)
=== CONT  TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy
--- PASS: TestAccELBV2TargetGroup_protocolGeneve (19.88s)
=== CONT  TestAccELBV2TargetGroup_changeNameForceNew
--- PASS: TestAccELBV2TargetGroup_preserveClientIPValid (30.60s)
=== CONT  TestAccELBV2TargetGroupDataSource_backwardsCompatibility
--- PASS: TestAccELBV2TargetGroup_NetworkLB_targetGroupWithProxy (30.39s)
=== CONT  TestAccELBV2TargetGroup_TCP_httpHealthCheck
--- PASS: TestAccELBV2TargetGroup_changeNameForceNew (34.38s)
=== CONT  TestAccELBV2TargetGroup_targetTypeInvalidWithIPv6
--- PASS: TestAccELBV2TargetGroup_targetTypeInvalidWithIPv6 (8.44s)
=== CONT  TestAccELBV2TargetGroup_A_lambdaMultiValueHeadersEnabled
--- PASS: TestAccELBV2TargetGroup_TCP_httpHealthCheck (31.12s)
=== CONT  TestAccELBV2TargetGroup_A_lambda
--- PASS: TestAccELBV2TargetGroup_A_lambda (13.78s)
=== CONT  TestAccELBV2TargetGroup_Protocol_tls
--- PASS: TestAccELBV2TargetGroup_A_lambdaMultiValueHeadersEnabled (34.03s)
=== CONT  TestAccELBV2TargetGroup_A_generatedName
--- PASS: TestAccELBV2TargetGroup_Protocol_tls (16.66s)
=== CONT  TestAccELBV2TargetGroupAttachment_ipAddress
--- PASS: TestAccELBV2TargetGroup_A_generatedName (17.08s)
=== CONT  TestAccELBV2TargetGroup_ProtocolTCPHealthCheck_protocol
--- PASS: TestAccELBV2TargetGroup_ProtocolTCPHealthCheck_protocol (31.55s)
=== CONT  TestAccELBV2TargetGroupDataSource_appCookie
--- PASS: TestAccELBV2TargetGroupAttachment_ipAddress (119.15s)
=== CONT  TestAccELBV2TargetGroup_basicUdp
--- PASS: TestAccELBV2TargetGroup_basicUdp (18.23s)
=== CONT  TestAccELBV2TargetGroup_ProtocolVersionHTTPGRPC_update
--- PASS: TestAccELBV2TargetGroup_ProtocolVersionHTTPGRPC_update (35.55s)
=== CONT  TestAccELBV2TargetGroup_basicIPv6
--- PASS: TestAccELBV2TargetGroupDataSource_backwardsCompatibility (246.16s)
=== CONT  TestAccELBV2TargetGroup_A_changeVPCForceNew
--- PASS: TestAccELBV2TargetGroup_basicIPv6 (18.45s)
=== CONT  TestAccELBV2TargetGroup_A_changePortForceNew
--- PASS: TestAccELBV2TargetGroup_A_changeVPCForceNew (29.39s)
=== CONT  TestAccELBV2TargetGroupDataSource_basic
--- PASS: TestAccELBV2TargetGroupDataSource_appCookie (175.14s)
=== CONT  TestAccELBV2TargetGroup_ProtocolVersionGRPC_healthCheck
--- PASS: TestAccELBV2TargetGroup_A_changePortForceNew (32.59s)
=== CONT  TestAccELBV2TargetGroup_protocolVersion
--- PASS: TestAccELBV2TargetGroup_ProtocolVersionGRPC_healthCheck (17.00s)
=== CONT  TestAccELBV2TargetGroup_backwardsCompatibility
--- PASS: TestAccELBV2TargetGroup_protocolVersion (16.76s)
=== CONT  TestAccELBV2TargetGroup_A_changeNameForceNew
--- PASS: TestAccELBV2TargetGroup_backwardsCompatibility (17.10s)
=== CONT  TestAccELBV2TargetGroup_A_basic
--- PASS: TestAccELBV2TargetGroup_A_basic (16.64s)
=== CONT  TestAccELBV2TargetGroupAttachment_lambda
--- PASS: TestAccELBV2TargetGroup_A_changeNameForceNew (34.08s)
=== CONT  TestAccELBV2TargetGroup_basic
--- PASS: TestAccELBV2TargetGroup_basic (17.11s)
=== CONT  TestAccELBV2TargetGroupAttachment_backwardsCompatibility
--- PASS: TestAccELBV2TargetGroupAttachment_lambda (31.06s)
=== CONT  TestAccELBV2TargetGroupAttachment_disappears
--- PASS: TestAccELBV2TargetGroupAttachment_backwardsCompatibility (99.79s)
=== CONT  TestAccELBV2TargetGroup_A_changeProtocolForceNew
--- PASS: TestAccELBV2TargetGroupAttachment_disappears (102.12s)
=== CONT  TestAccELBV2TargetGroupAttachment_port
--- PASS: TestAccELBV2TargetGroupDataSource_basic (215.26s)
--- PASS: TestAccELBV2TargetGroup_A_changeProtocolForceNew (35.50s)
--- PASS: TestAccELBV2TargetGroupAttachment_port (110.88s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elbv2      979.961s

...
```

### CODE REVIEW

**Comment by allenxiang** [comment]
Is there anything else needed to get this PR merged? We need this feature to use IPv6 target groups.

**Comment by igomez06** [comment]
What is needed to get this merged? We really need this feature as well.

**Comment by yann-soubeyrand** [comment]
We’re also dependent on this PR. If a maintainer passes by and can have a look at it, it would be awesome :wink:

**Comment by adamjlow** [comment]
+1 we're in need of IPv6 support on NLB target groups, would appreciate seeing this one merged and released.

**Comment by igomez06** [comment]
> We’re also dependent on this PR. If a maintainer passes by and can have a look at it, it would be awesome 😉

Hello Yann could you please put a thumbs in the top comment? That way we can get the maintainers to view this PR. Thank you!

**Comment by igomez06** [comment]
> +1 we're in need of IPv6 support on NLB target groups, would appreciate seeing this one merged and released.

Hello Adam could you please put a thumbs in the top comment? That way we can get the maintainers to view this PR. Thank you!

**Comment by adamjlow** [comment]
Any updates on this one, manually provisioning target groups is becoming increasingly problematic?

**Comment by yann-soubeyrand** [comment]
Hello @adamjlow, according to the [changelog](https://github.com/hashicorp/terraform-provider-aws/blob/main/CHANGELOG.md#4270-august-19-2022), it seems to have been addressed recently. See also https://github.com/hashicorp/terraform-provider-aws/pull/26320.

**Comment by ogonzalez-sd** [comment]
Yup, looks superseded by #26320

**Pull request closed without merging**
