### PR TITLE
New Resource: aws_codepipeline_custom_action_type

### LINKED ISSUE #6931: customAction support for aws codepipeline
_This issue was originally opened by @bsarbhukan as hashicorp/terraform#19696. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

### Current Terraform Version

```
Terraform v0.11.10
+ provider.aws v1.52.0
+ provider.null v1.0.0
+ provider.template v1.0.0

```

### Use-cases

We are trying to create a AWS Codepipeline with source->build->deploy->test
We are able to write source and deploy stage using terraform.
For Build and Test stage, we plan to use jenkins (which is custom action or third party)
I had used the same pipeline skeleton using cloudformation  and we need to create Custom action for Jenkins followed by codepipeline.

But I dont see any option to create a custom action for jenkins. 

I cloned terraform engine code but I dont see anything related to Custom action for aws codepipeline.

I would like to know if such feature is planned to release or anyone has used any work around?
### Attempted Solutions

I tried some random option for Owner/Provider (purely guess though) but it keep throwing below error:
Error creating CodePipeline: InvalidActionDeclarationException: ActionType (Category: 'Build', Provider: 'Jenkins', Owner: 'ThirdParty', Version: '1') in action 'Build' is not available
	status code: 400

* aws_codepipeline.codepipeline: Error creating CodePipeline: InvalidActionDeclarationException: ActionType (Category: 'Build', Provider: 'Jenkins', Owner: 'Custom', Version: '1') in action 'Build' is not available
status code: 400

### Proposal

Will it be wise to create clousformation stack as resource for this custom action followed by aws code pipeline?

### PR DESCRIPTION
**Pull request by atsushi-ishibashi**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Fixes #6931

Changes proposed in this pull request:

* `aws_codepipeline_custom_action_type`

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsCodePipelineCustomActionType'
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAwsCodePipelineCustomActionType -timeout 120m
=== RUN   TestAccAwsCodePipelineCustomActionType_basic
--- PASS: TestAccAwsCodePipelineCustomActionType_basic (47.27s)
=== RUN   TestAccAwsCodePipelineCustomActionType_settings
--- PASS: TestAccAwsCodePipelineCustomActionType_settings (38.30s)
=== RUN   TestAccAwsCodePipelineCustomActionType_configurationProperties
--- PASS: TestAccAwsCodePipelineCustomActionType_configurationProperties (39.63s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	125.256s
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by nicolai86** [comment]
@atsushi-ishibashi any chance you will update this PR to give it a chance to be merged into the aws provider?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCodePipelineCustomActionType_' PKG=codepipeline ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/codepipeline/... -v -count 1 -parallel 2  -run=TestAccCodePipelineCustomActionType_ -timeout 180m
=== RUN   TestAccCodePipelineCustomActionType_basic
=== PAUSE TestAccCodePipelineCustomActionType_basic
=== RUN   TestAccCodePipelineCustomActionType_disappears
=== PAUSE TestAccCodePipelineCustomActionType_disappears
=== RUN   TestAccCodePipelineCustomActionType_tags
=== PAUSE TestAccCodePipelineCustomActionType_tags
=== RUN   TestAccCodePipelineCustomActionType_allAttributes
=== PAUSE TestAccCodePipelineCustomActionType_allAttributes
=== CONT  TestAccCodePipelineCustomActionType_basic
=== CONT  TestAccCodePipelineCustomActionType_tags
--- PASS: TestAccCodePipelineCustomActionType_basic (21.97s)
=== CONT  TestAccCodePipelineCustomActionType_disappears
--- PASS: TestAccCodePipelineCustomActionType_disappears (13.96s)
=== CONT  TestAccCodePipelineCustomActionType_allAttributes
--- PASS: TestAccCodePipelineCustomActionType_tags (48.47s)
--- PASS: TestAccCodePipelineCustomActionType_allAttributes (18.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/codepipeline	58.617s
```

**Comment by ewbankkit** [comment]
@atsushi-ishibashi Thanks for the contribution :tada: :clap:.

**Pull request merged**
