### PR TITLE
Add configuration set support for Cognito user pools

### PR DESCRIPTION
**Pull request by johngallagher**
Adds configuration set support for Cognito user pools.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_cognito_user_pool: Add `configuration_set`
```

Output from acceptance testing:

```bash
$ make testacc TESTARGS='-run=TestAccAWSCognitoUserPool_withEmailConfiguration'                                                                                                  

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCognitoUserPool_withEmailConfiguration -timeout 120m
=== RUN   TestAccAWSCognitoUserPool_withEmailConfiguration
=== PAUSE TestAccAWSCognitoUserPool_withEmailConfiguration
=== CONT  TestAccAWSCognitoUserPool_withEmailConfiguration
--- PASS: TestAccAWSCognitoUserPool_withEmailConfiguration (49.71s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       52.910s
```

### CODE REVIEW

**Comment by jaynefox** [comment]
Hi, is there anything else we need to do to get someone to take a look at this? Happy to revise as required

**Comment by YakDriver** [comment]
@johngallagher @simplybusiness Thank you for your work on this PR! I will be working on this before long. In order to expedite the process, I will likely make some changes. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Comment by johngallagher** [comment]
@YakDriver Thanks! Sorry for the delay - I've been off work for a few weeks. I followed [the instructions on Github to do this](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/allowing-changes-to-a-pull-request-branch-created-from-a-fork) but the tickbox doesn't appear for me where it says it should on this PR page.

Let me know if I've done something wrong or if there's something else you need from me. Thanks.

**Comment by YakDriver** [comment]
@johngallagher Thanks for getting back to me. The problem is that @simplybusiness owns the repository that owns the fork that you requested to be pulled. SB will need to check that box. Another option is for me to create a separate branch and cherry pick your commits from this fork. You'll get credit as though it was your PR. Are you in contact with SB?

**Comment by johngallagher** [comment]
> @johngallagher Thanks for getting back to me. The problem is that @simplybusiness owns the repository that owns the fork that you requested to be pulled. SB will need to check that box. Another option is for me to create a separate branch and cherry pick your commits from this fork. You'll get credit as though it was your PR. Are you in contact with SB?

Yup, I still work there. So I'll ask for an admin to enable this... thanks for your patience!

**Comment by johngallagher** [comment]
> @johngallagher Thanks for getting back to me. The problem is that @simplybusiness owns the repository that owns the fork that you requested to be pulled. SB will need to check that box. Another option is for me to create a separate branch and cherry pick your commits from this fork. You'll get credit as though it was your PR. Are you in contact with SB?

Hey - I've asked an admin to look at this and they can't see the tickbox either. Sorry!

So yeah, if you could create a separate branch and cherry pick commits, that'd be great. Sorry for the hassle!

**Comment by YakDriver** [comment]
@johngallagher It's the second time I've run into this recently with contributors that do not own their forks. Perhap it's a GitHub limitation or it is influenced by a @simplybusiness organization-level setting.

**Comment by johngallagher** [comment]
> @johngallagher It's the second time I've run into this recently with contributors that do not own their forks. Perhap it's a GitHub limitation or it is influenced by a @simplybusiness organization-level setting.

My bet is that SB have disabled something at a high level even for admins. Cherry pick away and sorry again for the hassle.

**Comment by YakDriver** [comment]
@johngallagher You can see your contribution as part of #14935! Thanks again. 🎉

**Pull request closed without merging**
