### PR TITLE
Add an option to forcibly delete EventBridge Rules

### PR DESCRIPTION
**Pull request by case-k-git**
### Description

Add force delete option to Event Bridge Rule

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34906

### References
Currently can not delete event bridge rule if target exist. API support force delete option so I add the force option 

```
│ Error: deleting EventBridge Rule (): ValidationException: Rule can't be deleted since it has targets.
│       status code: 400, request id: <resource_id>
```

https://docs.aws.amazon.com/eventbridge/latest/APIReference/API_DeleteRule.html
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_event_rule

### Output from Acceptance Testing

```
make testacc TESTS=TestAccEventsRule_isForceDeletion PKG=events
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/events/... -v -count 1 -parallel 20 -run='TestAccEventsRule_isForceDeletion'  -timeout 360m
=== RUN   TestAccEventsRule_isForceDeletion
=== PAUSE TestAccEventsRule_isForceDeletion
=== CONT  TestAccEventsRule_isForceDeletion
--- PASS: TestAccEventsRule_isForceDeletion (44.16s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/events     46.105s
```

### CODE REVIEW

**Comment by case-k-git** [comment]
Hello @justinretzolk Thank you for label update. Could you please check this PR when you have time?

**Comment by case-k-git** [comment]
Hello @DrFaust92 Could you please review this PR when you have time?

**Comment by case-k-git** [comment]
Hello @ewbankkit 
Could you please review this PR if you have time?

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
make testacc TESTARGS='-run=TestAccEventsRule_' PKG=events

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/events/... -v -count 1 -parallel 20  -run=TestAccEventsRule_ -timeout 360m
    rule_test.go:701: Environment variable EVENT_BRIDGE_PARTNER_EVENT_BUS_NAME is not set
--- SKIP: TestAccEventsRule_partnerEventBus (0.00s)
--- PASS: TestAccEventsRule_patternJSONEncoder (26.41s)
--- PASS: TestAccEventsRule_namePrefix (32.74s)
--- PASS: TestAccEventsRule_eventBusARN (34.35s)
--- PASS: TestAccEventsRule_Name_generated (34.55s)
--- PASS: TestAccEventsRule_scheduleAndPattern (34.88s)
--- PASS: TestAccEventsRule_role (41.73s)
--- PASS: TestAccEventsRule_description (48.13s)
--- PASS: TestAccEventsRule_pattern (48.96s)
--- PASS: TestAccEventsRule_state (51.05s)
--- PASS: TestAccEventsRule_migrateV0_Equivalent (0.00s)
    --- PASS: TestAccEventsRule_migrateV0_Equivalent/disabled (52.88s)
    --- PASS: TestAccEventsRule_migrateV0_Equivalent/enabled (54.85s)
--- PASS: TestAccEventsRule_migrateV0 (0.00s)
    --- PASS: TestAccEventsRule_migrateV0/disabled (52.24s)
    --- PASS: TestAccEventsRule_migrateV0/basic (55.88s)
    --- PASS: TestAccEventsRule_migrateV0/enabled (57.16s)
--- PASS: TestAccEventsRule_tags (58.34s)
--- PASS: TestAccEventsRule_basic (58.41s)
--- PASS: TestAccEventsRule_eventBusName (59.17s)
--- PASS: TestAccEventsRule_isEnabled (60.99s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/events	66.943s
```

**Comment by johnsonaj** [comment]
@case-k-git thank you for the contribution! 🎉

**Pull request merged**
