### PR TITLE
Bugfix retry behavior in  aws_ssoadmin_managed_policy_attachment for eventual consistency issue

### LINKED ISSUE #19215: aws_ssoadmin_managed_policy_attachment fails if used simultaneously in multiple pipelines for different permission-sets, because of AWS IAM eventual consistency.
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.14.7

provider registry.terraform.io/hashicorp/aws v3.38.0

### Affected Resource(s)

* aws_ssoadmin_managed_policy_attachment

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
locals {
  aws_managed_policies = [
    "arn:aws:iam::aws:policy/AmazonVPCReadOnlyAccess",
    "arn:aws:iam::aws:policy/AmazonRoute53ReadOnlyAccess",
    "arn:aws:iam::aws:policy/AmazonMSKReadOnlyAccess",
    "arn:aws:iam::aws:policy/AWSCertificateManagerReadOnly",
    "arn:aws:iam::aws:policy/ServiceQuotasReadOnlyAccess",
    "arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess",
    "arn:aws:iam::aws:policy/job-function/SupportUser",
  ]
}
data "aws_ssoadmin_instances" "sso-admin" {}

resource "aws_ssoadmin_permission_set" "permission-set" {
  name             = "some-permission-set"
  instance_arn     = tolist(data.aws_ssoadmin_instances.sso-admin.arns)[0]
  session_duration = "PT12H"
}

resource "aws_ssoadmin_managed_policy_attachment" "managed-policies" {
  count              = length(local.aws_managed_policies)
  managed_policy_arn = local.aws_managed_policies[count.index]
  instance_arn       = aws_ssoadmin_permission_set.permission-set.instance_arn
  permission_set_arn = aws_ssoadmin_permission_set.permission-set.arn
}
```

### Debug Output

Destroy operation: https://gist.github.com/jvitor03/e393feae47b3a137984ec18e488e1477

### Expected Behavior

When running the `aws_ssoadmin_managed_policy_attachment` resource simultaneously in multiple pipelines for different permission-sets, 
the resource can fail to apply the attachment because of the eventual consistency of AWS IAM, however it should retry the attachment if it gets `ConflictException: There is a conflicting operation in process.`. This is a known problem that also happens in the AWS IAM Terraform resources.

This retry in attachment/detachment for AWS managed policies is recommended by the AWS Go SDK: https://github.com/aws/aws-sdk-go/blob/b5cfa2167e2bb7c4e509b3f3551183d4f31ef853/service/ssoadmin/api.go#L96

### Actual Behavior

When running multiples pipelines at the same time for aws_ssoadmin_managed_policy_attachment, the attachment will fail if other pipeline for a different permission-set is doing an attachment too and this change was not yet propagated: `ConflictException: There is a conflicting operation in process.`. The provider will not attempt to retry and will just fail and stop the rest of the pipeline.

### Steps to Reproduce

1. Create at least 4 different terraform folders with the source pasted above
2. Change the permission-set name, to match the index of the folder
3. Run `terraform apply` in all folders at the same time
4. The problem also appear during destruction, so after the apply, you can run `terraform destroy`

Since its a eventual consistency problem, its not guarantee that the problem will appear in the first run

### Important Factoids

This is a common AWS IAM propagation behavior, the terraform-provider-aws have a dedicated documentation about using retry for the eventual consistency: 
- https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#eventual-consistency
- https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#iam-error-retries

### References

- https://docs.aws.amazon.com/singlesignon/latest/APIReference/API_AttachManagedPolicyToPermissionSet.html#API_AttachManagedPolicyToPermissionSet_Errors
- https://github.com/aws/aws-sdk-go/blob/b5cfa2167e2bb7c4e509b3f3551183d4f31ef853/service/ssoadmin/api.go#L96

### PR DESCRIPTION
**Pull request by jvitor03**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19215 

This PR adds a retry behavior for Create and destroy in the aws_ssoadmin_managed_policy_attachment-consitency resource.

Output from acceptance testing:

No acceptance testes where created, because they are not reliable to cover eventual consistency issues: https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/retries-and-waiters.md#eventual-consistency

Full trace log from the fix being used during a destroy: https://gist.github.com/jvitor03/89cb2d10213cebefcd76e95046118968

Log retry summary:
```
-----------------------------------------------------: timestamp=2021-05-03T01:28:54.732-0300
2021-05-03T01:28:54.732-0300 [INFO]  plugin.terraform-provider-aws: 2021/05/03 01:28:54 [DEBUG] [aws-sdk-go] {"__type":"ConflictException","Message":"There is a conflicting operation in process."}: timestamp=2021-05-03T01:28:54.732-0300
2021-05-03T01:28:54.732-0300 [INFO]  plugin.terraform-provider-aws: 2021/05/03 01:28:54 [DEBUG] [aws-sdk-go] DEBUG: Validate Response SSO Admin/DetachManagedPolicyFromPermissionSet failed, attempt 0/25, error ConflictException: There is a conflicting operation in process.: timestamp=2021-05-03T01:28:54.732-0300
2021-05-03T01:28:54.732-0300 [INFO]  plugin.terraform-provider-aws: 2021/05/03 01:28:54 [TRACE] Waiting 500ms before next try: timestamp=2021-05-03T01:28:54.732-0300
2021-05-03T01:28:54.896-0300 [INFO]  plugin.terraform-provider-aws: 2021/05/03 01:28:54 [DEBUG] [aws-sdk-go] DEBUG: Response SSO Admin/DeleteAccountAssignment Details:
---[ RESPONSE ]--------------------------------------

[...]

{"InstanceArn":"arn:aws:sso:::instance/ssoins-7223f43a8b17208a","ManagedPolicyArn":"arn:aws:iam::aws:policy/CloudWatchReadOnlyAccess","PermissionSetArn":"arn:aws:sso:::permissionSet/ssoins-7223f43a8b17208a/ps-eb12a5e3a0d6a825"}
-----------------------------------------------------: timestamp=2021-05-03T01:28:55.935-0300
2021-05-03T01:28:56.638-0300 [INFO]  plugin.terraform-provider-aws: 2021/05/03 01:28:56 [DEBUG] [aws-sdk-go] DEBUG: Retrying Request SSO Admin/DetachManagedPolicyFromPermissionSet, attempt 1: timestamp=2021-05-03T01:28:56.638-0300
2021-05-03T01:28:56.638-0300 [INFO]  plugin.terraform-provider-aws: 2021/05/03 01:28:56 [DEBUG] [aws-sdk-go] DEBUG: Request SSO Admin/DetachManagedPolicyFromPermissionSet Details:
---[ REQUEST POST-SIGN ]-----------------------------
```

### CODE REVIEW

**Comment by aabadia** [comment]
+1

**Comment by anGie44** [comment]
Hi @jvitor03 , thank you for this PR and following the contribution guidelines for retry handling! With these eventual consistency errors happening on both create and delete, without a precise timeout as it can depend per account/user, we can instead add a connection retry handler in `config.go` to automatically retry when hitting the error described  e.g.

```go
client.ssoadminconn.Handlers.Retry.PushBack(func(r *request.Request) {
    if r.Operation.Name == "AttachManagedPolicyToPermissionSet" || r.Operation.Name == "DetachManagedPolicyFromPermissionSet" {
        if tfawserr.ErrCodeEquals(r.Error, ssoadmin.ErrCodeConflictException) {
            r.Retryable = aws.Bool(true)
	}
    }
}
```

**Comment by jvitor03** [comment]
That looks way better to avoid duplicated code, I will do the change.
Thanks for the review!

**Review by anGie44 — APPROVED** [review]
Looks great @jvitor03 🚀 

Output of acceptance tests:
```
--- PASS: TestAccAWSSSOAdminManagedPolicyAttachment_disappears (32.90s)
--- PASS: TestAccAWSSSOAdminManagedPolicyAttachment_disappears_permissionSet (24.52s)
--- PASS: TestAccAWSSSOAdminManagedPolicyAttachment_basic (32.00s)
--- PASS: TestAccAWSSSOAdminManagedPolicyAttachment_forceNew (57.42s)
--- PASS: TestAccAWSSSOAdminManagedPolicyAttachment_multipleManagedPolicies (82.14s)
```

**Pull request merged**
