### PR TITLE
r/codedeploy_app: Fix, parallelize sweeper

### LINKED ISSUE #19070: sweeper/aws_codedeploy_app: Sweeper fails
The sweeper for `aws_codedeploy_app` fails with the following error

```
error deleting CodeDeploy Application (...): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, DeleteApplicationInput.ApplicationName.
```

The sweeper is leveraging the resource Delete operation, which deletes the associated role by checking the value of the `name` parameter. This is not populated in the sweeper.

### Affected Resource

* aws_codedeploy_app

### PR DESCRIPTION
**Pull request by YakDriver**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19070

Output from testing:

```
SWEEP=$AWS_DEFAULT_REGION SWEEPARGS=-sweep-run=aws_codedeploy_app make sweep
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-west-2 -sweep-run=aws_codedeploy_app -timeout 60m
2021/06/17 15:08:52 [DEBUG] Running Sweepers for region (us-west-2):
2021/06/17 15:08:52 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-west-2)
2021/06/17 15:08:52 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/17 15:08:53 Sweeper Tests ran successfully:
	- aws_codedeploy_app
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.430s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
When sweeping 4 existing apps:

```console
% TEST=./aws SWEEP=us-east-1,us-east-2,us-west-1,us-west-2 SWEEPARGS=-sweep-run=aws_codedeploy_app make sweep
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-east-1,us-east-2,us-west-1,us-west-2 -sweep-run=aws_codedeploy_app -timeout 60m
2021/06/17 17:24:03 [DEBUG] Running Sweepers for region (us-east-1):
2021/06/17 17:24:03 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-east-1)
2021/06/17 17:24:03 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/17 17:24:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:03 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:05 Sweeper Tests ran successfully:
	- aws_codedeploy_app
2021/06/17 17:24:05 [DEBUG] Running Sweepers for region (us-east-2):
2021/06/17 17:24:05 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-east-2)
2021/06/17 17:24:05 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/17 17:24:05 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:05 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:06 Sweeper Tests ran successfully:
	- aws_codedeploy_app
2021/06/17 17:24:06 [DEBUG] Running Sweepers for region (us-west-1):
2021/06/17 17:24:06 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-west-1)
2021/06/17 17:24:06 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/17 17:24:06 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:06 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:07 Sweeper Tests ran successfully:
	- aws_codedeploy_app
2021/06/17 17:24:07 [DEBUG] Running Sweepers for region (us-west-2):
2021/06/17 17:24:07 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-west-2)
2021/06/17 17:24:07 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/17 17:24:07 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:07 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 17:24:30 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:32 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:32 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:34 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:34 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:34 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:34 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:35 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:35 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:35 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:35 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:35 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:35 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:36 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:36 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:36 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:37 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:38 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:38 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:39 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:40 [ERROR] Error deleting CodeDeploy application: ThrottlingException: Rate exceeded
2021/06/17 17:24:40 [ERROR] Error running Sweeper (aws_codedeploy_app) in region (us-west-2): 1 error occurred:
	* error sweeping CodeDeploy Applications for us-west-2: 21 errors occurred:
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded
	* ThrottlingException: Rate exceeded



FAIL	github.com/terraform-providers/terraform-provider-aws/aws	39.490s
FAIL
make: *** [sweep] Error 1
```

**Comment by YakDriver** [comment]
@ewbankkit _Or_ we retry.

I'd like to avoid:
1. Each sweeper needing to understand why sweeping failed and react
2. Skip destroying resources unless absolutely necessary
3. Limiting concurrency as a matter of course
 
Every other resource that I've personally tested has worked fine with high-concurrency deleting. I'm going to give this a whirl with a few codedeploy_apps.

**Comment by YakDriver** [comment]
I swept 9 apps with no throttling. I suspect it had to do with things going on in the account other than your sweep test. Another reason to avoid limiting concurrency:

```console
% SWEEP=$AWS_DEFAULT_REGION SWEEPARGS=-sweep-run=aws_codedeploy_app make sweep
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-west-2 -sweep-run=aws_codedeploy_app -timeout 60m
2021/06/17 19:19:58 [DEBUG] Running Sweepers for region (us-west-2):
2021/06/17 19:19:58 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-west-2)
2021/06/17 19:19:58 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/17 19:19:58 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 19:19:58 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:19:59 [DEBUG] Waiting for state to become: [success]
2021/06/17 19:20:00 Sweeper Tests ran successfully:
	- aws_codedeploy_app
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3.041s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% TEST=./aws SWEEP=us-east-1,us-east-2,us-west-1,us-west-2 SWEEPARGS=-sweep-run=aws_codedeploy_app make sweep
WARNING: This will destroy infrastructure. Use only in development accounts.
go test ./aws -v -sweep=us-east-1,us-east-2,us-west-1,us-west-2 -sweep-run=aws_codedeploy_app -timeout 60m
2021/06/18 09:24:44 [DEBUG] Running Sweepers for region (us-east-1):
2021/06/18 09:24:44 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-east-1)
2021/06/18 09:24:44 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 09:24:44 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:44 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:44 Sweeper Tests ran successfully:
	- aws_codedeploy_app
2021/06/18 09:24:44 [DEBUG] Running Sweepers for region (us-east-2):
2021/06/18 09:24:44 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-east-2)
2021/06/18 09:24:44 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 09:24:44 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:45 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:45 Sweeper Tests ran successfully:
	- aws_codedeploy_app
2021/06/18 09:24:45 [DEBUG] Running Sweepers for region (us-west-1):
2021/06/18 09:24:45 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-west-1)
2021/06/18 09:24:45 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 09:24:45 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:45 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:46 Sweeper Tests ran successfully:
	- aws_codedeploy_app
2021/06/18 09:24:46 [DEBUG] Running Sweepers for region (us-west-2):
2021/06/18 09:24:46 [DEBUG] Running Sweeper (aws_codedeploy_app) in region (us-west-2)
2021/06/18 09:24:46 [INFO] AWS Auth provider used: "EnvProvider"
2021/06/18 09:24:46 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:46 [DEBUG] Trying to get account information via sts:GetCallerIdentity
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:24:48 [DEBUG] Waiting for state to become: [success]
2021/06/18 09:25:14 Sweeper Tests ran successfully:
	- aws_codedeploy_app
ok  	github.com/terraform-providers/terraform-provider-aws/aws	33.745s
```

**Pull request merged**
