### PR TITLE
Update ECS cluster name validation

### PR DESCRIPTION
**Pull request by gregops312**
Previous regex was not complete and allowed for apply time failures

### Description

Updating the ECS `validateClusterName` which contained and incomplete regex allowing for many cases with plans that wouldn't fail as expected

### Relations

n/a

### References

n/a

### Output from Acceptance Testing

n/a

### CODE REVIEW

**Comment by gregops312** [comment]
So I know there's a lot that goes on in this provider, and while this is pretty small, it like many other bugs can have consequences to deployments and availability of resources. I would think fixing bugs would be fairly high priority. 

That said I've read the contributing docs and am still curious what is a normal timeframe for getting PRs reviewed?

**Review by gdavison — APPROVED** [review]
Thanks for submitting this, @gregops312.

I've made a couple adjustments:

* I've removed the `.` that was in the regex, since that's not valid for ECS cluster names
* We have an [order that the character classes should appear in](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/regular-expressions.md), since we cache compiled regexes. I've re-ordered the regexp.

**Comment by gregops312** [comment]
> Thanks for submitting this, @gregops312.
> 
> I've made a couple adjustments:
> 
> * I've removed the `.` that was in the regex, since that's not valid for ECS cluster names
> * We have an [order that the character classes should appear in](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/regular-expressions.md), since we cache compiled regexes. I've re-ordered the regexp.

@gdavison Thank you very much. I'll keep those things in mind should I come across anything else in the future. I also see you added a `changelog` file. I didn't see that in the contributing docs, is that something I should do when making a change or is that something that is reserved for maintainers?

**Comment by gdavison** [comment]
Yes, there is some documentation about adding a changelog entry (https://hashicorp.github.io/terraform-provider-aws/changelog-process/), but we have recently reorganized the contributor guide, so it may have been more buried when you created the PR originally.

**Pull request merged**
