### PR TITLE
Add fix for OpenSearch Serverless VPCE test

### PR DESCRIPTION
**Pull request by mumoumit**
### Description

There was a bug in the test code. When I ran the Acceptance test for VPCE I got this error:

```
make testacc TESTS=TestAccOpenSearchServerlessVPCEndpoint PKG=opensearchserverless
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessVPCEndpoint'  -timeout 360m
=== RUN   TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_basic
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_update
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_update
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_disappears
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_disappears
=== CONT  TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_update
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_disappears
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_basic
=== NAME  TestAccOpenSearchServerlessVPCEndpoint_securityGroups
    vpc_endpoint_test.go:72: Step 1/3 error: Check failed: Check 2/2 error: aws_opensearchserverless_vpc_endpoint.test: Attribute 'security_group_ids.#' not found
=== NAME  TestAccOpenSearchServerlessVPCEndpoint_basic
    vpc_endpoint_test.go:35: Step 1/2 error: Check failed: Check 3/3 error: aws_opensearchserverless_vpc_endpoint.test: Attribute 'security_group_ids.#' expected to be set
=== NAME  TestAccOpenSearchServerlessVPCEndpoint_update
    vpc_endpoint_test.go:118: Step 1/4 error: Check failed: Check 3/3 error: aws_opensearchserverless_vpc_endpoint.test: Attribute 'security_group_ids.#' not found
--- FAIL: TestAccOpenSearchServerlessVPCEndpoint_update (298.38s)
--- FAIL: TestAccOpenSearchServerlessVPCEndpoint_securityGroups (298.77s)
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_disappears (305.24s)
--- FAIL: TestAccOpenSearchServerlessVPCEndpoint_basic (338.38s)
--- PASS: TestAccOpenSearchServerlessVPCEndpointDataSource_basic (343.69s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless     343.864s
FAIL
make: *** [testacc] Error 1
```

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/33603.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/39021.

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccOpenSearchServerlessVPCEndpoint PKG=opensearchserverless
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessVPCEndpoint'  -timeout 360m
=== RUN   TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_basic
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_update
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_update
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_disappears
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_disappears
=== CONT  TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_update
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_basic
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_disappears
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_securityGroups
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_basic (326.96s)
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_disappears (332.66s)
--- PASS: TestAccOpenSearchServerlessVPCEndpointDataSource_basic (334.52s)
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_securityGroups (404.37s)
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_update (519.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless 519.529s

```

### CODE REVIEW

**Comment by ewbankkit** [comment]
We are seeing these failures in CI too:

```
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_basic
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_basic
    vpc_endpoint_test.go:35: Step 1/2 error: Check failed: Check 3/3 error: aws_opensearchserverless_vpc_endpoint.test: Attribute 'security_group_ids.#' not found
--- FAIL: TestAccOpenSearchServerlessVPCEndpoint_basic (434.48s)
```
```
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_securityGroups
    vpc_endpoint_test.go:71: Step 1/3 error: Check failed: Check 2/2 error: aws_opensearchserverless_vpc_endpoint.test: Attribute 'security_group_ids.#' not found
--- FAIL: TestAccOpenSearchServerlessVPCEndpoint_securityGroups (449.72s)
```
```
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_update
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_update
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_update
    vpc_endpoint_test.go:117: Step 1/4 error: Check failed: Check 3/3 error: aws_opensearchserverless_vpc_endpoint.test: Attribute 'security_group_ids.#' not found
--- FAIL: TestAccOpenSearchServerlessVPCEndpoint_update (402.41s)
```

**Comment by mumoumit** [comment]
@ewbankkit so are you looking into it then?
Need this tests to be fixed so that we can merge this : https://github.com/hashicorp/terraform-provider-aws/pull/39021

We had introduced 2 new fields in the BatchGetVPCEResponse and need this to get merged in terraform too.

**Comment by mumoumit** [comment]
There was a linting error. So raised another commit to fix it.

**Comment by mumoumit** [comment]
Squashed the previous 2 commits into 1.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccOpenSearchServerlessVPCEndpoint' PKG=opensearchserverless ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/opensearchserverless/... -v -count 1 -parallel 3  -run=TestAccOpenSearchServerlessVPCEndpoint -timeout 360m
=== RUN   TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_basic
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_basic
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_securityGroups
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_update
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_update
=== RUN   TestAccOpenSearchServerlessVPCEndpoint_disappears
=== PAUSE TestAccOpenSearchServerlessVPCEndpoint_disappears
=== CONT  TestAccOpenSearchServerlessVPCEndpointDataSource_basic
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_update
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_disappears
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_disappears (327.64s)
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_securityGroups
--- PASS: TestAccOpenSearchServerlessVPCEndpointDataSource_basic (366.21s)
=== CONT  TestAccOpenSearchServerlessVPCEndpoint_basic
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_update (574.60s)
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_basic (365.96s)
--- PASS: TestAccOpenSearchServerlessVPCEndpoint_securityGroups (455.89s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	788.962s
```

**Comment by ewbankkit** [comment]
@mumoumit Thanks for the contribution :tada: :clap:.
It turns out that `BatchGetVpcEndpoint` does **not** return the endpoints' security group IDs so we have to call the EC2 `DescribeVpcEndpoints` API directly.
I added the failure code and reason to the error returned when the VPC endpoint goes into failed state while waiting.

**Comment by mumoumit** [comment]
Wanted to clarify BatchGetVpcEndpoint should return the security group IDs  
https://docs.aws.amazon.com/opensearch-service/latest/ServerlessAPIReference/API_BatchGetVpcEndpoint.html#API_BatchGetVpcEndpoint_ResponseSyntax

**Pull request merged**
