### PR TITLE
Add aws_opensearchserverless_security_policy resource

### LINKED ISSUE #28457: [New Resource]: OpenSearch Serverless Security Policy
### Description

Amazon OpenSearch Serverless is a preview service enabling OpenSearch clusters to be spun up without having to be concerned about the compute or storage requirements.

Security Policies are used to specify encryption and network protections for the data and cluster respectively.

### Requested Resource(s) and/or Data Source(s)

* `aws_opensearchserverless_security_policy

### Potential Terraform Configuration

```terraform
resource "aws_opensearchserverless_security_policy" "example" {
  name = "example"
  type = "encryption"
  policy = <<-EOT
  {
    "Rules": [
      {
        "Resource": [
          "collection/example"
        ],
        "ResourceType": "collection"
      }
    ],
    "AWSOwnedKey": true
  }
  EOT
}
```

### References

* https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/opensearchserverless@v1.0.2

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by mattburgess**
### Description

Adds support for OpenSearch Serverless Security Policy resources.

### Relations

Closes #28457

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccOpenSearchServerlessSecurityPolic
y_ PKG=opensearchserverless
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessSecurityPolicy_'  -timeout 180m
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_basic
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_basic
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_disappears
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_disappears
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_basic
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_disappears
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_disappears (12.92s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_basic (17.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	17.238s
```

### CODE REVIEW

**Comment by mattburgess** [comment]
The tests intermittently fail like this:

```
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_basic
    security_policy_test.go:27: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating Amazon OpenSearch Serverless Security Policy (tf-acc-test-1423387959538794016): operation error OpenSearchServerless: CreateSecurityPolicy, https response error StatusCode: 400, RequestID: 9dd8be28-f54d-41eb-854f-dc46f6ee0e33, ConflictException: Failed during processing for policyName: tf-acc-test-1423387959538794016 and type: encryption. Please retry
        
          with aws_opensearchserverless_security_policy.test,
          on terraform_plugin_test.tf line 2, in resource "aws_opensearchserverless_security_policy" "test":
           2: resource "aws_opensearchserverless_security_policy" "test" {
```

**Comment by jtbrush56** [comment]
Is there anything stopping this PR from being merged so that the work on #28462 can be completed? This serverless went to GA over a month ago and this code appears to have been done a few months ago.

**Comment by mattburgess** [comment]
Having converted this new resource over to use the new plugin framework, I'm seeing this test failure:

```
make testacc TESTS=TestAccOpenSearchServerlessSecurityPolicy_basic PKG=opensearchserverless
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessSecurityPolicy_basic'  -timeout 180m
=== RUN   TestAccOpenSearchServerlessSecurityPolicy_basic
=== PAUSE TestAccOpenSearchServerlessSecurityPolicy_basic
=== CONT  TestAccOpenSearchServerlessSecurityPolicy_basic
    security_policy_test.go:28: Step 1/2 error: Error running apply: exit status 1
        
        Error: Provider produced inconsistent result after apply
        
        When applying changes to aws_opensearchserverless_security_policy.test,
        provider "provider[\"registry.terraform.io/hashicorp/aws\"]" produced an
        unexpected new value: .policy: was cty.StringVal("{\n \"Rules\": [\n  {\n
        \t\"Resource\": [\n  \t\t\"collection/tf-acc-test-840881701409025331\"\n
        \t],\n  \t\"ResourceType\": \"collection\"\n  }\n ],\n \"AWSOwnedKey\":
        true\n}\n"), but now
        cty.StringVal("{\"AWSOwnedKey\":true,\"Rules\":[{\"Resource\":[\"collection/tf-acc-test-840881701409025331\"],\"ResourceType\":\"collection\"}]}").
        
        This is a bug in the provider, which should be reported in the provider's own
        issue tracker.
--- FAIL: TestAccOpenSearchServerlessSecurityPolicy_basic (6.73s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	6.817s
FAIL
make: *** [GNUmakefile:272: testacc] Error 1
```

If I understand that message correctly, the value of `.policy` is being correctly normalized when being persisted to state, but then it's being compared against the non-normalized plan output/config input. I'm not sure of the idiomatic way to suppress that diff in the new framework. Is it `ModifyPlan`?

**Comment by mattburgess** [comment]
OK, tests are passing again now and AWS appear to have sorted out that `ConflictException` issue I was seeing back in December; re-running the tests 10 times in a row hasn't shown any issues.

**Comment by jtbrush56** [comment]
Just going to bump this again since this is a blocker for other PRs.

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

 ```console
make testacc TESTS=TestAccOpenSearchServerlessSecurityPolicy_ PKG=opensearchserverless

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/opensearchserverless/... -v -count 1 -parallel 20 -run='TestAccOpenSearchServerlessSecurityPolicy_'  -timeout 180m
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_disappears (15.19s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_basic (20.43s)
--- PASS: TestAccOpenSearchServerlessSecurityPolicy_update (29.50s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/opensearchserverless	32.715s
```

**Comment by johnsonaj** [comment]
@mattburgess thanks for the contribution! 🎉

**Pull request merged**
