### PR TITLE
Add resource aws_iot_ca_certificate and data aws_iot_registration_code

### LINKED ISSUE #14949: Add Providers to support AWS IoT private CA
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This feature request will add the registration code data source needed to verify
that you own a CA and the resource for importing the CA into AWS IoT Core.

### New or Affected Resource(s)

* aws_iot_ca
Arguments:
ca_certificate (required)
verification_certificate (required)
status: default "ACTIVE" ("INACTIVE", "ACTIVE")
auto_registration: default true

Attributes Reference:
certificate-id

* data.aws_iot_ca_registration_code
No arguments

Attributes Reference:
code
### Potential Terraform Configuration

```hcl
data "aws_iot_ca_registration_code" "example" {}

resource "tls_self_signed_cert" "ca" {
  private_key_pem   = tls_private_key.ca.private_key_pem
  ...
}

resource "tls_private_key" "ca" {...}

resource "tls_cert_request" "verification" {
  key_algorithm   = "RSA"
  private_key_pem = tls_private_key.verification.private_key_pem

  subject {
    common_name = data.aws_iot_ca_registration_code.code
  }
}

resource "tls_private_key" "verification" {...}

resource "tls_locally_signed_cert" "verification" {
  cert_request_pem   = tls_cert_request.verification.cert_request_pem
  ca_private_key_pem = tls_private_key.ca.private_key_pem
  ca_cert_pem        = tls_self_signed_cert.ca.cert_pem
  ...
}

resource "aws_iot_ca" "example" {
  ca_certificate            = tls_self_signed_cert.ca.cert_pem
  verification_certificate  = tls_locally_signed_cert.verification.cert_pem
  status                    = "ACTIVE"
  auto_registration         = true
}

```

### References

https://docs.aws.amazon.com/iot/latest/developerguide/register-CA-cert.html

* #0000

### PR DESCRIPTION
**Pull request by funnybirdman**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14949.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/15840.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/33057.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make test TESTARGS='-run=TestAccAWSIotRegistrationCodeDataSource_basic'
==> Checking that code complies with gofmt requirements...
go test ./... -run=TestAccAWSIotRegistrationCodeDataSource_basic -timeout=120s -parallel=4
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1.714s
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/encryption	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/experimental/sync	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/hashcode	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/mutexkv	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/acmpca/finder	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/acmpca/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/apigatewayv2/waiter	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/cognitoidentityprovider/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/finder	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ecs/waiter	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/guardduty/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/iam/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kafka/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kinesisanalytics/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kms/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/lex/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/neptune/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/rds/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/secretsmanager/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/servicediscovery/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/sfn/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/workspaces/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/xray/waiter	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/vault/helper/pgpkeys	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/vault/sdk/helper/jsonutil	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/helper/awsprovidertype/keyvaluetags	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT002	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT003	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT004	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT005	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT006	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR002	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSV001	(cached) [no tests to run]


$ make test TESTARGS='-run=TestAccAWSIoTCACertificate_certificate'
==> Checking that code complies with gofmt requirements...
go test ./... -run=TestAccAWSIoTCACertificate_certificate -timeout=120s -parallel=4
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1.719s
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/encryption	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/experimental/sync	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/hashcode	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/mutexkv	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/acmpca/finder	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/acmpca/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/apigatewayv2/waiter	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/cognitoidentityprovider/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/finder	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ec2/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ecs/waiter	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/guardduty/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/iam/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kafka/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kinesisanalytics/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kms/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/lex/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/neptune/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/rds/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/secretsmanager/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/servicediscovery/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/sfn/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/workspaces/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/xray/waiter	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/vault/helper/pgpkeys	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/vault/sdk/helper/jsonutil	(cached) [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/helper/awsprovidertype/keyvaluetags	[no test files]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT002	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT003	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT004	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT005	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT006	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR002	(cached) [no tests to run]
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSV001	(cached) [no tests to run]
...
```

### CODE REVIEW

**Comment by EdgarGrimbergNOV** [comment]
There seems to be a small conflict in this PR. @funnybirdman @brandon-bird-yolabs do you have time to fix this?

**Comment by AlmogCohen** [comment]
Any chance to see this included?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccIoTRegistrationCodeDataSource_' PKG=iot
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTRegistrationCodeDataSource_ -timeout 360m
=== RUN   TestAccIoTRegistrationCodeDataSource_basic
=== PAUSE TestAccIoTRegistrationCodeDataSource_basic
=== CONT  TestAccIoTRegistrationCodeDataSource_basic
--- PASS: TestAccIoTRegistrationCodeDataSource_basic (16.37s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	21.673s
```
```console
% make testacc TESTARGS='-run=TestAccIoTCACertificate_' PKG=iot ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 2  -run=TestAccIoTCACertificate_ -timeout 360m
=== RUN   TestAccIoTCACertificate_basic
=== PAUSE TestAccIoTCACertificate_basic
=== RUN   TestAccIoTCACertificate_disappears
=== PAUSE TestAccIoTCACertificate_disappears
=== RUN   TestAccIoTCACertificate_tags
=== PAUSE TestAccIoTCACertificate_tags
=== RUN   TestAccIoTCACertificate_defaultMode
=== PAUSE TestAccIoTCACertificate_defaultMode
=== CONT  TestAccIoTCACertificate_basic
=== CONT  TestAccIoTCACertificate_tags
--- PASS: TestAccIoTCACertificate_basic (21.54s)
=== CONT  TestAccIoTCACertificate_defaultMode
--- PASS: TestAccIoTCACertificate_tags (54.91s)
=== CONT  TestAccIoTCACertificate_disappears
--- PASS: TestAccIoTCACertificate_defaultMode (45.12s)
--- PASS: TestAccIoTCACertificate_disappears (17.64s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	78.487s
```
```console
% make testacc TESTARGS='-run=TestAccIoTCertificate_' PKG=iot ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 2  -run=TestAccIoTCertificate_ -timeout 360m
=== RUN   TestAccIoTCertificate_csr
=== PAUSE TestAccIoTCertificate_csr
=== RUN   TestAccIoTCertificate_Keys_certificate
=== PAUSE TestAccIoTCertificate_Keys_certificate
=== RUN   TestAccIoTCertificate_Keys_existingCertificate
=== PAUSE TestAccIoTCertificate_Keys_existingCertificate
=== CONT  TestAccIoTCertificate_csr
=== CONT  TestAccIoTCertificate_Keys_existingCertificate
--- PASS: TestAccIoTCertificate_csr (24.53s)
=== CONT  TestAccIoTCertificate_Keys_certificate
--- PASS: TestAccIoTCertificate_Keys_existingCertificate (40.24s)
--- PASS: TestAccIoTCertificate_Keys_certificate (19.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	49.638s
```

**Comment by ewbankkit** [comment]
@funnybirdman Thanks for the contribution :tada: :clap:.

**Pull request merged**
