### PR TITLE
Fix aws_ec2_instance_connect_endpoint/fips_dns_name in non-US regions

### LINKED ISSUE #37920: [Bug]: `aws_ec2_instance_connect_endpoint` known after apply issue for `fips_dns_name`
### Terraform Core Version

1.8.5, 1.5.7

### AWS Provider Version

5.53.0, 5.46.0

### Affected Resource(s)

* `aws_ec2_instance_connect_endpoint`

### Expected Behavior

When the `aws_ec2_instance_connect_endpoint` resource is successfully created, all resource attributes are correctly populated. Subsequent `terraform apply` runs do not:
* continually schedule changes to the resource due to missing attribute values,
* crash with `Error: Provider returned invalid result object after apply`.

### Actual Behavior

Each `terraform apply` run after successful EICE creation shows `fips_dns_name` as `(known after apply)`:
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_ec2_instance_connect_endpoint.this will be updated in-place
  ~ resource "aws_ec2_instance_connect_endpoint" "this" {
      + fips_dns_name         = (known after apply)
        id                    = "eice-XXXXXXXXXXXX"
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```
and any attempt to apply this fails with:
```
aws_ec2_instance_connect_endpoint.this: Modifying... [id=eice-XXXXXXXXXXXX]
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for aws_ec2_instance_connect_endpoint.this.fips_dns_name. All values must be known after apply, so this is
│ always a bug in the provider and should be reported in the provider's own repository. Terraform will still save the other known object values in the state.
```

### Relevant Error/Panic Output Snippet

```shell
aws_ec2_instance_connect_endpoint.this: Modifying... [id=eice-XXXXXXXXXXXX]
╷
│ Error: Provider returned invalid result object after apply
│ 
│ After the apply operation, the provider still indicated an unknown value for aws_ec2_instance_connect_endpoint.this.fips_dns_name. All values must be known after apply, so this is
│ always a bug in the provider and should be reported in the provider's own repository. Terraform will still save the other known object values in the state.
```

### Terraform Configuration Files

```hcl
resource "aws_security_group" "this" {
  name_prefix = "sg-eice-"
  description = "Security group for EICE."
  vpc_id      = "vpc-XXXXXX"

  egress {
    from_port   = 22
    to_port     = 22
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow outgoing SSH connections"
  }

  egress {
    from_port   = 3389
    to_port     = 3389
    protocol    = "tcp"
    cidr_blocks = ["0.0.0.0/0"]
    description = "Allow outgoing RDP connections"
  }
}

resource "aws_ec2_instance_connect_endpoint" "this" {
  subnet_id          = "subnet-XXXXXX"
  preserve_client_ip = false
  security_group_ids = [aws_security_group.this.id]
}
```

### Steps to Reproduce

1. run `terraform apply`
2. run `terraform apply` again

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

Running
```
aws ec2 describe-instance-connect-endpoints --instance-connect-endpoint-ids eice-XXXXXXXXXXX
```
on the created EICE does not return any data related to `FipsDnsName`. There is no such property, even though AWS documentation says it should be there.

`DnsName` is populated correctly.

### References

- https://github.com/hashicorp/terraform-provider-aws/issues/32011
- https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Ec2InstanceConnectEndpoint.html#API_Ec2InstanceConnectEndpoint_Contents
- https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-instance-connect-endpoints.html#output

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by arax**
### Description

Outside of FIPS-supported regions (us-east-1, us-east-2, us-west-1, us-west-2, ca-central-1, ca-west-1, us-gov-east-1, us-gov-west-1) AWS API responses for EICE do not contain the `FipsDnsName` property. That leaves the resource in an infinite `fips_dns_name = (known after apply)` loop and results in crashes on apply.

This makes sure  `fips_dns_name` is initialized with an empty string if the `FipsDnsName` property is missing from the AWS API response.

This does not change the resource's documented behavior or the behavior covered by tests.

### Relations

Closes #37920

### References

* https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_Ec2InstanceConnectEndpoint.html#API_Ec2InstanceConnectEndpoint_Contents
* https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/describe-instance-connect-endpoints.html#output
* https://aws.amazon.com/compliance/fips/

### TestAcc Output
For `us-east-1`:
```
❯ make testacc TESTS=TestAccEC2InstanceConnectEndpoint PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstanceConnectEndpoint'  -timeout 360m
=== RUN   TestAccEC2InstanceConnectEndpoint_basic
=== PAUSE TestAccEC2InstanceConnectEndpoint_basic
=== RUN   TestAccEC2InstanceConnectEndpoint_disappears
=== PAUSE TestAccEC2InstanceConnectEndpoint_disappears
=== RUN   TestAccEC2InstanceConnectEndpoint_tags
=== PAUSE TestAccEC2InstanceConnectEndpoint_tags
=== RUN   TestAccEC2InstanceConnectEndpoint_securityGroupIDs
=== PAUSE TestAccEC2InstanceConnectEndpoint_securityGroupIDs
=== CONT  TestAccEC2InstanceConnectEndpoint_basic
=== CONT  TestAccEC2InstanceConnectEndpoint_tags
=== CONT  TestAccEC2InstanceConnectEndpoint_securityGroupIDs
=== CONT  TestAccEC2InstanceConnectEndpoint_disappears
--- PASS: TestAccEC2InstanceConnectEndpoint_basic (388.42s)
--- PASS: TestAccEC2InstanceConnectEndpoint_securityGroupIDs (400.28s)
--- PASS: TestAccEC2InstanceConnectEndpoint_disappears (414.18s)
--- PASS: TestAccEC2InstanceConnectEndpoint_tags (1116.57s)
PASS
ok    [github.com/hashicorp/terraform-provider-aws/internal/service/ec2](http://github.com/hashicorp/terraform-provider-aws/internal/service/ec2)  1124.303s
```

For `eu-west-1`:
```
❯ make testacc TESTS=TestAccEC2InstanceConnectEndpoint PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccEC2InstanceConnectEndpoint'  -timeout 360m
=== RUN   TestAccEC2InstanceConnectEndpoint_basic
=== PAUSE TestAccEC2InstanceConnectEndpoint_basic
=== RUN   TestAccEC2InstanceConnectEndpoint_disappears
=== PAUSE TestAccEC2InstanceConnectEndpoint_disappears
=== RUN   TestAccEC2InstanceConnectEndpoint_tags
=== PAUSE TestAccEC2InstanceConnectEndpoint_tags
=== RUN   TestAccEC2InstanceConnectEndpoint_securityGroupIDs
=== PAUSE TestAccEC2InstanceConnectEndpoint_securityGroupIDs
=== CONT  TestAccEC2InstanceConnectEndpoint_basic
=== CONT  TestAccEC2InstanceConnectEndpoint_tags
=== CONT  TestAccEC2InstanceConnectEndpoint_securityGroupIDs
=== CONT  TestAccEC2InstanceConnectEndpoint_disappears
=== NAME  TestAccEC2InstanceConnectEndpoint_securityGroupIDs
    ec2_instance_connect_endpoint_test.go:138: Step 1/2 error: Check failed: Check 5/14 error: aws_ec2_instance_connect_endpoint.test: Attribute 'fips_dns_name' expected to be set
=== NAME  TestAccEC2InstanceConnectEndpoint_basic
    ec2_instance_connect_endpoint_test.go:29: Step 1/2 error: Check failed: Check 5/12 error: aws_ec2_instance_connect_endpoint.test: Attribute 'fips_dns_name' expected to be set
--- FAIL: TestAccEC2InstanceConnectEndpoint_securityGroupIDs (372.20s)
--- FAIL: TestAccEC2InstanceConnectEndpoint_basic (373.07s)
--- PASS: TestAccEC2InstanceConnectEndpoint_disappears (379.99s)
--- PASS: TestAccEC2InstanceConnectEndpoint_tags (1098.51s)
FAIL
FAIL  [github.com/hashicorp/terraform-provider-aws/internal/service/ec2](http://github.com/hashicorp/terraform-provider-aws/internal/service/ec2)  1107.920s
FAIL
make: *** [testacc] Error 1
```

### CODE REVIEW

**Comment by arax** [comment]
Q: I'm wondering how to properly write acc tests for behavior that depends on specific AWS regions being selected for the test. As shown above in the `testacc` output, `us-east-1` still works as it worked before. `eu-west-1` is still broken as it was broken before. Should I just relax the test criteria and check for a non-null value?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% AWS_DEFAULT_REGION=ap-northeast-1 make testacc TESTARGS='-run=TestAccEC2InstanceConnectEndpoint_nonFIPSRegion' PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2InstanceConnectEndpoint_nonFIPSRegion -timeout 360m
2024/12/27 12:22:16 Initializing Terraform AWS Provider...
=== RUN   TestAccEC2InstanceConnectEndpoint_nonFIPSRegion
=== PAUSE TestAccEC2InstanceConnectEndpoint_nonFIPSRegion
=== CONT  TestAccEC2InstanceConnectEndpoint_nonFIPSRegion
--- PASS: TestAccEC2InstanceConnectEndpoint_nonFIPSRegion (254.53s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	260.294s
```
```console
% make testacc TESTARGS='-run=TestAccEC2InstanceConnectEndpoint_basic\|TestAccEC2InstanceConnectEndpoint_fipsRegion' PKG=ec2
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccEC2InstanceConnectEndpoint_basic\|TestAccEC2InstanceConnectEndpoint_fipsRegion -timeout 360m
2024/12/27 12:29:16 Initializing Terraform AWS Provider...
=== RUN   TestAccEC2InstanceConnectEndpoint_basic
=== PAUSE TestAccEC2InstanceConnectEndpoint_basic
=== RUN   TestAccEC2InstanceConnectEndpoint_fipsRegion
=== PAUSE TestAccEC2InstanceConnectEndpoint_fipsRegion
=== CONT  TestAccEC2InstanceConnectEndpoint_basic
=== CONT  TestAccEC2InstanceConnectEndpoint_fipsRegion
--- PASS: TestAccEC2InstanceConnectEndpoint_basic (362.31s)
--- PASS: TestAccEC2InstanceConnectEndpoint_fipsRegion (364.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	370.237s
```

**Review by nam054 — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
@arax Thanks for the contribution :tada: :clap:.

**Pull request merged**
