### PR TITLE
d/aws_sagemaker_prebuilt_ecr_image - Add new deep learning images and enhance test cases

### LINKED ISSUE #32060: [Enhancement]: Add support for `huggingface-pytorch-tgi-inference` to `aws_sagemaker_prebuilt_ecr_image` data source
### Description

Hi,
I'm getting this error (trying to deploy huggingface LLMs on sagemaker via terraform) : 
##############################################################
```shell
Error: expected repository_name to be one of [blazingtext forecasting-deepar factorization-machines image-classification ipinsights 
kmeans knn lda linear-learner sagemaker-model-monitor-analyzer mxnet-inference mxnet-inference-eia mxnet-training ntm object2vec object-detection pca pytorch-inference pytorch-inference-eia pytorch-training randomcutforest sagemaker-scikit-learn semantic-segmentation 
seq2seq sagemaker-sparkml-serving tensorflow-inference tensorflow-inference-eia sagemaker-tensorflow-serving sagemaker-tensorflow-serving-eia tensorflow-training huggingface-tensorflow-training huggingface-tensorflow-inference huggingface-pytorch-training huggingface-pytorch-inference sagemaker-xgboost], got huggingface-pytorch-tgi-inference
```
##############################################################
Could you please add support for **huggingface-pytorch-tgi-inference** images ? 

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_prebuilt_ecr_image

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by deepakbshetty**
### Description

`d/aws_sagemaker_prebuilt_ecr_image`

[1]   Sync data source with Sagemaker image repositories
[2]   Add new regions to existing image repositories
[3]   Add new test cases for each case condition

### Relations
Closes #32060

### Output from Acceptance Testing
Tested on `us-east-1` and `eu-west-1`

```
$ make testacc TESTS=TestAccSageMakerPrebuiltECRImageDataSource_* PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerPrebuiltECRImageDataSource_*'  -timeout 360m
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_basic
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_basic
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_region
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_region
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseClarify
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseClarify
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerChainer
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerChainer
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerMXNetServingEIA
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerMXNetServingEIA
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerTensorFlowEIA
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerTensorFlowEIA
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerBasePython
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerBasePython
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerRL
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerRL
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSpark
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSpark
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_basic
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerChainer
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerRL
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSpark
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseClarify
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerTensorFlowEIA
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerBasePython
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_region
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerMXNetServingEIA
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger (126.76s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia (131.67s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI (132.46s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseClarify (133.35s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU (135.39s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference (135.39s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerBasePython (135.57s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_region (135.58s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerRL (136.30s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerMXNetServingEIA (136.60s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerTensorFlowEIA (137.26s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSpark (138.38s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch (138.67s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML (138.96s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSagemakerCustomSagemakerChainer (139.21s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_basic (139.48s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler (140.05s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference (140.90s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  172.852s
...
```

### CODE REVIEW

**Comment by deepakbshetty** [comment]
Dear @DrFaust92, Kindly review.

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMakerPrebuiltECRImageDataSource_' PKG=sagemaker ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 4  -run=TestAccSageMakerPrebuiltECRImageDataSource_ -timeout 360m
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_basic
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_basic
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_region
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_region
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseClarify
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseClarify
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerChainer
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerChainer
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerMXNetServingEIA
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerMXNetServingEIA
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerTensorFlowEIA
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerTensorFlowEIA
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerBasePython
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerBasePython
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerRL
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerRL
=== RUN   TestAccSageMakerPrebuiltECRImageDataSource_caseSpark
=== PAUSE TestAccSageMakerPrebuiltECRImageDataSource_caseSpark
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_basic
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerChainer
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerChainer (6.61s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningStabilityAI (6.61s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_basic (6.62s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoInferentiaPyTorch (6.64s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostSparkML (6.16s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseClarify
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDebugger (6.23s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerRL
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDataWrangler (6.25s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSpark
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseXGBoostHuggingFaceTEICPU (6.26s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseClarify (6.13s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSpark (6.06s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerRL (6.14s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_region
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningHuggingFacePyTorchTGIInference (6.14s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerBasePython
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseDeepLearningNVIDIATritionInference (6.28s)
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerTensorFlowEIA
=== CONT  TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerMXNetServingEIA
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerBasePython (6.17s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseInferentiaNeoTensorflowInferentia (6.30s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_region (6.23s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerMXNetServingEIA (5.80s)
--- PASS: TestAccSageMakerPrebuiltECRImageDataSource_caseSageMakerCustomSageMakerTensorFlowEIA (5.83s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	36.021s
```

**Comment by ewbankkit** [comment]
@deepakbshetty Thanks for the contribution :tada: :clap:.

**Pull request merged**
