### PR TITLE
feat: add appconfig_configuration_profile

### PR DESCRIPTION
**Pull request by suzuki-shunsuke**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #11973 #18032 #19307

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAppConfigConfigurationProfile'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppConfigConfigurationProfile -timeout 180m
=== RUN   TestAccAWSAppConfigConfigurationProfile_basic
=== PAUSE TestAccAWSAppConfigConfigurationProfile_basic
=== RUN   TestAccAWSAppConfigConfigurationProfile_disappears
=== PAUSE TestAccAWSAppConfigConfigurationProfile_disappears
=== RUN   TestAccAWSAppConfigConfigurationProfile_Tags
=== PAUSE TestAccAWSAppConfigConfigurationProfile_Tags
=== CONT  TestAccAWSAppConfigConfigurationProfile_basic
=== CONT  TestAccAWSAppConfigConfigurationProfile_Tags
=== CONT  TestAccAWSAppConfigConfigurationProfile_disappears
--- PASS: TestAccAWSAppConfigConfigurationProfile_disappears (52.39s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_basic (62.24s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Tags (121.66s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	123.624s
```

---

This adds `aws_appconfig_configuration_profile` to #19307 to support [AWS AppConfig Configuration Profile](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-appconfig-configurationprofile.html).

### CODE REVIEW

**Comment by suzuki-shunsuke** [comment]
CI was failed. I'll check.

```
FAIL	github.com/terraform-providers/terraform-provider-aws/aws [build failed]
aws/resource_aws_appconfig_configuration_profile_test.go:197:9: undefined: testAccAWSAppConfigApplicationName
```

**Comment by suzuki-shunsuke** [comment]
Renamed https://github.com/hashicorp/terraform-provider-aws/pull/19307/commits/876c4be9519463df40dbfcc3c07680bc2a87adf2

testAccAWSAppConfigApplicationName => testAccAWSAppConfigApplicationConfigDescription

**Comment by anGie44** [comment]
Nice, thanks @suzuki-shunsuke! -- looked related to the method name change I introduced but that should do it 👍 I'm going to give this one a read through, and will merge this one as well. If you don't mind, could you rebase your other draft PRs when you have a moment so we can get those in as well :)

**Comment by suzuki-shunsuke** [comment]
Thanks @anGie44 . I rebased #19324 and #19359

**Comment by suzuki-shunsuke** [comment]
I'm running the acceptance test.

```
$ make testacc TESTARGS='-run=TestAccAWSAppConfigConfigurationProfile'
```

**Comment by suzuki-shunsuke** [comment]
The acceptance test passed.
I updated the description.
https://github.com/hashicorp/terraform-provider-aws/pull/19320#issue-642076612

**Review by anGie44 — APPROVED** [review]
Looks great overall @suzuki-shunsuke ! I'm just adding in a commit to add default tags support (using the data stored in `meta.(*AWSClient).DefaultTagsConfig`) and similar updates to #19307 .

Output of acceptance tests (commercial):
```
--- PASS: TestAccAWSAppConfigConfigurationProfile_disappears (15.89s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_basic (18.92s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_updateName (30.77s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_updateDescription (33.42s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Tags (40.95s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Validators_Multiple (41.04s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Validators_JSON (42.83s)
```

GovCloud:
```
--- PASS: TestAccAWSAppConfigConfigurationProfile_disappears (19.19s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_basic (22.68s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_updateName (37.49s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_updateDescription (39.54s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Validators_Multiple (46.53s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Tags (49.32s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Validators_JSON (52.54s)
--- PASS: TestAccAWSAppConfigConfigurationProfile_Validators_Lambda (54.22s)
```

**Pull request merged**
