### PR TITLE
r/aws_appautoscaling_policy:Enable Metric Math support for TargetTrackingPolicy in Application Au…

### LINKED ISSUE #30049: [Enhancement]: Allow using metric math expressions in aws_appautoscaling_policy
### Description

AWS recently released support for doing metric math in `Application Auto Scaling` [see](https://aws.amazon.com/about-aws/whats-new/2023/03/application-auto-scaling-metric-math-target-tracking-policies/). Having this available would be nice 🥰

### Affected Resource(s) and/or Data Source(s)

aws_appautoscaling_policy

### Potential Terraform Configuration

```terraform
resource "aws_appautoscaling_policy" "ecs_target_cpu" {
  name               = "ScaleOnSQSDepthPerService"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.ecs_service.resource_id
  scalable_dimension = aws_appautoscaling_target.ecs_service.scalable_dimension
  service_namespace  = aws_appautoscaling_target.ecs_service.service_namespace

  target_tracking_scaling_policy_configuration {
    customized_metric_specification {
      target_value = 100
      metrics {
        label = "Get the queue size (the number of messages waiting to be processed)"
        id    = "m1"
        metric_stat {
          metric {
            namespace   = "AWS/SQS"
            metric_name = "ApproximateNumberOfMessagesVisible"
            dimensions {
              name  = "QueueName"
              value = "my-queue"
            }
          }
          stat = "Sum"
        }
        return_data = false
      }
      metrics {
        label = "Get the ECS running task count (the number of currently running tasks)"
        id    = "m2"
        metric_stat {
          metric {
            metric_name = "RunningTaskCount"
            namespace   = "ECS/ContainerInsights"
            dimensions {
              name  = "ClusterName"
              value = "default"
            }
            dimensions {
              name  = "ServiceName"
              value = "web-app"
            }
          }
          stat = "Average"
        }
        return_data = false
      }
      metrics {
        label       = "Calculate the backlog per instance"
        id          = "e1"
        expression  = "m1 / m2"
        return_data = true
      }
    }
  }
}
```

### References

[Whats New in AWS](https://aws.amazon.com/about-aws/whats-new/2023/03/application-auto-scaling-metric-math-target-tracking-policies/)

[AWS Docs](https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking-metric-math.html)

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by snghffc**
### Description
This PR enables Metric Math support for Applicationn AutoScaling TargetTracking policy. The feature was release on March 15, 2023.
https://aws.amazon.com/about-aws/whats-new/2023/03/application-auto-scaling-metric-math-target-tracking-policies/

### Relations

Closes #30049.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/28391.

### References
* https://aws.amazon.com/about-aws/whats-new/2023/03/application-auto-scaling-metric-math-target-tracking-policies/
* https://docs.aws.amazon.com/autoscaling/application/userguide/application-auto-scaling-target-tracking-metric-math.html
* https://docs.aws.amazon.com/autoscaling/application/APIReference/API_CustomizedMetricSpecification.html

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccAppAutoScalingPolicy PKG=appautoscaling
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 20 -run='TestAccAppAutoScalingPolicy'  -timeout 180m
=== RUN   TestAccAppAutoScalingPolicy_basic
=== PAUSE TestAccAppAutoScalingPolicy_basic
=== RUN   TestAccAppAutoScalingPolicy_disappears
=== PAUSE TestAccAppAutoScalingPolicy_disappears
=== RUN   TestAccAppAutoScalingPolicy_scaleOutAndIn
=== PAUSE TestAccAppAutoScalingPolicy_scaleOutAndIn
=== RUN   TestAccAppAutoScalingPolicy_spotFleetRequest
=== PAUSE TestAccAppAutoScalingPolicy_spotFleetRequest
=== RUN   TestAccAppAutoScalingPolicy_DynamoDB_table
=== PAUSE TestAccAppAutoScalingPolicy_DynamoDB_table
=== RUN   TestAccAppAutoScalingPolicy_DynamoDB_index
=== PAUSE TestAccAppAutoScalingPolicy_DynamoDB_index
=== RUN   TestAccAppAutoScalingPolicy_multiplePoliciesSameName
=== PAUSE TestAccAppAutoScalingPolicy_multiplePoliciesSameName
=== RUN   TestAccAppAutoScalingPolicy_multiplePoliciesSameResource
=== PAUSE TestAccAppAutoScalingPolicy_multiplePoliciesSameResource
=== RUN   TestAccAppAutoScalingPolicy_ResourceID_forceNew
=== PAUSE TestAccAppAutoScalingPolicy_ResourceID_forceNew
=== RUN   TestAccAppAutoScalingPolicy_TargetTrack_metricMath
=== PAUSE TestAccAppAutoScalingPolicy_TargetTrack_metricMath
=== CONT  TestAccAppAutoScalingPolicy_basic
=== CONT  TestAccAppAutoScalingPolicy_DynamoDB_index
=== CONT  TestAccAppAutoScalingPolicy_ResourceID_forceNew
=== CONT  TestAccAppAutoScalingPolicy_multiplePoliciesSameResource
=== CONT  TestAccAppAutoScalingPolicy_spotFleetRequest
=== CONT  TestAccAppAutoScalingPolicy_scaleOutAndIn
=== CONT  TestAccAppAutoScalingPolicy_TargetTrack_metricMath
=== CONT  TestAccAppAutoScalingPolicy_disappears
=== CONT  TestAccAppAutoScalingPolicy_DynamoDB_table
=== CONT  TestAccAppAutoScalingPolicy_multiplePoliciesSameName
--- PASS: TestAccAppAutoScalingPolicy_multiplePoliciesSameName (34.43s)
--- PASS: TestAccAppAutoScalingPolicy_DynamoDB_table (36.56s)
--- PASS: TestAccAppAutoScalingPolicy_multiplePoliciesSameResource (48.00s)
--- PASS: TestAccAppAutoScalingPolicy_DynamoDB_index (52.79s)
--- PASS: TestAccAppAutoScalingPolicy_spotFleetRequest (68.37s)
--- PASS: TestAccAppAutoScalingPolicy_disappears (84.47s)
--- PASS: TestAccAppAutoScalingPolicy_basic (87.37s)
--- PASS: TestAccAppAutoScalingPolicy_scaleOutAndIn (91.17s)
--- PASS: TestAccAppAutoScalingPolicy_ResourceID_forceNew (98.28s)
--- PASS: TestAccAppAutoScalingPolicy_TargetTrack_metricMath (98.73s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling     103.990s
...
```

### CODE REVIEW

**Comment by jungseoklee** [comment]
I am an author on #28560. This PR looks good to me.

**Review by jungseoklee — APPROVED** [review]
I am an author on #28560. The acceptance testing covers all combinations of metric data queries, e.g. expression with metric stat, standalone expression, expression relying on other metric data queries, metric with dimensions, and metric without dimensions. Hence, this PR looks good to me.

**Comment by jas550** [comment]
Hi,

Do you when this feature will be merged and if it will be available for aws provider version 3?

**Comment by tomcart90** [comment]
Still waiting on this one. Does it need further review? Is it worth tagging those who reviewed https://github.com/hashicorp/terraform-provider-aws/pull/28560?

**Comment by snghffc** [comment]
@ewbankkit Can we please get some help on this PR? 
I see your contribution on a similar code change we did for EC2 AutoScaling #28560

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAppAutoScalingPolicy_' PKG=appautoscaling ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 2  -run=TestAccAppAutoScalingPolicy_ -timeout 180m
=== RUN   TestAccAppAutoScalingPolicy_basic
=== PAUSE TestAccAppAutoScalingPolicy_basic
=== RUN   TestAccAppAutoScalingPolicy_disappears
=== PAUSE TestAccAppAutoScalingPolicy_disappears
=== RUN   TestAccAppAutoScalingPolicy_scaleOutAndIn
=== PAUSE TestAccAppAutoScalingPolicy_scaleOutAndIn
=== RUN   TestAccAppAutoScalingPolicy_spotFleetRequest
=== PAUSE TestAccAppAutoScalingPolicy_spotFleetRequest
=== RUN   TestAccAppAutoScalingPolicy_DynamoDB_table
=== PAUSE TestAccAppAutoScalingPolicy_DynamoDB_table
=== RUN   TestAccAppAutoScalingPolicy_DynamoDB_index
=== PAUSE TestAccAppAutoScalingPolicy_DynamoDB_index
=== RUN   TestAccAppAutoScalingPolicy_multiplePoliciesSameName
=== PAUSE TestAccAppAutoScalingPolicy_multiplePoliciesSameName
=== RUN   TestAccAppAutoScalingPolicy_multiplePoliciesSameResource
=== PAUSE TestAccAppAutoScalingPolicy_multiplePoliciesSameResource
=== RUN   TestAccAppAutoScalingPolicy_ResourceID_forceNew
=== PAUSE TestAccAppAutoScalingPolicy_ResourceID_forceNew
=== RUN   TestAccAppAutoScalingPolicy_TargetTrack_metricMath
=== PAUSE TestAccAppAutoScalingPolicy_TargetTrack_metricMath
=== CONT  TestAccAppAutoScalingPolicy_basic
=== CONT  TestAccAppAutoScalingPolicy_DynamoDB_index
--- PASS: TestAccAppAutoScalingPolicy_DynamoDB_index (36.41s)
=== CONT  TestAccAppAutoScalingPolicy_spotFleetRequest
--- PASS: TestAccAppAutoScalingPolicy_basic (78.27s)
=== CONT  TestAccAppAutoScalingPolicy_DynamoDB_table
--- PASS: TestAccAppAutoScalingPolicy_DynamoDB_table (27.88s)
=== CONT  TestAccAppAutoScalingPolicy_scaleOutAndIn
--- PASS: TestAccAppAutoScalingPolicy_spotFleetRequest (82.96s)
=== CONT  TestAccAppAutoScalingPolicy_disappears
--- PASS: TestAccAppAutoScalingPolicy_scaleOutAndIn (81.02s)
=== CONT  TestAccAppAutoScalingPolicy_ResourceID_forceNew
--- PASS: TestAccAppAutoScalingPolicy_disappears (74.80s)
=== CONT  TestAccAppAutoScalingPolicy_TargetTrack_metricMath
--- PASS: TestAccAppAutoScalingPolicy_TargetTrack_metricMath (77.71s)
=== CONT  TestAccAppAutoScalingPolicy_multiplePoliciesSameResource
--- PASS: TestAccAppAutoScalingPolicy_ResourceID_forceNew (90.37s)
=== CONT  TestAccAppAutoScalingPolicy_multiplePoliciesSameName
--- PASS: TestAccAppAutoScalingPolicy_multiplePoliciesSameName (25.74s)
--- PASS: TestAccAppAutoScalingPolicy_multiplePoliciesSameResource (32.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	309.268s
```
```console
% make testacc TESTARGS='-run=TestAccAppAutoScalingTarget_' PKG=appautoscaling ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 3  -run=TestAccAppAutoScalingTarget_ -timeout 180m
=== RUN   TestAccAppAutoScalingTarget_basic
=== PAUSE TestAccAppAutoScalingTarget_basic
=== RUN   TestAccAppAutoScalingTarget_disappears
=== PAUSE TestAccAppAutoScalingTarget_disappears
=== RUN   TestAccAppAutoScalingTarget_tags
=== PAUSE TestAccAppAutoScalingTarget_tags
=== RUN   TestAccAppAutoScalingTarget_spotFleetRequest
=== PAUSE TestAccAppAutoScalingTarget_spotFleetRequest
=== RUN   TestAccAppAutoScalingTarget_emrCluster
=== PAUSE TestAccAppAutoScalingTarget_emrCluster
=== RUN   TestAccAppAutoScalingTarget_multipleTargets
=== PAUSE TestAccAppAutoScalingTarget_multipleTargets
=== RUN   TestAccAppAutoScalingTarget_optionalRoleARN
=== PAUSE TestAccAppAutoScalingTarget_optionalRoleARN
=== CONT  TestAccAppAutoScalingTarget_basic
=== CONT  TestAccAppAutoScalingTarget_emrCluster
=== CONT  TestAccAppAutoScalingTarget_tags
--- PASS: TestAccAppAutoScalingTarget_tags (52.60s)
=== CONT  TestAccAppAutoScalingTarget_spotFleetRequest
--- PASS: TestAccAppAutoScalingTarget_basic (80.80s)
=== CONT  TestAccAppAutoScalingTarget_disappears
--- PASS: TestAccAppAutoScalingTarget_spotFleetRequest (83.75s)
=== CONT  TestAccAppAutoScalingTarget_optionalRoleARN
--- PASS: TestAccAppAutoScalingTarget_optionalRoleARN (25.10s)
=== CONT  TestAccAppAutoScalingTarget_multipleTargets
--- PASS: TestAccAppAutoScalingTarget_multipleTargets (25.95s)
--- PASS: TestAccAppAutoScalingTarget_disappears (84.06s)
--- PASS: TestAccAppAutoScalingTarget_emrCluster (612.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	618.376s
```

**Comment by snghffc** [comment]
Thank you so much @ewbankkit for your help on this PR.

**Comment by jas550** [comment]
Hi, will this be available for aws provider version 3 as well?

**Comment by jasonarewhy** [comment]
@snghffc @ewbankkit thanks for the additions. However, the provider is now erroring when trying to refresh state for existing targets _without_ tags:
```
Error: listing tags for Application Auto Scaling Target (): InvalidParameter: 1 validation error(s) found. - minimum field size of 1, ListTagsForResourceInput.ResourceARN
```

**Comment by SJBarden** [comment]
Yes also receiving the above error.
│ Error: listing tags for Application Auto Scaling Target (): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, ListTagsForResourceInput.ResourceARN.
│
│
│   with aws_appautoscaling_target.service_autoscale

**Comment by tribecar-shurn** [comment]
Also receiving this error:

<span><span>

│ Error: listing tags for Application Auto Scaling Target (): InvalidParameter: 1 validation error(s) found.
--


</span></span><span><span>│ - minimum field size of 1, ListTagsForResourceInput.ResourceARN.</span></span>

**Comment by snghffc** [comment]
Can you please share more details about the error?
What is the Test scenario and the provided API request for test?
Looking at the error message, It looks like ResourceARN property might not have been provided which is resulting in validation error. 
ResourceARN is a required parameter : https://docs.aws.amazon.com/autoscaling/application/APIReference/API_ListTagsForResource.html

**Comment by tribecar-shurn** [comment]
For me use case this is my resource block:

`resource "aws_appautoscaling_target" "tc-a-t-wla-dev" {`
`  max_capacity       = 4`
`  min_capacity       = 1`
`  resource_id        = "service/${aws_ecs_cluster.tc-ecs-c-wla-dev.name}/${aws_ecs_service.tc-ecs-s-wla-dev.name}"`
`  scalable_dimension = "ecs:service:DesiredCount"`
`  service_namespace  = "ecs"`
`}`

This resource block is working fine in 4.65.0.
According to https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/appautoscaling_target, all the required attributes have been provided.

**Comment by SJBarden** [comment]
Terraform works with 4.65 for Autoscaling (No Code Changes in the Terraform), however something has been introduced in 4.66 that is producing the above error.

Its almost like listing tags are now a required field. However in my code I have no tags listed. This works on 4.65.

resource "aws_appautoscaling_target" "service_autoscale" {
  min_capacity       = var.service_min_capacity
  max_capacity       = var.service_max_capacity
  resource_id        = "service/${local.prefix}/${aws_ecs_service.service.name}"
  scalable_dimension = "ecs:service:DesiredCount"
  service_namespace  = "ecs"
}

resource "aws_appautoscaling_policy" "service_autoscale" {
  name               = "${local.prefix}-${var.service_name}-autoscale"
  policy_type        = "TargetTrackingScaling"
  resource_id        = aws_appautoscaling_target.service_autoscale.resource_id
  scalable_dimension = aws_appautoscaling_target.service_autoscale.scalable_dimension
  service_namespace  = aws_appautoscaling_target.service_autoscale.service_namespace
  target_tracking_scaling_policy_configuration {
    predefined_metric_specification {
      predefined_metric_type = "ECSServiceAverageCPUUtilization"
    }
    target_value       = 50
    scale_in_cooldown  = 60
    scale_out_cooldown = 300
  }
}

**Comment by flowconic** [comment]
we are also facing this issue, our block is similar to yours @tribecar-shurn and with 4.66.0 it also started breaking. We are not having any tags in the resource block

**Comment by ghdiska** [comment]
the bug ( https://github.com/hashicorp/terraform-provider-aws/issues/31180 ) in version 4.66 can be related to this commit ?

**Comment by tribecar-shurn** [comment]
Looks like the same issue.

**Comment by JJiangZS** [comment]
Hi, I am facing the same issue, I must untick the checkbox named "Use service auto scaling" then this issue has gone.

**error details:**

The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.

module.main.module.service.module.service.data.aws_ecs_cluster.this: Refreshing state... [id=arn:aws:ecs:xxxx:cluster/APP-ECS]
module.main.module.service.module.service.data.aws_security_groups.ecs[0]: Refreshing state... [id=ap-southeast-1]
module.main.module.service.module.service.data.aws_iam_role.execute_role: Refreshing state... [id=APP-TASKEXE-ROLE]
module.main.module.service.module.service.data.aws_subnet.this: Refreshing state... [id=xxxx]
module.main.module.service.module.service.data.aws_iam_role.task_role: Refreshing state... [id=APP-TASK-ROLE]
module.main.module.service.module.service.data.aws_region.current: Refreshing state... [id=xxx]
module.main.module.service.module.service.data.aws_lb.this[0]: Refreshing state... [id=arn:aws:elasticloadbalancing:xxxxx:loadbalancer/app/APP-ALB/xxxxxxx]
module.main.module.service.module.service.aws_service_discovery_service.this[0]: Refreshing state... [id=xxxxxxx]
module.main.module.service.module.service.data.aws_arn.cluster: Refreshing state... [id=arn:aws:ecs:xxxxx:cluster/APP-APAC-ECS]
module.main.module.service.module.service.data.aws_lb_listener.public_443[0]: Refreshing state... [id=arn:aws:elasticloadbalancing:xxxxx:listener/app/APP-ALB/xxx/xxxx]
module.main.module.service.module.service.data.aws_vpc.this: Refreshing state... [id=xxxx]
module.main.module.service.module.service.aws_lb_target_group.this[0]: Refreshing state... [id=arn:aws:elasticloadbalancing:xxx:targetgroup/xxxxxx/xxxxx]
module.main.module.service.module.service.aws_lb_listener_rule.this[0]: Refreshing state... [id=arn:aws:elasticloadbalancing:xxxxx:listener-rule/app/APP-ALB/xxx/xxx/xxx]
module.main.module.service.module.service.aws_ecs_task_definition.this: Refreshing state... [id=app]
module.main.module.service.module.service.aws_ecs_service.this: Refreshing state... [id=arn:aws:ecs:app:service/APP-ECS/app-service]
module.main.module.service.module.service.aws_appautoscaling_target.this: Refreshing state... [id=service/APP-ECS/app-service]

Error: listing tags for Application Auto Scaling Target (): InvalidParameter: 1 validation error(s) found.
- minimum field size of 1, ListTagsForResourceInput.ResourceARN.



##[error]Error: The process '/usr/bin/bash' failed because one or more lines were written to the STDERR stream
Finishing: Validate Terraform

**Comment by btara1** [comment]
Does this change mandate some code updates which are not yet published in the registry?

**Comment by coolbananas118** [comment]
We have this bug also. We just upgraded Terraform from 1.1.7 -> 1.4.6. I reported it and another team in the company has seen it also but they didn't do any upgrade, it just started happening for them, they are using version 0.14.6. Another strange thing: deployments in 2x other environments was fine but only occurs in 1 environment. It seems to be random.

**Pull request merged**
