### PR TITLE
new resource: `aws_sagemaker_data_quality_job_definition`

### LINKED ISSUE #29768: [New Resource]: aws_sagemaker_monitoring_schedule
### Description

We would like to be able to manage Sagemaker monitoring schedules through terraform.  Some more detail on this capability can be found here:

https://docs.aws.amazon.com/sagemaker/latest/dg/model-monitor-scheduling.html

### Requested Resource(s) and/or Data Source(s)

* aws_sagemaker_monitoring_schedule

### Potential Terraform Configuration

```terraform
resource "aws_sagemaker_monitoring_schedule" "my_schedule" {
  config = {
    monitoring_job_definition = {
      monitoring_app_specification = {
        image_uri = "ecr.awsamazon.com/my_image"
        container_arguments = ["--foo", "--bar"]
        container_entrypoint = ["/monitor/start", "--run"]
        post_analytics_processor_source_uri = "http://myanalyticsuri.com"
        record_preprocessor_source_uri = "http://mypreprocessoruri.com"
      }
      monitoring_inputs = [
        {
          endpoint_name = "my-inference-endpoint"
          local_path = "/mnt/endpoint"
          end_time_offset = "-PT7H"
          features_attribute = "feature"
          inference_attribute = "inference"
          probability_attribute = "probability"
          probability_threshold_attribute = 0.1
          s3_data_distribution_type = "ShardedByS3Key"
          s3_input_mode = "Pipe"
          start_time_offset = "-PT7H"
        },
        {
          data_captured_destination_s3_uri = "s3://captured-data-bucket"
          dataset_format = {
            json = {
              line = true
            }
          }
          local_path = "/mnt/endpoint"
          end_time_offset = "-PT7H"
          features_attribute = "feature"
          inference_attribute = "inference"
          probability_attribute = "probability"
          probability_threshold_attribute = 0.1
          s3_data_distribution_type = "ShardedByS3Key"
          s3_input_mode = "Pipe"
          start_time_offset = "-PT7H"
        }
      ]
      monitoring_output_config = {
        monitoring_outputs = [
          {
            s3_output = {
              local_path = "/monitor/output"
              s3_uri = "s3://monitor-output-bucket"
              s3_upload_mode = "Continuous"
            }
          }
        ]
        kms_key_id = "alias/key_id"
      }
      monitoring_resources = {
        cluster_config = {
          instance_count = 2
          instance_type = "ml.t3.large"
          volume_size_in_gb = 100
          volume_kms_key_id = "alias/my_key"
        }
      }
      role_arn = "arn::1234567:iam:my_role"
      baseline_config = {
        baselining_job_name = "baselining"
        constraints_resource = {
          s3_uri = "s3://my-constraint/constraint.csv"
        }
        statistics_resource = {
          s3_uri = "s3://my-statistics/statistics.csv"
        }
      }
      environment = {
        foo = "bar"
      }
      network_config = {
        enable_inter_container_traffic_encryption = true
        enable_network_isolation = true
        vpc_config = {
          SecurityGroupIds = ["sg-123456789"]
          Subnets = ["subnet-123456789"]
        }
      }
      monitoring_stopping_condition = {
        max_runtime_in_seconds = 3600
      }
    }
    monitoring_job_name = "my_job"
    type = "DataQuality"
    schedule_config = {
      schedule_expression = "cron(0 * ? * * *)"
    }   
  }
  name = "my_schedule"
  tags = ["tag1", "tag2"]
}
```

### References

Sagemaker [CreateMonitoringSchedule](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.CreateMonitoringSchedule)
Sagemaker [DeleteMonitoringSchedule](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.DeleteMonitoringSchedule)
Sagemaker [DescribeMonitoringSchedule](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.DescribeMonitoringSchedule)
Sagemaker [ListMonitoringSchedules](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.ListMonitoringSchedules)
Sagemaker [StartMonitoringSchedule](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.StartMonitoringSchedule)
Sagemaker [StopMonitoringSchedule](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.StopMonitoringSchedule)
Sagemaker [UpdateMonitoringSchedule](https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/sagemaker#Client.UpdateMonitoringSchedule)

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by wrbooth**
### Description

Adds a new resource:

- `aws_sagemaker_data_quality_job_definition`: A definition of a job that monitors data quality and drift for sagemaker endpoints or batch transforms. 

Adds `sagemaker-model-monitor-analyzer` to `aws_sagemaker_prebuilt_ecr_image` data source.

### Relations

Relates #29768.

### References

[CreateDataQualityJobDefinition Documentation](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateDataQualityJobDefinition.html)
### Output from Acceptance Testing

```
❯ make testacc TESTS=TestAccSageMakerDataQualityJobDefinition PKG=sagemaker
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerDataQualityJobDefinition'  -timeout 180m
=== RUN   TestAccSageMakerDataQualityJobDefinition_endpoint
=== PAUSE TestAccSageMakerDataQualityJobDefinition_endpoint
=== RUN   TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_baselineConfig
=== PAUSE TestAccSageMakerDataQualityJobDefinition_baselineConfig
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransform
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransform
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformCsvHeader
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformCsvHeader
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformJson
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformJson
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformJsonLine
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformJsonLine
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_endpointOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_endpointOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId
=== PAUSE TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId
=== RUN   TestAccSageMakerDataQualityJobDefinition_outputConfigOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_outputConfigOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId
=== PAUSE TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId
=== RUN   TestAccSageMakerDataQualityJobDefinition_stoppingCondition
=== PAUSE TestAccSageMakerDataQualityJobDefinition_stoppingCondition
=== RUN   TestAccSageMakerDataQualityJobDefinition_networkConfig
=== PAUSE TestAccSageMakerDataQualityJobDefinition_networkConfig
=== RUN   TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption
=== PAUSE TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption
=== RUN   TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation
=== PAUSE TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation
=== RUN   TestAccSageMakerDataQualityJobDefinition_tags
=== PAUSE TestAccSageMakerDataQualityJobDefinition_tags
=== RUN   TestAccSageMakerDataQualityJobDefinition_disappears
=== PAUSE TestAccSageMakerDataQualityJobDefinition_disappears
=== CONT  TestAccSageMakerDataQualityJobDefinition_endpoint
=== CONT  TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformJson
=== CONT  TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation
=== CONT  TestAccSageMakerDataQualityJobDefinition_stoppingCondition
=== CONT  TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption
=== CONT  TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId
=== CONT  TestAccSageMakerDataQualityJobDefinition_disappears
=== CONT  TestAccSageMakerDataQualityJobDefinition_tags
=== CONT  TestAccSageMakerDataQualityJobDefinition_outputConfigOptional
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformOptional
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformJsonLine
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransform
=== CONT  TestAccSageMakerDataQualityJobDefinition_endpointOptional
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformCsvHeader
=== CONT  TestAccSageMakerDataQualityJobDefinition_networkConfig
=== CONT  TestAccSageMakerDataQualityJobDefinition_baselineConfig
=== CONT  TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional
--- PASS: TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId (46.58s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_outputConfigOptional (48.37s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation (51.35s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformJson (53.48s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_baselineConfig (54.07s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId (55.10s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_networkConfig (55.39s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_disappears (61.75s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransform (63.27s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformOptional (63.44s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional (65.97s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformCsvHeader (66.47s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformJsonLine (66.71s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption (68.21s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_stoppingCondition (70.17s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_tags (99.12s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_endpointOptional (240.34s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_endpoint (300.10s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	302.730s
❯
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
Hi [wrbooth](https://github.com/wrbooth), please split this PR to a resource per PR (as contribution guide suggests)

**Comment by wrbooth** [comment]
> Hi [wrbooth](https://github.com/wrbooth), please split this PR to a resource per PR (as contribution guide suggests)

Very sorry about that!  I've removed `aws_sagemaker_monitoring_schedule` from this PR and will open a new PR (dependent on this PR.)

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMakerDataQualityJobDefinition_' PKG=sagemaker ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 3  -run=TestAccSageMakerDataQualityJobDefinition_ -timeout 180m
=== RUN   TestAccSageMakerDataQualityJobDefinition_endpoint
=== PAUSE TestAccSageMakerDataQualityJobDefinition_endpoint
=== RUN   TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_baselineConfig
=== PAUSE TestAccSageMakerDataQualityJobDefinition_baselineConfig
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransform
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransform
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformCSVHeader
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformCSVHeader
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformJSON
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformJSON
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformJSONLine
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformJSONLine
=== RUN   TestAccSageMakerDataQualityJobDefinition_batchTransformOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_batchTransformOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_endpointOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_endpointOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId
=== PAUSE TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId
=== RUN   TestAccSageMakerDataQualityJobDefinition_outputConfigOptional
=== PAUSE TestAccSageMakerDataQualityJobDefinition_outputConfigOptional
=== RUN   TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId
=== PAUSE TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId
=== RUN   TestAccSageMakerDataQualityJobDefinition_stoppingCondition
=== PAUSE TestAccSageMakerDataQualityJobDefinition_stoppingCondition
=== RUN   TestAccSageMakerDataQualityJobDefinition_networkConfig
=== PAUSE TestAccSageMakerDataQualityJobDefinition_networkConfig
=== RUN   TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption
=== PAUSE TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption
=== RUN   TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation
=== PAUSE TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation
=== RUN   TestAccSageMakerDataQualityJobDefinition_tags
=== PAUSE TestAccSageMakerDataQualityJobDefinition_tags
=== RUN   TestAccSageMakerDataQualityJobDefinition_disappears
=== PAUSE TestAccSageMakerDataQualityJobDefinition_disappears
=== CONT  TestAccSageMakerDataQualityJobDefinition_endpoint
=== CONT  TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformJSON
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformJSON (25.91s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption
--- PASS: TestAccSageMakerDataQualityJobDefinition_ouputConfigKmsKeyId (28.42s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_disappears
--- PASS: TestAccSageMakerDataQualityJobDefinition_disappears (21.89s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_tags
--- PASS: TestAccSageMakerDataQualityJobDefinition_networkConfigTrafficEncryption (27.99s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation
--- PASS: TestAccSageMakerDataQualityJobDefinition_networkConfigEnableNetworkIsolation (26.35s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransform
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransform (23.30s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformCSVHeader
--- PASS: TestAccSageMakerDataQualityJobDefinition_tags (55.71s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_baselineConfig
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformCSVHeader (24.26s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_stoppingCondition
--- PASS: TestAccSageMakerDataQualityJobDefinition_baselineConfig (24.32s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_networkConfig
--- PASS: TestAccSageMakerDataQualityJobDefinition_stoppingCondition (22.95s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformOptional
--- PASS: TestAccSageMakerDataQualityJobDefinition_networkConfig (26.39s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_endpointOptional
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformOptional (29.03s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId
--- PASS: TestAccSageMakerDataQualityJobDefinition_jobResourcesVolumeKmsKeyId (30.52s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_batchTransformJSONLine
--- PASS: TestAccSageMakerDataQualityJobDefinition_endpoint (231.40s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_outputConfigOptional
--- PASS: TestAccSageMakerDataQualityJobDefinition_batchTransformJSONLine (46.74s)
=== CONT  TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional
--- PASS: TestAccSageMakerDataQualityJobDefinition_outputConfigOptional (62.26s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_appSpecificationOptional (52.44s)
--- PASS: TestAccSageMakerDataQualityJobDefinition_endpointOptional (354.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	516.677s
```

**Comment by ewbankkit** [comment]
@wrbooth Thanks for the contribution :tada: :clap:.

**Comment by wrbooth** [comment]
> @wrbooth Thanks for the contribution 🎉 👏.

Sure thing!  Thanks for the quick review and all the additions to get it merged!

I've just filed PR #30684 for the remainder of the code per request.

**Pull request merged**
