### PR TITLE
aws wafv2 webacl managed rule group version support

### LINKED ISSUE #20817: Add support for fixed versions for managed rules in WAFv2
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently added [versioning to WAFv2 rule groups](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-waf-offers-managed-rule-group-versioning/). You either use the newest version of a rule group (default) or can fix a specific version for your ACL (wanted by this feature request).

Currently, everyone using AWS managed rules has not way in Terraform to prevent AWS from updating the underlying rules and possibly breaking the production environment. This feature will enable you to fix a specific version and later safely upgrade to a new version of the rule group on production when you have already tested it on another stage.

### New or Affected Resource(s)

* aws_wafv2_web_acl
* aws_wafv2_rule_group

### References

* [AWS What's New: AWS WAF now offers managed rule group versioning](https://aws.amazon.com/about-aws/whats-new/2021/08/aws-waf-offers-managed-rule-group-versioning/)
* [AWS Documentation: Version management for managed rule groups ](https://docs.aws.amazon.com/waf/latest/developerguide/waf-managed-rule-groups-versioning.html)

### PR DESCRIPTION
**Pull request by galoitsu**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #20817 #21546 

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccWAFV2WebACL_.*' PKG_NAME=internal/service/wafv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run=TestAccWAFV2WebACL_.* -timeout 180m
=== RUN   TestAccWAFV2WebACL_basic
=== PAUSE TestAccWAFV2WebACL_basic
=== RUN   TestAccWAFV2WebACL_Update_rule
=== PAUSE TestAccWAFV2WebACL_Update_rule
=== RUN   TestAccWAFV2WebACL_Update_ruleProperties
=== PAUSE TestAccWAFV2WebACL_Update_ruleProperties
=== RUN   TestAccWAFV2WebACL_Update_nameForceNew
=== PAUSE TestAccWAFV2WebACL_Update_nameForceNew
=== RUN   TestAccWAFV2WebACL_disappears
=== PAUSE TestAccWAFV2WebACL_disappears
=== RUN   TestAccWAFV2WebACL_ManagedRuleGroup_basic
=== PAUSE TestAccWAFV2WebACL_ManagedRuleGroup_basic
=== RUN   TestAccWAFV2WebACL_ManagedRuleGroup_specify_version
=== PAUSE TestAccWAFV2WebACL_ManagedRuleGroup_specify_version
=== RUN   TestAccWAFV2WebACL_minimal
=== PAUSE TestAccWAFV2WebACL_minimal
=== RUN   TestAccWAFV2WebACL_RateBased_basic
=== PAUSE TestAccWAFV2WebACL_RateBased_basic
=== RUN   TestAccWAFV2WebACL_GeoMatch_basic
=== PAUSE TestAccWAFV2WebACL_GeoMatch_basic
=== RUN   TestAccWAFV2WebACL_GeoMatch_forwardedIP
=== PAUSE TestAccWAFV2WebACL_GeoMatch_forwardedIP
=== RUN   TestAccWAFV2WebACL_IPSetReference_basic
=== PAUSE TestAccWAFV2WebACL_IPSetReference_basic
=== RUN   TestAccWAFV2WebACL_IPSetReference_forwardedIP
=== PAUSE TestAccWAFV2WebACL_IPSetReference_forwardedIP
=== RUN   TestAccWAFV2WebACL_RateBased_forwardedIP
=== PAUSE TestAccWAFV2WebACL_RateBased_forwardedIP
=== RUN   TestAccWAFV2WebACL_RuleGroupReference_basic
=== PAUSE TestAccWAFV2WebACL_RuleGroupReference_basic
=== RUN   TestAccWAFV2WebACL_Custom_requestHandling
=== PAUSE TestAccWAFV2WebACL_Custom_requestHandling
=== RUN   TestAccWAFV2WebACL_Custom_response
=== PAUSE TestAccWAFV2WebACL_Custom_response
=== RUN   TestAccWAFV2WebACL_tags
=== PAUSE TestAccWAFV2WebACL_tags
=== RUN   TestAccWAFV2WebACL_RateBased_maxNested
=== PAUSE TestAccWAFV2WebACL_RateBased_maxNested
=== RUN   TestAccWAFV2WebACL_Operators_maxNested
=== PAUSE TestAccWAFV2WebACL_Operators_maxNested
=== CONT  TestAccWAFV2WebACL_basic
=== CONT  TestAccWAFV2WebACL_IPSetReference_basic
=== CONT  TestAccWAFV2WebACL_RateBased_maxNested
=== CONT  TestAccWAFV2WebACL_IPSetReference_forwardedIP
=== CONT  TestAccWAFV2WebACL_tags
=== CONT  TestAccWAFV2WebACL_Custom_response
=== CONT  TestAccWAFV2WebACL_Operators_maxNested
=== CONT  TestAccWAFV2WebACL_ManagedRuleGroup_specify_version
=== CONT  TestAccWAFV2WebACL_minimal
=== CONT  TestAccWAFV2WebACL_Custom_requestHandling
=== CONT  TestAccWAFV2WebACL_ManagedRuleGroup_basic
=== CONT  TestAccWAFV2WebACL_disappears
=== CONT  TestAccWAFV2WebACL_Update_ruleProperties
=== CONT  TestAccWAFV2WebACL_RuleGroupReference_basic
=== CONT  TestAccWAFV2WebACL_RateBased_forwardedIP
=== CONT  TestAccWAFV2WebACL_Update_rule
=== CONT  TestAccWAFV2WebACL_GeoMatch_basic
=== CONT  TestAccWAFV2WebACL_GeoMatch_forwardedIP
=== CONT  TestAccWAFV2WebACL_RateBased_basic
=== CONT  TestAccWAFV2WebACL_Update_nameForceNew
--- PASS: TestAccWAFV2WebACL_disappears (124.47s)
--- PASS: TestAccWAFV2WebACL_minimal (128.20s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_basic (138.20s)
--- PASS: TestAccWAFV2WebACL_Operators_maxNested (157.40s)
--- PASS: TestAccWAFV2WebACL_RateBased_maxNested (164.10s)
--- PASS: TestAccWAFV2WebACL_basic (166.96s)
--- PASS: TestAccWAFV2WebACL_Update_nameForceNew (188.22s)
--- PASS: TestAccWAFV2WebACL_RateBased_basic (209.13s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_forwardedIP (211.13s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_basic (212.59s)
--- PASS: TestAccWAFV2WebACL_Custom_response (213.74s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_specify_version (214.24s)
--- PASS: TestAccWAFV2WebACL_Custom_requestHandling (214.98s)
--- PASS: TestAccWAFV2WebACL_RateBased_forwardedIP (215.95s)
--- PASS: TestAccWAFV2WebACL_RuleGroupReference_basic (222.37s)
--- PASS: TestAccWAFV2WebACL_Update_rule (223.44s)
--- PASS: TestAccWAFV2WebACL_tags (248.44s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_basic (248.48s)
--- PASS: TestAccWAFV2WebACL_Update_ruleProperties (256.75s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_forwardedIP (278.66s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/wafv2      280.842s
```

### CODE REVIEW

**Comment by galoitsu** [comment]
I typo'd the commit message, so I [force-pushed](https://github.com/hashicorp/terraform-provider-aws/compare/81384d55cd5896d0b15ba0f6b2788dbfa0ce9d47..9757b74add0f334a915bc1a3f3f69fb763344476) 😓.

**Comment by Xyaren** [comment]
I really thin this requires more attention by the maintainers.
We recently had production issues, due to AWS updating their WAF managed rule sets.
This would not have happened, if we were able to pinpoint a specific version.

@maintainers Please Merge 😭

**Comment by pshen** [comment]
Please merge if possible.

AWS upgraded AWSManagedRulesCommonRuleSet today (2022-01-24) from 1.2 to 2.0 as default version, which caused an outage for us.

**Comment by cyn110** [comment]
Merge please...

**Comment by jonz-secops** [comment]
the people say `merge`

**Comment by maiconcarraro** [comment]
> Please merge if possible.
> 
> AWS upgraded AWSManagedRulesCommonRuleSet today (2022-01-24) from 1.2 to 2.0 as default version, which caused an outage for us.

we had the same issue but with `AWSManagedRulesSQLiRuleSet`

**Comment by Xyaren** [comment]
@justinretzolk this is tagged as enhancement, at this point this is more like a bugfix and should therefore be prioritized don't you think ?

**Comment by justinretzolk** [comment]
Hey @Xyaren 👋 We definitely see where you're coming from! This is currently on the [roadmap](https://github.com/hashicorp/terraform-provider-aws/pull/22760/files) (sorry, I can't link directly to the line, but it can be found by searching that page for `21546`) for Q1, which is February - April. While I can't speak to an exact date, I suspect that given this PR exists and has so much community feedback already, it will likely be an early candidate to be looked at during that timeframe.

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

Output from tests (`us-west-2`):
```console
% make testacc TESTS=TestAccWAFV2WebACL_ PKG=wafv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL_'  -timeout 180m
--- PASS: TestAccWAFV2WebACL_disappears (24.54s)
--- PASS: TestAccWAFV2WebACL_RateBased_maxNested (75.14s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_basic (80.44s)
--- PASS: TestAccWAFV2WebACL_RuleLabels (98.90s)
--- PASS: TestAccWAFV2WebACL_Operators_maxNested (104.29s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_specifyVersion (104.83s)
--- PASS: TestAccWAFV2WebACL_RuleGroupReference_basic (112.21s)
--- PASS: TestAccWAFV2WebACL_tags (116.34s)
--- PASS: TestAccWAFV2WebACL_Custom_requestHandling (122.37s)
--- PASS: TestAccWAFV2WebACL_RateBased_forwardedIP (134.72s)
--- PASS: TestAccWAFV2WebACL_LabelMatchStatement (146.86s)
--- PASS: TestAccWAFV2WebACL_basic (146.91s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_basic (147.02s)
--- PASS: TestAccWAFV2WebACL_Custom_response (151.63s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_forwardedIP (152.02s)
--- PASS: TestAccWAFV2WebACL_minimal (157.61s)
--- PASS: TestAccWAFV2WebACL_Update_rule (92.73s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_basic (170.52s)
--- PASS: TestAccWAFV2WebACL_RateBased_basic (175.24s)
--- PASS: TestAccWAFV2WebACL_Update_nameForceNew (177.07s)
--- PASS: TestAccWAFV2WebACL_Update_ruleProperties (160.14s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_forwardedIP (223.83s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	225.243s
```

Output from GovCloud:
```console
% make testacc TESTS=TestAccWAFV2WebACL_ PKG=wafv2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/wafv2/... -v -count 1 -parallel 20 -run='TestAccWAFV2WebACL_'  -timeout 180m
--- PASS: TestAccWAFV2WebACL_minimal (42.43s)
--- PASS: TestAccWAFV2WebACL_Update_nameForceNew (52.43s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_basic (56.00s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_specifyVersion (66.87s)
--- PASS: TestAccWAFV2WebACL_Custom_requestHandling (83.11s)
--- PASS: TestAccWAFV2WebACL_basic (85.43s)
--- PASS: TestAccWAFV2WebACL_Update_rule (44.37s)
--- PASS: TestAccWAFV2WebACL_disappears (42.81s)
--- PASS: TestAccWAFV2WebACL_RateBased_maxNested (103.04s)
--- PASS: TestAccWAFV2WebACL_LabelMatchStatement (104.56s)
--- PASS: TestAccWAFV2WebACL_RateBased_forwardedIP (115.71s)
--- PASS: TestAccWAFV2WebACL_ManagedRuleGroup_basic (117.97s)
--- PASS: TestAccWAFV2WebACL_RateBased_basic (122.16s)
--- PASS: TestAccWAFV2WebACL_tags (122.85s)
--- PASS: TestAccWAFV2WebACL_Custom_response (123.51s)
--- PASS: TestAccWAFV2WebACL_Update_ruleProperties (128.52s)
--- PASS: TestAccWAFV2WebACL_RuleLabels (146.68s)
--- PASS: TestAccWAFV2WebACL_RuleGroupReference_basic (159.68s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_basic (162.79s)
--- PASS: TestAccWAFV2WebACL_Operators_maxNested (167.17s)
--- PASS: TestAccWAFV2WebACL_IPSetReference_forwardedIP (169.00s)
--- PASS: TestAccWAFV2WebACL_GeoMatch_forwardedIP (170.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/wafv2	172.191s
```

**Pull request merged**
