### PR TITLE
add support for aws shield subscription resource fixes hashicorp#21430

### LINKED ISSUE #21430: Support for AWS Shield Advance Subscriptions
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to use terraform to manage AWS Shield Advance Subscriptions which are available via [the API](https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_CreateSubscription.html), which is part of AWS WAF.
General documentation can be found [here](https://docs.aws.amazon.com/waf/latest/developerguide/enable-ddos-prem.html).
Also find information about the [boto library](https://boto3.amazonaws.com/v1/documentation/api/latest/reference/services/shield.html#Shield.Client.create_subscription) or the [cli reference](https://docs.aws.amazon.com/cli/latest/reference/shield/create-subscription.html).

### New or Affected Resource(s)

* aws_shield_subscription

### Potential Terraform Configuration

```hcl
resource "aws_shield_subscription" "example" {
  name       = "example"
  auto_renew = false # Or true

  tags = {
    Organization = "ACME"
  }
}
```

The resource is more or less useless because there is no return body for it. Also the auto_renew can only be used with the implementation with [UpdateSubscription](https://docs.aws.amazon.com/waf/latest/DDOSAPIReference/API_UpdateSubscription.html).
As well i do not know if tags are supported. [WAF is listed in general](https://docs.aws.amazon.com/resourcegroupstagging/latest/APIReference/supported-services.html) but not shield.

### References

None

### PR DESCRIPTION
**Pull request by iwarapter**
### Description

Add resource for Shield Subscription:

### Relations

Closes #21430

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccShieldSubscription_basic PKG=shield
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/shield/... -v -count 1 -parallel 20 -run='TestAccShieldSubscription_basic'  -timeout 360m
=== RUN   TestAccShieldSubscription_basic
=== PAUSE TestAccShieldSubscription_basic
=== CONT  TestAccShieldSubscription_basic
    subscription_test.go:34: Error running post-test destroy, there may be dangling resources: exit status 1
        
        Error: deleting AWS Shield Subscription ("hidden"): operation error Shield: DeleteSubscription, https response error StatusCode: 400, RequestID: 13177d54-c466-46f8-9446-346d6abeeb7c, LockedSubscriptionException: The subscription could not be deactivated before time commitment expires.
        
        operation error Shield: DeleteSubscription, https response error StatusCode:
        400, RequestID: 13177d54-c466-46f8-9446-346d6abeeb7c,
        LockedSubscriptionException: The subscription could not be deactivated before
        time commitment expires.
--- FAIL: TestAccShieldSubscription_basic (14.72s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/shield     18.885s
FAIL
make: *** [testacc] Error 1
...
```
I ran out of accounts to subscribe in my organisation to finish the tests but added the `destroy = false` to both create/import steps.

All the accounts I tested with are correctly subscribed.

### CODE REVIEW

**Comment by barryib** [comment]
@iwarapter are you still working on this great improvement ?

**Comment by iwarapter** [comment]
Oh I didn't notice the linter failed, will take a look

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=shield TESTS=TestAccShieldSubscription_basic
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/shield/... -v -count 1 -parallel 20 -run='TestAccShieldSubscription_basic'  -timeout 360m
=== RUN   TestAccShieldSubscription_basic
    subscription_test.go:32: running this test requires a yearly commitment to AWS Shield Advanced with a $3000 monthly fee in the associated account
--- SKIP: TestAccShieldSubscription_basic (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/shield     5.888s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @iwarapter! 👍

**Pull request merged**
