### PR TITLE
[New Resource] `aws_rekognition_stream_processor`

### PR DESCRIPTION
**Pull request by bruceharrison1984**
### Description
The adds the `aws_rekognition_stream_processor` resource to the provider.

[API Docs](https://docs.aws.amazon.com/rekognition/latest/APIReference/API_CreateStreamProcessor.html)

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccRekognitionStreamProcessor_ PKG=rekognition

...
```

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=rekognition TESTS=TestAccRekognitionStreamProcessor_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rekognition/... -v -count 1 -parallel 20 -run='TestAccRekognitionStreamProcessor_'  -timeout 360m

--- PASS: TestAccRekognitionStreamProcessor_disappears (95.06s)
--- PASS: TestAccRekognitionStreamProcessor_basic (97.00s)
--- PASS: TestAccRekognitionStreamProcessor_faceRecognition_boundingBox (104.94s)
--- PASS: TestAccRekognitionStreamProcessor_faceRecognition_polygon (104.97s)
--- PASS: TestAccRekognitionStreamProcessor_connectedHome (105.40s)
--- PASS: TestAccRekognitionStreamProcessor_faceRecognition (107.02s)
--- PASS: TestAccRekognitionStreamProcessor_tags (120.70s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rekognition        126.632s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @bruceharrison1984! 👍

**Comment by bruceharrison1984** [comment]
Thanks for whipping it into shape @jar-b

**Review by jar-b — APPROVED** [review]
Tests still passing after latest additions:

```console
% make testacc PKG=rekognition TESTS=TestAccRekognitionStreamProcessor_
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/rekognition/... -v -count 1 -parallel 20 -run='TestAccRekognitionStreamProcessor_'  -timeout 360m

--- PASS: TestAccRekognitionStreamProcessor_disappears (94.71s)
--- PASS: TestAccRekognitionStreamProcessor_basic (97.21s)
--- PASS: TestAccRekognitionStreamProcessor_faceRecognition_boundingBox (104.64s)
--- PASS: TestAccRekognitionStreamProcessor_faceRecognition_polygon (104.96s)
--- PASS: TestAccRekognitionStreamProcessor_connectedHome (105.45s)
--- PASS: TestAccRekognitionStreamProcessor_faceRecognition (107.28s)
--- PASS: TestAccRekognitionStreamProcessor_tags (118.75s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rekognition        124.688s
```

**Pull request merged**
