### PR TITLE
resource/aws_security_group_rule: Validate conflicting arguments are not simultaneously specified

### LINKED ISSUE #15606: security_group_rule: 'self' conflicts with 'cidr_blocks'
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform 0.12.29
AWs Provider: 2.70.0

### Affected Resource(s)

* aws_security_group_rule

### Terraform Configuration Files

```hcl
"aws_security_group_rule" "foo" {
  cidr_blocks = ["1.2.3.4/16", "5.6.7.8/24"]
  self        = true
}
```

### Debug Output

n/a

### Panic Output

n/a

### Expected Behavior

According to the [documentation](https://github.com/terraform-providers/terraform-provider-aws/blob/v2.70.0/website/docs/r/security_group_rule.html.markdown) for 2.70.0, `source_security_group_id` conflicts with `cidr_blocks` and `self` for arguments. `self` does not conflict with `cidr_blocks`.

### Actual Behavior

> Error: 'self': conflicts with 'cidr_blocks' ([]interface {}{"1.2.3.4/16", "5.6.7.8/24"})

### Steps to Reproduce

`terraform apply`

### Important Factoids

Does not matter to me if this is a bug or documentation issue; I would just like some clarification please and thank you. I could even just easily PR the doc update myself if desired if that is the issue. If that is the issue, I also think the resource should probably also have argument validation added in a similar fashion to how co-specifying `source_security_group_id` with `self` throws an error before CRUD operations: https://github.com/terraform-providers/terraform-provider-aws/blob/v2.70.0/aws/resource_aws_security_group_rule.go#L129

### References

n/a

### PR DESCRIPTION
**Pull request by mschuchard**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #15606

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by mschuchard** [comment]
Removed `CHANGELOG` modifications. Created one because of item 2 in `Pull Request Lifecycle` in the contribution guidelines. Should that entry be removed?

**Comment by onematchfox** [comment]
Hi @mschuchard and @gdavison, 

Just a heads up at this point  - this change breaks the https://github.com/terraform-aws-modules/terraform-aws-security-group module. Caught me completely off guard :disappointed: - there's also nothing in the release notes for `v3.38.0` about this either? 

Error being thrown by the module is:

```
line 145, in resource "aws_security_group_rule" "computed_ingress_with_source_security_group_id": 
 145:   ipv6_cidr_blocks         = var.ingress_ipv6_cidr_blocks 
"ipv6_cidr_blocks": conflicts with source_security_group_idp
```

For now, I'm just going to restrict my provider version to `< 3.38.0` so I can go back to my weekend. Will try log something more detailed on Monday if someone else doesn't beat me to it.

**Comment by mschuchard** [comment]
@onematchfox The module maintainers would need to update/fix the module to not attempt simultaneously specifying those arguments since they are not allowed by the AWS API. The PR was an improvement/bug fix to invalidate that argument before the API throws an error during create operations during a apply. You can check the linked issue above for more.

**Comment by onematchfox** [comment]
> @onematchfox The module maintainers would need to update/fix the module to not attempt simultaneously specifying those arguments since they are not allowed by the AWS API. The PR was an improvement/bug fix to invalidate that usage before the API throws an error during create operations during a apply. You can check the linked issue above for more.

Fair enough. Except that I could argue that this change is a Breaking Change. Resources that previously planned and applied successfully no longer plan. 

I haven't dug too deep but my suspicion is that this is a result of how `ConflictsWith` works in comparison to the `apply` of the resource itself. I think the module uses blank lists (`[]`) as defaults which either weren't actually applied when the resource was applied (or were just ignored by the AWS API). Whereas it would seem like `ConflictsWith` views the blank list as a value and thus fails validation. Anyway, hopefully it is as simple as adjusting the defaults used on the module.

**Comment by mschuchard** [comment]
For Terraform versions >= 0.12, the `null` type is used in situations like this for optional arguments. Unless they are still supporting < 0.12, that sounds like the fix here based on your description.

**Pull request merged**
