### PR TITLE
r/aws_appmesh_virtual_node: Add connection pool and outlier detection

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes: #16097.

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_appmesh_virtual_node: Add `listener.connection_pool` attribute
resource/aws_appmesh_virtual_node: Add `listener.outlier_detection` attribute
```

Output from acceptance testing:

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/VirtualNode'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/VirtualNode -timeout 120m
=== RUN   TestAccAWSAppmesh_serial
=== RUN   TestAccAWSAppmesh_serial/VirtualNode
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerTls
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/logging
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/tags
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/disappears
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/basic
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm        
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendDefaults
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks
--- PASS: TestAccAWSAppmesh_serial (468.07s)
    --- PASS: TestAccAWSAppmesh_serial/VirtualNode (468.07s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection (28.23s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTls (71.32s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/logging (27.86s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/tags (40.02s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/disappears (12.83s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile (28.32s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery (100.22s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool (28.26s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout (28.09s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/basic (16.17s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm (52.11s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendDefaults (28.17s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks (28.25s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	468.135s
```

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

```
--- PASS: TestAccAWSAppmesh_serial (1265.32s)
    --- PASS: TestAccAWSAppmesh_serial/VirtualNode (1265.32s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/logging (84.35s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/tags (113.52s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/basic (45.67s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/disappears (38.22s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection (80.88s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks (81.50s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTls (195.17s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout (75.12s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm (131.11s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile (82.05s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendDefaults (87.50s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery (168.28s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool (81.96s)
```

**Comment by ewbankkit** [comment]
Rebase and resolved merge conflicts.

```console
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/VirtualNode'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/VirtualNode -timeout 120m
=== RUN   TestAccAWSAppmesh_serial
=== RUN   TestAccAWSAppmesh_serial/VirtualNode
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/basic
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/disappears
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerTls
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/logging
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendDefaults
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/tags
--- PASS: TestAccAWSAppmesh_serial (496.00s)
    --- PASS: TestAccAWSAppmesh_serial/VirtualNode (496.00s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile (30.24s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks (27.98s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/basic (15.94s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/disappears (12.45s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery (100.78s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool (28.51s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection (28.35s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout (28.63s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTls (72.93s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/logging (28.31s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm (52.41s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendDefaults (28.17s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/tags (41.28s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	496.083s
```

**Comment by awsiv** [comment]
Thanks! Have been waiting for this. Any idea on when this will be merged or what is missing from this PR (LGTM btw 🚀 )?

**Comment by ewbankkit** [comment]
@awsiv Should be merged soon...

**Comment by breathingdust** [comment]
LGTM :rocket: Thanks @ewbankkit 

Verified Acceptance Tests in Commercial (us-west-2)

```console
make testacc TEST=./aws TESTARGS='-run=TestAccAWSAppmesh/VirtualNode'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAppmesh/VirtualNode -timeout 120m
=== RUN   TestAccAWSAppmesh_serial
=== RUN   TestAccAWSAppmesh_serial/VirtualNode
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/basic
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/disappears
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/backendDefaults
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerTls
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/logging
=== RUN   TestAccAWSAppmesh_serial/VirtualNode/tags
--- PASS: TestAccAWSAppmesh_serial (461.96s)
    --- PASS: TestAccAWSAppmesh_serial/VirtualNode (461.96s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerHealthChecks (25.56s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/basic (13.16s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/disappears (12.02s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyAcm (50.82s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendClientPolicyFile (25.55s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/backendDefaults (23.72s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/cloudMapServiceDiscovery (113.72s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerConnectionPool (24.85s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTimeout (23.87s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerTls (62.29s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/listenerOutlierDetection (24.26s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/logging (25.95s)
        --- PASS: TestAccAWSAppmesh_serial/VirtualNode/tags (36.17s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	463.631s
```

**Pull request merged**
