### PR TITLE
r/s3_bucket_intelligent_tiering_configuration: New Resource

### LINKED ISSUE #16123: S3 Intelligent-Tiering Archive configuration
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon S3 Intelligent-Tiering adds Archive Access tiers.

### New or Affected Resource(s)

* `aws_s3_bucket_intelligent_tiering_configuration`

### Potential Terraform Configuration

```hcl
resource "aws_s3_bucket_intelligent_tiering_configuration" "example" {
  bucket = aws_s3_bucket.example.name
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2020/11/amazon-s3-intelligent-tiering-adds-archive-access-tiers/).
[Blog post](https://aws.amazon.com/blogs/aws/s3-intelligent-tiering-adds-archive-access-tiers/).

Requires [AWS SDK v1.35.24](https://github.com/aws/aws-sdk-go/releases/tag/v1.35.24):

* https://github.com/hashicorp/terraform-provider-aws/pull/16109

### PR DESCRIPTION
**Pull request by daniepett**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16123

Example
```terraform
resource "aws_s3_bucket_intelligent_tiering_configuration" "example" {
  bucket = "my-bucket-name"
  name   = "example-tier"

  filter {
    prefix = "test/"

    tags = {
      name = "example"
    }
  }

  tier {
    access_tier = "DEEP_ARCHIVE_ACCESS"
    days        = 180
  }

  tier {
    access_tier = "ARCHIVE_ACCESS"
    days        = 125
  }

}

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSS3BucketIntelligentTieringConfiguration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSS3BucketIntelligentTieringConfiguration_ -timeout 180m
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_basic
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_basic
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_removed
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_removed
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_disableBasic
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_disableBasic
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_updateBasic
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_updateBasic
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Empty
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Empty
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Prefix
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Prefix
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_SingleTag
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_SingleTag
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_MultipleTags
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_MultipleTags
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_PrefixAndTags
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_PrefixAndTags
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Remove
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Remove
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithTier_Empty
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithTier_Empty
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_Default
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_Default
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithOneTier_UpdateDays
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithOneTier_UpdateDays
=== RUN   TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_RemoveOne
=== PAUSE TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_RemoveOne
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_basic
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_PrefixAndTags
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Remove
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Empty
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_MultipleTags
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_SingleTag
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Prefix
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithOneTier_UpdateDays
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_RemoveOne
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithTier_Empty
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_Default
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_updateBasic
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_disableBasic
=== CONT  TestAccAWSS3BucketIntelligentTieringConfiguration_removed
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithTier_Empty (24.26s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Empty (24.97s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_basic (94.91s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_Default (98.00s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_removed (134.45s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_disableBasic (149.40s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_SingleTag (153.90s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithTwoTiers_RemoveOne (153.95s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_MultipleTags (155.14s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Prefix (156.40s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_Remove (156.61s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithOneTier_UpdateDays (156.62s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_WithFilter_PrefixAndTags (156.68s)
--- PASS: TestAccAWSS3BucketIntelligentTieringConfiguration_updateBasic (203.35s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       205.230s
...
```

### CODE REVIEW

**Comment by KVInventoR** [comment]
how will be it work if you setup many policies for different folders?

I think configuration for specific folder should in included in namespace for this folder.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc PKG_NAME=internal/service/s3 TESTARGS='-run=TestAccS3BucketIntelligentTieringConfiguration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run=TestAccS3BucketIntelligentTieringConfiguration_ -timeout 180m
=== RUN   TestAccS3BucketIntelligentTieringConfiguration_basic
=== PAUSE TestAccS3BucketIntelligentTieringConfiguration_basic
=== RUN   TestAccS3BucketIntelligentTieringConfiguration_disappears
=== PAUSE TestAccS3BucketIntelligentTieringConfiguration_disappears
=== RUN   TestAccS3BucketIntelligentTieringConfiguration_Filter
=== PAUSE TestAccS3BucketIntelligentTieringConfiguration_Filter
=== CONT  TestAccS3BucketIntelligentTieringConfiguration_basic
=== CONT  TestAccS3BucketIntelligentTieringConfiguration_Filter
=== CONT  TestAccS3BucketIntelligentTieringConfiguration_disappears
--- PASS: TestAccS3BucketIntelligentTieringConfiguration_disappears (25.23s)
--- PASS: TestAccS3BucketIntelligentTieringConfiguration_basic (27.99s)
--- PASS: TestAccS3BucketIntelligentTieringConfiguration_Filter (107.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	111.337s
```

##### GovCloud

```console
% make testacc PKG_NAME=internal/service/s3 TESTARGS='-run=TestAccS3BucketIntelligentTieringConfiguration_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/s3/... -v -count 1 -parallel 20 -run=TestAccS3BucketIntelligentTieringConfiguration_ -timeout 180m
=== RUN   TestAccS3BucketIntelligentTieringConfiguration_basic
=== PAUSE TestAccS3BucketIntelligentTieringConfiguration_basic
=== RUN   TestAccS3BucketIntelligentTieringConfiguration_disappears
=== PAUSE TestAccS3BucketIntelligentTieringConfiguration_disappears
=== RUN   TestAccS3BucketIntelligentTieringConfiguration_Filter
=== PAUSE TestAccS3BucketIntelligentTieringConfiguration_Filter
=== CONT  TestAccS3BucketIntelligentTieringConfiguration_basic
=== CONT  TestAccS3BucketIntelligentTieringConfiguration_Filter
=== CONT  TestAccS3BucketIntelligentTieringConfiguration_disappears
--- PASS: TestAccS3BucketIntelligentTieringConfiguration_disappears (28.16s)
--- PASS: TestAccS3BucketIntelligentTieringConfiguration_basic (31.24s)
--- PASS: TestAccS3BucketIntelligentTieringConfiguration_Filter (126.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/s3	130.097s
```

**Comment by ewbankkit** [comment]
@daniepett Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
```console
% make golangci-lint
==> Checking source code with golangci-lint...
```

**Pull request merged**
