### PR TITLE
Add fsx ontap_storage_virtual_machine resource

### PR DESCRIPTION
**Pull request by awsaxeman**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #20778

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccFSxOntapStorageVirtualMachine' PKG_NAME=internal/service/fsx

=== CONT  TestAccFSxOntapStorageVirtualMachine_name
--- PASS: TestAccFSxOntapStorageVirtualMachine_name (3020.50s)
=== CONT  TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
--- PASS: TestAccFSxOntapStorageVirtualMachine_svmAdminPassword (2729.62s)
=== CONT  TestAccFSxOntapStorageVirtualMachine_basic
--- PASS: TestAccFSxOntapStorageVirtualMachine_basic (2544.48s)
=== CONT  TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
--- PASS: TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle (2697.35s)
=== CONT  TestAccFSxOntapStorageVirtualMachine_disappears
--- PASS: TestAccFSxOntapStorageVirtualMachine_disappears (2693.69s)
=== CONT  TestAccFSxOntapStorageVirtualMachine_activeDirectory
--- PASS: TestAccFSxOntapStorageVirtualMachine_activeDirectory (2808.88s)
=== CONT  TestAccFSxOntapStorageVirtualMachine_tags
--- PASS: TestAccFSxOntapStorageVirtualMachine_tags (3565.28s)
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Similar: #21503.

**Comment by DrFaust92** [comment]
Code wise looks good to me, ill try to run tests in the coming days.

**Review by DrFaust92 — APPROVED** [review]

**Comment by breathingdust** [comment]
Validated tests in Commercial `us-west-2`

```console
make testacc TESTARGS='-run=TestAccFSxOntapStorageVirtualMachine' PKG_NAME=internal/service/fsx
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run=TestAccFSxOntapStorageVirtualMachine -timeout 180m
=== RUN   TestAccFSxOntapStorageVirtualMachine_basic
=== PAUSE TestAccFSxOntapStorageVirtualMachine_basic
=== RUN   TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
=== PAUSE TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
=== RUN   TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
=== PAUSE TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
=== RUN   TestAccFSxOntapStorageVirtualMachine_disappears
=== PAUSE TestAccFSxOntapStorageVirtualMachine_disappears
=== RUN   TestAccFSxOntapStorageVirtualMachine_name
=== PAUSE TestAccFSxOntapStorageVirtualMachine_name
=== RUN   TestAccFSxOntapStorageVirtualMachine_tags
=== PAUSE TestAccFSxOntapStorageVirtualMachine_tags
=== RUN   TestAccFSxOntapStorageVirtualMachine_activeDirectory
=== PAUSE TestAccFSxOntapStorageVirtualMachine_activeDirectory
=== CONT  TestAccFSxOntapStorageVirtualMachine_basic
=== CONT  TestAccFSxOntapStorageVirtualMachine_name
=== CONT  TestAccFSxOntapStorageVirtualMachine_disappears
=== CONT  TestAccFSxOntapStorageVirtualMachine_tags
=== CONT  TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
=== CONT  TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
=== CONT  TestAccFSxOntapStorageVirtualMachine_activeDirectory
--- PASS: TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle (2561.47s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_basic (2601.37s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_disappears (2650.53s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_activeDirectory (2683.11s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_svmAdminPassword (2689.35s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_tags (2724.07s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_name (3107.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	3110.620s
```

Validated Tests in GovCloud (`us-gov-west-1`)

```console
make testacc TESTARGS='-run=TestAccFSxOntapStorageVirtualMachine' PKG_NAME=internal/service/fsx
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fsx/... -v -count 1 -parallel 20 -run=TestAccFSxOntapStorageVirtualMachine -timeout 180m
=== RUN   TestAccFSxOntapStorageVirtualMachine_basic
=== PAUSE TestAccFSxOntapStorageVirtualMachine_basic
=== RUN   TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
=== PAUSE TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
=== RUN   TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
=== PAUSE TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
=== RUN   TestAccFSxOntapStorageVirtualMachine_disappears
=== PAUSE TestAccFSxOntapStorageVirtualMachine_disappears
=== RUN   TestAccFSxOntapStorageVirtualMachine_name
=== PAUSE TestAccFSxOntapStorageVirtualMachine_name
=== RUN   TestAccFSxOntapStorageVirtualMachine_tags
=== PAUSE TestAccFSxOntapStorageVirtualMachine_tags
=== RUN   TestAccFSxOntapStorageVirtualMachine_activeDirectory
=== PAUSE TestAccFSxOntapStorageVirtualMachine_activeDirectory
=== CONT  TestAccFSxOntapStorageVirtualMachine_basic
=== CONT  TestAccFSxOntapStorageVirtualMachine_name
=== CONT  TestAccFSxOntapStorageVirtualMachine_svmAdminPassword
=== CONT  TestAccFSxOntapStorageVirtualMachine_activeDirectory
=== CONT  TestAccFSxOntapStorageVirtualMachine_tags
=== CONT  TestAccFSxOntapStorageVirtualMachine_disappears
=== CONT  TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle
--- PASS: TestAccFSxOntapStorageVirtualMachine_tags (2406.80s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_svmAdminPassword (2427.79s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_rootVolumeSecurityStyle (2457.69s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_disappears (2610.12s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_basic (2713.25s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_activeDirectory (2849.83s)
--- PASS: TestAccFSxOntapStorageVirtualMachine_name (2902.43s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fsx	2905.325s
```

**Comment by breathingdust** [comment]
LGTM 🚀 Thanks @awsaxeman!

**Comment by gdavison** [comment]
Hi @DrFaust92 and @awsaxeman. In #21922, I've added the sweeper function `sweepFSXOntapStorageVirtualMachine` that's referenced in this PR, but isn't defined. Unfortunately, because of how the sweepers are implemented with build tags, the sweeper functions don't get compiled until they are run.

**Pull request merged**
