### PR TITLE
Data source aws_secretsmanager_secret_versions

### LINKED ISSUE #29469: [New Data Source]:  aws_secretsmanager_secret_versions / aws_secretsmanager_secret_version_ids
### Description

Lists the versions of a secret. Secrets Manager uses staging labels to indicate the different versions of a secret.

Example response:

``` hcl
versions = [
  {
    create_date    =  "2018-01-03T23:12:01Z"
    version_id     = "EXAMPLE2-90ab-cdef-fedc-ba987SECRET2"
    version_stages = ["AWSCURRENT"]
  }
  {
    create_date    = "2018-01-02T23:12:01Z"
    version_id     = "EXAMPLE1-90ab-cdef-fedc-ba987SECRET1"
    version_stages = ["AWSPREVIOUS"]
  }
  {
    create_date = "2018-01-01T23:12:01Z"
    version_id  = "EXAMPLE3-90ab-cdef-fedc-ba987SECRET3"
  }
]
```

### Requested Resource(s) and/or Data Source(s)

* aws_secretsmanager_secret_versions / aws_secretsmanager_secret_version_ids 

### Potential Terraform Configuration

```terraform
data "aws_secretsmanager_secret_versions" "example" {
    secret_id          = data.aws_secretsmanager_secret.example.id
    include_deprecated = false
}
```

### References

- [API Reference: ListSecretVersionIds](https://docs.aws.amazon.com/secretsmanager/latest/apireference/API_ListSecretVersionIds.html)
- [AWS CLI: list-secret-version-ids](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/secretsmanager/list-secret-version-ids.html)

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by wcmjunior**
### Description

Add a new data source `aws_secretsmanager_secret_versions` to retrieve the secret versions from a secret.

### Relations

Closes #29469

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccSecretsManagerSecretVersionsDataSource_basic PKG=secretsmanager 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretVersionsDataSource_basic'  -timeout 360m
=== RUN   TestAccSecretsManagerSecretVersionsDataSource_basic
=== PAUSE TestAccSecretsManagerSecretVersionsDataSource_basic
=== CONT  TestAccSecretsManagerSecretVersionsDataSource_basic
--- PASS: TestAccSecretsManagerSecretVersionsDataSource_basic (14.68s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager     20.550s

% make testacc TESTS=TestAccSecretsManagerSecretVersionsDataSource_maxResults PKG=secretsmanager
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretVersionsDataSource_maxResults'  -timeout 360m
=== RUN   TestAccSecretsManagerSecretVersionsDataSource_maxResults
=== PAUSE TestAccSecretsManagerSecretVersionsDataSource_maxResults
=== CONT  TestAccSecretsManagerSecretVersionsDataSource_maxResults
--- PASS: TestAccSecretsManagerSecretVersionsDataSource_maxResults (7.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager     13.146s
...
```

### CODE REVIEW

**Comment by wcmjunior** [comment]
Hey @justinretzolk . Do you know when you (or someone else) will be available to review this PR? This is just a gentle ping. TYVM. :)

**Comment by justinretzolk** [comment]
Hey @wcmjunior 👋 Thanks for checking in here! I can't speak to when this will be prioritized just yet. We base our prioritization on the count of :+1: reactions and a few other considerations (more information: [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/)).

**Comment by gabfelp** [comment]
Thanks for working on this! I would love for it to be added to the AWS provider 🤯

**Comment by mikkoc** [comment]
Can we please review and merge this? We need a way to list version IDs even if a secret has no versions (empty list would be returned). Right now there is not way of doing that :(

**Review by ulrichwinter — APPROVED** [review]

**Comment by wcmjunior** [comment]
> Can we please review and merge this? We need a way to list version IDs even if a secret has no versions (empty list would be returned). Right now there is not way of doing that :(

Hey @mikkoc , I don't think this is going to happen due to [this check](https://github.com/hashicorp/terraform-provider-aws/blob/4de08347c322f88b65dc91daf0792b5516b08f92/internal/service/secretsmanager/secret_version.go#L373-L375), but I'd need to test to make sure. I agree with you that is better to return an empty list and not fail in case no versions are found, otherwise there is no point on having a data source as it could fail and break the execution.

I will try to take a look at this during the week and get back with a solution. @ulrichwinter , please LMK if you have any thoughts on the proper behaviour for the data source.

**Comment by wcmjunior** [comment]
> > Can we please review and merge this? We need a way to list version IDs even if a secret has no versions (empty list would be returned). Right now there is not way of doing that :(
> 
> Hey @mikkoc , I don't think this is going to happen due to [this check](https://github.com/hashicorp/terraform-provider-aws/blob/4de08347c322f88b65dc91daf0792b5516b08f92/internal/service/secretsmanager/secret_version.go#L373-L375), but I'd need to test to make sure. I agree with you that is better to return an empty list and not fail in case no versions are found, otherwise there is no point on having a data source as it could fail and break the execution.
> 
> I will try to take a look at this during the week and get back with a solution. @ulrichwinter , please LMK if you have any thoughts on the proper behaviour for the data source.

I just tested and it *does not* fail for a non-existing version, so the data source is good to go. 🙏 

I added a test case for it, but I'm afraid that pushing the `32` lines of code with the new test will delay this PR even further. Will tackle this issue in a different PR that could eventually live forever in the backlog.

**Comment by wcmjunior** [comment]
Hey @justinretzolk. It would help a lot if this PR could be merged as it is already reviewed. Gentle ping again. :-)

**Comment by mikkoc** [comment]
yes, please let's get this merged ASAP. 🙏

**Comment by wcmjunior** [comment]
Just realized the review is not from a contributor (although I appreciate it), so decide to add a new test case as this may take a long time to be merged anyways.

**Review by nam054 — APPROVED** [review]
LGTM! 🚀  Thank you so much for your contribution! 
```
> make testacc TESTS=TestAccSecretsManagerSecretVersionsDataSource_ PKG=secretsmanager
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/secretsmanager/... -v -count 1 -parallel 20 -run='TestAccSecretsManagerSecretVersionsDataSource_'  -timeout 360m
=== RUN   TestAccSecretsManagerSecretVersionsDataSource_basic
=== PAUSE TestAccSecretsManagerSecretVersionsDataSource_basic
=== RUN   TestAccSecretsManagerSecretVersionsDataSource_emptyVer
=== PAUSE TestAccSecretsManagerSecretVersionsDataSource_emptyVer
=== CONT  TestAccSecretsManagerSecretVersionsDataSource_basic
=== CONT  TestAccSecretsManagerSecretVersionsDataSource_emptyVer
--- PASS: TestAccSecretsManagerSecretVersionsDataSource_emptyVer (11.86s)
--- PASS: TestAccSecretsManagerSecretVersionsDataSource_basic (12.62s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/secretsmanager     18.436s

**Comment by wcmjunior** [comment]
@nam054 thanks for reviewing and merging the feature. I really need it. A bit disappointing to see the contribution is not computed to the original PR author, but the feature availability is more important for me now. :-)

**Comment by mikkoc** [comment]
> @nam054 thanks for reviewing and merging the feature. I really need it. A bit disappointing to see the contribution is not computed to the original PR author, but the feature availability is more important for me now. :-)

this worked very well, thanks @wcmjunior . Only one minor note: the docs need to be updated. According to the docs, we should call `versions.version_stage` to get the stage. Instead, we need `version.version_stages` because it's a list, not a string.

**Pull request merged**
