### PR TITLE
aws_dms_endpoint.ignore_header_rows typo

### PR DESCRIPTION
**Pull request by bennylu2**
### Description
Fix typo in setting, should be `ignore_header_rows` not `ignore_headers_row`

### Relations
Closes https://github.com/hashicorp/terraform-provider-aws/issues/26957

### References
https://docs.aws.amazon.com/dms/latest/APIReference/API_S3Settings.html

### CODE REVIEW

**Comment by YakDriver** [comment]
What we should do here is add the new correct setting and keep the old with a deprecation (and "btw this setting does nothing") warning. That way, people's configurations won't break but we can move forward with the right stuff. Then we can make an issue for v5 to remove the deprecated, erroneous setting.

**Comment by bennylu2** [comment]
> What we should do here is add the new correct setting and keep the old with a deprecation (and "btw this setting does nothing") warning. That way, people's configurations won't break but we can move forward with the right stuff. Then we can make an issue for v5 to remove the deprecated, erroneous setting.

@YakDriver did you want me to make these changes or were you taking it? Was unsure but I can get to this later this week

**Comment by YakDriver** [comment]
@bennylu2 Thanks for your work on this! I added the deprecated setting back.

**Review by YakDriver — APPROVED** [review]
LGTM 🎉 

```console
% make testacc TESTS=TestAccDMSEndpoint_S3 PKG=dms
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/dms/... -v -count 1 -parallel 20 -run='TestAccDMSEndpoint_S3'  -timeout 180m
=== RUN   TestAccDMSEndpoint_S3_basic
=== PAUSE TestAccDMSEndpoint_S3_basic
=== RUN   TestAccDMSEndpoint_S3_extraConnectionAttributes
=== PAUSE TestAccDMSEndpoint_S3_extraConnectionAttributes
=== CONT  TestAccDMSEndpoint_S3_basic
=== CONT  TestAccDMSEndpoint_S3_extraConnectionAttributes
--- PASS: TestAccDMSEndpoint_S3_extraConnectionAttributes (52.43s)
--- PASS: TestAccDMSEndpoint_S3_basic (65.12s)
```

**Pull request merged**
