### PR TITLE
Add support for AllowClassicFlow to the Cognito Identity Pool resource.

### LINKED ISSUE #12926: Cognito Identity Pool resource does not support AllowClassicFlow boolean
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The aws_cognito_identity_pool resource type has no ability to set the "AllowClassicFlow" attribute

### New or Affected Resource(s)

aws_cognito_identity_pool

### Potential Terraform Configuration

```hcl
resource "aws_cognito_identity_pool" "example-pool" {
    identity_pool_name = "ExamplePool"
    allow_classic_flow = {true|false}
    ...
}
```

### References

* https://docs.aws.amazon.com/cognitoidentity/latest/APIReference/API_CreateIdentityPool.html

### PR DESCRIPTION
**Pull request by dtascione**
This adds an allow_classic_flow attribute to the aws_cognito_identity_pool
resource type. The default was chosen based on the current default when
using the AWS APIs directly.

Closes #12926

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCognitoIdentityPool*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCognitoIdentityPool* -timeout 180m
=== RUN   TestAccAWSCognitoIdentityPoolRolesAttachment_basic
=== PAUSE TestAccAWSCognitoIdentityPoolRolesAttachment_basic
=== RUN   TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappings
=== PAUSE TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappings
=== RUN   TestAccAWSCognitoIdentityPoolRolesAttachment_disappears
=== PAUSE TestAccAWSCognitoIdentityPoolRolesAttachment_disappears
=== RUN   TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithAmbiguousRoleResolutionError
=== PAUSE TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithAmbiguousRoleResolutionError
=== RUN   TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithRulesTypeError
=== PAUSE TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithRulesTypeError
=== RUN   TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithTokenTypeError
=== PAUSE TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithTokenTypeError
=== RUN   TestAccAWSCognitoIdentityPool_basic
=== PAUSE TestAccAWSCognitoIdentityPool_basic
=== RUN   TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== PAUSE TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== RUN   TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== PAUSE TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== RUN   TestAccAWSCognitoIdentityPool_samlProviderArns
=== PAUSE TestAccAWSCognitoIdentityPool_samlProviderArns
=== RUN   TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== PAUSE TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== RUN   TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider
--- PASS: TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider (32.15s)
=== RUN   TestAccAWSCognitoIdentityPool_tags
=== PAUSE TestAccAWSCognitoIdentityPool_tags
=== CONT  TestAccAWSCognitoIdentityPoolRolesAttachment_basic
=== CONT  TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== CONT  TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== CONT  TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithRulesTypeError
=== CONT  TestAccAWSCognitoIdentityPoolRolesAttachment_disappears
=== CONT  TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithAmbiguousRoleResolutionError
=== CONT  TestAccAWSCognitoIdentityPool_tags
=== CONT  TestAccAWSCognitoIdentityPool_basic
=== CONT  TestAccAWSCognitoIdentityPool_samlProviderArns
=== CONT  TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappings
=== CONT  TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== CONT  TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithTokenTypeError
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithTokenTypeError (16.25s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithAmbiguousRoleResolutionError (17.98s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappingsWithRulesTypeError (18.63s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_disappears (24.19s)
--- PASS: TestAccAWSCognitoIdentityPool_basic (31.41s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_basic (37.44s)
--- PASS: TestAccAWSCognitoIdentityPool_samlProviderArns (40.10s)
--- PASS: TestAccAWSCognitoIdentityPool_openidConnectProviderArns (40.12s)
--- PASS: TestAccAWSCognitoIdentityPool_supportedLoginProviders (40.81s)
--- PASS: TestAccAWSCognitoIdentityPool_tags (40.82s)
--- PASS: TestAccAWSCognitoIdentityPool_cognitoIdentityProviders (40.95s)
--- PASS: TestAccAWSCognitoIdentityPoolRolesAttachment_roleMappings (51.35s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	83.568s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@dtascione Thanks for the contribution 👏.
To get this merged quickly, could you please select _Allow edits from maintainers_ for this PR.

**Comment by dtascione** [comment]
> @dtascione Thanks for the contribution .
> To get this merged quickly, could you please select _Allow edits from maintainers_ for this PR.

Sorry -- it looks like because I created this from a fork in an organization, it won't let me change that setting. I can re-create this PR under my individual user account if that makes it easier.

**Comment by ewbankkit** [comment]
@dtascione No need for that.
What I was doing was

1. Adding a CHANGELOG entry `.changelog/19176.txt`:

\```release-note:enhancement
resource/aws_cognito_identity_pool: Add `allow_classic_flow` argument
\```

2. Added _Default is `false`._ to the documentation for `allow_classic_flow`

**Comment by dtascione** [comment]
Thanks! Updated!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSCognitoIdentityPool_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCognitoIdentityPool_ -timeout 180m
=== RUN   TestAccAWSCognitoIdentityPool_basic
=== PAUSE TestAccAWSCognitoIdentityPool_basic
=== RUN   TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== PAUSE TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== RUN   TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== PAUSE TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== RUN   TestAccAWSCognitoIdentityPool_samlProviderArns
=== PAUSE TestAccAWSCognitoIdentityPool_samlProviderArns
=== RUN   TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== PAUSE TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== RUN   TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider
--- PASS: TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider (30.73s)
=== RUN   TestAccAWSCognitoIdentityPool_tags
=== PAUSE TestAccAWSCognitoIdentityPool_tags
=== CONT  TestAccAWSCognitoIdentityPool_basic
=== CONT  TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== CONT  TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== CONT  TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== CONT  TestAccAWSCognitoIdentityPool_samlProviderArns
=== CONT  TestAccAWSCognitoIdentityPool_tags
--- PASS: TestAccAWSCognitoIdentityPool_basic (26.16s)
--- PASS: TestAccAWSCognitoIdentityPool_supportedLoginProviders (34.45s)
--- PASS: TestAccAWSCognitoIdentityPool_openidConnectProviderArns (36.24s)
--- PASS: TestAccAWSCognitoIdentityPool_tags (37.81s)
--- PASS: TestAccAWSCognitoIdentityPool_cognitoIdentityProviders (37.85s)
--- PASS: TestAccAWSCognitoIdentityPool_samlProviderArns (38.06s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	72.376s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSCognitoIdentityPool_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCognitoIdentityPool_ -timeout 180m
=== RUN   TestAccAWSCognitoIdentityPool_basic
=== PAUSE TestAccAWSCognitoIdentityPool_basic
=== RUN   TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== PAUSE TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== RUN   TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== PAUSE TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== RUN   TestAccAWSCognitoIdentityPool_samlProviderArns
=== PAUSE TestAccAWSCognitoIdentityPool_samlProviderArns
=== RUN   TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== PAUSE TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== RUN   TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider
--- PASS: TestAccAWSCognitoIdentityPool_addingNewProviderKeepsOldProvider (41.60s)
=== RUN   TestAccAWSCognitoIdentityPool_tags
=== PAUSE TestAccAWSCognitoIdentityPool_tags
=== CONT  TestAccAWSCognitoIdentityPool_basic
=== CONT  TestAccAWSCognitoIdentityPool_cognitoIdentityProviders
=== CONT  TestAccAWSCognitoIdentityPool_openidConnectProviderArns
=== CONT  TestAccAWSCognitoIdentityPool_samlProviderArns
=== CONT  TestAccAWSCognitoIdentityPool_supportedLoginProviders
=== CONT  TestAccAWSCognitoIdentityPool_tags
--- PASS: TestAccAWSCognitoIdentityPool_basic (32.62s)
--- PASS: TestAccAWSCognitoIdentityPool_supportedLoginProviders (44.51s)
--- PASS: TestAccAWSCognitoIdentityPool_tags (44.54s)
--- PASS: TestAccAWSCognitoIdentityPool_cognitoIdentityProviders (45.52s)
--- PASS: TestAccAWSCognitoIdentityPool_openidConnectProviderArns (45.55s)
--- PASS: TestAccAWSCognitoIdentityPool_samlProviderArns (47.68s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	92.171s
```

**Pull request merged**
