### PR TITLE
Add support for AWS Lambda Functions powered by AWS Graviton2 processors

### LINKED ISSUE #21090: AWS Lambda Functions powered by AWS Graviton2 processors
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

> AWS Lambda functions powered by next-generation AWS Graviton2 processors are now generally available.

### New or Affected Resource(s)

* [`aws_lambda_function`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/lambda_function)

### Potential Terraform Configuration

```hcl
resource "aws_lambda_function" "example" {
  architectures = ["arm64"]
}
```

### References

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/09/better-price-performance-aws-lambda-functions-aws-graviton2-processor/).

Requires [AWS SDK v1.40.52](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.52):

* #21087

### PR DESCRIPTION
**Pull request by bnusunny**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21090.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSLambdaFunction_Architectures'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaFunction_Architectures -timeout 180m
=== RUN   TestAccAWSLambdaFunction_Architectures
=== PAUSE TestAccAWSLambdaFunction_Architectures
=== RUN   TestAccAWSLambdaFunction_ArchitecturesUpdate
=== PAUSE TestAccAWSLambdaFunction_ArchitecturesUpdate
=== RUN   TestAccAWSLambdaFunction_ArchitecturesWithLayer
=== PAUSE TestAccAWSLambdaFunction_ArchitecturesWithLayer
=== CONT  TestAccAWSLambdaFunction_Architectures
=== CONT  TestAccAWSLambdaFunction_ArchitecturesWithLayer
=== CONT  TestAccAWSLambdaFunction_ArchitecturesUpdate
--- PASS: TestAccAWSLambdaFunction_Architectures (129.55s)
--- PASS: TestAccAWSLambdaFunction_ArchitecturesUpdate (133.42s)
--- PASS: TestAccAWSLambdaFunction_ArchitecturesWithLayer (158.51s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       161.156s

$ make testacc TESTARGS='-run=TestAccDataSourceAWSLambdaLayerVersion_architectures'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAWSLambdaLayerVersion_architectures -timeout 180m
=== RUN   TestAccDataSourceAWSLambdaLayerVersion_architectures
=== PAUSE TestAccDataSourceAWSLambdaLayerVersion_architectures
=== CONT  TestAccDataSourceAWSLambdaLayerVersion_architectures
--- PASS: TestAccDataSourceAWSLambdaLayerVersion_architectures (178.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	180.173s


$ make testacc TESTARGS='-run=TestAccAWSLambdaLayerVersion_compatibleArchitectures'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaLayerVersion_compatibleArchitectures -timeout 180m
=== RUN   TestAccAWSLambdaLayerVersion_compatibleArchitectures
=== PAUSE TestAccAWSLambdaLayerVersion_compatibleArchitectures
=== CONT  TestAccAWSLambdaLayerVersion_compatibleArchitectures
--- PASS: TestAccAWSLambdaLayerVersion_compatibleArchitectures (160.76s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	162.200s

...
```

### CODE REVIEW

**Comment by andymac4182** [comment]
Thanks @bnusunny and @gdavison! This is awesome to see this

**Review by gdavison — APPROVED** [review]
Looks good! 🚀 

Acceptance test results

--- SKIP: TestAccDataSourceAWSLambdaFunction_imageConfig (0.85s)
--- PASS: TestAccDataSourceAWSLambdaLayerVersion_runtime (42.72s)
--- PASS: TestAccDataSourceAWSLambdaLayerVersion_basic (42.81s)
--- PASS: TestAccDataSourceAWSLambdaLayerVersion_version (46.91s)
--- PASS: TestAccDataSourceAWSLambdaFunction_alias (79.97s)
--- PASS: TestAccDataSourceAWSLambdaFunction_environment (81.23s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_disappears_LambdaFunction (82.63s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_disappears_LambdaFunctionEventInvokeConfig (83.03s)
--- PASS: TestAccDataSourceAWSLambdaFunction_version (91.70s)
--- PASS: TestAccDataSourceAWSLambdaFunction_architectures (92.15s)
--- PASS: TestAccDataSourceAWSLambdaFunction_basic (92.47s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_FunctionName_Arn (91.42s)
--- PASS: TestAccDataSourceAWSLambdaFunction_layers (94.36s)
--- SKIP: TestAccAWSLambdaFunction_codeSigningConfig (1.27s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_basic (102.66s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_DestinationConfig_Swap (124.44s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_Qualifier_FunctionName_Arn (81.18s)
--- PASS: TestAccAWSLambdaFunction_expectFilenameAndS3Attributes (33.12s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_DestinationConfig_Remove (133.07s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_DestinationConfig_OnSuccess_Destination (137.60s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_DestinationConfig_OnFailure_Destination (148.69s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_Qualifier_AliasName (81.05s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_Qualifier_FunctionVersion (82.22s)
--- PASS: TestAccAWSLambdaFunction_basic (83.26s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_Qualifier_Latest (84.91s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_MaximumEventAgeInSeconds (128.87s)
--- SKIP: TestAccAWSLambdaFunction_imageConfig (1.09s)
--- PASS: TestAccDataSourceAWSLambdaLayerVersion_architectures (174.86s)
--- PASS: TestAccAWSLambdaFunction_disappears (83.07s)
--- PASS: TestAccAWSLambdaFunction_nilDeadLetterConfig (36.85s)
--- PASS: TestAccAWSLambdaFunction_Environment_Variables_NoValue (80.94s)
--- PASS: TestAccAWSLambdaFunction_versioned (87.68s)
--- PASS: TestAccAWSLambdaFunction_concurrency (127.38s)
--- PASS: TestAccAWSLambdaFunctionEventInvokeConfig_MaximumRetryAttempts (175.20s)
--- PASS: TestAccAWSLambdaFunction_UnpublishedCodeUpdate (145.22s)
--- PASS: TestAccAWSLambdaFunction_encryptedEnvVariables (138.78s)
--- PASS: TestAccAWSLambdaFunction_concurrencyCycle (183.19s)
--- PASS: TestAccAWSLambdaFunction_disablePublish (136.18s)
--- PASS: TestAccAWSLambdaFunction_KmsKeyArn_NoEnvironmentVariables (80.38s)
--- PASS: TestAccDataSourceAWSLambdaFunction_vpc (290.71s)
--- PASS: TestAccAWSLambdaFunction_Layers (86.08s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfig (143.38s)
--- PASS: TestAccAWSLambdaFunction_Architectures (132.33s)
--- PASS: TestAccAWSLambdaFunction_DeadLetterConfigUpdated (145.00s)
--- PASS: TestAccAWSLambdaFunction_ArchitecturesUpdate (143.33s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (185.63s)
--- PASS: TestAccAWSLambdaFunction_ArchitecturesWithLayer (142.27s)
--- PASS: TestAccAWSLambdaFunction_enablePublish (182.76s)
--- PASS: TestAccAWSLambdaFunction_tracingConfig (123.97s)
--- PASS: TestAccAWSLambdaFunction_envVariables (232.64s)
--- PASS: TestAccAWSLambdaFunction_zip_validation (6.73s)
--- PASS: TestFlattenLambdaImageConfigShouldNotFailWithEmptyImageConfig (0.00s)
--- PASS: TestAccAWSLambdaFunction_LayersUpdate (120.05s)
--- PASS: TestAccDataSourceAWSLambdaFunction_fileSystemConfig (354.14s)
--- PASS: TestAccAWSLambdaFunction_s3 (48.92s)
--- PASS: TestAccAWSLambdaLayerVersion_basic (36.72s)
--- PASS: TestAccAWSLambdaFunction_EmptyVpcConfig (68.02s)
--- PASS: TestAccAWSLambdaLayerVersion_s3 (44.17s)
--- PASS: TestAccAWSLambdaLayerVersion_compatibleRuntimes (44.76s)
--- PASS: TestAccAWSLambdaLayerVersion_update (68.28s)
--- PASS: TestAccAWSLambdaFunction_localUpdate (102.92s)
--- PASS: TestAccAWSLambdaFunction_localUpdate_nameOnly (102.77s)
--- PASS: TestAccAWSLambdaFunction_s3Update_unversioned (95.30s)
--- PASS: TestAccAWSLambdaLayerVersion_licenseInfo (41.07s)
--- PASS: TestAccAWSLambdaLayerVersion_description (41.96s)
--- PASS: TestAccAWSLambdaFunction_s3Update_basic (96.85s)
--- PASS: TestAccAWSLambdaFunction_tags (110.12s)
--- PASS: TestAccAWSLambdaLayerVersion_compatibleArchitectures (88.68s)
--- PASS: TestAccAWSLambdaFunction_VPC (258.35s)
--- PASS: TestAccAWSLambdaFunction_VPC_publish_No_Changes (270.90s)
--- PASS: TestAccAWSLambdaFunction_VpcConfig_ProperIamDependencies (266.54s)
--- PASS: TestAccAWSLambdaFunction_VPCRemoval (448.45s)
--- PASS: TestAccAWSLambdaFunction_runtimes (384.57s)
--- PASS: TestAccAWSLambdaFunction_VPC_withInvocation (430.49s)
--- PASS: TestAccAWSLambdaFunction_VPC_publish_Has_Changes (449.11s)
--- PASS: TestAccAWSLambdaFunction_FileSystemConfig (1915.23s)
--- PASS: TestAccAWSLambdaFunction_VPCUpdate (1861.15s)

**Comment by AMMullan** [comment]
What was the thinking behind using architectures plural and setting it as a list item? You can only set it to either arm64 or x86_64?

**Comment by bnusunny** [comment]
"architectures" is a list in Lambda API. So we match it in the provider.

**Pull request merged**
