### PR TITLE
Fix missing default value in cloudfront_distribution's origin.origin_path

### PR DESCRIPTION
**Pull request by kyontan**
The default value of `origin_path` parameter in `origin` block is blank string (`""`), not `null`.
It is known problem in https://github.com/hashicorp/terraform-provider-aws/issues/12065.  The workaround is described in the issue.
Without this PR, modifing `aws_cloudfront_distrtibution` will **crash** and state get **broken**.

It is apparently a bug in the provider and it should be handled by provider.

I have confirmed CLI (`aws cloudfront get-distribution`) returns blank string (`""`) as default value if create resource without setting `origin_path` explicitly.

According to the document, the default value is not noted though.
https://docs.aws.amazon.com/cloudfront/latest/APIReference/API_Origin.html

This problem is work-arounded https://github.com/jmgreg31/terraform-aws-cloudfront/pull/38.

Relates: #12065

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloudFrontDistribution*'
==> Checking that code complies with gofmt requirements...

TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudFrontDistribution* -timeout 180m
(RUN, PAUSE, and CONT are omitted)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyOriginID (84.70s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_EmptyDomainName (88.44s)
--- PASS: TestAccAWSCloudFrontDistribution_disappears (378.55s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_TrustedSigners (381.56s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_TrustedKeyGroups (425.97s)
--- PASS: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn_ConflictsWithCloudFrontDefaultCertificate (430.12s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_RealtimeLogConfigArn (435.36s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_RealtimeLogConfigArn (442.50s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Headers (455.09s)
--- PASS: TestAccAWSCloudFrontDistribution_DefaultCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (483.63s)
--- PASS: TestAccAWSCloudFrontDistribution_noOptionalItemsConfig (504.55s)
--- PASS: TestAccAWSCloudFrontDistribution_RetainOnDelete (559.72s)
--- PASS: TestAccAWSCloudFrontDistribution_IsIPV6EnabledConfig (560.71s)
--- PASS: TestAccAWSCloudFrontDistribution_noCustomErrorResponseConfig (565.85s)
--- PASS: TestAccAWSCloudFrontDistribution_HTTP11Config (567.32s)
--- PASS: TestAccAWSCloudFrontDistribution_originPolicyOrdered (482.98s)
--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehaviorCachePolicy (480.73s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_ConnectionTimeout (610.52s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_ConnectionAttempts (610.79s)
--- PASS: TestAccAWSCloudFrontDistribution_Origin_OriginShield (611.74s)
--- PASS: TestAccAWSCloudFrontDistribution_ViewerCertificate_AcmCertificateArn (236.41s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Cookies_WhitelistedNames (265.15s)
--- PASS: TestAccAWSCloudFrontDistribution_OrderedCacheBehavior_ForwardedValues_Headers (306.66s)
--- PASS: TestAccAWSCloudFrontDistribution_forwardedValuesToCachePolicy (751.16s)
--- PASS: TestAccAWSCloudFrontDistribution_orderedCacheBehavior (392.02s)
--- PASS: TestAccAWSCloudFrontDistribution_customOrigin (473.06s)
--- PASS: TestAccAWSCloudFrontDistribution_originPolicyDefault (469.09s)
--- PASS: TestAccAWSCloudFrontDistribution_OriginGroups (479.67s)
--- PASS: TestAccAWSCloudFrontDistribution_Enabled (905.76s)
--- PASS: TestAccAWSCloudFrontDistribution_multiOrigin (531.50s)
--- PASS: TestAccAWSCloudFrontDistribution_S3Origin (374.37s)
--- PASS: TestAccAWSCloudFrontDistribution_WaitForDeployment (449.19s)
--- PASS: TestAccAWSCloudFrontDistribution_S3OriginWithTags (577.89s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1086.053s
```

### CODE REVIEW

**Comment by kyontan** [comment]
We have ran the acceptance tests and confirmed no regression occured.

**Comment by kyontan** [comment]
@breathingdust Could you see this pr? Thanks.

**Comment by kyontan** [comment]
@ewbankkit @DrFaust92 Could you take a look for this pr?
Our environment's tfstate got broken by this bug, so I think it should have higher priority.

**Review by YakDriver — APPROVED** [review]
Thank you 🎉 

```console
% make testacc TESTS=TestAccCloudFrontDistribution PKG=cloudfront
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20 -run='TestAccCloudFrontDistribution'  -timeout 180m
--- PASS: TestAccCloudFrontDistribution_OrderedCacheBehaviorForwardedValues_headers (202.36s)
--- PASS: TestAccCloudFrontDistribution_DefaultCacheBehaviorForwardedValuesCookies_whitelistedNames (204.63s)
--- PASS: TestAccCloudFrontDistribution_DefaultCacheBehavior_trustedSigners (204.70s)
--- PASS: TestAccCloudFrontDistribution_OrderedCacheBehaviorForwardedValuesCookies_whitelistedNames (204.97s)
--- PASS: TestAccCloudFrontDistribution_ViewerCertificate_acmCertificateARN (224.22s)
--- PASS: TestAccCloudFrontDistribution_DefaultCacheBehavior_trustedKeyGroups (232.73s)
--- PASS: TestAccCloudFrontDistribution_DefaultCacheBehavior_realtimeLogARN (239.07s)
--- PASS: TestAccCloudFrontDistribution_OrderedCacheBehavior_realtimeLogARN (248.34s)
--- PASS: TestAccCloudFrontDistribution_DefaultCacheBehaviorForwardedValues_headers (256.20s)
--- PASS: TestAccCloudFrontDistribution_ViewerCertificateACMCertificateARN_conflictsWithCloudFrontDefaultCertificate (268.27s)
--- PASS: TestAccCloudFrontDistribution_http11 (370.16s)
--- PASS: TestAccCloudFrontDistribution_isIPV6Enabled (371.68s)
--- PASS: TestAccCloudFrontDistribution_Origin_emptyDomainName (0.80s)
--- PASS: TestAccCloudFrontDistribution_Origin_emptyOriginID (0.78s)
--- PASS: TestAccCloudFrontDistribution_noCustomErrorResponse (384.29s)
--- PASS: TestAccCloudFrontDistribution_Origin_connectionAttempts (386.37s)
--- PASS: TestAccCloudFrontDistributionDataSource_basic (387.11s)
--- PASS: TestAccCloudFrontDistribution_retainOnDelete (389.10s)
--- PASS: TestAccCloudFrontDistribution_waitForDeployment (396.73s)
--- PASS: TestAccCloudFrontDistribution_orderedCacheBehaviorCachePolicy (487.60s)
--- PASS: TestAccCloudFrontDistribution_originGroups (497.02s)
--- PASS: TestAccCloudFrontDistribution_disappears (189.06s)
--- PASS: TestAccCloudFrontDistribution_enabled (560.13s)
--- PASS: TestAccCloudFrontDistribution_orderedCacheBehavior (355.57s)
--- PASS: TestAccCloudFrontDistribution_originPolicyOrdered (359.08s)
--- PASS: TestAccCloudFrontDistribution_noOptionalItems (337.64s)
--- PASS: TestAccCloudFrontDistribution_multiOrigin (366.12s)
--- PASS: TestAccCloudFrontDistribution_originPolicyDefault (372.31s)
--- PASS: TestAccCloudFrontDistribution_customOrigin (332.03s)
--- PASS: TestAccCloudFrontDistribution_Origin_originShield (450.51s)
--- PASS: TestAccCloudFrontDistribution_s3Origin (421.80s)
--- PASS: TestAccCloudFrontDistribution_Origin_connectionTimeout (414.74s)
--- PASS: TestAccCloudFrontDistribution_orderedCacheBehaviorResponseHeadersPolicy (358.96s)
--- PASS: TestAccCloudFrontDistribution_s3OriginWithTags (514.25s)
```

**Pull request merged**
