### PR TITLE
Add import of `aws_ses_active_receipt_rule_set` resource

### LINKED ISSUE #29369: [Enhancement]: importing `aws_ses_active_receipt_rule_set`
### Description

Thanks to all the maintainers.

Current Provider has no way to import `aws_ses_active_receipt_rule_set`
https://registry.terraform.io/providers/hashicorp/aws/4.54.0/docs/resources/ses_active_receipt_rule_set

I have created the following PR and it has been reviewed and approved but not yet merged.
https://github.com/hashicorp/terraform-provider-aws/pull/27604

What else is needed to merge this PR?

### Affected Resource(s) and/or Data Source(s)

aws_ses_active_receipt_rule_set

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by yktakaha4**
Enable Import with the following command.

```
terraform import aws_ses_active_receipt_rule_set.my_rule_set my_rule_set_name
```

As a specification of SES, only one active receipt rule set is valid within the same region.

`describe-active-receipt-rule-set` AWS API cannot take any arguments and return an active rule set when called.
Import command will succeed only if the rule_set_name passed matches the API return value.

ref: https://docs.aws.amazon.com/cli/latest/reference/ses/describe-active-receipt-rule-set.html

### Relations

Closes #29369

### References

If no Active ruleset exists, Import will fail.

image

```
$ terraform import aws_ses_active_receipt_rule_set.my_rule_set hoge
aws_ses_active_receipt_rule_set.my_rule_set: Importing from ID "hoge"...
╷
│ Error: no active Receipt Rule Set found
│ 
│ 
╵
```

Import will also fail if the ruleset names do not match.

image

```
$ terraform import aws_ses_active_receipt_rule_set.my_rule_set fuga
aws_ses_active_receipt_rule_set.my_rule_set: Importing from ID "fuga"...
╷
│ Error: SES Receipt Rule Set (fuga) belonging to SES Active Receipt Rule Set not found
│ 
│ 
╵
```

If rule_set_name matches,

```
$ terraform import aws_ses_active_receipt_rule_set.my_rule_set hoge
aws_ses_active_receipt_rule_set.my_rule_set: Importing from ID "hoge"...
aws_ses_active_receipt_rule_set.my_rule_set: Import prepared!
  Prepared aws_ses_active_receipt_rule_set for import
aws_ses_active_receipt_rule_set.my_rule_set: Refreshing state... [id=hoge]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

$ terraform plan                                                   
╷
│ Warning: Provider development overrides are in effect
│ 
│ The following provider development overrides are set in the CLI configuration:
│  - hashicorp/aws in /home/tkhs/go/bin
│ 
│ The behavior may therefore not match any released version of the provider and applying changes may cause the state to become incompatible with published releases.
╵
aws_ses_active_receipt_rule_set.my_rule_set: Refreshing state... [id=hoge]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

### Output from Acceptance Testing

In my local.

```
$ make testacc TESTS=TestAccSESActiveReceiptRuleSet PKG=ses       
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESActiveReceiptRuleSet'  -timeout 180m
=== RUN   TestAccSESActiveReceiptRuleSet_serial
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/disappears
--- PASS: TestAccSESActiveReceiptRuleSet_serial (98.90s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource (38.36s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/basic (33.18s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet (5.17s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource (60.54s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/basic (32.96s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/disappears (27.58s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ses        98.980s
```

### CODE REVIEW

**Review by kamilturek — APPROVED** [review]
LGTM 👍

**Comment by yktakaha4** [comment]
Conflicts resolved.

```
$ make testacc TESTS=TestAccSESActiveReceiptRuleSet PKG=ses
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESActiveReceiptRuleSet'  -timeout 180m
=== RUN   TestAccSESActiveReceiptRuleSet_serial
=== PAUSE TestAccSESActiveReceiptRuleSet_serial
=== CONT  TestAccSESActiveReceiptRuleSet_serial
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/disappears
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet
--- PASS: TestAccSESActiveReceiptRuleSet_serial (86.02s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource (55.87s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/basic (31.21s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/disappears (24.66s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource (30.15s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/basic (25.59s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet (4.56s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ses        86.129s
```

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ make testacc PKG=ses TESTS=TestAccSESActiveReceiptRuleSet_serial
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ses/... -v -count 1 -parallel 20 -run='TestAccSESActiveReceiptRuleSet_serial'  -timeout 180m
=== RUN   TestAccSESActiveReceiptRuleSet_serial
=== PAUSE TestAccSESActiveReceiptRuleSet_serial
=== CONT  TestAccSESActiveReceiptRuleSet_serial
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/Resource/disappears
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/basic
=== RUN   TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet
--- PASS: TestAccSESActiveReceiptRuleSet_serial (50.98s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource (32.66s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/basic (18.04s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/Resource/disappears (14.62s)
    --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource (18.32s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/basic (15.94s)
        --- PASS: TestAccSESActiveReceiptRuleSet_serial/DataSource/noActiveRuleSet (2.37s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ses        54.441s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @yktakaha4! 👍

**Pull request merged**
