### PR TITLE
Fix: Setting default values for scale_in_protected_instances and standby_instances as per documentation

### PR DESCRIPTION
**Pull request by adiospeds**
### Description

Since https://github.com/hashicorp/terraform-provider-aws/pull/33310 was merged we are getting below error:
```
│ Error: starting Auto Scaling Group (terraform-x) instance refresh: ValidationError: 2 validation errors detected: 
Value '' at 'preferences.scaleInProtectedInstances' failed to satisfy constraint: Member must satisfy enum value set: [Ignore, Wait, Refresh]; 
Value '' at 'preferences.standbyInstances' failed to satisfy constraint: Member must satisfy enum value set: [Terminate, Ignore, Wait]
```

While the documentation for the above parameters says the Default value for the above arguments [scale_in_protected_instances](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#scale_in_protected_instances) and [standby_instances](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#standby_instances) is `Wait` I think we forgot to add it to the code.

### Relations

Relates [#33310](https://github.com/hashicorp/terraform-provider-aws/pull/33310).
Closes [#33377](https://github.com/hashicorp/terraform-provider-aws/issues/33377).

### CODE REVIEW

**Comment by zm-alex** [comment]
👍 +1

**Comment by mhowell-ims** [comment]
I wonder if 'Wait' is actually the right option for the default value. Using 'Wait' actually requires manual intervention if it gets triggered, which seems to go against the spirit of infrastructure-as-code. It would also cause the instance refresh to 'pause' for up to an hour while waiting for manual intervention to occur, which could cause other issues. The AWS web console actually recommends 'Ignore' for both of these settings.
Screenshot 2023-09-08 at 5 29 44 PM

**Comment by adiospeds** [comment]
@mhowell-ims I agree to what you are saying. ` Ignore` seems to be a more better option for majority of the use cases. Thank you for the suggestion and making this fix better. Pushing the change for your suggestion and I'll also have the [documentation](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/autoscaling_group#scale_in_protected_instances) updated.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAutoScalingGroup_InstanceRefresh_' PKG=autoscaling ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/autoscaling/... -v -count 1 -parallel 3  -run=TestAccAutoScalingGroup_InstanceRefresh_ -timeout 180m
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_basic
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_basic
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_start
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_start
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_triggers
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_triggers
=== RUN   TestAccAutoScalingGroup_InstanceRefresh_autoRollback
=== PAUSE TestAccAutoScalingGroup_InstanceRefresh_autoRollback
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_basic
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_autoRollback
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_triggers
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_autoRollback (188.24s)
=== CONT  TestAccAutoScalingGroup_InstanceRefresh_start
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_triggers (212.21s)
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_basic (344.02s)
--- PASS: TestAccAutoScalingGroup_InstanceRefresh_start (262.59s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/autoscaling	456.268s
```

**Comment by ewbankkit** [comment]
@adiospeds Thanks for the contribution :tada: :clap:.

**Pull request merged**
