### PR TITLE
r/sagemaker_space - new resource

### LINKED ISSUE #27265: [Bug]: aws_sagemaker_app still get persisted in spite of failure state
### Terraform Core Version

1.2.9

### AWS Provider Version

4.34.0

### Affected Resource(s)

During the provisioning of `aws_sagemaker_app` if there is an error that put the App in a `Failed` state (i.e a Lifecycle Configuration script error), the `aws_sagemaker_app` is still persisted in the Terraform state. This results in error trying to refresh its status in subsequent runs

### Expected Behavior

`aws_sagemaker_app` in a `Failed` state should not be persisted in the Terraform state

### Actual Behavior

`aws_sagemaker_app` in a `Failed` stabe persisted in the Terraform state, requiring manual removal to re-create

### Relevant Error/Panic Output Snippet

```shell
│ Error: waiting for SageMaker App (redacted) to create: unexpected state 'Failed', wanted target 'InService'. last error: %!s(<nil>)
│ 
│   with aws_sagemaker_app.jupyter,
│   on sagemaker.tf line 60, in resource "aws_sagemaker_app" "jupyter":
│   60: resource "aws_sagemaker_app" "jupyter" {

---

aws_sagemaker_app.jupyter: Refreshing state... [redacted]
╷
│ Error: listing tags for SageMaker App (redacted): ValidationException: 
│       status code: 400, request id: redacted
│ 
│   with aws_sagemaker_app.jupyter,
│   on sagemaker.tf line 60, in resource "aws_sagemaker_app" "jupyter":
│   60: resource "aws_sagemaker_app" "jupyter" {
```

### Terraform Configuration Files

https://gist.github.com/hungluong5791/4836adc3832c8b285dab635d6cf32d91

### Steps to Reproduce

- Plan + apply the configuration with error in the lifecycle configuration script- 
- Observe the error stating failure in waiting for SageMaker App
- Plan + apply the configuration again
- Observe the bug:
- a) the failed SageMaker app is in the state and still get refreshed
- b) an error listing tags for the failed SageMaker app (as it doesn't exists due to failure in provisioning)

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

_No response_

### LINKED ISSUE #27990: [Bug]: Cannot enable or disable SageMaker JumpStart templates
### Terraform Core Version

1.2.3

### AWS Provider Version

v4.40.0, v4.39.0, v4.38.0

### Affected Resource(s)

aws_sagemaker_domain

### Expected Behavior

Successfully able to update domain settings by enabling `SageMaker Projects and JumpStart`. Currently the terraform resource does not support doing this. 

### Actual Behavior

After successful sagemaker_domain provisioning, if you want to enable SageMaker jumpStart poject templates and submit validation error is thrown. 

ValidationException
2 validation errors detected

    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must have length greater than or equal to 20
    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$

### Relevant Error/Panic Output Snippet

```shell
After successful sagemaker_domain provisioning, if you want to enable SageMaker jumpStart poject templates and submit validation error is thrown. 


ValidationException
2 validation errors detected

    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must have length greater than or equal to 20
    Value '' at 'defaultSpaceSettings.executionRole' failed to satisfy constraint: Member must satisfy regular expression pattern: ^arn:aws[a-z\-]*:iam::\d{12}:role/?[a-zA-Z_0-9+=,.@\-_/]+$


POST API call from the web-console suggests DefaultSpaceSettings for `ExecutionRole` is empty


`{"DomainId":"d-xxxxx","DefaultUserSettings":{"ExecutionRole":"arn:aws:iam::xxxxxx:role/sagemaker-default-execution-role","SharingSettings":{"NotebookOutputOption":"Disabled","S3OutputPath":"s3://sagemaker-studio-xxxxxx"},"JupyterServerAppSettings":{"DefaultResourceSpec":{"SageMakerImageArn":"arn:aws:sagemaker:eu-central-1:xxxxxx:image/jupyter-server-3","InstanceType":"system"}}},"DefaultSpaceSettings":{"ExecutionRole":""}}`
```

### Terraform Configuration Files

```
resource "aws_sagemaker_domain" "sagemaker_domain" {
  domain_name = "sagemamker-domain"
  auth_mode   = "IAM"
  vpc_id      = module.vpc.vpc_id
  subnet_ids  = module.vpc.private_subnets

  default_user_settings {
    execution_role = aws_iam_role.sagemaker_execution_role.arn
  }

}

resource "aws_iam_role" "sagemaker_execution_role" {
  name               = "sagemaker-default-exec-role"
  path               = "/"
  assume_role_policy = data.aws_iam_policy_document.sagemaker_exec_policy.json
 managed_policy_arns = ["arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"]
}

data "aws_iam_policy_document" "sagemaker_exec_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["sagemaker.amazonaws.com"]
    }
  }
}
```

### Steps to Reproduce

1. Create `aws_sagemaker_domain` 
2. Try to update domain settings by enabling/ disabling `SageMaker Projects and JumpStart` and it fails due to validation exception.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

Related to https://github.com/hashicorp/terraform-provider-aws/issues/21490

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by DrFaust92**
### Relations

Closes #27265
Closes #27990

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccSageMaker_serial/Space

--- PASS: TestAccSageMaker_serial (1666.88s)
    --- PASS: TestAccSageMaker_serial/Space (1666.88s)
        --- PASS: TestAccSageMaker_serial/Space/basic (271.61s)
        --- PASS: TestAccSageMaker_serial/Space/disappears (324.01s)
        --- PASS: TestAccSageMaker_serial/Space/tags (265.95s)
        --- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings (269.04s)
        --- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings_lifecycleConfig (267.09s)
        --- PASS: TestAccSageMaker_serial/Space/jupyterServerAppSettings (269.17s)


--- PASS: TestAccSageMaker_serial (5300.99s)
    --- PASS: TestAccSageMaker_serial/Domain (5300.99s)
        --- PASS: TestAccSageMaker_serial/Domain/sharingSettings (444.31s)
        --- PASS: TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated (305.97s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage (324.92s)
        --- PASS: TestAccSageMaker_serial/Domain/securityGroup (298.91s)
        --- PASS: TestAccSageMaker_serial/Domain/domainSettings (293.67s)
        --- PASS: TestAccSageMaker_serial/Domain/rSessionAppSettings (261.86s)
        --- PASS: TestAccSageMaker_serial/Domain/tags (256.94s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings (264.39s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig (262.01s)
        --- PASS: TestAccSageMaker_serial/Domain/basic (264.71s)
        --- PASS: TestAccSageMaker_serial/Domain/disappears (327.10s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings (305.11s)
        --- PASS: TestAccSageMaker_serial/Domain/kms (428.08s)
        --- PASS: TestAccSageMaker_serial/Domain/canvas (468.37s)
        --- PASS: TestAccSageMaker_serial/Domain/code (265.32s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettings (264.47s)
        --- PASS: TestAccSageMaker_serial/Domain/jupyterServerAppSettings (264.84s)

--- PASS: TestAccSageMaker_serial (3120.53s)
    --- PASS: TestAccSageMaker_serial/App (3120.52s)
        --- PASS: TestAccSageMaker_serial/App/resourceSpec (410.41s)
        --- PASS: TestAccSageMaker_serial/App/resourceSpecLifecycle (545.64s)
        --- PASS: TestAccSageMaker_serial/App/space (484.87s)
        --- PASS: TestAccSageMaker_serial/App/basic (646.75s)
        --- PASS: TestAccSageMaker_serial/App/disappears (445.85s)
        --- PASS: TestAccSageMaker_serial/App/tags (587.00s)
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
should also resolve #27265

**Comment by pawelpesz** [comment]
If I may comment, because I'm also currently struggling with getting SageMaker to work when its resources are created with Terraform.
I'm afraid creating SageMaker space will not fix https://github.com/hashicorp/terraform-provider-aws/issues/27990 completely because domains with SSO (aka IAM Identity Center) do not support it.
Here's the error I'm getting when attempting to create a space with AWS CLI (v2.9.4):
```
$ aws sagemaker create-space --domain-id ztrgdmgpfeuu --space-name default

An error occurred (ValidationException) when calling the CreateSpace operation: Domains with AWS IAM Identity Center (successor to AWS SSO) enabled do not support Spaces.
```

**Comment by DrFaust92** [comment]
https://github.com/hashicorp/terraform-provider-aws/issues/27990 is not related to your issue, as the example in that issue is IAM. this is not a TF issue as you show an error from CLI for the service to not support this combo (yet)

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSageMaker_serial/App\|TestAccSageMaker_serial/Domain\|TestAccSageMaker_serial/Space\|TestAccSageMaker_serial/UserProfile' PKG=sagemaker
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20  -run=TestAccSageMaker_serial/App\|TestAccSageMaker_serial/Domain\|TestAccSageMaker_serial/Space\|TestAccSageMaker_serial/UserProfile -timeout 180m
=== RUN   TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Space
=== RUN   TestAccSageMaker_serial/Space/kernelGatewayAppSettings_imageConfig
    space_test.go:161: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Space/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/Space/basic
=== RUN   TestAccSageMaker_serial/Space/disappears
=== RUN   TestAccSageMaker_serial/Space/tags
=== RUN   TestAccSageMaker_serial/Space/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Space/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/UserProfile
=== RUN   TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/UserProfile/basic
=== RUN   TestAccSageMaker_serial/UserProfile/disappears
=== RUN   TestAccSageMaker_serial/UserProfile/tags
=== RUN   TestAccSageMaker_serial/UserProfile/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_imageConfig
    user_profile_test.go:233: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/UserProfile/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/App
=== RUN   TestAccSageMaker_serial/App/space
=== RUN   TestAccSageMaker_serial/App/basic
=== RUN   TestAccSageMaker_serial/App/disappears
=== RUN   TestAccSageMaker_serial/App/tags
=== RUN   TestAccSageMaker_serial/App/resourceSpec
=== RUN   TestAccSageMaker_serial/App/resourceSpecLifecycle
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/code
=== RUN   TestAccSageMaker_serial/Domain/disappears
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/Domain/canvas
=== RUN   TestAccSageMaker_serial/Domain/domainSettings
=== RUN   TestAccSageMaker_serial/Domain/rSessionAppSettings
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/basic
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage
=== RUN   TestAccSageMaker_serial/Domain/securityGroup
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage
    domain_test.go:431: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage
    domain_test.go:469: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/kms
=== RUN   TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated
=== RUN   TestAccSageMaker_serial/Domain/tags
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/Domain/sharingSettings
--- PASS: TestAccSageMaker_serial (10590.57s)
    --- PASS: TestAccSageMaker_serial/Space (1540.71s)
        --- SKIP: TestAccSageMaker_serial/Space/kernelGatewayAppSettings_imageConfig (0.00s)
        --- PASS: TestAccSageMaker_serial/Space/jupyterServerAppSettings (246.38s)
        --- PASS: TestAccSageMaker_serial/Space/basic (256.37s)
        --- PASS: TestAccSageMaker_serial/Space/disappears (296.01s)
        --- PASS: TestAccSageMaker_serial/Space/tags (253.46s)
        --- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings (245.38s)
        --- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings_lifecycleConfig (243.11s)
    --- PASS: TestAccSageMaker_serial/UserProfile (2049.16s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage (260.87s)
        --- PASS: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings (247.08s)
        --- PASS: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_lifecycleConfig (252.18s)
        --- PASS: TestAccSageMaker_serial/UserProfile/basic (253.29s)
        --- PASS: TestAccSageMaker_serial/UserProfile/disappears (289.12s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tags (244.39s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettings (247.07s)
        --- SKIP: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_imageConfig (0.00s)
        --- PASS: TestAccSageMaker_serial/UserProfile/jupyterServerAppSettings (255.16s)
    --- PASS: TestAccSageMaker_serial/App (2715.03s)
        --- PASS: TestAccSageMaker_serial/App/space (477.49s)
        --- PASS: TestAccSageMaker_serial/App/basic (474.46s)
        --- PASS: TestAccSageMaker_serial/App/disappears (431.27s)
        --- PASS: TestAccSageMaker_serial/App/tags (478.21s)
        --- PASS: TestAccSageMaker_serial/App/resourceSpec (404.81s)
        --- PASS: TestAccSageMaker_serial/App/resourceSpecLifecycle (448.79s)
    --- PASS: TestAccSageMaker_serial/Domain (4285.67s)
        --- PASS: TestAccSageMaker_serial/Domain/code (239.00s)
        --- PASS: TestAccSageMaker_serial/Domain/disappears (268.90s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig (237.78s)
        --- PASS: TestAccSageMaker_serial/Domain/canvas (240.28s)
        --- PASS: TestAccSageMaker_serial/Domain/domainSettings (259.04s)
        --- PASS: TestAccSageMaker_serial/Domain/rSessionAppSettings (255.70s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings (262.76s)
        --- PASS: TestAccSageMaker_serial/Domain/basic (250.77s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage (297.71s)
        --- PASS: TestAccSageMaker_serial/Domain/securityGroup (261.55s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage (0.00s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/kms (238.33s)
        --- PASS: TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated (260.87s)
        --- PASS: TestAccSageMaker_serial/Domain/tags (235.37s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettings (238.65s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings (247.71s)
        --- PASS: TestAccSageMaker_serial/Domain/jupyterServerAppSettings (251.72s)
        --- PASS: TestAccSageMaker_serial/Domain/sharingSettings (239.54s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	10595.699s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Pull request merged**
