### PR TITLE
r/aws_config_organization_custom_policy_rule: New resource

### LINKED ISSUE #26989: [New Resource]: aws_config_organization_custom_policy
### Description

The https://docs.aws.amazon.com/config/latest/APIReference/API_PutOrganizationConfigRule.html API supports `OrganizationCustomPolicyRuleMetadata` which allows setting AWS Config Custom Policy as AWS Cloudformation guard policy text. This feature is available with the [aws_config_config_rule](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule#custom-policies) but is not available for the `aws_config_organisation_*`.

### Requested Resource(s) and/or Data Source(s)

* aws_config_organization_custom_policy

### Potential Terraform Configuration

```terraform
resource "aws_config_organization_custom_policy" "example-organisation-config-rule" {
	name = "example-organisation-config-rule-name"

	organisation_config_rule_trigger_types = ["ConfigurationItemChangeNotification"]
	maximum_execution_frequency = "Twelve_Hours"

	policy_runtime = "guard-2.x.x"
	policy_text = << EOF
	rule tableisactive when
	resourceType == "AWS::DynamoDB::Table" {
		configuration.tableStatus == ['ACTIVE']
	}

	rule checkcompliance when
	resourceType == "AWS::DynamoDB::Table"
	tableisactive {
		supplementaryConfiguration.ContinuousBackupsDescription.pointInTimeRecoveryDescription.pointInTimeRecoveryStatus == "ENABLED"
	}
	EOF

}
```

### References

- https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule#custom-policies
- https://docs.aws.amazon.com/config/latest/APIReference/API_OrganizationCustomPolicyRuleMetadata.html#config-Type-OrganizationCustomPolicyRuleMetadata-PolicyText

### Would you like to implement a fix?

No

### LINKED ISSUE #27987: [Enhancement]: AWS Config Organizational Custom Rules using Guard Custom policy
### Description

Using the CLI, it is possible to create organization-level config rules using Guard custom policy like so

```
$ aws configservice put-organization-config-rule --organization-config-rule-name test-1 --organization-custom-policy-rule-metadata '{"Description": "test-guard-org-rule", "OrganizationConfigRuleTriggerTypes": ["ConfigurationItemChangeNotification"], "PolicyRuntime": "guard-2.x.x", "PolicyText": "let var = 5"}'
```

The terraform `aws_config_organization_custom_rule` supports custom resources via lambda functions only

### Affected Resource(s) and/or Data Source(s)

* aws_config_organization_custom_rule

### Potential Terraform Configuration

_No response_

### References

There's an issue [here](https://github.com/aws-cloudformation/cloudformation-coverage-roadmap/issues/1273) requesting the same functionality for CloudFormation.

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by georgealton**
### Description

This adds a new resource `aws_config_organization_custom_policy_rule`

AWS Config Rules added the capability to use a CloudFormation Guard Policy as a declarative way of performing assertions against resource configuration, without having to manage a Lambda Function. 

The Provider gained the capability to manage Account Level CFN Guard Policy backed Rules, but not learn this for Organization Config Rules.

This PR adds the Organization Rule Resource, allowing a team to easily apply a policy to an entire organization, without having to manage and deploy Lambda functions to many accounts.

This feature is really useful for central enabling teams looking to validate best practice compliance in a multi AWS account, high autonomy, organization.

### Relations
Closes #27987
Closes #26989

### References

API Docs: https://docs.aws.amazon.com/config/latest/APIReference/API_PutOrganizationConfigRule.html
Related Config Rule Resource: https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/config_config_rule#custom-policy-details

### Output from Acceptance Testing
It was tricky to get all the Acceptance tests to pass together, there is some eventual consistency between organizations and config that sometimes in resulted in AWS Config reporting that the account wasn't a member of an Organization. This might be addressable with more thought on https://github.com/hashicorp/terraform-provider-aws/issues/11582

```
make testacc TESTS='TestAccConfigServiceOrganizationCustomPolicyRule' PKG=configservice
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/configservice/... -v -count 1 -parallel 20 -run='TestAccConfigServiceOrganizationCustomPolicyRule'  -timeout 180m
=== RUN   TestAccConfigServiceOrganizationCustomPolicyRule_basic
--- PASS: TestAccConfigServiceOrganizationCustomPolicyRule_basic (267.03s)
=== RUN   TestAccConfigServiceOrganizationCustomPolicyRule_disappears
--- PASS: TestAccConfigServiceOrganizationCustomPolicyRule_disappears (246.83s)
=== RUN   TestAccConfigServiceOrganizationCustomPolicyRule_PolicyText
--- PASS: TestAccConfigServiceOrganizationCustomPolicyRule_PolicyText (386.49s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/configservice	905.497s
```

### CODE REVIEW

**Review by glenthomas — APPROVED** [review]
Looks good to me!

**Comment by gpetrovgeorgi** [comment]
Hello guys, when we could expect this PR to be merged ? My organization is looking for this exact solution at the moment. Thank you in advance.

**Comment by georgealton** [comment]
> Hello guys, when we could expect this PR to be merged ? My organization is looking for this exact solution at the moment. Thank you in advance.

You've encouraged me to get the tests passing again :)

**Comment by ewbankkit** [comment]
@georgealton Thanks for the contribution :tada: :clap:.

**Comment by valscion** [comment]
Looks like the changelog accidentally referred to PR #21373 rather than this PR :)

**Pull request merged**
