### PR TITLE
add data source for aws_servicecatalog_provisioning_artifacts

### LINKED ISSUE #25531: add data source for aws_servicecatalog_provisioning_artifacts
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new data source that can list provisioning artifacts for a specific product. This can then be used in conjunction with resource `aws_servicecatalog_provisioned_product`, which takes a `provisioning_artifact_id` attribute.

### New or Affected Resource(s)

* aws_servicecatalog_provisioning_artifacts

### Potential Terraform Configuration

```hcl
data "aws_servicecatalog_provisioning_artifacts" "this" {
  accept_language = "en"
  product_id      = "p-example"
}
```

### References

* https://docs.aws.amazon.com/servicecatalog/latest/dg/API_ListProvisioningArtifacts.html

* #24362

### PR DESCRIPTION
**Pull request by silvaalbert**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #25531

Output from acceptance testing:

```
$ make testacc TESTS='TestAccServiceCatalogProvisioningArtifactsDataSource_basic' PKG=servicecatalog TESTARGS=-short
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogProvisioningArtifactsDataSource_basic' -short -timeout 180m
=== RUN   TestAccServiceCatalogProvisioningArtifactsDataSource_basic
=== PAUSE TestAccServiceCatalogProvisioningArtifactsDataSource_basic
=== CONT  TestAccServiceCatalogProvisioningArtifactsDataSource_basic
--- PASS: TestAccServiceCatalogProvisioningArtifactsDataSource_basic (36.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	38.528s

...
```

### CODE REVIEW

**Comment by vanveele** [comment]
Is there anything blocking this PR?
The feature as it is implemented here would be useful to me.

**Comment by pdahake** [comment]
This would help us with our end to end automation.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccServiceCatalogProvisioningArtifactsDataSource_' PKG=servicecatalog ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/servicecatalog/... -v -count 1 -parallel 3  -run=TestAccServiceCatalogProvisioningArtifactsDataSource_ -timeout 180m
=== RUN   TestAccServiceCatalogProvisioningArtifactsDataSource_basic
=== PAUSE TestAccServiceCatalogProvisioningArtifactsDataSource_basic
=== CONT  TestAccServiceCatalogProvisioningArtifactsDataSource_basic
--- PASS: TestAccServiceCatalogProvisioningArtifactsDataSource_basic (36.56s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalog	41.917s
```

**Comment by ewbankkit** [comment]
@silvaalbert Thanks for the contribution :tada: :clap:.

**Pull request merged**
