### PR TITLE
New Resource: aws_cloudfront_key_value_store

### LINKED ISSUE #34512: [New Resource]: Amazon CloudFront KeyValueStore
### Description

> Amazon CloudFront announces general availability of CloudFront KeyValueStore, a global, low-latency, key value datastore.

* [Announcement](https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/)
* [Blog post](https://aws.amazon.com/blogs/aws/introducing-amazon-cloudfront-keyvaluestore-a-low-latency-datastore-for-cloudfront-functions/)

This is the resource creation issue that corresponds to this.

#### Resource(s)

* aws_cloudfront_keyvaluestore

### Potential Terraform Configuration

_No response_

### References

- Added to Go SDK v1.48.2
  - https://pkg.go.dev/github.com/aws/aws-sdk-go@v1.48.2/service/cloudfront
  - https://github.com/aws/aws-sdk-go/releases/tag/v1.48.2

Requires https://github.com/hashicorp/terraform-provider-aws/pull/34514.

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by justinpopa**
### Description
New resource for Cloudfront KeyValueStore

### Relations

Closes #34512.
Closes https://github.com/hashicorp/terraform-provider-aws/pull/34879.

### Output from Acceptance Testing
```console
$ make testacc TESTARGS='-run=TestAccCloudFrontKeyValueStore' PKG=cloudfront
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20  -run=TestAccCloudFrontKeyValueStore -timeout 360m
=== RUN   TestAccCloudFrontKeyValueStore_basic
=== PAUSE TestAccCloudFrontKeyValueStore_basic
=== RUN   TestAccCloudFrontKeyValueStore_disappears
=== PAUSE TestAccCloudFrontKeyValueStore_disappears
=== RUN   TestAccCloudFrontKeyValueStore_Comment
=== PAUSE TestAccCloudFrontKeyValueStore_Comment
=== CONT  TestAccCloudFrontKeyValueStore_basic
=== CONT  TestAccCloudFrontKeyValueStore_Comment
=== CONT  TestAccCloudFrontKeyValueStore_disappears
--- PASS: TestAccCloudFrontKeyValueStore_disappears (10.90s)
--- PASS: TestAccCloudFrontKeyValueStore_basic (13.37s)
--- PASS: TestAccCloudFrontKeyValueStore_Comment (18.17s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront 23.607s
```

### CODE REVIEW

**Comment by brittandeyoung** [comment]
Please add a [per attribute acceptance test](https://hashicorp.github.io/terraform-provider-aws/running-and-writing-acceptance-tests/#per-attribute-acceptance-tests)  the `comment` attribute.

**Comment by brittandeyoung** [comment]
@justinpopa I added a few comments to get you started. You will also need to address the merge conflicts.

**Review by brittandeyoung — COMMENTED** [review]
Here are a few items to get started on

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloudFrontKeyValueStore_' PKG=cloudfront
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudfront/... -v -count 1 -parallel 20  -run=TestAccCloudFrontKeyValueStore_ -timeout 360m
=== RUN   TestAccCloudFrontKeyValueStore_basic
=== PAUSE TestAccCloudFrontKeyValueStore_basic
=== RUN   TestAccCloudFrontKeyValueStore_disappears
=== PAUSE TestAccCloudFrontKeyValueStore_disappears
=== RUN   TestAccCloudFrontKeyValueStore_comment
=== PAUSE TestAccCloudFrontKeyValueStore_comment
=== CONT  TestAccCloudFrontKeyValueStore_basic
=== CONT  TestAccCloudFrontKeyValueStore_comment
=== CONT  TestAccCloudFrontKeyValueStore_disappears
--- PASS: TestAccCloudFrontKeyValueStore_disappears (35.16s)
--- PASS: TestAccCloudFrontKeyValueStore_basic (38.86s)
--- PASS: TestAccCloudFrontKeyValueStore_comment (51.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudfront	62.740s
```

**Comment by ewbankkit** [comment]
@justinpopa Thanks for the contribution :tada: :clap:.

**Pull request merged**
