### PR TITLE
Converts AWS API calls to and provider CRUD calls to `Context`-aware versions

### PR DESCRIPTION
**Pull request by gdavison**
Converts AWS API calls to and provider CRUD calls to `Context`-aware versions.

Required for #26029 implementation

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM (Reviewed all changes outside `internal/service`)

Should we update `skaff` to use context aware functions as well?

**Comment by gdavison** [comment]
I made some changes to the `skaff` templates in https://github.com/hashicorp/terraform-provider-aws/pull/29005/commits/26f786e9c2cacaf77faaeda95bf7e7166ff2c246

**Comment by jar-b** [comment]
> I made some changes to the `skaff` templates in [26f786e](https://github.com/hashicorp/terraform-provider-aws/commit/26f786e9c2cacaf77faaeda95bf7e7166ff2c246)

🤦 github cut off the changes at 3000 files. thanks for clarifying.

**Comment by kamilturek** [comment]
Hey, @gdavison 👋  Impressive work!

Is there a plan to update the docs section about acceptance tests and sweepers to reflect the changes there?
https://github.com/hashicorp/terraform-provider-aws/blob/04fddaa1f28e5cb7fc57417321cd84368b841534/docs/running-and-writing-acceptance-tests.md?plain=1#L200

**Pull request merged**
