### PR TITLE
New resource/aws_account_alternate_contact

### LINKED ISSUE #21118: Handling of alternate contacts for the account
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

New awscli/boto3 handles now alternate contacts for the account https://docs.aws.amazon.com/cli/latest/reference/account/put-alternate-contact.html
I'm creating new accounts often and this is something that needs to be done manually, which is time-consuming and would be cool if somebody could add it Terraform.

### New or Affected Resource(s)

* `aws_account_alternate_contact`

### References

* delete-alternate-contact https://docs.aws.amazon.com/cli/latest/reference/account/delete-alternate-contact.html
* get-alternate-contact https://docs.aws.amazon.com/cli/latest/reference/account/get-alternate-contact.html
* put-alternate-contact https://docs.aws.amazon.com/cli/latest/reference/account/put-alternate-contact.html

[Announcement](https://aws.amazon.com/about-aws/whats-new/2021/10/programmatically-manage-alternate-contacts-aws-accounts/).
[Blog post](https://aws.amazon.com/blogs/mt/programmatically-managing-alternate-contacts-on-member-accounts-with-aws-organizations/).

Requires [AWS SDK v1.40.53](https://github.com/aws/aws-sdk-go/releases/tag/v1.40.53):

* #21108

### PR DESCRIPTION
**Pull request by shedimon**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21118

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by shedimon** [comment]
@ewbankkit @gdavison for some reason my tests are failing locally with a circular dependency I'm struggling to find:
```bash
$ make testacc TESTARGS='-run=TestAccAccountAlternateContact'                                                                                                                         
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/... -v -count 1 -parallel 20 -run=TestAccAccountAlternateContact -timeout 180m
# github.com/hashicorp/terraform-provider-aws/internal/service/account
package github.com/hashicorp/terraform-provider-aws/internal/service/account
	imports github.com/hashicorp/terraform-provider-aws/internal/provider
	imports github.com/hashicorp/terraform-provider-aws/internal/acctest: import cycle not allowed in test
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/account [setup failed]
```
It seems that I'm using the same approach for testing as other services I've checked. Any help appreciated!

**Comment by ewbankkit** [comment]
@shedimon Thanks for the contribution.
The problem with the circular dependency is resolved by changing the acceptance test files' package to `account_test`.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc PKG_NAME=internal/service/account TESTARGS='-run=TestAccAccountAlternateContact_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/account/... -v -count 1 -parallel 20 -run=TestAccAccountAlternateContact_ -timeout 180m
=== RUN   TestAccAccountAlternateContact_basic
--- PASS: TestAccAccountAlternateContact_basic (27.04s)
=== RUN   TestAccAccountAlternateContact_disappears
--- PASS: TestAccAccountAlternateContact_disappears (11.69s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/account	42.243s
```

##### GovCloud

```console
% make testacc PKG_NAME=internal/service/account TESTARGS='-run=TestAccAccountAlternateContact_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/account/... -v -count 1 -parallel 20 -run=TestAccAccountAlternateContact_ -timeout 180m
=== RUN   TestAccAccountAlternateContact_basic
    alternate_contact_test.go:157: skipping acceptance testing: RequestError: send request failed
        caused by: Post "https://account.us-gov-west-1.amazonaws.com/getAlternateContact": dial tcp: lookup account.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAccountAlternateContact_basic (27.30s)
=== RUN   TestAccAccountAlternateContact_disappears
    alternate_contact_test.go:157: skipping acceptance testing: RequestError: send request failed
        caused by: Post "https://account.us-gov-west-1.amazonaws.com/getAlternateContact": dial tcp: lookup account.us-gov-west-1.amazonaws.com: no such host
--- SKIP: TestAccAccountAlternateContact_disappears (22.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/account	52.909s
```

**Comment by mforutan** [comment]
@shedimon @ewbankkit How about the optional `account-id` parameter which is needed to use this in an organization account?

**Comment by shedimon** [comment]
@mforutan To me it looks like two different resources - one to manage alternate contacts in the account it is created, the other one - via the org main AWS account. That's why I've added only one and left the decision on adding the additional optional parameter/additional resource to the AWS Provider team for further addition following their judgement.

**Comment by mforutan** [comment]
@shedimon I am not sure what would be the best implementation but following the aws-sdk, I think we should be able to add support for both scenario in this new resource: https://github.com/hashicorp/terraform-provider-aws/pull/21888

**Pull request merged**
