### PR TITLE
SNS Data Protection Policy

### LINKED ISSUE #29966: [Enhancement]: Support for data protection policy in SNS topic
### Description

Documentation says it's possible to configure data protection policy for SNS but it seems it's not supported yet by the provider

### Affected Resource(s) and/or Data Source(s)

aws_sns_topic

### Potential Terraform Configuration

_No response_

### References

https://docs.aws.amazon.com/sns/latest/dg/sns-message-data-protection-configure.html 

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

Adds a new SNS resource: `aws_sns_topic_data_protection_policy`

### Relations

Closes #29966

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccSNSTopicDataProtectionPolicy_ PKG=sns                                                                             (base) 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 20 -run='TestAccSNSTopicDataProtectionPolicy_'  -timeout 180m
=== RUN   TestAccSNSTopicDataProtectionPolicy_basic
=== PAUSE TestAccSNSTopicDataProtectionPolicy_basic
=== RUN   TestAccSNSTopicDataProtectionPolicy_disappears
=== PAUSE TestAccSNSTopicDataProtectionPolicy_disappears
=== CONT  TestAccSNSTopicDataProtectionPolicy_basic
=== CONT  TestAccSNSTopicDataProtectionPolicy_disappears
--- PASS: TestAccSNSTopicDataProtectionPolicy_disappears (23.86s)
--- PASS: TestAccSNSTopicDataProtectionPolicy_basic (26.61s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sns        26.699s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@bschaatsbergen Please add a CHANGELOG entry.

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen Please add a CHANGELOG entry.

Woops, fixed

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSNSTopicDataProtectionPolicy_' PKG=sns ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sns/... -v -count 1 -parallel 2  -run=TestAccSNSTopicDataProtectionPolicy_ -timeout 180m
=== RUN   TestAccSNSTopicDataProtectionPolicy_basic
=== PAUSE TestAccSNSTopicDataProtectionPolicy_basic
=== RUN   TestAccSNSTopicDataProtectionPolicy_disappears
=== PAUSE TestAccSNSTopicDataProtectionPolicy_disappears
=== CONT  TestAccSNSTopicDataProtectionPolicy_basic
=== CONT  TestAccSNSTopicDataProtectionPolicy_disappears
--- PASS: TestAccSNSTopicDataProtectionPolicy_disappears (16.40s)
--- PASS: TestAccSNSTopicDataProtectionPolicy_basic (18.34s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sns	23.765s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Pull request merged**
