### PR TITLE
New Resource: aws_transfer_tag

### PR DESCRIPTION
**Pull request by kenchan0130**
### Description

New Resource for `aws_transfer_tag`

### Relations

Relates #6956.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/18077.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/24426.

### References

My envisioned use case is https://docs.aws.amazon.com/transfer/latest/userguide/requirements-dns.html

### Output from Acceptance Testing

```sh
$ make testacc TESTS="TestAccTransferTag_" PKG=transfer
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 20 -run='TestAccTransferTag_'  -timeout 180m
=== RUN   TestAccTransferTag_basic
=== PAUSE TestAccTransferTag_basic
=== RUN   TestAccTransferTag_disappears
=== PAUSE TestAccTransferTag_disappears
=== RUN   TestAccTransferTag_value
=== PAUSE TestAccTransferTag_value
=== RUN   TestAccTransferTag_aws
=== PAUSE TestAccTransferTag_aws
=== CONT  TestAccTransferTag_basic
=== CONT  TestAccTransferTag_value
=== CONT  TestAccTransferTag_aws
=== CONT  TestAccTransferTag_disappears
--- PASS: TestAccTransferTag_disappears (188.04s)
--- PASS: TestAccTransferTag_aws (190.10s)
--- PASS: TestAccTransferTag_basic (190.20s)
--- PASS: TestAccTransferTag_value (198.88s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	201.225s
...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@kenchan0130 Could you add a test with the `aws:` tags listed in https://github.com/hashicorp/terraform-provider-aws/issues/18077? Thanks.

**Comment by kenchan0130** [comment]
@ewbankkit 

> Could you add a test with the `aws:` tags listed in #18077? Thanks.

The resource I have created in this case is one that allows you to add, create, update and delete individual tags.
Therefore, I recognize that **list** (https://docs.aws.amazon.com/transfer/latest/userguide/API_ListTagsForResource.html) is outside the scope of this PR.

If you have different perceptions of each other, please let us know your specific intentions.

**Comment by ewbankkit** [comment]
@kenchan0130 Thanks for the contribution :tada: :clap:.
What I needed to do was to tweak the code generator(s) that generate the `UpdateTags` code for each service so as to add a variant that **does not** call `IgnoreAWS()`. We can then manage the `aws:`-prefixed system tags required for custom hostnames.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccTransferTag_' PKG=transfer ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/transfer/... -v -count 1 -parallel 2  -run=TestAccTransferTag_ -timeout 180m
=== RUN   TestAccTransferTag_basic
=== PAUSE TestAccTransferTag_basic
=== RUN   TestAccTransferTag_disappears
=== PAUSE TestAccTransferTag_disappears
=== RUN   TestAccTransferTag_value
=== PAUSE TestAccTransferTag_value
=== RUN   TestAccTransferTag_system
=== PAUSE TestAccTransferTag_system
=== CONT  TestAccTransferTag_basic
=== CONT  TestAccTransferTag_value
--- PASS: TestAccTransferTag_value (179.44s)
=== CONT  TestAccTransferTag_system
--- PASS: TestAccTransferTag_basic (186.63s)
=== CONT  TestAccTransferTag_disappears
--- PASS: TestAccTransferTag_disappears (187.08s)
--- PASS: TestAccTransferTag_system (197.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/transfer	380.545s
```

**Comment by jufemaiz** [comment]
Wow that was fast! 👏🏼

**Pull request merged**
