### PR TITLE
Add Fargate support to Batch compute environments

### LINKED ISSUE #12543: Unmanaged aws_batch_compute_environment should not require compute_resources
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
$ terraform -v
Terraform v0.12.24
+ provider.aws v2.54.0
+ provider.template v2.1.2
```

### Affected Resource(s)

* `aws_batch_compute_environment`

### Terraform Configuration Files

```hcl
resource "aws_batch_compute_environment" "batch" {
  compute_environment_name = "${local.name}_batch_compute_environment"
  service_role             = aws_iam_role.this.arn
  type                     = "UNMANAGED"
  depends_on               = [aws_iam_role_policy_attachment.aws_batch_service_role]
}
```

### Expected Behavior

`terraform apply` should create a batch compute environment. 

### Actual Behavior

```
aws_batch_compute_environment.batch: Modifying... [id=production_batch_compute_environment]

Error: : Error executing request, Exception : At least one compute-resources attribute must be specified, RequestId: 4e2a1592-65bc-462b-a5e0-3c68ba2257b4
	status code: 400, request id: 4e2a1592-65bc-462b-a5e0-3c68ba2257b4

  on main.tf line 153, in resource "aws_batch_compute_environment" "batch":
 153: resource "aws_batch_compute_environment" "batch" {
```

The compute-resources attribute should be optional in an unmanaged compute environment. Per [the docs](https://www.terraform.io/docs/providers/aws/r/batch_compute_environment.html#compute_resources):

> compute_resources - (Optional) Details of the compute resources managed by the compute environment. This parameter is required for managed compute environments. See details below.

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #16592: Support AWS Batch Fargate compute environments
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS Batch now supports using Fargate or Fargate Spot as compute environments instead of a traditional EC2/Spot environment.

### New or Affected Resource(s)

* `aws_batch_compute_environment`
* `aws_batch_job_definition` (`ExecutionRoleArn` parameter becomes required)

### Potential Terraform Configuration

```hcl
resource "aws_batch_compute_environment" "sample" {
  compute_environment_name = "sample"

  compute_resources {
    max_vcpus = 16

    security_group_ids = [
      aws_security_group.sample.id,
    ]

    subnets = [
      aws_subnet.sample.id,
    ]

    type = "FARGATE|FARGATE_SPOT"
  }

  service_role = aws_iam_role.aws_batch_service_role.arn
  type         = "MANAGED"
  depends_on   = [aws_iam_role_policy_attachment.aws_batch_service_role]
}
```

### References

* https://aws.amazon.com/blogs/aws/new-fully-serverless-batch-computing-with-aws-batch-support-for-aws-fargate/
* https://docs.aws.amazon.com/batch/latest/APIReference/API_ComputeResource.html
* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-batch-computeenvironment-computeresources.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/batch/#ComputeResource

### PR DESCRIPTION
**Pull request by gmazelier**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16592
Closes #12543
Requires #16850 to be fully usable

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_batch_compute_environment: add Fargate support (#16819)
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSBatchComputeEnvironment_' ACCTEST_PARALLELISM=4 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 4 -run=TestAccAWSBatchComputeEnvironment_ -timeout 120m
=== RUN   TestAccAWSBatchComputeEnvironment_disappears
=== PAUSE TestAccAWSBatchComputeEnvironment_disappears
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2
=== RUN   TestAccAWSBatchComputeEnvironment_createWithNamePrefix
=== PAUSE TestAccAWSBatchComputeEnvironment_createWithNamePrefix
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2WithTags
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2WithTags
=== RUN   TestAccAWSBatchComputeEnvironment_createSpot
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpot
=== RUN   TestAccAWSBatchComputeEnvironment_createUnmanaged
=== PAUSE TestAccAWSBatchComputeEnvironment_createUnmanaged
=== RUN   TestAccAWSBatchComputeEnvironment_createFargate
=== PAUSE TestAccAWSBatchComputeEnvironment_createFargate
=== RUN   TestAccAWSBatchComputeEnvironment_createFargateSpot
=== PAUSE TestAccAWSBatchComputeEnvironment_createFargateSpot
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_DesiredVcpus_Computed
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_DesiredVcpus_Computed
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
=== RUN   TestAccAWSBatchComputeEnvironment_updateInstanceType
=== PAUSE TestAccAWSBatchComputeEnvironment_updateInstanceType
=== RUN   TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName
=== PAUSE TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
=== RUN   TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
=== PAUSE TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
=== RUN   TestAccAWSBatchComputeEnvironment_launchTemplate
=== PAUSE TestAccAWSBatchComputeEnvironment_launchTemplate
=== RUN   TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
=== PAUSE TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
=== RUN   TestAccAWSBatchComputeEnvironment_createSpotWithAllocationStrategy
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpotWithAllocationStrategy
=== RUN   TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage
=== RUN   TestAccAWSBatchComputeEnvironment_updateState
=== PAUSE TestAccAWSBatchComputeEnvironment_updateState
=== RUN   TestAccAWSBatchComputeEnvironment_Tags
=== PAUSE TestAccAWSBatchComputeEnvironment_Tags
=== CONT  TestAccAWSBatchComputeEnvironment_disappears
=== CONT  TestAccAWSBatchComputeEnvironment_updateInstanceType
=== CONT  TestAccAWSBatchComputeEnvironment_createFargate
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
--- PASS: TestAccAWSBatchComputeEnvironment_disappears (75.10s)
=== CONT  TestAccAWSBatchComputeEnvironment_createFargateSpot
--- PASS: TestAccAWSBatchComputeEnvironment_createFargate (79.64s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2WithTags
--- PASS: TestAccAWSBatchComputeEnvironment_updateInstanceType (142.82s)
=== CONT  TestAccAWSBatchComputeEnvironment_createUnmanaged
--- PASS: TestAccAWSBatchComputeEnvironment_createFargateSpot (76.93s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpot
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithTags (82.89s)
=== CONT  TestAccAWSBatchComputeEnvironment_createWithNamePrefix
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus (175.14s)
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanaged (67.66s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot (71.32s)
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_DesiredVcpus_Computed
--- PASS: TestAccAWSBatchComputeEnvironment_createWithNamePrefix (70.78s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpotWithAllocationStrategy
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2 (71.76s)
=== CONT  TestAccAWSBatchComputeEnvironment_Tags
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithAllocationStrategy (71.32s)
=== CONT  TestAccAWSBatchComputeEnvironment_updateState
--- PASS: TestAccAWSBatchComputeEnvironment_updateState (124.86s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage
--- PASS: TestAccAWSBatchComputeEnvironment_Tags (150.78s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithoutBidPercentage (34.25s)
=== CONT  TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources (32.97s)
=== CONT  TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus (308.59s)
=== CONT  TestAccAWSBatchComputeEnvironment_launchTemplate
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_DesiredVcpus_Computed (326.23s)
=== CONT  TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
--- PASS: TestAccAWSBatchComputeEnvironment_launchTemplate (81.37s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateComputeEnvironmentName (132.80s)
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate (132.74s)
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources (64.94s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       616.239s
```

### CODE REVIEW

**Comment by Skybound1** [comment]
Hi, gave this a test run locally and noticed an issue when updating the max vcpus parameter. The update command issued to AWS includes both max and min vcpus, and AWS responds with a `minvCpus is not applicable for Fargate` error message. 

A hacky fix I quickly tried out on line 456 of `resource_aws_batch_compute_environment.go` that seemed to fix the issue was:

```
if computeResource["type"] != "FARGATE" {
	input.ComputeResources.MinvCpus = aws.Int64(int64(computeResource["min_vcpus"].(int)))
}
```

**Comment by gmazelier** [comment]
@Skybound1 thanks for your feedback!

If I understand well to reproduce what you describe and add some test case. You have an existing Terraform configuration with Batch resources and you want to reconfigure the compute environment to use Fargate, correct? Have you removed `min_vcpus` from your configuration (is it explicitly defined)?

**Comment by Skybound1** [comment]
Yup this was migrating existing Batch to Fargate, and I had removed the `min_vcpus` definition from my terraform. I intercepted the API requests to AWS and noticed it was still sending the parameter with the value of `0`. Skimming through the code, I saw that both `MinvCpus` and `MaxvCpus` were being sent in the update command.

**Comment by gmazelier** [comment]
Hi @Skybound1. Thank you, just made an updated with your suggested fix. Also try to create a test case for this issue but was unable to reproduce your error. When switch from EC2 to Margate type in my tests, I find that the compute environment was deleted and created again, not updated. Can you have a look at ef9e6d8?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSBatchComputeEnvironment_' ACCTEST_PARALLELISM=4 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 4 -run=TestAccAWSBatchComputeEnvironment_ -timeout 180m
=== RUN   TestAccAWSBatchComputeEnvironment_basic
=== PAUSE TestAccAWSBatchComputeEnvironment_basic
=== RUN   TestAccAWSBatchComputeEnvironment_disappears
=== PAUSE TestAccAWSBatchComputeEnvironment_disappears
=== RUN   TestAccAWSBatchComputeEnvironment_NameGenerated
=== PAUSE TestAccAWSBatchComputeEnvironment_NameGenerated
=== RUN   TestAccAWSBatchComputeEnvironment_NamePrefix
=== PAUSE TestAccAWSBatchComputeEnvironment_NamePrefix
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags
=== RUN   TestAccAWSBatchComputeEnvironment_createSpot
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpot
=== RUN   TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage
=== RUN   TestAccAWSBatchComputeEnvironment_createFargate
=== PAUSE TestAccAWSBatchComputeEnvironment_createFargate
=== RUN   TestAccAWSBatchComputeEnvironment_createFargateSpot
=== PAUSE TestAccAWSBatchComputeEnvironment_createFargateSpot
=== RUN   TestAccAWSBatchComputeEnvironment_updateState
=== PAUSE TestAccAWSBatchComputeEnvironment_updateState
=== RUN   TestAccAWSBatchComputeEnvironment_updateServiceRole
=== PAUSE TestAccAWSBatchComputeEnvironment_updateServiceRole
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
=== RUN   TestAccAWSBatchComputeEnvironment_launchTemplate
=== PAUSE TestAccAWSBatchComputeEnvironment_launchTemplate
=== RUN   TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
=== PAUSE TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
=== RUN   TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate
=== PAUSE TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate
=== RUN   TestAccAWSBatchComputeEnvironment_Tags
=== PAUSE TestAccAWSBatchComputeEnvironment_Tags
=== RUN   TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
=== PAUSE TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
=== RUN   TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole
=== CONT  TestAccAWSBatchComputeEnvironment_basic
=== CONT  TestAccAWSBatchComputeEnvironment_Tags
=== CONT  TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole
=== CONT  TestAccAWSBatchComputeEnvironment_createFargateSpot
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole (17.63s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources (14.25s)
=== CONT  TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
--- PASS: TestAccAWSBatchComputeEnvironment_createFargateSpot (40.50s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags
--- PASS: TestAccAWSBatchComputeEnvironment_basic (46.63s)
=== CONT  TestAccAWSBatchComputeEnvironment_createFargate
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources (31.85s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage
--- PASS: TestAccAWSBatchComputeEnvironment_createFargate (35.11s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpot
--- PASS: TestAccAWSBatchComputeEnvironment_Tags (82.20s)
=== CONT  TestAccAWSBatchComputeEnvironment_NamePrefix
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage (36.36s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2 (34.87s)
=== CONT  TestAccAWSBatchComputeEnvironment_NameGenerated
--- PASS: TestAccAWSBatchComputeEnvironment_NamePrefix (64.30s)
=== CONT  TestAccAWSBatchComputeEnvironment_disappears
--- PASS: TestAccAWSBatchComputeEnvironment_NameGenerated (45.19s)
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
--- PASS: TestAccAWSBatchComputeEnvironment_disappears (35.02s)
=== CONT  TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags (149.31s)
=== CONT  TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate (55.25s)
=== CONT  TestAccAWSBatchComputeEnvironment_launchTemplate
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate (60.60s)
=== CONT  TestAccAWSBatchComputeEnvironment_updateServiceRole
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus (71.12s)
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
--- PASS: TestAccAWSBatchComputeEnvironment_launchTemplate (36.67s)
=== CONT  TestAccAWSBatchComputeEnvironment_updateState
--- PASS: TestAccAWSBatchComputeEnvironment_updateServiceRole (63.10s)
--- PASS: TestAccAWSBatchComputeEnvironment_updateState (51.28s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus (194.12s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot (459.77s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	544.574s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSBatchComputeEnvironment_' ACCTEST_PARALLELISM=4
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 4 -run=TestAccAWSBatchComputeEnvironment_ -timeout 180m
=== RUN   TestAccAWSBatchComputeEnvironment_basic
=== PAUSE TestAccAWSBatchComputeEnvironment_basic
=== RUN   TestAccAWSBatchComputeEnvironment_disappears
=== PAUSE TestAccAWSBatchComputeEnvironment_disappears
=== RUN   TestAccAWSBatchComputeEnvironment_NameGenerated
=== PAUSE TestAccAWSBatchComputeEnvironment_NameGenerated
=== RUN   TestAccAWSBatchComputeEnvironment_NamePrefix
=== PAUSE TestAccAWSBatchComputeEnvironment_NamePrefix
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags
=== RUN   TestAccAWSBatchComputeEnvironment_createSpot
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpot
=== RUN   TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage
=== RUN   TestAccAWSBatchComputeEnvironment_createFargate
=== PAUSE TestAccAWSBatchComputeEnvironment_createFargate
=== RUN   TestAccAWSBatchComputeEnvironment_createFargateSpot
=== PAUSE TestAccAWSBatchComputeEnvironment_createFargateSpot
=== RUN   TestAccAWSBatchComputeEnvironment_updateState
=== PAUSE TestAccAWSBatchComputeEnvironment_updateState
=== RUN   TestAccAWSBatchComputeEnvironment_updateServiceRole
=== PAUSE TestAccAWSBatchComputeEnvironment_updateServiceRole
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
=== RUN   TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
=== PAUSE TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
=== RUN   TestAccAWSBatchComputeEnvironment_launchTemplate
=== PAUSE TestAccAWSBatchComputeEnvironment_launchTemplate
=== RUN   TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
=== PAUSE TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
=== RUN   TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate
=== PAUSE TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate
=== RUN   TestAccAWSBatchComputeEnvironment_Tags
=== PAUSE TestAccAWSBatchComputeEnvironment_Tags
=== RUN   TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
=== PAUSE TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
=== RUN   TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
=== PAUSE TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
=== RUN   TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole
=== PAUSE TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole
=== CONT  TestAccAWSBatchComputeEnvironment_basic
=== CONT  TestAccAWSBatchComputeEnvironment_updateServiceRole
=== CONT  TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2WithoutComputeResources (18.81s)
=== CONT  TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources
--- PASS: TestAccAWSBatchComputeEnvironment_createSpotWithoutIamFleetRole (19.08s)
=== CONT  TestAccAWSBatchComputeEnvironment_Tags
--- PASS: TestAccAWSBatchComputeEnvironment_basic (35.98s)
=== CONT  TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate
--- PASS: TestAccAWSBatchComputeEnvironment_createUnmanagedWithComputeResources (33.86s)
=== CONT  TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate
--- PASS: TestAccAWSBatchComputeEnvironment_updateServiceRole (59.89s)
=== CONT  TestAccAWSBatchComputeEnvironment_launchTemplate
--- PASS: TestAccAWSBatchComputeEnvironment_Tags (76.47s)
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus
--- PASS: TestAccAWSBatchComputeEnvironment_launchTemplate (38.28s)
=== CONT  TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateSecurityGroupsAndSubnets_Fargate (63.88s)
=== CONT  TestAccAWSBatchComputeEnvironment_NamePrefix
--- PASS: TestAccAWSBatchComputeEnvironment_UpdateLaunchTemplate (66.99s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags
--- PASS: TestAccAWSBatchComputeEnvironment_NamePrefix (38.53s)
=== CONT  TestAccAWSBatchComputeEnvironment_createEc2
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2 (38.38s)
=== CONT  TestAccAWSBatchComputeEnvironment_createFargateSpot
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MaxVcpus (83.60s)
=== CONT  TestAccAWSBatchComputeEnvironment_updateState
--- PASS: TestAccAWSBatchComputeEnvironment_createFargateSpot (35.86s)
=== CONT  TestAccAWSBatchComputeEnvironment_NameGenerated
--- PASS: TestAccAWSBatchComputeEnvironment_updateState (55.68s)
=== CONT  TestAccAWSBatchComputeEnvironment_createFargate
--- PASS: TestAccAWSBatchComputeEnvironment_NameGenerated (35.91s)
=== CONT  TestAccAWSBatchComputeEnvironment_disappears
--- PASS: TestAccAWSBatchComputeEnvironment_createEc2_DesiredVcpus_Ec2KeyPair_ImageId_ComputeResourcesTags (139.26s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage
--- PASS: TestAccAWSBatchComputeEnvironment_createFargate (37.36s)
=== CONT  TestAccAWSBatchComputeEnvironment_createSpot
--- PASS: TestAccAWSBatchComputeEnvironment_disappears (34.12s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot_AllocationStrategy_BidPercentage (39.18s)
--- PASS: TestAccAWSBatchComputeEnvironment_ComputeResources_MinVcpus (200.75s)
--- PASS: TestAccAWSBatchComputeEnvironment_createSpot (455.75s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	730.891s
```

**Comment by ewbankkit** [comment]
@gmazelier Thanks for the contribution :clap:.
I went ahead and pushed some changes to your fork to get this released sooner.
The only practitioner-noticeable addition is that `security_group_ids` and `subnets` can be updated for Fargate compute resources without requiring a destruction and creation of the compute environment.

**Pull request merged**
