### PR TITLE
f-aws_msk_replicator:Argument for Replication starting position

### LINKED ISSUE #36850: [Enhancement]: Argument for Replication starting position in `aws_msk_replicator`
### Terraform Core Version

1.5.7

### AWS Provider Version

5.44.0

### Affected Resource(s)

aws_msk_replicator

### Expected Behavior

We are expecting the ability to customize *Replication starting position*, either EARLIEST or LATEST

### Actual Behavior

*Replication starting position* value is not overridable, forcing and defaulting the value to LATEST

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

image

### PR DESCRIPTION
**Pull request by nikhil-goenka**
### Relations

Closes #36850

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccKafkaReplicator_basic PKG=kafka       
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaReplicator_basic'  -timeout 360m
=== RUN   TestAccKafkaReplicator_basic
=== PAUSE TestAccKafkaReplicator_basic
=== CONT  TestAccKafkaReplicator_basic
--- PASS: TestAccKafkaReplicator_basic (6256.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	6272.142s

...
```

### CODE REVIEW

**Comment by michaelgeorgeattard** [comment]
Hello! Any updates on this PR?

**Comment by sappusaketh** [comment]
Any updates? we are waiting for this feature

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccKafkaReplicator_basic\|TestAccKafkaReplicator_update' PKG=kafka
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/kafka/... -v -count 1 -parallel 20  -run=TestAccKafkaReplicator_basic\|TestAccKafkaReplicator_update -timeout 360m
=== RUN   TestAccKafkaReplicator_basic
=== PAUSE TestAccKafkaReplicator_basic
=== RUN   TestAccKafkaReplicator_update
=== PAUSE TestAccKafkaReplicator_update
=== CONT  TestAccKafkaReplicator_basic
=== CONT  TestAccKafkaReplicator_update
--- PASS: TestAccKafkaReplicator_basic (7163.25s)
--- PASS: TestAccKafkaReplicator_update (7957.54s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	7962.227s
```

**Comment by ewbankkit** [comment]
@nikhil-goenka Thanks for the contribution :tada: :clap:.

**Pull request merged**
