### PR TITLE
add managed_instance_scaling to sagemaker endpoint config production_variants

### LINKED ISSUE #35011: [Enhancement]: one to one mapping with sagemaker jumpstart model creation
### Terraform Core Version

1.6.5

### AWS Provider Version

5.31.0

### Affected Resource(s)

Sagemaker Engpoint config.

### Expected Behavior

When creating a jumpstart endpoint through the SageMaker studio, you can create a LLM (like mistral) on an managed endpoint. There are few hacks you have to do to get this to work with Terraform because the values are these jumpstart images and s3 locations are not published. But by deploying a model on studio, then using `aws cli` to get the model's `primary_container.environment` and `model_data_source`, terraform can copy it.

The issue is that the `aws_sagemaker_endpoint_configuration` cannot support the configuration that sagemaker studio creates by default.

Here is the described endpoint configuration made by studio:

```
{
    "EndpointConfigName": "jumpstart-mistral-1703083557499",
    "EndpointConfigArn": "arn:aws:sagemaker:us-east-1:XXXX:endpoint-config/jumpstart-mistral-1703083557499",
    "ProductionVariants": [
        {
            "VariantName": "AllTraffic",
            "InitialInstanceCount": 1,
            "InstanceType": "ml.g5.2xlarge",
            "ManagedInstanceScaling": {
                "Status": "ENABLED",
                "MinInstanceCount": 1,
                "MaxInstanceCount": 20
            }
        }
    ],
    "CreationTime": "2023-12-20T14:45:57.903000+00:00",
    "ExecutionRoleArn": "arn:aws:iam::XXXX:role/service-role/AmazonSageMaker-ExecutionRole-20231215T143587",
    "EnableNetworkIsolation": true
}
```

### Actual Behavior

With terraform, it is not possible to specify `ManagedInstanceScaling`:

```
 "ManagedInstanceScaling": {
                "Status": "ENABLED",
                "MinInstanceCount": 1,
                "MaxInstanceCount": 20
            }
```

It is also not possible to specify `NetworkIsolation`

## This is the endpoint configuration created by terraform
```
{
    "EndpointConfigName": "chat-bot-sagemaker-config",
    "EndpointConfigArn": "arn:aws:sagemaker:us-east-1:XXX:endpoint-config/chat-bot-sagemaker-config",
    "ProductionVariants": [
        {
            "VariantName": "mistral-7b-variant",
            "ModelName": "llm-mistral-7b-instruct-model",
            "InitialInstanceCount": 1,
            "InstanceType": "ml.m5.2xlarge",
            "InitialVariantWeight": 1.0,
            "EnableSSMAccess": false
        }
    ],
    "CreationTime": "2023-12-19T22:54:12.219000+00:00",
    "EnableNetworkIsolation": false
}
```

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
# README
# these values for environment and model data source were found by deploying a 
# JumpStart endpoint with sagemaker studio then copying the values on that model 
# using `aws sagemaker describe-model --model-name your_model_name`
# Without these, the endpoint will fail to deploy. You can check cloudwatch logs for the reason
# The standard way to deploy a endpoint is with boto3.sagemaker or python CDK.
# There are no resources online where to find the env and model data source info.
resource "aws_sagemaker_model" "mistral_sagemaker_model" {
  name               = "llm-mistral-7b-instruct-model"
  execution_role_arn = aws_iam_role.sagemaker_trust_role.arn

  primary_container {
    image = var.sagemaker_mistral_public_image
    mode  = "SingleModel"
    environment = {
      ENDPOINT_SERVER_TIMEOUT        = "3600"
      HF_MODEL_ID                    = "/opt/ml/model"
      MAX_BATCH_PREFILL_TOKENS       = "8191"
      MAX_INPUT_LENGTH               = "8191"
      MAX_TOTAL_TOKENS               = "8192"
      MODEL_CACHE_ROOT               = "/opt/ml/model"
      SAGEMAKER_ENV                  = "1"
      SAGEMAKER_MODEL_SERVER_WORKERS = "1"
      SAGEMAKER_PROGRAM              = "inference.py"
      SM_NUM_GPUS                    = "1"
    }

    model_data_source {
      s3_data_source {
        s3_uri = "s3://jumpstart-cache-prod-us-east-1/huggingface-llm/huggingface-llm-mistral-7b-instruct/artifacts/inference-prepack/v1.0.0/",
        s3_data_type = "S3Prefix"
        compression_type = "None"
      }
    }
  }

  tags = {
    Application = var.app_name

    ENDPOINT_SERVER_TIMEOUT        = "3600"
    HF_MODEL_ID                    = "/opt/ml/model"
    MAX_BATCH_PREFILL_TOKENS       = "8191"
    MAX_INPUT_LENGTH               = "8191"
    MAX_TOTAL_TOKENS               = "8192"
    MODEL_CACHE_ROOT               = "/opt/ml/model"
    SAGEMAKER_ENV                  = "1"
    SAGEMAKER_MODEL_SERVER_WORKERS = "1"
    SAGEMAKER_PROGRAM              = "inference.py"
    SM_NUM_GPUS                    = "1"
  }
}

resource "aws_sagemaker_endpoint_configuration" "config" {
  name = "chat-bot-sagemaker-config"

  production_variants {
    variant_name           = "mistral-7b-variant"
    model_name             = aws_sagemaker_model.mistral_sagemaker_model.name
    initial_instance_count = 1
    instance_type          = var.sagemaker_inference_compute_size
  }
  net

  tags = {
    Application = var.app_name
  }
}

resource "aws_sagemaker_endpoint" "endpoint" {
  name                 = "sagemaker-mistral-inference-ep"
  endpoint_config_name = aws_sagemaker_endpoint_configuration.config.name

  tags = {
    Application = var.app_name
  }
}

resource "aws_iam_role" "sagemaker_trust_role" {
  name = "sagemaker_role"

  assume_role_policy = <<-EOF
  {
    "Version": "2012-10-17",
    "Statement": [
      {
        "Action": "sts:AssumeRole",
        "Principal": {
          "Service": "sagemaker.amazonaws.com"
        },
        "Effect": "Allow",
        "Sid": ""
      }
    ]
  }
  EOF

  tags = {
    Application = var.app_name
  }
}

resource "aws_iam_role_policy_attachment" "sagemaker_full_access" {
  role       = aws_iam_role.sagemaker_trust_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonSageMakerFullAccess"
}

resource "aws_iam_role_policy_attachment" "s3_read_write_access" {
  role       = aws_iam_role.sagemaker_trust_role.name
  policy_arn = "arn:aws:iam::aws:policy/AmazonS3FullAccess"
}

```

### Steps to Reproduce

run standard terraform `init`, `plan`, and `apply` and check the comparison between the endpoint configurations deployed by terraform and SageMaker studio UI.

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by deepakbshetty**
### Description
Add managed_instance_scaling to sagemaker endpoint config production_variants

### Relations
Fixes #35011

### References

[Create Endpint Config API](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_CreateEndpointConfig.html)

### Output from Acceptance Testing
```
$ make testacc TESTS=TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling'  -timeout 360m
=== RUN   TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== PAUSE TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== CONT  TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
--- PASS: TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling (108.90s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  140.715s

```

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by DrFaust92** [comment]
[deepakbshetty](https://github.com/deepakbshetty) can you add changelog entry?

**Comment by deepakbshetty** [comment]
Hi @DrFaust92 Changelog added and rebased.

**Review by DrFaust92 — CHANGES_REQUESTED** [review]
Missing tests

**Comment by deepakbshetty** [comment]
> Missing tests
I am struggling to find a jumpstart model that actually supports managed instance scaling.  The model specified in original issue does not.

Any advice is appreciated

`endpoint_configuration_test.go:162: Step 1/3 error: Error running apply: exit status 1

    Error: creating SageMaker Endpoint Configuration: ValidationException: ManagedInstanceScaling is not supported with the given EndpointConfig setup.
            status code: 400, request id: 32f1694c-6389-43f9-9bea-5245a1497bfd

      with aws_sagemaker_endpoint_configuration.test,
      on terraform_plugin_test.tf line 54, in resource "aws_sagemaker_endpoint_configuration" "test":
      54: resource "aws_sagemaker_endpoint_configuration" "test" {`

**Comment by DrFaust92** [comment]
[deepakbshetty](https://github.com/deepakbshetty) Thats tricky, ill see what i can find

**Comment by deepakbshetty** [comment]
Hi @DrFaust92 

Managed to add test now. All checks passing. Kindly review.
```
$ make testacc TESTS=TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling PKG=sagemaker
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/sagemaker/... -v -count 1 -parallel 20 -run='TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling'  -timeout 360m
=== RUN   TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== PAUSE TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== CONT  TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
--- PASS: TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling (108.90s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker  140.715s
```

**Review by DrFaust92 — APPROVED** [review]

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccSageMakerEndpointConfiguration_' PKG=sagemaker ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.0 test ./internal/service/sagemaker/... -v -count 1 -parallel 3  -run=TestAccSageMakerEndpointConfiguration_ -timeout 720m
=== RUN   TestAccSageMakerEndpointConfiguration_basic
=== PAUSE TestAccSageMakerEndpointConfiguration_basic
=== RUN   TestAccSageMakerEndpointConfiguration_nameGenerated
=== PAUSE TestAccSageMakerEndpointConfiguration_nameGenerated
=== RUN   TestAccSageMakerEndpointConfiguration_namePrefix
=== PAUSE TestAccSageMakerEndpointConfiguration_namePrefix
=== RUN   TestAccSageMakerEndpointConfiguration_shadowProductionVariants
=== PAUSE TestAccSageMakerEndpointConfiguration_shadowProductionVariants
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_routing
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_routing
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_serverless
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_serverless
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_ami
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_ami
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_serverlessProvisionedConcurrency
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_serverlessProvisionedConcurrency
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_initialVariantWeight
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_initialVariantWeight
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_acceleratorType
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_acceleratorType
=== RUN   TestAccSageMakerEndpointConfiguration_ProductionVariants_variantNameGenerated
=== PAUSE TestAccSageMakerEndpointConfiguration_ProductionVariants_variantNameGenerated
=== RUN   TestAccSageMakerEndpointConfiguration_kmsKeyID
=== PAUSE TestAccSageMakerEndpointConfiguration_kmsKeyID
=== RUN   TestAccSageMakerEndpointConfiguration_tags
=== PAUSE TestAccSageMakerEndpointConfiguration_tags
=== RUN   TestAccSageMakerEndpointConfiguration_dataCapture
=== PAUSE TestAccSageMakerEndpointConfiguration_dataCapture
=== RUN   TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
=== PAUSE TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
=== RUN   TestAccSageMakerEndpointConfiguration_disappears
=== PAUSE TestAccSageMakerEndpointConfiguration_disappears
=== RUN   TestAccSageMakerEndpointConfiguration_async
=== PAUSE TestAccSageMakerEndpointConfiguration_async
=== RUN   TestAccSageMakerEndpointConfiguration_async_includeInference
=== PAUSE TestAccSageMakerEndpointConfiguration_async_includeInference
=== RUN   TestAccSageMakerEndpointConfiguration_async_kms
=== PAUSE TestAccSageMakerEndpointConfiguration_async_kms
=== RUN   TestAccSageMakerEndpointConfiguration_Async_notif
=== PAUSE TestAccSageMakerEndpointConfiguration_Async_notif
=== RUN   TestAccSageMakerEndpointConfiguration_Async_client
=== PAUSE TestAccSageMakerEndpointConfiguration_Async_client
=== RUN   TestAccSageMakerEndpointConfiguration_Async_client_failurePath
=== PAUSE TestAccSageMakerEndpointConfiguration_Async_client_failurePath
=== RUN   TestAccSageMakerEndpointConfiguration_upgradeToEnableSSMAccess
=== PAUSE TestAccSageMakerEndpointConfiguration_upgradeToEnableSSMAccess
=== RUN   TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== PAUSE TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
=== CONT  TestAccSageMakerEndpointConfiguration_basic
=== CONT  TestAccSageMakerEndpointConfiguration_tags
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_ami
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_ami (24.16s)
=== CONT  TestAccSageMakerEndpointConfiguration_kmsKeyID
--- PASS: TestAccSageMakerEndpointConfiguration_basic (28.43s)
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_variantNameGenerated
--- PASS: TestAccSageMakerEndpointConfiguration_tags (38.36s)
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_acceleratorType
--- PASS: TestAccSageMakerEndpointConfiguration_kmsKeyID (19.32s)
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_initialVariantWeight
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_variantNameGenerated (21.57s)
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_serverlessProvisionedConcurrency
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_acceleratorType (24.11s)
=== CONT  TestAccSageMakerEndpointConfiguration_async_kms
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_initialVariantWeight (21.35s)
=== CONT  TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_serverlessProvisionedConcurrency (19.70s)
=== CONT  TestAccSageMakerEndpointConfiguration_upgradeToEnableSSMAccess
--- PASS: TestAccSageMakerEndpointConfiguration_async_kms (26.76s)
=== CONT  TestAccSageMakerEndpointConfiguration_Async_client_failurePath
--- PASS: TestAccSageMakerEndpointConfiguration_productionVariantsManagedInstanceScaling (27.57s)
=== CONT  TestAccSageMakerEndpointConfiguration_Async_client
--- PASS: TestAccSageMakerEndpointConfiguration_Async_client_failurePath (20.67s)
=== CONT  TestAccSageMakerEndpointConfiguration_Async_notif
--- PASS: TestAccSageMakerEndpointConfiguration_upgradeToEnableSSMAccess (41.96s)
=== CONT  TestAccSageMakerEndpointConfiguration_disappears
--- PASS: TestAccSageMakerEndpointConfiguration_Async_client (22.47s)
=== CONT  TestAccSageMakerEndpointConfiguration_async_includeInference
--- PASS: TestAccSageMakerEndpointConfiguration_Async_notif (25.39s)
=== CONT  TestAccSageMakerEndpointConfiguration_async
--- PASS: TestAccSageMakerEndpointConfiguration_disappears (24.22s)
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_serverless
--- PASS: TestAccSageMakerEndpointConfiguration_async_includeInference (22.23s)
=== CONT  TestAccSageMakerEndpointConfiguration_ProductionVariants_routing
--- PASS: TestAccSageMakerEndpointConfiguration_async (21.01s)
=== CONT  TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_serverless (21.18s)
=== CONT  TestAccSageMakerEndpointConfiguration_dataCapture
--- PASS: TestAccSageMakerEndpointConfiguration_ProductionVariants_routing (21.69s)
=== CONT  TestAccSageMakerEndpointConfiguration_namePrefix
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture_inputAndOutput (22.28s)
=== CONT  TestAccSageMakerEndpointConfiguration_nameGenerated
--- PASS: TestAccSageMakerEndpointConfiguration_namePrefix (21.61s)
=== CONT  TestAccSageMakerEndpointConfiguration_shadowProductionVariants
--- PASS: TestAccSageMakerEndpointConfiguration_dataCapture (27.16s)
--- PASS: TestAccSageMakerEndpointConfiguration_nameGenerated (24.36s)
--- PASS: TestAccSageMakerEndpointConfiguration_shadowProductionVariants (24.81s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	209.998s
```

**Comment by ewbankkit** [comment]
@deepakbshetty Thanks for the contribution :tada: :clap:.

**Pull request merged**
