### PR TITLE
r/aws_sesv2_configuration_set: new resource

### PR DESCRIPTION
**Pull request by kamilturek**
### Description

This PR adds the `aws_sesv2_configuration_set` resource.

### Relations

Relates #26796.

### References

https://docs.aws.amazon.com/ses/latest/APIReference-V2/Welcome.html

### Output from Acceptance Testing

```
$ make testacc PKG=sesv2 TESTS="TestAccSESV2ConfigurationSet_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20 -run='TestAccSESV2ConfigurationSet_'  -timeout 180m
=== RUN   TestAccSESV2ConfigurationSet_basic
=== PAUSE TestAccSESV2ConfigurationSet_basic
=== RUN   TestAccSESV2ConfigurationSet_disappears
=== PAUSE TestAccSESV2ConfigurationSet_disappears
=== RUN   TestAccSESV2ConfigurationSet_tlsPolicy
=== PAUSE TestAccSESV2ConfigurationSet_tlsPolicy
=== RUN   TestAccSESV2ConfigurationSet_reputationMetricsEnabled
=== PAUSE TestAccSESV2ConfigurationSet_reputationMetricsEnabled
=== RUN   TestAccSESV2ConfigurationSet_sendingEnabled
=== PAUSE TestAccSESV2ConfigurationSet_sendingEnabled
=== RUN   TestAccSESV2ConfigurationSet_suppressedReasons
=== PAUSE TestAccSESV2ConfigurationSet_suppressedReasons
=== RUN   TestAccSESV2ConfigurationSet_tags
=== PAUSE TestAccSESV2ConfigurationSet_tags
=== CONT  TestAccSESV2ConfigurationSet_basic
=== CONT  TestAccSESV2ConfigurationSet_sendingEnabled
=== CONT  TestAccSESV2ConfigurationSet_tags
=== CONT  TestAccSESV2ConfigurationSet_suppressedReasons
=== CONT  TestAccSESV2ConfigurationSet_disappears
=== CONT  TestAccSESV2ConfigurationSet_tlsPolicy
=== CONT  TestAccSESV2ConfigurationSet_reputationMetricsEnabled
--- PASS: TestAccSESV2ConfigurationSet_disappears (23.22s)
--- PASS: TestAccSESV2ConfigurationSet_basic (30.96s)
--- PASS: TestAccSESV2ConfigurationSet_reputationMetricsEnabled (51.09s)
--- PASS: TestAccSESV2ConfigurationSet_suppressedReasons (51.16s)
--- PASS: TestAccSESV2ConfigurationSet_sendingEnabled (51.63s)
--- PASS: TestAccSESV2ConfigurationSet_tlsPolicy (51.74s)
--- PASS: TestAccSESV2ConfigurationSet_tags (67.80s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sesv2      69.548s
```

### CODE REVIEW

**Comment by kamilturek** [comment]
Hey @ewbankkit, really weird. I just tried again and it passes for me.
```
$ make testacc TESTARGS='-run=TestAccSESV2ConfigurationSet_basic' PKG=sesv2 ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 3  -run=TestAccSESV2ConfigurationSet_basic -timeout 180m
=== RUN   TestAccSESV2ConfigurationSet_basic
=== PAUSE TestAccSESV2ConfigurationSet_basic
=== CONT  TestAccSESV2ConfigurationSet_basic
--- PASS: TestAccSESV2ConfigurationSet_basic (37.09s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sesv2      38.829s
```

From the error you got looks like it was an internal error on AWS side. Can you please try running these tests again?

**Comment by kamilturek** [comment]
Hey @ewbankkit, do you have any updates? Let me know if there's anything I can do to resolve the issues 👍

**Comment by jar-b** [comment]
Hey @kamilturek - this looks great. Just made a couple small changes:

- added changelog entry
- changed the ARN generation to use `ses` instead of `sesv2`. The [SES V2 IAM docs](https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonsimpleemailservicev2.html#amazonsimpleemailservicev2-configuration-set) use the former in the `configuration_set` ARN format, and it resolved acceptance test errors Kit and I were observing.

```console
$ aws sesv2 list-tags-for-resource --resource-arn arn:aws:sesv2:us-west-2:012345678901:configuration-set/jb-test

An error occurred (InternalFailure) when calling the ListTagsForResource operation (reached max retries: 2): None

$ aws sesv2 list-tags-for-resource --resource-arn arn:aws:ses:us-west-2:012345678901:configuration-set/jb-test
{
    "Tags": []
}
```

**Comment by jar-b** [comment]
```console
➜  make testacc PKG=sesv2 TESTS="TestAccSESV2ConfigurationSet_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sesv2/... -v -count 1 -parallel 20 -run='TestAccSESV2ConfigurationSet_'  -timeout 180m
=== RUN   TestAccSESV2ConfigurationSet_basic
=== PAUSE TestAccSESV2ConfigurationSet_basic
=== RUN   TestAccSESV2ConfigurationSet_disappears
=== PAUSE TestAccSESV2ConfigurationSet_disappears
=== RUN   TestAccSESV2ConfigurationSet_tlsPolicy
=== PAUSE TestAccSESV2ConfigurationSet_tlsPolicy
=== RUN   TestAccSESV2ConfigurationSet_reputationMetricsEnabled
=== PAUSE TestAccSESV2ConfigurationSet_reputationMetricsEnabled
=== RUN   TestAccSESV2ConfigurationSet_sendingEnabled
=== PAUSE TestAccSESV2ConfigurationSet_sendingEnabled
=== RUN   TestAccSESV2ConfigurationSet_suppressedReasons
=== PAUSE TestAccSESV2ConfigurationSet_suppressedReasons
=== RUN   TestAccSESV2ConfigurationSet_tags
=== PAUSE TestAccSESV2ConfigurationSet_tags
=== CONT  TestAccSESV2ConfigurationSet_basic
=== CONT  TestAccSESV2ConfigurationSet_sendingEnabled
=== CONT  TestAccSESV2ConfigurationSet_tlsPolicy
=== CONT  TestAccSESV2ConfigurationSet_disappears
=== CONT  TestAccSESV2ConfigurationSet_tags
=== CONT  TestAccSESV2ConfigurationSet_suppressedReasons
=== CONT  TestAccSESV2ConfigurationSet_reputationMetricsEnabled
--- PASS: TestAccSESV2ConfigurationSet_disappears (14.49s)
--- PASS: TestAccSESV2ConfigurationSet_basic (19.43s)
--- PASS: TestAccSESV2ConfigurationSet_suppressedReasons (30.76s)
--- PASS: TestAccSESV2ConfigurationSet_sendingEnabled (30.95s)
--- PASS: TestAccSESV2ConfigurationSet_tlsPolicy (31.07s)
--- PASS: TestAccSESV2ConfigurationSet_reputationMetricsEnabled (31.09s)
--- PASS: TestAccSESV2ConfigurationSet_tags (42.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/sesv2      44.613s
```

**Comment by kamilturek** [comment]
Hey @jar-b. Perfect, many thanks for handling that! 🙌

**Review by jar-b — APPROVED** [review]
LGTM - thanks for your contribution! 🚀

**Pull request merged**
