### PR TITLE
New resource: aws_elasticache_global_replication_group

### PR DESCRIPTION
**Pull request by MqllR**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #12708

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
New Resource: aws_elasticache_global_replication_group
```

Output from acceptance testing:

```
make testacc TESTARGS='-run=TestAccAWSElasticacheGlobalReplicationGroup'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheGlobalReplicationGroup -timeout 120m
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_basic
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_basic
=== RUN   TestAccAWSElasticacheGlobalReplicationGroup_disappears
=== PAUSE TestAccAWSElasticacheGlobalReplicationGroup_disappears
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_basic
=== CONT  TestAccAWSElasticacheGlobalReplicationGroup_disappears
    resource_aws_elasticache_global_replication_group_test.go:114: [INFO] Got non-empty plan, as expected
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_basic (970.16s)
--- PASS: TestAccAWSElasticacheGlobalReplicationGroup_disappears (987.04s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       987.066s
```

Note:
In order to get a working ElastiCache Global Datastore, we should refine the resource elasticache_replication_group. Actually, to associate an elasticache_replication_group, the only parameter accepted is a global_replication_group_id. The change is pretty big on the resource elasticache_replication_group, so what do you recommend? Treating this in another PR?

### CODE REVIEW

**Comment by fphilippon** [comment]
Hello, any idea when this wonderful PR will be merged?
Thanks!

**Comment by ppapishe** [comment]
is there any way we can get some traction on this PR?

**Review by gdavison — COMMENTED** [review]
Thanks for the PR, @MqllR. This is a great start. I've completed the initial support in #17615

**Comment by MqllR** [comment]
Thanks @gdavison for your review. Let me know if I can help or review something :)

**Pull request merged**
