### PR TITLE
Add Multi-AZ support for RDS clusters

### LINKED ISSUE #23475: aws_rds_cluster add new multi-AZ cluster deployment options
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add the ability to provision Multi-AZ cluster deployment MySQL or PostgreSQL instances.

It looks like aws-sdk-go added this in `1.43.9`.

```
To create a Multi-AZ DB cluster by using the RDS API, call the [CreateDBCluster](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CreateDBCluster.html) operation. Specify the DBClusterIdentifier. For the Engine parameter, specify either mysql or postgresql.
```

### New or Affected Resource(s)

aws_rds_cluster

### Potential Terraform Configuration

```hcl
resource "aws_rds_cluster" "asdf" {
  # ....
  engine = "postgres"
  # ....
}
```

### References
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/create-multi-az-db-cluster.html
* https://aws.amazon.com/blogs/aws/amazon-rds-multi-az-db-cluster/
* https://github.com/aws/aws-sdk-go/commit/4adef3588ff234c55aa0afb9cb33772660906758

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23475

Output from acceptance testing: **(I ran the new acceptance tests + a 'TestAccRDSCluster_basic' Aurora acceptance test)**

```
make testacc TESTS=TestAccRDSCluster_ PKG=rds                                                                                                                (base) 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_'  -timeout 180m
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN   TestAccRDSCluster_allowMajorVersionUpgrade
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgrade
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
=== RUN   TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== PAUSE TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
=== RUN   TestAccRDSCluster_onlyMajorVersion
=== PAUSE TestAccRDSCluster_onlyMajorVersion
=== RUN   TestAccRDSCluster_availabilityZones
=== PAUSE TestAccRDSCluster_availabilityZones
=== RUN   TestAccRDSCluster_storageType
=== PAUSE TestAccRDSCluster_storageType
=== RUN   TestAccRDSCluster_allocatedStorage
=== PAUSE TestAccRDSCluster_allocatedStorage
=== RUN   TestAccRDSCluster_iops
=== PAUSE TestAccRDSCluster_iops
=== RUN   TestAccRDSCluster_dbClusterInstanceClass
=== PAUSE TestAccRDSCluster_dbClusterInstanceClass
=== RUN   TestAccRDSCluster_backtrackWindow
=== PAUSE TestAccRDSCluster_backtrackWindow
=== RUN   TestAccRDSCluster_clusterIdentifierPrefix
=== PAUSE TestAccRDSCluster_clusterIdentifierPrefix
=== RUN   TestAccRDSCluster_dbSubnetGroupName
=== PAUSE TestAccRDSCluster_dbSubnetGroupName
=== RUN   TestAccRDSCluster_s3Restore
=== PAUSE TestAccRDSCluster_s3Restore
=== RUN   TestAccRDSCluster_pointInTimeRestore
=== PAUSE TestAccRDSCluster_pointInTimeRestore
=== RUN   TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
=== PAUSE TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
=== RUN   TestAccRDSCluster_generatedName
=== PAUSE TestAccRDSCluster_generatedName
=== RUN   TestAccRDSCluster_takeFinalSnapshot
=== PAUSE TestAccRDSCluster_takeFinalSnapshot
=== RUN   TestAccRDSCluster_missingUserNameCausesError
=== PAUSE TestAccRDSCluster_missingUserNameCausesError
=== RUN   TestAccRDSCluster_tags
=== PAUSE TestAccRDSCluster_tags
=== RUN   TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL
=== PAUSE TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL
=== RUN   TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
=== PAUSE TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
=== RUN   TestAccRDSCluster_updateIAMRoles
=== PAUSE TestAccRDSCluster_updateIAMRoles
=== RUN   TestAccRDSCluster_kmsKey
=== PAUSE TestAccRDSCluster_kmsKey
=== RUN   TestAccRDSCluster_encrypted
=== PAUSE TestAccRDSCluster_encrypted
=== RUN   TestAccRDSCluster_copyTagsToSnapshot
=== PAUSE TestAccRDSCluster_copyTagsToSnapshot
=== RUN   TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID
=== PAUSE TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID
=== RUN   TestAccRDSCluster_backupsUpdate
=== PAUSE TestAccRDSCluster_backupsUpdate
=== RUN   TestAccRDSCluster_iamAuth
=== PAUSE TestAccRDSCluster_iamAuth
=== RUN   TestAccRDSCluster_deletionProtection
=== PAUSE TestAccRDSCluster_deletionProtection
=== RUN   TestAccRDSCluster_engineMode
=== PAUSE TestAccRDSCluster_engineMode
=== RUN   TestAccRDSCluster_EngineMode_global
=== PAUSE TestAccRDSCluster_EngineMode_global
=== RUN   TestAccRDSCluster_EngineMode_multiMaster
=== PAUSE TestAccRDSCluster_EngineMode_multiMaster
=== RUN   TestAccRDSCluster_EngineMode_parallelQuery
=== PAUSE TestAccRDSCluster_EngineMode_parallelQuery
=== RUN   TestAccRDSCluster_engineVersion
=== PAUSE TestAccRDSCluster_engineVersion
=== RUN   TestAccRDSCluster_engineVersionWithPrimaryInstance
=== PAUSE TestAccRDSCluster_engineVersionWithPrimaryInstance
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
=== RUN   TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
=== RUN   TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters
=== RUN   TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier
=== RUN   TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
=== PAUSE TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
=== RUN   TestAccRDSCluster_port
=== PAUSE TestAccRDSCluster_port
=== RUN   TestAccRDSCluster_scaling
=== PAUSE TestAccRDSCluster_scaling
=== RUN   TestAccRDSCluster_Scaling_defaultMinCapacity
=== PAUSE TestAccRDSCluster_Scaling_defaultMinCapacity
=== RUN   TestAccRDSCluster_snapshotIdentifier
=== PAUSE TestAccRDSCluster_snapshotIdentifier
=== RUN   TestAccRDSCluster_SnapshotIdentifier_deletionProtection
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_deletionProtection
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineMode_serverless
    cluster_test.go:1629: serverless does not support snapshot restore on an empty volume
--- SKIP: TestAccRDSCluster_SnapshotIdentifierEngineMode_serverless (0.00s)
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
=== RUN   TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
=== PAUSE TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
=== RUN   TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
=== RUN   TestAccRDSCluster_SnapshotIdentifier_masterPassword
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_masterPassword
=== RUN   TestAccRDSCluster_SnapshotIdentifier_masterUsername
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_masterUsername
=== RUN   TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
=== RUN   TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
=== RUN   TestAccRDSCluster_SnapshotIdentifier_tags
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_tags
=== RUN   TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
=== RUN   TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
=== PAUSE TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
=== RUN   TestAccRDSCluster_SnapshotIdentifier_encryptedRestore
=== PAUSE TestAccRDSCluster_SnapshotIdentifier_encryptedRestore
=== RUN   TestAccRDSCluster_enableHTTPEndpoint
=== PAUSE TestAccRDSCluster_enableHTTPEndpoint
=== CONT  TestAccRDSCluster_basic
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global
=== CONT  TestAccRDSCluster_takeFinalSnapshot
=== CONT  TestAccRDSCluster_deletionProtection
=== CONT  TestAccRDSCluster_engineVersionWithPrimaryInstance
=== CONT  TestAccRDSCluster_engineVersion
=== CONT  TestAccRDSCluster_EngineMode_parallelQuery
=== CONT  TestAccRDSCluster_EngineMode_multiMaster
=== CONT  TestAccRDSCluster_EngineMode_global
=== CONT  TestAccRDSCluster_dbClusterInstanceClass
=== CONT  TestAccRDSCluster_engineMode
=== CONT  TestAccRDSCluster_s3Restore
=== CONT  TestAccRDSCluster_pointInTimeRestore
=== CONT  TestAccRDSCluster_dbSubnetGroupName
=== CONT  TestAccRDSCluster_clusterIdentifierPrefix
=== CONT  TestAccRDSCluster_iamAuth
=== CONT  TestAccRDSCluster_backupsUpdate
=== CONT  TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID
=== CONT  TestAccRDSCluster_backtrackWindow
=== CONT  TestAccRDSCluster_missingUserNameCausesError
--- PASS: TestAccRDSCluster_missingUserNameCausesError (15.64s)
=== CONT  TestAccRDSCluster_copyTagsToSnapshot
--- PASS: TestAccRDSCluster_EngineMode_multiMaster (143.78s)
=== CONT  TestAccRDSCluster_availabilityZones
--- PASS: TestAccRDSCluster_clusterIdentifierPrefix (163.13s)
=== CONT  TestAccRDSCluster_iops
--- PASS: TestAccRDSCluster_dbSubnetGroupName (163.65s)
=== CONT  TestAccRDSCluster_encrypted
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineMode_global (181.60s)
=== CONT  TestAccRDSCluster_allocatedStorage
--- PASS: TestAccRDSCluster_backupsUpdate (182.61s)
=== CONT  TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql
--- PASS: TestAccRDSCluster_backtrackWindow (182.98s)
=== CONT  TestAccRDSCluster_storageType
--- PASS: TestAccRDSCluster_EngineMode_global (183.47s)
=== CONT  TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL
--- PASS: TestAccRDSCluster_basic (186.87s)
=== CONT  TestAccRDSCluster_tags
--- PASS: TestAccRDSCluster_EngineMode_parallelQuery (203.15s)
=== CONT  TestAccRDSCluster_generatedName
--- PASS: TestAccRDSCluster_iamAuth (203.47s)
=== CONT  TestAccRDSCluster_kmsKey
--- PASS: TestAccRDSCluster_takeFinalSnapshot (204.35s)
=== CONT  TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports
--- PASS: TestAccRDSCluster_deletionProtection (224.61s)
=== CONT  TestAccRDSCluster_updateIAMRoles
--- PASS: TestAccRDSCluster_copyTagsToSnapshot (249.09s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned
--- PASS: TestAccRDSCluster_availabilityZones (147.12s)
=== CONT  TestAccRDSCluster_enableHTTPEndpoint
--- PASS: TestAccRDSCluster_EnabledCloudWatchLogsExports_postgresql (168.11s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_encryptedRestore
--- PASS: TestAccRDSCluster_encrypted (187.26s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding
--- PASS: TestAccRDSCluster_generatedName (157.03s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags
--- PASS: TestAccRDSCluster_tags (177.92s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery
--- PASS: TestAccRDSCluster_kmsKey (165.35s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs
--- PASS: TestAccRDSCluster_pointInTimeRestore (371.68s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters
--- PASS: TestAccRDSCluster_updateIAMRoles (218.99s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_deletionProtection
--- PASS: TestAccRDSCluster_EnabledCloudWatchLogsExports_mySQL (289.21s)
=== CONT  TestAccRDSCluster_snapshotIdentifier
--- PASS: TestAccRDSCluster_engineMode (502.00s)
=== CONT  TestAccRDSCluster_onlyMajorVersion
--- PASS: TestAccRDSCluster_engineVersion (509.54s)
=== CONT  TestAccRDSCluster_Scaling_defaultMinCapacity
--- PASS: TestAccRDSCluster_PointInTimeRestore_enabledCloudWatchLogsExports (398.45s)
=== CONT  TestAccRDSCluster_scaling
--- PASS: TestAccRDSCluster_enableHTTPEndpoint (381.24s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_tags
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineMode_provisioned (452.55s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterPassword
--- PASS: TestAccRDSCluster_SnapshotIdentifier_encryptedRestore (392.02s)
=== CONT  TestAccRDSCluster_port
--- PASS: TestAccRDSCluster_SnapshotIdentifierVPCSecurityGroupIDs_tags (396.73s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_kmsKeyID
--- PASS: TestAccRDSCluster_Scaling_defaultMinCapacity (351.98s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal
--- PASS: TestAccRDSCluster_snapshotIdentifier (391.41s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineMode_parallelQuery (526.18s)
=== CONT  TestAccRDSCluster_SnapshotIdentifierEngineVersion_different
--- PASS: TestAccRDSCluster_SnapshotIdentifier_deletionProtection (466.67s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update
--- PASS: TestAccRDSCluster_port (217.85s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow
--- PASS: TestAccRDSCluster_scaling (412.78s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_masterUsername
--- PASS: TestAccRDSCluster_SnapshotIdentifier_tags (392.88s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_remove (205.32s)
=== CONT  TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow
=== CONT  TestAccRDSCluster_s3Restore
    cluster_test.go:481: Step 1/1 error: Error running apply: exit status 1
        
        Error: Error waiting for RDS Cluster state to be "available": unexpected state 'migration-failed', wanted target 'available'. last error: %!s(<nil>)
        
          with aws_rds_cluster.test,
          on terraform_plugin_test.tf line 74, in resource "aws_rds_cluster" "test":
          74: resource "aws_rds_cluster" "test" {
        
=== CONT  TestAccRDSCluster_iops
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterPassword (394.23s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_update (204.22s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm
--- PASS: TestAccRDSCluster_SnapshotIdentifier_vpcSecurityGroupIDs (757.87s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add
--- PASS: TestAccRDSCluster_SnapshotIdentifier_kmsKeyID (433.55s)
=== CONT  TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned
--- PASS: TestAccRDSCluster_onlyMajorVersion (762.47s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgrade
--- PASS: TestAccRDSCluster_dbClusterInstanceClass (1297.76s)
--- PASS: TestAccRDSCluster_allocatedStorage (1117.48s)
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineVersion_equal (440.71s)
--- PASS: TestAccRDSCluster_engineVersionWithPrimaryInstance (1304.05s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineModeGlobal_add (182.04s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_preferredBackupWindow (361.87s)
--- PASS: TestAccRDSCluster_SnapshotIdentifierEngineVersion_different (458.61s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifierEngineMode_provisioned (183.65s)
--- PASS: TestAccRDSCluster_iops (1229.57s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_masterUsername (413.35s)
--- PASS: TestAccRDSCluster_storageType (1282.81s)
--- PASS: TestAccRDSCluster_SnapshotIdentifier_preferredMaintenanceWindow (412.36s)
--- FAIL: TestAccRDSCluster_s3Restore (1588.66s)
--- PASS: TestAccRDSCluster_ReplicationSourceIdentifier_kmsKeyID (1673.03s)
=== CONT  TestAccRDSCluster_allowMajorVersionUpgrade
    cluster_test.go:101: Step 3/3 error: Check failed: Check 4/4 error: aws_rds_cluster.test: Attribute 'engine_version' expected "13.5", got "12.9"


--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParameters (1922.92s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_secondaryClustersWriteForwarding (2096.21s)
--- FAIL: TestAccRDSCluster_allowMajorVersionUpgrade (1697.99s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_replicationSourceIdentifier (1897.84s)
--- PASS: TestAccRDSCluster_GlobalClusterIdentifier_primarySecondaryClusters (1972.25s)
--- PASS: TestAccRDSCluster_allowMajorVersionUpgradeWithCustomParametersApplyImm (1991.96s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/rds        3106.801s
FAIL
make: *** [GNUmakefile:36: testacc] Error 1
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Heya @YakDriver & @ewbankkit, I re-created the PR as the previous one became a bit messy to review after the rebases I did. I'll touch up the documentation of `aws_rds_cluster` later today and include it in the PR.

**Comment by bschaatsbergen** [comment]
Not quite sure why terrafmt is complaining about my changes in `cluster_test.go` and the docs I updated.

**Comment by ewbankkit** [comment]
@bschaatsbergen It's tabs vs. spaces that causes the `terrafmt` errors. `terrafmt` requires spaces.

**Comment by ewbankkit** [comment]
@bschaatsbergen It's tabs vs. spaces that causes the `terrafmt` errors. `terrafmt` requires spaces.

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen It's tabs vs. spaces that causes the `terrafmt` errors. `terrafmt` requires spaces.

Ah crap, that's good to know for the future. Thanks for fixing it!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccRDSCluster_basic\|TestAccRDSCluster_availabilityZones\|TestAccRDSCluster_storageType\|TestAccRDSCluster_allocatedStorage\|TestAccRDSCluster_iops\|TestAccRDSCluster_dbClusterInstanceClass\|TestAccRDSCluster_scaling' PKG=rds ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 3  -run=TestAccRDSCluster_basic\|TestAccRDSCluster_availabilityZones\|TestAccRDSCluster_storageType\|TestAccRDSCluster_allocatedStorage\|TestAccRDSCluster_iops\|TestAccRDSCluster_dbClusterInstanceClass\|TestAccRDSCluster_scaling -timeout 180m
=== RUN   TestAccRDSCluster_basic
=== PAUSE TestAccRDSCluster_basic
=== RUN   TestAccRDSCluster_availabilityZones
=== PAUSE TestAccRDSCluster_availabilityZones
=== RUN   TestAccRDSCluster_storageType
=== PAUSE TestAccRDSCluster_storageType
=== RUN   TestAccRDSCluster_allocatedStorage
=== PAUSE TestAccRDSCluster_allocatedStorage
=== RUN   TestAccRDSCluster_iops
=== PAUSE TestAccRDSCluster_iops
=== RUN   TestAccRDSCluster_dbClusterInstanceClass
=== PAUSE TestAccRDSCluster_dbClusterInstanceClass
=== RUN   TestAccRDSCluster_scaling
=== PAUSE TestAccRDSCluster_scaling
=== CONT  TestAccRDSCluster_basic
=== CONT  TestAccRDSCluster_iops
=== CONT  TestAccRDSCluster_scaling
--- PASS: TestAccRDSCluster_basic (162.63s)
=== CONT  TestAccRDSCluster_dbClusterInstanceClass
--- PASS: TestAccRDSCluster_iops (367.07s)
=== CONT  TestAccRDSCluster_storageType
--- PASS: TestAccRDSCluster_scaling (387.85s)
=== CONT  TestAccRDSCluster_allocatedStorage
--- PASS: TestAccRDSCluster_dbClusterInstanceClass (1200.41s)
=== CONT  TestAccRDSCluster_availabilityZones
--- PASS: TestAccRDSCluster_availabilityZones (126.73s)
--- PASS: TestAccRDSCluster_storageType (1263.22s)
--- PASS: TestAccRDSCluster_allocatedStorage (1252.03s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	1643.992s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Pull request merged**
