### PR TITLE
Fix wrong outputs of aws_dx_connection

### PR DESCRIPTION
**Pull request by posquit0**
### Description

`aws_dx_connection` resource and `aws_dx_connection` data source doesn't return `provider_name` and `vlan_id` outputs.

```
          + provider_name           = ""
          + vlan_id                       = null
```

Following is output from `aws-cli`.

```json
        {
            "ownerAccount": "xxxx",
            "connectionId": "dxcon-xxx",
            "connectionName": "xxxxx",
            "connectionState": "available",
            "region": "ap-northeast-2",
            "location": "LGKNX",
            "bandwidth": "50Mbps",
            "vlan": 1506,
            "partnerName": "KINX",
            "awsDevice": "xxxxx",
            "jumboFrameCapable": true,
            "awsDeviceV2": "xxxxxx",
            "awsLogicalDeviceId": "xxxxxx",
            "hasLogicalRedundancy": "no",
            "tags": [
 ...
            ],
            "macSecCapable": false,
            "portEncryptionStatus": "Encryption Down",
            "encryptionMode": "unknown"
        },
```

### Relations

Closes #0000

### References

- https://github.com/aws/aws-sdk-go/blob/main/models/apis/directconnect/2012-10-25/api-2.json#L1168
  - `Connection` Object Spec for DirectConnect in `aws-sdk-go`

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccDirectConnectConnection_\|TestAccDirectConnectConnectionDataSource_' PKG=directconnect ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/directconnect/... -v -count 1 -parallel 2  -run=TestAccDirectConnectConnection_\|TestAccDirectConnectConnectionDataSource_ -timeout 180m
=== RUN   TestAccDirectConnectConnectionDataSource_basic
=== PAUSE TestAccDirectConnectConnectionDataSource_basic
=== RUN   TestAccDirectConnectConnection_basic
=== PAUSE TestAccDirectConnectConnection_basic
=== RUN   TestAccDirectConnectConnection_disappears
=== PAUSE TestAccDirectConnectConnection_disappears
=== RUN   TestAccDirectConnectConnection_encryptionMode
    connection_test.go:87: Environment variable DX_CONNECTION_ID is not set
--- SKIP: TestAccDirectConnectConnection_encryptionMode (0.00s)
=== RUN   TestAccDirectConnectConnection_macsecRequested
=== PAUSE TestAccDirectConnectConnection_macsecRequested
=== RUN   TestAccDirectConnectConnection_providerName
=== PAUSE TestAccDirectConnectConnection_providerName
=== RUN   TestAccDirectConnectConnection_skipDestroy
=== PAUSE TestAccDirectConnectConnection_skipDestroy
=== RUN   TestAccDirectConnectConnection_tags
=== PAUSE TestAccDirectConnectConnection_tags
=== CONT  TestAccDirectConnectConnectionDataSource_basic
=== CONT  TestAccDirectConnectConnection_tags
--- PASS: TestAccDirectConnectConnectionDataSource_basic (27.07s)
=== CONT  TestAccDirectConnectConnection_providerName
--- PASS: TestAccDirectConnectConnection_providerName (34.84s)
=== CONT  TestAccDirectConnectConnection_disappears
=== CONT  TestAccDirectConnectConnection_macsecRequested
--- PASS: TestAccDirectConnectConnection_tags (76.63s)
--- PASS: TestAccDirectConnectConnection_disappears (24.31s)
=== CONT  TestAccDirectConnectConnection_basic
--- PASS: TestAccDirectConnectConnection_macsecRequested (32.37s)
=== CONT  TestAccDirectConnectConnection_skipDestroy
--- PASS: TestAccDirectConnectConnection_basic (31.08s)
--- PASS: TestAccDirectConnectConnection_skipDestroy (24.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/directconnect	144.243s
```

**Comment by ewbankkit** [comment]
@posquit0 Thanks for the contribution :tada: :clap:.

**Comment by posquit0** [comment]
@ewbankkit Thank you for helping my issue! But, `vlan_id` output is also broken as mentioned above. Can you figure out this too?

**Comment by ewbankkit** [comment]
@posquit0 The only API structure field applicable to `vlan_id` is `Vlan`, which is the one we are using.
Are you expecting a non-zero value to be returned from the service?

**Comment by posquit0** [comment]
@ewbankkit As mentioned above, the output from `aws-cli` command is `vlan: 1506`. However, the output from Terraform is `vlan_id: null`. I think this is a problem with the parsing process.

**Pull request merged**
