### PR TITLE
Fix inconsistent read after create for vpc_route_table

### LINKED ISSUE #31895: [Bug]:  aws_route_table - error reading Route Table (...): couldn't find resource
### Terraform Core Version

1.2.9

### AWS Provider Version

4.67.0

### Affected Resource(s)

* aws_route_table

### Expected Behavior

`aws_route_table` resource should have been created without error 

### Actual Behavior

creation failed because resource cannot be found (because of eventual consistency of AWS API) - similarly to #21629 & #30993

### Relevant Error/Panic Output Snippet

```shell
2023-04-19T13:38:24.273Z	ERROR	.rpk.managed-byoc	zapio/writer.go:145
        	            	failed applying network resource: failed creating network: failed running terraform apply: exit status 1
        	            	Error: error reading Route Table (rtb-0dedaa5ab2fbf3cc2): couldn't find resource
        	            	  with module.network[0].aws_route_table.private[1],
        	            	  on ../../modules/terraform-aws-redpanda-network/routing.tf line 11, in resource "aws_route_table" "private":
        	            	  11: resource "aws_route_table" "private" {
```

### Terraform Configuration Files

```
resource "aws_route_table" "private" {
  count  = length(var.private_subnet_cidrs)
  vpc_id = aws_vpc.redpanda.id

  tags = {
    purpose = "private"
  }
}
```

### Steps to Reproduce

Create the resource in a loop run repeatedly ideally tens or hundreds of times until you hit this AWS race/eventual consistency bug

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

We are hitting this issue consistently. There is already a PR https://github.com/hashicorp/terraform-provider-aws/pull/30999 fixing this issue but as it lacks attention, I have created this issue with hope the PR can can more traction to merged in soon.

### References

Similar to #30993 

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by alenkacz**
### Description

Similar to
This fixes read after newly created vpc_route_table that can fail because of AWS API eventual consistency https://docs.aws.amazon.com/AWSEC2/latest/APIReference/query-api-troubleshooting.html

```
2023-04-19T13:38:24.273Z	ERROR	.rpk.managed-byoc	zapio/writer.go:145
        	            	failed applying network resource: failed creating network: failed running terraform apply: exit status 1
        	            	Error: error reading Route Table (rtb-0dedaa5ab2fbf3cc2): couldn't find resource
        	            	  with module.network[0].aws_route_table.private[1],
        	            	  on ../../modules/terraform-aws-redpanda-network/routing.tf line 11, in resource "aws_route_table" "private":
        	            	  11: resource "aws_route_table" "private" {
```

Similar to https://github.com/hashicorp/terraform-provider-aws/pull/30994 - I don't have debug logs for this one but it's obviously the same problem.

### Relations

Relates #30993
Closes #31895

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by alenkacz** [comment]
@ewbankkit do you think we can merge this one as well? 🙏

**Comment by alenkacz** [comment]
@ewbankkit is there sth I can do to help merge this one?

**Comment by alenkacz** [comment]
@ewbankkit ping :)

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCRouteTable_basic\|TestAccVPCRouteTable_disappears' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCRouteTable_basic\|TestAccVPCRouteTable_disappears -timeout 180m
=== RUN   TestAccVPCRouteTable_basic
=== PAUSE TestAccVPCRouteTable_basic
=== RUN   TestAccVPCRouteTable_disappears
=== PAUSE TestAccVPCRouteTable_disappears
=== CONT  TestAccVPCRouteTable_basic
=== CONT  TestAccVPCRouteTable_disappears
--- PASS: TestAccVPCRouteTable_disappears (25.49s)
--- PASS: TestAccVPCRouteTable_basic (29.19s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	35.125s
```

**Pull request merged**
