### PR TITLE
mq_broker: don't recreate when `auto_minor_version_upgrade` and `host_instance_type` changed

### PR DESCRIPTION
**Pull request by nitrocode**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

## Why

The mq broker should not be recreated when

* auto minor version upgrade is enabled/disabled
* the host instance type is modified.

### References
* Closes https://github.com/hashicorp/terraform-provider-aws/issues/13351
* See https://docs.aws.amazon.com/cli/latest/reference/mq/update-broker.html#options which allows updating an existing broker's `--auto-minor-version-upgrade | --no-auto-minor-version-upgrade (boolean)` and `--host-instance-type`

### Commands

```shell
$ aws mq update-broker --broker-id <b-guid> --no-auto-minor-version-upgrade
{
    "AutoMinorVersionUpgrade": false,
    "BrokerId": "<b-guid>"
}
$ aws mq update-broker --broker-id <b-guid> --auto-minor-version-upgrade
{
    "AutoMinorVersionUpgrade": true,
    "BrokerId": "<b-guid>"
}
$ aws mq update-broker --broker-id <b-guid> --host-instance-type mq.t3.micro
{
    "BrokerId": "<b-guid>",
    "HostInstanceType": "mq.t3.micro"
}
```

### Testing

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSMqBroker_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSMqBroker_ -timeout 180m
=== RUN   TestAccAWSMqBroker_basic
=== PAUSE TestAccAWSMqBroker_basic
=== RUN   TestAccAWSMqBroker_throughputOptimized
=== PAUSE TestAccAWSMqBroker_throughputOptimized
=== RUN   TestAccAWSMqBroker_allFieldsDefaultVpc
=== PAUSE TestAccAWSMqBroker_allFieldsDefaultVpc
=== RUN   TestAccAWSMqBroker_allFieldsCustomVpc
=== PAUSE TestAccAWSMqBroker_allFieldsCustomVpc
=== RUN   TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== RUN   TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== PAUSE TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== RUN   TestAccAWSMqBroker_updateUsers
=== PAUSE TestAccAWSMqBroker_updateUsers
=== RUN   TestAccAWSMqBroker_tags
=== PAUSE TestAccAWSMqBroker_tags
=== RUN   TestAccAWSMqBroker_updateSecurityGroup
=== PAUSE TestAccAWSMqBroker_updateSecurityGroup
=== RUN   TestAccAWSMqBroker_updateEngineVersion
=== PAUSE TestAccAWSMqBroker_updateEngineVersion
=== RUN   TestAccAWSMqBroker_disappears
=== PAUSE TestAccAWSMqBroker_disappears
=== RUN   TestAccAWSMqBroker_rabbitmq
=== PAUSE TestAccAWSMqBroker_rabbitmq
=== RUN   TestAccAWSMqBroker_rabbitmq_Logs
=== PAUSE TestAccAWSMqBroker_rabbitmq_Logs
=== RUN   TestAccAWSMqBroker_rabbitmq_Validation_AuditLog
=== PAUSE TestAccAWSMqBroker_rabbitmq_Validation_AuditLog
=== RUN   TestAccAWSMqBroker_clusterRabbitMQ
=== PAUSE TestAccAWSMqBroker_clusterRabbitMQ
=== RUN   TestAccAWSMqBroker_ldap
=== PAUSE TestAccAWSMqBroker_ldap
=== CONT  TestAccAWSMqBroker_basic
=== CONT  TestAccAWSMqBroker_updateSecurityGroup
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled
=== CONT  TestAccAWSMqBroker_rabbitmq_Validation_AuditLog
=== CONT  TestAccAWSMqBroker_updateUsers
=== CONT  TestAccAWSMqBroker_rabbitmq_Logs
=== CONT  TestAccAWSMqBroker_rabbitmq
=== CONT  TestAccAWSMqBroker_disappears
=== CONT  TestAccAWSMqBroker_ldap
=== CONT  TestAccAWSMqBroker_tags
=== CONT  TestAccAWSMqBroker_allFieldsCustomVpc
=== CONT  TestAccAWSMqBroker_updateEngineVersion
=== CONT  TestAccAWSMqBroker_clusterRabbitMQ
=== CONT  TestAccAWSMqBroker_EncryptionOptions_KmsKeyId
=== CONT  TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled
=== CONT  TestAccAWSMqBroker_allFieldsDefaultVpc
=== CONT  TestAccAWSMqBroker_throughputOptimized
--- PASS: TestAccAWSMqBroker_rabbitmq_Validation_AuditLog (811.07s)
--- PASS: TestAccAWSMqBroker_rabbitmq_Logs (841.96s)
--- PASS: TestAccAWSMqBroker_rabbitmq (875.04s)
--- PASS: TestAccAWSMqBroker_throughputOptimized (952.62s)
--- PASS: TestAccAWSMqBroker_clusterRabbitMQ (1158.37s)
--- PASS: TestAccAWSMqBroker_basic (1230.64s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Disabled (1315.97s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_KmsKeyId (1334.22s)
--- PASS: TestAccAWSMqBroker_disappears (1342.43s)
--- PASS: TestAccAWSMqBroker_ldap (1351.62s)
--- PASS: TestAccAWSMqBroker_EncryptionOptions_UseAwsOwnedKey_Enabled (1417.87s)
--- PASS: TestAccAWSMqBroker_tags (1491.41s)
--- PASS: TestAccAWSMqBroker_updateEngineVersion (1651.67s)
--- PASS: TestAccAWSMqBroker_updateSecurityGroup (1668.08s)
--- PASS: TestAccAWSMqBroker_updateUsers (1878.46s)
--- PASS: TestAccAWSMqBroker_allFieldsDefaultVpc (2078.91s)
--- PASS: TestAccAWSMqBroker_allFieldsCustomVpc (2139.86s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2141.654s
```

### CODE REVIEW

**Comment by nitrocode** [comment]
@zhelding conflicts resolved 😄

**Comment by nitrocode** [comment]
@zhelding @breathingdust hi all, just a friendly bump. is there anything else i can do to get this in the next release?

**Comment by zhelding** [comment]
Hi @nitrocode!

No further action is required on your part. We will now review your PR as part of our standard triage prioritization process ([see here](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/faq.md#how-do-you-decide-what-gets-merged-for-each-release)). Unfortunately, we can't guarantee that your PR will get a review in a timely manner, but we will get to it as soon as we have capacity.

Thanks again for your contribution!

**Review by YakDriver — APPROVED** [review]
Looks good! 🎉 

Output from tests on `us-west-2`:
```console
% make testacc TESTS=TestAccMQBroker PKG=mq                        
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20 -run='TestAccMQBroker'  -timeout 180m
--- PASS: TestAccMQBroker_RabbitMQ_logs (738.37s)
--- PASS: TestAccMQBroker_throughputOptimized (845.89s)
--- PASS: TestAccMQBroker_RabbitMQ_validationAuditLog (897.57s)
--- PASS: TestAccMQBroker_RabbitMQ_basic (928.72s)
--- PASS: TestAccMQBroker_RabbitMQ_cluster (969.69s)
--- PASS: TestAccMQBrokerDataSource_basic (1149.69s)
--- PASS: TestAccMQBroker_disappears (1188.89s)
--- PASS: TestAccMQBroker_ldap (1190.90s)
--- PASS: TestAccMQBroker_basic (1192.11s)
--- PASS: TestAccMQBroker_Update_tags (1210.83s)
--- PASS: TestAccMQBroker_EncryptionOptions_kmsKeyID (1215.07s)
--- PASS: TestAccMQBroker_EncryptionOptions_awsOwnedKeyDisabled (1221.20s)
--- PASS: TestAccMQBroker_EncryptionOptions_awsOwnedKeyEnabled (1243.07s)
--- PASS: TestAccMQBroker_Update_securityGroup (1419.21s)
--- PASS: TestAccMQBroker_Update_engineVersion (1421.85s)
--- PASS: TestAccMQBroker_Update_users (1693.32s)
--- PASS: TestAccMQBroker_AllFields_customVPC (1818.89s)
--- PASS: TestAccMQBroker_AllFields_defaultVPC (1910.09s)
--- PASS: TestAccMQBroker_Update_hostInstanceType (1984.85s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/mq	1986.138s
```

Test output (GovCloud):
```console
% make testacc TESTS=TestAccMQBroker PKG=mq
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/mq/... -v -count 1 -parallel 20 -run='TestAccMQBroker'  -timeout 180m
--- PASS: TestAccMQBroker_RabbitMQ_validationAuditLog (717.94s)
--- PASS: TestAccMQBroker_RabbitMQ_logs (718.85s)
--- PASS: TestAccMQBroker_RabbitMQ_basic (765.38s)
--- PASS: TestAccMQBroker_throughputOptimized (852.94s)
--- FAIL: TestAccMQBroker_RabbitMQ_cluster (953.56s)
--- PASS: TestAccMQBroker_EncryptionOptions_awsOwnedKeyDisabled (1002.93s)
--- PASS: TestAccMQBroker_ldap (1007.61s)
--- PASS: TestAccMQBroker_basic (1018.00s)
--- PASS: TestAccMQBroker_EncryptionOptions_awsOwnedKeyEnabled (1021.03s)
--- PASS: TestAccMQBroker_Update_tags (1065.76s)
--- PASS: TestAccMQBroker_disappears (1090.48s)
--- PASS: TestAccMQBroker_EncryptionOptions_kmsKeyID (1096.04s)
--- PASS: TestAccMQBrokerDataSource_basic (1114.37s)
--- PASS: TestAccMQBroker_Update_engineVersion (1189.83s)
--- PASS: TestAccMQBroker_Update_securityGroup (1286.25s)
--- PASS: TestAccMQBroker_Update_users (1510.20s)
--- PASS: TestAccMQBroker_Update_hostInstanceType (1570.17s)
--- PASS: TestAccMQBroker_AllFields_customVPC (1689.72s)
--- PASS: TestAccMQBroker_AllFields_defaultVPC (1696.97s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/mq	1698.262s
```
Failure shows up in nightlies for GovCloud and is unrelated to these changes.

**Pull request merged**
