### PR TITLE
r/sagemaker_domain/user_profile - add additional canvas app args

### LINKED ISSUE #33034: [Bug]: aws_sagemaker_domain r_studio_server_pro_app_settings setting AccessStatus DISABLED is valid
### Terraform Core Version

1.5.5

### AWS Provider Version

4.66.0

### Affected Resource(s)

A sagemaker domain contains multiple user profiles.  A valid use case is where not every user profile in the domain is a RStudio user and new users are not given access to rstudio by default.   this is done by setting access_status to DISABLED at a domain level, and enabling it per user profile.

Reference, Step 5 at end of page 
https://docs.aws.amazon.com/sagemaker/latest/dg/rstudio-add-existing.html

via CLI

```shell
aws sagemaker update-domain --region ${data.aws_region.current.name} --domain-id ${aws_sagemaker_domain.domain.id} --app-security-group-management Service --domain-settings-for-update RStudioServerProDomainSettingsForUpdate={DomainExecutionRoleArn=${aws_iam_role.execution_domain_role.arn}} --default-user-settings RStudioServerProAppSettings={AccessStatus=DISABLED}
```

however the current TF `aws_sagemaker_domain` module seems to be setting optional `user_group` to a value when it should be omitted.

```shell
Error: updating SageMaker Domain: ValidationException: Unable to update Domain [arn:aws:sagemaker:ap-southeast-2:1234567890:domain/d-xxxxxxx] with update to RStudioServerProAppSettings. Make sure AccessStatus is set to ENABLED if the UserGroup attribute is also being set status code: 400,

	dynamic "r_studio_server_pro_app_settings" {
	  for_each = var.sagemaker_domain_rstudio_enable ? [1] : []
	  content {
		access_status = "DISABLED"
	  }
	}	
```

### Expected Behavior

Setting default-user-settings RStudioServerProAppSettings={AccessStatus=DISABLED} should succeed without error

### Actual Behavior

error returned from AWS API indicating `access_status` should be ENABLED when it is configured for DISABLED and no `user_group` attribute.

```shell
Error: updating SageMaker Domain: ValidationException: Unable to update Domain [arn:aws:sagemaker:ap-southeast-2:1234567890:domain/d-xxxxxx] with update to RStudioServerProAppSettings. Make sure AccessStatus is set to ENABLED if the UserGroup attribute is also being set status code: 400,
```

### Relevant Error/Panic Output Snippet

```shell
Error: updating SageMaker Domain: ValidationException: Unable to update Domain [arn:aws:sagemaker:ap-southeast-2:1234567890:domain/d-xxxxx] with update to RStudioServerProAppSettings. Make sure AccessStatus is set to ENABLED if the UserGroup attribute is also being set status code: 400,
```

### Terraform Configuration Files

```terraform
resource "aws_sagemaker_domain" "domain" {
  depends_on = [
    aws_iam_role.execution_domain_role
  ]
  domain_name             = "${var.sagemaker_domain_name}-${var.env}"
  auth_mode               = var.sagemaker_domain_auth_mode
  vpc_id                  = var.sagemaker_vpc_id
  subnet_ids              = var.sagemaker_subnet_ids
  app_network_access_type = var.app_network_access_type
  kms_key_id              = aws_kms_key.sagemaker_efs_kms_cmk.arn

...

  default_user_settings {
    security_groups = [aws_security_group.sagemakerstudio.id]
    execution_role  = aws_iam_role.execution_domain_role.arn

...


	dynamic "r_studio_server_pro_app_settings" {
	  for_each = var.sagemaker_domain_rstudio_enable ? [1] : []
	  content {
		access_status = "DISABLED"
	  }
	}	
...

  }

  domain_settings {
    # https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/sagemaker_domain#r_studio_server_pro_app_settings	
	# https://github.com/hashicorp/terraform-provider-aws/blob/v4.66.0/CHANGELOG.md
    r_studio_server_pro_domain_settings {
	  domain_execution_role_arn = aws_iam_role.execution_domain_role.arn
    }
  }
```

### Steps to Reproduce

Create SageMaker domain with the following `r_studio_server_pro_app_settings`

```
default_user_settings {
	r_studio_server_pro_app_settings {
		access_status = "DISABLED"
	 }
}
```

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #34004: [Enhancement]: Only 30 custom_image blocks allowed in aws_sagemaker_domain.kernel_gateway_app_settings
### Description

Recently AWS increased quota for max number of custom kernel images attached to the domain from 30 to 200. 

In the latest version of AWS provided we can have only 30 blocks as per code: 
https://github.com/hashicorp/terraform-provider-aws/blob/4be8994f30291b6144d5032b2488e1f565d92dde/internal/service/sagemaker/domain.go#L181

Since AWS allows more, could this be improved? 

### Affected Resource(s) and/or Data Source(s)

aws_sagemaker_domain.kernel_gateway_app_settings.custom_image

### Potential Terraform Configuration

_No response_

### References

[KernelGatewayAppSettings-CustomImages](https://docs.aws.amazon.com/sagemaker/latest/APIReference/API_KernelGatewayAppSettings.html#sagemaker-Type-KernelGatewayAppSettings-CustomImages)

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by DrFaust92**
### Relations

Closes #34004
Closes #33034

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccSageMaker_serial/Domain/identityProviderOauthSettings PKG=sagemaker

--- PASS: TestAccSageMaker_serial/Domain/identityProviderOauthSettings (439.49s)
--- PASS: TestAccSageMaker_serial/Domain/rStudioServerProAppSettings (652.62s)
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
 make testacc TESTARGS='-run=TestAccSageMaker_serial/Domain\|TestAccSageMaker_serial/UserProfile\|TestAccSageMaker_serial/Space' PKG=sagemaker 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/sagemaker/... -v -count 1 -parallel 20  -run=TestAccSageMaker_serial/Domain\|TestAccSageMaker_serial/UserProfile\|TestAccSageMaker_serial/Space -timeout 360m
=== RUN   TestAccSageMaker_serial
=== PAUSE TestAccSageMaker_serial
=== CONT  TestAccSageMaker_serial
=== RUN   TestAccSageMaker_serial/Domain
=== RUN   TestAccSageMaker_serial/Domain/workspaceSettings
=== RUN   TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/code
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage
    domain_test.go:700: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/canvas
=== RUN   TestAccSageMaker_serial/Domain/directDeploySettings
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/Domain/securityGroup
=== RUN   TestAccSageMaker_serial/Domain/modelRegisterSettings
=== RUN   TestAccSageMaker_serial/Domain/kendraSettings
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Domain/kms
=== RUN   TestAccSageMaker_serial/Domain/sharingSettings
=== RUN   TestAccSageMaker_serial/Domain/rSessionAppSettings
=== RUN   TestAccSageMaker_serial/Domain/rStudioServerProAppSettings
=== RUN   TestAccSageMaker_serial/Domain/basic
=== RUN   TestAccSageMaker_serial/Domain/disappears
=== RUN   TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage
    domain_test.go:661: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Domain/identityProviderOauthSettings
=== RUN   TestAccSageMaker_serial/Domain/domainSettings
=== RUN   TestAccSageMaker_serial/Domain/tags
=== RUN   TestAccSageMaker_serial/Domain/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated
=== RUN   TestAccSageMaker_serial/Space
=== RUN   TestAccSageMaker_serial/Space/kernelGatewayAppSettings_imageConfig
    space_test.go:170: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/Space/jupyterServerAppSettings
=== RUN   TestAccSageMaker_serial/Space/basic
=== RUN   TestAccSageMaker_serial/Space/disappears
=== RUN   TestAccSageMaker_serial/Space/tags
=== RUN   TestAccSageMaker_serial/Space/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/Space/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/UserProfile
=== RUN   TestAccSageMaker_serial/UserProfile/basic
=== RUN   TestAccSageMaker_serial/UserProfile/tags
=== RUN   TestAccSageMaker_serial/UserProfile/tensorboardAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_lifecycleConfig
=== RUN   TestAccSageMaker_serial/UserProfile/disappears
=== RUN   TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings
=== RUN   TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_imageConfig
    user_profile_test.go:244: Environment variable SAGEMAKER_IMAGE_VERSION_BASE_IMAGE is not set
=== RUN   TestAccSageMaker_serial/UserProfile/jupyterServerAppSettings
--- PASS: TestAccSageMaker_serial (10021.43s)
    --- PASS: TestAccSageMaker_serial/Domain (6248.46s)
        --- PASS: TestAccSageMaker_serial/Domain/workspaceSettings (422.19s)
        --- PASS: TestAccSageMaker_serial/Domain/spaceSettingsKernelGatewayAppSettings (282.85s)
        --- PASS: TestAccSageMaker_serial/Domain/code (258.98s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_defaultResourceAndCustomImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/canvas (258.65s)
        --- PASS: TestAccSageMaker_serial/Domain/directDeploySettings (258.75s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_lifecycleConfig (258.29s)
        --- PASS: TestAccSageMaker_serial/Domain/securityGroup (271.66s)
        --- PASS: TestAccSageMaker_serial/Domain/modelRegisterSettings (248.13s)
        --- PASS: TestAccSageMaker_serial/Domain/kendraSettings (248.58s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettings (249.36s)
        --- PASS: TestAccSageMaker_serial/Domain/tensorboardAppSettingsWithImage (316.91s)
        --- PASS: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings (248.66s)
        --- PASS: TestAccSageMaker_serial/Domain/kms (248.97s)
        --- PASS: TestAccSageMaker_serial/Domain/sharingSettings (249.51s)
        --- PASS: TestAccSageMaker_serial/Domain/rSessionAppSettings (249.29s)
        --- PASS: TestAccSageMaker_serial/Domain/rStudioServerProAppSettings (293.49s)
        --- PASS: TestAccSageMaker_serial/Domain/basic (258.87s)
        --- PASS: TestAccSageMaker_serial/Domain/disappears (289.64s)
        --- SKIP: TestAccSageMaker_serial/Domain/kernelGatewayAppSettings_customImage (0.00s)
        --- PASS: TestAccSageMaker_serial/Domain/identityProviderOauthSettings (260.36s)
        --- PASS: TestAccSageMaker_serial/Domain/domainSettings (281.98s)
        --- PASS: TestAccSageMaker_serial/Domain/tags (255.22s)
        --- PASS: TestAccSageMaker_serial/Domain/jupyterServerAppSettings (248.86s)
        --- PASS: TestAccSageMaker_serial/Domain/defaultUserSettingsUpdated (289.27s)
    --- PASS: TestAccSageMaker_serial/Space (1621.14s)
        --- SKIP: TestAccSageMaker_serial/Space/kernelGatewayAppSettings_imageConfig (0.00s)
        --- PASS: TestAccSageMaker_serial/Space/jupyterServerAppSettings (267.85s)
        --- PASS: TestAccSageMaker_serial/Space/basic (272.29s)
        --- PASS: TestAccSageMaker_serial/Space/disappears (292.50s)
        --- PASS: TestAccSageMaker_serial/Space/tags (261.27s)
        --- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings (264.16s)
        --- PASS: TestAccSageMaker_serial/Space/kernelGatewayAppSettings_lifecycleConfig (263.07s)
    --- PASS: TestAccSageMaker_serial/UserProfile (2151.83s)
        --- PASS: TestAccSageMaker_serial/UserProfile/basic (264.17s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tags (261.02s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettings (265.04s)
        --- PASS: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_lifecycleConfig (265.74s)
        --- PASS: TestAccSageMaker_serial/UserProfile/disappears (293.63s)
        --- PASS: TestAccSageMaker_serial/UserProfile/tensorboardAppSettingsWithImage (272.91s)
        --- PASS: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings (264.56s)
        --- SKIP: TestAccSageMaker_serial/UserProfile/kernelGatewayAppSettings_imageConfig (0.00s)
        --- PASS: TestAccSageMaker_serial/UserProfile/jupyterServerAppSettings (264.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker	10026.638s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Comment by damianslee** [comment]
Is there a way I can test this from tf cloud with our dev sagemaker implementation before 5.25 is released?

**Review by damianslee — COMMENTED** [review]
I'm testing 5.25 and getting this crash stack or expandCanvasAppSettings

Stack trace from the terraform-provider-aws_v5.25.0_x5 plugin:

panic: interface conversion: interface {} is *schema.Set, not []interface {}

goroutine 378 [running]:
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.expandCanvasAppSettings({0xc002ac0ad0?, 0xc00463b0b0?, 0xe27c8ce?})
	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/domain.go:1211 +0x533
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.expandDomainDefaultUserSettings({0xc002ac0a40?, 0xe239a6d?, 0xc0044dfe30?})
	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/domain.go:1009 +0xbf
github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker.resourceUserProfileUpdate({0xf5fc220, 0xc0044dfe30}, 0xc002cb8000, {0xe1a8680?, 0xc0002c8b40})
	github.com/hashicorp/terraform-provider-aws/internal/service/sagemaker/user_profile.go:577 +0x1fc
github.com/hashicorp/terraform-provider-aws/internal/provider.interceptedHandler[...].func1(0x0?, {0xe1a8680?, 0xc0002c8b40?})
	github.com/hashicorp/terraform-provider-aws/internal/provider/intercept.go:111 +0x32d
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).update(0xf5fc220?, {0xf5fc220?, 0xc004362c90?}, 0xd?, {0xe1a8680?, 0xc0002c8b40?})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:807 +0x87
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc001b4d340, {0xf5fc220, 0xc004362c90}, 0xc00436c410, 0xc0042e3400, {0xe1a8680, 0xc0002c8b40})
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/resource.go:919 +0x845
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc001c0dc20, {0xf5fc220?, 0xc004362b70?}, 0xc0042cd590)
	github.com/hashicorp/terraform-plugin-sdk/v2@v2.29.0/helper/schema/grpc_provider.go:1060 +0xe8d
github.com/hashicorp/terraform-plugin-mux/tf5muxserver.(*muxServer).ApplyResourceChange(0xf5fc178?, {0xf5fc220?, 0xc004362840?}, 0xc0042cd590)
	github.com/hashicorp/terraform-plugin-mux@v0.12.0/tf5muxserver/mux_server_ApplyResourceChange.go:36 +0x1b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ApplyResourceChange(0xc00095b9a0, {0xf5fc220?, 0xc004362030?}, 0xc004356a80)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/tf5server/server.go:859 +0x574
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler({0xdf2bb60?, 0xc00095b9a0}, {0xf5fc220, 0xc004362030}, 0xc004356a10, 0x0)
	github.com/hashicorp/terraform-plugin-go@v0.19.0/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:467 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000114d20, {0xf60a9a0, 0xc0034464e0}, 0xc004346d80, 0xc004030870, 0x15c32db8, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1376 +0xdd2
google.golang.org/grpc.(*Server).handleStream(0xc000114d20, {0xf60a9a0, 0xc0034464e0}, 0xc004346d80, 0x0)
	google.golang.org/grpc@v1.58.2/server.go:1753 +0xa36
google.golang.org/grpc.(*Server).serveStreams.func1.1()
	google.golang.org/grpc@v1.58.2/server.go:998 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
	google.golang.org/grpc@v1.58.2/server.go:996 +0x18c

Error: The terraform-provider-aws_v5.25.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

Operation failed: failed running terraform apply (exit 1)

**Pull request merged**
