### PR TITLE
r/aws_identitystore_user - Update emails Configuration Block title to name Configuration Block

### LINKED ISSUE #27060: [Docs]: aws_identitystore_user lists 2 "emails Configuration Block" when the second one should be "name Configuration Block"
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/identitystore_user

### Description

The second "emails Configuration Block" heading should be "name Configuration Block"

### References

_No response_

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by afrazchelsea**
### Description

As part of this PR, I updated `emails Configuration Block` title to `name Configuration Block` in Resource:`aws_identitystore_user` documentation.

### Relations

Closes #27060

### CODE REVIEW

**Comment by breathingdust** [comment]
Hi @afrazchelsea! 👋  Thanks for the contribution, it looks like there are lot of extraneous noise in the PR. Lots of `*` being changed to `-`. Can you remove those changes so the PR only includes the desired edit? Thank you!

**Comment by afrazchelsea** [comment]
@breathingdust thanks for reviewing! I have fixed the changes, can you please check again?

**Review by justinretzolk — APPROVED** [review]
Looks good to me! Thank you for your contribution! I'll get this merged in once the checks finish up.

**Comment by afrazchelsea** [comment]
Thanks a lot! @justinretzolk

**Pull request merged**
