### PR TITLE
Update Bug_Report.md

### PR DESCRIPTION
**Pull request by dinesh1202**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @dinesh1202 👋 It looks like you may have been attempting to open an issue, rather than this pull request. If I'm correct in that, you can open a bug report by following [this link](https://github.com/hashicorp/terraform-provider-aws/issues/new/choose) and selecting the **Bug Report** option.

**Comment by justinretzolk** [comment]
Hey @dinesh1202 -- apologies for pinging you twice on this, but on further review, I believe I know what is causing your issue, so you may not even need to bother opening the separate bug report. With version `3.75.2` of the provider, special care is needed when using the `aws_s3_bucket_logging` and `aws_s3_bucket_lifecycle_configuration` resources. This is described in the **Usage Notes** section of each of their respective documentation pages. I'll leave links below for reference.

- [`aws_s3_bucket_logging` Usage Notes](https://registry.terraform.io/providers/hashicorp/aws/3.75.2/docs/resources/s3_bucket_logging#usage-notes)
- [`aws_s3_bucket_lifecycle_configuration` Usage Notes](https://registry.terraform.io/providers/hashicorp/aws/3.75.2/docs/resources/s3_bucket_lifecycle_configuration#usage-notes)

**Comment by dinesh1202** [comment]
Hi Justin,

Thank you so much for your quick response, I am so sorry for the
inconvenience caused, I thought it is required to create a pull request
after updating the details.
let me undo it please

Thank you so much!!

Best Regards,
Dinesh
Be Hygienic, Be Healthy, Be Safe!!!

**Comment by dinesh1202** [comment]
Hi Justin,

Thank you so much for your quick response on the issue, sure I will follow
the Usage Note for each resource.
Also, I will not open any separate bug report.

Thanks a lot again for your kind attention

Best Regards,
Dinesh
Be Hygienic, Be Healthy, Be Safe!!!

**Comment by justinretzolk** [comment]
Hey @dinesh1202 👋 No problem at all! I'm glad that was able to get you sorted out. I'll go ahead and close this out for now, but if you run into any further issues, please feel free to open a new issue!

**Comment by dinesh1202** [comment]
Thank you so much Justin,  for all your great support

**Pull request closed without merging**
