### PR TITLE
Update vpnsite_customer_gateway.go

### PR DESCRIPTION
**Pull request by dionasaur**
Line 56 should be changed to optional as this is not a required field in the AWS SDK API. Having this as required breaks terraform applies for certificate based vpn connections.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates https://github.com/hashicorp/terraform-provider-aws/issues/10548.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @dionasaur 👋 Thank you for taking the time to open this PR! In order for this to be reviewed, please take a look at the contribution guide section on [making small changes to existing resources](https://hashicorp.github.io/terraform-provider-aws/bugs-and-enhancements/).

**Comment by dionasaur** [comment]
Thanks Justin! sorry about that I am working on the acceptance test :)

**Comment by dionasaur** [comment]
Hi Justin,

I'm a little unfamiliar with the process but i performed some tests with make test and this is what it came back with:

**Comment by bschaatsbergen** [comment]
Hi @dionasaur, could you please reference the issue related to this ticket in the body of the PR description. Also please take a good look at our contributor guide. I'm happy to help you if the pull request looks as expected, if you have a tough time enhancing this pull request feel free to shout and I'll give a hand.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccSiteVPNCustomerGateway' PKG=ec2 ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccSiteVPNCustomerGateway -timeout 180m
=== RUN   TestAccSiteVPNCustomerGatewayDataSource_filter
=== PAUSE TestAccSiteVPNCustomerGatewayDataSource_filter
=== RUN   TestAccSiteVPNCustomerGatewayDataSource_id
=== PAUSE TestAccSiteVPNCustomerGatewayDataSource_id
=== RUN   TestAccSiteVPNCustomerGateway_basic
=== PAUSE TestAccSiteVPNCustomerGateway_basic
=== RUN   TestAccSiteVPNCustomerGateway_disappears
=== PAUSE TestAccSiteVPNCustomerGateway_disappears
=== RUN   TestAccSiteVPNCustomerGateway_tags
=== PAUSE TestAccSiteVPNCustomerGateway_tags
=== RUN   TestAccSiteVPNCustomerGateway_deviceName
=== PAUSE TestAccSiteVPNCustomerGateway_deviceName
=== RUN   TestAccSiteVPNCustomerGateway_4ByteASN
=== PAUSE TestAccSiteVPNCustomerGateway_4ByteASN
=== RUN   TestAccSiteVPNCustomerGateway_certificate
=== PAUSE TestAccSiteVPNCustomerGateway_certificate
=== CONT  TestAccSiteVPNCustomerGatewayDataSource_filter
=== CONT  TestAccSiteVPNCustomerGateway_tags
--- PASS: TestAccSiteVPNCustomerGatewayDataSource_filter (29.01s)
=== CONT  TestAccSiteVPNCustomerGateway_basic
--- PASS: TestAccSiteVPNCustomerGateway_tags (57.53s)
=== CONT  TestAccSiteVPNCustomerGateway_disappears
--- PASS: TestAccSiteVPNCustomerGateway_basic (29.37s)
=== CONT  TestAccSiteVPNCustomerGatewayDataSource_id
--- PASS: TestAccSiteVPNCustomerGateway_disappears (24.12s)
=== CONT  TestAccSiteVPNCustomerGateway_4ByteASN
--- PASS: TestAccSiteVPNCustomerGatewayDataSource_id (27.01s)
=== CONT  TestAccSiteVPNCustomerGateway_certificate
--- PASS: TestAccSiteVPNCustomerGateway_4ByteASN (29.13s)
=== CONT  TestAccSiteVPNCustomerGateway_deviceName
--- PASS: TestAccSiteVPNCustomerGateway_deviceName (28.59s)
--- PASS: TestAccSiteVPNCustomerGateway_certificate (88.01s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	178.692s
```

**Comment by ewbankkit** [comment]
@dionasaur Thanks for the contribution :tada: :clap:.

**Comment by bschaatsbergen** [comment]
For future contributions, you can run `make testacc` with some flags:

```
make testacc TESTS=TestAccSiteVPNCustomerGateway_ PKG=ec2
```

This runs every test in the ec2 package that matches `TestAccSiteVPNCustomerGateway_`

**Pull request merged**
