### PR TITLE
r/aws_ecr_repository_creation_template: New resource.

### LINKED ISSUE #34503: [New Resource]: ECR Repository Creation Template
### Description

When the API is available, please support the [new configuration for repositories that are auto-created via pull-through cache rules](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-initial-configuration-repositories-pull-through-cache-preview/).

### Requested Resource(s) and/or Data Source(s)

* aws_ecr_repository_creation_template

### Potential Terraform Configuration

```terraform
resource "aws_ecr_repository_creation_template" "template" {
  prefix = "quay"
  description = "default settings for quay.io"
  image_tag_mutability = "IMMUTABLE"
  encryption_configuration = {
    encryption_type = "KMS"
    kms_key = "(arn)"
  }
  policy = "(json)"
  lifecycle_policy = "(json)"
  tags = {
    Foo = "bar"
  }
}
```

### References

- [Announcement on AWS blog](https://aws.amazon.com/about-aws/whats-new/2023/11/amazon-ecr-initial-configuration-repositories-pull-through-cache-preview)
- [Manage your repository creation templates](https://docs.aws.amazon.com/AmazonECR/latest/userguide/repository-creation-templates.html) on ECR docs

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bodgit**
### Description

Adds support for ECR Repository Creation Templates.

Example:

```terraform
resource "aws_ecr_repository_creation_template" "example" {
  prefix               = "example"
  description          = "A description"
  image_tag_mutability = "IMMUTABLE"
  custom_role_arn      = "arn:aws:iam::123456689012:role/somerole"

  applied_for = [
    "PULL_THROUGH_CACHE",
  ]

  encryption_configuration {
    encryption_type = "AES256"
  }

  lifecycle_policy = "…"

  repository_policy = "…"

  resource_tags = {
    One = "Two"
  }
}
```

### Relations

Closes #34503 

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccECRRepositoryCreationTemplate PKG=ecr
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRRepositoryCreationTemplate'  -timeout 360m
=== RUN   TestAccECRRepositoryCreationTemplate_basic
=== PAUSE TestAccECRRepositoryCreationTemplate_basic
=== RUN   TestAccECRRepositoryCreationTemplate_disappears
=== PAUSE TestAccECRRepositoryCreationTemplate_disappears
=== RUN   TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists
=== PAUSE TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists
=== RUN   TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle
=== PAUSE TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle
=== RUN   TestAccECRRepositoryCreationTemplate_repository
=== PAUSE TestAccECRRepositoryCreationTemplate_repository
=== CONT  TestAccECRRepositoryCreationTemplate_basic
=== CONT  TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle
=== CONT  TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists
=== CONT  TestAccECRRepositoryCreationTemplate_repository
=== CONT  TestAccECRRepositoryCreationTemplate_disappears
--- PASS: TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists (20.66s)
--- PASS: TestAccECRRepositoryCreationTemplate_disappears (35.03s)
--- PASS: TestAccECRRepositoryCreationTemplate_basic (40.05s)
--- PASS: TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle (43.23s)
--- PASS: TestAccECRRepositoryCreationTemplate_repository (51.35s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        51.500s
```

### CODE REVIEW

**Comment by bodgit** [comment]
I found I had to tweak the semgrep configuration as it was failing due to matching the `resourceRepositoryCreationTemplateCreate` function name against the `/(?i)ECR/` pattern, (took me a moment to spot it).

Tests are all passing now, let me know if I've missed anything.

**Comment by bodgit** [comment]
Have a data source as well:

```terraform
data "aws_ecr_repository_creation_template" "example" {
  prefix = "example"
}
```

```console
% make testacc TESTS=TestAccECRRepositoryCreationTemplateDataSource PKG=ecr
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecr/... -v -count 1 -parallel 20 -run='TestAccECRRepositoryCreationTemplateDataSource'  -timeout 360m
=== RUN   TestAccECRRepositoryCreationTemplateDataSource_basic
=== PAUSE TestAccECRRepositoryCreationTemplateDataSource_basic
=== CONT  TestAccECRRepositoryCreationTemplateDataSource_basic
--- PASS: TestAccECRRepositoryCreationTemplateDataSource_basic (14.27s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecr        14.378s
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccECRRepositoryCreationTemplate' PKG=ecr ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.5 test ./internal/service/ecr/... -v -count 1 -parallel 3  -run=TestAccECRRepositoryCreationTemplate -timeout 360m
=== RUN   TestAccECRRepositoryCreationTemplateDataSource_basic
=== PAUSE TestAccECRRepositoryCreationTemplateDataSource_basic
=== RUN   TestAccECRRepositoryCreationTemplate_basic
=== PAUSE TestAccECRRepositoryCreationTemplate_basic
=== RUN   TestAccECRRepositoryCreationTemplate_disappears
=== PAUSE TestAccECRRepositoryCreationTemplate_disappears
=== RUN   TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists
=== PAUSE TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists
=== RUN   TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle
=== PAUSE TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle
=== RUN   TestAccECRRepositoryCreationTemplate_repository
=== PAUSE TestAccECRRepositoryCreationTemplate_repository
=== CONT  TestAccECRRepositoryCreationTemplateDataSource_basic
=== CONT  TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists
=== CONT  TestAccECRRepositoryCreationTemplate_disappears
--- PASS: TestAccECRRepositoryCreationTemplate_failWhenAlreadyExists (6.64s)
=== CONT  TestAccECRRepositoryCreationTemplate_repository
--- PASS: TestAccECRRepositoryCreationTemplateDataSource_basic (10.10s)
=== CONT  TestAccECRRepositoryCreationTemplate_basic
--- PASS: TestAccECRRepositoryCreationTemplate_disappears (10.45s)
=== CONT  TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle
--- PASS: TestAccECRRepositoryCreationTemplate_basic (10.34s)
--- PASS: TestAccECRRepositoryCreationTemplate_ignoreEquivalentLifecycle (11.12s)
--- PASS: TestAccECRRepositoryCreationTemplate_repository (17.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecr	28.741s
```

**Comment by ewbankkit** [comment]
@bodgit Thanks for the contribution :tada: :clap:.

**Comment by jef-rubert-hs** [comment]
I am unable to create a ROOT `aws_ecr_repository_creation_template` because of this regex validation:
```
regexache.MustCompile(`(?:[a-z0-9]+(?:[._-][a-z0-9]+)*/)*[a-z0-9]+(?:[._-][a-z0-9]+)*`),
```

root is different from ROOT as I can have both defined using the ui, one would make AWS look for a `root` repository and ROOT means apply to any.

as per ui 
```
ROOT = 
Any prefix in your ECR registry
The settings in this template will be applied to all repositories that don't match another template in this Region.
```
vs
```
root = 
A specific prefix
The settings in this template will be applied to repositories matching the namespace prefix you specify.
```

**Pull request merged**
