### PR TITLE
enhancement: add tests for ECS task definition EFS volume (#24921)

### LINKED ISSUE #19549: aws_ecs_task_definition always displays “has been changed”
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.15.4
on darwin_amd64
+ provider registry.terraform.io/hashicorp/aws v3.42.0
+ provider registry.terraform.io/hashicorp/dns v3.1.0
+ provider registry.terraform.io/hashicorp/http v2.1.0
```

### Affected Resource(s)

* aws_ecs_task_definition

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
resource "aws_ecs_task_definition" "…" {
  tags                     = merge(local.tags, { Service = "…" })
  family                   = "…-${var.environment}"
  requires_compatibilities = ["FARGATE"]
  task_role_arn            = aws_iam_role.task.arn
  execution_role_arn       = aws_iam_role.execution.arn
  network_mode             = "awsvpc"
  cpu                      = 4096
  memory                   = 8192

  volume {
    name = "collection-storage"
    efs_volume_configuration {
      file_system_id     = var.collection_efs_file_system_id
      transit_encryption = "ENABLED"
    }
  }

  container_definitions = templatefile(
    "${path.module}/task-definitions/….json",
    {
      "REGION"          = var.region
      "CONTAINER_NAME"  = "…",
      "ENVIRONMENT"     = var.environment,
      "SENTRY_DSN"      = var.sentry_dsn,
      "CONTAINER_IMAGE" = "${aws_ecr_repository.this["…"].repository_url}:${lookup(var.container_tags, "…", "la
est")}",
      "LOG_GROUP"       = aws_cloudwatch_log_group.this["…"].name,
      "SERVICE_NAME"    = "…"
    }
  )
}
```

### Expected Behavior

Terraform should show that the resource has not changed from the definition

### Actual Behavior

```
# module.search.aws_ecs_task_definition.… has been changed
resource "aws_ecs_task_definition" "…" {
    id                       = "…"
    tags                     = {
        "Service" = "…"
    }
    # (11 unchanged attributes hidden)
  + volume {
      + name = "collection-storage"
      + efs_volume_configuration {
          + file_system_id          = "fs-ee6bf06d"
          + root_directory          = "/"
          + transit_encryption      = "ENABLED"
          + transit_encryption_port = 0
        }
    }
  - volume {
      - name = "collection-storage" -> null
      - efs_volume_configuration {
          - file_system_id     = "fs-ee6bf06d" -> null
          - root_directory     = "/" -> null
          - transit_encryption = "ENABLED" -> null
        }
    }
}
```

### Steps to Reproduce

1. `terraform apply`

### LINKED ISSUE #23541: efs_volume_configuration transit_encryption_port causing replace of task definition
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

$ terraform -v
Terraform v1.1.6
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.74.3
+ provider registry.terraform.io/hashicorp/external v2.2.0
+ provider registry.terraform.io/hashicorp/local v2.1.0
+ provider registry.terraform.io/hashicorp/null v3.1.0
+ provider registry.terraform.io/hashicorp/template v2.2.0

### Affected Resource(s)

aws_ecs_task_definition -> volume - > efs_volume_configuration -> transit_encryption_port

relevant code: https://github.com/hashicorp/terraform-provider-aws/blob/de6e94dea7b75ab5cf89626386da1747ed50d4b8/internal/service/ecs/task_definition.go#L355

reference: https://www.reddit.com/r/Terraform/comments/px60pb/terraform_constantly_reattaches_volumes_when/

* aws_XXXXX

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
volume {
    name = var.efs_volume_name
    efs_volume_configuration {
      file_system_id     = data.aws_efs_file_system.shared_fs.id
      root_directory     = "/"
      transit_encryption = "DISABLED"
      authorization_config {
        iam = "DISABLED"
      }
    }
  }
```

### Expected Behavior

no change

### Actual Behavior

it wants to replace

      - volume {
          - name = "efs" -> null
          - efs_volume_configuration {
              - file_system_id          = "fs-07d0e24a8153ed93c" -> null
              - root_directory          = "/" -> null
              - transit_encryption      = "DISABLED" -> null
              - transit_encryption_port = 0 -> null
              - authorization_config {
                  - iam = "DISABLED" -> null
                }
            }
        }
      + volume {
          + name = "efs"
          + efs_volume_configuration {
              + file_system_id     = "fs-07d0e24a8153ed93c"
              + root_directory     = "/"
              + transit_encryption = "DISABLED"
              + authorization_config {
                  + iam = "DISABLED"
                }
            }
        }

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

### PR DESCRIPTION
**Pull request by jeremychauvet**
### Description
Trying to qualifying issue #23541, I've seen that no test were covering this case (ECS task definition with encryption set to disabled and authorization_config also set to disable.

### Relations
Closes #23541
Closes #19549

### Output from Acceptance Testing
New test added: TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
Output:

```console
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20 -run='TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled'  -timeout 180m
=== RUN   TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
=== PAUSE TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
=== CONT  TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
--- PASS: TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled (37.11s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ecs        39.007s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
%  make testacc TESTARGS='-run=TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled' PKG=ecs
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ecs/... -v -count 1 -parallel 20  -run=TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled -timeout 180m
=== RUN   TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
=== PAUSE TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
=== CONT  TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled
--- PASS: TestAccECSTaskDefinition_EFSVolume_transitEncryptionDisabled (43.78s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ecs	50.543s
```

**Comment by ewbankkit** [comment]
@jeremychauvet Thanks for the contribution :tada: :clap:.
Does this PR close the linked issues?

**Comment by jeremychauvet** [comment]
My pleasure @ewbankkit 
I guess we can close the linked issues yes (manually tested if issue can be reproduced and  cannot, I've assumed it had been already fixed based on comments)

**Comment by markbaird** [comment]
@jeremychauvet What comments led you to believe those issues are fixed? I can still reproduce those issues today with the AWS provider version `5.9.0`. All I have to do is change the image tag on an ECS task definition and the `terraform plan` output says all the EFS volume mounts on the ECS task have changed. See the screenshot on [this comment](https://github.com/hashicorp/terraform-provider-aws/issues/23541#issuecomment-1299307989). 

That's exactly what I'm seeing in every `terraform plan` output today. @ewbankkit Those linked issues are not fixed.

**Comment by jeremychauvet** [comment]
Hey @markbaird 👋🏼 
Thanks for your quick reply, let's try to fix this definitively 😄 

I've tested with the following code, what should I change / add to reproduce your issue?
```terraform
resource "aws_efs_file_system" "default" {
  creation_token = "b-23541"
}

resource "aws_ecs_task_definition" "default" {
  family = "service"
  container_definitions = jsonencode([
    {
      name      = "sleep"
      image     = "busybox"
      cpu       = 10
      memory    = 512
      essential = true
      command   = ["sleep", "360"]
    },
  ])

  volume {
    name = "default"
    efs_volume_configuration {
      file_system_id     = aws_efs_file_system.default.id
      root_directory     = "/"
      transit_encryption = "DISABLED"
      authorization_config {
        iam = "DISABLED"
      }
    }
  }
}
```

**Comment by markbaird** [comment]
@jeremychauvet The issue occurs when `transit_encryption` is `ENABLED` not `DISABLED`. Given a `volume` definition like the following:

```
  volume {
    name = "my_volume"
    efs_volume_configuration {
      file_system_id     = aws_efs_file_system.efs.id
      transit_encryption = "ENABLED"
    }
  }
```

I run `terraform apply` once to deploy the ECS task. Then I come back later and update the `image` in the task definition and nothing else, followed by `terraform plan` and the output will include a diff of the volume indicating that the entire volume mapping is being replaced. It looks just like the screenshot someone posted [here](https://github.com/hashicorp/terraform-provider-aws/issues/23541#issuecomment-1299307989).

**Comment by ewbankkit** [comment]
Actually, that won't make a noticeable difference as nested values always get the zero value.
Try adding `Computed: true,` to the  `transit_encryption_port` schema definition.

**Comment by jeremychauvet** [comment]
Thanks for your help @ewbankkit 👍🏼 
I've tried both of your suggestions without any impact on the result. I'm still working on finding why `transit_encryption_port=0` is added.

**Pull request merged**
