### PR TITLE
New Resource: `aws_quicksight_refresh_schedule`

### LINKED ISSUE #30788: [New Resource]: aws_quicksight_data_set_refresh_schedule
### Description

Allow practitioners to manage refresh schedules for AWS QuickSight data sets.

### Requested Resource(s) and/or Data Source(s)

`aws_quicksight_data_set_refresh_schedule`

### Potential Terraform Configuration

```terraform
resource "aws_quicksight_data_set_refresh_schedule" "schedule" {
  data_set_id = "test",
  schedule_Id : "example",
  refresh_type : "INCREMENTAL_REFRESH", // INCREMENTAL_REFRESH | FULL_REFRESH
  start_after_date_time : "2023-04-18T00:00:00",
  schedule_frequency {
    interval : "WEEKLY", // MINUTE15 | MINUTE30 | HOURLY | DAILY | WEEKLY | MONTHLY
    time_of_the_day : "00:00",
    timezone : "Europe/London",
    refresh_on_day {
      day_of_month : "1",
      day_of_week : "MONDAY" // SUNDAY | MONDAY | TUESDAY | WEDNESDAY | THURSDAY | FRIDAY | SATURDAY
    }
  }
}
```

### References

* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListRefreshSchedules.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateRefreshSchedule.html

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by g-dx**
### Description

This PR adds a new `aws_quicksight_refresh_schedule` resource, allowing practitioners to manage scheduled refreshes of Quicksight data sets via Terraform.

### Relations
Closes #30788
Relates To #10990 & #30744

### References

* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeRefreshSchedule.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_ListRefreshSchedules.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_UpdateRefreshSchedule.html

### Output from Acceptance Testing

```
make testacc PKG=quicksight TESTS=TestAccQuickSightRefreshSchedule_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightRefreshSchedule_'  -timeout 180m
=== RUN   TestAccQuickSightRefreshSchedule_basic
=== PAUSE TestAccQuickSightRefreshSchedule_basic
=== RUN   TestAccQuickSightRefreshSchedule_disappears
=== PAUSE TestAccQuickSightRefreshSchedule_disappears
=== RUN   TestAccQuickSightRefreshSchedule_weeklyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_weeklyRefresh
=== RUN   TestAccQuickSightRefreshSchedule_monthlyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_monthlyRefresh
=== CONT  TestAccQuickSightRefreshSchedule_basic
=== CONT  TestAccQuickSightRefreshSchedule_weeklyRefresh
=== CONT  TestAccQuickSightRefreshSchedule_disappears
=== CONT  TestAccQuickSightRefreshSchedule_monthlyRefresh
--- PASS: TestAccQuickSightRefreshSchedule_disappears (27.80s)
--- PASS: TestAccQuickSightRefreshSchedule_weeklyRefresh (29.59s)
--- PASS: TestAccQuickSightRefreshSchedule_basic (30.83s)
--- PASS: TestAccQuickSightRefreshSchedule_monthlyRefresh (31.13s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	31.218s
```

### CODE REVIEW

**Comment by g-dx** [comment]
@jar-b - after further reading of the API docs I've realised that refresh schedules **can** be created from data sets which do not have refresh properties defined. The only limitation is that they must be of `FULL_REFRESH` type rather than `INCREMENTAL_REFRESH`.

Accordingly, I've reworked the acceptance tests in this PR to use QuickSight S3 data sources, as is done from the `aws_quicksight_data_set` tests, rather than Athena which avoids the problems you encountered on my other PR here: https://github.com/hashicorp/terraform-provider-aws/pull/30778#issuecomment-1516831773

As such this PR is ready to review and land! :ok_hand:

**Comment by g-dx** [comment]
@jar-b - thanks for the review.

Will make those changes now.

**Comment by g-dx** [comment]
@jar-b - that should be those changes all ready. 

I went with the following resource structure in the end:

```terraform
resource "aws_quicksight_refresh_schedule" "schedule" {
  arn            = "..."
  aws_account_id = "0123456789"
  data_set_id    = "id"
  schedule_id    = "example"

  schedule {
    refresh_type          = "FULL_REFRESH"
    start_after_date_time = "2023-12-18T00:00:00",
    schedule_frequency {
      interval        = "WEEKLY"
      time_of_the_day = "00:00"
      timezone        = "Europe/London"
      refresh_on_day {
        day_of_month = "1"
        day_of_week  = "MONDAY"
      }
    }
  }
}
```

Not exactly sure how I managed to misread the API structure so badly in the first place!

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightRefreshSchedule_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightRefreshSchedule_'  -timeout 180m
=== RUN   TestAccQuickSightRefreshSchedule_basic
=== PAUSE TestAccQuickSightRefreshSchedule_basic
=== RUN   TestAccQuickSightRefreshSchedule_disappears
=== PAUSE TestAccQuickSightRefreshSchedule_disappears
=== RUN   TestAccQuickSightRefreshSchedule_weeklyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_weeklyRefresh
=== RUN   TestAccQuickSightRefreshSchedule_monthlyRefresh
=== PAUSE TestAccQuickSightRefreshSchedule_monthlyRefresh
=== CONT  TestAccQuickSightRefreshSchedule_basic
=== CONT  TestAccQuickSightRefreshSchedule_weeklyRefresh
=== CONT  TestAccQuickSightRefreshSchedule_disappears
=== CONT  TestAccQuickSightRefreshSchedule_monthlyRefresh
--- PASS: TestAccQuickSightRefreshSchedule_disappears (29.51s)
--- PASS: TestAccQuickSightRefreshSchedule_weeklyRefresh (31.97s)
--- PASS: TestAccQuickSightRefreshSchedule_monthlyRefresh (32.03s)
--- PASS: TestAccQuickSightRefreshSchedule_basic (32.21s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 35.375s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @g-dx! 🥇 Really well done!

**Pull request merged**
