### PR TITLE
elbv2: add eventually consistent reads when listing tags on new rules

### LINKED ISSUE #20442: Eventual consistency problems in `aws_lb_listener_rule`
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.3
on linux_amd64
+ provider registry.terraform.io/hashicorp/aws v3.52.0
```

### Affected Resource(s)

* `aws_lb_listener_rule`

### Terraform Configuration Files

```hcl
variable "subnet_ids" {
    type = list
}

variable "security_group_id" {
    type = string
}

resource "aws_lb" "this" {
  name               = "reproducer-lb-0"
  internal           = true
  load_balancer_type = "application"
  security_groups    = [var.security_group_id]
  subnets            = var.subnet_ids
}

resource "aws_lb_listener" "this" {
  load_balancer_arn = aws_lb.this.arn
  port              = "80"
  protocol          = "HTTP"

  default_action {
    type = "fixed-response"

    fixed_response {
      content_type = "text/plain"
      message_body = "Fixed response content"
      status_code  = "200"
    }
  }
}

resource "aws_lb_listener_rule" "this" {
  count = 80
  
  priority = count.index + 1
  listener_arn = aws_lb_listener.this.arn

  action {
    type = "fixed-response"

    fixed_response {
      content_type = "text/plain"
      message_body = "HEALTHY"
      status_code  = "200"
    }
  }

  condition {
    host_header {
      values = ["example-${count.index}.test"]
    }
  }
}
```

### Expected Behavior

The listener rules should be created without errors.

### Actual Behavior

Creation of listener rules fails due to eventual consistency problems with the following errors:

```
aws_lb_listener_rule.this[71]: Creation complete after 3s [id=arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/b43fb72ceb463c6a]
aws_lb_listener_rule.this[67]: Creation complete after 3s [id=arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/19c1fb0c182e5483]
aws_lb_listener_rule.this[28]: Creation complete after 17s [id=arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/22452f1cf577ea98]
aws_lb_listener_rule.this[19]: Still creating... [20s elapsed]
aws_lb_listener_rule.this[24]: Creation complete after 5s [id=arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/a42cda15517c75d8]
aws_lb_listener_rule.this[19]: Creation complete after 23s [id=arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/640344f9cbb8578b]
╷
│ Error: error listing tags for (arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/95387a95d2740b47): RuleNotFound: Rule 'arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/95387a95d2740b47' not found
│       status code: 400, request id: 9e87e5f7-ba13-47c2-9726-6eadae3ef56b
│ 
│   with aws_lb_listener_rule.this[66],
│   on main.tf line 25, in resource "aws_lb_listener_rule" "this":
│   25: resource "aws_lb_listener_rule" "this" {
│ 
╵
╷
│ Error: error listing tags for (arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/2207875d512433d6): RuleNotFound: Rule 'arn:aws:elasticloadbalancing:us-east-1:xxx:listener-rule/app/reproducer-lb-0/b68cc505f2294d20/e2edf643be3ea082/2207875d512433d6' not found
│       status code: 400, request id: 5c870654-153b-46bc-b65d-ce61465e8974
│ 
│   with aws_lb_listener_rule.this[75],
│   on main.tf line 25, in resource "aws_lb_listener_rule" "this":
│   25: resource "aws_lb_listener_rule" "this" {
```

### Steps to Reproduce

This bug is not deterministic and may take multiple runs to reproduce.  I'm creating 80 rules per run in order to increase the probability that it occurs, though I've still seen it take multiple runs.  To do so, I was running this in a loop like the following until it failed.

```bash

# Replace these
export TF_VAR_security_group_id="sg-12345"
export TF_VAR_subnet_ids='["subnet-12345", "subnet-67890"]'

while terraform apply --auto-approve && terraform destroy -target=aws_lb_listener.this --auto-approve; do sleep 1s; done;
```

### References

I believe this is due to missing retry logic in this bit of code:

https://github.com/hashicorp/terraform-provider-aws/blob/cdb7db61b2e857d4ee217a4e56d6dbb8368972d5/aws/resource_aws_lb_listener_rule.go#L592

Similar to the lines above that, we should add retry logic to work around eventual consistency with this API on resource creation.

### PR DESCRIPTION
**Pull request by dcherman**
elbv2: add eventually consistent reads when listing tags on new rules

Fixes #20442

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #20442 #20454

Output from acceptance testing:

Unfortunately I'm not able to run the acceptance tests for this resource since it requires VPC creation which is restricted in my environment.

### CODE REVIEW

**Comment by dcherman** [comment]
Let me know when this is pending review and I'll rebase/resolve any merge conflicts.  Going to wait until someone is actively looking at it to avoid having to do that multiple times.  Thanks!

**Comment by richardgavel** [comment]
This seems like a different pattern of code to solving the eventual consistency issue compared to most of the other places it's solved. Any reason for the difference?

**Comment by dcherman** [comment]
@richardgavel This change was actually based on https://github.com/hashicorp/terraform-provider-aws/blob/f71bb5f455301493d7bcf1e7309553ffc701451f/aws/resource_aws_lb_listener_rule.go#L560-L574 which was written a while back to handle eventual consistency here.  I started writing a generalized version of that and noticed the `retryOnAwsCode` func was exactly what I wanted and already implemented nearly the identical logic, however it was hard-coded to check for error codes rather than specific errors.  That's why I refactored that to create `retryOnAwsPredicate` and then implemented `retryOnAwsCode` using that.

So to answer your question, it's actually handled the same way, just with a generalized helper.  The type cast is unfortunate since the helper returns `interface{}`, but hopefully with go generics we could potentially eliminate that in the future.

**Comment by mikemartin1090** [comment]
@dcherman let me know if you need some help refactoring this. I'd love to implement this fix as it's been making our runs inconsistent.

**Comment by dcherman** [comment]
@mikemartin1090 I assume this hasn't been prioritized for review yet per the previous comment - once someone is ready to review this, I'm happy to work on refactoring/rebasing this.

**Pull request closed without merging**
