### PR TITLE
resource/aws_ecs_service: Add support for deployment circuit breaker

### LINKED ISSUE #16499: Add support for ECS deployment circuit breakers
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS has announced ECS deployment circuit breakers that can automatically roll back a failed deployment: https://aws.amazon.com/blogs/containers/announcing-amazon-ecs-deployment-circuit-breaker/

### New or Affected Resource(s)

* aws_ecs_service

### Potential Terraform Configuration

```hcl
resource "aws_ecs_service" "bar" {
  name                = "bar"
  cluster             = aws_ecs_cluster.foo.id
  task_definition     = aws_ecs_task_definition.bar.arn
  scheduling_strategy = "DAEMON"

  deployment_configuration = {
    maximum_percent = 200
    minimum_healthy_percent = 100

    deployment_circuit_breaker = {
      enabled  = true
      rollback = true
    }
  }
}
```

I'm not a massive fan of that API layout and would love it to be as simple as `enable_deployment_circuit_breaker = true` as a top level thing but I think the general pattern here is to have Terraform follow the AWS API and then people can abstract that behind modules if that works for them. That way if the API changes it doesn't cause breaking changes in the provider to support the new functionality.

### References

* https://docs.aws.amazon.com/AmazonECS/latest/APIReference/API_DeploymentConfiguration.html

### LINKED ISSUE #18364: resource/aws_ecs_service: Intermittent acceptance test failure in TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion
There is a rare intermittent failure in `TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion` with the following error:

```console
=== RUN   TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion
=== PAUSE TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion
=== CONT  TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion
testing_new.go:63: Error running post-test destroy, there may be dangling resources: exit status 1
Error: Error deleting security group: DependencyViolation: resource sg-0467142aaec35c0a4 has a dependent object
  status code: 400, request id: e9327a0c-d814-47e4-bb51-e69892ab834a
Error: Error deleting security group: DependencyViolation: resource sg-093b061548736cdec has a dependent object
  status code: 400, request id: 7677f1c7-6101-467d-95de-4374b2ca385f
--- FAIL: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (794.34s)
```

### Affected Resource

* aws_ecs_service

### PR DESCRIPTION
**Pull request by shuheiktgw**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16499
Closes #18364

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_ecs_service: Add support for deployment circuit breaker
```

Output from acceptance testing:

```
$  make testacc TESTARGS='-run=TestAccAWSEcsService_withDeploymentCircuitBreaker'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEcsService_withDeploymentCircuitBreaker -timeout 120m
=== RUN   TestAccAWSEcsService_withDeploymentCircuitBreaker
=== PAUSE TestAccAWSEcsService_withDeploymentCircuitBreaker
=== CONT  TestAccAWSEcsService_withDeploymentCircuitBreaker
--- PASS: TestAccAWSEcsService_withDeploymentCircuitBreaker (101.96s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	103.757s
```

Thank you for your review! 👍

### CODE REVIEW

**Comment by shuheiktgw** [comment]
goreleaser failure seems to happen in other PRs so I don't think that is due to this PR.

**Comment by hanswesterbeek** [comment]
Looking forward to seeing this merged.

**Comment by berchev** [comment]
Hello Team,

Do you have any ETA when this PR is going to get merged?
We have TF Cloud customer (Team & Governance) interested on that.
Thank you in advance!

Regards,
Georgi Berchev

**Comment by mimozell** [comment]
Any updates on this? Looking forward to using it 😊

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

Acceptance tests on GovCloud:
```
--- PASS: TestAccAWSEcsService_withPlacementStrategy_Type_Missing (4.23s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (50.26s)
--- PASS: TestAccAWSEcsService_withARN (65.87s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_External (68.57s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (79.76s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (81.37s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (82.06s)
--- PASS: TestAccAWSEcsService_withForceNewDeployment (96.36s)
--- PASS: TestAccAWSEcsService_withDeploymentCircuitBreaker (96.72s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (96.72s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (96.75s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (61.96s)
--- PASS: TestAccAWSEcsService_withLbChanges (113.90s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (127.01s)
--- SKIP: TestAccAWSEcsService_withServiceRegistries_container (0.00s)
--- SKIP: TestAccAWSEcsService_withServiceRegistriesChanges (0.00s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (139.11s)
--- PASS: TestAccAWSEcsService_withIamRole (77.44s)
--- SKIP: TestAccAWSEcsService_withServiceRegistries (0.00s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndWaitForSteadyState (161.14s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (166.51s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (86.25s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (86.41s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (181.89s)
--- PASS: TestAccAWSEcsService_disappears (73.27s)
--- PASS: TestAccAWSEcsService_ExecuteCommand (92.51s)
--- PASS: TestAccAWSEcsService_basicImport (78.56s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndUpdateWaitForSteadyState (192.59s)
--- PASS: TestAccAWSEcsService_withMultipleCapacityProviderStrategies (140.81s)
--- PASS: TestAccAWSEcsService_Tags (117.88s)
--- PASS: TestAccAWSEcsService_ManagedTags (89.38s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (89.08s)
--- PASS: TestAccAWSEcsService_withMultipleTargetGroups (234.90s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (89.02s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy (251.49s)
--- PASS: TestAccAWSEcsService_withAlb (257.87s)
--- PASS: TestAccAWSEcsService_PropagateTags (194.66s)
--- PASS: TestAccAWSEcsService_withCapacityProviderStrategy (210.47s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (301.17s)
```

Acceptance tests on commercial:
```
--- PASS: TestAccAWSEcsService_withPlacementStrategy_Type_Missing (5.38s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategySetDeploymentMinimum (50.59s)
--- PASS: TestAccAWSEcsService_withForceNewDeployment (62.61s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints (64.58s)
--- PASS: TestAccAWSEcsService_withDaemonSchedulingStrategy (66.14s)
--- PASS: TestAccAWSEcsService_withEcsClusterName (81.91s)
--- PASS: TestAccAWSEcsService_withARN (93.24s)
--- PASS: TestAccAWSEcsService_withPlacementConstraints_emptyExpression (97.12s)
--- PASS: TestAccAWSEcsService_withPlacementStrategy (112.69s)
--- PASS: TestAccAWSEcsService_withLbChanges (118.49s)
--- PASS: TestAccAWSEcsService_withLaunchTypeEC2AndNetworkConfiguration (121.83s)
--- PASS: TestAccAWSEcsService_withReplicaSchedulingStrategy (85.89s)
--- PASS: TestAccAWSEcsService_withRenamedCluster (79.95s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_External (57.08s)
--- PASS: TestAccAWSEcsService_Tags (92.85s)
--- PASS: TestAccAWSEcsService_ExecuteCommand (97.77s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndPlatformVersion (170.84s)
--- PASS: TestAccAWSEcsService_withIamRole (64.78s)
--- PASS: TestAccAWSEcsService_withFamilyAndRevision (95.57s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndUpdateWaitForSteadyState (188.66s)
--- PASS: TestAccAWSEcsService_withServiceRegistries_container (189.72s)
--- PASS: TestAccAWSEcsService_withServiceRegistries (186.38s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargateAndWaitForSteadyState (194.75s)
--- PASS: TestAccAWSEcsService_disappears (69.89s)
--- PASS: TestAccAWSEcsService_withDeploymentValues (85.73s)
--- PASS: TestAccAWSEcsService_withCapacityProviderStrategy (207.89s)
--- PASS: TestAccAWSEcsService_withMultipleCapacityProviderStrategies (120.70s)
--- PASS: TestAccAWSEcsService_ManagedTags (70.19s)
--- PASS: TestAccAWSEcsService_withDeploymentMinimumZeroMaximumOneHundred (85.27s)
--- PASS: TestAccAWSEcsService_basicImport (73.15s)
--- PASS: TestAccAWSEcsService_withAlb (245.39s)
--- PASS: TestAccAWSEcsService_withMultipleTargetGroups (246.50s)
--- PASS: TestAccAWSEcsService_withDeploymentCircuitBreaker (86.10s)
--- PASS: TestAccAWSEcsService_withUnnormalizedPlacementStrategy (86.12s)
--- PASS: TestAccAWSEcsService_healthCheckGracePeriodSeconds (264.41s)
--- PASS: TestAccAWSEcsService_withLaunchTypeFargate (156.41s)
--- PASS: TestAccAWSEcsService_PropagateTags (184.23s)
--- PASS: TestAccAWSEcsService_withDeploymentController_Type_CodeDeploy (242.54s)
--- PASS: TestAccAWSEcsService_withServiceRegistriesChanges (366.84s)
```

**Pull request merged**
