### PR TITLE
feat: implement apprunner_hosted_zone_id

### PR DESCRIPTION
**Pull request by mussinbenarbia**
### Description

Adds a Data Source to get the HostedZoneId of an AWS App Runner service.
This can be consumed for the purpose of using it in an AWS Route53 Alias record, when associating a custom domain with a service.

Similar to https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elbv2/hosted_zone_id_data_source.go

### Relations

There is currently no issue for this. Should I open one?

### References

https://docs.aws.amazon.com/apprunner/latest/dg/manage-custom-domains-route53.html
https://docs.aws.amazon.com/general/latest/gr/apprunner.html

### Output from Acceptance Testing

```console
$ make testacc TESTS=TestAccAppRunnerHostedZoneIDDataSource_basic PKG=apprunner
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/apprunner/... -v -count 1 -parallel 20 -run='TestAccAppRunnerHostedZoneIDDataSource_basic'  -timeout 360m
=== RUN   TestAccAppRunnerHostedZoneIDDataSource_basic
=== PAUSE TestAccAppRunnerHostedZoneIDDataSource_basic
=== CONT  TestAccAppRunnerHostedZoneIDDataSource_basic
--- PASS: TestAccAppRunnerHostedZoneIDDataSource_basic (11.40s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/apprunner     15.457s
```

### CODE REVIEW

**Comment by mussinbenarbia** [comment]
Hello, this is my first contribution, please pardon any oversights. I read and tried to follow the [raising a pull request](https://hashicorp.github.io/terraform-provider-aws/raising-a-pull-request/) guide and I have a couple of questions:

### Implicit ID

The guide mentions:

>Skips id Attribute: The id attribute is implicit for all Terraform resources and does not need to be defined in the schema.

Does this apply to this data source? I feel like the resource id the guide refers to, and the hosted zone ID this data source aims to provide are slightly different. Should the field have a different name? I tried following the existing https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/elbv2/hosted_zone_id_data_source.go

### Should I use SetID and Set()?

I just noticed the guide recommends using `d.Set()` and `d.SetId()`. Maybe related the question above but does `d.SetId()` apply to this use case?


I'll address any comments as soon as possible. Thank you!

**Comment by mussinbenarbia** [comment]
@ewbankkit Thank you for taking a look! 

1. Added an entry to the document as requested in https://github.com/hashicorp/terraform-provider-aws/pull/36288/commits/3c124a484c7aedcefb94b2b3804a256a58ebaa17
2. Addressed [this](https://github.com/hashicorp/terraform-provider-aws/actions/runs/8218831424/job/22516200789) action failure in https://github.com/hashicorp/terraform-provider-aws/pull/36288/commits/bec7cecb87eb836bf811bcd81fe25a5599998a36
3. Addressed [this](https://github.com/hashicorp/terraform-provider-aws/actions/runs/8218831414) action failure in https://github.com/hashicorp/terraform-provider-aws/pull/36288/commits/7ff2cf77d0adfa744f12c892fa4c5c6cc3c48861

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAppRunnerHostedZoneIDDataSource_' PKG=apprunner
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/apprunner/... -v -count 1 -parallel 20  -run=TestAccAppRunnerHostedZoneIDDataSource_ -timeout 360m
=== RUN   TestAccAppRunnerHostedZoneIDDataSource_basic
=== PAUSE TestAccAppRunnerHostedZoneIDDataSource_basic
=== CONT  TestAccAppRunnerHostedZoneIDDataSource_basic
--- PASS: TestAccAppRunnerHostedZoneIDDataSource_basic (18.76s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apprunner	25.373s
```

**Comment by ewbankkit** [comment]
@mussinbenarbia Thanks for the contribution :tada: :clap:.

**Pull request merged**
