### PR TITLE
Add `kms_key_id` attribute to CloudTrail Event Data Store

### LINKED ISSUE #29219: [Enhancement]: Support `kms_key_id` for `aws_cloudtrail_event_data_store` resource
### Description

In `create-event-data-store` API of CloudTrail, `kms_key_id` parameter is supported. However, the `aws_cloudtrail_event_data_store` resource of Terraform AWS Provider doesn't support yet.

### Affected Resource(s) and/or Data Source(s)

* `aws_cloudtrail_event_data_store`

### Potential Terraform Configuration

```terraform
resource "aws_cloudtrail_event_data_store" "this" {
  name           = "test"

  kms_key_id = ...
}
```

### References

- [CloudTrail API: create-event-data-store](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/cloudtrail/create-event-data-store.html)

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

Adds a new attribute `kms_key_id` to the `aws_cloudtrail_event_data_store`

### Relations

Closes #29219

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccCloudTrailEventDataStore_ PKG=cloudtrail
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudtrail/... -v -count 1 -parallel 20 -run='TestAccCloudTrailEventDataStore_'  -timeout 180m
=== RUN   TestAccCloudTrailEventDataStore_basic
=== PAUSE TestAccCloudTrailEventDataStore_basic
=== RUN   TestAccCloudTrailEventDataStore_kmsKeyId
=== PAUSE TestAccCloudTrailEventDataStore_kmsKeyId
=== RUN   TestAccCloudTrailEventDataStore_disappears
=== PAUSE TestAccCloudTrailEventDataStore_disappears
=== RUN   TestAccCloudTrailEventDataStore_tags
=== PAUSE TestAccCloudTrailEventDataStore_tags
=== RUN   TestAccCloudTrailEventDataStore_options
=== PAUSE TestAccCloudTrailEventDataStore_options
=== RUN   TestAccCloudTrailEventDataStore_advancedEventSelector
=== PAUSE TestAccCloudTrailEventDataStore_advancedEventSelector
=== CONT  TestAccCloudTrailEventDataStore_basic
=== CONT  TestAccCloudTrailEventDataStore_tags
=== CONT  TestAccCloudTrailEventDataStore_disappears
=== CONT  TestAccCloudTrailEventDataStore_kmsKeyId
=== CONT  TestAccCloudTrailEventDataStore_advancedEventSelector
=== CONT  TestAccCloudTrailEventDataStore_options
    acctest.go:795: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudTrailEventDataStore_options (2.09s)
--- PASS: TestAccCloudTrailEventDataStore_disappears (16.44s)
--- PASS: TestAccCloudTrailEventDataStore_basic (22.64s)
--- PASS: TestAccCloudTrailEventDataStore_advancedEventSelector (23.26s)
--- PASS: TestAccCloudTrailEventDataStore_kmsKeyId (33.01s)
--- PASS: TestAccCloudTrailEventDataStore_tags (51.69s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail 53.762s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Fixed the failing check @ewbankkit

**Comment by bschaatsbergen** [comment]
👀 @ewbankkit

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccCloudTrailEventDataStore_' PKG=cloudtrail ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/cloudtrail/... -v -count 1 -parallel 3  -run=TestAccCloudTrailEventDataStore_ -timeout 180m
=== RUN   TestAccCloudTrailEventDataStore_basic
=== PAUSE TestAccCloudTrailEventDataStore_basic
=== RUN   TestAccCloudTrailEventDataStore_kmsKeyId
=== PAUSE TestAccCloudTrailEventDataStore_kmsKeyId
=== RUN   TestAccCloudTrailEventDataStore_disappears
=== PAUSE TestAccCloudTrailEventDataStore_disappears
=== RUN   TestAccCloudTrailEventDataStore_tags
=== PAUSE TestAccCloudTrailEventDataStore_tags
=== RUN   TestAccCloudTrailEventDataStore_options
=== PAUSE TestAccCloudTrailEventDataStore_options
=== RUN   TestAccCloudTrailEventDataStore_advancedEventSelector
=== PAUSE TestAccCloudTrailEventDataStore_advancedEventSelector
=== CONT  TestAccCloudTrailEventDataStore_basic
=== CONT  TestAccCloudTrailEventDataStore_advancedEventSelector
=== CONT  TestAccCloudTrailEventDataStore_options
    acctest.go:842: this AWS account must be the management account of an AWS Organization
--- SKIP: TestAccCloudTrailEventDataStore_options (1.17s)
=== CONT  TestAccCloudTrailEventDataStore_tags
--- PASS: TestAccCloudTrailEventDataStore_advancedEventSelector (20.38s)
=== CONT  TestAccCloudTrailEventDataStore_disappears
--- PASS: TestAccCloudTrailEventDataStore_basic (21.83s)
=== CONT  TestAccCloudTrailEventDataStore_kmsKeyId
--- PASS: TestAccCloudTrailEventDataStore_disappears (14.25s)
--- PASS: TestAccCloudTrailEventDataStore_tags (45.63s)
--- PASS: TestAccCloudTrailEventDataStore_kmsKeyId (25.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/cloudtrail	52.855s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Pull request merged**
