### PR TITLE
Add value for the AmazonECSManaged tag in the aws_autoscaling_group resource example

### PR DESCRIPTION
**Pull request by awesome-Leni**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #0000

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
NONE
```

### Reasoning for Change:
1. The `tag` in the `aws_autoscaling_group` resource example lacks a required field for the `tag` - `value`.
2. It doesn't say anywhere in the documentation what's the `value` for the `AmazonECSManaged` tag for a `aws_autoscaling_group` resource should be. The only mention of it, introduced in the following PR: https://github.com/terraform-providers/terraform-provider-aws/pull/11280/files/b44fb0a5a751af019915f7f52909de9b34913884 , was lost.

### CODE REVIEW

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by awesome-Leni** [comment]
Hey, Terraform team! How's it going? What are the next steps for this PR?

**Comment by awesome-Leni** [comment]
@bflad I would like to know what is the next step for this PR?

**Comment by breathingdust** [comment]
LGTM 🚀  Thanks @awesome-Leni!

**Pull request merged**
