### PR TITLE
r/aws_kinesis_firehose_delivery_stream: Add OpenSearch Serverless support

### LINKED ISSUE #32704: Kinesis Data Firehose
### Description

Please add Open Search Serverless to Kinesis Data Firehose as a destination - with the relevant options.

### Affected Resource(s) and/or Data Source(s)

_No response_

### Potential Terraform Configuration

```terraform
name        = "terraform-kinesis-firehose-os"


  opensearch_configuration {
    domain_arn = aws_opensearch_collection.collectionname.arn
    role_arn   = aws_iam_role.firehose_role.arn
    index_name = "test"
```

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by stschulte**
### Description

AWS [added][1] Amazon Kinesis Data Firehose stream delivery to OpenSearch Serverless which is currently not supported by the terraform provider. The provider only supports ElasticSearch and the regular OpenSearch.

In order to support this with terraform we now add a new `opensearchserverless_configuration` block that we can map to a desired
`AmazonOpenSearchServerlessDestinationConfiguration` (see [here][2]).

Please note that this is my first contribution to the provider and my first attempt in go. I don't have access to an AWS account right now, so this code is untested and I did not run acceptance tests. Unfortunately the only thing I can say at this point is "it compiles".

I hope I wil be able to run this against an actual AWS account soon but I wanted to get the MR out there in case
someone else is also planning to work on this so we are not duplicating effort.

[1]: https://aws.amazon.com/about-aws/whats-new/2022/11/amazon-kinesis-data-firehose-support-data-stream-delivery-opensearch-serverless
[2]: https://docs.aws.amazon.com/firehose/latest/APIReference/API_AmazonOpenSearchServerlessDestinationConfiguration.html

### Relations

Closes #32704

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by stschulte** [comment]
I also have two general questions:

1. I was looking for unittests of individual functions in the current resource (e.g. `extractElasticsearchRetryOptions`) but did not find any. Is this correct that these are just tested through acceptance tests? Are there good references to add unit tests?
2. The documentation right now describes different examples. These are not only always self-confined, e.g. https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#opensearch-destination references a resource in ` role_arn`  that is not defined in the same example. I now did the same for the new section. Is this desired so the example section does not explode in size or actually undesired?

**Comment by justinretzolk** [comment]
Hey @stschulte 👋 Thank you for your contribution! You're correct in that these are tested via acceptance tests only; not unit tests. Regarding examples, you're again correct; we don't always include an entire example in the documentation examples, often omitting details for brevity.

**Comment by ewbankkit** [comment]
@stschulte Your contributions were great and I lifted them verbatim into the refactored code 👏.
I am going to add support for [MSK inputs](https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-msk-data-s3-kinesis-data-firehose/) and then get this merged.

**Comment by ewbankkit** [comment]
Notes for MSK cluster input:
Screenshot 2023-10-05 at 6 55 55 AM

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccFirehoseDeliveryStream_' PKG=firehose ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 3  -run=TestAccFirehoseDeliveryStream_ -timeout 720m
=== RUN   TestAccFirehoseDeliveryStream_basic
=== PAUSE TestAccFirehoseDeliveryStream_basic
=== RUN   TestAccFirehoseDeliveryStream_disappears
=== PAUSE TestAccFirehoseDeliveryStream_disappears
=== RUN   TestAccFirehoseDeliveryStream_tags
=== PAUSE TestAccFirehoseDeliveryStream_tags
=== RUN   TestAccFirehoseDeliveryStream_s3WithCloudWatchLogging
=== PAUSE TestAccFirehoseDeliveryStream_s3WithCloudWatchLogging
=== RUN   TestAccFirehoseDeliveryStream_extendedS3basic
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3basic
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversion_enabled
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversion_enabled
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3_externalUpdate
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3_externalUpdate
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionDeserializer_update
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionDeserializer_update
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionHiveJSONSerDe_empty
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionHiveJSONSerDe_empty
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOpenXJSONSerDe_empty
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOpenXJSONSerDe_empty
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOrcSerDe_empty
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOrcSerDe_empty
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionParquetSerDe_empty
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionParquetSerDe_empty
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionSerializer_update
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionSerializer_update
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3_errorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3_errorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3_S3BackupConfiguration_ErrorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3_S3BackupConfiguration_ErrorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3Processing_empty
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3Processing_empty
=== RUN   TestAccFirehoseDeliveryStream_extendedS3KMSKeyARN
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3KMSKeyARN
=== RUN   TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning
=== RUN   TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioningUpdate
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioningUpdate
=== RUN   TestAccFirehoseDeliveryStream_extendedS3Updates
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3Updates
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3_kinesisStreamSource
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3_kinesisStreamSource
=== RUN   TestAccFirehoseDeliveryStream_ExtendedS3_mskClusterSource
=== PAUSE TestAccFirehoseDeliveryStream_ExtendedS3_mskClusterSource
=== RUN   TestAccFirehoseDeliveryStream_redshiftUpdates
=== PAUSE TestAccFirehoseDeliveryStream_redshiftUpdates
=== RUN   TestAccFirehoseDeliveryStream_splunkUpdates
=== PAUSE TestAccFirehoseDeliveryStream_splunkUpdates
=== RUN   TestAccFirehoseDeliveryStream_Splunk_ErrorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_Splunk_ErrorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_httpEndpoint
=== PAUSE TestAccFirehoseDeliveryStream_httpEndpoint
=== RUN   TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration
=== PAUSE TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration
=== RUN   TestAccFirehoseDeliveryStream_elasticSearchUpdates
=== PAUSE TestAccFirehoseDeliveryStream_elasticSearchUpdates
=== RUN   TestAccFirehoseDeliveryStream_elasticSearchEndpointUpdates
=== PAUSE TestAccFirehoseDeliveryStream_elasticSearchEndpointUpdates
=== RUN   TestAccFirehoseDeliveryStream_elasticSearchWithVPCUpdates
=== PAUSE TestAccFirehoseDeliveryStream_elasticSearchWithVPCUpdates
=== RUN   TestAccFirehoseDeliveryStream_Elasticsearch_ErrorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_Elasticsearch_ErrorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_openSearchUpdates
=== PAUSE TestAccFirehoseDeliveryStream_openSearchUpdates
=== RUN   TestAccFirehoseDeliveryStream_openSearchEndpointUpdates
=== PAUSE TestAccFirehoseDeliveryStream_openSearchEndpointUpdates
=== RUN   TestAccFirehoseDeliveryStream_openSearchWithVPCUpdates
=== PAUSE TestAccFirehoseDeliveryStream_openSearchWithVPCUpdates
=== RUN   TestAccFirehoseDeliveryStream_Opensearch_ErrorOutputPrefix
=== PAUSE TestAccFirehoseDeliveryStream_Opensearch_ErrorOutputPrefix
=== RUN   TestAccFirehoseDeliveryStream_openSearchServerlessUpdates
=== PAUSE TestAccFirehoseDeliveryStream_openSearchServerlessUpdates
=== RUN   TestAccFirehoseDeliveryStream_missingProcessing
=== PAUSE TestAccFirehoseDeliveryStream_missingProcessing
=== CONT  TestAccFirehoseDeliveryStream_basic
=== CONT  TestAccFirehoseDeliveryStream_httpEndpoint
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3_errorOutputPrefix
--- PASS: TestAccFirehoseDeliveryStream_basic (130.83s)
=== CONT  TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioningUpdate
--- PASS: TestAccFirehoseDeliveryStream_httpEndpoint (165.24s)
=== CONT  TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_errorOutputPrefix (185.87s)
=== CONT  TestAccFirehoseDeliveryStream_extendedS3KMSKeyARN
--- PASS: TestAccFirehoseDeliveryStream_extendedS3KMSKeyARN (121.75s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3Processing_empty
--- PASS: TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning (152.44s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3_S3BackupConfiguration_ErrorOutputPrefix
--- PASS: TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioningUpdate (293.09s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionDeserializer_update
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3Processing_empty (144.75s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionSerializer_update
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_S3BackupConfiguration_ErrorOutputPrefix (199.95s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionParquetSerDe_empty
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionSerializer_update (213.83s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOrcSerDe_empty
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionDeserializer_update (242.49s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOpenXJSONSerDe_empty
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionParquetSerDe_empty (168.54s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionHiveJSONSerDe_empty
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOpenXJSONSerDe_empty (139.41s)
=== CONT  TestAccFirehoseDeliveryStream_extendedS3Updates
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOrcSerDe_empty (140.03s)
=== CONT  TestAccFirehoseDeliveryStream_Splunk_ErrorOutputPrefix
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionHiveJSONSerDe_empty (129.39s)
=== CONT  TestAccFirehoseDeliveryStream_splunkUpdates
--- PASS: TestAccFirehoseDeliveryStream_Splunk_ErrorOutputPrefix (149.89s)
=== CONT  TestAccFirehoseDeliveryStream_extendedS3basic
--- PASS: TestAccFirehoseDeliveryStream_extendedS3Updates (162.08s)
=== CONT  TestAccFirehoseDeliveryStream_redshiftUpdates
--- PASS: TestAccFirehoseDeliveryStream_splunkUpdates (162.14s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3_externalUpdate
--- PASS: TestAccFirehoseDeliveryStream_extendedS3basic (129.86s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversion_enabled
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_externalUpdate (141.27s)
=== CONT  TestAccFirehoseDeliveryStream_tags
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversion_enabled (172.05s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3_mskClusterSource
--- PASS: TestAccFirehoseDeliveryStream_tags (175.63s)
=== CONT  TestAccFirehoseDeliveryStream_s3WithCloudWatchLogging
--- PASS: TestAccFirehoseDeliveryStream_redshiftUpdates (395.16s)
=== CONT  TestAccFirehoseDeliveryStream_ExtendedS3_kinesisStreamSource
--- PASS: TestAccFirehoseDeliveryStream_s3WithCloudWatchLogging (101.70s)
=== CONT  TestAccFirehoseDeliveryStream_disappears
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_kinesisStreamSource (81.31s)
=== CONT  TestAccFirehoseDeliveryStream_openSearchUpdates
--- PASS: TestAccFirehoseDeliveryStream_disappears (96.37s)
=== CONT  TestAccFirehoseDeliveryStream_openSearchWithVPCUpdates
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_mskClusterSource (538.83s)
=== CONT  TestAccFirehoseDeliveryStream_openSearchEndpointUpdates
--- PASS: TestAccFirehoseDeliveryStream_openSearchUpdates (1959.72s)
=== CONT  TestAccFirehoseDeliveryStream_Opensearch_ErrorOutputPrefix
--- PASS: TestAccFirehoseDeliveryStream_openSearchEndpointUpdates (1983.42s)
=== CONT  TestAccFirehoseDeliveryStream_missingProcessing
--- PASS: TestAccFirehoseDeliveryStream_missingProcessing (112.75s)
=== CONT  TestAccFirehoseDeliveryStream_openSearchServerlessUpdates
--- PASS: TestAccFirehoseDeliveryStream_openSearchWithVPCUpdates (2763.90s)
=== CONT  TestAccFirehoseDeliveryStream_elasticSearchEndpointUpdates
--- PASS: TestAccFirehoseDeliveryStream_openSearchServerlessUpdates (505.40s)
=== CONT  TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration
--- PASS: TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration (196.31s)
=== CONT  TestAccFirehoseDeliveryStream_Elasticsearch_ErrorOutputPrefix
--- PASS: TestAccFirehoseDeliveryStream_Opensearch_ErrorOutputPrefix (1937.63s)
=== CONT  TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix
--- PASS: TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix (191.20s)
=== CONT  TestAccFirehoseDeliveryStream_elasticSearchUpdates
--- PASS: TestAccFirehoseDeliveryStream_elasticSearchEndpointUpdates (1718.77s)
=== CONT  TestAccFirehoseDeliveryStream_elasticSearchWithVPCUpdates
--- PASS: TestAccFirehoseDeliveryStream_Elasticsearch_ErrorOutputPrefix (1804.50s)
--- PASS: TestAccFirehoseDeliveryStream_elasticSearchUpdates (1678.97s)
--- PASS: TestAccFirehoseDeliveryStream_elasticSearchWithVPCUpdates (2472.77s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	8453.764s
```

**Pull request merged**
