### PR TITLE
Add secondary IPs to AWS NAT Gateway

### LINKED ISSUE #31229: [Enhancement]: Allow secondary Elastic IPs in Nat Gateway configuration
### Description

Allow association of secondary Elastic IPs. I believe you can associate up to six additional ones.

### Affected Resource(s) and/or Data Source(s)

aws_nat_gateway

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

**Note:** the secondary IP related properties are not returned by the API, resulting in being unable to import these specific arguments.

### Relations

Closes #31229.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29471.

### Output from Acceptance Testing

```
$make testacc TESTARGS='-run=TestAccVPCNATGateway_secondaryAllocationIds\|TestAccVPCNATGateway_secondaryPrivateIpAddresses\|TestAccVPCNATGateway_secondaryPrivateIpAddressCount\|TestAccVPCNATGateway_secondaryPrivateIPAddresses_private' PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 20  -run=TestAccVPCNATGateway_secondaryAllocationIds\|TestAccVPCNATGateway_secondaryPrivateIpAddresses\|TestAccVPCNATGateway_secondaryPrivateIpAddressCount\|TestAccVPCNATGateway_secondaryPrivateIPAddresses_private -timeout 180m
=== RUN   TestAccVPCNATGateway_secondaryPrivateIPAddresses_private
=== PAUSE TestAccVPCNATGateway_secondaryPrivateIPAddresses_private
=== CONT  TestAccVPCNATGateway_secondaryPrivateIPAddresses_private
--- PASS: TestAccVPCNATGateway_secondaryPrivateIPAddresses_private (168.39s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@bschaatsbergen Looking good so far 👏. I think we need to be able to support updates for these new arguments via

* [`AssignPrivateNatGatewayAddress`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssignPrivateNatGatewayAddress.html)
* [`UnassignPrivateNatGatewayAddress`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_UnassignPrivateNatGatewayAddress.html)
* [`AssociateNatGatewayAddress`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AssociateNatGatewayAddress.html)
* [`DisassociateNatGatewayAddress`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DisassociateNatGatewayAddress.html)

**Comment by ewbankkit** [comment]
No worries, those APIs aren't listed in the NAT gateways section of the [Amazon VPC actions](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/OperationList-query-vpc.html) documentation.

**Comment by yushao2** [comment]
This is a welcome change, hoping it will be merged soon 💯

**Comment by bschaatsbergen** [comment]
@yushao2 we aim to have it merged as soon as possible, it's on the core team's radar 🤙

**Comment by benben** [comment]
Can we please have an ETA on this? THANKS!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCNATGatewayDataSource_' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCNATGatewayDataSource_ -timeout 180m
=== RUN   TestAccVPCNATGatewayDataSource_basic
=== PAUSE TestAccVPCNATGatewayDataSource_basic
=== CONT  TestAccVPCNATGatewayDataSource_basic
--- PASS: TestAccVPCNATGatewayDataSource_basic (213.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	218.773s
```
```
% make testacc TESTARGS='-run=TestAccVPCNATGateway_' PKG=ec2 ACCTEST_PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccVPCNATGateway_ -timeout 180m
=== RUN   TestAccVPCNATGateway_basic
=== PAUSE TestAccVPCNATGateway_basic
=== RUN   TestAccVPCNATGateway_disappears
=== PAUSE TestAccVPCNATGateway_disappears
=== RUN   TestAccVPCNATGateway_ConnectivityType_private
=== PAUSE TestAccVPCNATGateway_ConnectivityType_private
=== RUN   TestAccVPCNATGateway_privateIP
=== PAUSE TestAccVPCNATGateway_privateIP
=== RUN   TestAccVPCNATGateway_tags
=== PAUSE TestAccVPCNATGateway_tags
=== RUN   TestAccVPCNATGateway_secondaryAllocationIDs
=== PAUSE TestAccVPCNATGateway_secondaryAllocationIDs
=== RUN   TestAccVPCNATGateway_secondaryPrivateIPAddressCount
=== PAUSE TestAccVPCNATGateway_secondaryPrivateIPAddressCount
=== RUN   TestAccVPCNATGateway_secondaryPrivateIPAddresses
=== PAUSE TestAccVPCNATGateway_secondaryPrivateIPAddresses
=== RUN   TestAccVPCNATGateway_SecondaryPrivateIPAddresses_private
=== PAUSE TestAccVPCNATGateway_SecondaryPrivateIPAddresses_private
=== CONT  TestAccVPCNATGateway_basic
=== CONT  TestAccVPCNATGateway_secondaryAllocationIDs
--- PASS: TestAccVPCNATGateway_basic (229.49s)
=== CONT  TestAccVPCNATGateway_privateIP
--- PASS: TestAccVPCNATGateway_privateIP (205.65s)
=== CONT  TestAccVPCNATGateway_tags
--- PASS: TestAccVPCNATGateway_secondaryAllocationIDs (544.29s)
=== CONT  TestAccVPCNATGateway_secondaryPrivateIPAddresses
--- PASS: TestAccVPCNATGateway_tags (241.03s)
=== CONT  TestAccVPCNATGateway_SecondaryPrivateIPAddresses_private
--- PASS: TestAccVPCNATGateway_secondaryPrivateIPAddresses (535.22s)
=== CONT  TestAccVPCNATGateway_ConnectivityType_private
--- PASS: TestAccVPCNATGateway_ConnectivityType_private (216.14s)
=== CONT  TestAccVPCNATGateway_disappears
--- PASS: TestAccVPCNATGateway_SecondaryPrivateIPAddresses_private (629.49s)
=== CONT  TestAccVPCNATGateway_secondaryPrivateIPAddressCount
--- PASS: TestAccVPCNATGateway_disappears (180.62s)
--- PASS: TestAccVPCNATGateway_secondaryPrivateIPAddressCount (183.41s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	1494.269s
```

**Comment by AladinZaier** [comment]
Thank you for your contributions @bschaatsbergen  @FabianPonce 🎉 👏 Keep being awesome

**Comment by bschaatsbergen** [comment]
> Thank you for your contributions @bschaatsbergen  @FabianPonce 🎉 👏 Keep being awesome

With pleasure @AladinZaier !

**Pull request merged**
