### PR TITLE
feat: Enable S3-compatible providers with no support for bucket tagging

### PR DESCRIPTION
**Pull request by killzoner**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
* resource/aws_s3_bucket: Add `skip_get_s3_bucket_list_tags` to enable S3-compatible providers with no support for bucket tagging (ie https://wasabi.com)
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by killzoner** [comment]
Hi there, this is a WIP work, the base idea is here though.

The motivation behind this is to be able to work with some alternative S3-compatible providers which don't support bucket tagging. I checked and `S3BucketListTags` seems to be used only in `aws/resource_aws_s3_bucket.go` so it would not be a big change.

Currently looking into the contribution guides to add tests, even though it's not much change.
Still need to figure out to how to test it locally too.

One thing that maybe somebody can tell me is if it would be preferable to add default empty tag `map` on `d *schema.ResourceData` or if it's ok as is.

**Comment by bflad** [comment]
Hi @killzoner 👋  Thank you for submitting this! Our preference (also why I marked this with the `proposal` label) when implementing best effort support with these alternative implementations is typically to ignore their specific errors with specific API calls, instead of requiring operators to add extra/manual configuration. For example (the `NotImplemented` part):

https://github.com/terraform-providers/terraform-provider-aws/blob/818942acfd59940af2295587cca2b81a6aa4e895/aws/resource_aws_s3_bucket.go#L947

To get the correct error code/message, you will need to have the error handy. Let us know if you have questions. 👍

**Comment by killzoner** [comment]
Hi @bflad thanks for the input! Doing that soon then

**Comment by killzoner** [comment]
Hi @bflad I changed the modifications according to your review, it's working :+1: 
One thing I can't seem to understad is when I do an `plan` after creating a bucket, I get always the same change planned like this

```
- object_lock_configuration {
}

- replication_configuration {
}

- server_side_encryption_configuration {
}
```
even though I didn't define any of this.

Any idea or working this around? I'll look after other possibles fixes if not

**Pull request closed without merging**
