### PR TITLE
resource/aws_instance: update user data on change

### LINKED ISSUE #23: Feature Request: Stop, don't destroy instance on user-data update
_This issue was originally opened by @jwaldrip as hashicorp/terraform#1887. It was migrated here as part of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._

<hr>

when updating user-data, its not required to destroy the instance. In fact, this can be devastating to a etcd cluster. What would be acceptable is for the machines to be stopped, userdata updated, and then started.

### PR DESCRIPTION
**Pull request by Dudesons**
Fixes #23

### CODE REVIEW

**Comment by Dudesons** [comment]
Hi,

Can I have some indications if I have to update or create a new test (with vpc or I can reuse one from an other test) to test this pr.
There is something I have to do more ?

@bflad

**Comment by bflad** [comment]
@Dudesons an additional acceptance test should be added and existing acceptance testing should be performed if possible. Please let us know if we can clarify anything in the [CONTRIBUTING documentation](https://github.com/terraform-providers/terraform-provider-aws/blob/master/.github/CONTRIBUTING.md#enhancementbugfix-to-a-resource)

**Comment by et304383** [comment]
This PR is nearly 4 years in the making.  What has to happen to move this along?  Terraform needs to catch up to CloudFormation here.

**Comment by Dudesons** [comment]
@bflad Thank you for information I'll take a moment in the end of the week or next week to run and add the test

@et304383

**Comment by rogerhu** [comment]
Rebased and opened a separate PR with an acceptance test -- can someone review?

**Comment by nsvijay04b1** [comment]
Hi
When can we expect this? thanks!

**Comment by anGie44** [comment]
Hi @Dudesons , thank you for submitting this PR and apologies we didn't get to it sooner. The associated issue #23 is now in our queue, however, and in an effort to get these changes merged in a timely manner I'm going to review https://github.com/hashicorp/terraform-provider-aws/pull/18043 which is based off the code changes here with the addition of some needed tests.

**Pull request closed without merging**
