### PR TITLE
Add timeout support for EBS Snapshot copies

### LINKED ISSUE #14354: Add timeout support for aws_ebs_snapshot_copy
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for snapshot copies, specifically creation.  When copying large snapshots, especially between regions, it is virtually guaranteed that the default 10 minutes is inadequate. 

### New or Affected Resource(s)

* aws_ebs_snapshot_copy

### Potential Terraform Configuration

```hcl
resource "aws_ebs_snapshot" "snapshot" {
  volume_id   = "vol-fffffffffffffffff"
  description = "My Volume"

  # ...

  timeouts {
    create = "3h"
  }
}

resource "aws_ebs_snapshot_copy" "copy" {
  provider = "aws.virginia"

  source_snapshot_id = "${aws_ebs_snapshot.snapshot.id}"
  source_region      = "${data.aws_region.current.name}"

  description = "${aws_ebs_snapshot.snapshot.description}"
  encrypted   = "${aws_ebs_snapshot.snapshot.encrypted}"
  kms_key_id  = "${aws_ebs_snapshot.snapshot.kms_key_id}"
  tags        = "${aws_ebs_snapshot.snapshot.tags}"

  timeouts {
    create = "3h"
  }
}
```

### LINKED ISSUE #17186: aws_ebs_snapshot resource supports a timeouts block, but aws_ebs_snapshot_copy does not
aws_ebs_snapshot resource supports a timeouts block, so you can add this to increase the length of time a terraform apply waits for the snapshot creation to complete.

aws_ebs_snapshot_copy does not support this block. This means if you create a snapshot, then create a snapshot_copy, if the first snapshot takes longer than 10 minutes to create then you can add a timeout to increase this, but the snapshot_copy will always fail because it will take longer than 10 minutes.

Taking the example from the aws_ebs_snapshot_copy resource page:

```
resource "aws_ebs_volume" "example" {
  availability_zone = "us-west-2a"
  size              = 40
}

resource "aws_ebs_snapshot" "example_snapshot" {
  volume_id = aws_ebs_volume.example.id

  timeouts {
    create = "60m"
  }
}

resource "aws_ebs_snapshot_copy" "example_copy" {
  source_snapshot_id = aws_ebs_snapshot.example_snapshot.id
  source_region      = "us-west-2"
  encrypted          = true
  kms_key_id         = "<arn of a different key>"
}
```

aws_ebs_snapshot_copy.example_copy will always fail if you've had to add the timeouts block to aws_ebs_snapshot.example_snapshot in order to get that resource to create successfully.

```
module.storage.module.example.aws_ebs_snapshot.example_snapshot["vol01"]: Still creating... [17m10s elapsed]
module.storage.module.example.aws_ebs_snapshot.example_snapshot["vol01"]: Creation complete after 17m17s [id=snap-xxxx]
module.storage.module.example.aws_ebs_snapshot_copy.example_copy["vol01"]: Creating...
...
module.storage.module.example.aws_ebs_snapshot_copy.example_copy["vol01"]: Still creating... [9m40s elapsed]

Error: ResourceNotReady: exceeded wait attempts

  on storage/example/create_snapshots.tf line 14, in resource "aws_ebs_snapshot_copy" "example_copy":
  14: resource "aws_ebs_snapshot_copy" "example_copy" {
```

using terraform v0.12.25 and aws provider 2.64.

I've used the example of specifying a different KMS key to the snapshot_copy, to show my use case which is creating a snapshot using a KMS key which is different to the one that the volume is encrypted with (which would force the entire snapshot to be re-processed by AWS, so it would take the same length of time to create the copy as it did the full-volume snapshot).

### PR DESCRIPTION
**Pull request by ahorner**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Description

These copies can take an exorbitant amount of time to run, and if a
snapshot requires a custom timeout configuration, chances are
extremely high that any attempt to copy that snapshot will also exceed
the default 10-minute timeout.

Thankfully, the API is very similar between the base snapshot resource
and the copy resource, so we can borrow the logic almost wholesale
from the EBS snapshot to support this configuration block
appropriately.

Closes #14354.
Closes #17186.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSEbsSnapshotCopy_basic'

TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSEbsSnapshotCopy -timeout 180m
=== RUN   TestAccAWSEbsSnapshotCopy_basic
=== PAUSE TestAccAWSEbsSnapshotCopy_basic
=== RUN   TestAccAWSEbsSnapshotCopy_tags
=== PAUSE TestAccAWSEbsSnapshotCopy_tags
=== RUN   TestAccAWSEbsSnapshotCopy_withDescription
=== PAUSE TestAccAWSEbsSnapshotCopy_withDescription
=== RUN   TestAccAWSEbsSnapshotCopy_withRegions
=== PAUSE TestAccAWSEbsSnapshotCopy_withRegions
=== RUN   TestAccAWSEbsSnapshotCopy_withKms
=== PAUSE TestAccAWSEbsSnapshotCopy_withKms
=== RUN   TestAccAWSEbsSnapshotCopy_disappears
=== PAUSE TestAccAWSEbsSnapshotCopy_disappears
=== CONT  TestAccAWSEbsSnapshotCopy_basic
=== CONT  TestAccAWSEbsSnapshotCopy_withRegions
=== CONT  TestAccAWSEbsSnapshotCopy_withDescription
=== CONT  TestAccAWSEbsSnapshotCopy_disappears
=== CONT  TestAccAWSEbsSnapshotCopy_withKms
=== CONT  TestAccAWSEbsSnapshotCopy_tags
--- PASS: TestAccAWSEbsSnapshotCopy_basic (70.99s)
--- PASS: TestAccAWSEbsSnapshotCopy_withKms (71.78s)
--- PASS: TestAccAWSEbsSnapshotCopy_withDescription (71.83s)
--- PASS: TestAccAWSEbsSnapshotCopy_disappears (87.11s)
--- PASS: TestAccAWSEbsSnapshotCopy_tags (106.00s)
--- PASS: TestAccAWSEbsSnapshotCopy_withRegions (379.15s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	382.381s
```

### CODE REVIEW

**Comment by devindice** [comment]
This was crippling my company after switching to encrypted snapshots.

To compile from source:
git clone https://github.com/hashicorp/terraform-provider-aws.git
cd terraform-provider-aws
Install all dependancies: go mod vendor
Make the directory: mkdir -p ~/.terraform.d/plugins/your.domain/yourCompany/aws/3.42.0/linux_amd64/
Compile: go build -o terraform-provider-aws

mv terraform-provider-aws  ~/.terraform.d/plugins/your.domain/yourCompany/aws/3.42.0/linux_amd64/terraform-provider-aws

/opt/ecolane/terraform/providers.tf:

terraform {
    required_providers {
        aws = {
            source = "your.domain/yourCompany/aws"
            version = "~> 3.0"
        }
    }
}

**Comment by devindice** [comment]
This was crippling my company after switching to encrypted snapshots.

To compile from source:
git clone https://github.com/hashicorp/terraform-provider-aws.git
cd terraform-provider-aws
Checkout version and add code from this commit
Install all dependancies: go mod vendor
Make the directory: mkdir -p ~/.terraform.d/plugins/your.domain/yourCompany/aws/3.42.0/linux_amd64/
Compile: go build -o terraform-provider-aws

mv terraform-provider-aws ~/.terraform.d/plugins/your.domain/yourCompany/aws/3.42.0/linux_amd64/terraform-provider-aws

Path/terraform/providers.tf:

terraform {
required_providers {
aws = {
source = "your.domain/yourCompany/aws"
version = "~> 3.0"
}
}
}

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2EBSSnapshotCopy_' PKG=ec2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 2  -run=TestAccEC2EBSSnapshotCopy_ -timeout 180m
=== RUN   TestAccEC2EBSSnapshotCopy_basic
=== PAUSE TestAccEC2EBSSnapshotCopy_basic
=== RUN   TestAccEC2EBSSnapshotCopy_disappears
=== PAUSE TestAccEC2EBSSnapshotCopy_disappears
=== RUN   TestAccEC2EBSSnapshotCopy_tags
=== PAUSE TestAccEC2EBSSnapshotCopy_tags
=== RUN   TestAccEC2EBSSnapshotCopy_withDescription
=== PAUSE TestAccEC2EBSSnapshotCopy_withDescription
=== RUN   TestAccEC2EBSSnapshotCopy_withRegions
=== PAUSE TestAccEC2EBSSnapshotCopy_withRegions
=== RUN   TestAccEC2EBSSnapshotCopy_withKMS
=== PAUSE TestAccEC2EBSSnapshotCopy_withKMS
=== RUN   TestAccEC2EBSSnapshotCopy_storageTier
=== PAUSE TestAccEC2EBSSnapshotCopy_storageTier
=== CONT  TestAccEC2EBSSnapshotCopy_basic
=== CONT  TestAccEC2EBSSnapshotCopy_withRegions
--- PASS: TestAccEC2EBSSnapshotCopy_basic (75.74s)
=== CONT  TestAccEC2EBSSnapshotCopy_withDescription
--- PASS: TestAccEC2EBSSnapshotCopy_withRegions (79.96s)
=== CONT  TestAccEC2EBSSnapshotCopy_tags
--- PASS: TestAccEC2EBSSnapshotCopy_withDescription (73.59s)
=== CONT  TestAccEC2EBSSnapshotCopy_disappears
--- PASS: TestAccEC2EBSSnapshotCopy_tags (105.01s)
=== CONT  TestAccEC2EBSSnapshotCopy_storageTier
--- PASS: TestAccEC2EBSSnapshotCopy_disappears (70.64s)
=== CONT  TestAccEC2EBSSnapshotCopy_withKMS
--- PASS: TestAccEC2EBSSnapshotCopy_withKMS (69.57s)
--- PASS: TestAccEC2EBSSnapshotCopy_storageTier (145.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	341.614s
```

**Comment by ewbankkit** [comment]
@ahorner Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
```console
% make providerlint golangci-lint
==> Checking source code with providerlint...
==> Checking source code with golangci-lint...
```

**Pull request merged**
