### PR TITLE
Example of using a non-VPC endpoint prefix with a security group

### PR DESCRIPTION
**Pull request by acdha**
I wanted to add an example which shows how to use the `aws_prefix_list`
resource to look up a prefix list which wasn't based on a VPC endpoint,
especially because there's a financial incentive to use S3 Gateway
interfaces instead of VPC endpoint interfaces.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### CODE REVIEW

**Comment by acdha** [comment]
Note for reviewers: I added links to the data sources referenced but noticed that this doesn't appear to be commonly done in the rest of the documentation. If there's a policy against doing that (I'd guess something about the paths used in the repository versus the registry documentation site?) I can remove them.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@acdha Thanks for the contribution :tada: :clap:.

**Comment by acdha** [comment]
Thanks for the fast review!

**Pull request merged**
