### PR TITLE
fix: update documentation for AWS ALB health check paths

### PR DESCRIPTION
**Pull request by RoseSecurity**
### Description

- Documentation update with correct values for gRPC health check methods. The current docs state that the default is `/Amazon Web Services.ALB/healthcheck`, but it is really `/AWS.ALB/healthcheck`

### Output from Acceptance Testing

- Documentation update

### References

- [AWS Docs](https://docs.aws.amazon.com/elasticloadbalancing/latest/application/target-group-health-checks.html)

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM :tada:

**Comment by jar-b** [comment]
Thanks for your contribution, @RoseSecurity! 👍 

I reverted the changes to the CDKTF pages. We have an automated job which handles conversion of the standard Terraform content into the CDKTF pages, so we typically skip modifying them and allow the automated job to pick up changes instead.

**Review by YakDriver — APPROVED** [review]
LTMG 🎉

**Comment by RoseSecurity** [comment]
Thank you for the quick turnaround time! Appreciate it

**Pull request merged**
