### PR TITLE
aws_quicksight_data_set: Add support for configuring refresh properties

### LINKED ISSUE #30744: [Enhancement]: Add support for QuickSight dataset refresh properties
### Description

Now that the [aws_quicksight_ingestion](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/quicksight_ingestion) resource has landed it should be possible to use the [PutDataSetRefreshProperties](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_PutDataSetRefreshProperties.html) API to fully configure incremental refresh via Terraform.

### Affected Resource(s) and/or Data Source(s)

`aws_quicksight_data_set`

### Potential Terraform Configuration

```terraform
resource "aws_quicksight_data_set" "test" {

  data_set_id    = "test"

  // ... snip ...

  refresh_properties {
    refresh_configuration {
      incremental_refresh {
        lookback_window {
          column_name = "col"
          size        = 12
          size_unit   = "HOUR" // HOUR | DAY | WEEK
        }
      }
    }
  }
}
```

Alternatively, this could be implemented as a new resource:

```terraform
resource "aws_quicksight_data_set_refresh_properties" "test" {
  data_set_id = "id"
  
  refresh_configuration {
    incremental_refresh {
      lookback_window {
        column_name = "col"
        size        = 12
        size_unit   = "HOUR" // HOUR | DAY | WEEK
      }
    }
  }
}

```

Not sure what direction would be most appropriate.

### References

* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_PutDataSetRefreshProperties.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DescribeDataSetRefreshProperties.html
* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_DeleteDataSetRefreshProperties.html

Relates to https://github.com/hashicorp/terraform-provider-aws/issues/10990

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by g-dx**
### Description

This PR updates the existing `aws_quicksight_data_set` resource to allow configuration of [refresh properties](https://docs.aws.amazon.com/quicksight/latest/user/refreshing-imported-data.html#refresh-spice-data-incremental).

### Relations

Closes #30744
Relates To https://github.com/hashicorp/terraform-provider-aws/issues/10990

### Output from Acceptance Testing

```
make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_'  -timeout 180m
=== RUN   TestAccQuickSightDataSet_basic
=== PAUSE TestAccQuickSightDataSet_basic
=== RUN   TestAccQuickSightDataSet_disappears
=== PAUSE TestAccQuickSightDataSet_disappears
=== RUN   TestAccQuickSightDataSet_columnGroups
=== PAUSE TestAccQuickSightDataSet_columnGroups
=== RUN   TestAccQuickSightDataSet_columnLevelPermissionRules
=== PAUSE TestAccQuickSightDataSet_columnLevelPermissionRules
=== RUN   TestAccQuickSightDataSet_dataSetUsageConfiguration
=== PAUSE TestAccQuickSightDataSet_dataSetUsageConfiguration
=== RUN   TestAccQuickSightDataSet_fieldFolders
=== PAUSE TestAccQuickSightDataSet_fieldFolders
=== RUN   TestAccQuickSightDataSet_logicalTableMap
=== PAUSE TestAccQuickSightDataSet_logicalTableMap
=== RUN   TestAccQuickSightDataSet_permissions
=== PAUSE TestAccQuickSightDataSet_permissions
=== RUN   TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== PAUSE TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== RUN   TestAccQuickSightDataSet_refreshProperties
=== PAUSE TestAccQuickSightDataSet_refreshProperties
=== RUN   TestAccQuickSightDataSet_tags
=== PAUSE TestAccQuickSightDataSet_tags
=== CONT  TestAccQuickSightDataSet_basic
=== CONT  TestAccQuickSightDataSet_logicalTableMap
=== CONT  TestAccQuickSightDataSet_columnLevelPermissionRules
=== CONT  TestAccQuickSightDataSet_refreshProperties
=== CONT  TestAccQuickSightDataSet_fieldFolders
=== CONT  TestAccQuickSightDataSet_permissions
=== CONT  TestAccQuickSightDataSet_dataSetUsageConfiguration
=== CONT  TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== CONT  TestAccQuickSightDataSet_columnGroups
=== CONT  TestAccQuickSightDataSet_disappears
=== CONT  TestAccQuickSightDataSet_tags
--- PASS: TestAccQuickSightDataSet_disappears (41.91s)
--- PASS: TestAccQuickSightDataSet_columnGroups (44.04s)
--- PASS: TestAccQuickSightDataSet_refreshProperties (46.34s)
--- PASS: TestAccQuickSightDataSet_basic (48.23s)
--- PASS: TestAccQuickSightDataSet_dataSetUsageConfiguration (50.21s)
--- PASS: TestAccQuickSightDataSet_logicalTableMap (50.74s)
--- PASS: TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration (50.82s)
--- PASS: TestAccQuickSightDataSet_fieldFolders (51.19s)
--- PASS: TestAccQuickSightDataSet_columnLevelPermissionRules (51.63s)
--- PASS: TestAccQuickSightDataSet_tags (86.45s)
--- PASS: TestAccQuickSightDataSet_permissions (93.00s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	93.087s

```

### CODE REVIEW

**Comment by jar-b** [comment]
Hi @g-dx - thanks for your contribution! All the changes look great, but I'm running into issues with the newly added acceptance test. 

1. The test requires the QuickSight service role to have permissions to the Amazon Athena service. This results in an error like:

**Comment by g-dx** [comment]
Hey @jar-b, I've spent some time looking into the errors you saw and here is what I've found so far.

0. I'm unable to recreate the issue you are seeing & I can't find any docs which shed light on the `"Unable to put refresh properties for dataset: arn:aws:quicksight:us-west-2:<redacted>:dataset/tf-acc-test-7917405396813809390 due to dependency exception"` error message. The only difference of note is that I run the acceptance test with `AWS_DEFAULT_REGION=eu-west-1` set because that's where my QuickSight account resides. I could open an AWS support case for further info but they will probably want the ARN of the broken resource and as I can't recreate it that will be tricky.

1. An important point you **_didn't_** mention when enabling Athena access in your QuickSight account is _also_ allowing read + write access to the S3 bucket which stores the Athena query results (i.e. the one connected to the `primary` Athena workspace). You must allow full access to this otherwise you'll get failures to import any data.

2. I've never had to configure any AWS Lake Formation permissions to get Athena to work so I'm not sure what's happening. Maybe your AWS account has some specific setup there?

3. Unless I've missed something there is no API to ask QuickSight which IAM role it is using when accessing other AWS services so I'm not sure how exactly I could write a PreCheck for the test.

Sorry I can't be of more help here 😕

**Comment by jar-b** [comment]
Hey @g-dx 👋 - Thanks for taking another look, and apologize for my delayed response! 

I have some internal commitments through the end of this week and then I'm hoping to get back to researching this. Regardless, I don't want to hold up a valid enhancement due to account configuration issues on our end. If it can't be quickly resolved I think we can simply gate the test (ex. require a `QUICKSIGHT_AURORA_TESTING_ENABLED` environment variable) so its skipped by default. 

Hopefully its a simple configuration issue and that won't be necessary, but just want to add some transparency to next steps. Thanks again!

**Comment by g-dx** [comment]
@jar-b - I've added the new env var `QUICKSIGHT_ATHENA_TESTING_ENABLED` you suggested as a gate on the acceptance test.

Feel free to remove as and when you make progress on (hopefully) resolving the configuration issue.

**Comment by jar-b** [comment]
Hey @g-dx - good news! Your second point above about the `primary` Athena settings resolved the initial issue. The test is no longer hanging, however, I am seeing a failure during import verification.

```console
$ QUICKSIGHT_ATHENA_TESTING_ENABLED=true make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_refreshProperties
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_refreshProperties'  -timeout 180m
=== RUN   TestAccQuickSightDataSet_refreshProperties
=== PAUSE TestAccQuickSightDataSet_refreshProperties
=== CONT  TestAccQuickSightDataSet_refreshProperties
    data_set_test.go:355: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        -       "refresh_properties.#":                                                                             "1",
        -       "refresh_properties.0.%":                                                                           "1",
        -       "refresh_properties.0.refresh_configuration.#":                                                     "1",
        -       "refresh_properties.0.refresh_configuration.0.%":                                                   "1",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.#":                               "1",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.0.%":                             "1",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.0.lookback_window.#":             "1",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.0.lookback_window.0.%":           "3",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.0.lookback_window.0.column_name": "column1",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.0.lookback_window.0.size":        "1",
        -       "refresh_properties.0.refresh_configuration.0.incremental_refresh.0.lookback_window.0.size_unit":   "DAY",
          }
--- FAIL: TestAccQuickSightDataSet_refreshProperties (26.62s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 29.815s
FAIL
make: *** [testacc] Error 1
```

Is this test still passing for you? I suspect this could still be related to some permissions/configuration issue, but wanted to confirm its passing in an alternative environment before investigating further.

**Comment by g-dx** [comment]
Will check this later tonight and get back to you ASAP.

**Comment by g-dx** [comment]
Just double checked this and the test passes for me:

```
$ QUICKSIGHT_ATHENA_TESTING_ENABLED=true make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_refreshProperties

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_refreshProperties'  -timeout 180m
=== RUN   TestAccQuickSightDataSet_refreshProperties
=== PAUSE TestAccQuickSightDataSet_refreshProperties
=== CONT  TestAccQuickSightDataSet_refreshProperties
--- PASS: TestAccQuickSightDataSet_refreshProperties (27.21s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	27.278s
```

No idea how AWS configuration could be affecting Terraform import ... :thinking: 

(NOTE: I've rebased by changes on the latest from `main`)

**Comment by jar-b** [comment]
Thanks for confirming, @g-dx. I'm still seeing failures, so I'll try to do some manual investigation later this week. If nothing turns up I think we can still merge given you've got passing tests, but I'm hoping to get the permissions figured out and documented in the new test if possible.

**Comment by jar-b** [comment]
After much head scratching and consternation, I was able to determine the issue was with the default LakeFormation data catalog settings. From the [AWS documentation](https://docs.aws.amazon.com/lake-formation/latest/dg/change-settings.html) these settings seem to be changing from previous Glue defaults, so I'm leaning towards keeping this test gated. This will prevent this test suite from being too dependent on specific account configurations and any future Glue/Lake Formation default permissions changes.

```console
$ QUICKSIGHT_ATHENA_TESTING_ENABLED=true make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_refreshProperties
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_refreshProperties'  -timeout 180m
=== RUN   TestAccQuickSightDataSet_refreshProperties
=== PAUSE TestAccQuickSightDataSet_refreshProperties
=== CONT  TestAccQuickSightDataSet_refreshProperties
--- PASS: TestAccQuickSightDataSet_refreshProperties (27.01s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 30.195s
```

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ QUICKSIGHT_ATHENA_TESTING_ENABLED=true make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_'  -timeout 180m

--- PASS: TestAccQuickSightDataSet_disappears (31.73s)
--- PASS: TestAccQuickSightDataSet_refreshProperties (35.26s)
--- PASS: TestAccQuickSightDataSet_fieldFolders (35.65s)
--- PASS: TestAccQuickSightDataSet_basic (35.68s)
--- PASS: TestAccQuickSightDataSet_columnLevelPermissionRules (36.35s)
--- PASS: TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration (36.54s)
--- PASS: TestAccQuickSightDataSet_logicalTableMap (36.72s)
--- PASS: TestAccQuickSightDataSet_dataSetUsageConfiguration (36.86s)
--- PASS: TestAccQuickSightDataSet_columnGroups (36.89s)
--- PASS: TestAccQuickSightDataSet_tags (73.89s)
--- PASS: TestAccQuickSightDataSet_permissions (79.69s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 82.828s
```

**Comment by g-dx** [comment]
@jar-b - my apologies. 

I accidentally deleted your two commits while rebasing this MR in an attempt to get the CI build to pass. I hope it's not too much trouble to push them again when you get a chance :bow:

**Comment by g-dx** [comment]
Looks like we have a dead link in the documentation on `main`:

```
... snip ...

FILE: website/docs/d/kendra_index.html.markdown
  [✖] https://docs.aws.amazon.com/kendra/latest/dg/API_CreateIndex → Status: 404

  6 links checked.

  ERROR: 1 dead links found!
  [✖] https://docs.aws.amazon.com/kendra/latest/dg/API_CreateIndex → Status: 404

... snip ...
```
(From https://github.com/hashicorp/terraform-provider-aws/actions/runs/4948862075/jobs/8850179751?pr=30778)

Sure enough this https://docs.aws.amazon.com/kendra/latest/dg/API_CreateIndex return `404`.

**Comment by jar-b** [comment]
Thanks for your contribution, @g-dx ! 👍 

In case you're interested, a form to join our contributors Slack channel is [available here](https://forms.gle/Gf9ZAmUYXuzafkct6). Thanks again!

**Pull request merged**
