### PR TITLE
resource/aws_autoscaling_group: add instance_refresh block

### LINKED ISSUE #13785: Support ASG Instance Refresh
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When an auto-scaling group is updated in Terraform (e.g. modification of the Launch Template version), its instances remain unchanged, and a complete roll-out requires intervention by other means.

This is in contrast to [AWS::AutoScaling::AutoScalingGroup](https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-as-group.html) in CloudFormation, which orchestrates a roll-out, and waits until it's completed or times out.

AWS have recently introduced [ASG Instance Refresh](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html), which can be used to recycle the instances of an auto-scaling group.

Use ASG Instance Refresh to provide the user the option to automatically refresh an entire ASG in response to changes to an auto-scaling group. The proposed change introduces a new `aws_autoscaling_group` block, `instance_refresh`, that instructs Terraform to create and monitor an instance refresh in response to any changes to the ASG's properties, except for (1) those that do not affect individual instances, such as `max_size`; and (2) properties explicitly ignored by way of lifecycle.

The `instance_refresh` would be disabled by default, thus ensuring backwards compatibility.

### New or Affected Resource(s)

* aws_autoscaling_group

### Potential Terraform Configuration

```hcl
resource "aws_launch_template" "foobar" {
  name_prefix   = "foobar"
  image_id      = "ami-1a2b3c"
  instance_type = "t2.micro"
}

resource "aws_autoscaling_group" "bar" {
  availability_zones = ["us-east-1a"]
  desired_capacity   = 1
  max_size           = 1
  min_size           = 1

  launch_template {
    id      = "${aws_launch_template.foobar.id}"
    version = "${aws_launch_template.foobar.latest_version}"
  }

  instance_refresh {
    enabled = true
    instance_warmup = 300
    min_healthy_percentage = 90
  }
}
```

### References

* https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.DescribeInstanceRefreshes
* https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.StartInstanceRefresh
* https://docs.aws.amazon.com/sdk-for-go/api/service/autoscaling/#AutoScaling.CancelInstanceRefresh

### PR DESCRIPTION
**Pull request by roberth-k**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13785

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
ENHANCEMENTS:

* resource/aws_autoscaling_group: add `instance_refresh` block
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAutoScalingGroup_'
--- PASS: TestAccAWSAutoScalingGroup_launchTempPartitionNum (57.76s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_LaunchTemplateName (88.14s)
--- PASS: TestAccAWSAutoScalingGroup_serviceLinkedRoleARN (96.66s)
--- PASS: TestAccAWSAutoScalingGroup_classicVpcZoneIdentifier (104.83s)
--- PASS: TestAccAWSAutoScalingGroup_MaxInstanceLifetime (116.14s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_LaunchTemplateSpecification_Version (116.58s)
--- PASS: TestAccAWSAutoScalingGroup_withMetrics (117.32s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_UpdateToZeroOnDemandBaseCapacity (120.95s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_Override_InstanceType (123.72s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer_ToTargetGroup (379.68s)
--- PASS: TestAccAWSAutoScalingGroup_WithLoadBalancer (425.49s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotMaxPrice (141.26s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotInstancePools (86.65s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_SpotAllocationStrategy (57.79s)
--- PASS: TestAccAWSAutoScalingGroup_VpcUpdates (119.12s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_LaunchTemplate_Override_WeightedCapacity (174.51s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandPercentageAboveBaseCapacity (88.72s)
--- PASS: TestAccAWSAutoScalingGroup_emptyAvailabilityZones (95.30s)
--- PASS: TestAccAWSAutoScalingGroup_autoGeneratedName (58.22s)
--- PASS: TestAccAWSAutoScalingGroup_LaunchTemplate_IAMInstanceProfile (59.49s)
--- PASS: TestAccAWSAutoScalingGroup_enablingMetrics (210.73s)
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups (232.50s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate (89.84s)
--- PASS: TestAccAWSAutoScalingGroup_suspendingProcesses (244.34s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy (53.03s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandAllocationStrategy (90.53s)
--- PASS: TestAccAWSAutoScalingGroup_initialLifecycleHook (269.89s)
--- PASS: TestAccAWSAutoScalingGroup_namePrefix (89.34s)
--- PASS: TestAccAWSAutoScalingGroup_basic (277.90s)
--- PASS: TestAccAWSAutoScalingGroup_terminationPolicies (162.21s)
--- PASS: TestAccAWSAutoScalingGroup_TargetGroupArns (296.46s)
--- PASS: TestAccAWSAutoScalingGroup_withPlacementGroup (180.03s)
--- PASS: TestAccAWSAutoScalingGroup_MixedInstancesPolicy_InstancesDistribution_OnDemandBaseCapacity (116.18s)
--- PASS: TestAccAWSAutoScalingGroup_launchTemplate_update (185.73s)
--- PASS: TestAccAWSAutoScalingGroup_ALB_TargetGroups_ELBCapacity (348.21s)
--- PASS: TestAccAWSAutoScalingGroup_tags (276.82s)
--- PASS: TestAccAWSAutoScalingGroup_InstanceRefresh_Enabled (452.57s)
--- PASS: TestAccAWSAutoScalingGroup_InstanceRefresh_Triggers (477.33s)
--- PASS: TestAccAWSAutoScalingGroup_LoadBalancers (786.57s)
```

The following block will be added to `aws_autoscaling_group`:

```hcl
resource "aws_autoscaling_group" "default" {
  instance_refresh {
    instance_warmup_seconds = 300
    min_healthy_percentage = 90
    strategy = "Rolling"
  }
}
```

If the block is present, start an [ASG Instance Refresh](https://docs.aws.amazon.com/autoscaling/ec2/userguide/asg-instance-refresh.html) with the given parameters when the ASG is updated. The refresh is started only when a property is changed that would need a rollout to take effect (e.g. `launch_template`). If there is already an active refresh during an update, it is cancelled.

The instance refresh is "fire and forget": the resource does not wait for the refresh to complete. This comes partly down to the difficulty of choosing a sensible timeout (highly dependent on ASG size, warmup settings, healthy percentages), and partly down to difficulties related to the representation of a rollout in Terraform state. Since the ASG update and Instance Refresh are separate operations, the resource might initially fail the apply, but then report a misleading success on the second run. Workarounds would require an opinionated solution, such as using a separate resource so that the identity of an Instance Refresh could be tracked individually.

### CODE REVIEW

**Comment by Vivalldi** [comment]
>Should `wait_for_completion` be true by default?

I'm in favor of having the wait enabled by default. However, I don't think we need the `wait_for_completion` flag as we already have `wait_for_completion_timeout`. If we follow the behavior of `wait_for_capacity_timeout` we should be good. Wait for the specified time in `wait_for_completion_timeout`. If it's set to `"0"` don't wait.

**Comment by roberth-k** [comment]
@Vivalldi Consistency with the conventions of the other timeout field settles it.

I'm currently looking at the following remaining issues:

- [ ] Handling repeat updates. At present: if the first refresh fails, a subsequent update of the resource will succeed even though the refresh hasn't happened. This is misleading, if not dangerous.
- [ ] Handling conflicting updates. Only one Instance Refresh can be active at a time. The resource might want to start a refresh while another one is still in progress. Should the resource fail or wait? _(Interestingly: the Instance Refresh appears to capture the latest updates to an ASG even when they have been made mid-refresh)_
- [ ] When the refresh is cancelled after a timeout, should the resource wait for the cancellation to complete?

With the above plus acceptance tests, it will be a few more days before this is ready.

**Comment by Vivalldi** [comment]
PR looks good to me. Appreciate all the work you've put in.

Out of sheer curiosy, what's the reasoning behind dropping waiting and timeouts?

**Comment by roberth-k** [comment]
@Vivalldi I couldn't find a way of managing failures and timeouts such that the outcome is obvious to the user. Not unsolvable, but it would have been a distraction in this PR.

The link between an ASG's state and a particular Instance Refresh is weak, so realistically the provider would need a new resource in order to be able to declaratively start and track the outcome of a single refresh. An update to the ASG would cause ForceNew by way of a `null_resource`-esque trigger map. To do this inside of `aws_autoscaling_group` would have required refactoring it using partial state.

**Comment by flosell** [comment]
On waiting for completion: I think that's an extremely valuable feature, given that (at least as far as I can tell) one of the main use-cases for instance_refresh would be managing deployments. Essentially, what we are saying with instance_refresh is "ensure my autoscaling group and all the instances attached to it are configured as specified in the code". This operation is only complete once the instance refresh is done. 

I don't have a strong opinion on adding this in a separate PR though (might even help creating one) as long as this PR doesn't make it hard to do so. 

Would be curious @roberth-k what troubles you ran into, to me a behaviour like @Vivalldi mentioned, using `wait_for_completion` sounds reasonable. I'm thinking the `DescribeInstanceRefreshes` might help get around the misleading success on second run.

**Comment by roberth-k** [comment]
@flosell

Two main complications:

1. Terraform won't store the state of `aws_autoscaling_group` when the refresh fails (unless the resource is refactored using partial state). 
2. `DescribeInstanceRefreshes` doesn't offer enough information to reliably say which ASG update a refresh pertains to.

Hence if the first `terraform apply` fails (e.g. instances failed to start, or maybe the timeout was too short), the resource doesn't maintain the ID of the refresh it triggered. On the second run, `terraform apply` notices that the resource diff is unchanged (the ASG itself was updated after all), and gives the green light even though the ASG may have been left in an inconsistent state.

_(Note: CloudFormation doesn't have this issue, as it would roll back the entire ASG on failure)_

This can happen more often than it seems, as there's no one size fits all default to the timeout. A large ASG with a long warmup time could take ages to refresh.

Read at diff time might notice that there is _an_ ongoing (or failed) refresh, but wouldn't be able to tell whether it was the previous `terraform apply`, or perhaps whether an external agent had triggered it for its own reasons. `DescribeInstanceRefreshes` only provides the Instance Refresh ID and its start and end times, but `DescribeAutoScalingGroups` doesn't provide an UpdatedTime.

A separate `aws_autoscaling_instance_refresh` resource can work around these issues, as it would be able to track the lifecycle of a specific instance refresh separately from the ASG.

**Comment by roberth-k** [comment]
Superseded by https://github.com/terraform-providers/terraform-provider-aws/pull/14442.

**Comment by gdavison** [comment]
Hi @roberth-k. Thanks for both of your PRs for Instance Refresh. We've decided to base the Instance Refresh feature implementation on this PR, not #14442.

The Instance Refresh operation is triggered as part of the changes made to the resource, so it fits better as a configuration of the resource itself. A Refresh can also happen concurrently with a scaling operation, so we don't want to wait for scaling to complete before triggering the Refresh.

**Pull request merged**
