### PR TITLE
Add improved validation and required acceptance tests for `aws_lb_listener` and `aws_lb_listener_rule`

### PR DESCRIPTION
**Pull request by gdavison**
### Description

The `aws_lb_listener` and `aws_lb_listener_rule` explicitly ignore certain invalid configurations, and delays some validation to apply-time instead of plan-time. Moves validation that can be done at plan-time to plan-time. Other validation that returns a warning must still be done at apply-time.

A number of acceptance tests for common situations were missing. They have been added.

### Relations

Relates #22526

### Output from Acceptance Testing

```console
% make testacc PKG=elbv2 TESTS=TestAccELBV2Listener

--- PASS: TestAccELBV2ListenerRule_ConditionHTTPHeader_invalid (8.59s)
--- PASS: TestAccELBV2Listener_forwardTargetARNAndBlock (9.40s)
--- PASS: TestAccELBV2ListenerRule_conditionAttributesCount (33.94s)
--- PASS: TestAccELBV2Listener_Gateway_basic (195.56s)
--- PASS: TestAccELBV2Listener_backwardsCompatibility (215.65s)
--- PASS: TestAccELBV2Listener_Application_basic (219.49s)
--- PASS: TestAccELBV2Listener_disappears (220.69s)
--- PASS: TestAccELBV2Listener_Protocol_upd (227.61s)
--- PASS: TestAccELBV2ListenerCertificate_basic (229.58s)
--- PASS: TestAccELBV2Listener_Network_basic (236.56s)
--- PASS: TestAccELBV2ListenerRule_conditionHostHeader (237.71s)
--- PASS: TestAccELBV2ListenerRule_updateRulePriority (238.38s)
--- PASS: TestAccELBV2ListenerRule_conditionMultiple (230.33s)
--- PASS: TestAccELBV2ListenerRule_conditionPathPattern (252.20s)
--- PASS: TestAccELBV2ListenerRule_conditionHTTPHeader (255.14s)
--- PASS: TestAccELBV2Listener_forwardWeighted (263.36s)
--- PASS: TestAccELBV2ListenerRule_tags (266.26s)
--- PASS: TestAccELBV2Listener_tags (271.07s)
--- PASS: TestAccELBV2ListenerRule_conditionSourceIP (238.97s)
--- PASS: TestAccELBV2ListenerRule_conditionUpdateMixed (265.58s)
--- PASS: TestAccELBV2ListenerRule_conditionHTTPRequestMethod (278.31s)
--- PASS: TestAccELBV2ListenerRule_updateFixedResponse (279.50s)
--- PASS: TestAccELBV2ListenerRule_conditionUpdateMultiple (292.98s)
--- PASS: TestAccELBV2ListenerRule_conditionQueryString (211.46s)
--- PASS: TestAccELBV2ListenerRule_Action_actionDisappears (204.99s)
--- PASS: TestAccELBV2Listener_redirect (215.89s)
--- PASS: TestAccELBV2Listener_DefaultAction_actionDisappears (214.06s)
--- PASS: TestAccELBV2Listener_DefaultAction_specifyOrder (213.17s)
--- PASS: TestAccELBV2ListenerRule_Action_specifyOrder (215.70s)
--- PASS: TestAccELBV2Listener_DefaultAction_defaultOrder (214.63s)
--- PASS: TestAccELBV2ListenerRule_oidc (214.17s)
--- PASS: TestAccELBV2ListenerRule_Action_defaultOrder (216.43s)
--- PASS: TestAccELBV2Listener_oidc (216.45s)
--- PASS: TestAccELBV2ListenerRule_forwardTargetARNAndBlock (3.76s)
--- PASS: TestAccELBV2ListenerRule_cognito (212.33s)
--- PASS: TestAccELBV2Listener_fixedResponse (207.37s)
--- PASS: TestAccELBV2ListenerRule_basic (202.13s)
--- PASS: TestAccELBV2ListenerRule_disappears (205.69s)
--- PASS: TestAccELBV2Listener_EmptyDefaultAction (0.00s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/forward (2.02s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/redirect (2.11s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/fixed-response (1.96s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/authenticate-cognito (2.11s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/authenticate-oidc (2.17s)
--- PASS: TestAccELBV2ListenerDataSource_basic (202.52s)
--- PASS: TestAccELBV2Listener_mutualAuthenticationPassthrough (201.51s)
--- PASS: TestAccELBV2ListenerCertificate_disappears_Listener (211.65s)
--- PASS: TestAccELBV2ListenerRule_EmptyAction (0.00s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/authenticate-oidc (2.28s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/fixed-response (2.28s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/forward (2.26s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/redirect (2.11s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/authenticate-cognito (2.15s)
--- PASS: TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer (153.46s)
--- PASS: TestAccELBV2ListenerRule_priority (331.36s)
--- PASS: TestAccELBV2Listener_Protocol_tls (334.37s)
--- PASS: TestAccELBV2ListenerRule_fixedResponse (213.40s)
--- PASS: TestAccELBV2ListenerCertificate_disappears (210.65s)
--- PASS: TestAccELBV2ListenerRule_backwardsCompatibility (231.73s)
--- PASS: TestAccELBV2ListenerCertificate_CertificateARN_underscores (205.76s)
--- PASS: TestAccELBV2Listener_Protocol_https (216.35s)
--- PASS: TestAccELBV2ListenerRule_redirect (246.14s)
--- PASS: TestAccELBV2Listener_mutualAuthentication (230.36s)
--- PASS: TestAccELBV2ListenerRule_forwardWeighted (226.04s)
--- PASS: TestAccELBV2ListenerCertificate_multiple (247.74s)
--- PASS: TestAccELBV2ListenerRule_changeListenerRuleARNForcesNew (222.24s)
--- PASS: TestAccELBV2ListenerRule_cognito (207.95s)
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM 🚀.

```console
% make testacc TESTARGS='-run=TestAccELBV2Listener' PKG=elbv2 ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/elbv2/... -v -count 1 -parallel 2  -run=TestAccELBV2Listener -timeout 360m
=== RUN   TestAccELBV2ListenerCertificate_basic
=== PAUSE TestAccELBV2ListenerCertificate_basic
=== RUN   TestAccELBV2ListenerCertificate_CertificateARN_underscores
=== PAUSE TestAccELBV2ListenerCertificate_CertificateARN_underscores
=== RUN   TestAccELBV2ListenerCertificate_multiple
=== PAUSE TestAccELBV2ListenerCertificate_multiple
=== RUN   TestAccELBV2ListenerCertificate_disappears
=== PAUSE TestAccELBV2ListenerCertificate_disappears
=== RUN   TestAccELBV2ListenerCertificate_disappears_Listener
=== PAUSE TestAccELBV2ListenerCertificate_disappears_Listener
=== RUN   TestAccELBV2ListenerDataSource_basic
=== PAUSE TestAccELBV2ListenerDataSource_basic
=== RUN   TestAccELBV2ListenerRule_basic
=== PAUSE TestAccELBV2ListenerRule_basic
=== RUN   TestAccELBV2ListenerRule_disappears
=== PAUSE TestAccELBV2ListenerRule_disappears
=== RUN   TestAccELBV2ListenerRule_tags
=== PAUSE TestAccELBV2ListenerRule_tags
=== RUN   TestAccELBV2ListenerRule_forwardWeighted
=== PAUSE TestAccELBV2ListenerRule_forwardWeighted
=== RUN   TestAccELBV2ListenerRule_forwardTargetARNAndBlock
=== PAUSE TestAccELBV2ListenerRule_forwardTargetARNAndBlock
=== RUN   TestAccELBV2ListenerRule_backwardsCompatibility
=== PAUSE TestAccELBV2ListenerRule_backwardsCompatibility
=== RUN   TestAccELBV2ListenerRule_redirect
=== PAUSE TestAccELBV2ListenerRule_redirect
=== RUN   TestAccELBV2ListenerRule_fixedResponse
=== PAUSE TestAccELBV2ListenerRule_fixedResponse
=== RUN   TestAccELBV2ListenerRule_updateFixedResponse
=== PAUSE TestAccELBV2ListenerRule_updateFixedResponse
=== RUN   TestAccELBV2ListenerRule_updateRulePriority
=== PAUSE TestAccELBV2ListenerRule_updateRulePriority
=== RUN   TestAccELBV2ListenerRule_changeListenerRuleARNForcesNew
=== PAUSE TestAccELBV2ListenerRule_changeListenerRuleARNForcesNew
=== RUN   TestAccELBV2ListenerRule_priority
=== PAUSE TestAccELBV2ListenerRule_priority
=== RUN   TestAccELBV2ListenerRule_cognito
=== PAUSE TestAccELBV2ListenerRule_cognito
=== RUN   TestAccELBV2ListenerRule_oidc
=== PAUSE TestAccELBV2ListenerRule_oidc
=== RUN   TestAccELBV2ListenerRule_Action_defaultOrder
=== PAUSE TestAccELBV2ListenerRule_Action_defaultOrder
=== RUN   TestAccELBV2ListenerRule_Action_specifyOrder
=== PAUSE TestAccELBV2ListenerRule_Action_specifyOrder
=== RUN   TestAccELBV2ListenerRule_Action_actionDisappears
=== PAUSE TestAccELBV2ListenerRule_Action_actionDisappears
=== RUN   TestAccELBV2ListenerRule_EmptyAction
=== PAUSE TestAccELBV2ListenerRule_EmptyAction
=== RUN   TestAccELBV2ListenerRule_conditionAttributesCount
=== PAUSE TestAccELBV2ListenerRule_conditionAttributesCount
=== RUN   TestAccELBV2ListenerRule_conditionHostHeader
=== PAUSE TestAccELBV2ListenerRule_conditionHostHeader
=== RUN   TestAccELBV2ListenerRule_conditionHTTPHeader
=== PAUSE TestAccELBV2ListenerRule_conditionHTTPHeader
=== RUN   TestAccELBV2ListenerRule_ConditionHTTPHeader_invalid
=== PAUSE TestAccELBV2ListenerRule_ConditionHTTPHeader_invalid
=== RUN   TestAccELBV2ListenerRule_conditionHTTPRequestMethod
=== PAUSE TestAccELBV2ListenerRule_conditionHTTPRequestMethod
=== RUN   TestAccELBV2ListenerRule_conditionPathPattern
=== PAUSE TestAccELBV2ListenerRule_conditionPathPattern
=== RUN   TestAccELBV2ListenerRule_conditionQueryString
=== PAUSE TestAccELBV2ListenerRule_conditionQueryString
=== RUN   TestAccELBV2ListenerRule_conditionSourceIP
=== PAUSE TestAccELBV2ListenerRule_conditionSourceIP
=== RUN   TestAccELBV2ListenerRule_conditionUpdateMixed
=== PAUSE TestAccELBV2ListenerRule_conditionUpdateMixed
=== RUN   TestAccELBV2ListenerRule_conditionMultiple
=== PAUSE TestAccELBV2ListenerRule_conditionMultiple
=== RUN   TestAccELBV2ListenerRule_conditionUpdateMultiple
=== PAUSE TestAccELBV2ListenerRule_conditionUpdateMultiple
=== RUN   TestAccELBV2Listener_Application_basic
=== PAUSE TestAccELBV2Listener_Application_basic
=== RUN   TestAccELBV2Listener_Network_basic
=== PAUSE TestAccELBV2Listener_Network_basic
=== RUN   TestAccELBV2Listener_Gateway_basic
=== PAUSE TestAccELBV2Listener_Gateway_basic
=== RUN   TestAccELBV2Listener_disappears
=== PAUSE TestAccELBV2Listener_disappears
=== RUN   TestAccELBV2Listener_tags
=== PAUSE TestAccELBV2Listener_tags
=== RUN   TestAccELBV2Listener_forwardWeighted
=== PAUSE TestAccELBV2Listener_forwardWeighted
=== RUN   TestAccELBV2Listener_forwardTargetARNAndBlock
=== PAUSE TestAccELBV2Listener_forwardTargetARNAndBlock
=== RUN   TestAccELBV2Listener_Protocol_upd
=== PAUSE TestAccELBV2Listener_Protocol_upd
=== RUN   TestAccELBV2Listener_backwardsCompatibility
=== PAUSE TestAccELBV2Listener_backwardsCompatibility
=== RUN   TestAccELBV2Listener_Protocol_https
=== PAUSE TestAccELBV2Listener_Protocol_https
=== RUN   TestAccELBV2Listener_mutualAuthentication
=== PAUSE TestAccELBV2Listener_mutualAuthentication
=== RUN   TestAccELBV2Listener_mutualAuthenticationPassthrough
=== PAUSE TestAccELBV2Listener_mutualAuthenticationPassthrough
=== RUN   TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer
=== PAUSE TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer
=== RUN   TestAccELBV2Listener_Protocol_tls
=== PAUSE TestAccELBV2Listener_Protocol_tls
=== RUN   TestAccELBV2Listener_redirect
=== PAUSE TestAccELBV2Listener_redirect
=== RUN   TestAccELBV2Listener_fixedResponse
=== PAUSE TestAccELBV2Listener_fixedResponse
=== RUN   TestAccELBV2Listener_cognito
=== PAUSE TestAccELBV2Listener_cognito
=== RUN   TestAccELBV2Listener_oidc
=== PAUSE TestAccELBV2Listener_oidc
=== RUN   TestAccELBV2Listener_DefaultAction_defaultOrder
=== PAUSE TestAccELBV2Listener_DefaultAction_defaultOrder
=== RUN   TestAccELBV2Listener_DefaultAction_specifyOrder
=== PAUSE TestAccELBV2Listener_DefaultAction_specifyOrder
=== RUN   TestAccELBV2Listener_DefaultAction_actionDisappears
=== PAUSE TestAccELBV2Listener_DefaultAction_actionDisappears
=== RUN   TestAccELBV2Listener_EmptyDefaultAction
=== PAUSE TestAccELBV2Listener_EmptyDefaultAction
=== CONT  TestAccELBV2ListenerCertificate_basic
=== CONT  TestAccELBV2ListenerRule_conditionPathPattern
--- PASS: TestAccELBV2ListenerCertificate_basic (212.66s)
=== CONT  TestAccELBV2Listener_backwardsCompatibility
--- PASS: TestAccELBV2ListenerRule_conditionPathPattern (230.48s)
=== CONT  TestAccELBV2Listener_EmptyDefaultAction
=== RUN   TestAccELBV2Listener_EmptyDefaultAction/forward
=== PAUSE TestAccELBV2Listener_EmptyDefaultAction/forward
=== RUN   TestAccELBV2Listener_EmptyDefaultAction/authenticate-oidc
=== PAUSE TestAccELBV2Listener_EmptyDefaultAction/authenticate-oidc
=== RUN   TestAccELBV2Listener_EmptyDefaultAction/authenticate-cognito
=== PAUSE TestAccELBV2Listener_EmptyDefaultAction/authenticate-cognito
=== RUN   TestAccELBV2Listener_EmptyDefaultAction/redirect
=== PAUSE TestAccELBV2Listener_EmptyDefaultAction/redirect
=== RUN   TestAccELBV2Listener_EmptyDefaultAction/fixed-response
=== PAUSE TestAccELBV2Listener_EmptyDefaultAction/fixed-response
=== CONT  TestAccELBV2Listener_DefaultAction_actionDisappears
--- PASS: TestAccELBV2Listener_backwardsCompatibility (213.53s)
=== CONT  TestAccELBV2Listener_DefaultAction_specifyOrder
--- PASS: TestAccELBV2Listener_DefaultAction_actionDisappears (218.06s)
=== CONT  TestAccELBV2Listener_DefaultAction_defaultOrder
--- PASS: TestAccELBV2Listener_DefaultAction_specifyOrder (234.71s)
=== CONT  TestAccELBV2Listener_oidc
--- PASS: TestAccELBV2Listener_DefaultAction_defaultOrder (238.20s)
=== CONT  TestAccELBV2Listener_cognito
--- PASS: TestAccELBV2Listener_oidc (230.41s)
=== CONT  TestAccELBV2Listener_fixedResponse
--- PASS: TestAccELBV2Listener_cognito (224.97s)
=== CONT  TestAccELBV2Listener_redirect
--- PASS: TestAccELBV2Listener_fixedResponse (225.90s)
=== CONT  TestAccELBV2Listener_Protocol_tls
--- PASS: TestAccELBV2Listener_redirect (227.46s)
=== CONT  TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer
--- PASS: TestAccELBV2Listener_LoadBalancerARN_gatewayLoadBalancer (187.67s)
=== CONT  TestAccELBV2Listener_mutualAuthenticationPassthrough
--- PASS: TestAccELBV2Listener_Protocol_tls (347.02s)
=== CONT  TestAccELBV2Listener_mutualAuthentication
--- PASS: TestAccELBV2Listener_mutualAuthenticationPassthrough (210.32s)
=== CONT  TestAccELBV2Listener_Protocol_https
--- PASS: TestAccELBV2Listener_Protocol_https (205.71s)
=== CONT  TestAccELBV2Listener_Network_basic
--- PASS: TestAccELBV2Listener_Network_basic (220.77s)
=== CONT  TestAccELBV2Listener_Protocol_upd
--- PASS: TestAccELBV2Listener_Protocol_upd (233.28s)
=== CONT  TestAccELBV2Listener_forwardTargetARNAndBlock
--- PASS: TestAccELBV2Listener_forwardTargetARNAndBlock (3.25s)
=== CONT  TestAccELBV2Listener_forwardWeighted
--- PASS: TestAccELBV2Listener_forwardWeighted (248.27s)
=== CONT  TestAccELBV2Listener_tags
--- PASS: TestAccELBV2Listener_mutualAuthentication (213.42s)
=== CONT  TestAccELBV2Listener_disappears
--- PASS: TestAccELBV2Listener_tags (252.86s)
=== CONT  TestAccELBV2Listener_Gateway_basic
--- PASS: TestAccELBV2Listener_disappears (200.22s)
=== CONT  TestAccELBV2ListenerRule_conditionMultiple
--- PASS: TestAccELBV2Listener_Gateway_basic (197.28s)
=== CONT  TestAccELBV2Listener_Application_basic
--- PASS: TestAccELBV2ListenerRule_conditionMultiple (217.51s)
=== CONT  TestAccELBV2ListenerRule_conditionUpdateMultiple
--- PASS: TestAccELBV2Listener_Application_basic (214.43s)
=== CONT  TestAccELBV2ListenerRule_conditionSourceIP
--- PASS: TestAccELBV2ListenerRule_conditionUpdateMultiple (244.64s)
=== CONT  TestAccELBV2ListenerRule_updateRulePriority
--- PASS: TestAccELBV2ListenerRule_conditionSourceIP (228.06s)
=== CONT  TestAccELBV2ListenerRule_conditionHTTPRequestMethod
--- PASS: TestAccELBV2ListenerRule_updateRulePriority (222.68s)
=== CONT  TestAccELBV2ListenerRule_ConditionHTTPHeader_invalid
--- PASS: TestAccELBV2ListenerRule_ConditionHTTPHeader_invalid (1.93s)
=== CONT  TestAccELBV2ListenerRule_conditionUpdateMixed
--- PASS: TestAccELBV2ListenerRule_conditionHTTPRequestMethod (227.32s)
=== CONT  TestAccELBV2ListenerRule_conditionHTTPHeader
--- PASS: TestAccELBV2ListenerRule_conditionUpdateMixed (250.97s)
=== CONT  TestAccELBV2ListenerRule_tags
--- PASS: TestAccELBV2ListenerRule_conditionHTTPHeader (210.04s)
=== CONT  TestAccELBV2ListenerRule_updateFixedResponse
--- PASS: TestAccELBV2ListenerRule_tags (245.43s)
=== CONT  TestAccELBV2ListenerRule_fixedResponse
--- PASS: TestAccELBV2ListenerRule_updateFixedResponse (227.52s)
=== CONT  TestAccELBV2ListenerRule_redirect
--- PASS: TestAccELBV2ListenerRule_fixedResponse (221.46s)
=== CONT  TestAccELBV2ListenerRule_conditionHostHeader
--- PASS: TestAccELBV2ListenerRule_redirect (262.11s)
=== CONT  TestAccELBV2ListenerRule_conditionAttributesCount
--- PASS: TestAccELBV2ListenerRule_conditionAttributesCount (21.62s)
=== CONT  TestAccELBV2ListenerRule_EmptyAction
=== RUN   TestAccELBV2ListenerRule_EmptyAction/forward
=== PAUSE TestAccELBV2ListenerRule_EmptyAction/forward
=== RUN   TestAccELBV2ListenerRule_EmptyAction/authenticate-oidc
=== PAUSE TestAccELBV2ListenerRule_EmptyAction/authenticate-oidc
=== RUN   TestAccELBV2ListenerRule_EmptyAction/authenticate-cognito
=== PAUSE TestAccELBV2ListenerRule_EmptyAction/authenticate-cognito
=== RUN   TestAccELBV2ListenerRule_EmptyAction/redirect
=== PAUSE TestAccELBV2ListenerRule_EmptyAction/redirect
=== RUN   TestAccELBV2ListenerRule_EmptyAction/fixed-response
=== PAUSE TestAccELBV2ListenerRule_EmptyAction/fixed-response
=== CONT  TestAccELBV2ListenerRule_Action_actionDisappears
--- PASS: TestAccELBV2ListenerRule_conditionHostHeader (228.54s)
=== CONT  TestAccELBV2ListenerRule_backwardsCompatibility
--- PASS: TestAccELBV2ListenerRule_Action_actionDisappears (220.07s)
=== CONT  TestAccELBV2ListenerRule_forwardTargetARNAndBlock
--- PASS: TestAccELBV2ListenerRule_forwardTargetARNAndBlock (3.14s)
=== CONT  TestAccELBV2ListenerRule_forwardWeighted
--- PASS: TestAccELBV2ListenerRule_backwardsCompatibility (214.73s)
=== CONT  TestAccELBV2ListenerRule_conditionQueryString
--- PASS: TestAccELBV2ListenerRule_forwardWeighted (242.23s)
=== CONT  TestAccELBV2ListenerRule_Action_specifyOrder
--- PASS: TestAccELBV2ListenerRule_conditionQueryString (229.49s)
=== CONT  TestAccELBV2ListenerRule_priority
--- PASS: TestAccELBV2ListenerRule_Action_specifyOrder (223.76s)
=== CONT  TestAccELBV2ListenerRule_changeListenerRuleARNForcesNew
--- PASS: TestAccELBV2ListenerRule_priority (358.82s)
=== CONT  TestAccELBV2ListenerRule_Action_defaultOrder
--- PASS: TestAccELBV2ListenerRule_changeListenerRuleARNForcesNew (327.87s)
=== CONT  TestAccELBV2ListenerRule_cognito
--- PASS: TestAccELBV2ListenerRule_Action_defaultOrder (233.36s)
=== CONT  TestAccELBV2ListenerRule_oidc
--- PASS: TestAccELBV2ListenerRule_cognito (224.26s)
=== CONT  TestAccELBV2ListenerRule_basic
--- PASS: TestAccELBV2ListenerRule_oidc (209.36s)
=== CONT  TestAccELBV2ListenerCertificate_disappears_Listener
--- PASS: TestAccELBV2ListenerRule_basic (210.63s)
=== CONT  TestAccELBV2ListenerDataSource_basic
--- PASS: TestAccELBV2ListenerCertificate_disappears_Listener (209.72s)
=== CONT  TestAccELBV2ListenerCertificate_multiple
--- PASS: TestAccELBV2ListenerDataSource_basic (219.77s)
=== CONT  TestAccELBV2ListenerRule_disappears
--- PASS: TestAccELBV2ListenerCertificate_multiple (279.41s)
=== CONT  TestAccELBV2ListenerCertificate_CertificateARN_underscores
--- PASS: TestAccELBV2ListenerRule_disappears (200.94s)
=== CONT  TestAccELBV2ListenerCertificate_disappears
--- PASS: TestAccELBV2ListenerCertificate_CertificateARN_underscores (211.34s)
=== CONT  TestAccELBV2Listener_EmptyDefaultAction/forward
=== CONT  TestAccELBV2Listener_EmptyDefaultAction/redirect
=== CONT  TestAccELBV2Listener_EmptyDefaultAction/fixed-response
=== CONT  TestAccELBV2Listener_EmptyDefaultAction/authenticate-cognito
=== CONT  TestAccELBV2Listener_EmptyDefaultAction/authenticate-oidc
--- PASS: TestAccELBV2Listener_EmptyDefaultAction (0.00s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/forward (3.14s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/redirect (3.13s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/fixed-response (3.21s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/authenticate-cognito (3.31s)
    --- PASS: TestAccELBV2Listener_EmptyDefaultAction/authenticate-oidc (3.39s)
=== CONT  TestAccELBV2ListenerRule_EmptyAction/forward
=== CONT  TestAccELBV2ListenerRule_EmptyAction/redirect
=== CONT  TestAccELBV2ListenerRule_EmptyAction/fixed-response
=== CONT  TestAccELBV2ListenerRule_EmptyAction/authenticate-cognito
=== CONT  TestAccELBV2ListenerRule_EmptyAction/authenticate-oidc
--- PASS: TestAccELBV2ListenerRule_EmptyAction (0.00s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/forward (3.11s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/redirect (3.44s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/fixed-response (3.27s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/authenticate-cognito (3.17s)
    --- PASS: TestAccELBV2ListenerRule_EmptyAction/authenticate-oidc (3.16s)
--- PASS: TestAccELBV2ListenerCertificate_disappears (218.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/elbv2	6394.343s
```

**Comment by jrobison-sb** [comment]
Is it expected to see a diff like this when upgrading from 5.34.0 to 5.35.0?
```
  # module.production_application.aws_lb_listener.http[0] will be updated in-place
~ resource "aws_lb_listener" "http" {
        id                = "arn:aws:elasticloadbalancing:us-east-1:1234567890:listener/app/production-application/1f856bea10e7db15/3f32f460ef515297"
        # (5 unchanged attributes hidden)

      ~ default_action {
          + target_group_arn = "arn:aws:elasticloadbalancing:us-east-1:1234567890:targetgroup/tf-20210430190112588200000001/575b298869ff5b80"
            # (2 unchanged attributes hidden)

            # (1 unchanged block hidden)
        }
    }
```

This resource has already existed for a long time and shows no diffs under 5.34.0.

Thanks.

**Comment by gdavison** [comment]
Hi @jrobison-sb, could you please open a new issue and include your Terraform configuration?

**Comment by jrobison-sb** [comment]
@gdavison have done so. Thanks.

**Pull request merged**
