### PR TITLE
Fix/Enhancement: Add application_tag attribute to aws_servicecatalogappregistry_application

### PR DESCRIPTION
**Pull request by fatbasstard**
### Description

This PR adds the `application_tag` attribute to the `aws_servicecatalogappregistry_application` resource. There is a design flaw in the new resource. It's not the Application's ARN that has to be assigned to the resource.

The actual tag(s) (key and name) are available in the SDK so just needs to be added.

This PR adds the new attribute and updates the documentation. Also implemented this in the tests

### Relations

Closes #0000

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccServiceCatalogAppRegistryApplication PKG=servicecatalogappregistry
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryApplication'  -timeout 360m
=== RUN   TestAccServiceCatalogAppRegistryApplicationDataSource_basic
=== PAUSE TestAccServiceCatalogAppRegistryApplicationDataSource_basic
=== RUN   TestAccServiceCatalogAppRegistryApplication_basic
=== PAUSE TestAccServiceCatalogAppRegistryApplication_basic
=== RUN   TestAccServiceCatalogAppRegistryApplication_disappears
=== PAUSE TestAccServiceCatalogAppRegistryApplication_disappears
=== RUN   TestAccServiceCatalogAppRegistryApplication_update
=== PAUSE TestAccServiceCatalogAppRegistryApplication_update
=== CONT  TestAccServiceCatalogAppRegistryApplicationDataSource_basic
=== CONT  TestAccServiceCatalogAppRegistryApplication_disappears
=== CONT  TestAccServiceCatalogAppRegistryApplication_update
=== CONT  TestAccServiceCatalogAppRegistryApplication_basic
--- PASS: TestAccServiceCatalogAppRegistryApplicationDataSource_basic (8.73s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_disappears (8.97s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_basic (10.32s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_update (19.59s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry  24.110s
...
```

### CODE REVIEW

**Comment by fatbasstard** [comment]
@jar-b Can you take a look at this PR? Found out it's missing a vital feature in order to make it work decently..

**Comment by jar-b** [comment]
Thanks for the fix! I'll assign myself and get it reviewed before next weeks release.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=servicecatalogappregistry TESTS=TestAccServiceCatalogAppRegistryApplication
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/servicecatalogappregistry/... -v -count 1 -parallel 20 -run='TestAccServiceCatalogAppRegistryApplication'  -timeout 360m

--- PASS: TestAccServiceCatalogAppRegistryApplication_disappears (13.72s)
--- PASS: TestAccServiceCatalogAppRegistryApplicationDataSource_basic (13.81s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_basic (15.37s)
--- PASS: TestAccServiceCatalogAppRegistryApplication_update (28.11s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/servicecatalogappregistry  33.679s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @fatbasstard! 👍

**Pull request merged**
