### PR TITLE
Iot domain name configuration

### LINKED ISSUE #22654: IOT: Add resource for domain configurations
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the aws console in the settings panel of AWS Iot Core service it is possible to add domain configurations to provide a cname entry that routes to the iot endpoint. 
It would be great to have a terraform resource for defining such a domain name configuration.

### Potential Terraform Configuration

```hcl
# Where the name of the resource is unique and several domain name configurations can be created.
resource "aws_iot_domain_name_configuration" "example" {
  name = "example"
  domain_name = "example.dev.com"
  server_certificate_arns = ["arn1", "arn2"]
}

```

### References

This resource can be created via the aws cli command: https://docs.aws.amazon.com/cli/latest/reference/iot/create-domain-configuration.html

* #0000

### PR DESCRIPTION
**Pull request by jalavoy**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22654

Output from acceptance testing:
Using an example domain name I can't get the acceptance test to pass, but it's because of AWS returning the following error, which seems specific to them:
```
Cannot provide a custom domain name for an AWS Managed Domain
```

However, after building the provider and using it from my production terraform repo, it appears to work fine. Not sure the best way to handle this, as I'm not sure exactly what AWS is testing the domain against. 
```==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIotDomainNameConfiguration'  -timeout 180m
=== RUN   TestAccIotDomainNameConfiguration
    domain_name_configuration_test.go:14: Step 1/1 error: Error running apply: exit status 1
        
        Error: error creating IoT Domain Configuration (test): InvalidRequestException: Cannot provide a custom domain name for an AWS Managed Domain
        
          with aws_iot_domain_name_configuration.iot,
          on terraform_plugin_test.tf line 2, in resource "aws_iot_domain_name_configuration" "iot":
           2:   resource "aws_iot_domain_name_configuration" "iot" {
        
--- FAIL: TestAccIotDomainNameConfiguration (7.53s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/iot        11.062s
FAIL
make: *** [testacc] Error 1
```

Output from my terraform:
```
Terraform will perform the following actions:

  # aws_iot_domain_name_configuration.iot will be created
  + resource "aws_iot_domain_name_configuration" "iot" {
      + domain_name             = "REDACTED"
      + id                      = (known after apply)
      + name                    = "REDACTED"
      + server_certificate_arns = [
          + "REDACTED",
        ]
      + service_type            = "DATA"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
aws_iot_domain_name_configuration.iot: Creating...
aws_iot_domain_name_configuration.iot: Creation complete after 0s [id=REDACTED]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.
```

If y'all have any input on how I can improve my test I'm open to it. I'm still new at working on this code. If it's acceptable to remove the test since it works outside of testing I'm fine with that too.

I'm also not positive I did the tagging stuff right. Super open to input on that.

### CODE REVIEW

**Comment by HHSande** [comment]
Any updates on this?

**Comment by MickSheppardWB** [comment]
Are there any updates on this as we are looking for this functionality?

**Comment by lukaslentner** [comment]
We also need this! How can we help?

**Comment by ScottFinlaysonGMSL** [comment]
@jalavoy since you have a few tests failing then it's unlikely this would be merged in or even reviewed. Are you able to retry those failed tests (to get updated logs) and address the issues raised?

**Comment by lukaslentner** [comment]
How can we rerun the tests. The old logs are not anymore available ...?

**Comment by jalavoy** [comment]
> How can we rerun the tests. The old logs are not anymore available ...?

Copy my code into your own branch, probably re-based off of master, resubmit new PR.

**Comment by jalavoy** [comment]
Okay I got it rebased and fixed a few things, someone is free to take it from here. Probably just needs modernizing to current repo standards.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACM_CERTIFICATE_ROOT_DOMAIN=terraform-provider-aws-acctest-acm.com make testacc TESTARGS='-run=TestAccIoTDomainConfiguration_' PKG=iot ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 1  -run=TestAccIoTDomainConfiguration_ -timeout 360m
=== RUN   TestAccIoTDomainConfiguration_basic
--- PASS: TestAccIoTDomainConfiguration_basic (108.34s)
=== RUN   TestAccIoTDomainConfiguration_disappears
--- PASS: TestAccIoTDomainConfiguration_disappears (133.20s)
=== RUN   TestAccIoTDomainConfiguration_tags
--- PASS: TestAccIoTDomainConfiguration_tags (175.62s)
=== RUN   TestAccIoTDomainConfiguration_update
--- PASS: TestAccIoTDomainConfiguration_update (152.94s)
=== RUN   TestAccIoTDomainConfiguration_awsManaged
    acctest.go:2450: Environment variable IOT_DOMAIN_CONFIGURATION_TEST_AWS_MANAGED is not set, skipping test
--- SKIP: TestAccIoTDomainConfiguration_awsManaged (0.00s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iot        466.800s
```

**Comment by ewbankkit** [comment]
@jalavoy Thanks for the contribution :tada: :clap:.

**Pull request merged**
