### PR TITLE
[Enhancement]: Geoproximity Routing Policy in Route 53 resource.

### PR DESCRIPTION
**Pull request by Siddarthyuvaraj**
Enabling the geoproximity feature in Route 53 service

https://aws.amazon.com/about-aws/whats-new/2024/01/amazon-route-53-expands-geoproximity-routing/

Closes https://github.com/hashicorp/terraform-provider-aws/issues/35277.

### CODE REVIEW

**Comment by Siddarthyuvaraj** [comment]
@ewbankkit any update on this PR?

**Comment by Siddarthyuvaraj** [comment]
@justinretzolk any update on this PR

**Comment by robbo10** [comment]
Any ETA on when this will be available? :)

**Comment by ewbankkit** [comment]
@Siddarthyuvaraj Thanks for the contribution :tada: :clap:.
I have rolled your work into https://github.com/hashicorp/terraform-provider-aws/pull/35836 in order to this is in to today's Terraform AWS Provider **v5.37.0** release.

**Pull request closed without merging**
