### PR TITLE
r/aws_elasticache_replication_group: Add support for `transit_encryption_mode` and enabling transit encryption on existing groups

### LINKED ISSUE #29403: [Enhancement]: Support `TransitEncryptionMode` argument for ElastiCache clusters
### Description

Not so long ago, AWS announced ability to enable in-transit encryption for existing ElastiCache clusters. This feature is already available in AWS Console & AWS CLI. 
It would be nice to have in terraform also. It will help to make process of migration to TLS enabled cluster more smooth. 

### Affected Resource(s) and/or Data Source(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

```terraform
{
   transit_encryption_enabled = true
   transit_encryption_mode = preferred
}
```

### References

- [Amazon ElastiCache for Redis now supports enabling encryption in transit on existing clusters](https://aws.amazon.com/about-aws/whats-new/2022/12/amazon-elasticache-redis-enabling-encryption-transit-existing-clusters/)
- [Enabling in-transit encryption for an existing cluster using the (CLI)
](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html)
- [Options: --transit-encryption-mode](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/elasticache/create-replication-group.html)

### Would you like to implement a fix?

No

### LINKED ISSUE #30402: [Bug]: `aws_elasticache_replication_group` is delaying `terraform plan` for 30 seconds, presumably waiting for the group to become available even though the group is already available
### Terraform Core Version

1.3.9

### AWS Provider Version

4.61.0

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

The resource shouldn't needlessly slow down `terraform plan` or `terraform apply`. If a replication group is created and available then it shouldn't need to wait.

### Actual Behavior

If you have a `aws_elasticache_replication_group` created, the provider will wait for 30 seconds before it is done refreshing the state for the resource. According to the logs, it is waiting for the group state to become `available`. But it will wait for 30 seconds even if the group is _already_ available. It is a very annoying delay every time you want to simply plan a change.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```hcl
resource "aws_elasticache_replication_group" "redis" {
  replication_group_id       = "tftest-redis"
  description                = "Managed by Terraform"
  node_type                  = "cache.t3.micro"
  subnet_group_name          = "test"
  engine_version             = "6.2"
  port                       = 6379
  num_cache_clusters         = 1
  multi_az_enabled           = false
  automatic_failover_enabled = false
  apply_immediately          = true
}
```

### Steps to Reproduce

First create the replication group:

```
$ terraform apply
```

Then, without making any changes, just plan and wait for ~35 seconds:

```
$ time terraform plan

[...]

real	0m35.135s
user	0m1.437s
sys	0m0.362s
```

### Debug Output

Here's some output from `TF_LOG=1 terraform plan`:

```
2023-04-02T14:31:04.489-0700 [DEBUG] provider.terraform-provider-aws: [DEBUG] ElastiCache Replication Group (tftest-redis) Configuration Endpoint is nil
2023-04-02T14:31:04.489-0700 [DEBUG] provider.terraform-provider-aws: [DEBUG] ElastiCache Replication Group (tftest-redis) Primary Endpoint is not nil
2023-04-02T14:31:04.489-0700 [DEBUG] provider.terraform-provider-aws: [DEBUG] Waiting for ElastiCache Replication Group (tftest-redis) to become available
2023-04-02T14:31:04.489-0700 [DEBUG] provider.terraform-provider-aws: [DEBUG] Waiting for state to become: [available]
2023-04-02T14:31:05.324-0700 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_elasticache_replication_group.redis (expand)"
2023-04-02T14:31:05.324-0700 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2023-04-02T14:31:10.325-0700 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2023-04-02T14:31:10.325-0700 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_elasticache_replication_group.redis (expand)"
2023-04-02T14:31:15.326-0700 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2023-04-02T14:31:15.326-0700 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_elasticache_replication_group.redis (expand)"
2023-04-02T14:31:20.327-0700 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2023-04-02T14:31:20.327-0700 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_elasticache_replication_group.redis (expand)"
2023-04-02T14:31:25.328-0700 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2023-04-02T14:31:25.328-0700 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_elasticache_replication_group.redis (expand)"
2023-04-02T14:31:30.329-0700 [TRACE] dag/walk: vertex "provider[\"registry.terraform.io/hashicorp/aws\"] (close)" is waiting for "aws_elasticache_replication_group.redis (expand)"
2023-04-02T14:31:30.330-0700 [TRACE] dag/walk: vertex "root" is waiting for "provider[\"registry.terraform.io/hashicorp/aws\"] (close)"
2023-04-02T14:31:34.491-0700 [DEBUG] provider.terraform-provider-aws: HTTP Request Sent: @module=aws aws.operation=DescribeReplicationGroups
```

Pay attention to the timestamps.

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### LINKED ISSUE #30700: [Bug]: `aws_elasticache_replication_group` transit_encryption_enable changes cause resource replacement
### Terraform Core Version

0.12.31

### AWS Provider Version

4.62

### Affected Resource(s)

aws_elasticache_replication_group

### Expected Behavior

Updating the seeing for transit encryption enabled:
transit_encryption_enabled = true | false

Should just modify the cluster.  Running any either of the following commands will modify the existing cluster and not require the cluster to be rebuilt:
aws elasticache modify-replication-group --replication-group-id cache-cluster --transit-encryption-enabled --transit-encryption-mode preferred --apply-immediately
aws elasticache modify-replication-group --replication-group-id cache-cluster--no-transit-encryption-enabled --apply-immediately

### Actual Behavior

Running terraform plan or apply cause the resource to be recreated:
` ~ transit_encryption_enabled     = true -> false # forces replacement`

Modifying the transit encryption outside of terraform and updating terraform to match allows for the resource to plan/apply as expected. 

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
resource "aws_elasticache_replication_group" "redis" {
  count                         = var.clustered_cache ? 1 : 0

  lifecycle {
    # Comment out ignore_changes to force upgrade based on version change
    prevent_destroy = false
    ignore_changes = [engine_version]
  }

  automatic_failover_enabled    = local.automatic_failover_enabled
  multi_az_enabled              = local.multi_az_enabled
  replication_group_id          = "${var.owner}-${var.application}-${var.environment}${var.suffix}"
  description                   = "MultiAZ ${var.owner}-${var.application}-${var.environment}${var.suffix} Cluster"
  port                          = var.elasticache_port
  parameter_group_name          = aws_elasticache_parameter_group.parameter_group_redis.id

  node_type                     = var.node_type
  num_cache_clusters            = var.node_count
  num_node_groups               = var.num_node_groups
  replicas_per_node_group       = var.replicas_per_node_group

  snapshot_name                 = var.snapshot_name
  snapshot_retention_limit      = local.backup_days
  snapshot_window               = var.backup_window
  maintenance_window            = var.maintenance_window
  auto_minor_version_upgrade    = var.auto_minor_version_upgrade
  engine                        = "redis"
  engine_version                = var.engine_version
  security_group_ids            = [aws_security_group.redis.id]
  subnet_group_name             = local.subnet_group_name
  apply_immediately             = var.apply_immediately

  at_rest_encryption_enabled    = var.at_rest_encryption_enabled
  auth_token                    = var.auth_token      # This is required if transit_encryption_enabled is set
  kms_key_id                    = var.at_rest_encryption_enabled == true ? local.kms_key_id : null
  
  transit_encryption_enabled    = var.transit_encryption_enabled # MODIFY THIS VALUE 
  tags                     = local.tags
}
```

### Steps to Reproduce

Create an elasticache instance.
Modify the value of `transit_encryption_enabled`

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

This is related to a couple of additional open issues relating to elasticache transit encryption.  Including:
https://github.com/hashicorp/terraform-provider-aws/issues/29403
https://github.com/hashicorp/terraform-provider-aws/issues/26367
https://docs.aws.amazon.com/cli/latest/reference/elasticache/modify-cache-cluster.html

I think this gets resolved with this PR:
https://github.com/hashicorp/terraform-provider-aws/pull/30403

### Would you like to implement a fix?

No

### LINKED ISSUE #33906: [Bug]: TransitEncryptionMode still unsupported after #29403
### Terraform Core Version

1.5.0

### AWS Provider Version

5.20.1

### Affected Resource(s)

* `aws_elasticache_replication_group`

### Expected Behavior

After #29403 was closed, I'd expect the `transit_encryption_mode` attribute to be available for `aws_elasticache_replication_group` resource, with allowed values of `preferred` and `required`.

### Actual Behavior

There's no sign of setting `TransitEncryptionMode` attribute in the API Call, no mention of `transit_encryption_mode` in the code and documentation. As a result, TLS Connections to Redis Cluster still cannot be enforced, and can only be enabled (in "preferred" mode) for these who wish to connect securely.

### Relevant Error/Panic Output Snippet

```shell
N/A
```

### Terraform Configuration Files

N/A

### Steps to Reproduce

N/A

### Debug Output

N/A

### Panic Output

N/A

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by stefansundin**
### Description

I don't know if my fix for #30402 is good or not since there might be a better way to do it that I did not find. It is working in my simple test case though.

### Relations

Closes #30402
Closes #30700
Closes #33906

### References

Here's various errors you can get.

If you try to enable encryption on an older Redis version:

> Error: updating ElastiCache Replication Group (tftest-redis): InvalidParameterCombination: Transit encryption mode is not supported for engine version 6.2.6. Please use engine version 7.0.5 or higher.

Have to set `transit_encryption_mode` when enabling encryption:

> Error: updating ElastiCache Replication Group (tftest-redis): InvalidParameterCombination: To modify transit encryption, please specify transit-encryption-mode.

Can't go straight to `transit_encryption_mode = "required"`:

> Error: updating ElastiCache Replication Group (tftest-redis): InvalidParameterCombination: Direct transition from transit-encryption-disabled to transit-encryption-enabled is not allowed. Update the cluster to transit-encryption-mode preferred prior to enabling transit encryption.

### Output from Acceptance Testing

I don't have time to work on updating the acceptance tests at the moment.

### CODE REVIEW

**Comment by stefansundin** [comment]
Rebased

**Comment by teddy-wahle** [comment]
Let's merge this!

I really need this.

**Review by BrentOnRails — APPROVED** [review]

**Comment by schammah** [comment]
when is it planned to be merged at?

**Comment by stefansundin** [comment]
@schammah Unfortunately HashiCorp seems to have some issues handling community contributions. In the past I have had multiple PRs open for 12+ months before they get any attention from HashiCorp employees.

I would call everyone to upvote the top comment in this PR by clicking the 👍 button. This PR is currently number 10 if you sort PRs by the number of upvotes. https://github.com/hashicorp/terraform-provider-aws/pulls?q=is%3Apr+is%3Aopen+sort%3Areactions-%2B1-desc

If anyone here works at a company that is paying money to HashiCorp then I would suggest that you try and send a link to this PR to your HashiCorp representative and ask them to prioritize merging this. I think this is the only surefire way of getting it merged faster.

We're currently at [232 days](https://duckduckgo.com/?q=days+since+april+2%2C+2023&ia=answer) since this PR was opened.

**Comment by stefansundin** [comment]
We're now at [262 days](https://duckduckgo.com/?q=days+since+april+2%2C+2023&ia=answer) since this PR was opened since this PR was opened and it is now in [the number 3 spot](https://github.com/hashicorp/terraform-provider-aws/pulls?q=is%3Apr+is%3Aopen+sort%3Areactions-%2B1-desc) in the upvote ranking now. But evidently the upvotes don't actually matter since I see no extra attention paid to this PR. 🤷 

I just opened the same PR to the opentofu fork. I'm not even sure if they accept contributions yet, but let's see if it moves faster. https://github.com/opentofu/terraform-provider-aws/pull/36

**Comment by JTaylor-myenergi** [comment]
I'm guessing this is getting a low priority because the acceptance tests haven't been run, or updated. We could potentially help with this if you don't have time?

**Comment by stefansundin** [comment]
@JTaylor-myenergi I'm willing to pull updated tests into this branch. You can fork my branch and post a comment here with a link to it when you have updated the tests, and I'll cherry-pick your commits.

Or open a PR to the branch [in my fork](https://github.com/stefansundin/terraform-provider-aws), whatever works best for you.

**Comment by JTaylor-myenergi** [comment]
@stefansundin I had a quick look at this but found a large number of pre-existing tests are failing here so this probably needs some further work.

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
% make testacc PKG=elasticache TESTS="TestAccElastiCacheReplicationGroup_" ACCTEST_PARALLELISM=8
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/elasticache/... -v -count 1 -parallel 8 -run='TestAccElastiCacheReplicationGroup_'  -timeout 360m

--- PASS: TestAccElastiCacheReplicationGroup_clusteringAndCacheNodesCausesError (1.73s)
=== CONT  TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType
--- PASS: TestAccElastiCacheReplicationGroup_Validation_noNodeType (6.56s)
=== CONT  TestAccElastiCacheReplicationGroup_finalSnapshot
--- PASS: TestAccElastiCacheReplicationGroup_basic (765.44s)
=== CONT  TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC (787.55s)
=== CONT  TestAccElastiCacheReplicationGroup_updateMaintenanceWindow
--- PASS: TestAccElastiCacheReplicationGroup_Validation_globalReplicationGroupIdAndNodeType (888.98s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster
--- PASS: TestAccElastiCacheReplicationGroup_tags (935.00s)
=== CONT  TestAccElastiCacheReplicationGroup_vpc
--- PASS: TestAccElastiCacheReplicationGroup_finalSnapshot (959.36s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersFailover_autoFailoverDisabled (1298.62s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize
=== CONT  TestAccElastiCacheReplicationGroup_stateUpgrade5270
--- PASS: TestAccElastiCacheReplicationGroup_updateMaintenanceWindow (761.09s)
--- PASS: TestAccElastiCacheReplicationGroup_autoMinorVersionUpgrade (824.35s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled
--- PASS: TestAccElastiCacheReplicationGroup_vpc (991.71s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_basic (2246.99s)
=== CONT  TestAccElastiCacheReplicationGroup_authToken
--- PASS: TestAccElastiCacheReplicationGroup_stateUpgrade5270 (850.05s)
=== CONT  TestAccElastiCacheReplicationGroup_updateParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_addMemberCluster (1509.31s)
=== CONT  TestAccElastiCacheReplicationGroup_dataTiering
=== CONT  TestAccElastiCacheReplicationGroup_updateNodeSize
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_atTargetSize (1105.17s)
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappearsRemoveMemberCluster_scaleDown (1460.95s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_full (2863.52s)
=== CONT  TestAccElastiCacheReplicationGroup_updateUserGroups
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_multiAZEnabled (1502.14s)
=== CONT  TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled
--- PASS: TestAccElastiCacheReplicationGroup_dataTiering (732.11s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_updateParameterGroup (922.30s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersMemberClusterDisappears_noChange (1498.39s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClustersFailover_autoFailoverEnabled
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Enabled (1026.32s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_update
--- PASS: TestAccElastiCacheReplicationGroup_updateNodeSize (1368.18s)
=== CONT  TestAccElastiCacheReplicationGroup_disappears
--- PASS: TestAccElastiCacheReplicationGroup_authToken (1533.32s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion
--- PASS: TestAccElastiCacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ClusterMode_Disabled (721.71s)
=== CONT  TestAccElastiCacheReplicationGroup_updateDescription
--- PASS: TestAccElastiCacheReplicationGroup_updateUserGroups (975.68s)
=== CONT  TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears
--- PASS: TestAccElastiCacheReplicationGroup_disappears (144.42s)
=== CONT  TestAccElastiCacheReplicationGroup_uppercase
--- PASS: TestAccElastiCacheReplicationGroup_updateDescription (115.92s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterModeValidation_numNodeGroupsOnSecondary (613.00s)
=== CONT  TestAccElastiCacheReplicationGroup_EngineVersion_v7
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_6xToRealVersion (154.05s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_singleNode
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClustersFailover_autoFailoverEnabled (667.28s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup
--- PASS: TestAccElastiCacheReplicationGroup_uppercase (198.63s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_singleNode (547.05s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_v7 (589.39s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_nonClusteredParameterGroup (598.99s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupIDClusterMode_basic (1679.37s)
=== CONT  TestAccElastiCacheReplicationGroup_basic_v5
--- PASS: TestAccElastiCacheReplicationGroup_GlobalReplicationGroupID_disappears (1512.96s)
=== CONT  TestAccElastiCacheReplicationGroup_tagWithOtherModification
--- PASS: TestAccElastiCacheReplicationGroup_basic_v5 (796.13s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption7x
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_updateReplicasPerNodeGroup (1690.47s)
=== CONT  TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover
--- PASS: TestAccElastiCacheReplicationGroup_ValidationMultiAz_noAutomaticFailover (1.18s)
=== CONT  TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleDown (1792.18s)
=== CONT  TestAccElastiCacheReplicationGroup_ClusterMode_basic
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroups_scaleUp (1707.04s)
=== CONT  TestAccElastiCacheReplicationGroup_useCMKKMSKeyID
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleDown (2216.28s)
=== CONT  TestAccElastiCacheReplicationGroup_networkType
--- PASS: TestAccElastiCacheReplicationGroup_ClusterModeUpdateNumNodeGroupsAndReplicasPerNodeGroup_scaleUp (2237.06s)
=== CONT  TestAccElastiCacheReplicationGroup_enableAtRestEncryption
--- PASS: TestAccElastiCacheReplicationGroup_ClusterMode_basic (879.29s)
=== CONT  TestAccElastiCacheReplicationGroup_ipDiscovery
--- PASS: TestAccElastiCacheReplicationGroup_useCMKKMSKeyID (727.13s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken
--- PASS: TestAccElastiCacheReplicationGroup_EngineVersion_update (3748.93s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_NumberCacheClusters_basic (1520.00s)
=== CONT  TestAccElastiCacheReplicationGroup_transitEncryption5x
--- PASS: TestAccElastiCacheReplicationGroup_tagWithOtherModification (2014.84s)
=== CONT  TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC
--- PASS: TestAccElastiCacheReplicationGroup_enableAtRestEncryption (731.15s)
=== CONT  TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated
--- PASS: TestAccElastiCacheReplicationGroup_ipDiscovery (898.31s)
=== CONT  TestAccElastiCacheReplicationGroup_enableSnapshotting
--- PASS: TestAccElastiCacheReplicationGroup_networkType (990.69s)
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryptionWithAuthToken (730.96s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzNotInVPC_repeated (234.11s)
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption7x (2125.64s)
--- PASS: TestAccElastiCacheReplicationGroup_deprecatedAvailabilityZones_multiAzInVPC (366.87s)
--- PASS: TestAccElastiCacheReplicationGroup_multiAzInVPC (533.45s)
--- PASS: TestAccElastiCacheReplicationGroup_transitEncryption5x (525.81s)
--- PASS: TestAccElastiCacheReplicationGroup_enableSnapshotting (196.81s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/elasticache        7887.350s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @stefansundin! 👍 

We also appreciate your patience in getting this reviewed. We do our best to keep track and prioritize the most popular community items, but recognize we don't always get it right. I made a handful of small changes to your initial submission:

- Instead of explicitly checking for an `available` status in the read operation, I changed the waiter to accept a `delay` argument. This allows us to skip the initial delay in cases we expect the replication group to already be available (such as the read operation or checking for tagging operations to be completed), but continue to delay polling in cases we know it will take time (such as creation or modification).
- I added some context to the `transit_encryption_enabled` documentation to indicate a new resource is still forced when the Redis engine version is `< 7.0.5`.
- I added acceptance tests to cover workflows where the `transit_encryption_enabled` and `transit_encryption_mode` arguments are modified for both `5.x` and `7.x` engine versions, ensuring the replication group is re-created in the former case, but updated in-place for the latter.

We appreciate all the detail around potential error cases in the PR summary and related issues - it was helpful to ensure we got the test cases right. Thanks again!

**Pull request merged**
