### PR TITLE
[WIP] Region/partition-agnostic aws_instance acceptance tests

### PR DESCRIPTION
**Pull request by ewbankkit**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes https://github.com/terraform-providers/terraform-provider-aws/issues/4987.

Enable the `aws_instance` data source and resource acceptance tests to be run outside `us-west-2`.

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

See below.

### CODE REVIEW

**Comment by ewbankkit** [comment]
Not all instance types are available in all regions:

```console
$ AWS_DEFAULT_REGION=us-east-2 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstanceDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstanceDataSource_ -timeout 12000m
=== RUN   TestAccAWSInstanceDataSource_basic
=== PAUSE TestAccAWSInstanceDataSource_basic
=== RUN   TestAccAWSInstanceDataSource_tags
=== PAUSE TestAccAWSInstanceDataSource_tags
=== RUN   TestAccAWSInstanceDataSource_AzUserData
=== PAUSE TestAccAWSInstanceDataSource_AzUserData
=== RUN   TestAccAWSInstanceDataSource_gp2IopsDevice
=== PAUSE TestAccAWSInstanceDataSource_gp2IopsDevice
=== RUN   TestAccAWSInstanceDataSource_blockDevices
=== PAUSE TestAccAWSInstanceDataSource_blockDevices
=== RUN   TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
=== PAUSE TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
=== RUN   TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
=== PAUSE TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
=== RUN   TestAccAWSInstanceDataSource_rootInstanceStore
=== PAUSE TestAccAWSInstanceDataSource_rootInstanceStore
=== RUN   TestAccAWSInstanceDataSource_privateIP
=== PAUSE TestAccAWSInstanceDataSource_privateIP
=== RUN   TestAccAWSInstanceDataSource_keyPair
=== PAUSE TestAccAWSInstanceDataSource_keyPair
=== RUN   TestAccAWSInstanceDataSource_VPC
=== PAUSE TestAccAWSInstanceDataSource_VPC
=== RUN   TestAccAWSInstanceDataSource_PlacementGroup
=== PAUSE TestAccAWSInstanceDataSource_PlacementGroup
=== RUN   TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups
--- SKIP: TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups (0.00s)
    data_source_aws_instance_test.go:273: EC2_CLASSIC_REGION must be set to run EC2-Classic acceptance tests
=== RUN   TestAccAWSInstanceDataSource_VPCSecurityGroups
=== PAUSE TestAccAWSInstanceDataSource_VPCSecurityGroups
=== RUN   TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== PAUSE TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== RUN   TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== PAUSE TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== RUN   TestAccAWSInstanceDataSource_GetUserData
=== PAUSE TestAccAWSInstanceDataSource_GetUserData
=== RUN   TestAccAWSInstanceDataSource_GetUserData_NoUserData
=== PAUSE TestAccAWSInstanceDataSource_GetUserData_NoUserData
=== RUN   TestAccAWSInstanceDataSource_creditSpecification
=== PAUSE TestAccAWSInstanceDataSource_creditSpecification
=== CONT  TestAccAWSInstanceDataSource_basic
=== CONT  TestAccAWSInstanceDataSource_VPC
--- FAIL: TestAccAWSInstanceDataSource_basic (15.97s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: fdd0b438-08f2-4af5-9477-f6d8e5e81498
        
          on /tmp/tf-test758210104/main.tf line 17:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_creditSpecification
--- FAIL: TestAccAWSInstanceDataSource_VPC (20.51s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: 5fb2137c-62eb-4030-927f-c3726dc85d1a
        
          on /tmp/tf-test561705015/main.tf line 41:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_GetUserData_NoUserData
--- PASS: TestAccAWSInstanceDataSource_creditSpecification (83.42s)
=== CONT  TestAccAWSInstanceDataSource_GetUserData
--- PASS: TestAccAWSInstanceDataSource_GetUserData (129.01s)
=== CONT  TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
--- PASS: TestAccAWSInstanceDataSource_GetUserData_NoUserData (252.12s)
=== CONT  TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_falseToTrue (164.39s)
=== CONT  TestAccAWSInstanceDataSource_VPCSecurityGroups
--- FAIL: TestAccAWSInstanceDataSource_VPCSecurityGroups (30.60s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: 4ed60c18-c399-472c-b622-df647ced23aa
        
          on /tmp/tf-test853420282/main.tf line 66:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_PlacementGroup
--- FAIL: TestAccAWSInstanceDataSource_PlacementGroup (19.29s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: de69c621-0da6-4d18-914d-8e02d0b440e9
        
          on /tmp/tf-test576384619/main.tf line 47:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
--- FAIL: TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId (4.27s)
    testing.go:635: Step 0 error: errors during refresh:
        
        Error: Your query returned no results. Please change your search criteria and try again.
        
          on /tmp/tf-test599268656/main.tf line 2:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_keyPair
--- FAIL: TestAccAWSInstanceDataSource_keyPair (11.94s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: c3aeb9c1-ba4b-49ba-956d-13434997218e
        
          on /tmp/tf-test317505743/main.tf line 22:
          (source code not available)
        
        
    testing.go:696: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during refresh: Your query returned no results. Please change your search criteria and try again.
        
        State: <nil>
=== CONT  TestAccAWSInstanceDataSource_privateIP
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_trueToFalse (194.11s)
=== CONT  TestAccAWSInstanceDataSource_rootInstanceStore
--- FAIL: TestAccAWSInstanceDataSource_rootInstanceStore (15.48s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: c8a9b2bf-3fbc-4b23-a507-e4cb734d013e
        
          on /tmp/tf-test059023204/main.tf line 17:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
--- FAIL: TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId (4.30s)
    testing.go:635: Step 0 error: errors during refresh:
        
        Error: Your query returned no results. Please change your search criteria and try again.
        
          on /tmp/tf-test187818550/main.tf line 2:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_gp2IopsDevice
--- FAIL: TestAccAWSInstanceDataSource_gp2IopsDevice (4.12s)
    testing.go:635: Step 0 error: errors during refresh:
        
        Error: Your query returned no results. Please change your search criteria and try again.
        
          on /tmp/tf-test850867741/main.tf line 2:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_blockDevices
--- FAIL: TestAccAWSInstanceDataSource_blockDevices (4.43s)
    testing.go:635: Step 0 error: errors during refresh:
        
        Error: Your query returned no results. Please change your search criteria and try again.
        
          on /tmp/tf-test404832472/main.tf line 2:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_AzUserData
--- FAIL: TestAccAWSInstanceDataSource_AzUserData (15.13s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: InvalidParameterValue: Invalid availability zone: [us-west-2a]
        	status code: 400, request id: 701dd8c0-0896-474f-bfc4-c8dfd5cb020c
        
          on /tmp/tf-test185421399/main.tf line 17:
          (source code not available)
        
        
=== CONT  TestAccAWSInstanceDataSource_tags
--- FAIL: TestAccAWSInstanceDataSource_tags (11.21s)
    testing.go:635: Step 0 error: errors during apply:
        
        Error: Error launching source instance: Unsupported: The requested configuration is currently not supported. Please check the documentation for supported configurations.
        	status code: 400, request id: e0d8bac1-8a20-4ad6-83c7-3dc6dd4a91dc
        
          on /tmp/tf-test506749324/main.tf line 17:
          (source code not available)
        
        
    testing.go:696: Error destroying resource! WARNING: Dangling resources
        may exist. The full state and error is shown below.
        
        Error: errors during refresh: Your query returned no results. Please change your search criteria and try again.
        
        State: <nil>
--- PASS: TestAccAWSInstanceDataSource_privateIP (92.96s)
FAIL
FAIL	github.com/terraform-providers/terraform-provider-aws/aws	551.890s
FAIL
GNUmakefile:24: recipe for target 'testacc' failed
make: *** [testacc] Error 1
```

**Comment by ewbankkit** [comment]
Acceptance test results.

#### Data sources:

##### `aws_instance`

```console
# EC2-Classic tests now gated by environment variable.
$ EC2_CLASSIC_REGION=us-east-1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups -timeout 1200m
=== RUN   TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups
=== PAUSE TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups
=== CONT  TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups
--- PASS: TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups (307.50s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	307.527s
# Default acceptance test region (us-west-2):
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstanceDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstanceDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstanceDataSource_basic
=== PAUSE TestAccAWSInstanceDataSource_basic
=== RUN   TestAccAWSInstanceDataSource_tags
=== PAUSE TestAccAWSInstanceDataSource_tags
=== RUN   TestAccAWSInstanceDataSource_AzUserData
=== PAUSE TestAccAWSInstanceDataSource_AzUserData
=== RUN   TestAccAWSInstanceDataSource_gp2IopsDevice
=== PAUSE TestAccAWSInstanceDataSource_gp2IopsDevice
=== RUN   TestAccAWSInstanceDataSource_blockDevices
=== PAUSE TestAccAWSInstanceDataSource_blockDevices
=== RUN   TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
=== PAUSE TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
=== RUN   TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
=== PAUSE TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
=== RUN   TestAccAWSInstanceDataSource_rootInstanceStore
=== PAUSE TestAccAWSInstanceDataSource_rootInstanceStore
=== RUN   TestAccAWSInstanceDataSource_privateIP
=== PAUSE TestAccAWSInstanceDataSource_privateIP
=== RUN   TestAccAWSInstanceDataSource_keyPair
=== PAUSE TestAccAWSInstanceDataSource_keyPair
=== RUN   TestAccAWSInstanceDataSource_VPC
=== PAUSE TestAccAWSInstanceDataSource_VPC
=== RUN   TestAccAWSInstanceDataSource_PlacementGroup
=== PAUSE TestAccAWSInstanceDataSource_PlacementGroup
=== RUN   TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups
--- SKIP: TestAccAWSInstanceDataSource_Ec2ClassicSecurityGroups (0.00s)
    data_source_aws_instance_test.go:330: EC2_CLASSIC_REGION must be set to run EC2-Classic acceptance tests
=== RUN   TestAccAWSInstanceDataSource_VPCSecurityGroups
=== PAUSE TestAccAWSInstanceDataSource_VPCSecurityGroups
=== RUN   TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== PAUSE TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
=== RUN   TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== PAUSE TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
=== RUN   TestAccAWSInstanceDataSource_GetUserData
=== PAUSE TestAccAWSInstanceDataSource_GetUserData
=== RUN   TestAccAWSInstanceDataSource_GetUserData_NoUserData
=== PAUSE TestAccAWSInstanceDataSource_GetUserData_NoUserData
=== RUN   TestAccAWSInstanceDataSource_creditSpecification
=== PAUSE TestAccAWSInstanceDataSource_creditSpecification
=== CONT  TestAccAWSInstanceDataSource_basic
=== CONT  TestAccAWSInstanceDataSource_VPC
--- PASS: TestAccAWSInstanceDataSource_VPC (113.78s)
=== CONT  TestAccAWSInstanceDataSource_creditSpecification
--- PASS: TestAccAWSInstanceDataSource_basic (126.65s)
=== CONT  TestAccAWSInstanceDataSource_GetUserData_NoUserData
--- PASS: TestAccAWSInstanceDataSource_creditSpecification (123.93s)
=== CONT  TestAccAWSInstanceDataSource_GetUserData
--- PASS: TestAccAWSInstanceDataSource_GetUserData_NoUserData (286.12s)
=== CONT  TestAccAWSInstanceDataSource_getPasswordData_falseToTrue
--- PASS: TestAccAWSInstanceDataSource_GetUserData (198.00s)
=== CONT  TestAccAWSInstanceDataSource_getPasswordData_trueToFalse
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_falseToTrue (197.48s)
=== CONT  TestAccAWSInstanceDataSource_VPCSecurityGroups
--- PASS: TestAccAWSInstanceDataSource_getPasswordData_trueToFalse (198.58s)
=== CONT  TestAccAWSInstanceDataSource_PlacementGroup
--- PASS: TestAccAWSInstanceDataSource_VPCSecurityGroups (121.09s)
=== CONT  TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId
--- PASS: TestAccAWSInstanceDataSource_PlacementGroup (101.96s)
=== CONT  TestAccAWSInstanceDataSource_keyPair
--- PASS: TestAccAWSInstanceDataSource_keyPair (96.45s)
=== CONT  TestAccAWSInstanceDataSource_privateIP
--- PASS: TestAccAWSInstanceDataSource_EbsBlockDevice_KmsKeyId (132.13s)
=== CONT  TestAccAWSInstanceDataSource_rootInstanceStore
--- PASS: TestAccAWSInstanceDataSource_privateIP (132.63s)
=== CONT  TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId
--- PASS: TestAccAWSInstanceDataSource_rootInstanceStore (111.89s)
=== CONT  TestAccAWSInstanceDataSource_gp2IopsDevice
--- PASS: TestAccAWSInstanceDataSource_gp2IopsDevice (105.44s)
=== CONT  TestAccAWSInstanceDataSource_blockDevices
--- PASS: TestAccAWSInstanceDataSource_RootBlockDevice_KmsKeyId (142.21s)
=== CONT  TestAccAWSInstanceDataSource_AzUserData
--- PASS: TestAccAWSInstanceDataSource_blockDevices (105.13s)
=== CONT  TestAccAWSInstanceDataSource_tags
--- PASS: TestAccAWSInstanceDataSource_AzUserData (116.96s)
--- PASS: TestAccAWSInstanceDataSource_tags (208.97s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	1394.955s
# us-east-2:
```

##### `aws_instances`

```console
# Default acceptance test region (us-west-2):
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- PASS: TestAccAWSInstancesDataSource_instance_state_names (100.09s)
=== CONT  TestAccAWSInstancesDataSource_tags
--- PASS: TestAccAWSInstancesDataSource_basic (100.16s)
--- PASS: TestAccAWSInstancesDataSource_tags (100.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	200.593s
# us-east-2:
$ AWS_DEFAULT_REGION=us-east-2 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- PASS: TestAccAWSInstancesDataSource_instance_state_names (77.45s)
=== CONT  TestAccAWSInstancesDataSource_tags
--- PASS: TestAccAWSInstancesDataSource_basic (77.46s)
--- PASS: TestAccAWSInstancesDataSource_tags (87.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	164.508s
# us-east-1; EC2-Classic:
$ AWS_DEFAULT_REGION=us-east-1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- SKIP: TestAccAWSInstancesDataSource_basic (1.91s)
    provider_test.go:267: This test can only in regions without EC2 Classic, platforms available in us-east-1: ["EC2" "VPC"]
=== CONT  TestAccAWSInstancesDataSource_tags
--- SKIP: TestAccAWSInstancesDataSource_instance_state_names (1.97s)
    provider_test.go:267: This test can only in regions without EC2 Classic, platforms available in us-east-1: ["EC2" "VPC"]
--- SKIP: TestAccAWSInstancesDataSource_tags (1.67s)
    provider_test.go:267: This test can only in regions without EC2 Classic, platforms available in us-east-1: ["EC2" "VPC"]
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3.613s
# eu-west-1; No default VPC:
$ AWS_DEFAULT_REGION=eu-west-1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- SKIP: TestAccAWSInstancesDataSource_basic (2.85s)
    resource_aws_instance_test.go:4101: skipping tests; eu-west-1 does not have a default VPC
=== CONT  TestAccAWSInstancesDataSource_tags
--- SKIP: TestAccAWSInstancesDataSource_instance_state_names (2.86s)
    resource_aws_instance_test.go:4101: skipping tests; eu-west-1 does not have a default VPC
--- SKIP: TestAccAWSInstancesDataSource_tags (2.45s)
    resource_aws_instance_test.go:4101: skipping tests; eu-west-1 does not have a default VPC
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5.328s
```

#### Resource:

```console
```

**Comment by ewbankkit** [comment]
Acceptance test results.

#### Data sources:

##### `aws_instances`

```console
# Default acceptance test region (us-west-2):
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- PASS: TestAccAWSInstancesDataSource_instance_state_names (100.09s)
=== CONT  TestAccAWSInstancesDataSource_tags
--- PASS: TestAccAWSInstancesDataSource_basic (100.16s)
--- PASS: TestAccAWSInstancesDataSource_tags (100.48s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	200.593s
# us-east-2:
$ AWS_DEFAULT_REGION=us-east-2 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- PASS: TestAccAWSInstancesDataSource_instance_state_names (77.45s)
=== CONT  TestAccAWSInstancesDataSource_tags
--- PASS: TestAccAWSInstancesDataSource_basic (77.46s)
--- PASS: TestAccAWSInstancesDataSource_tags (87.03s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	164.508s
# us-east-1; EC2-Classic:
$ AWS_DEFAULT_REGION=us-east-1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- SKIP: TestAccAWSInstancesDataSource_basic (1.91s)
    provider_test.go:267: This test can only in regions without EC2 Classic, platforms available in us-east-1: ["EC2" "VPC"]
=== CONT  TestAccAWSInstancesDataSource_tags
--- SKIP: TestAccAWSInstancesDataSource_instance_state_names (1.97s)
    provider_test.go:267: This test can only in regions without EC2 Classic, platforms available in us-east-1: ["EC2" "VPC"]
--- SKIP: TestAccAWSInstancesDataSource_tags (1.67s)
    provider_test.go:267: This test can only in regions without EC2 Classic, platforms available in us-east-1: ["EC2" "VPC"]
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	3.613s
# eu-west-1; No default VPC:
$ AWS_DEFAULT_REGION=eu-west-1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstancesDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 2 -run=TestAccAWSInstancesDataSource_ -timeout 1200m
=== RUN   TestAccAWSInstancesDataSource_basic
=== PAUSE TestAccAWSInstancesDataSource_basic
=== RUN   TestAccAWSInstancesDataSource_tags
=== PAUSE TestAccAWSInstancesDataSource_tags
=== RUN   TestAccAWSInstancesDataSource_instance_state_names
=== PAUSE TestAccAWSInstancesDataSource_instance_state_names
=== CONT  TestAccAWSInstancesDataSource_basic
=== CONT  TestAccAWSInstancesDataSource_instance_state_names
--- SKIP: TestAccAWSInstancesDataSource_basic (2.85s)
    resource_aws_instance_test.go:4101: skipping tests; eu-west-1 does not have a default VPC
=== CONT  TestAccAWSInstancesDataSource_tags
--- SKIP: TestAccAWSInstancesDataSource_instance_state_names (2.86s)
    resource_aws_instance_test.go:4101: skipping tests; eu-west-1 does not have a default VPC
--- SKIP: TestAccAWSInstancesDataSource_tags (2.45s)
    resource_aws_instance_test.go:4101: skipping tests; eu-west-1 does not have a default VPC
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5.328s
```

**Comment by ewbankkit** [comment]
Acceptance test results.

#### Resource:

```console
```

**Comment by ewbankkit** [comment]
The acceptance test failures for the `aws_instance` resource in `us-east-1` are because that account has EC2-Classic available and `source_dest_check` has a default value of `true` in the resource's schema but isn't set on Read when the instance is not on a subnet (i.e. in EC2-Classic).

I'm removing _WIP_ - this PR is now ready for review.

The gist of the changes is:
* Pass `instance_type` as a parameter to each test case's configuration generation function (plus a random instance name) and check that the current test region (as configured via `AWS_DEFAULT_REGION`) supports that instance type by using the new EC2 [`DescribeInstanceTypeOfferings`](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_DescribeInstanceTypeOfferings.html) API and a `PreCheck`function. No instance types were changed
* Add `PreCheck`s that the test region either has a default VPC or supports EC2-Classic in the (many) test cases that no `subnet_id` is specified for the instance
* Changed the `image_id`s to use the preferred `amzn-ami-minimal-hvm-instance-store` AMI (region-agnostic) except when an AMI with a very specific device configuration is required
* In the one case where a very specific AMI is required and is only available in `us-west-2`, add a `PreCheck` for that region

**Comment by ewbankkit** [comment]
Rebased to remove merge conflict and re-ran affected acceptance test:

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSInstance_instanceProfileChange'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSInstance_instanceProfileChange -timeout 120m
=== RUN   TestAccAWSInstance_instanceProfileChange
=== PAUSE TestAccAWSInstance_instanceProfileChange
=== CONT  TestAccAWSInstance_instanceProfileChange
--- PASS: TestAccAWSInstance_instanceProfileChange (286.57s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	287.871s
```

**Comment by ewbankkit** [comment]
See also https://github.com/terraform-providers/terraform-provider-aws/pull/12277.

**Comment by ewbankkit** [comment]
Related:
* https://github.com/terraform-providers/terraform-provider-aws/issues/12995
* https://github.com/terraform-providers/terraform-provider-aws/issues/12996
* https://github.com/terraform-providers/terraform-provider-aws/issues/12994

**Comment by ewbankkit** [comment]
See also:
* https://github.com/terraform-providers/terraform-provider-aws/issues/13083
* https://github.com/terraform-providers/terraform-provider-aws/pull/13076

**Comment by YakDriver** [comment]
@ewbankkit 👋  Kit, this is a tremendous effort! Thank you. This fixes issues that we are currently working to fix and so we'd like to move this along. However, due to its size, this PR creates conflicts and is difficult to review. Would you be willing to break it into several incremental steps? I'm not sure of the exact best way to break it up but figured you'd know better than anyone.

**Comment by ewbankkit** [comment]
@YakDriver Yes, this one has become a bit stale over the months and is probably not worth keeping in its current form.
Since I started on this the `aws_ec2_instance_type_offering` data source has been introduced and the `testAccAvailableEc2InstanceTypeForRegion()` function can be used instead of hard-coding and checking for the instance types. I'd also make the tests independent of the default VPC wherever possible (#13260).
As a preliminary, could you look at https://github.com/terraform-providers/terraform-provider-aws/pull/13361 and https://github.com/terraform-providers/terraform-provider-aws/pull/13091 as these provide some useful shared methods for tackling this problem?
I'd also have separate PRs for each data source and resource.
Let's leave this one open until I have submitted at least _WIP_ replacement PRs.

**Comment by YakDriver** [comment]
@ewbankkit Sorry to leave this languishing. Where do you want to take this PR at this point? The flurry of region/partition activity has calmed down so may be a good time to see what's what here.

**Comment by ewbankkit** [comment]
I'll do a review but I think that the material changes have all been made via the PRs you mention.
If that's the case I'll just close this one.

**Comment by ewbankkit** [comment]
OK, I'm going to close this one. The only changes that haven't been covered by other PRs are ones that check for default VPC with default subnets (using `testAccPreCheckEc2ClassicOrHasDefaultVpcWithDefaultSubnets`) that should be addressed for #13260.

**Pull request closed without merging**
