### PR TITLE
`r/aws_quicksight_data_set`: Allow physical_table_map to be optional

### LINKED ISSUE #31863: [Bug]:  Cannot create Quicksight Dataset from other datasets
### Terraform Core Version

1.4.5

### AWS Provider Version

5.1.0

### Affected Resource(s)

aws_quicksight_data_set

### Expected Behavior

Creates dataset by joining two existing datasets

### Actual Behavior

Fails to create resource

### Relevant Error/Panic Output Snippet

```shell
│ {
│   RespMetadata: {
│     StatusCode: 400,
│     RequestID: "897f6e0e-bcb4-48a8-8f84-c8c85d0c1891"
│   },
│   Message_: "Invalid PhysicalTableMap"
│ }
│
│   with aws_quicksight_data_set.account_emails_dataset,
│   on main.tf line 396, in resource "aws_quicksight_data_set" "account_emails_dataset":
│  396: resource "aws_quicksight_data_set" "account_emails_dataset" {
```

### Terraform Configuration Files

```
resource "aws_quicksight_data_set" "account_emails_dataset" {
  aws_account_id = data.aws_caller_identity.current.account_id
  data_set_id    = "account-emails-dataset"
  import_mode    = "SPICE"
  name           = "Account Emails"

  data_set_usage_configuration {
    disable_use_as_direct_query_source = false
    disable_use_as_imported_source     = false
  }

  physical_table_map {
    physical_table_map_id = "account-email-dataset"
  }

  logical_table_map {
    logical_table_map_id = "accounts-table"
    alias                = "accounts"
    source {
      data_set_arn = "b55386c7-b7f2-4105-ac5e-ad8e782ee851"
    }
  }

  logical_table_map {
    logical_table_map_id = "email-table"
    alias                = "emails"
    source {
      data_set_arn = "45a84a9-22d2-45ae-8e0f-f1f1e386d84b"
    }
  }

  logical_table_map {
    logical_table_map_id = "account-emails"
    alias                = "Account Emails"
    data_transforms {
      project_operation {
        projected_columns = [
          "username",
          "email"
        ]
      }
    }

    source {
      join_instruction {
        left_operand  = "accounts-table"
        right_operand = "emails-table"
        type          = "INNER"
        on_clause     = "{account_id} = {external_id}"
      }
    }
  }
}
```

### Steps to Reproduce

1. Create two Datasets in Quicksight
2. Create a Dataset in Quicksight that joins the two dataset resources

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by g-dx**
### Description

Currently, the schema for the `aws_quicksight_data_set` resource marks the `physical_table_map` field as `Required`. 

However, the AWS API makes clear that while required, the map it represents may contain zero entries:

```
PhysicalTableMap

    Declares the physical tables that are available in the underlying data sources.

    Type: String to PhysicalTable object map

    Map Entries: Minimum number of 0 items. Maximum number of 32 items.

    Key Length Constraints: Minimum length of 1. Maximum length of 64.

    Key Pattern: [0-9a-zA-Z-]*

    Required: Yes
```
[Source](https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateDataSet.html#API_CreateDataSet_RequestSyntax)

The present schema definition of `Required` therefore makes it impossible to specify an empty map. 

This PR fixes this by updating the `physical_table_map` field to be `Optional` and ensures that an empty map is passed to the AWS SDK in the event that no `physical_table_map` blocks have been specified.

### Relations

Fixes #31863
Related To: #30349

### References

* https://docs.aws.amazon.com/quicksight/latest/APIReference/API_CreateDataSet.html#API_CreateDataSet_RequestSyntax

### Output from Acceptance Testing

```
$ make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet'  -timeout 180m
?   	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema	[no test files]
=== RUN   TestAccQuickSightDataSetDataSource_basic
=== PAUSE TestAccQuickSightDataSetDataSource_basic
=== RUN   TestAccQuickSightDataSet_basic
=== PAUSE TestAccQuickSightDataSet_basic
=== RUN   TestAccQuickSightDataSet_disappears
=== PAUSE TestAccQuickSightDataSet_disappears
=== RUN   TestAccQuickSightDataSet_columnGroups
=== PAUSE TestAccQuickSightDataSet_columnGroups
=== RUN   TestAccQuickSightDataSet_columnLevelPermissionRules
=== PAUSE TestAccQuickSightDataSet_columnLevelPermissionRules
=== RUN   TestAccQuickSightDataSet_dataSetUsageConfiguration
=== PAUSE TestAccQuickSightDataSet_dataSetUsageConfiguration
=== RUN   TestAccQuickSightDataSet_fieldFolders
=== PAUSE TestAccQuickSightDataSet_fieldFolders
=== RUN   TestAccQuickSightDataSet_logicalTableMap
=== PAUSE TestAccQuickSightDataSet_logicalTableMap
=== RUN   TestAccQuickSightDataSet_permissions
=== PAUSE TestAccQuickSightDataSet_permissions
=== RUN   TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== PAUSE TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== RUN   TestAccQuickSightDataSet_refreshProperties
    data_set_test.go:373: Environment variable QUICKSIGHT_ATHENA_TESTING_ENABLED is not set
--- SKIP: TestAccQuickSightDataSet_refreshProperties (0.00s)
=== RUN   TestAccQuickSightDataSet_tags
=== PAUSE TestAccQuickSightDataSet_tags
=== RUN   TestAccQuickSightDataSet_noPhysicalTableMap
=== PAUSE TestAccQuickSightDataSet_noPhysicalTableMap
=== CONT  TestAccQuickSightDataSetDataSource_basic
=== CONT  TestAccQuickSightDataSet_fieldFolders
=== CONT  TestAccQuickSightDataSet_noPhysicalTableMap
=== CONT  TestAccQuickSightDataSet_tags
=== CONT  TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration
=== CONT  TestAccQuickSightDataSet_columnGroups
=== CONT  TestAccQuickSightDataSet_permissions
=== CONT  TestAccQuickSightDataSet_logicalTableMap
=== CONT  TestAccQuickSightDataSet_basic
=== CONT  TestAccQuickSightDataSet_disappears
=== CONT  TestAccQuickSightDataSet_columnLevelPermissionRules
=== CONT  TestAccQuickSightDataSet_dataSetUsageConfiguration
--- PASS: TestAccQuickSightDataSet_disappears (44.39s)
--- PASS: TestAccQuickSightDataSetDataSource_basic (49.79s)
--- PASS: TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration (54.89s)
--- PASS: TestAccQuickSightDataSet_columnGroups (54.89s)
--- PASS: TestAccQuickSightDataSet_basic (55.04s)
--- PASS: TestAccQuickSightDataSet_fieldFolders (55.82s)
--- PASS: TestAccQuickSightDataSet_dataSetUsageConfiguration (55.87s)
--- PASS: TestAccQuickSightDataSet_columnLevelPermissionRules (56.42s)
--- PASS: TestAccQuickSightDataSet_noPhysicalTableMap (56.95s)
--- PASS: TestAccQuickSightDataSet_logicalTableMap (82.24s)
--- PASS: TestAccQuickSightDataSet_tags (95.20s)
--- PASS: TestAccQuickSightDataSet_permissions (106.93s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/quicksight	107.055s
...

### CODE REVIEW

**Comment by g-dx** [comment]
Hey, @jar-b of course I can add a test.

More generally the intent of this PR is that it allows data sets which are **composed of other datasets**, via a join instruction. In these cases there is no physical table map. 

Roughly like this:

```terraform
resource "aws_quicksight_data_set" "one" {
 // ...
}

resource "aws_quicksight_data_set" "two" {
 // ...
}

resource "aws_quicksight_data_set" "joined" {

  logical_table_map {
    logical_table_map_id = "one"
    source {
      data_set_arn = aws_quicksight_data_set.one.arn
    }
  }


  logical_table_map {
    logical_table_map_id = "two"
    source {
      data_set_arn = aws_quicksight_data_set.two.arn
    }
  }


  logical_table_map {
    logical_table_map_id = "result"

    source {
      join_instruction {
        left_operand  = "one"
        right_operand = "two"
        type          = "INNER"
        on_clause     = "{col1} = {col2}"
      }
    }
  }
}
```

**Comment by jar-b** [comment]
Ah, thanks for the clarification. I should have been using `source.data_set_arn` from a separate data set instead of `source.physical_table_id`. I'll await a functional test from someone that knows what they're doing :). Thanks!

**Comment by g-dx** [comment]
Hey @jar-b I've updated the PR with a test which creates a data set _without_ a physical table map. Let me know if that's all good or there's anything else which should be added.

Thanks again for your help!

**Review by jar-b — APPROVED** [review]
LGTM 🎉 

```console
$ make testacc PKG=quicksight TESTS=TestAccQuickSightDataSet_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/quicksight/... -v -count 1 -parallel 20 -run='TestAccQuickSightDataSet_'  -timeout 180m
?       github.com/hashicorp/terraform-provider-aws/internal/service/quicksight/schema  [no test files]

--- PASS: TestAccQuickSightDataSet_disappears (40.21s)
--- PASS: TestAccQuickSightDataSet_columnLevelPermissionRules (43.61s)
--- PASS: TestAccQuickSightDataSet_rowLevelPermissionTagConfiguration (44.26s)
--- PASS: TestAccQuickSightDataSet_fieldFolders (45.44s)
--- PASS: TestAccQuickSightDataSet_basic (45.47s)
--- PASS: TestAccQuickSightDataSet_columnGroups (45.92s)
--- PASS: TestAccQuickSightDataSet_dataSetUsageConfiguration (45.92s)
--- PASS: TestAccQuickSightDataSet_noPhysicalTableMap (48.54s)
--- PASS: TestAccQuickSightDataSet_logicalTableMap (70.08s)
--- PASS: TestAccQuickSightDataSet_tags (88.90s)
--- PASS: TestAccQuickSightDataSet_permissions (93.98s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/quicksight 97.212s
```

**Comment by jar-b** [comment]
Thanks for your contribution, @g-dx! 👍

**Pull request merged**
