### PR TITLE
feat: Pinpoint - Support new Google Cloud Messaging auth

### LINKED ISSUE #35261: [New Resource]: Add Pinpoint FCM channel resource
### Description

Existing resource `aws_pinpoint_gcm_channel` uses Google Cloud Messaging API which is going to be deprecated by **6/20/2024**

"If you are an existing user of the legacy HTTP or XMPP APIs (deprecated on 6/20/2023), you must migrate to the latest Firebase Cloud Messaging API (HTTP v1) by 6/20/2024"

Official migration manual https://firebase.google.com/docs/cloud-messaging/migrate-v1

### Requested Resource(s) and/or Data Source(s)
```
aws_pinpoint_fcm_channel
```
### Potential Terraform Configuration

_No response_

### References

- https://docs.aws.amazon.com/pinpoint/latest/apireference/apps-application-id-channels-gcm.html

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by TokyoQ**
### Description
Support for the updated Google Cloud Messaging authentication method as mentioned in #35261. 

The existing (legacy) method is deprecated as of 21 June 2024 (day PR is raised). 

### Relations

Closes #35261

### Development Notes

I wasn't sure how to set `default_authentication_method` to be an enum. Valid values are `KEY` or `TOKEN`.

### Output from Acceptance Testing

```console
λ make testacc TESTS=GCM  PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='GCM'  -timeout 360m
=== RUN   TestAccPinpointGCMChannel_basic
=== PAUSE TestAccPinpointGCMChannel_basic
=== CONT  TestAccPinpointGCMChannel_basic
--- PASS: TestAccPinpointGCMChannel_basic (54.04s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	58.338s
```

### CODE REVIEW

**Comment by gdavison** [comment]
Thanks for the PR, @TokyoQ. I've made a few changes to the resource and tests.

According to the documentation, the `GCMChannelResponse` returns the `DefaultAuthenticationMethod` value, so it can be set in `Read`. It also has a `Credential` field that should contain the API key, and I'd like to see if this is true and also if it contains the token value.

We don't have access to a Firebase Cloud Messaging service. Would you be able to run the updated tests and post the results here, please?

**Comment by TokyoQ** [comment]
Hi @gdavison, this is the initial test output

```
λ make testacc TESTS=GCM  PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='GCM'  -timeout 360m
=== RUN   TestAccPinpointGCMChannel_basicAPIKey
=== PAUSE TestAccPinpointGCMChannel_basicAPIKey
=== RUN   TestAccPinpointGCMChannel_apiKeyAuthMethod
=== PAUSE TestAccPinpointGCMChannel_apiKeyAuthMethod
=== RUN   TestAccPinpointGCMChannel_tokenAuthMethod
=== PAUSE TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_basicAPIKey
=== CONT  TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_apiKeyAuthMethod
=== NAME  TestAccPinpointGCMChannel_tokenAuthMethod
    gcm_channel_test.go:120: Step 1/2 error: Check failed: Check 3/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'default_authentication_method' expected "KEY", got "TOKEN"
        Check 4/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'api_key' not found
        Check 5/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'service_json' expected "<redacted json file>", got ""
=== NAME  TestAccPinpointGCMChannel_apiKeyAuthMethod
    gcm_channel_test.go:78: Step 1/2 error: Check failed: Check 4/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'api_key' expected "<redacted API key>", got ""
        Check 5/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'service_json' not found
=== NAME  TestAccPinpointGCMChannel_basicAPIKey
    gcm_channel_test.go:41: Step 1/2 error: Check failed: Check 4/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'api_key' expected "<redacted API key>", got ""
        Check 5/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'service_json' not found
--- FAIL: TestAccPinpointGCMChannel_tokenAuthMethod (13.65s)
--- FAIL: TestAccPinpointGCMChannel_basicAPIKey (13.85s)
--- FAIL: TestAccPinpointGCMChannel_apiKeyAuthMethod (13.87s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	18.294s
FAIL
make: *** [testacc] Error 1
```

I updated one of the tests (it passed KEY instead of TOKEN). Latest output:

```
λ make testacc TESTS=GCM  PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='GCM'  -timeout 360m
=== RUN   TestAccPinpointGCMChannel_basicAPIKey
=== PAUSE TestAccPinpointGCMChannel_basicAPIKey
=== RUN   TestAccPinpointGCMChannel_apiKeyAuthMethod
=== PAUSE TestAccPinpointGCMChannel_apiKeyAuthMethod
=== RUN   TestAccPinpointGCMChannel_tokenAuthMethod
=== PAUSE TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_basicAPIKey
=== CONT  TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_apiKeyAuthMethod
=== NAME  TestAccPinpointGCMChannel_basicAPIKey
    gcm_channel_test.go:41: Step 1/2 error: Check failed: Check 4/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'api_key' expected "<redacted api key>", got ""
        Check 5/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'service_json' not found
=== NAME  TestAccPinpointGCMChannel_tokenAuthMethod
    gcm_channel_test.go:120: Step 1/2 error: Check failed: Check 4/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'api_key' not found
        Check 5/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'service_json' expected "<redacted json>", got ""
=== NAME  TestAccPinpointGCMChannel_apiKeyAuthMethod
    gcm_channel_test.go:78: Step 1/2 error: Check failed: Check 4/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'api_key' expected "<redacted api key>", got ""
        Check 5/6 error: aws_pinpoint_gcm_channel.test_gcm_channel: Attribute 'service_json' not found
--- FAIL: TestAccPinpointGCMChannel_basicAPIKey (13.07s)
--- FAIL: TestAccPinpointGCMChannel_tokenAuthMethod (13.39s)
--- FAIL: TestAccPinpointGCMChannel_apiKeyAuthMethod (13.63s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	18.172s
FAIL
make: *** [testacc] Error 1
```

**Comment by gdavison** [comment]
Thanks for running the tests, @TokyoQ. Can you rerun the failing tests with debugging enabled, please? Set the environment variable `TF_LOG` to `DEBUG`

**Comment by TokyoQ** [comment]
@gdavison some debug logs below. I don't see `Credential` being returned anywhere. 

```
# KEY
2024-07-12T12:06:13.596+0100 [DEBUG] aws: HTTP Response Received: tf_aws.sdk=aws-sdk-go rpc.service=Pinpoint http.response.header.x_amz_cf_id=L1WTLoFC2u0DQm_YthuMgiySzF5tQ6ALtasXf4JKkIVids4mHyeVaQ== http.response.header.cache_control=no-store http.status_code=200 http.response.header.x_amzn_trace_id=Root=1-66910e25-53b477ee508fcc8e2516eac0 http.response.header.x_cache="Miss from cloudfront" tf_provider_addr=registry.terraform.io/hashicorp/aws tf_resource_type=aws_pinpoint_gcm_channel tf_rpc=ApplyResourceChange tf_mux_provider="*schema.GRPCProviderServer" rpc.system=aws-api tf_req_id=4404232f-b6af-ec8e-c173-f89d2e9e9fd2 http.response.header.access_control_allow_origin="*" http.response.header.x_amz_apigw_id=ay8l5G_VvHcEOew= http.duration=480 rpc.method=UpdateGcmChannel aws.region=us-west-2 http.response.header.content_type=application/json http.response_content_length=305 http.response.header.via="1.1 6e05560e2a116f10e93777df92ea6478.cloudfront.net (CloudFront)" http.response.header.date="Fri, 12 Jul 2024 11:06:13 GMT"
  http.response.body=
  | {"ApplicationId":"97abd44ab1fb403f82e0baff36820399","IsArchived":false,"Version":1,"CreationDate":"2024-07-12T11:06:13.539Z","LastModifiedDate":"2024-07-12T11:06:13.539Z","Id":"gcm","Enabled":false,"HasCredential":true,"Platform":"GCM","HasFcmServiceCredentials":false,"DefaultAuthenticationMethod":"KEY"}
   http.response.header.x_amz_cf_pop=LHR50-P4 http.response.header.x_amzn_requestid=e73cb7db-c971-41e6-9f5f-bdef3a7d9316

# Token
2024-07-12T12:06:13.302+0100 [DEBUG] aws: HTTP Response Received: tf_aws.sdk=aws-sdk-go tf_resource_type=aws_pinpoint_gcm_channel http.response.header.date="Fri, 12 Jul 2024 11:06:13 GMT" http.response.header.x_amz_apigw_id=ay8l3EARvHcEVeg= http.response.header.access_control_allow_origin="*" http.response.header.x_amzn_requestid=b7f3dd6f-332c-43d9-a090-25a83a50c852 http.response.header.content_type=application/json rpc.system=aws-api tf_rpc=ApplyResourceChange http.response_content_length=307
  http.response.body=
  | {"ApplicationId":"809f908bc8a34b13b7d910409b353d54","IsArchived":false,"Version":1,"CreationDate":"2024-07-12T11:06:13.096Z","LastModifiedDate":"2024-07-12T11:06:13.096Z","Id":"gcm","Enabled":false,"HasCredential":false,"Platform":"GCM","HasFcmServiceCredentials":true,"DefaultAuthenticationMethod":"TOKEN"}
   http.duration=163 http.response.header.via="1.1 6dcfe970273dbabb7e3f096812b664f4.cloudfront.net (CloudFront)" tf_req_id=29596390-1240-bcf8-934d-267c6613bc25 rpc.method=GetGcmChannel aws.region=us-west-2 tf_provider_addr=registry.terraform.io/hashicorp/aws tf_mux_provider="*schema.GRPCProviderServer" rpc.service=Pinpoint http.response.header.x_amz_cf_id=xXl6mJBlhpVjWEm7JH_S4ZbndJxlZdhAE-tC61TIw2MutAgTS0z0EQ== http.status_code=200 http.response.header.cache_control=no-store http.response.header.x_amzn_trace_id=Root=1-66910e25-7a08b0166f15a75e5cf89a70 http.response.header.x_cache="Miss from cloudfront" http.response.header.x_amz_cf_pop=LHR50-P4
```

**Comment by gdavison** [comment]
Thanks for running the tests, @TokyoQ, and sorry for the delay in getting back to you.

I've updated the tests to match the results that you got. It should be ready to merge, but it would be great if you could verify that the tests pass

**Comment by TokyoQ** [comment]
No problem @gdavison. This is the run on the latest.

```
λ make testacc TESTS=GCM  PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='GCM'  -timeout 360m
=== RUN   TestAccPinpointGCMChannel_basicAPIKey
=== PAUSE TestAccPinpointGCMChannel_basicAPIKey
=== RUN   TestAccPinpointGCMChannel_apiKeyAuthMethod
=== PAUSE TestAccPinpointGCMChannel_apiKeyAuthMethod
=== RUN   TestAccPinpointGCMChannel_tokenAuthMethod
=== PAUSE TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_basicAPIKey
=== CONT  TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_apiKeyAuthMethod
=== NAME  TestAccPinpointGCMChannel_tokenAuthMethod
    gcm_channel_test.go:115: Step 1/2 error: After applying this test step, the non-refresh plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_pinpoint_gcm_channel.test_gcm_channel will be updated in-place
          ~ resource "aws_pinpoint_gcm_channel" "test_gcm_channel" {
                id                            = "939ca663f3f1456aa56c52c4527d7c7f"
              + service_json                  = (sensitive value)
                # (3 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
=== NAME  TestAccPinpointGCMChannel_apiKeyAuthMethod
    gcm_channel_test.go:78: Step 1/2 error: After applying this test step, the non-refresh plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_pinpoint_gcm_channel.test_gcm_channel will be updated in-place
          ~ resource "aws_pinpoint_gcm_channel" "test_gcm_channel" {
              + api_key                       = (sensitive value)
                id                            = "103cf767ed634fbfa635c06dac86a00b"
                # (3 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
=== NAME  TestAccPinpointGCMChannel_basicAPIKey
    gcm_channel_test.go:41: Step 1/2 error: After applying this test step, the non-refresh plan was not empty.
        stdout:


        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place

        Terraform will perform the following actions:

          # aws_pinpoint_gcm_channel.test_gcm_channel will be updated in-place
          ~ resource "aws_pinpoint_gcm_channel" "test_gcm_channel" {
              + api_key                       = (sensitive value)
                id                            = "94c76c15293143c78da1c3859e90ef8c"
                # (3 unchanged attributes hidden)
            }

        Plan: 0 to add, 1 to change, 0 to destroy.
--- FAIL: TestAccPinpointGCMChannel_tokenAuthMethod (16.09s)
--- FAIL: TestAccPinpointGCMChannel_apiKeyAuthMethod (16.10s)
--- FAIL: TestAccPinpointGCMChannel_basicAPIKey (16.22s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	20.533s
FAIL
make: *** [testacc] Error 1
```

**Comment by gdavison** [comment]
I think this should fix the test errors

**Comment by TokyoQ** [comment]
@gdavison Hitting this now unfortunately
```
λ make testacc TESTS=GCM  PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='GCM'  -timeout 360m
=== RUN   TestAccPinpointGCMChannel_basicAPIKey
=== PAUSE TestAccPinpointGCMChannel_basicAPIKey
=== RUN   TestAccPinpointGCMChannel_apiKeyAuthMethod
=== PAUSE TestAccPinpointGCMChannel_apiKeyAuthMethod
=== RUN   TestAccPinpointGCMChannel_tokenAuthMethod
=== PAUSE TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_basicAPIKey
=== CONT  TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_apiKeyAuthMethod
    gcm_channel_test.go:78: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"api_key": "<redacted>",
          }
=== NAME  TestAccPinpointGCMChannel_basicAPIKey
    gcm_channel_test.go:41: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"api_key": "<redacted>,
          }
=== NAME  TestAccPinpointGCMChannel_tokenAuthMethod
    gcm_channel_test.go:115: Step 2/2 error running import: ImportStateVerify attributes not equivalent. Difference is shown below. The - symbol indicates attributes missing after import.

          map[string]string{
        - 	"service_json": "{ <redacted> },
          }
--- FAIL: TestAccPinpointGCMChannel_basicAPIKey (21.10s)
--- FAIL: TestAccPinpointGCMChannel_apiKeyAuthMethod (21.54s)
--- FAIL: TestAccPinpointGCMChannel_tokenAuthMethod (21.70s)
FAIL
FAIL	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	26.076s
FAIL
make: *** [testacc] Error 1
```

**Comment by TokyoQ** [comment]
I read through this - it seems setting `ImportStateVerifyIgnore` is appropriate since we aren't getting these back in the response?
https://github.com/hashicorp/terraform/issues/20985

I've added a commit anyway and the tests are passing now.
```
λ make testacc TESTS=GCM  PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='GCM'  -timeout 360m
=== RUN   TestAccPinpointGCMChannel_basicAPIKey
=== PAUSE TestAccPinpointGCMChannel_basicAPIKey
=== RUN   TestAccPinpointGCMChannel_apiKeyAuthMethod
=== PAUSE TestAccPinpointGCMChannel_apiKeyAuthMethod
=== RUN   TestAccPinpointGCMChannel_tokenAuthMethod
=== PAUSE TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_basicAPIKey
=== CONT  TestAccPinpointGCMChannel_tokenAuthMethod
=== CONT  TestAccPinpointGCMChannel_apiKeyAuthMethod
--- PASS: TestAccPinpointGCMChannel_tokenAuthMethod (21.20s)
--- PASS: TestAccPinpointGCMChannel_basicAPIKey (21.55s)
--- PASS: TestAccPinpointGCMChannel_apiKeyAuthMethod (22.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	26.563s
```

**Comment by juanmesa-jt** [comment]
Hi everyone. First of all thank you to you all for working on this. I am wondering when are you expecting to merge these changes? Google FCM endpoint shutdown has already started. So, for now we have made the Pinpoint channel changes manually while we wait for the new FCM authentication method to by supported by the provider.

**Review by gdavison — APPROVED** [review]

**Pull request merged**
