### PR TITLE
[WIP] aws_globalaccelerator_custom_routing_accelerator

### PR DESCRIPTION
**Pull request by YvanGuidoin**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #16690

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=globalaccelerator

...
```

TODO:

- [x] Testing
- [ ] Traffic allow/deny
- [ ] Avoid massive duplication for accelerator and accelerator_attributes

Issues:

AllowCustomRoutingTraffic and DenyCustromRoutingTraffic current state reading is not clear to me

### CODE REVIEW

**Comment by NetDevAutomate** [comment]
@YvanGuidoin Great work on this resource! Are you still working on this resource, and if so is there is any support you need, please let me know? I've emailed you privately with some additional detail.

Again, thank you very much for the great work done and really looking forward to seeing this added to the Provider.

**Comment by YvanGuidoin** [comment]
Hi, I was working on another part of our system, but we still need it so I will come back to it soon.

**Comment by AdamTylerLynch** [comment]
@YvanGuidoin please let @NetDevAutomate and myself know if you need any help! We are happy to roll up our sleeves and and write some code if you want!

**Comment by YvanGuidoin** [comment]
@AdamTylerLynch I added a bit more tests, but not idea how to test properly the `aws_globalaccelerator_custom_routing_endpoint_group` as spinning up endpoints automatically seems unclear to me.

Should I put the PR up for review for now and leave it to you guys ?

**Comment by julianxhokaxhiu** [comment]
@AdamTylerLynch can you please have a look at this? We're also in need of using custom routing and it's a shame is not yet available on the provider.

**Comment by julianxhokaxhiu** [comment]
@YvanGuidoin Would you also be able to rebase your fork so this PR has no more conflicts in place when @AdamTylerLynch comes around for a review? Thank you!

**Comment by amontalban** [comment]
Thank you very much for doing this @YvanGuidoin!

We are really interested in seeing this merged ASAP as it is blocking us to have everything codified in Terraform 🙏

**Comment by amontalban** [comment]
@AdamTylerLynch @NetDevAutomate do you think this is good to go? It would be great to have this natively in the provider instead of doing dozens of AWS CLI calls in Terraform.

Thanks!

**Pull request closed without merging**
