### PR TITLE
Added FIS support for EKS Cluster

### LINKED ISSUE #27314: [Bug]: aws_fis_experiment_template should support resource of type EKS Cluster
### Terraform Core Version

1.0.4

### AWS Provider Version

4.35

### Affected Resource(s)

`aws_fis_experiment_template` should allow targets of type EKS cluster for the fis action 'aws:eks:inject-kubernetes-custom-resource`. Currently the resource only supports the types [Clusters DBInstances Instances SpotInstances Nodegroups Roles] and does not support the type "Cluster" for selecting a aws eks resource. 

### Expected Behavior

EKS clusters should be allowed to be targeted in aws fis templates as documented here: https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#inject-kubernetes-custom-resource. This is different than the NodeGroups which targets only node groups of the eks clusters

### Actual Behavior

│ Error: expected action.0.target.0.key to be one of [Clusters DBInstances Instances SpotInstances Nodegroups Roles], got Cluster
│
│   with aws_fis_experiment_template.fis_eks_fault["terminate-pod"],
│   on fis-eks-faults.tf line 1, in resource "aws_fis_experiment_template" "fis_eks_fault":
│    1: resource "aws_fis_experiment_template" "fis_eks_fault" {
│
╵

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

resource "aws_fis_experiment_template" "fis_eks_fault" {
  description = format("Inject %s Fault Into EKS Cluster",var.kubernetes_kind)
  role_arn    = var.fis_role_arn 

  action {
    name      = var.kubernetes_kind
    action_id = "aws:eks:inject-kubernetes-custom-resource"

    target {
      key   = "Cluster" # Errors out
      value = "eksCluster"
    }

    parameter {
      key   = "kubernetesApiVersion"
      value = "chaos-mesh.org/v1alpha1"
    }

    parameter {
      key   = "kubernetesKind"
      value = var.kubernetes_kind
    }

    parameter {
      key   = "kubernetesNamespace"
      value = var.kubernetes_namespace
    }

    parameter {
      key   = "kubernetesSpec"
      value = jsonencode(var.kubernetes_spec)
    }

    parameter {
      key   = "maxDuration"
      value = var.max_duration
    }
  }

  target {
    name           = "eksCluster"
    resource_type  = "aws:eks:cluster"
    selection_mode = "ALL"
    resource_arns  = [var.eks_cluster_arn]
  }
}

### Steps to Reproduce

Try to deploy an fis experiment for an eks cluster. Document:
https://docs.aws.amazon.com/fis/latest/userguide/fis-actions-reference.html#inject-kubernetes-custom-resource

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by akshaychopra5207**
### Description

This is to fix a validation failure for Cluster(EKS Cluster)

### Relations
Closes #27314

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccFISExperimentTemplate_eks  PKG=fis
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fis/... -v -count 1 -parallel 20 -run='TestAccFISExperimentTemplate_eks'  -timeout 180m
=== RUN   TestAccFISExperimentTemplate_eks
=== PAUSE TestAccFISExperimentTemplate_eks
=== CONT  TestAccFISExperimentTemplate_eks
--- PASS: TestAccFISExperimentTemplate_eks (647.24s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/fis        648.932s
...
```

### CODE REVIEW

**Comment by akshaychopra5207** [comment]
Any update on when this can be picked up ? @ewbankkit

**Comment by bcubk** [comment]
Hi @ewbankkit, can you please revise this open PR? This bug still occurs on the latest version. Can you tell me what has to be done? First, of course rebasing 😂

**Comment by bcubk** [comment]
if necesssary, I would take and do the rest of the work

**Comment by akshaychopra5207** [comment]
any news on this one?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccFISExperimentTemplate_' PKG=fis ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/fis/... -v -count 1 -parallel 2  -run=TestAccFISExperimentTemplate_ -timeout 180m
=== RUN   TestAccFISExperimentTemplate_basic
=== PAUSE TestAccFISExperimentTemplate_basic
=== RUN   TestAccFISExperimentTemplate_disappears
=== PAUSE TestAccFISExperimentTemplate_disappears
=== RUN   TestAccFISExperimentTemplate_update
=== PAUSE TestAccFISExperimentTemplate_update
=== RUN   TestAccFISExperimentTemplate_spot
=== PAUSE TestAccFISExperimentTemplate_spot
=== RUN   TestAccFISExperimentTemplate_eks
=== PAUSE TestAccFISExperimentTemplate_eks
=== CONT  TestAccFISExperimentTemplate_basic
=== CONT  TestAccFISExperimentTemplate_spot
--- PASS: TestAccFISExperimentTemplate_spot (16.49s)
=== CONT  TestAccFISExperimentTemplate_update
=== CONT  TestAccFISExperimentTemplate_eks
--- PASS: TestAccFISExperimentTemplate_basic (19.41s)
--- PASS: TestAccFISExperimentTemplate_update (28.43s)
=== CONT  TestAccFISExperimentTemplate_disappears
--- PASS: TestAccFISExperimentTemplate_disappears (14.02s)
--- PASS: TestAccFISExperimentTemplate_eks (752.67s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/fis	777.643s
```

**Comment by ewbankkit** [comment]
@akshaychopra5207 Thanks for the contribution :tada: :clap:.

**Pull request merged**
