### PR TITLE
Add Tiered storage to Amazon MSK

### LINKED ISSUE #27540: [Enhancement]: Support for Amazon MSK Tiered storage
### Description

Amazon MSK now supports tiered storage with S3 backend.
Terraform aws_msk_cluster should provide an option to pass `[--storage-mode <value>]` to the MSK cluster create call.

### Affected Resource(s) and/or Data Source(s)

* aws_msk_cluster

### Potential Terraform Configuration

```terraform
broker_node_group_info {
    instance_type = "kafka.m5.large"
    client_subnets = [
      aws_subnet.subnet_az1.id,
      aws_subnet.subnet_az2.id,
      aws_subnet.subnet_az3.id,
    ]
    storage_info {
      ebs_storage_info {
        volume_size = 1000
      }
      storage_mode = "TIERED"
    }
}
```

### References

https://aws.amazon.com/about-aws/whats-new/2022/10/amazon-msk-offers-low-cost-storage-tier-scales-virtually-unlimited-storage/
https://docs.aws.amazon.com//cli/latest/reference/kafka/create-cluster.html

### Would you like to implement a fix?

_No response_

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

Adds support for tiered storage in Amazon MSK.

### Relations

Closes #27540

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccKafkaCluster_basic\|TestAccKafkaCluster_storageMode PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_basic|TestAccKafkaCluster_storageMode'  -timeout 180m
=== RUN   TestAccKafkaCluster_basic
=== PAUSE TestAccKafkaCluster_basic
=== RUN   TestAccKafkaCluster_storageMode
=== PAUSE TestAccKafkaCluster_storageMode
=== CONT  TestAccKafkaCluster_basic
=== CONT  TestAccKafkaCluster_storageMode
--- PASS: TestAccKafkaCluster_basic (999.97s)
--- PASS: TestAccKafkaCluster_storageMode (1877.88s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kafka      1879.662s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Running acceptance tests... takes a while...

**Comment by bschaatsbergen** [comment]
Need to run tests... high likely doing that tomorrow.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccKafkaCluster_basic\|TestAccKafkaCluster_storageMode PKG=kafka
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kafka/... -v -count 1 -parallel 20 -run='TestAccKafkaCluster_basic|TestAccKafkaCluster_storageMode'  -timeout 180m
=== RUN   TestAccKafkaCluster_basic
=== PAUSE TestAccKafkaCluster_basic
=== RUN   TestAccKafkaCluster_storageMode
=== PAUSE TestAccKafkaCluster_storageMode
=== CONT  TestAccKafkaCluster_basic
=== CONT  TestAccKafkaCluster_storageMode
--- PASS: TestAccKafkaCluster_basic (1781.56s)
--- PASS: TestAccKafkaCluster_storageMode (2716.12s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kafka	2721.649s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Comment by trevorpburke** [comment]
@ewbankkit do you know roughly when v4.40.0 might be added to the TF registry? looks like [aws is still on v4.39.0](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/msk_cluster)

**Comment by bschaatsbergen** [comment]
We aim to release every week @trevorpburke around Thursday.

**Pull request merged**
