### PR TITLE
r/aws_lambda_function: Added Lambda function name validation

### LINKED ISSUE #25090: Validate Lambda Function Name
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be helpful to check `aws_lambda_function.function_name` against the AWS constraints.

> Use only letters, numbers, hyphens, or underscores with no spaces.

The API docs (linked below) also state that this should be no longer than 64 characters.

### New or Affected Resource(s)

* `aws_lambda_function`

### Potential Terraform Configuration

This should be accepted:

```hcl
resource "aws_lambda_function" "viewer_request_lambda" {
  function_name = "viewer_request_lambda"
}
```

Whereas this should be rejected:

```hcl
resource "aws_lambda_function" "viewer_request_lambda" {
  function_name = "prefix.viewer_request_lambda"
}
```

### References

* <https://docs.aws.amazon.com/lambda/latest/dg/API_CreateFunction.html#API_CreateFunction_RequestSyntax>

### PR DESCRIPTION
**Pull request by daftkid**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #25090

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @daftkid 👋 Thank you very much for your contribution! Can you add a [changelog entry](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process) as well?

**Comment by daftkid** [comment]
> Hey @daftkid 👋 Thank you very much for your contribution! Can you add a [changelog entry](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/pullrequest-submission-and-lifecycle.md#changelog-process) as well?

Hi @justinretzolk Done!

**Comment by daftkid** [comment]
> Hi @daftkid Is it expected to be merged to main soon?

Hi @nimroda I did all the required code changes, however, I'm not a maintainer of the repo so I cannot merge it by myself.

@justinretzolk any plans on moving it into the main?

**Comment by johnsonaj** [comment]
LGTM 🚀 

```console
$ make testacc TESTS=TestAccLambdaFunction_ PKG=lambda
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lambda/... -v -count 1 -parallel 20 -run='TestAccLambdaFunction_'  -timeout 180m
=== RUN   TestAccLambdaFunction_basic
=== PAUSE TestAccLambdaFunction_basic
=== RUN   TestAccLambdaFunction_unpublishedCodeUpdate
=== PAUSE TestAccLambdaFunction_unpublishedCodeUpdate
=== RUN   TestAccLambdaFunction_disappears
=== PAUSE TestAccLambdaFunction_disappears
=== RUN   TestAccLambdaFunction_codeSigning
=== PAUSE TestAccLambdaFunction_codeSigning
=== RUN   TestAccLambdaFunction_concurrency
=== PAUSE TestAccLambdaFunction_concurrency
=== RUN   TestAccLambdaFunction_concurrencyCycle
=== PAUSE TestAccLambdaFunction_concurrencyCycle
=== RUN   TestAccLambdaFunction_expectFilenameAndS3Attributes
=== PAUSE TestAccLambdaFunction_expectFilenameAndS3Attributes
=== RUN   TestAccLambdaFunction_envVariables
=== PAUSE TestAccLambdaFunction_envVariables
=== RUN   TestAccLambdaFunction_EnvironmentVariables_noValue
=== PAUSE TestAccLambdaFunction_EnvironmentVariables_noValue
=== RUN   TestAccLambdaFunction_encryptedEnvVariables
=== PAUSE TestAccLambdaFunction_encryptedEnvVariables
=== RUN   TestAccLambdaFunction_nameValidation
=== PAUSE TestAccLambdaFunction_nameValidation
=== RUN   TestAccLambdaFunction_versioned
=== PAUSE TestAccLambdaFunction_versioned
=== RUN   TestAccLambdaFunction_versionedUpdate
=== PAUSE TestAccLambdaFunction_versionedUpdate
=== RUN   TestAccLambdaFunction_enablePublish
=== PAUSE TestAccLambdaFunction_enablePublish
=== RUN   TestAccLambdaFunction_disablePublish
=== PAUSE TestAccLambdaFunction_disablePublish
=== RUN   TestAccLambdaFunction_deadLetter
=== PAUSE TestAccLambdaFunction_deadLetter
=== RUN   TestAccLambdaFunction_deadLetterUpdated
=== PAUSE TestAccLambdaFunction_deadLetterUpdated
=== RUN   TestAccLambdaFunction_nilDeadLetter
=== PAUSE TestAccLambdaFunction_nilDeadLetter
=== RUN   TestAccLambdaFunction_fileSystem
=== PAUSE TestAccLambdaFunction_fileSystem
=== RUN   TestAccLambdaFunction_image
=== PAUSE TestAccLambdaFunction_image
=== RUN   TestAccLambdaFunction_architectures
=== PAUSE TestAccLambdaFunction_architectures
=== RUN   TestAccLambdaFunction_architecturesUpdate
=== PAUSE TestAccLambdaFunction_architecturesUpdate
=== RUN   TestAccLambdaFunction_architecturesWithLayer
=== PAUSE TestAccLambdaFunction_architecturesWithLayer
=== RUN   TestAccLambdaFunction_ephemeralStorage
=== PAUSE TestAccLambdaFunction_ephemeralStorage
=== RUN   TestAccLambdaFunction_tracing
=== PAUSE TestAccLambdaFunction_tracing
=== RUN   TestAccLambdaFunction_KMSKeyARN_noEnvironmentVariables
=== PAUSE TestAccLambdaFunction_KMSKeyARN_noEnvironmentVariables
=== RUN   TestAccLambdaFunction_layers
=== PAUSE TestAccLambdaFunction_layers
=== RUN   TestAccLambdaFunction_layersUpdate
=== PAUSE TestAccLambdaFunction_layersUpdate
=== RUN   TestAccLambdaFunction_vpc
=== PAUSE TestAccLambdaFunction_vpc
=== RUN   TestAccLambdaFunction_vpcRemoval
=== PAUSE TestAccLambdaFunction_vpcRemoval
=== RUN   TestAccLambdaFunction_vpcUpdate
=== PAUSE TestAccLambdaFunction_vpcUpdate
=== RUN   TestAccLambdaFunction_VPC_withInvocation
=== PAUSE TestAccLambdaFunction_VPC_withInvocation
=== RUN   TestAccLambdaFunction_VPCPublishNo_changes
=== PAUSE TestAccLambdaFunction_VPCPublishNo_changes
=== RUN   TestAccLambdaFunction_VPCPublishHas_changes
=== PAUSE TestAccLambdaFunction_VPCPublishHas_changes
=== RUN   TestAccLambdaFunction_VPC_properIAMDependencies
=== PAUSE TestAccLambdaFunction_VPC_properIAMDependencies
=== RUN   TestAccLambdaFunction_emptyVPC
=== PAUSE TestAccLambdaFunction_emptyVPC
=== RUN   TestAccLambdaFunction_s3
=== PAUSE TestAccLambdaFunction_s3
=== RUN   TestAccLambdaFunction_localUpdate
=== PAUSE TestAccLambdaFunction_localUpdate
=== RUN   TestAccLambdaFunction_LocalUpdate_nameOnly
=== PAUSE TestAccLambdaFunction_LocalUpdate_nameOnly
=== RUN   TestAccLambdaFunction_S3Update_basic
=== PAUSE TestAccLambdaFunction_S3Update_basic
=== RUN   TestAccLambdaFunction_S3Update_unversioned
=== PAUSE TestAccLambdaFunction_S3Update_unversioned
=== RUN   TestAccLambdaFunction_tags
=== PAUSE TestAccLambdaFunction_tags
=== RUN   TestAccLambdaFunction_runtimes
=== PAUSE TestAccLambdaFunction_runtimes
=== RUN   TestAccLambdaFunction_Zip_validation
=== PAUSE TestAccLambdaFunction_Zip_validation
=== CONT  TestAccLambdaFunction_basic
=== CONT  TestAccLambdaFunction_versioned
=== CONT  TestAccLambdaFunction_vpcUpdate
=== CONT  TestAccLambdaFunction_layers
=== CONT  TestAccLambdaFunction_expectFilenameAndS3Attributes
=== CONT  TestAccLambdaFunction_nilDeadLetter
=== CONT  TestAccLambdaFunction_architecturesWithLayer
=== CONT  TestAccLambdaFunction_Zip_validation
=== CONT  TestAccLambdaFunction_runtimes
=== CONT  TestAccLambdaFunction_tags
=== CONT  TestAccLambdaFunction_S3Update_unversioned
=== CONT  TestAccLambdaFunction_S3Update_basic
=== CONT  TestAccLambdaFunction_LocalUpdate_nameOnly
=== CONT  TestAccLambdaFunction_localUpdate
=== CONT  TestAccLambdaFunction_s3
=== CONT  TestAccLambdaFunction_emptyVPC
=== CONT  TestAccLambdaFunction_VPC_properIAMDependencies
=== CONT  TestAccLambdaFunction_VPCPublishHas_changes
=== CONT  TestAccLambdaFunction_VPCPublishNo_changes
=== CONT  TestAccLambdaFunction_VPC_withInvocation
--- PASS: TestAccLambdaFunction_Zip_validation (7.76s)
=== CONT  TestAccLambdaFunction_codeSigning
--- PASS: TestAccLambdaFunction_expectFilenameAndS3Attributes (20.10s)
=== CONT  TestAccLambdaFunction_concurrencyCycle
--- PASS: TestAccLambdaFunction_s3 (37.98s)
=== CONT  TestAccLambdaFunction_concurrency
--- PASS: TestAccLambdaFunction_nilDeadLetter (54.12s)
=== CONT  TestAccLambdaFunction_disappears
--- PASS: TestAccLambdaFunction_S3Update_unversioned (57.15s)
=== CONT  TestAccLambdaFunction_disablePublish
--- PASS: TestAccLambdaFunction_basic (57.57s)
=== CONT  TestAccLambdaFunction_deadLetterUpdated
--- PASS: TestAccLambdaFunction_versioned (62.49s)
=== CONT  TestAccLambdaFunction_deadLetter
--- PASS: TestAccLambdaFunction_emptyVPC (69.46s)
=== CONT  TestAccLambdaFunction_encryptedEnvVariables
--- PASS: TestAccLambdaFunction_S3Update_basic (72.32s)
=== CONT  TestAccLambdaFunction_nameValidation
--- PASS: TestAccLambdaFunction_nameValidation (0.59s)
=== CONT  TestAccLambdaFunction_enablePublish
--- PASS: TestAccLambdaFunction_tags (107.48s)
=== CONT  TestAccLambdaFunction_tracing
--- PASS: TestAccLambdaFunction_codeSigning (100.78s)
=== CONT  TestAccLambdaFunction_KMSKeyARN_noEnvironmentVariables
--- PASS: TestAccLambdaFunction_runtimes (316.02s)
=== CONT  TestAccLambdaFunction_unpublishedCodeUpdate
--- PASS: TestAccLambdaFunction_VPCPublishNo_changes (491.42s)
=== CONT  TestAccLambdaFunction_versionedUpdate
--- PASS: TestAccLambdaFunction_VPC_withInvocation (501.66s)
=== CONT  TestAccLambdaFunction_EnvironmentVariables_noValue
--- PASS: TestAccLambdaFunction_layers (1060.22s)
=== CONT  TestAccLambdaFunction_architectures
--- PASS: TestAccLambdaFunction_VPC_properIAMDependencies (1069.44s)
=== CONT  TestAccLambdaFunction_architecturesUpdate
--- PASS: TestAccLambdaFunction_localUpdate (1073.30s)
=== CONT  TestAccLambdaFunction_envVariables
--- PASS: TestAccLambdaFunction_LocalUpdate_nameOnly (1079.16s)
=== CONT  TestAccLambdaFunction_image
    function_test.go:979: AWS_LAMBDA_IMAGE_LATEST_ID, AWS_LAMBDA_IMAGE_V1_ID and AWS_LAMBDA_IMAGE_V2_ID env vars must be set for Lambda Container Image Support acceptance tests.
--- SKIP: TestAccLambdaFunction_image (0.00s)
=== CONT  TestAccLambdaFunction_vpc
--- PASS: TestAccLambdaFunction_concurrency (1046.06s)
=== CONT  TestAccLambdaFunction_vpcRemoval
=== CONT  TestAccLambdaFunction_ephemeralStorage
--- PASS: TestAccLambdaFunction_VPCPublishHas_changes (1084.66s)
--- PASS: TestAccLambdaFunction_disappears (1033.31s)
=== CONT  TestAccLambdaFunction_fileSystem
--- PASS: TestAccLambdaFunction_concurrencyCycle (1070.15s)
=== CONT  TestAccLambdaFunction_layersUpdate
--- PASS: TestAccLambdaFunction_disablePublish (1050.19s)
--- PASS: TestAccLambdaFunction_deadLetterUpdated (1061.39s)
--- PASS: TestAccLambdaFunction_deadLetter (1060.97s)
--- PASS: TestAccLambdaFunction_architecturesWithLayer (1124.90s)
--- PASS: TestAccLambdaFunction_enablePublish (1060.95s)
--- PASS: TestAccLambdaFunction_encryptedEnvVariables (1065.02s)
--- PASS: TestAccLambdaFunction_KMSKeyARN_noEnvironmentVariables (1030.10s)
--- PASS: TestAccLambdaFunction_tracing (1042.10s)
--- PASS: TestAccLambdaFunction_EnvironmentVariables_noValue (654.35s)
--- PASS: TestAccLambdaFunction_architectures (111.64s)
--- PASS: TestAccLambdaFunction_envVariables (151.11s)
--- PASS: TestAccLambdaFunction_ephemeralStorage (302.50s)
--- PASS: TestAccLambdaFunction_vpc (488.99s)
--- PASS: TestAccLambdaFunction_unpublishedCodeUpdate (1259.90s)
--- PASS: TestAccLambdaFunction_architecturesUpdate (516.10s)
--- PASS: TestAccLambdaFunction_layersUpdate (502.78s)
--- PASS: TestAccLambdaFunction_versionedUpdate (1108.47s)
--- PASS: TestAccLambdaFunction_vpcRemoval (518.68s)
--- PASS: TestAccLambdaFunction_fileSystem (1049.75s)
--- PASS: TestAccLambdaFunction_vpcUpdate (2217.42s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lambda	2220.056s
```

**Review by johnsonaj — APPROVED** [review]

**Comment by johnsonaj** [comment]
@daftkid thanks for the contribution! 🎉 👏🏾

**Pull request merged**
