### PR TITLE
r/aws_medialive_channel: fix flatten/expand/docs vpc settings for a channel.

### LINKED ISSUE #33554: [Docs]: Medialive channel vpc attribute
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/medialive_channel?q=aws_medialive_output_destination#vpc

### Description

vpc field is missing associated fields, the link directs you nowhere.

github shows multiple fields https://github.com/hashicorp/terraform-provider-aws/blob/57f32fbb187dc8da7e495be24c03953fd014461d/internal/service/medialive/channel.go#L690-L721

### References

_No response_

### Would you like to implement a fix?

None

### LINKED ISSUE #33556: [Bug]: AWS Elemental MediaLive Channel creation missing required field CreateChannelInput.Vpc.SubnetIds
### Terraform Core Version

1.5.7

### AWS Provider Version

5.17.0

### Affected Resource(s)

- aws_medialive_channel

### Expected Behavior

Upon creation, a `aws_medialive_channel` with a `vpc` block, including a valid `subnet_ids` attribute, should successfully send that configuration to AWS. 

### Actual Behavior

`aws_medialive_channel.vpc.subnet_ids` does not get passed to AWS Elemental MediaLive during apply.

### Relevant Error/Panic Output Snippet

```shell
Error: creating AWS Elemental MediaLive Channel (medialive-channel-name): operation error MediaLive: CreateChannel, 1 validation error(s) found.
│ - missing required field, CreateChannelInput.Vpc.SubnetIds.
│ 
│ 
│   with aws_medialive_channel.medialive_channel,
│   on main.tf line 58, in resource "aws_medialive_channel" "medialive_channel":
│   58: resource "aws_medialive_channel" "medialive_channel" {
```

### Terraform Configuration Files

```terraform
terraform {
  required_version = "~>1.5.7"
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = ">= 5.17.0"
    }
}

provider "aws" {}

resource "aws_medialive_channel" "medialive_channel" {
  name          = "medialive-channel-name"
  channel_class = "SINGLE_PIPELINE"
  role_arn      = "arn:aws:iam::xxx:role/xxx" // Provides access to VPC
  vpc {
    public_address_allocation_ids = [] // Not required to have an item
    security_group_ids            = ["sg-xxx"] // Valid security group ID redacted
    subnet_ids                    = ["subnet-xxx"] // Valid subnet ID redacted
  }
  // [Other required fields ...]
}
```

### Steps to Reproduce

**Creation (doesn't work)**

1. Create a MediaLive channel using Terraform with a valid VPC block including subnet IDs
2. Perform a plan (is successful)
3. Perform an apply (raises an error from validation from AWS, not Terraform schema)

**Updating a managed resource (works)**
1. Use the same exact Terraform configuration as during creation
2. Create a MediaLive channel in the AWS console with the same fields
  - At least the fields that could force a replacement should match the Terraform (name, channel_class, VPC block)
3. Import the created resource into Terraform
4. Run a plan and apply (both are successful)

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by gbw**
### Description
Changes the VPC config settings to use sets instead of lists where appropriate and updates to use flatten/expand functions.

### Relations
Closes #33556, closes #33554

### Output from Acceptance Testing
I lack permissions to test this.

### CODE REVIEW

**Comment by evelynhathaway** [comment]
I cloned and used this as my local provider. I've confirmed to fix my reported issue #33556! Thanks @gbw

**Comment by evelynhathaway** [comment]
Thanks for adding documentation! This also now fixes #33554

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTARGS='-run=TestAccMediaLiveChannel_' PKG=medialive

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/medialive/... -v -count 1 -parallel 20  -run=TestAccMediaLiveChannel_ -timeout 360m
--- PASS: TestAccMediaLiveChannel_M2TS_settings (89.68s)
--- PASS: TestAccMediaLiveChannel_disappears (97.54s)
--- PASS: TestAccMediaLiveChannel_basic (101.38s)
--- PASS: TestAccMediaLiveChannel_updateTags (126.62s)
--- PASS: TestAccMediaLiveChannel_MsSmooth_outputSettings (156.98s)
--- PASS: TestAccMediaLiveChannel_AudioDescriptions_codecSettings (169.75s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h265Settings (170.94s)
--- PASS: TestAccMediaLiveChannel_status (189.85s)
--- PASS: TestAccMediaLiveChannel_update (202.73s)
--- PASS: TestAccMediaLiveChannel_hls (219.73s)
--- PASS: TestAccMediaLiveChannel_VideoDescriptions_CodecSettings_h264Settings (243.53s)
--- PASS: TestAccMediaLiveChannel_captionDescriptions (243.71s)
--- PASS: TestAccMediaLiveChannel_UDP_outputSettings (264.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/medialive	267.509s
```

**Comment by johnsonaj** [comment]
@gbw thank you for the contribution! 🎉

**Pull request merged**
