### PR TITLE
resource/aws_api_gateway_rest_api: suppressed plan diffs for policy

### LINKED ISSUE #5549: Terraform constantly updates resource policy on API Gateway
We're seeing an issue where Terraform constantly updates the resource policy of an API gateway:
```
module.apps.aws_api_gateway_rest_api.segmentation-etl-creation-api: Modifying... (ID: x023a0eez5)
  policy: "{\"Version\":\"2012-10-17\",\"Statement\":[{\"Sid\":\"\",\"Effect\":\"Allow\",\"Principal\":\"*\",\"Action\":\"execute-api:Invoke\",\"Resource\":\"arn:aws:execute-api:us-west-1:999999999999:0123456789a/*\",\"Condition\":{\"StringEquals\":{\"aws:SourceVpc\":\"vpc-bcdef123\"}}}]}" => "{\n  \"Version\": \"2012-10-17\",\n  \"Statement\": [\n    {\n      \"Sid\": \"\",\n      \"Effect\": \"Allow\",\n      \"Action\": \"execute-api:Invoke\",\n      \"Resource\": \"execute-api:/*\",\n      \"Principal\": \"*\",\n      \"Condition\": {\n        \"StringEquals\": {\n          \"aws:SourceVpc\": \"vpc-bcdef123\"\n        }\n      }\n    }\n  ]\n}"
```

In our terraform module we want to apply a resource policy our API gateway, so we have the following:
```hcl
data "aws_iam_policy_document" "resource-policy" {
  statement {
    principals {
      type        = "*"
      identifiers = ["*"]
    }
    actions = [
      "execute-api:Invoke",
    ]
    resources = [
      "execute-api:/*",
    ]
    condition {
      test     = "StringEquals"
      variable = "aws:SourceVpc"
      values   = ["${var.vpc_id}"]
    }
  }
}
resource "aws_api_gateway_rest_api" "rest-api" {
  name        = "rest-api"
  description = "API to manage things"
  endpoint_configuration {
    types = ["PRIVATE"]
  }
  policy = "${data.aws_iam_policy_document.resource-policy.json}"
}
```

According to the [Amazon docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html) we can use this `execute-api:/stage/method/part` short hand and AWS will expand this to the full ARN of the `aws_api_gateway_rest_api` instance.

Ideally we'd like to be able to change the `resources` part of the resource policy to reference the ARN of the `aws_api_gateway_rest_api` instance directly, like so:
```hcl
    resources = [
      "${aws_api_gateway_rest_api.rest-api.execution_arn}:/*",
    ]
```
except that this introduces a cycle between the resource policy and the REST API as both require each other to exist before they can be created:
```
Error: Cycle: module.apps.data.aws_iam_policy_document.resource-policy, module.apps.aws_api_gateway_rest_api.rest-api
```

This appears to be due to the unfortunate way that resource policies are stored in AWS. Reading the [docs](https://docs.aws.amazon.com/apigateway/latest/developerguide/apigateway-resource-policies-create-attach.html) it looks like resource policies don't exist as entities themselves but only as things that hang off a REST API.

At the moment we're working around this by ignoring policy changes - it'd be great if there were a nicer way to do this.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform version `0.11.7`
* AWS provider version `1.31.0`

### Affected Resource(s)

* aws_api_gateway_rest_api

### PR DESCRIPTION
**Pull request by sergei-ivanov**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #5549
Relates #10706

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Suppress spurious plan changes for `policy` attribute of `aws_api_gateway_rest_api`
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSAPIGatewayRestApi_*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSAPIGatewayRestApi_* -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSAPIGatewayRestApi_basic
=== PAUSE TestAccAWSAPIGatewayRestApi_basic
=== RUN   TestAccAWSAPIGatewayRestApi_tags
=== PAUSE TestAccAWSAPIGatewayRestApi_tags
=== RUN   TestAccAWSAPIGatewayRestApi_disappears
=== PAUSE TestAccAWSAPIGatewayRestApi_disappears
=== RUN   TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== PAUSE TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== RUN   TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== PAUSE TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== RUN   TestAccAWSAPIGatewayRestApi_api_key_source
=== PAUSE TestAccAWSAPIGatewayRestApi_api_key_source
=== RUN   TestAccAWSAPIGatewayRestApi_policy
=== PAUSE TestAccAWSAPIGatewayRestApi_policy
=== RUN   TestAccAWSAPIGatewayRestApi_openapi
=== PAUSE TestAccAWSAPIGatewayRestApi_openapi
=== CONT  TestAccAWSAPIGatewayRestApi_basic
=== CONT  TestAccAWSAPIGatewayRestApi_api_key_source
=== CONT  TestAccAWSAPIGatewayRestApi_tags
=== CONT  TestAccAWSAPIGatewayRestApi_disappears
=== CONT  TestAccAWSAPIGatewayRestApi_openapi
=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration
=== CONT  TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private
=== CONT  TestAccAWSAPIGatewayRestApi_policy
--- PASS: TestAccAWSAPIGatewayRestApi_disappears (27.07s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration_Private (78.84s)
--- PASS: TestAccAWSAPIGatewayRestApi_EndpointConfiguration (114.13s)
--- PASS: TestAccAWSAPIGatewayRestApi_policy (143.60s)
--- PASS: TestAccAWSAPIGatewayRestApi_basic (199.59s)
--- PASS: TestAccAWSAPIGatewayRestApi_tags (221.69s)
--- PASS: TestAccAWSAPIGatewayRestApi_api_key_source (244.16s)
--- PASS: TestAccAWSAPIGatewayRestApi_openapi (298.21s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	298.263s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.015s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.005s [no tests to run]
```

### CODE REVIEW

**Comment by sergei-ivanov** [comment]
Can anyone from the team please review?
This PR supersedes #10706 as a backwards-compatible implementation based on diff suppression.

**Comment by sergei-ivanov** [comment]
Anyone to review please?

**Comment by sergei-ivanov** [comment]
Hi @bflad , sorry for tagging you directly. Can you please take a look at this change, because I keep rebasing it and nobody picks it up. Here I have reimplemented #10706 as a result of our earlier discussion. I hope it is better this way, because it does not introduce any breaking changes.

**Comment by Constantin07** [comment]
Any ETA when this PR can be reviewed by maintainers ? I need this feature in my project.

**Comment by walkafwalka** [comment]
Looking forward to having this reviewed and implemented. Thanks @sergei-ivanov.

**Comment by shederman** [comment]
Any ETA on this PR? Yet another "Terraform broken for non-toy API Gateway usage" bug. Getting the very strong feeling that we shouldn't be using Terraform for API Gateway.

**Comment by sergei-ivanov** [comment]
Rebased on the latest upstream master and resolved the conflicts.

**Comment by DrFaust92** [comment]
Hey @sergei-ivanov, thanks for the contribution. resource policies seem to be a pain point in several other resources as well. to give better control and prevent issues such as you are proposing to solve in this PR the maintainer team introduced some guidelines for resource access policy: https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/contributing/contribution-checklists.md#adding-resource-policy-support.

best solution here would be to implement this policy as separate resource as proposed at #5834 and deprecated this field eventually. 
would you like to take a look? let me know ill address this otherwise in the in the following few days.

**Comment by bflad** [comment]
Hi @sergei-ivanov 👋  Thank you for submitting this. As mentioned above, we are now preferring that Terraform AWS Provider handling of resource policies be done via separate `_policy` resources, which allows direct interpolation of the resource ARN values into the policy. Given that #13619 implements the new `aws_api_gateway_rest_api_policy` resource, I'm going to close this pull request. Thanks again for the contribution though.

**Pull request closed without merging**
