### PR TITLE
Don't destroy instance on user_data

### PR DESCRIPTION
**Pull request by rogerhu**
This PR is a rebase from https://github.com/hashicorp/terraform-provider-aws/pull/7863 with an acceptance test.

### CODE REVIEW

**Comment by rogerhu** [comment]
Friendly ping on this one =)

**Comment by rogerhu** [comment]
Can someone take a look?

**Comment by VLZZZ** [comment]
Looking forward to be reviewed

**Comment by rogerhu** [comment]
Issuing a new PR off the master branch: https://github.com/hashicorp/terraform-provider-aws/pull/18043

**Pull request closed without merging**
