### PR TITLE
aws BYODKIM support 

### LINKED ISSUE #23312: Add BYODKIM support into the aws_ses_domain_dkim
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We'd like to set BYODKIM for thousands of our SES domains.

### New or Affected Resource(s)

* aws_ses_domain_dkim

### Potential Terraform Configuration

```hcl
resource "aws_ses_domain_dkim" "example" {
  domain = aws_ses_domain_identity.example.domain

  private_key = path|key
  selector = "my_selector"
}
```

### References

* https://docs.aws.amazon.com/ses/latest/dg/send-email-authentication-dkim-bring-your-own.html
* https://docs.aws.amazon.com/sdk-for-go/api/service/sesv2/#PutEmailIdentityDkimSigningAttributesInput

### PR DESCRIPTION
**Pull request by ornokrean**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23312

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Review by kayrus — COMMENTED** [review]
Why didn't you embed this feature into the existing `aws_ses_domain_dkim` resource? I don't see a reason to create a dedicated resource for BYODKIM.

**Comment by ornokrean** [comment]
Initially I did, had a conflict with the Easy DKIM flow (requests were denied no matter which configuration was sent), so David and I thought it is better this way.

**Comment by kayrus** [comment]
> requests were denied no matter which configuration was sent

can you provide more details on this? error messages, etc.

**Comment by ewbankkit** [comment]
Superseded by https://github.com/hashicorp/terraform-provider-aws/pull/27260.
@ornokrean Thanks for the contribution :tada: :clap:.

**Pull request closed without merging**
