### PR TITLE
r/d/aws_connect_lambda_function_association - add new resource and data source

### LINKED ISSUE #21047: Add new resource/data_source for aws_connect_lambda_association
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* aws_connect_lambda_function_association
* data/aws_connect_lambda_function_association

### Potential Terraform Configuration

```hcl
resource "aws_connect_lambda_function_association" "test" {
  instance_id = "97afc98d-101a-ba98-ab97-ae114fc115ec"
  function_arn = "arn:aws:lambda:us-east-1:123456789012:function:my-function:1"
}
```
Data Resource

By function_arn
```
data "aws_connect_lambda_function_association" "test" {
  instance_id = "97afc98d-101a-ba98-ab97-ae114fc115ec"
  function_arn = "arn:aws:lambda:us-east-1:123456789012:function:my-function:1"
}
```

### References

* https://docs.aws.amazon.com/connect/latest/APIReference/API_AssociateLambdaFunction.html
* https://docs.aws.amazon.com/connect/latest/APIReference/API_DisassociateLambdaFunction.html

### PR DESCRIPTION
**Pull request by AdamTylerLynch**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21047

Release note for [CHANGELOG](CHANGELOG.md):
```
resource_aws_connect_lambda_function_association - add new resource
datasource_aws_connect_lambda_function_association - add new datasource
````

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAwsConnectLambdaFunctionAssociation' ACCTEST PARALLELISM=2 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsConnectLambdaFunctionAssociation -timeout 180m
=== RUN   TestAccAwsConnectLambdaFunctionAssociationDataSource_basic
--- PASS: TestAccAwsConnectLambdaFunctionAssociationDataSource_basic (127.83s)
=== RUN   TestAccAwsConnectLambdaFunctionAssociation_serial
=== RUN   TestAccAwsConnectLambdaFunctionAssociation_serial/disappears
=== PAUSE TestAccAwsConnectLambdaFunctionAssociation_serial/disappears
=== RUN   TestAccAwsConnectLambdaFunctionAssociation_serial/basic
=== PAUSE TestAccAwsConnectLambdaFunctionAssociation_serial/basic
=== CONT  TestAccAwsConnectLambdaFunctionAssociation_serial/disappears
=== CONT  TestAccAwsConnectLambdaFunctionAssociation_serial/basic
--- PASS: TestAccAwsConnectLambdaFunctionAssociation_serial (0.00s)
    --- PASS: TestAccAwsConnectLambdaFunctionAssociation_serial/disappears (82.48s)
    --- PASS: TestAccAwsConnectLambdaFunctionAssociation_serial/basic (85.34s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	214.980s
make: *** No rule to make target `ACCTEST'.  Stop.

...
```

### CODE REVIEW

**Comment by AdamTylerLynch** [comment]
Depends on: #21097

**Comment by AdamTylerLynch** [comment]
make testacc TESTARGS='-run=TestAccLambdaFunctionAssociation' PKG_NAME=internal/service/connect ACCTEST PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 20 -run=TestAccLambdaFunctionAssociation -timeout 180m
=== RUN   TestAccLambdaFunctionAssociationDataSource_basic
--- PASS: TestAccLambdaFunctionAssociationDataSource_basic (84.89s)
=== RUN   TestAccLambdaFunctionAssociation_serial
=== RUN   TestAccLambdaFunctionAssociation_serial/disappears
=== PAUSE TestAccLambdaFunctionAssociation_serial/disappears
=== RUN   TestAccLambdaFunctionAssociation_serial/basic
=== PAUSE TestAccLambdaFunctionAssociation_serial/basic
=== CONT  TestAccLambdaFunctionAssociation_serial/disappears
=== CONT  TestAccLambdaFunctionAssociation_serial/basic
--- PASS: TestAccLambdaFunctionAssociation_serial (0.00s)
    --- PASS: TestAccLambdaFunctionAssociation_serial/disappears (81.49s)
    --- PASS: TestAccLambdaFunctionAssociation_serial/basic (87.48s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	173.975s

**Comment by AdamTylerLynch** [comment]
Review Requested.

**Comment by AdamTylerLynch** [comment]
LGTM 🚀

**Comment by anGie44** [comment]
Output of acceptance tests (commercial):
```
--- PASS: TestAccConnectLambdaFunctionAssociationDataSource_basic (109.55s)
--- PASS: TestAccConnectLambdaFunctionAssociation_serial (195.21s)
    --- PASS: TestAccConnectLambdaFunctionAssociation_serial/basic (99.61s)
    --- PASS: TestAccConnectLambdaFunctionAssociation_serial/disappears (95.59s)
```

Output of acceptance tests (govcloud):
```
--- PASS: TestAccConnectLambdaFunctionAssociationDataSource_basic (74.91s)
--- PASS: TestAccConnectLambdaFunctionAssociation_serial (169.10s)
    --- PASS: TestAccConnectLambdaFunctionAssociation_serial/basic (85.31s)
    --- PASS: TestAccConnectLambdaFunctionAssociation_serial/disappears (83.80s)
```

**Review by anGie44 — APPROVED** [review]
Thanks again @AdamTylerLynch 🚀 🚀

**Pull request merged**
