### PR TITLE
Allow local and remote IPv4 and IPv6 CIDRs to be of any size

### LINKED ISSUE #16879: aws_vpn_connection raises errors with local_ipv4_network_cidr and remote_ipv4_network_cidr network values less than 32 bits
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```shell
❯ terraform -v
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.22.0
```

### Affected Resource(s)

* aws_vpn_connection

### Terraform Configuration Files

```hcl
variable "profile" {
  type    = string
  default = "default"
}

variable "region" {
  type    = string
  default = "us-east-1"
}

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "3.22.0"
    }
  }
}

provider "aws" {
  profile = var.profile
  region  = var.region
}

resource "aws_vpc" "vpc" {
  cidr_block = "10.0.0.0/16"
}

resource "aws_vpn_gateway" "vpn_gateway" {
  vpc_id = aws_vpc.vpc.id
}

resource "aws_customer_gateway" "customer_gateway" {
  bgp_asn    = 65000
  ip_address = "172.0.0.1"
  type       = "ipsec.1"
}

resource "aws_vpn_connection" "main" {
  vpn_gateway_id           = aws_vpn_gateway.vpn_gateway.id
  customer_gateway_id      = aws_customer_gateway.customer_gateway.id
  type                     = "ipsec.1"
  static_routes_only       = true
  local_ipv4_network_cidr  = "192.168.0.0/24"
  remote_ipv4_network_cidr = "10.0.0.0/16"
}
```

### Expected Behavior

The above configuration file should be valid.

### Actual Behavior

```shell
❯ terraform validate

Error: expected "local_ipv4_network_cidr" to contain a network Value with between 32 and 32 significant bits, got: 24

  on test.tf line 45, in resource "aws_vpn_connection" "main":
  45:   local_ipv4_network_cidr  = "192.168.0.0/24"



Error: expected "remote_ipv4_network_cidr" to contain a network Value with between 32 and 32 significant bits, got: 16

  on test.tf line 46, in resource "aws_vpn_connection" "main":
  46:   remote_ipv4_network_cidr = "10.0.0.0/16"
```

### Steps to Reproduce

1. `terraform init`
2. `terraform validate`

### References

* Per the aws provider resource documentation, both [local_ipv4_network_cidr](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection#local_ipv4_network_cidr) and [remote_ipv4_network_cidr](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/vpn_connection#remote_ipv4_network_cidr) should default to `0.0.0.0/0` (0 is less than 32 bits).
* These parameters are configureable through both the AWS console and the [CLI (LocalIpv4NetworkCidr and RemoteIpv4NetworkCidr)](https://awscli.amazonaws.com/v2/documentation/api/latest/reference/ec2/modify-vpn-tunnel-options.html) and should accept any valid IPv4 CIDR with a network value between 0 and 32.
* I believe the issue is in the [aws/resource_aws_vpn_connection.go validateLocalIpv4NetworkCidr()](https://github.com/hashicorp/terraform-provider-aws/blob/22664288907bfac377160ab6cd288a188fd167d2/aws/resource_aws_vpn_connection.go#L1691) function

  ```golang
  func validateLocalIpv4NetworkCidr() schema.SchemaValidateFunc {
	  return validation.All(
		  validation.IsCIDRNetwork(32, 32),
	  )
  }
  ```
  
  I believe this should be modified to accept CIDR networks in the range of 0 to 32:
  
  ```golang
  func validateLocalIpv4NetworkCidr() schema.SchemaValidateFunc {
	  return validation.All(
		  validation.IsCIDRNetwork(0, 32),
	  )
  }
  ```

### PR DESCRIPTION
**Pull request by jsf9k**
Previously the IPv4 parameters were required to be a `/32` and the IPv6 parameters were restricted to be a `/128`.  This constraint is not mentioned in the Terraform or AWS documentation, and in fact the default values are `/0`s.

Without this change, users are forced to leave `local_ipv4_network_cidr`, `local_ipv6_network_cidr`, `remote_ipv4_network_cidr`, and `remote_ipv6_network_cidr` unspecified, resulting in the values `0.0.0.0/0` or `0::/128` being used.  This is obviously suboptimal.  Depending on what hardware or software is at the other end of the tunnel, it may even prevent the tunnel from functioning as expected.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #16879.

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSVpnConnection_specifyIpv*'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSVpnConnection_specifyIpv* -timeout 120m
=== RUN   TestAccAWSVpnConnection_specifyIpv4
=== PAUSE TestAccAWSVpnConnection_specifyIpv4
=== RUN   TestAccAWSVpnConnection_specifyIpv6
=== PAUSE TestAccAWSVpnConnection_specifyIpv6
=== CONT  TestAccAWSVpnConnection_specifyIpv4
=== CONT  TestAccAWSVpnConnection_specifyIpv6
--- PASS: TestAccAWSVpnConnection_specifyIpv4 (231.47s)
--- PASS: TestAccAWSVpnConnection_specifyIpv6 (648.26s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       648.345s
```

### CODE REVIEW

**Comment by nikolai-derzhak-distillery** [comment]
Hey, guys, we really would appreciate if you you merge that (assuming no issues with PR). As we are going to have bunch of customers soon and rest of infra already in terraform. Thanks !

**Comment by jsf9k** [comment]
@YakDriver, do you want me to fix those failing tests or is that something you're currently working on?  I don't want to step on your toes.

**Comment by YakDriver** [comment]
@jsf9k Thanks for the offer and this PR! GovCloud operates a little differently so I'm adjusting that while I'm here. Other than that we should be good to go in the next few (30-60) minutes.

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 Thanks!

Output from acceptance tests (`us-west-2`):
```
--- PASS: TestAccAWSVpnConnection_basic (716.42s)
--- PASS: TestAccAWSVpnConnection_disappears (375.44s)
--- PASS: TestAccAWSVpnConnection_specifyIpv4 (754.19s)
--- PASS: TestAccAWSVpnConnection_specifyIpv6 (669.27s)
--- PASS: TestAccAWSVpnConnection_tags (303.79s)
--- PASS: TestAccAWSVpnConnection_TransitGatewayID (657.22s)
--- PASS: TestAccAWSVpnConnection_Tunnel1InsideCidr (645.87s)
--- PASS: TestAccAWSVpnConnection_Tunnel1InsideIpv6Cidr (616.98s)
--- PASS: TestAccAWSVpnConnection_Tunnel1PresharedKey (769.15s)
--- PASS: TestAccAWSVpnConnection_tunnelOptions (306.45s)
--- PASS: TestAccAWSVpnConnection_tunnelOptionsLesser (332.30s)
--- PASS: TestAccAWSVpnConnection_withEnableAcceleration (737.10s)
--- PASS: TestAccAWSVpnConnection_withIpv6 (589.56s)
--- PASS: TestAccAWSVpnConnection_withoutStaticRoutes (316.15s)
```

Output from acceptance tests (GovCloud):
```

--- PASS: TestAccAWSVpnConnection_basic (658.72s)
--- PASS: TestAccAWSVpnConnection_disappears (256.03s)
--- PASS: TestAccAWSVpnConnection_specifyIpv4 (210.24s)
--- PASS: TestAccAWSVpnConnection_specifyIpv6 (841.73s)
--- PASS: TestAccAWSVpnConnection_tags (274.36s)
--- PASS: TestAccAWSVpnConnection_TransitGatewayID (906.37s)
--- PASS: TestAccAWSVpnConnection_Tunnel1InsideCidr (245.02s)
--- PASS: TestAccAWSVpnConnection_Tunnel1InsideIpv6Cidr (786.89s)
--- PASS: TestAccAWSVpnConnection_Tunnel1PresharedKey (225.87s)
--- PASS: TestAccAWSVpnConnection_tunnelOptionsLesser (242.62s)
--- PASS: TestAccAWSVpnConnection_withIpv6 (781.76s)
--- PASS: TestAccAWSVpnConnection_withoutStaticRoutes (227.04s)
--- SKIP: TestAccAWSVpnConnection_tunnelOptions (29.48s)
--- SKIP: TestAccAWSVpnConnection_withEnableAcceleration (486.27s)
```

**Comment by jsf9k** [comment]
Thanks @YakDriver!

**Pull request merged**
