### PR TITLE
B add filter to iot_thing_indexing_configuration

### PR DESCRIPTION
**Pull request by Oltier**
## Change summary
Update the [Create|Get|Update]IndexingConfiguration requests with a new optional parameter: filter 

## Change details
AWS has introduced a breaking change, making `filter` attribute required, when `named_shadow_indexing_mode` is set to ON. 
https://docs.aws.amazon.com/iot/latest/apireference/API_ThingIndexingConfiguration.html
https://awsapichanges.info/archive/changes/0a7be3-iot.html

If filter is missing in the described case above, then the following error message is returned when trying to add a similar configuration:

```
resource "aws_iot_indexing_configuration" "indexing-config" {
  thing_indexing_configuration {
    thing_indexing_mode              = "REGISTRY_AND_SHADOW"
    thing_connectivity_indexing_mode = "STATUS"
    named_shadow_indexing_mode       = "ON"

    custom_field {
      name = "shadow.name.shadowName.desired.someStringValue"
      type = "String"
    }
  }
}
```

```
Error: error updating IoT Indexing Configuration: InvalidRequestException: NamedShadowNames Filter must not be empty for enabling NamedShadowIndexingMode
```

Closes https://github.com/hashicorp/terraform-provider-aws/issues/27532

Output from acceptance testing:

```
AWS_PROFILE=default TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20 -run='TestAccIoTIndexingConfiguration_serial'  -timeout 180m
=== RUN   TestAccIoTIndexingConfiguration_serial
=== RUN   TestAccIoTIndexingConfiguration_serial/basic
=== RUN   TestAccIoTIndexingConfiguration_serial/allAttributes
--- PASS: TestAccIoTIndexingConfiguration_serial (51.15s)
    --- PASS: TestAccIoTIndexingConfiguration_serial/basic (27.02s)
    --- PASS: TestAccIoTIndexingConfiguration_serial/allAttributes (24.13s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/iot        52.884s
```

### CODE REVIEW

**Comment by yelloweiffel** [comment]
:thumbsup:

**Comment by tmarlok88** [comment]
The functionality is currently broken since aws introduced this change: https://awsapichanges.info/archive/changes/0a7be3-iot.html
`named_shadow_indexing_mode` cannot be enabled without a filter.

**Comment by gergo-schreiner-goto** [comment]
Hey,

Can somebody review the PR and merge the changes?

Thanks in advance!

**Comment by BernhardRode** [comment]
Any news on when this can be merged?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

#### Before

```console
% make testacc TESTARGS='-run=TestAccIoTIndexingConfiguration_serial' PKG=iot
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTIndexingConfiguration_serial -timeout 360m
=== RUN   TestAccIoTIndexingConfiguration_serial
=== PAUSE TestAccIoTIndexingConfiguration_serial
=== CONT  TestAccIoTIndexingConfiguration_serial
=== RUN   TestAccIoTIndexingConfiguration_serial/basic
=== RUN   TestAccIoTIndexingConfiguration_serial/allAttributes
    indexing_configuration_test.go:64: Step 1/2 error: Error running apply: exit status 1
        
        Error: updating IoT Indexing Configuration: InvalidRequestException: NamedShadowNames Filter must not be empty for enabling NamedShadowIndexingMode
        
          with aws_iot_indexing_configuration.test,
          on terraform_plugin_test.tf line 2, in resource "aws_iot_indexing_configuration" "test":
           2: resource "aws_iot_indexing_configuration" "test" {
        
--- FAIL: TestAccIoTIndexingConfiguration_serial (28.95s)
    --- PASS: TestAccIoTIndexingConfiguration_serial/basic (21.73s)
    --- FAIL: TestAccIoTIndexingConfiguration_serial/allAttributes (7.23s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/iot        33.982s
FAIL
make: *** [testacc] Error 1
```

#### After

```console
% make testacc TESTARGS='-run=TestAccIoTIndexingConfiguration_serial' PKG=iot
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 20  -run=TestAccIoTIndexingConfiguration_serial -timeout 360m
=== RUN   TestAccIoTIndexingConfiguration_serial
=== PAUSE TestAccIoTIndexingConfiguration_serial
=== CONT  TestAccIoTIndexingConfiguration_serial
=== RUN   TestAccIoTIndexingConfiguration_serial/basic
=== RUN   TestAccIoTIndexingConfiguration_serial/allAttributes
--- PASS: TestAccIoTIndexingConfiguration_serial (43.69s)
    --- PASS: TestAccIoTIndexingConfiguration_serial/basic (22.00s)
    --- PASS: TestAccIoTIndexingConfiguration_serial/allAttributes (21.68s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	49.206s
```

**Comment by ewbankkit** [comment]
@Oltier Thanks for the contribution :tada: :clap:.

**Pull request merged**
