### PR TITLE
r/iot_authorizer - new resource 

### LINKED ISSUE #13412: Support AWS IoT Core Custom Authorizers
_This issue was originally opened by @uvtrip as hashicorp/terraform#24977. It was migrated here as a result of the [provider split](https://www.hashicorp.com/blog/upcoming-provider-changes-in-terraform-0-10/). The original body of the issue is below._
    
<hr>
    

### Current Terraform Version

```
0.12.25
```

### Use-cases

We're using AWS IoT custom authorizers as part of our IoT deployment. We use it to authenticate IoT devices.
### Attempted Solutions

Currently we're using 'local-exec' in order to run aws command to create the custom authorize. This means we need to handle cases where the object exists or not and take care of it.
### Proposal

I would be easier if we can use it as TF module

### PR DESCRIPTION
**Pull request by Billlynch**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #13412

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource_aws_iot_authorizer - new resource
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSIoTAuthorizer'
--- PASS: TestAccAWSIoTAuthorizer_disappears (44.06s)
--- PASS: TestAccAWSIoTAuthorizer_basic (87.09s)

...
```

### CODE REVIEW

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Action Required: Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by ballwood** [comment]
@bflad any timescales on review of this? quite a lot of +1’s now

**Comment by vhbfernandes** [comment]
@bflad anyone looking at this?

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TESTARGS='-run=TestAccAWSIoTAuthorizer_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSIoTAuthorizer_ -timeout 180m
=== RUN   TestAccAWSIoTAuthorizer_basic
=== PAUSE TestAccAWSIoTAuthorizer_basic
=== RUN   TestAccAWSIoTAuthorizer_disappears
=== PAUSE TestAccAWSIoTAuthorizer_disappears
=== RUN   TestAccAWSIoTAuthorizer_SigningDisabled
=== PAUSE TestAccAWSIoTAuthorizer_SigningDisabled
=== RUN   TestAccAWSIoTAuthorizer_Update
=== PAUSE TestAccAWSIoTAuthorizer_Update
=== CONT  TestAccAWSIoTAuthorizer_basic
=== CONT  TestAccAWSIoTAuthorizer_Update
=== CONT  TestAccAWSIoTAuthorizer_SigningDisabled
=== CONT  TestAccAWSIoTAuthorizer_disappears
--- PASS: TestAccAWSIoTAuthorizer_disappears (40.49s)
--- PASS: TestAccAWSIoTAuthorizer_Update (45.84s)
--- PASS: TestAccAWSIoTAuthorizer_basic (49.35s)
--- PASS: TestAccAWSIoTAuthorizer_SigningDisabled (54.32s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	57.722s
```

##### GovCloud

```console
% make testacc TESTARGS='-run=TestAccAWSIoTAuthorizer_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSIoTAuthorizer_ -timeout 180m
=== RUN   TestAccAWSIoTAuthorizer_basic
=== PAUSE TestAccAWSIoTAuthorizer_basic
=== RUN   TestAccAWSIoTAuthorizer_disappears
=== PAUSE TestAccAWSIoTAuthorizer_disappears
=== RUN   TestAccAWSIoTAuthorizer_SigningDisabled
=== PAUSE TestAccAWSIoTAuthorizer_SigningDisabled
=== RUN   TestAccAWSIoTAuthorizer_Update
=== PAUSE TestAccAWSIoTAuthorizer_Update
=== CONT  TestAccAWSIoTAuthorizer_basic
=== CONT  TestAccAWSIoTAuthorizer_Update
=== CONT  TestAccAWSIoTAuthorizer_SigningDisabled
=== CONT  TestAccAWSIoTAuthorizer_disappears
--- PASS: TestAccAWSIoTAuthorizer_basic (37.34s)
--- PASS: TestAccAWSIoTAuthorizer_disappears (41.32s)
--- PASS: TestAccAWSIoTAuthorizer_SigningDisabled (56.25s)
--- PASS: TestAccAWSIoTAuthorizer_Update (62.92s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	66.121s
```

**Comment by ewbankkit** [comment]
@Billlynch Thanks for the contribution :tada: :clap:.

**Pull request merged**
