### PR TITLE
Add support for importing root CA certs to aws_acmpca_certificate resource

### LINKED ISSUE #19350: Add import support for aws_acmpca_certificate and aws_acmpca_certificate_authority_certificate
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Now that the ACM PCA support has been added to this provider, we find ourselves in a situation where we've been using a forked version of the provider to create these resources for the last year or so. We'd like to migrate all of these to the mainline provider, but without all of the resource types being importable, there is no obvious way of doing this.

Ways that don't work:
- removing from state and importing (only aws_acmpca_certificate_authority is currently importable).
- moving providers and then attempting to `state mv` resources - changing resource types with state moves is not permitted. The forked provider had different names for resources to what is now in the mainline of terraform-provider-aws.
- just running Terraform and letting it figure out what to do - this will reissue all of our ACM PCA resources which will be very disruptive to our services. I imagine many other people will be in the same situation.

### Affected Resource(s)

* aws_acmpca_certificate
* aws_acmpca_certificate_authority_certificate

### Potential Terraform Configuration

N/A

### References

* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate#import
* https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/acmpca_certificate_authority_certificate (no import section)

### PR DESCRIPTION
**Pull request by liath**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19350

Output from acceptance testing:

```
$ $ rg '^func TestAcc' aws/resource_aws_acmpca_certificate_test.go | cut -d ' ' -f 2 | cut -d '(' -f 1 | xargs -I'{}' make testacc TESTARGS="-run={}"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAcmpcaCertificate_RootCertificate -timeout 180m
=== RUN   TestAccAwsAcmpcaCertificate_RootCertificate
=== PAUSE TestAccAwsAcmpcaCertificate_RootCertificate
=== CONT  TestAccAwsAcmpcaCertificate_RootCertificate
--- PASS: TestAccAwsAcmpcaCertificate_RootCertificate (26.43s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       28.099s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAcmpcaCertificate_SubordinateCertificate -timeout 180m
=== RUN   TestAccAwsAcmpcaCertificate_SubordinateCertificate
=== PAUSE TestAccAwsAcmpcaCertificate_SubordinateCertificate
=== CONT  TestAccAwsAcmpcaCertificate_SubordinateCertificate
--- PASS: TestAccAwsAcmpcaCertificate_SubordinateCertificate (34.95s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       36.600s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAcmpcaCertificate_EndEntityCertificate -timeout 180m
=== RUN   TestAccAwsAcmpcaCertificate_EndEntityCertificate
=== PAUSE TestAccAwsAcmpcaCertificate_EndEntityCertificate
=== CONT  TestAccAwsAcmpcaCertificate_EndEntityCertificate
--- PASS: TestAccAwsAcmpcaCertificate_EndEntityCertificate (38.39s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       40.080s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAcmpcaCertificate_Validity_EndDate -timeout 180m
=== RUN   TestAccAwsAcmpcaCertificate_Validity_EndDate
=== PAUSE TestAccAwsAcmpcaCertificate_Validity_EndDate
=== CONT  TestAccAwsAcmpcaCertificate_Validity_EndDate
--- PASS: TestAccAwsAcmpcaCertificate_Validity_EndDate (36.77s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       38.436s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAwsAcmpcaCertificate_Validity_Absolute -timeout 180m
=== RUN   TestAccAwsAcmpcaCertificate_Validity_Absolute
=== PAUSE TestAccAwsAcmpcaCertificate_Validity_Absolute
=== CONT  TestAccAwsAcmpcaCertificate_Validity_Absolute
--- PASS: TestAccAwsAcmpcaCertificate_Validity_Absolute (32.71s)
PASS
```

### CODE REVIEW

**Comment by Liath** [comment]
Am I reading this right in the docs? https://www.terraform.io/docs/extend/resources/import.html#multiple-resource-import
It seems to say we can populate the aws_acmpca_certificate_authority_certificate resource in one pass.

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by liath** [comment]
Stalebot isn't really appropriate for a project that moves this slow lol

**Comment by liath** [comment]
Looks like the documentation update for this happened in #27333 and I don't remember the relevance of the code change so closing this

**Pull request closed without merging**
