### PR TITLE
docs: Clarify kinesis_firehose_delivery_stream dynamic partitioning requirements

### LINKED ISSUE #29092: [Docs]: kinesis_firehose_delivery_stream
### Documentation Link

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream

### Description

There are two minor problems I have found.

1 A delivery stream cannot be updated when enabling dynamic partitioning.

When defining a delivery stream with dynamic partitioning, you must create a new delivery stream and cannot update an existing delivery stream. 

This is a known limitation within AWS. 
This could be highlighted in the provider documentation to simplify debugging.

The `dynamic_partitioning_configuration` block makes things confusing because one might assume that this can be toggled. However, changing this configuration does not destroy and recreate the stream (as would be required to effect the change that is desired).

In other words, if you want to enable dynamic partitioning configuration on an existing stream, *it must first be deleted*, regardless of any configuration.

2 Missing configuration block

You must include the `dynamic_partitioning_configuration` block otherwise the apply will fail with the error:

`Error: creating Kinesis Firehose Delivery Stream: InvalidArgumentException: Dynamic Partitioning Namespaces can only be part of a prefix expression when Dynamic Partitioning is enabled.`

The example given in the documentation does not include this block. 

The error message therefore is a little ambiguous; it seems to indicate a problem with the prefix expression and it is not obvious that `dynamic_partitioning_configuration` should be specified.

### References

https://docs.aws.amazon.com/firehose/latest/dev/dynamic-partitioning.html

Within "How to enable dynamic partitioning" :

> You can enable dynamic partitioning only when you create a new delivery stream. You cannot enable dynamic partitioning for an existing delivery stream that does not have dynamic partitioning already enabled.

Also

> Once you enable dynamic partitioning on a delivery stream, it cannot be disabled on this delivery stream.

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by baolsen**
Closes #29092

### CODE REVIEW

**Review by mattburgess — COMMENTED** [review]
Hi @baolsen. Given the behaviour you describe and kindly pointed to in the documentation, would you be able to add `ForceNew: true,` [here](https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/firehose/delivery_stream.go#L70-L74) please? That way Terraform will actually force the recreation of the resource rather than just failing as is happening to you at the moment.

**Comment by baolsen** [comment]
Thanks for the feedback @mattburgess , that is super useful.

I've made a fixup commit for the changes - please check :)

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
$ make testacc TESTARGS='-run=TestAccFirehoseDeliveryStream_' PKG=firehose

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20  -run=TestAccFirehoseDeliveryStream_ -timeout 180m
--- PASS: TestAccFirehoseDeliveryStream_s3KinesisStreamSource (63.27s)
--- PASS: TestAccFirehoseDeliveryStream_extendedS3basic (216.59s)
--- PASS: TestAccFirehoseDeliveryStream_missingProcessing (216.59s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionHiveJSONSerDe_empty (226.75s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionDeserializer_update (233.43s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_errorOutputPrefix (233.66s)
--- PASS: TestAccFirehoseDeliveryStream_splunkUpdates (235.65s)
--- PASS: TestAccFirehoseDeliveryStream_s3Updates (241.87s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOpenXJSONSerDe_empty (243.49s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionOrcSerDe_empty (244.20s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionSerializer_update (245.46s)
--- PASS: TestAccFirehoseDeliveryStream_basic (253.87s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversionParquetSerDe_empty (257.73s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_externalUpdate (267.13s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_kinesisStreamSource (56.80s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3DataFormatConversion_enabled (287.31s)
--- PASS: TestAccFirehoseDeliveryStream_s3basicWithSSEAndKeyARN (433.20s)
--- PASS: TestAccFirehoseDeliveryStream_extendedS3KMSKeyARN (191.94s)
--- PASS: TestAccFirehoseDeliveryStream_HTTPEndpoint_ErrorOutputPrefix (246.12s)
--- PASS: TestAccFirehoseDeliveryStream_s3basicWithPrefixes (284.82s)
--- PASS: TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioningUpdate (466.78s)
--- PASS: TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning (278.61s)
--- PASS: TestAccFirehoseDeliveryStream_disappears (294.81s)
--- PASS: TestAccFirehoseDeliveryStream_extendedS3Updates (308.64s)
--- PASS: TestAccFirehoseDeliveryStream_s3basic (300.86s)
--- PASS: TestAccFirehoseDeliveryStream_s3basicWithTags (302.53s)
--- PASS: TestAccFirehoseDeliveryStream_s3WithCloudWatchLogging (304.66s)
--- PASS: TestAccFirehoseDeliveryStream_HTTPEndpoint_retryDuration (263.42s)
--- PASS: TestAccFirehoseDeliveryStream_s3basicWithSSEAndKeyType (325.32s)
--- PASS: TestAccFirehoseDeliveryStream_s3basicWithSSE (402.65s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3Processing_empty (208.66s)
--- PASS: TestAccFirehoseDeliveryStream_httpEndpoint (244.10s)
--- PASS: TestAccFirehoseDeliveryStream_ExtendedS3_S3BackupConfiguration_ErrorOutputPrefix (201.58s)
--- PASS: TestAccFirehoseDeliveryStream_Splunk_ErrorOutputPrefix (216.05s)
--- PASS: TestAccFirehoseDeliveryStream_tagUpdates (537.47s)
--- PASS: TestAccFirehoseDeliveryStream_redshiftUpdates (545.65s)
--- PASS: TestAccFirehoseDeliveryStream_elasticSearchEndpointUpdates (1524.80s)
--- PASS: TestAccFirehoseDeliveryStream_Elasticsearch_ErrorOutputPrefix (1626.40s)
--- PASS: TestAccFirehoseDeliveryStream_elasticSearchUpdates (1667.06s)
--- PASS: TestAccFirehoseDeliveryStream_elasticSearchWithVPCUpdates (2461.72s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	2464.911s
```

**Comment by johnsonaj** [comment]
@baolsen thank you for the contribution! 🎉 👏🏾

**Pull request merged**
