### PR TITLE
Only reject tags for standard EIPs on EC2 Classic

### LINKED ISSUE #18756: Tags not being assigned to Elastic IP instances
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Regression
Relates #17612

### Terraform CLI and Terraform AWS Provider Version

ubuntu@ip-10-1-10-161:~/sandbox$ terraform -v
Terraform v0.14.5
+ provider registry.terraform.io/hashicorp/aws v3.36.0

### Affected Resource(s)

* aws_eip

### Terraform Configuration Files

```hcl
data "aws_ami" "ubuntu" {
  most_recent = true
  filter {
    name   = "name"
    values = ["ami-ubuntu-16.04-*"]
  }
  owners = ["285398391915"] # Canonical
}

locals {
  common_tags = {"Deployment" = "custom", "email" = "qa@editshare.com"}
}

resource aws_instance "nodes" {
  ami = data.aws_ami.ubuntu.id
  instance_type = "t2.medium"
  key_name = "TO_BE_SUPPLIED"
  availability_zone = "us-east-2a"
  subnet_id = "TO_BE_SUPPLIED"
  tags = {
    Name = "tome-foo"
  }
}

resource "aws_eip" "node_eip" {
  instance = aws_instance.nodes.id
  tags = {
      Name = "foo-node-01-eip"
      NodeName = "foo-node-01"
    }
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

The two tags specified in the aws_eip declaration should be present when viewing the Tags section of the Elastic IP from the AWS Console.

### Actual Behavior

No Tags are present.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

1.  the tags are assigned correctly when this test module is run from Mac OS X deployment machines
2. the tags are assigned correctly when this test module is run from Terraform Cloud
3.  the tags are NOT assigned at all when this test module is run from Ubuntu 20.04 LTS, recreated on a server in our Dev Ops pipeline or one Launched from the AWS Console
4.  the tags are NOT assigned at all when this test module is run from Ubuntu 18.04 LTS ec2 instance running in AWS
5. if you run `terraform apply` again from the Ubuntu 20.04 test machine, terraform indicates the aws_eip will be updated in-place, with the changes being to add the two tags.  looks like the provider supports the tags, but somehow not on the initial deployment of the resource.  output from that `apply` operation is below
6. *IMPORTANT! the tags are properly assigned to the EIP when it is created if we pin the aws provider to 3.35.0.  therefore we believe this was introduced in recent changes that are part of aws provider 3.36.0*

```shell
ubuntu@ip-10-1-10-161:~/sandbox$ terraform apply
aws_instance.nodes: Refreshing state... [id=i-01f47a7fb12aca60e]
aws_eip.node_eip: Refreshing state... [id=eipalloc-02c6281e8fe1a3479]

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_eip.node_eip will be updated in-place
  ~ resource "aws_eip" "node_eip" {
        id                   = "eipalloc-02c6281e8fe1a3479"
      ~ tags                 = {
          + "Name"     = "foo-node-01-eip"
          + "NodeName" = "foo-node-01"
        }
        # (11 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.
```

### References

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/eip

* #0000

### PR DESCRIPTION
**Pull request by rick-masters**
Only reject tags for standard EIPs for EC2 Classic platforms.

Fixes a regression introduced here:
https://github.com/hashicorp/terraform-provider-aws/pull/17612/files#diff-5cc53a93a886b4b2474bd02b135f8aabd7f4aeb82d77e8ac0378386eaa01ae84L186

The code above did not take account of the fact that  accounts without EC2 Classic support will automatically default to type "vpc" for EIPs and so tags are ok.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #18756 

Output from acceptance testing:

Pending...

### CODE REVIEW

**Comment by YakDriver** [comment]
@rick-masters Cool! Thanks for the awesomely quick response.

I want to make sure we catch all cases. Forgive/correct my ignorances of all the EC2 classic nuances as I go through these. This is how it _should_ behave?

| acct/region type | default vpc? | `vpc = true` | tags set | resulting eip domain | result |
| -- | -- | -- | -- | -- | -- |
| EC2 Classic | Yes | Yes | Yes | VPC |  Tags |
| EC2 Classic | Yes | No | Yes | Standard? | Error |
| EC2 Classic | No | Yes |  Yes | VPC |Tags |
| EC2 Classic | No | No |  Yes | Standard | Error |
| VPC | Yes | Yes | Yes | VPC | Tags |
| VPC | Yes | No | Yes | VPC? | Tags |
| VPC | No | Yes | Yes | VPC | Tags |
| VPC | No | No | Yes | Standard | Error |
| EC2 Classic | Yes | Yes | No | VPC |  No Tags |
| EC2 Classic | Yes | No | No | Standard? | No Tags |
| EC2 Classic | No | Yes |  No | VPC | No Tags |
| EC2 Classic | No | No |  No | Standard | No Tags |
| VPC | Yes | Yes | No | VPC | No Tags |
| VPC | Yes | No | No | VPC? | No Tags |
| VPC | No | Yes | No | VPC | No Tags |
| VPC | No | No | No | Standard | No Tags |

**Comment by rick-masters** [comment]
I'm not sure about the column "default vpc?". Does that mean "Is there a default VPC present in the region?" If so, then I'm not sure that is relevant but I suppose it can't hurt to test.

With regards to EC2 Classic or VPC there are two factors: whether the account supports EC2 classic (was it created circa 2013 or earlier) and the second factor is does the region support EC2 Classic (us-east-1, us-west-1, us-west-2 are yes, us-east-2 is no). EC2 Classic is available only when both are true. BTW, I have access to both types of accounts for testing.

**Comment by YakDriver** [comment]
Are tags precisely on allocation terribly important? If not, we could simply skip tags in create and let update (called by create) take care of them. The benefit there is that we're relying on what AWS says the domain type is rather than trying to make sure we guess correctly. I think 🤞 we've got the logic down but I'm concerned about edge cases. If a VPC account/region has no default VPC and the config doesn't set `vpc = true`, does AWS assign a domain type of standard?

**Comment by YakDriver** [comment]
Yes, it looks like based on your comment here https://github.com/hashicorp/terraform-provider-aws/issues/16881#issuecomment-778936536, that tags are indeed important on creation.

**Comment by rick-masters** [comment]
My understanding is that the present of a default vpc is not relevant to the type of EIP that is created. https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_AllocateAddress.html
```
Default: If the Region supports EC2-Classic, the default is standard. Otherwise, the default is vpc.
```
I suspect this means "If your account and region supports EC2-Classic,  ...." but I'll confirm when I run my test in a few minutes.

**Comment by rick-masters** [comment]
I didn't run all variations, but I ran these and have not seen a problem so far:

| Acct Type | Region Type | default vpc? | vpc = true | Tags? | ->Domain | -> Tags/Error |
|---------- |------------ | -------------|------------|-------|----------|---------------|
| ec2       | ec2         | Yes          | Yes        | Yes   |  vpc     | tags |
| ec2       | ec2         | Yes          | No         | Yes   |  n/a     | error |
| ec2       | vpc         | No           | Yes        | Yes   |  vpc     | tags |
| ec2       | vpc         | No           | No         | Yes   |  vpc     | tags |
| vpc       | ec2         | Yes          | Yes        | Yes   |  vpc     | tags |
| vpc       | ec2         | Yes          | No         | Yes   |  vpc     | tags  |
| vpc       | vpc         | No           | Yes        | Yes   |  vpc     | tags |
| vpc       | vpc         | No           | No         | Yes   |  vpc     | tags |
| ec2       | ec2         | Yes          | Yes        | No    |  vpc     | no tags |
| ec2       | ec2         | Yes          | No         | No    |  ec2     | no tags |
| ec2       | vpc         | No           | Yes        | No    |  vpc     | no tags |
| ec2       | vpc         | No           | No         | No    |  vpc     | no tags |
| vpc       | ec2         | Yes          | Yes        | No    |  vpc     | no tags |
| vpc       | ec2         | Yes          | No         | No    |  vpc     | no tags |
| vpc       | vpc         | No           | Yes        | No    |  vpc     | no tags |
| vpc       | vpc         | No           | No         | No    |  vpc     | no tags |

main.tf
```
resource "aws_eip" "node_eip" {
  tags = {
    Name = "test-foo-node-01-eip"
    NodeName = "test-foo-node-01"
   }
   vpc = true
}
```

test.sh
```
#!/usr/bin/env bash
#shellcheck disable=1090

for tags_present in yes no; do
   for account_type in vpc ec2; do
      for region_type in ec2 vpc; do
          for vpc_true in no yes; do

               if [ "$account_type" = "ec2" ]; then
                   source ec2_creds.sh
               else
                   source vpc_creds.sh
               fi

               if [ "$region_type" = "ec2" ]; then
                   export AWS_DEFAULT_REGION=us-west-1
               else
                   export AWS_DEFAULT_REGION=us-east-2
               fi

               if [ "$vpc_true" = "yes" ]; then
                   sed -i 's/#vpc = true/ vpc = true/' main.tf
               else
                   sed -i 's/ vpc = true/#vpc = true/' main.tf
               fi

               if [ "$tags_present" = "yes" ]; then
                   sed -i 's/#tags/ tags/' main.tf
                   sed -i 's/#Name/ Name/' main.tf
                   sed -i 's/#Node/ Node/' main.tf
                   sed -i 's/ #}/  }/' main.tf
               else
                   sed -i 's/ tags/#tags/' main.tf
                   sed -i 's/ Name/#Name/' main.tf
                   sed -i 's/ Node/#Node/' main.tf
                   sed -i 's/  }/ #}/' main.tf
               fi

               cat main.tf
               printf "acct: %s region: %s vpc_true: %s tags: %s\n" "$account_type" "$region_type" "$vpc_true" "$tags_present"
               set | grep AWS
               read -r _
               TF_LOG=debug TF_CLI_CONFIG_FILE=rcterraform terraform apply
               printf "acct: %s region: %s vpc_true: %s tags: %s\n" "$account_type" "$region_type" "$vpc_true" "$tags_present"
               printf "Check results: "; read -r _
               TF_LOG=debug TF_CLI_CONFIG_FILE=rcterraform terraform destroy
           done
       done
   done
done
```

**Comment by rick-masters** [comment]
Passed all EIP acceptance tests. There are two runs here, one with a VPC style account and one with an EC2 Classic account.

VPC style account:
```
TF_ACC=1 go test ./aws -v -count 1 -parallel 1 -run=TestAccAWSEIP -timeout 180m               
=== RUN   TestAccAWSEIPAssociation_instance                                                                                                      
=== PAUSE TestAccAWSEIPAssociation_instance          
=== RUN   TestAccAWSEIPAssociation_networkInterface
=== PAUSE TestAccAWSEIPAssociation_networkInterface      
=== RUN   TestAccAWSEIPAssociation_basic             
=== PAUSE TestAccAWSEIPAssociation_basic          
=== RUN   TestAccAWSEIPAssociation_ec2Classic      
=== PAUSE TestAccAWSEIPAssociation_ec2Classic               
=== RUN   TestAccAWSEIPAssociation_spotInstance                                                                                                  
=== PAUSE TestAccAWSEIPAssociation_spotInstance                                                                                                  
=== RUN   TestAccAWSEIPAssociation_disappears                           
=== PAUSE TestAccAWSEIPAssociation_disappears                                                                                                    
=== RUN   TestAccAWSEIP_Ec2Classic
=== PAUSE TestAccAWSEIP_Ec2Classic
=== RUN   TestAccAWSEIP_basic
=== PAUSE TestAccAWSEIP_basic
=== RUN   TestAccAWSEIP_instance
=== PAUSE TestAccAWSEIP_instance
=== RUN   TestAccAWSEIP_networkInterface
=== PAUSE TestAccAWSEIP_networkInterface
=== RUN   TestAccAWSEIP_twoEIPsOneNetworkInterface
=== PAUSE TestAccAWSEIP_twoEIPsOneNetworkInterface
=== RUN   TestAccAWSEIP_associated_user_private_ip
=== PAUSE TestAccAWSEIP_associated_user_private_ip
=== RUN   TestAccAWSEIP_Instance_Reassociate
=== PAUSE TestAccAWSEIP_Instance_Reassociate
=== RUN   TestAccAWSEIP_disappears
=== PAUSE TestAccAWSEIP_disappears
=== RUN   TestAccAWSEIP_notAssociated
=== PAUSE TestAccAWSEIP_notAssociated
=== RUN   TestAccAWSEIP_tags_Vpc
=== PAUSE TestAccAWSEIP_tags_Vpc
=== RUN   TestAccAWSEIP_tags_Ec2Classic
=== PAUSE TestAccAWSEIP_tags_Ec2Classic
=== RUN   TestAccAWSEIP_PublicIpv4Pool_default
=== PAUSE TestAccAWSEIP_PublicIpv4Pool_default
=== RUN   TestAccAWSEIP_NetworkBorderGroup
=== PAUSE TestAccAWSEIP_NetworkBorderGroup
=== RUN   TestAccAWSEIP_CarrierIP
=== PAUSE TestAccAWSEIP_CarrierIP
=== RUN   TestAccAWSEIP_PublicIpv4Pool_custom
    resource_aws_eip_test.go:515: Environment variable AWS_EC2_EIP_PUBLIC_IPV4_POOL is not set                                          [11/1697]
--- SKIP: TestAccAWSEIP_PublicIpv4Pool_custom (0.00s)
=== RUN   TestAccAWSEIP_CustomerOwnedIpv4Pool
=== PAUSE TestAccAWSEIP_CustomerOwnedIpv4Pool
=== CONT  TestAccAWSEIPAssociation_instance
--- PASS: TestAccAWSEIPAssociation_instance (342.87s)
=== CONT  TestAccAWSEIP_NetworkBorderGroup
--- PASS: TestAccAWSEIP_NetworkBorderGroup (15.39s)
=== CONT  TestAccAWSEIP_CustomerOwnedIpv4Pool
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSEIP_CustomerOwnedIpv4Pool (0.38s)
=== CONT  TestAccAWSEIP_CarrierIP
    resource_aws_ec2_carrier_gateway_test.go:249: skipping since no Wavelength Zones are available
--- SKIP: TestAccAWSEIP_CarrierIP (0.12s)
=== CONT  TestAccAWSEIP_networkInterface
--- PASS: TestAccAWSEIP_networkInterface (63.56s)
=== CONT  TestAccAWSEIP_PublicIpv4Pool_default
--- PASS: TestAccAWSEIP_PublicIpv4Pool_default (14.99s)
=== CONT  TestAccAWSEIPAssociation_disappears
--- PASS: TestAccAWSEIPAssociation_disappears (85.42s)
=== CONT  TestAccAWSEIP_tags_Ec2Classic
    ec2_classic_test.go:54: this test can only run in EC2-Classic, platforms available in us-east-1: ["VPC"]
--- SKIP: TestAccAWSEIP_tags_Ec2Classic (0.95s)
=== CONT  TestAccAWSEIP_instance
--- PASS: TestAccAWSEIP_instance (92.10s)
=== CONT  TestAccAWSEIP_tags_Vpc
--- PASS: TestAccAWSEIP_tags_Vpc (22.29s)
=== CONT  TestAccAWSEIP_basic
--- PASS: TestAccAWSEIP_basic (14.70s)
=== CONT  TestAccAWSEIP_notAssociated
--- PASS: TestAccAWSEIP_notAssociated (130.81s)
=== CONT  TestAccAWSEIP_Ec2Classic
    ec2_classic_test.go:54: this test can only run in EC2-Classic, platforms available in us-east-1: ["VPC"]
--- SKIP: TestAccAWSEIP_Ec2Classic (0.00s)
=== CONT  TestAccAWSEIP_disappears
--- PASS: TestAccAWSEIP_disappears (10.41s)
=== CONT  TestAccAWSEIP_Instance_Reassociate
--- PASS: TestAccAWSEIP_Instance_Reassociate (115.90s)
=== CONT  TestAccAWSEIP_twoEIPsOneNetworkInterface
--- PASS: TestAccAWSEIP_twoEIPsOneNetworkInterface (64.26s)
=== CONT  TestAccAWSEIP_associated_user_private_ip
--- PASS: TestAccAWSEIP_associated_user_private_ip (224.12s)
=== CONT  TestAccAWSEIPAssociation_ec2Classic
    ec2_classic_test.go:54: this test can only run in EC2-Classic, platforms available in us-east-1: ["VPC"]
--- SKIP: TestAccAWSEIPAssociation_ec2Classic (0.00s)
=== CONT  TestAccAWSEIPAssociation_spotInstance
--- PASS: TestAccAWSEIPAssociation_spotInstance (358.90s)
=== CONT  TestAccAWSEIPAssociation_basic
--- PASS: TestAccAWSEIPAssociation_basic (216.45s)
=== CONT  TestAccAWSEIPAssociation_networkInterface
--- PASS: TestAccAWSEIPAssociation_networkInterface (59.54s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1833.248s
```

With EC2 Classic account:

```
TF_ACC=1 go test ./aws -v -count 1 -parallel 1 -run=TestAccAWSEIP -timeout 180m               
=== RUN   TestAccAWSEIPAssociation_instance           
=== PAUSE TestAccAWSEIPAssociation_instance  
=== RUN   TestAccAWSEIPAssociation_networkInterface                                                                                              
=== PAUSE TestAccAWSEIPAssociation_networkInterface
=== RUN   TestAccAWSEIPAssociation_basic            
=== PAUSE TestAccAWSEIPAssociation_basic                    
=== RUN   TestAccAWSEIPAssociation_ec2Classic               
=== PAUSE TestAccAWSEIPAssociation_ec2Classic                                                                                                    
=== RUN   TestAccAWSEIPAssociation_spotInstance                                                                                                  
=== PAUSE TestAccAWSEIPAssociation_spotInstance
=== RUN   TestAccAWSEIPAssociation_disappears
=== PAUSE TestAccAWSEIPAssociation_disappears
=== RUN   TestAccAWSEIP_Ec2Classic
=== PAUSE TestAccAWSEIP_Ec2Classic
=== RUN   TestAccAWSEIP_basic
=== PAUSE TestAccAWSEIP_basic
=== RUN   TestAccAWSEIP_instance
=== PAUSE TestAccAWSEIP_instance
=== RUN   TestAccAWSEIP_networkInterface
=== PAUSE TestAccAWSEIP_networkInterface
=== RUN   TestAccAWSEIP_twoEIPsOneNetworkInterface
=== PAUSE TestAccAWSEIP_twoEIPsOneNetworkInterface
=== RUN   TestAccAWSEIP_associated_user_private_ip
=== PAUSE TestAccAWSEIP_associated_user_private_ip
=== RUN   TestAccAWSEIP_Instance_Reassociate
=== PAUSE TestAccAWSEIP_Instance_Reassociate
=== RUN   TestAccAWSEIP_disappears
=== PAUSE TestAccAWSEIP_disappears
=== RUN   TestAccAWSEIP_notAssociated
=== PAUSE TestAccAWSEIP_notAssociated
=== RUN   TestAccAWSEIP_tags_Vpc
=== PAUSE TestAccAWSEIP_tags_Vpc
=== RUN   TestAccAWSEIP_tags_Ec2Classic
=== PAUSE TestAccAWSEIP_tags_Ec2Classic
=== RUN   TestAccAWSEIP_PublicIpv4Pool_default
=== PAUSE TestAccAWSEIP_PublicIpv4Pool_default
=== RUN   TestAccAWSEIP_NetworkBorderGroup
=== PAUSE TestAccAWSEIP_NetworkBorderGroup
=== RUN   TestAccAWSEIP_CarrierIP
=== PAUSE TestAccAWSEIP_CarrierIP
=== RUN   TestAccAWSEIP_PublicIpv4Pool_custom
    resource_aws_eip_test.go:515: Environment variable AWS_EC2_EIP_PUBLIC_IPV4_POOL is not set
--- SKIP: TestAccAWSEIP_PublicIpv4Pool_custom (0.00s)
=== RUN   TestAccAWSEIP_CustomerOwnedIpv4Pool
=== PAUSE TestAccAWSEIP_CustomerOwnedIpv4Pool
=== CONT  TestAccAWSEIPAssociation_instance
--- PASS: TestAccAWSEIPAssociation_instance (58.99s)
=== CONT  TestAccAWSEIP_associated_user_private_ip
--- PASS: TestAccAWSEIP_associated_user_private_ip (217.24s)
=== CONT  TestAccAWSEIP_CustomerOwnedIpv4Pool
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSEIP_CustomerOwnedIpv4Pool (0.35s)
=== CONT  TestAccAWSEIP_CarrierIP
    resource_aws_ec2_carrier_gateway_test.go:249: skipping since no Wavelength Zones are available
--- SKIP: TestAccAWSEIP_CarrierIP (0.13s)
=== CONT  TestAccAWSEIP_NetworkBorderGroup
--- PASS: TestAccAWSEIP_NetworkBorderGroup (15.14s)
=== CONT  TestAccAWSEIP_PublicIpv4Pool_default
--- PASS: TestAccAWSEIP_PublicIpv4Pool_default (14.92s)
=== CONT  TestAccAWSEIP_tags_Ec2Classic
--- PASS: TestAccAWSEIP_tags_Ec2Classic (6.11s)
=== CONT  TestAccAWSEIP_tags_Vpc
--- PASS: TestAccAWSEIP_tags_Vpc (23.17s)
=== CONT  TestAccAWSEIP_notAssociated
--- PASS: TestAccAWSEIP_notAssociated (112.30s)
=== CONT  TestAccAWSEIP_disappears
--- PASS: TestAccAWSEIP_disappears (10.45s)
=== CONT  TestAccAWSEIP_Ec2Classic
--- PASS: TestAccAWSEIP_Ec2Classic (107.94s)
=== CONT  TestAccAWSEIP_twoEIPsOneNetworkInterface
--- PASS: TestAccAWSEIP_twoEIPsOneNetworkInterface (64.25s)
=== CONT  TestAccAWSEIP_networkInterface
--- PASS: TestAccAWSEIP_networkInterface (63.70s)
=== CONT  TestAccAWSEIP_instance
--- PASS: TestAccAWSEIP_instance (71.19s)
=== CONT  TestAccAWSEIP_basic
--- PASS: TestAccAWSEIP_basic (14.78s)
=== CONT  TestAccAWSEIPAssociation_ec2Classic
--- PASS: TestAccAWSEIPAssociation_ec2Classic (240.82s)
=== CONT  TestAccAWSEIPAssociation_disappears
--- PASS: TestAccAWSEIPAssociation_disappears (85.32s)
=== CONT  TestAccAWSEIPAssociation_spotInstance
--- PASS: TestAccAWSEIPAssociation_spotInstance (118.91s)
=== CONT  TestAccAWSEIP_Instance_Reassociate
--- PASS: TestAccAWSEIP_Instance_Reassociate (114.63s)
=== CONT  TestAccAWSEIPAssociation_basic
    provider_test.go:713: This test can only in regions without EC2 Classic, platforms available in us-west-1: ["EC2" "VPC"]
--- SKIP: TestAccAWSEIPAssociation_basic (0.00s)
=== CONT  TestAccAWSEIPAssociation_networkInterface
--- PASS: TestAccAWSEIPAssociation_networkInterface (59.81s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1400.242s
```

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

I ran tests in 4 environments with varying levels of EC2VPC, Classicness.

Acceptance tests in `us-west-2` (187) (EC2VPC & EC2Classic):
```
--- PASS: TestAccAWSEIP_basic (15.49s)
--- PASS: TestAccAWSEIP_carrierIP (19.02s)
--- PASS: TestAccAWSEIP_disappears (10.27s)
--- PASS: TestAccAWSEIP_Instance (75.28s)
--- PASS: TestAccAWSEIP_Instance_ec2Classic (105.01s)
--- PASS: TestAccAWSEIP_Instance_notAssociated (119.49s)
--- PASS: TestAccAWSEIP_Instance_reassociate (136.69s)
--- PASS: TestAccAWSEIP_networkBorderGroup (14.44s)
--- PASS: TestAccAWSEIP_NetworkInterface (75.25s)
--- PASS: TestAccAWSEIP_NetworkInterface_twoEIPsOneInterface (74.76s)
--- PASS: TestAccAWSEIP_PublicIPv4Pool_default (14.41s)
--- PASS: TestAccAWSEIP_Tags_EC2Classic_withoutVPCTrue (3.07s)
--- PASS: TestAccAWSEIP_Tags_EC2Classic_withVPCTrue (15.42s)
--- PASS: TestAccAWSEIP_Tags_EC2VPC_withoutVPCTrue (21.91s)
--- PASS: TestAccAWSEIP_Tags_EC2VPC_withVPCTrue (22.41s)
--- SKIP: TestAccAWSEIP_CustomerOwnedIPv4Pool (0.64s)
--- SKIP: TestAccAWSEIP_PublicIPv4Pool_custom (0.00s)
```

Acceptance tests in `us-west-2` (153) (EC2VPC):
```
--- PASS: TestAccAWSEIP_basic (17.51s)
--- PASS: TestAccAWSEIP_disappears (9.69s)
--- PASS: TestAccAWSEIP_Instance (87.05s)
--- PASS: TestAccAWSEIP_Instance_associatedUserPrivateIP (254.11s)
--- PASS: TestAccAWSEIP_Instance_notAssociated (127.85s)
--- PASS: TestAccAWSEIP_Instance_reassociate (141.58s)
--- PASS: TestAccAWSEIP_networkBorderGroup (14.70s)
--- PASS: TestAccAWSEIP_NetworkInterface (73.95s)
--- PASS: TestAccAWSEIP_NetworkInterface_twoEIPsOneInterface (75.22s)
--- PASS: TestAccAWSEIP_PublicIPv4Pool_default (14.07s)
--- PASS: TestAccAWSEIP_Tags_EC2VPC_withoutVPCTrue (21.62s)
--- PASS: TestAccAWSEIP_Tags_EC2VPC_withVPCTrue (23.98s)
--- SKIP: TestAccAWSEIP_carrierIP (0.36s)
--- SKIP: TestAccAWSEIP_CustomerOwnedIPv4Pool (0.61s)
--- SKIP: TestAccAWSEIP_Instance_ec2Classic (0.00s)
--- SKIP: TestAccAWSEIP_PublicIPv4Pool_custom (0.00s)
--- SKIP: TestAccAWSEIP_Tags_EC2Classic_withoutVPCTrue (0.41s)
--- SKIP: TestAccAWSEIP_Tags_EC2Classic_withVPCTrue (0.00s)
```

Acceptance tests in `us-east-1` (187) (EC2Classic):
```

--- PASS: TestAccAWSEIP_basic (10.29s)
--- PASS: TestAccAWSEIP_carrierIP (11.19s)
--- PASS: TestAccAWSEIP_disappears (7.13s)
--- PASS: TestAccAWSEIP_Instance (68.33s)
--- PASS: TestAccAWSEIP_Instance_associatedUserPrivateIP (250.69s)
--- PASS: TestAccAWSEIP_Instance_ec2Classic (236.33s)
--- PASS: TestAccAWSEIP_Instance_notAssociated (118.52s)
--- PASS: TestAccAWSEIP_Instance_reassociate (143.94s)
--- PASS: TestAccAWSEIP_networkBorderGroup (9.74s)
--- PASS: TestAccAWSEIP_NetworkInterface (60.48s)
--- PASS: TestAccAWSEIP_NetworkInterface_twoEIPsOneInterface (59.32s)
--- PASS: TestAccAWSEIP_PublicIPv4Pool_default (9.81s)
--- PASS: TestAccAWSEIP_Tags_EC2Classic_withoutVPCTrue (2.69s)
--- PASS: TestAccAWSEIP_Tags_EC2Classic_withVPCTrue (15.09s)
--- SKIP: TestAccAWSEIP_CustomerOwnedIPv4Pool (0.33s)
--- SKIP: TestAccAWSEIP_PublicIPv4Pool_custom (0.00s)
--- SKIP: TestAccAWSEIP_Tags_EC2VPC_withoutVPCTrue (0.00s)
--- SKIP: TestAccAWSEIP_Tags_EC2VPC_withVPCTrue (0.52s)
```

Acceptance tests in GovCloud (EC2VPC):
```

--- PASS: TestAccAWSEIP_basic (19.27s)
--- PASS: TestAccAWSEIP_disappears (12.02s)
--- PASS: TestAccAWSEIP_Instance (96.93s)
--- PASS: TestAccAWSEIP_Instance_associatedUserPrivateIP (210.48s)
--- PASS: TestAccAWSEIP_Instance_notAssociated (117.47s)
--- PASS: TestAccAWSEIP_Instance_reassociate (158.41s)
--- PASS: TestAccAWSEIP_networkBorderGroup (17.91s)
--- PASS: TestAccAWSEIP_NetworkInterface (76.14s)
--- PASS: TestAccAWSEIP_NetworkInterface_twoEIPsOneInterface (76.64s)
--- PASS: TestAccAWSEIP_PublicIPv4Pool_default (17.88s)
--- PASS: TestAccAWSEIP_Tags_EC2VPC_withoutVPCTrue (27.81s)
--- PASS: TestAccAWSEIP_Tags_EC2VPC_withVPCTrue (28.55s)
--- SKIP: TestAccAWSEIP_carrierIP (0.35s)
--- SKIP: TestAccAWSEIP_CustomerOwnedIPv4Pool (1.91s)
--- SKIP: TestAccAWSEIP_Instance_ec2Classic (0.00s)
--- SKIP: TestAccAWSEIP_PublicIPv4Pool_custom (0.00s)
--- SKIP: TestAccAWSEIP_Tags_EC2Classic_withoutVPCTrue (1.00s)
--- SKIP: TestAccAWSEIP_Tags_EC2Classic_withVPCTrue (0.48s)
```

**Pull request merged**
