### PR TITLE
Fix RDS instance bug where switching to IO2 from GP needs the allocated storage set

### LINKED ISSUE #36648: [Bug]: Changing to IO2 storage on RDS instance fails
### Terraform Core Version

1.4.6

### AWS Provider Version

5.40.0

### Affected Resource(s)

* resource/aws_db_instance

### Expected Behavior

We should be able to switch from gp3 with provisioned iops to io2 without changing the allocated storage

### Actual Behavior

When changing from gp3 to io2, AWS expects the allocated storage to be passed. Because this value didn't change however, the call to the AWS API excludes the allocated storage value and produces the error

```
│ Error: updating RDS DB Instance (<database-name>): operation error RDS: ModifyDBInstance, https response error StatusCode: 400, RequestID: <request-id>, api error InvalidParameterCombination: You must specify both the storage size and iops when modifying the storage size or iops on a DB instance that has iops.
```

Creating a new database with io2 works however because it's a new value that Terraform passes to the API

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```
data "aws_rds_orderable_db_instance" "custom-sqlserver" {
  engine                     = "custom-sqlserver-se"
  engine_version             = "15.00.4249.2.v1"
  storage_type               = "gp3"
  preferred_instance_classes = ["db.r5.xlarge", "db.r5.2xlarge", "db.r5.4xlarge"]
}

# The RDS instance resource requires an ARN. Look up the ARN of the KMS key.
data "aws_kms_key" "by_id" {
  key_id = "example-ef278353ceba4a5a97de6784565b9f78" # KMS key
}

resource "aws_db_instance" "example" {
  allocated_storage                     = 500
  auto_minor_version_upgrade  = false
  custom_iam_instance_profile = "AWSRDSCustomSQLServerInstanceProfile"
  backup_retention_period        = 7
  db_subnet_group_name          = local.db_subnet_group_name # Copy the subnet group from the RDS Console
  engine                                        = data.aws_rds_orderable_db_instance.custom-sqlserver.engine
  engine_version                          = data.aws_rds_orderable_db_instance.custom-sqlserver.engine_version
  identifier                                     = "sql-instance-demo"
  instance_class                           = data.aws_rds_orderable_db_instance.custom-sqlserver.instance_class
  kms_key_id                                = data.aws_kms_key.by_id.arn
  multi_az                                      = false # Custom for SQL Server does support multi-az
  password                                    = "avoid-plaintext-passwords"
  storage_encrypted                    = true
  storage_type.                             = "gp3"
  username                                    = "test"

  timeouts {
    create = "3h"
    delete = "3h"
    update = "3h"
  }
}
```

### Steps to Reproduce

Create an RDS instance with gp3, then change only the storage type from gp3 to io2

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by nhenjes**
### Description
When creating an RDS instance, the Allocated Storage param is passed correctly to AWS. When going from, for example, GP3 to IO2 on an existing instance only a change in the Storage Type is detected by the provider and only Storage Type is passed. AWS' API however, requires that both storage type and Allocated Storage are submitted as part of the request

### Relations

Closes #36648.
Relates (closes?) https://github.com/hashicorp/terraform-provider-aws/issues/28589.

### References
When running `aws rds modify-db-instance --db-instance-identifier <db-name> --storage-type io2 --iops 3000` the following error is thrown

```
An error occurred (InvalidParameterCombination) when calling the ModifyDBInstance operation: You must specify both the storage size and iops when modifying the storage size or iops on a DB instance that has iops.
```

When running `aws rds modify-db-instance --db-instance-identifier <db-name> --storage-type io2 --iops 3000 --allocated-storage 100`

The result is a successful change

Subsequent runs with the same params result in success meaning passing the allocated storage again is perfectly fine

### Output from Acceptance Testing
```bash
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops'  -timeout 360m
=== RUN   TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops
=== PAUSE TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops
=== CONT  TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops
--- PASS: TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops (970.05s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	976.063s
```

### CODE REVIEW

**Comment by DrFaust92** [comment]
[nhenjes](https://github.com/nhenjes) Thank you for your contribution, can you also add a test for this?

**Comment by nhenjes** [comment]
@DrFaust92 I can work on writing a test for this

**Comment by nhenjes** [comment]
I was able to get my test working properly now. The test will provision a cluster using GP3 at 400GB with 12000 provisioned IOPs then updates to IO2 successfully

**Review by YakDriver — APPROVED** [review]
Looks good 🎉 

```
% make t T=TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops K=rds
make: go1.23.3 not found
make: installing go1.23.3...
make: if you get an error, see https://go.dev/doc/manage-install to locally install various Go versions
go: downloading golang.org/dl v0.0.0-20241106222207-4e0968199959
Downloaded   0.0% (   16384 / 71639942 bytes) ...
Downloaded  17.8% (12763072 / 71639942 bytes) ...
Downloaded 100.0% (71639942 / 71639942 bytes)
Unpacking /Users/dirk/sdk/go1.23.3/go1.23.3.darwin-arm64.tar.gz ...
Success. You may now run 'go1.23.3'
make: go1.23.3 ready
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops'  -timeout 360m
go: downloading github.com/aws/aws-sdk-go-v2/service/apigateway v1.28.0
go: downloading github.com/aws/aws-sdk-go-v2/service/applicationautoscaling v1.34.0
go: downloading github.com/aws/aws-sdk-go-v2/service/appsync v1.40.0
go: downloading github.com/aws/aws-sdk-go-v2/service/cloudfront v1.43.0
go: downloading github.com/aws/aws-sdk-go-v2/service/cloudtrail v1.46.0
go: downloading github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs v1.44.0
go: downloading github.com/aws/aws-sdk-go-v2/service/costexplorer v1.44.0
go: downloading github.com/aws/aws-sdk-go-v2/service/dlm v1.28.7
go: downloading github.com/aws/aws-sdk-go-v2/service/ec2 v1.193.0
go: downloading github.com/aws/aws-sdk-go-v2/service/elasticache v1.44.0
go: downloading github.com/aws/aws-sdk-go-v2/service/elasticloadbalancingv2 v1.42.1
go: downloading github.com/aws/aws-sdk-go-v2/service/iot v1.61.0
go: downloading github.com/aws/aws-sdk-go-v2/service/lambda v1.68.0
go: downloading github.com/aws/aws-sdk-go-v2/service/polly v1.45.7
go: downloading github.com/aws/aws-sdk-go-v2/service/resiliencehub v1.28.0
go: downloading github.com/aws/aws-sdk-go-v2/service/s3 v1.68.0
go: downloading github.com/aws/aws-sdk-go-v2/service/ssm v1.56.0
go: downloading github.com/aws/aws-sdk-go-v2/service/ssmquicksetup v1.3.0
go: downloading github.com/aws/aws-sdk-go-v2/service/xray v1.30.0
go: downloading github.com/aws/aws-sdk-go-v2/feature/s3/manager v1.17.40
2024/11/22 09:58:11 Initializing Terraform AWS Provider...
=== RUN   TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops
=== PAUSE TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops
=== CONT  TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops
--- PASS: TestAccRDSCluster_storageTypeGeneralPurposeToProvisionedIops (1084.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	1088.267s
```

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀

**Pull request merged**
