### PR TITLE
[Enhancement] Add NO_ENCAP support to aws_networkmanager_connect_attachment

### LINKED ISSUE #34101: AWS Cloud WAN Tunnel-less connect
> Today AWS announces Tunnel-less connect, a new feature of AWS Cloud WAN that provides you with a simple and more performant way to build global SD-WAN (Software Defined Wide Area Network).

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2023/10/aws-cloud-wan-tunnel-less-high-performant-global-sd-wans/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/build-global-sd-wans-with-aws-cloud-wan-tunnel-less-connect/)

Requires [AWS SDK for Go v1.46.2](https://github.com/aws/aws-sdk-go/releases/tag/v1.46.2), https://github.com/hashicorp/terraform-provider-aws/pull/34078.

Affected resources:

* [`aws_networkmanager_connect_peer`](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/networkmanager_connect_peer)

### PR DESCRIPTION
**Pull request by ddericco**
### Description
- `aws_networkmanager_connect_attachment`: Add support for the `NO_ENCAP` protocol option required for tunnel-less connect.
- `aws_networkmanager_connect_peer`: Add `subnet_arn` attribute to support tunnel-less Connect attachments
- `aws_networkmanager_connect_peer`: Mark `inside_cidr_blocks` argument as optional to support tunnel-less Connect attachments

This also updates the existing acceptance tests to check for the protocol type.

### Relations

Closes #34101

### References

Launch announcement: https://aws.amazon.com/about-aws/whats-new/2023/10/aws-cloud-wan-tunnel-less-high-performant-global-sd-wans/
API reference: https://docs.aws.amazon.com/networkmanager/latest/APIReference/API_ConnectAttachmentOptions.html#networkmanager-Type-ConnectAttachmentOptions-Protocol

### Output from Acceptance Testing

```console
$ make testacc TESTS='TestAccNetworkManagerConnectAttachment_' PKG=networkmanager 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 20 -run='TestAccNetworkManagerConnectAttachment_'  -timeout 360m
=== RUN   TestAccNetworkManagerConnectAttachment_basic
=== PAUSE TestAccNetworkManagerConnectAttachment_basic
=== RUN   TestAccNetworkManagerConnectAttachment_basic_NoDependsOn
=== PAUSE TestAccNetworkManagerConnectAttachment_basic_NoDependsOn
=== RUN   TestAccNetworkManagerConnectAttachment_disappears
=== PAUSE TestAccNetworkManagerConnectAttachment_disappears
=== RUN   TestAccNetworkManagerConnectAttachment_protocolNoEncap
=== PAUSE TestAccNetworkManagerConnectAttachment_protocolNoEncap
=== RUN   TestAccNetworkManagerConnectAttachment_tags
=== PAUSE TestAccNetworkManagerConnectAttachment_tags
=== CONT  TestAccNetworkManagerConnectAttachment_basic
=== CONT  TestAccNetworkManagerConnectAttachment_protocolNoEncap
=== CONT  TestAccNetworkManagerConnectAttachment_tags
=== CONT  TestAccNetworkManagerConnectAttachment_disappears
=== CONT  TestAccNetworkManagerConnectAttachment_basic_NoDependsOn
--- PASS: TestAccNetworkManagerConnectAttachment_tags (1055.17s)
--- PASS: TestAccNetworkManagerConnectAttachment_protocolNoEncap (1132.04s)
--- PASS: TestAccNetworkManagerConnectAttachment_basic_NoDependsOn (1171.50s)
--- PASS: TestAccNetworkManagerConnectAttachment_basic (1199.77s)
--- PASS: TestAccNetworkManagerConnectAttachment_disappears (1241.14s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager     1246.530s

$ make testacc TESTS='TestAccNetworkManagerConnectPeer_' PKG=networkmanager ACCTEST_PARALLELISM=4 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 4 -run='TestAccNetworkManagerConnectPeer_'  -timeout 360m
=== RUN   TestAccNetworkManagerConnectPeer_basic
=== PAUSE TestAccNetworkManagerConnectPeer_basic
=== RUN   TestAccNetworkManagerConnectPeer_noDependsOn
=== PAUSE TestAccNetworkManagerConnectPeer_noDependsOn
=== RUN   TestAccNetworkManagerConnectPeer_subnetArn
=== PAUSE TestAccNetworkManagerConnectPeer_subnetArn
=== RUN   TestAccNetworkManagerConnectPeer_tags
=== PAUSE TestAccNetworkManagerConnectPeer_tags
=== CONT  TestAccNetworkManagerConnectPeer_basic
=== CONT  TestAccNetworkManagerConnectPeer_subnetArn
=== CONT  TestAccNetworkManagerConnectPeer_noDependsOn
=== CONT  TestAccNetworkManagerConnectPeer_tags
--- PASS: TestAccNetworkManagerConnectPeer_basic (1461.53s)
--- PASS: TestAccNetworkManagerConnectPeer_tags (1483.78s)
--- PASS: TestAccNetworkManagerConnectPeer_noDependsOn (1515.02s)
--- PASS: TestAccNetworkManagerConnectPeer_subnetArn (1522.34s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager     1525.729s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@ddericco Thanks for the contribution :tada: :clap:.
To close #34101 we will need to add `subnet_arn` to `aws_networkmanager_connect_peer` -- https://docs.aws.amazon.com/networkmanager/latest/APIReference/API_CreateConnectPeer.html#networkmanager-CreateConnectPeer-request-SubnetArn.

**Comment by ddericco** [comment]
@ewbankkit good catch - will work on including that in this PR

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% ACCTEST_TIMEOUT=720m make testacc TESTARGS='-run=TestAccNetworkManagerConnectAttachment_\|TestAccNetworkManagerConnectPeer_' PKG=networkmanager ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/networkmanager/... -v -count 1 -parallel 2  -run=TestAccNetworkManagerConnectAttachment_\|TestAccNetworkManagerConnectPeer_ -timeout 720m
=== RUN   TestAccNetworkManagerConnectAttachment_basic
=== PAUSE TestAccNetworkManagerConnectAttachment_basic
=== RUN   TestAccNetworkManagerConnectAttachment_basic_NoDependsOn
=== PAUSE TestAccNetworkManagerConnectAttachment_basic_NoDependsOn
=== RUN   TestAccNetworkManagerConnectAttachment_disappears
=== PAUSE TestAccNetworkManagerConnectAttachment_disappears
=== RUN   TestAccNetworkManagerConnectAttachment_protocolNoEncap
=== PAUSE TestAccNetworkManagerConnectAttachment_protocolNoEncap
=== RUN   TestAccNetworkManagerConnectAttachment_tags
=== PAUSE TestAccNetworkManagerConnectAttachment_tags
=== RUN   TestAccNetworkManagerConnectPeer_basic
=== PAUSE TestAccNetworkManagerConnectPeer_basic
=== RUN   TestAccNetworkManagerConnectPeer_noDependsOn
=== PAUSE TestAccNetworkManagerConnectPeer_noDependsOn
=== RUN   TestAccNetworkManagerConnectPeer_subnetARN
=== PAUSE TestAccNetworkManagerConnectPeer_subnetARN
=== RUN   TestAccNetworkManagerConnectPeer_tags
=== PAUSE TestAccNetworkManagerConnectPeer_tags
=== CONT  TestAccNetworkManagerConnectAttachment_basic
=== CONT  TestAccNetworkManagerConnectPeer_basic
--- PASS: TestAccNetworkManagerConnectAttachment_basic (1199.16s)
=== CONT  TestAccNetworkManagerConnectPeer_subnetARN
--- PASS: TestAccNetworkManagerConnectPeer_basic (1396.01s)
=== CONT  TestAccNetworkManagerConnectPeer_tags
--- PASS: TestAccNetworkManagerConnectPeer_subnetARN (1564.75s)
=== CONT  TestAccNetworkManagerConnectAttachment_protocolNoEncap
--- PASS: TestAccNetworkManagerConnectPeer_tags (1403.90s)
=== CONT  TestAccNetworkManagerConnectAttachment_tags
--- PASS: TestAccNetworkManagerConnectAttachment_tags (1017.96s)
=== CONT  TestAccNetworkManagerConnectAttachment_disappears
--- PASS: TestAccNetworkManagerConnectAttachment_protocolNoEncap (1079.16s)
=== CONT  TestAccNetworkManagerConnectPeer_noDependsOn
--- PASS: TestAccNetworkManagerConnectAttachment_disappears (1126.20s)
=== CONT  TestAccNetworkManagerConnectAttachment_basic_NoDependsOn
--- PASS: TestAccNetworkManagerConnectPeer_noDependsOn (1450.98s)
--- PASS: TestAccNetworkManagerConnectAttachment_basic_NoDependsOn (953.73s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/networkmanager	5903.443s
```

**Comment by ewbankkit** [comment]
@ddericco Thanks for the contribution :tada: :clap:.

**Pull request merged**
