### PR TITLE
r/aws_vpc_endpoint: Fix `private_dns_enabled` when `false` or undefined

### LINKED ISSUE #37694: [Bug]: `aws_vpc_endpoint` resource: `private_dns_enabled` effectively stuck on `true`.
### Terraform Core Version

1.8.4

### AWS Provider Version

5.51.0, 5.51.1

### Affected Resource(s)

* `aws_vpc_endpoint`

### Expected Behavior

The `aws_vpc_endpoint.private_dns_enabled` attribute should be respected, i.e. setting to `false` (or leaving undefined) should not attempt to create Route 53 resources.

### Actual Behavior

Regardless of whether the `aws_vpc_endpoint.private_dns_enabled` attribute is set to `true` / `false` / undefined, it always attempts to create Route 53 resources.

### Relevant Error/Panic Output Snippet

_No response_

### Terraform Configuration Files

```tf
# variables.tf
variable "vpce_service_name" {
 type = string
}

# vpc.tf
resource "aws_vpc" "this" {
  cidr_block = "10.0.0.0/16"
}

# vpc_endpoint.tf
resource "aws_vpc_endpoint" "this" {
  service_name = var.vpce_service_name
  vpc_id       = aws_vpc.this.id

  vpc_endpoint_type = "Interface"
}
```

Optionally:

```tf
# route53.tf
resource "aws_route53_zone" "this" {
  name = join(".", reverse(split(".", aws_vpc_endpoint.this.service_name)))

  vpc {
    vpc_id = aws_vpc_endpoint.this.vpc_id
  }
}
```

### Steps to Reproduce

Apply the above configuration with an arbitrary (unused) AWS VPC endpoint name, e.g.

```sh
terraform init
terraform apply -var "vpce_service_name=com.amazonaws.eu-west-2.iot.fleethub.api"
```

### Debug Output

When executing the above configuration as-is, it produces the following error:

```sh
╷
│ Error: creating EC2 VPC Endpoint (com.amazonaws.eu-west-2.iot.fleethub.api): operation error EC2: CreateVpcEndpoint, https response error StatusCode: 400, RequestID: <abcdef>, api error InvalidParameter: Enabling private DNS requires both enableDnsSupport and enableDnsHostnames VPC attributes set to true for vpc-<id>
│ 
│   with aws_vpc_endpoint.this,
│   on vpc_endpoint.tf line 1, in resource "aws_vpc_endpoint" "this":
│    1: resource "aws_vpc_endpoint" "this" {
│ 
╵
```

This error is unexpected, because enabling DNS for the VPC should not be required.

For science / completeness, one can additionally configure `aws_vpc.enable_dns_hostnames = true` and `aws_vpc.enable_dns_support = true` and re-run from scratch (e.g. using `terraform test`) to produce the subsequent error:

```sh
╷
│ Error: creating Route53 Hosted Zone (api.fleethub.iot.eu-west-2.amazonaws.com): operation error Route 53: CreateHostedZone, https response error StatusCode: 400, RequestID: <abcdef>, ConflictingDomainExists: The VPC vpc-<id> in region eu-west-2 has already been associated with the hosted zone <zone-id> with the same domain name.
│ 
│   with aws_route53_zone.this,
│   on route53.tf line 1, in resource "aws_route53_zone" "this":
│    1: resource "aws_route53_zone" "this" {
│ 
╵
```

which is still unexpected, because private DNS for the VPC endpoint was not requested.

### Panic Output

_No response_

### Important Factoids

Seems to be a regression with `hashicorp/aws:5.51.0`, because reverting to `5.50.0` does not have this problem. I've also reproduced the problem with `5.51.1` in the last few minutes, just in case. 🙂 

I initially encountered the `aws_route53_zone` error described above, which is why I've included it in the issue description. It was only after further investigation that I realised it is probably unrelated to `aws_route53_zone` and instead related to `aws_vpc_endpoint`.

### References

_No response_

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by theipster**
### Description

The [API documentation for the `CreateVpcEndpoint` operation](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateVpcEndpoint.html) documents that the `PrivateDnsEnabled` attribute defaults to `true`, whereas this TF provider's `aws_vpc_endpoint` resource's `private_dns_enabled` attribute defaults to `false` (at least, prior to bug).

This means that if the user wants the attribute to be `false` (either by explicitly configuring `private_dns_enabled = false` or leaving `private_dns_enabled` undefined), then the `aws_vpc_endpoint` resource implementation must _explicitly_ pass `PrivateDnsEnabled = false` in the SDK call.

#### Notes

Appreciate there's a recently introduced resource `aws_vpc_endpoint_private_dns`, which is designed to take precedence over `aws_vpc_endpoint.private_dns_enabled`, and if used in conjunction with this fix will cause drift (if `aws_vpc_endpoint.private_dns_enabled` is undefined, then one-off drift; if defined and not equal to the `aws_vpc_endpoint_private_dns.private_dns_enabled`, then perpetual drift).

However, introducing some drift is still preferable than a regression / breaking change, which is the case without this fix. Furthermore, the [documentation for `aws_vpc_endpoint_private_dns`](https://github.com/hashicorp/terraform-provider-aws/blob/main/website/docs/r/vpc_endpoint_private_dns.html.markdown) sufficiently documents and discourages this conflicting usage.

### Relations

Closes #37694

### Output from Acceptance Testing

```console
$ make testacc PKG=ec2 TESTS="TestAccVPCEndpoint_|TestAccVPCEndpointPrivateDNS_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpoint_|TestAccVPCEndpointPrivateDNS_'  -timeout 360m
=== RUN   TestAccVPCEndpointPrivateDNS_basic
=== PAUSE TestAccVPCEndpointPrivateDNS_basic
=== RUN   TestAccVPCEndpointPrivateDNS_disabled
=== PAUSE TestAccVPCEndpointPrivateDNS_disabled
=== RUN   TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== PAUSE TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== RUN   TestAccVPCEndpointPrivateDNS_update
=== PAUSE TestAccVPCEndpointPrivateDNS_update
=== RUN   TestAccVPCEndpoint_gatewayBasic
=== PAUSE TestAccVPCEndpoint_gatewayBasic
=== RUN   TestAccVPCEndpoint_interfaceBasic
=== PAUSE TestAccVPCEndpoint_interfaceBasic
=== RUN   TestAccVPCEndpoint_interfaceNoPrivateDNS
=== PAUSE TestAccVPCEndpoint_interfaceNoPrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNS
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== RUN   TestAccVPCEndpoint_disappears
=== PAUSE TestAccVPCEndpoint_disappears
=== RUN   TestAccVPCEndpoint_tags
=== PAUSE TestAccVPCEndpoint_tags
=== RUN   TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== PAUSE TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== RUN   TestAccVPCEndpoint_gatewayPolicy
=== PAUSE TestAccVPCEndpoint_gatewayPolicy
=== RUN   TestAccVPCEndpoint_ignoreEquivalent
=== PAUSE TestAccVPCEndpoint_ignoreEquivalent
=== RUN   TestAccVPCEndpoint_ipAddressType
=== PAUSE TestAccVPCEndpoint_ipAddressType
=== RUN   TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== PAUSE TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== RUN   TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== PAUSE TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== CONT  TestAccVPCEndpoint_gatewayBasic
=== CONT  TestAccVPCEndpoint_gatewayPolicy
=== CONT  TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== CONT  TestAccVPCEndpointPrivateDNS_basic
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== CONT  TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== CONT  TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== CONT  TestAccVPCEndpoint_ipAddressType
=== CONT  TestAccVPCEndpoint_ignoreEquivalent
=== CONT  TestAccVPCEndpointPrivateDNS_disabled
=== CONT  TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== CONT  TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== CONT  TestAccVPCEndpoint_tags
=== CONT  TestAccVPCEndpointPrivateDNS_update
=== CONT  TestAccVPCEndpoint_disappears
=== CONT  TestAccVPCEndpoint_interfaceNoPrivateDNS
=== CONT  TestAccVPCEndpoint_interfacePrivateDNS
=== CONT  TestAccVPCEndpoint_interfaceBasic
--- PASS: TestAccVPCEndpoint_disappears (145.69s)
--- PASS: TestAccVPCEndpointPrivateDNS_disabled (147.63s)
--- PASS: TestAccVPCEndpointPrivateDNS_disappears_Endpoint (150.40s)
--- PASS: TestAccVPCEndpoint_gatewayBasic (172.73s)
--- PASS: TestAccVPCEndpoint_ignoreEquivalent (177.60s)
--- PASS: TestAccVPCEndpointPrivateDNS_update (195.54s)
--- PASS: TestAccVPCEndpointPrivateDNS_basic (199.09s)
--- PASS: TestAccVPCEndpoint_interfaceNoPrivateDNS (206.86s)
--- PASS: TestAccVPCEndpoint_interfaceBasic (209.75s)
--- PASS: TestAccVPCEndpoint_gatewayPolicy (215.74s)
--- PASS: TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy (221.40s)
--- PASS: TestAccVPCEndpoint_tags (224.66s)
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate (363.21s)
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate (368.18s)
--- PASS: TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer (417.41s)
--- PASS: TestAccVPCEndpoint_ipAddressType (429.22s)
--- PASS: TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup (463.90s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNSNoGateway (522.97s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNS (584.99s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        585.177s
```

### CODE REVIEW

**Comment by theipster** [comment]
Before taking this PR out of draft, I'm tempted to add an additional test for the explicit `private_dns_enabled = false` scenario.

**Comment by theipster** [comment]
New test:

```console
make testacc PKG=ec2 TESTS="TestAccVPCEndpoint_interfaceNoPrivateDNS"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpoint_interfaceNoPrivateDNS'  -timeout 360m
=== RUN   TestAccVPCEndpoint_interfaceNoPrivateDNS
=== PAUSE TestAccVPCEndpoint_interfaceNoPrivateDNS
=== CONT  TestAccVPCEndpoint_interfaceNoPrivateDNS
--- PASS: TestAccVPCEndpoint_interfaceNoPrivateDNS (131.97s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        132.434s
```

**Comment by theipster** [comment]
Further tests:

```console
$ make testacc PKG=ec2 TESTS="TestAccVPCEndpointPrivateDNS_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpointPrivateDNS_'  -timeout 360m
=== RUN   TestAccVPCEndpointPrivateDNS_basic
=== PAUSE TestAccVPCEndpointPrivateDNS_basic
=== RUN   TestAccVPCEndpointPrivateDNS_disabled
=== PAUSE TestAccVPCEndpointPrivateDNS_disabled
=== RUN   TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== PAUSE TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== RUN   TestAccVPCEndpointPrivateDNS_update
=== PAUSE TestAccVPCEndpointPrivateDNS_update
=== CONT  TestAccVPCEndpointPrivateDNS_basic
=== CONT  TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== CONT  TestAccVPCEndpointPrivateDNS_disabled
=== CONT  TestAccVPCEndpointPrivateDNS_update
--- PASS: TestAccVPCEndpointPrivateDNS_disabled (91.20s)
--- PASS: TestAccVPCEndpointPrivateDNS_basic (171.95s)
--- PASS: TestAccVPCEndpointPrivateDNS_disappears_Endpoint (180.20s)
--- PASS: TestAccVPCEndpointPrivateDNS_update (219.22s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        219.365s
```

**Comment by theipster** [comment]
And for completeness, proving that the same tests are failing without the fix in place:

```console
$ make testacc PKG=ec2 TESTS="TestAccVPCEndpoint_|TestAccVPCEndpointPrivateDNS_"
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 20 -run='TestAccVPCEndpoint_|TestAccVPCEndpointPrivateDNS_'  -timeout 360m
=== RUN   TestAccVPCEndpointPrivateDNS_basic
=== PAUSE TestAccVPCEndpointPrivateDNS_basic
=== RUN   TestAccVPCEndpointPrivateDNS_disabled
=== PAUSE TestAccVPCEndpointPrivateDNS_disabled
=== RUN   TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== PAUSE TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== RUN   TestAccVPCEndpointPrivateDNS_update
=== PAUSE TestAccVPCEndpointPrivateDNS_update
=== RUN   TestAccVPCEndpoint_gatewayBasic
=== PAUSE TestAccVPCEndpoint_gatewayBasic
=== RUN   TestAccVPCEndpoint_interfaceBasic
=== PAUSE TestAccVPCEndpoint_interfaceBasic
=== RUN   TestAccVPCEndpoint_interfaceNoPrivateDNS
=== PAUSE TestAccVPCEndpoint_interfaceNoPrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNS
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== RUN   TestAccVPCEndpoint_disappears
=== PAUSE TestAccVPCEndpoint_disappears
=== RUN   TestAccVPCEndpoint_tags
=== PAUSE TestAccVPCEndpoint_tags
=== RUN   TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== PAUSE TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== RUN   TestAccVPCEndpoint_gatewayPolicy
=== PAUSE TestAccVPCEndpoint_gatewayPolicy
=== RUN   TestAccVPCEndpoint_ignoreEquivalent
=== PAUSE TestAccVPCEndpoint_ignoreEquivalent
=== RUN   TestAccVPCEndpoint_ipAddressType
=== PAUSE TestAccVPCEndpoint_ipAddressType
=== RUN   TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== PAUSE TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== RUN   TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== PAUSE TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== CONT  TestAccVPCEndpointPrivateDNS_basic
=== CONT  TestAccVPCEndpoint_tags
=== CONT  TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== CONT  TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== CONT  TestAccVPCEndpoint_ipAddressType
=== CONT  TestAccVPCEndpoint_ignoreEquivalent
=== CONT  TestAccVPCEndpoint_gatewayPolicy
=== CONT  TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== CONT  TestAccVPCEndpoint_interfaceBasic
=== CONT  TestAccVPCEndpoint_disappears
=== CONT  TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== CONT  TestAccVPCEndpoint_interfacePrivateDNS
=== CONT  TestAccVPCEndpoint_interfaceNoPrivateDNS
=== CONT  TestAccVPCEndpointPrivateDNS_update
=== CONT  TestAccVPCEndpoint_gatewayBasic
=== CONT  TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== CONT  TestAccVPCEndpointPrivateDNS_disabled
=== NAME  TestAccVPCEndpoint_interfaceNoPrivateDNS
    vpc_endpoint_test.go:116: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating EC2 VPC Endpoint (com.amazonaws.eu-west-1.ec2): operation error EC2: CreateVpcEndpoint, https response error StatusCode: 400, RequestID: 13e4610f-884b-4803-b7c8-c13a5db92fbc, api error InvalidParameter: Enabling private DNS requires both enableDnsSupport and enableDnsHostnames VPC attributes set to true for vpc-09a6058864bc29dee
        
          with aws_vpc_endpoint.test,
          on terraform_plugin_test.tf line 22, in resource "aws_vpc_endpoint" "test":
          22: resource "aws_vpc_endpoint" "test" {
        
=== NAME  TestAccVPCEndpoint_interfaceBasic
    vpc_endpoint_test.go:72: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating EC2 VPC Endpoint (com.amazonaws.eu-west-1.ec2): operation error EC2: CreateVpcEndpoint, https response error StatusCode: 400, RequestID: 690febc4-0bd3-4ec5-b9fb-3fc6e3ca99a6, api error InvalidParameter: Enabling private DNS requires both enableDnsSupport and enableDnsHostnames VPC attributes set to true for vpc-0fbaae57225283b9c
        
          with aws_vpc_endpoint.test,
          on terraform_plugin_test.tf line 22, in resource "aws_vpc_endpoint" "test":
          22: resource "aws_vpc_endpoint" "test" {
        
=== NAME  TestAccVPCEndpointPrivateDNS_disabled
    vpc_endpoint_private_dns_test.go:74: Step 1/2 error: Error running apply: exit status 1
        
        Error: creating EC2 VPC Endpoint (com.amazonaws.eu-west-1.ec2): operation error EC2: CreateVpcEndpoint, https response error StatusCode: 400, RequestID: 8811ef0e-0427-4e13-9cdd-06bfc8af3014, api error InvalidParameter: Enabling private DNS requires both enableDnsSupport and enableDnsHostnames VPC attributes set to true for vpc-0e429663f50dc9428
        
          with aws_vpc_endpoint.test,
          on terraform_plugin_test.tf line 22, in resource "aws_vpc_endpoint" "test":
          22: resource "aws_vpc_endpoint" "test" {
        
--- FAIL: TestAccVPCEndpoint_interfaceNoPrivateDNS (100.30s)
--- FAIL: TestAccVPCEndpoint_interfaceBasic (100.40s)
--- FAIL: TestAccVPCEndpointPrivateDNS_disabled (100.67s)
--- PASS: TestAccVPCEndpoint_disappears (168.03s)
--- PASS: TestAccVPCEndpoint_gatewayBasic (179.64s)
--- PASS: TestAccVPCEndpoint_ignoreEquivalent (199.34s)
=== NAME  TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
    vpc_endpoint_test.go:483: Step 1/3 error: After applying this test step, the non-refresh plan was not empty.
        stdout:
        
        
        Terraform used the selected providers to generate the following execution
        plan. Resource actions are indicated with the following symbols:
          ~ update in-place
        
        Terraform will perform the following actions:
        
          # aws_vpc_endpoint.test will be updated in-place
          ~ resource "aws_vpc_endpoint" "test" {
                id                    = "vpce-026ef09596ae5bef8"
              ~ private_dns_enabled   = true -> false
                tags                  = {
                    "Name" = "tf-acc-test-8479936531020150750"
                }
                # (16 unchanged attributes hidden)
        
                # (1 unchanged block hidden)
            }
        
        Plan: 0 to add, 1 to change, 0 to destroy.
--- PASS: TestAccVPCEndpointPrivateDNS_disappears_Endpoint (260.56s)
--- PASS: TestAccVPCEndpoint_gatewayPolicy (260.66s)
--- PASS: TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy (272.17s)
--- PASS: TestAccVPCEndpoint_tags (282.44s)
--- PASS: TestAccVPCEndpointPrivateDNS_basic (310.50s)
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate (341.61s)
--- PASS: TestAccVPCEndpointPrivateDNS_update (356.04s)
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate (394.39s)
--- FAIL: TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup (415.18s)
--- PASS: TestAccVPCEndpoint_ipAddressType (462.08s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNSNoGateway (482.52s)
--- PASS: TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer (487.79s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNS (612.36s)
FAIL
FAIL    github.com/hashicorp/terraform-provider-aws/internal/service/ec2        612.799s
FAIL
```

**Comment by theipster** [comment]
Hi, any news on this please? It's ready for review.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCEndpoint_\|TestAccVPCEndpointPrivateDNS_' PKG=ec2 ACCTEST_PARALLELISM=4
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/ec2/... -v -count 1 -parallel 4  -run=TestAccVPCEndpoint_\|TestAccVPCEndpointPrivateDNS_ -timeout 360m
=== RUN   TestAccVPCEndpointPrivateDNS_basic
=== PAUSE TestAccVPCEndpointPrivateDNS_basic
=== RUN   TestAccVPCEndpointPrivateDNS_disabled
=== PAUSE TestAccVPCEndpointPrivateDNS_disabled
=== RUN   TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== PAUSE TestAccVPCEndpointPrivateDNS_disappears_Endpoint
=== RUN   TestAccVPCEndpointPrivateDNS_update
=== PAUSE TestAccVPCEndpointPrivateDNS_update
=== RUN   TestAccVPCEndpoint_gatewayBasic
=== PAUSE TestAccVPCEndpoint_gatewayBasic
=== RUN   TestAccVPCEndpoint_interfaceBasic
=== PAUSE TestAccVPCEndpoint_interfaceBasic
=== RUN   TestAccVPCEndpoint_interfaceNoPrivateDNS
=== PAUSE TestAccVPCEndpoint_interfaceNoPrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNS
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNS
=== RUN   TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== PAUSE TestAccVPCEndpoint_interfacePrivateDNSNoGateway
=== RUN   TestAccVPCEndpoint_disappears
=== PAUSE TestAccVPCEndpoint_disappears
=== RUN   TestAccVPCEndpoint_tags
=== PAUSE TestAccVPCEndpoint_tags
=== RUN   TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== PAUSE TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
=== RUN   TestAccVPCEndpoint_gatewayPolicy
=== PAUSE TestAccVPCEndpoint_gatewayPolicy
=== RUN   TestAccVPCEndpoint_ignoreEquivalent
=== PAUSE TestAccVPCEndpoint_ignoreEquivalent
=== RUN   TestAccVPCEndpoint_ipAddressType
=== PAUSE TestAccVPCEndpoint_ipAddressType
=== RUN   TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== PAUSE TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
=== RUN   TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== PAUSE TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
=== RUN   TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== PAUSE TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== CONT  TestAccVPCEndpointPrivateDNS_basic
=== CONT  TestAccVPCEndpoint_tags
=== CONT  TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate
--- PASS: TestAccVPCEndpoint_tags (57.95s)
=== CONT  TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate
--- PASS: TestAccVPCEndpointPrivateDNS_basic (144.41s)
=== CONT  TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnUpdate (308.16s)
=== CONT  TestAccVPCEndpoint_ipAddressType
--- PASS: TestAccVPCEndpoint_interfaceNonAWSServiceAcceptOnCreate (272.29s)
=== CONT  TestAccVPCEndpoint_ignoreEquivalent
--- PASS: TestAccVPCEndpoint_VPCEndpointType_gatewayLoadBalancer (350.41s)
=== CONT  TestAccVPCEndpoint_gatewayPolicy
--- PASS: TestAccVPCEndpoint_ignoreEquivalent (33.30s)
=== CONT  TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy
--- PASS: TestAccVPCEndpoint_gatewayPolicy (48.18s)
=== CONT  TestAccVPCEndpoint_interfaceBasic
--- PASS: TestAccVPCEndpoint_gatewayWithRouteTableAndPolicy (47.18s)
=== CONT  TestAccVPCEndpoint_disappears
--- PASS: TestAccVPCEndpoint_disappears (25.61s)
=== CONT  TestAccVPCEndpoint_interfacePrivateDNSNoGateway
--- PASS: TestAccVPCEndpoint_interfaceBasic (43.60s)
=== CONT  TestAccVPCEndpoint_interfacePrivateDNS
--- PASS: TestAccVPCEndpoint_interfaceWithSubnetAndSecurityGroup (341.44s)
=== CONT  TestAccVPCEndpoint_interfaceNoPrivateDNS
--- PASS: TestAccVPCEndpoint_interfaceNoPrivateDNS (77.96s)
=== CONT  TestAccVPCEndpointPrivateDNS_update
--- PASS: TestAccVPCEndpoint_ipAddressType (318.50s)
=== CONT  TestAccVPCEndpoint_gatewayBasic
--- PASS: TestAccVPCEndpoint_gatewayBasic (28.01s)
=== CONT  TestAccVPCEndpointPrivateDNS_disappears_Endpoint
--- PASS: TestAccVPCEndpointPrivateDNS_update (202.70s)
=== CONT  TestAccVPCEndpointPrivateDNS_disabled
--- PASS: TestAccVPCEndpointPrivateDNS_disappears_Endpoint (127.90s)
--- PASS: TestAccVPCEndpointPrivateDNS_disabled (63.81s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNSNoGateway (464.42s)
--- PASS: TestAccVPCEndpoint_interfacePrivateDNS (478.17s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	925.199s
```

**Pull request merged**
