### PR TITLE
Private Registry Access for Lightsail container services

### LINKED ISSUE #27201: [Enhancement]: Lightsail add option to enable access to Amazon ECR private repositories
### Description

Lightsail Container Service can poll images from private ECR repositories. For this to work, two things need to happen:

1. activate the Amazon ECR image puller IAM role for your Lightsail container service
2. add a policy to a private ECR repository

see: https://lightsail.aws.amazon.com/ls/docs/en_us/articles/amazon-lightsail-container-service-ecr-private-repo-access

While I can do (2) using the `aws_ecr_repository_policy` resource, I haven't found anything in the `aws_lightsail_container_service` to accomplish (1).

### Affected Resource(s) and/or Data Source(s)

aws_lightsail_container_service

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

Adds Private Registry Access, see tagged issue for more information.

### Relations

Closes #27201

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccLightsailContainerService_ PKG=lightsail 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 20 -run='TestAccLightsailContainerService_'  -timeout 180m
=== RUN   TestAccLightsailContainerService_basic
=== PAUSE TestAccLightsailContainerService_basic
=== RUN   TestAccLightsailContainerService_disappears
=== PAUSE TestAccLightsailContainerService_disappears
=== RUN   TestAccLightsailContainerService_Name
=== PAUSE TestAccLightsailContainerService_Name
=== RUN   TestAccLightsailContainerService_IsDisabled
=== PAUSE TestAccLightsailContainerService_IsDisabled
=== RUN   TestAccLightsailContainerService_Power
=== PAUSE TestAccLightsailContainerService_Power
=== RUN   TestAccLightsailContainerService_PublicDomainNames
=== PAUSE TestAccLightsailContainerService_PublicDomainNames
=== RUN   TestAccLightsailContainerService_PrivateRegistryAccess
=== PAUSE TestAccLightsailContainerService_PrivateRegistryAccess
=== RUN   TestAccLightsailContainerService_Scale
=== PAUSE TestAccLightsailContainerService_Scale
=== RUN   TestAccLightsailContainerService_tags
=== PAUSE TestAccLightsailContainerService_tags
=== CONT  TestAccLightsailContainerService_basic
=== CONT  TestAccLightsailContainerService_PublicDomainNames
=== CONT  TestAccLightsailContainerService_Scale
=== CONT  TestAccLightsailContainerService_tags
=== CONT  TestAccLightsailContainerService_PrivateRegistryAccess
=== CONT  TestAccLightsailContainerService_IsDisabled
=== CONT  TestAccLightsailContainerService_Power
=== CONT  TestAccLightsailContainerService_Name
=== CONT  TestAccLightsailContainerService_disappears
--- PASS: TestAccLightsailContainerService_PublicDomainNames (13.47s)
--- PASS: TestAccLightsailContainerService_PrivateRegistryAccess (79.05s)
--- PASS: TestAccLightsailContainerService_disappears (94.44s)
--- PASS: TestAccLightsailContainerService_Scale (120.85s)
--- PASS: TestAccLightsailContainerService_basic (135.28s)
--- PASS: TestAccLightsailContainerService_tags (141.43s)
--- PASS: TestAccLightsailContainerService_Power (171.34s)
--- PASS: TestAccLightsailContainerService_IsDisabled (229.41s)
--- PASS: TestAccLightsailContainerService_Name (245.57s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/lightsail  247.315s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
Note to self; add computed attribute 'principalArn'

**Comment by bschaatsbergen** [comment]
Ready for review 🚀

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccLightsailContainerService_' PKG=lightsail ACCTEST_PARALLELISM=3
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/lightsail/... -v -count 1 -parallel 3  -run=TestAccLightsailContainerService_ -timeout 180m
=== RUN   TestAccLightsailContainerService_basic
=== PAUSE TestAccLightsailContainerService_basic
=== RUN   TestAccLightsailContainerService_disappears
=== PAUSE TestAccLightsailContainerService_disappears
=== RUN   TestAccLightsailContainerService_Name
=== PAUSE TestAccLightsailContainerService_Name
=== RUN   TestAccLightsailContainerService_IsDisabled
=== PAUSE TestAccLightsailContainerService_IsDisabled
=== RUN   TestAccLightsailContainerService_Power
=== PAUSE TestAccLightsailContainerService_Power
=== RUN   TestAccLightsailContainerService_PublicDomainNames
=== PAUSE TestAccLightsailContainerService_PublicDomainNames
=== RUN   TestAccLightsailContainerService_PrivateRegistryAccess
=== PAUSE TestAccLightsailContainerService_PrivateRegistryAccess
=== RUN   TestAccLightsailContainerService_Scale
=== PAUSE TestAccLightsailContainerService_Scale
=== RUN   TestAccLightsailContainerService_tags
=== PAUSE TestAccLightsailContainerService_tags
=== CONT  TestAccLightsailContainerService_basic
=== CONT  TestAccLightsailContainerService_PublicDomainNames
=== CONT  TestAccLightsailContainerService_IsDisabled
--- PASS: TestAccLightsailContainerService_PublicDomainNames (25.10s)
=== CONT  TestAccLightsailContainerService_Scale
--- PASS: TestAccLightsailContainerService_basic (130.00s)
=== CONT  TestAccLightsailContainerService_tags
--- PASS: TestAccLightsailContainerService_IsDisabled (132.57s)
=== CONT  TestAccLightsailContainerService_Name
--- PASS: TestAccLightsailContainerService_Scale (109.73s)
=== CONT  TestAccLightsailContainerService_PrivateRegistryAccess
--- PASS: TestAccLightsailContainerService_PrivateRegistryAccess (79.39s)
=== CONT  TestAccLightsailContainerService_disappears
--- PASS: TestAccLightsailContainerService_tags (111.10s)
=== CONT  TestAccLightsailContainerService_Power
--- PASS: TestAccLightsailContainerService_disappears (88.02s)
--- PASS: TestAccLightsailContainerService_Name (173.56s)
--- PASS: TestAccLightsailContainerService_Power (108.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/lightsail	353.149s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Pull request merged**
