### PR TITLE
r/aws_sqs_queue: append .fifo suffix for FIFO queue if name unspecified

### LINKED ISSUE #17005: aws_sqs_queue fifo queues with no name provided do not generate valid queue name.
When creating a fifo sqs queue resource without specifying a name or prefix, the generated name does not have the required `.fifo` suffix causing AWS to reject the queue creation.

The issue appears to be here: https://github.com/hashicorp/terraform-provider-aws/blob/master/aws/resource_aws_sqs_queue.go#L150

When using `name_prefix` the `.fifo` suffix will be appended but not when using a unique id.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v0.14.3
+ provider registry.terraform.io/hashicorp/aws v3.22.0
+ provider registry.terraform.io/hashicorp/null v3.0.0
+ provider registry.terraform.io/hashicorp/time v0.6.0
+ provider registry.terraform.io/phillbaker/elasticsearch v1.5.1
```

### Affected Resource(s)

* aws_sqs_queue

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    aws = {
      source = "hashicorp/aws"
      version = "3.22"
    }
  }
}

provider "aws" {
  region = "ap-southeast-2"
}

resource "aws_sqs_queue" "test_queue" {
  fifo_queue = true
}
```

### Debug Output

[Debug Log](https://gist.github.com/steven-schmoll-at/d3f2d933c1ea7010879aa00ce9463da9)

### Expected Behavior

The queue should have been created with a name such as `terraform-20210107023518303200000001.fifo`

### Actual Behavior

Creation was attempted with the name `terraform-20210107023518303200000001` which was rejected by the AWS API.

### Steps to Reproduce

Nothing fancy, just use the config above and apply

1. `terraform apply`

### Important Factoids

None

### PR DESCRIPTION
**Pull request by drexler**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17005

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
append .fifo suffix for FIFO queue if name unspecified
```

Output from acceptance testing:

```
 make testacc TEST=./aws TESTARGS='-run=TestAccAWSSQSQueue'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSSQSQueue -timeout 120m
=== RUN   TestAccAWSSQSQueuePolicy_basic
=== PAUSE TestAccAWSSQSQueuePolicy_basic
=== RUN   TestAccAWSSQSQueuePolicy_disappears_queue
=== PAUSE TestAccAWSSQSQueuePolicy_disappears_queue
=== RUN   TestAccAWSSQSQueuePolicy_disappears
=== PAUSE TestAccAWSSQSQueuePolicy_disappears
=== RUN   TestAccAWSSQSQueue_basic
=== PAUSE TestAccAWSSQSQueue_basic
=== RUN   TestAccAWSSQSQueue_tags
=== PAUSE TestAccAWSSQSQueue_tags
=== RUN   TestAccAWSSQSQueue_namePrefix
=== PAUSE TestAccAWSSQSQueue_namePrefix
=== RUN   TestAccAWSSQSQueue_namePrefix_fifo
=== PAUSE TestAccAWSSQSQueue_namePrefix_fifo
=== RUN   TestAccAWSSQSQueue_policy
=== PAUSE TestAccAWSSQSQueue_policy
=== RUN   TestAccAWSSQSQueue_queueDeletedRecently
=== PAUSE TestAccAWSSQSQueue_queueDeletedRecently
=== RUN   TestAccAWSSQSQueue_redrivePolicy
=== PAUSE TestAccAWSSQSQueue_redrivePolicy
=== RUN   TestAccAWSSQSQueue_Policybasic
=== PAUSE TestAccAWSSQSQueue_Policybasic
=== RUN   TestAccAWSSQSQueue_FIFO
=== PAUSE TestAccAWSSQSQueue_FIFO
=== RUN   TestAccAWSSQSQueue_FIFOExpectNameError
=== PAUSE TestAccAWSSQSQueue_FIFOExpectNameError
=== RUN   TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication
=== PAUSE TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication
=== RUN   TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError
=== PAUSE TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError
=== RUN   TestAccAWSSQSQueue_Encryption
=== PAUSE TestAccAWSSQSQueue_Encryption
=== RUN   TestAccAWSSQSQueue_FIFO_MinusName
=== PAUSE TestAccAWSSQSQueue_FIFO_MinusName
=== CONT  TestAccAWSSQSQueuePolicy_basic
=== CONT  TestAccAWSSQSQueue_redrivePolicy
=== CONT  TestAccAWSSQSQueuePolicy_disappears_queue
=== CONT  TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError
=== CONT  TestAccAWSSQSQueue_FIFOExpectNameError
=== CONT  TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication
=== CONT  TestAccAWSSQSQueue_FIFO_MinusName
=== CONT  TestAccAWSSQSQueue_Policybasic
=== CONT  TestAccAWSSQSQueue_Encryption
=== CONT  TestAccAWSSQSQueue_policy
=== CONT  TestAccAWSSQSQueue_FIFO
=== CONT  TestAccAWSSQSQueue_namePrefix
=== CONT  TestAccAWSSQSQueue_basic
=== CONT  TestAccAWSSQSQueue_queueDeletedRecently
=== CONT  TestAccAWSSQSQueue_namePrefix_fifo
=== CONT  TestAccAWSSQSQueuePolicy_disappears
=== CONT  TestAccAWSSQSQueue_tags
--- PASS: TestAccAWSSQSQueue_FIFOExpectNameError (11.06s)
--- PASS: TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError (11.85s)
--- PASS: TestAccAWSSQSQueuePolicy_disappears_queue (25.90s)
--- PASS: TestAccAWSSQSQueuePolicy_disappears (31.18s)
--- PASS: TestAccAWSSQSQueue_FIFO_MinusName (32.58s)
--- PASS: TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication (32.79s)
--- PASS: TestAccAWSSQSQueue_Encryption (33.02s)
--- PASS: TestAccAWSSQSQueue_FIFO (33.16s)
--- PASS: TestAccAWSSQSQueue_namePrefix_fifo (33.22s)
--- PASS: TestAccAWSSQSQueue_namePrefix (33.38s)
--- PASS: TestAccAWSSQSQueue_redrivePolicy (33.59s)
--- PASS: TestAccAWSSQSQueue_Policybasic (35.33s)
--- PASS: TestAccAWSSQSQueue_policy (35.86s)
--- PASS: TestAccAWSSQSQueuePolicy_basic (39.98s)
--- PASS: TestAccAWSSQSQueue_queueDeletedRecently (40.16s)
--- PASS: TestAccAWSSQSQueue_basic (50.78s)
--- PASS: TestAccAWSSQSQueue_tags (50.83s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       50.937s

...
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Should do something similar for SNS FIFO topics: https://github.com/hashicorp/terraform-provider-aws/pull/15828.
Suggest converting this code to use the name generation functionality in `aws/internal/naming/naming.go`: #15694.
Could add a new function `naming.GenerateWithSuffix(name, namePrefix, nameSuffix string)`.

**Comment by drexler** [comment]
> Should do something similar for SNS FIFO topics: #15828.
> Suggest converting this code to use the name generation functionality in `aws/internal/naming/naming.go`: #15694.
> Could add a new function `naming.GenerateWithSuffix(name, namePrefix, nameSuffix string)`.

@ewbankkit  Thanks. I'll update this PR with your suggestions. 👍

**Comment by ewbankkit** [comment]
@drexler Thanks for the contribution 👏.
I took the liberty of rebasing and making naming changes similar to those for SNS FIFO topics (#15828).

**Review by ewbankkit — APPROVED** [review]
LGTM.

#### Acceptance test output

##### Commercial

```
--- PASS: TestAccAWSSQSQueue_Encryption (14.77s)
--- PASS: TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError (1.72s)
--- PASS: TestAccAWSSNSTopic_basic (16.80s)
--- PASS: TestAccAWSSQSQueue_FIFOExpectNameError (1.63s)
--- PASS: TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication (11.88s)
--- PASS: TestAccAWSSQSQueue_FIFO (11.97s)
--- PASS: TestAccAWSSQSQueue_tags (33.93s)
--- PASS: TestAccAWSSNSTopic_Name_Generated_FIFOTopic (13.70s)
--- PASS: TestAccAWSSNSTopic_withIAMRole (23.54s)
--- PASS: TestAccAWSSQSQueue_basic (31.91s)
--- PASS: TestAccAWSSQSQueue_Policybasic (66.90s)
--- PASS: TestAccAWSSNSTopic_deliveryStatus (29.88s)
--- PASS: TestAccAWSSNSTopic_withDeliveryPolicy (14.34s)
--- PASS: TestAccAWSSNSTopic_FIFOExpectContentBasedDeduplicationError (1.65s)
--- PASS: TestAccAWSSNSTopic_tags (37.41s)
--- PASS: TestAccAWSSNSTopic_FIFOWithContentBasedDeduplication (25.47s)
--- PASS: TestAccAWSSQSQueue_queueDeletedRecently (18.44s)
--- PASS: TestAccAWSSQSQueue_redrivePolicy (14.43s)
--- PASS: TestAccAWSSNSTopic_NamePrefix_FIFOTopic (13.71s)
--- PASS: TestAccAWSSNSTopic_Name_FIFOTopic (15.97s)
--- PASS: TestAccAWSSNSTopic_encryption (27.08s)
--- PASS: TestAccAWSSQSQueue_NamePrefix_FIFOQueue (13.98s)
--- PASS: TestAccAWSSQSQueue_Name_Generated (12.38s)
--- PASS: TestAccAWSSNSTopic_NamePrefix (13.69s)
--- PASS: TestAccAWSSQSQueue_Name_Generated_FIFOQueue (11.91s)
--- PASS: TestAccAWSSNSTopic_policy (15.38s)
--- PASS: TestAccAWSSQSQueue_NamePrefix (12.08s)
--- PASS: TestAccAWSSNSTopic_Name (13.73s)
--- PASS: TestAccAWSSNSTopic_withFakeIAMRole (125.55s)
--- PASS: TestAccAWSSQSQueue_policy (64.10s)
```

##### GovCloud

```
--- PASS: TestAccAWSSQSQueue_ExpectContentBasedDeduplicationError (4.22s)
--- PASS: TestAccAWSSQSQueue_Encryption (18.32s)
--- PASS: TestAccAWSSQSQueue_FIFOWithContentBasedDeduplication (16.20s)
--- PASS: TestAccAWSSQSQueue_FIFOExpectNameError (2.13s)
--- PASS: TestAccAWSSNSTopic_basic (20.48s)
--- PASS: TestAccAWSSQSQueue_FIFO (16.64s)
--- PASS: TestAccAWSSQSQueue_redrivePolicy (20.01s)
--- PASS: TestAccAWSSQSQueue_tags (46.35s)
--- PASS: TestAccAWSSQSQueue_NamePrefix_FIFOQueue (15.91s)
--- PASS: TestAccAWSSQSQueue_queueDeletedRecently (27.00s)
--- PASS: TestAccAWSSQSQueue_NamePrefix (16.24s)
--- PASS: TestAccAWSSQSQueue_Name_Generated_FIFOQueue (16.26s)
--- FAIL: TestAccAWSSNSTopic_Name_Generated_FIFOTopic (4.01s)
--- PASS: TestAccAWSSQSQueue_Policybasic (71.18s)
--- PASS: TestAccAWSSQSQueue_Name_Generated (17.25s)
--- PASS: TestAccAWSSQSQueue_policy (69.93s)
--- FAIL: TestAccAWSSQSQueue_basic (27.75s)
--- PASS: TestAccAWSSNSTopic_FIFOExpectContentBasedDeduplicationError (2.24s)
--- FAIL: TestAccAWSSNSTopic_FIFOWithContentBasedDeduplication (4.09s) 
--- FAIL: TestAccAWSSNSTopic_NamePrefix_FIFOTopic (4.10s)
--- FAIL: TestAccAWSSNSTopic_Name_FIFOTopic (4.16s)
--- PASS: TestAccAWSSNSTopic_encryption (35.77s)
--- PASS: TestAccAWSSNSTopic_tags (50.52s)
--- PASS: TestAccAWSSNSTopic_withIAMRole (27.06s)
--- PASS: TestAccAWSSNSTopic_withDeliveryPolicy (18.96s)
--- PASS: TestAccAWSSNSTopic_deliveryStatus (33.81s)
--- PASS: TestAccAWSSNSTopic_NamePrefix (20.43s)
--- PASS: TestAccAWSSNSTopic_policy (21.95s)
--- PASS: TestAccAWSSNSTopic_Name (20.13s)
--- PASS: TestAccAWSSNSTopic_withFakeIAMRole (127.89s)
```

Failures are pre-existing.

**Comment by drexler** [comment]
@ewbankkit  Thanks for taking care of this. 👍

**Pull request merged**
