### PR TITLE
`route53profiles` - `r/association`, `r/resource_association` and `d/profiles` resources added

### LINKED ISSUE #37050: [New Service]: Route53 Profiles
### Description

With Route 53 Profiles, you can apply and manage DNS-related Route 53 configurations across many VPCs and in different AWS accounts. Profiles make managing the DNS settings for many VPCs as easy as managing them for a single VPC and when you update a Profile, its settings are propagated to all the VPCs associated to the Profile. You can also share a Profile with AWS accounts in the same Regions by using AWS RAM. (extracted from: https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/profiles.html)

### Requested Resource(s) and/or Data Source(s)

Resources:

- aws_route53profiles_profile -> Creates an empty route53 profile
- aws_route53profiles_resource_association -> Associates DNS FW rule, private hosted zones or resolver rules to the route53 profile
- aws_route53profiles_association -> Associates the Route53 profile to the VPC (at the moment only supports vpc's even tough the property is called ResourceId - so I'm a little bit dubious what should be named this resource)

Data Sources:

- aws_route53profiles_profile
- aws_route53profiles_association
- aws_route53profiles_resource_association

### Potential Terraform Configuration

```terraform
resource "aws_route53profiles_profile" "example" {
  name = "my-profile"
  tags = {}
}

resource "aws_route53profiles_resource_association" "dns_firewall_rule" {
  name                = "my-dns-firewall-rule"
  profile_id          = aws_route53profiles_profile.example.id
  resource_arn        = "arn:aws:route53resolver:us-east-1:123456789012:firewall-rule-group/rslvr-frg-cfe7f72example"
  resource_properties = "{\"priority\": 102}"
}

resource "aws_route53profiles_association" "example" {
  name        = "my-vpc-association"
  profile_id  = aws_route53profiles_profile.example.id
  resource_id = "vpc-0af3b96b3example"
  tags        = {}
}

data "aws_route53profiles_profile" "example" {
  profile_id = "rp-4987774726example"
}

data "aws_route53profiles_association" "example" {
  profile_association_id = "rpassoc-489ce212fexample"
}

data "aws_route53profiles_resource_association" "example" {
  profile_resource_association_id = "rpr-001913120a7example"
}
```

### References

https://docs.aws.amazon.com/Route53/latest/DeveloperGuide/profiles.html

Resources:

https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53profiles_CreateProfile.html (aws_route53profiles_profile)
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53profiles_AssociateResourceToProfile.html (aws_route53profiles_resource_association)
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53profiles_AssociateProfile.html (aws_route53profiles_association)

Data Sources:
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53profiles_GetProfile.html (aws_route53profiles_profile)
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53profiles_GetProfileAssociation.html (aws_route53profiles_association)
https://docs.aws.amazon.com/Route53/latest/APIReference/API_route53profiles_GetProfileResourceAssociation.html (aws_route53profiles_resource_association)

* [Announcement](https://aws.amazon.com/about-aws/whats-new/2024/04/amazon-route-53-profiles/)
* [Blog post](https://aws.amazon.com/blogs/aws/unify-dns-management-using-amazon-route-53-profiles-with-multiple-vpcs-and-aws-accounts/)
* [Blog post](https://aws.amazon.com/blogs/networking-and-content-delivery/using-amazon-route-53-profiles-for-scalable-multi-account-aws-environments/)

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by aristosvo**
### Description
Extra resources `aws_route53profiles_association` and `aws_route53profiles_resource_association` added on top of an open MR (https://github.com/hashicorp/terraform-provider-aws/pull/37124) for `aws_route53profiles_profile`. Besides that, added data source `aws_route53profiles_profiles` as profiles are shared via RAM with other accounts and lookup via the API is only possible via ID or as a list. Providing the ID to use the data source is more cumbersome than have a list showing all profiles on which you can filter client side (if necessary at all).

TODO:
- [x] sweeper
- [x] changelog
- [x] data source `aws_route53profiles_profiles` -> profiles are shared via RAM with other accounts, lookup via the API is only possible via ID or as a list. Providing the ID to use the data source is more cumbersome than filter a list client side based on one of its attributes (name?).
- [x] improve `resource_properties` json parsing

### Relations
Improves #37124
Closes #37050

### Output from Acceptance Testing
```console
% make testacc TESTS=TestAccRoute53ProfilesResourceAssociation_ PKG=route53profiles   
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/route53profiles/... -v -count 1 -parallel 20 -run='TestAccRoute53ProfilesResourceAssociation_'  -timeout 360m
=== RUN   TestAccRoute53ProfilesResourceAssociation_basic
=== PAUSE TestAccRoute53ProfilesResourceAssociation_basic
=== RUN   TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup
=== PAUSE TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup
=== RUN   TestAccRoute53ProfilesResourceAssociation_resolverRule
=== PAUSE TestAccRoute53ProfilesResourceAssociation_resolverRule
=== RUN   TestAccRoute53ProfilesResourceAssociation_disappears
=== PAUSE TestAccRoute53ProfilesResourceAssociation_disappears
=== CONT  TestAccRoute53ProfilesResourceAssociation_basic
=== CONT  TestAccRoute53ProfilesResourceAssociation_resolverRule
=== CONT  TestAccRoute53ProfilesResourceAssociation_disappears
=== CONT  TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup
--- PASS: TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup (143.28s)
--- PASS: TestAccRoute53ProfilesResourceAssociation_resolverRule (166.51s)
--- PASS: TestAccRoute53ProfilesResourceAssociation_disappears (374.42s)
--- PASS: TestAccRoute53ProfilesResourceAssociation_basic (379.82s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    383.579s
```
```
% make testacc TESTS=TestAccRoute53ProfilesAssociation_ PKG=route53profiles    
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/route53profiles/... -v -count 1 -parallel 20 -run='TestAccRoute53ProfilesAssociation_'  -timeout 360m
=== RUN   TestAccRoute53ProfilesAssociation_basic
=== PAUSE TestAccRoute53ProfilesAssociation_basic
=== RUN   TestAccRoute53ProfilesAssociation_disappears
=== PAUSE TestAccRoute53ProfilesAssociation_disappears
=== CONT  TestAccRoute53ProfilesAssociation_basic
=== CONT  TestAccRoute53ProfilesAssociation_disappears
--- PASS: TestAccRoute53ProfilesAssociation_basic (316.20s)
--- PASS: TestAccRoute53ProfilesAssociation_disappears (316.97s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    320.751s
```

### CODE REVIEW

**Comment by tdiener01** [comment]
Hello! My organization is very much looking forward to the Route 53 Profiles resources making it in. @justinretzolk I noticed you added labels a few weeks back, is there a rough time frame for incorporating this feature?  Would love to use it soon, thanks!

**Comment by tonyhess** [comment]
@justinretzolk Is there a way to get this approved?

**Comment by claytonolley** [comment]
I'm also badly in need of this functionality, just curious what the hold up is.

**Comment by Pacobart** [comment]
I solved for this using the `awscc` provider https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/route53profiles_profile
@claytonolley @tdiener01

**Comment by PacoVK** [comment]
> I solved for this using the `awscc` provider https://registry.terraform.io/providers/hashicorp/awscc/latest/docs/resources/route53profiles_profile @claytonolley @tdiener01

That is a solution but take https://github.com/hashicorp/terraform-provider-aws/issues/37050#issuecomment-2348075226 into account. Depending on your setup awscc is not a solution unfortunately :/ hope this get merged soon

**Review by nam054 — APPROVED** [review]
LGTM 🚀 
```
> make testacc TESTARGS="-run=TestAccRoute53ProfilesProfile_" PKG=route53profiles
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/route53profiles/... -v -count 1 -parallel 20  -run=TestAccRoute53ProfilesProfile_ -timeout 360m
=== RUN   TestAccRoute53ProfilesProfile_basic
=== PAUSE TestAccRoute53ProfilesProfile_basic
=== RUN   TestAccRoute53ProfilesProfile_disappears
=== PAUSE TestAccRoute53ProfilesProfile_disappears
=== RUN   TestAccRoute53ProfilesProfile_tags
=== PAUSE TestAccRoute53ProfilesProfile_tags
=== CONT  TestAccRoute53ProfilesProfile_basic
=== CONT  TestAccRoute53ProfilesProfile_tags
=== CONT  TestAccRoute53ProfilesProfile_disappears
--- PASS: TestAccRoute53ProfilesProfile_disappears (13.26s)
--- PASS: TestAccRoute53ProfilesProfile_basic (15.70s)
--- PASS: TestAccRoute53ProfilesProfile_tags (15.73s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    20.893s

> make testacc TESTARGS="-run=TestAccRoute53ProfilesAssociation_" PKG=route53profiles
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/route53profiles/... -v -count 1 -parallel 20  -run=TestAccRoute53ProfilesAssociation_ -timeout 360m
=== RUN   TestAccRoute53ProfilesAssociation_basic
=== PAUSE TestAccRoute53ProfilesAssociation_basic
=== RUN   TestAccRoute53ProfilesAssociation_disappears
=== PAUSE TestAccRoute53ProfilesAssociation_disappears
=== CONT  TestAccRoute53ProfilesAssociation_basic
=== CONT  TestAccRoute53ProfilesAssociation_disappears
--- PASS: TestAccRoute53ProfilesAssociation_disappears (273.91s)
--- PASS: TestAccRoute53ProfilesAssociation_basic (274.54s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    279.595s

> make testacc TESTARGS="-run=TestAccRoute53ProfilesResourceAssociation_" PKG=route53profiles
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/route53profiles/... -v -count 1 -parallel 20  -run=TestAccRoute53ProfilesResourceAssociation_ -timeout 360m
=== RUN   TestAccRoute53ProfilesResourceAssociation_basic
=== PAUSE TestAccRoute53ProfilesResourceAssociation_basic
=== RUN   TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup
=== PAUSE TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup
=== RUN   TestAccRoute53ProfilesResourceAssociation_resolverRule
=== PAUSE TestAccRoute53ProfilesResourceAssociation_resolverRule
=== RUN   TestAccRoute53ProfilesResourceAssociation_disappears
=== PAUSE TestAccRoute53ProfilesResourceAssociation_disappears
=== CONT  TestAccRoute53ProfilesResourceAssociation_basic
=== CONT  TestAccRoute53ProfilesResourceAssociation_resolverRule
=== CONT  TestAccRoute53ProfilesResourceAssociation_disappears
=== CONT  TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup
--- PASS: TestAccRoute53ProfilesResourceAssociation_firewallRuleGroup (126.43s)
--- PASS: TestAccRoute53ProfilesResourceAssociation_resolverRule (158.75s)
--- PASS: TestAccRoute53ProfilesResourceAssociation_basic (399.76s)
--- PASS: TestAccRoute53ProfilesResourceAssociation_disappears (403.72s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    410.278s

> make testacc TESTARGS="-run=TestAccRoute53ProfilesProfilesDataSource_" PKG=route53profiles
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.7 test ./internal/service/route53profiles/... -v -count 1 -parallel 20  -run=TestAccRoute53ProfilesProfilesDataSource_ -timeout 360m
=== RUN   TestAccRoute53ProfilesProfilesDataSource_basic
=== PAUSE TestAccRoute53ProfilesProfilesDataSource_basic
=== CONT  TestAccRoute53ProfilesProfilesDataSource_basic
--- PASS: TestAccRoute53ProfilesProfilesDataSource_basic (11.31s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/route53profiles    16.398s

**Pull request merged**
