### PR TITLE
[New Resource] aws_glue_catalog_table_optimizer

### LINKED ISSUE #38035: [New Resource]: AWS Glue catalog table optimizer
### Description

Automatic compaction of Iceberg tables in AWS Glue was added last year (https://aws.amazon.com/blogs/aws/aws-glue-data-catalog-now-supports-automatic-compaction-of-apache-iceberg-tables/).

It would be useful if an optimizer could be created with Terraform for AWS Glue catalog tables that support this feature (iceberg).

### Requested Resource(s) and/or Data Source(s)

* aws_glue_catalog_table_optimizer

### Potential Terraform Configuration

```terraform
resource "aws_glue_catalog_table_optimizer" "table_optimizer" {
  catalog_id    = 123456789012
  database_name = iceberg_db
  table_name    = iceberg_table

  configuration = {
    roleArn = "arn:aws:iam::123456789012:role/example-role"
    enabled = true
  }

  type = "COMPACTION"
}
```

### References

There appears to be supported Go SDKv2 APIs for all the functionality that would be needed to support this feature:
- https://docs.aws.amazon.com/glue/latest/webapi/API_CreateTableOptimizer.html
- https://docs.aws.amazon.com/glue/latest/webapi/API_DeleteTableOptimizer.html
- https://docs.aws.amazon.com/glue/latest/webapi/API_UpdateTableOptimizer.html

### Would you like to implement a fix?

I will try!

### PR DESCRIPTION
**Pull request by t04glovern**
### Description

- `aws_glue_catalog_table_optimizer` resource added to support automatic compaction of Iceberg tables in AWS Glue was added last year (https://aws.amazon.com/blogs/aws/aws-glue-data-catalog-now-supports-automatic-compaction-of-apache-iceberg-tables/).
- Acceptance test added for `aws_glue_catalog_table_optimizer` 
- Website documentation added for `aws_glue_catalog_table_optimizer` 

### Relations

Closes #38035

### References

- https://docs.aws.amazon.com/glue/latest/webapi/API_CreateTableOptimizer.html
- https://docs.aws.amazon.com/glue/latest/webapi/API_DeleteTableOptimizer.html
- https://docs.aws.amazon.com/glue/latest/webapi/API_UpdateTableOptimizer.html

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccGlueCatalogTableOptimizer PKG=glue
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.2 test ./internal/service/glue/... -v -count 1 -parallel 20 -run='TestAccGlueCatalogTableOptimizer'  -timeout 360m
=== RUN   TestAccGlueCatalogTableOptimizer_basic
=== PAUSE TestAccGlueCatalogTableOptimizer_basic
=== CONT  TestAccGlueCatalogTableOptimizer_basic
--- PASS: TestAccGlueCatalogTableOptimizer_basic (56.20s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/glue       56.366s
...
```

### CODE REVIEW

**Comment by nickdelnano** [comment]
@johnsonaj could you help find a reviewer for this one? This supports a new-ish feature from AWS Glue, from Nov 2023. Having this supported in terraform-provider-aws is huge, otherwise folks are tracking up to thousands of these resources outside of terraform (1 per data lake table).

**Review by johnsonaj — APPROVED** [review]
LGTM 🚀 

```console
% make testacc TESTARGS='-run=TestAccGlue_serial/CatalogTableOptimizer/' PKG=glue

make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/glue/... -v -count 1 -parallel 20  -run=TestAccGlue_serial/CatalogTableOptimizer/ -timeout 360m
=== RUN   TestAccGlue_serial
=== PAUSE TestAccGlue_serial
=== CONT  TestAccGlue_serial
=== RUN   TestAccGlue_serial/CatalogTableOptimizer
=== RUN   TestAccGlue_serial/CatalogTableOptimizer/basic
=== RUN   TestAccGlue_serial/CatalogTableOptimizer/update
=== PAUSE TestAccGlue_serial/CatalogTableOptimizer/update
=== CONT  TestAccGlue_serial/CatalogTableOptimizer/update
--- PASS: TestAccGlue_serial (66.11s)
    --- PASS: TestAccGlue_serial/CatalogTableOptimizer (28.16s)
        --- PASS: TestAccGlue_serial/CatalogTableOptimizer/basic (28.16s)
        --- PASS: TestAccGlue_serial/CatalogTableOptimizer/update (37.95s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/glue	72.172s
```

**Comment by johnsonaj** [comment]
@t04glovern thank you for the contribution! 🎉

**Comment by nickdelnano** [comment]
Glue released new optimizer features [1], filed https://github.com/hashicorp/terraform-provider-aws/issues/39405 to track adding them

[1] https://aws.amazon.com/blogs/big-data/the-aws-glue-data-catalog-now-supports-storage-optimization-of-apache-iceberg-tables/

**Pull request merged**
