### PR TITLE
Add Pinpoint email templates

### LINKED ISSUE #14293: Terraform equivalent of aws pinpoint create-email-template
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

Terraform v0.12.28

### Affected Resource(s)

https://docs.aws.amazon.com/cli/latest/reference/pinpoint/create-email-template.html

* aws_pinpoint_?

### Terraform Configuration Files

Currently there is no way (as far as I can tell) to create a PinPoint email template from terraform.  There is an overlap between PinPoint and SES and some resources can be created in either place (and still be usable with PinPoint), but that is not the case with email templates.  Creating an email template in SES does not result in a template usable in PinPoint (AWS consultant confirmed this).

Could you please add this to your roadmap?  Do you have a workaround?

### PR DESCRIPTION
**Pull request by bashtoni**
### Description

Adds support for [Amazon Pinpoint Email templates](https://docs.aws.amazon.com/pinpoint/latest/userguide/message-templates-creating-email.html).

### Relations

Closes #14293

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccPinpointEmailTemplate_ PKG=pinpoint
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/pinpoint/... -v -count 1 -parallel 20 -run='TestAccPinpointEmailTemplate_'  -timeout 180m
=== RUN   TestAccPinpointEmailTemplate_basic
=== PAUSE TestAccPinpointEmailTemplate_basic
=== RUN   TestAccPinpointEmailTemplate_update
=== PAUSE TestAccPinpointEmailTemplate_update
=== CONT  TestAccPinpointEmailTemplate_basic
=== CONT  TestAccPinpointEmailTemplate_update
--- PASS: TestAccPinpointEmailTemplate_basic (32.35s)
--- PASS: TestAccPinpointEmailTemplate_update (71.66s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint	71.987s
```

### CODE REVIEW

**Comment by rocky4570** [comment]
👍

**Comment by chefren** [comment]
@jar-b are you able to assign reviewer/review please?

**Comment by cemo** [comment]
@jar-b can you assign reviewer please? I would like to send PR remaining related Pinpoint resources.

**Comment by vl-kp** [comment]
Anyone can merge it?

**Comment by cemo** [comment]
@ewbankkit can you please review this?

**Comment by cemo** [comment]
Hey @justinretzolk would you please merge this?

**Comment by justinretzolk** [comment]
Hey @cemo 👋 Thanks for checking in here! I can't speak to when this will be prioritized just yet. We base our prioritization on the count of :+1: reactions and a few other considerations (more information: [prioritization guide](https://hashicorp.github.io/terraform-provider-aws/prioritization/)).

**Review by nam054 — APPROVED** [review]
LGTM! 🚀  Thank you for your contribution!
```
> make testacc TESTARGS='-run=TestAccPinpointEmailTemplate_' PKG=pinpoint
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.6 test ./internal/service/pinpoint/... -v -count 1 -parallel 20  -run=TestAccPinpointEmailTemplate_ -timeout 360m
=== RUN   TestAccPinpointEmailTemplate_basic
=== PAUSE TestAccPinpointEmailTemplate_basic
=== RUN   TestAccPinpointEmailTemplate_update
=== PAUSE TestAccPinpointEmailTemplate_update
=== RUN   TestAccPinpointEmailTemplate_tags
=== PAUSE TestAccPinpointEmailTemplate_tags
=== CONT  TestAccPinpointEmailTemplate_basic
=== CONT  TestAccPinpointEmailTemplate_tags
=== CONT  TestAccPinpointEmailTemplate_update
--- PASS: TestAccPinpointEmailTemplate_tags (16.01s)
--- PASS: TestAccPinpointEmailTemplate_basic (16.09s)
--- PASS: TestAccPinpointEmailTemplate_update (24.17s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/pinpoint   28.890s

**Pull request merged**
