### PR TITLE
d/aws_connect_user_hierarchy_group

### LINKED ISSUE #24776: Add new data_source for aws_connect_user_hierarchy_group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add data source for connect user hierarchy group.

### New or Affected Resource(s)

* aws_connect_user_hierarchy_group

### Potential Terraform Configuration

```hcl
# By Name
data "aws_connect_user_hierarchy_group" "example" {
  instance_id = "aaaaaaaa-bbbb-cccc-dddd-111111111111"
  name        = "Example"
}

# By ID
data "aws_connect_user_hierarchy_group" "example" {
  instance_id        = "aaaaaaaa-bbbb-cccc-dddd-111111111111"
  hierarchy_group_id = "cccccccc-bbbb-cccc-dddd-111111111111"
}
```

### References

* #24777
* https://docs.aws.amazon.com/connect/latest/APIReference/API_DescribeUserHierarchyGroup.html
* https://docs.aws.amazon.com/connect/latest/APIReference/API_ListUserHierarchyGroups.html

### PR DESCRIPTION
**Pull request by GlennChia**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #24776 

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccConnectUserHierarchyGroupDataSource' PKG=connect ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 1  -run=TestAccConnectUserHierarchyGroupDataSource -timeout 180m
=== RUN   TestAccConnectUserHierarchyGroupDataSource_hierarchyGroupID
--- PASS: TestAccConnectUserHierarchyGroupDataSource_hierarchyGroupID (82.83s)
=== RUN   TestAccConnectUserHierarchyGroupDataSource_name
--- PASS: TestAccConnectUserHierarchyGroupDataSource_name (82.85s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/connect    165.737s
...
```

### CODE REVIEW

**Review by AdamTylerLynch — APPROVED** [review]
LGTM 🚀

**Comment by ewbankkit** [comment]
```console
% make providerlint
==> Checking source code with providerlint...
```

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccConnectUserHierarchyGroupDataSource_' PKG=connect ACCTEST_PARALLELISM=1
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/connect/... -v -count 1 -parallel 1  -run=TestAccConnectUserHierarchyGroupDataSource_ -timeout 180m
=== RUN   TestAccConnectUserHierarchyGroupDataSource_hierarchyGroupID
--- PASS: TestAccConnectUserHierarchyGroupDataSource_hierarchyGroupID (87.57s)
=== RUN   TestAccConnectUserHierarchyGroupDataSource_name
--- PASS: TestAccConnectUserHierarchyGroupDataSource_name (86.52s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/connect	178.575s
```

**Comment by ewbankkit** [comment]
@GlennChia Thanks for the contribution :tada: :clap:.

**Pull request merged**
