### PR TITLE
on lambda updates, output the returned values to ensure consistency

### LINKED ISSUE #13099: aws_lambda_alias not updating on new aws_lambda_function version
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version
Terraform: v0.12.24
provider.aws: v2.59.0

### Affected Resource(s)
* aws_lambda_function
* aws_lambda_alias

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "example" {
  function_name = "example-lambda"
  handler = "main"
  role = aws_iam_role.lambda_role.arn
  runtime = "go1.x"
  filename = "../code.zip"
  timeout = 20
  memory_size = 128
  reserved_concurrent_executions = 1
  publish = true
}

resource "aws_lambda_alias" "example" {
  name             = "example-alias"
  description      = "latest version"
  function_name    = aws_lambda_function.example.arn
  function_version = aws_lambda_function.example.version

  depends_on=[aws_lambda_function.example]
}
```

### Expected Behavior

The aws_lambda_funcion resource gets updated to a new version, because publish=true. The aws_lambda_alias resource gets updated to the new version of aws_lambda_function.

### Actual Behavior

The aws_lambda_funcion resource gets updated to a new version, because publish=true. The aws_lambda_alias does not get updated until the next apply. 

### Steps to Reproduce

1. `terraform apply` -> aws_lambda_function gets updated
2. `terraform apply` -> aws_lambda_alias gets updated 

### References

* #3032 
* #628 
* #3192

### LINKED ISSUE #14210: Lambda auto-publish - Sometimes does not output new version
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version
```
terraform 0.12.26

provider "aws" {
  version = "2.47.0"
}
```

I realize this is not the latest AWS provider but for a few reasons I feel this ticket should be considered anyway.
- The bug is seemingly a race condition so it's very hard for us to find instances of the bug. If we bump to latest we will have to wait another few weeks to find the bug again.
- I'm fairly sure I know the reason of the bug and I believe the problem may still exists in the codebase 

### Affected Resource(s)

* aws_lambda_function

### Terraform Configuration Files

```hcl
resource "aws_lambda_function" "lambda" {
  function_name                  = format("%s-service", var.resource_name)
  role                           = var.role_arn
  source_code_hash               = var.source_code_hash
  handler                        = var.handler
  runtime                        = var.runtime
  timeout                        = var.timeout
  publish                        = var.publish
  memory_size                    = var.memory_size
  description                    = var.description
  reserved_concurrent_executions = var.reserved_concurrent_executions
  s3_bucket                      = var.s3_bucket
  s3_key                         = aws_s3_bucket_object.artifact.key
  s3_object_version              = aws_s3_bucket_object.artifact.version_id

  dynamic "dead_letter_config" {
    for_each = var.dead_letter_config == null ? [] : [var.dead_letter_config]
    content {
      target_arn = dead_letter_config.value.target_arn
    }
  }

  dynamic "tracing_config" {
    for_each = var.tracing_config == null ? [] : [var.tracing_config]
    content {
      mode = tracing_config.value.mode
    }
  }

  vpc_config {
    security_group_ids = [aws_security_group.lambda_egress.id]
    subnet_ids         = var.private_subnets
  }

  dynamic "environment" {
    for_each = length(var.environment) < 1 ? [] : [var.environment]
    content {
      variables = environment.value.variables
    }
  }

  tags = var.tags
}
```

### Expected Behavior

We have output the lambda version. I expect if lambda version `8` is created on a Terraform run, that the output be `8`.
### Actual Behavior

Usually the output will be `8`. Infrequently the Terraform logic will create `8` but output the old version `7`.

### Steps to Reproduce

Simply push changes to your lambda and deploy with Terraform many times until you hit this condition. It seems to be very infrequent.

#### Guess at Cause

I believe I have found the cause but I'd hope someone can confirm.

It seems that the auto-publish feature is used in updating lambdas. This API call to AWS will return the updated version. However the AWS provider doesn't appear to use that version and instead appears to call `get-function-versions` and grab the largest version from the return list and use that value. However, I've confirmed with AWS Support that `get-function-versions` isn't a strongly consistent call and in fact is eventually consistent and has a cache TTL (length unknown).

I believe that the calls to `get-function-versions` sometimes returns stale data and so the new version is not present.

To solve this issue the AWS provider should use the version returned from the `update-function` call (`create-function` call too if that's relevant). 

* #0000

### PR DESCRIPTION
**Pull request by keithcom**
On lambda updates that publish new versions, output the returned values to ensure consistency as the read is eventually consistent.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #14210
Closes #13099

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSLambdaFunction_versioned'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLambdaFunction_versioned -timeout 120m
=== RUN   TestAccAWSLambdaFunction_versioned
=== PAUSE TestAccAWSLambdaFunction_versioned
=== RUN   TestAccAWSLambdaFunction_versionedUpdate
=== PAUSE TestAccAWSLambdaFunction_versionedUpdate
=== CONT  TestAccAWSLambdaFunction_versioned
=== CONT  TestAccAWSLambdaFunction_versionedUpdate
--- PASS: TestAccAWSLambdaFunction_versioned (37.82s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (64.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	65.540s
```

### CODE REVIEW

**Comment by kevinmstephens** [comment]
This fixes #13099 too!

**Comment by kevinmstephens** [comment]
is there any timeline for this getting merged? auto lambda versioning is broken without this

**Comment by danieladams456** [comment]
This would be a helpful fix!

**Comment by YakDriver** [comment]
@keithcom Thank you for your work on this PR! I will be working on this before long. In order to expedite the process, I will likely make some changes. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Review by YakDriver — APPROVED** [review]
Looks great! 🎉 

GovCloud:
```
--- PASS: TestAccAWSLambdaFunction_versioned (45.55s)
--- PASS: TestAccAWSLambdaFunction_enablePublish (76.22s)
--- PASS: TestAccAWSLambdaFunction_disablePublish (77.48s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (96.20s)
--- PASS: TestAccAWSLambdaAlias_basic (43.96s)
--- PASS: TestAccAWSLambdaAlias_FunctionName_Name (54.76s)
--- PASS: TestAccAWSLambdaAlias_nameupdate (62.34s)
--- PASS: TestAccAWSLambdaAlias_routingconfig (70.64s)
```

`us-west-2`:
```
--- PASS: TestAccAWSLambdaFunction_versioned (50.41s)
--- PASS: TestAccAWSLambdaFunction_disablePublish (80.97s)
--- PASS: TestAccAWSLambdaFunction_versionedUpdate (89.92s)
--- PASS: TestAccAWSLambdaFunction_enablePublish (90.78s)
--- PASS: TestAccAWSLambdaAlias_nameupdate (40.70s)
--- PASS: TestAccAWSLambdaAlias_FunctionName_Name (43.94s)
--- PASS: TestAccAWSLambdaAlias_basic (44.22s)
--- PASS: TestAccAWSLambdaAlias_routingconfig (74.77s)
```

**Pull request merged**
