### PR TITLE
enhancement(resourcegroups): Add configuration type and attribute

### LINKED ISSUE #26933: [Enhancement]: resourcegroups group should support Host-resource-group/configuration type groups
### Description

The `aws_resourcegroups_group` resource should support host-resource-groups and configuration groups in general.

AWS implemented Host-Resource-Groups as a type of resource-group. Instead of a resource-query, configuration groups use the group configuration API to attach or update group configurations

### Affected Resource(s) and/or Data Source(s)

* aws_resourcegroups_group

### Potential Terraform Configuration

```terraform
resource "aws_licensemanager_license_configuration"  "mac_license_config"{  
  name                     = "mac-dedicated-license"
  description              = "Pass through configuration for Host Resource Group"
  license_count            = 32
  license_count_hard_limit = false
  license_counting_type    = "Core"
}

resource "aws_resourcegroups_group" "mac" {
  name        = "mac-hrg"
  description = "A host-resource-group for mac dedicated instances"

  configuration {
    type = "AWS::EC2::HostManagement"

    parameters {
      name   = "allowed-host-families"
      values = [
        "mac1",
      ]
    }

    parameters {
      name   = "allowed-host-based-license-configurations"
      values = [
        aws_licensemanager_license_configuration.mac_license_config.arn,
      ]
    }

    parameters {
      name   = "auto-allocate-host"
      values = [
        "true",
      ]
    }

    parameters {
      name   = "auto-release-host"
      values = [
        "true",
      ]
    }
  }

  configuration {
    type = "AWS::ResourceGroups::Generic"

    parameters {
      name = "allowed-resource-types"
      values = [
        "AWS::EC2::Host",
      ]
    }

    parameters {
      name = "deletion-protection"
      values = [
        "UNLESS_EMPTY"
      ]
    }
  }
}
```

### References

Examples and description of host-resource-groups https://aws.amazon.com/blogs/compute/implementing-autoscaling-for-ec2-mac-instances/

Supported types https://docs.aws.amazon.com/ARG/latest/APIReference/about-slg.html#about-slg-types

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by IainSteers**
Closes #26933

Output from acceptance testing:

I added some new acceptance tests for the configuration group and also verified that the additions don't fail the existing acceptance tests. 

```
$ make testacc TESTS=TestAccResourceGroupsGroup PKG=resourcegroups
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/resourcegroups/... -v -count 1 -parallel 20 -run='TestAccResourceGroupsGroup'  -timeout 180m
=== RUN   TestAccResourceGroupsGroup_Resource_basic
=== PAUSE TestAccResourceGroupsGroup_Resource_basic
=== RUN   TestAccResourceGroupsGroup_Resource_Configuration
=== PAUSE TestAccResourceGroupsGroup_Resource_Configuration
=== RUN   TestAccResourceGroupsGroup_Resource_tags
=== PAUSE TestAccResourceGroupsGroup_Resource_tags
=== CONT  TestAccResourceGroupsGroup_Resource_basic
=== CONT  TestAccResourceGroupsGroup_Resource_Configuration
=== CONT  TestAccResourceGroupsGroup_Resource_tags
--- PASS: TestAccResourceGroupsGroup_Resource_basic (30.40s)
--- PASS: TestAccResourceGroupsGroup_Resource_tags (47.49s)
--- PASS: TestAccResourceGroupsGroup_Resource_Configuration (55.93s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups	57.856s
...
```

### CODE REVIEW

**Comment by dkheyman** [comment]
This is crucial for my customer's use of capacity reservations. If this works according to the planned use of `Configuration`, let's approve!

**Comment by IainSteers** [comment]
@dkheyman using one of our test AWS accounts I was able to use this resource to create a Host Resource Group, verify the fields in the console.

I was then able to reference the created Host-Resource-Group from both the Instance Launch Wizard and a Launch Template successfully and have dedicated host.

Basically following https://aws.amazon.com/blogs/compute/implementing-autoscaling-for-ec2-mac-instances/ but with this new resource support

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccResourceGroupsGroup_' PKG=resourcegroups ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/resourcegroups/... -v -count 1 -parallel 2  -run=TestAccResourceGroupsGroup_ -timeout 180m
=== RUN   TestAccResourceGroupsGroup_basic
=== PAUSE TestAccResourceGroupsGroup_basic
=== RUN   TestAccResourceGroupsGroup_tags
=== PAUSE TestAccResourceGroupsGroup_tags
=== RUN   TestAccResourceGroupsGroup_Configuration
=== PAUSE TestAccResourceGroupsGroup_Configuration
=== CONT  TestAccResourceGroupsGroup_basic
=== CONT  TestAccResourceGroupsGroup_Configuration
--- PASS: TestAccResourceGroupsGroup_basic (34.17s)
=== CONT  TestAccResourceGroupsGroup_tags
--- PASS: TestAccResourceGroupsGroup_Configuration (56.72s)
--- PASS: TestAccResourceGroupsGroup_tags (45.15s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/resourcegroups	83.659s
```

**Comment by ewbankkit** [comment]
@IainSteers Thanks for the contribution :tada: :clap:.

**Pull request merged**
