### PR TITLE
data_source/aws_outposts_outpost and aws_outposts_outposts: add argument for owner_id

### LINKED ISSUE #17517: owner_id argument added to aws_outposts_outpost*
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Add the owner_id argument so can filter for outposts owned by a given account_id 

### New or Affected Resource(s)

* aws_outposts_outpost
* aws_outposts_outposts

### Potential Terraform Configuration

```hcl
owner_id - AWS Account identifier of the Outpost owner.
```

### References

* https://docs.aws.amazon.com/outposts/latest/APIReference/API_ListOutposts.html

### PR DESCRIPTION
**Pull request by farhanangullia**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #17517

Release note for [CHANGELOG](https://github.com/hashicorp/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
enhancement:

data_source/aws_outposts_outpost: Add support for `owner_id` argument

data_source/aws_outposts_outposts: Add support for `owner_id` argument
```

### Affected Resource(s)
- data_source: aws_outposts_outpost
- data_source: aws_outposts_outposts

### Terraform Configuration
```HCL
data "aws_outposts_outpost" "foo" {
  owner_id = "123456789012"
}

data "aws_outposts_outposts" "foo" {
  owner_id = "123456789012"
}

```
Output from acceptance testing for data_source/aws_outposts_outpost:

```
$ make testacc TESTARGS='-run=TestAccAWSOutpostsOutpostDataSource'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSOutpostsOutpostDataSource -timeout 120m
=== RUN   TestAccAWSOutpostsOutpostDataSource_Id
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Id
=== RUN   TestAccAWSOutpostsOutpostDataSource_Name
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Name
=== RUN   TestAccAWSOutpostsOutpostDataSource_Arn
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Arn
=== RUN   TestAccAWSOutpostsOutpostDataSource_OwnerId
=== PAUSE TestAccAWSOutpostsOutpostDataSource_OwnerId
=== CONT  TestAccAWSOutpostsOutpostDataSource_Id
=== CONT  TestAccAWSOutpostsOutpostDataSource_OwnerId
=== CONT  TestAccAWSOutpostsOutpostDataSource_Arn
=== CONT  TestAccAWSOutpostsOutpostDataSource_Name
--- PASS: TestAccAWSOutpostsOutpostDataSource_Id (99.88s)
--- PASS: TestAccAWSOutpostsOutpostDataSource_Arn (100.06s)
--- PASS: TestAccAWSOutpostsOutpostDataSource_Name (102.92s)
--- PASS: TestAccAWSOutpostsOutpostDataSource_OwnerId (110.32s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       112.209s

...
```

Output from acceptance testing for data_source/aws_outposts_outposts:

```
$ make testacc TESTARGS='-run=TestAccAWSOutpostsOutpostsDataSource'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSOutpostsOutpostsDataSource -timeout 120m
=== RUN   TestAccAWSOutpostsOutpostsDataSource_basic
=== PAUSE TestAccAWSOutpostsOutpostsDataSource_basic
=== CONT  TestAccAWSOutpostsOutpostsDataSource_basic
--- PASS: TestAccAWSOutpostsOutpostsDataSource_basic (58.41s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       59.618s

...
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSOutpostsOutpostDataSource_\|TestAccAWSOutpostsOutpostsDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSOutpostsOutpostDataSource_\|TestAccAWSOutpostsOutpostsDataSource_ -timeout 180m
=== RUN   TestAccAWSOutpostsOutpostDataSource_Id
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Id
=== RUN   TestAccAWSOutpostsOutpostDataSource_Name
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Name
=== RUN   TestAccAWSOutpostsOutpostDataSource_Arn
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Arn
=== RUN   TestAccAWSOutpostsOutpostDataSource_OwnerId
=== PAUSE TestAccAWSOutpostsOutpostDataSource_OwnerId
=== RUN   TestAccAWSOutpostsOutpostsDataSource_basic
=== PAUSE TestAccAWSOutpostsOutpostsDataSource_basic
=== CONT  TestAccAWSOutpostsOutpostDataSource_Id
=== CONT  TestAccAWSOutpostsOutpostDataSource_OwnerId
=== CONT  TestAccAWSOutpostsOutpostDataSource_Name
=== CONT  TestAccAWSOutpostsOutpostDataSource_Arn
=== CONT  TestAccAWSOutpostsOutpostsDataSource_basic
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostsDataSource_basic (1.70s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_OwnerId
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_OwnerId (1.73s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_Id
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_Id (1.76s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_Name
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_Name (1.97s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_Arn
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_Arn (2.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	5.252s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSOutpostsOutpostDataSource_\|TestAccAWSOutpostsOutpostsDataSource_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSOutpostsOutpostDataSource_\|TestAccAWSOutpostsOutpostsDataSource_ -timeout 180m
=== RUN   TestAccAWSOutpostsOutpostDataSource_Id
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Id
=== RUN   TestAccAWSOutpostsOutpostDataSource_Name
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Name
=== RUN   TestAccAWSOutpostsOutpostDataSource_Arn
=== PAUSE TestAccAWSOutpostsOutpostDataSource_Arn
=== RUN   TestAccAWSOutpostsOutpostDataSource_OwnerId
=== PAUSE TestAccAWSOutpostsOutpostDataSource_OwnerId
=== RUN   TestAccAWSOutpostsOutpostsDataSource_basic
=== PAUSE TestAccAWSOutpostsOutpostsDataSource_basic
=== CONT  TestAccAWSOutpostsOutpostDataSource_Id
=== CONT  TestAccAWSOutpostsOutpostDataSource_OwnerId
=== CONT  TestAccAWSOutpostsOutpostDataSource_Arn
=== CONT  TestAccAWSOutpostsOutpostsDataSource_basic
=== CONT  TestAccAWSOutpostsOutpostDataSource_Name
=== CONT  TestAccAWSOutpostsOutpostsDataSource_basic
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostsDataSource_basic (2.02s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_Name
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_Name (2.04s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_OwnerId
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_OwnerId (2.20s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_Id
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_Id (7.07s)
=== CONT  TestAccAWSOutpostsOutpostDataSource_Arn
    data_source_aws_outposts_outposts_test.go:67: skipping since no Outposts found
--- SKIP: TestAccAWSOutpostsOutpostDataSource_Arn (7.14s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	10.350s
```

**Comment by ewbankkit** [comment]
@farhanangullia Thanks for the contribution :clap:.

**Comment by farhanangullia** [comment]
> @farhanangullia Thanks for the contribution 👏.

Thanks Kit!

**Comment by farhanangullia** [comment]
Thanks @ewbankkit 😄

**Pull request merged**
