### PR TITLE
Add aws_iot_provisioning_template resource

### LINKED ISSUE #12107: New Resource: AWS IoT Fleet Provisioning Template
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS recently launched a beta for [fleet provisioning](https://docs.aws.amazon.com/iot/latest/developerguide/provision-wo-cert.html), which allows IoT to generate certificates and private keys for devices as they connect to IoT with a provisioning template.

### New or Affected Resource(s)

* `aws_iot_provisioning_template`

### Potential Terraform Configuration

```hcl
data "aws_iam_policy_document" "iot_assume_role_policy" {
  statement {
    actions = ["sts:AssumeRole"]

    principals {
      type        = "Service"
      identifiers = ["iot.amazonaws.com"]
    }
  }
}

resource "aws_iam_role" "iot_fleet_provisioning" {
  name = "IoTProvisioningServiceRole"
  path = "/service-role/"
  assume_role_policy = data.aws_iam_policy_document.iot_assume_role_policy.json
}

resource "aws_iam_role_policy_attachment" "iot_fleet_provisioning_registration" {
  role       = aws_iam_role.iot_fleet_provisioning.name
  policy_arn = "arn:aws:iam::aws:policy/service-role/AWSIoTThingsRegistration"
}

resource "aws_iot_provisioning_template" "fleet" {
  template_name         = "FleetProvisioningTemplate"
  description           = "My fleet provisioning template"
  provisioning_role_arn = aws_iam_role.iot_fleet_provisioning

  template_body = <<EOF
{
  "Version": "2012-10-17",
  "Statement": [
    {
      "Action": [
        "iot:*"
      ],
      "Effect": "Allow",
      "Resource": "*"
    }
  ]
}
EOF
}
```

Optional: provide a data source to allow cleaner generation of template bodies.

### References

None

### PR DESCRIPTION
**Pull request by oleg-codaio**
Adds the resource `aws_iot_provisioning_template` to enable creating [IoT Fleet Provisioning Templates](https://docs.aws.amazon.com/iot/latest/developerguide/provision-wo-cert.html). This is a new AWS IoT feature, still in beta, that allows IoT to automatically create and deliver device certificates and private keys to new devices as they connect to IoT.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12107

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
**New resource**: `aws_iot_provisioning_template`
```

Output from acceptance testing:

```
$ AWS_DEFAULT_REGION=us-east-1 make testacc TESTARGS='-run=TestAccAWSIoTProvisioningTemplate'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSIoTProvisioningTemplate -timeout 120m
?       github.com/terraform-providers/terraform-provider-aws   [no test files]
=== RUN   TestAccAWSIoTProvisioningTemplate_basic
=== PAUSE TestAccAWSIoTProvisioningTemplate_basic
=== CONT  TestAccAWSIoTProvisioningTemplate_basic
--- PASS: TestAccAWSIoTProvisioningTemplate_basic (49.26s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       50.911s
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap      0.342s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags 0.247s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency    0.247s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token    0.157s [no tests to run]
?       github.com/terraform-providers/terraform-provider-aws/awsproviderlint   [no test files]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes    0.631s [no tests to run]
testing: warning: no tests to run
PASS
ok      github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001   0.307s [no tests to run]
```

### Notes

- Fleet provisioning is currently only available in `us-east-1`
- Changes to template bodies are made via new versions, exposed in the AWS API. To simplify usage, any changes to template bodies result in a new version being created and set as the default under the hood. This seems fine since Terraform is essentially the versioning provider, and is in line with the implementation of other resources like `aws_iot_policy`

### CODE REVIEW

**Comment by l85m** [comment]
> Fleet provisioning is currently only available in us-east-1

Fleet provisioning is in GA now and available in most (all?) regions: https://aws.amazon.com/about-aws/whats-new/2020/04/announcing-general-availability-of-aws-iot-core-fleet-provisioning/

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Action Required: Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by burningalchemist** [comment]
Hello! Is there any update for the PR? This resource would be highly appreciated. I'm happy to help with the leftovers if needed. 👍

**Comment by vaskevich** [comment]
It's been ready for a while, but the Terraform team is overwhelmed with issues and PRs unfortunately. I'm going to take care of the above needed changes in the week or so.

**Comment by burningalchemist** [comment]
Yay, thanks a lot! 👍

**Comment by vaskevich** [comment]
This should be good for review again.

```
$ AWS_DEFAULT_REGION=us-east-1 make testacc TESTARGS='-run=TestAccAWSIoTProvisioningTemplate' 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSIoTProvisioningTemplate -timeout 120m
=== RUN   TestAccAWSIoTProvisioningTemplate_basic
=== PAUSE TestAccAWSIoTProvisioningTemplate_basic
=== CONT  TestAccAWSIoTProvisioningTemplate_basic
--- PASS: TestAccAWSIoTProvisioningTemplate_basic (47.51s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       49.231s
```

**Comment by agacel1** [comment]
Hi :) When do you plan to release this feature?

**Comment by kkotowick** [comment]
Agreed, this is a major limitation to using AWS IoT. What's an ETA for review?

**Comment by Fran-E** [comment]
I'm very impatient to see this new feature. Thanks in advance.

**Comment by emazzotta** [comment]
Sorry for bothering. This feature being missing is currently a show-stopper for me, any news? 🙂

**Comment by cgddrd-gardin** [comment]
Hi, would someone from the Terraform dev community be able to give any indication as to when this PR for IoT fleet provisioning will be merged? Thanks.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccIoTProvisioningTemplate_ PKG=iot ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/iot/... -v -count 1 -parallel 2 -run='TestAccIoTProvisioningTemplate_'  -timeout 180m
=== RUN   TestAccIoTProvisioningTemplate_basic
=== PAUSE TestAccIoTProvisioningTemplate_basic
=== RUN   TestAccIoTProvisioningTemplate_disappears
=== PAUSE TestAccIoTProvisioningTemplate_disappears
=== RUN   TestAccIoTProvisioningTemplate_tags
=== PAUSE TestAccIoTProvisioningTemplate_tags
=== RUN   TestAccIoTProvisioningTemplate_update
=== PAUSE TestAccIoTProvisioningTemplate_update
=== CONT  TestAccIoTProvisioningTemplate_basic
=== CONT  TestAccIoTProvisioningTemplate_tags
--- PASS: TestAccIoTProvisioningTemplate_basic (34.32s)
=== CONT  TestAccIoTProvisioningTemplate_update
--- PASS: TestAccIoTProvisioningTemplate_tags (57.94s)
=== CONT  TestAccIoTProvisioningTemplate_disappears
--- PASS: TestAccIoTProvisioningTemplate_update (45.06s)
--- PASS: TestAccIoTProvisioningTemplate_disappears (30.26s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/iot	91.917s
```

**Comment by ewbankkit** [comment]
@oleg-codaio Thanks for the contribution :tada: :clap:.

**Pull request merged**
