### PR TITLE
r/flow_log: Add `cross_account_iam_role_arn` attribute

### LINKED ISSUE #28577: [Enhancement]: aws_flow_log attribute for Cross Account Role
### Terraform Core Version

1.3.5

### AWS Provider Version

4.48.0

### Affected Resource(s)

aws_flow_log

### Expected Behavior

I should be able to set both DeliverLogsPermissionArn(attribute exists iam_role_arn) role and DeliverCrossAccountRole(doesn't exist)

### Actual Behavior

Unable to set Kinesis Firehose from the destination account

### Relevant Error/Panic Output Snippet

```shell
Error: creating Flow Log (vpc-************): InvalidParameter: When providing a role for cross-account delivery, both the DeliverLogsPermissionArn and DeliverCrossAccountRole fields must be set.
│       status code: 400, request id: **********-**********
```

### Terraform Configuration Files

```
resource "aws_flow_log" "vpc_to_kinesis_data_firehose" {
  iam_role_arn         = aws_iam_role.vpc_to_cwl.arn
  log_destination_type = "kinesis-data-firehose"
  log_destination      = aws_kinesis_firehose_delivery_stream.vpc_stream.arn
  traffic_type         = "ALL"
  vpc_id               = data.aws_ssm_parameter.vpc.value
}
```

### Steps to Reproduce

this attribute just does not exist in the provider

### Debug Output

_No response_

### Panic Output

_No response_

### Important Factoids

_No response_

### References

_No response_

### Would you like to implement a fix?

No

### PR DESCRIPTION
**Pull request by mattburgess**
### Relations

Closes #28577.
Closes https://github.com/hashicorp/terraform-provider-aws/issues/29323.

### Output from Acceptance Testing

```
$ make testacc ACCTEST_PARALLELISM=3 TESTS=TestAccVPCFlowLog_ PKG=ec2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3 -run='TestAccVPCFlowLog_'  -timeout 180m
=== RUN   TestAccVPCFlowLog_vpcID
=== PAUSE TestAccVPCFlowLog_vpcID
=== RUN   TestAccVPCFlowLog_logFormat
=== PAUSE TestAccVPCFlowLog_logFormat
=== RUN   TestAccVPCFlowLog_subnetID
=== PAUSE TestAccVPCFlowLog_subnetID
=== RUN   TestAccVPCFlowLog_crossAccountRole
=== PAUSE TestAccVPCFlowLog_crossAccountRole
=== RUN   TestAccVPCFlowLog_transitGatewayID
=== PAUSE TestAccVPCFlowLog_transitGatewayID
=== RUN   TestAccVPCFlowLog_transitGatewayAttachmentID
=== PAUSE TestAccVPCFlowLog_transitGatewayAttachmentID
=== RUN   TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
=== PAUSE TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
=== RUN   TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
=== PAUSE TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
=== RUN   TestAccVPCFlowLog_LogDestinationType_s3
=== PAUSE TestAccVPCFlowLog_LogDestinationType_s3
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3_invalid
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3_invalid
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour
=== RUN   TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval
=== PAUSE TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval
=== RUN   TestAccVPCFlowLog_tags
=== PAUSE TestAccVPCFlowLog_tags
=== RUN   TestAccVPCFlowLog_disappears
=== PAUSE TestAccVPCFlowLog_disappears
=== CONT  TestAccVPCFlowLog_vpcID
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3_invalid
=== CONT  TestAccVPCFlowLog_transitGatewayAttachmentID
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3_invalid (9.50s)
=== CONT  TestAccVPCFlowLog_crossAccountRole
--- PASS: TestAccVPCFlowLog_crossAccountRole (17.66s)
=== CONT  TestAccVPCFlowLog_transitGatewayID
--- PASS: TestAccVPCFlowLog_vpcID (30.51s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour (15.46s)
=== CONT  TestAccVPCFlowLog_disappears
--- PASS: TestAccVPCFlowLog_disappears (13.40s)
=== CONT  TestAccVPCFlowLog_tags
--- PASS: TestAccVPCFlowLog_tags (36.89s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval
--- PASS: TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval (15.70s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet (15.39s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible (14.86s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
--- PASS: TestAccVPCFlowLog_transitGatewayID (172.61s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_s3
--- PASS: TestAccVPCFlowLog_LogDestinationType_s3 (14.54s)
=== CONT  TestAccVPCFlowLog_subnetID
--- PASS: TestAccVPCFlowLog_LogDestinationType_kinesisFirehose (82.57s)
=== CONT  TestAccVPCFlowLog_logFormat
--- PASS: TestAccVPCFlowLog_subnetID (15.78s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible (16.10s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
--- PASS: TestAccVPCFlowLog_logFormat (28.68s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText
--- PASS: TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs (17.16s)
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText (16.75s)
--- PASS: TestAccVPCFlowLog_transitGatewayAttachmentID (281.25s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	281.350s
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccVPCFlowLog_' PKG=ec2 ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccVPCFlowLog_ -timeout 180m
=== RUN   TestAccVPCFlowLog_basic
=== PAUSE TestAccVPCFlowLog_basic
=== RUN   TestAccVPCFlowLog_logFormat
=== PAUSE TestAccVPCFlowLog_logFormat
=== RUN   TestAccVPCFlowLog_subnetID
=== PAUSE TestAccVPCFlowLog_subnetID
=== RUN   TestAccVPCFlowLog_transitGatewayID
=== PAUSE TestAccVPCFlowLog_transitGatewayID
=== RUN   TestAccVPCFlowLog_transitGatewayAttachmentID
=== PAUSE TestAccVPCFlowLog_transitGatewayAttachmentID
=== RUN   TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
=== PAUSE TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
=== RUN   TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
=== PAUSE TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
=== RUN   TestAccVPCFlowLog_LogDestinationType_s3
=== PAUSE TestAccVPCFlowLog_LogDestinationType_s3
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3_invalid
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3_invalid
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible
=== RUN   TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour
=== PAUSE TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour
=== RUN   TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval
=== PAUSE TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval
=== RUN   TestAccVPCFlowLog_tags
=== PAUSE TestAccVPCFlowLog_tags
=== RUN   TestAccVPCFlowLog_disappears
=== PAUSE TestAccVPCFlowLog_disappears
=== CONT  TestAccVPCFlowLog_basic
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour
--- PASS: TestAccVPCFlowLog_basic (26.24s)
=== CONT  TestAccVPCFlowLog_disappears
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DO_plainText (27.20s)
=== CONT  TestAccVPCFlowLog_tags
=== CONT  TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DOParquetHiveCompatible_perHour (27.61s)
--- PASS: TestAccVPCFlowLog_disappears (20.62s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs
--- PASS: TestAccVPCFlowLog_LogDestinationType_maxAggregationInterval (23.81s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3_invalid
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3_invalid (13.68s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_s3
--- PASS: TestAccVPCFlowLog_LogDestinationType_cloudWatchLogs (23.77s)
=== CONT  TestAccVPCFlowLog_LogDestinationType_kinesisFirehose
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible
--- PASS: TestAccVPCFlowLog_tags (55.89s)
--- PASS: TestAccVPCFlowLog_LogDestinationType_s3 (24.47s)
=== CONT  TestAccVPCFlowLog_transitGatewayID
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DOPlainText_hiveCompatible (24.29s)
=== CONT  TestAccVPCFlowLog_transitGatewayAttachmentID
--- PASS: TestAccVPCFlowLog_LogDestinationType_kinesisFirehose (154.32s)
=== CONT  TestAccVPCFlowLog_subnetID
--- PASS: TestAccVPCFlowLog_transitGatewayID (157.71s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible
--- PASS: TestAccVPCFlowLog_subnetID (23.30s)
=== CONT  TestAccVPCFlowLog_logFormat
--- PASS: TestAccVPCFlowLog_logFormat (24.44s)
=== CONT  TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DOParquet_hiveCompatible (25.72s)
--- PASS: TestAccVPCFlowLog_LogDestinationTypeS3DO_parquet (23.36s)
--- PASS: TestAccVPCFlowLog_transitGatewayAttachmentID (301.86s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	414.889s
```

**Comment by ewbankkit** [comment]
@xxx Thanks for the contribution :tada: :clap:.

I changed the new attribute name to `deliver_cross_account_role` to match the underlying AWS EC2 API.

**Comment by marcel-mattr** [comment]
@ewbankkit Why isn't this attribute called `deliver_cross_account_role_arn` instead of `deliver_cross_account_role` like `iam_role_arn` just to keep standards?

**Comment by mattburgess** [comment]
@marcel-mattr as @ewbankkit mentioned above, the AWS Provider tries to align with the underlying AWS API whenever possible. As you'll see [here](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/API_CreateFlowLogs.html), AWS (for whatever reason), decided to call this new parameter ` DeliverCrossAccountRole `. I agree with you that the naming isn't great, but it is what it is.

As to why, then, `iam_role_arn` isn't called `deliver_logs_permission_arn` to similarly match the underlying API I've no idea. Turns out consistency is hard? :smile:

If it was up to me, the AWS API would have parameters called `DeliverLogsIamRoleArn` and `DeliverLogsCrossAccountRoleArn` but it's always easier to name things perfectly in hindsight.

**Pull request merged**
