### PR TITLE
resource/aws_dlm_lifecycle_policy: Implement support for Cross-Region Copy feature

### LINKED ISSUE #12204: aws_dlm_lifecycle_policy - Implement support for "Cross Region copy"
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amazon Data Lifecycle Manager support "Cross region copy" since December 2019.

The feature is currently not supported by the Terraform AWS Provider.

### New or Affected Resource(s)

* aws/resource_aws_dlm_lifecycle_policy.go

### Potential Terraform Configuration

```hcl
cross_region_copy_rule [
  target_region = "string"
  encrypted = true|false
  cmk_arn = "string"
  copy_tags = true|false
  retain_rule = {
    interval = "integer"
    interval_unit = "DAYS"|"WEEKS"|"MONTHS"|"YEARS"
  }
]
```

### References

* https://aws.amazon.com/about-aws/whats-new/2019/12/amazon-data-lifecycle-manager-enables-automation-snapshot-copy-via-policies/

### PR DESCRIPTION
**Pull request by sysbart**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #12204

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
resource/aws_dlm_lifecycle_policy: Implement support for Cross-Region Copy feature
```

Output from acceptance testing:

```
$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSDlmLifecyclePolicy_Full'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDlmLifecyclePolicy_Full -timeout 120m
=== RUN   TestAccAWSDlmLifecyclePolicy_Full
=== PAUSE TestAccAWSDlmLifecyclePolicy_Full
=== CONT  TestAccAWSDlmLifecyclePolicy_Full
--- PASS: TestAccAWSDlmLifecyclePolicy_Full (68.75s)
PASS
```

### CODE REVIEW

**Comment by rmlsun** [comment]
Please consider merging this!

**Comment by bitle** [comment]
I see a lot of value in this feature. What needs to be done to get this PR merged?

**Comment by Karl-Webster** [comment]
Is there an update on this?

**Comment by ayoubboulila** [comment]
Any Updates on this ?

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Review by anGie44 — APPROVED** [review]
Thank you for this PR @sysbart 🚀  ! Looked great overall, just a couple changes have been added to account for the provider codebase restructuring.

Output of acceptance tests:
```
--- PASS: TestAccDLMLifecyclePolicy_basic (26.33s)
--- PASS: TestAccDLMLifecyclePolicy_full (29.05s)
--- PASS: TestAccDLMLifecyclePolicy_tags (43.07s)
--- PASS: TestAccDLMLifecyclePolicy_crossRegionCopyRule (50.99s)
```

**Pull request merged**
