### PR TITLE
New resource: `aws_db_instance_automated_backups_replication `

### LINKED ISSUE #16708: resource/aws_db_instance: Should support enabling cross-region automated backups
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RDS supports enabling cross-region automated backups via the API as described here:
https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html

### New or Affected Resource(s)

* aws_db_instance

### Potential Terraform Configuration

```hcl
resource "aws_db_instance" "this_db_instance" {
	identifier = local.rds_name

	allocated_storage = var.allocated_storage
	max_allocated_storage = var.max_allocated_storage
	
	apply_immediately = var.apply_immediately
	
	auto_minor_version_upgrade = var.auto_minor_version_upgrade
	allow_major_version_upgrade = var.allow_major_version_upgrade
	
	availability_zone = data.aws_subnet.rds_subnet1.availability_zone
	multi_az = var.multi_az
	
	backup_retention_period = var.backup_retention_period
	backup_window = var.backup_window
	
	###### NEW CONFIGURATION
	backup_replication_region = "us-east-2"
	backup_replication_retention_period = 28
	######
	
	maintenance_window = var.maintenance_window
	
	db_subnet_group_name = aws_db_subnet_group.this_db_subnet_group.name

	deletion_protection = var.deletion_protection
	
	engine = var.engine
	engine_version = var.engine_version
	
	kms_key_id = aws_kms_key.this_key.arn
	storage_encrypted = "true"
	
	parameter_group_name = aws_db_parameter_group.this_parameter_group.name

	username = var.username
	password = var.password
	
	publicly_accessible = false
	
	skip_final_snapshot = false
	final_snapshot_identifier = "finalsnapshot-${local.rds_name}"
	
	instance_class = var.instance_class
	
	performance_insights_enabled = true
	performance_insights_kms_key_id = aws_kms_key.this_key.arn
	performance_insights_retention_period = var.performance_insights_retention_period
	
	tags = {
		Name = local.rds_name
	}
}
```

### LINKED ISSUE #23673: RDS: Cross-region automated backups
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
In RDS it is possible to enable snapshots to be saved in another region besides the region the instance is in. This is helpful from a disaster recovery standpoint.

### New or Affected Resource(s)
* aws_db_instance
* aws_rds_cluster

### Potential Terraform Configuration

```hcl
resource "aws_db_instance" "default" {
  ...
  backup_replication_region = "us-west-2"
  backup_replication_period = 7
  backup_replication_kms_key_id = "11111111-aaaa-1111-aaaa-111111111111"
  ...
}
```

### References
* https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html
* https://github.com/aws/aws-sdk-go/pull/3675

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #23673.
Closes #16708.
Similar https://github.com/hashicorp/terraform-provider-aws/pull/20448.

Output from acceptance testing:

```
$ make testacc TESTS=TestAccRDSInstanceAutomatedBackupReplication_ PKG=rds                                                                             (base) 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccRDSInstanceAutomatedBackupReplication_'  -timeout 180m
=== RUN   TestAccRDSInstanceAutomatedBackupReplication_basic
=== PAUSE TestAccRDSInstanceAutomatedBackupReplication_basic
=== RUN   TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod
=== PAUSE TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod
=== RUN   TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted
=== PAUSE TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted
=== CONT  TestAccRDSInstanceAutomatedBackupReplication_basic
=== CONT  TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted
=== CONT  TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod
--- PASS: TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod (1112.49s)
--- PASS: TestAccRDSInstanceAutomatedBackupReplication_basic (1143.40s)
--- PASS: TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted (1166.08s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/rds        1166.316s
```

### CODE REVIEW

**Comment by bschaatsbergen** [comment]
@ewbankkit wanted to get some of your input here, the API is a bit poorly designed in my opinion. It's expected that this call is done from within the destination region (if you want to replicate backups from us-east-1 to us-west-2, I would have to declare the resource in us-west-2, pointing to a source_db_instance_arn in us-east-1). 

This conflicts a little bit with having to wait for the instance is 'available' after modifying..

At the moment I have this, which works fine but I still don't find it pretty that it has to be declared in the destination region.

```terraform
resource "aws_db_instance_backup_replication" "default" {
  source_db_instance_arn = "arn:aws:rds:eu-west-1:832224938332:db:database-1"
  kms_key_id             = "arn:aws:kms:eu-central-1:832224938332:key/example-key-id"
}

provider "aws" {
  region = "eu-central-1"
}
```

**Comment by YakDriver** [comment]
@bschaatsbergen We've run into this sort of thing in a few places. A recent one that I work on is here:
https://github.com/hashicorp/terraform-provider-aws/blob/928c293f71ef4ebb2ac70b01699431191db577e8/internal/service/rds/global_cluster.go#L580-L588

If it needs to wait on something in another region, my opinion is that it should wait the same, as though it were in the same region.

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen We've run into this sort of thing in a few places. A recent one that I worked on is here:
> 
> https://github.com/hashicorp/terraform-provider-aws/blob/928c293f71ef4ebb2ac70b01699431191db577e8/internal/service/rds/global_cluster.go#L580-L588
> 
> If it needs to wait on something in another region, my opinion is that it should wait the same, as though it were in the same region.

Thank you Yak! :)

**Comment by bschaatsbergen** [comment]
I believe it's ready for a review :sunglasses: @ewbankkit @YakDriver

**Comment by bschaatsbergen** [comment]
I believe this is ready for review..

cc @ewbankkit @YakDriver

**Comment by bschaatsbergen** [comment]
@ewbankkit, fixed the acceptance tests :+1:

**Comment by ewbankkit** [comment]
@bschaatsbergen In general everything was great.
The only significant change was to the wait after the call to `StopDBInstanceAutomatedBackupsReplication`. The long list of DB Instance statuses seemed quite brittle so I went with the approach of polling the DB Instance's list of `DBInstanceAutomatedBackupsReplications` until the required backup ARN is no longer present.

Do you know anything about the [`PreSignedUrl`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_StartDBInstanceAutomatedBackupsReplication.html#API_StartDBInstanceAutomatedBackupsReplication_RequestParameters) parameter? The [User Guide](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html#AutomatedBackups.Replicating.Enable) says

> If you encrypt the backups, you must also include a presigned URL.

but the `TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted` test case is currently passing without it.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccRDSInstanceAutomatedBackupReplication_ PKG=rds ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 2 -run='TestAccRDSInstanceAutomatedBackupReplication_'  -timeout 180m
=== RUN   TestAccRDSInstanceAutomatedBackupReplication_basic
=== PAUSE TestAccRDSInstanceAutomatedBackupReplication_basic
=== RUN   TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod
=== PAUSE TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod
=== RUN   TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted
=== PAUSE TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted
=== CONT  TestAccRDSInstanceAutomatedBackupReplication_basic
=== CONT  TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted
--- PASS: TestAccRDSInstanceAutomatedBackupReplication_basic (1439.87s)
=== CONT  TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod
--- PASS: TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted (1479.54s)
--- PASS: TestAccRDSInstanceAutomatedBackupReplication_retentionPeriod (1405.06s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	2854.272s
```

**Comment by bschaatsbergen** [comment]
> @bschaatsbergen In general everything was great. The only significant change was to the wait after the call to `StopDBInstanceAutomatedBackupsReplication`. The long list of DB Instance statuses seemed quite brittle so I went with the approach of polling the DB Instance's list of `DBInstanceAutomatedBackupsReplications` until the required backup ARN is no longer present.
> 
> Do you know anything about the [`PreSignedUrl`](https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_StartDBInstanceAutomatedBackupsReplication.html#API_StartDBInstanceAutomatedBackupsReplication_RequestParameters) parameter? The [User Guide](https://docs.aws.amazon.com/AmazonRDS/latest/UserGuide/USER_ReplicateBackups.html#AutomatedBackups.Replicating.Enable) says
> 
> > If you encrypt the backups, you must also include a presigned URL.
> 
> but the `TestAccRDSInstanceAutomatedBackupReplication_kmsEncrypted` test case is currently passing without it.
> 
> I see no harm in adding `presigned_url` as an optional argument (I'll do that).

Clear, regarding the `PreSignedUrl` parameter, I read the following when digging through the SDK

> PreSignedUrl
> //    **Specifying SourceRegion autogenerates a pre-signed URL** that
> //    is a valid request for the operation that can be executed in the source
> //    Amazon Web Services Region.
> 
> / SourceRegion is the source region where the resource exists. **This is not**
> 	// **sent over the wire and is only used for presigning**. This value should always
> 	// have the same region as the source ARN.
> 	SourceRegion *string `type:"string" ignore:"true"`

At first I was under the impression that this was handled internally if not specified. After taking a look at Event History in CloudTrail I didn't see any PreSignedUrl (explicitly setting it through the CLI it does show in the event) going over the wire even if the automated backup was encrypted. But indeed it's good to add :+1:

**Comment by ewbankkit** [comment]
OK, another change 😄. Renamed the resource to `aws_db_instance_automated_backups_replication` to match the underlying AWS API.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccRDSInstanceAutomatedBackupsReplication_ PKG=rds ACCTEST_PARALLELISM=2
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 2 -run='TestAccRDSInstanceAutomatedBackupsReplication_'  -timeout 180m
=== RUN   TestAccRDSInstanceAutomatedBackupsReplication_basic
=== PAUSE TestAccRDSInstanceAutomatedBackupsReplication_basic
=== RUN   TestAccRDSInstanceAutomatedBackupsReplication_retentionPeriod
=== PAUSE TestAccRDSInstanceAutomatedBackupsReplication_retentionPeriod
=== RUN   TestAccRDSInstanceAutomatedBackupsReplication_kmsEncrypted
=== PAUSE TestAccRDSInstanceAutomatedBackupsReplication_kmsEncrypted
=== CONT  TestAccRDSInstanceAutomatedBackupsReplication_basic
=== CONT  TestAccRDSInstanceAutomatedBackupsReplication_kmsEncrypted
--- PASS: TestAccRDSInstanceAutomatedBackupsReplication_basic (1188.64s)
=== CONT  TestAccRDSInstanceAutomatedBackupsReplication_retentionPeriod
--- PASS: TestAccRDSInstanceAutomatedBackupsReplication_kmsEncrypted (1249.54s)
--- PASS: TestAccRDSInstanceAutomatedBackupsReplication_retentionPeriod (1047.58s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	2240.134s
```

**Pull request merged**
