### PR TITLE
Update the Sagemaker Waiter Timeout for Creation from 10 to 60minutes

### PR DESCRIPTION
**Pull request by Ninir**
In some cases, it appears a sagemaker instance takes more than 10minutes to get created (even with the correct Secret being configured in Secret Manager).

Here are the logs:
```
aws_sagemaker_notebook_instance.main[0]: Still creating... [10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [1m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [1m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [1m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [1m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [1m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [1m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [2m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [2m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [2m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [2m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [2m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [2m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [3m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [3m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [3m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [3m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [3m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [3m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [4m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [4m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [4m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [4m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [4m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [4m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [5m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [5m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [5m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [5m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [5m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [5m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [6m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [6m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [6m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [6m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [6m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [6m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [7m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [7m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [7m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [7m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [7m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [7m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [8m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [8m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [8m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [8m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [8m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [8m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [9m0s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [9m10s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [9m20s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [9m30s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [9m40s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [9m50s elapsed]
aws_sagemaker_notebook_instance.main[0]: Still creating... [10m0s elapsed]

Error: error waiting for sagemaker notebook instance (test-instance) to create: timeout while waiting for state to become 'InService' (last state: 'Pending', timeout: 10m0s)
```

After a replan, the notebook instance is shown as "tainted", which needs to get fixed manually. Also, the Sagemaker Notebook instance appears to be created correctly and is InService on our side.

This work makes it possible to wait a bit more so that there is a plain success.
It is bumped to 60minutes since it's what is being "set" on the AWS Go SDK: https://github.com/aws/aws-sdk-go/blob/master/service/sagemaker/waiters.go#L82-L83

### CODE REVIEW

**Comment by DrFaust92** [comment]
Hey @Ninir, Looks good. can you resolve conflicts?

**Comment by Ninir** [comment]
@DrFaust92 Sure thing! it's done 🙇

**Review by DrFaust92 — APPROVED** [review]
LGTM

**Comment by breathingdust** [comment]
LGTM! 🚀 Thanks @Ninir!

**Pull request merged**
