### PR TITLE
Gen Client: servicecatalogappregistry

### PR DESCRIPTION
**Pull request by abebars**
- Ignore Vendored Packages
- Generate servicecatalogappregistry client

### Description
Generate Required client for `servicecatalogappregistry` resources
### Relations
relates #34702

### References

Add Service Client: https://hashicorp.github.io/terraform-provider-aws/add-a-new-service/#add-a-service-client

### CODE REVIEW

**Comment by fatbasstard** [comment]
@abebars Ola! Is there any way we can help to get this thing moving forward?

**Comment by abebars** [comment]
@fatbasstard I believe I will work on the resource once this PR is ready and merged. Can you help with that?

**Comment by fatbasstard** [comment]
Hi @johnsonaj @ewbankkit @YakDriver

I'm really looking forward for this functionality. You're the "last mergers" on these files... Can one of you take a look at this PR? 

Thanks in advance!

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@abebars Thanks for the contribution :tada: :clap:.

**Pull request merged**
