### PR TITLE
Migrate `controltower` service to `aws-sdk-go-v2`

### LINKED ISSUE #34558: [Enhancement]: Migrate `controltower` service to aws-sdk-go-v2
### Description

Relates to #32976

### Affected Resource(s) and/or Data Source(s)

aws_controltower_control

### Potential Terraform Configuration

_No response_

### References

_No response_

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by bschaatsbergen**
### Description

Some tech debt I'm addressing to support our migration to `aws-sdk-go-v2` and this unblocks the implementation of a new resource in #34557 

### Relations

Closes #34558.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/32976.

### Output from Acceptance Testing

```console
% make testacc TESTS= TestAccControlTower PKG=controltower

...
```

### CODE REVIEW

**Comment by aristosvo** [comment]
Hi @bschaatsbergen! I went already ahead (based on your work) with implementation of the `landing_zone`, as I was in dire need, see (this branch)[https://github.com/hashicorp/terraform-provider-aws/compare/main...aristosvo:terraform-provider-aws:controltower/landingzone?expand=1]. Feel free to copy or to stick to your own code, just wanted to let you know.

Do you already have any idea with regard to testing? I've done work on Azure, but especially with these kind of resources I'm lost on the testing part.

**Comment by bschaatsbergen** [comment]
> Hi @bschaatsbergen! I went already ahead (based on your work) with implementation of the `landing_zone`, as I was in dire need, see (this branch)[https://github.com/hashicorp/terraform-provider-aws/compare/main...aristosvo:terraform-provider-aws:controltower/landingzone?expand=1]. Feel free to copy or to stick to your own code, just wanted to let you know.
> 
> Do you already have any idea with regard to testing? I've done work on Azure, but especially with these kind of resources I'm lost on the testing part.

Hey @aristosvo - thanks for sharing this. Lets get this PR through in order to migrate the service to the `aws-sdk-go-v2` pkg and then create a follow-up PR to implement the `aws_controltower_landing_zone` resource using your code 👍🏼 !

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccControlTowerControlsDataSource_\|TestAccControlTowerControl_serial' PKG=controltower
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/controltower/... -v -count 1 -parallel 20  -run=TestAccControlTowerControlsDataSource_\|TestAccControlTowerControl_serial -timeout 360m
=== RUN   TestAccControlTowerControl_serial
=== PAUSE TestAccControlTowerControl_serial
=== RUN   TestAccControlTowerControlsDataSource_basic
=== PAUSE TestAccControlTowerControlsDataSource_basic
=== CONT  TestAccControlTowerControl_serial
=== RUN   TestAccControlTowerControl_serial/Control
=== RUN   TestAccControlTowerControl_serial/Control/disappears
=== CONT  TestAccControlTowerControlsDataSource_basic
--- PASS: TestAccControlTowerControlsDataSource_basic (23.06s)
=== RUN   TestAccControlTowerControl_serial/Control/basic
--- PASS: TestAccControlTowerControl_serial (446.58s)
    --- PASS: TestAccControlTowerControl_serial/Control (446.58s)
        --- PASS: TestAccControlTowerControl_serial/Control/disappears (221.97s)
        --- PASS: TestAccControlTowerControl_serial/Control/basic (224.61s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/controltower	451.750s
```

**Comment by ewbankkit** [comment]
@bschaatsbergen Thanks for the contribution :tada: :clap:.

**Pull request merged**
