### PR TITLE
Improve SC Portfolio consistency and reliability

### PR DESCRIPTION
**Pull request by ahgittin**
As part of adding new resources for Service Catalog in #13797 we reviewed the pre-existing SC Portfolio resource code.  There were a few items which were inconsistent with how things are named and done elsewhere and for consistency within the entire SC set of resources we've addressed that "technical debt".

These are minor changes but ensure that method names follow the same pattern.

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates #13797

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
NONE
```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSServiceCatalogPortfolio'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./... -v -count 1 -parallel 20 -run=TestAccAWSServiceCatalogPortfolio -timeout 120m
?   	github.com/terraform-providers/terraform-provider-aws	[no test files]
=== RUN   TestAccAWSServiceCatalogPortfolio_basic
=== PAUSE TestAccAWSServiceCatalogPortfolio_basic
=== RUN   TestAccAWSServiceCatalogPortfolio_disappears
=== PAUSE TestAccAWSServiceCatalogPortfolio_disappears
=== RUN   TestAccAWSServiceCatalogPortfolio_tags
=== PAUSE TestAccAWSServiceCatalogPortfolio_tags
=== CONT  TestAccAWSServiceCatalogPortfolio_basic
=== CONT  TestAccAWSServiceCatalogPortfolio_tags
=== CONT  TestAccAWSServiceCatalogPortfolio_disappears
--- PASS: TestAccAWSServiceCatalogPortfolio_disappears (16.60s)
--- PASS: TestAccAWSServiceCatalogPortfolio_basic (20.63s)
2020/06/22 14:49:27 DestroyEdgeTransformer: pruning unused resource node aws_servicecatalog_portfolio.test (prepare state)
--- PASS: TestAccAWSServiceCatalogPortfolio_tags (48.23s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	49.608s
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/flatmap	0.699s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/keyvaluetags	0.477s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/naming	0.481s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/apigatewayv2/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/batch/equivalency	1.003s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/ecs/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/eks/token	0.840s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/guardduty/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/iam/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kinesisanalytics/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/kms/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/neptune/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/rds/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/secretsmanager/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/servicediscovery/waiter	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/aws/internal/service/workspaces/waiter	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws/internal/tfawsresource	0.297s [no tests to run]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint	[no test files]
?   	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/helper/awsprovidertype/keyvaluetags	[no test files]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes	0.699s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSAT001	1.163s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR001	0.306s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/AWSR002	0.910s [no tests to run]
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/awsproviderlint/passes/fmtsprintfcallexpr	0.363s [no tests to run]
```

### CODE REVIEW

**Comment by ahgittin** [comment]
This PR also adds some guidance on using portfolios in practice, along with the associations (that are in the process of being created).

**Comment by ahgittin** [comment]
This has been updated as per the 18 Aug notification to use the v2 sdk and remove `aws.erb` (fixing the conflicts), and also updating to conform to the stricter markdown checks.

**Comment by YakDriver** [comment]
@ahgittin Thank you for your work on this PR! I will be working on this before long. In order to expedite the process, I will likely make some changes. Make sure that you have checked the box "Allow edits from maintainers." (Don't worry though, you will receive all credit for your contribution and code!) Also, please coordinate with us before making any commits to this branch. Again, thank you for your help and we look forward to this popular addition to the AWS provider!

**Comment by ahgittin** [comment]
Replaced by https://github.com/hashicorp/terraform-provider-aws/pull/18074

**Pull request closed without merging**
