### PR TITLE
[WIP] - Allow `suppressed_reasons` to be an empty list in order to overwrite the default suppressed reasons

### LINKED ISSUE #28669: [Bug]: SESv2: aws_sesv2_configuration_set does not allow empty list for suppressed_reasons to disable suppression list
### Terraform Core Version

1.3.6

### AWS Provider Version

4.48.0

### Affected Resource(s)

aws_sesv2_configuration_set

### Expected Behavior

Using the following configuration for the resource should allow a configuration set with the suppression list disabled to be created:

```
resource "aws_sesv2_configuration_set" "example" {
  configuration_set_name = "example"

  suppression_options {
    suppressed_reasons = []
  }
}
```

### Actual Behavior

The resource could not be created, because it expects at least one of `BOUNCE` and or `COMPLAINT` in the `suppressed_reasons` attribute

### Relevant Error/Panic Output Snippet

```shell
│ Error: Not enough list items
│
│   with aws_sesv2_configuration_set.test,
│   on main.tf line 21, in resource "aws_sesv2_configuration_set" "test":
│   21:     suppressed_reasons = []
│
│ Attribute suppression_options.0.suppressed_reasons requires 1 item minimum, but config has only 0 declared.
```
```


### Terraform Configuration Files

terraform {
  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 4.0"
    }
  }
}

# Configure the AWS Provider
provider "aws" {
  region = "us-east-1"
  access_key = var.access_key
  secret_key = var.secret_key
}

resource "aws_sesv2_configuration_set" "test" {
  configuration_set_name = "example"

  suppression_options {
    suppressed_reasons = []
  }
}

### Steps to Reproduce

Run `terraform apply` with the above configuration file.

### Debug Output

https://gist.github.com/F21/7ce1daa2846d55827d6e19664fcdc0df

### Panic Output

_No response_

### Important Factoids

_No response_

### References

https://github.com/hashicorp/terraform-provider-aws/issues/26796

### Would you like to implement a fix?

None

### PR DESCRIPTION
**Pull request by bschaatsbergen**
Closes #28669

### Relations

Closes #0000

### Output from Acceptance Testing

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by F21** [comment]
I made some attempts to try and allow empty lists for the `suppression_reasons` attribute in a local build, but it seems to be a lot more involved than removing `MinItems` here: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sesv2/configuration_set.go#L110

For some reason, the value from `d.GetOk("suppression_options")` is `[<nil>]`, rather than `[map[suppressed_reasons:[]]]` when setting suppression reasons to an empty list here: https://github.com/hashicorp/terraform-provider-aws/blob/main/internal/service/sesv2/configuration_set.go#L163

From testing against my AWS account, just removing `MinItems` did not override the account level suppression list settings correctly.

**Comment by bschaatsbergen** [comment]
I've put out the draft and will follow up this week @F21, thanks for the detailed input.

**Comment by F21** [comment]
Thanks for looking at this@bschaatsbergen! I spent most of yesterday looking at this and it was driving me mad, glad to have a second pair of eyes looking at this.

**Comment by bschaatsbergen** [comment]
Any suggestions on the above @ewbankkit ?

**Comment by ewbankkit** [comment]
Try changing [`expandSuppressionOptions`](https://github.com/hashicorp/terraform-provider-aws/blob/5fd8df3d1b18a84b7a4d70bb831438d84f3c1a66/internal/service/sesv2/configuration_set.go#L569-L581) to

```go
func expandSuppressionOptions(tfMap map[string]interface{}) *types.SuppressionOptions {
	if tfMap == nil {
		return nil
	}

	a := &types.SuppressionOptions{}

	if v, ok := tfMap["suppressed_reasons"].([]interface{}); ok {
		if len(v) > 0 {
			a.SuppressedReasons = expandSuppressedReasons(v)
		} else {
			a.SuppressedReasons = []types.SuppressionListReason
		}
	}

	return a
}
```

**Comment by bschaatsbergen** [comment]
@ewbankkit - I have the feeling that the SDK checks whether `SuppressedReasons` is empty or not, as when setting an empty slice it doesn't seem to become part of the CreateConfigurationSet API call.

```
  "requestParameters": {
        "configurationSetName": "tf-acc-test-4803928077497064113"
    },
```

**Comment by bschaatsbergen** [comment]
Hi @F21, I haven't looked at this PR in a while. Have you made any progress on your side with this?

**Comment by F21** [comment]
@bschaatsbergen My PR #29671 fixes the issue, but I am still waiting for it to be reviewed.

**Pull request closed without merging**
