### PR TITLE
New Data Source: aws_vpc_public_ipv4_pools

### PR DESCRIPTION
**Pull request by gatsbysghost**
### Description
(Note: I originally raised this as Draft PR #28203, but I accidentally broke git on that & so just decided to start over here with the ready-for-review PR).

Presently, there are some gaps in coverage relating to IPv4 Pools. #17425 raises the following user story (among others):

> As an IaC engineer, I want to be able to get a list of IPv4 address pools we've added to a specific AWS account via BYOIP so that we can utilise the ranges programatically in the remaining infrastructure.

This gap impacted my org as well (and I have seen several random users on various sites requesting this particular feature), which is why I am submitting this PR, in part-fulfillment of the needs of #17425.

This PR therefore adds the following items:
1. A new data source (located in the VPC section of the docs, but in the ec2 service directory) called `aws_vpc_public_ipv4_pools`
2. Tests and docs for the foregoing data source.

### Relations
Relates #17425

### Output from Acceptance Testing

n/a (not possible to run because it requires access to public IPv4 addresses). I should note here that **all existing tests for BYOIP AND all IPAM variations simply skip any kind of AccTest for public IPv4 addresses, for obvious reasons.** There's really nothing I can see in the existing framework to to pattern this approach off of, and I'm struggling to think how we would do this--apart from, e.g., spoofing the existence of public IPv4 pools in the tfstate.

per @ewbankkit (https://github.com/hashicorp/terraform-provider-aws/pull/28203#issuecomment-1340928787):

> The HashiCorp maintainers don't have access to BYOIP functionality so in such cases we will:
> 
> 1. Make sure that if the changes affect other resources, ensure there are no regressions
> 2. Do a code review
> 3. Solicit the community for testing
> 4. Release the functionality "as-is" (with text in the release notes) and encourage practitioner feedback

### CODE REVIEW

**Comment by gatsbysghost** [comment]
(For the record: after this most recent commit ^^, I _think_ I am passing all lint checks again).

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccEC2PublicIPv4Pool' PKG=ec2 ACCTEST_PARALLELISM=3 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 3  -run=TestAccEC2PublicIPv4Pool -timeout 180m
=== RUN   TestAccEC2PublicIPv4PoolDataSource_basic
=== PAUSE TestAccEC2PublicIPv4PoolDataSource_basic
=== RUN   TestAccEC2PublicIPv4PoolsDataSource_basic
=== PAUSE TestAccEC2PublicIPv4PoolsDataSource_basic
=== RUN   TestAccEC2PublicIPv4PoolsDataSource_tags
=== PAUSE TestAccEC2PublicIPv4PoolsDataSource_tags
=== CONT  TestAccEC2PublicIPv4PoolDataSource_basic
=== CONT  TestAccEC2PublicIPv4PoolsDataSource_tags
=== CONT  TestAccEC2PublicIPv4PoolsDataSource_basic
=== CONT  TestAccEC2PublicIPv4PoolDataSource_basic
    ec2_public_ipv4_pool_data_source_test.go:49: skipping since no EC2 Public IPv4 Pools found
--- SKIP: TestAccEC2PublicIPv4PoolDataSource_basic (0.84s)
--- PASS: TestAccEC2PublicIPv4PoolsDataSource_basic (12.61s)
--- PASS: TestAccEC2PublicIPv4PoolsDataSource_tags (12.62s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/ec2	17.951s
```

**Comment by ewbankkit** [comment]
@gatsbysghost Thanks for the contribution :tada: :clap:.
I renamed the data sources to `aws_ec2_public_ipv4_pool` and `aws_ec2_public_ipv4_pools` as the underlying AWS API used is listed in the [Amazon EC2 actions](https://docs.aws.amazon.com/AWSEC2/latest/APIReference/OperationList-query-ec2.html) section of the documentation.
I also modified the attributes returned to better match our pattern of the plural data source returning just a list of IDs and the singular data source accepting a single ID and returning all the attributes for the specified resource.

**Comment by gatsbysghost** [comment]
@ewbankkit Fab! Thank you so much for your help! 😁

**Pull request merged**
