### PR TITLE
r/aws_kinesis_stream: add stream_mode attribute

### LINKED ISSUE #21972: r/aws_kinesis_stream: support on-demand capacity mode
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the on-demand capacity mode of Kinesis Data Streams. It seems this feature hasn't landed in the Go SDK yet.

This will require that the `shard_count` be optional, as it cannot be passed when `stream_mode` is `PROVISIONED`.

### New or Affected Resource(s)

* aws_kinesis_stream

### Potential Terraform Configuration

```hcl
resource "aws_kinesis_stream" "test_stream" {
  name = "example"

  stream_mode_details {
    stream_mode = "PROVISIONED"
  }
}
```

### References

* https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-kinesis-data-streams-on-demand/
* https://docs.aws.amazon.com/streams/latest/dev/how-do-i-size-a-stream.html
* https://docs.aws.amazon.com/kinesis/latest/APIReference/API_CreateStream.html

### PR DESCRIPTION
**Pull request by roberth-k**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #21972

Note that this PR flattens the `stream_mode_details`, i.e. `stream_mode` is a top-level attribute of `aws_kinesis_stream`.

Output from acceptance testing:

```
$ make testacc PKG=kinesis TESTS=TestAccKinesisStream_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kinesis/... -v -count 1 -parallel 20 -run='TestAccKinesisStream_' -timeout 180m
=== RUN   TestAccKinesisStream_basic
=== PAUSE TestAccKinesisStream_basic
=== RUN   TestAccKinesisStream_createMultipleConcurrentStreams
=== PAUSE TestAccKinesisStream_createMultipleConcurrentStreams
=== RUN   TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError
=== PAUSE TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError
=== RUN   TestAccKinesisStream_encryption
=== PAUSE TestAccKinesisStream_encryption
=== RUN   TestAccKinesisStream_shardCount
=== PAUSE TestAccKinesisStream_shardCount
=== RUN   TestAccKinesisStream_retentionPeriod
=== PAUSE TestAccKinesisStream_retentionPeriod
=== RUN   TestAccKinesisStream_shardLevelMetrics
=== PAUSE TestAccKinesisStream_shardLevelMetrics
=== RUN   TestAccKinesisStream_enforceConsumerDeletion
=== PAUSE TestAccKinesisStream_enforceConsumerDeletion
=== RUN   TestAccKinesisStream_tags
=== PAUSE TestAccKinesisStream_tags
=== RUN   TestAccKinesisStream_updateKMSKeyID
=== PAUSE TestAccKinesisStream_updateKMSKeyID
=== RUN   TestAccKinesisStream_basicOnDemand
=== PAUSE TestAccKinesisStream_basicOnDemand
=== RUN   TestAccKinesisStream_switchBetweenProvisionedAndOnDemand
=== PAUSE TestAccKinesisStream_switchBetweenProvisionedAndOnDemand
=== RUN   TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination
=== PAUSE TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination
=== CONT  TestAccKinesisStream_basic
=== CONT  TestAccKinesisStream_enforceConsumerDeletion
=== CONT  TestAccKinesisStream_basicOnDemand
=== CONT  TestAccKinesisStream_createMultipleConcurrentStreams
=== CONT  TestAccKinesisStream_updateKMSKeyID
=== CONT  TestAccKinesisStream_tags
=== CONT  TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError
=== CONT  TestAccKinesisStream_shardCount
=== CONT  TestAccKinesisStream_shardLevelMetrics
=== CONT  TestAccKinesisStream_encryption
=== CONT  TestAccKinesisStream_retentionPeriod
=== CONT  TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination
=== CONT  TestAccKinesisStream_switchBetweenProvisionedAndOnDemand
--- PASS: TestAccKinesisStream_basicOnDemand (64.85s)
--- PASS: TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError (66.67s)
--- PASS: TestAccKinesisStream_enforceConsumerDeletion (76.72s)
--- PASS: TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination (97.42s)
--- PASS: TestAccKinesisStream_basic (101.60s)
--- PASS: TestAccKinesisStream_retentionPeriod (123.84s)
--- PASS: TestAccKinesisStream_shardCount (131.42s)
--- PASS: TestAccKinesisStream_updateKMSKeyID (143.66s)
--- PASS: TestAccKinesisStream_shardLevelMetrics (144.77s)
--- PASS: TestAccKinesisStream_createMultipleConcurrentStreams (166.42s)
--- PASS: TestAccKinesisStream_tags (174.10s)
--- PASS: TestAccKinesisStream_encryption (179.46s)
--- PASS: TestAccKinesisStream_switchBetweenProvisionedAndOnDemand (237.45s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesis    239.318s

$ make testacc PKG=kinesis TESTS=TestAccKinesisStreamDataSource_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kinesis/... -v -count 1 -parallel 20 -run='TestAccKinesisStreamDataSource_' -timeout 180m
=== RUN   TestAccKinesisStreamDataSource_basic
=== PAUSE TestAccKinesisStreamDataSource_basic
=== CONT  TestAccKinesisStreamDataSource_basic
--- PASS: TestAccKinesisStreamDataSource_basic (128.87s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/kinesis    130.742s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
@xxx Thanks for the contribution :tada: :clap:.
We do prefer that attributes do not get flattened. Could you please update this PR to define the attribute as

```go
"stream_mode_details": {
	Type:     schema.TypeList,
	Optional: true,
	MaxItems: 1,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
            "stream_mode": {
				Type:         schema.TypeString,
				Optional:     true,
				Default:      kinesis.StreamModeProvisioned,
				ValidateFunc: validation.StringInSlice(kinesis.StreamMode_Values(), false),
			},
		},
	},
},
```

**Comment by roberth-k** [comment]
@ewbankkit That's now been introduced.

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc PKG=kinesis TESTS=TestAccKinesisStream_  
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kinesis/... -v -count 1 -parallel 20 -run='TestAccKinesisStream_' -timeout 180m
=== RUN   TestAccKinesisStream_basic
=== PAUSE TestAccKinesisStream_basic
=== RUN   TestAccKinesisStream_disappears
=== PAUSE TestAccKinesisStream_disappears
=== RUN   TestAccKinesisStream_createMultipleConcurrentStreams
=== PAUSE TestAccKinesisStream_createMultipleConcurrentStreams
=== RUN   TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError
=== PAUSE TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError
=== RUN   TestAccKinesisStream_encryption
=== PAUSE TestAccKinesisStream_encryption
=== RUN   TestAccKinesisStream_shardCount
=== PAUSE TestAccKinesisStream_shardCount
=== RUN   TestAccKinesisStream_retentionPeriod
=== PAUSE TestAccKinesisStream_retentionPeriod
=== RUN   TestAccKinesisStream_shardLevelMetrics
=== PAUSE TestAccKinesisStream_shardLevelMetrics
=== RUN   TestAccKinesisStream_enforceConsumerDeletion
=== PAUSE TestAccKinesisStream_enforceConsumerDeletion
=== RUN   TestAccKinesisStream_tags
=== PAUSE TestAccKinesisStream_tags
=== RUN   TestAccKinesisStream_updateKMSKeyID
=== PAUSE TestAccKinesisStream_updateKMSKeyID
=== RUN   TestAccKinesisStream_basicOnDemand
=== PAUSE TestAccKinesisStream_basicOnDemand
=== RUN   TestAccKinesisStream_switchBetweenProvisionedAndOnDemand
=== PAUSE TestAccKinesisStream_switchBetweenProvisionedAndOnDemand
=== RUN   TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination
=== PAUSE TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination
=== CONT  TestAccKinesisStream_basic
=== CONT  TestAccKinesisStream_enforceConsumerDeletion
=== CONT  TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError
=== CONT  TestAccKinesisStream_disappears
=== CONT  TestAccKinesisStream_encryption
=== CONT  TestAccKinesisStream_shardLevelMetrics
=== CONT  TestAccKinesisStream_retentionPeriod
=== CONT  TestAccKinesisStream_switchBetweenProvisionedAndOnDemand
=== CONT  TestAccKinesisStream_shardCount
=== CONT  TestAccKinesisStream_updateKMSKeyID
=== CONT  TestAccKinesisStream_createMultipleConcurrentStreams
=== CONT  TestAccKinesisStream_basicOnDemand
=== CONT  TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination
=== CONT  TestAccKinesisStream_tags
--- PASS: TestAccKinesisStream_encryptionWithoutKMSKeyThrowsError (44.74s)
--- PASS: TestAccKinesisStream_basic (54.06s)
--- PASS: TestAccKinesisStream_basicOnDemand (54.12s)
--- PASS: TestAccKinesisStream_enforceConsumerDeletion (54.13s)
--- PASS: TestAccKinesisStream_disappears (61.82s)
--- PASS: TestAccKinesisStream_failOnBadStreamCountAndStreamModeCombination (70.00s)
--- PASS: TestAccKinesisStream_shardCount (95.36s)
--- PASS: TestAccKinesisStream_shardLevelMetrics (108.61s)
--- PASS: TestAccKinesisStream_encryption (131.75s)
--- PASS: TestAccKinesisStream_tags (132.09s)
--- PASS: TestAccKinesisStream_updateKMSKeyID (134.18s)
--- PASS: TestAccKinesisStream_retentionPeriod (142.53s)
--- PASS: TestAccKinesisStream_switchBetweenProvisionedAndOnDemand (191.17s)
--- PASS: TestAccKinesisStream_createMultipleConcurrentStreams (195.74s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesis	199.328s
% make testacc PKG=kinesis TESTS=TestAccKinesisStreamDataSource_
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/kinesis/... -v -count 1 -parallel 20 -run='TestAccKinesisStreamDataSource_' -timeout 180m
=== RUN   TestAccKinesisStreamDataSource_basic
=== PAUSE TestAccKinesisStreamDataSource_basic
=== CONT  TestAccKinesisStreamDataSource_basic
--- PASS: TestAccKinesisStreamDataSource_basic (105.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/kinesis	112.345s
```

**Comment by ewbankkit** [comment]
@roberth-k Thanks for the contribution :tada: :clap:.

**Comment by palani-ram-google-partner** [comment]
@ewbankkit @roberth-k Thank you so much for quickly putting this feature together. we are waiting for this feature Can we know the release date for v3.69.0 ?

**Comment by rpalanisamy** [comment]
@roberth-k , @ewbankkit , Thank you so much for putting this feature together. we are actually waiting for this release. when can we expect the release v3.69.0 in GA ?

**Comment by ewbankkit** [comment]
We usually release on [Thursdays](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/faq.md#how-often-do-you-release).

**Pull request merged**
