### PR TITLE
Fix for issue #11343

### LINKED ISSUE #11343: Allow parametrization for unregistration of all targets in target groups when attaching instance/ip to target group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Having looked at the [aws/resource_aws_lb_target_group_attachment.go](./aws/resource_aws_lb_target_group_attachment.go) code and considering the fact that by default, AWS/terraform-aws-provider (don't know which one) assigns all spawned instances in an Autoscaling group to all listeners in target group, it might be interesting to add an extra argument which, if specified to non-default false value, cleans up all existing attached targets prior to register the give one. Currently, without this argument the list of targets remain unchanged

### New or Affected Resource(s)

* aws_lb_target_group_attachment

### Potential Terraform Configuration

```hcl
resource "aws_lb_target_group_attachment" "monitoring" {
    count            = "${var.monitoring_enable * var.cluster_size}"
    target_group_arn = "${element(aws_lb_target_group.monitoring.*.arn, count.index)}"
    target_id        = "${element(data.aws_instances.asg_instances.ids, count.index)}"
    port             = 12345
    replace_all_targets = true
 }
```

### References

None

### PR DESCRIPTION
**Pull request by obourdon**
Cleans up all existing attached targets prior to
register the new given one

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #11343

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Add parameter to clean up all existing attached targets prior to
register a new one
```

### CODE REVIEW

**Comment by obourdon** [comment]
In which zone should I pass the acceptance tests because when I try to specify one like eu-west-1 us-east-1 or us-west-1 I get an error saying AMI ami-f701cb97 does not exist and if I used the default zone (I guess it is us-west-2) I get:
```
        Error: Error launching source instance: Unsupported: Your requested instance type (t2.micro) is not supported in your requested Availability Zone (us-west-2d). Please retry your request by not specifying an Availability Zone or choosing us-west-2a, us-west-2b, us-west-2c.
```

**Comment by obourdon** [comment]
In the meantime I have modified aws/resource_aws_lb_target_group_attachment_test.go locally to have the AMI corresponding to ubuntu/images/hvm-ssd/ubuntu-xenial-16.04-amd64-server-20160815 within my default zone of eu-west-1 and managed to get the results:
```
AWS_DEFAULT_REGION=eu-west-1 make testacc TEST=./aws TESTARGS='-run=TestAccAWSLBTargetGroupAttachment'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSLBTargetGroupAttachment -timeout 120m
=== RUN   TestAccAWSLBTargetGroupAttachment_basic
=== PAUSE TestAccAWSLBTargetGroupAttachment_basic
=== RUN   TestAccAWSLBTargetGroupAttachment_disappears
=== PAUSE TestAccAWSLBTargetGroupAttachment_disappears
=== RUN   TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility
=== PAUSE TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility
=== RUN   TestAccAWSLBTargetGroupAttachment_withoutPort
=== PAUSE TestAccAWSLBTargetGroupAttachment_withoutPort
=== RUN   TestAccAWSLBTargetGroupAttachment_ipAddress
=== PAUSE TestAccAWSLBTargetGroupAttachment_ipAddress
=== RUN   TestAccAWSLBTargetGroupAttachment_lambda
=== PAUSE TestAccAWSLBTargetGroupAttachment_lambda
=== CONT  TestAccAWSLBTargetGroupAttachment_basic
=== CONT  TestAccAWSLBTargetGroupAttachment_ipAddress
=== CONT  TestAccAWSLBTargetGroupAttachment_withoutPort
=== CONT  TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility
=== CONT  TestAccAWSLBTargetGroupAttachment_disappears
=== CONT  TestAccAWSLBTargetGroupAttachment_lambda
--- PASS: TestAccAWSLBTargetGroupAttachment_lambda (47.35s)
--- PASS: TestAccAWSLBTargetGroupAttachment_BackwardsCompatibility (92.88s)
--- PASS: TestAccAWSLBTargetGroupAttachment_withoutPort (92.90s)
--- PASS: TestAccAWSLBTargetGroupAttachment_basic (92.91s)
--- PASS: TestAccAWSLBTargetGroupAttachment_disappears (112.43s)
--- PASS: TestAccAWSLBTargetGroupAttachment_ipAddress (297.41s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	297.502s
```

**Comment by obourdon** [comment]
Currently trying to fix new test, all help welcome

**Comment by obourdon** [comment]
If anyone could help me with the test, that would be awesome. I understand that[ these lines](https://github.com/obourdon/terraform-provider-aws/blob/fix-11343/aws/resource_aws_lb_target_group_attachment_test.go#L491:L496) will directly impact [the resources defined in these other lines](https://github.com/obourdon/terraform-provider-aws/blob/fix-11343/aws/resource_aws_lb_target_group_attachment_test.go#L432:L437) by deleting indexes 1 and 2 and was wondering if there was a way to mention this somehow in the [test steps definitions defined here](https://github.com/obourdon/terraform-provider-aws/blob/fix-11343/aws/resource_aws_lb_target_group_attachment_test.go#L43:L66).
Tried to browse through other _test.go files without much success
I know there is another way to achieve this without specifying target group attachements and using only ASGs + target group but wanted to know if this kind of case was already implemented
Thanks for any help, pointer, insights, ...

**Comment by bflad** [comment]
Hi @obourdon 👋 Please note that I'm passing by just to triage this pull request with labels and that I marked it with `proposal` since we discourage resources that directly cause side-effects of other infrastructure unless it is a parent-child relationship. It may be best to instead introduce an `attachments` argument to the `aws_lb_target_group` resource (Optional + Computed).

**Pull request closed without merging**
