### PR TITLE
r/cloudwatch_log_metric_filter - add `unit`

### LINKED ISSUE #19800: aws_cloudwatch_log_metric_filter - missing atribute unit
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In resource aws_cloudwatch_log_metric_filter there is currently not possible to define Unit.

The unit field exists in AWS GUI form:
image

### New or Affected Resource(s)

aws_cloudwatch_log_metric_filter

### Potential Terraform Configuration

resource "aws_cloudwatch_log_metric_filter" "" {
  name                      = ""
  pattern         = ""
  log_group_name   = ""
  metric_transformation {
    name           = ""
    namespace         = ""
    value            = ""
    default_value     = ""
    unit                   =   "  UNIT_NAME "
  }
}

### References

Currently atribute Unit does not exist in the documentation:
https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/cloudwatch_log_metric_filter

### PR DESCRIPTION
**Pull request by DrFaust92**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #19800

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccAWSCloudWatchLogMetricFilter_'
--- PASS: TestAccAWSCloudWatchLogMetricFilter_disappears (38.42s)
--- PASS: TestAccAWSCloudWatchLogMetricFilter_basic (226.30s)
--- PASS: TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup (28.00s)
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

##### Commercial

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSCloudWatchLogMetricFilter_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudWatchLogMetricFilter_ -timeout 180m
=== RUN   TestAccAWSCloudWatchLogMetricFilter_basic
=== PAUSE TestAccAWSCloudWatchLogMetricFilter_basic
=== RUN   TestAccAWSCloudWatchLogMetricFilter_disappears
=== PAUSE TestAccAWSCloudWatchLogMetricFilter_disappears
=== RUN   TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup
=== PAUSE TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup
=== CONT  TestAccAWSCloudWatchLogMetricFilter_basic
=== CONT  TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup
=== CONT  TestAccAWSCloudWatchLogMetricFilter_disappears
--- PASS: TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup (13.09s)
--- PASS: TestAccAWSCloudWatchLogMetricFilter_disappears (15.38s)
--- PASS: TestAccAWSCloudWatchLogMetricFilter_basic (76.04s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	79.514s
```

##### GovCloud

```console
% make testacc TEST=./aws TESTARGS='-run=TestAccAWSCloudWatchLogMetricFilter_'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSCloudWatchLogMetricFilter_ -timeout 180m
=== RUN   TestAccAWSCloudWatchLogMetricFilter_basic
=== PAUSE TestAccAWSCloudWatchLogMetricFilter_basic
=== RUN   TestAccAWSCloudWatchLogMetricFilter_disappears
=== PAUSE TestAccAWSCloudWatchLogMetricFilter_disappears
=== RUN   TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup
=== PAUSE TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup
=== CONT  TestAccAWSCloudWatchLogMetricFilter_basic
=== CONT  TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup
=== CONT  TestAccAWSCloudWatchLogMetricFilter_disappears
--- PASS: TestAccAWSCloudWatchLogMetricFilter_disappears_logGroup (14.44s)
--- PASS: TestAccAWSCloudWatchLogMetricFilter_disappears (16.96s)
--- PASS: TestAccAWSCloudWatchLogMetricFilter_basic (87.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	90.376s
```

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Comment by tdmalone** [comment]
Getting spurious diffs from this change in the latest version of the provider:
```
build	18-Jun-2021 08:33:00	  # aws_cloudwatch_log_metric_filter.functionbeat_ingest_failures["cloudwatch-logs"] will be updated in-place
build	18-Jun-2021 08:33:00	  ~ resource "aws_cloudwatch_log_metric_filter" "functionbeat_ingest_failures"
build	18-Jun-2021 08:33:00	
build	18-Jun-2021 08:33:00	      ~ metric_transformation
build	18-Jun-2021 08:33:00	          + unit          = "None"
build	18-Jun-2021 08:33:00	
build	18-Jun-2021 08:33:00	  # aws_cloudwatch_log_metric_filter.functionbeat_ingest_failures["dlq"] will be updated in-place
build	18-Jun-2021 08:33:00	  ~ resource "aws_cloudwatch_log_metric_filter" "functionbeat_ingest_failures"
build	18-Jun-2021 08:33:00	
build	18-Jun-2021 08:33:00	      ~ metric_transformation
build	18-Jun-2021 08:33:00	          + unit          = "None"
build	18-Jun-2021 08:33:00	
build	18-Jun-2021 08:33:00	  # aws_cloudwatch_log_metric_filter.functionbeat_ingest_failures["sqs"] will be updated in-place
build	18-Jun-2021 08:33:00	  ~ resource "aws_cloudwatch_log_metric_filter" "functionbeat_ingest_failures"
build	18-Jun-2021 08:33:00	
build	18-Jun-2021 08:33:00	      ~ metric_transformation
build	18-Jun-2021 08:33:00	          + unit          = "None"
build	18-Jun-2021 08:33:00	
build	18-Jun-2021 08:33:00	Plan: 0 to add, 3 to change, 0 to destroy.
```

**Comment by ewbankkit** [comment]
@tdmalone Applying the planned change _should_ cause no difference in functionality as the [API Reference](https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_MetricTransformation.html#CWL-Type-MetricTransformation-unit) states
> If you omit this, the unit is set as `None`.

Before:

Screen Shot 2021-06-18 at 9 15 01 AM

After:

Screen Shot 2021-06-18 at 9 16 04 AM

Feel free to raise an issue linking to this PR if necessary.
Thanks.

**Pull request merged**
