### PR TITLE
add aws_appfabric_ingestion_destination resource

### PR DESCRIPTION
**Pull request by professional-ian**
### Description

This pr adds a resource for aws_appfabric_ingestion_destination

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/34549.

### References

https://docs.aws.amazon.com/appfabric/latest/api/API_CreateIngestionDestination.html

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccAppFabricIngestionDestination PKG=appfabric
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.21.8 test ./internal/service/appfabric/... -v -count 1 -parallel 20 -run='TestAccAppFabricIngestionDestination'  -timeout 360m
=== RUN   TestAccAppFabricIngestionDestination_basic
=== PAUSE TestAccAppFabricIngestionDestination_basic
=== RUN   TestAccAppFabricIngestionDestination_firehose
--- PASS: TestAccAppFabricIngestionDestination_firehose (10.18s)
=== RUN   TestAccAppFabricIngestionDestination_destinationUpdate
=== PAUSE TestAccAppFabricIngestionDestination_destinationUpdate
=== RUN   TestAccAppFabricIngestionDestination_disappears
=== PAUSE TestAccAppFabricIngestionDestination_disappears
=== CONT  TestAccAppFabricIngestionDestination_basic
=== CONT  TestAccAppFabricIngestionDestination_disappears
=== CONT  TestAccAppFabricIngestionDestination_destinationUpdate
--- PASS: TestAccAppFabricIngestionDestination_disappears (10.71s)
--- PASS: TestAccAppFabricIngestionDestination_basic (12.63s)
--- PASS: TestAccAppFabricIngestionDestination_destinationUpdate (19.96s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/appfabric  36.599s
```

### CODE REVIEW

**Review by meetreks — COMMENTED** [review]
Looks good now. I think we are still missing change log and html documentation,

**Review by meetreks — APPROVED** [review]
Very good first contribution. A few things to check
1. Has the tests covered all possible API values populated even though they are optional?
2. Similar comment for fields which can be updated.
3.  you can move all wait code to a separate file

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% AWS_APPFABRIC_TERRAFORMCLOUD_TENANT_ID=... AWS_APPFABRIC_TERRAFORMCLOUD_SERVICE_ACCOUNT_TOKEN=... AWS_DEFAULT_REGION=us-east-1 make testacc TESTARGS='-run=TestAccAppFabric_serial/IngestionDestination' PKG=appfabric 
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.22.4 test ./internal/service/appfabric/... -v -count 1 -parallel 20  -run=TestAccAppFabric_serial/IngestionDestination -timeout 360m
=== RUN   TestAccAppFabric_serial
=== PAUSE TestAccAppFabric_serial
=== CONT  TestAccAppFabric_serial
=== RUN   TestAccAppFabric_serial/IngestionDestination
=== RUN   TestAccAppFabric_serial/IngestionDestination/tags
=== RUN   TestAccAppFabric_serial/IngestionDestination/update
=== RUN   TestAccAppFabric_serial/IngestionDestination/firehose
=== RUN   TestAccAppFabric_serial/IngestionDestination/basic
=== RUN   TestAccAppFabric_serial/IngestionDestination/disappears
--- PASS: TestAccAppFabric_serial (223.51s)
    --- PASS: TestAccAppFabric_serial/IngestionDestination (223.51s)
        --- PASS: TestAccAppFabric_serial/IngestionDestination/tags (35.35s)
        --- PASS: TestAccAppFabric_serial/IngestionDestination/update (28.53s)
        --- PASS: TestAccAppFabric_serial/IngestionDestination/firehose (110.26s)
        --- PASS: TestAccAppFabric_serial/IngestionDestination/basic (21.80s)
        --- PASS: TestAccAppFabric_serial/IngestionDestination/disappears (20.22s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appfabric	227.813s
```

**Comment by ewbankkit** [comment]
@professional-ian Thanks for the contribution :tada: :clap:.

**Pull request merged**
