### PR TITLE
f/aws_config_remediation_configuration: Support for automatic remedia…

### LINKED ISSUE #15491: aws_config_remediation_configuration: No support for "automatic" remediation
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to be able to configure a aws_config_remediation_configuration resource of type "automatic", see: https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-remediationconfiguration.html

### New or Affected Resource(s)

* aws_config_remediation_configuration

### Potential Terraform Configuration

```hcl
resource "aws_config_remediation_configuration" "this" {
  type = automatic
  config_rule_name = aws_config_config_rule.this.name
  resource_type    = "AWS::S3::Bucket"
  target_type      = "SSM_DOCUMENT"
  target_id        = "AWS-EnableS3BucketEncryption"
  target_version   = "1"

  parameter {
    name         = "AutomationAssumeRole"
    static_value = "arn:aws:iam::875924563244:role/security_config"
  }
  parameter {
    name           = "BucketName"
    resource_value = "RESOURCE_ID"
  }
  parameter {
    name         = "SSEAlgorithm"
    static_value = "AES256"
  }
}```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-config-remediationconfiguration.html

### PR DESCRIPTION
**Pull request by nikhil-goenka**
…tion

### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Relates OR Closes #15491

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note

```

Output from acceptance testing:

```
$ make testacc TESTARGS='-run=TestAccXXX'

...
```

### CODE REVIEW

**Comment by susumutomita** [comment]
It looks we need to set maximum_automatic_attempts and retry_attempt_seconds as well.
I also little bit modify your fix, and it works in my local environment.
Can I send another pull request?

**Comment by nikhil-goenka** [comment]
> Thank you for your work.
> It looks we need to set maximum_automatic_attempts and retry_attempt_seconds as well.
> I also little bit modify your fix, and it works in my local environment.
> Can I send another pull request?

thank you
I am not able to see those variables in AWS api, can you please elaborate more on them ?

**Comment by susumutomita** [comment]
Yes I can.
Please read https://docs.aws.amazon.com/config/latest/APIReference/API_RemediationConfiguration.html#config-Type-RemediationConfiguration-Automatic

**Comment by nikhil-goenka** [comment]
> Yes I can.
> Please read https://docs.aws.amazon.com/config/latest/APIReference/API_RemediationConfiguration.html#config-Type-RemediationConfiguration-Automatic

ok ya, we need to set those as well, but sending another PR will create a duplicate one.
if it fine with you then you can commit in the change in the current PR.

**Comment by EiZei** [comment]
Been trying to implement remediation in aws config and this terraform resource is pretty useless without this feature

**Comment by japrakash-contino** [comment]
Is there any update on this ticket? I am also looking for this feature and without it there is no use of it.

**Comment by nikhil-goenka** [comment]
@bflad @DrFaust92 @gdavison : Hey guys, can we get this reviewed and closed, lately it has been gaining a lot of attention.

**Comment by nakulpathak3** [comment]
Not a moderator but I am just curious, are there any updates needed to https://github.com/hashicorp/terraform-provider-aws/blob/dff8af6af2a3cfe1dc1ab9d3d376943e8b594fc1/aws/resource_aws_config_remediation_configuration_test.go?

**Review by nakulpathak3 — COMMENTED** [review]
Not a moderator but I am just curious, are there any updates needed to https://github.com/hashicorp/terraform-provider-aws/blob/dff8af6af2a3cfe1dc1ab9d3d376943e8b594fc1/aws/resource_aws_config_remediation_configuration_test.go?

I'm also unclear on how to run the above acceptance test. Both of the below runs return no tests to run. 
```bash
$ make testacc TESTARGS='-run=TestAccConfigRemediationConfiguration_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccConfigRemediationConfiguration_basic -timeout 120m
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.687s [no tests to run]
```

```bash
$ make testacc TESTARGS='-run=testAccConfigRemediationConfiguration_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=testAccConfigRemediationConfiguration_basic -timeout 120m
testing: warning: no tests to run
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	2.527s [no tests to run]
```

(Moving this to review so it shows up in my Github pulls list)

**Comment by ctrawick** [comment]
PR #18079 may be more complete than this one for enabling automatic remediation support.

**Comment by ewbankkit** [comment]
@nikhil-goenka Thanks for the contribution 👏.
I am going to close this PR in favor of #18079 as it has a more complete implementation.

**Pull request closed without merging**
