### PR TITLE
r/aws_kinesis_firehose_delivery_stream - Send defaults for BufferIntervalInSeconds and BufferSizeInMBs

### PR DESCRIPTION
**Pull request by mtt88**
When updating the BufferIntervalInSeconds or BufferSizeInMBs [processor parameters](https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/kinesis_firehose_delivery_stream#processing_configuration) on a `kinesis_firehose_delivery_stream` , if we wish to change only one of these parameters then we no longer need to set the other to it's 'default' value.

Not really a bug but due to requirement by the API to set both of these parameters it will cause an annoying perpetual drift if only one of these parameters needs to be updated as the other must be set to it's default value.  See linked issue for more details on this behaviour. 

Priority: low

Relates #9827

Output from acceptance testing:

```
make testacc TESTS=TestAccFirehoseDeliveryStream_extendedS3Updates PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_extendedS3Updates'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStream_extendedS3Updates
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3Updates
=== CONT  TestAccFirehoseDeliveryStream_extendedS3Updates
--- PASS: TestAccFirehoseDeliveryStream_extendedS3Updates (551.16s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/firehose   551.213s
...
```

### CODE REVIEW

**Comment by ameddin73** [comment]
@ewbankkit is this being looked at? I'm trying to run the tests to open another PR and this issue is a blocker.

**Comment by ameddin73** [comment]
@mtt88 Were you able to get all tests passing with this? I believe the kinesis firehose testing suite fails due to the dissonance between the resource and default values.

**Comment by mtt88** [comment]
@ameddin73 - I'm afraid it's been a while since I looked at this - I'll try and find the time over the next few days to review any failing tests.

Matt

**Comment by mtt88** [comment]
@ameddin73 Whilst I've not run the entire test suite, I've run some of the tests which were failing on your branch (`ameddin73:main`) against this version of the code (`mtt88:f-aws-kinesis-firehose-delivery-stream-default-processor-params`). These all passed:

```
make testacc TESTS=TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning
=== CONT  TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning
--- PASS: TestAccFirehoseDeliveryStream_extendedS3DynamicPartitioning (1278.61s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	1282.125s

make testacc TESTS=TestAccFirehoseDeliveryStream_extendedS3Updates PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_extendedS3Updates'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStream_extendedS3Updates
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3Updates
=== CONT  TestAccFirehoseDeliveryStream_extendedS3Updates
--- PASS: TestAccFirehoseDeliveryStream_extendedS3Updates (1165.18s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	1167.475s

make testacc TESTS=TestAccFirehoseDeliveryStream_extendedS3basic PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_extendedS3basic'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStream_extendedS3basic
=== PAUSE TestAccFirehoseDeliveryStream_extendedS3basic
=== CONT  TestAccFirehoseDeliveryStream_extendedS3basic
--- PASS: TestAccFirehoseDeliveryStream_extendedS3basic (1042.68s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	1044.915s

make testacc TESTS=TestAccFirehoseDeliveryStream_basic PKG=firehose
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/firehose/... -v -count 1 -parallel 20 -run='TestAccFirehoseDeliveryStream_basic'  -timeout 180m
=== RUN   TestAccFirehoseDeliveryStream_basic
=== PAUSE TestAccFirehoseDeliveryStream_basic
=== CONT  TestAccFirehoseDeliveryStream_basic
--- PASS: TestAccFirehoseDeliveryStream_basic (1279.84s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/firehose	1282.072s
```

I've not run the failing Elastic Search or Redshift tests yet so it would be helpful if someone has the ability to run the entire test suite against this branch.

**Comment by ewbankkit** [comment]
This work has been rolled into https://github.com/hashicorp/terraform-provider-aws/pull/35137.

**Pull request closed without merging**
