### PR TITLE
Increase endpointInServiceTimeout from 10m to 60m

### PR DESCRIPTION
**Pull request by bruceadowns**
### Description

SageMaker endpoints are now taking a little over 10 minutes to become InService. This aligns the hardcoded endpoint timeout to 60 minutes.

This primarily effects SageMaker serverless endpoints. As an example, a test endpoint that deploys in >10m is using an xgboost model and associated container.

i.e.

```
...
module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0]: Still creating... [9m40s elapsed]
module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0]: Still creating... [9m50s elapsed]
module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0]: Still creating... [10m0s elapsed]
╷
│ Error: waiting for SageMaker Endpoint (ep-demo-sample-svrless) to be in service: timeout while waiting for state to become 'InService' (last state: 'Creating', timeout: 10m0s)
│ 
│   with module.tf_modules_sagemaker.module.endpoint.aws_sagemaker_endpoint.sagemaker_endpoint[0],
│   on .terraform/modules/tf_modules_sagemaker/modules/endpoint/main.tf line 55, in resource "aws_sagemaker_endpoint" "sagemaker_endpoint":
│   55: resource "aws_sagemaker_endpoint" "sagemaker_endpoint" {
```

### Relations

Closes #0000

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Review by Tradunsky — APPROVED** [review]
damn, 10 min startup time... 

Have you found the reason why it takes so long? A heavy docker image or we download something during startup?

**Comment by bruceadowns** [comment]
> damn, 10 min startup time...
> 
> Have you found the reason why it takes so long? A heavy docker image or we download something during startup?

(updated pr comment with...)

This primarily effects SageMaker serverless endpoints. As an example, a test endpoint that deploys in >10m is using an xgboost model and associated container, using 4g of memory.

**Review by DrFaust92 — APPROVED** [review]

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@bruceadowns Thanks for the contribution :tada: :clap:.

**Pull request merged**
