### PR TITLE
Add resource aws_db_snapshot_copy

### LINKED ISSUE #9885: Terraform AWS Provider does not support CopyDBSnapshot
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Terraform AWS Provider does not support the CopyDBSnapshot API call, which allows copying a manual snapshot of an RDS instance, either to the same region, to a different region or even to a different AWS account. 

This functionality can be of particular use in Terraform for a multitude of reasons, including disaster recovery plans with snapshots copied across multiple regions, launch of testing environments on different regions restoring from some database snapshot, among others.

### New or Affected Resource(s)

* aws_db_snapshot_copy

### Potential Terraform Configuration

```hcl
resource "aws_db_snapshot_copy" "test" {
  source_region                 = "<region where the snapshot is>"
  source_db_snapshot_identifier = "<snapshot ARN>"
  target_db_snapshot_identifier = "<name to give to the copied snapshot"
  kms_key_id                    = "<key to encrypt copy>"
}
```

### References

AWS API Call documentation: https://docs.aws.amazon.com/AmazonRDS/latest/APIReference/API_CopyDBSnapshot.html

AWS Go SDK documentation: https://godoc.org/github.com/aws/aws-sdk-go/service/rds#CopyDBSnapshot

### PR DESCRIPTION
**Pull request by PedroRibeiro95**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" comments, they generate extra noise for pull request followers and do not help prioritize the request

Closes #9885

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adds new aws_db_snapshot_copy resource allowing the copy of manual RDS snapshots.
```

Output from acceptance testing:

```
make testacc TEST=./aws TESTARGS='-run=TestAccAWSRdsSnapshotCopy_basic'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSRdsSnapshotCopy_basic -timeout 120m
=== RUN   TestAccAWSRdsSnapshotCopy_basic
=== PAUSE TestAccAWSRdsSnapshotCopy_basic
=== CONT  TestAccAWSRdsSnapshotCopy_basic
--- PASS: TestAccAWSRdsSnapshotCopy_basic (706.08s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	706.127s

$ make testacc TEST=./aws TESTARGS='-run=TestAccAWSRdsDbSnapshotCopy_withRegions'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -parallel 20 -run=TestAccAWSRdsDbSnapshotCopy_withRegions -timeout 120m
=== RUN   TestAccAWSRdsDbSnapshotCopy_withRegions
=== PAUSE TestAccAWSRdsDbSnapshotCopy_withRegions
=== CONT  TestAccAWSRdsDbSnapshotCopy_withRegions
--- PASS: TestAccAWSRdsDbSnapshotCopy_withRegions (728.24s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	728.295s
```

### CODE REVIEW

**Comment by PedroRibeiro95** [comment]
@bflad can you take a look at this when you have the time? Thank you!

**Comment by artemsablin** [comment]
Hello. Any update on this? This feature appears to be quite useful.

**Comment by haines** [comment]
This also fixes #3295

**Comment by haines** [comment]
I attempted to merge this on top of the latest release (v2.59.0) but it fails to build.

```
aws/provider.go:477:4: cannot use resourceAwsDbSnapshotCopy() (type *"github.com/hashicorp/terraform/helper/schema".Resource) as type *"github.com/hashicorp/terraform-plugin-sdk/helper/schema".Resource in map value
aws/resource_aws_db_snapshot_copy.go:72:10: undefined: tagsFromMapRDS
aws/resource_aws_db_snapshot_copy.go:134:12: undefined: saveTagsRDS
```

Looks like the imports need to be updated to [the new plugin SDK](https://www.terraform.io/docs/extend/plugin-sdk.html), and the tags functions were removed in #11255 in favour of the `keyvaluetags` package.

@PedroRibeiro95 are you able to update this PR with the latest master?

**Comment by PedroRibeiro95** [comment]
Hi @haines, I will try to work on it this weekend. Thanks for the help.

**Comment by Tensho** [comment]
Hey guys, would be nice to get this stuff merged and released 👍

**Comment by teamterraform** [comment]
## Notification of Recent and Upcoming Changes to Contributions

Thank you for this contribution! There have been a few recent development changes that affect this pull request. We apologize for the inconvenience, especially if there have been long review delays up until now. Please note that this is automated message from an unmonitored account. See the [FAQ](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/FAQ.md) for additional information on the maintainer team and review prioritization.

If you are unable to complete these updates, please leave a comment for the community and maintainers so someone can potentially continue the work. The maintainers will encourage other contributors to use the existing contribution as the base for additional changes as appropriate. Otherwise, contributions that do not receive updated code or comments from the original contributor may be closed in the future so the maintainers can focus on active items.

For the most up to date information about Terraform AWS Provider development, see the [Contributing Guide](https://github.com/terraform-providers/terraform-provider-aws/blob/master/docs/CONTRIBUTING.md). Additional technical debt changes can be tracked with the [`technical-debt` label on issues](https://github.com/terraform-providers/terraform-provider-aws/issues?q=is%3Aopen+is%3Aissue+label%3Atechnical-debt).

As part of updating a pull request with these changes, the most current unit testing and linting will run. These may report issues that were not previously reported.

### Terraform 0.12 Syntax

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/8950
Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14417

Version 3 and later of the Terraform AWS Provider, which all existing contributions would potentially be added, only supports Terraform 0.12 and later. Certain syntax elements of Terraform 0.11 and earlier show deprecation warnings during runs with Terraform 0.12. Documentation and test configurations, such as those including deprecated string interpolations (`some_attribute = "${aws_service_thing.example.id}"`) should be updated to the newer syntax (`some_attribute = aws_service_thing.example.id`). Contribution testing will automatically fail on older syntax in the near future. Please see the referenced issues for additional information.

### Action Required: Terraform Plugin SDK Version 2

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14551

The Terraform AWS Provider has been upgraded to the latest version of the Terraform Plugin SDK. Generally, most changes to contributions should only involve updating Go import paths in source code files. Please see the referenced issue for additional information.

### Removal of website/aws.erb File

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14712

Any changes to the `website/aws.erb` file are no longer necessary and should be removed from this contribution to prevent merge issues in the near future when the file is removed from the repository. Please see the referenced issue for additional information.

### Upcoming Change of Git Branch Naming

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14292

Development environments will need their upstream Git branch updated from `master` to `main` in the near future. Please see the referenced issue for additional information and scheduling.

### Upcoming Change of GitHub Organization

Reference: https://github.com/terraform-providers/terraform-provider-aws/issues/14715

This repository will be migrating from https://github.com/terraform-providers/terraform-provider-aws to https://github.com/hashicorp/terraform-provider-aws. No practitioner or developer action is anticipated and most GitHub functionality will automatically redirect to the new location. Go import paths including `terraform-providers` can remain for now. Please see the referenced issue for additional information and scheduling.

**Comment by PedroRibeiro95** [comment]
So finally I was able to tackle this, sorry everyone for the huge delay but you know, life happens. Anyway, I believe that the new changes are now using correctly the new SDK, but at the moment I am now able to test it. @haines, would you mind taking another look? Thanks!

**Comment by tutecano1995** [comment]
Hi guys! Is there any update related to this PR? This feature would be really useful 🚀

**Comment by Gregy** [comment]
I have rebased this PR onto the current code here: https://github.com/Gregy/terraform-provider-aws/tree/add-resource-db-snapshot-copy

If you have time you can take it and update this PR with it. I will not create a competing PR.

I have also pushed a version of the provider with this functionality integrated into the [registry](https://registry.terraform.io/providers/Gregy/aws/)

**Comment by johnsonaj** [comment]
LGTM 🚀 

#### Commercial
```console
$ make testacc TESTS=TestAccSnapshotCopy_ PKG=rds                                                                                                                                                                              
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccSnapshotCopy_'  -timeout 180m
=== RUN   TestAccSnapshotCopy_basic
=== PAUSE TestAccSnapshotCopy_basic
=== RUN   TestAccSnapshotCopy_tags
=== PAUSE TestAccSnapshotCopy_tags
=== RUN   TestAccSnapshotCopy_disappears
=== PAUSE TestAccSnapshotCopy_disappears
=== CONT  TestAccSnapshotCopy_basic
=== CONT  TestAccSnapshotCopy_disappears
=== CONT  TestAccSnapshotCopy_tags
--- PASS: TestAccSnapshotCopy_basic (776.89s)
--- PASS: TestAccSnapshotCopy_tags (854.61s)
--- PASS: TestAccSnapshotCopy_disappears (966.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	968.987s
```

#### Gov Cloud
```console
$ make testacc TESTS=TestAccSnapshotCopy_ PKG=rds
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/rds/... -v -count 1 -parallel 20 -run='TestAccSnapshotCopy_'  -timeout 180m
=== RUN   TestAccSnapshotCopy_basic
=== PAUSE TestAccSnapshotCopy_basic
=== RUN   TestAccSnapshotCopy_tags
=== PAUSE TestAccSnapshotCopy_tags
=== RUN   TestAccSnapshotCopy_disappears
=== PAUSE TestAccSnapshotCopy_disappears
=== CONT  TestAccSnapshotCopy_basic
=== CONT  TestAccSnapshotCopy_disappears
=== CONT  TestAccSnapshotCopy_tags
--- PASS: TestAccSnapshotCopy_basic (610.32s)
--- PASS: TestAccSnapshotCopy_tags (687.70s)
--- PASS: TestAccSnapshotCopy_disappears (740.99s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/rds	743.287s
```

**Comment by johnsonaj** [comment]
@PedroRibeiro95 thanks for the contribution 🎉 👏🏾

**Pull request merged**
