### PR TITLE
r/aws_vpc_ipam_pool_cidr_allocation - new attribute

### LINKED ISSUE #22471: r/aws_vpc_ipam_pool_cidr_allocation - new attribute
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add the `disallowed_cidrs` to the `aws_vpc_ipam_pool_cidr_allocation` resource

### New or Affected Resource(s)

* `aws_vpc_ipam_pool_cidr_allocation`

### Potential Terraform Configuration

```hcl
resource "aws_vpc_ipam_pool_cidr_allocation" "example" {
  ipam_pool_id  = aws_vpc_ipam_pool.example.id
  netmaskLength = 28

  disallowed_cidrs = [
    "172.2.0.0/28"
  ]

  depends_on = [
    aws_vpc_ipam_pool_cidr.example
  ]
}
```

### References

* #22470

### PR DESCRIPTION
**Pull request by GlennChia**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22471

Output from acceptance testing:

```
$ make testacc TESTS=TestAccVPCIpamPoolAllocation PKG=ec2 ACCTEST_PARALLELISM=1 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 1 -run='TestAccVPCIpamPoolAllocation' -timeout 180m
=== RUN   TestAccVPCIpamPoolAllocation_ipv4Basic
=== PAUSE TestAccVPCIpamPoolAllocation_ipv4Basic
=== RUN   TestAccVPCIpamPoolAllocation_ipv4BasicNetmask
=== PAUSE TestAccVPCIpamPoolAllocation_ipv4BasicNetmask
=== RUN   TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr
=== PAUSE TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr
=== CONT  TestAccVPCIpamPoolAllocation_ipv4Basic
--- PASS: TestAccVPCIpamPoolAllocation_ipv4Basic (138.24s)
=== CONT  TestAccVPCIpamPoolAllocation_ipv4BasicNetmask
--- PASS: TestAccVPCIpamPoolAllocation_ipv4BasicNetmask (109.75s)
=== CONT  TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr
--- PASS: TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr (126.84s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        383.549s

...
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTS=TestAccVPCIpamPoolAllocation PKG=ec2 ACCTEST_PARALLELISM=1 
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/ec2/... -v -count 1 -parallel 1 -run='TestAccVPCIpamPoolAllocation' -timeout 180m
=== RUN   TestAccVPCIpamPoolAllocation_ipv4Basic
=== PAUSE TestAccVPCIpamPoolAllocation_ipv4Basic
=== RUN   TestAccVPCIpamPoolAllocation_ipv4BasicNetmask
=== PAUSE TestAccVPCIpamPoolAllocation_ipv4BasicNetmask
=== RUN   TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr
=== PAUSE TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr
=== CONT  TestAccVPCIpamPoolAllocation_ipv4Basic
--- PASS: TestAccVPCIpamPoolAllocation_ipv4Basic (64.87s)
=== CONT  TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr
--- PASS: TestAccVPCIpamPoolAllocation_ipv4DisallowedCidr (81.57s)
=== CONT  TestAccVPCIpamPoolAllocation_ipv4BasicNetmask
--- PASS: TestAccVPCIpamPoolAllocation_ipv4BasicNetmask (67.20s)
PASS
ok      github.com/hashicorp/terraform-provider-aws/internal/service/ec2        220.968s
```

**Comment by ewbankkit** [comment]
@GlennChia Thanks for the contribution :tada: :clap:.

**Comment by ewbankkit** [comment]
@drewmullen I'm happy to merge this once you have reviewed.

**Review by drewmullen — APPROVED** [review]
LGTM! TY for adding this feature @GlennChia

**Pull request merged**
