### PR TITLE
r/aws_autoscaling_group_tag: new resource for tagging existing ASGs

### PR DESCRIPTION
**Pull request by jbg**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

### Related issues

Relates #13643
Relates #9061
Relates aws/containers-roadmap#724

### Background

This PR allows tagging of ASGs created implicitly by other resources. For example, tagging the ASGs created by EKS node groups:

```hcl
resource "aws_autoscaling_group_tag" "eks_node_group_autoscaler_node_template_capacity_type" {
  for_each = toset(
    [for asg in flatten(
      [for resources in aws_eks_node_group.node_group.resources: resources.autoscaling_groups]
    ): asg.name]
  )

  asg_name = each.value
  tag {
    key = "k8s.io/cluster-autoscaler/node-template/label/eks.amazonaws.com/capacityType"
    value = "SPOT"
    propagate_at_launch = false
  }
}
```

### Output from acceptance testing

```
$ AWS_PROFILE=terraform-test make testacc TESTARGS='-run=TestAccAWSAutoscalingGroupTag'
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSAutoscalingGroupTag -timeout 180m
=== RUN   TestAccAWSAutoscalingGroupTag_basic
=== PAUSE TestAccAWSAutoscalingGroupTag_basic
=== RUN   TestAccAWSAutoscalingGroupTag_disappears
=== PAUSE TestAccAWSAutoscalingGroupTag_disappears
=== RUN   TestAccAWSAutoscalingGroupTag_Value
=== PAUSE TestAccAWSAutoscalingGroupTag_Value
=== CONT  TestAccAWSAutoscalingGroupTag_basic
=== CONT  TestAccAWSAutoscalingGroupTag_Value
=== CONT  TestAccAWSAutoscalingGroupTag_disappears
--- PASS: TestAccAWSAutoscalingGroupTag_basic (72.00s)
--- PASS: TestAccAWSAutoscalingGroupTag_disappears (79.74s)
--- PASS: TestAccAWSAutoscalingGroupTag_Value (113.01s)
PASS
ok  	github.com/terraform-providers/terraform-provider-aws/aws	114.407s
```

### CODE REVIEW

**Comment by ewbankkit** [comment]
Relates: https://github.com/hashicorp/terraform-provider-aws/pull/13783.

**Comment by sergkondr** [comment]
Hello! Do you have any updates on that? The impossibility of adding tags to node-group-created autoscaling-group is a very frustrating thing and it prevents us to use cluster autoscaler in EKS.

**Comment by jbg** [comment]
Haven't had any feedback, but that seems fairly normal for PRs on this repo

**Comment by ewbankkit** [comment]
@jbg Thanks for the contribution :tada: :clap:.
In order to get this merged for this week's release I used your commits and fixed some formatting errors in #20674.
I also changed the `asg_name` argument to `autoscaling_group_name` to match other resources.

**Pull request closed without merging**
