### PR TITLE
[WIP] F amazon bedrock

### LINKED ISSUE #33718: [New Resource]: `aws_bedrock_model_customization_job`
### Description

Add BedRock as a new Terraform Resource / Data Source so users with IaC requirements in their production environments can effectively start using the service.

### Requested Resource(s) and/or Data Source(s)

Resources:
- aws_bedrock_model_customization_job

Data Sources:
- aws_bedrock_model_customization_job

### Potential Terraform Configuration

```terraform
resource "aws_bedrock_model_customization_job" "example" {
  base_model_identifier = "asdf"
  client_request_token  = "c9a0b34f-877c-4cee-9fa6-e7d08d04f4fd"
  kms_key_id            = "arn:aws:kms:..."
  model_name            = "Custom Model"
  role_arn              = "arn:aws:iam:..."
  job_name              = "example"

  model_tags {
    "tag1" = "value1"
    "tag2" = "value2"
  }

  hyper_parameters {
    "param1" = "pvalue2"
  }

  job_tags {
    "tag1" = "value1"
    "tag2" = "value2"
  }

  output_data_config = {
    s3_uri = "s3://..."
  }

  training_data_config = {
    s3_uri = "s3://..."
  }

  validation_data_config = {
    s3_uri = "s3://..."
  }

  vpc_config = {
    security_group_ids = [
      "sg-123",
      "sg-456",
    ]

    subnet_ids = [
      "x",
      "y",
    ]
  }
}
```

### References

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_CreateModelCustomizationJob.html
https://docs.aws.amazon.com/service-authorization/latest/reference/list_amazonbedrock.html

### Would you like to implement a fix?

No

### LINKED ISSUE #33737: [New Resource]: Amazon Bedrock - Model invocation logging
### Description

Model invocation logging is an optional feature to collect invocation logs, model input data, and model output data for all invocations in your AWS account used in Amazon Bedrock. By default, this feature is disabled. It would be nice to enable this configuration via Infrastructure as Code.

### Requested Resource(s) and/or Data Source(s)

`aws_bedrock_model_invocation_logging_configuration`

### Potential Terraform Configuration

```terraform
resource "aws_bedrock_model_invocation_logging_configuration" "example" {

  data_delivery_config {
    text = true
    image = true
    embedding = false
  }

  logging_destinations {

    s3_config {
      bucket_name = "my-bucket"
      key_prefix = "prefix"
    }

    cloudwatch_config {
      log_group_name = "my-bucket"
      role_arn = "arn:aws:iam::...."

      large_data_delivery {
        bucket_name = "..."
        key_prefix = "..."
      }
    }
  }
}
```

### References

https://docs.aws.amazon.com/bedrock/latest/APIReference/API_PutModelInvocationLoggingConfiguration.html

### Would you like to implement a fix?

No

### LINKED ISSUE #33738: [New Service]: Amazon Bedrock - Service Client
### Description

Amazon Bedrock is a fully managed service that offers a choice of high-performing FMs from leading AI companies. 
There is need to create configurations via IaC like the model logging configuration.
https://github.com/hashicorp/terraform-provider-aws/issues/33737 

### Requested Resource(s) and/or Data Source(s)

`aws_bedrock_thing`

### Potential Terraform Configuration

_No response_

### References

https://aws.amazon.com/about-aws/whats-new/2023/09/amazon-bedrock-generally-available/
https://docs.aws.amazon.com/sdk-for-go/api/service/bedrock/

### Would you like to implement a fix?

Yes

### LINKED ISSUE #33809: [New Service]: Amazon Bedrock
### Description

Implement support for Amazon Bedrock. 

### Requested Resource(s) and/or Data Source(s)

datasources:

- [x] [`aws_bedrock_foundation_models`](https://github.com/hashicorp/terraform-provider-aws/pull/34148)
- [x] [`aws_bedrock_foundation_model`](https://github.com/hashicorp/terraform-provider-aws/pull/34148)
- [x] [`aws_bedrock_custom_models`](https://github.com/hashicorp/terraform-provider-aws/pull/34310)
- [x] [`aws_bedrock_custom_model`](https://github.com/hashicorp/terraform-provider-aws/pull/34310)

resources:

- [x] [`aws_bedrock_custom_model`](https://github.com/hashicorp/terraform-provider-aws/pull/34310)
- [ ] [`aws_bedrock_provisioned_model_throughput`](https://github.com/hashicorp/terraform-provider-aws/pull/35689)
- [x] [`aws_bedrock_model_invocation_logging_configuration`](https://github.com/hashicorp/terraform-provider-aws/pull/34303)

### Potential Terraform Configuration

```terraform
data "aws_bedrock_foundation_models" "test" {
}

data "aws_bedrock_foundation_model" "test" {
  model_arn = "foundationmodelarn"
}

data "aws_bedrock_custom_models" "test" {
}

data "aws_bedrock_custom_model" "test" {
	model_arn = "testmodelarn"
}

resource "aws_bedrock_custom_model" "test" {
  custom_model_name = "test"
  job_name          = "test"
  base_model_arn    = "amazon.titan-text-express-v1"
  hyper_parameters = {
    "epochCount"              = "1"
    "batchSize"               = "1"
    "learningRate"            = "0.005"
    "learningRateWarmupSteps" = "0"
  }
  output_data_config   = "s3://${aws_s3_bucket.output_data.id}/myfolder/"
  role_arn             = aws_iam_role.bedrock_fine_tuning.arn
  training_data_config = "s3://${aws_s3_bucket.training_data.id}/myfolder/training_data.jsonl"
}
```

### References

https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html

### Would you like to implement a fix?

Yes

### PR DESCRIPTION
**Pull request by skyscrapr**
### Description

Amazon Bedrock New  Service Implementation

### Relations

Closes #33809.
Closes #33738.
Closes #33737.
Closes #33718.

### References

[Amazon Bedrock API](https://docs.aws.amazon.com/bedrock/latest/APIReference/welcome.html)

### Output from Acceptance Testing

TBD

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by skyscrapr** [comment]
There are a number of areas that need design discussion:

resource_aws_bedrock_custom_model:
-- I chose to not export the `model customisation job` as a resource since this cannot be managed or deleted. 
-- Instead I chose to create a `custom model` resource and wrap the customisation job in that handling.
-- This has a couple of implications for tag handling.
-- What is the best way to handle failures for resources with long creation times? I've chosen to save the ID's in state as early as possible to facilitate destroy/create by the built-in taint behaviour. Is that a good approach? 
-- I'll upload the test output if the current implementation is approved. 

@wellsiau-aws feel free to loop in anyone that might be interested in reviewing.

**Comment by breathingdust** [comment]
Hi @skyscrapr! 👋  Thanks for the contribution, I know it’s WIP but I noticed a few things at first glance 

This week we are finally making a [policy change](https://github.com/hashicorp/terraform-provider-aws/issues/32917) to require that net new resources are based on [AWS Go SDK v2](https://github.com/aws/aws-sdk-go-v2) and [terraform-plugin-framework](https://github.com/hashicorp/terraform-plugin-framework) rather than [terraform-plugin-sdk](https://github.com/hashicorp/terraform-plugin-sdk). These resources will need to be updated to confirm as a result. It should not be complex to do, but do reach out if you have any questions.

Additionally, if possible we also like to see one PR per resource/data source when ready for final review. It can be very difficult/inefficient for maintainers to review PR’s with multiple additions. 

Thank you!

**Comment by skyscrapr** [comment]
I'm opening a bunch of new ones PRs to cover the recommendation above. 
Please close.

**Comment by AdamTylerLynch** [comment]
> I'm opening a bunch of new ones PRs to cover the recommendation above. Please close.

@skyscrapr do you want us to close this PR without any merge? Do you new PRs #34042 and #34043 supersede this PR?

**Comment by skyscrapr** [comment]
@AdamTylerLynch 

This PR is against sdk v1. 
New PRs are against sdk v2. 

As soon as the current open PRs are approved, I'll raise the remaining PRs for the other data sources and resources. 

This one can be closed 👍. Thanks

**Comment by skyscrapr** [comment]
I'm closing this as the new PRs have all been raised. Thanks!

**Pull request closed without merging**
