### PR TITLE
doc: update route53 import command

### PR DESCRIPTION
**Pull request by nimboya**
### Relations

Closes #0000

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by justinretzolk** [comment]
Hey @nimboya 👋 Thank you for taking the time to raise this! I'm not certain I follow this change. Can you provide a bit more information as to why you feel this is a necessary change?

**Comment by nimboya** [comment]
> Hey @nimboya 👋 Thank you for taking the time to raise this! I'm not certain I follow this change. Can you provide a bit more information as to why you feel this is a necessary change?

The command to import Route53 DNS record was wrong. It does not need the Domain and Record type. When I used it that way it did not import the resource correctly to the Terraform state. The correct command was without the Domain/Sub-domain and record type.

It should be this

```terraform import aws_route53_record.myrecord Z4KAPRWWNC7JR_dev_NS_dev

and not this

```terraform import aws_route53_record.myrecord Z4KAPRWWNC7JR_dev.example.com_NS

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

**Comment by ewbankkit** [comment]
@nimboya Thanks for the contribution :tada: :clap:.

**Pull request merged**
