### PR TITLE
#22385 elasticache redis 6 regexp validation fix

### LINKED ISSUE #22385: AWS has changed Elasticache Redis versioning again
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform CLI and Terraform AWS Provider Version

```
Terraform v1.0.7
on windows_amd64
+ provider registry.terraform.io/hashicorp/aws v3.70.0
```

### Affected Resource(s)

* `aws_elasticache_replication_group`

(This probably also impacts `aws_elasticache_cluster` when used with Redis, but I haven't personally verified it)

### Terraform Configuration Files

Please include all Terraform configurations required to reproduce the bug. Bug reports without a functional reproduction may be closed without investigation.

```hcl
terraform {
  backend "local" { }

  required_providers {
    aws = {
      source  = "hashicorp/aws"
      version = "~> 3.70"
    }
  }
}

provider "aws" {
  region  = "us-east-1"
}

resource "aws_elasticache_replication_group" "example1" {
  replication_group_id          = "tf-rep-group-1"
  replication_group_description = "test description"
  engine_version                = "6.0"
  node_type                     = "cache.m4.large"
  parameter_group_name          = "default.redis6.x"
}

resource "aws_elasticache_replication_group" "example2" {
  replication_group_id          = "tf-rep-group-2"
  replication_group_description = "test description"
  engine_version                = "6.2"
  node_type                     = "cache.m4.large"
  parameter_group_name          = "default.redis6.x"
}
```

### Debug Output

https://gist.github.com/philomory/eeead53871f26c6a3825e36c17a862af

### Expected Behavior

Create two Redis clusters, one at 6.0 and one at 6.2

### Actual Behavior

An error is displayed, stating `engine_version: Redis versions must match <major>.x when using version 6 or higher, or <major>.<minor>.<bug-fix>`.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Previously, Amazon had announced the following for Redis versions 6 and higher:
> Beginning with Redis 6, ElastiCache for Redis will offer a single version for each Redis OSS major release, rather than offering multiple minor versions. Versionless engine support is designed to minimize confusion and ambiguity on having to choose from multiple minor versions. ElastiCache for Redis will also automatically keep your cache cluster up to date on the selected major version (Redis 6 and above). By providing the updated engine version, it ensures improved performance and enhanced security.
> 
> You specify the engine version by using 6.x. ElastiCache for Redis will automatically invoke the preferred minor version of Redis 6 that is available.

(This was as opposed to with versions 5.x and lower, where you could specify full version numbers).

However, at some point in the recent past (_probably_ coinciding with the [2021-11-23 announcement of support for Redis 6.2](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-elasticache-redis-support-redis-6-2/), but I'm not certain), the documentation was changed to state:
> Beginning with Redis 6.0, ElastiCache for Redis will offer a single version for each Redis OSS minor release, rather than offering multiple patch versions.
> 
> Beginning with Redis 6.0, you can also opt-in to the next auto minor version upgrade by setting the AutoMinorVersionUpgrade parameter to yes, and ElastiCache for Redis will manage the minor version upgrade, through self-service updates. This will be handled through standard customer-notification channels via a self-service update campaign. For more information, see Self-service updates in Amazon ElastiCache.

The output of `aws elasticache describe-cache-engine-versions` now confirms that there are engine versions `"6.0"` and `"6.2"` now, but _not_ any engine version identified as `"6.x"` (although oddly attempting to create a cluster with engine_version "6.x" _does_ still work, and results in a cluster using version 6.2.5).

### References

* [Elasticache Redis 6.2 support announcement](https://aws.amazon.com/about-aws/whats-new/2021/11/amazon-elasticache-redis-support-redis-6-2/)
* [Elasticache Redis supported engine versions](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/supported-engine-versions.html)
* [Elasticache Redis uprading versions](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/VersionManagement.html)
* #15625, the issue initially resulting in implementation of support for `6.x` as an `engine_version` and _removal_ of support for e.g. `6.0`.
* #18920, the pull request that resulted from the above-mentioned issue

### LINKED ISSUE #22657: Support for JSON as input to aws_glue_schema
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AWS now supports using JSON in addition to AVRO for defining `data_format` in `aws_glue_schema`. Currently only `AVRO` is supported

### New or Affected Resource(s)

* aws_glue_schema

### PR DESCRIPTION
**Pull request by errcmd**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Closes #22385

Output from acceptance testing:

```
$ make testacc TESTS=TestAccXXX PKG=ec2

...
```

### CODE REVIEW

**Comment by ktham** [comment]
@errcmd Can you add the corresponding test cases for your change?

**Comment by bschaatsbergen** [comment]
I'll pick this PR up to solve both #23729 and #22385

**Comment by galindro** [comment]
Hey guys, whet is preventing you from merge this PR?

**Comment by ewbankkit** [comment]
@errcmd Thanks for the contribution :tada: :clap:.
Superseded by #23734.

**Pull request closed without merging**
