### PR TITLE
r/aws_appautoscaling_target: Skip `ListTags`/`UpdateTags` for existing resources with no assigned ARN

### PR DESCRIPTION
**Pull request by ewbankkit**
### Description

Older `aws_appautoscaling_target`s have no ARN assigned by AWS. This causes errors when making the `ListTags` call to get any resource tags.
Skip the call if no ARN (or more generally, no identifier value) is present.
The same logic applies to `UpdateTags` (e.g. when using `default_tags`).

#### Maintainer Instructions

In the main test account, with this configuration:

```hcl
provider "aws" {}

resource "aws_appautoscaling_target" "test" {
  service_namespace  = "ecs"
  resource_id        = "service/cluster-8xupcpmfyu/foobar"
  scalable_dimension = "ecs:service:DesiredCount"
  min_capacity       = 1
  max_capacity       = 3
}
```

```console
% git checkout v4.65.0
% make
% terraform import aws_appautoscaling_target.test ecs/service/cluster-8xupcpmfyu/foobar/ecs:service:DesiredCount
aws_appautoscaling_target.test: Importing from ID "ecs/service/cluster-8xupcpmfyu/foobar/ecs:service:DesiredCount"...
aws_appautoscaling_target.test: Import prepared!
  Prepared aws_appautoscaling_target for import
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

Import successful!

The resources that were imported are shown above. These resources are now in
your Terraform state and will henceforth be managed by Terraform.

% terraform plan 
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

No changes. Your infrastructure matches the configuration.

% git checkout v4.66.0
% make
% terraform plan
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]
╷
│ Error: listing tags for Application Auto Scaling Target (): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, ListTagsForResourceInput.ResourceARN.
│ 
│ 
│   with aws_appautoscaling_target.test,
│   on main.tf line 3, in resource "aws_appautoscaling_target" "test":
│    3: resource "aws_appautoscaling_target" "test" {
│ 
╵

% git checkout deaacb40f009007e9bdacfb8c40344438d8d5b3a
% make
% terraform plan
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_appautoscaling_target.test has been changed
  ~ resource "aws_appautoscaling_target" "test" {
        id                 = "service/cluster-8xupcpmfyu/foobar"
      + tags               = {}
      + tags_all           = {}
        # (6 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the
following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

No changes. Your infrastructure matches the configuration.

Your configuration already matches the changes detected above. If you'd like to update the Terraform state to match, create and
apply a refresh-only plan:
  terraform apply -refresh-only

```

If we then add some [default tags](https://registry.terraform.io/providers/hashicorp/aws/latest/docs#default_tags-configuration-block):

```hcl
provider "aws" {
  default_tags {
    tags = {
      Environment = "Test"
      Name        = "Provider Tag"
    }
  }
}

resource "aws_appautoscaling_target" "test" {
  service_namespace  = "ecs"
  resource_id        = "service/cluster-8xupcpmfyu/foobar"
  scalable_dimension = "ecs:service:DesiredCount"
  min_capacity       = 1
  max_capacity       = 3
}
```

```console
% terraform apply
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_appautoscaling_target.test will be updated in-place
  ~ resource "aws_appautoscaling_target" "test" {
        id                 = "service/cluster-8xupcpmfyu/foobar"
        tags               = {}
      ~ tags_all           = {
          + "Environment" = "Test"
          + "Name"        = "Provider Tag"
        }
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_appautoscaling_target.test: Modifying... [id=service/cluster-8xupcpmfyu/foobar]
╷
│ Error: updating tags for Application Auto Scaling Target (): tagging resource (): InvalidParameter: 1 validation error(s) found.
│ - minimum field size of 1, TagResourceInput.ResourceARN.
│ 
│ 
│   with aws_appautoscaling_target.test,
│   on main.tf line 10, in resource "aws_appautoscaling_target" "test":
│   10: resource "aws_appautoscaling_target" "test" {
│ 
╵

% git checkout 379529d9df8eda142cc5d61d5d1dd903aaf5d615
% make
% terraform apply                                                    
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

Note: Objects have changed outside of Terraform

Terraform detected the following changes made outside of Terraform since the last "terraform apply":

  # aws_appautoscaling_target.test has been changed
  ~ resource "aws_appautoscaling_target" "test" {
        id                 = "service/cluster-8xupcpmfyu/foobar"
        tags               = {}
      ~ tags_all           = {
          - "Environment" = "Test" -> null
          - "Name"        = "Provider Tag" -> null
        }
        # (6 unchanged attributes hidden)
    }

Unless you have made equivalent changes to your configuration, or ignored the relevant attributes using ignore_changes, the
following plan may include actions to undo or respond to these changes.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_appautoscaling_target.test will be updated in-place
  ~ resource "aws_appautoscaling_target" "test" {
        id                 = "service/cluster-8xupcpmfyu/foobar"
        tags               = {}
      ~ tags_all           = {
          + "Environment" = "Test"
          + "Name"        = "Provider Tag"
        }
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

aws_appautoscaling_target.test: Modifying... [id=service/cluster-8xupcpmfyu/foobar]
aws_appautoscaling_target.test: Modifications complete after 1s [id=service/cluster-8xupcpmfyu/foobar]

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

% terraform plan 
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with the following
symbols:
  ~ update in-place

Terraform will perform the following actions:

  # aws_appautoscaling_target.test will be updated in-place
  ~ resource "aws_appautoscaling_target" "test" {
        id                 = "service/cluster-8xupcpmfyu/foobar"
        tags               = {}
      ~ tags_all           = {
          + "Environment" = "Test"
          + "Name"        = "Provider Tag"
        }
        # (6 unchanged attributes hidden)
    }

Plan: 0 to add, 1 to change, 0 to destroy.

───────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────────

Note: You didn't use the -out option to save this plan, so Terraform can't guarantee to take exactly these actions if you run
"terraform apply" now.
```

The "permadiff" can be suppressed via a [`lifecycle.ignore_changes`](https://developer.hashicorp.com/terraform/language/meta-arguments/lifecycle#ignore_changes) meta-argument.

```hcl
provider "aws" {
  default_tags {
    tags = {
      Environment = "Test"
      Name        = "Provider Tag"
    }
  }
}

resource "aws_appautoscaling_target" "test" {
  service_namespace  = "ecs"
  resource_id        = "service/cluster-8xupcpmfyu/foobar"
  scalable_dimension = "ecs:service:DesiredCount"
  min_capacity       = 1
  max_capacity       = 3

  lifecycle {
    ignore_changes = [
      tags_all,
    ]
  }
}
```

```console
% terraform plan
aws_appautoscaling_target.test: Refreshing state... [id=service/cluster-8xupcpmfyu/foobar]

No changes. Your infrastructure matches the configuration.

Terraform has compared your real infrastructure against your configuration and found no differences, so no changes are needed.
```

### Relations

Closes https://github.com/hashicorp/terraform-provider-aws/issues/31180.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/30172.
Relates https://github.com/hashicorp/terraform-provider-aws/issues/28391.

### Output from Acceptance Testing

```console
% make testacc TESTARGS='-run=TestAccAppAutoScalingTarget_basic$$\|TestAccAppAutoScalingTarget_tags$$' PKG=appautoscaling
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./internal/service/appautoscaling/... -v -count 1 -parallel 20  -run=TestAccAppAutoScalingTarget_basic$\|TestAccAppAutoScalingTarget_tags$ -timeout 180m
=== RUN   TestAccAppAutoScalingTarget_basic
=== PAUSE TestAccAppAutoScalingTarget_basic
=== RUN   TestAccAppAutoScalingTarget_tags
=== PAUSE TestAccAppAutoScalingTarget_tags
=== CONT  TestAccAppAutoScalingTarget_basic
=== CONT  TestAccAppAutoScalingTarget_tags
--- PASS: TestAccAppAutoScalingTarget_tags (54.10s)
--- PASS: TestAccAppAutoScalingTarget_basic (90.32s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/appautoscaling	95.864s
```

### CODE REVIEW

**Review by jar-b — APPROVED** [review]
LGTM 👍

**Review by justinretzolk — APPROVED** [review]
LGTM 🚀

**Comment by coolbananas118** [comment]
We fixed this in the end by forcing our provider back to 4.65.0. Hopefully 4.67.0 will prove to be stable and we can revert to using the latest minor/patch version below 5.0 🤞

**Comment by ewbankkit** [comment]
The fix is available in **v4.66.1** of the Terraform AWS Provider: https://registry.terraform.io/providers/hashicorp/aws/4.66.1.

**Comment by coolbananas118** [comment]
We switched back to 4.66.1 and everything is fixed now. Thanks @ewbankkit 🙇

**Pull request merged**
