### PR TITLE
r/apigateway_base_path_mapping - add support `domain_name_id`

### PR DESCRIPTION
**Pull request by DrFaust92**
### Relations

Relates #40274.
Relates https://github.com/hashicorp/terraform-provider-aws/pull/40364.

### Output from Acceptance Testing

```console
% make testacc TESTS=TestAccAPIGatewayBasePathMapping_  PKG=apigateway

--- PASS: TestAccAPIGatewayBasePathMapping_basic (66.44s)
--- PASS: TestAccAPIGatewayBasePathMapping_private (17.31s)
```

### CODE REVIEW

**Review by ewbankkit — APPROVED** [review]
LGTM :rocket:.

```console
% make testacc TESTARGS='-run=TestAccAPIGatewayBasePathMapping_' PKG=apigateway ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/apigateway/... -v -count 1 -parallel 3  -run=TestAccAPIGatewayBasePathMapping_ -timeout 360m
2024/12/05 11:28:23 Initializing Terraform AWS Provider...
=== RUN   TestAccAPIGatewayBasePathMapping_basic
=== PAUSE TestAccAPIGatewayBasePathMapping_basic
=== RUN   TestAccAPIGatewayBasePathMapping_private
=== PAUSE TestAccAPIGatewayBasePathMapping_private
=== RUN   TestAccAPIGatewayBasePathMapping_BasePath_empty
=== PAUSE TestAccAPIGatewayBasePathMapping_BasePath_empty
=== RUN   TestAccAPIGatewayBasePathMapping_updates
=== PAUSE TestAccAPIGatewayBasePathMapping_updates
=== RUN   TestAccAPIGatewayBasePathMapping_disappears
=== PAUSE TestAccAPIGatewayBasePathMapping_disappears
=== RUN   TestAccAPIGatewayBasePathMapping_updateIDFormat
=== PAUSE TestAccAPIGatewayBasePathMapping_updateIDFormat
=== CONT  TestAccAPIGatewayBasePathMapping_basic
=== CONT  TestAccAPIGatewayBasePathMapping_updates
=== CONT  TestAccAPIGatewayBasePathMapping_updateIDFormat
--- PASS: TestAccAPIGatewayBasePathMapping_basic (48.67s)
=== CONT  TestAccAPIGatewayBasePathMapping_disappears
--- PASS: TestAccAPIGatewayBasePathMapping_disappears (38.01s)
=== CONT  TestAccAPIGatewayBasePathMapping_BasePath_empty
--- PASS: TestAccAPIGatewayBasePathMapping_updateIDFormat (103.02s)
=== CONT  TestAccAPIGatewayBasePathMapping_private
--- PASS: TestAccAPIGatewayBasePathMapping_private (39.99s)
--- PASS: TestAccAPIGatewayBasePathMapping_BasePath_empty (68.40s)
--- PASS: TestAccAPIGatewayBasePathMapping_updates (291.71s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	297.465s
```

**Review by gdavison — COMMENTED** [review]
A few comments. Non-blocking except for the documentation, if needed

**Comment by ewbankkit** [comment]
After `aws_api_gateway_domain_name` resource ID separator change:

```console
% make testacc TESTARGS='-run=TestAccAPIGatewayDomainName_\|TestAccAPIGatewayDomainNameDataSource_' PKG=apigateway ACCTEST_PARALLELISM=3
make: Verifying source code with gofmt...
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go1.23.3 test ./internal/service/apigateway/... -v -count 1 -parallel 3  -run=TestAccAPIGatewayDomainName_\|TestAccAPIGatewayDomainNameDataSource_ -timeout 360m
2024/12/05 12:51:19 Initializing Terraform AWS Provider...
=== RUN   TestAccAPIGatewayDomainNameDataSource_tags
=== PAUSE TestAccAPIGatewayDomainNameDataSource_tags
=== RUN   TestAccAPIGatewayDomainNameDataSource_tags_NullMap
=== PAUSE TestAccAPIGatewayDomainNameDataSource_tags_NullMap
=== RUN   TestAccAPIGatewayDomainNameDataSource_tags_EmptyMap
=== PAUSE TestAccAPIGatewayDomainNameDataSource_tags_EmptyMap
=== RUN   TestAccAPIGatewayDomainNameDataSource_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccAPIGatewayDomainNameDataSource_tags_DefaultTags_nonOverlapping
=== RUN   TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_DefaultTag
=== PAUSE TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_DefaultTag
=== RUN   TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_ResourceTag
=== RUN   TestAccAPIGatewayDomainNameDataSource_basic
=== PAUSE TestAccAPIGatewayDomainNameDataSource_basic
=== RUN   TestAccAPIGatewayDomainName_tags
=== PAUSE TestAccAPIGatewayDomainName_tags
=== RUN   TestAccAPIGatewayDomainName_tags_null
=== PAUSE TestAccAPIGatewayDomainName_tags_null
=== RUN   TestAccAPIGatewayDomainName_tags_EmptyMap
=== PAUSE TestAccAPIGatewayDomainName_tags_EmptyMap
=== RUN   TestAccAPIGatewayDomainName_tags_AddOnUpdate
=== PAUSE TestAccAPIGatewayDomainName_tags_AddOnUpdate
=== RUN   TestAccAPIGatewayDomainName_tags_EmptyTag_OnCreate
=== PAUSE TestAccAPIGatewayDomainName_tags_EmptyTag_OnCreate
=== RUN   TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Add
=== PAUSE TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Add
=== RUN   TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Replace
=== PAUSE TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Replace
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_providerOnly
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_providerOnly
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_nonOverlapping
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_nonOverlapping
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_overlapping
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_overlapping
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_updateToProviderOnly
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_updateToProviderOnly
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_updateToResourceOnly
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_updateToResourceOnly
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_emptyResourceTag
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_emptyResourceTag
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_emptyProviderOnlyTag
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_emptyProviderOnlyTag
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_nullOverlappingResourceTag
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_nullOverlappingResourceTag
=== RUN   TestAccAPIGatewayDomainName_tags_DefaultTags_nullNonOverlappingResourceTag
=== PAUSE TestAccAPIGatewayDomainName_tags_DefaultTags_nullNonOverlappingResourceTag
=== RUN   TestAccAPIGatewayDomainName_tags_ComputedTag_OnCreate
=== PAUSE TestAccAPIGatewayDomainName_tags_ComputedTag_OnCreate
=== RUN   TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Add
=== PAUSE TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Add
=== RUN   TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Replace
=== PAUSE TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Replace
=== RUN   TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_DefaultTag
=== PAUSE TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_DefaultTag
=== RUN   TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_ResourceTag
=== PAUSE TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_ResourceTag
=== RUN   TestAccAPIGatewayDomainName_certificateARN
    domain_name_test.go:29: Environment variable ACM_CERTIFICATE_ROOT_DOMAIN is not set. For DNS validation requests, this domain must be publicly accessible and configurable via Route53 during the testing. For email validation requests, you must have access to one of the five standard email addresses used (admin|administrator|hostmaster|postmaster|webmaster)@domain or one of the WHOIS contact addresses.
--- SKIP: TestAccAPIGatewayDomainName_certificateARN (0.00s)
=== RUN   TestAccAPIGatewayDomainName_certificateName
    domain_name_test.go:65: Environment variable AWS_API_GATEWAY_DOMAIN_NAME_CERTIFICATE_BODY is not set. This environment variable must be set to any non-empty value with a publicly trusted certificate body to enable the test.
--- SKIP: TestAccAPIGatewayDomainName_certificateName (0.00s)
=== RUN   TestAccAPIGatewayDomainName_regionalCertificateARN
=== PAUSE TestAccAPIGatewayDomainName_regionalCertificateARN
=== RUN   TestAccAPIGatewayDomainName_regionalCertificateName
    domain_name_test.go:162: Environment variable AWS_API_GATEWAY_DOMAIN_NAME_REGIONAL_CERTIFICATE_NAME_ENABLED is not set. This environment variable must be set to any non-empty value in a region where uploading REGIONAL certificates is allowed to enable the test.
--- SKIP: TestAccAPIGatewayDomainName_regionalCertificateName (0.00s)
=== RUN   TestAccAPIGatewayDomainName_securityPolicy
=== PAUSE TestAccAPIGatewayDomainName_securityPolicy
=== RUN   TestAccAPIGatewayDomainName_private
=== PAUSE TestAccAPIGatewayDomainName_private
=== RUN   TestAccAPIGatewayDomainName_privatePolicy
=== PAUSE TestAccAPIGatewayDomainName_privatePolicy
=== RUN   TestAccAPIGatewayDomainName_disappears
=== PAUSE TestAccAPIGatewayDomainName_disappears
=== RUN   TestAccAPIGatewayDomainName_MutualTLSAuthentication_basic
    domain_name_test.go:322: Environment variable ACM_CERTIFICATE_ROOT_DOMAIN is not set. For DNS validation requests, this domain must be publicly accessible and configurable via Route53 during the testing. For email validation requests, you must have access to one of the five standard email addresses used (admin|administrator|hostmaster|postmaster|webmaster)@domain or one of the WHOIS contact addresses.
--- SKIP: TestAccAPIGatewayDomainName_MutualTLSAuthentication_basic (0.00s)
=== RUN   TestAccAPIGatewayDomainName_MutualTLSAuthentication_ownership
    domain_name_test.go:378: Environment variable ACM_CERTIFICATE_ROOT_DOMAIN is not set. For DNS validation requests, this domain must be publicly accessible and configurable via Route53 during the testing. For email validation requests, you must have access to one of the five standard email addresses used (admin|administrator|hostmaster|postmaster|webmaster)@domain or one of the WHOIS contact addresses.
--- SKIP: TestAccAPIGatewayDomainName_MutualTLSAuthentication_ownership (0.00s)
=== RUN   TestAccAPIGatewayDomainName_updateIDFormat
=== PAUSE TestAccAPIGatewayDomainName_updateIDFormat
=== CONT  TestAccAPIGatewayDomainNameDataSource_tags
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_updateToProviderOnly
=== CONT  TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccAPIGatewayDomainNameDataSource_tags (20.50s)
=== CONT  TestAccAPIGatewayDomainName_updateIDFormat
--- PASS: TestAccAPIGatewayDomainName_updateIDFormat (81.88s)
=== CONT  TestAccAPIGatewayDomainName_disappears
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_updateToProviderOnly (163.31s)
=== CONT  TestAccAPIGatewayDomainName_privatePolicy
--- PASS: TestAccAPIGatewayDomainName_privatePolicy (14.20s)
=== CONT  TestAccAPIGatewayDomainName_private
--- PASS: TestAccAPIGatewayDomainName_private (26.43s)
=== CONT  TestAccAPIGatewayDomainName_securityPolicy
--- PASS: TestAccAPIGatewayDomainName_securityPolicy (20.27s)
=== CONT  TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_ResourceTag (80.55s)
=== CONT  TestAccAPIGatewayDomainName_tags_EmptyMap
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyMap (69.43s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_overlapping
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_overlapping (80.62s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_nonOverlapping
--- PASS: TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_DefaultTag (471.95s)
=== CONT  TestAccAPIGatewayDomainName_regionalCertificateARN
--- PASS: TestAccAPIGatewayDomainName_regionalCertificateARN (27.81s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_providerOnly
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_nonOverlapping (104.05s)
=== CONT  TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Add
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_providerOnly (94.89s)
=== CONT  TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Replace
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Add (66.04s)
=== CONT  TestAccAPIGatewayDomainName_tags_EmptyTag_OnCreate
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Replace (64.99s)
=== CONT  TestAccAPIGatewayDomainName_tags_AddOnUpdate
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyTag_OnCreate (66.96s)
=== CONT  TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_ResourceTag
--- PASS: TestAccAPIGatewayDomainName_tags_AddOnUpdate (64.60s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_nullNonOverlappingResourceTag
--- PASS: TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_ResourceTag (64.76s)
=== CONT  TestAccAPIGatewayDomainName_tags_null
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_nullNonOverlappingResourceTag (67.00s)
=== CONT  TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Replace
--- PASS: TestAccAPIGatewayDomainName_tags_null (48.67s)
=== CONT  TestAccAPIGatewayDomainName_tags
--- PASS: TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Replace (57.94s)
=== CONT  TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Add
--- PASS: TestAccAPIGatewayDomainName_tags (92.88s)
=== CONT  TestAccAPIGatewayDomainNameDataSource_basic
--- PASS: TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Add (62.46s)
=== CONT  TestAccAPIGatewayDomainName_tags_ComputedTag_OnCreate
--- PASS: TestAccAPIGatewayDomainNameDataSource_basic (18.52s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_emptyProviderOnlyTag
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_emptyProviderOnlyTag (68.19s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_nullOverlappingResourceTag
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_nullOverlappingResourceTag (40.74s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_updateToResourceOnly
--- PASS: TestAccAPIGatewayDomainName_tags_ComputedTag_OnCreate (116.46s)
=== CONT  TestAccAPIGatewayDomainNameDataSource_tags_DefaultTags_nonOverlapping
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_updateToResourceOnly (64.89s)
=== CONT  TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_DefaultTag
--- PASS: TestAccAPIGatewayDomainNameDataSource_tags_DefaultTags_nonOverlapping (83.90s)
=== CONT  TestAccAPIGatewayDomainNameDataSource_tags_EmptyMap
--- PASS: TestAccAPIGatewayDomainNameDataSource_tags_IgnoreTags_Overlap_DefaultTag (65.67s)
=== CONT  TestAccAPIGatewayDomainNameDataSource_tags_NullMap
--- PASS: TestAccAPIGatewayDomainNameDataSource_tags_EmptyMap (64.31s)
=== CONT  TestAccAPIGatewayDomainName_tags_DefaultTags_emptyResourceTag
--- PASS: TestAccAPIGatewayDomainNameDataSource_tags_NullMap (40.45s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_emptyResourceTag (81.83s)
--- PASS: TestAccAPIGatewayDomainName_disappears (1352.35s)
PASS
ok  	github.com/hashicorp/terraform-provider-aws/internal/service/apigateway	1462.858s
```

**Review by gdavison — APPROVED** [review]
Looks good! 🚀 

--- PASS: TestAccAPIGatewayDomainName_disappears (56.33s)
--- PASS: TestAccAPIGatewayBasePathMapping_updateIDFormat (68.50s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_overlapping (189.32s)
--- PASS: TestAccAPIGatewayDomainName_securityPolicy (191.63s)
--- PASS: TestAccAPIGatewayDomainName_tags_AddOnUpdate (221.87s)
--- PASS: TestAccAPIGatewayDomainName_private (224.63s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_emptyProviderOnlyTag (258.12s)
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyMap (192.07s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_providerOnly (346.44s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_updateToResourceOnly (369.02s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_updateToProviderOnly (84.24s)
--- PASS: TestAccAPIGatewayBasePathMapping_disappears (112.15s)
--- PASS: TestAccAPIGatewayBasePathMapping_basic (466.01s)
--- PASS: TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Add (502.66s)
--- PASS: TestAccAPIGatewayBasePathMapping_private (66.91s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_nonOverlapping (85.67s)
--- PASS: TestAccAPIGatewayBasePathMapping_BasePath_empty (146.17s)
--- PASS: TestAccAPIGatewayDomainName_privatePolicy (627.22s)
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyTag_OnCreate (414.54s)
--- PASS: TestAccAPIGatewayDomainName_regionalCertificateARN (679.94s)
--- PASS: TestAccAPIGatewayDomainName_updateIDFormat (730.03s)
--- PASS: TestAccAPIGatewayBasePathMapping_updates (467.35s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_nullNonOverlappingResourceTag (812.23s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_nullOverlappingResourceTag (920.52s)
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Add (738.33s)
--- PASS: TestAccAPIGatewayDomainName_tags_ComputedTag_OnUpdate_Replace (994.60s)
--- PASS: TestAccAPIGatewayDomainName_tags_DefaultTags_emptyResourceTag (1003.45s)
--- PASS: TestAccAPIGatewayDomainName_tags_null (832.54s)
--- PASS: TestAccAPIGatewayDomainName_tags_ComputedTag_OnCreate (1080.45s)
--- PASS: TestAccAPIGatewayDomainName_tags_EmptyTag_OnUpdate_Replace (880.87s)
--- PASS: TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_DefaultTag (1190.39s)
--- PASS: TestAccAPIGatewayDomainName_tags_IgnoreTags_Overlap_ResourceTag (1234.82s)
--- PASS: TestAccAPIGatewayDomainName_tags (1169.21s)

**Comment by ewbankkit** [comment]
@DrFaust92 Thanks for the contribution :tada: :clap:.

**Pull request merged**
