### PR TITLE
Enhancement add Elasticache (Redis) LogDeliveryConfigurations issue #20068

### LINKED ISSUE #20068: LogDeliveryConfiguration for Elasticache replication group
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for slowlog capturing into CloudWatch Logs(/Firehose) for Elasticache replication group -> LogDeliveryConfigurations

### New or Affected Resource(s)

* aws_elasticache_replication_group

### Potential Terraform Configuration

```hcl
# example for cloudwatch logs
resource "aws_elasticache_replication_group" "this" {
  replication_group_description = "elasticache-replication-group with logging"
  replication_group_id =  "elasticache-replication-group"
  log_delivery_configurations {
    log_type = "slow-log"
    destination_type = "cloudwatch-logs"
    log_format = "json"
    destination_details {
      cloudwatch_logs_details {
        log_group = var.log_group_arn
      }
    }
  }
}
```

### References

* https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-properties-elasticache-replicationgroup-logdeliveryconfigurationrequest.html

### PR DESCRIPTION
**Pull request by nickyamanaka**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

This is a somewhat long PR (each commit is isolated tho), but the majority of the logic is within `elasticache_logdeliveryconfigurations.go`
`aws_elasticache_cluster`, `aws_elasticache_replication_group` resources along their `data` counterparts are using the same implementation, so it seemed reasonable for me to create a file to encapsulate these changes, let me know if there's a better location or approach for this.

+14 tests, covers enable/disable and updates in different scenarios.

Website, examples and docs added as-well.

Relates OR Closes #20068

Output from acceptance testing:

```
make testacc TESTARGS="-run=TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_" && \
make testacc TESTARGS="-run=TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_" && \
make testacc TESTARGS="-run=TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_" && \
make testacc TESTARGS="-run=TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_" && \
make testacc TESTARGS="-run=TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_"

==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_ -timeout 180m
=== RUN   TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch
=== PAUSE TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch
=== RUN   TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose
=== PAUSE TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose
=== CONT  TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch
=== CONT  TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose
--- PASS: TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch (632.17s)
--- PASS: TestAccAWSDataElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose (729.28s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       729.370s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ -timeout 180m
=== RUN   TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_CloudWatch
=== PAUSE TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_CloudWatch
=== RUN   TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose
=== PAUSE TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose
=== CONT  TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_CloudWatch
=== CONT  TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose
--- PASS: TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_CloudWatch (669.38s)
--- PASS: TestAccDataSourceAwsElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose (683.01s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       683.109s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_ -timeout 180m
=== RUN   TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== PAUSE TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== RUN   TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable
=== PAUSE TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable
=== RUN   TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== PAUSE TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== CONT  TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== CONT  TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== CONT  TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable
--- PASS: TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable (782.05s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable (926.78s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update (927.20s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       927.296s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_ -timeout 180m
=== RUN   TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== PAUSE TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== RUN   TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_EnableDisable
=== PAUSE TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_EnableDisable
=== RUN   TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== PAUSE TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== CONT  TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== CONT  TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== CONT  TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_EnableDisable
--- PASS: TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_EnableDisable (789.85s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_KinesisFirehose_EnableDisable (854.05s)
--- PASS: TestAccAWSElasticacheReplicationGroup_Engine_Redis_ClusterMode_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update (1007.64s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       1007.739s
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test ./aws -v -count 1 -parallel 20 -run=TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_ -timeout 180m
=== RUN   TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== PAUSE TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== RUN   TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable
=== PAUSE TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable
=== RUN   TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== PAUSE TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== CONT  TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update
=== CONT  TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable
=== CONT  TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable
--- PASS: TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_EnableDisable (755.09s)
--- PASS: TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_KinesisFirehose_EnableDisable (894.02s)
--- PASS: TestAccAWSElasticacheCluster_Engine_Redis_LogDeliveryConfigurations_Cloudwatch_KinesisFirehose_Update (900.19s)
PASS
ok      github.com/terraform-providers/terraform-provider-aws/aws       900.317s

...
```

### CODE REVIEW

**Comment by zhelding** [comment]
Pull request #21306 has significantly refactored the AWS Provider codebase. As a result, most PRs opened prior to the refactor now have merge conflicts that must be resolved before proceeding.

Specifically, PR #21306 relocated the code for all AWS resources and data sources from a single `aws` directory to a large number of separate directories in `internal/service`, each corresponding to a particular AWS service. This separation of code has also allowed for us to simplify the names of underlying functions -- while still avoiding namespace collisions.

We recognize that many pull requests have been open for some time without yet being addressed by our maintainers. Therefore, we want to make it clear that resolving these conflicts _in no way affects the prioritization_ of a particular pull request. Once a pull request has been prioritized for review, the necessary changes will be made by a maintainer -- either directly or in collaboration with the pull request author.

For a more complete description of this refactor, including examples of how old filepaths and function names correspond to their new counterparts: please refer to issue #20000.

For a quick guide on how to amend your pull request to resolve the merge conflicts resulting from this refactor and bring it in line with our new code patterns: please refer to our [Service Package Refactor Pull Request Guide](https://github.com/hashicorp/terraform-provider-aws/blob/main/docs/contributing/service-package-pullrequest-guide.md).

**Comment by JustAnotherSoftwareDeveloper** [comment]
@nickyamanaka Is this PR dead or has there been progress behind the scenes?

**Comment by nickyamanaka** [comment]
> @nickyamanaka Is this PR dead or has there been progress behind the scenes?

Will fix the conflicting files asap or close the PR if it’s not needed anymore.

**Comment by nickyamanaka** [comment]
New PR https://github.com/hashicorp/terraform-provider-aws/pull/22183

**Pull request closed without merging**
