### PR TITLE
Adds available_ip_address_count to data_source_aws_subnet.

### PR DESCRIPTION
**Pull request by wuxort**
### Community Note

* Please vote on this pull request by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original pull request comment to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for pull request followers and do not help prioritize the request

Release note for [CHANGELOG](https://github.com/terraform-providers/terraform-provider-aws/blob/master/CHANGELOG.md):

```release-note
Adds available_ip_address_count to data_source_aws_subnet.
```

Output from acceptance testing:

```
ok  	github.com/terraform-providers/terraform-provider-aws/aws	19.767s
```
Local tests passed, but I would like to request a proper acceptance test on AWS.

### CODE REVIEW

**Comment by nirmalparekh1984** [comment]
Which version is this feature going to be available?

**Comment by jaekunchoi** [comment]
I also need this. Is this going to be merged soon?

**Comment by connor-tyndall** [comment]
Yes, I am in need of this as well!

**Review by YakDriver — APPROVED** [review]
Looks great!

Acceptance tests on GovCloud:
```
--- PASS: TestAccDataSourceAwsSubnet_basic (27.88s)
--- PASS: TestAccDataSourceAwsSubnet_ipv6ByIpv6CidrBlock (49.43s)
--- PASS: TestAccDataSourceAwsSubnet_ipv6ByIpv6Filter (49.94s)
```

`us-west-2`:
```
--- PASS: TestAccDataSourceAwsSubnet_basic (24.24s)
--- PASS: TestAccDataSourceAwsSubnet_ipv6ByIpv6CidrBlock (43.54s)
--- PASS: TestAccDataSourceAwsSubnet_ipv6ByIpv6Filter (44.32s)
```

**Pull request merged**
